### PR TITLE
Convert worker_transactions to new connection API

### LINKED ISSUE #1023: All 2PC transactions should support automated recovery.
Right now, when 2PC is being used for DDL, failures are not being handled well.  If the main transaction fails badly, or a connection dies, we end up with leaked prepared transactions. That's bad because they still hold locks and such, and because they are a scarce resource.

That's going to get even worse once reference tables use 2PC (#966), due to the increased frequency of 2PC usage.

### LINKED ISSUE #1043: master_add_node errors out when a node is down (>6.0)
#996 introduced an issue where `master_add_node` might fail if a worker is down, while the expectation is that this would only happen if hasmetadata set to true for that worker. This is because the worker_transactions framework currently connects to all workers when invoked, even if only sending to `WORKERS_WITH_METADATA`.

### PR DESCRIPTION
**Pull request by marcocitus**
Fixes #1043 
Fixes #1023

### CODE REVIEW

File: src/backend/distributed/transaction/remote_transaction.c [hunk 1]
```diff
@@ -388,6 +392,13 @@ StartRemoteTransactionPrepare(struct MultiConnection *connection)
 
 	Assign2PCIdentifier(connection);
 
+	/* log transactions to workers in pg_dist_transaction */
```
Comment (anarazel) [inline src/backend/distributed/transaction/remote_transaction.c]: Shouldn't we build that association once, instead of doing it over and over?

File: src/backend/distributed/connection/remote_commands.c [hunk 2]
```diff
@@ -187,6 +187,35 @@ LogRemoteCommand(MultiConnection *connection, const char *command)
 
 /* wrappers around libpq functions, with command logging support */
 
+
+/*
+ * ExecuteCriticalRemoteCommand executes a remote command that is critical
+ * to the transaction. If the command fails then the transaction aborts.
+ */
```
Comment (anarazel) [inline src/backend/distributed/connection/remote_commands.c]: Hm - nothing in the content of this really seems to be related to "Critical"? Or is that just meant to refer to the ERROR level?

File: src/backend/distributed/connection/remote_commands.c [hunk 3]
```diff
@@ -187,6 +187,35 @@ LogRemoteCommand(MultiConnection *connection, const char *command)
...
+ExecuteCriticalRemoteCommand(MultiConnection *connection, const char *command)
+{
+	int querySent = 0;
+	PGresult *result = NULL;
+	bool raiseInterrupts = true;
+
+	querySent = SendRemoteCommand(connection, command);
+	if (querySent == 0)
+	{
+		ReportConnectionError(connection, WARNING);
```
Comment (anarazel) [inline src/backend/distributed/connection/remote_commands.c]: Shouldn't this be ERROR?

File: src/backend/distributed/transaction/remote_transaction.c [hunk 4]
```diff
@@ -388,6 +392,13 @@ StartRemoteTransactionPrepare(struct MultiConnection *connection)
...
+	workerNode = FindWorkerNode(connection->hostname, connection->port);
+	if (workerNode != NULL)
+	{
+		LogTransactionRecord(workerNode->groupId, transaction->preparedName);
```
Comment (anarazel) [inline src/backend/distributed/transaction/remote_transaction.c]: I think it's great that we use this more generally now, but I do think we should have some tests for recovery for !MX stuff.

File: src/backend/distributed/transaction/worker_transaction.c [hunk 5]
```diff
@@ -122,437 +82,113 @@ SendCommandToWorkersParams(TargetWorkerSet targetWorkerSet, char *command,
...
-	{
-		/* nothing to do */
-		return;
-	}
-	else if (event == XACT_EVENT_PRE_COMMIT)
-	{
-		if (MultiShardCommitProtocol == COMMIT_PROTOCOL_2PC)
+		int querySent = PQsendQueryParams(connection->pgConn, command, parameterCount,
+										  parameterTypes, parameterValues, NULL, NULL, 0);
+		if (querySent == 0)
```
Comment (anarazel) [inline src/backend/distributed/transaction/worker_transaction.c]: Doesn't have to be now, but we really should have a wrapper for PQsendQueryParams too, marking the connection as nonblocking before sending the command. Otherwise we can stall here too :(

File: src/backend/distributed/transaction/worker_transaction.c [hunk 6]
```diff
@@ -122,437 +82,113 @@ SendCommandToWorkersParams(TargetWorkerSet targetWorkerSet, char *command,
...
-		transactionConnection->nodePort = nodePort;
-
-		connectionList = lappend(connectionList, transactionConnection);
+		ForgetResults(connection);
 	}
-
-	MemoryContextSwitchTo(oldContext);
-
-	return connectionList;
 }
```
Comment (anarazel) [inline src/backend/distributed/transaction/worker_transaction.c]: Wow, github's diff view is nearly useless for this :(

File: src/backend/distributed/connection/remote_commands.c (hunk 3 above)
Comment (marcocitus) [inline src/backend/distributed/connection/remote_commands.c]: Oops, yes.

File: src/backend/distributed/transaction/remote_transaction.c (hunk 4 above)
Comment (marcocitus) [inline src/backend/distributed/transaction/remote_transaction.c]: Agreed, that was the [WIP] :), also will do some more failure testing.

File: src/backend/distributed/transaction/remote_transaction.c (hunk 1 above)
Comment (marcocitus) [inline src/backend/distributed/transaction/remote_transaction.c]: The current recovery logic expects every remote prepared transaction to be logged separately. We could have one record per (worker, coordinated transaction) pair, but that requires a more sophisticated implementation that matches the remote prepared transactions to a coordinated transaction ID. For metadata syncing and reference tables, such and implementation wouldn't make a difference and multi-shard commands are sufficiently rare to not worry about them. I am a bit worried about frequent COPY commands generating a ton of records, although calling recover_prepared_transactions() once a day is probably sufficient to deal with several COPY commands per second. We could also consider regressing a bit on transaction recovery here until we have an implementation that uses a more compact representation.

Comment (anarazel) [inline src/backend/distributed/transaction/remote_transaction.c]: > The current recovery logic expects every remote prepared transaction to be logged separately.

I was really just commenting on the FindWorkerNode() - we could quite easily store that in the connection.

> I am a bit worried about frequent COPY commands generating a ton of records,

Yea, me too.  We probably should suggest calling the cleanup at a quite regular basis.

> We could also consider regressing a bit on transaction recovery here until we have an implementation that uses a more compact representation.

Not sure what you mean by that?

Comment (marcocitus) [inline src/backend/distributed/transaction/remote_transaction.c]: Misunderstood the comment. I looked into moving FindWorkerNode to StartConnectionEstablishment where the MultiConnection is initialised, but that code path is called from a few different contexts such as the task tracker background worker which made that a bit impractical. For now I'll stick to the current approach, which usually only involves a hash look-up.

File: src/backend/distributed/transaction/worker_transaction.c (hunk 5 above)
Comment (marcocitus) [inline src/backend/distributed/transaction/worker_transaction.c]: Agreed, added it.

File: src/backend/distributed/connection/remote_commands.c (hunk 2 above)
Comment (marcocitus) [inline src/backend/distributed/connection/remote_commands.c]: Yes, critical as in: the transaction fails if the command fails, as opposed to "regular" ExecuteRemoteCommand, which just returns false.

Comment (anarazel) [inline src/backend/distributed/connection/remote_commands.c]: Not particularly happy about the name, but I can't think of something a lot better.

File: src/backend/distributed/connection/remote_commands.c [hunk 7]
```diff
@@ -221,6 +253,19 @@ SendRemoteCommand(MultiConnection *connection, const char *command)
...
+ * SendRemoteCommand is a PQsendQuery wrapper that logs remote commands, and
+ * accepts a MultiConnection instead of a plain PGconn.  It makes sure it can
+ * send commands asynchronously without blocking (at the potential expense of
+ * an additional memory allocation).
+ */
+int
+SendRemoteCommand(MultiConnection *connection, const char *command)
+{
+	return SendRemoteCommandParams(connection, command, 0, NULL, NULL);
+}
```
Comment (anarazel) [inline src/backend/distributed/connection/remote_commands.c]: cool.

File: src/test/regress/sql/multi_transaction_recovery.sql [hunk 8]
```diff
@@ -35,3 +35,36 @@ SELECT count(*) FROM pg_dist_transaction;
...
+SELECT recover_prepared_transactions();
+SELECT count(*) FROM pg_dist_transaction;
+
+-- INSERT..SELECT should write 4 transaction recovery records
+INSERT INTO test_recovery SELECT x, 'earth' FROM test_recovery;
+
+SELECT count(*) FROM pg_dist_transaction;
+SELECT recover_prepared_transactions();
+SELECT count(*) FROM pg_dist_transaction;
+
```
Comment (anarazel) [inline src/test/regress/sql/multi_transaction_recovery.sql]: Tests for aborted transactions wouldn't hurt.
