### PR TITLE
Fix an undefined behavior for bit shift in citus_stat_tenants.c

### LINKED ISSUE #7953: Undefined behavior for bit shift in citus_stat_tenants.c
We have bit shift operation without control of shift length in citus_stat_tenants.c.
Shift operators where the amount shifted is greater or equal to the promoted bit-width of the left hand side or less than zero, or where the left hand side is negative, can lead to undefined bahavior.

https://github.com/citusdata/citus/blob/0e6127c4f60b26da18ac8df48d2b6a8de5ed9d4c/src/backend/distributed/utils/citus_stat_tenants.c#L608

```
	/*
	 * If the last score reduction was not in this period we do score reduction now.
	 */
	if (periodCountAfterLastScoreReduction > 0)
	{
		tenantStats->score >>= periodCountAfterLastScoreReduction;
		tenantStats->lastScoreReduction = queryTime;
	}
```

I caught this problem with sanitizer. It seems on start

`	stats->lastScoreReduction = 0;`

and it lead to bitwise shifts that are out of bounds for their data type

Also, it seems, better to backport it at least at release-13.0 and release-12.1

### PR DESCRIPTION
**Pull request by manaldush**
DESCRIPTION: Fixes an undefined behavior that could happen when computing tenant score for citus_stat_tenants

Add check for shift size, reset to zero in case of overflow

Fixes #7953.

### CODE REVIEW

File: src/backend/distributed/utils/citus_stat_tenants.c [hunk 1]
```diff
@@ -48,6 +48,9 @@ ExecutorEnd_hook_type prev_ExecutorEnd = NULL;
 #define ATTRIBUTE_STRING_FORMAT_WITHOUT_TID "/*{\"cId\":%d}*/"
 #define STAT_TENANTS_COLUMNS 9
 #define ONE_QUERY_SCORE 1000000000
+#define BYTE_TO_BIT 3               /* 2^3 bits/byte */
+#define TENANTS_STATS_FIELD_BIT_LENGTH(tenantStats, field) (sizeof((tenantStats)->field) \
+															<< BYTE_TO_BIT)
```
Comment (onurctirtir) [inline src/backend/distributed/utils/citus_stat_tenants.c]:
```suggestion
/* this doesn't attempt dereferencing given input and is computed in compile-time, so it's safe */
#define TENANTS_STATS_SCORE_FIELD_BIT_LENGTH (sizeof(((TenantStats*) NULL)->score) * 8)
```

File: src/backend/distributed/utils/citus_stat_tenants.c [hunk 2]
```diff
@@ -605,8 +608,13 @@ ReduceScoreIfNecessary(TenantStats *tenantStats, TimestampTz queryTime)
...
 	if (periodCountAfterLastScoreReduction > 0)
 	{
-		tenantStats->score >>= periodCountAfterLastScoreReduction;
 		tenantStats->lastScoreReduction = queryTime;
+
+		/*addtional check to avoid undefined behavior */
+		tenantStats->score = (periodCountAfterLastScoreReduction <
+							  TENANTS_STATS_FIELD_BIT_LENGTH(tenantStats, score))
+			? tenantStats->score >> periodCountAfterLastScoreReduction
+			: 0;
```
Comment (onurctirtir) [inline src/backend/distributed/utils/citus_stat_tenants.c]:
```suggestion
		/* addtional check to avoid undefined behavior */
		tenantStats->score = (periodCountAfterLastScoreReduction <
							  TENANTS_STATS_SCORE_FIELD_BIT_LENGTH)
			? tenantStats->score >> periodCountAfterLastScoreReduction
			: 0;
```

**Comment by onurctirtir** [comment]
Thanks for the contribution!

File: src/backend/distributed/stats/stat_tenants.c [hunk 3]
```diff
@@ -49,6 +49,9 @@ ExecutorEnd_hook_type prev_ExecutorEnd = NULL;
 #define STAT_TENANTS_COLUMNS 9
 #define ONE_QUERY_SCORE 1000000000
 
+/* this doesn't attempt dereferencing given input and is computed in compile-time, so it's safe */
+#define TENANTS_STATS_SCORE_FIELD_BIT_LENGTH (sizeof(((TenantStats *) NULL)->score) * 8)
```
Comment (onurctirtir) [inline src/backend/distributed/stats/stat_tenants.c]:
```suggestion
#define TENANT_STATS_SCORE_FIELD_BIT_LENGTH (sizeof(((TenantStats *) NULL)->score) * 8)
```

File: src/backend/distributed/stats/stat_tenants.c [hunk 4]
```diff
@@ -605,8 +608,13 @@ ReduceScoreIfNecessary(TenantStats *tenantStats, TimestampTz queryTime)
 	 */
 	if (periodCountAfterLastScoreReduction > 0)
 	{
-		tenantStats->score >>= periodCountAfterLastScoreReduction;
 		tenantStats->lastScoreReduction = queryTime;
+
+		/* addtional check to avoid undefined behavior */
+		tenantStats->score = (periodCountAfterLastScoreReduction <
+							  TENANTS_STATS_SCORE_FIELD_BIT_LENGTH)
```
Comment (onurctirtir) [inline src/backend/distributed/stats/stat_tenants.c]:
```suggestion
							  TENANT_STATS_SCORE_FIELD_BIT_LENGTH)
```
