### PR TITLE
Fixes the ALTER TABLE IF EXISTS SET SCHEMA bug

### LINKED ISSUE #4056: ALTER TABLE IF EXISTS SET SCHEMA on a Non-existing Table
```
ALTER TABLE IF EXISTS nonexistsingtable SET SCHEMA public;
```
gives
```
NOTICE:  relation "nonexistsingtable" does not exist, skipping
ERROR:  relation "nonexistsingtable" does not exist
```
There should be only the notice, not the error.

### PR DESCRIPTION
**Pull request by halilozanakgul**
DESCRIPTION: Fixes the bug ALTER TABLE IF EXISTS SET SCHEMA with non existing table bug.

Fixes #4056

### CODE REVIEW

File: src/test/regress/sql/multi_schema_support.sql [hunk 1]
```diff
@@ -842,6 +842,16 @@ ALTER TABLE non_existent_schema.non_existent_table SET SCHEMA another_non_existe
...
+
+
+-- test ALTER TABLE IF EXISTS SET SCHEMA with nonexisting schemas and table
+ALTER TABLE IF EXISTS non_existent_schema.table_set_schema SET SCHEMA another_existing_schema;
+ALTER TABLE IF EXISTS non_existent_schema.non_existent_table SET SCHEMA another_existing_schema;
+ALTER TABLE IF EXISTS non_existent_schema.table_set_schema SET SCHEMA another_non_existent_schema;
+ALTER TABLE IF EXISTS non_existent_schema.non_existent_table SET SCHEMA another_non_existent_schema;
+ALTER TABLE IF EXISTS existing_schema.non_existent_table SET SCHEMA another_existing_schema;
+ALTER TABLE IF EXISTS existing_schema.non_existent_table SET SCHEMA non_existent_schema;
+ALTER TABLE IF EXISTS existing_schema.table_set_schema SET SCHEMA non_existent_schema;
```
Comment (thanodnl) [inline src/test/regress/sql/multi_schema_support.sql:854]: can we have one without a fully qualified table name?
```SQL
ALTER TABLE IF EXISTS non_existing_table SET SCHEMA existing_schema;
ALTER TABLE IF EXISTS non_existing_table SET SCHEMA non_existing_schema;
```

This will also follow the codepath where the schema is not set on the parsetree.
