### PR TITLE
Prevent Deadlocks When a Worker Tries to Create Collation (Fix #5583)

### LINKED ISSUE #5583: Creating Collation on Worker Causes Distributed Deadlock
```
CREATE COLLATION col (locale = 'en_US.utf8');
ERROR:  canceling the transaction since it was involved in a distributed deadlock
```

### PR DESCRIPTION
**Pull request by gledis69**
* When a worker tried to create a collation which had a dependency in the same worker node,
it would cause a deadlock.

### CODE REVIEW

File: src/backend/distributed/commands/collation.c [hunk 1]
```diff
@@ -519,6 +519,27 @@ DefineCollationStmtObjectAddress(Node *node, bool missing_ok)
...
+ * if the created collation is set to propagate and the statement is not
+ * part of a multi statement transaction.
+ */
+List *
+PreprocessDefineCollationStmt(Node *node, const char *queryString,
+							  ProcessUtilityContext processUtilityContext)
+{
+	Assert(castNode(DefineStmt, node)->kind == OBJECT_COLLATION);
+
+	if (ShouldPropagate() && !IsMultiStatementTransaction())
```
Comment (agedemenli) [inline src/backend/distributed/commands/collation.c:534]: couldn't get the reason for that. Could you explain a bit? Or maybe it could be good to have some comments on the code

Comment (gledis69) [reply src/backend/distributed/commands/collation.c:538]: Comment added, but because none of these lines were edited (new lines were added) girhub doesn't consider this portion of the code outdated.

Comment (agedemenli) [reply src/backend/distributed/commands/collation.c:538]: That will not call `EnsureCoordinator` if we are in a tx block. What I couldn't understand is, why do we allow the worker to execute `CREATE COLLATION` for non tx block cases?

Comment (gledis69) [reply src/backend/distributed/commands/collation.c:538]: Well I can answer that by looking at the if statement:
* The worker will only be able to execute if the if statement evaluates to false or `EnsureCoordinator` is triggered and there is an error on a worker.
* For non transaction block cases, `!IsMultiStatementTransaction` is true, so the worker can only execute if `ShouldPropage` is false.

So the worker can only execute outside of a tx block when metadata syncing is off. This can happen when the user turns off metadata syncing manually, or when the CREATE statement is predicated from the Coordinator to the worker.

Comment (agedemenli) [reply src/backend/distributed/commands/collation.c:538]: sorry, my bad, forget my previous comment. The correct one should be:
"What I couldn't understand is, why do we allow the worker to execute CREATE COLLATION for ~non~ tx block cases?"

As far as I see, if there's an ongoing tx block, `CREATE COLLATION` will be executed on the worker?

Comment (gledis69) [reply src/backend/distributed/commands/collation.c]: > "What I couldn't understand is, why do we allow the worker to execute CREATE COLLATION for non tx block cases?"
You are correct. I do not know why, but this behavior is tested for, so it is expected. @onderkalaci might have more insights regarding this.

**Comment by onderkalaci** [comment]
> You are correct. I do not know why, but this behavior is tested for, so it is expected. @onderkalaci might have more insights regarding this.

First, I added another comment on that function, we did some changes and we should reflect it here.

In general, if you propagate an object inside a TX block, then you need to switch to sequential mode as the next commands might depend on the existence of the object. In other words, you need a single transaction on the worker, otherwise, the other transactions cannot access to the new object. 

In order not to switch to sequential mode, we *defer* creating the object on the remote node. We defer until we really need the object (e.g., an index uses a collation we have just created). In that case, we use a separate connection and commit immediately, meaning slightly breaking transactional behavior (e.g., if you rollback, you cannot rollback the object creation).

There are certain discussions to avoid this in the future, but for now that is the expected behavior.

**Comment by onderkalaci** [comment]
> DESCRIPTION: PR description that will go into the change log, up to 78 characters

If the change is interesting for the users, we keep this DESCRIPTION tag so that is shows up in the release notes. I think, this change is not very interesting for users to see on the release notes, so we could remove the DESCRIPTION tag from the PR description.

File: src/backend/distributed/commands/collation.c [hunk 2]
```diff
@@ -519,6 +519,38 @@ DefineCollationStmtObjectAddress(Node *node, bool missing_ok)
...
 
+/*
+ * Do not propage collation define statement if:
+ * - metadata syncing if off
+ * - statement is part of a multi stmt transaction
+ */
+static bool
+ShouldPropagateDefineCollationStmt()
+{
+	return ShouldPropagate() && !IsMultiStatementTransaction();
```
[the remark this answers is not in the document]
Comment (gledis69) [reply src/backend/distributed/commands/collation.c]: Added the same checks and structure.

File: src/backend/distributed/commands/collation.c [hunk 3]
```diff
@@ -519,6 +519,38 @@ DefineCollationStmtObjectAddress(Node *node, bool missing_ok)
 }
 
 
+/*
+ * Do not propage collation define statement if:
+ * - metadata syncing if off
+ * - statement is part of a multi stmt transaction
+ */
+static bool
+ShouldPropagateDefineCollationStmt()
```
[the remark this answers is not in the document]
Comment (gledis69) [reply src/backend/distributed/commands/collation.c]: I moved the definition of `ShouldPropagateDefineCollationStmt` at the very bottom like in the distributed/commands/schema.c example you shared.
Also started the comment with the function name.

**Review by onderkalaci — APPROVED** [review]
Please do not forget to squash the commits before merging.
