### PR TITLE
Fix master_append_table_to_shard to work with schemas

### LINKED ISSUE #78: master_append_table_to_shard() does not work with tables in a schema different from public.
master_append_table_to_shard() does not work with tables in a schema different from public.

### PR DESCRIPTION
**Pull request by byucesoy**
Fixes #78

With this change, it is possible to append a table in any schema to shard. The function
master_append_table_to_shard now supports schema names.

### CODE REVIEW

File: src/backend/distributed/master/master_stage_protocol.c [hunk 1]
```diff
@@ -191,10 +191,14 @@ master_append_table_to_shard(PG_FUNCTION_ARGS)
 	text *sourceTableNameText = PG_GETARG_TEXT_P(1);
 	text *sourceNodeNameText = PG_GETARG_TEXT_P(2);
 	uint32 sourceNodePort = PG_GETARG_UINT32(3);
+
 	char *sourceTableName = text_to_cstring(sourceTableNameText);
 	char *sourceNodeName = text_to_cstring(sourceNodeNameText);
 
-	char *shardName = NULL;
+	Oid shardSchemaOid = 0;
```
Comment (metdos) [inline src/backend/distributed/master/master_stage_protocol.c]: Can we use similar naming to your PR here;
https://github.com/citusdata/citus/pull/588/files

Such as we can keep shardName, schemaId, schemaName, shardQualifiedName etc.

We would like to have consistency over all the codebase unless old naming does not make sense.

File: src/backend/distributed/worker/worker_data_fetch_protocol.c [hunk 2]
```diff
@@ -1031,45 +1033,60 @@ ParseTreeNode(const char *ddlCommand)
...
+	DeconstructQualifiedName(remoteQualifiedNameList,
+							 &remoteSchemaName,
+							 &remoteTableName);
 
 	/*
 	 * We lock on the shardId, but do not unlock. When the function returns, and
 	 * the transaction for this function commits, this lock will automatically
 	 * be released. This ensures appends to a shard happen in a serial manner.
 	 */
+	shardNameString = makeStringInfo();
```
Comment (metdos) [inline src/backend/distributed/worker/worker_data_fetch_protocol.c]: Should it be before the comment block?

**Comment by metdos** [comment]
Could you add regression tests? Probably a new file, something like multi_schema_support.sql

File: src/backend/distributed/worker/worker_data_fetch_protocol.c (hunk 2 above)
Comment (byucesoy) [inline src/backend/distributed/worker/worker_data_fetch_protocol.c]: We create shardNameString only to be able to extract shardId and thus put a lock on shardId. ExtractShardId function only works on StringInfo type. Therefore creating shardNameString is part of locking procedure.

File: src/backend/distributed/master/master_stage_protocol.c (hunk 1 above)
Comment (byucesoy) [inline src/backend/distributed/master/master_stage_protocol.c]: There are 2 different schemas, table names etc. in the context of this function. One is the source table we read the data from and the other one is the target we will write data into. Therefore I prefixed them with; remote(if it is the source we read from) and shard(if it is the target we will write into)

Also I did not used shardName specifically. Because it is not clear whether shardName contains just table name or both schema name and table name. So instead I used names shardSchameName and shardTableName.

On the other hand names like shardQuotedQualifiedName may be excessive and shardQualifiedName could be enough.

File: src/backend/distributed/master/master_stage_protocol.c [hunk 3]
```diff
@@ -11,7 +11,7 @@
  *
  * $Id$
  *
- *-------------------------------------------------------------------------
+ **********-------------------------------------------------------------------------
```
Comment (metdos) [inline src/backend/distributed/master/master_stage_protocol.c]: Could you run citus_indent? It adds a star here.

**Comment by metdos** [comment]
Could you rebase this? I though that we have missed some fix in other PR :)

**Comment by metdos** [comment]
> Could you rebase this? I thought that we have missed some fix in other PR :)

I rebased this for testing purposes.

File: src/backend/distributed/worker/worker_data_fetch_protocol.c [hunk 4]
```diff
@@ -602,6 +602,8 @@ LocalTableSize(Oid relationId)
 		{
 			char *relationName = get_rel_name(relationId);
 			struct stat fileStat;
+
```
Comment (metdos) [inline src/backend/distributed/worker/worker_data_fetch_protocol.c]: Double newlines!

**Comment by metdos** [comment]
I got an error on this test case;

```sql
DROP TABLE "nation._'append";
CREATE TABLE "nation._'append" (
    n_nationkey integer not null,
    n_name char(25) not null,
    n_regionkey integer not null,
    n_comment varchar(152));

SELECT master_create_distributed_table('"nation._''append"', 'n_nationkey', 'append');
SELECT master_create_empty_shard('"nation._''append"');

SELECT master_append_table_to_shard(102060, 'nation_local', 'localhost', 5432);
```

Worker log;
```
LOG:  statement: SELECT worker_append_table_to_shard ('public."nation._''append_102060"', 'nation_local', 'localhost', 5432)
ERROR:  syntax error at or near "append_102060" at character 40
STATEMENT:  SELECT pg_table_size('public."nation._'append_102060"')
```

It seems that we don't set shard name properly in UpdateShardStatistics(). We need to escape single quote in the table name, pg_table_size() call must be like this.

```sql
SELECT pg_table_size('public."nation._''append_102060"');
```

File: src/backend/distributed/master/master_stage_protocol.c (hunk 1 above)
Comment (metdos) [inline src/backend/distributed/master/master_stage_protocol.c]: > There are 2 different schemas, table names etc. in the context of this function. One is the source table we read the data from and the other one is the target we will write data into. Therefore I prefixed them with; remote(if it is the source we read from) and shard(if it is the target we will write into)

Then, can we use source prefix for source instead of remote?

Comment (metdos) [inline src/backend/distributed/master/master_stage_protocol.c]: > On the other hand names like shardQuotedQualifiedName may be excessive and I can change them to something like shardQualifiedName.

I think that we can use shardQualifiedName to maintain consistency in the codebase.

Comment (byucesoy) [inline src/backend/distributed/master/master_stage_protocol.c]: Done

File: src/backend/distributed/worker/worker_data_fetch_protocol.c (hunk 4 above)
Comment (byucesoy) [inline src/backend/distributed/worker/worker_data_fetch_protocol.c]: Fixes. It was another weird citus_indent fix.

**Comment by byucesoy** [comment]
I fixed the bug in the UpdateShardStatistics(). I will send another patch to add test cases.

File: src/test/regress/multi_schedule [hunk 5]
```diff
@@ -17,6 +17,7 @@
 # ---
 test: multi_extension
 test: multi_table_ddl
+test: multi_schema_support
```
Comment (metdos) [inline src/test/regress/multi_schedule]: Shall we add this new test to the end of the file? I think "Tests around schema changes" implies the "table schema" here.

Similarly in multi_task_tracker_extra_schedule.

File: src/backend/distributed/master/master_stage_protocol.c [hunk 6]
```diff
@@ -601,11 +613,13 @@ WorkerTableSize(char *nodeName, uint32 nodePort, Oid relationId, char *tableName
 
 	if (cstoreTable)
 	{
-		appendStringInfo(tableSizeQuery, SHARD_CSTORE_TABLE_SIZE_QUERY, tableName);
+		appendStringInfo(tableSizeQuery, SHARD_CSTORE_TABLE_SIZE_QUERY,
+						 quote_literal_cstr(tableName));
```
Comment (metdos) [inline src/backend/distributed/master/master_stage_protocol.c]: Maybe
quotedTableName = quote_literal_cstr(tableName);

and use quotedTableName in all 3 occurrences.

File: src/backend/distributed/master/master_stage_protocol.c [hunk 7]
```diff
@@ -234,14 +238,21 @@ master_append_table_to_shard(PG_FUNCTION_ARGS)
...
+	shardTableName = LoadShardAlias(relationId, shardId);
+	if (shardTableName == NULL)
 	{
-		shardName = get_rel_name(relationId);
-		AppendShardIdToName(&shardName, shardId);
+		shardTableName = get_rel_name(relationId);
+		AppendShardIdToName(&shardTableName, shardId);
 	}
 
+	shardQualifiedName = quote_qualified_identifier(shardSchemaName,
```
Comment (metdos) [inline src/backend/distributed/master/master_stage_protocol.c]: This could fit in one line. Less than 90 characters.

File: src/backend/distributed/master/master_stage_protocol.c [hunk 8]
```diff
@@ -299,7 +310,8 @@ master_append_table_to_shard(PG_FUNCTION_ARGS)
 								workerName, workerPort);
 
 		ereport(WARNING, (errmsg("could not append table to shard \"%s\" on node "
-								 "\"%s:%u\"", shardName, workerName, workerPort),
+								 "\"%s:%u\"", shardQualifiedName, workerName,
+								 workerPort),
```
Comment (metdos) [inline src/backend/distributed/master/master_stage_protocol.c]: workerPort), could be on the upper line, it makes exactly 90 characters :)

File: src/backend/distributed/worker/worker_data_fetch_protocol.c [hunk 9]
```diff
@@ -1031,61 +1032,79 @@ ParseTreeNode(const char *ddlCommand)
...
 	uint64 shardId = INVALID_SHARD_ID;
 	bool received = false;
-	char *quotedTableName = NULL;
 	StringInfo queryString = NULL;
-	const char *schemaName = NULL;
 
-	/* copy remote table's data to this node */
-	shardNameString = makeStringInfo();
-	appendStringInfoString(shardNameString, shardName);
+	/* We extract schema names and table names from qualified names */
```
Comment (metdos) [inline src/backend/distributed/worker/worker_data_fetch_protocol.c]: Both can fit in one line.

File: src/backend/distributed/worker/worker_data_fetch_protocol.c [hunk 10]
```diff
@@ -1031,61 +1032,79 @@ ParseTreeNode(const char *ddlCommand)
...
 
+	/* copy remote table's data to this node */
 	localFilePath = makeStringInfo();
 	appendStringInfo(localFilePath, "base/%s/%s" UINT64_FORMAT,
 					 PG_JOB_CACHE_DIR, TABLE_FILE_PREFIX, shardId);
 
-	quotedTableName = quote_qualified_identifier(NULL, remoteTableName);
-	remoteCopyCommand = makeStringInfo();
-	appendStringInfo(remoteCopyCommand, COPY_OUT_COMMAND, quotedTableName);
+	sourceQualifiedName = quote_qualified_identifier(sourceSchemaName,
```
Comment (metdos) [inline src/backend/distributed/worker/worker_data_fetch_protocol.c]: Can fit in one line. <= 90 characters

**Comment by metdos** [comment]
@byucesoy I have some minor comments (mostly visual). After fixing them, you can :ship:

File: src/test/regress/multi_schedule (hunk 5 above)
Comment (byucesoy) [inline src/test/regress/multi_schedule]: Done

File: src/backend/distributed/master/master_stage_protocol.c (hunk 6 above)
Comment (byucesoy) [inline src/backend/distributed/master/master_stage_protocol.c]: Done

File: src/backend/distributed/master/master_stage_protocol.c (hunk 7 above)
Comment (byucesoy) [inline src/backend/distributed/master/master_stage_protocol.c]: Done

File: src/backend/distributed/master/master_stage_protocol.c (hunk 8 above)
Comment (byucesoy) [inline src/backend/distributed/master/master_stage_protocol.c]: It makes 91 (+1 for space) :(

File: src/backend/distributed/worker/worker_data_fetch_protocol.c (hunk 9 above)
Comment (byucesoy) [inline src/backend/distributed/worker/worker_data_fetch_protocol.c]: Done

File: src/backend/distributed/worker/worker_data_fetch_protocol.c (hunk 10 above)
Comment (byucesoy) [inline src/backend/distributed/worker/worker_data_fetch_protocol.c]: Done
