### PR TITLE
Prevent Citus table functions from being called on shards (Fix #5610)

### LINKED ISSUE #5610: Prevent Citus UDF to work on shards
When coordinator is added to the metadata, or on the workers, there are shards showing up. We normally guard manual modification to the shards via ` citus.enable_manual_changes_to_shards`.

```SQL
truncate ref_102040;
ERROR:  cannot modify "ref_102040" because it is a shard of a distributed table
HINT:  Use the distributed table or set citus.enable_manual_changes_to_shards to on to modify shards directly
Time: 4.606 ms
```

We should use the same/similar logic to prevent creating reference/distributed/citus_local_table etc:

```SQL
select create_reference_table('ref_102040');
ERROR:  relation "ref_102040" already exists
CONTEXT:  while executing command on localhost:9700
Time: 350.653 ms
```

### PR DESCRIPTION
**Pull request by gledis69**
DESCRIPTION: Prevent Citus table functions from being called on shards

The operations that guard against using shards are:
* Create Local Table
* Create distributed table (which affects reference table creation as well).

* I used a `ErrorIfRaltionIsKnownShard` instead of `ErrorIfIllegallyChangingKnownShard`.
`ErrorIfIllegallyChangingKnownShard` allows the operation if `citus.enable_manual_changes_to_shards`,
but I am not sure if it ever makes sense to create a distributed, reference, or citus local table out of a shard.

I tried to go over the code to identify other UDF-s where shards could be illegaly changed, but I could not find any other.
My knowledge of the codebase is not solid enough for me to say for sure.

Fixes #5610

### CODE REVIEW

File: src/backend/distributed/commands/citus_add_local_table_to_metadata.c [hunk 1]
```diff
@@ -195,6 +195,7 @@ CreateCitusLocalTable(Oid relationId, bool cascadeViaForeignKeys, bool autoConve
 	 */
 	EnsureCoordinator();
 	EnsureTableOwner(relationId);
+	ErrorIfRelationIsAKnownShard(relationId);
```
Comment (agedemenli) [inline src/backend/distributed/commands/citus_add_local_table_to_metadata.c:198]: We actually don't need that here. We already check this for Citus Local Tables.
In the function `ErrorIfUnsupportedCreateCitusLocalTable`. 
Please see:
https://github.com/citusdata/citus/blob/master/src/backend/distributed/commands/citus_add_local_table_to_metadata.c#L486

File: src/backend/distributed/commands/create_distributed_table.c [hunk 2]
```diff
@@ -378,6 +379,8 @@ CreateDistributedTable(Oid relationId, Var *distributionColumn, char distributio
 					   int shardCount, bool shardCountIsStrict,
 					   char *colocateWithTableName, bool viaDeprecatedAPI)
 {
+	ErrorIfRelationIsAKnownShard(relationId);
```
Comment (agedemenli) [inline src/backend/distributed/commands/create_distributed_table.c:382]: Nice to catch both distributed and reference tables with a single check!

**Review by agedemenli — CHANGES_REQUESTED** [review]
Looks good if the second check on Citus Local Tables could be removed. Before merging this PR, it would be good to have regression tests including each table type.

File: src/backend/distributed/commands/create_distributed_table.c (hunk 2 above)
Comment (agedemenli) [reply src/backend/distributed/commands/create_distributed_table.c:382]: Could you also please add a single comment here?

Comment (onderkalaci) [reply src/backend/distributed/commands/create_distributed_table.c:382]: Can we maybe move this check to `EnsureCitusTableCanBeCreated`? That seems like a place we do these kinds of checks. This probably goes as the last check there

**Comment by onderkalaci** [comment]
>  Before merging this PR, it would be good to have regression tests including each table type.

+1 on doing this

**Comment by gledis69** [comment]
I added the tests in the single_node test because afaict it was most convenient to perform operations on shards with coordinator permissions.

**Comment by jj262361** [comment]
朋友,你的来信我刚收到,谢谢你!我祝你在每天的工作或学习中都开开心心的!

File: src/backend/distributed/commands/create_distributed_table.c [hunk 3]
```diff
@@ -342,6 +344,12 @@ EnsureCitusTableCanBeCreated(Oid relationOid)
 	 * will be performed in CreateDistributedTable.
 	 */
 	EnsureRelationKindSupported(relationOid);
+
+	/*
+	 * When coordinator is added to the metadata, or on the workers,
+	 * some of the relations of the coordinator node may/will be shards.
+	 */
+	ErrorIfRelationIsAKnownShard(relationOid);
```
Comment (agedemenli) [inline src/backend/distributed/commands/create_distributed_table.c:352]: This comment looks a bit irrelevant to me. I think it would be better if we could have a more explanatory comment that tells the reader that we don't allow shards to be distributed. We'll throw this error if the user tries to create a distributed/reference table from a shard. It would be nice if we can tell this in the comment.

File: src/test/regress/sql/single_node.sql [hunk 4]
```diff
@@ -1020,6 +1020,23 @@ DROP TABLE test_disabling_drop_and_truncate_102040;
 RESET citus.shard_replication_factor;
 DROP TABLE test_disabling_drop_and_truncate;
 
+-- test creating distributed or reference tables from shards
+SET citus.shard_replication_factor TO 1;
```
Comment (agedemenli) [inline src/test/regress/sql/single_node.sql:1024]: minor: It would be the same if we could remove the reset command on line 1020, instead of adding a set command here

We already have shard_replication_factor set to 1, on line 1019. We reset that on the next line (1020), and here (1024) we set it back to 1 again.

**Review by agedemenli — COMMENTED** [review]
I have some minor comments. I think we're close to merge this. 
I also want to test it with partitioned tables.

File: src/test/regress/sql/single_node.sql [hunk 5]
```diff
@@ -1020,6 +1020,23 @@ DROP TABLE test_disabling_drop_and_truncate_102040;
...
+SELECT create_distributed_table('test_creating_distributed_relation_table_from_shard', 'a');
+
+-- these should error because shards cannot be used to:
+-- create distributed table
+SELECT create_distributed_table('test_creating_distributed_relation_table_from_shard_102044', 'a');
+
+-- create reference table
+SELECT create_reference_table('test_creating_distributed_relation_table_from_shard_102044');
+
+DROP TABLE test_creating_distributed_relation_table_from_shard_102044;
```
[the remark this answers is not in the document]
Comment (gledis69) [reply src/test/regress/sql/single_node.sql:1035]: I was not sure that the shard would be dropped as well so I erred in the side of safety. Will remove.

File: src/backend/distributed/commands/create_distributed_table.c (hunk 3 above)
Comment (agedemenli) [reply src/backend/distributed/commands/create_distributed_table.c:352]: /*
	 * When coordinator is added to the metadata, or on the workers,
	 * some of the relations of the coordinator node may/will be shards.
	 * We disallow creating distributed tables from shard relations, by
	 * erroring out here.
	 */

**Review by agedemenli — APPROVED** [review]
Thanks!
Could you please revise the comment before merging? I've added a suggestion.

File: src/backend/distributed/commands/create_distributed_table.c (hunk 3 above)
Comment (agedemenli) [reply src/backend/distributed/commands/create_distributed_table.c:352]: No, we have a separate check for Citus Local Tables.
https://github.com/citusdata/citus/pull/5694#discussion_r802443357

Comment (onderkalaci) [reply src/backend/distributed/commands/create_distributed_table.c:355]: Thanks for the clarification!

**Review by onderkalaci — APPROVED** [review]
