### PR TITLE
Send explain queries with savepoints

### LINKED ISSUE #1344: EXPLAIN ANALYZE with DML executes write twice
I think this used to just throw an error:

```
CREATE TABLE test (x int, y int);
SELECT create_distributed_table('test', 'x');
EXPLAIN ANALYZE INSERT INTO test (x) VALUES (5);
                                                   QUERY PLAN                                                   
----------------------------------------------------------------------------------------------------------------
 Custom Scan (Citus Router)  (cost=0.00..0.00 rows=0 width=0) (actual time=5.292..5.292 rows=0 loops=1)
   Task Count: 1
   Tasks Shown: All
   ->  Task
         Node: host=localhost port=9700 dbname=postgres
         ->  Insert on test_102951  (cost=0.00..0.01 rows=1 width=8) (actual time=0.058..0.058 rows=0 loops=1)
               ->  Result  (cost=0.00..0.01 rows=1 width=8) (actual time=0.001..0.002 rows=1 loops=1)
             Planning time: 0.321 ms
             Execution time: 0.099 ms
 Planning time: 0.177 ms
 Execution time: 5.357 ms
(11 rows)

postgres=# SELECT * FROM test;
 x | y 
---+---
 5 |  
 5 |  
(2 rows)
```

### PR DESCRIPTION
**Pull request by metdos**
With this commit, we started to send explain queries within a savepoint. After
running explain query, we rollback to savepoint. This saves us from side effects
of EXPLAIN ANALYZE on DML queries.

Fixes #1344

### CODE REVIEW

**Comment by metdos** [comment]
I couldn't add regression tests because EXPLAIN ANALYZE prints time even though I switch off costs and time.

```sql
postgres=# EXPLAIN (ANALYZE TRUE, VERBOSE FALSE, COSTS FALSE, BUFFERS FALSE, TIMING FALSE, FORMAT TEXT) INSERT INTO public.explain_table_102070 (id) VALUES (995);
                       QUERY PLAN
--------------------------------------------------------
 Insert on explain_table_102070 (actual rows=0 loops=1)
   ->  Result (actual rows=1 loops=1)
 Planning time: 0.144 ms
 Execution time: 0.086 ms
(4 rows)
```

Here are some tests I run;

```SQL
CREATE TABLE explain_table (id int, value int);
SELECT create_distributed_table('explain_table', 'id');

-- test explain analyze with DML queries
EXPLAIN ANALYZE INSERT INTO explain_table VALUES (1, 0);
SELECT * FROM explain_table ORDER BY id, value;

EXPLAIN ANALYZE UPDATE explain_table SET value = 1 WHERE id = 1;
SELECT * FROM explain_table ORDER BY id, value;

-- DELETE is a bit tricky because we first DELETE rows then run the explain query
EXPLAIN ANALYZE DELETE FROM explain_table WHERE id = 1;
SELECT * FROM explain_table ORDER BY id, value;

-- test explain within a transaction
BEGIN;
EXPLAIN ANALYZE INSERT INTO explain_table VALUES (1, 0);
COMMIT;
SELECT * FROM explain_table ORDER BY id, value;

BEGIN;
EXPLAIN ANALYZE INSERT INTO explain_table VALUES (2, 0);
ROLLBACK;
SELECT * FROM explain_table ORDER BY id, value;

BEGIN;
INSERT INTO explain_table VALUES (3, 0);
EXPLAIN ANALYZE INSERT INTO explain_table VALUES (3, 0);
EXPLAIN ANALYZE INSERT INTO explain_table VALUES (3, 0);
INSERT INTO explain_table VALUES (3, 0);
COMMIT;
SELECT * FROM explain_table ORDER BY id, value;

DROP TABLE explain_table;
```

I run a couple of next scripts in parallel to test concurrency.
```bash
for i in `seq 1 1000`;
do
    /usr/local/pgsql/bin/psql -d postgres -c  "EXPLAIN ANALYZE INSERT INTO explain_table VALUES ($i);"
done
```

**Comment by metdos** [comment]
@anarazel, could you take a look when you have time?

File: src/backend/distributed/connection/remote_commands.c [hunk 1]
```diff
@@ -326,6 +328,38 @@ SendRemoteCommand(MultiConnection *connection, const char *command)
...
+
+	ExecStatusType status = PQresultStatus(queryResult);
+	if (status == PGRES_TUPLES_OK)
+	{
+		rowCount = PQntuples(queryResult);
+	}
+
+	for (rowIndex = 0; rowIndex < rowCount; rowIndex++)
+	{
+		char *rowValue = MultiClientGetValue(queryResult, rowIndex, columnIndex);
```
Comment (marcocitus) [inline src/backend/distributed/connection/remote_commands.c]: This is just a thin (deprecated) wrapper around PQgetvalue, so maybe just call that directly.

File: src/backend/distributed/planner/multi_explain.c [hunk 2]
```diff
@@ -293,10 +296,60 @@ RemoteExplain(Task *task, ExplainState *es)
...
+
+		/*
+		 * Use a coordinated transaction to skip sending BEGIN in an already
+		 * existing transaction.
+		 */
+		BeginOrContinueCoordinatedTransaction();
+		RemoteTransactionBeginIfNecessary(connection);
+
+		/* start a savepoint for explain */
+		executeResult = ExecuteOptionalRemoteCommand(connection,
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_explain.c]: Why optional? We just want to roll back on failure.

Comment (marcocitus) [inline src/backend/distributed/planner/multi_explain.c]: Never mind, we don't :)

File: src/backend/distributed/planner/multi_explain.c [hunk 3]
```diff
@@ -293,10 +296,60 @@ RemoteExplain(Task *task, ExplainState *es)
...
-		remotePlan->explainOutputList = ExecuteRemoteQuery(nodeName, nodePort,
-														   NULL, explainQuery);
+
+		connection = GetNodeConnection(connectionFlags, nodeName, nodePort);
+
+		/*
+		 * Use a coordinated transaction to skip sending BEGIN in an already
+		 * existing transaction.
+		 */
+		BeginOrContinueCoordinatedTransaction();
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_explain.c]: Maybe move this to before the loop.

File: src/backend/distributed/planner/multi_explain.c [hunk 4]
```diff
@@ -293,10 +296,60 @@ RemoteExplain(Task *task, ExplainState *es)
...
+		MultiConnection *connection = NULL;
+		PGresult *queryResult = NULL;
+		int connectionFlags = SESSION_LIFESPAN;
+		int executeResult = 0;
 
 		remotePlan->placementIndex = placementIndex;
-		remotePlan->explainOutputList = ExecuteRemoteQuery(nodeName, nodePort,
-														   NULL, explainQuery);
+
+		connection = GetNodeConnection(connectionFlags, nodeName, nodePort);
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_explain.c]: We should probably use GetPlacementConnection here. We might create a deadlock if we run an EXPLAIN on the wrong connection after a DDL.

File: src/backend/distributed/connection/remote_commands.c (hunk 1 above)
Comment (metdos) [inline src/backend/distributed/connection/remote_commands.c]: Good point!

File: src/backend/distributed/planner/multi_explain.c (hunk 2 above)
Comment (marcocitus) [inline src/backend/distributed/planner/multi_explain.c]: On the other hand, the code would be a bit cleaner here if we used ExecuteCriticalRemoteCommand. If we add `if (connection->pgConn) continue;` after `GetPlacementConnection` then we still get failover if the worker is down.

File: src/backend/distributed/connection/remote_commands.c [hunk 5]
```diff
@@ -326,6 +327,38 @@ SendRemoteCommand(MultiConnection *connection, const char *command)
 
 
 /*
+ * ReadRemoteQueryResults reads first columns of result tuples from the given
+ * PGresult struct and returns them in a StringInfo list.
+ */
+List *
+ReadRemoteQueryResults(PGresult *queryResult)
```
Comment (marcocitus) [inline src/backend/distributed/connection/remote_commands.c]: To be more descriptive, maybe something like `ReadColumnAsText`

File: src/backend/distributed/planner/multi_explain.c [hunk 6]
```diff
@@ -310,25 +310,20 @@ RemoteExplain(Task *task, ExplainState *es)
...
 		}
 
+		RemoteTransactionBeginIfNecessary(connection);
+
+		/* start a savepoint for explain */
+		ExecuteCriticalRemoteCommand(connection, "SAVEPOINT citus_explain_savepoint");
+
 		/* run explain query */
-		queryResult = NULL;
 		executeResult = ExecuteOptionalRemoteCommand(connection, explainQuery->data,
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_explain.c]: Probably makes sense to use ExecuteCriticalRemoteCommand here too.

File: src/backend/distributed/planner/multi_explain.c [hunk 7]
```diff
@@ -288,15 +292,56 @@ RemoteExplain(Task *task, ExplainState *es)
...
+	BeginOrContinueCoordinatedTransaction();
+
 	for (placementIndex = 0; placementIndex < placementCount; placementIndex++)
 	{
 		ShardPlacement *taskPlacement = list_nth(taskPlacementList, placementIndex);
-		char *nodeName = taskPlacement->nodeName;
-		uint32 nodePort = taskPlacement->nodePort;
+		MultiConnection *connection = NULL;
+		PGresult *queryResult = NULL;
+		int connectionFlags = SESSION_LIFESPAN;
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_explain.c]: This should be 0.

File: src/backend/distributed/planner/multi_explain.c [hunk 8]
```diff
@@ -288,15 +292,56 @@ RemoteExplain(Task *task, ExplainState *es)
...
+
+		/* try other placements if we fail to connect this one */
+		if (PQstatus(connection->pgConn) != CONNECTION_OK)
+		{
+			continue;
+		}
+
+		RemoteTransactionBeginIfNecessary(connection);
+
+		/* start a savepoint for explain */
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_explain.c]: Maybe elaborate on why we set a savepoint.

**Comment by metdos** [comment]
@marcocitus, do you have any further comments?

**Comment by anarazel** [comment]
Could you add a test that does something like
```
BEGIN;
CREATE TABLE whatnot(parcol int primary key);
create_distributed_table(...)
EXPLAIN SELECT count(*) FROM whatnot;
```
to make sure we use the right connection?

**Comment by marcocitus** [comment]
`create_distributed_table` doesn't use the connection API.

**Comment by marcocitus** [comment]
Hm, well, maybe if you put in some data first and then do an explain analyze to check the row count. The data loading does use the connection API.

**Comment by anarazel** [comment]
On 2017-04-28 10:30:09 -0700, Marco Slot wrote:
> `create_distributed_table` doesn't use the connection API.

GAH, we should fix that, right.

**Comment by marcocitus** [comment]
I guess this works:

```
BEGIN;
INSERT INTO test VALUES (1,2);
SELECT create_distributed_table('test', 'x');
EXPLAIN (ANALYZE, COSTS FALSE) SELECT * FROM test WHERE x = 1;
                                     QUERY PLAN                                     
------------------------------------------------------------------------------------
 Custom Scan (Citus Router) (actual time=0.848..0.849 rows=1 loops=1)
   Task Count: 1
   Tasks Shown: All
   ->  Task
         Node: host=localhost port=9701 dbname=postgres
         ->  Seq Scan on test_103138 test (actual time=0.004..0.004 rows=1 loops=1)
               Filter: (x = 1)
             Planning time: 0.221 ms
             Execution time: 0.019 ms
 Planning time: 1.087 ms
 Execution time: 0.946 ms
(11 rows)

```

**Comment by marcocitus** [comment]
(this shouldn't be a regression test, given planning/execution time)

**Comment by marcocitus** [comment]
ok, this appears to work and would deadlock if it picked the wrong connection:

```

postgres=# BEGIN;
BEGIN
Time: 0.315 ms
postgres=# ALTER TABLE test ADD COLUMN z int;
NOTICE:  using one-phase commit for distributed DDL commands
HINT:  You can enable two-phase commit for extra safety with: SET citus.multi_shard_commit_protocol TO '2pc'
ALTER TABLE
Time: 68.545 ms
postgres=# EXPLAIN (COSTS OFF) SELECT z FROM test WHERE x = 1; 
                       QUERY PLAN                       
--------------------------------------------------------
 Custom Scan (Citus Router)
   Task Count: 1
   Tasks Shown: All
   ->  Task
         Node: host=localhost port=9701 dbname=postgres
         ->  Seq Scan on test_103234 test
               Filter: (x = 1)
(7 rows)

Time: 2.477 ms
```

**Comment by metdos** [comment]
@marcocitus, @anarazel, I added the regression test and squashed commits. If this looks good, I will merge it.

File: src/test/regress/expected/multi_explain.out [hunk 9]
```diff
@@ -669,3 +669,21 @@ Custom Scan (Citus Router)  (cost=0.00..0.00 rows=0 width=0)
...
+EXPLAIN (COSTS FALSE) SELECT value FROM explain_table WHERE id = 1;
+Custom Scan (Citus Router)
+  Task Count: 1
+  Tasks Shown: All
+  ->  Task
+        Node: host=localhost port=57637 dbname=regression
+        ->  Index Scan using explain_table_pkey_570001 on explain_table_570001 explain_table
+              Index Cond: (id = 1)
+COMMIT;
+DROP TABLE explain_table;
```
Comment (marcocitus) [inline src/test/regress/expected/multi_explain.out]: Would be fine to just ABORT here.

File: src/test/regress/expected/multi_explain.out [hunk 10]
```diff
@@ -669,3 +669,21 @@ Custom Scan (Citus Router)  (cost=0.00..0.00 rows=0 width=0)
...
+ALTER TABLE explain_table ADD COLUMN value int;
+NOTICE:  using one-phase commit for distributed DDL commands
+HINT:  You can enable two-phase commit for extra safety with: SET citus.multi_shard_commit_protocol TO '2pc'
+EXPLAIN (COSTS FALSE) SELECT value FROM explain_table WHERE id = 1;
+Custom Scan (Citus Router)
+  Task Count: 1
+  Tasks Shown: All
+  ->  Task
+        Node: host=localhost port=57637 dbname=regression
+        ->  Index Scan using explain_table_pkey_570001 on explain_table_570001 explain_table
```
Comment (marcocitus) [inline src/test/regress/expected/multi_explain.out]: I wonder if this can every be a sequential scan due to the small table size. Could consider removing the primary key.
