### PR TITLE
Exclude-Generated-Columns-In-Copy

### LINKED ISSUE #6705: Problem with generated column when rebalancing tables shards.
Hi,
We're using Citus 11.1.4

## Steps to reproduce

1. Create distributed table and insert some data into it
```sql
CREATE TABLE t1 (id int PRIMARY KEY);
SELECT create_distributed_table('t1', 'id');
INSERT INTO t1 SELECT generate_series(1,1000) AS id;
```
2. Move shards off the designated node and disable the node temporarily
```sql
SELECT * FROM citus_drain_node('citus_worker_3', 5432);
SELECT * FROM citus_disable_node('citus_worker_3', 5432);
```
3. Add a new generated column to the distributed table
```sql
ALTER TABLE t1 ADD COLUMN new_id INT GENERATED ALWAYS AS ( id + 3 ) STORED;
```
4. Activate node
```sql
SELECT * FROM citus_activate_node('citus_worker_3', 5432);
SELECT * FROM citus_set_node_property('citus_worker_3', 5432, 'shouldhaveshards', true);
```
5. Start to rebalance tables shards
```sql
SELECT * FROM citus_rebalance_start();
```
6. Run query to monitor rebalance progress
```sql
SELECT * FROM pg_dist_background_task WHERE job_id = 1 ORDER BY task_id ASC \gx
```
```bash
-[ RECORD 1 ]--------------------------------------------------------------------------------------------------------
job_id      | 1
task_id     | 1
owner       | postgres
pid         |
status      | error
command     | SELECT pg_catalog.citus_move_shard_placement(102009,'citus_worker_2',5432,'citus_worker_3',5432,'auto')
retry_count | 33
not_before  |
message     | ERROR: row field count is 2, expected 1                                                                +
            | CONTEXT: while executing command on citus_worker_2:5432                                                +
            | Citus Background Task Queue Executor: docker/postgres                                                  +
```
or see logs on the citus_worker_3
```sql
2023-02-08 14:58:22.165 UTC [1088] ERROR:  row field count is 2, expected 1
2023-02-08 14:58:22.165 UTC [1088] CONTEXT:  COPY t1_102009, line 1
```
(Above steps has been reproduced in the docker environment using https://github.com/citusdata/docker/blob/master/docker-compose.yml)

### PR DESCRIPTION
**Pull request by emelsimsek**
DESCRIPTION: Fixes a bug in shard copy operations.

For copying shards in both shard move and shard split operations, Citus uses the COPY statement.  

A COPY all statement in the following form
` COPY target_shard FROM STDIN;`
throws an error when there is a GENERATED column in the shard table.

In order to fix this issue, we need to exclude the GENERATED columns in the COPY and the matching SELECT statements. Hence this fix converts the COPY and SELECT all statements to the following form:
```
COPY target_shard (col1, col2, ..., coln) FROM STDIN;
SELECT (col1, col2, ..., coln) FROM source_shard;
```
where (col1, col2, ..., coln) does not include a GENERATED column. 
GENERATED column values are created in the target_shard as the values are inserted.

Fixes #6705.

### CODE REVIEW

**Comment by marcocitus** [comment]
I think the problem is that we should not add GENERATED properties to the sharda to begin with, only to shell tables. The DDL propagation should be updated.

**Review by marcocitus — DISMISSED** [review]
See above

**Review by JelteF — COMMENTED** [review]
Should include some tests to make sure we don't regress in the future.

**Comment by marcocitus** [comment]
Looking at it more closely, I guess GENERATED ALWAYS properties have to be pushed down to workers because they can change in case of update, and we would miss those changes unless we explicitly add assignments for those fields in the UPDATE.

We may have to be a little bit careful what we allow on the DDL side though, e.g. things can change per node:
```sql
create table test (x int, y int);
select create_distributed_table('test','x');
insert into test select generate_series(1,10) s;
alter table test add column n oid generated always as (tableoid) stored;
select * from test order by 1,2;
┌────┬───┬────────┐
│ x  │ y │   n    │
├────┼───┼────────┤
│  1 │   │ 242995 │
│  2 │   │ 255643 │
│  3 │   │ 243016 │
│  4 │   │ 255619 │
│  5 │   │ 255616 │
│  6 │   │ 255637 │
│  7 │   │ 255619 │
│  8 │   │ 255607 │
│  9 │   │ 255649 │
│ 10 │   │ 255613 │
└────┴───┴────────┘
(10 rows)
```
(though there's probably no good way to support this one, so maybe using the shard OID is an acceptable trade-off)

File: src/backend/distributed/operations/worker_shard_copy.c [hunk 1]
```diff
@@ -344,21 +345,99 @@ ShardCopyDestReceiverDestroy(DestReceiver *dest)
 }
 
 
+static StringInfo
+ConstructTargetColumnsList(TupleDesc tupdesc)
+{
+	StringInfo columnList = makeStringInfo();
+	int i;
+
+	for (i = 0; i < tupdesc->natts; i++)
```
Comment (JelteF) [inline src/backend/distributed/operations/worker_shard_copy.c:354]: nit:

```suggestion
	for (int i = 0; i < tupdesc->natts; i++)
```

File: src/backend/distributed/operations/worker_shard_copy.c [hunk 2]
```diff
@@ -344,21 +345,99 @@ ShardCopyDestReceiverDestroy(DestReceiver *dest)
...
+		if (!first)
+		{
+			appendStringInfo(columnList, ", ");
+		}
+
+		appendStringInfo(columnList, "%s ", NameStr(attributeTuple->attname));
+
+		first = false;
+	}
+
```
Comment (JelteF) [inline src/backend/distributed/operations/worker_shard_copy.c:411]: Instead of implementing the same loop twice, I think this can call `ConstructTargetColumnsList(relation->rd_att)`

File: src/backend/distributed/operations/worker_shard_copy.c (hunk 1 above)
Comment (emelsimsek) [reply src/backend/distributed/operations/worker_shard_copy.c]: Done.

**Comment by emelsimsek** [comment]
@JelteF, this change is ready for a re-review I believe.

File: src/backend/distributed/operations/worker_shard_copy.c [hunk 3]
```diff
@@ -344,21 +345,80 @@ ShardCopyDestReceiverDestroy(DestReceiver *dest)
 }
 
 
+/*
+ *  GenerateColumnListFromTupleDesc function creates and returns a comma seperated column names string  to be used in COPY
+ *  and SELECT statements when copying a table. The COPY and SELECT statements should filter out the GENERATED columns since COPY
+ *  statement fails to handle them. Iterating over the attributes of the table we also need to skip the dropped columns.
+ */
+const char *
+GenerateColumnListFromTupleDesc(TupleDesc tupDesc)
```
Comment (JelteF) [inline src/backend/distributed/operations/worker_shard_copy.c:354]:
```suggestion
CopyableColumnNamesFromTupleDesc(TupleDesc tupDesc)
```

File: src/backend/distributed/operations/worker_shard_copy.c [hunk 4]
```diff
@@ -344,21 +345,80 @@ ShardCopyDestReceiverDestroy(DestReceiver *dest)
...
+
+	return columnList->data;
+}
+
+
+/*
+ *  GenerateColumnListFromRelationName function is a wrapper for GenerateColumnListFromTupleDesc.
+ */
+const char *
+GenerateColumnListFromRelationName(const char *relationName, const char *schemaName)
```
Comment (JelteF) [inline src/backend/distributed/operations/worker_shard_copy.c:384]: Previous name is not very descriptive and generally schemaname comes before tablename.
```suggestion
CopyableColumnNamesFromRelationName(const char *schemaName, const char *relationName)
```

**Review by JelteF — APPROVED** [review]

File: src/test/regress/sql/worker_split_copy_test.sql [hunk 5]
```diff
@@ -110,8 +110,61 @@ SELECT COUNT(*) FROM worker_split_copy_test."test !/ \n _""dist_123_table_810700
...
+\c - - - :master_port
+SET search_path TO worker_split_copy_test;
+SET citus.shard_count TO 2;
+SET citus.shard_replication_factor TO 1;
+SET citus.next_shard_id TO 81080000;
+
+-- BEGIN: Create distributed table and insert data.
+CREATE TABLE worker_split_copy_test.dist_table_with_generated_col(id int primary key, new_id int GENERATED ALWAYS AS ( id + 3 ) stored, value char);
+SELECT create_distributed_table('dist_table_with_generated_col', 'id');
+INSERT INTO dist_table_with_generated_col (id, value) (SELECT g.id, 'N' FROM generate_series(1, 1000) AS g(id));
```
Comment (JelteF) [inline src/test/regress/sql/worker_split_copy_test.sql:123]: Would be good to drop the value column here too. To also test for dropped columns, just like is done for shard moves.

File: src/test/regress/sql/worker_split_copy_test.sql [hunk 6]
```diff
@@ -110,8 +110,61 @@ SELECT COUNT(*) FROM worker_split_copy_test."test !/ \n _""dist_123_table_810700
...
+\c - - - :worker_1_port
+SELECT COUNT(*) FROM worker_split_copy_test.dist_table_with_generated_col_81080000;
+SELECT COUNT(*) FROM worker_split_copy_test.dist_table_with_generated_col_81080015;
+
+-- BEGIN: List row count for target shard in Worker2.
+\c - - - :worker_2_port
+SELECT COUNT(*) FROM worker_split_copy_test.dist_table_with_generated_col_81080016;
+
+\c - - - :worker_1_port
+SELECT * from worker_split_copy(
```
Comment (JelteF) [inline src/test/regress/sql/worker_split_copy_test.sql:142]: This is testing the low level function only. I think it would be good to add a generated column to the table in `citus_split_shard_by_split_points.sql` and `citus_non_blocking_split_shards.sql`to also test everything end-to-end.

**Review by JelteF — DISMISSED** [review]
added some final comments for regression test additions. Other than that this looks good.

**Comment by emelsimsek** [comment]
> added some final comments for regression test additions. Other than that this looks good.

@JelteF, I believe I have addressed all the review comments now. But looks like I need another approval.

**Review by JelteF — APPROVED** [review]
