### PR TITLE
Prevent pushing down INSERT .. SELECT queries that we shouldn't (and allow some more)

### LINKED ISSUE #1428: Unify error checks for subquery pushdown and INSERT .. SELECT
(Note that this came up in a customer conversation)

With 6.2 release, we've merged the logic of subquery pushdown and `INSERT .. SELECT`. However, the error checks for each of the logic remains separated. We should unify the error checks to give better user experience.

For example, `INSERT ... SELECT` could support `DISTINCT ON` and `UNION` with 6.2. However, due to some of the limitations of 6.1, Citus errors out on such queries unnecessarily.

As we're planning to improve subquery pushdown coverage (i.e., `LIMIT`s in the subqueries), this issue would become more apparent.

### LINKED ISSUE #6749: Distributed INSERT SELECT might mistakenly push-down / not push-down some SELECT queries that we shouldn't / could
```sql
-- create two distributed tables that belong to same colocation group
create table dist_c1_t1 (a int, b int);
create table dist_c1_t2 (a int, b int);

SELECT create_distributed_table('dist_c1_t1', 'a', shard_count=>4);
SELECT create_distributed_table('dist_c1_t2', 'a', colocate_with=>'dist_c1_t1');

-- create another distributed table that belong to a different colocation group
create table dist_c2_t1 (a int, b int);
SELECT create_distributed_table('dist_c2_t1', 'a', shard_count=>3);

-- and create a reference table
create table ref(a int, b int);
SELECT create_reference_table('ref');
```

----

Example - 1: Incorrect query push-down due to missing colocation check.

As long as we're inserting into target rel's distribution column from the distribution column of a colocated distributed rel, we consider given INSERT .. SELECT command as distributed. However, this might not be always correct.
```sql
-- Below, we create two join tasks based on same shard (public.dist_c2_t1_102016) due to shard count mismatch.
explain insert into dist_c1_t1 select dist_c1_t2.* from dist_c1_t2 join dist_c2_t1 using(a);
DEBUG:  distributed statement: INSERT INTO public.dist_c1_t1_102008 AS citus_table_alias (a, b) SELECT dist_c1_t2.a, dist_c1_t2.b FROM (public.dist_c1_t2_102012 dist_c1_t2(a, b) JOIN public.dist_c2_t1_102016 dist_c2_t1(a, b) USING (a)) WHERE (dist_c1_t2.a IS NOT NULL)
DEBUG:  distributed statement: INSERT INTO public.dist_c1_t1_102009 AS citus_table_alias (a, b) SELECT dist_c1_t2.a, dist_c1_t2.b FROM (public.dist_c1_t2_102013 dist_c1_t2(a, b) JOIN public.dist_c2_t1_102016 dist_c2_t1(a, b) USING (a)) WHERE (dist_c1_t2.a IS NOT NULL)
DEBUG:  distributed statement: INSERT INTO public.dist_c1_t1_102010 AS citus_table_alias (a, b) SELECT dist_c1_t2.a, dist_c1_t2.b FROM (public.dist_c1_t2_102014 dist_c1_t2(a, b) JOIN public.dist_c2_t1_102017 dist_c2_t1(a, b) USING (a)) WHERE (dist_c1_t2.a IS NOT NULL)
DEBUG:  distributed statement: INSERT INTO public.dist_c1_t1_102011 AS citus_table_alias (a, b) SELECT dist_c1_t2.a, dist_c1_t2.b FROM (public.dist_c1_t2_102015 dist_c1_t2(a, b) JOIN public.dist_c2_t1_102018 dist_c2_t1(a, b) USING (a)) WHERE (dist_c1_t2.a IS NOT NULL)
```

Also see https://github.com/citusdata/citus/issues/6749#issuecomment-1470874911.

----

Example - 2: Incorrect query push-down because MultiTaskRouterSelectQuerySupported lacks of some push-down checks that we normally perform for SELECT queries, via DeferErrorIfUnsupportedSubqueryPushdown.

Besides that, MultiTaskRouterSelectQuerySupported also enforces some restrictions that we don't need and hence prevents pushing down some forms of INSERT .. SELECT.
See https://github.com/citusdata/citus/issues/6749#issuecomment-1470681280.

```sql
-- I don't think we normally allow pushing down such an outer join.
-- Normally, we should handle such a join via recursive planning.
--
-- Root-cause: 
explain insert into dist_c1_t2 select t1.* from dist_c1_t1 t1 right join ref using(a);
DEBUG:  distributed statement: INSERT INTO public.dist_c1_t2_102012 AS citus_table_alias (a, b) SELECT t1.a, t1.b FROM (public.dist_c1_t1_102008 t1(a, b) RIGHT JOIN public.ref_102019 ref(a, b) USING (a)) WHERE (t1.a IS NOT NULL)
DEBUG:  distributed statement: INSERT INTO public.dist_c1_t2_102013 AS citus_table_alias (a, b) SELECT t1.a, t1.b FROM (public.dist_c1_t1_102009 t1(a, b) RIGHT JOIN public.ref_102019 ref(a, b) USING (a)) WHERE (t1.a IS NOT NULL)
DEBUG:  distributed statement: INSERT INTO public.dist_c1_t2_102014 AS citus_table_alias (a, b) SELECT t1.a, t1.b FROM (public.dist_c1_t1_102010 t1(a, b) RIGHT JOIN public.ref_102019 ref(a, b) USING (a)) WHERE (t1.a IS NOT NULL)
DEBUG:  distributed statement: INSERT INTO public.dist_c1_t2_102015 AS citus_table_alias (a, b) SELECT t1.a, t1.b FROM (public.dist_c1_t1_102011 t1(a, b) RIGHT JOIN public.ref_102019 ref(a, b) USING (a)) WHERE (t1.a IS NOT NULL)
```

### LINKED ISSUE #6920: Inline CTEs for modification queries
As @tejeswarm noted, Postgres does inline CTEs when the top-level command is modification, whereas Citus skips.

```C
Postgres

SS_process_ctes
    CmdType         cmdType = ((Query *) cte->ctequery)->commandType;
    if (cmdType == CMD_SELECT && !contain_dml(cte->ctequery) &&....

 

Citus

InlineCTEsInQueryTree(Query *query)
    PostgreSQLCTEInlineCondition(cte, query->commandType))
        if  cmdType == CMD_SELECT && !contain_dml(cte->ctequery) &&...
```

We should be careful about stable functions inside CTEs.

### PR DESCRIPTION
**Pull request by onurctirtir**
DESCRIPTION: Fixes a bug that causes incorrectly pushing down some INSERT .. SELECT queries that we shouldn't
DESCRIPTION: Prevents unnecessarily pulling the data into coordinator for some INSERT .. SELECT queries
DESCRIPTION: Drops support for pushing down INSERT .. SELECT with append table as target

Fixes #6749.
Fixes #1428.
Fixes #6920.

### CODE REVIEW

File: src/backend/distributed/planner/insert_select_planner.c [hunk 1]
```diff
@@ -688,7 +690,11 @@ DistributedInsertSelectSupported(Query *queryTree, RangeTblEntry *insertRte,
 	}
 
 	/* we don't support LIMIT, OFFSET and WINDOW functions */
-	DeferredErrorMessage *error = MultiTaskRouterSelectQuerySupported(subquery);
+    bool requireSubqueryPushdownCondsForTopLevel = true;
```
Comment (onurctirtir) [inline src/backend/distributed/planner/insert_select_planner.c:693]: While using limit / offset clauses in top-level query doesn't prevent a query from being handled by router planner, this is not the case for distributed insert select. This is because, a "distributed insert select" doesn't necessarily mean targeting a single worker node.

File: src/test/regress/expected/coordinator_shouldhaveshards.out [hunk 2]
```diff
@@ -939,7 +939,8 @@ inserts AS (
 ) SELECT count(*) FROM inserts;
 DEBUG:  generating subplan XXX_1 for CTE stats: SELECT count(key) AS m FROM coordinator_shouldhaveshards.table_1
 DEBUG:  generating subplan XXX_2 for CTE inserts: INSERT INTO coordinator_shouldhaveshards.table_2 (key, value) SELECT table_1.key, count(*) AS count FROM coordinator_shouldhaveshards.table_1 WHERE (table_1.key OPERATOR(pg_catalog.>=) (SELECT stats.m FROM (SELECT intermediate_result.m FROM read_intermediate_result('XXX_1'::text, 'binary'::citus_copy_format) intermediate_result(m bigint)) stats)) GROUP BY table_1.key HAVING (count(*) OPERATOR(pg_catalog.<=) (SELECT stats.m FROM (SELECT intermediate_result.m FROM read_intermediate_result('XXX_1'::text, 'binary'::citus_copy_format) intermediate_result(m bigint)) stats)) LIMIT 1 RETURNING table_2.key, table_2.value
-DEBUG:  LIMIT clauses are not allowed in distributed INSERT ... SELECT queries
+DEBUG:  cannot push down this subquery
+DETAIL:  Limit clause is currently unsupported when a subquery references a column from another query
```
Comment (onurctirtir) [inline src/test/regress/expected/coordinator_shouldhaveshards.out:943]: DeferErrorIfUnsupportedSubqueryPushdown assumes that the input query is a subquery, hence the debug message is misleading

File: src/test/regress/expected/intermediate_result_pruning.out [hunk 3]
```diff
@@ -762,7 +762,8 @@ ROLLBACK;
 -- We use offset 1 to make sure the result needs to be pulled to the coordinator, offset 0 would be optimized away
 INSERT INTO table_1
 	SELECT * FROM table_2 OFFSET 1;
-DEBUG:  OFFSET clauses are not allowed in distributed INSERT ... SELECT queries
+DEBUG:  cannot push down this subquery
+DETAIL:  Offset clause is currently unsupported when a subquery references a column from another query
```
Comment (onurctirtir) [inline src/test/regress/expected/intermediate_result_pruning.out:766]: DeferErrorIfUnsupportedSubqueryPushdown assumes that the input query is a subquery, hence the debug message is misleading

File: src/test/regress/expected/multi_insert_select.out [hunk 4]
```diff
@@ -765,10 +762,16 @@ DEBUG:  distributed statement: INSERT INTO multi_insert_select.agg_events_133000
...
-DEBUG:  distributed statement: INSERT INTO multi_insert_select.agg_events_13300010 AS citus_table_alias (user_id) SELECT raw_events_second.user_id FROM (multi_insert_select.reference_table_13300012 reference_table LEFT JOIN multi_insert_select.raw_events_second_13300006 raw_events_second ON ((reference_table.user_id OPERATOR(pg_catalog.=) raw_events_second.user_id))) WHERE (raw_events_second.user_id IS NOT NULL)
-DEBUG:  distributed statement: INSERT INTO multi_insert_select.agg_events_13300011 AS citus_table_alias (user_id) SELECT raw_events_second.user_id FROM (multi_insert_select.reference_table_13300012 reference_table LEFT JOIN multi_insert_select.raw_events_second_13300007 raw_events_second ON ((reference_table.user_id OPERATOR(pg_catalog.=) raw_events_second.user_id))) WHERE (raw_events_second.user_id IS NOT NULL)
+DEBUG:  cannot perform a lateral outer join when a distributed subquery references a reference table
```
Comment (onurctirtir) [inline src/test/regress/expected/multi_insert_select.out:765]: When throwing an error in DeferredErrorIfUnsupportedRecurringTuplesJoin, we assume that the outer join is a lateral one because recursive planner should've already handled the such a join already, see https://github.com/citusdata/citus/pull/6512. However, this is not the case for INSERT .. SELECT. Hence the debug message is misleading.

Also copy pasting the relevant code-comment from DeferredErrorIfUnsupportedRecurringTuplesJoin:
```c
		 * For outer joins, this can only happen if it's a lateral outer join
		 * where the inner distributed subquery references the recurring outer
		 * rel. This because, such outer joins should not appear here because
		 * the recursive planner (RecursivelyPlanRecurringTupleOuterJoinWalker)
		 * should have already planned the non-recurring side if it wasn't a
		 * lateral join. For this reason, if the outer join is between a recurring
		 * rel --on the outer side-- and a non-recurring rel --on the other side--,
		 * we throw an error assuming that it's a lateral outer join. ...
```

Comment (onurctirtir) [reply src/test/regress/expected/multi_insert_select.out:765]: Besides that, this is one of the cases where we were incorrectly pushing down some insert .. select queries on main (and not on that branch).

File: src/test/regress/expected/multi_insert_select.out [hunk 5]
```diff
@@ -1126,7 +1129,8 @@ FROM   (SELECT SUM(raw_events_second.value_4) AS v4,
                raw_events_second
         WHERE  raw_events_first.user_id = raw_events_second.user_id
         GROUP  BY raw_events_second.value_3) AS foo;
-DEBUG:  Group by list without distribution column is not allowed  in distributed INSERT ... SELECT queries
+DEBUG:  cannot push down this subquery
+DETAIL:  Group by list without partition column is currently unsupported when a subquery references a column from another query
```
Comment (onurctirtir) [inline src/test/regress/expected/multi_insert_select.out:1133]: DeferErrorIfUnsupportedSubqueryPushdown assumes that the input query is a subquery, hence the debug message is misleading

**Review by onurctirtir — COMMENTED** [review]
Need to find way to improve the error messages returned from DeferErrorIfUnsupportedSubqueryPushdown.

File: src/test/regress/expected/coordinator_shouldhaveshards.out [hunk 6]
```diff
@@ -908,7 +908,7 @@ key
 FROM a JOIN table_2 USING (key)
 GROUP BY key
 HAVING (max(table_2.value) >= (SELECT value FROM a));
-DEBUG:  Group by list without distribution column is not allowed  in distributed INSERT ... SELECT queries
+DEBUG:  complex joins are only supported when all distributed tables are co-located and joined on their distribution columns
```
Comment (onurctirtir) [inline src/test/regress/expected/coordinator_shouldhaveshards.out:911]: not sure if this is the correct reason

File: src/test/regress/expected/multi_insert_select.out [hunk 7]
```diff
@@ -724,7 +720,7 @@ INSERT INTO
   raw_events_first(user_id)
   (SELECT user_id FROM raw_events_first) INTERSECT
   (SELECT user_id FROM raw_events_first);
-DEBUG:  Set operations are not allowed in distributed INSERT ... SELECT queries
+DEBUG:  complex joins are only supported when all distributed tables are co-located and joined on their distribution columns
```
Comment (onurctirtir) [inline src/test/regress/expected/multi_insert_select.out:723]: where is the join here?

**Comment by onurctirtir** [comment]
I _don't_ think we should _close & combine_ this PR with the other one.

File: src/backend/distributed/planner/insert_select_planner.c [hunk 8]
```diff
@@ -687,8 +689,30 @@ DistributedInsertSelectSupported(Query *queryTree, RangeTblEntry *insertRte,
 							 NULL, NULL);
 	}
 
-	/* we don't support LIMIT, OFFSET and WINDOW functions */
-	DeferredErrorMessage *error = MultiTaskRouterSelectQuerySupported(subquery);
+
+	/*
```
Comment (onderkalaci) [inline src/backend/distributed/planner/insert_select_planner.c:693]: Well, I'm not sure if we really need a special case for `LIMIT` here. `DeferErrorIfUnsupportedSubqueryPushdown` already has the check. 

I know that there is a special case regarding LIMIT when SubqueryPushdown is enabled. I'm fine obeying that.

SubqueryPushdown is heavily discouraged anyway, if you try to set, you get the following Notice:
```
NOTICE:  Setting citus.subquery_pushdown flag is discouraged becuase it forces the planner to pushdown certain queries, skipping relevant correctness checks.
DETAIL:  When enabled, the planner skips many correctness checks for subqueries and pushes down the queries to shards as-is. It means that the queries are likely to return wrong results unless the user is absolutely sure that pushing down the subquery is safe. This GUC is maintained only for backward compatibility, no new users are supposed to use it. The planner is capable of pushing down as much computation as possible to the shards depending on the query.
SET
```

All and all, I don't care about `SubqueryPushdown`, and I don't prefer to carry any further special rules around that.

File: src/test/regress/expected/coordinator_shouldhaveshards.out (hunk 6 above)
Comment (onderkalaci) [reply src/test/regress/expected/coordinator_shouldhaveshards.out:911]: We use `a` two times in the query. I guess ` a` on this one `SELECT value FROM a` is not colocated with the rest of the tables, so probably this is also a right error message.

I guess the order of the error checks have changed

File: src/test/regress/expected/insert_select_single_shard_table_0.out [hunk 9]
```diff
@@ -0,0 +1,845 @@
+--
```
Comment (onderkalaci) [inline src/test/regress/expected/insert_select_single_shard_table_0.out:1]: Can you please share the reason why we end-up with multiple files? I'd rather reduce the log level and remove the additional file if needed

File: src/test/regress/expected/intermediate_result_pruning.out (hunk 3 above)
Comment (onderkalaci) [reply src/test/regress/expected/intermediate_result_pruning.out:766]: Yeah, right. But I'm fine with that as of this PR given it is only debug message.

We can definitely consider a follow=up patch to improve the messages, but for now it is good to keep this patch smaller.

@onurctirtir is that OK for you as well?

File: src/test/regress/expected/intermediate_result_pruning.out [hunk 10]
```diff
@@ -830,7 +831,7 @@ INSERT INTO table_1
 	 ) foo
 	 where table_2.key != 1 AND
  	foo.key = table_2.value::int;
-DEBUG:  Set operations are not allowed in distributed INSERT ... SELECT queries
```
Comment (onderkalaci) [inline src/test/regress/expected/intermediate_result_pruning.out:833]: Do we have any tests like:

INSERT INTO TEST SELECT * FROM test UNION SELECT * FROM test;

I'm trying to understand why we disallowed SET operation pushdown in the past.  It might be some deparsing problems.

Try also:

INSERT INTO TEST b,a SELECT b,a FROM test UNION ALL SELECT b,a FROM test;

Normally these should be fine to pushdown, but apperatenly do not on main

File: src/backend/distributed/planner/insert_select_planner.c (hunk 8 above)
Comment (aykut-bozkurt) [reply src/backend/distributed/planner/insert_select_planner.c:693]: You are right that we donot need limit clause check here. `SubqueryPushdown ` is false by default, which makes subqueries with `LIMIT` clause not pushdownable. When a colocated lateral query with limit clause references an outer query, it is still safe to push down `insert select`. I just added 2 tests to show that.

File: src/test/regress/expected/intermediate_result_pruning.out (hunk 10 above)
Comment (aykut-bozkurt) [reply src/test/regress/expected/intermediate_result_pruning.out:833]: I think, ideally, we can push down the first query but `ContainsUnionSubquery` returns false since the union query does not contain FROM clause. Then `RestrictionEquivalenceForPartitionKeys` check throws error as expected. INSERT SELECT is handled by repartition as fallback though.

But still, we should let union operations be pushed down if possible for INSERT SELECT. When not possible, they will be pulled to coordinator or repartitioned.

File: src/test/regress/expected/query_single_shard_table.out [hunk 11]
```diff
@@ -1265,9 +1271,15 @@ DEBUG:  Collecting INSERT ... SELECT results on coordinator
 INSERT INTO raw_events_second
   WITH cte AS MATERIALIZED (SELECT * FROM raw_events_first)
   SELECT user_id * 1000, time, value_1, value_2, value_3, value_4 FROM cte;
+DEBUG:  cannot push down this subquery
```
Comment (aykut-bozkurt) [inline src/test/regress/expected/query_single_shard_table.out:1274]: is this OK? @onderkalaci

File: src/test/regress/expected/query_single_shard_table.out [hunk 12]
```diff
@@ -1227,6 +1230,8 @@ FROM   users_ref_table
 WHERE  NOT EXISTS (SELECT 1
                    FROM   raw_events_second
                    WHERE  raw_events_second.user_id = users_ref_table.user_id);
+DEBUG:  correlated subqueries are not supported when the FROM clause contains a reference table
```
Comment (aykut-bozkurt) [inline src/test/regress/expected/query_single_shard_table.out:1233]: Looks like a bug is fixed. Instead of pushing down, we now pull to coordinator.

File: src/test/regress/expected/query_single_shard_table.out [hunk 13]
```diff
@@ -1197,6 +1198,8 @@ SELECT COALESCE(raw_events_first.user_id, users_ref_table.user_id)
 FROM raw_events_first
      RIGHT JOIN (users_ref_table LEFT JOIN raw_events_second ON users_ref_table.user_id = raw_events_second.user_id)
      ON raw_events_first.user_id = users_ref_table.user_id;
+DEBUG:  cannot perform a lateral outer join when a distributed subquery references a reference table
```
Comment (aykut-bozkurt) [inline src/test/regress/expected/query_single_shard_table.out:1201]: Looks like a bug fixed. Instead of pushing down, we now pull to coordinator.

Comment (aykut-bozkurt) [inline src/test/regress/expected/query_single_shard_table.out:1201]: This is an odd message since we do not have lateral join. But it is fine after I check `DeferredErrorIfUnsupportedRecurringTuplesJoin`. Normally we expect only lateral recurring outer joins can throw error here since we recursively plan other recurring outer joins via recursive planner. But, this check can be hit by INSERT SELECT planner before we recursively plan SELECT part of the query.

Comment (onurctirtir) [reply src/test/regress/expected/query_single_shard_table.out:1201]: https://github.com/citusdata/citus/pull/6752#discussion_r1175404134

>  But it is fine after I check DeferredErrorIfUnsupportedRecurringTuplesJoin.

I think we should fix the wording used DeferredErrorIfUnsupportedRecurringTuplesJoin, i.e., we should stop assuming that the joins that appear in that function are lateral joins.

**Review by onderkalaci — COMMENTED** [review]
This is mostly in a good shape, with some minor comments. And, very important improvement!

However, this also changes a very critical code-path. Do you mind spending a little more time adding tests? The idea is that we expanded subquery pushdown logic a lot in the past, and probably do not have any tests/coverage for INSERT .. SELECT pieces of the equivalent queries as they went over completely different code-paths.

Test suggestions:
1. Some tests with colocated sublinks in the target-list with INSERT .. SELECT queries: https://github.com/citusdata/citus/pull/4360     And, some recursive #4255
2. I know you added few, but `ref LEFT JOIN dist` in the sub-select part of INSERT .. SELECT. Some tests from #6512.
3. Some edge case tests that we do not support from #4255
4. Some queries from this subquery pushdown improvement as INSEET .. SELECT #4355
5. Local table dist table joins: #4358
6. Views / Mat views in the INSERT .. SELECT

**Review by onderkalaci — COMMENTED** [review]
This is mostly in a good shape, with some minor comments. And, very important improvement!

However, this also changes a very critical code-path. Do you mind spending a little more time adding tests? The idea is that we expanded subquery pushdown logic a lot in the past, and probably do not have any tests/coverage for INSERT .. SELECT pieces of the equivalent queries as they went over completely different code-paths.

Test suggestions:
1. Some tests with colocated sublinks in the target-list with INSERT .. SELECT queries: https://github.com/citusdata/citus/pull/4360     And, some recursive #4255
2. I know you added few, but `ref LEFT JOIN dist` in the sub-select part of INSERT .. SELECT. Some tests from #6512.
3. Some edge case tests that we do not support from #4255
4. Some queries from this subquery pushdown improvement as INSEET .. SELECT #4355
5. Local table dist table joins: #4358
6. Views / Mat views in the INSERT .. SELECT

**Review by onderkalaci — COMMENTED** [review]
This is mostly in a good shape, with some minor comments. And, very important improvement!

However, this also changes a very critical code-path. Do you mind spending a little more time adding tests? The idea is that we expanded subquery pushdown logic a lot in the past, and probably do not have any tests/coverage for INSERT .. SELECT pieces of the equivalent queries as they went over completely different code-paths.

Test suggestions:
1. Some tests with colocated sublinks in the target-list with INSERT .. SELECT queries: https://github.com/citusdata/citus/pull/4360     And, some recursive #4255
2. I know you added few, but `ref LEFT JOIN dist` in the sub-select part of INSERT .. SELECT. Some tests from #6512.
3. Some edge case tests that we do not support from #4255
4. Some queries from this subquery pushdown improvement as INSEET .. SELECT #4355
5. Local table dist table joins: #4358
6. Views / Mat views in the INSERT .. SELECT

**Review by onderkalaci — COMMENTED** [review]
This is mostly in a good shape, with some minor comments. And, very important improvement!

However, this also changes a very critical code-path. Do you mind spending a little more time adding tests? The idea is that we expanded subquery pushdown logic a lot in the past, and probably do not have any tests/coverage for INSERT .. SELECT pieces of the equivalent queries as they went over completely different code-paths.

Test suggestions:
1. Some tests with colocated sublinks in the target-list with INSERT .. SELECT queries: https://github.com/citusdata/citus/pull/4360     And, some recursive #4255
2. I know you added few, but `ref LEFT JOIN dist` in the sub-select part of INSERT .. SELECT. Some tests from #6512.
3. Some edge case tests that we do not support from #4255
4. Some queries from this subquery pushdown improvement as INSEET .. SELECT #4355
5. Local table dist table joins: #4358
6. Views / Mat views in the INSERT .. SELECT

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 14]
```diff
@@ -1960,13 +1962,43 @@ AllDistributedRelationsInRTEListColocated(List *rangeTableEntryList)
...
+
+
 /*
  * AllDistributedRelationsInListColocated determines whether all of the
  * distributed relations in the given list are co-located.
  */
 bool
 AllDistributedRelationsInListColocated(List *relationList)
 {
+	if (AllRelationsSame(relationList))
```
[the remark this answers is not in the document]
Comment (aykut-bozkurt) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:1997]: Yes, one isolation test like below failed
```sql
INSERT append_t1 INTO select * from append_t1;
```

Then, it makes sense to me to get rid of the check and disable INSERT SELECT pushdown for append tables.

File: src/test/regress/expected/multi_insert_select.out [hunk 15]
```diff
@@ -3242,5 +3242,209 @@ returning text_col_1;
...
+dist_col bigint,
+int_col integer
+);
+SELECT create_distributed_table('dist_table_3', 'dist_col');
+ create_distributed_table
+---------------------------------------------------------------------
+
+(1 row)
+
+-- dist_table_2 and dist_table_3 are non-colocated source tables. Pulling the SELECT part to coordinator is also not possible.
```
Comment (onderkalaci) [inline src/test/regress/expected/multi_insert_select.out:3255]: improve comment, the below is also similar but that works. what is the difference? Different data types cannot be repartitioned, this is more than non-colocated. Strictly non-colocated :)

**Review by onderkalaci — COMMENTED** [review]
Can you also test a little bit https://github.com/citusdata/citus/issues/3156? This should also be fixed.

**Comment by aykut-bozkurt** [comment]
> Can you also test a little bit #3156? This should also be fixed.

We still pull cte to coordinator due to `errorDetail = "CTEs in subqueries are currently unsupported` at `DeferErrorIfUnsupportedTableCombination` in pushdown checks. Then, after inlining the cte, router planner can handle the SELECT part of the query (pulled to coordinator). We could have pushed down the query if we try inlining cte before pushdown `INSERT SELECT` planner.

**Comment by onderkalaci** [comment]
> We still pull cte to coordinator due to errorDetail = "CTEs in subqueries are currently unsupported at DeferErrorIfUnsupportedTableCombination in pushdown checks. Then, after inlining the cte, router planner can handle the SELECT part of the query (pulled to coordinator). We could have pushed down the query if we try inlining cte before pushdown  INSERT SELECT planner.
Still added a test to point out that incapability of INSERT SELECT pushdown planner.

I guess due to: https://github.com/citusdata/citus/issues/6920

But, these should be fine where CTE is part of the SELECT:
```SQL
 insert into dist_table_5 WITH cte_1 AS (SELECT id FROM dist_table_5 JOIN ref ON (id = a) GROUP BY id)  SELECT id FROM dist_table_5 JOIN cte_1 USING(id);
```

Can you add some tests for that? Also, can you rebase and fix the conflicts? Otherwise, looks good

**Review by onderkalaci — APPROVED** [review]
