### PR TITLE
Fix ADD {PRIMARY KEY/UNIQUE} USING INDEX command

### LINKED ISSUE #6644: Issues in adding nameless constraints using existing index
We shouldn't treat nameless constraints using existing index as "nameless" because the name of the existing index will be used.

Even if we do treat them as nameless, our deparser currently doesn't include "USING INDEX index_name" when deparsing unique/primary key constraints

Steps to reproduce:
```SQL
create table tbl (col1 int, col2 int);
select create_distributed_table('tbl', 'col1');
create unique index my_index on tbl(col1);
alter table tbl add primary key using index my_index;
```

Error:
```
alter table tbl add primary key using index my_index;
NOTICE:  ALTER TABLE / ADD CONSTRAINT USING INDEX will rename index "my_index" to "tbl_pkey"
ERROR:  syntax error at or near ")"
CONTEXT:  while executing command on localhost:9701
```

### PR DESCRIPTION
**Pull request by emelsimsek**
This change allows creating a constraint without a name using an index. The index name will be used as the constraint name the same way postgres handles it.

I am not adding a description since this is a pre-release PR and should not be in changelog.

Fixes #6644

### CODE REVIEW

File: src/backend/distributed/commands/table.c [hunk 1]
```diff
@@ -1269,7 +1269,11 @@ PreprocessAlterTableStmt(Node *node, const char *alterTableCommand,
 															 constraint);
 				}
 			}
-			else if (constraint->conname == NULL)
+			/*
+			 * When constraint->indexname is not NULL we are handling an ADD {PRIMARY KEY, UNIQUE} USING INDEX command. In this case
+			 * we do not have to create a name and change the command. The index name will be used by the postgres.
```
Comment (naisila) [inline src/backend/distributed/commands/table.c:1274]: Shorter comment lines

File: src/backend/distributed/relay/relay_event_utility.c [hunk 2]
```diff
@@ -150,6 +150,7 @@ RelayEventExtendNames(Node *parseTree, char *schemaName, uint64 shardId)
 				if (command->subtype == AT_AddConstraint)
 				{
 					Constraint *constraint = (Constraint *) command->def;
+
```
Comment (naisila) [inline src/backend/distributed/relay/relay_event_utility.c:153]: remove this new line

**Review by naisila — COMMENTED** [review]
Should extend assert to include indexname == NULL as well
`Assert(constraint->conname == NULL)`

**Review by naisila — COMMENTED** [review]
Not fully related to this PR but I was checking if we need to add (indexname == NULL) condition when we error out in nameless constraints, and I realized we can't error out anymore, so we should remove the following block:
```C
/*
 * We will use constraint name in each placement by extending it at
 * workers. Therefore we require it to be exist.
 */
if (constraint->conname == NULL)
{
	/*
	 * We support ALTER TABLE ... ADD PRIMARY ... commands by creating a constraint name
	 * and changing the command into the following form.
	 * ALTER TABLE ... ADD CONSTRAINT <constaint_name> PRIMARY KEY ...
	 */
	if (ConstrTypeCitusCanDefaultName(constraint->contype) == false)
	{
		ereport(ERROR, (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
						errmsg(
							"cannot create constraint without a name on a "
							"distributed table")));
	}
}
```

**Review by marcocitus — APPROVED** [review]
Looks good.

I also briefly looked into what happens if a constraint with the name of the index already exists. Seems Postgres gives a quite low-level error:
```
create unique index my_index3 on test (x);
alter table test add constraint my_index3 check ((x > 0));
alter table test add unique using index my_index3;
ERROR:  duplicate key value violates unique constraint "pg_constraint_conrelid_contypid_conname_index"
DETAIL:  Key (conrelid, contypid, conname)=(447688, 0, my_index3) already exists.
```
could be nice to add a test for it

**Comment by naisila** [comment]
> Looks good.
> 
> I also briefly looked into what happens if a constraint with the name of the index already exists. Seems Postgres gives a quite low-level error:
> 
> ```
> create unique index my_index3 on test (x);
> alter table test add constraint my_index3 check ((x > 0));
> alter table test add unique using index my_index3;
> ERROR:  duplicate key value violates unique constraint "pg_constraint_conrelid_contypid_conname_index"
> DETAIL:  Key (conrelid, contypid, conname)=(447688, 0, my_index3) already exists.
> ```
> 
> could be nice to add a test for it

That error that is out of scope for this PR because it's not something related to nameless constraints that use existing index. The same error appears with the following command as well: `alter table test add constraint my_index3 unique using index my_index3;` And also it's a PG level error. Maybe I missed your point but I don't see why that test could be included in this PR.
