### PR TITLE
Discard index deletion requests made to columnarAM

### LINKED ISSUE #5326: Unique index + ROLLBACK cause persistent ERRORs on columnar
```SQL
select version(), citus_version();
-[ RECORD 1 ]-+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
version       | PostgreSQL 14rc1 on x86_64-apple-darwin20.6.0, compiled by Apple clang version 12.0.5 (clang-1205.0.22.11), 64-bit
citus_version | Citus 10.2devel on x86_64-apple-darwin20.6.0, compiled by Apple clang version 12.0.5 (clang-1205.0.22.11), 64-bit gitref: add_more_columnar_upgrade_tests(sha: c9fa020c3)


```

The following steps gets columnar into a state where any data ingestion throws an error. The problem is that even if I restart the server, the error persists. The only way to avoid the error is to `TRUNCATE` or `DROP` the table.

I can reproduce this with UNIQUE INDEX or PRIMARY KEY or UNIQUE CONSTRAINT.

```SQL
CREATE TABLE test (a int) USING COLUMNAR;
CREATE UNIQUE INDEX i1 ON test(a);

BEGIN;
    SAVEPOINT s1;
     INSERT INTO test SELECT i FROM generate_series(0,10000)i;
   ROLLBACK TO SAVEPOINT s1;

     INSERT INTO test SELECT i FROM generate_series(0,10000)i;
     ERROR:  columnar_index_delete_tuples not implemented

ROLLBACK;

-- after we get into this state, any INSERT fails
INSERT INTO test VALUES (1);
ERROR:  columnar_index_delete_tuples not implemented

INSERT INTO test SELECT i FROM generate_series(0,10000)i;
ERROR:  columnar_index_delete_tuples not implemented

COPY test FROM STDIN;
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself, or an EOF signal.
>> 1
>> 2
>> \.
ERROR:  columnar_index_delete_tuples not implemented
CONTEXT:  COPY test, line 1
Time: 2047.673 ms (00:02.048)

```

### PR DESCRIPTION
**Pull request by onurctirtir**
(Will test a bit more and ask for reviews)

TODO: 
- [x] add tests with copy too

----

Fixes #5326 

A write operation might trigger index deletion if index already had
dead entries for the key we are about to insert.
There are two ways of index deletion:
  a) simple deletion
  b) bottom-up deletion (>= pg14)

Since columnar_index_fetch_tuple never sets all_dead to true,
columnarAM doesn't ever expect to receive simple deletion requests
(columnar_index_delete_tuples) as we don't mark any index entries
as dead.

However, since columnarAM doesn't delete any dead entries via simple
deletion, postgres might ask for a more comprehensive deletion
(i.e.: bottom-up) at some point when pg >= 14.

So with this commit, we start gracefully ignoring bottom-up deletion
requests made to columnar_index_delete_tuples.

Given that users can anyway "VACUUM FULL" their columnar tables,
we don't see any problem in ignoring deletion requests.

DESCRIPTION: Fixes an unexpected error that occurs due to aborted writes to a columnar table with an index

### CODE REVIEW

File: src/backend/columnar/columnar_tableam.c [hunk 1]
```diff
@@ -655,7 +658,46 @@ static TransactionId
...
+	 * reason for that, just to keep things simple.
+	 *
+	 * See the rest of this function to see how we deal with
+	 * index_delete_tuples requests made to columnarAM.
+	 */
+
+	if (delstate->bottomup)
+	{
+		/*
+		 * Ignore any deletion bottom-up deletion requests.
```
Comment (onurctirtir) [inline src/backend/columnar/columnar_tableam.c:675]:
```suggestion
		 * Ignore any bottom-up deletion requests.
```

File: src/backend/columnar/columnar_tableam.c [hunk 2]
```diff
@@ -655,7 +658,46 @@ static TransactionId
...
+		 * for bottom-up deletion.
+		 */
+		delstate->ndeltids = 0;
+		return InvalidTransactionId;
+	}
+	else
+	{
+		/*
+		 * TableAM is not expected to set ndeltids to 0 for simple deletion
+		 * case so we cannot do what we do for bottomup case.
```
Comment (onurctirtir) [inline src/backend/columnar/columnar_tableam.c:689]:
```suggestion
		 * case, so here we cannot do the same trick that we do for
		 * bottom-up deletion.
```

File: src/backend/columnar/columnar_tableam.c [hunk 3]
```diff
@@ -655,7 +658,46 @@ static TransactionId
...
+		 * See the assertion around table_index_delete_tuples call in pg
+		 * function index_compute_xid_horizon_for_tuples.
+		 *
+		 * For this reason, not to encounter with simple deletion case for
+		 * columnar tables (bottomup = false), columnar_index_fetch_tuple
+		 * doesn't ever set all_dead to true in order to prevent triggering
+		 * simple deletion of index tuples. But let's throw an error to be on
+		 * the safe side.
```
Comment (onurctirtir) [inline src/backend/columnar/columnar_tableam.c:697]:
```suggestion
		 * For this reason, to avoid receiving simple deletion requests for
		 * columnar tables (bottomup = false), columnar_index_fetch_tuple
		 * doesn't ever set all_dead to true in order to prevent triggering
		 * simple deletion of index tuples. But let's throw an error to be on
		 * the safe side.
```

**Review by jeff-davis — APPROVED** [review]

**Comment by onurctirtir** [comment]
(backported to 10.2)
