### PR TITLE
DROP EXTENSION without any warnings

### LINKED ISSUE #200: Remove WARNING after dropping the extension in the same session
<a href="https://github.com/onderkalaci"></img></a> **Issue by [onderkalaci](https://github.com/onderkalaci)**
_Friday Dec 11, 2015 at 09:11 GMT_
_Originally opened as https://github.com/citusdata/citusdb-private/issues/52_

----

This seems to be a pretty minor bug, but I am noting here.

We get an error after dropping the extension until the user reconnects to the server.

 All the steps should be executed in the same session. Here are the steps to reproduce the bug:
* `create extension citusdb`
* `create table test(a int)`
* `select master_create_distributed_table('test', 'a', 'hash')`
* `select master_create_worker_shards('test', 4, 1)`
* some queries on the `test` (or skip this step)
* `drop extension citusdb CASCADE`
* At the step, execute `\d`, you get an error such as: `ERROR:  could not open relation with OID 350391`. Note that this OID does not belong to the `test` table.
* If the user re-connects to the server, the error is gone.

### LINKED ISSUE #367: Confusing WARNING message on DROP EXTENSION citus
```
postgres=# drop extension citus ;
WARNING:  could not clean the metadata cache on DROP EXTENSION command
HINT:  Reconnect to the server again.
ERROR:  cannot drop extension citus because other objects depend on it
DETAIL:  table github_events depends on extension citus
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```

In this case, even if the extension isn't dropped, we ask the user to reconnect. This causes a confusion as to the cause of the problem is. People familiar with Postgres might understand why they're seeing the `ERROR` message (dependency on the tables), others might not.

Also, the error message

```
WARNING:  could not clean the metadata cache on DROP EXTENSION command
HINT:  Reconnect to the server again.
```

might not be very understandable to new users. We were chatting with @begriffs and he mentioned that he didn't understand what the metadata cache is and why it couldn't be cleaned up.

### PR DESCRIPTION
**Pull request by lithp**
fixes #367 
Also fixes #200

Not quite ready for review, there are some big issues with this PR that maybe @anarazel can help me resolve. 

**1**

The approach I used is to make sure the oid of `pg_dist_shard_placement` is cached. Every time it is invalidated I call `get_relname_relid` to see if it still exists, and if it doesn't I wipe all state.

`get_relname_relid` must be called inside a transaction though (or else an assertion in `cache/catcache:SearchCatCache` will fail), which makes the code a little more complicated. Is there another method I can call?

**2**

From my position of ignorance this seems super fragile. 

If you call `CREATE EXTENSION` and immediately follow it with `DROP EXTENSION` the invalidate callback is never called. That's fine because we also never cached anything. But I can't figure out in what situations it is called. `extensionLoaded` is set whenever `IsDistributedTable` is called, and if any of those places don't also cause the invalidate callback to be later called this code will break.

What causes postgres to start sending invalidation callbacks for our tables?

**Misc adtl issues for myself**

- Do we also need to reset `DistPartitionScanKey` and `DistShardScanKey`?

### CODE REVIEW

File: src/backend/distributed/utils/metadata_cache.c [hunk 1]
```diff
@@ -339,10 +365,12 @@ CitusHasBeenLoaded(void)
 Oid
 DistShardRelationId(void)
 {
-	static Oid cachedOid = InvalidOid;
+	Oid cachedOid = metadataCacheState.distShardRelationId;
```
Comment (lithp) [inline src/backend/distributed/utils/metadata_cache.c]: Onder pulled this up in code review for my compressed_fdw.

What's the argument for this being more readable than just using the struct directly?

File: src/backend/distributed/utils/metadata_cache.c [hunk 2]
```diff
@@ -677,6 +722,32 @@ InvalidateDistRelationCacheCallback(Datum argument, Oid relationId)
...
+		return;
+	}
+
+	shardPlacementId = DistShardPlacementRelationId();
+
+	elog(WARNING,"Invalidate rel: %d target: %d", relationId, shardPlacementId);
+
+	if (relationId != InvalidOid && relationId == shardPlacementId)
+	{
+		shardPlacementId = get_relname_relid("pg_dist_shard_placement",
```
Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: Invalidation events seem rare enough that we could just drop the cache if there is an invalidation event on a metadata table. I tried checking relationId == metadataCacheState.distPartitionRelationId and it seems that the only place where we get an invalidation message for pg_dist_partition in the regression tests is when we create and drop the extension.

File: src/backend/distributed/utils/metadata_cache.c [hunk 3]
```diff
@@ -677,6 +722,32 @@ InvalidateDistRelationCacheCallback(Datum argument, Oid relationId)
 			cacheEntry->isValid = false;
 		}
 	}
+
+	/* now check whether we're in the middle of dropping the extension */
```
Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: We should also invalidate the cache entries.

File: src/backend/distributed/utils/metadata_cache.c [hunk 4]
```diff
@@ -677,6 +722,32 @@ InvalidateDistRelationCacheCallback(Datum argument, Oid relationId)
...
+
+	/* if we're not in a transaction then we'll crash while looking up oids */
+	inTransaction = IsTransactionState();
+	if (!inTransaction)
+	{
+		return;
```
Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: Right now, this means that there's no invalidation, right?

File: src/backend/distributed/utils/metadata_cache.c [hunk 5]
```diff
@@ -677,6 +722,32 @@ InvalidateDistRelationCacheCallback(Datum argument, Oid relationId)
...
+	if (relationId != InvalidOid && relationId == shardPlacementId)
+	{
+		shardPlacementId = get_relname_relid("pg_dist_shard_placement",
+											 PG_CATALOG_NAMESPACE);
+		if (shardPlacementId == InvalidOid)
+		{
+			/* The extension is being dropped, we should drop our state too */
+			elog(WARNING,"Dropping all metadata_cache state");
+
+			memset(&metadataCacheState, 0, sizeof(MetadataCacheState));
```
Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: I'd be slightly in favour of explicitly assigning InvalidOid values. The fact that all the default values happen to be equal to 0 is rather arbitrary.

File: src/backend/distributed/utils/metadata_cache.c (hunk 1 above)
Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: Why use a struct?

**Comment by marcocitus** [comment]
Some comments got hidden because I commented on an outdated diff, but I think they still apply.

File: src/backend/distributed/utils/metadata_cache.c (hunk 1 above)
Comment (lithp) [inline src/backend/distributed/utils/metadata_cache.c]: Honestly it just looks nicer, I like the semantics of "this is all the state which needs to be cleared" which I can use to just `memset` the whole thing later.

File: src/backend/distributed/utils/metadata_cache.c (hunk 3 above)
Comment (lithp) [inline src/backend/distributed/utils/metadata_cache.c]: They're already invalidated, the existing code in `InvalidateDistRelationCacheCallback` takes care of that.

File: src/backend/distributed/utils/metadata_cache.c (hunk 4 above)
Comment (lithp) [inline src/backend/distributed/utils/metadata_cache.c]: For those calls that means there's no invalidation. This is very handwavey but in every situation I tried pg_dist_shard_partition is invalidated at least once from within a transaction during the DROP.

File: src/backend/distributed/utils/metadata_cache.c (hunk 5 above)
Comment (lithp) [inline src/backend/distributed/utils/metadata_cache.c]: It's true. I wouldn't ever use this line as an argument to avoid adding a field to the struct which doesn't have an initial value represented as 0, but for now it's pretty convenient and I think simpler.

Actually, this means grepping for `extensionLoaded`, for instance, will miss this access. That's probably reason enough to be more explicit.

File: src/backend/distributed/utils/metadata_cache.c (hunk 1 above)
Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: The usual pattern in postgres/citus is to use static variables (e.g. with a common prefix). We'd like our code to use consistent patterns when possible. It also saves you from requiring separate declaration and initialisation at the top.

File: src/backend/distributed/utils/metadata_cache.c (hunk 4 above)
Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: Ah, makes sense, it is called for each of the distributed tables when they are dropped.

File: src/backend/distributed/utils/metadata_cache.c [hunk 6]
```diff
@@ -677,6 +722,32 @@ InvalidateDistRelationCacheCallback(Datum argument, Oid relationId)
...
+	if (!inTransaction)
+	{
+		return;
+	}
+
+	shardPlacementId = DistShardPlacementRelationId();
+
+	elog(WARNING,"Invalidate rel: %d target: %d", relationId, shardPlacementId);
+
+	if (relationId != InvalidOid && relationId == shardPlacementId)
```
Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: I think this could be moved into an if-else block above.

**Comment by lithp** [comment]
@marcocitus I appreciate the review. Is there any chance you have answers to the questions I asked in the PR description? Most importantly, what kinds of things cause invalidation events to be sent? Why does removing the table only sometimes trigger our callback?

**Comment by marcocitus** [comment]
@lithp You could do a quick:
grep -r CacheInvalidateRelcache postgresql-9.5.2/src/

Mainly DDL events on the table (add trigger, drop index, etc.).

> If you call CREATE EXTENSION and immediately follow it with DROP EXTENSION the invalidate callback is never called. That's fine because we also never cached anything. But I can't figure out in what situations it is called. 

In this case, InitializeDistTableCache is never called because we don't go through the planner/executor and we don't call it from the process utility hook for create/drop extension. If InitializeDistTableCache isn't called, the invalidation handler is never registered, so never gets called.

**Comment by lithp** [comment]
> In this case, InitializeDistTableCache is never called because we don't go through the planner/executor and we don't call it from the process utility hook for create/drop extension. If InitializeDistTableCache isn't called, the invalidation handler is never registered, so never gets called.

Oh, good point. That was dumb.

Okay, that makes things easier. If we can make sure that every code path which sets some state also installs that hook we're golden. That sounds way less brittle, it only involves code local to this file.

File: src/backend/distributed/utils/metadata_cache.c (hunk 1 above)
Comment (lithp) [inline src/backend/distributed/utils/metadata_cache.c]: Okay, I'll add a commit which removes the struct. Should these functions still create a local variable , or are we okay with having the functions just read and write from their respective globals?

Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: Using the globals directly seems fine.

File: src/backend/distributed/utils/metadata_cache.c [hunk 7]
```diff
@@ -677,6 +676,48 @@ InvalidateDistRelationCacheCallback(Datum argument, Oid relationId)
...
+	/*
+	 * if we're not in a transaction then we'll crash while looking up oids
+	 */
+	inTransaction = IsTransactionState();
+	if (!inTransaction)
+	{
+		return;
+	}
+
+	shardPlacementId = DistShardPlacementRelationId();
```
Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: Can we use distShardPlacementRelationId here?

Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: or instead of shardPlacementId

File: src/backend/distributed/utils/metadata_cache.c [hunk 8]
```diff
@@ -34,6 +34,19 @@
 #include "utils/relmapper.h"
 #include "utils/syscache.h"
 
+#include "access/xact.h"
+
+
+/* state which should be cleared upon DROP EXTENSION */
```
Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: We should add a note that these shouldn't be accessed directly. Instead, the relevant functions should be called.

File: src/backend/distributed/utils/metadata_cache.c [hunk 9]
```diff
@@ -34,6 +34,19 @@
...
+static bool extensionLoaded = false;
+static Oid distShardRelationId = InvalidOid;
+static Oid distShardPlacementRelationId = InvalidOid;
+static Oid distPartitionRelationId = InvalidOid;
+static Oid distPartitionLogicalRelidIndexId = InvalidOid;
+static Oid distShardLogicalRelidIndexId = InvalidOid;
+static Oid distShardShardidIndexId = InvalidOid;
+static Oid distShardPlacementShardidIndexId = InvalidOid;
```
Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: Maybe give them a prefix like cachedDistShardRelationId to make the purpose more clear and distinguish from the function names.

Comment (anarazel) [inline src/backend/distributed/utils/metadata_cache.c]: On 2016-04-19 04:33:02 -0700, Marco Slot wrote:
> > @@ -34,6 +34,19 @@
> >  #include "utils/relmapper.h"
> >  #include "utils/syscache.h"
> >  
> > +#include "access/xact.h"
> > +
> > +
> > +/* state which should be cleared upon DROP EXTENSION */
> > +static bool extensionLoaded = false;
> > +static Oid distShardRelationId = InvalidOid;
> > +static Oid distShardPlacementRelationId = InvalidOid;
> > +static Oid distPartitionRelationId = InvalidOid;
> > +static Oid distPartitionLogicalRelidIndexId = InvalidOid;
> > +static Oid distShardLogicalRelidIndexId = InvalidOid;
> > +static Oid distShardShardidIndexId = InvalidOid;
> > +static Oid distShardPlacementShardidIndexId = InvalidOid;
> 
> Maybe give them a prefix like cachedDistShardRelationId to make the purpose more clear and distinguish from the function names.

I think I prefer Brian's approach of putting them into one struct that
can be zeroed with memset.  I didn't understand the argument against
that?

Andres

File: src/backend/distributed/utils/metadata_cache.c (hunk 7 above)
Comment (anarazel) [inline src/backend/distributed/utils/metadata_cache.c]: Seconded. It'd be much better to not have that transaction state test.

File: src/backend/distributed/utils/metadata_cache.c (hunk 9 above)
Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: Cons of struct is needing a separate declaration, long struct+variable names, introducing a style that doesn't appear elsewhere in the code, relying on defaults being 0 which seems arbitrary. Pros are being able to clear the cache in one line and making it easier to add new cached variables if they're 0 by default. To me the cons slightly outweigh the pros, but will let Brian make the call.

File: src/backend/distributed/utils/metadata_cache.c (hunk 8 above)
Comment (lithp) [inline src/backend/distributed/utils/metadata_cache.c]: I think that's not necessary since they're `static`?

**Comment by lithp** [comment]
@marcocitus Okay, got rid of the transaction checking by dropping whenever pg_dist_partition is invalidated. Did some manual testing and this seems to work.

I think prepending "cached" to the variable names makes them dreadfully long for not much additional benefit, not only are they part of the metadata_cache any variable which holds an oid is a cache.

**Comment by lithp** [comment]
@marcocitus Just a friendly ping :)

File: src/backend/distributed/utils/metadata_cache.c [hunk 10]
```diff
@@ -677,6 +678,25 @@ InvalidateDistRelationCacheCallback(Datum argument, Oid relationId)
...
+
+	/*
+	 * If pg_dist_partition is being invalidated drop all state
+	 * This happens pretty rarely, but most importantly happens during
+	 * DROP EXTENSION citus;
+	 */
+
+	if (relationId != InvalidOid && relationId == distPartitionRelationId)
+	{
+			extensionLoaded = false;
```
Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: There seems to be an extra tab here.

File: src/backend/distributed/utils/metadata_cache.c [hunk 11]
```diff
@@ -677,6 +678,25 @@ InvalidateDistRelationCacheCallback(Datum argument, Oid relationId)
 			cacheEntry->isValid = false;
 		}
 	}
+
+	/*
+	 * If pg_dist_partition is being invalidated drop all state
+	 * This happens pretty rarely, but most importantly happens during
+	 * DROP EXTENSION citus;
+	 */
+
```
Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: Maybe remove this line

File: src/backend/distributed/utils/metadata_cache.c [hunk 12]
```diff
@@ -677,6 +678,25 @@ InvalidateDistRelationCacheCallback(Datum argument, Oid relationId)
...
+	if (relationId != InvalidOid && relationId == distPartitionRelationId)
```
Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: Why not move this into the if-else block above?

    if (relationId == InvalidOid)
    ...
    else if (relationId == distPartitionRelationId)
    ...
    else

File: src/backend/distributed/utils/metadata_cache.c [hunk 13]
```diff
@@ -329,6 +335,12 @@ CitusHasBeenLoaded(void)
 		}
 
 		extensionLoaded = extensionPresent && extensionScriptExecuted;
+
+		if (extensionLoaded)
+		{
+			/* Cache pg_dist_partition's id so we can look for it to be invalidated */
+			DistPartitionRelationId();
```
Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: Do we need this?

**Comment by marcocitus** [comment]
Sorry about the delay!

File: src/backend/distributed/utils/metadata_cache.c (hunk 11 above)
Comment (lithp) [inline src/backend/distributed/utils/metadata_cache.c]: Remove the whole comment?

Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: No, just the extra whitespace, the comment is very useful :)

File: src/backend/distributed/utils/metadata_cache.c (hunk 12 above)
Comment (lithp) [inline src/backend/distributed/utils/metadata_cache.c]: I like the separation, this method has two sections and each has a different responsibility.

Also, if relationId is simply not null we want to invalidate the cache entry. If relationId is not null and also distPartitionRelationID we want to both invalidate the cache entry and drop the rest of the state. I think expressing that is cleaner with two if blocks.

File: src/backend/distributed/utils/metadata_cache.c (hunk 10 above)
Comment (lithp) [inline src/backend/distributed/utils/metadata_cache.c]: oops :/

File: src/backend/distributed/utils/metadata_cache.c (hunk 13 above)
Comment (lithp) [inline src/backend/distributed/utils/metadata_cache.c]: I believe not but it feels less brittle if this is left in.

It's important that `CitusHasBeenLoaded` is called with some method which calls `DistPartitionRelationId` because `Citus...Loaded` sets extensionLoaded, which must be cleared during a `DROP EXTENSION`. If `Dist...Id` is not called, then we will never notice `pg_dist_partition` is being dropped and never reset `extensionLoaded`.

It turns out that `Dist...Id` is indirectly called by all methods which also call `CitusHasBeenLoaded`, but there's nothing which enforces that. Considering breaking this assumption will result in subtle problems much later instead of crashes, I think it's important to spend some lines to not rely on our callers doing the right thing.

File: src/backend/distributed/utils/metadata_cache.c (hunk 10 above)
Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: Just do the lazy thing and run make reindent ;)

**Comment by lithp** [comment]
No problem with the delay, you're busy!

Just pushed better indentation and removed the extra empty line.

File: src/backend/distributed/utils/metadata_cache.c (hunk 12 above)
Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: Fair. 

btw, if there is a cache entry for pg_dist_partition, you have much bigger problems :)

File: src/backend/distributed/utils/metadata_cache.c (hunk 13 above)
Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: That's fine, this will help future callers. Maybe expand the comment a bit to clarify.

Minor: one-line comments should be lower-case.

File: src/backend/distributed/utils/metadata_cache.c [hunk 14]
```diff
@@ -339,102 +351,91 @@ CitusHasBeenLoaded(void)
...
-	return cachedOid;
+	return distPartitionRelationId;
 }
 
 
 /* return oid of pg_dist_partition_logical_relid_index index */
 Oid
 DistPartitionLogicalRelidIndexId(void)
 {
-	static Oid cachedOid = InvalidOid;
```
Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: Running make reindent removes this extra line.

File: src/test/regress/expected/multi_table_ddl.out [hunk 15]
```diff
@@ -66,7 +64,5 @@ SELECT * FROM pg_dist_shard_placement;
 -- before creating the extension to expire extension specific variables which
 -- are cached for performance.
```
Comment (marcocitus) [inline src/test/regress/expected/multi_table_ddl.out]: We should be able to remove the reconnect now, and do some basic test (create distributed table, do a query)

**Comment by lithp** [comment]
@marcocitus Line has been removed, comment has been improved, and tests have been changed.

File: src/test/regress/expected/multi_table_ddl.out [hunk 16]
```diff
@@ -62,11 +60,20 @@ SELECT * FROM pg_dist_shard_placement;
...
 CREATE EXTENSION citus;
+-- verify that a table can be created after the extension has been dropped and recreated
+CREATE TABLE testtableddl(somecol int, distributecol text NOT NULL);
+SELECT master_create_distributed_table('testtableddl', 'distributecol', 'append');
+ master_create_distributed_table 
+---------------------------------
+ 
+(1 row)
+
+SELECT * FROM testtableddl;
```
Comment (marcocitus) [inline src/test/regress/expected/multi_table_ddl.out]: We probably also want to create shards, just to make sure that pg_dist_shard_placement is invalidated.

**Comment by marcocitus** [comment]
Pending squash and addressing 1 comment: 🚢

File: src/test/regress/expected/multi_table_ddl.out (hunk 16 above)
Comment (lithp) [inline src/test/regress/expected/multi_table_ddl.out]: So, yeeeees, and I'll do it if you push back, but this is one of the very first tests and incrementing the shardid on every following test isn't very fun. The tests do later end up creating shards and invalidating pg...placement.

Comment (marcocitus) [inline src/test/regress/expected/multi_table_ddl.out]: What if you create a new test for create/drop extension at the end? This seems somewhat unrelated to the other tests.

**Comment by sumedhpathak** [comment]
@lithp We good to get this checked in?

**Comment by lithp** [comment]
Oof, squashed but forgot to merge! We're better than ready to, we already have ;)

**Comment by sumedhpathak** [comment]
🍷 !
