### PR TITLE
Fix CTE column alias issue

### LINKED ISSUE #1885: Using column aliases causes warnings and errors
Citus does not support column aliases in any of its planners and gives weird warnings and errors instead.

Router:
```sql
SELECT a FROM test t(a,b) WHERE a = 1;
WARNING:  column "a" does not exist
ERROR:  could not receive query results
```

Real-time:
```
SELECT a FROM test t(a,b);
WARNING:  column "a" does not exist
WARNING:  column "a" does not exist
WARNING:  column "a" does not exist
WARNING:  column "a" does not exist
WARNING:  column "a" does not exist
WARNING:  column "a" does not exist
WARNING:  column "a" does not exist
WARNING:  column "a" does not exist
ERROR:  failed to execute task 50
```

Recursive:
```
WITH foo(a,b) AS (SELECT * FROM test) SELECT * FROM foo;
WARNING:  column "a" does not exist
ERROR:  could not receive query results
```

### PR DESCRIPTION
**Pull request by mtuncer**
We were creating intermediate query result's target names from subquery target list. Now we also check if cte re-defines its column name aliases and create intermediate result query accordingly.

Partially fixes #1885 for recursive planner (CTE)

### CODE REVIEW

File: src/backend/distributed/planner/recursive_planning.c [hunk 1]
```diff
@@ -482,13 +483,15 @@ ContainsReferencesToOuterQueryWalker(Node *node, VarLevelsUpWalkerContext *conte
...
- * The target list and column definition list are derived from the given subquery.
+ * The target list and column definition list are derived from the given subquery
+ * and the cte columm name alias list.
  *
  * If any of the types in the target list cannot be used in the binary copy format,
  * then the copy format 'text' is used, otherwise 'binary' is used.
  */
 static Query *
-BuildSubPlanResultQuery(Query *subquery, uint64 planId, uint32 subPlanId)
+BuildSubPlanResultQuery(Query *subquery, CommonTableExpr *cte, uint64 planId,
```
Comment (onderkalaci) [inline src/backend/distributed/planner/recursive_planning.c]: We're going to call this function for subqueries as well. So we'd better not to pass cte here?

Comment (onderkalaci) [reply src/backend/distributed/planner/recursive_planning.c]: Maybe pass `List *aliascolnames `?

File: src/test/regress/expected/with_basics.out [hunk 2]
```diff
@@ -220,6 +220,52 @@ JOIN
   users_table USING (user_id);
 ERROR:  cannot push down this subquery
 DETAIL:  Aggregates without group by are currently unsupported
+-- column aliases in CTE
```
Comment (onderkalaci) [inline src/test/regress/expected/with_basics.out]: Maybe also add a target list entry with expressions such as `SELECT id, id * val, val, val+2 FROM cte` ?

File: src/backend/distributed/planner/recursive_planning.c (hunk 1 above)
Comment (mtuncer) [reply src/backend/distributed/planner/recursive_planning.c]: makes sense

File: src/backend/distributed/planner/recursive_planning.c [hunk 3]
```diff
@@ -546,7 +551,16 @@ BuildSubPlanResultQuery(Query *subquery, uint64 planId, uint32 subPlanId)
 		newTargetEntry = makeNode(TargetEntry);
 		newTargetEntry->expr = (Expr *) functionColumnVar;
 		newTargetEntry->resno = columnNumber;
-		newTargetEntry->resname = columnName;
+		if (cteAliasCount >= columnNumber)
```
Comment (onderkalaci) [inline src/backend/distributed/planner/recursive_planning.c]: I cannot follow what does `if (cteAliasCount >= columnNumber)` mean.  

Did we mean `if (cteAliasCount > 0)` such that alias is provided?

Also,  `cteAliasCount` should probably not contain `cte` in the name.

File: src/test/regress/expected/with_basics.out [hunk 4]
```diff
@@ -220,6 +220,88 @@ JOIN
...
+  3 |       5
+  1 |       5
+  5 |       4
+(10 rows)
+
+-- computed targets from columns also work
+WITH top_ten(id, val, val_mul, val_sum) AS (
+	SELECT user_id, value_1, value_1*2, value_1 + value_2 FROM users_table ORDER BY value_1 DESC, user_id DESC LIMIT 10
+)
+SELECT * FROM top_ten ORDER BY id DESC, val_mul DESC;
```
Comment (onderkalaci) [inline src/test/regress/expected/with_basics.out]: I'd even to some calculations on the final target list such as `SELECT *, id+val, val_mul - 5 FROM top_ten ..` 😄 

Btw, could you please double check that the results are the same with Postgres?

File: src/backend/distributed/planner/recursive_planning.c (hunk 3 above)
Comment (mtuncer) [reply src/backend/distributed/planner/recursive_planning.c]: renamed the variable.

apparently you can write queries like
```sql
with cte(a, b) as ( select x, y, z from t) select * from cte;
```
cte defines only 2 columns even if inner query has 3. In such cases the output looks like
```sql
 a | b | z
---+---+---
```

Therefore, we only rename the column if an alias is specified, otherwise its own name is used as before.

Comment (mtuncer) [reply src/backend/distributed/planner/recursive_planning.c]: Perhaps I should write that down as a comment

Comment (onderkalaci) [reply src/backend/distributed/planner/recursive_planning.c]: > cte defines only 2 columns even if inner query has 3. 

Oh, that's crazy 😄

File: src/test/regress/expected/with_basics.out (hunk 4 above)
Comment (mtuncer) [reply src/test/regress/expected/with_basics.out]: final calculations : done,
comparison with postgres results : done

File: src/test/regress/expected/with_basics.out [hunk 5]
```diff
@@ -220,6 +220,88 @@ JOIN
   users_table USING (user_id);
 ERROR:  cannot push down this subquery
 DETAIL:  Aggregates without group by are currently unsupported
+-- column aliases in CTE
+WITH top_ten(id, val1) AS (
+	SELECT user_id, value_1 FROM users_table ORDER BY value_1 DESC, user_id DESC LIMIT 10
+)
+SELECT * FROM top_ten;
```
Comment (onderkalaci) [inline src/test/regress/expected/with_basics.out]: I wonder if we need `ORDER BY` on the top as well? What do you think? I think given that there is a single CTE, it seems fine. Feel free to ignore this comment.

Comment (mtuncer) [reply src/test/regress/expected/with_basics.out]: we have order by in another test
```sql
-- computed targets from columns and group by outside
WITH top_ten(id, val, val_mul, val_sum) AS (
	SELECT user_id, value_1, value_1*2, value_1 + value_2 FROM users_table ORDER BY value_1 DESC, user_id DESC
)
SELECT id, count(*), avg(val), max(val_mul), min(val_sum) FROM top_ten
GROUP BY id
ORDER BY 2 DESC, 1 DESC;
```

File: src/test/regress/expected/with_basics.out (hunk 2 above)
Comment (mtuncer) [reply src/test/regress/expected/with_basics.out]: added

File: src/test/regress/expected/with_basics.out (hunk 5 above)
Comment (onderkalaci) [reply src/test/regress/expected/with_basics.out]: I mean could the results be inconsistent since we skip `ORDER BY`

File: src/backend/distributed/planner/recursive_planning.c [hunk 6]
```diff
@@ -528,7 +530,7 @@ RecursivelyPlanSubquery(Query *subquery, RecursivePlanningContext *planningConte
 	subPlan = CreateDistributedSubPlan(subPlanId, subquery);
 	planningContext->subPlanList = lappend(planningContext->subPlanList, subPlan);
 
-	resultQuery = BuildSubPlanResultQuery(subquery, planId, subPlanId);
+	resultQuery = BuildSubPlanResultQuery(subquery, NIL, planId, subPlanId);
```
Comment (onderkalaci) [inline src/backend/distributed/planner/recursive_planning.c]: Maybe add a single line comment explaining why we're always passing `NIL` such as 
`/*  BuildSubPlanResultQuery() preserves the column aliases (if exists) for subqueries, thus no need to provide them for the result query */`

File: src/test/regress/sql/with_basics.sql [hunk 7]
```diff
@@ -156,6 +156,44 @@ FROM
 JOIN
   users_table USING (user_id);
 
+-- column aliases in CTE
+WITH top_ten(id, val1) AS (
```
Comment (onderkalaci) [inline src/test/regress/sql/with_basics.sql]: Well, I should have added this in #1876, but I didn't think that we could write such queries:
```SQL
 SELECT * FROM (SELECT user_id, value_1, value_2 from users_table OFFSET 0) as foo(x, y) ORDER BY 1 DESC, 2 DESC, 3 DESC LIMIT 5;
```

Would you mind adding this to `src/test/regress/sql/subquery_complex_target_list.sql` ?

File: src/backend/distributed/planner/recursive_planning.c (hunk 6 above)
Comment (mtuncer) [reply src/backend/distributed/planner/recursive_planning.c]: done

File: src/test/regress/expected/with_basics.out (hunk 5 above)
Comment (mtuncer) [reply src/test/regress/expected/with_basics.out]: it should not cause inconsistency, we have order by in inner query on all columns. Generated intermediate table should have the results in order. If that behavior changes for any reason we would know from this test

File: src/test/regress/sql/with_basics.sql (hunk 7 above)
Comment (mtuncer) [reply src/test/regress/sql/with_basics.sql]: added

Comment (mtuncer) [reply src/test/regress/sql/with_basics.sql]: done
