### PR TITLE
PG18 deparser: map Vars through JOIN aliases (fixes whole-row join column names)

### LINKED ISSUE #8278: PG18 -  invalid reference to FROM-clause entry for table "a"
```
 --- /__w/citus/citus/src/test/regress/expected/sqlancer_failures.out.modified	2025-10-17 11:52:04.721918720 +0000
+++ /__w/citus/citus/src/test/regress/results/sqlancer_failures.out.modified	2025-10-17 11:52:04.734918676 +0000
@@ -367,91 +367,76 @@
 
 -- unsupported outer JOIN in a sublevel INNER JOIN
 SELECT
  COUNT(unsupported_join.*)
 FROM
    (distributed_table a
    LEFT JOIN reference_table b ON (true)
    RIGHT JOIN reference_table c ON (true)) as unsupported_join (x,y,z,t,e,f,q)
 JOIN
    (reference_table d JOIN reference_table e ON(true)) ON (true);
- count
----------------------------------------------------------------------
-  2500
-(1 row)
-
+ERROR:  invalid reference to FROM-clause entry for table "a"
```

### PR DESCRIPTION
**Pull request by m3hm3t**
fixes #8278

Please check issue: https://github.com/citusdata/citus/issues/8278#issuecomment-3431707484

https://github.com/postgres/postgres/commit/f4e7756ef9a437f30a4dc5ded41b8824a9d291b9

### What PG18 changed

SELECT creates diff has a **named join**:

```sql
(...) AS unsupported_join (x,y,z,t,e,f,q)
```

On PG17, `COUNT(unsupported_join.*)` stayed as a single whole-row Var that referenced the **join alias**.

On PG18, the parser expands that whole-row Var **early** into a `ROW(...)` of **base** columns:

```
ROW(a.user_id, a.item_id, a.buy_count,
    b.id, b.it_name, b.k_no,
    c.id, c.it_name, c.k_no)
```

But since the join is *named*, inner aliases `a/b/c` are hidden. Referencing them later blows up with
“invalid reference to FROM-clause entry for table ‘a’”.

### What this PR changes

1. **Retarget at `RowExpr` deparse (not in `get_variable`)**

   * In `get_rule_expr()`’s `T_RowExpr` branch, each element `e` of `ROW(...)` is examined.
   * If `e` unwraps to a simple, same-level `Var` (`varlevelsup == 0`, `varattno > 0`) and there is a **named `RTE_JOIN`** with `joinaliasvars`, we **do not** change `varno/varattno`.
   * Instead, we build a copy of the Var and set **`varnosyn/varattnosyn`** to the matching join alias column (from `joinaliasvars`).
   * Then we deparse that Var via `get_rule_expr_toplevel(...)`, which naturally prints `join_alias.colname`.
   * Scope is limited to **query deparsing** (`dpns->plan == NULL`), exactly where PG18 expands whole-row vars into `ROW(...)` of base Vars.

2. **Helpers (PG18-only file)**

   * `unwrap_simple_var(Node*)`: strips trivial wrappers (`RelabelType`, `CoerceToDomain`, `CollateExpr`) to reveal a `Var`.
   * `var_matches_base(const Var*, int varno, AttrNumber attno)`: matches canonical or synonym identity.
   * `dpns_has_named_join(const deparse_namespace*)`: fast precheck for any named join with `joinaliasvars`.
   * `map_var_through_join_alias(...)`: scans `joinaliasvars` to locate the **JOIN RTE index + attno** for a 1:1 alias; the caller uses these to set `varnosyn/varattnosyn`.

3. **Safety and non-goals**

   * **No effect on plan deparsing** (`dpns->plan != NULL`).
   * **No change to semantic identity**: we leave `varno/varattno` untouched; only set `varnosyn/varattnosyn`.
   * Skip whole-row/system columns (`attno <= 0`) and non-simple join columns (computed expressions).
   * Works with named joins **with or without** an explicit column list (we rely on `joinaliasvars`, not the alias collist).

### Reproducer

```sql
CREATE TABLE distributed_table(user_id int, item_id int, buy_count int);
CREATE TABLE reference_table(id int, it_name varchar(25), k_no int);
SELECT create_distributed_table('distributed_table', 'user_id');

SELECT COUNT(unsupported_join.*)
FROM (distributed_table a
      LEFT JOIN reference_table b ON true
      RIGHT JOIN reference_table c ON true)
     AS unsupported_join (x,y,z,t,e,f,q)
JOIN (reference_table d JOIN reference_table e ON true) ON true;
```

**Before (PG18):** deparser emitted `ROW(a.user_id, …)` → `ERROR: invalid reference to FROM-clause entry for table "a"`
**After:** deparser emits
`ROW(unsupported_join.x, ..., unsupported_join.k_no)` → runs successfully.

Now maps to `unsupported_join.<auto_col_names>` and runs.

### CODE REVIEW

File: src/backend/distributed/deparser/ruleutils_18.c [hunk 1]
```diff
@@ -4315,6 +4322,22 @@ get_variable(Var *var, int levelsup, bool istoplevel, deparse_context *context)
...
+	*
+	* Guarded to avoid touching system/whole-row cols and non-join queries.
+	*/
+	if (dpns->plan == NULL &&
+		var->varlevelsup == 0 &&
+		varattno > 0 &&
+		dpns_has_named_join(dpns))
+	{
+		(void) map_var_through_join_alias(dpns, var, &varno, &varattno);
+	}
```
Comment (colm-mchugh) [inline src/backend/distributed/deparser/ruleutils_18.c]: I think this is a low-level place to make the check, as every Var node is passed through it. How about doing the check and mapping in `get_rule_expr()`'s `RowExpr` handling? That has a specific reference to whole-row vars and seems a less invasive place to check, and remap if applicable: 

```
						/* Whole-row Vars need special treatment here */
						get_rule_expr_toplevel(e, context, true);
```

File: src/backend/distributed/deparser/ruleutils_18.c [hunk 2]
```diff
@@ -4576,6 +4599,126 @@ get_variable(Var *var, int levelsup, bool istoplevel, deparse_context *context)
...
+
+            Var *aliasVar = unwrap_simple_var((Node *) lfirst(vlc));
+            if (!aliasVar)
+                continue; /* not a 1:1 alias; skip */
+
+            if (var_matches_base(aliasVar, want_varno, want_attno))
+            {
+                *p_varno = rti;
+                *p_attno = jattno;
+                return true;
```
Comment (colm-mchugh) [inline src/backend/distributed/deparser/ruleutils_18.c]: How about setting the var's `varnosyn` and `varattrnosyn` instead ? Going by their definition (from `primnodes.h` it may be appropriate. 
```
 * In the parser, varnosyn and varattnosyn are either identical to
 * varno/varattno, or they specify the column's position in an aliased JOIN
 * RTE that hides the semantic referent RTE's refname.  This is a syntactic
 * identifier as opposed to the semantic identifier; it tells ruleutils.c
 * how to print the Var properly.  varnosyn/varattnosyn retain their values
 * throughout planning and execution, so they are particularly helpful to
 * identify Vars when debugging.  Note, however, that a Var that is generated
 * in the planner and doesn't correspond to any simple relation column may
 * have varnosyn = varattnosyn = 0.
```

The reason for this suggestion is function `get_variable()` has logic for specifically handling join alias vars:
```
		/*
		 * if the rte var->varnosyn points to is not a regular table and it is a join
		 * then the correct relname will be found with var->varnosyn and var->varattnosyn
		 */
		if (rte->rtekind == RTE_JOIN && rte->relid == 0 && var->varnosyn != var->varno) {
			varno = var->varnosyn;
			varattno = var->varattnosyn;
```

So it looks like adjusting them to the JOIN alias is an appropriate use. In fact I wonder why PG18 does not do this when building the Row expression for the whole-row var in the first place, when parsing the target list (or having clause, or anywhere a whole-row var can appear). It makes me wonder if its an omission on PG18's part.

File: src/backend/distributed/deparser/ruleutils_18.c (hunk 1 above)
Comment (m3hm3t) [reply src/backend/distributed/deparser/ruleutils_18.c]: Moved the fix the location suggested, thanks.

File: src/backend/distributed/deparser/ruleutils_18.c (hunk 2 above)
Comment (m3hm3t) [reply src/backend/distributed/deparser/ruleutils_18.c]: Updated the code segment, now only set syn identity

```
	nv->varnosyn    = (Index) join_rtindex;
	nv->varattnosyn = join_attno;
```

Comment (colm-mchugh) [reply src/backend/distributed/deparser/ruleutils_18.c]: After looking into the PG planner code, setting the syn identity is the right way to go. The PG commit that triggered this test failure is [247dea89f](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=247dea89f), the one that adds support for the GROUP RTE, and specifically [this line](https://github.com/postgres/postgres/blame/master/src/backend/parser/parse_agg.c#L1276) in `parseCheckAggregates()` which has a PG18+ side-effect of replacing a whole-row join alias var with a flattened var row expr. The flattened vars do not refer to their join alias so `ruleutils` is not able to correctly deparse and we end up with this issue.

If the query is changed from `SELECT count(join_alias.*)` to `SELECT join_alias.*` then there is no problem because the var nodes in the expanded column reference do refer to the join alias, thanks to `[expandNSItemVars()](https://github.com/postgres/postgres/blob/master/src/backend/parser/parse_relation.c#L3227)`. I suspect that `flatten_join_alias_vars()` could (and maybe really should) set the syn attributes of each flattened var, so they all refer to the join alias, but that's in PG code so this is the next best thing. I will leave a few minor suggestions, but fundamentally this is the way to go.

File: src/backend/distributed/deparser/ruleutils_18.c [hunk 3]
```diff
@@ -4576,6 +4584,162 @@ get_variable(Var *var, int levelsup, bool istoplevel, deparse_context *context)
...
+	if (!map_var_through_join_alias(dpns, v, &join_rtindex, &join_attno))
+		return e;
+
+	/* Keep semantic identity; set SYN to guide printing via join alias */
+	Var *nv = makeVar(v->varno, v->varattno,
+	                  v->vartype, v->vartypmod, v->varcollid, 0);
+	nv->location = v->location;
+	nv->varreturningtype = v->varreturningtype;
+	nv->varnosyn    = (Index) join_rtindex;
+	nv->varattnosyn = join_attno;
```
Comment (colm-mchugh) [inline src/backend/distributed/deparser/ruleutils_18.c]: Can we simplify this so that `map_var_through_join_alias` sets the syn fields of the given var node directly ? So no need for join_rtindex or join_attno, and no need to construct a var node here.

File: src/backend/distributed/deparser/ruleutils_18.c [hunk 4]
```diff
@@ -4576,6 +4584,162 @@ get_variable(Var *var, int levelsup, bool istoplevel, deparse_context *context)
...
+ * and only for 1:1 aliasing (simple Var, possibly wrapped).
+ *
+ */
+static bool
+map_var_through_join_alias(deparse_namespace *dpns,
+                           const Var *orig,
+                           int *p_varno,
+                           AttrNumber *p_attno)
+{
+    if (!dpns || dpns->plan != NULL || !orig || orig->varlevelsup != 0)
```
Comment (colm-mchugh) [inline src/backend/distributed/deparser/ruleutils_18.c]: Is this check redundant ? It looks like these details are already checked by the caller (?)

File: src/backend/distributed/deparser/ruleutils_18.c [hunk 5]
```diff
@@ -4576,6 +4584,162 @@ get_variable(Var *var, int levelsup, bool istoplevel, deparse_context *context)
...
+ * return e unchanged. Only active for query deparse (dpns->plan == NULL). */
+static inline Node *
+rowelem_retarget_to_join_alias(Node *e, deparse_context *context)
+{
+	Var *v = unwrap_simple_var(e);
+	if (!v || v->varlevelsup != 0 || v->varattno <= 0 || context->namespaces == NIL)
+		return e;
+
+	deparse_namespace *dpns = (deparse_namespace *) linitial(context->namespaces);
+	if (!dpns || dpns->plan != NULL || !dpns_has_named_join(dpns))
```
Comment (colm-mchugh) [inline src/backend/distributed/deparser/ruleutils_18.c]: Can this check be hoisted to the caller ? It just needs to be made once, it looks like, and could be a gating check on calling `rowelem_retarget_to_join_alias()`

File: src/backend/distributed/deparser/ruleutils_18.c [hunk 6]
```diff
@@ -6605,8 +6769,12 @@ get_rule_expr(Node *node, deparse_context *context,
 						!TupleDescAttr(tupdesc, i)->attisdropped)
 					{
 						appendStringInfoString(buf, sep);
+
+						/* PG18: retarget inner base Vars in ROW(...) to the named JOIN alias */
+						Node *printNode = rowelem_retarget_to_join_alias(e, context);
```
Comment (colm-mchugh) [inline src/backend/distributed/deparser/ruleutils_18.c]: nit: what's the purpose of introducing a new variable here ? Can use `e` instead ?

File: src/backend/distributed/deparser/ruleutils_18.c (hunk 3 above)
Comment (m3hm3t) [reply src/backend/distributed/deparser/ruleutils_18.c]: refactored

File: src/backend/distributed/deparser/ruleutils_18.c (hunk 4 above)
Comment (m3hm3t) [reply src/backend/distributed/deparser/ruleutils_18.c]: precomputed

File: src/backend/distributed/deparser/ruleutils_18.c (hunk 5 above)
Comment (m3hm3t) [reply src/backend/distributed/deparser/ruleutils_18.c]: rowelem_retarget_to_join_alias removed

File: src/backend/distributed/deparser/ruleutils_18.c (hunk 6 above)
Comment (m3hm3t) [reply src/backend/distributed/deparser/ruleutils_18.c]: removed

File: src/backend/distributed/deparser/ruleutils_18.c [hunk 7]
```diff
@@ -4576,6 +4582,108 @@ get_variable(Var *var, int levelsup, bool istoplevel, deparse_context *context)
...
+
+/* Mutate v in place: if v maps to a named JOIN's column, set varnosyn/varattnosyn.
+ * Returns true iff SYN fields were set. Query deparse only (dpns->plan == NULL). */
+static bool
+map_var_through_join_alias(deparse_namespace *dpns, Var *v)
+{
+    if (!(dpns && v) || dpns->plan != NULL ||
+        v->varlevelsup != 0 || v->varattno <= 0 ||
+        !dpns_has_named_join(dpns))
+        return false;
```
Comment (colm-mchugh) [inline src/backend/distributed/deparser/ruleutils_18.c]: nit: can this line be removed ? These checks are made elsewhere - by the RowExpr handling code in `get_rule_expr()` mainly.

File: src/backend/distributed/deparser/ruleutils_18.c [hunk 8]
```diff
@@ -4576,6 +4582,108 @@ get_variable(Var *var, int levelsup, bool istoplevel, deparse_context *context)
...
+        AttrNumber jattno = 0;
+        ListCell *vlc;
+        foreach (vlc, jrte->joinaliasvars)
+        {
+            jattno++;
+            Var *aliasVar = unwrap_simple_var((Node *) lfirst(vlc));
+            if (!aliasVar)
+                continue;
+
+            if (var_matches_base(aliasVar, want_varno, want_attno))
```
Comment (colm-mchugh) [inline src/backend/distributed/deparser/ruleutils_18.c]:
```suggestion
            if (var_matches_base(aliasVar, v->varno, v->varattno)
```

File: src/backend/distributed/deparser/ruleutils_18.c [hunk 9]
```diff
@@ -4576,6 +4582,108 @@ get_variable(Var *var, int levelsup, bool istoplevel, deparse_context *context)
...
+static bool
+map_var_through_join_alias(deparse_namespace *dpns, Var *v)
+{
+    if (!(dpns && v) || dpns->plan != NULL ||
+        v->varlevelsup != 0 || v->varattno <= 0 ||
+        !dpns_has_named_join(dpns))
+        return false;
+
+    Index       want_varno = v->varno;
+    AttrNumber  want_attno = v->varattno;
```
Comment (colm-mchugh) [inline src/backend/distributed/deparser/ruleutils_18.c]:
```suggestion
```

File: src/backend/distributed/deparser/ruleutils_18.c [hunk 10]
```diff
@@ -6605,6 +6718,17 @@ get_rule_expr(Node *node, deparse_context *context,
...
 					{
 						appendStringInfoString(buf, sep);
+
+						/* PG18: if element is a simple base Var, set its SYN to the JOIN alias */
+						if (try_map)
+						{
+							Var *v = unwrap_simple_var(e);
+							if (v)
+							{
+								(void) map_var_through_join_alias(dpns, v);
```
Comment (colm-mchugh) [inline src/backend/distributed/deparser/ruleutils_18.c]:
```suggestion
								e =  map_var_through_join_alias(dpns, v);
```

And change `map_var_through_join_alias()` accodingly.

File: src/backend/distributed/deparser/ruleutils_18.c (hunk 7 above)
Comment (m3hm3t) [reply src/backend/distributed/deparser/ruleutils_18.c]: Added them to be safe but I will refactor as 

```
    if (!dpns || !v || dpns->plan != NULL)
        return false;

```

File: src/backend/distributed/deparser/ruleutils_18.c (hunk 8 above)
Comment (m3hm3t) [reply src/backend/distributed/deparser/ruleutils_18.c]: done

File: src/backend/distributed/deparser/ruleutils_18.c (hunk 9 above)
Comment (m3hm3t) [reply src/backend/distributed/deparser/ruleutils_18.c]: done

File: src/backend/distributed/deparser/ruleutils_18.c (hunk 10 above)
Comment (m3hm3t) [reply src/backend/distributed/deparser/ruleutils_18.c]: I am not sure that I understand the logic here.

Comment (colm-mchugh) [reply src/backend/distributed/deparser/ruleutils_18.c]: Have `map_var_through_join_alias` return the passed in Var node, instead of returning whether or not it changed the passed-in Var node. Alternatively have it return `void`, as discussed.

Comment (m3hm3t) [reply src/backend/distributed/deparser/ruleutils_18.c]: refactored to return void
