### PR TITLE
Convert postgres tables to citus local when creating reference tables having fkeys

### LINKED ISSUE #4532: No local table conversion if create_reference_table comes after foreign key creation
Foreign key creation comes first, incorrect (due to existing behaviour):
```sql
drop table if exists ref, local;
create table ref (a int primary key);
insert into ref values (1);

create table local (a int references ref (a) on delete cascade);
insert into local values (1);

select create_reference_table('ref');

-- should delete row from local
delete from ref;

select * from local;
┌───┐
│ a │
├───┤
│ 1 │
└───┘
(1 row)
```

Reference table creation comes first, correct thanks to local table conversion:
```sql
drop table if exists ref, local;
create table ref (a int primary key);
insert into ref values (1);
select create_reference_table('ref');

create table local (a int references ref (a) on delete cascade);
insert into local values (1);

-- should delete row from local
delete from ref;

select * from local;
┌───┐
│ a │
├───┤
└───┘
(0 rows)
```

### PR DESCRIPTION
**Pull request by onurctirtir**
Closes #4532

As part of #4415, we need to convert postgres tables that are chained with the table -from which we are creating a reference table- to citus local tables.

TODO:
- [x] Add more regression tests maybe

### CODE REVIEW

File: src/backend/distributed/commands/create_distributed_table.c [hunk 1]
```diff
@@ -354,15 +355,34 @@ CreateDistributedTable(Oid relationId, Var *distributionColumn, char distributio
...
+	 * we drop & re-define foreign keys at the end of this function so
+	 * that ALTER TABLE hook does the necessary job, which means converting
+	 * local tables to citus local tables to properly support such foreign
+	 * keys.
+	 */
+	else if (distributionMethod == DISTRIBUTE_BY_NONE &&
+			 ShouldEnableLocalReferenceForeignKeys() &&
+			 HasForeignKeyWithLocalTable(relationId))
+	{
+		/* store foreign key creation commands that relation is involved */
```
Comment (onurctirtir) [inline src/backend/distributed/commands/create_distributed_table.c:379]: wrong comment

File: src/backend/distributed/commands/create_distributed_table.c [hunk 2]
```diff
@@ -114,9 +114,10 @@ static void EnsureLocalTableEmptyIfNecessary(Oid relationId, char distributionMe
 static bool ShouldLocalTableBeEmpty(Oid relationId, char distributionMethod, bool
 									viaDeprecatedAPI);
 static void EnsureCitusTableCanBeCreated(Oid relationOid);
-static List * GetFKeyCreationCommandsRelationInvolved(Oid relationId);
+static List * GetFKeyCreationCommandsRelationInvolvedWithTableType(Oid relationId,
```
Comment (onurctirtir) [inline src/backend/distributed/commands/create_distributed_table.c:117]: possible to have a shorter function name ?

File: src/backend/distributed/commands/create_distributed_table.c [hunk 3]
```diff
@@ -354,15 +355,34 @@ CreateDistributedTable(Oid relationId, Var *distributionColumn, char distributio
 	 * given relation is involved, then we undistribute the relation and finally
 	 * we re-create dropped foreign keys at the end of this function.
 	 */
-	List *fKeyCreationCommandsRelationInvolved = NIL;
+	List *droppedFKeyCreationCommands = NIL;
```
Comment (marcocitus) [inline src/backend/distributed/commands/create_distributed_table.c:358]: droppedCreation commands confuses me a bit,

originalForeignKeyRecreationCommands?

File: src/backend/distributed/commands/create_distributed_table.c [hunk 4]
```diff
@@ -354,15 +355,34 @@ CreateDistributedTable(Oid relationId, Var *distributionColumn, char distributio
...
 	}
 
+	/*
+	 * To support foreign keys between reference tables and local tables,
+	 * we drop & re-define foreign keys at the end of this function so
+	 * that ALTER TABLE hook does the necessary job, which means converting
+	 * local tables to citus local tables to properly support such foreign
+	 * keys.
+	 */
+	else if (distributionMethod == DISTRIBUTE_BY_NONE &&
```
Comment (marcocitus) [inline src/backend/distributed/commands/create_distributed_table.c:375]: maybe IsCitusTableType(relationId, CITUS_REFERENCE_TABLE) just for clarity

File: src/backend/distributed/commands/foreign_constraint.c [hunk 5]
```diff
@@ -711,6 +712,38 @@ get_relation_constraint_oid_compat(HeapTuple heapTuple)
...
+{
+	int referencingFKeysFlag = INCLUDE_REFERENCING_CONSTRAINTS |
+							   INCLUDE_LOCAL_TABLES;
+	List *referencingFKeyList = GetForeignKeyOids(relationId, referencingFKeysFlag);
+
+	/* already captured self referencing foreign keys, so use EXCLUDE_SELF_REFERENCES */
+	int referencedFKeysFlag = INCLUDE_REFERENCED_CONSTRAINTS |
+							  EXCLUDE_SELF_REFERENCES |
+							  INCLUDE_LOCAL_TABLES;
+	List *referencedFKeyList = GetForeignKeyOids(relationId, referencedFKeysFlag);
```
Comment (marcocitus) [inline src/backend/distributed/commands/foreign_constraint.c:742]: for referenced local tables, do we need some kind of check for forbidden ON CASCADE options?

File: src/backend/distributed/commands/create_distributed_table.c (hunk 4 above)
Comment (onurctirtir) [reply src/backend/distributed/commands/create_distributed_table.c:375]: we are actually just creating the reference table, so we don't have this info in metadata cache :/

File: src/backend/distributed/commands/foreign_constraint.c (hunk 5 above)
Comment (marcocitus) [reply src/backend/distributed/commands/foreign_constraint.c:742]: Makes sense, would be good to add a test.

File: src/backend/distributed/commands/create_distributed_table.c [hunk 6]
```diff
@@ -354,15 +359,48 @@ CreateDistributedTable(Oid relationId, Var *distributionColumn, char distributio
...
+	List *originalForeignKeyRecreationCommands = NIL;
 	if (IsCitusTableType(relationId, CITUS_LOCAL_TABLE))
 	{
 		/* store foreign key creation commands that relation is involved */
-		fKeyCreationCommandsRelationInvolved =
-			GetFKeyCreationCommandsRelationInvolved(relationId);
+		originalForeignKeyRecreationCommands =
+			GetFKeyCreationCommandsRelationInvolvedWithTableType(relationId,
+																 INCLUDE_ALL_TABLE_TYPES);
 		relationId = DropFKeysAndUndistributeTable(relationId);
```
Comment (onurctirtir) [inline src/backend/distributed/commands/create_distributed_table.c:369]: question, should we switch to local execution here too (related #4489) ?

Comment (marcocitus) [reply src/backend/distributed/commands/create_distributed_table.c:369]: I think yes,

```sql

create table ref2 (a int primary key);
create table local (X int references ref2(a), y int);
alter table local add constraint pk primary key (x);
create table local2 (x int references ref2(a), y int references local (x));
select create_reference_table('ref2');
ERROR:  cannot switch local execution status from local execution disabled to local execution enabled since it can cause visibility problems in the current transaction
DETAIL:  When adding a foreign key from a local table to a reference table, Citus applies a conversion to all the local tables in the foreign key graph
```

Comment (marcocitus) [reply src/backend/distributed/commands/create_distributed_table.c:369]: I'm guessing that already happens when sending a drop constraint command to a Citus local table

Comment (onurctirtir) [reply src/backend/distributed/commands/create_distributed_table.c:369]: True.
When dropping citus local table, we will always use local execution unless local execution is disabled.
If local execution is disabled, then `CreateCitusLocalTable` would already error out.

But to be on the safe side, does it make sense to set local execution to required  ?

File: src/backend/distributed/commands/foreign_constraint.c (hunk 5 above)
Comment (onurctirtir) [reply src/backend/distributed/commands/foreign_constraint.c:742]: added now c6fa753901833aa06302c388297890a9e8c7fb11

File: src/backend/distributed/commands/create_distributed_table.c (hunk 6 above)
Comment (marcocitus) [reply src/backend/distributed/commands/create_distributed_table.c:369]: It definitely can't hurt.

**Review by marcocitus — APPROVED** [review]
I'm fine with these changes. Maybe wait for @onderkalaci to give his verdict.

File: src/backend/distributed/commands/create_distributed_table.c [hunk 7]
```diff
@@ -344,6 +346,9 @@ void
 CreateDistributedTable(Oid relationId, Var *distributionColumn, char distributionMethod,
 					   int shardCount, char *colocateWithTableName, bool viaDeprecatedAPI)
 {
+	char replicationModel = DecideReplicationModel(distributionMethod,
```
Comment (onderkalaci) [inline src/backend/distributed/commands/create_distributed_table.c:349]: `DecideReplicationModel ()` ignores Citus local tables and so I was confused that we rely on its return value.

I guess the proper way would be to pass `replicationModel` parameter to `CreateDistributedTable()`. Otherwise, it is not possible to distinguish reference/citus local here. That seems like a large change.

We should probably avoid relying on `DecideReplicationModel` unless we can fix it easily (and document that we ignore those):
```C
--- a/src/backend/distributed/commands/create_distributed_table.c
+++ b/src/backend/distributed/commands/create_distributed_table.c
@@ -375,9 +375,12 @@ CreateDistributedTable(Oid relationId, Var *distributionColumn, char distributio
         * that ALTER TABLE hook does the necessary job, which means converting
         * local tables to citus local tables to properly support such foreign
         * keys.
+        *
+        * This function does not expect to create Citus local table, so we blindly
+        * create reference table when the method is DISTRIBUTE_BY_NONE.
+        *
         */
-       else if (IsCitusTableTypeInternal(distributionMethod, replicationModel,
-                                                                         REFERENCE_TABLE) &&
+       else if (distributionMethod == DISTRIBUTE_BY_NONE &&
                         ShouldEnableLocalReferenceForeignKeys() &&
                         HasForeignKeyWithLocalTable(relationId))
        {

--- a/src/backend/distributed/commands/create_distributed_table.c
+++ b/src/backend/distributed/commands/create_distributed_table.c
@@ -461,6 +461,10 @@ CreateDistributedTable(Oid relationId, Var *distributionColumn, char distributio
        }
        else if (distributionMethod == DISTRIBUTE_BY_NONE)
        {
+               /*
+                * This function does not expect to create Citus local table, so we blindly
+                * create reference table when the method is DISTRIBUTE_BY_NONE.
+                *  */
                CreateReferenceTableShard(relationId);
        }
```

**Review by onderkalaci — APPROVED** [review]
This all looks good, tested in detail and everything seems to work fine.

File: src/backend/distributed/commands/create_distributed_table.c (hunk 7 above)
Comment (onderkalaci) [reply src/backend/distributed/commands/create_distributed_table.c:349]: (and move back `char replicationModel = DecideReplicationModel(distributionMetho` ) call into old place
