### PR TITLE
Columnar: use clause Vars for chunk group filtering.

### LINKED ISSUE #4780: Columnar: chunk group filtering doesn't work with partitioned tables

### PR DESCRIPTION
**Pull request by jeff-davis**
This solves a problem relying on dummy Vars and also provides a cleaner separation between chunk
group filtering and projection pushdown.

Closes #4780

### CODE REVIEW

File: src/backend/columnar/columnar_reader.c [hunk 1]
```diff
@@ -149,6 +152,10 @@ ColumnarBeginRead(Relation relation, TupleDesc tupleDescriptor,
 		totalRowCount += stripeMetadata->rowCount;
 	}
 
+	int flags = PVC_RECURSE_AGGREGATES |
+				PVC_RECURSE_WINDOWFUNCS | PVC_RECURSE_PLACEHOLDERS;
```
Comment (pykello) [inline src/backend/columnar/columnar_reader.c:156]: Can we also add some tests which would fail if we didn't set some of these flags?

File: src/test/regress/output/columnar_chunk_filtering.source [hunk 2]
```diff
@@ -182,3 +182,25 @@ EXPLAIN (analyze on, costs off, timing off, summary off)
...
+create table part_1_row partition of part_table for values from (150000) to (160000);
+create table part_2_columnar partition of part_table for values from (0) to (150000) using columnar;
+insert into part_table select generate_series(1,159999);
+explain (analyze, costs off, timing off, summary off)
+  select count(*) from part_table where id > 75000;
+                                             QUERY PLAN
+---------------------------------------------------------------------
+ Aggregate (actual rows=1 loops=1)
+   ->  Append (actual rows=84999 loops=1)
+         ->  Custom Scan (ColumnarScan) on part_2_columnar part_table_1 (actual rows=74999 loops=1)
```
Comment (onurctirtir) [inline src/test/regress/output/columnar_chunk_filtering.source:198]: Is it possible to use `filtered_row_count` or a similar function so that we don't need to put an alternative test output to/not to print parent table ?

File: src/test/regress/output/columnar_chunk_filtering.source [hunk 3]
```diff
@@ -182,3 +182,25 @@ EXPLAIN (analyze on, costs off, timing off, summary off)
...
+               Filter: (id > 75000)
+               Rows Removed by Filter: 5000
+               Columnar Chunk Groups Removed by Filter: 7
+         ->  Seq Scan on part_1_row part_table_2 (actual rows=10000 loops=1)
+               Filter: (id > 75000)
+(8 rows)
+
```
Comment (onurctirtir) [inline src/test/regress/output/columnar_chunk_filtering.source:205]: maybe one more test, with window functions:

```sql
alter table part_table add column second_col int;
truncate part_table ;

insert into part_table select i, i*2 from generate_series(1,159999) i;
explain (analyze,... ) select avg(second_col) over (partition by id) from part_table where id > 140000;
```

File: src/backend/columnar/columnar_reader.c (hunk 1 above)
Comment (jeff-davis) [reply src/backend/columnar/columnar_reader.c:156]: On second thought, why would any of these matter? The only cases we care about are when the min/max can disprove it. If you have something like `HAVING count(x) > 3` or some window function, then a min/max on `x` won't disprove that.

I just copied those flags across, but I can't imagine a situation where they help. And even if we miss one, it won't affect correctness. Thoughts? Am I missing a case?

File: src/test/regress/output/columnar_chunk_filtering.source (hunk 3 above)
Comment (jeff-davis) [reply src/test/regress/output/columnar_chunk_filtering.source:205]: What would that actually test for? It seems that the `WHERE` clause is the same.

File: src/test/regress/output/columnar_chunk_filtering.source (hunk 2 above)
Comment (jeff-davis) [reply src/test/regress/output/columnar_chunk_filtering.source]: Done.

File: src/backend/columnar/columnar_reader.c [hunk 4]
```diff
@@ -77,15 +77,17 @@ struct ColumnarReadState
 	List *projectedColumnList;
 
 	List *whereClauseList;
+	List *clauseVars;
```
[the remark this answers is not in the document]
Comment (jeff-davis) [reply src/backend/columnar/columnar_reader.c]: Done.

File: src/test/regress/output/columnar_chunk_filtering_1.source [hunk 5]
```diff
@@ -0,0 +1,206 @@
+--
+-- Test chunk filtering in columnar using min/max values in stripe skip lists.
+--
+--
+-- filtered_row_count returns number of rows filtered by the WHERE clause.
+-- If chunks get filtered by columnar, less rows are passed to WHERE
+-- clause, so this function should return a lower number.
+--
+CREATE OR REPLACE FUNCTION filtered_row_count (query text) RETURNS bigint AS
```
[the remark this answers is not in the document]
Comment (jeff-davis) [reply src/test/regress/output/columnar_chunk_filtering_1.source]: That's a good idea.

File: src/test/regress/input/columnar_chunk_filtering.source [hunk 6]
```diff
@@ -101,3 +101,13 @@ EXPLAIN (analyze on, costs off, timing off, summary off)
   SELECT count(*) FROM multi_column_chunk_filtering WHERE a > 50000 AND b > 50000;
 
 DROP TABLE multi_column_chunk_filtering;
+
+--
+-- https://github.com/citusdata/citus/issues/4780
+--
+create table part_table (id int) partition by range (id);
+create table part_1_row partition of part_table for values from (150000) to (160000);
+create table part_2_columnar partition of part_table for values from (0) to (150000) using columnar;
```
Comment (onurctirtir) [inline src/test/regress/input/columnar_chunk_filtering.source:110]: should we also test with more than one columnar partitions where we prune chunks from different partitions in the same query ?

row_part -> 0, 99 (actually not needed at allt)
columnar_part_1 -> 100, 79999
columnar_part_2 -> 80000, 119999

```sql
select filtered_row_count('select count(*) from part_table where id > 50000 and id < 110000');
```

File: src/test/regress/output/columnar_chunk_filtering.source (hunk 3 above)
Comment (onurctirtir) [reply src/test/regress/output/columnar_chunk_filtering.source:197]: oh true, where clause is the same here

File: src/backend/columnar/columnar_reader.c [hunk 7]
```diff
@@ -759,6 +767,58 @@ BuildBaseConstraint(Var *variable)
...
+	 */
+	int flags = 0;
+	List *vars = pull_var_clause((Node *) whereClauseList, flags);
+	Var **deduplicate = palloc0(sizeof(Var *) * natts);
+
+	ListCell *lc;
+	foreach(lc, vars)
+	{
+		Node *node = lfirst(lc);
+		Assert(IsA(Var, node));
```
[the remark this answers is not in the document]
Comment (jeff-davis) [reply src/backend/columnar/columnar_reader.c:792]: Thanks. I wonder how the first one even compiled?

[the remark this answers is not in the document]
Comment (onurctirtir) [reply src/backend/columnar/columnar_reader.c:792]: Afaik ci doesn't use `--enable-cassert`, so we couldn't catch this

File: src/test/regress/input/columnar_chunk_filtering.source (hunk 6 above)
Comment (jeff-davis) [reply src/test/regress/input/columnar_chunk_filtering.source:110]: The filtered_row_count function only returns a single number, so it's not really sufficient to make this test change. I'll just leave it as-is matching the issue in the tracker. We can refactor some other things later.

File: src/backend/columnar/columnar_reader.c (hunk 7 above)
[the remark this answers is not in the document]
Comment (jeff-davis) [reply src/backend/columnar/columnar_reader.c]: Done.
