### PR TITLE
Fixes ConnectionModifiedPlacement output for a failed transaction

### LINKED ISSUE #5199: Assertion failure if transaction failed
@thanodnl hit this assert during failure tests

The following from `failure_mx_metadata_sync` test fail at the assert `Assert(!ConnectionModifiedPlacement(connection));`

```SQL
-- Failure to set groupid in the worker
SELECT citus.mitmproxy('conn.onQuery(query="^UPDATE pg_dist_local_group SET groupid").kill()');
SELECT stop_metadata_sync_to_node('localhost', :worker_2_proxy_port);

-- Failure to drop all tables in pg_dist_partition
SELECT citus.mitmproxy('conn.onQuery(query="^SELECT worker_drop_distributed_table").kill()');
SELECT stop_metadata_sync_to_node('localhost', :worker_2_proxy_port);

-- Failure to truncate pg_dist_node in the worker
SELECT citus.mitmproxy('conn.onQuery(query="^TRUNCATE pg_dist_node CASCADE").kill()');
SELECT stop_metadata_sync_to_node('localhost', :worker_2_proxy_port);
```

### PR DESCRIPTION
**Pull request by naisila**
We skip `FinishRemoteTransactionPrepare` for connections for which `ConnectionModifiedPlacement` returned false.

However, for transactions that failed, `ConnectionModifiedPlacement` returns true from this if condition
```
if (dlist_is_empty(&connection->referencedPlacements))
```
causing the test `failure_mx_metadata_sync` to fail in onquery.kill() commands in the assert: 
```
Assert(!ConnectionModifiedPlacement(connection));
```

~~Since we don't prepare a transaction that failed, I added `transaction->transactionFailed` to the assert.~~

Alternatively, we could add a check in `ConnectionModifiedPlacement` which returns false if the transaction failed.

Fixes #5199

### CODE REVIEW

**Comment by SaitTalhaNisanci** [comment]
I verified that this is indeed fixing the assertion failure.

```
	if (dlist_is_empty(&connection->referencedPlacements))
	{
		/*
		 * When referencesPlacements are empty, it means that we come here
		 * from an API that uses a node connection (e.g., not placement connection),
		 * which doesn't set placements.
		 * In that case, the command sent could be either write or read, so we assume
		 * it is write to be on the safe side.
		 */
		return true;
	}
```

If we are returning true from this block, then isn't that a bug in that method? Because the comment that explains why we return true is not actually correct if the transaction failed, do you think we should update `ConnectionModifiedPlacement`?

I think the description line is a bit misleading because this PR doesn't add any logical code, I am not sure if we should add a description line for this PR.

**Comment by naisila** [comment]
Thanks @SaitTalhaNisanci. Updating `ConnectionModifiedPlacement` would be more correct yes. Also, I think we don't need a description line for this PR.

File: src/backend/distributed/connection/placement_connection.c [hunk 1]
```diff
@@ -846,6 +846,12 @@ ConnectionModifiedPlacement(MultiConnection *connection)
 		return false;
 	}
 
+	if (connection->remoteTransaction.transactionFailed)
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/connection/placement_connection.c:849]: @marcocitus Do you see any potential problem with this change? I am asking since this is a critical method

Comment (marcocitus) [reply src/backend/distributed/connection/placement_connection.c:849]: No, I think we mainly use this to check whether we should send a prepared transaction.

There's one additional call from Activate2PCIfModifyingTransactionExpandsToNewNode, but we should not get there for failed connections.

Comment (onderkalaci) [reply src/backend/distributed/connection/placement_connection.c:849]: Minor: I think the caller of `ConnectionModifiedPlacement` should not call this function if the connection failed. It feels confusing when reading the code. I don't want future callers to assume that failed transactions are OK to check  `ConnectionModifiedPlacement`

In the first iteration of `CoordinatedRemoteTransactionsPrepare` we already skip failed transactions.

I think we should not change this function and make the assert cover failed transactions such as:
```C
/* have some comment*/
Assert( transaction->transactionFailed || !ConnectionModifiedPlacement(connection));
```

**Comment by naisila** [comment]
Modifying the `Assert` and not the inside of `ConnectionModifiedPlacement` because of @onderkalaci 's important remark that ideally the caller of `ConnectionModifiedPlacement` should not call this function if the connection failed.

**Comment by naisila** [comment]
Note: The wrong PR name made its way into the commit message on the default branch
