### PR TITLE
Fall-back to seq-scan when accessing columnar metadata if the index doesn't exist

### LINKED ISSUE #5510: pg_dump gives columnar AM dependency loop warnings
When I run pg_dump against a database with Citus I get a series of warnings:
```sql
$ pg_dump
pg_dump: warning: could not resolve dependency loop among these items:
pg_dump:   ACCESS METHOD columnar  (ID 1769 OID 361215)
pg_dump:   INDEX stripe_pkey  (ID 3323 OID 361190)
pg_dump:   CONSTRAINT stripe_pkey  (ID 3324 OID 361191)                                  
pg_dump:   POST-DATA BOUNDARY  (ID 3482)    
pg_dump:   TABLE DATA test  (ID 3478 OID 361296)
pg_dump:   PRE-DATA BOUNDARY  (ID 3481)     
pg_dump: warning: could not resolve dependency loop among these items:
pg_dump:   ACCESS METHOD columnar  (ID 1769 OID 361215)                                  
pg_dump:   INDEX options_pkey  (ID 3319 OID 361185)
pg_dump:   CONSTRAINT options_pkey  (ID 3320 OID 361186)    
pg_dump:   POST-DATA BOUNDARY  (ID 3482)    
pg_dump:   TABLE DATA test  (ID 3478 OID 361296)
pg_dump:   PRE-DATA BOUNDARY  (ID 3481)
pg_dump: warning: could not resolve dependency loop among these items:
pg_dump:   ACCESS METHOD columnar  (ID 1769 OID 361215)
pg_dump:   INDEX chunk_group_pkey  (ID 3325 OID 361195)
pg_dump:   CONSTRAINT chunk_group_pkey  (ID 3326 OID 361196)
pg_dump:   POST-DATA BOUNDARY  (ID 3482)    
pg_dump:   TABLE DATA test  (ID 3478 OID 361296)
pg_dump:   PRE-DATA BOUNDARY  (ID 3481)                                                  
pg_dump: warning: could not resolve dependency loop among these items:                   
pg_dump:   ACCESS METHOD columnar  (ID 1769 OID 361215)
pg_dump:   INDEX chunk_pkey  (ID 3327 OID 361207)
pg_dump:   CONSTRAINT chunk_pkey  (ID 3328 OID 361208)
pg_dump:   POST-DATA BOUNDARY  (ID 3482)    
pg_dump:   TABLE DATA test  (ID 3478 OID 361296)
pg_dump:   PRE-DATA BOUNDARY  (ID 3481)     
pg_dump: warning: could not resolve dependency loop among these items:
pg_dump:   ACCESS METHOD columnar  (ID 1769 OID 361215)
pg_dump:   INDEX stripe_first_row_number_idx  (ID 3321 OID 361286)
pg_dump:   CONSTRAINT stripe_first_row_number_idx  (ID 3322 OID 361287)
pg_dump:   POST-DATA BOUNDARY  (ID 3482)                                                 
pg_dump:   TABLE DATA test  (ID 3478 OID 361296)
pg_dump:   PRE-DATA BOUNDARY  (ID 3481) 
```

fwiw, test is not a columnar table.

### LINKED ISSUE #6570: pg_upgrade 14 -> 15 fails when using columnar 11.1 in child table
When a child table in a partitioned table is using citus_columnar then an upgrade from PSQL 14 to 15 fails

PostgreSQL 14.5 and 15.1
citus/citus_columnar 11.1-1
RHEL 7.9

Steps to reproduce:

```
$ mkdir test_citus_pg_14_15_upgrade
$ /usr/pgsql-14/bin/initdb -D test_citus_pg_14_15_upgrade/data14
$ /usr/pgsql-15/bin/initdb -D test_citus_pg_14_15_upgrade/data15
$ echo  "shared_preload_libraries = 'citus'" >> test_citus_pg_14_15_upgrade/data15/postgresql.conf
$ echo  "shared_preload_libraries = 'citus'" >> test_citus_pg_14_15_upgrade/data14/postgresql.conf
$ /usr/pgsql-14/bin/pg_ctl -D test_citus_pg_14_15_upgrade/data14 start
$ psql -c "CREATE EXTENSION citus_columnar ; CREATE TABLE foo (d DATE NOT NULL) PARTITION BY RANGE (d); CREATE TABLE foo3 PARTITION OF foo FOR VALUES FROM ('2009-02-01') TO ('2009-03-01') USING COLUMNAR; "
$ pg_ctl -D test_citus_pg_14_15_upgrade/data14 stop
$ /usr/pgsql-15/bin/pg_upgrade --link --old-datadir="/var/lib/pgsql/test_citus_pg_14_15_upgrade/data14" --new-datadir="/var/lib/pgsql/test_citus_pg_14_15_upgrade/data15" --old-bindir="/usr/pgsql-14/bin" --new-bindir="/usr/pgsql-15/bin"
```

Output from upgrade command:
```
Performing Consistency Checks
-----------------------------
Checking cluster versions                                   ok
Checking database user is the install user                  ok
Checking database connection settings                       ok
Checking for prepared transactions                          ok
Checking for system-defined composite types in user tables  ok
Checking for reg* data types in user tables                 ok
Checking for contrib/isn with bigint-passing mismatch       ok
Creating dump of global objects                             ok
Creating dump of database schemas
                                                            ok
Checking for presence of required libraries                 ok
Checking database user is the install user                  ok
Checking for prepared transactions                          ok
Checking for new cluster tablespace directories             ok

If pg_upgrade fails after this point, you must re-initdb the
new cluster before continuing.

Performing Upgrade
------------------
Analyzing all rows in the new cluster                       ok
Freezing all rows in the new cluster                        ok
Deleting files from new pg_xact                             ok
Copying old pg_xact to new server                           ok
Setting oldest XID for new cluster                          ok
Setting next transaction ID and epoch for new cluster       ok
Deleting files from new pg_multixact/offsets                ok
Copying old pg_multixact/offsets to new server              ok
Deleting files from new pg_multixact/members                ok
Copying old pg_multixact/members to new server              ok
Setting next multixact ID and offset for new cluster        ok
Resetting WAL archives                                      ok
Setting frozenxid and minmxid counters in new cluster       ok
Restoring global objects in the new cluster                 ok
Restoring database schemas in the new cluster
  postgres
*failure*

Consult the last few lines of "/var/lib/pgsql/test_citus_pg_14_15_upgrade/data15/pg_upgrade_output.d/20221221T093126.357/log/pg_upgrade_dump_14486.log" for
the probable cause of the failure.
Failure, exiting
```

```
$ egrep -B3 -A3 '(warning)|(ERROR)' /var/lib/pgsql/test_citus_pg_14_15_upgrade/data15/pg_upgrade_output.d/20221221T094039.598/log/pg_upgrade_dump_14486.log
command: "/usr/pgsql-15/bin/pg_dump" --host /var/lib/pgsql --port 50432 --username postgres --schema-only --quote-all-identifiers --binary-upgrade --format=custom  --file="/var/lib/pgsql/test_citus_pg_14_15_upgrade/data15/pg_upgrade_output.d/20221221T094039.598/dump/pg_upgrade_dump_14486.custom" 'dbname=postgres' >> "/var/lib/pgsql/test_citus_pg_14_15_upgrade/data15/pg_upgrade_output.d/20221221T094039.598/log/pg_upgrade_dump_14486.log" 2>&1
pg_dump: warning: could not resolve dependency loop among these items:
pg_dump: warning: could not resolve dependency loop among these items:
pg_dump: warning: could not resolve dependency loop among these items:
pg_dump: warning: could not resolve dependency loop among these items:
pg_dump: warning: could not resolve dependency loop among these items:
pg_dump: warning: could not resolve dependency loop among these items:


command: "/usr/pgsql-15/bin/pg_restore" --host /var/lib/pgsql --port 50432 --username postgres --clean --create --exit-on-error --verbose --dbname template1 "/var/lib/pgsql/test_citus_pg_14_15_upgrade/data15/pg_upgrade_output.d/20221221T094039.598/dump/pg_upgrade_dump_14486.custom" >> "/var/lib/pgsql/test_citus_pg_14_15_upgrade/data15/pg_upgrade_output.d/20221221T094039.598/log/pg_upgrade_dump_14486.log" 2>&1
--
pg_restore: creating TABLE ATTACH "public.foo3"
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 3950; 0 0 TABLE ATTACH foo3 postgres
pg_restore: error: could not execute query: ERROR:  could not open relation with OID 0
Command was: ALTER TABLE ONLY "public"."foo" ATTACH PARTITION "public"."foo3" FOR VALUES FROM ('2009-02-01') TO ('2009-03-01');

```

### PR DESCRIPTION
**Pull request by onurctirtir**
DESCRIPTION: Fixes a bug that breaks pg upgrades if the user has a columnar table

Fixes #6570.

In the past, having columnar tables in the cluster was causing pg
upgrades to fail when attempting to access columnar metadata. This is
because, pg_dump doesn't see objects that we use for columnar-am related
booking as the dependencies of the tables using columnar-am.
To fix that; in #5456, we inserted some "normal dependency" edges (from
those objects to columnar-am) into pg_depend.

This helped us ensuring the existency of a class of metadata objects
--such as columnar.storageid_seq-- and helped fixing #5437.

However, the normal-dependency edges that we added for indexes on
columnar metadata tables --such columnar.stripe_pkey-- didn't help at
all because they were indeed causing dependency loops (#5510) and
pg_dump was not able to take those dependency edges into the account.

For this reason, this commit allows columnar metadata accessors to
fall-back to sequential scan if the index is not available, which can
only be the case during pg upgrades.

### CODE REVIEW

File: src/test/regress/sql/upgrade_columnar_before.sql [hunk 1]
```diff
@@ -1,5 +1,29 @@
 -- Test if relying on topological sort of the objects, not their names, works
 -- fine when re-creating objects during pg_upgrade.
+
+DO
+$$
+BEGIN
+IF EXISTS (SELECT * FROM pg_namespace WHERE nspname = 'citus_schema')
```
Comment (onurctirtir) [inline src/test/regress/sql/upgrade_columnar_before.sql:7]: maybe check for upgrade_columnar instead

File: src/test/regress/sql/multi_extension.sql [hunk 2]
```diff
@@ -552,6 +552,40 @@ ALTER EXTENSION citus UPDATE TO '11.2-1';
 SELECT * FROM pg_dist_placement ORDER BY shardid;
 SELECT * FROM pg_dist_cleanup;
 
+-- TODO: Looks like citus_columnar doesn't get auto-updated when updating Citus
```
Comment (onurctirtir) [inline src/test/regress/sql/multi_extension.sql:555]: well, seems like another bug ..

File: src/backend/columnar/columnar_metadata.c [hunk 3]
```diff
@@ -923,31 +932,67 @@ StripeMetadataLookupRowNumber(Relation relation, uint64 rowNumber, Snapshot snap
...
+		while (HeapTupleIsValid(heapTuple = systable_getnext(scanDescriptor)))
+		{
+			StripeMetadata *stripe = BuildStripeMetadata(columnarStripes, heapTuple);
+			if (!foundStripeMetadata)
+			{
+				/* first match */
+				foundStripeMetadata = stripe;
+			}
+			else if (lookupMode == FIND_LESS_OR_EQUAL &&
+					 stripe->firstRowNumber > foundStripeMetadata->firstRowNumber)
```
Comment (onurctirtir) [inline src/backend/columnar/columnar_metadata.c:975]: add columnar partition test from the issue for a better coverage

File: src/backend/columnar/columnar_metadata.c [hunk 4]
```diff
@@ -1305,14 +1370,19 @@ UpdateStripeMetadataRow(uint64 storageId, uint64 stripeId, bool *update,
...
-															&dirtySnapshot, 2, scanKey);
+	/* can't rely on indexes during pg upgrades */
+	Oid indexId = ColumnarStripePKeyIndexRelationId();
+	bool indexOk = !IsBinaryUpgrade;
+	SysScanDesc scanDescriptor = systable_beginscan(columnarStripes, indexId, indexOk,
+													&dirtySnapshot, 2, scanKey);
+
+	if (!indexOk)
+	{
+		ereport(WARNING, (errmsg(SLOW_METADATA_ACCESS_WARNING, "stripe_pkey")));
```
Comment (onurctirtir) [inline src/backend/columnar/columnar_metadata.c:1382]: do the logging once by using a static var

File: src/backend/columnar/columnar_metadata.c [hunk 5]
```diff
@@ -923,31 +932,67 @@ StripeMetadataLookupRowNumber(Relation relation, uint64 rowNumber, Snapshot snap
...
 
-	ScanDirection scanDirection = NoMovementScanDirection;
-	if (lookupMode == FIND_LESS_OR_EQUAL)
-	{
-		scanDirection = BackwardScanDirection;
-	}
-	else if (lookupMode == FIND_GREATER)
+	/* can't rely on indexes during pg upgrades */
+	Oid indexId = ColumnarStripeFirstRowNumberIndexRelationId();
+	bool indexOk = !IsBinaryUpgrade;
```
Comment (onurctirtir) [inline src/backend/columnar/columnar_metadata.c:939]: Maybe not always fall-back to seq-scan, if the index exists ? This is quite possible if pg_dump decides creating the metadata index before creating columnar tables.

File: src/backend/columnar/sql/citus_columnar--11.1-1--11.2-1.sql [hunk 6]
```diff
@@ -1 +1,61 @@
 -- citus_columnar--11.1-1--11.2-1
+
+CREATE OR REPLACE FUNCTION columnar_internal.columnar_ensure_am_depends_catalog()
```
Comment (onurctirtir) [inline src/backend/columnar/sql/citus_columnar--11.1-1--11.2-1.sql:3]: Doing this here because columnar-Makefile doesn't know how to expand `#include` directives. At least comment this in the downgrade script ?

File: src/backend/columnar/sql/citus_columnar--11.1-1--11.2-1.sql [hunk 7]
```diff
@@ -1 +1,61 @@
...
+  -- Avoid inserting duplicate entries into pg_depend.
+  EXCEPT TABLE pg_depend;
+END;
+$func$;
+COMMENT ON FUNCTION columnar_internal.columnar_ensure_am_depends_catalog()
+  IS 'internal function responsible for creating dependencies from columnar '
+     'table access method to the rel objects in columnar schema';
+
+DELETE FROM pg_depend
+WHERE classid = 'pg_am'::regclass::oid
```
Comment (onurctirtir) [inline src/backend/columnar/sql/citus_columnar--11.1-1--11.2-1.sql:48]: Not reverting this change in the downgrade script because it doesn't make sense to re-introduce a bug, just because we're doing a downgrade.

This is what we've done for #5456 too.

Maybe comment this in the downgrade script.

File: src/backend/columnar/columnar_metadata.c [hunk 8]
```diff
@@ -701,15 +705,24 @@ ReadStripeSkipList(RelFileNode relfilenode, uint64 stripe, TupleDesc tupleDescri
...
-															snapshot, 2, scanKey);
+	Oid indexId = ColumnarChunkIndexRelationId();
+	bool indexOk = OidIsValid(indexId);
+	SysScanDesc scanDescriptor = systable_beginscan(columnarChunk, indexId,
+													indexOk, snapshot, 2, scanKey);
+
+	static bool loggedSlowMetadataAccessWarning = false;
+	if (!indexOk && !loggedSlowMetadataAccessWarning)
+	{
+		Assert(IsBinaryUpgrade);
```
Comment (onurctirtir) [inline src/backend/columnar/columnar_metadata.c:722]: Drop asserts and add some regression tests by dropping those metadata indexes to forcefully trigger the bug.

**Review by marcocitus — COMMENTED** [review]
This looks pretty good, but is there any way to have an actual pg_upgrade test?

**Comment by onurctirtir** [comment]
> This looks pretty good, but is there any way to have an actual pg_upgrade test?

The following is added in this PR.
https://github.com/citusdata/citus/blob/3ea3089525a099b3d0810d806e757a583b7083a6/src/test/regress/expected/upgrade_columnar_before.out#L374-L376

Without the fix done in this PR, pg_upgrade was failing when restoring the database.

**Review by marcocitus — APPROVED** [review]

**Comment by onurctirtir** [comment]
(not created the release branch for 11.2 yet, so we don't need to add cherry-pick-11.2 flag)

**Comment by onurctirtir** [comment]
(backported to 11.0 & 11.1 too)
