### PR TITLE
Fix insert query with CTEs/sublinks/subqueries etc

### LINKED ISSUE #4091: Inserting values from generate_series might give assertion failure
```sql
CREATE TABLE no_index_cleanup (i INT PRIMARY KEY, t TEXT);
SELECT create_reference_table('no_index_cleanup');
INSERT INTO no_index_cleanup(i, t)
VALUES (
  generate_series(1,30),
  repeat('1234567890',269)
);
```

Above insert crashes due to assertion failure with below backtrace:

```c
#2  0x0000000000aae380 in ExceptionalCondition (conditionName=0x7f5ffa87f990 "!(currentPlan->fastPathRouterPlan || !EnableFastPathRouterPlanner)",
    errorType=0x7f5ffa87f861 "FailedAssertion", fileName=0x7f5ffa87f922 "executor/citus_custom_scan.c", lineNumber=346) at assert.c:54
#3  0x00007f5ffa7e21aa in CitusBeginModifyScan (node=0x1dbefe0, estate=0x1dbed58, eflags=0) at executor/citus_custom_scan.c:346
#4  0x00007f5ffa7e1f01 in CitusBeginScan (node=0x1dbefe0, estate=0x1dbed58, eflags=0) at executor/citus_custom_scan.c:196
#5  0x0000000000732c4e in ExecInitCustomScan (cscan=0x1db9e60, estate=0x1dbed58, eflags=0) at nodeCustom.c:103
#6  0x000000000071a276 in ExecInitNode (node=0x1db9e60, estate=0x1dbed58, eflags=0) at execProcnode.c:282
#7  0x00000000007109a7 in InitPlan (queryDesc=0x1dc95c8, eflags=0) at execMain.c:1020
#8  0x000000000070f829 in standard_ExecutorStart (queryDesc=0x1dc95c8, eflags=0) at execMain.c:266
#9  0x00007f5ffa7ea47e in CitusExecutorStart (queryDesc=0x1dc95c8, eflags=0) at executor/multi_executor.c:116
#10 0x000000000070f5a5 in ExecutorStart (queryDesc=0x1dc95c8, eflags=0) at execMain.c:146
#11 0x0000000000923aa1 in ProcessQuery (plan=0x1dba2a0,
    sourceText=0x1c1fae8 "INSERT INTO no_index_cleanup(i, t)\nVALUES (\n  generate_series(1,30),\n  repeat('1234567890',269)\n);", params=0x0,
    queryEnv=0x0, dest=0x1dcab48, completionTag=0x7ffeb0978690 "") at pquery.c:156
#12 0x00000000009254f0 in PortalRunMulti (portal=0x1cf87d8, isTopLevel=true, setHoldSnapshot=false, dest=0x1dcab48, altdest=0x1dcab48,
    completionTag=0x7ffeb0978690 "") at pquery.c:1283
#13 0x0000000000924a4d in PortalRun (portal=0x1cf87d8, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x1dcab48, altdest=0x1dcab48,
    completionTag=0x7ffeb0978690 "") at pquery.c:796
#14 0x000000000091e5b4 in exec_simple_query (
    query_string=0x1c1fae8 "INSERT INTO no_index_cleanup(i, t)\nVALUES (\n  generate_series(1,30),\n  repeat('1234567890',269)\n);") at postgres.c:1215
#15 0x0000000000922a7c in PostgresMain (argc=1, argv=0x1cb8880, dbname=0x1cb86c0 "postgres", username=0x1cb8698 "postgres") at postgres.c:4247
#16 0x00000000008713bd in BackendRun (port=0x1c3b9f0) at postmaster.c:4448
#17 0x0000000000870b06 in BackendStartup (port=0x1c3b9f0) at postmaster.c:4139
#18 0x000000000086cc46 in ServerLoop () at postmaster.c:1704
#19 0x000000000086c46d in PostmasterMain (argc=3, argv=0x1c1a760) at postmaster.c:1377
#20 0x00000000007850f7 in main (argc=3, argv=0x1c1a760) at main.c:228
```

And if we disable assertions, we get no errors nor warnings.

### LINKED ISSUE #4663: Insert CTE Crash
```sql
create table table1 (a int);
create table table2 (a text);
select create_distributed_table('table1','a');
select create_distributed_table('table2','a');
with wcte as (insert into table1 values (42))
  insert into table2 values ('hello world');
```

Gdb:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fb9f2f3f801 in __GI_abort () at abort.c:79
#2  0x000055acd49f1c96 in ExceptionalCondition (conditionName=<optimized out>,
    errorType=<optimized out>, fileName=<optimized out>, lineNumber=<optimized out>)
    at assert.c:54
#3  0x00007fb9f0527e8a in RegenerateTaskListForInsert (workerJob=0x2)
    at executor/citus_custom_scan.c:472
#4  0x00007fb9f0527f90 in CitusBeginModifyScan (node=0x55acd5d5bf50, estate=<optimized out>,
    eflags=<optimized out>) at executor/citus_custom_scan.c:347
#5  0x000055acd4749dd8 in ExecInitCustomScan (cscan=0x55acd5d5bf50, cscan@entry=0x55acd5d511e8,
    estate=0x55acd5d511e8, estate@entry=0x55acd5d5bc88, eflags=65002, eflags@entry=0)
    at nodeCustom.c:103
#6  0x000055acd4737e95 in ExecInitNode (node=node@entry=0x55acd5d511e8,
    estate=estate@entry=0x55acd5d5bc88, eflags=eflags@entry=0) at execProcnode.c:282
#7  0x000055acd4731eba in InitPlan (queryDesc=queryDesc@entry=0x55acd5ce4ac8,
    eflags=eflags@entry=0) at execMain.c:1020
#8  0x000055acd473206c in standard_ExecutorStart (queryDesc=0x55acd5ce4ac8, eflags=0)
    at execMain.c:266
#9  0x00007fb9f052d05a in CitusCustomScanStateWalker (planState=0x2,
    citusCustomScanStates=0x7fff60befdd0) at executor/multi_executor.c:273
#10 0x00007fb9ea3fc729 in pgss_ExecutorStart (queryDesc=0x55acd5d513c0, eflags=<optimized out>)
    at pg_stat_statements.c:853
#11 0x000055acd4732164 in ExecutorStart (queryDesc=queryDesc@entry=0x55acd5ce4ac8,
    eflags=eflags@entry=0) at execMain.c:146
#12 0x000055acd48be79d in ProcessQuery (plan=plan@entry=0x55acd5d513c0,
    sourceText=<optimized out>, params=0x0, queryEnv=0x0, dest=dest@entry=0x55acd5d51630,
    completionTag=completionTag@entry=0x7fff60bf0570 "") at pquery.c:156
#13 0x000055acd48be999 in PortalRunMulti (portal=portal@entry=0x55acd5ca22c8,
    isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false,
    dest=dest@entry=0x55acd5d51630, altdest=altdest@entry=0x55acd5d51630,
    completionTag=completionTag@entry=0x7fff60bf0570 "") at pquery.c:1283
#14 0x000055acd48bf920 in PortalRun (portal=portal@entry=0x55acd5ca22c8,
    count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true,
    run_once=run_once@entry=true, dest=dest@entry=0x55acd5d51630,
    altdest=altdest@entry=0x55acd5d51630, completionTag=0x7fff60bf0570 "") at pquery.c:796
#15 0x000055acd48bb9c6 in exec_simple_query (
    query_string=query_string@entry=0x55acd5bcbcb8 "with wcte as (insert into table1 values (42))\n  insert into table2 values ('hello world');") at postgres.c:1215
#16 0x000055acd48bda78 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x55acd5c68338,
    dbname=<optimized out>, username=<optimized out>) at postgres.c:4247
#17 0x000055acd482cd15 in BackendRun (port=port@entry=0x55acd5c65f70) at postmaster.c:4448
#18 0x000055acd48301b0 in BackendStartup (port=port@entry=0x55acd5c65f70) at postmaster.c:4139
#19 0x000055acd48304cf in ServerLoop () at postmaster.c:1704
#20 0x000055acd48318f9 in PostmasterMain (argc=5, argv=<optimized out>) at postmaster.c:1377
#21 0x000055acd478868f in main (argc=5, argv=0x55acd5bc39f0) at main.c:228
```

### PR DESCRIPTION
**Pull request by naisila**
DESCRIPTION: Fix insert query with CTEs/sublinks/subqueries etc

Fixes #4663 
Other than handling the failing assert, the following `SELECT` cte with an `INSERT` query isn't routable, therefore it is added to the checks in `multi_router_planner.c`, otherwise it fails.
```SQL
with wcte as (select * from table1)
  insert into table2 values ('hello world');
```

Also fixes #4091 as pointed out by @onurctirtir . The examples in this issue are all different cases of deferred pruning of `INSERT` queries with CTEs, sublinks, subqueries etc for which `fastPathRouterPlan` attribute is false. That's why the assert failed and we had a crash.

### CODE REVIEW

File: src/backend/distributed/executor/citus_custom_scan.c [hunk 1]
```diff
@@ -344,6 +344,10 @@ CitusBeginModifyScan(CustomScanState *node, EState *estate, int eflags)
 		 * Given that pruning is deferred always for INSERTs, we get here
 		 * !EnableFastPathRouterPlanner  as well.
 		 */
+		if (jobQuery->commandType == CMD_INSERT)
+		{
+			currentPlan->fastPathRouterPlan = true;
+		}
```
Comment (onurctirtir) [inline src/backend/distributed/executor/citus_custom_scan.c:350]: This might fix three cases given in #4091 too, looking into that.
See https://github.com/citusdata/citus/issues/4663#issuecomment-778114155

File: src/backend/distributed/executor/citus_custom_scan.c [hunk 2]
```diff
@@ -344,6 +344,10 @@ CitusBeginModifyScan(CustomScanState *node, EState *estate, int eflags)
 		 * Given that pruning is deferred always for INSERTs, we get here
 		 * !EnableFastPathRouterPlanner  as well.
 		 */
+		if (jobQuery->commandType == CMD_INSERT)
+		{
+			currentPlan->fastPathRouterPlan = true;
```
Comment (onurctirtir) [inline src/backend/distributed/executor/citus_custom_scan.c:349]: here instead of setting `fastPathRouterPlan` to `true`, I think we could directly do below:

```c
Assert(jobQuery->commandType == CMD_INSERT || currentPlan->fastPathRouterPlan || !EnableFastPathRouterPlanner);
```

This is because, for example the insert with cte isn't actually fast path router, according to definition:

```c

/*
 * FastPathRouterQuery gets a query and returns true if the query is eligable for
 * being a fast path router query.
 * The requirements for the fast path query can be listed below:
 *
 *   - SELECT query without CTES, sublinks-subqueries, set operations
 *   - The query should touch only a single hash distributed or reference table
 *   - The distribution with equality operator should be in the WHERE clause
 *      and it should be ANDed with any other filters. Also, the distribution
 *      key should only exists once in the WHERE clause. So basically,
 *          SELECT ... FROM dist_table WHERE dist_key = X
 *      If the filter is a const, distributionKeyValue is set
 *   - All INSERT statements (including multi-row INSERTs) as long as the commands
 *     don't have any sublinks/CTEs etc
 */
```

File: src/test/regress/expected/multi_router_planner_fast_path.out [hunk 3]
```diff
@@ -2111,6 +2111,26 @@ DEBUG:  query has a single distribution column value: 4
      0
 (1 row)
 
+-- test INSERT using values from generate_series() and repeat() functions
+INSERT INTO authors_reference (id, name) VALUES (generate_series(1, 10), repeat('Migjeni', 3));
+DEBUG:  Creating router plan
+SELECT * FROM authors_reference;
```
Comment (onderkalaci) [inline src/test/regress/expected/multi_router_planner_fast_path.out:2117]: We should add `ORDER BY` to make sure the output doesn't change on different runs of the test

File: src/backend/distributed/planner/multi_router_planner.c [hunk 4]
```diff
@@ -560,16 +560,17 @@ ModifyPartialQuerySupported(Query *queryTree, bool multiShardQuery,
...
-										 NULL, NULL);
-				}
+				return DeferredError(ERRCODE_FEATURE_NOT_SUPPORTED,
+									 "Router planner doesn't support common table expressions with INSERT queries.",
+									 NULL, NULL);
+			}
 
+			if (cteQuery->commandType != CMD_SELECT)
+			{
+				/* Modifying CTEs still not supported for multi shard queries. */
```
Comment (onurctirtir) [inline src/backend/distributed/planner/multi_router_planner.c:573]: just to understand better, is this part of the bugfix or some style & error/debug message improvement ?

File: src/test/regress/expected/multi_router_planner_fast_path.out (hunk 3 above)
Comment (onurctirtir) [inline src/test/regress/expected/multi_router_planner_fast_path.out:2117]: I think we should add `order by`s to `select`s so that tests don't become flaky in feature

**Review by onderkalaci — COMMENTED** [review]
> Also fixes #4091 as pointed out by @onurctirtir . The examples in this issue are all different cases of deferred pruning of INSERT queries with CTEs, sublinks, subqueries etc for which fastPathRouterPlan attribute is false. That's why the assert failed and we had a crash.

just fyi, this is only fixed for reference tables, if we use distributed table:

```SQL
INSERT INTO no_index_cleanup(i, t)
VALUES (
  generate_series(1,10),
  repeat('123',5)
) RETURNING *;
DEBUG:  Creating router plan
ERROR:  failed to evaluate partition key in insert
HINT:  try using constant values for partition column
Time: 0.447 ms
```

File: src/test/regress/expected/single_node.out [hunk 5]
```diff
@@ -694,6 +694,63 @@ SELECT * FROM collections_list, collections_list_0 WHERE collections_list.key=co
...
+CREATE TABLE parent_tab (id int) PARTITION BY RANGE (id);
+SELECT create_distributed_table('parent_tab', 'id');
+ create_distributed_table
+---------------------------------------------------------------------
+
+(1 row)
+
+INSERT INTO parent_tab VALUES (generate_series(0, 29));
+ERROR:  failed to evaluate partition key in insert
+HINT:  try using constant values for partition column
```
Comment (onurctirtir) [inline src/test/regress/expected/single_node.out:753]: after this line, let's add one more column to table:
`alter table parent_tab  add column b int;`

then let's show that below actually works:
`INSERT INTO parent_tab VALUES (1, generate_series(0, 29));`

File: src/test/regress/sql/single_node.sql [hunk 6]
```diff
@@ -409,6 +409,45 @@ SELECT count(*) FROM collections_list_1 WHERE key = 11;
...
+ALTER TABLE hash_parted DETACH PARTITION hpart2;
+ALTER TABLE hash_parted DETACH PARTITION hpart3;
+
+-- test range partition without creating partitions and inserting with generate_series()
+-- should error out even in plain PG since no partition of relation "parent_tab" is found for row
+-- in Citus it errors out because it fails to evaluate partition key in insert
+CREATE TABLE parent_tab (id int) PARTITION BY RANGE (id);
+SELECT create_distributed_table('parent_tab', 'id');
+INSERT INTO parent_tab VALUES (generate_series(0, 29));
+
```
Comment (onurctirtir) [inline src/test/regress/sql/single_node.sql:450]: some tests with distributed tables:

```sql
create table table1 (a int);
select create_distributed_table('table1','a');

-- test with returning
with wcte as (insert into table1 values (42) returning *)
insert into table2 values ('hello world');

-- even if we do multi-row insert, it is not fast path router due to cte
with wcte as (select 1 as col)
insert into table2 values ('hello world'), ('hello world');
```

Comment (onurctirtir) [reply src/test/regress/sql/single_node.sql:450]: Also, it might be better to check the rows inserted for all the tests to make sure that we actually insert the data as expected.
Before doing that, maybe we can insert less rows (like VALUES `(generate_series(0, 3)`) to make tests less verbose

File: src/test/regress/expected/with_modifying.out [hunk 7]
```diff
@@ -822,6 +822,33 @@ EXECUTE olu(1,ARRAY[1,2],ARRAY[1,2]);
...
+(1 row)
+
+SELECT * FROM with_modifying.anchor_table WHERE id = 1998;
+  id
+---------------------------------------------------------------------
+ 1998
+(1 row)
+
+-- test insert query with select CTE
+WITH select_cte AS
```
Comment (onderkalaci) [inline src/test/regress/expected/with_modifying.out:842]: `select_cte ` is not used at all, and both Citus/PG would ignore this CTE anyway. Can we write a query where we use the output of the CTE?

Comment (marcocitus) [reply src/test/regress/expected/with_modifying.out:842]: probably the only thing that works is using another modifying CTE that uses the select_cte, since sublinks in the insert are not supported

File: src/backend/distributed/planner/multi_router_planner.c (hunk 4 above)
Comment (naisila) [reply src/backend/distributed/planner/multi_router_planner.c:573]: As mentioned in the description, It is part of the bugfix for this case:
```SQL
with wcte as (select * from table1)
  insert into table2 values ('hello world');
```

File: src/test/regress/expected/with_modifying.out (hunk 7 above)
Comment (naisila) [reply src/test/regress/expected/with_modifying.out:842]: It's not ignored when the query is an insert query with a select CTE. If it uses router plan, query after rebuilding is not correct.

```SQL
create table table1 (a int);
create table table2 (a text);
select create_distributed_table('table1','a');
select create_distributed_table('table2','a');
with wcte as (select * from table1)
  insert into table2 values ('hello world');
```
Errors out as:
```SQL
DEBUG:  StartTransaction(1) name: unnamed; blockState: DEFAULT; state: INPROGRESS, xid/subid/cid: 0/1/0
DEBUG:  Creating router plan
DEBUG:  query has a single distribution column value: hello world
DEBUG:  query before rebuilding: (null)
DEBUG:  query after rebuilding:  WITH wcte AS (SELECT table1.a FROM public.table1) INSERT INTO public.table2_102063 (a) VALUES ('hello world'::text)
DEBUG:  assigned task 0 to node localhost:9702
DEBUG:  opening 1 new connections to localhost:9702
DEBUG:  established connection to localhost:9702 for session 10
NOTICE:  issuing WITH wcte AS (SELECT table1.a FROM public.table1) INSERT INTO public.table2_102063 (a) VALUES ('hello world'::text)
DETAIL:  on server postgres@localhost:9702 connectionId: 7
ERROR:  relation "public.table1" does not exist
CONTEXT:  while executing command on localhost:9702
```

This is why I checked this case at `multi_router_planner.c`, and then added a test for it to make sure it doesn't error out.
@onurctirtir also has more detail for your question https://github.com/citusdata/citus/pull/4700#discussion_r578303982

I can try adding a test like @marcocitus  suggested.

File: src/test/regress/expected/multi_router_planner_fast_path.out (hunk 3 above)
Comment (naisila) [reply src/test/regress/expected/multi_router_planner_fast_path.out:2117]: will do 👍

Comment (naisila) [reply src/test/regress/expected/multi_router_planner_fast_path.out:2117]: will do :+1:

File: src/test/regress/expected/single_node.out (hunk 5 above)
Comment (naisila) [reply src/test/regress/expected/single_node.out:753]: sounds good, will add it :+1:

File: src/test/regress/sql/single_node.sql (hunk 6 above)
Comment (naisila) [reply src/test/regress/sql/single_node.sql:450]: Good idea, I will add them at `with_modifying.sql` file

File: src/backend/distributed/planner/multi_router_planner.c (hunk 4 above)
Comment (onurctirtir) [reply src/backend/distributed/planner/multi_router_planner.c:573]: now I understood the difference, I was confused since I couldn't realize that we check for different things in those two if's (`cteQuery->commandType` and `queryTree->commandType`)

**Review by onurctirtir — APPROVED** [review]
LGTM, let's wait for @onderkalaci's final review

**Comment by onderkalaci** [comment]
> INSERT INTO no_index_cleanup(i, t)
VALUES (
  generate_series(1,10),
  repeat('123',5)
) RETURNING *;
DEBUG:  Creating router plan
ERROR:  failed to evaluate partition key in insert
HINT:  try using constant values for partition column
Time: 0.447 ms


Can you please add a regression test like the above?

**Review by onderkalaci — APPROVED** [review]
In the past we allowed INSERTs with CTEs that are SELECT, but as @naisila noted, that was already broken as we were not properly deparsing it. So, with this patch we fix this on top of the assertion failure.

Thanks for adding comprehensive tests @onurctirtir and @naisila.

I have a very minor comments, please consider those before merging.
