### PR TITLE
Fix wrong storage type for foreign tables

### LINKED ISSUE #496: Wrong storage type for table.
According to the [answer](http://stackoverflow.com/a/36898566/4632019)
>We do automatically create shards with storage-type 'f', when you issue master_create_distributed_table.

But 
```
CREATE FOREIGN TABLE "files2" (
  "id" character varying(16) DEFAULT '' NOT NULL,
  "site_id" bigint DEFAULT 0 NOT NULL
) 
SERVER mysql_svr
   OPTIONS (dbname 'test', table_name 'files2');

SELECT master_create_distributed_table( 'files2', 'site_id', 'range');
select master_create_empty_shard( 'files2' );
select * from pg_dist_shard;
 logicalrelid | shardid | shardstorage | shardalias | shardminvalue |    shardmaxvalue    
--------------+---------+--------------+------------+---------------+---------------------
        36465 |  102019 | t            |            |               | 
\d+ files2;
 Foreign table "public.files2"
.....
Server: mysql_svr
FDW Options: (dbname 'test', table_name 'files2')
```
On the worker:
```
\d+ files2_102019 ;
Foreign table "public.files2_102019"
....
Server: mysql_svr_102019
FDW Options: (dbname 'test', table_name 'files2')
```

As you can see the `shardstorage` is 't' but should be 'f' if I understand the stackoverflow [answer](http://stackoverflow.com/a/36898566/4632019) and [this doc](https://www.citusdata.com/docs/citus/5.0/reference/metadata_tables.html#shard-storage-types) right.

### PR DESCRIPTION
**Pull request by byucesoy**
Fixes #496

Previously we do not check whether table is foreign or not while creating empty
shards, and set storage type to 't'(Standard table) or 'c'(Columnar table). Now
if the table is foreign table(but not CStore foreign table) we set storage
type to 'f'(Foreign table). If it is CStore foreign table, we set its storage
type to 'c', i.e. columnar table have priority over foreign table.

I also tested the issue in #497 and it is resolved as well with this change.

Please note that 'c' is only used for CStore tables not for other possible
columnar stores at the moment. Possible improvement could be checking for other
columnar stores, though I am not sure if there is a way to check it for all
other columnar stores.

### CODE REVIEW

**Comment by KES777** [comment]
The remote storage alse may be VIEW: https://github.com/citusdata/citus/issues/538

**Comment by aamederen** [comment]
Adding a test for this change could be beneficial. I think check-multi-fdw is the place here. In that test, we can create an ordinary distributed table and see that shardstorage == 't' for its shard. After that, create a foreign distributed table and see that shardstorage == 'f'.

**Comment by byucesoy** [comment]
I sent a new patch which contains new test to check whether we set shardstorage of foreign tables correctly.

File: src/test/regress/sql/multi_fdw_shardstorage.sql [hunk 1]
```diff
@@ -0,0 +1,40 @@
+--
+-- MULTI_FDW_SHARDSTORAGE
+--
+
+-- Create two tables one regular and one foreign, then check whether
+-- shardstorage is correct
+
```
Comment (aamederen) [inline src/test/regress/sql/multi_fdw_shardstorage.sql]: It would be nice to set shardIDs explicitly before the tests referencing specific shard IDs with something like:
`ALTER SEQUENCE pg_catalog.pg_dist_shardid_seq RESTART 400000;`

**Comment by byucesoy** [comment]
I added explicit shard id and set it to 400000. If you need to, we can change it to more appropriate number when you go over all tests.

**Comment by aamederen** [comment]
Seems nice, rebase and :shipit: .

File: src/test/regress/expected/multi_fdw_shardstorage.out [hunk 2]
```diff
@@ -0,0 +1,63 @@
+--
+-- MULTI_FDW_SHARDSTORAGE
```
Comment (metdos) [inline src/test/regress/expected/multi_fdw_shardstorage.out]: Maybe  MULTI_FDW_STORAGE_TYPE?
Similarly, filename.

**Comment by metdos** [comment]
Can we create hash-partitioned cstore tables? I'm asking this because we have a similar check inside 
master_create_worker_shards()

```
	if (relationKind == RELKIND_FOREIGN_TABLE)
	{
		shardStorageType = SHARD_STORAGE_FOREIGN;
	}
```

File: src/backend/distributed/master/master_stage_protocol.c [hunk 3]
```diff
@@ -84,14 +84,29 @@ master_create_empty_shard(PG_FUNCTION_ARGS)
...
-		storageType = SHARD_STORAGE_COLUMNAR;
+		if (CStoreTable(relationId))
+		{
+			storageType = SHARD_STORAGE_COLUMNAR;
+		}
+		else
+		{
+			storageType = SHARD_STORAGE_FOREIGN;
+		}
 	}
```
Comment (aamederen) [inline src/backend/distributed/master/master_stage_protocol.c]: This code assumes that relationKind can be either a foreign table or normal table.

A similar check is also done in master_get_table_metadata(): 
```
	if (relationType == RELKIND_RELATION)
	{
		storageType = SHARD_STORAGE_TABLE;
	}
	else if (relationType == RELKIND_FOREIGN_TABLE)
	{
		bool cstoreTable = CStoreTable(relationId);
		if (cstoreTable)
		{
			storageType = SHARD_STORAGE_COLUMNAR;
		}
		else
		{
			storageType = SHARD_STORAGE_FOREIGN;
		}
	}
```

Possibilities for get_rel_relkind output can be found in pg_class.h:
```
RELKIND_RELATION		
RELKIND_INDEX			
RELKIND_SEQUENCE		
RELKIND_TOASTVALUE	
RELKIND_VIEW			
RELKIND_COMPOSITE_TYPE
RELKIND_FOREIGN_TABLE 
RELKIND_MATVIEW	
```	

In our case, can relationType be something other than RELKIND_RELATION and RELKIND_FOREIGN_TABLE (for example a view or something  If so, what should we do then?

Comment (aamederen) [inline src/backend/distributed/master/master_stage_protocol.c]: We also have SHARD_STORAGE_RELAY type but I could not found any usage for it. @metdos do you know what it is?

File: src/backend/distributed/master/master_create_shards.c [hunk 4]
```diff
@@ -158,7 +159,14 @@ master_create_worker_shards(PG_FUNCTION_ARGS)
 	/* set shard storage type according to relation type */
 	if (relationKind == RELKIND_FOREIGN_TABLE)
 	{
-		shardStorageType = SHARD_STORAGE_FOREIGN;
+		if (cstoreTable)
```
Comment (metdos) [inline src/backend/distributed/master/master_create_shards.c]: We can define cstoreTable here because we don't use it anywhere else. Similarly for other changes.

File: src/backend/distributed/master/master_stage_protocol.c (hunk 3 above)
Comment (metdos) [inline src/backend/distributed/master/master_stage_protocol.c]: > We also have SHARD_STORAGE_RELAY type but I could not found any usage for it. @metdos do you know what it is?

The comment where it is defined has a note about it.
"Relay file types are currently unused."

**Comment by byucesoy** [comment]
@metdos I changed the scope of cstoreTable and fix the issue in `master_create_worker_shards()`

@aamederen We error out other kinds of relations at CheckDistributedTable()

**Comment by aamederen** [comment]
Looks good, rebase and :shipit:
