### PR TITLE
Fixes bug about int and smallint sequences on MX

### LINKED ISSUE #5126: int and smallint sequences on MX only support 7 workers in the cluster
To reproduce:
```
make install-all -j20 && make -C src/test/regress/ check-minimal EXTRA_TESTS='multi_sequence_default'
```

You will see an error like this:
```diff
INSERT INTO sequence_default.seq_test_4 VALUES (1,2) RETURNING *;
- x | y | a | b
----------------------------------------------------------------------
- 1 | 2 | | 268435457
-(1 row)
-
+ERROR: integer out of range
```

The reason for this is that, when run like this the node with `worker_1_port` has `groupid` 14. For `int` and `smallint` sequences we only use 3 bytes to encode the groupid (really 4 bytes, but because we don't use negative numbers 1 byte is "lost"). This creates a limit of 7 worker nodes and 1 coordinator. Nodes after that would use a range that's invalid for the specified types.

There's a decision to be made here. Either we disallow `int` and `smallint` sequences in `MX` completely (and thus also `serial` and `smallserial`). This would be a breaking change for customers using MX with 7 worker nodes or less. The second option is that we only disallow it for nodes with a groupid larger than 7. This is what we essentially do now, except that the error messages are not clear at all.

The advantage of disallowing it completely, is that otherwise people will start running into it when they want to scale out their cluster, at which point it will likely be very difficult to change the types.

UPDATE: After #5133  was merged it seems that now the behaviour is different again

When you run the following SQL on a cluster where one node has a nodeid that's larger than 7:
```sql
CREATE TABLE t(id serial PRIMARY KEY);
select create_distributed_table('t', 'id');
```

On the master branch `create_distributed_table` fails with following error:
```
ERROR:  22023: MAXVALUE (2147483649) is out of range for sequence data type integer
CONTEXT:  while executing command on localhost:9707
```

On v10.1.1, it doesn't fail during `create_distributed_table`. However, when using MX to insert rows on the node with nodeid > 7, then those inserts will fail with an error like this:
```
insert into t(a) SELECT generate_series(0, 10);
ERROR:  22003: integer out of range
```

### PR DESCRIPTION
**Pull request by naisila**
DESCRIPTION: Fixes bug about int and smallint sequences on MX

Introduce a new udf, `worker_nextval`, which currently errors out, but can be improved in the future to get a globally unique value within int/smallint range for the sequence in MX worker nodes.

TODO:
- [x] Add more comments in the code
- [x] Fix comments in current tests
- [x] Add more tests, especially about setval

Fixes #5126

### CODE REVIEW

File: src/backend/distributed/commands/citus_add_local_table_to_metadata.c [hunk 1]
```diff
@@ -464,9 +464,11 @@ GetShellTableDDLEventsForCitusLocalTable(Oid relationId)
 	 * a sequence.
 	 */
 	bool includeSequenceDefaults = true;
+	bool nextvalInWorkerNode = false;
 
 	List *tableDDLCommands = GetFullTableCreationCommands(relationId,
-														  includeSequenceDefaults);
+														  includeSequenceDefaults,
+														  nextvalInWorkerNode);
```
Comment (marcocitus) [inline src/backend/distributed/commands/citus_add_local_table_to_metadata.c:471]: could this be an enum that encapsulates the 3 values?
- no default
- nextval as default
- worker_nextval as default

File: src/backend/distributed/commands/table.c [hunk 2]
```diff
@@ -1730,6 +1746,17 @@ PostprocessAlterTableStmt(AlterTableStmt *alterTableStatement)
 								{
 									MarkSequenceDistributedAndPropagateDependencies(
 										seqOid);
+									if (pg_get_sequencedef(seqOid)->seqtypid != INT8OID)
+									{
+										appendStringInfo(AT_worker_nextval_query,
+														 "ALTER TABLE %s ALTER COLUMN %s "
+														 "SET DEFAULT worker_nextval('%s'::regclass)",
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:1753]: minor: preferable to use quote_literal_cstr instead of inline quoting

File: src/backend/distributed/commands/table.c [hunk 3]
```diff
@@ -1777,16 +1813,33 @@ PostprocessAlterTableStmt(AlterTableStmt *alterTableStatement)
...
 		const char *sequenceCommand = NULL;
 		foreach_ptr(sequenceCommand, sequenceCommandList)
 		{
 			SendCommandToWorkersWithMetadata(sequenceCommand);
 		}
 
+		if (AT_worker_nextval_query->len > 0)
+		{
+			SendCommandToWorkersWithMetadata((char *) alterTableCommand);
+			SendCommandToWorkersWithMetadata(AT_worker_nextval_query->data);
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:1840]: This solution seems quite messy.

File: src/backend/distributed/commands/table.c [hunk 4]
```diff
@@ -1762,31 +1797,57 @@ PostprocessAlterTableStmt(AlterTableStmt *alterTableStatement)
...
 					}
 				}
 			}
 		}
 	}
 
 	/* for the new sequences coming with this ALTER TABLE statement */
-	if (ShouldSyncTableMetadata(relationId) && ClusterHasKnownMetadataWorkers())
+	if (alterTableDefaultNextvalStmt.len > 0 && ShouldSyncTableMetadata(relationId) &&
+		ClusterHasKnownMetadataWorkers())
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:1820]: we could probably use a single boolean here that gets set above

File: src/backend/distributed/commands/table.c [hunk 5]
```diff
@@ -654,6 +657,14 @@ PreprocessAlterTableStmt(Node *node, const char *alterTableCommand,
 	 */
 	bool deparseAT = false;
 	bool propagateCommandToWorkers = true;
+
+	/*
+	 * Sometimes we want to run a different DDL Command string in MX workers
+	 * For example, in cases where worker_nextval should be used instead
+	 * of nextval() in column defaults with type int and smallint
+	 */
+	bool useInitialDDLCommandString = true;
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:666]: One the one hand this is a bit ugly, but on the other hand, the root of the ugliness is that we use the original command string at all, so I'm happy we're making that explicit.

File: src/backend/distributed/commands/table.c [hunk 6]
```diff
@@ -1762,14 +1788,22 @@ PostprocessAlterTableStmt(AlterTableStmt *alterTableStatement)
...
 				}
 			}
 		}
 	}
 
 	/* for the new sequences coming with this ALTER TABLE statement */
-	if (ShouldSyncTableMetadata(relationId) && ClusterHasKnownMetadataWorkers())
+	bool newSequencesMetadataSync = alterTableDefaultNextvalStmt.len > 0 &&
+									ShouldSyncTableMetadata(relationId) &&
+									ClusterHasKnownMetadataWorkers();
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:1805]: I was thinking we would set newSequencesMetadataSync to true in the places where we generate alterTableDefaultNextvalStmt, which are already conditional on `ShouldSyncTableMetadata(relationId) &&	ClusterHasKnownMetadataWorkers()`

File: src/backend/distributed/commands/table.c [hunk 7]
```diff
@@ -1886,6 +1917,53 @@ get_attrdef_oid(Oid relationId, AttrNumber attnum)
...
+		 * https://github.com/citusdata/citus/issues/5126
+		 */
+		nextval_expr = "worker_nextval";
+	}
+
+	if (typeName == NULL)
+	{
+		appendStringInfo(buf, "ALTER TABLE %s ALTER COLUMN %s "
+							  "SET DEFAULT %s(%s::regclass)",
+						 qualifiedRelationName, colname, nextval_expr,
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:1949]: maybe instead of nextval_expr, we could use `quote_qualified_identifier("pg_catalog", nextvalFunctionName)`

File: src/backend/distributed/commands/table.c [hunk 8]
```diff
@@ -928,7 +941,11 @@ PreprocessAlterTableStmt(Node *node, const char *alterTableCommand,
 		sqlForTaskList = DeparseTreeNode((Node *) newStmt);
 	}
 
-	ddlJob->commandString = alterTableCommand;
+	ddlJob->commandString = NULL;
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:944]: I wouldn't mind if this said `useInitialDDLCommandString ? alterTableCommand : NULL`

File: src/backend/distributed/commands/table.c [hunk 9]
```diff
@@ -1886,6 +1917,53 @@ get_attrdef_oid(Oid relationId, AttrNumber attnum)
...
+static void
+AppendAlterTableWithNextvalDefaultStmt(StringInfo buf, Oid sequenceOid, Oid relationId,
+									   char *colname, TypeName *typeName)
+{
+	char *qualifiedSequenceName = generate_qualified_relation_name(sequenceOid);
+	char *qualifiedRelationName = generate_qualified_relation_name(relationId);
+
+	char *nextval_expr = "nextval";
+	bool use_worker_nextval = (pg_get_sequencedef(sequenceOid)->seqtypid != INT8OID);
+	if (use_worker_nextval)
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:1935]: unusual variable naming schema

File: src/backend/distributed/commands/utility_hook.c [hunk 10]
```diff
@@ -891,7 +891,10 @@ ExecuteDistributedDDLJob(DDLJob *ddlJob)
 				SendCommandToWorkersWithMetadata(setSearchPathCommand);
 			}
 
-			SendCommandToWorkersWithMetadata((char *) ddlJob->commandString);
+			if (ddlJob->commandString != NULL)
+			{
+				SendCommandToWorkersWithMetadata((char *) ddlJob->commandString);
```
Comment (marcocitus) [inline src/backend/distributed/commands/utility_hook.c:896]: Optional: I'm wondering whether we should have a separate field for the metadata syncing, e.g. `ddlJob->metadataSyncCommand` that can sometimes be NULL.

File: src/backend/distributed/commands/table.c (hunk 6 above)
Comment (naisila) [reply src/backend/distributed/commands/table.c:1805]: Right, much better to do it there

File: src/backend/distributed/commands/utility_hook.c (hunk 10 above)
Comment (naisila) [reply src/backend/distributed/commands/utility_hook.c:896]: From what I checked, current `ddlJob->commandString` is already used only as `metadataSyncCommand` in terms of functionality, so we might as well rename `commandString` to `metadataSyncCommand`

File: src/backend/distributed/commands/table.c [hunk 11]
```diff
@@ -1761,15 +1787,20 @@ PostprocessAlterTableStmt(AlterTableStmt *alterTableStatement)
...
+							command->name, NULL);
 					}
 				}
 			}
 		}
 	}
 
-	/* for the new sequences coming with this ALTER TABLE statement */
-	if (ShouldSyncTableMetadata(relationId) && ClusterHasKnownMetadataWorkers())
+	if (newSequencesMetadataSync)
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:1803]: maybe: needMetadataSyncForNewSequences

File: src/backend/distributed/commands/table.c [hunk 12]
```diff
@@ -1821,15 +1854,10 @@ GetSequenceOid(Oid relationId, AttrNumber attnum)
...
-		{
-			ereport(ERROR, (errmsg(
-								"More than one sequence in a column default"
-								" is not supported for adding local tables to metadata")));
-		}
 		ereport(ERROR, (errmsg(
 							"More than one sequence in a column default"
-							" is not supported for distribution")));
+							" is not supported for distribution "
+							"or for adding local tables to metadata")));
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:1860]: Why did this change?

File: src/backend/distributed/commands/table.c [hunk 13]
```diff
@@ -1886,6 +1914,55 @@ get_attrdef_oid(Oid relationId, AttrNumber attnum)
...
 
+/*
+ * AppendAlterTableWithNextvalDefaultStmt appends a string representing either:
+ * ALTER TABLE ADD COLUMN .. DEFAULT nextval(), if TypeName isn't empty, or
+ * ALTER TABLE ALTER COLUMN .. SET DEFAULT nextval()
+ * If sequence type is not bigint, we use worker_nextval() instead of nextval().
+ */
+static void
+AppendAlterTableWithNextvalDefaultStmt(StringInfo buf, Oid sequenceOid, Oid relationId,
+									   char *colname, TypeName *typeName)
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:1925]: I'd have a slight preference for splitting this up into 2 functions instead of changing the outcome based on typeName.

File: src/backend/distributed/commands/table.c [hunk 14]
```diff
@@ -1728,8 +1747,15 @@ PostprocessAlterTableStmt(AlterTableStmt *alterTableStatement)
 								if (ShouldSyncTableMetadata(relationId) &&
 									ClusterHasKnownMetadataWorkers())
 								{
+									newSequencesMetadataSync = true;
 									MarkSequenceDistributedAndPropagateDependencies(
 										seqOid);
+
+									AppendAlterTableWithNextvalDefaultStmt(
+										&alterTableDefaultNextvalStmt, seqOid,
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:1755]: could AppendAlterTableWithNextvalDefaultStmt just return a char *? The use of StringInfo seems redundant.

**Review by marcocitus — COMMENTED** [review]
This makes sense to me, just some style comments.

File: src/backend/distributed/commands/table.c (hunk 12 above)
Comment (naisila) [reply src/backend/distributed/commands/table.c:1860]: Because I am now calling `GetSequenceOid` before checking the value of `includeSequenceDefaults` (for style reasons) in `pg_get_tableschemadef_string`, which is used in `GetShellTableDDLEventsForCitusLocalTable`, which is called before converting the table to type `CITUS_LOCAL_TABLE`. Hence we wouldn't reach the error for citus local tables.

> I am now calling `GetSequenceOid` before checking the value of `includeSequenceDefaults` (for style reasons)

I can revert this back if it's not a good error message and change the style in `pg_get_tableschemadef_string`

File: src/backend/distributed/commands/table.c [hunk 15]
```diff
@@ -1787,6 +1816,8 @@ PostprocessAlterTableStmt(AlterTableStmt *alterTableStatement)
 			SendCommandToWorkersWithMetadata(sequenceCommand);
 		}
 
+		SendCommandToWorkersWithMetadata(alterTableDefaultNextvalCmd);
+
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:1820]: Could use a comment on why we do it here instead of in ExecuteDistributedDDLJob

File: src/backend/distributed/commands/utility_hook.c (hunk 10 above)
Comment (marcocitus) [reply src/backend/distributed/commands/utility_hook.c:896]: Would be nice

**Review by marcocitus — APPROVED** [review]

File: src/backend/distributed/commands/utility_hook.c (hunk 10 above)
Comment (naisila) [reply src/backend/distributed/commands/utility_hook.c:896]: Let me open a separate PR for that rename, seems out of scope for this PR.
