### PR TITLE
Fixes CREATE INDEX CONCURRENTLY bug

### LINKED ISSUE #4057: CREATE INDEX CONCURRENTLY on a Local Table
```
CREATE TABLE tbl (a int);
CREATE INDEX CONCURRENTLY ON tbl(a);
```
This crashes. It gives an error message if the table is distributed but crashes if it is not.

### PR DESCRIPTION
**Pull request by halilozanakgul**
DESCRIPTION: Fixes the CREATE INDEX CONCURRENTLY with no index name on a local table bug.

Fixes #4057

### CODE REVIEW

File: src/backend/distributed/commands/index.c [hunk 1]
```diff
@@ -411,14 +411,21 @@ PostprocessIndexStmt(Node *node, const char *queryString)
 		return NIL;
 	}
 
+	Oid schemaId = get_namespace_oid(indexStmt->relation->schemaname, true);
```
Comment (marcocitus) [inline src/backend/distributed/commands/index.c:414]: worth adding a comment that we ensure schemaname is not NULL in PreprocessIndexStmt.
