### PR TITLE
Relax reference table restrictions in subquery union pushdowns

### LINKED ISSUE #2518: Subquery pushdown planning with UNION/UNION ALL fails with reference tables
Reported by @saicitus and @marcocitus. I wanted to open an issue to not track of it.

```SQL
 CREATE TABLE test (x int, y int);
 SELECT create_distributed_table('test', 'x');

CREATE TABLE ref (a int, b int);
SELECT create_reference_table('ref');


set client_min_messages TO DEBUG;

-- unnecessarily switch to recursive planning 
 SELECT * FROM (SELECT x, y FROM test JOIN ref ON (x = a) UNION ALL SELECT x, y FROM test) a;
DEBUG:  generating subplan 1_1 for subquery SELECT test.x, test.y FROM (public.test JOIN public.ref ON ((test.x OPERATOR(pg_catalog.=) ref.a)))
DEBUG:  generating subplan 1_2 for subquery SELECT x, y FROM public.test
DEBUG:  Creating router plan
DEBUG:  Plan is router executable
DEBUG:  generating subplan 1_3 for subquery SELECT intermediate_result.x, intermediate_result.y FROM read_intermediate_result('1_1'::text, 'binary'::citus_copy_format) intermediate_result(x integer, y integer) UNION ALL SELECT intermediate_result.x, intermediate_result.y FROM read_intermediate_result('1_2'::text, 'binary'::citus_copy_format) intermediate_result(x integer, y integer)
DEBUG:  Plan 1 query after replacing subqueries and CTEs: SELECT x, y FROM (SELECT intermediate_result.x, intermediate_result.y FROM read_intermediate_result('1_3'::text, 'binary'::citus_copy_format) intermediate_result(x integer, y integer)) a
DEBUG:  Creating router plan
DEBUG:  Plan is router executable
 x | y 
---+---
(0 rows)
```

There is no reason for this query not to pushdown. We seem to have aggressive checks in `DeferErrorIfUnsupportedUnionQuery()` such that it errors out whenever we see a reference table or recurring tuple. The check seems to be added for the following types of queries, which is still valid, so we shouldn't forget those cases:

```SQL
SELECT * FROM 
(
     SELECT * FROM reference_table 
UNION
    SELECT * FROM distributed_table
);
```

### PR DESCRIPTION
**Pull request by mtuncer**
DESCRIPTION: Relax subquery union pushdown restrictions for reference tables

Fixes #2518

### CODE REVIEW

File: src/backend/distributed/planner/query_pushdown_planning.c [hunk 1]
```diff
@@ -1367,6 +1367,11 @@ HasRecurringTuples(Node *node, RecurringTuplesType *recurType)
 			return true;
 		}
 
+		if (FindNodeCheckInRangeTableList(query->rtable, IsDistributedTableRTE))
```
Comment (marcocitus) [inline src/backend/distributed/planner/query_pushdown_planning.c]: I like how small this change is, but this function is becoming a little odd. If I look at the `if (IsA(node, RangeTblEntry))` block it appears as though we return true if any RTE is a reference table. In reality, we already look at all the RTEs here so we would return false if there is a reference table and a distributed table. The function would also behave quite differently if we passed an RTE or rtable directly. It would help to do some refactoring / write this function from scratch.

Comment (onderkalaci) [reply src/backend/distributed/planner/query_pushdown_planning.c]: Here is my take: I think with this change, we're actually breaking `HasRecurringTuples()` function.

I think the right way to do is refactor `DeferErrorIfFromClauseRecurs()` and its callers such that `if (!queryTree->hasSubLinks)` is not there anymore. And, finally, call `DeferErrorIfFromClauseRecurs()` in `DeferErrorIfUnsupportedUnionQuery()`  instead of `HasRecurringTuples()`.

 `DeferErrorIfFromClauseRecurs()` is already broken (e.g., it doesn't do what its name suggests due to the `if` statement) and if we merge this, we'd break `HasRecurringTuples()`.

I think refactoring  is straight forward, simply pull  `if (!queryTree->hasSubLinks)` to the places where `DeferErrorIfFromClauseRecurs()`. 

Does that make sense to you as well?

Comment (mtuncer) [reply src/backend/distributed/planner/query_pushdown_planning.c]: Complication of what we are trying to do is causing the issue
We want HasRecurringTuples to return
1 - true : if the query only has a reference table
2 - true : if the query does not reference any table (function, values etc)
3 - false : if the query references at least one distributed table.

Originally, I want to restrict the function such that it will check if the reference table is involved in a join with a distributed table. But we decided to go with presence of a distributed table instead.

`HasRecurringTuples` is called from 3 external places. 1 call from `IsRecurringRangeTable` and 2 calls from  `DeferErrorIfUnsupportedUnionQuery`. Our starting point was to fix the second call.

`IsRecurringRangeTable` is indirectly called from many other places through `RelationInfoContainsOnlyRecurringTuples` and  `RelationInfoContainsRecurringTuples`. Thus, even though the changes are small, it is affects more places it is intended to do.

Given that, it would have been nicer limiting the change with subquery union pushdown.

@onderkalaci I am not following comment. 

> Here is my take: I think with this change, we're actually breaking HasRecurringTuples() function.

Function was too restrictive. It had (still has) many false positives. This change removes some restrictions and allows some false negatives relying that these would be caught later by join checks.

Let me spend some time on your suggestion on not using HasRecurringTuples.

Comment (mtuncer) [reply src/backend/distributed/planner/query_pushdown_planning.c]: @onderkalaci There are 2 issues with that approach
1 - `DeferErrorIfFromClauseRecurs` only checks distributed table presence in immediate range table entries. Thus if union includes a join wrapped inside another subquery, we won't be able to detect that. This would cause future regressions on this matter.

2 - Less of an issue, we would need to do some more refactoring to return correct error message.

**Comment by onderkalaci** [comment]
> 1 - DeferErrorIfFromClauseRecurs only checks distributed table presence in immediate range table entries. Thus if union includes a join wrapped inside another subquery, we won't be able to detect that. This would cause future regressions on this matter.

But we call it for every single subquery already?
```C
	ExtractQueryWalker((Node *) originalQuery, &subqueryList);
	subqueryList = list_delete(subqueryList, originalQuery);

	/* iterate on the subquery list and error out accordingly */
	foreach(subqueryCell, subqueryList)
	{
		Query *subquery = lfirst(subqueryCell);
		error = DeferErrorIfCannotPushdownSubquery(subquery,
												   outerMostQueryHasLimit);
		if (error)
		{
			return error;
		}
	}
```

**Comment by marcocitus** [comment]
Maybe we should split the problem into two steps, one for correctness and one for a nice error message? 

e.g.
```c
DeferErrorIfUnsupportedUnionQuery
...
if (!FindNodeCheckInRangeTableList(query->rtable, IsDistributedTableRTE))
{
    recurType = FindRecurringTuplesType(leftArgSubquery);
}
...
```

`FindRecurringTuplesType` would basically just be a wrapper around `HasRecurringTuples`. 

Or, if we want to be lazier:
```c

DeferErrorIfUnsupportedUnionQuery
...
if (!FindNodeCheckInRangeTableList(query->rtable, IsDistributedTableRTE))
{
    HasRecurringTuples(leftArgSubquery, &recurType);
}
...
```

**Comment by onderkalaci** [comment]
> Maybe we should split the problem into two steps, one for correctness and one for a nice error message?

We talked with @mtuncer and decided something similar to your suggestion above

File: src/backend/distributed/planner/query_pushdown_planning.c [hunk 2]
```diff
@@ -644,6 +622,50 @@ DeferErrorIfFromClauseRecurs(Query *queryTree)
 }
 
 
+/*
+ * DetermineQueryReturnsRecurringTuples returns tuple recurrence information
```
Comment (onderkalaci) [inline src/backend/distributed/planner/query_pushdown_planning.c]: Hmm, I think having `Query` in the function name is slightly confusing because we're not actually checking all parts of the query.

name suggestion: `FromClauseRecurringTupleType ()`
function comment suggestion: 
```
FromClauseRecurringTupleType recursively checks the query's range table list
 and returns a valid recurring tuple type if there are no distributed tables 
exist. Note that the function recursively checks all subqueries as well. 

If there are several candidate recurring tuples, we'll simply pick the first one.
```

**Comment by mtuncer** [comment]
that looks like the only solution. I will do that once I got a reliable internet connection.

File: src/backend/distributed/planner/query_pushdown_planning.c [hunk 3]
```diff
@@ -644,6 +622,50 @@ DeferErrorIfFromClauseRecurs(Query *queryTree)
...
+ *
+ * Returned information is used to prepare appropriate deferred error
+ * message for subquery pushdown checks.
+ */
+static RecurringTuplesType
+DetermineQueryReturnsRecurringTuples(Query *queryTree)
+{
+	RecurringTuplesType recurType = RECURRING_TUPLES_INVALID;
+
+	if (queryTree->rtable == NIL)
```
[the remark this answers is not in the document]
Comment (mtuncer) [reply src/backend/distributed/planner/query_pushdown_planning.c]: if `queryTree->rtable` is NIL walker function [does not call](https://github.com/postgres/postgres/blob/master/src/backend/nodes/nodeFuncs.c#L2313) `IsDistributedTableRTE`

File: src/backend/distributed/planner/query_pushdown_planning.c [hunk 4]
```diff
@@ -644,6 +622,50 @@ DeferErrorIfFromClauseRecurs(Query *queryTree)
...
+		 * find such conditions in other calls.
+		 */
+		return RECURRING_TUPLES_INVALID;
+	}
+
+	/*
+	 * Try to figure out which type of recurring tuples we have to produce a
+	 * relevant error message. If there are several we'll pick the first one.
+	 */
+	IsRecurringRangeTable(queryTree->rtable, &recurType);
```
[the remark this answers is not in the document]
Comment (mtuncer) [reply src/backend/distributed/planner/query_pushdown_planning.c]: Not mandatory, but good pre-caution. added.

[the remark this answers is not in the document]
Comment (mtuncer) [reply src/backend/distributed/planner/query_pushdown_planning.c]: Nothing sets `recurType` prior to that point. You probably meant after the function call.

[the remark this answers is not in the document]
Comment (mtuncer) [reply src/backend/distributed/planner/query_pushdown_planning.c]: I don't think assert is a good idea there.

File: src/backend/distributed/planner/query_pushdown_planning.c [hunk 5]
```diff
@@ -572,30 +573,7 @@ DeferErrorIfFromClauseRecurs(Query *queryTree)
...
-	}
-
-
-	/*
-	 * Try to figure out which type of recurring tuples we have to produce a
-	 * relevant error message. If there are several we'll pick the first one.
-	 */
-	IsRecurringRangeTable(queryTree->rtable, &recurType);
-
+	recurType = DetermineQueryReturnsRecurringTuples(queryTree);
```
[the remark this answers is not in the document]
Comment (mtuncer) [reply src/backend/distributed/planner/query_pushdown_planning.c]: Think we talked about moving this outside when we wanted to call `DeferErrorIfFromClauseRecurs` for union pushdown too. But later decided to refactor search code into `DetermineQueryReturnsRecurringTuples` and call that function from both sides instead.

So I am more inclined to keep it this way.

File: src/backend/distributed/planner/query_pushdown_planning.c [hunk 6]
```diff
@@ -1367,6 +1389,7 @@ HasRecurringTuples(Node *node, RecurringTuplesType *recurType)
 			return true;
 		}
 
+
```
[the remark this answers is not in the document]
Comment (mtuncer) [reply src/backend/distributed/planner/query_pushdown_planning.c]: removed

File: src/backend/distributed/planner/query_pushdown_planning.c (hunk 2 above)
Comment (mtuncer) [reply src/backend/distributed/planner/query_pushdown_planning.c]: We are also interested in the recurrence type to provide a customized error message.  So I am not in favor for having a bool function. 

Agreed that it could have a better name

File: src/test/regress/expected/multi_subquery_complex_reference_clause.out [hunk 7]
```diff
@@ -150,30 +150,46 @@ WHERE subquery_1.user_id = subquery_2.user_id ;
...
-  -- Should be able to push down since reference tables are inner joined
-  -- with hash distributed tables, the results of those joins are the parts of
-  -- an outer join
-SELECT subquery_2.id FROM
-  (SELECT tt1.user_id, random() FROM user_buy_test_table AS tt1 JOIN users_return_test_table as tt2
-    ON tt1.user_id = tt2.user_id) subquery_1
-  RIGHT JOIN
-  (SELECT tt1.user_id, ref.id, random() FROM user_buy_test_table as tt1 JOIN users_ref_test_table as ref
-   ON tt1.user_id = ref.id) subquery_2 ON subquery_1.user_id = subquery_2.user_id ORDER BY 1 DESC LIMIT 5;
+-- Should be able to push down since reference tables are inner joined
```
Comment (onderkalaci) [inline src/test/regress/expected/multi_subquery_complex_reference_clause.out]: As far as I can see, we don't have tests that triggers the following two cases:

- We're recursively planning an unrelated part of the query, but still be able to pushdown the UNION query
- We're recursively planning an unrelated part of the query, and cannot pushdown the UNION because there is no distribution key equality.

I can hear your complaints that these cases are not directly related to your changes. That's true, they are semi-related since they involve reference table JOIN dist table, and unrelated intermediate results. Still, I'd be happy to have these tests as well.

I'm giving two example queries based on the tables [here](https://github.com/citusdata/citus/issues/2518#issue-387260734). 


```SQL

SELECT *
FROM
  (SELECT test.x,
          test.y
   FROM REF
   JOIN test ON (test.x = ref.a)
   WHERE a IN
       (SELECT y
        FROM test)
   UNION SELECT x,
                y
   FROM test
   WHERE x IN
       (SELECT a
        FROM REF) ) AS fpp;

        
SELECT *
FROM
  (SELECT test.x,
          test.y
   FROM REF
   JOIN test ON (test.x = ref.a)
   WHERE a IN
       (SELECT y
        FROM test)
   UNION SELECT y,
                x
   FROM test
   WHERE x IN
       (SELECT a
        FROM REF) ) AS fpp;
```
