### PR TITLE
Fix memory issues around deparsing index commands 

### LINKED ISSUE #4258: Memory issue in CreateIndexTaskList->deparse_shard_index_statement
Last week's valgrind test reported a memory issue around `CreateIndexTaskList` & `deparse_shard_index_statement`.

As it is an invalid memory-read issue, it is highly possible that we might end up with segfaults or processing garbage values when executing `CREATE INDEX` commands.

See below stack-trace from https://github.com/citusdata/release-test-results/blob/citusbot_valgrind_test_resource_group/10_12_2020_1602495166/periodic_job_results/10_12_2020_1602495166/valgrind_test_log_citus.txt#L19..L46:

```c
==22985== VALGRINDERROR-BEGIN
==22985== Invalid read of size 1
==22985==    at 0x8E5F6F: MemoryContextStrdup (mcxt.c:1151)
==22985==    by 0x8E5FAD: pstrdup (mcxt.c:1163)
==22985==    by 0x69EF2A: _copyIndexStmt (copyfuncs.c:3460)
==22985==    by 0x69AC0C: copyObjectImpl (copyfuncs.c:5251)
==22985==    by 0x5B31B6: transformIndexStmt (parse_utilcmd.c:2630)
==22985==    by 0x10445BD4: deparse_shard_index_statement (citus_ruleutils.c:669)
==22985==    by 0x1042EBE5: CreateIndexTaskList (index.c:660)
==22985==    by 0x1042F6BE: PreprocessIndexStmt (index.c:193)
==22985==    by 0x1043E042: multi_ProcessUtility (utility_hook.c:388)
==22985==    by 0x12D30EF7: pgss_ProcessUtility (pg_stat_statements.c:1002)
==22985==    by 0x7AA35B: ProcessUtility (utility.c:356)
==22985==    by 0x7A6C8E: PortalRunUtility (pquery.c:1175)
==22985==  Address 0x1dbdf004 is 7,092 bytes inside a recently re-allocated block of size 8,192 alloc'd
==22985==    at 0x4C29F73: malloc (vg_replace_malloc.c:309)
==22985==    by 0x8DD0B4: AllocSetAlloc (aset.c:914)
==22985==    by 0x8E54B3: palloc (mcxt.c:938)
==22985==    by 0x67D372: initStringInfo (stringinfo.c:50)
==22985==    by 0x8649F4: quote_qualified_identifier (ruleutils.c:10733)
==22985==    by 0x10445BED: deparse_shard_index_statement (citus_ruleutils.c:671)
==22985==    by 0x1042EBE5: CreateIndexTaskList (index.c:660)
==22985==    by 0x1042F6BE: PreprocessIndexStmt (index.c:193)
==22985==    by 0x1043E042: multi_ProcessUtility (utility_hook.c:388)
==22985==    by 0x12D30EF7: pgss_ProcessUtility (pg_stat_statements.c:1002)
==22985==    by 0x7AA35B: ProcessUtility (utility.c:356)
==22985==    by 0x7A6C8E: PortalRunUtility (pquery.c:1175)
==22985== 
==22985== VALGRINDERROR-END
```

### PR DESCRIPTION
**Pull request by onurctirtir**
DESCRIPTION: Fixes memory issues around deparsing index commands

Fixes #4258

------

When calling `AppendShardIdToName`, doing below is problematic:

```c
// assume we already have "char *originalStringToAppend"
char *anotherStrReference = originalStringToAppend;
AppendShardIdToName(&anotherStrReference);
```

This is because, `AppendShardIdToName` might invalidate `originalStringToAppend` as it calls `repalloc`.

If we want to update the original string here, either:
* we should assign `anotherStrReference` back to `originalStringToAppend` after calling AppendShardIdToName(`anotherStrReference`) or,
* we should directly pass `&stringToAppend` to `AppendShardIdToName`.

Or, if we don't want to update the original string here, we should instead do:

```c
// assume we already have "char *originalStringToAppend"
char *anotherStrReference = pstrdup(originalStringToAppend);
AppendShardIdToName(&anotherStrReference);
```

Please also see (see https://github.com/citusdata/citus/issues/4258#issuecomment-713709216).

-----

(For easier review, split the work into commits, I will remove reference to issue
number in commit message and squash commits before merging)

First commit (35fd53e) fixes https://github.com/citusdata/citus/issues/4258.
Then I looked into all usages of `AppendShardIdToName` in codebase, and a similar pattern exists in in the same file, in `deparse_shard_reindex_statement`, second commit (5b26824) fixes this.

----

I tested the pr by running `make check-base-vg` with pg13.0. However, I'm planning to start a custom valgrind job with `make check-multi-vg` after merging the pr.

Unfortunately I cannot add a regression test for that, any ideas ?

### CODE REVIEW

**Comment by onderkalaci** [comment]
> If we want to update the original string here, either:

I don't think we'd ever need that?

File: src/backend/distributed/deparser/citus_ruleutils.c [hunk 1]
```diff
@@ -684,12 +684,13 @@ deparse_shard_index_statement(IndexStmt *origStmt, Oid distrelid, int64 shardid,
 							  StringInfo buffer)
 {
 	IndexStmt *indexStmt = copyObject(origStmt); /* copy to avoid modifications */
-	char *relationName = indexStmt->relation->relname;
-	char *indexName = indexStmt->idxname;
 
 	/* extend relation and index name using shard identifier */
-	AppendShardIdToName(&relationName, shardid);
-	AppendShardIdToName(&indexName, shardid);
+	AppendShardIdToName(&(indexStmt->relation->relname), shardid);
```
Comment (onderkalaci) [inline src/backend/distributed/deparser/citus_ruleutils.c:689]: I cannot follow how this solves the issue. Why don't we use your regular steps?
```C
char *shardName = pstrdup(indexStmt->relation->relname);
AppendShardIdToName(&relationName, shardid);

char *shardIndexName = pstrdup(indexStmt-> idxname);
AppendShardIdToName(&shardIndexName, shardid);
```

Comment (onderkalaci) [reply src/backend/distributed/deparser/citus_ruleutils.c:689]: Ok, sorry. This is slightly different that what  we typically do as we call `transformIndexStmt` on `indexStmt`.

Let  me think a bit more

**Comment by onurctirtir** [comment]
> > If we want to update the original string here, either:
> 
> I don't think we'd ever need that?

Actually it seems that we heavily do that:
https://github.com/citusdata/citus/blob/a58a4395abec1e38d83629b66d1b33766c040897/src/backend/distributed/relay/relay_event_utility.c#L399-L433

```c
			IndexStmt *indexStmt = (IndexStmt *) parseTree;
			char **relationName = &(indexStmt->relation->relname);
			char **indexName = &(indexStmt->idxname);
			char **relationSchemaName = &(indexStmt->relation->schemaname);
                        .........
			AppendShardIdToName(relationName, shardId);
			AppendShardIdToName(indexName, shardId);
```

File: src/backend/distributed/deparser/citus_ruleutils.c (hunk 1 above)
Comment (onurctirtir) [reply src/backend/distributed/deparser/citus_ruleutils.c:689]: As we first copy `indexStmt`, I thought we might want to replace the strings in `indexStmt` as well.

**Comment by onderkalaci** [comment]
> Actually it seems that we heavily do that:

For `RelayEventExtendNames` I was aware. But, on the coordinator we typically do NOT modify the input statement (e.g., IndexStatement) not to get into trouble as standardProcessUtility also uses it. 

In this case, we already copy the `IndexStatement`, so should be fine, though I was confused to see it.

File: src/backend/distributed/deparser/citus_ruleutils.c (hunk 1 above)
Comment (onderkalaci) [inline src/backend/distributed/deparser/citus_ruleutils.c:689]: a personal taste, I prefer to see this a little more explicit, feel free to ignore:
```C
--- a/src/backend/distributed/deparser/citus_ruleutils.c
+++ b/src/backend/distributed/deparser/citus_ruleutils.c
@@ -683,26 +683,27 @@ void
 deparse_shard_index_statement(IndexStmt *origStmt, Oid distrelid, int64 shardid,
                                                          StringInfo buffer)
 {
-       IndexStmt *indexStmt = copyObject(origStmt); /* copy to avoid modifications */
+       /* we need to copy because we are modifying the origStmt */
+       IndexStmt *indexStmt = copyObject(origStmt);
 
-       /* extend relation and index name using shard identifier */
-       AppendShardIdToName(&(indexStmt->relation->relname), shardid);
-       AppendShardIdToName(&(indexStmt->idxname), shardid);
+       char **relationName = &(indexStmt->relation->relname);
+       char **indexName = &(indexStmt->idxname);
 
-       char *relationName = indexStmt->relation->relname;
-       char *indexName = indexStmt->idxname;
+       /* extend relation and index name using shard identifier on the indexStmt */
+       AppendShardIdToName(relationName, shardid);
+       AppendShardIdToName(indexName, shardid);
 
        /* use extended shard name and transformed stmt for deparsing */
-       List *deparseContext = deparse_context_for(relationName, distrelid);
+       List *deparseContext = deparse_context_for(*relationName, distrelid);
        indexStmt = transformIndexStmt(distrelid, indexStmt, NULL);
 
        appendStringInfo(buffer, "CREATE %s INDEX %s %s %s ON %s USING %s ",
                                         (indexStmt->unique ? "UNIQUE" : ""),
                                         (indexStmt->concurrent ? "CONCURRENTLY" : ""),
                                         (indexStmt->if_not_exists ? "IF NOT EXISTS" : ""),
-                                        quote_identifier(indexName),
+                                        quote_identifier(*indexName),
                                         quote_qualified_identifier(indexStmt->relation->schemaname,
-                                                                                               relationName),
+                                                                                               *relationName),
                                         indexStmt->accessMethod);
```

**Review by onderkalaci — APPROVED** [review]
Let's see if this fixes the valgrind issue. Can you note on this PR after running the tests again?

File: src/backend/distributed/deparser/citus_ruleutils.c (hunk 1 above)
Comment (onurctirtir) [reply src/backend/distributed/deparser/citus_ruleutils.c:689]: I'm slightly more inclined to make this pr as small as possible, so merging as is

**Comment by onurctirtir** [comment]
>Can you note on this PR after running the tests again?

Valgrind tests on pg12.3 is fine:
https://github.com/citusdata/release-test-results/blob/citusbot_valgrind_test_resource_group/10_23_2020_1603476139/periodic_job_results/10_23_2020_1603476139/valgrind_test_log_citus.txt

[Waiting for results on pg13.0]
