### PR TITLE
Not consider subplans in restriction list

### LINKED ISSUE #4678: Nested Select Query with Lateral Crashes
```
create table tbl (a int);
select create_distributed_table('tbl', 'a');

select 1 from (
  select 1 from (
    select 1 from 
      pg_catalog.pg_type,
      lateral (
        select 1 from public.tbl
        where typdefault ~ null
        limit 1) as subq_0
    where (
      select true from pg_catalog.pg_am
      where typdefault > 'a'
    )
  ) as subq_1
) as subq_2;
```

This is found by SQLsmith

### PR DESCRIPTION
**Pull request by SaitTalhaNisanci**
Fixes #4678 

It seems that some of the restriction clauses are not safe to be recursively planned hence we now skip those.

Skipping a clause should not cause any correctness because at worst we will be pulling more data than needed but the final query will have the right filters hence the result will be correct.

### CODE REVIEW

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 1]
```diff
@@ -1885,6 +1885,12 @@ GetRestrictInfoListForRelation(RangeTblEntry *rangeTblEntry,
 			continue;
 		}
 
+		/* Currently we don't know how to process Subplans */
+		if (IsA(restrictionClause, SubPlan))
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1889]: Here we could also put the condition on when we want to continue to also cover other possible failures. I will need to look more into what other types this can or cannot be.

File: src/test/regress/sql/local_table_join.sql [hunk 2]
```diff
@@ -335,6 +335,39 @@ ALTER TABLE local DROP column key3;
...
+        limit 1) as subq_0
+    where (
+      select true from pg_catalog.pg_am
+      where typdefault > 'a'
+    )
+  ) as subq_1
+) as subq_2;
+
+-- sublink
+SELECT COUNT(*) FROM distributed_table JOIN postgres_table using(key)
```
Comment (SaitTalhaNisanci) [inline src/test/regress/sql/local_table_join.sql:360]: I thought this would be a sublink but debugging it doesn't show it as a sublink

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 3]
```diff
@@ -1945,16 +1949,29 @@ RelationRestrictionForRelation(RangeTblEntry *rangeTableEntry,
...
- * IsParam determines whether the given node is a param.
+ * IsNotSafeRestrictionToRecursivelyPlan returns true if the given node
+ * is not a safe restriction to be recursivelly planned.
  */
 static bool
-IsParam(Node *node)
+IsNotSafeRestrictionToRecursivelyPlan(Node *node)
 {
 	if (IsA(node, Param))
+	{
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1959]: Minor: Might be simpler if all the checks in a single if statement?

File: src/test/regress/expected/local_table_join.out [hunk 4]
```diff
@@ -1324,7 +1324,83 @@ DEBUG:  Plan XXX query after replacing subqueries and CTEs: SELECT count(*) AS c
...
+DEBUG:  Plan XXX query after replacing subqueries and CTEs: SELECT 1 FROM (SELECT 1 FROM (SELECT intermediate_result."?column?" FROM read_intermediate_result('XXX_2'::text, 'binary'::citus_copy_format) intermediate_result("?column?" integer)) subq_1("?column?")) subq_2("?column?")
+ ?column?
+---------------------------------------------------------------------
+(0 rows)
+
+-- sublink
+SELECT COUNT(*) FROM distributed_table JOIN postgres_table using(key)
```
Comment (onderkalaci) [inline src/test/regress/expected/local_table_join.out:1359]: Does this really hit the sublink check in the tests? (it might not be possible to hit that check easily)

Comment (SaitTalhaNisanci) [reply src/test/regress/expected/local_table_join.out:1359]: this doesn't, see https://github.com/citusdata/citus/pull/4679/files#r573650595

Comment (SaitTalhaNisanci) [reply src/test/regress/expected/local_table_join.out:1359]: Also we can see that it doesn't hit the check from the filters that we have in the subquery (if we were hitting it, we wouldn't have the filters of the sublink)

File: src/test/regress/expected/local_table_join.out [hunk 5]
```diff
@@ -1324,7 +1324,83 @@ DEBUG:  Plan XXX query after replacing subqueries and CTEs: SELECT count(*) AS c
...
+--Issue 4678
+create table tbl (a int);
+select create_distributed_table('tbl', 'a');
+ create_distributed_table
+---------------------------------------------------------------------
+
+(1 row)
+
+-- subplans work but we might skip the restrictions in them
+select 1 from (
```
Comment (onderkalaci) [inline src/test/regress/expected/local_table_join.out:1336]: Is it possible for this query to return any rows? Like, not using `pg_type ` but instead having a custom table and have a result? That'd be great (and compare the result with all tables local)

File: src/test/regress/expected/local_table_join.out [hunk 6]
```diff
@@ -1324,7 +1324,83 @@ DEBUG:  Plan XXX query after replacing subqueries and CTEs: SELECT count(*) AS c
...
+DEBUG:  generating subplan XXX_1 for subquery SELECT key FROM local_table_join.distributed_table_pkey WHERE (key OPERATOR(pg_catalog.=) 5)
+DEBUG:  Plan XXX query after replacing subqueries and CTEs: SELECT count(*) AS count FROM ((SELECT distributed_table_pkey_1.key, NULL::text AS value, NULL::jsonb AS value_2 FROM (SELECT intermediate_result.key FROM read_intermediate_result('XXX_1'::text, 'binary'::citus_copy_format) intermediate_result(key integer)) distributed_table_pkey_1) distributed_table_pkey JOIN local_table_join.postgres_table USING (key)) WHERE (distributed_table_pkey.key OPERATOR(pg_catalog.=) ANY (SELECT intermediate_result.key FROM read_intermediate_result('XXX_1'::text, 'binary'::citus_copy_format) intermediate_result(key integer)))
+ count
+---------------------------------------------------------------------
+   100
+(1 row)
+
+SELECT COUNT(*) FROM distributed_table_pkey JOIN postgres_table using(key)
```
Comment (onderkalaci) [inline src/test/regress/expected/local_table_join.out:1391]: would be good if the queries return rows

**Review by onderkalaci — COMMENTED** [review]
I think this looks good, I have few minor comments, I'd like to see them and approve later

File: src/test/regress/sql/local_table_join.sql (hunk 2 above)
Comment (onderkalaci) [reply src/test/regress/sql/local_table_join.sql:360]: Maybe use subqueries in the target list to generate sublinks?

Comment (SaitTalhaNisanci) [reply src/test/regress/sql/local_table_join.sql:360]: what difference does it have compared to a subquery in WHERE clause?

File: src/test/regress/expected/local_table_join.out (hunk 4 above)
Comment (onderkalaci) [reply src/test/regress/expected/local_table_join.out:1405]: Postgres converts subqueries in WHERE clause to joins, avoiding sublinks more often

**Review by onderkalaci — APPROVED** [review]
