### PR TITLE
Remove placement metadata of reference tables after master_remove_node

### LINKED ISSUE #972: Reference Tables: Removing a new node
Currently, when user tries to remove a node from the cluster, and if there exists an active placement on it, the user ends-up with an error:

```SQL
SELECT master_remove_node('localhost', 9700);   
ERROR:  you cannot remove a node which has active shard placements
```

However, if  there exist any reference tables on the cluster, it'll always be on all nodes and be in an active state. Thus, removing a node becomes impossible.

The simplest way would be to error out with a descriptive message saying that manually remove the metadata and drop the target placement.

A relatively simple solution would be to mark the placements of reference tables on the removed node as `INACTIVE` under the covers and so allow the `remove_node` operation. (Or even remove the related rows from `pg_dist_shard_placement`)

The more comprehensive solution would be to drop the placements of all reference tables on the removed node first, and then proceed with the operation. But, I guess some users may not want to the placements being dropped.

We marked this nice-to-have for 6.1. But, I think it is worth implementing the simplest solution at least.

This is semi-related to #931

### PR DESCRIPTION
**Pull request by byucesoy**
Fixes #972 

With this change, we start to delete placement of reference tables at given worker node after master_remove_node UDF call. We remove placement metadata at master node but we do not drop actual shard from the worker node. There are two reasons for that decision, first, it is not critical to DROP the shards in the workers because Citus will ignore them as long as node is removed from cluster and if we add that node back to cluster we will DROP and recreate all reference tables. Second, if node is unreachable, it becomes complicated to cover failure cases and have a transaction support.

### CODE REVIEW

File: src/backend/distributed/utils/reference_table_utils.c [hunk 1]
```diff
@@ -319,6 +322,57 @@ CreateReferenceTableColocationId()
...
+
+		DeleteShardPlacementRow(shardId, workerName, workerPort);
+	}
+
+	/*
+	 * After deleting reference tables placements, we will update replication factor
+	 * column for colocation group of reference tables so that replication factor will
+	 * be equal to worker count again.
+	 */
+	workerNodeList = WorkerNodeList();
```
Comment (onderkalaci) [inline src/backend/distributed/utils/reference_table_utils.c]: Note that this line relies on `DeleteNodeRow()` being called before calling this function. So, if you move `DeleteAllReferenceTablePlacementsFromNode ()` you need to make sure that we update colocation information with the correct worker count.

File: src/backend/distributed/utils/reference_table_utils.c [hunk 2]
```diff
@@ -319,6 +322,57 @@ CreateReferenceTableColocationId()
...
+	List *workerNodeList = NIL;
+	int workerCount = 0;
+
+	/* if there is no reference table, we do not need to do anything */
+	if (list_length(referenceTableList) == 0)
+	{
+		return;
+	}
+
+	referenceTableList = SortList(referenceTableList, CompareOids);
```
Comment (onderkalaci) [inline src/backend/distributed/utils/reference_table_utils.c]: Maybe a single line comment why are we sorting the table list? Is that to prevent deadlocks among concurrent `remove_node()` calls?

File: src/test/regress/sql/multi_remove_node_reference_table.sql [hunk 3]
```diff
@@ -0,0 +1,386 @@
...
+     FROM pg_dist_partition
+     WHERE logicalrelid = 'remove_node_reference_table'::regclass);
+
+
+-- remove same node twice
+SELECT master_remove_node('localhost', :worker_2_port);
+
+-- re-add the node for next tests
+SELECT master_add_node('localhost', :worker_2_port);
+UPDATE pg_dist_shard_placement SET shardstate = 3 WHERE nodeport = :worker_2_port;
```
Comment (onderkalaci) [inline src/test/regress/sql/multi_remove_node_reference_table.sql]: As I noted earlier, we should not need to set `shardstate` to `3`. In fact, it is never possible to set shard state of reference tables to `3` for reference tables.

**Comment by metdos** [comment]
Hey @onderkalaci, this is again ready for you to review.

File: src/backend/distributed/utils/reference_table_utils.c [hunk 4]
```diff
@@ -319,6 +326,62 @@ CreateReferenceTableColocationId()
...
+	List *referenceTableList = ReferenceTableOidList();
+	ListCell *referenceTableCell = NULL;
+
+	Oid firstReferenceTableId = InvalidOid;
+	uint32 referenceTableColocationId = INVALID_COLOCATION_ID;
+
+	List *workerNodeList = NIL;
+	int workerCount = 0;
+
+	/* if there is no reference table, we do not need to do anything */
```
Comment (byucesoy) [inline src/backend/distributed/utils/reference_table_utils.c]: I think both versions can be used but I changed to yours anyway

File: src/backend/distributed/utils/node_metadata.c [hunk 5]
```diff
@@ -356,6 +358,28 @@ RemoveNodeFromCluster(char *nodeName, int32 nodePort, bool forceRemove)
...
 
+	/*
+	 * We do not allow master_remove_node and master_disable_node in a transaction
+	 * used by previous operations. That is because if this transaction is used
+	 * by other operations, connection management will be responsible for setting
+	 * shard state of related placements. However we will delete these shard
+	 * placements, so they will not be available when connection management tries
+	 * to set their shard state.
+	 */
+	if (XactModificationLevel > XACT_MODIFICATION_NONE)
```
Comment (onderkalaci) [inline src/backend/distributed/utils/node_metadata.c]: Should be fine to remove this once you rebase from the master

**Comment by byucesoy** [comment]
@onderkalaci I rebased the PR and tested latest changes.

**Comment by onderkalaci** [comment]
@byucesoy 

This is a conditional :shipit: . Feel free to merge it after applying the following changes

- [ ] I think the commit message and the PR description is not accurate for the connection/transaction management. The problem we've solved was related to existing `SESSION_LIFESPAN` connections, not related to `DROP shard` command that we'd send. With the current master branch, we could actually support transactional `DROP shard` command for reference table placements. However, we choose not to do that for two reasons: (i) That's not needed since we'll re-create the placement if a node is added back. (ii) The node could be actually down, and failure semantics become more complicated in that case. So, could you update the commit message and PR description to reflect those?

- [ ] The value of `workerCount` variable in `DeleteAllReferenceTablePlacementsFromNode ()` is very fragile. It depends on where we call `DeleteNodeRow()`. I'm thinking that we should move updating the reference table colocation group logic into `RemoveNodeFromCluster ()` function itself. So that, it is almost moving [these codes](https://github.com/citusdata/citus/pull/1105/files#diff-6c81f2bdf83dcf330792e96430b0d4a0R370) to  `RemoveNodeFromCluster ()` right afer calling `DeleteAllReferenceTablePlacementsFromNode ()`. In that case, (i) the reader could easily see that we're updating the colocation group with the new worker count (ii) We wouldn't overload `DeleteAllReferenceTablePlacementsFromNode()` function.     (Also, don't forget to update the function comment to reflect the changes)
