### PR TITLE
Deparse ALTER TABLE commands if ADD COLUMN is the only subcommand

### LINKED ISSUE #3678: Adding a column with custom type in custom schema in search_path fails
Adding a column of a custom type that is in the local search path, but not in the global search_path fails

```sql
CREATE SCHEMA foo;
SET search_path TO foo;
CREATE TABLE test (x int, y int);
SELECT create_distributed_table('test','x');
CREATE TYPE xy AS (x int, y int);
ALTER TABLE test ADD COLUMN z xy;
ERROR:  type "xy" does not exist
CONTEXT:  while executing command on localhost:9701
```

The reason is that the type is not qualified when we send the command to alter the shard:
```sql
SELECT worker_apply_shard_ddl_command (102112, 'foo', 'ALTER TABLE test ADD COLUMN z xy;')    
```

Using fully qualified names does work:
```sql
ALTER TABLE foo.test ADD COLUMN z foo.xy;
```

### PR DESCRIPTION
**Pull request by onurctirtir**
Some clients send ALTER TABLE .. ADD COLUMN .. commands together
with some other DDLs and this makes it impossible to directly send
the original DDL command to the workers.

For this reason, this commit adds support for deparsing such ALTER
TABLE commands so that we can avoid from directly sending the original
one to the workers.

Partially fixes https://github.com/citusdata/citus/issues/690.
Fixes #3678

### CODE REVIEW

File: src/backend/distributed/commands/table.c [hunk 1]
```diff
@@ -1439,12 +1432,59 @@ PreprocessAlterTableStmt(Node *node, const char *alterTableCommand,
...
+				/*
+				 * Given that we're in the preprocess, any reference to the
+				 * column that we're adding would break the deparser. This
+				 * can only be the case with CHECK constraints. For this
+				 * reason, we don't allow check constraints to be added by
+				 * using ADD COLUMN subcommands. For other constraint types,
+				 * we prepare the constraint to make sure that we can deparse
+				 * it.
+				 *
+				 * TODO: discuss if we're okay with check constraint limitation
```
Comment (onurctirtir) [inline src/backend/distributed/commands/table.c:1453]: discuss with the team if we're okay with this limitation

File: src/backend/distributed/deparser/deparse_table_stmts.c [hunk 2]
```diff
@@ -208,6 +214,8 @@ AppendAlterTableCmdConstraint(StringInfo buf, Constraint *constraint,
 	}
 	else if (constraint->contype == CONSTR_EXCLUSION)
 	{
+		/* TODO: check if possible with ADD COLUMN */
```
Comment (onurctirtir) [inline src/backend/distributed/deparser/deparse_table_stmts.c:217]: Postgres docs don't claim support for adding exclusion constraints by using ADD COLUMN subcommands, make sure that this is the case.

File: src/backend/distributed/deparser/deparse_table_stmts.c [hunk 3]
```diff
@@ -497,23 +569,81 @@ AppendAlterTableCmdAddColumn(StringInfo buf, AlterTableCmd *alterTableCmd)
...
+							 DeparseRowExprForColumnDefault(relationId, typeOid, typmod,
+															columnDefinition->colname,
+															constraint->raw_expr));
+		}
+		else if (constraint->contype == CONSTR_IDENTITY)
+		{
+			appendStringInfo(buf, " GENERATED %s AS IDENTITY",
+							 GeneratedWhenStr(constraint->generated_when));
+
+			/* TODO: add sequence_options */
```
Comment (onurctirtir) [inline src/backend/distributed/deparser/deparse_table_stmts.c:606]: .

File: src/backend/distributed/deparser/deparse_table_stmts.c [hunk 4]
```diff
@@ -497,23 +569,81 @@ AppendAlterTableCmdAddColumn(StringInfo buf, AlterTableCmd *alterTableCmd)
...
+		}
+		else if (constraint->contype == CONSTR_GENERATED)
+		{
+			/* TODO: appropriate to use DeparseRowExprForColumnDefault? */
```
Comment (onurctirtir) [inline src/backend/distributed/deparser/deparse_table_stmts.c:610]: .

File: src/backend/distributed/commands/table.c (hunk 1 above)
Comment (onurctirtir) [reply src/backend/distributed/commands/table.c:1453]: check if the workaround proposal is applicable for django

Comment (marcocitus) [reply src/backend/distributed/commands/table.c:1453]: I feel like we're going down a rabbit hole where we keep putting more stuff (special case logic) into preprocess to work around the fact that a lot of our logic was supposed to be in postprocess.

I think we could tolerate it to fix the Django issue, but it's a bit concerning.

File: src/test/regress/expected/multi_alter_table_statements.out [hunk 5]
```diff
@@ -1236,33 +1286,148 @@ ALTER TABLE test_table_1 ADD COLUMN test_col int PRIMARY KEY;
...
-ALTER TABLE test_table_1 ADD COLUMN test_col int REFERENCES reference_table(i) ON DELETE CASCADE ON UPDATE SET NULL;
-ERROR:  cannot execute ADD COLUMN command with PRIMARY KEY, UNIQUE, FOREIGN and CHECK constraints
-DETAIL:  Adding a column with a constraint in one command is not supported because all constraints in Citus must have explicit names
-HINT:  You can issue each command separately such as ALTER TABLE test_table_1 ADD COLUMN test_col data_type; ALTER TABLE test_table_1 ADD CONSTRAINT constraint_name FOREIGN KEY (test_col) REFERENCES reference_table(i) ON DELETE CASCADE ON UPDATE SET NULL;
-DROP TABLE reference_table;
+ALTER TABLE test_table_1 ADD COLUMN test_col_1 int REFERENCES reference_table(i) ON DELETE CASCADE;
+ALTER TABLE test_table_1 ADD COLUMN test_col_2 int REFERENCES reference_table(i) ON DELETE CASCADE ON UPDATE SET NULL;
+SELECT result FROM run_command_on_all_nodes(
+$$
+  SELECT jsonb_pretty(jsonb_agg(to_jsonb(q1.*) ORDER BY q1.*)) AS n_fkey_with_config FROM (
```
Comment (onurctirtir) [inline src/test/regress/expected/multi_alter_table_statements.out:1302]: Replace the query with a function call to the one defined in helpers.sql

File: src/backend/distributed/deparser/deparse_table_stmts.c [hunk 6]
```diff
@@ -445,28 +494,77 @@ AppendAlterTableCmd(StringInfo buf, AlterTableCmd *alterTableCmd, AlterTableStmt
...
+	}
+}
+
+
+/*
+ * DeparseRowExprForColumnDefault returns string representation of given
+ * rawExpr based on given column type information.
+ */
+static char *
+DeparseRowExprForColumnDefault(Oid relationId, Oid columnTypeId, int32 columnTypeMod,
```
Comment (onurctirtir) [inline src/backend/distributed/deparser/deparse_table_stmts.c:528]: -> DeparseRaw..

File: src/test/regress/expected/multi_alter_table_statements.out [hunk 7]
```diff
@@ -823,15 +841,17 @@ SELECT relname, reloptions FROM pg_class WHERE relname = 'lineitem_alter';
...
 \c - - - :worker_1_port
-SELECT relname, reloptions FROM pg_class WHERE relname LIKE 'lineitem_alter%' AND relname <> 'lineitem_alter_220002' /* failed copy trails */ ORDER BY relname;
+SELECT relname, reloptions FROM pg_class WHERE relname LIKE 'lineitem_alter%' AND relname <> 'lineitem_alter_222002' /* failed copy trails */ ORDER BY relname;
         relname        |   reloptions
 ---------------------------------------------------------------------
  lineitem_alter_220000 | {fillfactor=40}
- lineitem_alter_220001 | {fillfactor=40}
- lineitem_alter_220003 | {fillfactor=40}
+ lineitem_alter_222000 | {fillfactor=40}
+ lineitem_alter_222001 | {fillfactor=80}
```
Comment (onurctirtir) [inline src/test/regress/expected/multi_alter_table_statements.out:849]: Why the fillfactor changed?

File: src/test/regress/expected/multi_alter_table_statements.out [hunk 8]
```diff
@@ -840,15 +860,17 @@ SELECT relname, reloptions FROM pg_class WHERE relname = 'lineitem_alter';
...
-SELECT relname, reloptions FROM pg_class WHERE relname LIKE 'lineitem_alter%'  AND relname <> 'lineitem_alter_220002' /* failed copy trails */ ORDER BY relname;
-        relname        | reloptions
+SELECT relname, reloptions FROM pg_class WHERE relname LIKE 'lineitem_alter%'  AND relname <> 'lineitem_alter_222002' /* failed copy trails */ ORDER BY relname;
+        relname        |   reloptions
 ---------------------------------------------------------------------
  lineitem_alter_220000 |
- lineitem_alter_220001 |
- lineitem_alter_220003 |
+ lineitem_alter_222000 |
+ lineitem_alter_222001 | {fillfactor=80}
```
Comment (onurctirtir) [inline src/test/regress/expected/multi_alter_table_statements.out:868]: Same here

**Comment by marcocitus** [comment]
This also partially fixes https://github.com/citusdata/citus/issues/690

File: src/backend/distributed/deparser/deparse_table_stmts.c [hunk 9]
```diff
@@ -184,14 +201,34 @@ AppendAlterTableCmdAddConstraint(StringInfo buf, Constraint *constraint,
...
+			appendStringInfoString(buf, " WITH(");
+
+			ListCell *defListCell;
+			foreach(defListCell, constraint->options)
+			{
+				DefElem *def = (DefElem *) lfirst(defListCell);
+
+				bool first = (defListCell == list_head(constraint->options));
+				appendStringInfo(buf, "%s%s=%s", first ? "" : ",",
+								 def->defname, defGetString(def));
```
Comment (marcocitus) [inline src/backend/distributed/deparser/deparse_table_stmts.c:227]: is defname guaranteed to never need escaping?

Comment (marcocitus) [reply src/backend/distributed/deparser/deparse_table_stmts.c:227]: also defGetString

File: src/backend/distributed/deparser/deparse_table_stmts.c [hunk 10]
```diff
@@ -478,23 +594,86 @@ AppendAlterTableCmdAddColumn(StringInfo buf, AlterTableCmd *alterTableCmd)
 	typenameTypeIdAndMod(NULL, columnDefinition->typeName, &typeOid, &typmod);
 	appendStringInfo(buf, "%s", format_type_extended(typeOid, typmod,
 													 formatFlags));
-	if (columnDefinition->is_not_null)
+
+	if (columnDefinition->compression)
 	{
-		appendStringInfoString(buf, " NOT NULL");
+		appendStringInfo(buf, " COMPRESSION %s", columnDefinition->compression);
```
Comment (marcocitus) [inline src/backend/distributed/deparser/deparse_table_stmts.c:600]: needs identifier escaping, I think

File: src/backend/distributed/deparser/deparse_table_stmts.c [hunk 11]
```diff
@@ -224,7 +224,8 @@ AppendAlterTableCmdConstraint(StringInfo buf, Constraint *constraint,
 
 				bool first = (defListCell == list_head(constraint->options));
 				appendStringInfo(buf, "%s%s=%s", first ? "" : ",",
-								 def->defname, defGetString(def));
+								 quote_identifier(def->defname),
+								 quote_identifier(defGetString(def)));
```
Comment (marcocitus) [inline src/backend/distributed/deparser/deparse_table_stmts.c:228]: should this be quote_literal_cstr?

File: src/backend/distributed/deparser/deparse_table_stmts.c [hunk 12]
```diff
@@ -445,28 +513,77 @@ AppendAlterTableCmd(StringInfo buf, AlterTableCmd *alterTableCmd, AlterTableStmt
...
  */
 static void
-AppendAlterTableCmdAddColumn(StringInfo buf, AlterTableCmd *alterTableCmd)
+AppendAlterTableCmdAddColumn(StringInfo buf, AlterTableCmd *alterTableCmd,
+							 AlterTableStmt *stmt)
 {
 	Assert(alterTableCmd->subtype == AT_AddColumn);
 
+	LOCKMODE lockmode = AlterTableGetLockLevel(stmt->cmds);
+	Oid relationId = AlterTableLookupRelation(stmt, lockmode);
```
[the remark this answers is not in the document]
Comment (onurctirtir) [reply src/backend/distributed/deparser/deparse_table_stmts.c:581]: Let me instead use NoLock because we should've already locked the rel before the deparser.

File: src/backend/distributed/commands/table.c [hunk 13]
```diff
@@ -1396,14 +1410,23 @@ PreprocessAlterTableStmt(Node *node, const char *alterTableCommand,
...
+			if (columnExists)
+			{
+				/*
+				 * Return NIL regardless of whether IF NOT EXISTS is provided.
+				 * If the column exists and IF NOT EXISTS is provided, standard
+				 * process utility will do nothing. And if that option was not
+				 * provided, standard process utility will throw an error anyway.
+				 */
+				ReleaseSysCache(columnTuple);
+				return NIL;
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:1427]: shouldn't we continue looping over other subcommands?

they might still need to be applied in case of IF NOT EXISTS

Comment (onurctirtir) [reply src/backend/distributed/commands/table.c:1427]: Or maybe we should return NIL if it's the only subcommand and the column already exists. And if it's not the only subcommand and the column already exists, then we should continue the loop without setting deparseAT to true.

Comment (onurctirtir) [reply src/backend/distributed/commands/table.c:1427]: Or maybe for simplicity, we shouldn't return NIL here but teach deparser to add IF NOT EXISTS when needed.

File: src/backend/distributed/commands/table.c [hunk 14]
```diff
@@ -1447,14 +1515,19 @@ PreprocessAlterTableStmt(Node *node, const char *alterTableCommand,
...
-							/* the new column definition will have no constraint */
-							ColumnDef *newColDef = copyObject(columnDefinition);
-							newColDef->constraints = NULL;
-
-							newCmd->def = (Node *) newColDef;
+							/* drop the default expression from new subcomand */
+							ColumnDef *newColumnDef = (ColumnDef *) newCmd->def;
+							newColumnDef->constraints =
+								list_delete_nth_cell(newColumnDef->constraints,
+													 constraintIdx);
```
Comment (onurctirtir) [inline src/backend/distributed/commands/table.c:1522]: I'm not sure if this is the right thing to do.

File: src/backend/distributed/commands/table.c (hunk 13 above)
Comment (marcocitus) [reply src/backend/distributed/commands/table.c:1427]: > Or maybe for simplicity, we shouldn't return NIL here but teach deparser to add IF NOT EXISTS when needed.

seems like a good idea in general

File: src/backend/distributed/relay/relay_event_utility.c [hunk 15]
```diff
@@ -622,6 +599,56 @@ RelayEventExtendNames(Node *parseTree, char *schemaName, uint64 shardId)
...
+		constraint->contype != CONSTR_CHECK)
+	{
+		/*
+		 * constraint->conname could be empty in the case of
+		 * ADD {PRIMARY KEY, UNIQUE} USING INDEX.
+		 * In this case, already extended index name will be used by postgres.
+		 */
+		if (constraint->conname != NULL)
+		{
+			AppendShardIdToName(constraintName, shardId);
```
Comment (marcocitus) [inline src/backend/distributed/relay/relay_event_utility.c:646]: are there any hazards around partitioned tables?

Comment (onurctirtir) [reply src/backend/distributed/relay/relay_event_utility.c:646]: I wouldn't expect such a problem because we perform the necessary checks via PrepareAlterTableStmtForConstraint beforehand.

File: src/test/regress/sql/alter_table_add_column.sql [hunk 16]
```diff
@@ -0,0 +1,71 @@
...
+ALTER TABLE referencing ADD COLUMN test_3 integer GENERATED ALWAYS AS (test_1 * my_random(1)) STORED UNIQUE REFERENCES referenced(int_col) MATCH FULL;
+ALTER TABLE referencing ADD COLUMN test_4 integer PRIMARY KEY WITH (fillfactor=70) NOT NULL REFERENCES referenced(int_col) MATCH SIMPLE ON UPDATE CASCADE ON DELETE SET DEFAULT;
+ALTER TABLE referencing ADD COLUMN test_5 integer CONSTRAINT unique_c UNIQUE WITH (fillfactor=50);
+ALTER TABLE referencing ADD COLUMN test_6 text COMPRESSION pglz COLLATE caseinsensitive NOT NULL;
+ALTER TABLE referencing ADD COLUMN "test_\'!7" "simple_!\'custom_type";
+
+-- we give up deparsing ALTER TABLE command if it needs to create a check constraint, and we fallback to legacy behavior
+ALTER TABLE referencing ADD COLUMN test_8 integer CHECK (test_8 > 0);
+ALTER TABLE referencing ADD COLUMN test_8 integer CONSTRAINT check_test_8 CHECK (test_8 > 0);
+
```
Comment (marcocitus) [inline src/test/regress/sql/alter_table_add_column.sql:41]: I couldn't see any issues, but it would be good to have a more complex GENERATED ALWAYS AS expressions (e.g. stuff from different schemas)

**Review by marcocitus — APPROVED** [review]
A lot of this is a little bit gross, but not really this PR's fault :)
