### PR TITLE
Fix attribute numbers in subquery conversions

### LINKED ISSUE #4416: Assert failure in local table join in subquery
The following steps crash on master:
```sql
CREATE TABLE test (x int, y int);
SELECT create_distributed_table('test','x');

CREATE TABLE local (key1 int, key2 int, key3 int);
ALTER TABLE local DROP COLUMN key2;

SELECT * FROM (SELECT local.key1, local.key3 FROM local JOIN test ON(local.key1 = test.x) GROUP BY local.key1, local.key3) a; 
```

Backtrace:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fb9e1988859 in __GI_abort () at abort.c:79
#2  0x00005574c65efd71 in ExceptionalCondition (conditionName=conditionName@entry=0x5574c67965f3 "!(n < list->length)", 
    errorType=errorType@entry=0x5574c6645028 "FailedAssertion", fileName=fileName@entry=0x5574c67bec1c "list.c", lineNumber=lineNumber@entry=392) at assert.c:54
#3  0x00005574c6393d52 in list_nth_cell (list=0x5574c830d4d0, n=2) at list.c:392
#4  0x00005574c6393d8b in list_nth (list=<optimized out>, n=<optimized out>) at list.c:413
#5  0x00007fb9df72eb49 in FindReferencedTableColumn (columnExpression=columnExpression@entry=0x5574c8301990, parentQueryList=parentQueryList@entry=0x0, 
    query=query@entry=0x5574c82e8eb0, relationId=relationId@entry=0x7fffd89c983c, column=column@entry=0x7fffd89c9840) at planner/multi_logical_optimizer.c:4516
#6  0x00007fb9df72ec8a in IsPartitionColumn (columnExpression=columnExpression@entry=0x5574c8301990, query=query@entry=0x5574c82e8eb0) at planner/multi_logical_optimizer.c:4435
#7  0x00007fb9df7302d0 in TargetListOnPartitionColumn (query=query@entry=0x5574c82e8eb0, targetEntryList=<optimized out>) at planner/multi_logical_planner.c:223
#8  0x00007fb9df73deb3 in DeferErrorIfSubqueryRequiresMerge (subqueryTree=subqueryTree@entry=0x5574c82e8eb0) at planner/query_pushdown_planning.c:1045
#9  0x00007fb9df73e2da in DeferErrorIfCannotPushdownSubquery (subqueryTree=subqueryTree@entry=0x5574c82e8eb0, outerMostQueryHasLimit=outerMostQueryHasLimit@entry=false)
    at planner/query_pushdown_planning.c:940
#10 0x00007fb9df73e627 in CanPushdownSubquery (subqueryTree=subqueryTree@entry=0x5574c82e8eb0, outerMostQueryHasLimit=outerMostQueryHasLimit@entry=false)
    at planner/query_pushdown_planning.c:884
#11 0x00007fb9df73e7ca in ShouldRecursivelyPlanSubquery (subquery=subquery@entry=0x5574c82e8eb0, context=context@entry=0x7fffd89c9a70) at planner/recursive_planning.c:930
#12 0x00007fb9df740349 in RecursivelyPlanSubqueryWalker (node=0x5574c82e8eb0, context=0x7fffd89c9a70) at planner/recursive_planning.c:895
#13 0x00005574c6390f6a in range_table_entry_walker (rte=0x5574c818a5d0, walker=walker@entry=0x7fb9df7402fa <RecursivelyPlanSubqueryWalker>, 
    context=context@entry=0x7fffd89c9a70, flags=flags@entry=0) at nodeFuncs.c:2465
#14 0x00005574c6391009 in range_table_walker (rtable=<optimized out>, walker=walker@entry=0x7fb9df7402fa <RecursivelyPlanSubqueryWalker>, context=context@entry=0x7fffd89c9a70, 
    flags=flags@entry=0) at nodeFuncs.c:2433
#15 0x00005574c6391220 in query_tree_walker (query=query@entry=0x5574c82f3ae0, walker=walker@entry=0x7fb9df7402fa <RecursivelyPlanSubqueryWalker>, 
    context=context@entry=0x7fffd89c9a70, flags=flags@entry=0) at nodeFuncs.c:2410
#16 0x00007fb9df7400d2 in RecursivelyPlanSubqueriesAndCTEs (query=query@entry=0x5574c82f3ae0, context=context@entry=0x7fffd89c9a70) at planner/recursive_planning.c:304
#17 0x00007fb9df740219 in GenerateSubplansForSubqueriesAndCTEs (planId=planId@entry=1, originalQuery=originalQuery@entry=0x5574c82f3ae0, 
    plannerRestrictionContext=plannerRestrictionContext@entry=0x5574c8301fa8) at planner/recursive_planning.c:238
#18 0x00007fb9df7213aa in CreateDistributedPlan (planId=planId@entry=1, originalQuery=0x5574c82f3ae0, query=0x5574c818a6e8, boundParams=0x0, 
    hasUnresolvedParams=hasUnresolvedParams@entry=false, plannerRestrictionContext=0x5574c8301fa8) at planner/distributed_planner.c:978
#19 0x00007fb9df721cd1 in CreateDistributedPlannedStmt (planContext=planContext@entry=0x7fffd89c9bd0) at planner/distributed_planner.c:646
#20 0x00007fb9df722106 in PlanDistributedStmt (planContext=planContext@entry=0x7fffd89c9bd0, rteIdCounter=<optimized out>, rteIdCounter@entry=3)
    at planner/distributed_planner.c:583
#21 0x00007fb9df7223e4 in distributed_planner (parse=0x5574c818a6e8, cursorOptions=256, boundParams=0x0) at planner/distributed_planner.c:231
#22 0x00005574c63f1404 in planner (parse=parse@entry=0x5574c818a6e8, cursorOptions=cursorOptions@entry=256, boundParams=boundParams@entry=0x0) at planner.c:273
#23 0x00005574c64bf5e6 in pg_plan_query (querytree=querytree@entry=0x5574c818a6e8, cursorOptions=cursorOptions@entry=256, boundParams=boundParams@entry=0x0) at postgres.c:878
#24 0x00005574c64bf6bd in pg_plan_queries (querytrees=<optimized out>, cursorOptions=cursorOptions@entry=256, boundParams=boundParams@entry=0x0) at postgres.c:968
#25 0x00005574c64bfaa3 in exec_simple_query (
    query_string=query_string@entry=0x5574c8188a28 "SELECT * FROM (SELECT local.key1, local.key3 FROM local JOIN test ON(local.key1 = test.x) GROUP BY local.key1, local.key3) a;") at postgres.c:1143
#26 0x00005574c64c1b1b in PostgresMain (argc=<optimized out>, argv=argv@entry=0x5574c8225a30, dbname=<optimized out>, username=<optimized out>) at postgres.c:4247
#27 0x00005574c643098e in BackendRun (port=port@entry=0x5574c821f780) at postmaster.c:4494
#28 0x00005574c6433e88 in BackendStartup (port=port@entry=0x5574c821f780) at postmaster.c:4177
#29 0x00005574c64340de in ServerLoop () at postmaster.c:1725
#30 0x00005574c6435671 in PostmasterMain (argc=3, argv=<optimized out>) at postmaster.c:1398
#31 0x00005574c638ed1d in main (argc=3, argv=0x5574c8181b60) at main.c:228
(gdb) 
```

### PR DESCRIPTION
**Pull request by SaitTalhaNisanci**
Attribute number in a subquery RTE and relation RTE means different
things. In a relation attribute number will point to the column number
in the table definition including the dropped columns as well however in
subquery, it means the index in the target list. When we convert a
relation RTE to subquery RTE we should either correct all the relevant
attribute numbers or we can just add a dummy column for the dropped
columns. We choose the latter in this commit because it is practically
too vulnerable to update all the vars in a query.

Another thing this commit fixes is that in case a join restriction
clause list contains a false clause, we should just returns a false
clause instead of the whole list, because the whole list will contain
restrictions from other RTEs as well and this breaks the query, which
can be seen from the output changes, now it is much simpler.

Also instead of adding single tests for dropped columns, we choose to
run the whole mixed queries with tables with dropped columns, this
revealed some bugs already, which are fixed in this commit.

Fixes #4416.

### CODE REVIEW

File: src/backend/distributed/planner/query_colocation_checker.c [hunk 1]
```diff
@@ -347,6 +364,27 @@ CreateAllTargetListForRelation(Oid relationId, List *requiredAttributes)
...
+	{
+		Form_pg_attribute attributeTuple =
+			TupleDescAttr(tupleDesc, attrNum - 1);
+		if (!attributeTuple->attisdropped)
+		{
+			return attributeTuple;
+		}
+	}
+	ereport(ERROR, (errmsg(
+						"Unexpected state: there should be at least one non-dropped column in relation.")));
```
Comment (marcocitus) [inline src/backend/distributed/planner/query_colocation_checker.c:384]: why? :)

File: src/backend/distributed/planner/query_colocation_checker.c [hunk 2]
```diff
@@ -434,6 +473,25 @@ CreateTargetEntryForNullCol(Form_pg_attribute attributeTuple, int resno)
...
 
+/*
+ * CreateTargetEntryForDroppedCol creates a dummy column for the dropped column.
+ */
+static TargetEntry *
+CreateTargetEntryForDroppedCol(Form_pg_attribute attributeTuple, int resno)
+{
+	Expr *nullExpr = (Expr *) makeNullConst(attributeTuple->atttypid,
+											attributeTuple->atttypmod,
+											attributeTuple->attcollation);
```
Comment (marcocitus) [inline src/backend/distributed/planner/query_colocation_checker.c:484]: why do we use values from a completely unrelated column? could we just set this to some arbitrary constants? (e.g. use INT4OID)

File: src/backend/distributed/planner/query_colocation_checker.c (hunk 1 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/query_colocation_checker.c:384]: umm, interesting

File: src/backend/distributed/planner/query_colocation_checker.c (hunk 2 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/query_colocation_checker.c:484]: I guess we could do this, maybe we can do the similar for null target entries, do you think that would be confusing?

Comment (marcocitus) [reply src/backend/distributed/planner/query_colocation_checker.c:484]: at least for dropped columns it would be less confusing than taking some random column

for unused columns, either way works I think

Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/query_colocation_checker.c]: I left the other part as is

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 3]
```diff
@@ -1862,8 +1865,8 @@ GetRestrictInfoListForRelation(RangeTblEntry *rangeTblEntry,
 	List *joinRestrictClauseList = get_all_actual_clauses(joinRestrictInfo);
 	if (ContainsFalseClause(joinRestrictClauseList))
 	{
-		/* found WHERE false, no need  to continue */
-		return copyObject((List *) joinRestrictClauseList);
+		/* found WHERE false, no need  to continue, we just return a false clause */
+		return GetFalseClause(joinRestrictClauseList);
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1869]: We can possible generate a false clause from scratch as well

File: src/backend/distributed/planner/query_colocation_checker.c [hunk 4]
```diff
@@ -388,15 +400,9 @@ CreateFilteredTargetListForRelation(Oid relationId, List *requiredAttributes)
...
-
-	Form_pg_attribute attributeTuple =
-		TupleDescAttr(relation->rd_att, 0);
-	TargetEntry *nullTargetEntry =
-		CreateTargetEntryForNullCol(attributeTuple, 1);
-
-	relation_close(relation, NoLock);
-	return list_make1(nullTargetEntry);
+	int resno = 1;
+	TargetEntry *dummyTargetEntry = CreateTargetEntryForDroppedCol(resno);
```
Comment (marcocitus) [inline src/backend/distributed/planner/query_colocation_checker.c:404]: Maybe CreateNullTargetEntry / CreateUnusedTargetEntry?

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 3 above)
Comment (marcocitus) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:1869]: makes sense

File: src/backend/distributed/planner/query_colocation_checker.c (hunk 4 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/query_colocation_checker.c:404]: Maybe I can have a wrapper around `CreateTargetEntryForDroppedCol` because `CreateTargetEntryForDroppedCol` is specifically used for dropped columns and here we should create a target entry that is similar to a target entry of a dropped column (as we should use the dummy values for the constant). So CreateUnusedTargetEntry could call `CreateTargetEntryForDroppedCol`. We already have CreateNullTargetEntry, which creates a null target entry but it has the actual column types etc.

Comment (marcocitus) [reply src/backend/distributed/planner/query_colocation_checker.c:404]: it's mainly weird to use CreateTargetEntryForDroppedCol for other purposes than dropped columns. Maybe the name should describe what it returns rather than what it is used for?

Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/query_colocation_checker.c:404]: Makes sense

File: src/backend/distributed/planner/query_colocation_checker.c (hunk 1 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/query_colocation_checker.c]: added a basic test for this case as well

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 5]
```diff
@@ -1862,8 +1865,11 @@ GetRestrictInfoListForRelation(RangeTblEntry *rangeTblEntry,
 	List *joinRestrictClauseList = get_all_actual_clauses(joinRestrictInfo);
 	if (ContainsFalseClause(joinRestrictClauseList))
 	{
-		/* found WHERE false, no need  to continue */
-		return copyObject((List *) joinRestrictClauseList);
+		/* found WHERE false, no need  to continue, we just return a false clause */
+		bool value = false;
+		bool isNull = false;
+		List *falseClause = list_make1(makeBoolConst(value, isNull));
+		return falseClause;
```
Comment (marcocitus) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1872]: very minor: I was a bit surprised that falseClause was a list, maybe this can be `return list_make1(falseClause)`  and `falseClause` a `Const`

**Review by marcocitus — APPROVED** [review]
