### PR TITLE
Fix partition column index issue

### LINKED ISSUE #4315: Four-way co-located+repartition join gives incorrect count
Strange issue when combining a co-located join with two re-partition joins.
```sql
create table cars (car_id int);
insert into cars select s from generate_series(1,10) s;

create table trips (trip_id int, car_id int);
insert into trips select s % 10, s % 11 from generate_series(1, 100) s;

select count(*) from trips t1, cars r1, trips t2, cars r2 where t1.trip_id = t2.trip_id and t1.car_id = r1.car_id and t2.car_id = r2.car_id;
 count 
-------
   829
(1 row)

select create_distributed_table('trips', 'trip_id');
select create_distributed_table('cars', 'car_id');

set citus.enable_repartition_joins to on;
set citus.enable_single_hash_repartition_joins to off;
select count(*) from trips t1, cars r1, trips t2, cars r2 where t1.trip_id = t2.trip_id and t1.car_id = r1.car_id and t2.car_id = r2.car_id;
 count 
-------
   125
(1 row)

set citus.enable_single_hash_repartition_joins to on;
select count(*) from trips t1, cars r1, trips t2, cars r2 where t1.trip_id = t2.trip_id and t1.car_id = r1.car_id and t2.car_id = r2.car_id;
 count 
-------
   107
(1 row)

-- no problem with reference tables
select undistribute_table('cars');
select create_reference_table('cars');

select count(*) from trips t1, cars r1, trips t2, cars r2 where t1.trip_id = t2.trip_id and t1.car_id = r1.car_id and t2.car_id = r2.car_id;
 count 
-------
   829
(1 row)

``` 
Has been broken for a while (at least 9.0) .

### PR DESCRIPTION
**Pull request by SaitTalhaNisanci**
We send column names to worker_hash/range_partition_table methods, and
in these methods we check the column name index from tuple descriptor.
Then this index is used to decide the bucket that the current row will
be sent for the repartition.

This becomes a problem when there are the same column names in the
tupleDescriptor. Then we can choose the wrong index. Hence the
partitioned data will be put to wrong workers. Then the result could
miss some data because workers might contain different range of data.

An example:
TupleDescriptor contains "trip_id", "car_id", "car_id" for one table.
It contains only "car_id" for the other table. And assuming that the
tables will be partitioned by car_id, it is not certain what should be
used for deciding the bucket number for the first table. Assuming value
2 goes to bucket 2 and value 3 goes to bucket 3, it is not certain which
bucket "1 2 3" (trip_id, car_id, car_id)  row will go to.

As a solution we send the index of partition column in targetList
instead of the column name.

The old API is kept so that if workers upgrade work, it still works
(though it will have the same bug)

DESCRIPTION: Fixes bug related to correctness of multiple joins

Fixes #4315.

### CODE REVIEW

File: src/backend/distributed/worker/worker_partition_protocol.c [hunk 1]
```diff
@@ -110,12 +111,23 @@ worker_range_partition_table(PG_FUNCTION_ARGS)
 	uint32 taskId = PG_GETARG_UINT32(1);
 	text *filterQueryText = PG_GETARG_TEXT_P(2);
 	text *partitionColumnText = PG_GETARG_TEXT_P(3);
+	char *partitionColumnNameCandidate = text_to_cstring(partitionColumnText);
+
+	char *partitionColumnName = NULL;
+	char *endptr = NULL;
+	uint32 partitionColumnIndex = strtoul(partitionColumnNameCandidate, &endptr,
+										  10 /*base*/);
+	if (endptr == partitionColumnNameCandidate)
```
Comment (marcocitus) [inline src/backend/distributed/worker/worker_partition_protocol.c:120]: this could use a nice and big comment on why we'd do something so crazy :)

Comment (SaitTalhaNisanci) [reply src/backend/distributed/worker/worker_partition_protocol.c]: @marcocitus added a comment

**Review by marcocitus — APPROVED** [review]
all makes sense to me
