### PR TITLE
Do not trigger 2PC for reads on local execution

### LINKED ISSUE #4777: Unexpected error on standby nodes when distributed subplans exists
Queries with intermediate results fail:
```SQL
WITH cte_1 AS (SELECT * FROM test LIMIT 5) SELECT * FROM cte_1;
ERROR:  cannot assign TransactionIds during recovery

 SELECT * FROM (SELECT * FROM test LIMIT 5) as foo;
ERROR:  cannot assign TransactionIds during recovery
Time: 9.145 ms

```

Though regular queries work fine:
```SQL
SELECT * FROM test LIMIT 5;
 a  
----
  1
 15
 25
 63
 82
(5 rows)

Time: 42.151 ms
```

### PR DESCRIPTION
**Pull request by onderkalaci**
Fixes #4777

Before this commit, Citus used 2PC no matter what kind of
local query execution happens.

For example, if the coordinator has shards (and the workers as well),
even a simple SELECT query could start 2PC:
```SQL

WITH cte_1 AS (SELECT * FROM test LIMIT 10) SELECT count(*) FROM cte_1;
```

In this query, the local execution of the shards (and also intermediate
result reads) triggers the 2PC.

To prevent that, Citus now distinguishes local reads and local writes.
And, Citus switches to 2PC only if a modification happens. This may
still lead to unnecessary 2PCs when there is a local modification
and remote SELECTs only. Though, we handle that separately
via #4587.

DESCRIPTION: Fixes a bug that causes SELECT queries to use 2PC unnecessarily

### CODE REVIEW

File: src/backend/distributed/transaction/transaction_management.c [hunk 1]
```diff
@@ -98,7 +98,7 @@ MemoryContext CommitContext = NULL;
  * CoordinatedTransactionUse2PC(), e.g. if DDL was issued and
  * MultiShardCommitProtocol was set to 2PC.
  */
-bool CoordinatedTransactionUses2PC = false;
+bool CoordinatedTransactionShouldUse2PCFlag = false;
```
Comment (onderkalaci) [inline src/backend/distributed/transaction/transaction_management.c:101]: Can we have a better name?

File: src/test/regress/sql/single_node.sql [hunk 2]
```diff
@@ -906,6 +906,60 @@ WITH cte_1 AS
 SELECT bool_and(z is null) FROM cte_1;
 
 RESET citus.local_copy_flush_threshold;
+
+RESET citus.local_copy_flush_threshold;
+
+CREATE OR REPLACE FUNCTION coordinated_transaction_uses_2PC()
+RETURNS BOOL LANGUAGE C STRICT VOLATILE AS 'citus',
+$$coordinated_transaction_uses_2PC$$;
```
Comment (onderkalaci) [inline src/test/regress/sql/single_node.sql:914]: These tests are not strictly necessary with this patch, as it was relevant to the previous patch. But still I didn't remove, just failing over to local host is something that we should be careful and having some extra tests sounds OK to me

File: src/backend/distributed/test/xact_stats.c [hunk 3]
```diff
@@ -54,3 +59,20 @@ MemoryContextTotalSpace(MemoryContext context)
...
 }
+
+
+/*
+ * coordinated_transaction_uses_2PC returns true if the transaction is in a
+ * coordinated transaction and uses 2PC. If the transaction is nott in a
+ * coordinated transaction, the function throws an error.
+ */
+Datum
+coordinated_transaction_uses_2PC(PG_FUNCTION_ARGS)
```
Comment (onderkalaci) [inline src/backend/distributed/test/xact_stats.c:70]: The name should be changed to "should use"

**Review by marcocitus — APPROVED** [review]
Looks good after addressing your comments. 

We always seems to do the right thing now (except in case of modifications that are not handled by Citus).
