### PR TITLE
Check if the limit is null

### LINKED ISSUE #7663: limit null is implementation is broken when offset is used
steps
1. create distribute table
```sql
create table t1(a int, b int);
select create_distributed_table('t1', 'a');
insert into t1 select a, a from generate_series(1, 50) a;
```

2. run the query
```
select * from t1 offset 0 limit null;
--> returns 0 rows
```
3. set log remote commands to on and run the query

```sql
set citus.log_remote_commands to on; 
select * from t1 offset 0 limit null;
--> observer many NOTICE:  issuing SELECT a, b FROM public.t1_102102 t1 WHERE true LIMIT '0'::bigint  
```

Notice that removing `offset 0` fixes the problem, worker query looks like

```
NOTICE:  issuing SELECT a, b FROM public.t1_102102 t1 WHERE true LIMIT ALL     
```

Citus 12.1 on PG 16.3 and ubuntu 20

### PR DESCRIPTION
**Pull request by eaydingol**
DESCRIPTION: Add a check to see if the given limit is null. 

Fixes a bug by checking if the limit given in the query is null when the actual limit is computed with respect to the given offset.
Prior to this change, null is interpreted as 0 during the limit calculation when both limit and offset are given. 

Fixes #7663

### CODE REVIEW

**Comment by eaydingol** [comment]
All of the flaky test checks are failing as these tests require base schedule. They use "lineitem" table from "multi_create_table.sql"

File: src/backend/distributed/planner/multi_logical_optimizer.c [hunk 1]
```diff
@@ -4753,22 +4753,32 @@ WorkerLimitCount(Node *limitCount, Node *limitOffset, OrderByLimitReference
 	if (workerLimitNode != NULL && limitOffset != NULL)
 	{
 		Const *workerLimitConst = (Const *) workerLimitNode;
-		Const *workerOffsetConst = (Const *) limitOffset;
-		int64 workerLimitCount = DatumGetInt64(workerLimitConst->constvalue);
-		int64 workerOffsetCount = DatumGetInt64(workerOffsetConst->constvalue);
-
-		workerLimitCount = workerLimitCount + workerOffsetCount;
-		workerLimitNode = (Node *) MakeIntegerConstInt64(workerLimitCount);
+		if (!workerLimitConst->constisnull)
```
Comment (hanefi) [inline src/backend/distributed/planner/multi_logical_optimizer.c:4756]: Similar to LIMIT, OFFSET can also have NULL argument. `OFFSET NULL` is equivalent to `OFFSET 0` and it is safe to use DatumGetInt64 as we do it in the next block.

However, I think we need to explain this briefly in a comment.

File: src/backend/distributed/planner/multi_logical_optimizer.c [hunk 2]
```diff
@@ -4753,22 +4753,32 @@ WorkerLimitCount(Node *limitCount, Node *limitOffset, OrderByLimitReference
...
+		{
+			/* Only update the worker limit if the const is not null.*/
```
Comment (hanefi) [inline src/backend/distributed/planner/multi_logical_optimizer.c:4758]: This comment appears to be about the next line, and is confusing. I think you want to move this before the `if` clause. Preferably preceded by an empty line.

File: src/backend/distributed/planner/multi_logical_optimizer.c [hunk 3]
```diff
@@ -4753,22 +4753,32 @@ WorkerLimitCount(Node *limitCount, Node *limitOffset, OrderByLimitReference
...
+			Const *workerOffsetConst = (Const *) limitOffset;
+			int64 workerLimitCount = DatumGetInt64(workerLimitConst->constvalue);
+			int64 workerOffsetCount = DatumGetInt64(workerOffsetConst->constvalue);
```
Comment (hanefi) [inline src/backend/distributed/planner/multi_logical_optimizer.c:4761]: Please add a comment on how it is ok to use this even when `OFFSET NULL` is used. See earlier comment for details.

File: src/test/regress/expected/multi_limit_clause.out [hunk 4]
```diff
@@ -521,6 +521,63 @@ SELECT
...
+          1
+          1
+          1
+          1
+          1
+          1
+          2
+(7 rows)
+
+SELECT l_orderkey FROM lineitem WHERE l_orderkey < 3 ORDER BY l_orderkey OFFSET 1 LIMIT null;
```
Comment (hanefi) [inline src/test/regress/expected/multi_limit_clause.out:538]: Do you think that it makes sense to add a test case with `LIMIT ALL` to show that we cover this as well?

File: src/backend/distributed/planner/multi_logical_optimizer.c (hunk 2 above)
Comment (eaydingol) [reply src/backend/distributed/planner/multi_logical_optimizer.c:4758]: Sure, done. Both sytles seem to be used in this function, and both look ok to me.

File: src/backend/distributed/planner/multi_logical_optimizer.c (hunk 3 above)
Comment (eaydingol) [reply src/backend/distributed/planner/multi_logical_optimizer.c:4761]: Done

File: src/backend/distributed/planner/multi_logical_optimizer.c (hunk 1 above)
Comment (eaydingol) [reply src/backend/distributed/planner/multi_logical_optimizer.c:4756]: Added a comment.

File: src/test/regress/expected/multi_limit_clause.out (hunk 4 above)
Comment (eaydingol) [reply src/test/regress/expected/multi_limit_clause.out:538]: Added two tests, it looks like we did not have null/all tests in this file.

**Review by hanefi — APPROVED** [review]
