### PR TITLE
PG18 compatibility: misc output diffs

### LINKED ISSUE #8154: PG18 - sql_procedure diff -- CONTEXT:  SQL function "test_procedure_rollback" statement 2
```diff
diff -dU10 -w /__w/citus/citus/src/test/regress/expected/sql_procedure.out /__w/citus/citus/src/test/regress/results/sql_procedure.out
--- /__w/citus/citus/src/test/regress/expected/sql_procedure.out.modified	2025-08-25 12:43:26.618623624 +0000
+++ /__w/citus/citus/src/test/regress/results/sql_procedure.out.modified	2025-08-25 12:43:26.627623578 +0000
@@ -31,36 +31,36 @@
 -- following calls should fail
 CREATE PROCEDURE test_procedure_commit(tt_id int, tt_org_id int) LANGUAGE SQL AS $$
 	DELETE FROM test_table;
 	COMMIT;
 	INSERT INTO test_table VALUES(tt_id, -1);
 	UPDATE test_table SET org_id = tt_org_id WHERE id = tt_id;
 	COMMIT;
 $$;
 CALL test_procedure_commit(2,5);
 ERROR:  COMMIT is not allowed in an SQL function
-CONTEXT:  SQL function "test_procedure_commit" during startup
+CONTEXT:  SQL function "test_procedure_commit" statement 2
 SELECT * FROM test_table ORDER BY 1, 2;
  id | org_id 
 ----+--------
   2 |      3
 (1 row)
 
 CREATE PROCEDURE test_procedure_rollback(tt_id int, tt_org_id int) LANGUAGE SQL AS $$
 	DELETE FROM test_table;
 	ROLLBACK;
 	UPDATE test_table SET org_id = tt_org_id WHERE id = tt_id;
     COMMIT;
 $$;
 CALL test_procedure_rollback(2,15);
 ERROR:  ROLLBACK is not allowed in an SQL function
-CONTEXT:  SQL function "test_procedure_rollback" during startup
+CONTEXT:  SQL function "test_procedure_rollback" statement 2
 SELECT * FROM test_table ORDER BY 1, 2;
  id | org_id 
 ----+--------
   2 |      3
 (1 row)
```

### LINKED ISSUE #8157: PG18 - multi_alter_table_add_constraints_without_name diff
PG18 started cataloging NOT NULL as real constraints.

```diff
diff -dU10 -w /__w/citus/citus/src/test/regress/expected/multi_alter_table_add_constraints_without_name.out /__w/citus/citus/src/test/regress/results/multi_alter_table_add_constraints_without_name.out
--- /__w/citus/citus/src/test/regress/expected/multi_alter_table_add_constraints_without_name.out.modified	2025-08-25 12:45:11.759753364 +0000
+++ /__w/citus/citus/src/test/regress/results/multi_alter_table_add_constraints_without_name.out.modified	2025-08-25 12:45:11.787753148 +0000
@@ -20,34 +20,36 @@
 
 ALTER TABLE AT_AddConstNoName.products ADD PRIMARY KEY(product_no);
 SELECT con.conname
     FROM pg_catalog.pg_constraint con
       INNER JOIN pg_catalog.pg_class rel ON rel.oid = con.conrelid
       INNER JOIN pg_catalog.pg_namespace nsp ON nsp.oid = connamespace
 	      WHERE rel.relname = 'products';
            conname            
 ------------------------------
  products_pkey
-(1 row)
+ products_product_no_not_null
+(2 rows)
 
 -- Check that the primary key name created on the coordinator is sent to workers and
 -- the constraints created for the shard tables conform to the <conname>_shardid naming scheme.
 \c - - :public_worker_1_host :worker_1_port
 SELECT con.conname
     FROM pg_catalog.pg_constraint con
       INNER JOIN pg_catalog.pg_class rel ON rel.oid = con.conrelid
       INNER JOIN pg_catalog.pg_namespace nsp ON nsp.oid = connamespace
 		WHERE rel.relname = 'products_5410000';
                conname                
 --------------------------------------
+ products_5410000_product_no_not_null
  products_pkey_5410000
-(1 row)
+(2 rows)
```

### PR DESCRIPTION
**Pull request by naisila**
Minor changes to reduce some noise from the regression diffs. Refer to https://github.com/citusdata/citus/actions/runs/18308366595?pr=8065 for diffs prior to this PR.

**_Note to reviewer:_** Review commit by commit as each change has its explanation and relevant PG18 commit.

Fixes #8154 
Fixes #8157

### CODE REVIEW

File: src/test/regress/sql/subquery_in_where.sql [hunk 1]
```diff
@@ -34,7 +34,8 @@ SELECT *
 FROM   (SELECT 1 AS id, 2 AS value_1, 3 AS value_3
 		UNION ALL SELECT 2 as id, 3 as value_1, 4 as value_3) AS tt1
 WHERE  id IN (SELECT user_id
-              FROM   events_table);
+              FROM   events_table)
+ORDER BY 1;
```
Comment (colm-mchugh) [inline src/test/regress/sql/subquery_in_where.sql:38]: would `ORDER BY 1, 2, 3` be more future-proof ?

File: src/test/regress/sql/partitioning_issue_3970.sql [hunk 2]
```diff
@@ -47,6 +48,7 @@ ORDER BY 1,2,3;
 SELECT relname, conname, pg_catalog.pg_get_constraintdef(con.oid, true)
 FROM pg_constraint con JOIN pg_class rel ON (rel.oid=con.conrelid)
 WHERE relname SIMILAR TO 'part_table%\_\d%'
+    AND contype <> 'n'
```
Comment (colm-mchugh) [inline src/test/regress/sql/partitioning_issue_3970.sql:51]: Down the line tests that want to show constraints will need to explicitly exclude NOT NULL, until pg18 is the oldest supported version.

File: src/test/regress/sql/multi_metadata_sync.sql [hunk 3]
```diff
@@ -38,7 +38,9 @@ SELECT * FROM pg_dist_partition WHERE partmethod='h' AND repmodel='s';
 ALTER SYSTEM SET password_encryption TO md5;
 SELECT pg_reload_conf();
 SELECT pg_sleep(0.1);
+SET client_min_messages TO ERROR;
 ALTER ROLE CURRENT_USER WITH PASSWORD 'dummypassword';
+RESET client_min_messages;
```
Comment (colm-mchugh) [inline src/test/regress/sql/multi_metadata_sync.sql:43]: These tests will break when md5 support is dropped, but am good with this as interim solution.

**Review by colm-mchugh — APPROVED** [review]
Thx, couple of minor comments, lgtm overall.

File: src/test/regress/sql/multi_metadata_sync.sql (hunk 3 above)
Comment (naisila) [reply src/test/regress/sql/multi_metadata_sync.sql:43]: Good point. Made some research on this. It looks like the plan to remove md5 support is for PG21 https://www.postgresql.org/message-id/ZwbfpJJol7lDWajL%40nathan
So as you said let's keep this interim support for now, but after 3 years this test will definitely need to be changed :)

File: src/test/regress/sql/partitioning_issue_3970.sql (hunk 2 above)
Comment (naisila) [reply src/test/regress/sql/partitioning_issue_3970.sql:51]: That's right. I also don't expect changes to this file since it's a test file opened for a specific partitioning issue.

File: src/test/regress/sql/subquery_in_where.sql (hunk 1 above)
Comment (naisila) [reply src/test/regress/sql/subquery_in_where.sql:38]: The expected output in this test is
```
 id | value_1 | value_3
---------------------------------------------------------------------
  1 |       2 |       3
  2 |       3 |       4
(2 rows)
```
So in this case `ORDER BY 1` is deterministic.

File: src/test/regress/sql/multi_metadata_sync.sql (hunk 3 above)
Comment (naisila) [reply src/test/regress/sql/multi_metadata_sync.sql:43]: After your comment I tried changing the encryption to scram-sha-256. However, it produces a different output per every test run, so it wasn't a straightforward change.
