### PR TITLE
Use a fixed application_name while connecting to remote nodes

### LINKED ISSUE #5631: Setting application_name causes commands to fail due to not recognizing remote backends
```sql
[local] onurctirtir@onurctirtir:10700-8085=# create table dist_1(a int);
[local] onurctirtir@onurctirtir:10700-8085=# SELECT create_distributed_table('dist_1', 'a');
```

Restart the coordinator but use a custom `application_name` this time:
```bash
export PGAPPNAME='my_app'; citus_dev restart /data/postgres/pg13.5/ --port 10700
```

```sql
[local] onurctirtir@onurctirtir:10700-8127=# drop table dist_1 ;
ERROR:  cannot modify "dist_1_102008" because it is a shard of a distributed table
HINT:  Use the distributed table or set citus.enable_manual_changes_to_shards to on to modify shards directly
CONTEXT:  while executing command on localhost:10700
SQL statement "SELECT citus_drop_all_shards(v_obj.objid, v_obj.schema_name, v_obj.object_name, drop_shards_metadata_only := false)"
PL/pgSQL function citus_drop_trigger() line 25 at PERFORM
```

Changes in #5601 seem to fix the issue, so need to backport the relevant subset of the changes in that pr into 10.1 & 10.2 branches.

### LINKED ISSUE #5656: Application_name breaks metadata syncing
If you set:
```SQL
export PGAPPNAME=test_name
```

Then, psql:
```SQL
CREATE TABLE test (a int);
SELECT create_distributed_table('test', 'a');
ERROR:  This is an internal Citus function can only be used in a distributed transaction
CONTEXT:  while executing command on localhost:9700
```

There are two workarounds:

1) Do not set PGAPPNAME

2) Set  to set `enable_manual_metadata_changes_for_user` with the current user name:
```SQL
SELECT run_command_on_workers($$alter system set citus.enable_manual_metadata_changes_for_user to 'citus';$$);
SELECT run_command_on_workers($$SELECT pg_reload_conf();$$);
```

### PR DESCRIPTION
**Pull request by onderkalaci**
Citus heavily relies on application_name, see
`IsCitusInitiatedRemoteBackend()`.

But if the user set the application name, such as export PGAPPNAME=test_name,
Citus uses that name while connecting to the remote node.

With this commit, we ensure that Citus always connects with
the "citus" user name to the remote nodes.

DESCRIPTION: Use a fixed application_name while connecting to remote nodes

fixes #5656 
fixes #5631

### CODE REVIEW

File: src/test/regress/sql/mx_application_name.sql [hunk 1]
```diff
@@ -0,0 +1,10 @@
+CREATE SCHEMA mx_app_name;
+
+SET application_name TO mx_app_name;
```
Comment (marcocitus) [inline src/test/regress/sql/mx_application_name.sql:3]: as far as I can tell this does not reproduce the issue, so this test seems redundant

Comment (marcocitus) [reply src/test/regress/sql/mx_application_name.sql:3]: Maybe we can set PGAPPNAME in pg_regress_multi.pl somehow

Comment (onderkalaci) [reply src/test/regress/sql/mx_application_name.sql]: I think the trick you used for pg_dump works fine

Comment (onderkalaci) [reply src/test/regress/sql/mx_application_name.sql]: nope, that didn't work either

**Review by marcocitus — DISMISSED** [review]

**Comment by onurctirtir** [comment]
Noting fwiw: https://github.com/citusdata/citus/pull/5601#pullrequestreview-856790633

File: src/test/regress/sql/mx_application_name.sql [hunk 2]
```diff
@@ -0,0 +1,14 @@
+CREATE SCHEMA mx_app_name;
+
+CREATE TABLE output (line text);
+
+-- a hack to run command with another user
```
Comment (halilozanakgul) [inline src/test/regress/sql/mx_application_name.sql:5]: Isn't this the same user but another application name?

**Review by halilozanakgul — APPROVED** [review]

File: src/test/regress/sql/mx_application_name.sql (hunk 2 above)
Comment (onderkalaci) [reply src/test/regress/sql/mx_application_name.sql:5]: yes, copy & paste error

**Comment by onderkalaci** [comment]
> missed that the pg_dump approach also does not work

Finally it works with arbitrary configs. I think the potential downside is that I cannot cherry-pick the arbitrary test commit  to 10.1, but that sounds reasonable to be.

@marcocitus does that sound OK to you?

File: src/test/regress/citus_tests/common.py [hunk 3]
```diff
@@ -82,7 +82,16 @@ def start_databases(pg_path, rel_data_path, node_name_to_ports, logfile_prefix):
             "--log",
             os.path.join(abs_data_path, logfile_name(logfile_prefix, node_name)),
         ]
-        subprocess.run(command, check=True)
+
+        new_env = os.environ.copy()
+
+        # set the application name if requires
```
Comment (onderkalaci) [inline src/test/regress/citus_tests/common.py:88]: should probably be more generic, append env_variables to os.environ

**Review by marcocitus — APPROVED** [review]

**Comment by onderkalaci** [comment]
> Noting fwiw: #5601 (review)

I think this is a fair point, but we probably cannot backport such a change. Though, with Ozan's PR, we can consider doing that to citus 11.
