### PR TITLE
Planner: lift volatile target‑list items in `WrapSubquery` to coordinator (prevents sequence‑leap in distributed `INSERT … SELECT`)

### LINKED ISSUE #7784: with as select insert - queries use incorrect sequence
Hi, we are using citus in schema based sharding and are experiencing strange behavior when running the following query:

```sql
set citus.enable_schema_based_sharding to on;

create schema citus_test;

SET search_path = citus_test, public;
create table version (
	id bigserial not null,
	description varchar(255),
	primary key (id)
);

insert into version (description) values ('Version 1');

with v as (
	select * from version where description = 'Version 1'
)
insert into 
version (description) 
select description
from v;

select * from citus_test.version;
```
**Expected:**
<table>
 <tr>
   <th>id</td>
   <th>description</td>
  </tr>
  <tr>
    <td>1</td>
    <td> Version 1</td>
  </tr>
  <tr>
    <td>2</td>
    <td>Version 1</td>
  </tr>
</table>

**Actual:**
<table>
 <tr>
   <th>id</td>
   <th>description</td>
  </tr>
  <tr>
    <td>1</td>
    <td> Version 1</td>
  </tr>
  <tr>
    <td>562949953421313</td>
    <td>Version 1</td>
  </tr>
</table>

I found the following issue: [6798](https://github.com/citusdata/citus/issues/6798), and from the values it looks like it could be related.

### PR DESCRIPTION
**Pull request by m3hm3t**
This PR fixes #7784 and refactors the `WrapSubquery(Query *subquery)` function to improve clarity and correctness when handling volatile expressions in subqueries during Citus insert-select rewriting.

### Background

The `WrapSubquery` function rewrites a query of the form:

```sql
INSERT INTO target_table SELECT ... FROM ...
```

...by wrapping the `SELECT` in a subquery:

```sql
SELECT <outer-TL>
  FROM ( <subquery with volatile expressions replaced with NULL> ) citus_insert_select_subquery
```

This transformation allows:

* **Volatile expressions** (e.g., `nextval`, `now`) **not used in `GROUP BY` or `ORDER BY`** to be evaluated **exactly once on the coordinator**.
* **Stable/immutable or sort-relevant expressions** to remain in the worker-executed subquery.
* Placeholder `NULL`s to maintain column alignment in the inner subquery.

### Fix Details

* Restructured the code into labeled logical sections:

  1. Build wrapper query (`SELECT … FROM (subquery)`)
  2. Rewrite target lists with volatility analysis
  3. Assign and return updated query trees
  
* Preserved existing behavior, focusing on clarity and maintainability.

### How the new code handles volatile items

stage | what we look for | what we do | why
-- | -- | -- | --
scan target list once | 1. `expr_is_volatile(te->expr)` 2. `te->ressortgroupref != 0` (is the column used in GROUP BY / ORDER BY?) | decide whether to hoist or keep | we must not hoist an expression the inner query still needs for sorting/grouping, otherwise its `SortGroupClause` breaks
volatile & not used in sort/group | deep‑copy the expression into the outer target list | executes once on the coordinator |  
  | leave a typed `NULL `placeholder (visible, not `resjunk`) in the inner target list | keeps column numbering stable for helpers that already ran (reorder, cast); the worker sends a cheap constant |  
stable / immutable, or volatile but used in sort/group | keep the original expression in the inner list; outer list references it via a `Var `| workers can evaluate it safely and, if needed, the inner ORDER BY still works |  

###  Example

Given this query:

```sql
INSERT INTO t SELECT nextval('s'), 42 FROM generate_series(1, 2);
```

The planner rewrites it as:

```sql
SELECT nextval('s'), col2
  FROM (SELECT NULL::bigint AS col1, 42 AS col2 FROM generate_series(1, 2)) citus_insert_select_subquery;
```

This ensures `nextval('s')` is evaluated only once per row on the **coordinator**, not on each worker node, preserving correct sequence semantics.

#### **Outer‑Var guard (`FindReferencedTableColumn`)**

Because `WrapSubquery` adds an extra query level, lots of Vars that the old code never expected become “outer” Vars; without teaching `FindReferencedTableColumn` to climb that extra level reliably, Citus would intermittently reject valid foreign keys and even hit asserts.

* Re‑implemented the outer‑Var guard so that the function:

  * **Walks deterministically up the query stack** when `skipOuterVars = false` (default for FK / UNION checks). A new while‑loop copies — rather than truncates — `parentQueryList` on each hop, eliminating list‑aliasing that made *issue 5248* fail intermittently in parallel regressions.

* Handles multi‑level `varlevelsup` in a single loop; never mutates the caller’s list in place.

### CODE REVIEW

File: src/backend/distributed/planner/insert_select_planner.c [hunk 1]
```diff
@@ -1543,76 +1536,109 @@ InsertSelectResultIdPrefix(uint64 planId)
...
+    foreach_declared_ptr(te, subquery->targetList)
+    {
+        if (te->resjunk)
+        {
+            /* keep resjunk items only in the inner TL */
+            newInnerTL = lappend(newInnerTL, te);
+            continue;
+        }
+
+        if (expr_is_volatile((Node *) te->expr))
```
Comment (colm-mchugh) [inline src/backend/distributed/planner/insert_select_planner.c:1599]: Probably should also check that the target is not referenced by the GROUP BY or ORDER BY clause, if present. Going by the definition of `TargetEntry` in `primnodes.h` (below) checking that `ressortgroupref` is zero should suffice.

```
* ressortgroupref is used in the representation of ORDER BY, GROUP BY, and
 * DISTINCT items.  Targetlist entries with ressortgroupref=0 are not
 * sort/group items.  If ressortgroupref>0, then this item is an ORDER BY,
 * GROUP BY, and/or DISTINCT target value.  No two entries in a targetlist
 * may have the same nonzero ressortgroupref --- but there is no particular
 * meaning to the nonzero values, except as tags.  (For example, one must
 * not assume that lower ressortgroupref means a more significant sort key.)
 * The order of the associated SortGroupClause lists determine the semantics.
```

Comment (m3hm3t) [reply src/backend/distributed/planner/insert_select_planner.c]: Added a logic to peel away a column the sub‑query still needs for its own ORDER BY/GROUP BY.

File: src/backend/distributed/planner/insert_select_planner.c [hunk 2]
```diff
@@ -1543,71 +1543,147 @@ InsertSelectResultIdPrefix(uint64 planId)
...
-	/*
-	 * This part of the code is more of a sanity check for readability,
-	 * it doesn't really do anything.
-	 * addRangeTableEntryForSubquery doesn't add permission info
-	 * because the range table is set to be RTE_SUBQUERY.
-	 * Hence we should also have no perminfos here.
-	 */
-	Assert(newRangeTableEntry->rtekind == RTE_SUBQUERY &&
-		   newRangeTableEntry->perminfoindex == 0);
+#if PG_VERSION_NUM >= 160000
```
Comment (colm-mchugh) [inline src/backend/distributed/planner/insert_select_planner.c:1596]: nit: `#if PG_VERSION_NUM >= PG_VERSION_16`

File: src/backend/distributed/planner/insert_select_planner.c [hunk 3]
```diff
@@ -1543,71 +1543,147 @@ InsertSelectResultIdPrefix(uint64 planId)
...
+			 *   - volatile but needed for sorting or grouping
+			 *
+			 * In both cases, keep it in subquery and reference it using a Var.
+			 */
+			TargetEntry *innerTE = te;          /* reuse original node */
+			innerTE->resno = nextResno++;
+			newInnerTL = lappend(newInnerTL, innerTE);
+
+			Var *v = makeVar(/* subquery reference index is 1 */
+				1,
```
Comment (colm-mchugh) [inline src/backend/distributed/planner/insert_select_planner.c:1666]: nit: can we pass `rtref->rtindex` instead of 1 here?

File: src/backend/distributed/planner/multi_logical_optimizer.c [hunk 4]
```diff
@@ -4478,46 +4478,43 @@ FindReferencedTableColumn(Expr *columnExpression, List *parentQueryList, Query *
...
+			return;                             /* malformed tree */
 		}
 
-		/*
-		 * Before we recurse into the query tree, we should update the candidateColumn and we use copy of it.
-		 * As we get the query from varlevelsup up, we reset the varlevelsup.
-		 */
+		/* Work on a fresh copy of the Var with varlevelsup reset */
 		candidateColumn = copyObject(candidateColumn);
 		candidateColumn->varlevelsup = 0;
```
Comment (colm-mchugh) [inline src/backend/distributed/planner/multi_logical_optimizer.c:4500]: This assignment means that the body of the while loop is executed at most once - so what's the rationale for changing `if (candidateColumn->varlevelsup > 0)` to `while (candidateColumn->varlevelsup > 0)` ?

Comment (m3hm3t) [reply src/backend/distributed/planner/multi_logical_optimizer.c:4500]: It was done for defensive reasons.

Right now `WrapSubquery` adds one extra query level, therefore every outer reference enters the helper with `varlevelsup == 1`.

If we later introduce planner steps that can add two (or more) levels—`WrapSubquery `+ an automatic aggregation wrapper—the while already handles it without any extra change.

I assume that `while `costs nothing (the compiler generates the same code for the single‑iteration case) but if we are certain we will never add another wrapper level we can switch back to `if`.

Comment (colm-mchugh) [reply src/backend/distributed/planner/multi_logical_optimizer.c:4500]: I see, thanks for the explanation. it sounds reasonable to me, it is a premature optimization somewhat but as you say `while` and `if` are equivalent here, we (or I) cannot be certain wrapper levels will not be extended, so no objections to this change.

**Review by colm-mchugh — APPROVED** [review]
Couple of minor nits, looks good otherwise.

File: src/backend/distributed/planner/insert_select_planner.c (hunk 3 above)
Comment (m3hm3t) [reply src/backend/distributed/planner/insert_select_planner.c]: done
