### PR TITLE
Use single-quote interpolation in partition test

### LINKED ISSUE #92: We have some regression tests that hard code directory and file paths. worker_range_partition.sql is one such example. Now that PostgreSQL 9.0 supports variable interpolation, we can fix these hard coded paths.
We have some regression tests that hard code directory and file paths. worker_range_partition.sql is one such example. Now that PostgreSQL 9.0 supports variable interpolation, we can fix these hard coded paths.

### PR DESCRIPTION
**Pull request by jasonmp85**
Noticed an old issue and this outdated comment. Figured I'd fix it.

Fixes #92

### CODE REVIEW

File: src/test/regress/sql/worker_range_partition.sql [hunk 1]
```diff
@@ -21,22 +21,22 @@ ALTER SEQUENCE pg_catalog.pg_dist_jobid_seq RESTART 1160000;
 \set Table_Part_02 lineitem_range_part_02
 \set Table_Part_03 lineitem_range_part_03
 
+\set File_Prefix   base/pgsql_job_cache/job_
+\set Table_File_00 :File_Prefix:JobId/task_:TaskId/p_00000
```
Comment (marcocitus) [inline src/test/regress/sql/worker_range_partition.sql]: Minor, this would be slightly more readable as:
```
\set File_Prefix   base/pgsql_job_cache
\set Table_File_00 :File_Prefix/job_:JobId/task_:TaskId/p_00000
```

Comment (jasonmp85) [inline src/test/regress/sql/worker_range_partition.sql]: Yeah, I thought so too but over-optimization kicked in.

Comment (jasonmp85) [inline src/test/regress/sql/worker_range_partition.sql]: (I'll change, and call it `Basedir` or something rather than prefix)
