### PR TITLE
Fix node adding itself with citus_add_node leading to deadlock (Fix #5720)

### LINKED ISSUE #5720: Node calling citus_add_node on itself doesn't fail and locks other citus_add_node operations on that same node
1) On one terminal:
```
psql -p 9700
SELECT citus_add_node('localhost', 9700);
```

2) On another terminal
```
psql -p 9700
SELECT citus_add_node('localhost', 9701);
```

There is deadlock and both operations wait forever.

### PR DESCRIPTION
**Pull request by gledis69**
If a worker node is being added, a command is sent to get the server_id of the worker from the pg_dist_node_metadata table. If the worker's id is the same as the node executing the code, we will know the node is trying to add itself. If the node tries to add itself without specifying `groupid:=0` the operation will result in an error.

Fix #5720

### CODE REVIEW

File: src/backend/distributed/transaction/worker_transaction.c [hunk 1]
```diff
@@ -639,3 +640,53 @@ ErrorIfAnyMetadataNodeOutOfSync(List *metadataNodeList)
...
+	MultiConnection *workerConnection = GetNodeUserDatabaseConnection(connectionFlags,
+																	  workerNode->
+																	  workerName,
+																	  workerNode->
+																	  workerPort,
+																	  CurrentUserName(),
+																	  NULL);
+	const char *partialCommand =
+		"SELECT COUNT(*) FROM pg_locks JOIN pg_class ON pg_locks.relation = pg_class.oid "
+		"WHERE pg_class.relname = 'pg_dist_node' AND pg_locks.granted AND pg_locks.mode = 'ExclusiveLock' AND pid = ";
```
Comment (marcocitus) [inline src/backend/distributed/transaction/worker_transaction.c:664]: this seems a bit sketchy because this view is not always reliable

each node has a unique identifier in `pg_dist_node_metadata`. Can we check whether the identifier on the node we're adding is the same as our own?

File: src/backend/distributed/metadata/node_metadata.c [hunk 2]
```diff
@@ -273,6 +273,19 @@ citus_add_node(PG_FUNCTION_ARGS)
...
+		WorkerNode *workerNode = FindWorkerNodeAnyCluster(nodeNameString, nodePort);
+
+		/*
+		 * If the worker is not marked as a coordinator, check that
+		 * the node is not trying to add itself
+		 */
+		if (workerNode->groupId != 0 && IsWorkerTheCurrentNode(workerNode))
+		{
+			ereport(ERROR, (errmsg("Node cannot add itself as a worker."),
+							errhint("Either try to add the node as a coordinator "
```
Comment (onderkalaci) [inline src/backend/distributed/metadata/node_metadata.c:285]: should we give the full command? That is mostly very useful:
```
.... as coordinator SELECT citus_add_node(%s, %d, groupid:=0), nodeNameString,Nodeport)

Comment (marcocitus) [reply src/backend/distributed/metadata/node_metadata.c:285]: Maybe use citus_set_coordinator_host

File: src/backend/distributed/transaction/worker_transaction.c [hunk 3]
```diff
@@ -639,3 +641,52 @@ ErrorIfAnyMetadataNodeOutOfSync(List *metadataNodeList)
...
+	int connectionFlags = REQUIRE_METADATA_CONNECTION;
+
+	MultiConnection *workerConnection =
+		GetNodeUserDatabaseConnection(connectionFlags,
+									  workerNode->workerName,
+									  workerNode->workerPort,
+									  CurrentUserName(),
+									  NULL);
+	const char *command =
+		"SELECT metadata ->> 'server_id' AS server_id FROM pg_dist_node_metadata";
```
Comment (onderkalaci) [inline src/backend/distributed/transaction/worker_transaction.c:663]: The logic to parse the output of a json is too complex. To remove those codes, can we do
```SQL
SELECT count(*) FROM pg_dist_node_metadata where metadata = %s::jsonb; 
```
where we supply our own pg_dist_node_metadata, which can be get:
```C
		metadataJsonbDatum = DistNodeMetadata();
		metadataJsonbStr = DatumGetCString(DirectFunctionCall1(jsonb_out,
															   metadataJsonbDatum));
```

If so, I'd rather prefer to parse (or even check a single row returns or not)

Comment (onderkalaci) [reply src/backend/distributed/transaction/worker_transaction.c:663]: (Oh, we mostly copy & pasted from other places, let me have a look again first)

File: src/backend/distributed/metadata/node_metadata.c [hunk 4]
```diff
@@ -273,6 +273,26 @@ citus_add_node(PG_FUNCTION_ARGS)
...
+
+		/*
+		 * If the worker is not marked as a coordinator, check that
+		 * the node is not trying to add itself
+		 */
+		if (workerNode != NULL &&
+			workerNode->groupId != 0 &&
+			IsWorkerTheCurrentNode(workerNode))
+		{
+			ereport(ERROR, (errmsg("Node cannot add itself as a worker."),
```
Comment (onderkalaci) [inline src/backend/distributed/metadata/node_metadata.c:286]: maybe we give the hint based on the state, giving both citus_add_node and citus_set_coordinator_host as suggestion is confusing

```C

	WorkerNode *coordinatorNode = PrimaryNodeForGroup(COORDINATOR_GROUP_ID,
													  &isCoordinatorInMetadata);
     if (isCoordinatorInMetadata) hint_with_citus_set_coordinator_host
     else hint_with_ citus_add_node

Comment (onderkalaci) [reply src/backend/distributed/metadata/node_metadata.c:286]: (and, also add test triggering both)

File: src/backend/distributed/transaction/worker_transaction.c (hunk 3 above)
Comment (onderkalaci) [reply src/backend/distributed/transaction/worker_transaction.c:663]: yes, majority of the code already exists, sorry, I couldn't realize  :)

File: src/backend/distributed/transaction/worker_transaction.c [hunk 5]
```diff
@@ -639,3 +641,52 @@ ErrorIfAnyMetadataNodeOutOfSync(List *metadataNodeList)
...
+
+	SendRemoteCommand(workerConnection, command);
+
+	PGresult *result = GetRemoteCommandResult(workerConnection, true);
+	List *commandResult = ReadFirstColumnAsText(result);
+
+	if (commandResult == NIL)
```
Comment (onderkalaci) [inline src/backend/distributed/transaction/worker_transaction.c:670]: maybe be a little more strict: if(list_length(commandResult) != 1))

(not sure if otherwise is ever possible, but still)

File: src/backend/distributed/transaction/worker_transaction.c [hunk 6]
```diff
@@ -639,3 +641,52 @@ ErrorIfAnyMetadataNodeOutOfSync(List *metadataNodeList)
...
 }
+
+
+/*
+ * IsWorkerTheCurrentNode checks if the given worker refers to the
+ * the current node by comparing the server id of the worker and of the
+ * current nodefrom pg_dist_node_metadata
+ */
+bool
+IsWorkerTheCurrentNode(WorkerNode *workerNode)
```
Comment (onderkalaci) [inline src/backend/distributed/transaction/worker_transaction.c:652]: Not sure if the usage of `worker` is good as we could be dealing with the coordinator. Though, I couldn't come up with a better alternative, if you can, please update the name

File: src/backend/distributed/transaction/worker_transaction.c [hunk 7]
```diff
@@ -639,3 +641,52 @@ ErrorIfAnyMetadataNodeOutOfSync(List *metadataNodeList)
...
+									  workerNode->workerPort,
+									  CurrentUserName(),
+									  NULL);
+	const char *command =
+		"SELECT metadata ->> 'server_id' AS server_id FROM pg_dist_node_metadata";
+
+	SendRemoteCommand(workerConnection, command);
+
+	PGresult *result = GetRemoteCommandResult(workerConnection, true);
+	List *commandResult = ReadFirstColumnAsText(result);
```
Comment (onderkalaci) [inline src/backend/distributed/transaction/worker_transaction.c:668]: can `result` be NULL? If so, please add a NULL check

File: src/backend/distributed/utils/jsonbutils.c [hunk 8]
```diff
@@ -0,0 +1,120 @@
...
+													lowerbounds, TEXTOID, typeLength,
+													typeByValue, typeAlignment);
+	Datum pathDatum = PointerGetDatum(pathArrayObject);
+
+	/*
+	 * We need to check whether the result of jsonb_extract_path is NULL or not, so use
+	 * FunctionCallInvoke() instead of other function call api.
+	 *
+	 * We cannot use jsonb_path_exists to ensure not-null since it is not available in
+	 * postgres 11.
```
Comment (onderkalaci) [inline src/backend/distributed/utils/jsonbutils.c:49]: we don't use PG 11 anymore, maybe good time to remove useless code

**Review by onderkalaci — COMMENTED** [review]
I think the only actual missing thing is the showing the relevant hint in the error messages based on the cases

File: src/backend/distributed/transaction/worker_transaction.c [hunk 9]
```diff
@@ -50,6 +51,7 @@ static void SendCommandToWorkersOutsideTransaction(TargetWorkerSet targetWorkerS
 												   const char *command, const char *user,
 												   bool
 												   failOnError);
+bool IsWorkerTheCurrentNode(WorkerNode *workerNode);
```
Comment (onderkalaci) [inline src/backend/distributed/transaction/worker_transaction.c:54]: we already externally declared `IsWorkerTheCurrentNode`, so probably this is redundant (and slightly confusing)

File: src/backend/distributed/metadata/node_metadata.c (hunk 4 above)
Comment (gledis69) [reply src/backend/distributed/metadata/node_metadata.c:286]: Afaik If the coordinator is in the metadata, an error will be thrown because coordinator permissions are needed to run citus_add_node and this code I added will not execute.

File: src/backend/distributed/utils/jsonbutils.c (hunk 8 above)
Comment (gledis69) [reply src/backend/distributed/utils/jsonbutils.c]: I just removed the comments here.
Using a different function call api does not really reduce the code size so there is no benefit I can see to rewriting this portion of the code.

(I tried rewriting with directfunctioncall macro)

File: src/backend/distributed/transaction/worker_transaction.c (hunk 6 above)
Comment (gledis69) [reply src/backend/distributed/transaction/worker_transaction.c:651]: True, but the parameter of this is a worker node, and if you look at the code logic, it tries to check if the worker node is the node executing the code. 
I could change it to: `IsTargetNodeTheCurrentNode`, but I think the current name is reflective of what the function does.

File: src/backend/distributed/metadata/node_metadata.c (hunk 4 above)
Comment (onderkalaci) [reply src/backend/distributed/metadata/node_metadata.c:286]: > an error will be thrown because coordinator permissions are needed

can you please clarify this a bit more? I can do it without an error:
```SQL
# SELECT nodename,nodeport, groupid FROM pg_dist_node;
┌───────────┬──────────┬─────────┐
│ nodename  │ nodeport │ groupid │
├───────────┼──────────┼─────────┤
│ localhost │     5432 │       0 │
└───────────┴──────────┴─────────┘
(1 row)

SELECT citus_add_node('localhost', 5432);
┌────────────────┐
│ citus_add_node │
├────────────────┤
│             10 │
└────────────────┘
(1 row)
```

I think we don't get here because we are operating on `if (!nodeAlreadyExists))`, where the node already exists.

What we can do it:
1) remove `citus_set_coordinator_host` from this error message
2) on the else of `if (!nodeAlreadyExists)`, if `isCoordinatorInMetadata`, we give a NOTICE to use `citus_set_coordinator_host`.

File: src/test/regress/expected/add_coordinator.out [hunk 10]
```diff
@@ -1,6 +1,10 @@
 --
 -- ADD_COORDINATOR
 --
+-- node trying to add itself without specifying groupid => 0 should error out
+SELECT master_add_node('localhost', :master_port);
+ERROR:  Node cannot add itself as a worker.
+HINT:  Add the node as a coordinator by using: SELECT citus_add_node(localhost, 57636, groupid => 0);
```
Comment (marcocitus) [inline src/test/regress/expected/add_coordinator.out:7]: for consistency with the other error message in AddNodeMetadata, can we suggest citus_set_coordinator_host here?

Comment (onderkalaci) [reply src/test/regress/expected/add_coordinator.out:7]: But it seems we do not need `citus_set_coordinator_host` with `master_add_node`. because we add this message `if (!nodeAlreadyExists)`, whereas `citus_set_coordinator_host` happens `if (nodeAlreadyExists)`.

I think we can do that separately, but it looked confusing to see `citus_set_coordinator_host` when the node does not really exist.

I thought we could consider another PR which does a similar check but gives `citus_set_coordinator_host` notice/warning when ` `if (nodeAlreadyExists)`.

Do you think we should definitely have it here as well?

Comment (marcocitus) [reply src/test/regress/expected/add_coordinator.out:7]: We do not need citus_add_node if we use citus_set_coordinator_host. If the coordinator is not yet added to the metadata then citus_set_coordinator_host will add it.

I think we should at least be self-consistent in our error messages. Adding the node to itself also seems like a weird thing to do. Surely the coordinator knows it exists? Setting the coordinator host seems like a much more reasonable thing to do.

Comment (onderkalaci) [reply src/test/regress/expected/add_coordinator.out:7]: > . If the coordinator is not yet added to the metadata then citus_set_coordinator_host will add it.

Ops, I didn't realize this. Given the name contains `set`, I was considering this as operating only if the node exists.

So, @gledis69 would you mind adding back `citus_set_coordinator_host` to the message, sorry for the extra iteration

File: src/backend/distributed/metadata/node_metadata.c [hunk 11]
```diff
@@ -273,6 +273,23 @@ citus_add_node(PG_FUNCTION_ARGS)
...
+		 * the node is not trying to add itself
+		 */
+		if (workerNode != NULL &&
+			workerNode->groupId != COORDINATOR_GROUP_ID &&
+			IsWorkerTheCurrentNode(workerNode))
+		{
+			ereport(ERROR, (errmsg("Node cannot add itself as a worker."),
+							errhint(
+								"Add the node as a coordinator by using: "
+								"SELECT citus_set_coordinator_host(%s, %d);",
```
Comment (onderkalaci) [inline src/backend/distributed/metadata/node_metadata.c:289]: ah, %s is missing single quotes, which makes it hard to copy&past. Can you make it `'%s'` so that copy&paste works?

**Review by onderkalaci — APPROVED** [review]

File: src/backend/distributed/metadata/node_metadata.c (hunk 4 above)
Comment (onderkalaci) [reply src/backend/distributed/metadata/node_metadata.c:288]: > What we can do it remove citus_set_coordinator_host from this error message


As Marco noted in the other comment in this PR, we decided to only go with `citus_set_coordinator_host`
