### PR TITLE
Fix COPY produces error when using array of user-defined types

### LINKED ISSUE #463: COPY produces error when using hstore[]
COPY on distributed tables throws an error when ingesting data into an hstore[]. A single hstore and other array types don't seem to have this issue.

    postgres=# CREATE TABLE test (key int, data hstore[]);
    CREATE TABLE
    postgres=# SELECT master_create_distributed_table('test','key','hash');
     master_create_distributed_table 
    ---------------------------------
     
    (1 row)
    
    postgres=# SELECT master_create_worker_shards('test',4,1);
     master_create_worker_shards 
    -----------------------------
     
    (1 row)

    postgres=# COPY (SELECT 0, ARRAY[hstore(ARRAY['key'],ARRAY['value'])]) TO '/tmp/test';
    COPY 1
    postgres=# COPY test FROM '/tmp/test';
    ERROR:  wrong element type

### PR DESCRIPTION
**Pull request by byucesoy**
Fixes #463 

OID of user-defined types may be different in master and worker nodes. This causes errors
while sending data between nodes with binary nodes. Because binary copy format adds OID
of the element if it is in an array. The code adding OID is in PostgreSQL code, therefore
we cannot change it. Instead we decided to use text format if we try to send array of
user-defined type.

### CODE REVIEW

File: src/backend/distributed/commands/multi_copy.c [hunk 1]
```diff
@@ -126,6 +126,134 @@
 #include "utils/tuplestore.h"
 #include "utils/memutils.h"
 
+/* Data structures from copy.c, to keep track of COPY processing state */
```
Comment (anarazel) [inline src/backend/distributed/commands/multi_copy.c]: We should work very hard avoiding copying all these. It'll be a maintenance nightmare to keep the structs in sync.

In fact, we can just check the target table for the problematic types / NextCopyFrom() returns values for all the columns in the target table anyway.

File: src/backend/distributed/commands/multi_copy.c [hunk 2]
```diff
@@ -986,6 +1165,50 @@ OpenCopyTransactions(CopyStmt *copyStatement, ShardConnections *shardConnections
...
+		char typeCategory = '\0';
+		bool typePreferred = false;
+
+		get_type_category_preferred(typeId, &typeCategory, &typePreferred);
+
+		if (!builtInType && typeCategory == TYPCATEGORY_ARRAY)
+		{
+			binaryCopyFormat = false;
+			break;
+		}
```
Comment (anarazel) [inline src/backend/distributed/commands/multi_copy.c]: You also need to check for non-builtin composite types here, they have the same problem.

Comment (byucesoy) [inline src/backend/distributed/commands/multi_copy.c]: I tried this example but could not produce error;

```sql
CREATE TYPE inventory_item AS (
    name text,
    supplier_id integer,
    price numeric
);

CREATE TABLE on_hand (
  id integer,
  item inventory_item
);

SELECT master_create_distributed_table('on_hand', 'id', 'hash');

SELECT master_create_worker_shards('on_hand', 4, 1);

COPY (SELECT 1, ROW('fuzzy dice', 42, 1.99)) TO '/tmp/test';

COPY on_hand FROM '/tmp/test';
```

As far as I understand copy operation of composite type itself is made by record_send/record_recv functions, and they do not add Oid. COPY operation of array of composite type is still made by array_send/array_recv, but typCategory of that is TYPECATEGORY_ARRAY

File: src/backend/distributed/commands/multi_copy.c (hunk 1 above)
Comment (byucesoy) [inline src/backend/distributed/commands/multi_copy.c]: I sent new patch without copying these structs.

File: src/backend/distributed/commands/multi_copy.c (hunk 2 above)
Comment (anarazel) [inline src/backend/distributed/commands/multi_copy.c]: But record_recv() verifies the oids of contained datums.  So if you use any non-builtin members (or to double down on the problem an array of non-builtins), you'll end up with the same problem.

**Comment by sumedhpathak** [comment]
Assigning this to @lithp. Brian, could you review this change? Thanks!

**Comment by lithp** [comment]
Sure thing, looking at this soon

File: src/backend/distributed/commands/multi_copy.c (hunk 2 above)
Comment (byucesoy) [inline src/backend/distributed/commands/multi_copy.c]: I understand. In case of composite types, oid of the element itself does not included but oids of contained elements are included. Therefore if contained type is not built-in that would cause same problem. I sent a patch to fix this issue also.

File: src/backend/distributed/commands/multi_copy.c [hunk 3]
```diff
@@ -137,24 +136,28 @@ static PGconn *masterConnection = NULL;
...
-static void CopyToNewShards(CopyStmt *copyStatement, char *completionTag, Oid relationId);
+static void CopyToNewShards(CopyStmt *copyStatement, char *completionTag,
+							Oid relationId);
 static char MasterPartitionMethod(RangeVar *relation);
 static void RemoveMasterOptions(CopyStmt *copyStatement);
 static void OpenCopyTransactions(CopyStmt *copyStatement,
-								 ShardConnections *shardConnections, bool stopOnFailure);
+								 ShardConnections *shardConnections, bool stopOnFailure,
+								 bool binaryCopyFormat);
+static bool BinaryCopyFormat(TupleDesc tupleDescription, CopyOutState rowOutputState);
```
Comment (lithp) [inline src/backend/distributed/commands/multi_copy.c]: I think this should be something like `RequiresBinaryCopyFormat` or `ShouldUseBinaryCopyFormat` to make it clear it returns a `bool`.

File: src/backend/distributed/commands/multi_copy.c [hunk 4]
```diff
@@ -1430,7 +1516,8 @@ AppendCopyBinaryFooters(CopyOutState footerOutputState)
  * opens connections to shard placements.
  */
 static void
-StartCopyToNewShard(ShardConnections *shardConnections, CopyStmt *copyStatement)
+StartCopyToNewShard(ShardConnections *shardConnections, CopyStmt *copyStatement,
+					bool binaryCopyFormat)
```
Comment (lithp) [inline src/backend/distributed/commands/multi_copy.c]: this is a really small nitpick feel free to ignore it but something like `useBinaryCopyFormat` sounds slightly better

File: src/backend/distributed/commands/multi_copy.c [hunk 5]
```diff
@@ -1075,23 +1156,27 @@ SendCopyBinaryFooters(CopyOutState copyOutState, List *connectionList)
...
-
-	char *shardName = pstrdup(relationName);
+	char *shardSchemaName = copyStatement->relation->schemaname;
+	char *shardTableName = copyStatement->relation->relname;
 	char *shardQualifiedName = NULL;
 
-	AppendShardIdToName(&shardName, shardId);
-
-	shardQualifiedName = quote_qualified_identifier(schemaName, shardName);
+	shardTableName = pstrdup(shardTableName);
```
Comment (lithp) [inline src/backend/distributed/commands/multi_copy.c]: Why not do this on the same line as initialization? If this were a more complicated function it'd make sense to separate it out for debuggability but I don't think future devs are likely to want to know the argument pstrdup was given.

File: src/backend/distributed/commands/multi_copy.c [hunk 6]
```diff
@@ -986,6 +1023,50 @@ OpenCopyTransactions(CopyStmt *copyStatement, ShardConnections *shardConnections
 
 
 /*
+ * BinaryCopyFormat iterates over columns of the relation given in rowOutputState and
+ * looks for a column whose type is array of user-defined type. If it founds that
```
Comment (lithp) [inline src/backend/distributed/commands/multi_copy.c]: "If it founds" -> "If it finds one"

"and it return false" -> "and it returns"

File: src/backend/distributed/commands/multi_copy.c [hunk 7]
```diff
@@ -986,6 +1023,50 @@ OpenCopyTransactions(CopyStmt *copyStatement, ShardConnections *shardConnections
...
+ * means we cannot use binary format for COPY and it return false.
+ */
+static bool
+BinaryCopyFormat(TupleDesc tupleDescription, CopyOutState rowOutputState)
+{
+	bool binaryCopyFormat = true;
+	uint32 totalColumnCount = (uint32) tupleDescription->natts;
```
Comment (lithp) [inline src/backend/distributed/commands/multi_copy.c]: Why use `uint32` and cast `natts` instead of using `int` like natts does?

File: src/backend/distributed/commands/multi_copy.c [hunk 8]
```diff
@@ -986,6 +1023,50 @@ OpenCopyTransactions(CopyStmt *copyStatement, ShardConnections *shardConnections
...
+	MemoryContext oldContext = MemoryContextSwitchTo(rowOutputState->rowcontext);
+
+	for (columnIndex = 0; columnIndex < totalColumnCount; columnIndex++)
+	{
+		Form_pg_attribute currentColumn = tupleDescription->attrs[columnIndex];
+		Oid typeId = currentColumn->atttypid;
+		char typeCategory = '\0';
+		bool typePreferred = false;
+		bool builtInType = typeId < FirstNormalObjectId;
+        bool containsOid = false;
```
Comment (lithp) [inline src/backend/distributed/commands/multi_copy.c]: Forgot to use tabs here :)

**Comment by lithp** [comment]
This looks great, pretty straightforward. I left a lot of nitpicky comments, feel free to ignore most them I think this is ready to merge except for a few things: `BinaryCopyFormat` should probably have a better name, the line `copyOutState->binary = BinaryCopyFormat(tupleDescriptor, copyOutState);` doesn't give me any indication that we're dealing with a boolean.

Besides that:
- Are you sure `PerTupleExprContext` is the right context to use? We're not dealing with individual tuples here.
- If it's easy to add, a regression test would be nice to make it easy to confirm this fixes the problem.

File: src/backend/distributed/commands/multi_copy.c [hunk 9]
```diff
@@ -986,6 +1023,50 @@ OpenCopyTransactions(CopyStmt *copyStatement, ShardConnections *shardConnections
...
+ * means we cannot use binary format for COPY and it return false.
+ */
+static bool
+BinaryCopyFormat(TupleDesc tupleDescription, CopyOutState rowOutputState)
+{
+	bool binaryCopyFormat = true;
+	uint32 totalColumnCount = (uint32) tupleDescription->natts;
+	uint32 columnIndex = 0;
+
+	MemoryContext oldContext = MemoryContextSwitchTo(rowOutputState->rowcontext);
```
Comment (lithp) [inline src/backend/distributed/commands/multi_copy.c]: Just talked with Andres about this, I think this is unnecessary complication. It's just a few Oid's which are going to be released at the end of the transaction anyway, we don't really care if they're held onto a little longer than necessary.

**Comment by lithp** [comment]
Confirmed that the test fails on the pre-patched version, and that everything works now. Merge it!

File: src/backend/distributed/commands/multi_copy.c [hunk 10]
```diff
@@ -126,7 +126,6 @@
 #include "utils/tuplestore.h"
 #include "utils/memutils.h"
 
-
```
Comment (anarazel) [inline src/backend/distributed/commands/multi_copy.c]: spurious change.

File: src/backend/distributed/commands/multi_copy.c [hunk 11]
```diff
@@ -986,6 +1024,46 @@ OpenCopyTransactions(CopyStmt *copyStatement, ShardConnections *shardConnections
...
+CanUseBinaryCopyFormat(TupleDesc tupleDescription, CopyOutState rowOutputState)
+{
+	bool useBinaryCopyFormat = true;
+	int totalColumnCount = tupleDescription->natts;
+	int columnIndex = 0;
+
+	for (columnIndex = 0; columnIndex < totalColumnCount; columnIndex++)
+	{
+		Form_pg_attribute currentColumn = tupleDescription->attrs[columnIndex];
+		Oid typeId = currentColumn->atttypid;
```
Comment (anarazel) [inline src/backend/distributed/commands/multi_copy.c]: It's imo not really correct to access this, before checking attisdropped.

File: src/backend/distributed/commands/multi_copy.c [hunk 12]
```diff
@@ -986,6 +1024,46 @@ OpenCopyTransactions(CopyStmt *copyStatement, ShardConnections *shardConnections
...
+		char typeCategory = '\0';
+		bool typePreferred = false;
+		bool builtInType = typeId < FirstNormalObjectId;
```
Comment (anarazel) [inline src/backend/distributed/commands/multi_copy.c]: Same here.

File: src/backend/distributed/commands/multi_copy.c [hunk 13]
```diff
@@ -1075,23 +1153,26 @@ SendCopyBinaryFooters(CopyOutState copyOutState, List *connectionList)
...
+ConstructCopyStatement(CopyStmt *copyStatement, int64 shardId, bool useBinaryCopyFormat)
 {
 	StringInfo command = makeStringInfo();
 
-	char *schemaName = copyStatement->relation->schemaname;
-	char *relationName = copyStatement->relation->relname;
-
-	char *shardName = pstrdup(relationName);
+	char *shardSchemaName = copyStatement->relation->schemaname;
+	char *shardTableName = pstrdup(copyStatement->relation->relname);
```
Comment (anarazel) [inline src/backend/distributed/commands/multi_copy.c]: For the future, please don't perform independent refactoring in the same commit as an independent functional change.

File: src/backend/distributed/commands/multi_copy.c [hunk 14]
```diff
@@ -1075,23 +1153,26 @@ SendCopyBinaryFooters(CopyOutState copyOutState, List *connectionList)
...
-					 shardQualifiedName);
+	if (useBinaryCopyFormat)
+	{
+		appendStringInfo(command, "COPY %s FROM STDIN WITH (FORMAT BINARY)",
+						 shardQualifiedName);
+	}
+	else
+	{
+		appendStringInfo(command, "COPY %s FROM STDIN", shardQualifiedName);
+	}
```
Comment (anarazel) [inline src/backend/distributed/commands/multi_copy.c]: Wouldn't it be better to only have one appendStringInfo() here, but store the format in another variable? I.e. something like
```
const char *copyFormat = NULL;
...
if (useBinaryCopyFormat)
{
     copyFormat = "BINARY"; 
}
else
{
     copyFormat = "TEXT"; 
}
```
appendStringInfo(command, "COPY %s FROM STDIN (FORMAT %s)", shardQualifiedName, copyFormat);

File: src/backend/distributed/commands/multi_copy.c [hunk 15]
```diff
@@ -1259,7 +1340,8 @@ ColumnOutputFunctions(TupleDesc rowDescriptor, bool binaryFormat)
 		}
 		else if (binaryFormat)
 		{
-			getTypeBinaryOutputInfo(columnTypeId, &outputFunctionId, &typeVariableLength);
+			getTypeBinaryOutputInfo(columnTypeId, &outputFunctionId,
+									&typeVariableLength);
```
Comment (anarazel) [inline src/backend/distributed/commands/multi_copy.c]: Independent change.

**Comment by byucesoy** [comment]
@anarazel I changed the patch based on your comments. Could you check it?

File: src/backend/distributed/commands/multi_copy.c [hunk 16]
```diff
@@ -348,6 +352,8 @@ CopyToExistingShards(CopyStmt *copyStatement, char *completionTag)
 	FmgrInfo *compareFunction = NULL;
 	bool hasUniformHashDistribution = false;
 	DistTableCacheEntry *cacheEntry = DistributedTableCacheEntry(tableId);
+	char *delimiterCharacter = pstrdup("\t");
+	char *nullPrintCharacter = pstrdup("\\N");
```
Comment (anarazel) [inline src/backend/distributed/commands/multi_copy.c]: These shouldn't be dynamically allocated.

File: src/backend/distributed/commands/multi_copy.c [hunk 17]
```diff
@@ -615,6 +632,9 @@ CopyToNewShards(CopyStmt *copyStatement, char *completionTag, Oid relationId)
 	MemoryContext executorTupleContext = GetPerTupleMemoryContext(executorState);
 	ExprContext *executorExpressionContext = GetPerTupleExprContext(executorState);
 
+	char *delimiterCharacter = pstrdup("\t");
+	char *nullPrintCharacter = pstrdup("\\N");
+
```
Comment (anarazel) [inline src/backend/distributed/commands/multi_copy.c]: Same as above.

File: src/backend/distributed/commands/multi_copy.c [hunk 18]
```diff
@@ -986,6 +1023,49 @@ OpenCopyTransactions(CopyStmt *copyStatement, ShardConnections *shardConnections
...
+		{
+			continue;
+		}
+
+		typeId = currentColumn->atttypid;
+		builtInType = typeId < FirstNormalObjectId;
+
+		get_type_category_preferred(typeId, &typeCategory, &typePreferred);
+		containsOid = typeCategory == TYPCATEGORY_ARRAY ||
+					  typeCategory == TYPCATEGORY_COMPOSITE;
```
Comment (anarazel) [inline src/backend/distributed/commands/multi_copy.c]: We shouldn't perform these tests when it's a builtin type. They're not all that cheap.

File: src/backend/distributed/commands/multi_copy.c [hunk 19]
```diff
@@ -1075,23 +1155,29 @@ SendCopyBinaryFooters(CopyOutState copyOutState, List *connectionList)
...
-ConstructCopyStatement(CopyStmt *copyStatement, int64 shardId)
+ConstructCopyStatement(CopyStmt *copyStatement, int64 shardId, bool useBinaryCopyFormat)
 {
 	StringInfo command = makeStringInfo();
 
 	char *schemaName = copyStatement->relation->schemaname;
-	char *relationName = copyStatement->relation->relname;
-
-	char *shardName = pstrdup(relationName);
+	char *relationName = pstrdup(copyStatement->relation->relname);
```
Comment (anarazel) [inline src/backend/distributed/commands/multi_copy.c]: These changes appear to be unrelated.

**Comment by byucesoy** [comment]
Hi @anarazel, all done. Do you have any other comments?

File: src/backend/distributed/commands/multi_copy.c [hunk 20]
```diff
@@ -348,6 +352,8 @@ CopyToExistingShards(CopyStmt *copyStatement, char *completionTag)
 	FmgrInfo *compareFunction = NULL;
 	bool hasUniformHashDistribution = false;
 	DistTableCacheEntry *cacheEntry = DistributedTableCacheEntry(tableId);
+	char *delimiterCharacter = "\t";
+	char *nullPrintCharacter = "\\N";
```
Comment (anarazel) [inline src/backend/distributed/commands/multi_copy.c]: these should be const - doesn't your compiler warn you here?

File: src/backend/distributed/commands/multi_copy.c [hunk 21]
```diff
@@ -615,6 +632,9 @@ CopyToNewShards(CopyStmt *copyStatement, char *completionTag, Oid relationId)
 	MemoryContext executorTupleContext = GetPerTupleMemoryContext(executorState);
 	ExprContext *executorExpressionContext = GetPerTupleExprContext(executorState);
 
+	char *delimiterCharacter = "\t";
+	char *nullPrintCharacter = "\\N";
```
Comment (anarazel) [inline src/backend/distributed/commands/multi_copy.c]: Same.

**Comment by byucesoy** [comment]
Hi @anarazel my compiler did not produce warning for that lines. Anyway, I changed type of these variables to const char*

**Comment by anarazel** [comment]
@lithp Could you have a final look? Looks good to me.

File: src/backend/distributed/commands/multi_copy.c [hunk 22]
```diff
@@ -441,7 +447,10 @@ CopyToExistingShards(CopyStmt *copyStatement, char *completionTag)
 	executorExpressionContext = GetPerTupleExprContext(executorState);
 
 	copyOutState = (CopyOutState) palloc0(sizeof(CopyOutStateData));
-	copyOutState->binary = true;
+	copyOutState->delim = delimiterCharacter;
+	copyOutState->null_print = nullPrintCharacter;
+	copyOutState->null_print_client = nullPrintCharacter;
```
Comment (lithp) [inline src/backend/distributed/commands/multi_copy.c]: I get some compiler warnings:

```
commands/multi_copy.c: In function ‘CopyToExistingShards’:
commands/multi_copy.c:450:22: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  copyOutState->delim = delimiterCharacter;
                      ^
commands/multi_copy.c:451:27: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  copyOutState->null_print = nullPrintCharacter;
                           ^
commands/multi_copy.c:452:34: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  copyOutState->null_print_client = nullPrintCharacter;
                                  ^
```

File: src/backend/distributed/commands/multi_copy.c [hunk 23]
```diff
@@ -631,7 +651,10 @@ CopyToNewShards(CopyStmt *copyStatement, char *completionTag, Oid relationId)
 										copyStatement->options);
 
 	CopyOutState copyOutState = (CopyOutState) palloc0(sizeof(CopyOutStateData));
-	copyOutState->binary = true;
+	copyOutState->delim = delimiterCharacter;
+	copyOutState->null_print = nullPrintCharacter;
+	copyOutState->null_print_client = nullPrintCharacter;
```
Comment (lithp) [inline src/backend/distributed/commands/multi_copy.c]: More compiler warnings:

```
commands/multi_copy.c: In function ‘CopyToNewShards’:
commands/multi_copy.c:654:22: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  copyOutState->delim = delimiterCharacter;
                      ^
commands/multi_copy.c:655:27: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  copyOutState->null_print = nullPrintCharacter;
                           ^
commands/multi_copy.c:656:34: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  copyOutState->null_print_client = nullPrintCharacter;
                                  ^
```

Comment (anarazel) [inline src/backend/distributed/commands/multi_copy.c]: On 2016-07-12 08:21:18 -0700, Brian Cloutier wrote:
> > @@ -631,7 +651,10 @@ CopyToNewShards(CopyStmt *copyStatement, char *completionTag, Oid relationId)
> >  										copyStatement->options);
> >  
> >  	CopyOutState copyOutState = (CopyOutState) palloc0(sizeof(CopyOutStateData));
> > -	copyOutState->binary = true;
> > +	copyOutState->delim = delimiterCharacter;
> > +	copyOutState->null_print = nullPrintCharacter;
> > +	copyOutState->null_print_client = nullPrintCharacter;
> 
> More compiler warnings:
> 
> ```
> commands/multi_copy.c: In function ‘CopyToNewShards’:
> commands/multi_copy.c:654:22: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
>   copyOutState->delim = delimiterCharacter;
>                       ^
> commands/multi_copy.c:655:27: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
>   copyOutState->null_print = nullPrintCharacter;
>                            ^
> commands/multi_copy.c:656:34: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
>   copyOutState->null_print_client = nullPrintCharacter;
>                                   ^
> ```

Burak, what compiler do you use? These are pretty common warnings, and
IIRC are automatically enabled by our configure script?

Comment (byucesoy) [inline src/backend/distributed/commands/multi_copy.c]: I found the problem, somehow I added a line something like;
`make -s` 
to build script which I created for my local use. I removed -s parameter and it shows all warnings now.

File: src/backend/distributed/commands/multi_copy.c [hunk 24]
```diff
@@ -986,6 +1023,49 @@ OpenCopyTransactions(CopyStmt *copyStatement, ShardConnections *shardConnections
 
 
 /*
+ * CanUseBinaryCopyFormat iterates over columns of the relation given in rowOutputState
+ * and looks for a column whose type is array of user-defined type or composite type.
```
Comment (lithp) [inline src/backend/distributed/commands/multi_copy.c]: This line has a trailing space

File: src/backend/distributed/commands/multi_copy.c [hunk 25]
```diff
@@ -986,6 +1023,49 @@ OpenCopyTransactions(CopyStmt *copyStatement, ShardConnections *shardConnections
...
+		{
+			continue;
+		}
+
+		typeId = currentColumn->atttypid;
+		if (typeId >= FirstNormalObjectId)
+		{
+			get_type_category_preferred(typeId, &typeCategory, &typePreferred);
+			if (typeCategory == TYPCATEGORY_ARRAY || 
+			    typeCategory == TYPCATEGORY_COMPOSITE)
```
Comment (lithp) [inline src/backend/distributed/commands/multi_copy.c]: This is indented with spaces where tabs will do

File: src/backend/distributed/commands/multi_copy.c (hunk 23 above)
Comment (anarazel) [inline src/backend/distributed/commands/multi_copy.c]: On 2016-07-13 00:25:57 -0700, Burak Yücesoy wrote:
> > @@ -631,7 +651,10 @@ CopyToNewShards(CopyStmt *copyStatement, char *completionTag, Oid relationId)
> >  										copyStatement->options);
> >  
> >  	CopyOutState copyOutState = (CopyOutState) palloc0(sizeof(CopyOutStateData));
> > -	copyOutState->binary = true;
> > +	copyOutState->delim = delimiterCharacter;
> > +	copyOutState->null_print = nullPrintCharacter;
> > +	copyOutState->null_print_client = nullPrintCharacter;
> 
> I found the problem, somehow I added a line something like;
> `make -s` 
> to build script which I created for my local use. I removed -s parameter and it shows all warnings now.

But -s doesn't hide warnings?

**Comment by lithp** [comment]
(Those last two were caught by citus_indent)

File: src/backend/distributed/commands/multi_copy.c [hunk 26]
```diff
@@ -986,6 +1023,49 @@ OpenCopyTransactions(CopyStmt *copyStatement, ShardConnections *shardConnections
...
+ * worker nodes for user-defined types.
+ */
+static bool
+CanUseBinaryCopyFormat(TupleDesc tupleDescription, CopyOutState rowOutputState)
+{
+	bool useBinaryCopyFormat = true;
+	int totalColumnCount = tupleDescription->natts;
+	int columnIndex = 0;
+
+	for (columnIndex = 0; columnIndex < totalColumnCount; columnIndex++)
```
Comment (lithp) [inline src/backend/distributed/commands/multi_copy.c]: I think it doesn't block the PR at all, I would only care if there was more code after the loop, but so I know what our preferred code style is... @anarazel wouldn't it be better to declare columnIndex inside the loop itself, on line 1039?

File: src/test/regress/input/multi_copy.source [hunk 27]
```diff
@@ -414,3 +414,99 @@ WITH (FORMAT 'csv');
...
+        packed_numbers number_pack[]
+);
+
+SELECT master_create_distributed_table('packed_numbers_append', 'id', 'append');
+COPY packed_numbers_append FROM '/tmp/copy_test_array_of_composite';
+
+-- Verify data is actually copied
+SELECT * FROM packed_numbers_append;
+
+-- Test composite type containing an element with different Oid with append distribution
```
Comment (lithp) [inline src/test/regress/input/multi_copy.source]: It'd be nice to have a SELECT which checks that the Oids are actually different between the master and workers but I can't think of an easy way to write it.

File: src/backend/distributed/commands/multi_copy.c (hunk 23 above)
Comment (byucesoy) [inline src/backend/distributed/commands/multi_copy.c]: I added it for that reason, hide regular output and only see errors and warnings and my setup was working for quite bit of time. I am not sure why it stopped to show warnings. Maybe some other stuff affected it, but I dont know at the moment.

**Comment by lithp** [comment]
I'm happy :)

Fix the citus_indent issues and shit it!

**Comment by byucesoy** [comment]
I tried on two different machines, there are no new warnings. citus_indent does not fix anything new also.
