### PR TITLE
Fix nextval('seq_name'::text) bug, and schema for seq tests

### LINKED ISSUE #5037: create_reference_table crashes when casting a sequence, on single node
On single node Citus, `create_reference_table` crashes, if there's a column set to the next value of a casted sequence. Here is an example to reproduce:
```
CREATE SEQUENCE seq;
CREATE TABLE t1 (
    col1 int DEFAULT nextval('seq'::text)
);
SELECT create_reference_table('t1');
```
Backtrace:
```
#0  EnsureSequenceTypeSupported (relationId=relationId@entry=16914, attnum=<optimized out>, seqTypId=23)
    at deparser/citus_ruleutils.c:526
#1  0x00007fbebe893f45 in pg_get_tableschemadef_string (tableRelationId=tableRelationId@entry=16914,
    includeSequenceDefaults=includeSequenceDefaults@entry=false, accessMethod=accessMethod@entry=0x0)
    at deparser/citus_ruleutils.c:380
#2  0x00007fbebe8ca4ff in GetPreLoadTableCreationCommands (relationId=relationId@entry=16914,
    includeSequenceDefaults=includeSequenceDefaults@entry=false, accessMethod=accessMethod@entry=0x0)
    at operations/node_protocol.c:678
#3  0x00007fbebe8ca631 in GetFullTableCreationCommands (relationId=relationId@entry=16914,
    includeSequenceDefaults=includeSequenceDefaults@entry=false) at operations/node_protocol.c:549
#4  0x00007fbebe8d3e47 in CreateShardsOnWorkers (distributedRelationId=distributedRelationId@entry=16914,
    shardPlacements=0x562367d0c5c0, useExclusiveConnection=useExclusiveConnection@entry=false,
    colocatedShard=colocatedShard@entry=false) at operations/stage_protocol.c:547
#5  0x00007fbebe8c803c in CreateReferenceTableShard (distributedTableId=distributedTableId@entry=16914)
    at operations/create_shards.c:384
#6  0x00007fbebe870879 in CreateDistributedTable (relationId=relationId@entry=16914,
    distributionColumn=distributionColumn@entry=0x0, distributionMethod=distributionMethod@entry=110 'n',
    shardCount=32, shardCountIsStrict=shardCountIsStrict@entry=false,
    colocateWithTableName=colocateWithTableName@entry=0x0, viaDeprecatedAPI=false)
    at commands/create_distributed_table.c:496
#7  0x00007fbebe870d1c in create_reference_table (fcinfo=<optimized out>) at commands/create_distributed_table.c:312
#8  0x0000562365948292 in ExecInterpExpr (state=0x562367cc3330, econtext=0x562367cc3030, isnull=0x7fff5fb64187)
    at execExprInterp.c:699
#9  0x00005623659450f0 in ExecInterpExprStillValid (state=0x562367cc3330, econtext=0x562367cc3030,
    isNull=0x7fff5fb64187) at execExprInterp.c:1802
#10 0x0000562365981b1d in ExecEvalExprSwitchContext (isNull=0x7fff5fb64187, econtext=0x562367cc3030,
    state=0x562367cc3330) at ../../../src/include/executor/executor.h:316
#11 ExecProject (projInfo=0x562367cc3328) at ../../../src/include/executor/executor.h:350
#12 ExecResult (pstate=<optimized out>) at nodeResult.c:136
---Type <return> to continue, or q <return> to quit---
#13 0x0000562365955441 in ExecProcNodeFirst (node=0x562367cc2f18) at execProcnode.c:450
#14 0x000056236594d22b in ExecProcNode (node=0x562367cc2f18) at ../../../src/include/executor/executor.h:248
#15 ExecutePlan (estate=estate@entry=0x562367cc2ce0, planstate=0x562367cc2f18, use_parallel_mode=<optimized out>,
    operation=operation@entry=CMD_SELECT, sendTuples=sendTuples@entry=true, numberTuples=numberTuples@entry=0,
    direction=ForwardScanDirection, dest=0x562367cc9e48, execute_once=true) at execMain.c:1632
#16 0x000056236594df0c in standard_ExecutorRun (queryDesc=queryDesc@entry=0x562367b741d0,
    direction=direction@entry=ForwardScanDirection, count=count@entry=0, execute_once=execute_once@entry=true)
    at execMain.c:350
#17 0x00007fbebe8b4d8b in CitusExecutorRun (queryDesc=0x562367b741d0, direction=ForwardScanDirection, count=0,
    execute_once=<optimized out>) at executor/multi_executor.c:214
#18 0x00007fbeb87713fd in pgss_ExecutorRun (queryDesc=0x562367b741d0, direction=ForwardScanDirection, count=0,
    execute_once=<optimized out>) at pg_stat_statements.c:1043
#19 0x000056236594dfcd in ExecutorRun (queryDesc=queryDesc@entry=0x562367b741d0,
    direction=direction@entry=ForwardScanDirection, count=count@entry=0, execute_once=<optimized out>)
    at execMain.c:292
#20 0x0000562365afa666 in PortalRunSelect (portal=portal@entry=0x562367c2bf90, forward=forward@entry=true, count=0,
    count@entry=9223372036854775807, dest=dest@entry=0x562367cc9e48) at pquery.c:912
#21 0x0000562365afbd9f in PortalRun (portal=portal@entry=0x562367c2bf90, count=count@entry=9223372036854775807,
    isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x562367cc9e48,
    altdest=altdest@entry=0x562367cc9e48, qc=0x7fff5fb64720) at pquery.c:756
#22 0x0000562365af7ea6 in exec_simple_query (
    query_string=query_string@entry=0x562367b54f20 "select create_reference_table('t1');") at postgres.c:1239
#23 0x0000562365afa00b in PostgresMain (argc=<optimized out>, argv=argv@entry=0x562367bf1fb0, dbname=<optimized out>,
    username=<optimized out>) at postgres.c:4329
#24 0x0000562365a6356d in BackendRun (port=port@entry=0x562367befc30) at postmaster.c:4526
#25 0x0000562365a666d0 in BackendStartup (port=port@entry=0x562367befc30) at postmaster.c:4210
#26 0x0000562365a669d7 in ServerLoop () at postmaster.c:1739
#27 0x0000562365a67d6f in PostmasterMain (argc=5, argv=<optimized out>) at postmaster.c:1412
#28 0x00005623659ab75d in main (argc=5, argv=0x562367b4cba0) at main.c:210
```

### PR DESCRIPTION
**Pull request by naisila**
DESCRIPTION: Fix nextval('seq_name'::text) bug, and schema for seq tests

Fixes #5037 
Addresses https://github.com/citusdata/citus/pull/4914#discussion_r649252973

When defining the table with `DEFAULT nextval('seq'::text)` instead of `DEFAULT nextval('seq')`, sequence dependency is not saved.
In fact, `seq` doesn't even have to be an existing sequence for the table to be created successfully! Check out the following behavior in plain PG:
```SQL
-- table creation doesn't work
postgres=$ CREATE TABLE t1 (col0 int, col1 int DEFAULT nextval('non_existent_sequence'));
ERROR:  relation "non_existent_sequence" does not exist

-- table creation works when casting name to text
postgres=$ CREATE TABLE t1 (col0 int, col1 int DEFAULT nextval('non_existent_sequence'::text));
CREATE TABLE

-- of course later insertion will fail
postgres=$ INSERT INTO t1 VALUES (0);
ERROR:  relation "non_existent_sequence" does not exist
```

### CODE REVIEW

File: src/backend/distributed/deparser/citus_ruleutils.c [hunk 1]
```diff
@@ -523,44 +523,54 @@ EnsureSequenceTypeSupported(Oid relationId, AttrNumber attnum, Oid seqTypId)
...
-	Oid citusTableId = InvalidOid;
-	foreach_oid(citusTableId, citusTableIdList)
+	/*
+	 * We need this check because sometimes there are cases where the
+	 * dependency between the table and the sequence is not formed
+	 * One example is when the default is defined by
+	 * DEFAULT nextval('seq_name'::text) (not by DEFAULT nextval('seq_name'))
+	 * In these cases, sequencesFromAttrDef with be empty.
+	 */
+	else if (list_length(sequencesFromAttrDef) == 1)
```
Comment (marcocitus) [inline src/backend/distributed/deparser/citus_ruleutils.c:533]: I was a slightly confused by this check because it is checking the opposite of what the comment describes.

If could be nice to have something like
```
if (list_length(sequencesFromAttrDef) == 0)
{
    /* ... describe this case ... */
    return;
}

if (list_length(sequencesFromAttrDef) > 1)
{
    /* we do not support cases like "DEFAULT nextval('..') - nextval('..')" */
    ereport(ERROR, ...);
}

```

**Review by marcocitus — APPROVED** [review]
