### PR TITLE
Prevent infinite recursion for queries that involve UNION ALL and JOIN

### LINKED ISSUE #4703: UNION ALL joined with a table/subquery crashes
From postgres/equivclass.sql, on single node (maybe I should find a more minimal table schema to reproduce):

Reproduced on 9.5.2 too.

```sql
create type int8alias1;
create function int8alias1in(cstring) returns int8alias1
  strict immutable language internal as 'int8in';
create function int8alias1out(int8alias1) returns cstring
  strict immutable language internal as 'int8out';
create type int8alias1 (
    input = int8alias1in,
    output = int8alias1out,
    like = int8
);

create type int8alias2;
create function int8alias2in(cstring) returns int8alias2
  strict immutable language internal as 'int8in';
create function int8alias2out(int8alias2) returns cstring
  strict immutable language internal as 'int8out';
create type int8alias2 (
    input = int8alias2in,
    output = int8alias2out,
    like = int8
);

create cast (int8 as int8alias1) without function;
create cast (int8 as int8alias2) without function;
create cast (int8alias1 as int8) without function;
create cast (int8alias2 as int8) without function;

create function int8alias1eq(int8alias1, int8alias1) returns bool
  strict immutable language internal as 'int8eq';
create operator = (
    procedure = int8alias1eq,
    leftarg = int8alias1, rightarg = int8alias1,
    commutator = =,
    restrict = eqsel, join = eqjoinsel,
    merges
);
alter operator family integer_ops using btree add
  operator 3 = (int8alias1, int8alias1);

create function int8alias2eq(int8alias2, int8alias2) returns bool
  strict immutable language internal as 'int8eq';
create operator = (
    procedure = int8alias2eq,
    leftarg = int8alias2, rightarg = int8alias2,
    commutator = =,
    restrict = eqsel, join = eqjoinsel,
    merges
);
alter operator family integer_ops using btree add
  operator 3 = (int8alias2, int8alias2);

create function int8alias1eq(int8, int8alias1) returns bool
  strict immutable language internal as 'int8eq';
create operator = (
    procedure = int8alias1eq,
    leftarg = int8, rightarg = int8alias1,
    restrict = eqsel, join = eqjoinsel,
    merges
);
alter operator family integer_ops using btree add
  operator 3 = (int8, int8alias1);

create function int8alias1eq(int8alias1, int8alias2) returns bool
  strict immutable language internal as 'int8eq';
create operator = (
    procedure = int8alias1eq,
    leftarg = int8alias1, rightarg = int8alias2,
    restrict = eqsel, join = eqjoinsel,
    merges
);
alter operator family integer_ops using btree add
  operator 3 = (int8alias1, int8alias2);

create function int8alias1lt(int8alias1, int8alias1) returns bool
  strict immutable language internal as 'int8lt';
create operator < (
    procedure = int8alias1lt,
    leftarg = int8alias1, rightarg = int8alias1
);
alter operator family integer_ops using btree add
  operator 1 < (int8alias1, int8alias1);

create function int8alias1cmp(int8, int8alias1) returns int
  strict immutable language internal as 'btint8cmp';
alter operator family integer_ops using btree add
  function 1 int8alias1cmp (int8, int8alias1);
```

```sql
create table ec1 (ff int8 primary key, f1 int8alias1, f2 int8alias2);

SELECT create_distributed_table('ec1', 'ff');
  
  select * from ec1,
    (select ff + 1 as x from
       (select ff + 2 as ff from ec1
        union all
        select ff + 3 as ff from ec1) ss0
     union all
     select ff + 4 as x from ec1) as ss1
  where ss1.x = ec1.f1 and ec1.ff = 42::int8;  
```

We end up doing infinite recursion in this codepath and finally it segfaults:

```c
AddToAttributeEquivalenceClass
AddRteSubqueryToAttributeEquivalenceClass,
AddUnionAllSetOperationsToAttributeEquivalenceClass  
AddToAttributeEquivalenceClass 
....
```

```c
#0  0x00007fb61fcc0c95 in AddUnionAllSetOperationsToAttributeEquivalenceClass (attributeEquivalenceClass=0x7ffe9f051458, root=0x2675128,
    varToBeAdded=<error reading variable: Cannot access memory at address 0x7ffe9e852ff8>) at planner/relation_restriction_equivalence.c:1361
#1  0x00007fb61fcc0b1a in AddRteSubqueryToAttributeEquivalenceClass (attributeEquivalenceClass=0x7ffe9f051458, rangeTableEntry=0x26782e8, root=0x2675128,
    varToBeAdded=0x2679a28) at planner/relation_restriction_equivalence.c:1292
#2  0x00007fb61fcc0a38 in AddToAttributeEquivalenceClass (attributeEquivalenceClass=0x7ffe9f051458, root=0x2675128, varToBeAdded=0x2679a28)
    at planner/relation_restriction_equivalence.c:1220
#3  0x00007fb61fcc0d17 in AddUnionAllSetOperationsToAttributeEquivalenceClass (attributeEquivalenceClass=0x7ffe9f051458, root=0x2675128,
    varToBeAdded=0x2679a28) at planner/relation_restriction_equivalence.c:1383
#4  0x00007fb61fcc0b1a in AddRteSubqueryToAttributeEquivalenceClass (attributeEquivalenceClass=0x7ffe9f051458, rangeTableEntry=0x26782e8, root=0x2675128,
    varToBeAdded=0x2679a28) at planner/relation_restriction_equivalence.c:1292
#5  0x00007fb61fcc0a38 in AddToAttributeEquivalenceClass (attributeEquivalenceClass=0x7ffe9f051458, root=0x2675128, varToBeAdded=0x2679a28)
    at planner/relation_restriction_equivalence.c:1220
#6  0x00007fb61fcc0d17 in AddUnionAllSetOperationsToAttributeEquivalenceClass (attributeEquivalenceClass=0x7ffe9f051458, root=0x2675128,
    varToBeAdded=0x2679a28) at planner/relation_restriction_equivalence.c:1383
#7  0x00007fb61fcc0b1a in AddRteSubqueryToAttributeEquivalenceClass (attributeEquivalenceClass=0x7ffe9f051458, rangeTableEntry=0x26782e8, root=0x2675128,
    varToBeAdded=0x2679a28) at planner/relation_restriction_equivalence.c:1292
#8  0x00007fb61fcc0a38 in AddToAttributeEquivalenceClass (attributeEquivalenceClass=0x7ffe9f051458, root=0x2675128, varToBeAdded=0x2679a28)
    at planner/relation_restriction_equivalence.c:1220
#9  0x00007fb61fcc0d17 in AddUnionAllSetOperationsToAttributeEquivalenceClass (attributeEquivalenceClass=0x7ffe9f051458, root=0x2675128,
    varToBeAdded=0x2679a28) at planner/relation_restriction_equivalence.c:1383
#10 0x00007fb61fcc0b1a in AddRteSubqueryToAttributeEquivalenceClass (attributeEquivalenceClass=0x7ffe9f051458, rangeTableEntry=0x26782e8, root=0x2675128,
    varToBeAdded=0x2679a28) at planner/relation_restriction_equivalence.c:1292
...
...
...
#104766 0x00007fb61fcc0d17 in AddUnionAllSetOperationsToAttributeEquivalenceClass (attributeEquivalenceClass=0x7ffe9f051458, root=0x2675128,
    varToBeAdded=0x2640db0) at planner/relation_restriction_equivalence.c:1383
#104767 0x00007fb61fcc0b1a in AddRteSubqueryToAttributeEquivalenceClass (attributeEquivalenceClass=0x7ffe9f051458, rangeTableEntry=0x25843e8,
    root=0x2675128, varToBeAdded=0x2640db0) at planner/relation_restriction_equivalence.c:1292
#104768 0x00007fb61fcc0a38 in AddToAttributeEquivalenceClass (attributeEquivalenceClass=0x7ffe9f051458, root=0x2675128, varToBeAdded=0x7fb6243967f8)
    at planner/relation_restriction_equivalence.c:1220
#104769 0x00007fb61fcc0082 in AttributeEquivalenceClassForEquivalenceClass (plannerEqClass=0x7fb624397780, relationRestriction=0x7fb62439cbf0)
    at planner/relation_restriction_equivalence.c:797
#104770 0x00007fb61fcbfe96 in GenerateAttributeEquivalencesForRelationRestrictions (restrictionContext=0x2674ff0)
    at planner/relation_restriction_equivalence.c:735
#104771 0x00007fb61fcbfb36 in GenerateAllAttributeEquivalences (plannerRestrictionContext=0x2674c28) at planner/relation_restriction_equivalence.c:586
#104772 0x00007fb61fcbfa5b in RestrictionEquivalenceForPartitionKeys (restrictionContext=0x2674c28) at planner/relation_restriction_equivalence.c:501
#104773 0x00007fb61fcbf4b1 in AllDistributionKeysInQueryAreEqual (originalQuery=0x2583e90, plannerRestrictionContext=0x2674c28)
    at planner/relation_restriction_equivalence.c:186
#104774 0x00007fb61fcbc655 in GenerateSubplansForSubqueriesAndCTEs (planId=1, originalQuery=0x2583e90, plannerRestrictionContext=0x2674c28)
    at planner/recursive_planning.c:236
#104775 0x00007fb61fc8c7ea in CreateDistributedPlan (planId=1, originalQuery=0x2583e90, query=0x2583fa8, boundParams=0x0, hasUnresolvedParams=false,
    plannerRestrictionContext=0x2674c28) at planner/distributed_planner.c:978
#104776 0x00007fb61fc8c0e8 in CreateDistributedPlannedStmt (planContext=0x7ffe9f0517f0) at planner/distributed_planner.c:646
#104777 0x00007fb61fc8bfe7 in PlanDistributedStmt (planContext=0x7ffe9f0517f0, rteIdCounter=5) at planner/distributed_planner.c:583
#104778 0x00007fb61fc8b88b in distributed_planner (parse=0x2583fa8,
    query_string=0x24f4af0 "select * from ec1,\n    (select ff + 1 as x from\n       (select ff + 2 as ff from ec1\n        union all\n        select ff + 3 as ff from ec1) ss0\n     union all\n     select ff + 4 as x from ec1) as ss1\n  where ss1.x = ec1.f1 and ec1.ff = 42::int8;", cursorOptions=256,
    boundParams=0x0) at planner/distributed_planner.c:231
#104779 0x0000000000840313 in planner (parse=0x2583fa8,
    query_string=0x24f4af0 "select * from ec1,\n    (select ff + 1 as x from\n       (select ff + 2 as ff from ec1\n        union all\n        select ff + 3 as ff from ec1) ss0\n     union all\n     select ff + 4 as x from ec1) as ss1\n  where ss1.x = ec1.f1 and ec1.ff = 42::int8;", cursorOptions=256,
    boundParams=0x0) at planner.c:273
#104780 0x0000000000969f88 in pg_plan_query (querytree=0x2583fa8,
    query_string=0x24f4af0 "select * from ec1,\n    (select ff + 1 as x from\n       (select ff + 2 as ff from ec1\n        union all\n        select ff + 3 as ff from ec1) ss0\n     union all\n     select ff + 4 as x from ec1) as ss1\n  where ss1.x = ec1.f1 and ec1.ff = 42::int8;", cursorOptions=256,
    boundParams=0x0) at postgres.c:875
#104781 0x000000000096a0c0 in pg_plan_queries (querytrees=0x2642598,
    query_string=0x24f4af0 "select * from ec1,\n    (select ff + 1 as x from\n       (select ff + 2 as ff from ec1\n        union all\n        select ff + 3 as ff from ec1) ss0\n     union all\n     select ff + 4 as x from ec1) as ss1\n  where ss1.x = ec1.f1 and ec1.ff = 42::int8;", cursorOptions=256,
    boundParams=0x0) at postgres.c:966
#104782 0x000000000096a481 in exec_simple_query (
    query_string=0x24f4af0 "select * from ec1,\n    (select ff + 1 as x from\n       (select ff + 2 as ff from ec1\n        union all\n        select ff + 3 as ff from ec1) ss0\n     union all\n     select ff + 4 as x from ec1) as ss1\n  where ss1.x = ec1.f1 and ec1.ff = 42::int8;") at postgres.c:1158
#104783 0x000000000096e96d in PostgresMain (argc=1, argv=0x25890d0, dbname=0x2588fe8 "postgres", username=0x2588fc0 "postgres") at postgres.c:4315
#104784 0x00000000008b5ca3 in BackendRun (port=0x257c810) at postmaster.c:4536
#104785 0x00000000008b541c in BackendStartup (port=0x257c810) at postmaster.c:4220
#104786 0x00000000008b1851 in ServerLoop () at postmaster.c:1739
#104787 0x00000000008b1080 in PostmasterMain (argc=3, argv=0x24ef760) at postmaster.c:1412
#104788 0x00000000007b0914 in main (argc=3, argv=0x24ef760) at main.c:210
```

### PR DESCRIPTION
**Pull request by onderkalaci**
With this commit, we make sure to prevent infinite recursion for queries
in the format: [subquery with a UNION ALL] JOIN [table or subquery]

Also, fixes a bug where we pushdown UNION ALL below a JOIN even if the
UNION ALL is not safe to pushdown.

DESCRIPTION: Prevent infinite recursion for queries that involve UNION ALL below JOIN

Fixes #4703

### CODE REVIEW

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 1]
```diff
@@ -1383,16 +1386,94 @@ AddUnionAllSetOperationsToAttributeEquivalenceClass(AttributeEquivalenceClass **
...
 
+/*
+ * TranslatedVarsForRteIdentity gets an rteIdentity and returns the
+ * translatedVars that belong to the range table relation. If no
+ * translatedVars found, the function returns NIL;
+ */
+static List *
+TranslatedVarsForRteIdentity(int rteIdentity)
+{
+	PlannerRestrictionContext *currentPlannerRestrictionContext =
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1458]: It is not the best approach to call `CurrentPlannerRestrictionContext ()` at this point. However, otherwise all the APIs `(starting from AddToAttributeEquivalenceClass())` need to change significantly and I wanted to get some feedback before doing that.

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 2]
```diff
@@ -1383,16 +1386,94 @@ AddUnionAllSetOperationsToAttributeEquivalenceClass(AttributeEquivalenceClass **
...
+								&partitionKeyIndex);
+			if (partitionKeyIndex == 0)
+			{
+				/* no partition key on the target list */
+				continue;
+			}
 
-		AddToAttributeEquivalenceClass(attributeEquivalenceClass, root,
-									   varToBeAdded);
+			if (unionQueryPartitionKeyIndex == 0)
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1418]: This check is not enough for queries like:
```SQL
SELECT * FROM
(
	SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT user_id, value_1 FROM users_table_part UNION ALL SELECT user_id, value_1 FROM users_table_part) as level_5) as level_4) as level_3) as level_2) as level_1
	UNION ALL
	SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT value_1, user_id FROM users_table_part UNION ALL SELECT value_1, user_id FROM users_table_part) as level_5) as level_4) as level_3) as level_2) as level_1
) as top_level
JOIN
events_table_part USING(user_id)
 ORDER BY 1 DESC LIMIT 3;
```

Comment (onderkalaci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c]: fixed it by the last commit

File: src/test/regress/sql/union_pushdown.sql [hunk 3]
```diff
@@ -230,5 +230,297 @@ SELECT DISTINCT user_id FROM
...
+	SELECT * FROM
+	(
+		(((SELECT * FROM users_table_part JOIN events_table_part USING (user_id)) UNION ALL (SELECT * FROM users_table_part JOIN events_table_part USING (user_id))) as l1
+			JOIN
+		((SELECT * FROM users_table_part JOIN events_table_part USING (user_id)) UNION ALL (SELECT * FROM users_table_part JOIN events_table_part USING (user_id))) as l2
+			USING(user_id))
+	) as right_subquery
+) as top_level_righy USING (user_id)
+ORDER BY user_id DESC
+) ORDER BY 1 LIMIT 1;
```
Comment (SaitTalhaNisanci) [inline src/test/regress/sql/union_pushdown.sql:365]: If the `events_table_part` is a reference table I get this error:

`+ERROR:  no distribution column found for relation 17051, because it is a reference table`

This comes from the join order but is this expected? Also we should probably give the table name in this error


```
CREATE TABLE events_table_part(user_id bigint, value_1 int, value_2 int) ;
-- CREATE TABLE events_table_part_0 PARTITION OF events_table_part FOR VALUES FROM (0) TO (1);
-- CREATE TABLE events_table_part_1 PARTITION OF events_table_part FOR VALUES FROM (1) TO (2);
-- CREATE TABLE events_table_part_2 PARTITION OF events_table_part FOR VALUES FROM (2) TO (3);
-- CREATE TABLE events_table_part_3 PARTITION OF events_table_part FOR VALUES FROM (3) TO (4);
-- CREATE TABLE events_table_part_4 PARTITION OF events_table_part FOR VALUES FROM (4) TO (5);
-- CREATE TABLE events_table_part_5 PARTITION OF events_table_part FOR VALUES FROM (5) TO (6);
-- CREATE TABLE events_table_part_6 PARTITION OF events_table_part FOR VALUES FROM (6) TO (7);
-- CREATE TABLE events_table_part_7 PARTITION OF events_table_part FOR VALUES FROM (7) TO (8);
-- CREATE TABLE events_table_part_8 PARTITION OF events_table_part FOR VALUES FROM (8) TO (9);
SELECT create_reference_table('events_table_part');
```

Comment (SaitTalhaNisanci) [reply src/test/regress/sql/union_pushdown.sql:365]: And if this is a citus local table we get:

` relation events_table_part is not distributed`

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 4]
```diff
@@ -1383,16 +1386,96 @@ AddUnionAllSetOperationsToAttributeEquivalenceClass(AttributeEquivalenceClass **
...
+								&partitionKeyIndex);
+			if (partitionKeyIndex == 0)
+			{
+				/* no partition key on the target list */
+				continue;
+			}
 
-		AddToAttributeEquivalenceClass(attributeEquivalenceClass, root,
-									   varToBeAdded);
+			if ((*attributeEquivalenceClass)->unionQueryPartitionKeyIndex == 0)
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1418]: these `(*attributeEquivalenceClass)->` seem a bit hard to read, can we avoid it?

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 5]
```diff
@@ -1383,16 +1386,96 @@ AddUnionAllSetOperationsToAttributeEquivalenceClass(AttributeEquivalenceClass **
...
+				 * Partition keys on the leaves of the UNION ALL queries on
+				 * different ordinal positions. We cannot pushdown, so skip.
+				 */
+				continue;
+			}
+
+			if (varOnUnionAllSubquery != NULL)
+			{
+				AddToAttributeEquivalenceClass(attributeEquivalenceClass, root,
+											   varOnUnionAllSubquery);
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1437]: Here it feels a bit strange that we don't add `varToBeAdded` when there is a variable called `varToBeAdded`. Do you think we can have a method that returns the var to be added (or NULL if we don't need to continue) so that this method is simplified?

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 6]
```diff
@@ -1383,16 +1386,96 @@ AddUnionAllSetOperationsToAttributeEquivalenceClass(AttributeEquivalenceClass **
 			continue;
 		}
 		int rtoffset = RangeTableOffsetCompat(root, appendRelInfo);
+		int childRelId = appendRelInfo->child_relid - rtoffset;
 
-		/* set the varno accordingly for this specific child */
-		varToBeAdded->varno = appendRelInfo->child_relid - rtoffset;
+		RangeTblEntry *rte = root->simple_rte_array[childRelId];
```
[the remark this answers is not in the document]
Comment (onderkalaci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:1391]: > Do you think it makes sense to error here if childRelId < root->simple_rel_array_size

Maybe not error, but just skip is better?

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 7]
```diff
@@ -1383,16 +1386,96 @@ AddUnionAllSetOperationsToAttributeEquivalenceClass(AttributeEquivalenceClass **
...
+		{
+			Index partitionKeyIndex = 0;
+			List *translatedVars = TranslatedVarsForRteIdentity(GetRTEIdentity(rte));
+			Var *varOnUnionAllSubquery =
+				FindUnionAllVar(root, translatedVars, rte->relid, childRelId,
+								&partitionKeyIndex);
+			if (partitionKeyIndex == 0)
+			{
+				/* no partition key on the target list */
+				continue;
```
[the remark this answers is not in the document]
Comment (onderkalaci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:1415]: I think we should not because that'd mean that we skip the remaining of the `appendRelList`. And, if the one that we just skipped via `continue` has a dist. key equivalence via another relationship (like a  join), we can still pushdown the whole query

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 6 above)
[the remark this answers is not in the document]
Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:1391]: umm, skipping might be better. But if that happens we would also want to know that. So how can we know that this happened in a production cluster without the user seeing an error etc? I guess this isn't possible

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 5 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:1437]: Hmm, I guess a rename to the variable is good enough: `varToBeAddedOnUnionAllSubquery`, let me know if you think otherwise.

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 1 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:1460]: > Or what about we move this method to distributed_planner ?

I think this is a good idea, and yes keeping `CurrentPlannerRestrictionContext ` static is better

Comment (onderkalaci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:1460]: > umm, can we avoid making CurrentPlannerRestrictionContext public? I think we could have a method like CurrentRelationRestrictionList that returns the restriction list, which is what we need here.

I don't see much difference if we move this function to distributed_planner, what do you think?

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 6 above)
[the remark this answers is not in the document]
Comment (onderkalaci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:1391]: we may have a DEBUG2 message?

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 1 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c]: if we move to distributed_planner then we don't need to have `CurrentRelationRestrictionList`

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 6 above)
[the remark this answers is not in the document]
Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:1406]: but DEBUG2 will not be logged in production in general?

I think you can choose either way (Skipping is already a good idea). My thinking was this "if there is a bug here in production, it will be hard to find. Hence if we could at least log this or somehow know that this happened, we can try to fix it without users realizing it"

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 8]
```diff
@@ -431,6 +434,13 @@ static Var *
 FindUnionAllVar(PlannerInfo *root, List *translatedVars, Oid relationOid,
 				Index relationRteIndex, Index *partitionKeyIndex)
 {
+	if (!IsCitusTableType(relationOid, STRICTLY_PARTITIONED_DISTRIBUTED_TABLE))
+	{
+		/* we only care about hash and range partitioned tables */
+		*partitionKeyIndex = 0;
+		return NULL;
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:441]: would that make sense to add a single test with reference table to trigger this line?

File: src/test/regress/sql/union_pushdown.sql [hunk 9]
```diff
@@ -230,5 +236,381 @@ SELECT DISTINCT user_id FROM
...
+	UNION ALL
+	SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM users_table_part UNION ALL SELECT * FROM users_table_part) as level_5) as level_4) as level_3) as level_2) as level_1
+) as top_level
+JOIN
+events_table_part USING(user_id)
+ ORDER BY 1 DESC LIMIT 3;
+
+-- UNION ALL leaf queries deep in the subquery
+-- and random() calls prevent any pullup
+SELECT user_id FROM
```
Comment (SaitTalhaNisanci) [inline src/test/regress/sql/union_pushdown.sql:271]: Minor: is there any value in having union all that is not in leaf or at top level but in between?

File: src/test/regress/sql/union_pushdown.sql [hunk 10]
```diff
@@ -230,5 +236,381 @@ SELECT DISTINCT user_id FROM
 USING (user_id)
 ORDER BY 1 LIMIT 1;
 
+-- UNION ALL leaf queries deep in the subquery
+SELECT * FROM
```
Comment (SaitTalhaNisanci) [inline src/test/regress/sql/union_pushdown.sql:240]: Do we have this test

```sql
SELECT * FROM (
    (SELECT user_id FROM users_table_part UNION ALL SELECT * FROM
         (SELECT user_id FROM users_table_part UNION ALL SELECT user_id FROM users_table_part) as bar1) as foo
    JOIN 
    (SELECT user_id FROM users_table_part UNION ALL SELECT * FROM 
        (SELECT user_id FROM users_table_part UNION ALL SELECT user_id FROM users_table_part) as bar2) as bar
USING (user_id)
);
```

**Review by SaitTalhaNisanci — APPROVED** [review]

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 8 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:441]: yes, added one test with local table and one with reference

File: src/test/regress/sql/union_pushdown.sql (hunk 10 above)
Comment (onderkalaci) [reply src/test/regress/sql/union_pushdown.sql:240]: added

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 4 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c]: For some reason, we used to pass `AttributeEquivalenceClass**` all over. Looking into the code-paths, that is not necessary, so I changed everything back to `AttributeEquivalenceClass*`, see the second commit

File: src/test/regress/sql/union_pushdown.sql (hunk 9 above)
Comment (onderkalaci) [reply src/test/regress/sql/union_pushdown.sql:282]: I think the main distinction is being top-level vs not top level in the code, and we have quite a lot of different cases in the test now that triggers various queryTree structures

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 11]
```diff
@@ -1383,12 +1392,74 @@ AddUnionAllSetOperationsToAttributeEquivalenceClass(AttributeEquivalenceClass **
...
 		int rtoffset = RangeTableOffsetCompat(root, appendRelInfo);
+		int childRelId = appendRelInfo->child_relid - rtoffset;
 
-		/* set the varno accordingly for this specific child */
-		varToBeAdded->varno = appendRelInfo->child_relid - rtoffset;
+		if (root->simple_rel_array_size <= childRelId)
+		{
+			/*
+			 * We always expect to find the childRel in the rte_array. Still,
+			 * being defensive is preferable.
```
Comment (marcocitus) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1401]: What is defensive about it?

Maybe: We prefer to return ever an Assert or error to be defensive.

**Review by marcocitus — APPROVED** [review]
I kind of wonder whether we could have some kind of unit tests for this particular code file.

Anyway, I did quite a bit of testing and it all seems fine and the code make sense, and our recursive planning + pushdown logic is pretty clever.

**Comment by onderkalaci** [comment]
> I kind of wonder whether we could have some kind of unit tests for this particular code file.

We actually added the test file `union_pushdown.sql` for this code, on #4746

**Comment by onderkalaci** [comment]
> I kind of wonder whether we could have some kind of unit tests for this particular code file.

Ah sorry, you are considering tests like `src/backend/distributed/test/`. Let me think about that a little

File: src/test/regress/sql/union_pushdown.sql (hunk 3 above)
Comment (onderkalaci) [reply src/test/regress/sql/union_pushdown.sql:466]: for reference we fixed this, and added regression tests
