### PR TITLE
Deparse/parse the local cached queries

### LINKED ISSUE #5038: Local execution with cached query execution mode may fail due to dropped columns
For local cached plans, Citus gets the original query and simply updates the relationIds to the corresponding shard relations via `UpdateRelationsToLocalShardTables()`. While doing that, Citus assumes that the attribute numbers of the shell table and the shard are in sync. However, under certain circumstances the attribute numbers of the shards may differ from the shell table. The main source of such changes is `DROP COLUMN ..`. And, if the attribute numbers differ, some operations may fail, such as the below:

```SQL
CREATE TABLE t1 (a int, b int, c int UNIQUE);
SELECT create_distributed_table('t1', 'c');

-- drop a column that is before "ON CONFLICT" clause
ALTER TABLE t1 DROP COLUMN b;

SELECT start_metadata_sync_to_node(nodename,nodeport) FROM pg_dist_node;

-- connect to a worker node where local execution is done
[local] onderkalaci@postgres:9701-97280=# prepare p1(int) as insert into t1(a,c) VALUES (5,$1) ON CONFLICT (c) DO NOTHING;
PREPARE
Time: 1.664 ms
[local] onderkalaci@postgres:9701-97280=# execute p1(2);
INSERT 0 0
Time: 9.402 ms
[local] onderkalaci@postgres:9701-97280=# execute p1(2);
INSERT 0 0
Time: 0.740 ms
[local] onderkalaci@postgres:9701-97280=# execute p1(2);
INSERT 0 0
Time: 1.235 ms
[local] onderkalaci@postgres:9701-97280=# execute p1(2);
INSERT 0 0
Time: 0.775 ms
[local] onderkalaci@postgres:9701-97280=# execute p1(2);
INSERT 0 0
Time: 0.987 ms
[local] onderkalaci@postgres:9701-97280=# execute p1(2);
INSERT 0 0
Time: 1.012 ms
[local] onderkalaci@postgres:9701-97280=# execute p1(2);
ERROR:  there is no unique or exclusion constraint matching the ON CONFLICT specification
Time: 0.704 ms

set client_min_messages to debug5;

execute p1(2);
DEBUG:  StartTransaction(1) name: unnamed; blockState: DEFAULT; state: INPROGRESS, xid/subid/cid: 0/1/0
DEBUG:  query before rebuilding: (null)
DEBUG:  query after rebuilding:  INSERT INTO public.t1_102098 AS citus_table_alias (a, c) VALUES (5, 2) ON CONFLICT(c) DO NOTHING
DEBUG:  assigned task 0 to node localhost:9701
ERROR:  invalid attnum 2 for relation "t1"
Time: 0.705 ms

select attrelid::regclass, attname, attnum, attisdropped from pg_attribute WHERE attrelid IN ('t1'::regclass, 't1_102102'::regclass) and attname NOT IN ('tableoid','cmax', 'xmax', 'cmin', 'xmin', 'ctid') ;
 attrelid  |           attname            | attnum | attisdropped 
-----------+------------------------------+--------+--------------
 t1_102102 | a                            |      1 | f
 t1_102102 | ........pg.dropped.2........ |      2 | t
 t1_102102 | c                            |      3 | f
 t1        | a                            |      1 | f
 t1        | c                            |      2 | f
(5 rows)
```

## Workaround to avoid the error
```SQL
SET citus.enable_local_execution TO false;
execute p1(2);
INSERT 0 0
```

# Can we reproduce with other queries

Yes, almost any query.

```SQL
prepare p2(int) as SELECT count(*) FROM t1 WHERE c = $1 GROUP BY c;

 execute p2(9);
 execute p2(9);
 execute p2(9);
 execute p2(9);
 execute p2(9);
 execute p2(9);
DEBUG:  StartTransaction(1) name: unnamed; blockState: DEFAULT; state: INPROGRESS, xid/subid/cid: 0/1/0
DEBUG:  constraint value: 9
DEBUG:  shard count after pruning for t1: 1
ERROR:  invalid attnum 2 for relation "t1"
Time: 0.827 ms

-- or with logs enabled
 execute p2(9);
NOTICE:  executing the command locally: SELECT count(*) AS count FROM public.t1_102102 t1 WHERE (c OPERATOR(pg_catalog.=) 9) GROUP BY c
ERROR:  attribute 2 of type t1_102102 has been dropped
Time: 1.153 ms
```

## Potential approaches to fix the issue:

1) Always make sure that the table definitions are in sync. So, instead of sending `CREATE TABLE ..` commands to the shards with the only existing columns, we should include all the dropped columns in the table definition as well as `DROP COLUMN` definitions.

2) As we update the shell relations to shard relations on the queryTree via `UpdateRelationsToLocalShardTables()`, we should also build a map of `Vars` on the shell tables to the shard tables. We should probably rely on column names while creating the mapping. Plus, we should be careful that we cannot simply use `varno`s as the common keys because `varno`s are defined per query. 

3) We could just deparse/parse once and then cache the plan

## Why remote executions are not affected by this (or non-cached local executions )

Router planner follows a similar approach via `UpdateRelationToShardNames()` function, where table names are replaced with shard names. However, in that case all the deparsing is done on the original query and original shell table. We only use the `CITUS_RTE_SHARD` hack to generate the shard name via deparsing functions like `generate_rte_shard_name()/generate_fragment_name()`

When we don't use cached plan local executions, the query string is generated via `TaskQueryString()`. In that case, we use `deparse_shard_query()` which uses the shell table's attributes while generating the query.

### PR DESCRIPTION
**Pull request by onderkalaci**
With local query caching, we try to avoid deparse/parse stages as the
operation is too costly.

However, we can do deparse/parse operations once per cached queries, right
before we put the plan into the cache. With that, we avoid edge
cases like (#4239) or (#5038).

In a sense, we are making the local plan caching behave similar for non-cached
local/remote queries, by forcing to deparse the query once.

DESCRIPTION: Fixes a bug with local cached plans on tables with dropped columns

Fixes #5038

### CODE REVIEW

File: src/test/regress/sql/local_shard_execution_dropped_column.sql [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+execute p1(8);
+execute p1(8);
+execute p1(8);
+execute p1(8);
+execute p1(8);
+execute p1(8);
+execute p1(8);
+execute p1(8);
+
+prepare p2(int) as SELECT count(*) FROM t1 WHERE c = $1 GROUP BY c;
```
Comment (onderkalaci) [inline src/test/regress/sql/local_shard_execution_dropped_column.sql:43]: maybe add some more tests, updates/deletes/multi-shard queries etc for future changes

File: src/test/regress/sql/local_shard_execution_dropped_column.sql [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+SELECT stop_metadata_sync_to_node('localhost',:worker_1_port);
+SELECT stop_metadata_sync_to_node('localhost',:worker_2_port);
+
+-- create a distributed table, drop a column and sync the metadata
+SET citus.shard_replication_factor TO 1;
+CREATE TABLE t1 (a int, b int, c int UNIQUE);
+SELECT create_distributed_table('t1', 'c');
+ALTER TABLE t1 DROP COLUMN b;
+SELECT start_metadata_sync_to_node('localhost',:worker_1_port);
+SELECT start_metadata_sync_to_node('localhost',:worker_2_port);
```
Comment (JelteF) [inline src/test/regress/sql/local_shard_execution_dropped_column.sql:19]: Another case that I think would result in a similar bug is:
```
-- start metadata sync now
CREATE TABLE t2 (a int, b int, c int UNIQUE);
ALTER TABLE t2 DROP COLUMN b;
select citus_move_shard_placement(...); -- now the newly created shard has different attribute numbers
-- run multi shard query on node where the shard was moved to
```

As far as I understand the current fix only reparses the query once for a random shard, and uses those attribute numbers for each shard. If that's indeed the case, then I think this will still fail with the current fix, because the attribute numbers are not the same for all shards.

Comment (onderkalaci) [reply src/test/regress/sql/local_shard_execution_dropped_column.sql:19]: > -- run multi shard query on node where the shard was moved to

The bug is only relevant for single shard queries that can have deferredPruning (e.g., INSERTs and fast-path queries). Because we do caching only for these types of queries


> As far as I understand the current fix only reparses the query once for a random shard,

The caching mechanism in general does the caching per shard/per query, see `GetCachedLocalPlan()` for the details.

> select citus_move_shard_placement(...); -- now the newly created shard has different attribute numbers

In that case, the shell table would have the dropped column and not the shard -- as the shard is re-created. 

```SQL
select attrelid::regclass, attname, attnum, attisdropped from pg_attribute WHERE attrelid IN ('t2'::regclass, 't2_102106'::regclass) and attname NOT IN ('tableoid','cmax', 'xmax', 'cmin', 'xmin', 'ctid') ;
 attrelid  |           attname            | attnum | attisdropped 
-----------+------------------------------+--------+--------------
 t2        | ........pg.dropped.1........ |      1 | t
 t2        | c                            |      2 | f
 t2_102106 | c                            |      1 | f
(3 rows)
```

However, because the patch deparses the query, we actually do not care about the discrepancy between attribute numbers anymore. Because, now Postgres will give us the accurate attribute numbers anyway.

But, I think still this is a good test to have -- even both directions of moves--, thanks for pointing out.

Comment (onderkalaci) [reply src/test/regress/sql/local_shard_execution_dropped_column.sql:19]: > However, because the patch deparses the query, we actually do not care about the discrepancy between attribute numbers anymore. Because, now Postgres will give us the accurate attribute numbers anyway.

I'm actually not sure about this, will look more. There could be some issues, but somehow it works fine

Comment (onderkalaci) [reply src/test/regress/sql/local_shard_execution_dropped_column.sql:19]: Ok, I understand now why that is not becoming an issue.

To start with, the situation you described is applicable not only for local cached plans but also any remote query as well where the table attribute differs from the shard attribute.

The deparsing logic roughly works as follow:
- We get a query from the user, and put it as `jobQuery`
- For each task, we call `UpdateRelationToShardNames(jobquery, relationShardList)`, which does a trick where the relations are replaces with functions, see :

```C
/*
 * SetRangeTblExtraData adds additional data to a RTE, overwriting previous
 * values, if present.
 *
 * The data is stored as RTE_FUNCTION type RTE of a special
 * citus_extradata_container function, with the extra data serialized into the
 * function arguments. That works, because these RTEs aren't used by Postgres
 * to any significant degree, and Citus' variant of ruleutils.c knows how to
 * deal with these extended RTEs. Note that rte->eref needs to be set prior
 * to calling SetRangeTblExtraData to ensure the funccolcount can be set
 * correctly.
 *
 * NB: If used for postgres defined RTEKinds, fields specific to that RTEKind
 * will not be handled by out/readfuncs.c. For the current uses that's ok.
 */
```
- And the deparsing logic replaces the table names with shard names

The short of the story is that we do the deparsing based on the `jobQuery`, meaning that we don't care about the shard table's attributes. But when we parse back the queryString that is on `shard table`, Postgres would already give us the accurate attribute number for the shard.

Does that make sense to you @JelteF ?

File: src/backend/distributed/planner/local_plan_cache.c [hunk 3]
```diff
@@ -99,6 +96,66 @@ CacheLocalPlanForShardQuery(Task *task, DistributedPlan *originalDistributedPlan
...
+	{
+		/*
+		 * For INSERT queries we cannot use pg_get_query_def. Mainly because we
+		 * cannot run UpdateRelationToShardNames on an INSERT query. This is
+		 * because the PG deparsing logic fails when trying to insert into a
+		 * RTE_FUNCTION (which is what will happen if you call
+		 * UpdateRelationToShardNames).
+		 */
+		deparse_shard_query(jobQuery, task->anchorDistributedTableId, task->anchorShardId,
+							localShardSqlQuery);
```
Comment (marcocitus) [inline src/backend/distributed/planner/local_plan_cache.c:124]: It seems like this logic is not robust to INSERT..SELECT. Should we have some Assert? Alternatively, what if we call UpdateRelationToShardNames here as well? That seems to be how we handle INSERT..SELECT via PlanRouterQuery.

File: src/backend/distributed/planner/local_plan_cache.c [hunk 4]
```diff
@@ -99,6 +96,66 @@ CacheLocalPlanForShardQuery(Task *task, DistributedPlan *originalDistributedPlan
...
+	int numParams = 0;
+	if (orig_paramListInfo != NULL)
+	{
+		/* not used anywhere, so declare here */
+		const char **parameterValues = NULL;
+		ParamListInfo paramListInfo = copyParamList(orig_paramListInfo);
+		ExtractParametersForLocalExecution(paramListInfo, &parameterTypes,
+										   &parameterValues);
+		numParams = paramListInfo->numParams;
+	}
```
Comment (marcocitus) [inline src/backend/distributed/planner/local_plan_cache.c:146]: Maybe introduce a ParameterTypesForParamListInfo function

File: src/backend/distributed/planner/local_plan_cache.c [hunk 5]
```diff
@@ -99,6 +96,66 @@ CacheLocalPlanForShardQuery(Task *task, DistributedPlan *originalDistributedPlan
...
+
+	Query *localShardQuery =
+		ParseQueryString(localShardSqlQuery->data, parameterTypes, numParams);
+
+	/* we don't need the sql statements anymore */
+	pfree(localShardSqlQuery->data);
+	pfree(localShardSqlQuery);
+
+	return localShardQuery;
```
Comment (marcocitus) [inline src/backend/distributed/planner/local_plan_cache.c:155]: It took me a moment to realize this was not the same variable as localShardSqlQuery

File: src/backend/distributed/planner/local_plan_cache.c [hunk 6]
```diff
@@ -54,39 +60,30 @@ CacheLocalPlanForShardQuery(Task *task, DistributedPlan *originalDistributedPlan
 	 * We prefer to use jobQuery (over task->query) because we don't want any
 	 * functions/params to have been evaluated in the cached plan.
 	 */
-	Query *shardQuery = copyObject(originalDistributedPlan->workerJob->jobQuery);
+	Query *jobQuery = copyObject(originalDistributedPlan->workerJob->jobQuery);
```
Comment (marcocitus) [inline src/backend/distributed/planner/local_plan_cache.c:63]: We previously free-d this query, but now we don't.

File: src/backend/distributed/planner/local_plan_cache.c [hunk 7]
```diff
@@ -99,6 +96,66 @@ CacheLocalPlanForShardQuery(Task *task, DistributedPlan *originalDistributedPlan
...
+		 * UpdateRelationToShardNames).
+		 */
+		deparse_shard_query(jobQuery, task->anchorDistributedTableId, task->anchorShardId,
+							localShardSqlQuery);
+	}
+	else
+	{
+		UpdateRelationToShardNames((Node *) jobQuery, task->relationShardList);
+		pg_get_query_def(jobQuery, localShardSqlQuery);
+	}
```
Comment (marcocitus) [inline src/backend/distributed/planner/local_plan_cache.c:130]: Is there a reason why we cannot use TaskQueryString here?

**Review by marcocitus — COMMENTED** [review]
I like bug fixes that reduce code. 

It would be nice if we could also address doing the deparse+parse+plan twice (and use the cached plan for subsequent executions), but it seems better to not do that last minute.

File: src/test/regress/sql/local_shard_execution_dropped_column.sql (hunk 2 above)
Comment (marcocitus) [reply src/test/regress/sql/local_shard_execution_dropped_column.sql:19]: We cache a separate plan for every anchor shard (see GetCachedLocalPlan), and therefore would deparse+parse seperately for every shard. 

To do deparsing for a specific shard, we replace table RTEs with function calls that contain metadata about the shard in UpdateRelationToShardNames. We also modified the ruleutils logic to recognize those RTEs (CITUS_RTE_SHARD) and generate shard names. The reason we do this elaborate trick is that ruleutils normally only knows how to deparse table names that exist in pg_class.

The local Citus plans are cached within the cached prepared statement plan. Invasive maneuvers like pg_dist_placement updates (read: shard moves) invalidate the prepared statement cache by sending a invalidation for the relation (e.g. see citus_dist_placement_cache_invalidate, or InsertShardPlacementRow) when they commit, which implicitly invalidates the cached Citus plans as well.

Comment (JelteF) [reply src/test/regress/sql/local_shard_execution_dropped_column.sql:19]: Thanks for all the details both, makes sense that this fixes that too then. But like onder said, might still be nice to add it as a test though.

File: src/backend/distributed/planner/local_plan_cache.c (hunk 7 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/local_plan_cache.c]: One minor difference is that I used to free the generated SQL. But, when we use `TaskQueryString ` it sets the string to a pointer in the task, so we cannot free.

I think we should prefer having less code, so switched to that

File: src/backend/distributed/planner/local_plan_cache.c (hunk 3 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/local_plan_cache.c]: `UpdateRelationToShardNames((Node *) jobQuery, task->relationShardList);` followed by `TaskQueryString(task);` seems to be more generic, switching to that makes more sense

Comment (onderkalaci) [reply src/backend/distributed/planner/local_plan_cache.c]: Also, in `DeparseTaskQuery` there is a comment saying:
```		 * For INSERT queries we cannot use pg_get_query_def. Mainly because we
		 * cannot run UpdateRelationToShardNames on an INSERT query. This is
		 * because the PG deparsing logic fails when trying to insert into a
		 * RTE_FUNCTION (which is what will happen if you call
		 * UpdateRelationToShardNames).
		 */
```

However, pg deparsing logic doesn't seem to fail whenn we insert RTE_FUNCTION for INSERT. Is tthat something we improved in the past? Or the comment is not accurate?

File: src/test/regress/sql/local_shard_execution_dropped_column.sql (hunk 2 above)
Comment (onderkalaci) [reply src/test/regress/sql/local_shard_execution_dropped_column.sql:19]: > Thanks for all the details both, makes sense that this fixes that too then. But like onder said, might still be nice to add it as a test though.

Yes, makes sense added such an example

File: src/backend/distributed/planner/local_plan_cache.c (hunk 3 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/local_plan_cache.c]: well, it seems this is accurate, we cannot call `UpdateRelationToShardNames` for plain INSERTs. so, switched back to old implementation, and added an assert for now. I'll look more and update here

File: src/backend/distributed/planner/local_plan_cache.c (hunk 7 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/local_plan_cache.c:146]: It seems we cannot use `TaskQueryString()` because all the caching logic is based on the `jobQuery` where coordinator evaluation does not happen. 


When we use `TaskQueryString()` at the stage of caching, the parameters have already been resolved and that would be cached. Luckily we have the tests in `coordinator_evaluation_modify` which caught this subtle case.

I think this change still requires a little more attention from this perspective and memory context perspectives.

I added a comment on this

Comment (marcocitus) [reply src/backend/distributed/planner/local_plan_cache.c:146]: Makes sense, though I wish this was a little more obvious from the code.

Comment (marcocitus) [reply src/backend/distributed/planner/local_plan_cache.c:146]: I think an important thing to keep in mind is how this relates to function evaluation.

The reason it is ok to deparse a parameterized query for the local execution case, but not quite ok in the general case is that the insert may have fields like `stable_or_volatile_function($1)` which should in general be evaluated on the coordinator of the query. In the local execution case, we can allow those function calls to be evaluated when the query on the shard is execution, because that's still on the coordinator. That is what makes local execution special.

Comment (onderkalaci) [reply src/backend/distributed/planner/local_plan_cache.c:146]: I added a comment based on your comment. I think there is one more confusing thing, which is not related to this PR, but more generic confusion.

As you noted, we rely on Postgres to evaluate functions/params for cached local queries. However, we still do the function/param evaluation for those queries on the **Task** query. That's why, when we do `set citus.log_remote_commands TO ON`, even if the query has param/functions, we see the constant values:
```SQL
execute p2(2);
NOTICE:  executing the command locally: INSERT INTO public.users_table_102012 (user_id, value_1) VALUES (10, 2)
```

Where, the plan that is being executed has the params and functions:
```SQL
            {TARGETENTRY 
            :expr 
               {FUNCEXPR 
               :funcid 25339 
               :funcresulttype 23 
               :funcretset false 
               :funcvariadic false 
               :funcformat 0 
               :funccollid 0 
               :inputcollid 0 
               :args <> 
               :location 65
               }

...
           {TARGETENTRY 
            :expr 
               {PARAM 
               :paramkind 0 
               :paramid 1 
               :paramtype 23 
               :paramtypmod -1 
               :paramcollid 0 
               :location 100
               }
            :resno 3 
            :resname value_1 
            :ressortgroupref 0 
            :resorigtbl 0 
            :resorigcol 0 
            :resjunk false
            }
```


I think we can live with this for now, but would be good to improve separately for better debugging.

File: src/backend/distributed/planner/local_plan_cache.c [hunk 8]
```diff
@@ -54,39 +61,31 @@ CacheLocalPlanForShardQuery(Task *task, DistributedPlan *originalDistributedPlan
...
+	RangeTblEntry *rangeTableEntry = (RangeTblEntry *) linitial(localShardQuery->rtable);
 
 	/*
 	 * If the shard has been created in this transction, we wouldn't see the relationId
 	 * for it, so do not cache.
 	 */
 	if (rangeTableEntry->relid == InvalidOid)
 	{
-		pfree(shardQuery);
+		pfree(jobQuery);
```
[the remark this answers is not in the document]
Comment (onderkalaci) [reply src/backend/distributed/planner/local_plan_cache.c:79]: This is a special case where the plan and the distributed table is created in the same transaction. So, I think should be OK to leave as-is?

File: src/backend/distributed/planner/local_plan_cache.c (hunk 4 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/local_plan_cache.c:172]: Then we'd still need to convert the list to `Oid *`, so it looked like equally not-so-nice to me. If you prefer the other way around, I can push the commit.

Comment (marcocitus) [reply src/backend/distributed/planner/local_plan_cache.c:172]: I list more as a concept, so either adding `, Oid *parameterTypes, int numParams` or something like `numParams = ExtractParameterTypesForParamListInfo(orig_paramListInfo, &parameterTypes)`

File: src/backend/distributed/planner/local_plan_cache.c [hunk 9]
```diff
@@ -99,6 +98,86 @@ CacheLocalPlanForShardQuery(Task *task, DistributedPlan *originalDistributedPlan
...
+	 *
+	 * Additionally, we can allow them to be evaluated again because they are stable,
+	 * and we do not cache plans / use unevaluated query strings for queries containing
+	 * volatile functions.
+	 */
+	if (jobQuery->commandType == CMD_INSERT)
+	{
+		/*
+		 * We cannot use deparse_shard_query for INSERT .. SELECT, and we
+		 * currently do not support INSERT .. SELECT here.
```
Comment (marcocitus) [inline src/backend/distributed/planner/local_plan_cache.c:137]: I don't think this statement is correct. We use deparse_shard_query in RouterModifyTaskForShardInterval for INSERT..SELECT.

File: src/backend/distributed/planner/local_plan_cache.c (hunk 7 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/local_plan_cache.c:156]: Actually might be interesting to see the performance penalty of coordination evaluation for local cached plans. Could help to gain some cpu cycles.

File: src/backend/distributed/planner/local_plan_cache.c [hunk 10]
```diff
@@ -99,6 +98,86 @@ CacheLocalPlanForShardQuery(Task *task, DistributedPlan *originalDistributedPlan
...
+		 */
+		deparse_shard_query(jobQuery, task->anchorDistributedTableId, task->anchorShardId,
+							queryString);
+	}
+	else
+	{
+		UpdateRelationToShardNames((Node *) jobQuery, task->relationShardList);
+
+		pg_get_query_def(jobQuery, queryString);
+	}
```
Comment (marcocitus) [inline src/backend/distributed/planner/local_plan_cache.c:156]: I'm wondering whether we can capture this block in a function, something like `char *shardQueryString = DeparseShardQuery(jobQuery, task->relationShardList, task->anchorDistributedTableId, task->anchorShardId)`

File: src/backend/distributed/planner/local_plan_cache.c (hunk 7 above)
Comment (marcocitus) [reply src/backend/distributed/planner/local_plan_cache.c:156]: I think we need to do function/parameter evaluation to do the shard pruning, though we only really need to do it for the distribution column.

File: src/backend/distributed/planner/local_plan_cache.c [hunk 11]
```diff
@@ -99,6 +99,106 @@ CacheLocalPlanForShardQuery(Task *task, DistributedPlan *originalDistributedPlan
...
+ *
+ * It is not guaranteed to have consistent attribute numbers on the shards
+ * and on the shell (e.g., distributed/reference tables) due to DROP COLUMN
+ * commands. To avoid any edge cases due to such discrepancies, we first
+ * deparse the jobQuery with the tables replaced to shards, and parse the
+ * query string back. This is normally a very expensive operation, however
+ * we only do it once per cached local plan, which is acceptable.
+ */
+static Query *
+GetLocalShardQuery(Query *jobQuery, Task *task, ParamListInfo orig_paramListInfo)
```
Comment (marcocitus) [inline src/backend/distributed/planner/local_plan_cache.c:114]: We probably should emphasize in the name that this is specifically for local plan caching (at least, as long as we do not implement insert..select) and not a general function for getting a local shard query.

File: src/backend/distributed/planner/local_plan_cache.c (hunk 10 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/local_plan_cache.c:157]: yes, seems like the code becomes more readable. Though, I named it as `DeparseLocalShardQuery` as I wanted to explicitly warn future callers of this function,

File: src/test/regress/sql/local_shard_execution_dropped_column.sql (hunk 1 above)
Comment (onderkalaci) [reply src/test/regress/sql/local_shard_execution_dropped_column.sql:43]: added

File: src/backend/distributed/planner/local_plan_cache.c (hunk 11 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/local_plan_cache.c]: changed the name to `GetLocalShardQueryForCache`

**Comment by onderkalaci** [comment]
> Makes sense, though I wish this was a little more obvious from the code.

I think now `GetLocalShardQueryForCache` is easy to follow and have sufficient tests?

**Review by marcocitus — APPROVED** [review]

**Review by marcocitus — APPROVED** [review]
