### PR TITLE
Propagate DDL Commands with 2PC

### LINKED ISSUE #480: Improve error messages on failed unique indexes
Related to https://github.com/citusdata/citus/issues/221, when creating a unique index, if there is duplicate data in a shard, the only error reported back to the master is `PG::InternalError: ERROR:  could not execute DDL command on worker node shards`. This gives no indication to the root cause of `DETAIIL:  Key ... is duplicated.` which can only be found in the worker node's logs.

### LINKED ISSUE #513: Propagate DDL commands to workers through 2PC
(update to issue to track DDL propagation through 2PC here)

Citus 5.0 propagates Alter Table and Create Index commands to worker nodes. We implemented this feature using Citus' current replication model. We also decided to switch to using 2PC (or pg_paxos) once the metadata propagation changes were implemented.

One drawback to the current approach is when ALTER TABLE ... SET NOT NULL fails it marks shards inactive:

````
postgres=# ALTER TABLE ddl_testing ALTER COLUMN address SET NOT NULL;
WARNING:  could not receive query results from [snip]
DETAIL:  Client error: column "address" contains null values
WARNING:  could not apply command on shard 102025 on [snip]
DETAIL:  Shard placement will be marked as inactive.
ALTER TABLE
````

If the problem was caused by the user and not by a failed node we probably shouldn't mark the placements inactive. We should instead somehow error out like we do when you try to create a duplicate index.

### PR DESCRIPTION
**Pull request by aamederen**
Fixes #513

This change modifies the DDL Propagation logic so that DDL queries
are propagated via 2-Phase Commit protocol. This way, failures during
the execution of distributed DDL commands will not leave the table in
an intermediate state.

The workflow of the successful case is this:
1. Open individual connections to all shard placements and send `BEGIN`
2. Send `SELECT worker_apply_shard_ddl_command(<shardId>, <DDL Command>)`
to all connections, one by one, in a serial manner.
3. Send `PREPARE TRANSCATION <transaction_id>` to all connections.
4. Sedn `COMMIT` to all connections.

Failure cases:
- If a worker problem occurs before sending of all DDL commands is finished, then
all changes are rolled back.
- If a worker problem occurs after all DDL commands are sent but not after
`PREPARE TRANSACTION` commands are finished, then all changes are rolled back.
However, if a worker node is failed, then the prepared transactions in that worker
should be rolled back manually.
- If a worker problem occurs during `COMMIT PREPARED` statements are being sent,
then the prepared transactions on the failed workers should be commited manually.
- If master fails before the first 'PREPARE TRANSACTION' is sent, then nothing is
changed on workers.
- If master fails during `PREPARE TRANSACTION` commands are being sent, then the
prepared transactions on workers should be rolled back manually.
- If master fails during `COMMIT PREPARED` or `ROLLBACK PREPARED` commands are being
sent, then the remaining prepared transactions on the workers should be handled manually.

### CODE REVIEW

File: src/backend/distributed/utils/multi_transaction.c [hunk 1]
```diff
@@ -347,3 +348,62 @@ ConnectionList(HTAB *connectionHash)
...
 }
+
+
+/*
+ * OpenConnectionsToShardPlacements opens connections to all placements of the
+ * shard with the given shardId and populates the shardConnectionHash table
+ * accordingly.
+ */
+void
+OpenConnectionsToShardPlacements(uint64 shardId, HTAB *shardConnectionHash,
```
Comment (marcocitus) [inline src/backend/distributed/utils/multi_transaction.c]: What do you think of moving this into a transaction/shard_transaction.c file?

In the future, we'll have a worker_transaction.c related to doing transactions across all workers (e.g. syncing metadata), which uses the 2PC functions from multi_transaction.c. It would be nice if we separated logic for doing transactions across shard placements into a separate file.

File: src/backend/distributed/executor/multi_utility.c [hunk 2]
```diff
@@ -1045,88 +1056,203 @@ ExecuteDistributedDDLCommand(Oid relationId, const char *ddlCommandString)
...
+	else if (event == XACT_EVENT_PRE_COMMIT)
+	{
+		/*
+		 * Any failure here will cause local changes to be rolled back,
+		 * and remote changes to either roll back (1PC) or, in case of
+		 * connection or node failure, leave a prepared transaction
+		 * (2PC).
+		 */
+
+		PrepareRemoteTransactions(shardPlacementConnectionList);
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_utility.c]: Should we honour multi_shard_commit_protocol here?

File: src/backend/distributed/executor/multi_utility.c [hunk 3]
```diff
@@ -1045,88 +1056,203 @@ ExecuteDistributedDDLCommand(Oid relationId, const char *ddlCommandString)
...
 
-		FreeStringInfo(applyCommand);
+
+/*
+ * OpenConnectionsToAllShardPlacement opens connections to all placements of
+ * the given shard Id Pointer List and returns the hash table containing the connections.
+ * The resulting hash table maps shardIds to ShardConnection structs.
+ */
+static HTAB *
+OpenConnectionsToAllShardPlacements(List *shardIdList, char *relationOwner)
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_utility.c]: This logic seems fairly generic and could be added to shard_transaction.c.

File: src/backend/distributed/executor/multi_utility.c [hunk 4]
```diff
@@ -1045,88 +1056,203 @@ ExecuteDistributedDDLCommand(Oid relationId, const char *ddlCommandString)
...
 static bool
 ExecuteCommandOnWorkerShards(Oid relationId, const char *commandString,
 							 List **failedPlacementList)
 {
-	bool isFirstPlacement = true;
-	ListCell *shardCell = NULL;
-	List *shardList = NIL;
+	List *shardIdList = LoadShardList(relationId);
 	char *relationOwner = TableOwner(relationId);
+	HTAB *shardConnectionHash = OpenConnectionsToAllShardPlacements(shardIdList,
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_utility.c]: If we were to implement multi-statement DDL changes. Would we want to store this hash in a static variable, or rebuild the hash from shardPlacementConnectionList?

File: src/backend/distributed/executor/multi_utility.c [hunk 5]
```diff
@@ -1045,88 +1056,203 @@ ExecuteDistributedDDLCommand(Oid relationId, const char *ddlCommandString)
...
+
+	foreach(connectionCell, connectionList)
+	{
+		TransactionConnection *transactionConnection =
+			(TransactionConnection *) lfirst(connectionCell);
+		PGconn *connection = transactionConnection->connection;
+		PGresult *result = NULL;
+
+		/* send the query */
+		result = PQexec(connection, "BEGIN");
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_utility.c]: I think it might make more sense to send the BEGIN after opening the connection. It creates a bit more symmetry between open+begin and commit+close which will help when we add support for multi-statement transactions.

File: src/backend/distributed/master/master_modify_multiple_shards.c [hunk 6]
```diff
@@ -266,81 +265,22 @@ static HTAB *
 OpenConnectionsToAllShardPlacements(List *shardIntervalList)
```
Comment (marcocitus) [inline src/backend/distributed/master/master_modify_multiple_shards.c]: How similar is this function to the one in multi_utility.c? Would it be possible to unify them?

File: src/backend/distributed/utils/multi_transaction.c (hunk 1 above)
Comment (marcocitus) [inline src/backend/distributed/utils/multi_transaction.c]: The other functions like GetShardConnections are also candidates to go into that file.

File: src/backend/distributed/executor/multi_utility.c [hunk 7]
```diff
@@ -1045,88 +1056,203 @@ ExecuteDistributedDDLCommand(Oid relationId, const char *ddlCommandString)
...
+
+		OpenConnectionsToShardPlacements(shardId, shardConnectionHash, relationOwner);
 	}
 
-	return true;
+	shardPlacementConnectionList = ConnectionList(shardConnectionHash);
+
+	MemoryContextSwitchTo(oldContext);
+
+	if (!isXactCallbackRegistered)
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_utility.c]: For integration purposes, maybe move this if-block into an EnableXactCallback function (or better name).

e.g.
https://github.com/citusdata/citus-mx/blob/4c70aba5b300be28bb3a81187591246ef16b390f/src/backend/distributed/transaction/worker_transaction.c#L200

File: src/backend/distributed/utils/multi_transaction.c [hunk 8]
```diff
@@ -347,3 +348,62 @@ ConnectionList(HTAB *connectionHash)
...
+								 char *nodeUser)
+{
+	bool shardConnectionsFound = false;
+
+	/* get existing connections to the shard placements, if any */
+	ShardConnections *shardConnections = GetShardConnections(shardConnectionHash,
+															 shardId,
+															 &shardConnectionsFound);
+
+	List *shardPlacementList = FinalizedShardPlacementList(shardId);
```
Comment (marcocitus) [inline src/backend/distributed/utils/multi_transaction.c]: It seems like we never lock the metadata for the shards. Not this PR's fault, but this could cause things to break in the event that shard rebalancer runs during a DDL command.

**Comment by marcocitus** [comment]
I think it's worth adding regression tests for #480 at least.

File: src/include/distributed/shard_transaction.h [hunk 9]
```diff
@@ -0,0 +1,20 @@
...
+ *
+ * shard_transaction.h
+ *	  Type and function declarations used in performing transactions across
+ *	  shard placements.
+ *
+ * Copyright (c) 2016, Citus Data, Inc.
+ *
+ *-------------------------------------------------------------------------
+ */
+
```
Comment (marcocitus) [inline src/include/distributed/shard_transaction.h]: #ifndef is missing

File: src/backend/distributed/transaction/shard_transaction.c [hunk 10]
```diff
@@ -0,0 +1,212 @@
...
+		TransactionConnection *transactionConnection =
+			(TransactionConnection *) lfirst(connectionCell);
+		PGconn *connection = transactionConnection->connection;
+		PGresult *result = NULL;
+		
+		result = PQexec(connection, "BEGIN");
+		if (PQresultStatus(result) != PGRES_COMMAND_OK)
+		{
+			WarnRemoteError(connection, result);
+			ereport(ERROR, (errmsg("could not send ddl command to shard placement")));
```
Comment (marcocitus) [inline src/backend/distributed/transaction/shard_transaction.c]: Maybe just ReraiseRemoteError. If this function has another caller, the error message doesn't make much sense.

File: src/backend/distributed/transaction/shard_transaction.c [hunk 11]
```diff
@@ -0,0 +1,212 @@
...
+}
+
+
+/*
+ * OpenTransactionsToAllShardPlacements opens connections to all placements of
+ * the given shard Id Pointer List and returns the hash table containing the connections.
+ * The resulting hash table maps shardIds to ShardConnection structs.
+ */
+HTAB *
+OpenTransactionsToAllShardPlacements(List *shardIdList, char *relationOwner)
```
Comment (marcocitus) [inline src/backend/distributed/transaction/shard_transaction.c]: relationOwner seems very specific to DDL, maybe just something like userName or nodeUser.

File: src/backend/distributed/executor/multi_utility.c [hunk 12]
```diff
@@ -1045,88 +1055,175 @@ ExecuteDistributedDDLCommand(Oid relationId, const char *ddlCommandString)
...
+	return true;
+}
+
+
+/*
+ * CompleteShardPlacementTransactions commits or aborts pending shard placement
+ * transactions when the local transaction commits or aborts.
+ */
+static void
+CompleteShardPlacementTransactions(XactEvent event, void *arg)
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_utility.c]: I wonder whether it makes sense to move this logic into shard_transaction.c as well, since other callers might want to use it.

File: src/backend/distributed/executor/multi_utility.c [hunk 13]
```diff
@@ -1045,88 +1055,175 @@ ExecuteDistributedDDLCommand(Oid relationId, const char *ddlCommandString)
...
- * and not on the others. In that case, this function might still end up returning
- * a large number of placements as failed.
+ * and not on the others. 
+ * 
+ * Note: The execution will be blocked if a prepared transaction from previous
+ * executions exist on the workers. In this case, those prepared transactions should
+ * be removed by either COMMIT PREPARED or ROLLBACK PREPARED.
  */
 static bool
 ExecuteCommandOnWorkerShards(Oid relationId, const char *commandString,
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_utility.c]: failedPlacementList seems no longer used.

File: src/backend/distributed/executor/multi_utility.c [hunk 14]
```diff
@@ -1045,88 +1055,175 @@ ExecuteDistributedDDLCommand(Oid relationId, const char *ddlCommandString)
...
 		appendStringInfo(applyCommand, WORKER_APPLY_SHARD_DDL_COMMAND, shardId,
 						 escapedCommandString);
 
-		shardPlacementList = FinalizedShardPlacementList(shardId);
-		foreach(shardPlacementCell, shardPlacementList)
-		{
-			ShardPlacement *placement = (ShardPlacement *) lfirst(shardPlacementCell);
-			char *workerName = placement->nodeName;
-			uint32 workerPort = placement->nodePort;
+		ExecuteCommandOnShardReplicas(applyCommand, shardId, shardConnections);
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_utility.c]: I guess we usually say Placements instead of Replicas in code.

File: src/backend/distributed/executor/multi_utility.c [hunk 15]
```diff
@@ -1045,88 +1055,175 @@ ExecuteDistributedDDLCommand(Oid relationId, const char *ddlCommandString)
...
+	shardPlacementConnectionList = ConnectionList(shardConnectionHash);
+	MemoryContextSwitchTo(oldContext);
+	
+	if (!isXactCallbackRegistered)
+	{
+		RegisterXactCallback(CompleteShardPlacementTransactions, NULL);
+		isXactCallbackRegistered = true;
+	}
+	
+	foreach(shardCell, shardIdList)
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_utility.c]: If we wanted to parallelise this block, how would it change?

**Comment by aamederen** [comment]
> * What do you think of moving this into a transaction/shard_transaction.c file?
 In the future, we'll have a worker_transaction.c related to doing transactions across all workers (e.g. syncing metadata), which uses the 2PC functions from multi_transaction.c. It would be nice if we separated logic for doing transactions across shard placements into a separate file.

> * The other functions like GetShardConnections are also candidates to go into that file.

> * This logic seems fairly generic and could be added to shard_transaction.c.

> * I wonder whether it makes sense to move this logic into shard_transaction.c as well, since other callers might want to use it.

I have created `src/backend/distributed/transaction` directory, created `shard_transaction.c` file and also moved `multi_transaction.c` there. I have moved these functions to the `shard_transaction.c` file. 

However, I am not sure about what should be the distinction between shard_transaction.c and multi_transaction.c. 

Currently, they are separated so that `multi_transaction.c` has prepare/commit/abort related functions and `shard_transaction.c` has shard/placement connection-related functions. 

1. Do you think is this a good separation?
2. To me, the names of `shard_transaction.c` and `multi_transaction.c` do not tell any difference between them.
3. I think `CompleteShardPlacementTransactions` function may go to multi_transaction instead of shard_transaction, since it couples with the functions in multi_transaction.

File: src/backend/distributed/executor/multi_utility.c (hunk 2 above)
Comment (aamederen) [inline src/backend/distributed/executor/multi_utility.c]: I had removed the multi_shard_commit_protocol reference because it seemed to me that all DDL propagations should have been done via 2PC. I put it back now.

File: src/backend/distributed/executor/multi_utility.c (hunk 5 above)
Comment (aamederen) [inline src/backend/distributed/executor/multi_utility.c]: Right, it now sends the BEGIN after openin the connections in shard_transaction.c::OpenTransactionsToAllShardPlacements function.

After this change, BEGIN commands are now sent before PG_TRY in master_modify_multiple_shards.c::SendQueryToShards(), would it bring any problems?

File: src/backend/distributed/master/master_modify_multiple_shards.c (hunk 6 above)
Comment (aamederen) [inline src/backend/distributed/master/master_modify_multiple_shards.c]: You are right, they were almost identical. After the change of sending BEGIN after opening the connections, it is also renamed to `OpenTransactionsToAllShardPlacements`

File: src/backend/distributed/executor/multi_utility.c (hunk 7 above)
Comment (aamederen) [inline src/backend/distributed/executor/multi_utility.c]: Moved the logic to a RegisterShardPlacementXactCallback function.

File: src/include/distributed/shard_transaction.h (hunk 9 above)
Comment (aamederen) [inline src/include/distributed/shard_transaction.h]: Added.

File: src/backend/distributed/transaction/shard_transaction.c (hunk 10 above)
Comment (aamederen) [inline src/backend/distributed/transaction/shard_transaction.c]: Makes sense

File: src/backend/distributed/transaction/shard_transaction.c (hunk 11 above)
Comment (aamederen) [inline src/backend/distributed/transaction/shard_transaction.c]: Changed nodeUser and relationOwner to userName.

File: src/backend/distributed/executor/multi_utility.c (hunk 13 above)
Comment (aamederen) [inline src/backend/distributed/executor/multi_utility.c]: Correct, removed the failedPlacementList related logic as well.

File: src/backend/distributed/executor/multi_utility.c (hunk 14 above)
Comment (aamederen) [inline src/backend/distributed/executor/multi_utility.c]: You are right, changed its name.

File: src/backend/distributed/utils/multi_transaction.c (hunk 8 above)
Comment (aamederen) [inline src/backend/distributed/utils/multi_transaction.c]: Added `lockShards` to `ExecuteCommandOnWorkerShards`, before opening the connections and used ShareLock. Is it sufficient?

File: src/backend/distributed/executor/multi_utility.c (hunk 15 above)
Comment (aamederen) [inline src/backend/distributed/executor/multi_utility.c]: I am not sure but, I think using PQsendQuery instead of PQexec in ExecuteCommandOnShardPlacements function,  and checking the results after the foreach with `PQgetResult` would be needed.

File: src/backend/distributed/executor/multi_utility.c (hunk 4 above)
Comment (aamederen) [inline src/backend/distributed/executor/multi_utility.c]: One of doing that came to my mind is the following: We can make `shardConnectionsHash` an extern variable and make `OpenTransactionsToAllShardPlacements` aware of the current state of `shardConnectionsHash`. This way, we can have multiple calls to `ExecuteCommandOnWorkerShards`. What do you think?

File: src/backend/distributed/executor/multi_utility.c (hunk 15 above)
Comment (aamederen) [inline src/backend/distributed/executor/multi_utility.c]: Would you like me to try it in this PR?

**Comment by marcocitus** [comment]
> To me, the names of shard_transaction.c and multi_transaction.c do not tell any difference between them.

Given that multi_transaction.c deals with generic 1PC/2PC operations. An alternative name could be commit_protocol.c

File: src/backend/distributed/executor/multi_utility.c [hunk 16]
```diff
@@ -1045,88 +1036,136 @@ ExecuteDistributedDDLCommand(Oid relationId, const char *ddlCommandString)
...
+
+	LockShards(shardIntervalList, ShareLock);
+
+	shardConnectionHash = OpenTransactionsToAllShardPlacements(shardIntervalList,
+															   tableOwner);
+
+	shardPlacementConnectionList = ConnectionList(shardConnectionHash);
+	MemoryContextSwitchTo(oldContext);
+
+	RegisterShardPlacementXactCallback();
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_utility.c]: Maybe move this into OpenTransactionsToAllShardPlacements.

File: src/backend/distributed/executor/multi_utility.c [hunk 17]
```diff
@@ -1045,88 +1036,136 @@ ExecuteDistributedDDLCommand(Oid relationId, const char *ddlCommandString)
...
-	shardList = LoadShardList(relationId);
-	foreach(shardCell, shardList)
+	MemoryContext oldContext = MemoryContextSwitchTo(TopTransactionContext);
+
+	LockShards(shardIntervalList, ShareLock);
+
+	shardConnectionHash = OpenTransactionsToAllShardPlacements(shardIntervalList,
+															   tableOwner);
+
+	shardPlacementConnectionList = ConnectionList(shardConnectionHash);
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_utility.c]: Maybe move this into OpenTransactionsToAllShardPlacements

File: src/backend/distributed/executor/multi_utility.c [hunk 18]
```diff
@@ -1045,88 +1036,136 @@ ExecuteDistributedDDLCommand(Oid relationId, const char *ddlCommandString)
...
 
-				*failedPlacementList = lappend(*failedPlacementList, placement);
-			}
-			else
-			{
-				ereport(DEBUG2, (errmsg("applied command on shard " UINT64_FORMAT
-										" on node %s:%d", shardId, workerName,
-										workerPort)));
-			}
+	/* CloseConnections(allShardsConnectionList); */
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_utility.c]: Should this be removed?

File: src/backend/distributed/transaction/shard_transaction.c [hunk 19]
```diff
@@ -0,0 +1,279 @@
...
+}
+
+
+/*
+ * OpenTransactionsToAllShardPlacements opens connections to all placements of
+ * the given shard Id Pointer List and returns the hash table containing the connections.
+ * The resulting hash table maps shardIds to ShardConnection structs.
+ */
+HTAB *
+OpenTransactionsToAllShardPlacements(List *shardIntervalList, char *userName)
```
Comment (marcocitus) [inline src/backend/distributed/transaction/shard_transaction.c]: We usually try to follow calling order in our files, so this function should be above CreateShardConnectionHash.

File: src/backend/distributed/transaction/shard_transaction.c [hunk 20]
```diff
@@ -0,0 +1,279 @@
...
+{
+	HTAB *shardConnectionHash = CreateShardConnectionHash();
```
Comment (marcocitus) [inline src/backend/distributed/transaction/shard_transaction.c]: The current code allows transaction blocks and gets into a deadlock because it opens new connections for every statement.

    postgres=# BEGIN;
    BEGIN
    postgres=# ALTER TABLE test ADD COLUMN z int;
    ALTER TABLE
    postgres=# ALTER TABLE test ADD COLUMN q int;
    ...

What if we just go all the way by caching the shardConnectionHash instead of shardPlacementConnectionList and returning it here if it is not null? That would allow multi-statement DDL transactions.

**Comment by marcocitus** [comment]
You might want to check if there's any relevant overlap with #627, e.g. in the Xact handler.

File: src/backend/distributed/master/master_modify_multiple_shards.c [hunk 21]
```diff
@@ -198,10 +198,12 @@ HasReplication(List *shardIntervalList)
  * the shards when necessary before calling SendQueryToShards.
  */
 static int
-SendQueryToShards(Query *query, List *shardIntervalList)
+SendQueryToShards(Query *query, List *shardIntervalList, Oid relationId)
 {
 	int affectedTupleCount = 0;
-	HTAB *shardConnectionHash = OpenConnectionsToAllShardPlacements(shardIntervalList);
+	char *relationOwner = TableOwner(relationId);
+	HTAB *shardConnectionHash = OpenTransactionsToAllShardPlacements(shardIntervalList,
```
Comment (marcocitus) [inline src/backend/distributed/master/master_modify_multiple_shards.c]: I just realised that if you move RegisterShardPlacementXactCallback() into OpenTransactionsToAllShardPlacements, the behaviour would change here, but what if we remove the PG_TRY/PG_CATCH block now?

**Comment by aamederen** [comment]
> Given that multi_transaction.c deals with generic 1PC/2PC operations, which could be across all shards or across all workers, an alternative name could be commit_protocol.c
> 
> Perhaps shard_transaction.c should be multi_shard_transaction.c for clarity.

Makes sense, changed accordingly and pushed a commit.

File: src/backend/distributed/executor/multi_utility.c (hunk 16 above)
Comment (aamederen) [inline src/backend/distributed/executor/multi_utility.c]: Doing so will also change the master_modify_multiple_shards, since it uses PG_TRY after OpenTransactionsToAllPlacements. 

Would you prefer changing master_modify_multiple_shards error handling logic in this PR anyways or leave it to a separate technical dept issue.

File: src/backend/distributed/executor/multi_utility.c (hunk 17 above)
Comment (aamederen) [inline src/backend/distributed/executor/multi_utility.c]: Moved

File: src/backend/distributed/executor/multi_utility.c (hunk 18 above)
Comment (aamederen) [inline src/backend/distributed/executor/multi_utility.c]: Yeah, sorry for my overlook, removed now.

File: src/backend/distributed/executor/multi_utility.c (hunk 16 above)
Comment (aamederen) [inline src/backend/distributed/executor/multi_utility.c]: Moved it inside the OpenTransactionsToAllShardPlacements and modified master_modify_multiple_shards accordingly.

File: src/backend/distributed/transaction/shard_transaction.c (hunk 19 above)
Comment (aamederen) [inline src/backend/distributed/transaction/shard_transaction.c]: You are right, fixed the file.

File: src/backend/distributed/transaction/multi_shard_transaction.c [hunk 22]
```diff
@@ -0,0 +1,303 @@
+/*-------------------------------------------------------------------------
+ *
+ * shard_transaction.c
```
Comment (marcocitus) [inline src/backend/distributed/transaction/multi_shard_transaction.c]: should be multi_shard_transaction.c

File: src/include/distributed/multi_shard_transaction.h [hunk 23]
```diff
@@ -0,0 +1,44 @@
+/*-------------------------------------------------------------------------
+ *
+ * shard_transaction.h
```
Comment (marcocitus) [inline src/include/distributed/multi_shard_transaction.h]: should be multi_shard_transaction

Comment (aamederen) [inline src/include/distributed/multi_shard_transaction.h]: Fixed

File: src/backend/distributed/transaction/multi_shard_transaction.c (hunk 22 above)
Comment (aamederen) [inline src/backend/distributed/transaction/multi_shard_transaction.c]: fixed

File: src/backend/distributed/transaction/shard_transaction.c (hunk 20 above)
Comment (aamederen) [inline src/backend/distributed/transaction/shard_transaction.c]: Put a `PreventTransactionChain` call in `ExecuteDistributedDDLCommand` function to error out in this case.

**Comment by marcocitus** [comment]
Just ran some tests. Looks good overall apart from the multi-statement issue.

The 1PC failure scenario is not so nice right now:

    postgres=# ALTER TABLE test ADD COLUMN foo int;
    WARNING:  failed to commit transaction on localhost:9700
    WARNING:  failed to commit transaction on localhost:9700
    ALTER TABLE
    postgres=# SELECT * FROM test;
    WARNING:  column "foo" does not exist
    CONTEXT:  while executing command on localhost:9700
    WARNING:  column "foo" does not exist
    CONTEXT:  while executing command on localhost:9700
    WARNING:  column "foo" does not exist
    CONTEXT:  while executing command on localhost:9700
    WARNING:  column "foo" does not exist
    CONTEXT:  while executing command on localhost:9700
    WARNING:  column "foo" does not exist
    CONTEXT:  while executing command on localhost:9700
    ERROR:  failed to execute job 8
    DETAIL:  Failure due to failed task 6

We could provide better instructions on what to do after a failure, though maybe it's better if we enforce 2PC for DDL changes (e.g. error out if commit_protocol is not 2pc).

**Comment by aamederen** [comment]
> We could provide better instructions on what to do after a failure, though maybe it's better if we enforce 2PC for DDL changes (e.g. error out if commit_protocol is not 2pc).

At the beginning, I though about, regardless of multi_shard_commit_protocol, we should do it in 2PC. 

I think now that instead of doing 2PC silently, forcing user to `SET citus.multi_shard_commit_protocol TO '2pc'` makes more sense. However, this would require changes in more than 10 regression tests.

**Comment by aamederen** [comment]
Went back to using 2PC silently, even the `citus.multi_shard_commit_protocol` is set to 1pc.

File: src/backend/distributed/executor/multi_utility.c [hunk 24]
```diff
@@ -1044,89 +1039,148 @@ ExecuteDistributedDDLCommand(Oid relationId, const char *ddlCommandString)
 
 
 /*
+ * SwitchTo2PCForSession sets the citus.multi_shard_commit_protocol value
+ * to '2pc', in order to force 2PC even the value of citus.multi_shard_commit_protocol
+ * is '1pc';
+ */
+static void
+SwitchTo2PCForSession()
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_utility.c]: It's only the transaction because of GUC_ACTION_LOCAL.

File: src/backend/distributed/master/master_modify_multiple_shards.c [hunk 25]
```diff
@@ -162,7 +163,7 @@ LockShardsForModify(List *shardIntervalList)
 	{
 		lockMode = ShareLock;
 	}
-	else if (!HasReplication(shardIntervalList)) /* check if any shards have >1 replica */
+	else if (!HasReplication(shardIntervalList)) /* check if any shard has >1 replicas */
```
Comment (marcocitus) [inline src/backend/distributed/master/master_modify_multiple_shards.c]: We don't usually put code comments at the end of the line, should be on the line above.

Comment (aamederen) [inline src/backend/distributed/master/master_modify_multiple_shards.c]: Removed the comment, since the line is self-explanatory

File: src/backend/distributed/executor/multi_utility.c (hunk 24 above)
Comment (aamederen) [inline src/backend/distributed/executor/multi_utility.c]: Yeah, changed accordingly.

File: src/backend/distributed/transaction/commit_protocol.c [hunk 26]
```diff
@@ -197,6 +260,8 @@ CommitRemoteTransactions(List *connectionList, bool stopOnFailure)
 											  command->data, nodeName, nodePort)));
 				}
 			}
+
+			ereport(DEBUG2, (errmsg("sent COMMIT PREPARED over connection %ld", connectionId)));
```
Comment (marcocitus) [inline src/backend/distributed/transaction/commit_protocol.c]: are the connection ids meaningful to a user / other developer?

File: src/test/regress/output/multi_alter_table_statements.source [hunk 27]
```diff
@@ -412,6 +412,126 @@ ERROR:  renaming distributed tables or their objects is currently unsupported
...
+(1 row)
+
+INSERT INTO test_ab VALUES (2, 10);
+INSERT INTO test_ab VALUES (2, 11);
+CREATE UNIQUE INDEX temp_unique_index_1 ON test_ab(a);
+WARNING:  could not create unique index "temp_unique_index_1_220016"
+DETAIL:  Key (a)=(2) is duplicated.
+CONTEXT:  while executing command on localhost:57638
+ERROR:  could not execute DDL command on worker node shards
+SELECT * FROM pg_dist_shard_placement WHERE shardstate=3;
```
Comment (marcocitus) [inline src/test/regress/output/multi_alter_table_statements.source]: This query seems like it would break if any other tests produce shardstate 3 in the future.

File: src/test/regress/output/multi_alter_table_statements.source [hunk 28]
```diff
@@ -412,6 +412,126 @@ ERROR:  renaming distributed tables or their objects is currently unsupported
...
+CREATE INDEX temp_index_1 ON lineitem_alter(l_linenumber);
+COMMIT;
+SELECT indexname, tablename FROM pg_indexes WHERE tablename = 'lineitem_alter';
+  indexname   |   tablename    
+--------------+----------------
+ temp_index_1 | lineitem_alter
+(1 row)
+
+DROP INDEX temp_index_1;
+-- verify that distributed ddl commands are not allowd inside a transaction block
```
Comment (marcocitus) [inline src/test/regress/output/multi_alter_table_statements.source]: s/allowd/allowed/

File: src/backend/distributed/transaction/commit_protocol.c (hunk 26 above)
Comment (marcocitus) [inline src/backend/distributed/transaction/commit_protocol.c]: If we want to show something here, it might be nice to just show the command that was sent, such that the user can see the transactions that were prepared/committed.

Comment (aamederen) [inline src/backend/distributed/transaction/commit_protocol.c]: no, but I though that distinguishing between matching commits/rollbacks wouldn't hurt anyone.

File: src/backend/distributed/executor/multi_utility.c [hunk 29]
```diff
@@ -77,9 +83,12 @@ static void ErrorIfDistributedRenameStmt(RenameStmt *renameStatement);
 /* Local functions forward declarations for helper functions */
 static void CreateLocalTable(RangeVar *relation, char *nodeName, int32 nodePort);
 static bool IsAlterTableRenameStmt(RenameStmt *renameStatement);
-static void ExecuteDistributedDDLCommand(Oid relationId, const char *ddlCommandString);
-static bool ExecuteCommandOnWorkerShards(Oid relationId, const char *commandString,
-										 List **failedPlacementList);
+static void ExecuteDistributedDDLCommand(Oid relationId, const char *ddlCommandString,
+										 bool isTopLevel);
+static void SwitchTo2PCForTransaction();
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_utility.c]: Should have void between the brackets.

This function is the equivalent of SET LOCAL citus.multi_shard_commit_protocol TO '2pc'. I think it might make sense to make that more explicit in the name, e.g. SetLocalCommitProtocolTo2PC.

**Comment by marcocitus** [comment]
Apart from naming issue and re-running make reindent, this seems ready to 🚢 .

File: src/backend/distributed/transaction/commit_protocol.c [hunk 30]
```diff
@@ -47,6 +46,66 @@ InitializeDistributedTransaction(void)
...
+			PrepareRemoteTransactions(shardPlacementConnectionList);
+		}
+
+		return;
+	}
+	else if (event == XACT_EVENT_COMMIT)
+	{
+		/*
+		 * A failure here will cause some remote changes to either
+		 * roll back (1PC) or, in case of connection or node failure,
```
Comment (lithp) [inline src/backend/distributed/transaction/commit_protocol.c]: Is this comment wrong? Since you're giving `CommitRemoteTransactions` the false flag nothing will be rolled back upon error?
