### PR TITLE
Not drop GENERATED AS ALWAYS STORED cols from shard when adding local table to metadata

### LINKED ISSUE #4609: Confusing error when creating a foreign key from local table with generated column to reference table
Not quite sure what is meant:

```sql
create table test (x int, y int generated always as (x+1) stored) ;
alter table test add constraint fk foreign key (x) references ref (a);
ERROR:  column "y" of relation "test_102093" is a generated column
DETAIL:  When adding a foreign key from a local table to a reference table, Citus applies a conversion to all the local tables in the foreign key graph
HINT:  Use ALTER TABLE ... ALTER COLUMN ... DROP EXPRESSION instead.

select citus_add_local_table_to_metadata('test');
ERROR:  column "y" of relation "test_102049" is a generated column
HINT:  Use ALTER TABLE ... ALTER COLUMN ... DROP EXPRESSION instead.
```

### PR DESCRIPTION
**Pull request by onurctirtir**
Fixes #4609.

When adding local table to metadata, we are dropping `DEFAULT` expressions
from shard relation. When finding columns having `DEFAULT` expressions,
we shouldn't rely on `atthasdef` since it might be true if column has
`GENERATED ALWAYS AS (...) STORED` expression.

On the other hand, we should not actually drop such `GENERATED` expressions from
shard relation since we don't evaluate such columns in coordinator and this would
result in inserting `NULL` values to such columns.
(I believe that's why we keep such expressions on shell relation & shard relation
when creating reference tables and distributed tables)

The function that we fix with this commit is not only used when adding local
table to metadata but also used when defining dependencies to sequences
in metadata nodes, but I think that logic was already fine before this commit
since we already had a [guard](https://github.com/citusdata/citus/blob/131c98150269984c7bd461d74e9c92a78ef1ed77/src/backend/distributed/metadata/metadata_sync.c#L1139..L1146) against that case.

----------

\+
But now when undistributing such citus local tables, we would hit to this behavior: #4614
Opened seperate pr for that #4616

### CODE REVIEW

File: src/backend/distributed/commands/citus_add_local_table_to_metadata.c [hunk 1]
```diff
@@ -900,12 +901,47 @@ DropDefaultColumnDefinition(Oid relationId, char *columnName)
...
 					 "ALTER TABLE %s ALTER COLUMN %s DROP DEFAULT",
 					 qualifiedRelationName, quotedColumnName);
 
-	ExecuteAndLogUtilityCommand(sequenceDropCommand->data);
+	ExecuteAndLogUtilityCommand(dropDefaultColumnDefCommand->data);
+}
+
+
+static bool
+ColumnIsGeneratedStored(Oid relationId, char *targetColumnName)
```
Comment (onurctirtir) [inline src/backend/distributed/commands/citus_add_local_table_to_metadata.c:916]: should do something like in `DistributionColumnUsesGeneratedStoredColumn` to fix pg11 builds

Comment (onurctirtir) [reply src/backend/distributed/commands/citus_add_local_table_to_metadata.c:920]: 71ad1bf

**Comment by onurctirtir** [comment]
This pr doesn't fix `GENERATED AS IDENTITY` cols and it doesn't seem to be an easy one to fix, I propose to error out such columns in another pr.

**Comment by onurctirtir** [comment]
Now I realized that we can't actually support GENERATED STORED columns too since our planner doesn't know that it should evaluate generated columns in coordinator.

**Comment by onurctirtir** [comment]
But now when undistributing such citus local tables, we would hit to this behavior: https://github.com/citusdata/citus/issues/4614
Not sure if we should support such GENERATED columns for citus local tables ?

File: src/backend/distributed/commands/sequence.c [hunk 2]
```diff
@@ -178,6 +179,12 @@ ExtractColumnsOwningSequences(Oid relationId, List **columnNameList,
 		}
 
 		char *columnName = NameStr(attributeForm->attname);
+		if (ColumnIsGeneratedStored(relationId, columnName))
```
Comment (onderkalaci) [inline src/backend/distributed/commands/sequence.c:182]: Why don't we check `if (attriuteForm-> attgenerated == ATTRIBUTE_GENERATED_STORED)`?

Comment (onurctirtir) [reply src/backend/distributed/commands/sequence.c:182]: oh true, we don't even need `ColumnIsGeneratedStored` :)

File: src/backend/distributed/commands/sequence.c [hunk 3]
```diff
@@ -177,6 +177,14 @@ ExtractColumnsOwningSequences(Oid relationId, List **columnNameList,
 			continue;
 		}
 
+#if PG_VERSION_NUM >= PG_VERSION_12
```
Comment (onderkalaci) [inline src/backend/distributed/commands/sequence.c:180]: I think the name of the function `ExtractColumnsOwningSequences` is pretty confusing. Maybe `ExtractDefaultColumnsAndOwningSequences()` and update the function comment a little?

Also, even `DropAndMoveDefaultSequenceOwnerships` -> `DropDefaultExpressiosAndMoveOwningSequnenceOwnerships` or such

**Review by onderkalaci — COMMENTED** [review]
It seems we treat `GENERATED BY DEFAULT AS IDENTITY` differently, where we don't re-create it on the shell table, which makes it inconsistent with `GENERATED BY .. STORED`:
```SQL
CREATE SEQUENCE my_seq;


CREATE TABLE t1(a int DEFAULT 5, 
				 b serial, 
				 c int generated always as (b*2) stored,
				 d int generated by default as identity (START WITH 100000 INCREMENT BY 1), 
				 e int);
                              Table "public.t1"
 Column |  Type   | Collation | Nullable |              Default               
--------+---------+-----------+----------+------------------------------------
 a      | integer |           |          | 5
 b      | integer |           | not null | nextval('t1_b_seq'::regclass)
 c      | integer |           |          | generated always as (b * 2) stored
 d      | integer |           | not null | generated by default as identity
 e      | integer |           |          | 


INSERT INTO t1 (e) VALUES (1), (2), (3);

SELECT * FROM t1;

SELECT citus_add_local_table_to_metadata('t1');

                              Table "public.t1"
 Column |  Type   | Collation | Nullable |              Default               
--------+---------+-----------+----------+------------------------------------
 a      | integer |           |          | 5
 b      | integer |           | not null | nextval('t1_b_seq'::regclass)
 c      | integer |           |          | generated always as (b * 2) stored
 d      | integer |           | not null | 
 e      | integer |           |          | 


                            Table "public.t1_102076"
 Column |  Type   | Collation | Nullable |              Default               
--------+---------+-----------+----------+------------------------------------
 a      | integer |           |          | 
 b      | integer |           | not null | 
 c      | integer |           |          | generated always as (b * 2) stored
 d      | integer |           | not null | generated by default as identity
 e      | integer |           |          | 



SELECT * FROM t1;
INSERT INTO t1 (e) VALUES (4), (5), (6);
SELECT * FROM t1;

```

Is this something that can we fix easily?

**Comment by onurctirtir** [comment]
>It seems we treat GENERATED BY DEFAULT AS IDENTITY differently, where we don't re-create it on the shell table, which makes it inconsistent with GENERATED BY .. STORED:

true, currently it's broken as I mentioned [here](https://github.com/citusdata/citus/pull/4613#issuecomment-770837197)

>Is this something that can we fix easily?
Yesterday I looked into that but seems that we need to implement deparse logic for such columns in deparser, which might require some more scoping. What do you think ?

File: src/backend/distributed/commands/sequence.c (hunk 3 above)
Comment (onurctirtir) [reply src/backend/distributed/commands/sequence.c:180]: makes sense, I will address those

Comment (onurctirtir) [reply src/backend/distributed/commands/sequence.c:180]: maybe ExtractColumnsOwningSequences -> ExtractDefaultColumnsAnd**Owned**Sequences

Comment (onurctirtir) [reply src/backend/distributed/commands/sequence.c:180]: similarly, maybe DropAndMoveDefaultSequenceOwnerships -> DropAndMoveDefaultSequenceOwnerships DropDefaultExpressionsAndMove**Owned**SequenceOwnerships

**Review by onderkalaci — COMMENTED** [review]
Overall, I'm not happy that `ExtractDefaultColumnsAndOwnedSequences ` does two things, by passing `Oid ownedSequenceId = InvalidOid;` if the column is a regular expression (opposed to expression with sequence). But, that's not this PR's problem, so maybe we can split function into two later with a separate PR

**Review by onderkalaci — APPROVED** [review]
I meant to approve with my previous comment
