### PR TITLE
PG18 - Handle PG18’s synthetic `RTE_GROUP` in `FindReferencedTableColumn` for correct GROUP BY pushdown

### LINKED ISSUE #8032: PG18 - cannot push down this subquery - add synthetic GROUP RTE support
**Description:**

https://github.com/postgres/postgres/commit/247dea89f7616fdf06b7272b74abafc29e8e5860

**Introduces a dedicated “grouping-step” RTE**
The parser now builds a pseudo-relation whose columns are exactly the grouping expressions (both simple Vars and arbitrary expressions) rather than leaving them buried in resjunk entries. 
[postgresql.org](https://www.postgresql.org/message-id/E1snrhe-000OKC-NW%40gemulon.postgresql.org?utm_source=chatgpt.com)

**Rewrites SELECT/HAVING refs to use that RTE**
Any reference to a grouping expression in the target list or HAVING clause is turned into a Var pointing at the new RTE. That guarantees there’s exactly one evaluation path — and one SubPlan for any subquery in a grouping expression — even under grouping sets.

**Ensures groupingSets is populated when needed**
Because the parser now knows precisely which grouping columns aren’t in the SELECT list, it automatically sets 
`Query->groupingSets` to non-NULL whenever you GROUP BY a column you haven’t projected.

Under PostgreSQL 18, whenever you write something like:

```
SELECT a + b AS sum_ab
  FROM tbl
  GROUP BY a, b, c;

```
—even though you didn’t project column c—the parser will now:

**Populate `Query->groupingSets` with a default singleton grouping set**

- It creates a one-element list whose contents are the grouping expressions `{a, b, c}`.
- In the internal `Query `struct, `groupingSets` was formerly left NULL for plain `GROUP BY`; now it holds something like

```
groupingSets = list_make1(list_make3(
    makeInteger(tleIndexOf(a)),
    makeInteger(tleIndexOf(b)),
    makeInteger(tleIndexOf(c))
));
```
This makes it unambiguous downstream which columns drove the grouping, even if some aren’t in the `SELECT`.

**Drives insertion of resjunk target-list entries**
- Because the planner sees that `c` is part of a grouping set but not one of the user-visible target columns, it creates a “resjunk” `TargetEntry` for it (and wires the `Var` in the new grouping-step RTE to that slot).
- That guarantees the executor still computes `c` per‐group, making it available for grouping logic without leaking it into your final result.

**Regress Diff:**

```
 SELECT
   events_table.event_type,
   users_count.ct
 FROM events_table
 	JOIN
 	(SELECT distinct_users.user_id, count(1) as ct
      FROM
      	(SELECT
           user_id
     	 FROM
           users_table
   		) as distinct_users
   	 GROUP BY
         distinct_users.user_id
     ) as users_count
     ON users_count.user_id = events_table.user_id
 ORDER BY
   users_count.ct desc, event_type DESC
 LIMIT 5;
- event_type | ct
----------------------------------------------------------------------
-          5 | 26
-          4 | 26
-          3 | 26
-          3 | 26
-          3 | 26
-(5 rows)
-
+ERROR:  cannot push down this subquery
+DETAIL:  Group by list without partition column is currently unsupported when a subquery references a column from another query
```

**Minimal reproduction**

```
-- schema -----------------------------------------------------------
CREATE TABLE raw_events_first (
  user_id  int,
  value_1  int,
  value_2  int,
  value_3  float,
  value_4  int
);
SELECT create_distributed_table('raw_events_first','user_id');

CREATE TABLE agg_events (
  value_3_agg float,
  value_4_agg bigint,
  value_1_agg int,
  user_id     int
);
SELECT create_distributed_table('agg_events','user_id');

-- trigger the planner difference ----------------------------------
SET client_min_messages = DEBUG1;        -- to see the DEBUG lines
INSERT INTO agg_events (value_3_agg, value_4_agg, value_1_agg, user_id)
SELECT sum(value_3), count(value_4), sum(value_1), user_id
FROM   raw_events_first
GROUP  BY value_2, user_id;

```

### PR DESCRIPTION
**Pull request by m3hm3t**
Fixes #8032 

PostgreSQL 18 introduces a dedicated “grouping-step” range table entry (`RTE_GROUP`) whose target columns are exactly the expressions in our `GROUP BY` clause, rather than hiding them as `resjunk` items. In Citus’s distributed planner, the function `FindReferencedTableColumn` must be able to map from a `Var` referencing a grouped column back to the underlying table column. Without special handling for `RTE_GROUP`, queries that rely on pushdown of `GROUP BY` expressions can fail or mis-identify their target columns.

This PR adds support for `RTE_GROUP` in Citus when built against PG 18 or later, ensuring that:

* Each grouped expression is correctly resolved.
* The pushdown planner can trace a `Var`’s `varattno` into the corresponding `groupexprs` list.
* Existing behavior on PG < 18 is unchanged.

---

## What’s Changed

In **`src/backend/distributed/planner/multi_logical_optimizer.c`**, inside `FindReferencedTableColumn`:

* **Under** `#if PG_VERSION_NUM >= PG_VERSION_18`
  Introduce an `else if` branch for

  ```c
  rangeTableEntry->rtekind == RTE_GROUP
  ```

* **Extraction of grouped expressions:**

  ```c
  List *groupexprs   = rangeTableEntry->groupexprs;
  AttrNumber groupIndex = candidateColumn->varattno - 1;
  ```

* **Safety check** to guard against malformed `Var` numbers:

  ```c
  if (groupIndex < 0 || groupIndex >= list_length(groupexprs))
      return;    /* malformed Var */
  ```

* **Recursive descent:**
  Fetch the corresponding expression from `groupexprs` and call

  ```c
  FindReferencedTableColumn(groupExpr, parentQueryList, query,
                            column, rteContainingReferencedColumn,
                            skipOuterVars);
  ```

  so that the normal resolution logic applies to the underlying expression.

* **Unchanged code path** for PG < 18 and for other `rtekind` values.

---

### CODE REVIEW

File: src/backend/distributed/planner/multi_logical_optimizer.c [hunk 1]
```diff
@@ -4557,6 +4557,31 @@ FindReferencedTableColumn(Expr *columnExpression, List *parentQueryList, Query *
...
+		 * columns produced by the grouping step, in the *same ordinal order* as
+		 * the Vars that reference them.
+		 */
+		List *groupexprs = rangeTableEntry->groupexprs;
+		AttrNumber groupIndex = candidateColumn->varattno - 1;
+
+		/* Safety check */
+		if (groupIndex < 0 || groupIndex >= list_length(groupexprs))
+		{
+			return;  /* malformed Var */
```
Comment (colm-mchugh) [inline src/backend/distributed/planner/multi_logical_optimizer.c]: Is this `malformed Var` codepath ever taken ? It doesn't seem probable, unless the Postgres planner has miscalculated when constructing a Var that references a Group RTE. If it is please give an example, but if not can we make this an Assert that the groupIndex is a valid index into the Group RTE's grouping expressions ?

Comment (m3hm3t) [reply src/backend/distributed/planner/multi_logical_optimizer.c]: @colm-mchugh 

I’m confident that PostgreSQL core always assigns each `Var` on an `RTE_GROUP` a `varattno` in the range `1…list_length(rte->groupexprs)` but cannot find the related code segment. 

So turning that safety check into an `Assert` seems ideal—under debug builds it will immediately catch any rare planner mis-wiring, while in production there’s no added branch or error‐handling overhead. If that sounds good, I’ll apply the diff below.


```diff
-   /* Safety check */
-   if (groupIndex < 0 || groupIndex >= list_length(gexprs))
-       return;  /* malformed Var */
+   AttrNumber groupIndex = candidateColumn->varattno - 1;
+   /* this must always hold unless upstream Postgres mis-constructed the RTE_GROUP */
+   Assert(groupIndex >= 0 && groupIndex < list_length(gexprs));
```

Comment (m3hm3t) [reply src/backend/distributed/planner/multi_logical_optimizer.c]: refactored as agreed

https://github.com/citusdata/citus/pull/8034/commits/2b306069703c3d917ef9b5baae5e1d9c15174e28

**Review by naisila — COMMENTED** [review]
LGTM as well, thanks for the detailed description.
Let's wait for merging until after we merge the build PR.

**Comment by m3hm3t** [comment]
Executed using the pg18 configuration, and the expected error remains resolved.

https://github.com/citusdata/citus/actions/runs/16324324890
