### PR TITLE
verify shards if exists for insert, delete, update

### LINKED ISSUE #1160: Add a serialization failure error for DMLs on a splitted shard
During tenant isolation, we get exclusive locks on the target shards (on the shardid). Modification queries which come during tenant isolation start to wait on these locks. After tenant isolation finishes, modification queries will get the locks, but shards in the question will be gone already, and they will error out with this message:

```sql
“WARNING:  could not find any shard placements for shardId 102763
ERROR:  failed to assign 1 task(s) to worker nodes
STATEMENT:  INSERT INTO lineitem (l_orderkey) values (21787)”
```

We discussed adding a new function VerifyShardStillExists(). First of all, the problem above is not a big problem as much as I though at the first place thanks to our new connection API. We will not have a case where the client thinks he successfully inserted a row but that row inserted to the dropped shard.

By adding VerifyShardStillExists(), we can return a serialization failure error code to the user such that clients know that they should retry the query.

### PR DESCRIPTION
**Pull request by aykut-bozkurt**
DESCRIPTION: Checks existence of the shards before insert, delete, and update.

Resolves #1160.

### CODE REVIEW

**Comment by aykut-bozkurt** [comment]
TODO: We can reroute tasks with invalid shards if we really can.

File: src/backend/distributed/utils/shard_utils.c [hunk 1]
```diff
@@ -121,3 +124,29 @@ GetLargestShardId()
...
+ * shard id.
+ */
+void
+VerifyShardsStillExist(List *taskList)
+{
+	Task *task = NULL;
+	foreach_ptr(task, taskList)
+	{
+		bool missingOk = true;
+		Oid shardRelationId = LookupShardRelationFromCatalog(task->anchorShardId,
```
Comment (marcocitus) [inline src/backend/distributed/utils/shard_utils.c:140]: Hmz, this seems like it might be slow for the common / no split case, since we need to be able to handle hundreds of thousands of queries per second via this path. Can we go via the cache here?

File: src/backend/distributed/executor/citus_custom_scan.c [hunk 2]
```diff
@@ -440,6 +444,41 @@ CitusBeginModifyScan(CustomScanState *node, EState *estate, int eflags)
...
+EnsureShardsExist(Job *job, bool fastPath)
+{
+	if (!ShardsStillExist(job->taskList))
+	{
+		if (fastPath)
+		{
+			if (job->jobQuery->commandType == CMD_INSERT)
+			{
+				RegenerateTaskListForInsert(job);
+			}
```
Comment (marcocitus) [inline src/backend/distributed/executor/citus_custom_scan.c:462]: This function does more than the name suggests. Should we split it in two?

```c
if (fastPath && !ShardsStillExists(job->taskList))
{
    TryToRerouteFastPathQuery(job);
}

EnsureShardsExist(job);
```

File: src/backend/distributed/metadata/metadata_cache.c [hunk 3]
```diff
@@ -798,13 +800,32 @@ LoadShardInterval(uint64 shardId)
...
+/*
+ * ShardExists returns whether given shard exists or not. It fails if missingOk is false
+ * and shard is not found.
+ */
+bool
+ShardExists(uint64 shardId, bool missingOk)
+{
+	ShardIdCacheEntry *shardIdEntry = LookupShardIdCacheEntry(shardId, missingOk);
+
+	if (!shardIdEntry || !shardIdEntry->tableEntry || !shardIdEntry->tableEntry->isValid)
```
Comment (marcocitus) [inline src/backend/distributed/metadata/metadata_cache.c:812]: would the !shardIdEntry be enough? the other two checks seem a bit strange

File: src/backend/distributed/planner/deparse_shard_query.c [hunk 4]
```diff
@@ -79,13 +80,20 @@ RebuildQueryStrings(Job *workerJob)
...
 			 * pg_get_query_def() directly.
 			 */
-			List *relationShardList = task->relationShardList;
 			UpdateRelationToShardNames((Node *) query, relationShardList);
+
+			/*
+			 * For UPDATE and DELETE queries, we have relations wrapped in citus container
+			 * function. We traverse those, and convert them to shards.
+			 */
+			UpdateCitusContainerWrappedRelationToShardNames(query, relationShardList);
```
Comment (marcocitus) [inline src/backend/distributed/planner/deparse_shard_query.c:96]: It's a bit strange that we do this right after UpdateRelationToShardNames, because we basically transform the RTEs again.

Could we integrate this into UpdateRelationToShardNames?

File: src/test/regress/expected/isolation_tenant_isolation.out [hunk 5]
```diff
@@ -135,15 +133,14 @@ step s2-print-cluster:
 nodeport|shardid|success|result
 ---------------------------------------------------------------------
    57637|1500009|t      |     0
-   57637|1500010|t      |     1
+   57637|1500010|t      |     0
```
Comment (marcocitus) [inline src/test/regress/expected/isolation_tenant_isolation.out:136]: why do these appear?

Comment (aykut-bozkurt) [reply src/test/regress/expected/isolation_tenant_isolation.out:136]: We are isolating tenant with id=5 inside a transaction. Then, before committing it, we also try to delete id=5 from another transaction which does not see the effects of first transaction. It fetches old shards and waits for the locks. Then first transaction commits, and second transaction acquires locks and checks if shards are still valid. It reroutes shards because they changed and successfully deletes id=5. 

Before we were failing with a shard not found error, but now we execute delete successfully. That is why we have those changes. 

```sql
step s2-begin:
 BEGIN;

step s2-isolate-tenant:
 SELECT isolate_tenant_to_new_shard('isolation_table', 5, shard_transfer_mode => 'block_writes');

isolate_tenant_to_new_shard
---------------------------------------------------------------------
                    1500010
(1 row)

step s1-delete:
 DELETE FROM isolation_table WHERE id = 5;
 <waiting ...>
step s2-commit: 
 COMMIT;

step s1-delete: <... completed>
```

File: src/backend/distributed/metadata/metadata_sync.c [hunk 6]
```diff
@@ -3660,13 +3661,14 @@ citus_internal_delete_shard_metadata(PG_FUNCTION_ARGS)
 		/* this UDF is not allowed allowed for executing as a separate command */
 		EnsureCoordinatorInitiatedOperation();
 
-		if (!ShardExists(shardId))
+		bool missingOk = false;
+
+		if (!ShardExists(shardId, missingOk))
```
Comment (marcocitus) [inline src/backend/distributed/metadata/metadata_sync.c:3666]: with missingOk is false, the error below is never reached. It seems like the intention of ShardExists is to always have missingOk is true, so the argument can probaby be removed.

File: src/backend/distributed/planner/multi_router_planner.c [hunk 7]
```diff
@@ -2677,8 +2677,8 @@ TargetShardIntervalForFastPathQuery(Query *query, bool *isMultiShardQuery,
 	}
 
 	/* we're only expecting single shard from a single table */
-	Node *distKey PG_USED_FOR_ASSERTS_ONLY = NULL;
-	Assert(FastPathRouterQuery(query, &distKey) || !EnableFastPathRouterPlanner);
+	/*Node *distKey PG_USED_FOR_ASSERTS_ONLY = NULL; */
+	/*Assert(FastPathRouterQuery(query, &distKey) || !EnableFastPathRouterPlanner); */
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_router_planner.c:2681]: I would expect this to still hold / we shouldn't go in here for non-fast-path queries.

File: src/test/regress/expected/isolation_tenant_isolation.out (hunk 5 above)
Comment (marcocitus) [reply src/test/regress/expected/isolation_tenant_isolation.out:136]: got it, we may want to cover a non-fast-path query

Comment (marcocitus) [reply src/test/regress/expected/isolation_tenant_isolation.out:136]: added

File: src/backend/distributed/planner/multi_router_planner.c (hunk 7 above)
Comment (marcocitus) [reply src/backend/distributed/planner/multi_router_planner.c]: this no longer holds because we rewrote the RTEs already, but we can remove the assert

**Review by marcocitus — APPROVED** [review]
