### PR TITLE
PG18 - register snapshot where needed

### LINKED ISSUE #8195: PG18 - More snapshot crashes when assertions are enabled
Relevant PG commit https://github.com/postgres/postgres/commit/8076c00592e40e8dbd1fce7a98b20d4bf075e4ba

Reproduction steps:

```SQL
CREATE TABLE test_table (id int) USING columnar;
INSERT INTO test_table VALUES (0);

SELECT * FROM test_table;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

Assertion that fails is:
```C
Assert(snapshot->regd_count > 0 || snapshot->active_count > 0);
```

Crashing since PG 18beta1. Example crashing test: `citus_split_shard_columnar_partitioned`

**EDIT:**
`multi_partitioning` also crashing when creating indexes, steps to reproduce:
```SQL
CREATE TABLE partitioning_test(id int, time date) PARTITION BY RANGE (time);
CREATE TABLE partitioning_test_2009 PARTITION OF partitioning_test FOR VALUES FROM ('2009-01-01') TO ('2010-01-01');
CREATE TABLE partitioning_test_2010 PARTITION OF partitioning_test FOR VALUES FROM ('2010-01-01') TO ('2011-01-01');
INSERT INTO partitioning_test VALUES (1, '2009-06-06');
INSERT INTO partitioning_test VALUES (2, '2010-07-07');
INSERT INTO partitioning_test_2009 VALUES (3, '2009-09-09');
INSERT INTO partitioning_test_2010 VALUES (4, '2010-03-03');
SELECT create_distributed_table('partitioning_test', 'id');

CREATE INDEX partitioning_index ON partitioning_test(id);
CREATE INDEX partitioning_2009_index ON partitioning_test_2009(id);

CREATE INDEX CONCURRENTLY partitioned_2010_index ON partitioning_test_2010(id);
-- crash
```

### PR DESCRIPTION
**Pull request by naisila**
Register and push snapshots as needed per the relevant PG18 commits
https://github.com/postgres/postgres/commit/8076c00592e40e8dbd1fce7a98b20d4bf075e4ba
https://github.com/postgres/postgres/commit/706054b

`citus_split_shard_columnar_partitioned`, `multi_partitioning` tests are handled.

Fixes #8195

### CODE REVIEW

File: src/backend/columnar/columnar_metadata.c [hunk 1]
```diff
@@ -1267,7 +1267,13 @@ StripesForRelfilelocator(RelFileLocator relfilelocator)
 {
 	uint64 storageId = LookupStorageId(relfilelocator);
 
-	return ReadDataFileStripeList(storageId, GetTransactionSnapshot());
+	Snapshot snapshot = RegisterSnapshot(GetTransactionSnapshot());
```
Comment (m3hm3t) [inline src/backend/columnar/columnar_metadata.c:1278]: nitpick to add comment

```
/*
 * PG18 requires snapshots to be registered before use in syscache/catalog
 * lookups. Without this, we hit "HaveRegisteredOrActiveSnapshot" asserts
 * when reading columnar stripes.
 */
```
