### PR TITLE
Fix write queries with const expressions and COLLATE in various places

### LINKED ISSUE #3957: ERROR: unrecognized node type: 127 with queries involving COLLATE
The error "PSQLException: ERROR: unrecognized node type: 127" shows up with queries involving COLLATE. This error was hit many times by the SQLancer tool, and logs for 2 sample executions are attached including steps to reproduce.
[database2 log.txt](https://github.com/citusdata/citus/files/4852231/database2.log.txt)
[database16 log.txt](https://github.com/citusdata/citus/files/4852232/database16.log.txt)

### PR DESCRIPTION
**Pull request by JelteF**
DESCRIPTION: Fix write queries with const expressions and COLLATE in various places

Fixes #3957

There might be better places to put these calls to `eval_const_expressions`.
This PR is currently meant to discuss that.

### CODE REVIEW

File: src/backend/distributed/planner/multi_router_planner.c [hunk 1]
```diff
@@ -2701,8 +2701,11 @@ BuildRoutesForInsert(Query *query, DeferredErrorMessage **planningError)
 	{
 		InsertValues *insertValues = (InsertValues *) lfirst(insertValuesCell);
 		List *prunedShardIntervalList = NIL;
-		Expr *partitionValueExpr = (Expr *) strip_implicit_coercions(
-			(Node *) insertValues->partitionValueExpr);
+		Expr *partitionValueExpr = (Expr *) eval_const_expressions(NULL,
+																   strip_implicit_coercions(
```
Comment (JelteF) [inline src/backend/distributed/planner/multi_router_planner.c:2705]: maybe these calls should be swapped, i.e
```suggestion
		Expr *partitionValueExpr = (Expr *) strip_implicit_coercions(NULL,
																   eval_const_expressions(
```

**Comment by SaitTalhaNisanci** [comment]
I guess it would be more useful to write what we are fixing here instead of `Fix issues found by SQLancer` which won't mean much to whoever is looking at the changelog.

File: src/backend/distributed/planner/multi_router_planner.c [hunk 2]
```diff
@@ -2701,8 +2701,17 @@ BuildRoutesForInsert(Query *query, DeferredErrorMessage **planningError)
...
+		partitionValueExpr = strip_implicit_coercions(partitionValueExpr);
+
+		/*
+		 * By evaluating constant expressions an expression such as 2 + 4
+		 * will become const 6. That way we can use them as a partition column
+		 * value. Normally the planner evaluates constant expressions, but we
+		 * may be working on the original query tree here. So we do it here
+		 * explicitely before checking that the partition value is a const.
+		 */
+		partitionValueExpr = eval_const_expressions(NULL, partitionValueExpr);
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_router_planner.c:2714]: In Citus code, we mostly rely on `eval_const_expression`. But, I was considering to use [`expression_planner`](https://github.com/postgres/postgres/blob/92c58fd94801dd5c81ee20e26c5bb71ad64552a8/src/backend/optimizer/plan/planner.c#L6128) at some point. 

Do you see any difference for this case? I have no  idea, just bringing up as I was considering to use `expression_planner` over `eval_const_expressions ` if we think it is better at some point

Comment (JelteF) [reply src/backend/distributed/planner/multi_router_planner.c:2714]: I took a look at the source code of `expression_planner`. The only difference is it also calls `fix_opfuncids` after it called `eval_const_expressions`. This doesn't matter in either of the calls in this PR:
1. `fix_opfuncids` doesn't do anything for `T_Const`, so we don't care about it at this callsite of `eval_const_expressions`. Because if we don't get a `T_Const` we error out.
2. In the other callsite, `fix_opfuncids` is already called in `citus_evaluate_expr`. So we would do it twice.

Since `fix_opfuncids` is another `expression_tree_walker`, I think it's better to leave them as is to not cause unnecessary slowdowns.

I'll add this information to the respective comments.

File: src/backend/distributed/utils/citus_clauses.c [hunk 3]
```diff
@@ -117,6 +117,38 @@ PartiallyEvaluateExpression(Node *expression,
...
+		 * We do not need this, since that is already called in
+		 * citus_evaluate_expr. So we won't needlessly traverse the expression
+		 * tree by calling it another time.
+		 */
+		expression = eval_const_expressions(NULL, expression);
+		if (!ShouldEvaluateExpression((Expr *) expression))
+		{
+			/*
+			 * It's possible that after evaluating const expressions we
+			 * actually don't need to evaluate this expression anymore e.g:
```
Comment (marcocitus) [inline src/backend/distributed/utils/citus_clauses.c:140]: What does this comment refer to? Should it me moved above the if statement?

File: src/backend/distributed/planner/multi_router_planner.c [hunk 4]
```diff
@@ -2701,8 +2701,22 @@ BuildRoutesForInsert(Query *query, DeferredErrorMessage **planningError)
 	{
 		InsertValues *insertValues = (InsertValues *) lfirst(insertValuesCell);
 		List *prunedShardIntervalList = NIL;
-		Expr *partitionValueExpr = (Expr *) strip_implicit_coercions(
-			(Node *) insertValues->partitionValueExpr);
+		Node *partitionValueExpr = (Node *) insertValues->partitionValueExpr;
+		partitionValueExpr = strip_implicit_coercions(partitionValueExpr);
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_router_planner.c:2705]: I'm wondering: Is strip_implicit_coercions still necessary if we call eval_const_expressions?

File: src/test/regress/expected/sqlancer_failures.out [hunk 5]
```diff
@@ -0,0 +1,113 @@
...
+(7 rows)
+
+CREATE TABLE t5(c0 int);
+SELECT create_distributed_table('t5', 'c0');
+ create_distributed_table
+---------------------------------------------------------------------
+
+(1 row)
+
+INSERT INTO t5 VALUES (GREATEST(1, 2));
```
Comment (marcocitus) [inline src/test/regress/expected/sqlancer_failures.out:86]: this line causes tests to fail

Comment (JelteF) [reply src/test/regress/expected/sqlancer_failures.out]: Yes, seems it's constant evaluated in PG12, but not in PG11. I removed it since it's not super important and the test doesn't add much over `CASE ... WHEN ... END`. Seems I forgot to update the test output though.

File: src/test/regress/expected/sqlancer_failures.out [hunk 6]
```diff
@@ -0,0 +1,112 @@
...
+
+EXPLAIN SELECT FROM t5 WHERE c0 = CASE WHEN 2 BETWEEN 1 AND 3 THEN 2 ELSE 1 END;
+                                 QUERY PLAN
+---------------------------------------------------------------------
+ Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=0 width=0)
+   Task Count: 1
+   Tasks Shown: All
+   ->  Task
+         Node: host=localhost port=xxxxx dbname=regression
+         ->  Seq Scan on t5_92862423 t5  (cost=0.00..41.88 rows=13 width=0)
```
Comment (marcocitus) [inline src/test/regress/expected/sqlancer_failures.out:107]: should turn off costs

File: src/backend/distributed/planner/multi_router_planner.c (hunk 4 above)
Comment (JelteF) [reply src/backend/distributed/planner/multi_router_planner.c]: This indeed seems like it's not needed anymore. I've removed it now. Tests still pass without it, now that we have `eval_const_expressions`. Lot's of tests start failing when we remove both though, so we do have tests for the effects of `strip_implicit_coercions`. Without both we get lot's of failures with this error:
```

Comment (JelteF) [reply src/backend/distributed/planner/multi_router_planner.c]: Looking at the code for `strip_implicit_coercions` it also removes `CoerceViaIO`, but `eval_const_expressions` replaces it with two function calls. So I think it might be safer to still keep it and call `strip_implicit_coercions` first. I'll take a look on monday if I can create a test that would fail without having it.

File: src/backend/distributed/utils/citus_clauses.c [hunk 7]
```diff
@@ -117,6 +117,40 @@ PartiallyEvaluateExpression(Node *expression,
...
+		expression = eval_const_expressions(NULL, expression);
+
+		/*
+		 * It's possible that after evaluating const expressions we
+		 * actually don't need to evaluate this expression anymore e.g:
+		 *
+		 * 1 = 0 AND now() > timestamp '10-10-2000 00:00'
+		 *
+		 * This statement would simply resolve to false, because 1 = 0 is
+		 * false. That's whe we now check again if we should evaluate the
```
Comment (JelteF) [inline src/backend/distributed/utils/citus_clauses.c:144]:
```suggestion
		 * false. That's why we now check again if we should evaluate the
```
