### PR TITLE
Fix segfault. Issue #7381

### LINKED ISSUE #7381: Segmentation fault CASE WHEN with DO block
When using the CASE WHEN expression in the body of the function that is used in the DO block, a segmentation error occurs.
If you call with a simple parameter in the DO block, then the error is not observed.
There is no such error in pure postgresql.
I have checked several versions of citus and this problem has been observed everywhere.

**Example:**
```
CREATE OR REPLACE FUNCTION public.test_err(v1 text)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$

begin
  return v1 || ' - ok';
END;
$function$;
do $$ declare 
 lNewValues text;
 val text;
begin 
 val = 'test';
 lNewValues = public.test_err(v1 => case when val::text = 'test'::text then 'yes' else 'no' end);
 raise notice 'lNewValues= %', lNewValues;
end;$$ ;
```

**Short log:**
```
14:11:30.082 [2673] LOG:  server process (PID 14341) was terminated by signal 11: Segmentation fault
14:11:30.082 [2673] DETAIL:  Failed process was running: do $$ declare 
     lNewValues text;
     val text;
    begin 
     val = 'test';
     lNewValues = public.test_err(v1 => case when val::text = 'test'::text then 'yes' else 'no' end);
    
     raise notice 'lNewValues= %', lNewValues;
    end;$$ ;
14:11:30.082 [2673] LOG:  terminating any other active server processes
14:11:30.083 [14185] LOG:  could not receive data from client: Connection reset by peer
14:11:30.086 [14343] FATAL:  the database system is in recovery mode
14:11:30.087 [2673] LOG:  all server processes terminated; reinitializing
14:11:30.123 [14344] LOG:  database system was interrupted; last known up at 13:51:57 
14:11:30.136 [14344] LOG:  database system was not properly shut down; automatic recovery in progress
14:11:30.138 [14344] LOG:  redo starts at 2/BA198838
14:11:30.138 [14344] LOG:  invalid record length at 2/BA198870: wanted 24, got 0
14:11:30.138 [14344] LOG:  redo done at 2/BA198838 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
14:11:30.146 [14345] LOG:  checkpoint starting: end-of-recovery immediate wait
14:11:30.152 [14345] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.002 s, sync=0.001 s, total=0.007 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB
14:11:30.163 [2673] LOG:  database system is ready to accept connections
14:11:31.161 [7821] WARNING:  111:5432:SELECT waiting_pid, waiting_node_id, waiting_transaction_num, waiting_transaction_stamp, blocking_pid, blocking_node_id, blocking_transaction_num, blocking_transaction_stamp, blocking_transaction_waiting FROM dump_local_wait_edges() 
14:11:31.161 [7821] CONTEXT:  Citus maintenance daemon for database 244221 user 10
14:11:31.161 [7821] WARNING:  SSL SYSCALL error: EOF detected
14:11:31.161 [7821] CONTEXT:  while executing command on 127.0.0.1:5432
```

### PR DESCRIPTION
**Pull request by copetol**
Hi!

Fixes #7381

### CODE REVIEW

**Comment by copetol** [comment]
@microsoft-github-policy-service agree company="Fors"

**Comment by JelteF** [comment]
Thank you for the contribution! On first glance the fix looks reasonable. Could you add a the repro case from the linked issue as a regression test? That way we can make sure we wont re-introduce this issue accidentally in the future.

**Comment by copetol** [comment]
I've added test to multi_schedule, do not know if it is ok, but only there it works

File: src/test/regress/multi_schedule [hunk 1]
```diff
@@ -134,3 +134,5 @@ test: check_mx
 test: generated_identity
 test: drop_database
 test: check_cluster_state
+
+test: function_with_case_when
```
Comment (JelteF) [inline src/test/regress/multi_schedule:138]: can you move this test above line 125, which contains `ensure_no_intermediate_data_leak`?

File: src/test/regress/sql/function_with_case_when.sql [hunk 2]
```diff
@@ -0,0 +1,22 @@
+-- create function
```
Comment (JelteF) [inline src/test/regress/sql/function_with_case_when.sql:1]: To avoid leaking objects from one test to another we generally create a dedicated schema for the test and set the search_path accordingly. The easiest way to do that is by running this script: https://github.com/citusdata/citus/blob/main/src/test/regress/bin/create_test.py

File: src/test/regress/multi_schedule (hunk 1 above)
Comment (copetol) [reply src/test/regress/multi_schedule]: done

File: src/test/regress/sql/function_with_case_when.sql [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+ lNewValues text;
+ val text;
+begin 
+ val = 'test';
+ lNewValues = test_err(v1 => case when val::text = 'test'::text then 'yes' else 'no' end);
+ raise notice 'lNewValues= %', lNewValues;
+end;$$ ;
+
+-- call function
+SELECT test_err('test');
```
Comment (JelteF) [inline src/test/regress/sql/function_with_case_when.sql:25]: Should have `DROP SCHEMA function_with_case`

**Review by JelteF — APPROVED** [review]
