### PR TITLE
Throw an error if there is a RangeTblEntry that is not assigned an RTE identity.

### LINKED ISSUE #6109: Segfault or (assertion failure) is possible when using a SQL function
Based on https://github.com/citusdata/citus/issues/6102#issuecomment-1199955084 & https://github.com/citusdata/citus/issues/6102#issuecomment-1200151367:

```sql
create table test1 (
    dist_col text,
    random_col_1 text,
    random_col_2 int
);

create table test2 (
    dist_col text,
    random_col_1 text,
    random_col_2 int,
    random_col_3 int,
    random_col_4 text
);

select * from create_distributed_table('test1', 'dist_col');
select * from create_distributed_table('test2', 'dist_col');

create or replace function public.get_test1()
returns setof test1 
language sql
stable parallel safe as 
$function$
    select * from test1
$function$;
```

```sql
select (select 1 from test1 limit 1) from get_test1();
```

And if asserts are disabled, then we segfault at:
```c
citus.so!list_nth_cell(const List * list, int n) (\opt\pgenv\pgsql-14.3\include\server\nodes\pg_list.h:260)
citus.so!GetRTEIdentity(RangeTblEntry * rte) (\home\onurctirtir\citus\src\backend\distributed\planner\distributed_planner.c:480)
citus.so!UniqueRelationCount(RelationRestrictionContext * restrictionContext, CitusTableType tableType) (\home\onurctirtir\citus\src\backend\distributed\planner\relation_restriction_equivalence.c:663)
citus.so!ContainsMultipleDistributedRelations(PlannerRestrictionContext * plannerRestrictionContext) (\home\onurctirtir\citus\src\backend\distributed\planner\relation_restriction_equivalence.c:582)
citus.so!RestrictionEquivalenceForPartitionKeys(PlannerRestrictionContext * restrictionContext) (\home\onurctirtir\citus\src\backend\distributed\planner\relation_restriction_equivalence.c:526)
citus.so!AllDistributionKeysInQueryAreEqual(Query * originalQuery, PlannerRestrictionContext * plannerRestrictionContext) (\home\onurctirtir\citus\src\backend\distributed\planner\relation_restriction_equivalence.c:202)
citus.so!GenerateSubplansForSubqueriesAndCTEs(uint64 planId, Query * originalQuery, PlannerRestrictionContext * plannerRestrictionContext) (\home\onurctirtir\citus\src\backend\distributed\planner\recursive_planning.c:228)
citus.so!CreateDistributedPlan(uint64 planId, Query * originalQuery, Query * query, ParamListInfo boundParams, _Bool hasUnresolvedParams, PlannerRestrictionContext * plannerRestrictionContext) (\home\onurctirtir\citus\src\backend\distributed\planner\distributed_planner.c:968)
citus.so!CreateDistributedPlan(uint64 planId, Query * originalQuery, Query * query, ParamListInfo boundParams, _Bool hasUnresolvedParams, PlannerRestrictionContext * plannerRestrictionContext) (\home\onurctirtir\citus\src\backend\distributed\planner\distributed_planner.c:1015)
citus.so!CreateDistributedPlannedStmt(DistributedPlanningContext * planContext) (\home\onurctirtir\citus\src\backend\distributed\planner\distributed_planner.c:676)
citus.so!PlanDistributedStmt(DistributedPlanningContext * planContext, int rteIdCounter) (\home\onurctirtir\citus\src\backend\distributed\planner\distributed_planner.c:612)
citus.so!distributed_planner(Query * parse, const char * query_string, int cursorOptions, ParamListInfo boundParams) (\home\onurctirtir\citus\src\backend\distributed\planner\distributed_planner.c:240)
pg_stat_statements.so!pgss_planner(Query * parse, const char * query_string, int cursorOptions, ParamListInfo boundParams) (\opt\pgenv\src\postgresql-14.3\contrib\pg_stat_statements\pg_stat_statements.c:946)
planner(Query * parse, const char * query_string, int cursorOptions, ParamListInfo boundParams) (\opt\pgenv\src\postgresql-14.3\src\backend\optimizer\plan\planner.c:269)
pg_plan_query(Query * querytree, const char * query_string, int cursorOptions, ParamListInfo boundParams) (\opt\pgenv\src\postgresql-14.3\src\backend\tcop\postgres.c:847)
pg_plan_queries(List * querytrees, const char * query_string, int cursorOptions, ParamListInfo boundParams) (\opt\pgenv\src\postgresql-14.3\src\backend\tcop\postgres.c:939)
exec_simple_query(const char * query_string) (\opt\pgenv\src\postgresql-14.3\src\backend\tcop\postgres.c:1133)
PostgresMain(int argc, char ** argv, const char * dbname, const char * username) (\opt\pgenv\src\postgresql-14.3\src\backend\tcop\postgres.c:4496)
BackendRun(Port * port) (\opt\pgenv\src\postgresql-14.3\src\backend\postmaster\postmaster.c:4530)
BackendStartup(Port * port) (\opt\pgenv\src\postgresql-14.3\src\backend\postmaster\postmaster.c:4252)
ServerLoop() (\opt\pgenv\src\postgresql-14.3\src\backend\postmaster\postmaster.c:1745)
PostmasterMain(int argc, char ** argv) (\opt\pgenv\src\postgresql-14.3\src\backend\postmaster\postmaster.c:1417)
main(int argc, char ** argv) (\opt\pgenv\src\postgresql-14.3\src\backend\main\main.c:209)
```

### PR DESCRIPTION
**Pull request by emelsimsek**
DESCRIPTION: Makes sure to disallow usage of SQL functions referencing to a distributed table and prevents a segfault

Using a SQL function may result in segmentation fault in some cases.  This change fixes the issue by throwing an error message when a SQL function cannot be handled.

Fixes #6109.

### CODE REVIEW

**Comment by onurctirtir** [comment]
1) test-14_check-isolation seems to be a flaky failure, so a re-run should be fine.

2) check-style failure means that you need to run `make reindent` on your branch to automatically do the changes needed to make `check-style` happy.

3) We add a DESCRIPTION: line into the PRs if we're doing something user-facing --such as fixing a bug-- so that our release tooling can automatically add that entry into `CHANGELOG.md` file. So let's add the following into PR description:

> DESCRIPTION: Ensures disallowing the usage of SQL functions referencing to a distributed table and prevents a segfault
>
> Fixes #6109.

4) Having a PR title that tells about "how" we're fixing the linked issue is also important:

> Throw an error if there is a RangeTblEntry that is not assigned an RTE identity

5) Adding the case noted in https://github.com/citusdata/citus/issues/6109 as a regression test (to an appropriate SQL file) would be nice.

Feel free to ping me for any of those if you need any help.

File: src/backend/distributed/planner/distributed_planner.c [hunk 1]
```diff
@@ -559,7 +559,22 @@ int
...
 {
 	Assert(rte->rtekind == RTE_RELATION);
-	Assert(rte->values_lists != NIL);
+
+	/*
+	 * RangeTblEntry value_lists must not be empty at this point.
+	 * However, this might happen when processing SQL functions
+	 * in which case we will throw an error.
+	*/
+	if (rte->values_lists == NIL)
```
Comment (onurctirtir) [inline src/backend/distributed/planner/distributed_planner.c:568]: I think we can drop below assertion as well and do:

```suggestion
	if (list_length(rte->values_lists) != 2)
```

File: src/backend/distributed/planner/distributed_planner.c [hunk 2]
```diff
@@ -559,7 +559,22 @@ int
 GetRTEIdentity(RangeTblEntry *rte)
 {
 	Assert(rte->rtekind == RTE_RELATION);
-	Assert(rte->values_lists != NIL);
+
+	/*
+	 * RangeTblEntry value_lists must not be empty at this point.
+	 * However, this might happen when processing SQL functions
+	 * in which case we will throw an error.
```
Comment (onurctirtir) [inline src/backend/distributed/planner/distributed_planner.c:566]: Suggestion for a slightly better comment:
```suggestion
	 * Since SQL functions might be in-lined by standard_planner,
	 * we might miss assigning an RTE identity for RangeTblEntry's
	 * related to SQL functions. We already have checks in other
	 * places to throw an error for SQL functions but they are not
	 * sufficient due to function in-lining; so here we capture such
	 * cases and throw an error here.
```

**Comment by onurctirtir** [comment]
> 3) We add a DESCRIPTION: line into the PRs if we're doing something user-facing --such as fixing a bug-- so that our release tooling can automatically add that entry into `CHANGELOG.md` file. So let's add the following into PR description. The last line allows automatically closing the related issue after merging the PR.
> 
> > DESCRIPTION: Ensures disallowing the usage of SQL functions referencing to a distributed table and prevents a segfault
> >
> > Using a SQL function may result in segmentation fault in some cases. This change ....
> >
> > Fixes #6109.

Thank you for updating PR title, and let's not forget this^ as well.

File: src/backend/distributed/planner/distributed_planner.c (hunk 1 above)
Comment (emelsimsek) [reply src/backend/distributed/planner/distributed_planner.c]: Changed to suggested.

File: src/backend/distributed/planner/distributed_planner.c [hunk 3]
```diff
@@ -559,9 +559,26 @@ int
...
+	{
+		ereport(ERROR, (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
+						errmsg("cannot perform distributed planning on this "
+							   "query because parameterized queries for SQL "
+							   "functions referencing distributed tables are "
+							   "not supported"),
+						errhint("Consider using PL/pgSQL functions instead.")));
+	}
+
 	Assert(IsA(rte->values_lists, IntList));
```
Comment (onurctirtir) [inline src/backend/distributed/planner/distributed_planner.c:581]: let's move this to right after L561

**Review by onurctirtir — APPROVED** [review]
LGTM, please consider addressing the last^ comment.

And please squash merge by inheriting the PR title as commit message, which is what github automatically does I guess.

File: src/backend/distributed/planner/distributed_planner.c (hunk 3 above)
Comment (onurctirtir) [reply src/backend/distributed/planner/distributed_planner.c:581]: nvm, this doesn't make sense
