### PR TITLE
Fix error message of start_metadata_sync_to_node

### LINKED ISSUE #1203: Fix error message of start_metadata_sync_to_node
In error message of start_metadata_sync_to_node, if node is not in the cluster, it says 
```
you cannot sync metadata to a non-existent node
First, add the node with SELECT master_add_node(localhost,9705)
```
We should add quotation marks around localhost.

### PR DESCRIPTION
**Pull request by velioglu**
Fixes #1203.

Single quotation mark is added around nodename to make the error code consistent with master_add_node usage.

### CODE REVIEW

File: src/backend/distributed/metadata/metadata_sync.c [hunk 1]
```diff
@@ -94,8 +94,9 @@ start_metadata_sync_to_node(PG_FUNCTION_ARGS)
 	{
 		ereport(ERROR, (errcode(ERRCODE_OBJECT_NOT_IN_PREREQUISITE_STATE),
 						errmsg("you cannot sync metadata to a non-existent node"),
-						errhint("First, add the node with SELECT master_add_node(%s,%d)",
-								nodeNameString, nodePort)));
+						errhint(
```
Comment (byucesoy) [inline src/backend/distributed/metadata/metadata_sync.c]: Let's start error message in this line and continue from next line when character limit is reached such as;

```c
errhint("First, add the node with SELECT master_add_node "
        "(\'%s\',%d)", nodeNameString, nodePort)));
```

Separate texts in quotation marks are concatenated automatically.

File: src/backend/distributed/metadata/metadata_sync.c [hunk 2]
```diff
@@ -94,8 +94,9 @@ start_metadata_sync_to_node(PG_FUNCTION_ARGS)
...
+							"First, add the node with SELECT master_add_node(\'%s\',%d)",
```
Comment (byucesoy) [inline src/backend/distributed/metadata/metadata_sync.c]: Instead of manually wrapping %s with single quotation marks, you can use quote_literal_cstr function

File: src/backend/distributed/metadata/metadata_sync.c [hunk 3]
```diff
@@ -94,8 +94,9 @@ start_metadata_sync_to_node(PG_FUNCTION_ARGS)
 	{
 		ereport(ERROR, (errcode(ERRCODE_OBJECT_NOT_IN_PREREQUISITE_STATE),
 						errmsg("you cannot sync metadata to a non-existent node"),
-						errhint("First, add the node with SELECT master_add_node(%s,%d)",
-								nodeNameString, nodePort)));
+						errhint("First, add the node with SELECT master_add_node"
+								"(%s,%d)", quote_literal_cstr(nodeNameString),
```
Comment (byucesoy) [inline src/backend/distributed/metadata/metadata_sync.c]: Very minor but I think it is better if we assign result of the quote_literal_cstr to a variable

**Comment by byucesoy** [comment]
Looks good :ship:

Congratulations on your first contribution.
