### PR TITLE
Fix CreateShardConnectionHash memory leak

### LINKED ISSUE #767: Memory leak in shard connection hash
@jasonmp85 found this while doing #764 

In [CreateShardConnectionHash](https://github.com/citusdata/citus/blob/master/src/backend/distributed/transaction/multi_shard_transaction.c#L97) we pass the HASH_CONTEXT flag to hash_create, but we do not specify info.hcxt, which ends up creating a parentless memory context (like TopMemoryContext) and thus creates a session-level memory leak.

### PR DESCRIPTION
**Pull request by jasonmp85**
The call to `hash_create` specified `HASH_CONTEXT` without actually setting one using the provided `HASHCTL`. The hashes returned by this function are used locally, so simply using `CurrentMemoryContext` is sufficient.

Fixes #767

### CODE REVIEW

File: src/backend/distributed/transaction/multi_shard_transaction.c [hunk 1]
```diff
@@ -92,6 +92,7 @@ CreateShardConnectionHash(void)
 	info.keysize = sizeof(int64);
 	info.entrysize = sizeof(ShardConnections);
 	info.hash = tag_hash;
+	info.hcxt = CurrentMemoryContext;
```
Comment (anarazel) [inline src/backend/distributed/transaction/multi_shard_transaction.c]: I'd be more comfortable with using TopTransactionContext. Do you see any arguments against that?

Comment (jasonmp85) [inline src/backend/distributed/transaction/multi_shard_transaction.c]: Nope. So if I switch that is this a ship it?

--
*Jason Petersen*
Software Engineer | Citus Data
303.736.9255
jason@citusdata.com

On Sep 2, 2016, at 4:33 PM, Andres Freund <notifications@github.com> wrote:

I'd be more comfortable with using TopTransactionContext. Do you see any
arguments against that?

Comment (jasonmp85) [inline src/backend/distributed/transaction/multi_shard_transaction.c]: Updated. Ship?

Comment (jasonmp85) [inline src/backend/distributed/transaction/multi_shard_transaction.c]: Assuming yes, merging to unblock `5.1.1` release.
