### PR TITLE
Handle user-defined type parameters in EXPLAIN ANALYZE

### LINKED ISSUE #5788: EXPLAIN ANALYZE EXECUTE with a parameter of a custom type fails
EXPLAIN ANALYZE EXECUTE with a parameter of a custom type in a CTE fails.
```sql
create type foo as (x int, y int);
create table test (x int, y int, z foo);
select create_distributed_table('test','x');

PREPARE q1(foo) AS WITH a AS (SELECT * FROM test WHERE z = $1 AND x = 1 OFFSET 0) SELECT * FROM a;

-- fine, type can be inferred from query
EXECUTE q1('(1,2)');
NOTICE:  issuing SELECT x, y, z FROM (SELECT test.x, test.y, test.z FROM public.test_102010 test WHERE ((test.z OPERATOR(pg_catalog.=) $1::public.foo) AND (test.x OPERATOR(pg_catalog.=) 1)) OFFSET 0) a;

-- explain ANALYZE includes the parameter in the query string, but does not pass parameters to worker_save_query_explain_analyze
EXPLAIN ANALYZE EXECUTE q1('(1,2)');
NOTICE:  issuing SELECT * FROM worker_save_query_explain_analyze('SELECT x, y, z FROM (SELECT test.x, test.y, test.z FROM public.test_102010 test WHERE ((test.z OPERATOR(pg_catalog.=) $1::public.foo) AND (test.x OPERATOR(pg_catalog.=) 1)) OFFSET 0) a', '{"verbose": false, "costs": false, "buffers": false, "wal": false, "timing": false, "summary": false, "format": "TEXT"}') AS (field_0 integer, field_1 integer, field_2 foo)
ERROR:  could not determine data type of parameter $1
```

### PR DESCRIPTION
**Pull request by marcocitus**
DESCRIPTION: Fixes a bug that could cause EXPLAIN ANALYZE to fail for prepared statements with custom type

Fixes #5788 

When using explain analyze on a prepared statement and the executor does not evaluate the parametesrs on the coordinator, then we pass down parameters to the query that call `worker_save_query_explain_analyze`. Those parameters are not directly referenced by the query, but `worker_save_query_explain_analyze` digs them up via `ExecutorBoundParams()` . However, if one of the parameters is of a custom type, then we pass the type as `UNKNOWNOID` and expect postgres to infer from the query tree. The reason we do not pass the OID directly is that the OIDs might not be the same on other nodes. When an unknown parameter is not directly referenced, postgres throws `"could not determine data type of parameter $1"`. To address this issue, we now add an unused CTE that references all the parameters and adds explicit casts into the queries that call the UDFs.

That brings us to another issue within `worker_save_query_explain_analyze`, namely that it also does not know the type OID either, which triggers an `"there is no parameter $1"` error in `fixed_paramref_hook` somewhere deep in `pg_analyze_and_rewrite`. We therefore slightly altered the query rewriting logic in `worker_save_query_explain_analyze` to match `exec_parse_message`.

### CODE REVIEW

**Comment by tejeswarm** [comment]
Looks good to me, having a dummy CTE is a good idea, was thinking if such thing can be done in #5787 , whether used or unused just attach a dummy CTE with all the params, and the exec_parse_message() on the worker will not complain?

**Comment by tejeswarm** [comment]
Looks good to me, having a dummy CTE is a good idea, was thinking if such thing can be done in #5787 , whether used or unused just attach a dummy CTE with all the params, and the exec_parse_message() on the worker will not complain?

File: src/backend/distributed/planner/multi_explain.c [hunk 1]
```diff
@@ -1453,6 +1473,17 @@ WrapQueryForExplainAnalyze(const char *queryString, TupleDesc tupleDesc)
...
 	 */
 	char *workerSaveQueryFetchCols = (tupleDesc->natts == 0) ? "" : "*";
+
+	if (params != NULL)
+	{
+		/*
+		 * Add a dummy CTE to ensure all parameters are referenced, such that their
+		 * types can be resolved.
+		 */
+		appendStringInfo(wrappedQuery, "WITH unused AS (%s) ",
```
Comment (tejeswarm) [inline src/backend/distributed/planner/multi_explain.c:1483]: Just wondering, if we should push this part of the query too into the routine and have one routine (GenerateParamResDummyCTE()) that builds the dummy CTE from passed-params

Comment (tejeswarm) [inline src/backend/distributed/planner/multi_explain.c:1483]: Just wondering, if we should push this part of the query too into the routine and have one routine (GenerateParamResDummyCTE()) that builds the dummy CTE from passed-params

**Review by tejeswarm — APPROVED** [review]

**Review by tejeswarm — APPROVED** [review]

File: src/backend/distributed/planner/multi_explain.c (hunk 1 above)
Comment (marcocitus) [reply src/backend/distributed/planner/multi_explain.c:1483]: The fact that we can simply prepend a WITH clause here is quite specific to the fact that the query below does not have any CTE yet, so  I feel like there's not really a generic answer to GenerateParamResDummyCTE.
