### PR TITLE
Queries with only intermediate results do not rely on task assignment policy

### LINKED ISSUE #2594: Queries with only intermediate results error after when "round-robin" task-assignment policy set
Reported and analyzed by @marcocitus.

When a router query with only intermediate results are planned, the code-path that assigns the placement looks for a placement of the `shardId`. However, intermediate results doesn't have one.

Steps to repro:
```SQL
CREATE TABLE test (a int);
SELECT create_distributed_table('test', 'a');

WITH q1 AS (SELECT * FROM test) SELECT * FROM q1;
 a 
---
(0 rows)



SET citus.task_assignment_policy TO "round-robin";
WITH q1 AS (SELECT * FROM test) SELECT * FROM q1;
ERROR:  could not find valid entry for shard 0

```

Backtrace: 
```
#0  0x00007fbcbb90147a in LookupShardRelation (shardId=0, missingOk=missingOk@entry=false) at utils/metadata_cache.c:3457
#1  0x00007fbcbb9014e2 in LookupShardCacheEntry (shardId=<optimized out>, shardId@entry=0) at utils/metadata_cache.c:725
#2  0x00007fbcbb9017d2 in ShardPlacementList (shardId=0) at utils/metadata_cache.c:669
#3  0x00007fbcbb8cc316 in FinalizedShardPlacementList (shardId=<optimized out>) at master/master_metadata_utility.c:681
#4  0x00007fbcbb8df4d0 in ActiveShardPlacementLists (taskList=taskList@entry=0x7fb37a4fba78) at planner/multi_physical_planner.c:5208
#5  0x00007fbcbb8df568 in ReorderAndAssignTaskList (taskList=0x7fb37a4fba78, reorderFunction=reorderFunction@entry=0x7fbcbb8df6e0 <RoundRobinReorder>)
    at planner/multi_physical_planner.c:5121
#6  0x00007fbcbb8e17ec in RoundRobinAssignTaskList (taskList=<optimized out>) at planner/multi_physical_planner.c:5073
#7  0x00007fbcbb8e6693 in ReorderTaskPlacementsByTaskAssignmentPolicy (job=0x7fb37a4f9698, taskAssignmentPolicy=<optimized out>) at planner/multi_router_planner.c:1680
#8  RouterJob (originalQuery=originalQuery@entry=0x28de178, plannerRestrictionContext=plannerRestrictionContext@entry=0x2909828, planningError=planningError@entry=0x7fb37a4f5258)
    at planner/multi_router_planner.c:1643
#9  0x00007fbcbb8e68ff in CreateSingleTaskRouterPlan (plannerRestrictionContext=0x2909828, query=0x279dba0, originalQuery=0x28de178) at planner/multi_router_planner.c:264
#10 CreateRouterPlan (originalQuery=originalQuery@entry=0x28de178, query=query@entry=0x279dba0, plannerRestrictionContext=plannerRestrictionContext@entry=0x2909828)
    at planner/multi_router_planner.c:174
#11 0x00007fbcbb8d46ce in CreateDistributedPlan (planId=planId@entry=1, originalQuery=originalQuery@entry=0x28de178, query=query@entry=0x279dba0, 
    boundParams=boundParams@entry=0x0, hasUnresolvedParams=hasUnresolvedParams@entry=false, plannerRestrictionContext=plannerRestrictionContext@entry=0x2909828)
    at planner/distributed_planner.c:636
#12 0x00007fbcbb8d469c in CreateDistributedPlan (planId=planId@entry=1, originalQuery=originalQuery@entry=0x28de178, query=query@entry=0x279dba0, 
    boundParams=boundParams@entry=0x0, hasUnresolvedParams=hasUnresolvedParams@entry=false, plannerRestrictionContext=0x2909828, plannerRestrictionContext@entry=0x29097a0)
    at planner/distributed_planner.c:732
#13 0x00007fbcbb8d4a38 in CreateDistributedPlannedStmt (plannerRestrictionContext=0x29097a0, boundParams=0x0, query=0x279dba0, originalQuery=0x28de178, localPlan=0x7fbcb9f38478, 
    planId=1) at planner/distributed_planner.c:498
#14 distributed_planner (parse=0x279dba0, cursorOptions=256, boundParams=0x0) at planner/distributed_planner.c:158
#15 0x0000000000730c8d in pg_plan_query (querytree=querytree@entry=0x279dba0, cursorOptions=cursorOptions@entry=256, boundParams=boundParams@entry=0x0) at postgres.c:832
#16 0x0000000000730d66 in pg_plan_queries (querytrees=querytrees@entry=0x279db50, cursorOptions=256, boundParams=boundParams@entry=0x0) at postgres.c:898
#17 0x0000000000825a9f in BuildCachedPlan (plansource=plansource@entry=0x28063e0, qlist=0x279db50, qlist@entry=0x0, boundParams=boundParams@entry=0x0, 
    queryEnv=queryEnv@entry=0x0) at plancache.c:938
#18 0x0000000000825d53 in GetCachedPlan (plansource=plansource@entry=0x28063e0, boundParams=boundParams@entry=0x0, useResOwner=useResOwner@entry=false, 
    queryEnv=queryEnv@entry=0x0) at plancache.c:1168
#19 0x0000000000732826 in exec_bind_message (input_message=0x7ffd59f1fc30) at postgres.c:1822
#20 PostgresMain (argc=<optimized out>, argv=argv@entry=0x280c9b8, dbname=<optimized out>, username=<optimized out>) at postgres.c:4228
#21 0x00000000006c6b7a in BackendRun (port=0x2804870) at postmaster.c:4361
#22 BackendStartup (port=0x2804870) at postmaster.c:4033
#23 ServerLoop () at postmaster.c:1706
#24 0x00000000006c7a96 in PostmasterMain (argc=argc@entry=3, argv=argv@entry=0x2798250) at postmaster.c:1379
#25 0x000000000048414a in main (argc=3, argv=0x2798250) at main.c:228
```

### PR DESCRIPTION
**Pull request by onderkalaci**
Fixes #2594 

Previously we allowed task assignment policy to have affect on router queries
with only intermediate results. However, that is erroneous since the code-path
that assigns placements relies on shardIds and placements, which doesn't exists
for intermediate results.

With this commit, we do not apply task assignment policies when a router query
hits only intermediate results.

DESCRIPTION: Queries with only intermediate results do not rely on task assignment policy

### CODE REVIEW

File: src/backend/distributed/planner/multi_router_planner.c [hunk 1]
```diff
@@ -1630,10 +1630,24 @@ RouterJob(Query *originalQuery, PlannerRestrictionContext *plannerRestrictionCon
...
+		 * valid anchorShardId).
 		 */
-		ReorderTaskPlacementsByTaskAssignmentPolicy(job, TaskAssignmentPolicy);
+		if (shardId != INVALID_SHARD_ID)
+		{
+			ReorderTaskPlacementsByTaskAssignmentPolicy(job, TaskAssignmentPolicy);
+		}
+		else if (shardId == INVALID_SHARD_ID &&
+				 TaskAssignmentPolicy == TASK_ASSIGNMENT_ROUND_ROBIN)
+		{
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_router_planner.c]: My intention was to have an assert with `DeferErrorIfFromClauseRecurs()` or such. But the whole recurring tuple logic is locally defined in `query_pushdown.c`. And, I don't want to make things public just for this.

Comment (marcocitus) [reply src/backend/distributed/planner/multi_router_planner.c]: Maybe just omit the `else if` then. We're not really checking anything.

Comment (onderkalaci) [reply src/backend/distributed/planner/multi_router_planner.c]: Yes, it seems confusing to me as well.

File: src/test/regress/expected/multi_task_assignment_policy.out [hunk 2]
```diff
@@ -211,4 +211,21 @@ DEBUG:  Plan is router executable
...
 (2 rows)
 
+-- we should be able to use round-robin with router queries that 
+-- only contains intermediate results
+SET LOCAL citus.task_assignment_policy TO 'round-robin';
+EXPLAIN (COSTS FALSE) WITH q1 AS (SELECT * FROM task_assignment_test_table) SELECT * FROM q1;
+DEBUG:  generating subplan 14_1 for CTE q1: SELECT test_id FROM public.task_assignment_test_table
+DEBUG:  assigned task 3 to node localhost:57637
+DEBUG:  assigned task 2 to node localhost:57637
+DEBUG:  assigned task 1 to node localhost:57638
```
Comment (marcocitus) [inline src/test/regress/expected/multi_task_assignment_policy.out]: is this going to be consistent if we make changes?

Comment (onderkalaci) [reply src/test/regress/expected/multi_task_assignment_policy.out]: I think so because the table is append distributed and the metadata is manually added.

**Comment by onderkalaci** [comment]
PG 11 is failing because of https://github.com/citusdata/citus/issues/2592. FYI: @mtuncer is looking into fixing that.

File: src/test/regress/expected/multi_task_assignment_policy.out (hunk 2 above)
Comment (marcocitus) [reply src/test/regress/expected/multi_task_assignment_policy.out]: It seems nicer to just have a regular query somewhere.

**Comment by onderkalaci** [comment]
> Consider changing the test to a regular query without debug output. Otherwise looks good.

The problem is that the placements do not exists, they are only in the metadata :)  So, shall I turn off debug messages and keep `EXPLAIN`, or use another table?

**Comment by marcocitus** [comment]
Regular query on another table. We don't care much about the other assignments for this particular case.
