### PR TITLE
Fixes a bug that causes crash when using auto_explain extension with ALTER TABLE...ADD FOREIGN KEY... queries.

### LINKED ISSUE #6424: Crash when using Citus with auto_explain configured.
Running regression tests with auto_explain configured results in crash with the bt below.

Reproduction Steps:

1. Configure auto_explain in your local test directory by editing pg_regress_multi.pl.

```
git diff pg_regress_multi.pl
diff --git a/src/test/regress/pg_regress_multi.pl b/src/test/regress/pg_regress_multi.pl
  ....
+$sharedPreloadLibraries .= ',auto_explain';
+
+push(@pgOptions, "auto_explain.log_min_duration = 0");
+push(@pgOptions, "auto_explain.log_level = DEBUG5");
+
.....
```
    
2. Run the regression test
` make check-minimal EXTRA_TESTS='multi_create_table_constraints'`
   
3. See that two core files are created.  Possibly the 2 workers crashed as a result of running this test.

```
Core was generated by `postgres: postgres regression 127.0.0.1(47524) COMMIT PREPARED                '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007ff35187d201 in HasModificationFailedForShard (shardEntry=shardEntry@entry=0x558b46688280) at connection/placement_connection.c:1039
1039                    if (!connection || connection->remoteTransaction.transactionFailed)
(gdb) bt
#0  0x00007ff35187d201 in HasModificationFailedForShard (shardEntry=shardEntry@entry=0x558b46688280) at connection/placement_connection.c:1039
#1  0x00007ff35187df51 in ErrorIfPostCommitFailedShardPlacements () at connection/placement_connection.c:1001
#2  0x00007ff351924bc4 in CoordinatedTransactionCallback (event=<optimized out>, arg=<optimized out>) at transaction/transaction_management.c:509
#3  0x0000558b445bcfdd in CallXactCallbacks (event=XACT_EVENT_PRE_COMMIT) at xact.c:3587
#4  0x0000558b445c12fa in CommitTransaction () at xact.c:2127
#5  0x0000558b445c2180 in CommitTransactionCommand () at xact.c:2986
#6  0x0000558b448dd21d in finish_xact_command () at postgres.c:2721
#7  0x0000558b448dfbad in exec_simple_query (query_string=query_string@entry=0x558b4661d140 "COMMIT PREPARED 'citus_0_773_90_13'") at postgres.c:1239
#8  0x0000558b448e1f40 in PostgresMain (argc=argc@entry=1, argv=argv@entry=0x7fffbe3c9f70, dbname=<optimized out>, username=<optimized out>) at postgres.c:4496
#9  0x0000558b44839e5a in BackendRun (port=port@entry=0x558b466beab0) at postmaster.c:4530
#10 0x0000558b4483d218 in BackendStartup (port=port@entry=0x558b466beab0) at postmaster.c:4252
#11 0x0000558b4483d461 in ServerLoop () at postmaster.c:1745
#12 0x0000558b4483e9bd in PostmasterMain (argc=<optimized out>, argv=<optimized out>) at postmaster.c:1417
#13 0x0000558b4477b012 in main (argc=5, argv=0x558b46615ee0) at main.c:209
(gdb) set print pretty
(gdb) list
1034                            continue;
1035                    }
1036
1037                    MultiConnection *connection = primaryConnection->connection;
1038
1039                    if (!connection || connection->remoteTransaction.transactionFailed)
1040                    {
1041                            return true;
1042                    }
1043            }
(gdb) p primaryConnection
$1 = (ConnectionReference *) 0x558b46870750
(gdb) p *primaryConnection
$2 = {
  userName = 0x7f7f7f7f7f7f7f7f <error: Cannot access memory at address 0x7f7f7f7f7f7f7f7f>,
  connection = 0x7f7f7f7f7f7f7f7f,
  hadDML = 127,
  hadDDL = 127,
  colocationGroupId = 2139062143,
  representativeValue = 2139062143,
  placementId = 9187201950435737471,
  connectionNode = {
    prev = 0x7f7f7f7f7f7f7f7f,
    next = 0x7f7f7f7f7f7f7f7f
  }
}
(gdb)
```

### PR DESCRIPTION
**Pull request by emelsimsek**
Fixes a bug that causes crash when using auto_explain extension with ALTER TABLE...ADD FOREIGN KEY... queries.
Those queries trigger a SELECT query on the citus tables as part of the foreign key constraint validation check. At the explain hook, workers try to explain this SELECT query as a distributed query causing memory corruption in the connection data structures. Hence, we will not explain ALTER TABLE...ADD FOREIGN KEY... and the triggered queries on the workers.

Fixes #6424.

### CODE REVIEW

**Comment by emelsimsek** [comment]
> 

@microsoft-github-policy-service agree [company="Microsoft Corp."]

**Comment by emelsimsek** [comment]
@microsoft-github-policy-service agree

**Comment by emelsimsek** [comment]
@microsoft-github-policy-service agree

**Comment by emelsimsek** [comment]
@microsoft-github-policy-service agree company="microsoft"

File: src/backend/distributed/planner/multi_explain.c [hunk 1]
```diff
@@ -199,6 +201,20 @@ CitusExplainScan(CustomScanState *node, List *ancestors, struct ExplainState *es
...
+	{
+		/*
+		 * We do not want to explain ALTER TABLE ... ADD FOREIGN KEY .. queries in
+		 * in the workers. They trigger a SELECT query on the citus tables as part of the
+		 * constraint validation check. Explaining the distributed SELECT query in the
+		 * workers cause memory corruption resulting in a crash later on.
+		 */
+		appendStringInfoSpaces(es->str, es->indent * 2);
+		appendStringInfo(es->str, "explain statements for distributed queries ");
+		appendStringInfo(es->str, "triggered via DDL commands are only supported on the coordinator \n");
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_explain.c:214]: I wonder we should at least add a single test:
```SQL
LOAD 'auto_explain';
SET auto_explain.log_min_duration = 0;
SET auto_explain.log_level = LOG;
SET client_min_messages to LOG;
SET auto_explain.log_timing TO off;

BEGIN;
   -- simulate being a worker session/backend
	SET LOCAL application_name to 'citus_internal gpid=10000000001';
	SET citus.enable_ddl_propagation TO OFF;
    -- alter table triggers SELECT, and auto_explain catches that
	ALTER TABLE target_table ADD CONSTRAINT fkey_167 FOREIGN KEY (col_1) REFERENCES test_ref_table(key) ON DELETE CASCADE;
	LOG:  duration: 0.008 ms  plan:
Query Text: SELECT fk."col_1" FROM ONLY "public"."target_table" fk LEFT OUTER JOIN ONLY "public"."test_ref_table" pk ON ( pk."key" OPERATOR(pg_catalog.=) fk."col_1") WHERE pk."key" IS NULL AND (fk."col_1" IS NOT NULL)
Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=100000 width=4) (never executed)
  explain statements for distributed queries triggered via DDL commands are only supported on the coordinator 
ALTER TABLE
```

But, we should find a way to make the test outputs consistent, because we somehow have `LOG:  **duration: 0.008** ms  plan:` in the output, which would change across executions.

**Comment by emelsimsek** [comment]
@microsoft-github-policy-service agree company="microsoft"

File: src/backend/distributed/planner/multi_explain.c [hunk 2]
```diff
@@ -199,6 +201,21 @@ CitusExplainScan(CustomScanState *node, List *ancestors, struct ExplainState *es
 		return;
 	}
 
+	if (SkipConstraintValidation || (AlterTableInProgress() && IsCitusInternalBackend()))
```
Comment (CyberDem0n) [inline src/backend/distributed/planner/multi_explain.c:204]: AFAIK, constraints could be created/validated only by using ALTER TABLE.
Do we need to have a `SkipConstraintValidation` check here? It looks redundant. Also it probably might produce unwanted side effects like explain not working correctly for normal queries when `citus.skip_constraint_validation` GUC is set.

Comment (onderkalaci) [reply src/backend/distributed/planner/multi_explain.c:204]: You are right, `SkipConstraintValidation` seems wrong (which I suggested to Emel).

 I think we don't even need `IsCitusInternalBackend`, we can just leave `AlterTableInProgress`. Because, even on the coordinator, the EXPLAIN is just useless as we skip the constraint checks anyway.

What do you think?

File: src/backend/distributed/planner/multi_explain.c [hunk 3]
```diff
@@ -199,6 +201,20 @@ CitusExplainScan(CustomScanState *node, List *ancestors, struct ExplainState *es
...
+	{
+		/*
+		 * We do not want to explain ALTER TABLE ... ADD FOREIGN KEY .. queries in
+		 * in the workers. They trigger a SELECT query on the citus tables as part of the
```
[the remark this answers is not in the document]
Comment (emelsimsek) [reply src/backend/distributed/planner/multi_explain.c:208]: I was actually going to propose 

   if (AlterTableInProgress() && SkipConstraintValidation)

instead. 

 My reasoning goes like this:

    if (AlterTableInProgress() && SkipConstraintValidation) 
           -  will never explain the validation steps for shell tables since SkipConstraintValidation is always set by citus for them.
           - will explain the validation on shards if the validation is not skipped explicitly by the client.

I believe this condition best captures the intention assuming the validation on shards do not cause distributed transaction unlike validation on citus (shell) tables.

[the remark this answers is not in the document]
Comment (onderkalaci) [reply src/backend/distributed/planner/multi_explain.c:208]: > - will never explain the validation steps for shell tables since SkipConstraintValidation is always set by citus for them.

Is this accurate? Do we always send it to workers AND set it on the coordinator? Maybe true, but as far as I can see we don't send it to workers for all operations, we only send it for certain code-paths in the rebalancer ?

File: src/backend/distributed/planner/multi_explain.c (hunk 1 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/multi_explain.c]: friendly reminder: I think it'd be much better to have at least one test covering this case, the above is an example/suggestion, but anything is welcome

File: src/backend/distributed/planner/multi_explain.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (emelsimsek) [reply src/backend/distributed/planner/multi_explain.c:208]: As for my debugging:

    On a worker process: 
         SkipConstraintValidation is always set on implicitly by the EnableSkippingConstraintValidation function for the citus/distributed/shell tables. Hence it is always true for 

 ` SELECT fk.\"col_1\" FROM ONLY \"public\".\"target_table\" fk LEFT OUTER JOIN ONLY \"public\".\"test_ref_table\" pk ON ( pk.\"key\" OPERATOR(pg_catalog.=) fk.\"col_1\") WHERE pk.\"key\" IS NULL AND (fk.\"col_1\" IS NOT 
    `
     queries.

         SkipConstraintValidation is not overriden for the shard tables. Hence it could be true or false. Those queries are not distributed and do not get explained by CitusExplainScan (I was wrong mentioning enabling those in CitusExplainScan above)

     In CitusExplainScan, we are trying to mimic AlterTableConstraintCheck which  seems to be the function for deciding if a statement is a constraint check or not. 

   Now my question is :

   Since we cannot exactly express AlterTableConstraintCheck  within CitusExplainScan, can we choose to skip all ALTER TABLE statements with the following condition check?
 
  if (AlterTableInProgress())

File: src/backend/distributed/planner/multi_explain.c (hunk 1 above)
Comment (emelsimsek) [reply src/backend/distributed/planner/multi_explain.c]: It looks like we can normalize the variable data in the output.

File: src/backend/distributed/planner/multi_explain.c [hunk 4]
```diff
@@ -199,6 +200,17 @@ CitusExplainScan(CustomScanState *node, List *ancestors, struct ExplainState *es
 		return;
 	}
 
+	if (AlterTableInProgress())
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_explain.c:203]: I think this definitely deserves a comment. When this happens? Why cannot we support it?

File: src/backend/distributed/planner/multi_explain.c [hunk 5]
```diff
@@ -199,6 +200,17 @@ CitusExplainScan(CustomScanState *node, List *ancestors, struct ExplainState *es
...
+	{
+		/*
+		 * EXPLAIN for ALTER TABLE commands are not supported.
+		 */
+		ExplainPropertyText("Citus Explain Scan",
+							"Explain for ALTER TABLE commands are not supported",
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_explain.c:209]: minor: EXPLAIN for ALTER table is not supported Postgres anyway. 

Maybe change the message to something like:

Explain for constraint validation queries during ALTER TABLE commands are not supported by Citus

**Review by onderkalaci — COMMENTED** [review]
I think the change looks good, mostly minor style comments

**Review by onderkalaci — APPROVED** [review]
