### PR TITLE
PG18: Fix multi-shard MIN/MAX on composite types by blessing record aggregates

### LINKED ISSUE #8400: Allow MIN()/MAX() aggregates on arrays and composite types
https://github.com/postgres/postgres/commit/a0f1fce80c0373c16b22a1bdc9b0b61958fc9b6a

https://github.com/postgres/postgres/commit/2d24fd942c7010247c5b7b54b416acf7f4592a4e

### PR DESCRIPTION
**Pull request by m3hm3t**
DESCRIPTION: Fix multi-shard MIN/MAX on composite types by blessing record aggregates

fixes #8400 https://github.com/citusdata/citus/issues/8400#issuecomment-3681663914

PG18 adds `MIN/MAX` support for composite values.

https://github.com/postgres/postgres/commit/a0f1fce80c0373c16b22a1bdc9b0b61958fc9b6a

On Citus distributed tables, multi-shard execution computes `MIN/MAX` per shard on workers and then re-aggregates those shard results on the coordinator. The shard results arrive as `record` without a concrete record typmod/tuple descriptor, so the coordinator cannot parse/compare them and fails with:

`ERROR: input of anonymous composite types is not implemented`

### Solution

Extend `BlessRecordExpression()` to handle `Aggref` nodes that return `RECORDOID`. For `min/max` over a composite column, derive the tuple descriptor from the aggregate’s input argument rowtype, convert it to a `record` tupledesc, and call `BlessTupleDesc()` so Postgres assigns a non-anonymous record typmod. This preserves enough metadata across the worker→coordinator boundary for the coordinator-stage aggregate to work.

### Tests

Add a PG18 regression case that creates a distributed table with a composite type and verifies distributed `MIN/MAX` returns the expected composite values instead of raising the anonymous composite error.

### CODE REVIEW

File: src/backend/distributed/planner/distributed_planner.c [hunk 1]
```diff
@@ -1767,6 +1768,36 @@ BlessRecordExpression(Expr *expr)
...
+
+		if (aggref->aggtype == RECORDOID && list_length(aggref->args) > 0)
+		{
+			TargetEntry *argTle = (TargetEntry *) linitial(aggref->args);
+			Oid argTypeId = exprType((Node *) argTle->expr);
+			int32 argTypeMod = exprTypmod((Node *) argTle->expr);
+
+			if (argTypeId == RECORDOID)
+			{
+				argTypeMod = BlessRecordExpression((Expr *) argTle->expr);
```
Comment (colm-mchugh) [inline src/backend/distributed/planner/distributed_planner.c:1800]: Can a test case be added for this codepath ? Where argTypeId is a `RECORDOID`.

Comment (colm-mchugh) [reply src/backend/distributed/planner/distributed_planner.c:1800]: Curious how this codepath is taken, given that aggregates must be applied to a concrete type.

File: src/backend/distributed/planner/distributed_planner.c [hunk 2]
```diff
@@ -1767,6 +1768,36 @@ BlessRecordExpression(Expr *expr)
...
+			{
+				TupleDesc argTupleDesc =
+					lookup_rowtype_tupdesc_copy(argTypeId, argTypeMod);
+
+				argTupleDesc->tdtypeid = RECORDOID;
+				argTupleDesc->tdtypmod = -1;
+				BlessTupleDesc(argTupleDesc);
+				typeMod = argTupleDesc->tdtypmod;
+			}
+		}
```
Comment (colm-mchugh) [inline src/backend/distributed/planner/distributed_planner.c:1820]: How about aggregates with more than one argument ? Probably in the realm of custom aggregates if so.

File: src/backend/distributed/planner/distributed_planner.c [hunk 3]
```diff
@@ -1767,6 +1768,36 @@ BlessRecordExpression(Expr *expr)
...
+			if (type_is_rowtype(argTypeId))
+			{
+				TupleDesc argTupleDesc =
+					lookup_rowtype_tupdesc_copy(argTypeId, argTypeMod);
+
+				argTupleDesc->tdtypeid = RECORDOID;
+				argTupleDesc->tdtypmod = -1;
+				BlessTupleDesc(argTupleDesc);
+				typeMod = argTupleDesc->tdtypmod;
+			}
```
Comment (colm-mchugh) [inline src/backend/distributed/planner/distributed_planner.c:1813]: Need to handle if the argument is not of a type derived from or related to a Row ?

File: src/backend/distributed/planner/distributed_planner.c (hunk 1 above)
Comment (m3hm3t) [reply src/backend/distributed/planner/distributed_planner.c:1800]: This codepath is reachable during planning when Citus constructs the combine query (remote_scan) for non-router/multi-shard plans. The call stack is:

`PlanCombineQuery() → RemoteScanTargetList() → BlessRecordExpression()`

We hit the `Aggref` branch because worker tasks can return aggregate outputs typed as `RECORD`

File: src/backend/distributed/planner/distributed_planner.c (hunk 3 above)
Comment (m3hm3t) [reply src/backend/distributed/planner/distributed_planner.c:1813]: I suppose that an aggregate will only match with declaredArgType == RECORDOID if the input is already a rowtype. Because according to AGG_MATCH_RECORD logic ( https://github.com/citusdata/citus/blob/afdc45891a831eaf0ddadeb9de9c022fc59bc7d9/src/backend/distributed/planner/multi_logical_optimizer.c#L3652 ), an aggregate will only have `aggtype == RECORDOID` if its input type is a rowtype.


But I can add a comment about that. Or more defensively I can add assertion to check row type.

File: src/backend/distributed/planner/distributed_planner.c (hunk 2 above)
Comment (m3hm3t) [reply src/backend/distributed/planner/distributed_planner.c:1820]: Since MIN and MAX only accept a single argument, handling multiple arguments isn't required for the PG18 MIN/MAX feature.

However, I can take the following actions:

1. Add comments to clarify the current limitation
2. Include a defensive assertion/check for clarity
3. Open a separate issue to track multi-argument aggregate support as a future enhancement outside the scope of this PG18 work.


What do you think on these steps?

File: src/backend/distributed/planner/distributed_planner.c (hunk 1 above)
Comment (m3hm3t) [reply src/backend/distributed/planner/distributed_planner.c:1800]: New test scenario is added.

File: src/backend/distributed/planner/distributed_planner.c (hunk 2 above)
Comment (colm-mchugh) [reply src/backend/distributed/planner/distributed_planner.c:1820]: 1 and 2 sound good. I don't think there's a need for 3. Thanks!

File: src/backend/distributed/planner/distributed_planner.c (hunk 3 above)
Comment (colm-mchugh) [reply src/backend/distributed/planner/distributed_planner.c:1813]: Let's add a comment at least. If we should only be here on `AGG_MATCH_RECORD` and assert would also help.

File: src/backend/distributed/planner/distributed_planner.c (hunk 2 above)
Comment (m3hm3t) [reply src/backend/distributed/planner/distributed_planner.c:1820]: 1 and 2 added

File: src/backend/distributed/planner/distributed_planner.c (hunk 3 above)
Comment (m3hm3t) [reply src/backend/distributed/planner/distributed_planner.c:1813]: comment added
