### PR TITLE
Fix memory corruptions that could happen when a Citus downgrade is followed by an upgrade

### LINKED ISSUE #7933: multi_extension fails on ubuntu 22.04 arm version
multi_extension fails on ubuntu 22.04 arm64 version running on a UTM virtual machine on MacOS (M1):

Here is the steps to reproduce the issue: 
- clone postgresql source code, configure, make and make install using REL_16_STABLE branch. 
- clone citus source code, configure, make and "make install-all" using main branch. 
- cd src/test/regress
- run: pipenv run citus_tests/run_test.py multi_extension --use-base-schedule --use-whole-schedule-line

The test fails with following output: 

```
waiting for server to start.... done
server started
waiting for server to start.... done
server started
waiting for server to start.... done
server started
CREATE DATABASE
CREATE EXTENSION
CREATE FUNCTION
CREATE FOREIGN DATA WRAPPER
CREATE DATABASE
CREATE EXTENSION
CREATE FUNCTION
CREATE FOREIGN DATA WRAPPER
# using postmaster on localhost, port 57636
not ok 1     - multi_extension                          1052 ms
# (test process exited with exit code 2)
1..1
# 1 of 1 tests failed.
# The differences that caused some tests to fail can be viewed in the file "/home/alperkocatas/citus/src/test/regress/regression.diffs".
# A copy of the test summary that you see above is saved in the file "/home/alperkocatas/citus/src/test/regress/regression.out".
waiting for server to shut down.... done
server stopped
waiting for server to shut down.... done
server stopped
waiting for server to shut down.... done
server stopped
Failed in 2 seconds. 
```

Last lines from `regression.diffs`:

```
-RESET citus.enable_schema_based_sharding;
-DROP EXTENSION citus;
-CREATE EXTENSION citus;
-DROP TABLE version_mismatch_table;
-DROP TABLE  multi_extension.extension_basic_types;
-DROP SCHEMA multi_extension;
-ERROR:  cannot drop schema multi_extension because other objects depend on it
-DETAIL:  function multi_extension.print_extension_changes() depends on schema multi_extension
-HINT:  Use DROP ... CASCADE to drop the dependent objects too.
+SSL SYSCALL error: EOF detected
+connection to server was lost
```

Apparently, the server crashes during the test. If we inspect the stack trace using the produced code-dump, we get the following: 

```
libc.so.6!__pthread_kill_implementation(pthread_t threadid, int signo, int no_tid) (pthread_kill.c:44)
libc.so.6!__pthread_kill_internal(int signo, pthread_t threadid) (pthread_kill.c:78)
libc.so.6!__GI_raise(int sig) (raise.c:26)
libc.so.6!__GI_abort() (abort.c:79)
libc.so.6!__libc_message(enum __libc_message_action action, const char * fmt) (libc_fatal.c:156)
libc.so.6!__GI___fortify_fail(const char * msg) (fortify_fail.c:26)
libc.so.6!__stack_chk_fail() (stack_chk_fail.c:24)
citus.so!BuildCitusTableCacheEntry (Unknown Source:0)
citus.so!LookupCitusTableCacheEntry (Unknown Source:0)
citus.so!GetCitusTableCacheEntry (Unknown Source:0)
citus.so!InitializeTableCacheEntry (Unknown Source:0)
citus.so!LookupShardIdCacheEntry (Unknown Source:0)
citus.so!ShardPlacementList (Unknown Source:0)
citus.so!CreateSingleShardTableShardWithRoundRobinPolicy (Unknown Source:0)
citus.so!CreateSingleShardTableShard (Unknown Source:0)
citus.so!CreateCitusTable (Unknown Source:0)
citus.so!CreateSingleShardTable (Unknown Source:0)
citus.so!create_distributed_table (Unknown Source:0)
ExecInterpExpr (Unknown Source:0)
ExecInterpExprStillValid (Unknown Source:0)
```

Note: the same test can also fail sometimes on ubuntu x86 version - wsl running on windows. However, the test failure is not as consistent in the arm case. The stack trace is also slightly different in that case:

```
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140561101195072) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140561101195072) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140561101195072, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007fd6f06f6476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007fd6f06dc7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00005600a29daebe in ExceptionalCondition ()
#6  0x00007fd6ee728de5 in MaintenanceDaemonShmemExit () from /home/alperkocatas/oss-postgres-bin/16/lib/citus.so
#7  0x00005600a28503a4 in shmem_exit ()
#8  0x00005600a28504a9 in proc_exit_prepare ()
#9  0x00005600a285054b in proc_exit ()
#10 0x00007fd6ee72a290 in CitusMaintenanceDaemonMain () from /home/alperkocatas/oss-postgres-bin/16/lib/citus.so
#11 0x00005600a27d11a6 in StartBackgroundWorker ()
#12 0x00005600a27d7c4b in do_start_bgworker ()
#13 0x00005600a27d7dc5 in maybe_start_bgworkers ()
#14 0x00005600a27d86f0 in process_pm_pmsignal ()
#15 0x00005600a27d8c9b in ServerLoop ()
#16 0x00005600a27da23c in PostmasterMain ()
#17 0x00005600a26f10b5 in main ()
```

### PR DESCRIPTION
**Pull request by manaldush**
DESCRIPTION: Fixes potential memory corruptions that could happen when a Citus downgrade is followed by a Citus upgrade.

In case of citus downgrade and further upgrade citus crash with core dump.
The reason is that citus hardcoded number of columns in pg_dist_partition table,
but in case of downgrade and following update table can have more columns, and
some of then can be marked as dropped.

Patch suggest decision for this problem with using tupleDescriptor->nattrs(postgres internal approach).

Fixes #7933.

### CODE REVIEW

**Comment by manaldush** [comment]
@microsoft-github-policy-service agree

**Comment by onurctirtir** [comment]
@alperkocatas, could you test this on your Mac once you have some time for it?

File: src/backend/distributed/metadata/metadata_utility.c [hunk 1]
```diff
@@ -2231,11 +2236,10 @@ UpdatePgDistPartitionAutoConverted(Oid citusTableId, bool autoConverted)
 							   citusTableId)));
 	}
 
-	memset(replace, 0, sizeof(replace));
-
-	values[Anum_pg_dist_partition_autoconverted - 1] = BoolGetDatum(autoConverted);
-	isnull[Anum_pg_dist_partition_autoconverted - 1] = false;
-	replace[Anum_pg_dist_partition_autoconverted - 1] = true;
+	autoconvertedindex = GetAutoConvertedAttrIndexInPgDistPartition(tupleDescriptor);
```
Comment (onurctirtir) [inline src/backend/distributed/metadata/metadata_utility.c:2239]: nit - let's declare this right away here

```suggestion
	int autoconvertedindex = GetAutoConvertedAttrIndexInPgDistPartition(tupleDescriptor);
```

File: src/backend/distributed/metadata/metadata_utility.c [hunk 2]
```diff
@@ -2317,9 +2325,10 @@ UpdateDistributionColumn(Oid relationId, char distributionMethod, Var *distribut
 	values[Anum_pg_dist_partition_colocationid - 1] = UInt32GetDatum(colocationId);
 	isnull[Anum_pg_dist_partition_colocationid - 1] = false;
 
-	replace[Anum_pg_dist_partition_autoconverted - 1] = true;
-	values[Anum_pg_dist_partition_autoconverted - 1] = BoolGetDatum(false);
-	isnull[Anum_pg_dist_partition_autoconverted - 1] = false;
+	autoconvertedindex = GetAutoConvertedAttrIndexInPgDistPartition(tupleDescriptor);
```
Comment (onurctirtir) [inline src/backend/distributed/metadata/metadata_utility.c:2328]: same here

```suggestion
	int autoconvertedindex = GetAutoConvertedAttrIndexInPgDistPartition(tupleDescriptor);
```

File: src/backend/distributed/metadata/metadata_utility.c [hunk 3]
```diff
@@ -2411,9 +2424,10 @@ UpdateNoneDistTableMetadata(Oid relationId, char replicationModel, uint32 coloca
 	isnull[Anum_pg_dist_partition_repmodel - 1] = false;
 	replace[Anum_pg_dist_partition_repmodel - 1] = true;
 
-	values[Anum_pg_dist_partition_autoconverted - 1] = BoolGetDatum(autoConverted);
-	isnull[Anum_pg_dist_partition_autoconverted - 1] = false;
-	replace[Anum_pg_dist_partition_autoconverted - 1] = true;
+	autoconvertedindex = GetAutoConvertedAttrIndexInPgDistPartition(tupleDescriptor);
```
Comment (onurctirtir) [inline src/backend/distributed/metadata/metadata_utility.c:2427]: same here

```suggestion
	int autoconvertedindex = GetAutoConvertedAttrIndexInPgDistPartition(tupleDescriptor);
```

File: src/backend/distributed/metadata/metadata_utility.c [hunk 4]
```diff
@@ -4419,3 +4437,17 @@ UnblockDependingBackgroundTasks(BackgroundTask *task)
 
 	table_close(pgDistBackgroundTasksDepend, NoLock);
 }
+
+/*
+ * AutoConverted attr was added to table pg_dist_partition using alter operation, so
+ * in case of downgrade we can get additional tuple field in tuple desc with dropped flag
+ * and in case of futher upgrade we can get number of fields > Natts_pg_dist_partition.
+ * So we should properly address AutoConverted attr in arrays.
+ */
```
Comment (onurctirtir) [inline src/backend/distributed/metadata/metadata_utility.c:4446]: We usually start function comments with the name of the function, also proposing slight improvements for the comment:

```suggestion
/*
 * GetAutoConvertedAttrIndexInPgDistPartition returns attrnum for autoconverted attr.
 *
 * autoconverted attr was added to table pg_dist_partition using alter operation after
 * the version where Citus started supporting downgrades, and it's only column that we've
 * introduced to pg_dist_partition since then.
 *
 * And in case of a downgrade + upgrade, tupleDEsc->natts becomes greater than
 * Natts_pg_dist_partition and when this happens, then we know that attrnum autoconverted is
 * not Anum_pg_dist_partition_autoconverted anymore but tupleDEsc->natts - 1.
 */
```

File: src/backend/distributed/utils/colocation_utils.c [hunk 5]
```diff
@@ -1000,14 +1001,16 @@ ColocationGroupTableList(uint32 colocationId, uint32 count)
 	HeapTuple heapTuple = systable_getnext(scanDescriptor);
 	while (HeapTupleIsValid(heapTuple))
 	{
-		bool isNullArray[Natts_pg_dist_partition];
-		Datum datumArray[Natts_pg_dist_partition];
+		Datum* datumArray = (Datum *) palloc(tupleDescriptor->natts * sizeof(Datum));
```
Comment (onurctirtir) [inline src/backend/distributed/utils/colocation_utils.c:1004]: I'd allocate these outside & right before of the loop to avoid excessive amount of palloc calls.

File: src/backend/distributed/utils/colocation_utils.c [hunk 6]
```diff
@@ -1194,8 +1197,8 @@ ColocatedTableId(int32 colocationId)
...
```
Comment (onurctirtir) [inline src/backend/distributed/utils/colocation_utils.c:1200]: I'd allocate these outside & right before of the loop to avoid excessive amount of palloc calls.

**Review by onurctirtir — COMMENTED** [review]
@naisila / @thanodnl

Do you think could this introduce a perf regression? From my perspective, that "might" the case but also not quite sure ..

So, we should definitely do performance testing for this PR, but it could also wait until the release testing kicks in.

What do you think?

**Comment by manaldush** [comment]
@onurctirtir re-run `make reindent` and commit changes

**Comment by onurctirtir** [comment]
Oh, seems some of the regression tests are failing. Could you look to see why it's the case @manaldush?

From https://github.com/citusdata/citus/actions/runs/14310120419?pr=7950, as an example, multi_cluster_management is failing. You can run this test locally as below (we of course need to fix others too):

```py
cd src/test/regress/

# one time setup begins
pip install pipenv
pipenv --rm
pipenv install
# one time setup ends

pipenv shell

citus_tests/run_test.py multi_cluster_management --use-base-schedule --use-whole-schedule-line
```

Also see src/test/regress/README.md.

**Comment by manaldush** [comment]
> Oh, seems some of the regression tests are failing. Could you look to see why it's the case @manaldush?
> 
> From https://github.com/citusdata/citus/actions/runs/14310120419?pr=7950, as an example, multi_cluster_management is failing. You can run this test locally as below (we of course need to fix others too):
> 
> ```python
> cd src/test/regress/
> 
> # one time setup begins
> pip install pipenv
> pipenv --rm
> pipenv install
> # one time setup ends
> 
> pipenv shell
> 
> citus_tests/run_test.py multi_cluster_management --use-base-schedule --use-whole-schedule-line
> ```
> 
> Also see src/test/regress/README.md.

@onurctirtir, found problem and fixed

**Comment by alperkocatas** [comment]
@onurctirtir @manaldush I tried the patch on ubuntu 22.04 on arm (UTM virtuial machine on M1 Mac). 

It surely behaves better than before. At least multi_extension can pass on some runs. But it still fails on some of the runs when I run the test repeatedly using: 

```bash
cd src/test/regress
pipenv run citus_tests/run_test.py multi_extension --use-base-schedule --use-whole-schedule-line
```

When I look at the `regression.diffs` file, the reason looks like the same as before: server crashing. 

```
+SSL SYSCALL error: EOF detected
+connection to server was lost
```
