### PR TITLE
Set table size to zero if no size is read

### LINKED ISSUE #5041: citus_total_relation_size can throw an error during rebalance
when doing `select * from citus_tables`, which calls `citus_total_relation_size` I got this error:
```
ERROR:  XX000: Error parsing  as uint64, no digits found

LOCATION:  SafeStringToUint64, citus_safe_lib.c:129
```

This indicates that we got an empty string here, possibly because the result was NULL: https://github.com/citusdata/citus/blob/4c3934272fa0089a1476b46532dc863879ce3305/src/backend/distributed/metadata/metadata_utility.c#L647

### PR DESCRIPTION
**Pull request by agedemenli**
DESCRIPTION: Fixes the relation size bug during rebalancing

If a shard is dropped or moved while `citus_total_relation_size()` is being executed, we get an empty string for table size. For that cases, converting an empty string to an unsigned long integer throws an unnecessary error. To prevent that, we can take these empty strings as zero.

Fixes #5041

### CODE REVIEW

**Comment by marcocitus** [comment]
Does this bug fix need a DESCRIPTION? (only needed if it existed pre-10.1)

File: src/backend/distributed/metadata/metadata_utility.c [hunk 1]
```diff
@@ -644,7 +644,14 @@ DistributedTableSizeOnWorker(WorkerNode *workerNode, Oid relationId,
...
 	char *tableSizeString = tableSizeStringInfo->data;
 
-	*tableSize = SafeStringToUint64(tableSizeString);
+	if (strlen(tableSizeString) > 0)
+	{
+		*tableSize = SafeStringToUint64(tableSizeString);
+	}
+	else
+	{
+		*tableSize = 0;
```
Comment (marcocitus) [inline src/backend/distributed/metadata/metadata_utility.c:653]: could use a comment on when this happens

(I assume it happens because the shard was moved away and dropped just when the citus_total_relation_size started)

**Review by marcocitus — APPROVED** [review]

**Comment by agedemenli** [comment]
We can't add a test cover this. Since it's a bug we can't reproduce.

**Review by JelteF — APPROVED** [review]
