### PR TITLE
Faster regression tests

### LINKED ISSUE #346: Reduce runtime for Citus regression tests
(I'm copy / pasting our email thread to continue the conversation here)

I was checking the regression tests to reduce their running time.

Current Running Time
\----------
I run check-multi and check-full on my computer (4 core 1.8 GHz).
* Running time of check-multi: 125 seconds (~10 seconds for initialization and shut-down)
* Running time of check-full: 450 seconds

Critical Tests in Check-Multi
\----------
Here are the slowest tests and their approximate times during check-multi:
* multi_subquery: 5 sec
* multi_single_relation_subquery: 15 sec
* parallel group of multi_prepare_sql and multi_prepare_plsql: 40 sec 
* multi_large_table_join_planning : 7 sec
* multi_large_table_pruning: 7 sec
* multi_large_table_task_assignment: 10 sec

Speeding Up Check-Multi
\----------
To improve check-multi, I need to make more tests run parallel, especially the slowest ones. Here there are two possible ideas:

1. Trying to make the slowest tests parallel without touching their content if they are not dependent
2. Breaking the slow tests into smaller pieces and run these pieces in parallel

To try the first idea, I put the the multi_single_relation_subquery and the parallel group (multi_prepare_sql and multi_prepare_plsql) together because these are the slowest ones and not dependent to each other. However, it only decreases the total time approximately 5 seconds. Also, it seems there are not too many options for this kind of improvement but I need to investigate a bit more.

To try the second idea, I divided the tests of the parallel group (multi_prepare_sql and multi_prepare_plsql) into smaller pieces and put them parallel. It decreases the total time approximately 15 seconds and it seems easy to find more options for this kind of improvement. Intuitively, I am waiting to decrease the total time of check-multi to 80-90 seconds with better organization and by dividing the more tests. However, I am suspicious about its maintenance because I needed to create 10 more tests for this specific example.

Speeding Up Check-Full
\----------
In check-full, we run the test suit of check-multi three times so improving check-multi will improve check-full, too. Also, we don't cover too many new parameters by re-running the suit because of explicit settings in the tests. Here, Andres suggested to replace the check-multi-binary with additional explicit tests. This will remove unnecessary testing and the initialization time of check-multi-binary (~approximately 10 sec for each suit). To remove initialization time of other suits, we can also integrate check-worker and check-multi-fdw into the main schedule.

These changes may decrease time of check-full to approximately 300 seconds without the improvements on check-multi.

### PR DESCRIPTION
**Pull request by mtuncer**
We used to go over multi_schedule 3 times to run  check-multi, check-multi-binary and check-multi-task-tracker runs during check-full.

This was causing extra long running times during development.
I created 2 more schedules multi_binary_schedule and multi_task_tracker_extra_schedule. These schedules are stripped down versions of multi_schedule.  

multi_task_tracker_extra_schedule : contains tests that do not explicitly set task-executor in the beginning of the test. This way the same test is run in both modes only if it does not specify the task-executor.

multi_binary_schedule : contains **some** regression tests that do repartitioning since binary-worker-copy-format is only related to data repartitioning. Unfortunately, I could not make this a part of multi_schedule since this parameter is on the worker side, and only activated after a restart. 

Changes in above tests are related to reducing number of tests run in check-full.

I also added 2 settings when running those schedules.
```
task_tracker_delay = 10ms
remote_task_check_interval = 1 ms
```

These are pretty aggressive numbers. However, they seem to be fine on both my laptop and on travis.

Overall total runtime is reduced to the less than half of original value.

There are few more optimizations possible
1- reduce the number of schedules being run, since setup time costs significant time. For example setup time for ```check-worker``` takes longer than actual tests. Perhaps we could merge check-multi-fdw, check-multi-hll into a single schedule. This would save us from one test setup time (about 15 seconds on my laptop)

2-go over long running tests and reduce the number of cases that do repartitioning. We need to be careful about not reducing the coverage here, same coverage with less tests.

Fixes #346

### CODE REVIEW

**Comment by metdos** [comment]
> These schedules are stripped down versions of multi_schedule.

I didn't like the fact that now we need to add new regression tests to multiple schedules. On the other hand, it seems that this decreases regression time significantly (on my tests it decreased around 50 seconds just for task-tracker).

Could you document this, maybe in the Makefile? Also, you can send an email to team after we merge this.

**Comment by metdos** [comment]
Have you tried parallelizing different regression tests?

File: src/test/regress/Makefile [hunk 1]
```diff
@@ -47,6 +47,8 @@ check-worker: all
 
 check-multi: all tempinstall-main
 	$(pg_regress_multi_check) --load-extension=citus \
+	--server-option=citus.task_tracker_delay=10ms \
+	--server-option=citus.remote_task_check_interval=5ms \
```
Comment (metdos) [inline src/test/regress/Makefile]: Can we set remote_task_check_interva to smaller numbers such as 1ms. I have seen extra performance on my local tests with 1ms. Is there any blocker for this?

File: src/test/regress/multi_task_tracker_extra_schedule [hunk 2]
```diff
@@ -0,0 +1,109 @@
+# ----------
+# $Id$
+#
+# Regression tests that exercise distributed planning/execution functionality.
+#
```
Comment (metdos) [inline src/test/regress/multi_task_tracker_extra_schedule]: Could you add a description about tests in this schedule? Similarly for multi_binary_schedule.

File: src/test/regress/Makefile (hunk 1 above)
Comment (anarazel) [inline src/test/regress/Makefile]: On 2016-06-10 06:54:38 -0700, Metin Döşlü wrote:
> > @@ -47,6 +47,8 @@ check-worker: all
> >  
> >  check-multi: all tempinstall-main
> >  	$(pg_regress_multi_check) --load-extension=citus \
> > +	--server-option=citus.task_tracker_delay=10ms \
> > +	--server-option=citus.remote_task_check_interval=5ms \
> 
> Can we set remote_task_check_interva to smaller numbers such as 1ms. I have seen extra performance on my local tests with 1ms. Is there any blocker for this?

I think it'd be better to set these in pg_regress_multi.pl.

File: src/test/regress/multi_task_tracker_extra_schedule (hunk 2 above)
Comment (mtuncer) [inline src/test/regress/multi_task_tracker_extra_schedule]: done

File: src/test/regress/Makefile (hunk 1 above)
Comment (mtuncer) [inline src/test/regress/Makefile]: 1- added these settings to pg_regress_multi.pl
2- further reduced remote_task_check_interval to 1ms. reducing task tracker delay actually increased running time.

File: src/test/regress/pg_regress_multi.pl [hunk 3]
```diff
@@ -96,6 +96,9 @@ ()
 push(@pgOptions, '-c', "citus.shard_max_size=300kB");
 push(@pgOptions, '-c', "citus.max_running_tasks_per_node=4");
 push(@pgOptions, '-c', "citus.expire_cached_shards=on");
+push(@pgOptions, '-c', "citus.task_tracker_delay=10ms");
+push(@pgOptions, '-c', "citus.remote_task_check_interval=1ms");
+
```
Comment (metdos) [inline src/test/regress/pg_regress_multi.pl]: Very minor. We introduced a new line here.

Comment (mtuncer) [inline src/test/regress/pg_regress_multi.pl]: ok
