### PR TITLE
Columnar: separate plan and runtime quals.

### LINKED ISSUE #5258: Multiple tests SIGSEGV'd when using range / multi range types
Doesn't reproduce on v10.1.0.

Sharing steps to repro & backtrace for only one of 5 coredumps:
```sql
set default_table_access_method to columnar;
CREATE TABLE atest1 ( a int, b text );
CREATE TABLE atest2 (col1 varchar(10), col2 boolean);

INSERT INTO atest1 VALUES (1, 'one');
SELECT * FROM atest1; -- ok
SELECT * FROM atest2; -- ok
INSERT INTO atest1 VALUES (2, 'two'); -- ok
INSERT INTO atest1 SELECT 1, b FROM atest1; -- ok

-- crahes
SELECT * FROM atest2 WHERE ( col1 IN ( SELECT b FROM atest1 ) );
```

```c
#0  0x0000000000b6d074 in pg_detoast_datum (datum=0x0) at fmgr.c:1724
#1  0x000000000080162c in makeConst (consttype=1043, consttypmod=14, constcollid=100, constlen=-1, constvalue=0, constisnull=false, constbyval=false)
    at makefuncs.c:315
#2  0x00007ff6063ff107 in EvalParamsMutator (node=0x2b75a78, econtext=0x2b9a3a8) at ../columnar/columnar_customscan.c:1358
#3  0x0000000000807698 in expression_tree_mutator (node=0x2b75a20, mutator=0x7ff6063ff036 <EvalParamsMutator>, context=0x2b9a3a8) at nodeFuncs.c:2877
#4  0x00007ff6063ff124 in EvalParamsMutator (node=0x2b75a20, econtext=0x2b9a3a8) at ../columnar/columnar_customscan.c:1367
#5  0x00000000008082b9 in expression_tree_mutator (node=0x2b75ab0, mutator=0x7ff6063ff036 <EvalParamsMutator>, context=0x2b9a3a8) at nodeFuncs.c:3109
#6  0x00007ff6063ff124 in EvalParamsMutator (node=0x2b75ab0, econtext=0x2b9a3a8) at ../columnar/columnar_customscan.c:1367
#7  0x00000000008070fb in expression_tree_mutator (node=0x2b759c8, mutator=0x7ff6063ff036 <EvalParamsMutator>, context=0x2b9a3a8) at nodeFuncs.c:2765
#8  0x00007ff6063ff124 in EvalParamsMutator (node=0x2b759c8, econtext=0x2b9a3a8) at ../columnar/columnar_customscan.c:1367
#9  0x00000000008082b9 in expression_tree_mutator (node=0x2b75b08, mutator=0x7ff6063ff036 <EvalParamsMutator>, context=0x2b9a3a8) at nodeFuncs.c:3109
#10 0x00007ff6063ff124 in EvalParamsMutator (node=0x2b75b08, econtext=0x2b9a3a8) at ../columnar/columnar_customscan.c:1367
#11 0x00007ff6063ff1e0 in ColumnarScan_BeginCustomScan (cscanstate=0x2b520f8, estate=0x2b51680, eflags=16) at ../columnar/columnar_customscan.c:1388
#12 0x000000000078203b in ExecInitCustomScan (cscan=0x2b752d0, estate=0x2b51680, eflags=16) at nodeCustom.c:102
#13 0x0000000000764153 in ExecInitNode (node=0x2b752d0, estate=0x2b51680, eflags=16) at execProcnode.c:289
#14 0x00000000007a4cee in ExecInitNestLoop (node=0x2b75b60, estate=0x2b51680, eflags=16) at nodeNestloop.c:302
#15 0x0000000000764172 in ExecInitNode (node=0x2b75b60, estate=0x2b51680, eflags=16) at execProcnode.c:297
#16 0x0000000000759e35 in InitPlan (queryDesc=0x2b683e0, eflags=16) at execMain.c:936
#17 0x0000000000758e03 in standard_ExecutorStart (queryDesc=0x2b683e0, eflags=16) at execMain.c:263
#18 0x00007ff606356f64 in CitusExecutorStart (queryDesc=0x2b683e0, eflags=0) at executor/multi_executor.c:123
#19 0x00007ff600b0203a in pgss_ExecutorStart (queryDesc=0x2b683e0, eflags=0) at pg_stat_statements.c:963
#20 0x0000000000758b4b in ExecutorStart (queryDesc=0x2b683e0, eflags=0) at execMain.c:141
#21 0x00000000009b69af in PortalStart (portal=0x2a9e2e0, params=0x0, eflags=0, snapshot=0x0) at pquery.c:512
#22 0x00000000009b06e9 in exec_simple_query (query_string=0x29bf510 "SELECT * FROM atest2 WHERE ( col1 IN ( SELECT b FROM atest1 ) );") at postgres.c:1175
#23 0x00000000009b4fed in PostgresMain (argc=1, argv=0x7ffe8d3ffb80, dbname=0x2a5cb98 "regression", username=0x2a5cb70 "postgres") at postgres.c:4486
#24 0x00000000008e8a84 in BackendRun (port=0x2a56fe0) at postmaster.c:4506
#25 0x00000000008e8393 in BackendStartup (port=0x2a56fe0) at postmaster.c:4228
#26 0x00000000008e46c7 in ServerLoop () at postmaster.c:1745
#27 0x00000000008e3ef6 in PostmasterMain (argc=5, argv=0x29b9ea0) at postmaster.c:1417
#28 0x00000000007ddf20 in main (argc=5, argv=0x29b9ea0) at main.c:209
```

-----

Other four queries crashed with a very similar backtrace are:
```sql
select * from\n  (select distinct f1, f2, (select f2 from t1 x where x.f1 = up.f1) as fs\n   from t1 up) ss\ngroup by f1,f2,fs;
```
```sql
select * from nummultirange_test natural join nummultirange_test2 order by nmr;
```
```sql
SELECT * FROM\n(SELECT name, n as s1_n, 1 as s1_1 FROM t1) as s1\nNATURAL INNER JOIN\n(SELECT name, n as s2_n, 2 as s2_2 FROM t2) as s2\nNATURAL INNER JOIN\n(SELECT name, n as s3_n, 3 as s3_2 FROM t3) s3;
```
```sql
select * from numrange_test natural join numrange_test2 order by nr;
```

### PR DESCRIPTION
**Pull request by jeff-davis**
Fixes #5258.

### CODE REVIEW

**Comment by onurctirtir** [comment]
Tested with other crashing queries in `parallel_schedule`, I think we can add them as regression tests as well.
I did that on a separate branch, for the cases this pr fixes: 
See https://github.com/citusdata/citus/tree/fix5258-onur.

But looks like one of them is still crashing:
```sql
create temp table t1 (f1 numeric(14,0), f2 varchar(30)) USING columnar;
select * from
  (select distinct f1, f2, (select f2 from t1 x where x.f1 = up.f1) as fs
   from t1 up) ss
group by f1,f2,fs;
```

```c
#0  0x0000000000b6d074 in pg_detoast_datum (datum=0x0) at fmgr.c:1724
#1  0x000000000080162c in makeConst (consttype=1700, consttypmod=917508, constcollid=0, constlen=-1, constvalue=0, constisnull=false, constbyval=false)
    at makefuncs.c:315
#2  0x00007fe9e3460fa8 in EvalParamsMutator (node=0x1b4d550, econtext=0x195e9e8) at ../columnar/columnar_customscan.c:1379
#3  0x00000000008082b9 in expression_tree_mutator (node=0x1b4d4f8, mutator=0x7fe9e3460ed7 <EvalParamsMutator>, context=0x195e9e8) at nodeFuncs.c:3109
#4  0x00007fe9e3460fc5 in EvalParamsMutator (node=0x1b4d4f8, econtext=0x195e9e8) at ../columnar/columnar_customscan.c:1388
#5  0x00000000008070fb in expression_tree_mutator (node=0x1b4d448, mutator=0x7fe9e3460ed7 <EvalParamsMutator>, context=0x195e9e8) at nodeFuncs.c:2765
#6  0x00007fe9e3460fc5 in EvalParamsMutator (node=0x1b4d448, econtext=0x195e9e8) at ../columnar/columnar_customscan.c:1388
#7  0x00000000008082b9 in expression_tree_mutator (node=0x1b4d588, mutator=0x7fe9e3460ed7 <EvalParamsMutator>, context=0x195e9e8) at nodeFuncs.c:3109
#8  0x00007fe9e3460fc5 in EvalParamsMutator (node=0x1b4d588, econtext=0x195e9e8) at ../columnar/columnar_customscan.c:1388
#9  0x00007fe9e3461099 in ColumnarScan_BeginCustomScan (cscanstate=0x195d1d8, estate=0x195cf50, eflags=0) at ../columnar/columnar_customscan.c:1409
#10 0x000000000078203b in ExecInitCustomScan (cscan=0x1b434a8, estate=0x195cf50, eflags=0) at nodeCustom.c:102
#11 0x0000000000764153 in ExecInitNode (node=0x1b434a8, estate=0x195cf50, eflags=0) at execProcnode.c:289
#12 0x0000000000759d8e in InitPlan (queryDesc=0x18219d0, eflags=16) at execMain.c:923
#13 0x0000000000758e03 in standard_ExecutorStart (queryDesc=0x18219d0, eflags=16) at execMain.c:263
#14 0x00007fe9e33be603 in CitusExecutorStart (queryDesc=0x18219d0, eflags=0) at executor/multi_executor.c:123
#15 0x0000000000758b4b in ExecutorStart (queryDesc=0x18219d0, eflags=0) at execMain.c:141
#16 0x00000000009b69af in PortalStart (portal=0x1776130, params=0x0, eflags=0, snapshot=0x0) at pquery.c:512
#17 0x00000000009b06e9 in exec_simple_query (
    query_string=0x16aa190 "select * from\n  (select distinct f1, f2, (select f2 from t1 x where x.f1 = up.f1) as fs\n   from t1 up) ss\ngroup by f1,f2,fs;") at postgres.c:1175
#18 0x00000000009b4fed in PostgresMain (argc=1, argv=0x7ffd14c015c0, dbname=0x1740030 "onurctirtir", username=0x1740008 "onurctirtir") at postgres.c:4486
#19 0x00000000008e8a84 in BackendRun (port=0x1733160) at postmaster.c:4506
#20 0x00000000008e8393 in BackendStartup (port=0x1733160) at postmaster.c:4228
#21 0x00000000008e46c7 in ServerLoop () at postmaster.c:1745
#22 0x00000000008e3ef6 in PostmasterMain (argc=3, argv=0x16a4c10) at postmaster.c:1417
#23 0x00000000007ddf20 in main (argc=3, argv=0x16a4c10) at main.c:209
```

**Comment by onurctirtir** [comment]
SQLAncer also hit to this one, just noting fyi:
https://github.com/citusdata/citus/issues/5258#issuecomment-916768320

File: src/backend/columnar/columnar_customscan.c [hunk 1]
```diff
@@ -1540,8 +1561,10 @@ ColumnarScan_ReScanCustomScan(CustomScanState *node)
 	ColumnarScanState *columnarScanState = (ColumnarScanState *) node;
 
 	ResetExprContext(columnarScanState->css_RuntimeContext);
+	List *allClauses = list_concat(list_copy(linitial(cscan->custom_exprs)),
```
Comment (thanodnl) [inline src/backend/columnar/columnar_customscan.c:1564]: could the first list ever be `NIL`? This would cause a reuse of the pointer for the second list, which might be 
problematic based on the use after this place.

Would it make sense to also make a copy of the list stored in the second element? Or do we know that the `allClauses` list will not be mutated?

**Review by thanodnl — APPROVED** [review]
looks good, left some questions around the mutability of the second argument which could happen if the `plainClauses` had a `NIL` list stored.

File: src/backend/columnar/columnar_customscan.c (hunk 1 above)
Comment (jeff-davis) [reply src/backend/columnar/columnar_customscan.c]: I changed this so that the second list is all the usable clauses, and the plain clauses are a subset. 

expression_tree_mutator() is generally supposed to return a modified copy; it's comment reads: "The original tree is (normally) not changed.". So I think we're OK without an additional copy.

I don't know if this entirely addresses your concern though. Can you restate after looking at the newest version?

**Comment by onurctirtir** [comment]
(Marked as rebased onto fix5257 via github, since this branch was already rebased onto fix5257)

**Review by onurctirtir — APPROVED** [review]
Verified that this fixes the queries that were crashing before, thank you.

Can we also include the other tests from ea8f589b50a3574d45808a20917e95aedfcf5e9e ?
I think cherry-pick'ing that commit should just work.

File: src/backend/columnar/columnar_customscan.c [hunk 2]
```diff
@@ -1100,6 +1100,29 @@ ParameterizationAsString(PlannerInfo *root, Relids paramRelids, StringInfo buf)
 }
 
 
+/*
+ * ContainsExecParams tests whether the node contains any exec params. The
+ * signature accepts an extra argument for use with expression_tree_walker.
+ */
+static bool
+ContainsExecParams(Node *node, void *notUsed)
```
Comment (onurctirtir) [inline src/backend/columnar/columnar_customscan.c:1108]: I think we can just remove notUsed from here, since we always pass NULL arg to walker

Comment (jeff-davis) [reply src/backend/columnar/columnar_customscan.c:1108]: Then the function signature won't match what expression_tree_walker expects. I think that might be undefined behavior in C, though it would probably work.

Comment (onurctirtir) [reply src/backend/columnar/columnar_customscan.c:1108]: oh got it, sorry I missed this.
