### PR TITLE
Give nicer error message when using alter_table_set_access_method on a view

### LINKED ISSUE #6001: Error message of running alter_table_set_access_method for views can be improved
We can improve the error message of running alter_table_set_access_method for views.

``` sql
select alter_table_set_access_method('view_1','columnar');
ERROR: cache lookup failed for access method 0
```

### PR DESCRIPTION
**Pull request by gurkanindibay**
DESCRIPTION: Fixes alter_table_set_access_method error for views.

Fixes #6001

### CODE REVIEW

File: src/backend/distributed/commands/alter_table.c [hunk 1]
```diff
@@ -1116,7 +1117,12 @@ CreateTableConversion(TableConversionParameters *params)
 												relation->rd_rel->relam));
 		if (!HeapTupleIsValid(amTuple))
 		{
-			ereport(ERROR, (errmsg("cache lookup failed for access method %d",
+			bool isView = get_rel_relkind(con->relationId) == RELKIND_VIEW;
+			if ((strcmp(params->accessMethod ,"columnar") == 0) && isView){
+				ereport(ERROR, (errmsg("Views are not supported for columnar type.")));
+			}
+			else
```
Comment (marcocitus) [inline src/backend/distributed/commands/alter_table.c:1124]: missing braces.

File: src/backend/distributed/commands/alter_table.c [hunk 2]
```diff
@@ -1116,7 +1117,12 @@ CreateTableConversion(TableConversionParameters *params)
 												relation->rd_rel->relam));
 		if (!HeapTupleIsValid(amTuple))
 		{
-			ereport(ERROR, (errmsg("cache lookup failed for access method %d",
+			bool isView = get_rel_relkind(con->relationId) == RELKIND_VIEW;
```
Comment (marcocitus) [inline src/backend/distributed/commands/alter_table.c:1120]: I don't think we need to wait this long to do this check. We could do it immediately at the start of alter_table_set_access_method.

File: src/backend/distributed/commands/alter_table.c [hunk 3]
```diff
@@ -1116,7 +1117,12 @@ CreateTableConversion(TableConversionParameters *params)
...
+			if ((strcmp(params->accessMethod ,"columnar") == 0) && isView){
```
Comment (marcocitus) [inline src/backend/distributed/commands/alter_table.c:1121]: You can use `make reindent` to normalize the code style.

File: src/backend/distributed/commands/alter_table.c [hunk 4]
```diff
@@ -1116,7 +1117,12 @@ CreateTableConversion(TableConversionParameters *params)
...
+				ereport(ERROR, (errmsg("Views are not supported for columnar type.")));
```
Comment (marcocitus) [inline src/backend/distributed/commands/alter_table.c:1122]: minor: the convention in postgres is that error messages start with a small letter and do not have `.` at the end

**Review by marcocitus — COMMENTED** [review]
would be good to add a regression test

File: src/backend/distributed/commands/alter_table.c (hunk 3 above)
Comment (marcocitus) [reply src/backend/distributed/commands/alter_table.c:1121]: btw, I think this is independent of the access method (strcmp is not needed). We can never set an access method on a view.

File: src/backend/distributed/commands/alter_table.c (hunk 2 above)
Comment (gurkanindibay) [reply src/backend/distributed/commands/alter_table.c]: Moved the block and applied all review notes on the new place

File: src/backend/distributed/commands/alter_table.c (hunk 3 above)
Comment (gurkanindibay) [reply src/backend/distributed/commands/alter_table.c]: Moved the block and applied all review notes on the new place

File: src/backend/distributed/commands/alter_table.c (hunk 1 above)
Comment (gurkanindibay) [reply src/backend/distributed/commands/alter_table.c]: Moved the block and applied all review notes on the new place

File: src/test/regress/sql/alter_table_set_access_method_view.sql [hunk 5]
```diff
@@ -0,0 +1,14 @@
+CREATE SCHEMA view_acceess_method_test;
```
Comment (hanefi) [inline src/test/regress/sql/alter_table_set_access_method_view.sql:1]: Typo in the word `access`. Check other occurrences of this typo in the same file.

File: src/test/regress/sql/alter_table_set_access_method_view.sql [hunk 6]
```diff
@@ -0,0 +1,14 @@
...
+SET search_path TO view_acceess_method_test;
```
Comment (hanefi) [inline src/test/regress/sql/alter_table_set_access_method_view.sql:2]: Can we move this test to file `alter_table_set_access_method.sql`?

File: src/test/regress/sql/alter_table_set_access_method_view.sql [hunk 7]
```diff
@@ -0,0 +1,14 @@
...
+
+--create the view to test alter table set access method on it
+CREATE TABLE view_test_table (id int, val int, flag bool, kind int);
+SELECT create_distributed_table('view_acceess_method_test.view_test_table','id');
```
Comment (hanefi) [inline src/test/regress/sql/alter_table_set_access_method_view.sql:6]: Info: since you set search path to our schema, you can safely omit the schema name in this call. `SET search_path .. ` is there to make it easy to read the rest of the tests in the same file.

File: src/test/regress/sql/alter_table_set_access_method_view.sql [hunk 8]
```diff
@@ -0,0 +1,14 @@
...
+INSERT INTO view_test_table VALUES (1, 1, true, 99), (2, 2, false, 99), (2, 3, true, 88);
+CREATE VIEW view_test_view AS SELECT * FROM view_test_table;
+
+--alter the view to columnar
```
Comment (hanefi) [inline src/test/regress/sql/alter_table_set_access_method_view.sql:10]: It is a nice idea to have comments that explicitly state that the next line is expected to get errors.

```suggestion
-- error out when attempting to set access method of a view.
```

**Review by marcocitus — APPROVED** [review]

**Review by hanefi — CHANGES_REQUESTED** [review]

File: src/test/regress/sql/alter_table_set_access_method.sql [hunk 9]
```diff
@@ -274,3 +274,19 @@ COMMIT;
 SET client_min_messages TO WARNING;
 DROP SCHEMA alter_table_set_access_method CASCADE;
 SELECT 1 FROM master_remove_node('localhost', :master_port);
+
+--test failure when a view is being tried to be altered to columnar
+CREATE SCHEMA view_access_method_test;
+SET search_path TO view_access_method_test;
+
```
Comment (hanefi) [inline src/test/regress/sql/alter_table_set_access_method.sql:281]: No need to create a new schema for this IMO. We usually have a single schema, if we do not directly test some case that involves multiple schemas.

I suggest you (1) remove the first 3 lines you added, (2) move your tests before we drop `alter_table_set_access_method` schema, (3) do not drop any schema as we already do it in this file.

File: src/test/regress/sql/alter_table_set_access_method.sql [hunk 10]
```diff
@@ -274,3 +274,19 @@ COMMIT;
...
+CREATE TABLE view_test_table (id int, val int, flag bool, kind int);
+SELECT create_distributed_table('view_access_method_test.view_test_table','id');
+INSERT INTO view_test_table VALUES (1, 1, true, 99), (2, 2, false, 99), (2, 3, true, 88);
+CREATE VIEW view_test_view AS SELECT * FROM view_test_table;
+
+-- error out when attempting to set access method of a view.
+select alter_table_set_access_method('view_test_view','columnar');
+
+--clean environment
+DROP SCHEMA view_access_method_test CASCADE;
```
Comment (hanefi) [inline src/test/regress/sql/alter_table_set_access_method.sql:292]: No need to drop the schema if you move your tests to earlier in the file.

File: src/test/regress/sql/alter_table_set_access_method.sql (hunk 9 above)
Comment (gurkanindibay) [reply src/test/regress/sql/alter_table_set_access_method.sql]: Fixed you as you suggested

File: src/test/regress/sql/alter_table_set_access_method.sql (hunk 10 above)
Comment (gurkanindibay) [reply src/test/regress/sql/alter_table_set_access_method.sql]: Fixed you as you suggested

File: src/test/regress/sql/alter_table_set_access_method_view.sql (hunk 8 above)
Comment (gurkanindibay) [reply src/test/regress/sql/alter_table_set_access_method_view.sql]: Fixed you as you suggested

File: src/test/regress/sql/alter_table_set_access_method_view.sql (hunk 7 above)
Comment (gurkanindibay) [reply src/test/regress/sql/alter_table_set_access_method_view.sql]: Fixed you as you suggested

File: src/test/regress/sql/alter_table_set_access_method_view.sql (hunk 6 above)
Comment (gurkanindibay) [reply src/test/regress/sql/alter_table_set_access_method_view.sql]: Fixed you as you suggested

File: src/test/regress/sql/alter_table_set_access_method_view.sql (hunk 5 above)
Comment (gurkanindibay) [reply src/test/regress/sql/alter_table_set_access_method_view.sql]: Fixed

File: src/test/regress/sql/alter_table_set_access_method.sql [hunk 11]
```diff
@@ -99,10 +99,10 @@ CREATE INDEX idx1 ON index_table (a);
 -- also create an index with statistics
 CREATE INDEX idx2 ON index_table ((a+1));
 ALTER INDEX idx2 ALTER COLUMN 1 SET STATISTICS 300;
-SELECT indexname FROM pg_indexes WHERE schemaname = 'alter_table_set_access_method' AND tablename = 'index_table';
+SELECT indexname FROM pg_indexes WHERE schemaname = 'alter_table_set_access_method' AND tablename = 'index_table' order by indexname;
```
Comment (hanefi) [inline src/test/regress/sql/alter_table_set_access_method.sql:102]: Thanks for fixing this flaky test case.

File: src/test/regress/sql/alter_table_set_access_method.sql [hunk 12]
```diff
@@ -271,6 +271,20 @@ BEGIN;
...
+select alter_table_set_access_method('view_test_view','columnar');
+
 SET client_min_messages TO WARNING;
 DROP SCHEMA alter_table_set_access_method CASCADE;
 SELECT 1 FROM master_remove_node('localhost', :master_port);
+
+
+
+
+
```
[the remark this answers is not in the document]
Comment (gurkanindibay) [reply src/test/regress/sql/alter_table_set_access_method.sql]: Fixed
