### PR TITLE
Send commands to coordinator when it is added as a worker

### LINKED ISSUE #3996: Single node citus does does not work with repartition joins
Trying to run a repartition join on a cluster where the only worker is also the coordinator, we get a `floating-point exception`:
```sql
-- Add coordinator as worker
SELECT 1 FROM master_add_node('localhost', :master_port, groupid => 0);
SELECT 1 FROM master_set_node_property('localhost', :master_port, 'shouldhaveshards', true);

-- NOTE: Make sure no other nodes are in pg_dist_node (otherwise below queries will succeed)
SET citus.enable_repartition_joins TO ON;
SELECT * FROM test t1, test t2 WHERE t1.x = t2.y ORDER BY t1.x;
-- ERROR:  floating-point exception
-- DETAIL:  An invalid floating-point operation was signaled. This probably means an out-of-range result or an invalid operation, such as division by zero.
```
This is because of two places where `ActiveReadableWorkerNodeCount` returns 0 in that case and eventually we will divide or modulo on `0`:
1. https://github.com/citusdata/citus/blob/844221bb9f9e7524f82742e63abbe2f913585dfa/src/backend/distributed/planner/multi_physical_planner.c#L2110
2. https://github.com/citusdata/citus/blob/844221bb9f9e7524f82742e63abbe2f913585dfa/src/backend/distributed/planner/multi_physical_planner.c#L5720-L5721

Changing these places to use `ActiveReadableNodeList` instead causes other issues again:
```
ERROR:  relation "task_000005" already exists
CONTEXT:  while executing command on localhost:57636
```
or 
```
ERROR:  duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(task_000005, 2200) already exists.
CONTEXT:  while executing command on localhost:57636
```

Which of these you get is timing related: https://www.postgresql.org/message-id/flat/4F9541D3.1000202%40beccati.com

They both indicate that we try to create the same `task_000005` table multiple times. These changes also cause this error to occur in cases that are currently working in the `coordinator_shouldhaveshards.sql` test file.

### LINKED ISSUE #4007: Task Tracker fails with single node
If we add this to the single node:

```sql
SET citus.task_executor_type to 'task-tracker';
SELECT count(*) FROM test;
```
we get:
```diff
+SET citus.task_executor_type to 'task-tracker';
+SELECT count(*) FROM test;
+WARNING:  this query assigns more tasks per node than the configured max_tracked_tasks_per_node limit
+ERROR:  could not find task tracker for node "localhost:57636"
```
These two errors are because we don't include coordinator as a worker when it is added to cluster. So we use the wrong methods to get node list.

https://github.com/citusdata/citus/blob/b642ed10e9805a06c3ea06d9f897b0bf3668c950/src/backend/distributed/executor/multi_server_executor.c#L121-L124

At these lines the workerCount will be 0 if there is only coordinator as a worker, hence it will be incorrect. that is why we get the warning.

And here:
https://github.com/citusdata/citus/blob/b642ed10e9805a06c3ea06d9f897b0bf3668c950/src/backend/distributed/executor/multi_task_tracker_executor.c#L206-L222

We don't get the coordinator, so we don't connect to coordinator. That is why we get `could not find task tracker for node "localhost:57636"`. Note that 57636 is the coordinator.

If we are not going to backport this, it might not make sense to fix this, because we are already removing task tracker with this release: #3850.

### PR DESCRIPTION
**Pull request by SaitTalhaNisanci**
DESCRIPTION: send commands to coordinator when it is added as a worker

We were using ALL_WORKERS TargetWorkerSet while sending temporary schema
creation and cleanup. We(well mostly I) thought that ALL_WORKERS would 
also include coordinator when it is added as a worker. It turns out that it was 
FILTERING OUT the coordinator even if it is added as a worker to the cluster.

So to have some context here, in repartitions, for each jobId we create
(at least we were supposed to) a schema in each worker node in the cluster. 
Then we partition each shard table into some intermediate files, which is 
called the PARTITION step. So after this partition step each node has some 
intermediate files having tuples in those nodes. Then we fetch the partition
 files to necessary worker nodes, which is called the FETCH step. Then from
 the files we create intermediate tables in the temporarily created schemas, 
which is called a MERGE step. Then after evaluating the result, we remove the
 temporary schemas(one for each job ID in each node) and files.

If node 1 has file1, and node 2 has file2 after PARTITION step, it is
enough to either move file1 from node1 to node2 or vice versa. So we
prune one of them.

In the MERGE step, if the schema for a given jobID doesn't exist, the
node tries to use the `public` schema if it is a superuser, which is
actually added for testing in the past.

So when we were not sending schema creation comands for each job ID to
the coordinator(because we were using ALL_WORKERS flag, and it doesn't
include the coordinator), we would basically not have any schemas for
repartitions in the coordinator. The PARTITION step would be executed on
the coordinator (because the tasks are generated in the planner part)
and it wouldn't give us any error because it doesn't have anything to do
with the temporary schemas(that we didn't create). But later two things
would happen:

- If by chance the fetch is pruned on the coordinator side, we the other
nodes would fetch the partitioned files from the coordinator and execute
the query as expected, because it has all the information.
- If the fetch tasks are not pruned in the coordinator, in the MERGE
step, the coordinator would either error out saying that the necessary
schema doesn't exist, or it would try to create the temporary tables
under public schema ( if it is a superuser). But then if we had the same
task ID with different jobID it would fail saying that the table already
exists, which is an error we were getting.

In the first case, the query would work okay, but it would still not do
the cleanup, hence we would leave the partitioned files from the
PARTITION step there. Hence ensure_no_intermediate_data_leak would fail.

To make things more explicit and prevent such bugs in the future,
ALL_WORKERS is named as ALL_NON_COORD_WORKERS. And a new flag to return
all the active nodes is added as ALL_DATA_NODES. For repartition case,
we don't use the only-reference table nodes but this version makes the
code simpler and there shouldn't be any significant performance issue
with that.

0dd3c6e2e043b37911b976ee7c7e5e4e88a4e974 and 57f4b3ccaf4b7f02cec29f65195488767f0ae816 Fixes #3996 
https://github.com/citusdata/citus/pull/4005/commits/e7aab6dab043f46a6e1983dfd0e7af2c6e749845 Fixes #4007

### CODE REVIEW

File: src/backend/distributed/commands/collation.c [hunk 1]
```diff
@@ -278,7 +278,7 @@ PreprocessDropCollationStmt(Node *node, const char *queryString)
 								(void *) dropStmtSql,
 								ENABLE_DDL_PROPAGATION);
 
-	return NodeDDLTaskList(ALL_WORKERS, commands);
+	return NodeDDLTaskList(ALL_NON_COORD_WORKERS, commands);
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/commands/collation.c:281]: will rebase onto https://github.com/citusdata/citus/pull/4003 and rename this as ALL_NON_COORDINATOR_WORKERS

**Comment by onderkalaci** [comment]
> DESCRIPTION: send commands to coordinator when it is added as a worker


This description sounds too generic. Are we only changing something related to repartition joins? If not, could you please add tests for other things as well?

**Comment by SaitTalhaNisanci** [comment]
>This description sounds too generic. Are we only changing something related to repartition joins? If not, could you please add tests for other things as well?

No this is not repartition specific, I will try to add tests for other cases.

File: src/test/regress/expected/follower_single_node.out [hunk 2]
```diff
@@ -102,15 +113,6 @@ SELECT * FROM ref, local WHERE a = c ORDER BY a;
...
 
--- Check repartion joins are support
-SELECT * FROM test t1, test t2 WHERE t1.x = t2.y ORDER BY t1.x;
-ERROR:  floating-point exception
-DETAIL:  An invalid floating-point operation was signaled. This probably means an out-of-range result or an invalid operation, such as division by zero.
-SET citus.enable_repartition_joins TO ON;
-SELECT * FROM test t1, test t2 WHERE t1.x = t2.y ORDER BY t1.x;
-ERROR:  floating-point exception
-DETAIL:  An invalid floating-point operation was signaled. This probably means an out-of-range result or an invalid operation, such as division by zero.
-RESET citus.enable_repartition_joins;
```
Comment (JelteF) [inline src/test/regress/expected/follower_single_node.out:113]: Why did you remove these tests (and the ones below)? Is it because they now gave "in recovery" errors? If so, I think it's better to keep them. This way you know they will continue giving the expected error.

File: src/include/distributed/worker_transaction.h [hunk 3]
```diff
@@ -24,7 +24,8 @@ typedef enum TargetWorkerSet
 {
 	WORKERS_WITH_METADATA,
 	OTHER_WORKERS,
```
Comment (JelteF) [inline src/include/distributed/worker_transaction.h:26]: I believe OTHER_WORKERS is not used at all. Can we just remove it then?

File: src/include/distributed/worker_transaction.h [hunk 4]
```diff
@@ -24,7 +24,8 @@ typedef enum TargetWorkerSet
...
-	ALL_WORKERS
+	ALL_NON_COORDINATOR_WORKERS,
```
Comment (JelteF) [inline src/include/distributed/worker_transaction.h:27]: Maybe ALL_NON_COORDINATOR_NODES? And possibly similar rename for `WORKERS_WITH_METADATA` to stay consistent.

File: src/test/regress/expected/follower_single_node.out (hunk 2 above)
Comment (SaitTalhaNisanci) [reply src/test/regress/expected/follower_single_node.out:113]: Yeah I thought the reason we wanted to have those tests were testing repartition joins, not recovery case with repartition joins so that is why I moved them above.

But we can keep them there to test the recovery case for sure, I will put them back before merging this PR.

File: src/test/regress/expected/single_node.out [hunk 5]
```diff
@@ -226,6 +231,50 @@ SELECT count(*) FROM test WHERE false GROUP BY GROUPING SETS (x,y);
...
+-- INSERT SELECT from distributed table to local table
+BEGIN;
+INSERT INTO local(c, d) SELECT a, b FROM ref;
+SELECT count(*) from local;
+ count
+---------------------------------------------------------------------
+     6
+(1 row)
+
+ROLLBACK;
```
Comment (JelteF) [inline src/test/regress/expected/single_node.out:277]: Let's reset `task_executor_type` again here.

File: src/include/distributed/worker_transaction.h (hunk 3 above)
Comment (SaitTalhaNisanci) [reply src/include/distributed/worker_transaction.h:26]: https://github.com/citusdata/citus/blob/master/src/backend/distributed/transaction/worker_transaction.c#L213 seems to be used

File: src/test/regress/expected/single_node.out (hunk 5 above)
Comment (JelteF) [inline src/test/regress/expected/single_node.out:277]: Reading the other tests I realised that there's some more operations that are good to test that I didn't add in my previous PR.
1. `UPDATE` (both router and everything)
2. `DELETE` (both router and everything)
3. `TRUNCATE` (reference, local, and distributed)
4. `DROP TABLE` (reference, local, and distributed)
5. `CREATE INDEX` (reference, local, and distributed)
6. `DROP INDEX` (reference, local, and distributed)

File: src/include/distributed/worker_transaction.h (hunk 3 above)
Comment (JelteF) [reply src/include/distributed/worker_transaction.h:26]: I meant it's never set to that value, so that check can also be removed then.

File: src/backend/distributed/planner/multi_router_planner.c [hunk 6]
```diff
@@ -2275,7 +2275,7 @@ CreateDummyPlacement(bool hasLocalRelation)
 		return CreateLocalDummyPlacement();
 	}
 
-	List *workerNodeList = ActiveReadableNonCoordinatorNodeList();
+	List *workerNodeList = ActiveReadableNodeList();
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_router_planner.c:2278]: one line above, we return local dummy placement when needed. Why do we need coordinator here?

Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/multi_router_planner.c:2278]: Right, I guess in terms of functionality including/excluding coordinator doesn't make a difference since this is just a dummy placement, but I will revert this since it seems unnecessary.

File: src/include/distributed/worker_transaction.h (hunk 4 above)
Comment (SaitTalhaNisanci) [reply src/include/distributed/worker_transaction.h:27]: #4015

File: src/backend/distributed/planner/multi_router_planner.c (hunk 6 above)
Comment (JelteF) [reply src/backend/distributed/planner/multi_router_planner.c]: I think changing this line is an improvement. Otherwise if the coordinator is part of the workers it's never part of round-robin (unless it's the only node), which seems weird.

**Comment by SaitTalhaNisanci** [comment]
What about this method?

https://github.com/citusdata/citus/blob/3f50165365e8b83c3c66aeb0a97e9f6ebafed251/src/backend/distributed/planner/intermediate_result_pruning.c#L148-L154

It also seems that we would want to include the coordinator here if it is added to the cluster?

**Comment by JelteF** [comment]
> It also seems that we would want to include the coordinator here if it is added to the cluster?

It seems like that would break with MX and the coordinator added as a worker. It seems like it would not get the intermediate results then. There might be more issues there. So I think it makes sense to copy over the `coordinator_shouldhaveshards` test to MX.

Also, I'm wondering what will happen in MX and normal when workers are added without `shouldhaveshards=false and only the coordinator has `shouldhaveshards=true`. Seems like that might cause a different set of issues too. Or maybe we would send intermediate results to those workers even though it's not necessary to do so, although intermediate result pruning might have solved that.

File: src/test/regress/expected/follower_single_node.out (hunk 2 above)
Comment (SaitTalhaNisanci) [reply src/test/regress/expected/follower_single_node.out:113]: added them back

File: src/backend/distributed/planner/multi_physical_planner.c [hunk 7]
```diff
@@ -2107,7 +2107,7 @@ BuildMapMergeJob(Query *jobQuery, List *dependentJobList, Var *partitionKey,
 static uint32
 HashPartitionCount(void)
 {
-	uint32 groupCount = ActiveReadableNonCoordinatorNodeCount();
+	uint32 groupCount = list_length(ActiveReadableNodeList());
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_physical_planner.c:2110]: The return value of this defines the number of hash partitions. So, it doesn't matter if we use `readable` or `primary` in this context. So, it is better to keep the behaviour similar by using `ActiveReadableNodeList ()`.

(but it would probably more natural if we use an API with primary nodes in  the future)

File: src/backend/distributed/planner/multi_physical_planner.c [hunk 8]
```diff
@@ -5717,7 +5717,7 @@ AssignDualHashTaskList(List *taskList)
 	 * if subsequent jobs have a small number of tasks, we won't allocate the
 	 * tasks to the same worker repeatedly.
 	 */
-	List *workerNodeList = ActiveReadableNonCoordinatorNodeList();
+	List *workerNodeList = ActiveReadableNodeList();
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_physical_planner.c:5720]: We have other types  of repartition joins as well. We should at least make sure that single hash  repartition joins work fine. In that case, you need to do two things: (a) join should include table_1.dist_key = table_2.non_dist_key  (b) `SET citus.enable_single_hash_repartition_joins TO ON;`

File: src/backend/distributed/planner/multi_physical_planner.c (hunk 7 above)
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_physical_planner.c:2110]: The return value of this defines the number of hash partitions. So, it doesn't matter if we use `readable` or `primary` in this context. So, it is better to keep the behaviour similar by using `ActiveReadableNodeList ()`.

(but it would probably more natural if we use an API with primary nodes in  the future)

File: src/include/distributed/worker_transaction.h [hunk 9]
```diff
@@ -24,7 +24,8 @@
 typedef enum TargetWorkerSet
 {
 	NON_COORDINATOR_METADATA_NODES,
-	NON_COORDINATOR_NODES
+	NON_COORDINATOR_NODES,
+	ALL_DATA_NODES
```
Comment (onderkalaci) [inline src/include/distributed/worker_transaction.h:28]: With this change, we're even increasing the complexity (#4016) by adding one more option :/ In fact, the name of the struct is `TargetWorkerSet` but  now we're adding the coordinator. In fact, `TargetWorkerSetNodeList ` seem to be designed/used only for worker nodes in the code

Is there another way to add the coordinator in a less controversial way? I mean, scoping the changes only to `DoRepartitionCleanup ()  / CreateTemporarySchemasForMergeTasks ()`?

In any case, we may consider renaming `ALL_DATA_NODES ` to `ALL_NODES ` as  we don't have a `data node ` concept in the code and lets not have it?

File: src/test/regress/expected/follower_single_node.out [hunk 10]
```diff
@@ -34,6 +34,17 @@ CREATE TABLE local(c int, d int);
 INSERT INTO test VALUES (1, 2), (3, 4), (5, 6), (2, 7), (4, 5);
 INSERT INTO ref VALUES (1, 2), (5, 6), (7, 8);
 INSERT INTO local VALUES (1, 2), (3, 4), (7, 8);
+-- Check repartion joins are supported
+SET citus.enable_repartition_joins TO ON;
+SELECT * FROM test t1, test t2 WHERE t1.x = t2.y ORDER BY t1.x;
```
Comment (onderkalaci) [inline src/test/regress/expected/follower_single_node.out:39]: At this point, we've not added coordinator to the metadata or running it on a secondary. I guess this test is not useful here

File: src/test/regress/expected/follower_single_node.out [hunk 11]
```diff
@@ -226,15 +232,10 @@ SELECT * FROM ref, local WHERE a = c ORDER BY a;
  7 | 8 | 7 | 8
 (2 rows)
 
--- Check repartion joins are support
+SET citus.enable_repartition_joins TO ON;
```
Comment (onderkalaci) [inline src/test/regress/expected/follower_single_node.out:235]: This might be because of the comment I had on `MultiTaskTrackerExecute `

File: src/test/regress/expected/follower_single_node.out [hunk 12]
```diff
@@ -226,15 +232,10 @@ SELECT * FROM ref, local WHERE a = c ORDER BY a;
...
 SELECT * FROM test t1, test t2 WHERE t1.x = t2.y ORDER BY t1.x;
-ERROR:  floating-point exception
-DETAIL:  An invalid floating-point operation was signaled. This probably means an out-of-range result or an invalid operation, such as division by zero.
-SET citus.enable_repartition_joins TO ON;
-SELECT * FROM test t1, test t2 WHERE t1.x = t2.y ORDER BY t1.x;
-ERROR:  floating-point exception
-DETAIL:  An invalid floating-point operation was signaled. This probably means an out-of-range result or an invalid operation, such as division by zero.
-RESET citus.enable_repartition_joins;
+ERROR:  writing to worker nodes is not currently allowed
+DETAIL:  the database is in recovery mode
```
Comment (onderkalaci) [inline src/test/regress/expected/follower_single_node.out:238]: Can we add tests for:
- single hash repartition joins
- Changing `citus.task_assignment_policy`

File: src/include/distributed/worker_transaction.h (hunk 9 above)
Comment (marcocitus) [reply src/include/distributed/worker_transaction.h:28]: It's probably a little nicer to pass function pointers instead of this enum, e.g. IsNodePrimaryWithShards

File: src/backend/distributed/executor/multi_task_tracker_executor.c [hunk 13]
```diff
@@ -209,7 +209,7 @@ MultiTaskTrackerExecute(Job *job)
 	 * assigning and checking the status of tasks. The second (temporary) hash
 	 * helps us in fetching results data from worker nodes to the master node.
 	 */
-	List *workerNodeList = ActivePrimaryNonCoordinatorNodeList(NoLock);
+	List *workerNodeList = ActiveReadableNodeList();
```
[the remark this answers is not in the document]
Comment (SaitTalhaNisanci) [reply src/backend/distributed/executor/multi_task_tracker_executor.c:212]: Makes sense. I guess we should not use NoLock though right? What if a node is being added concurrently? Should we use ShareLock?

File: src/include/distributed/worker_transaction.h (hunk 9 above)
Comment (SaitTalhaNisanci) [reply src/include/distributed/worker_transaction.h:28]: >In fact, the name of the struct is TargetWorkerSet but now we're adding the coordinator.

I think this goes back to `What is a worker?` because assuming that we consider coordinator is also a worker when `shouldhaveshards=true` this enum will return it in `ALL_DATA_NODES` case. If we use `ALL_NODES` it seems a bit incorrect to me because I would expect `ALL_NODES` to return coordinator even if it is not added to the cluster as a worker.

So I guess maybe `ALL_SHARD_NODES`? This part also needs refactoring but would it be better to have that with the new structure which will be introduced for fixing #4016 (where we can also remove the worker concept)?

File: src/test/regress/expected/follower_single_node.out (hunk 10 above)
Comment (SaitTalhaNisanci) [reply src/test/regress/expected/follower_single_node.out:39]: Above we have:

```sql
SELECT 1 FROM master_add_node('localhost', :master_port, groupid => 0);
SELECT 1 FROM master_set_node_property('localhost', :master_port, 'shouldhaveshards', true);
```

so isnt coordinator added?

Comment (onderkalaci) [reply src/test/regress/expected/follower_single_node.out:39]: (I probably meant that we're not running it on the secondary at  this point -- given that the test file is intended for secondaries --, but lets keep this test in case we don't have something similar in other places)

Comment (SaitTalhaNisanci) [reply src/test/regress/expected/follower_single_node.out:39]: We also test this in `single_node.sql` so we can remove it maybe.

File: src/test/regress/expected/follower_single_node.out [hunk 14]
```diff
@@ -34,6 +34,40 @@ CREATE TABLE local(c int, d int);
...
+ 4 | 5 | 3 | 4
+ 5 | 6 | 4 | 5
+(3 rows)
+
+RESET citus.enable_repartition_joins;
+RESET citus.enable_single_hash_repartition_joins;
+SET citus.task_assignment_policy TO 'round-robin';
+SET citus.enable_single_hash_repartition_joins TO ON;
+SELECT * FROM test t1, test t2 WHERE t1.x = t2.y ORDER BY t1.x;
+ERROR:  the query contains a join that requires repartitioning
```
Comment (onderkalaci) [inline src/test/regress/expected/follower_single_node.out:61]: I guess enabling `enable_repartition_joins ` would be nicer, let's see that the query runs OK?

File: src/backend/distributed/planner/multi_router_planner.c (hunk 6 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/multi_router_planner.c]: I guess we won't do this improvement in this PR if there isn't any objection.
