### PR TITLE
Propagate alter schema rename

### LINKED ISSUE #4248: Alter schema rename does not propagate
After an ALTER SCHEMA, distributed tables in that schema may no longer work.

```sql
create schema foo;                                                            
create table foo.test (x int, y int);                                                                                                                                  
select create_distributed_table('foo.test', 'x'); 
alter schema foo rename to bar;
select count(*) from bar.test;
ERROR:  relation "bar.test_102425" does not exist
CONTEXT:  while executing command on localhost:9700
```

### PR DESCRIPTION
**Pull request by agedemenli**
DESCRIPTION: Implementation of propagating schema renamings

We were not supporting `ALTER SCHEMA x RENAME TO y;`
This PR adds propagation for allowing users to rename schemas across the workers.

fixes #4248

### CODE REVIEW

**Comment by agedemenli** [comment]
Will add tests.
Maybe qualify function as well? @thanodnl

File: src/backend/distributed/commands/schema.c [hunk 1]
```diff
@@ -186,3 +241,41 @@ FilterDistributedSchemas(List *schemas)
...
+{
+	if (!IsTransactionBlock())
+	{
+		/* we do not need to switch to sequential mode if we are not in a transaction */
+		return;
+	}
+
+	if (ParallelQueryExecutedInTransaction())
+	{
+		ereport(ERROR, (errmsg("cannot create or modify type because there was a "
```
Comment (halilozanakgul) [inline src/backend/distributed/commands/schema.c:265]: It should be `schema` instead of `type`.

Comment (agedemenli) [reply src/backend/distributed/commands/schema.c:265]: copy-paste's gift :)

File: src/backend/distributed/deparser/deparse_schema_stmts.c [hunk 2]
```diff
@@ -131,3 +146,12 @@ AppendGrantOnSchemaGrantees(StringInfo buf, GrantStmt *stmt)
...
 	}
 }
+
+
+static void
+AppendAlterSchemaRenameStmt(StringInfo buf, RenameStmt *stmt)
+{
+	Assert(stmt->renameType == OBJECT_SCHEMA);
+
+	appendStringInfo(buf, "ALTER SCHEMA %s RENAME TO %s;", stmt->subname, stmt->newname);
```
Comment (halilozanakgul) [inline src/backend/distributed/deparser/deparse_schema_stmts.c:156]: Schema names with special characters could fail here. (like `oz'an`)
You can use quote_identifier function for them.

This should not fail:
```
ALTER SCHEMA "ab'cd" RENAME TO "ef'gh";
```

Also you can add that to the tests

File: src/test/regress/expected/multi_schema_support.out [hunk 3]
```diff
@@ -1442,6 +1442,34 @@ ALTER TABLE "CiTuS.TeeN"."TeeNTabLE.1!?!" ADD COLUMN "NEW_TeeN:COl" text;
...
+ALTER SCHEMA foo rename to bar;
+SELECT COUNT(*) FROM bar.test;
+ count
+---------------------------------------------------------------------
+     2
+(1 row)
+
+-- test propagation with weird name
+ALTER SCHEMA "CiTuS.TeeN" RENAME TO "Citus'Teen123";
+SELECT * FROM "Citus'Teen123"."TeeNTabLE.1!?!";
```
Comment (halilozanakgul) [inline src/test/regress/expected/multi_schema_support.out:1464]: You can add ORDER BY here, so the order of the output does not change randomly.

File: src/backend/distributed/commands/schema.c [hunk 4]
```diff
@@ -153,6 +157,57 @@ PreprocessGrantOnSchemaStmt(Node *node, const char *queryString)
...
+PreprocessAlterSchemaRenameStmt(Node *node, const char *queryString)
+{
+	ObjectAddress schemaAddress = GetObjectAddressFromParseTree(node, false);
+	if (!ShouldPropagateObject(&schemaAddress))
+	{
+		return NIL;
+	}
+
+	/* deparse sql*/
+	const char *renameStmtSql = DeparseTreeNode(node);
```
Comment (thanodnl) [inline src/backend/distributed/commands/schema.c:178]: I'd like a call to `QualifyTreeNode` above this to make the function more similar to the other `Prepare...Stmt` functions. Even though we don't have a qualify function on this type of tree - which is correct -. It will be effectively a no-op.

Reasons is that this prepare function becomes so generic we can at some point fold them into 1 so all statements behave the same. Already having this call here makes it easier to merge it with others.

File: src/backend/distributed/commands/schema.c [hunk 5]
```diff
@@ -186,3 +241,41 @@ FilterDistributedSchemas(List *schemas)
...
+		ereport(ERROR, (errmsg("cannot create or modify schema because there was a "
+							   "parallel operation on a distributed table in the "
+							   "transaction"),
+						errdetail("When creating or altering a schema, Citus needs to "
+								  "perform all operations over a single connection per "
+								  "node to ensure consistency."),
+						errhint("Try re-running the transaction with "
+								"\"SET LOCAL citus.multi_shard_modify_mode TO "
+								"\'sequential\';\"")));
+	}
```
Comment (thanodnl) [inline src/backend/distributed/commands/schema.c:274]: lets try and add a test that exhibits this code path.

```sql
BEGIN;
-- A query that will fan out to multiple shards at once, something like a `count(*)` (might need to set a setting to force the count(*) to use maximum parallelism
-- Rename a schema here, this should error
ROLLBACK;
```

Then the same block, however after the begin first run
```sql
SET LOCAL citus.multi_shard_modify_mode TO 'sequential';
```

This makes sure we know that the message works!

File: src/backend/distributed/deparser/deparse_schema_stmts.c (hunk 2 above)
Comment (thanodnl) [reply src/backend/distributed/deparser/deparse_schema_stmts.c]: ❤️ 

Thanks for the proactive review Ozan! It helped me to go quickly through the last parts when the low hanging fruit was already addressed! (and ofc thank you Amhet for addressing them already)

File: src/test/regress/expected/multi_schema_support.out [hunk 6]
```diff
@@ -1442,6 +1442,58 @@ ALTER TABLE "CiTuS.TeeN"."TeeNTabLE.1!?!" ADD COLUMN "NEW_TeeN:COl" text;
...
+BEGIN;
+    SET LOCAL citus.multi_shard_modify_mode TO 'sequential';
+    SELECT COUNT(*) FROM bar.test;
+ count
+---------------------------------------------------------------------
+     9
+(1 row)
+
+    ALTER SCHEMA bar RENAME TO foo;
+ROLLBACK;
```
Comment (thanodnl) [inline src/test/regress/expected/multi_schema_support.out:1496]: 🎉

**Review by thanodnl — APPROVED** [review]
