### PR TITLE
Stop background daemon before dropping the database

### LINKED ISSUE #5297: Make sure to stop maintenance daemon of the database being dropped if Citus created
Reported by a slack user.

We already stop the maintenance daemon when executing a `DROP DATABASE` command, if the database itself has Citus extension created already.
However, if we are trying to drop that database from another one which doesn't have Citus extension created, then we don't care about the maintenance daemon so throwing the following error:

```
psql -p 10700 -d citus_not_created

drop database citus_created;
ERROR:  database "citus_created" is being accessed by other users
DETAIL:  There is 1 other session using the database.
```

### LINKED ISSUE #6670: SQLancer "database is being accessed by other users"
The Citus implementation of SQLancer has been failing for the last couple of months (see https://github.com/sqlancer/sqlancer/issues/698). I just created a PR to ignore a known Citus bug in SQLancer (see https://github.com/sqlancer/sqlancer/pull/706), but the tests still frequently fail with the issue below:

```
org.postgresql.util.PSQLException: ERROR: database "database1" is being accessed by other users
  Detail: There is 1 other session using the database.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
	at sqlancer.citus.CitusProvider.prepareCitusWorkerNodes(CitusProvider.java:374)
	at sqlancer.citus.CitusProvider.createDatabase(CitusProvider.java:426)
	at sqlancer.postgres.PostgresProvider.createDatabase(PostgresProvider.java:1)
	at sqlancer.Main$DBMSExecutor.run(Main.java:347)
	at sqlancer.Main$2.run(Main.java:559)
	at sqlancer.Main$2.runThread(Main.java:541)
	at sqlancer.Main$2.run(Main.java:532)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
--org.postgresql.util.PSQLException: ERROR: database "database1" is being accessed by other users
--  Detail: There is 1 other session using the database.
--	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
--	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
--	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
--	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
--	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
--	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
--	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
--	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
--	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
--	at sqlancer.citus.CitusProvider.prepareCitusWorkerNodes(CitusProvider.java:374)
--	at sqlancer.citus.CitusProvider.createDatabase(CitusProvider.java:426)
--	at sqlancer.postgres.PostgresProvider.createDatabase(PostgresProvider.java:1)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:347)
--	at sqlancer.Main$2.run(Main.java:559)
--	at sqlancer.Main$2.runThread(Main.java:541)
--	at sqlancer.Main$2.run(Main.java:532)
--	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
--	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
--	at java.base/java.lang.Thread.run(Thread.java:829)
--
-- Time: [202](https://github.com/sqlancer/sqlancer/actions/runs/4035273876/jobs/6937078631#step:6:203)3/01/29 05:19:44
-- Database: database1
-- Database version: null
-- seed value: 1
\c test;
DROP DATABASE IF EXISTS database1;
CREATE DATABASE database1 ;
\c database1;
CREATE EXTENSION citus;
\c test;
SELECT * FROM citus_get_active_worker_nodes();
\q;
postgresql://localhost:9701/test;
DROP DATABASE IF EXISTS database1;
CREATE DATABASE database1 ;
```

Any idea what the problem could be and how SQLancer should address it? Most of the Citus implementation was contributed by the Citus team, so I am not that familiar with this part of SQLancer's code and Citus' expected behavior.

### PR DESCRIPTION
**Pull request by gokhangulbiz**
DESCRIPTION: Stop maintenance daemon when dropping a database even without Citus extension

Fixes #6670.
Fixes #5297.

### CODE REVIEW

File: src/backend/distributed/commands/utility_hook.c [hunk 1]
```diff
@@ -219,6 +219,23 @@ multi_ProcessUtility(PlannedStmt *pstmt,
 		PreprocessCreateExtensionStmtForCitusColumnar(parsetree);
 	}
 
+	/*
+	 * Make sure that on DROP DATABASE we terminate the background daemon
+	 * associated with it.
+	 */
+	if (IsA(parsetree, DropdbStmt))
```
Comment (onderkalaci) [inline src/backend/distributed/commands/utility_hook.c:226]: looks like a reasonable change

**Comment by gokhangulbiz** [comment]
thanks to @marcocitus for editing the PR description :) let's merge it if all looks good. /cc @onurctirtir

File: src/test/regress/sql/drop_database.sql [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+CREATE EXTENSION citus;
+
+CREATE DATABASE citus_not_created;
+
+\c citus_not_created
+DROP DATABASE citus_created;
+
+\c regression
+DROP DATABASE citus_not_created;
+
```
Comment (onurctirtir) [inline src/test/regress/sql/drop_database.sql:19]: Can we test the same from a worker node too ?

**Review by onurctirtir — APPROVED** [review]
