### PR TITLE
FIX "mixed declarations and code" Warning in multi_physical_planner.c

### LINKED ISSUE #477: Compile Time "mixed declarations and code" Warning in multi_physical_planner.c
In compilation time, we have a warning about multi_physical_planner:
```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -pg -DLINUX_PROFILE -ggdb -O0 -fno-omit-frame-pointer -fpic -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-missing-field-initializers -Wno-clobbered -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wmissing-declarations -Wmissing-prototypes -I '/home/eren/workspace/citus/src/include' -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE  -I/usr/local/pgsql/include  -c -o planner/multi_physical_planner.o planner/multi_physical_planner.c -MMD -MP -MF .deps/multi_physical_planner.Po

planner/multi_physical_planner.c: In function ‘BuildMapMergeJob’:
planner/multi_physical_planner.c:1741:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   char basePartitionMethod PG_USED_FOR_ASSERTS_ONLY =
```

The mentioned code part is this:

```
...
		if (hasUninitializedShardInterval)
		{
			ereport(ERROR, (errmsg("cannot range repartition shard with "
								   "missing min/max values")));
		}

		/* this join-type currently doesn't work for hash partitioned tables */
		char basePartitionMethod PG_USED_FOR_ASSERTS_ONLY =
			PartitionMethod(baseRelationId);
		Assert(basePartitionMethod != DISTRIBUTE_BY_HASH);

		mapMergeJob->partitionType = RANGE_PARTITION_TYPE;
...
```

### PR DESCRIPTION
**Pull request by aamederen**
Fixes #477

This change fixes the compile time warning message in BuildMapMergeJob in
multi_physical_planner.c about mixed declarations and code. Basically, the
problematic declaration is moved up so that no expression is before it.

### CODE REVIEW

File: src/backend/distributed/planner/multi_physical_planner.c [hunk 1]
```diff
@@ -1729,6 +1729,8 @@ BuildMapMergeJob(Query *jobQuery, List *dependedJobList, Var *partitionKey,
 		bool hasUninitializedShardInterval = false;
 		uint32 shardCount = cache->shardIntervalArrayLength;
 		ShardInterval **sortedShardIntervalArray = cache->sortedShardIntervalArray;
+		char basePartitionMethod PG_USED_FOR_ASSERTS_ONLY =
+					PartitionMethod(baseRelationId);
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_physical_planner.c]: Maybe keep initialization below.

File: src/backend/distributed/planner/multi_physical_planner.c [hunk 2]
```diff
@@ -1729,17 +1729,18 @@ BuildMapMergeJob(Query *jobQuery, List *dependedJobList, Var *partitionKey,
 		bool hasUninitializedShardInterval = false;
 		uint32 shardCount = cache->shardIntervalArrayLength;
 		ShardInterval **sortedShardIntervalArray = cache->sortedShardIntervalArray;
+		char basePartitionMethod PG_USED_FOR_ASSERTS_ONLY;
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_physical_planner.c]: We always initialize variables to 0 on declaration. For char, you can use = 0.

Comment (aamederen) [inline src/backend/distributed/planner/multi_physical_planner.c]: Done :+1:

**Comment by marcocitus** [comment]
:shipit:
