### PR TITLE
Fix vanilla tests with domain creation

### LINKED ISSUE #8042: PG18 - Print out error position for CREATE DOMAIN
PG commit: https://github.com/postgres/postgres/commit/39240bcad56dc51a7896d04a1e066efcf988b58f

```
 create domain d_fail as anyelement;
-ERROR:  "anyelement" is not a valid base type for a domain
+ERROR:  "pg_catalog.anyelement" is not a valid base type for a domain
```

### PR DESCRIPTION
**Pull request by naisila**
Qualify create domain stmt after local execution, to avoid such diffs in PG vanilla tests:

```diff
create domain d_fail as anyelement;
-ERROR:  "anyelement" is not a valid base type for a domain
+ERROR:  "pg_catalog.anyelement" is not a valid base type for a domain
```

These tests were newly added in PG18, however this is not new PG18 behavior, just some added tests.
https://github.com/postgres/postgres/commit/0172b4c94

Fixes #8042

### CODE REVIEW

File: src/backend/distributed/utils/citus_depended_object.c [hunk 1]
```diff
@@ -374,6 +374,17 @@ DistOpsValidityState(Node *node, const DistributeObjectOps *ops)
...
+		if (nodeTag(node) == T_CreateDomainStmt)
+		{
+			/*
+			 * Create Domain statements should be qualified after local creation
+			 * because in case of an error in creation, we don't want to modify
+			 * the statement at all.
+			 */
+			return ShouldQualifyAfterLocalCreation;
+		}
+
```
Comment (colm-mchugh) [inline src/backend/distributed/utils/citus_depended_object.c:386]: nit: is the preceding comment - lines 373 - 376 no longer strictly true with this change ?

Comment (naisila) [reply src/backend/distributed/utils/citus_depended_object.c:386]: Good point. I should modify that comment
