### PR TITLE
Remove call to SchemaNode() in multi_ProcessUtility

### LINKED ISSUE #1170: PostgreSQL regression tests fail with crash
I created a cluster and set shared_preload_libraries to citus, but did not `CREATE EXTENSION`. Then run postgresql regression tests with `make installcheck`. Tests failed with crash at [metadata_cache.c:1680](https://github.com/citusdata/citus/blob/master/src/backend/distributed/utils/metadata_cache.c#L1680).

It is also possible to reproduce the problem with `make check-vanilla`

Crashing line is this;

```c
localGroupTableOid = get_relname_relid("pg_dist_local_group", PG_CATALOG_NAMESPACE);
if (localGroupTableOid == InvalidOid)
{
	return 0;
}
```

I think this line should be OK. We even check for InvalidOid case, but code crashes before reaching that point.

Still I try to add `CitusHasBeenLoaded()` before that line to prevent its execution but this time code crashed  at `CitusHasBeenLoaded()`. More specifically [metadata_cache.c:935](https://github.com/citusdata/citus/blob/master/src/backend/distributed/utils/metadata_cache.c#L935)

I think some problem occurs when we try to reach catalog tables, but I could not figure out the exact problem.

### PR DESCRIPTION
**Pull request by marcocitus**
Fixes #1170

### CODE REVIEW

**Comment by lithp** [comment]
This fixes the immediate problem but I don't think it fixes the root cause. I believe all other utility commands will also fail in this situation (where you're inside an aborted transaction)

**Comment by sumedhpathak** [comment]
@anarazel Could you take a look at this PR? Thanks!

**Comment by anarazel** [comment]
> This fixes the immediate problem but I don't think it fixes the root cause. I believe all other utility commands will also fail in this situation (where you're inside an aborted transaction)

Well, failing is ok, if it's failing gracefully.  Note that only a limited number of commands will reach the utility hook inside an aborted transaction:
```
static void
exec_simple_query(const char *query_string)
{
...
		/*
		 * If we are in an aborted transaction, reject all commands except
		 * COMMIT/ABORT.  It is important that this test occur before we try
		 * to do parse analysis, rewrite, or planning, since all those phases
		 * try to do database accesses, which may fail in abort state. (It
		 * might be safe to allow some additional utility commands in this
		 * state, but not many...)
		 */
		if (IsAbortedTransactionBlockState() &&
			!IsTransactionExitStmt(parsetree->stmt))
			ereport(ERROR,
					(errcode(ERRCODE_IN_FAILED_SQL_TRANSACTION),
					 errmsg("current transaction is aborted, "
						  "commands ignored until end of transaction block"),
					 errdetail_abort()));
```

ISTM, we  should just short circuit transaction stuff in our hook.

**Comment by marcocitus** [comment]
Added the extra check for TransactionStmt.

File: src/backend/distributed/executor/multi_utility.c [hunk 1]
```diff
@@ -296,9 +304,9 @@ multi_ProcessUtility(Node *parsetree,
 									  "move all tables.")));
 		}
 	}
-	else if (!schemaNode)
+	else
```
Comment (anarazel) [inline src/backend/distributed/executor/multi_utility.c]: Isn't the else block entirely superfluous now? I.e. shouldn't the contained if be one layer up?

File: src/backend/distributed/executor/multi_utility.c [hunk 2]
```diff
@@ -170,11 +170,19 @@ multi_ProcessUtility(Node *parsetree,
 					 DestReceiver *dest,
 					 char *completionTag)
 {
-	bool schemaNode = SchemaNode();
 	bool commandMustRunAsOwner = false;
 	Oid savedUserId = InvalidOid;
 	int savedSecurityContext = 0;
 
+	if (IsA(parsetree, TransactionStmt))
```
Comment (anarazel) [inline src/backend/distributed/executor/multi_utility.c]: Maybe add a comment like
```
/*
 * Transaction statements are run in aborted transactions and such - a lot of checks cannot be done safely in that
 * state. Since we never need to intercept transaction statements, short-circuit.
 */
```
instead of the contained one?

Comment (marcocitus) [inline src/backend/distributed/executor/multi_utility.c]: Added a comment.

File: src/backend/distributed/executor/multi_utility.c (hunk 1 above)
Comment (marcocitus) [inline src/backend/distributed/executor/multi_utility.c]: The fact that there is only one such if-block for the case where !EnableDDLPropagation seemed a arbitrary, so I wanted to leave space for more. Added a comment elaborating on our behaviour when citus.enable_ddl_propagation is off right after the else.

**Comment by marcocitus** [comment]
I ended up removing the call to SchemaNode() altogether, since I couldn't see a reason why you would not want to skip validation when you `SET citus.enable_ddl_propagation TO off` on the master, since the SPI query that performs the validation might otherwise pull the whole table contents to the master without any apparent benefit. Also added a regression test.

**Comment by byucesoy** [comment]
> I ended up removing the call to SchemaNode() altogether, since I couldn't see a reason why you would not want to skip validation when you SET citus.enable_ddl_propagation TO off on the master, since the SPI query that performs the validation might otherwise pull the whole table contents to the master without any apparent benefit. Also added a regression test.

Agreed. It is OK to completely remove SchemaNode() check for this case.
