### PR TITLE
Fix permissions checks in UDFs called from the drop table trigger

### LINKED ISSUE #2274: master_drop_sequences should connect as current user
We use `master_drop_sequences` to drop sequences from worker nodes in an MX set-up, because the sequences are created separately from the tables. Currently, the coordinator connects to the worker nodes as superuser, but it should connect as the current user to avoid dropping a sequence that the user is not allowed to drop.

### PR DESCRIPTION
**Pull request by onderkalaci**
Not fixes #2274 as described in the issue, but addresses in another way, similar to how drop table is handled.

In MX, we allow unauthorized users to drop (or at least mess up) tables/sequences. This PR prevents that.

I'm assigning @marcocitus since he asked for the change. But, feel to re-assign to @metdos if you're not avaliable.

### CODE REVIEW

File: src/backend/distributed/master/master_delete_protocol.c [hunk 1]
```diff
@@ -268,12 +269,13 @@ master_drop_sequences(PG_FUNCTION_ARGS)
 	Datum sequenceText = 0;
 	bool isNull = false;
 	StringInfo dropSeqCommand = makeStringInfo();
-	bool coordinator = IsCoordinator();
 
 	CheckCitusVersion(ERROR);
 
-	/* do nothing if DDL propagation is switched off or this is not the coordinator */
-	if (!EnableDDLPropagation || !coordinator)
+	EnsureCoordinator();
```
Comment (marcocitus) [inline src/backend/distributed/master/master_delete_protocol.c]: I think this function always gets called when anything is dropped on Postgres, so that's why we don't want an explicit error.

Comment (onderkalaci) [reply src/backend/distributed/master/master_delete_protocol.c]: Makes sense, I'll undo that and add a test.

Comment (onderkalaci) [reply src/backend/distributed/master/master_delete_protocol.c]: Should be ready for review again.
