### PR TITLE
Fix handling of empty intermediate results when distributing custom aggregates

### LINKED ISSUE #3219: Aggregate result of empty set should be initcond
Postgres returns `initcond`'s value when there are no input tuples, but our custom aggregate implementation returns `NULL`.

### PR DESCRIPTION
**Pull request by serprex**
DESCRIPTION: Fix empty intermediate results returning `NULL` when distributing custom aggregates

This leverages `AggGetAggref` to pull the first argument's value. If a user is directly using these aggregates they may not be passing a constant, in that case we continue to return `NULL`

The issue went deeper than I'd initially assessed. `NULL`s were being returned from shards without intermediate results, which could taint the whole result set. This is what causes the change to the `FILTER` test results

Fixes #3219

### CODE REVIEW

File: src/backend/distributed/utils/aggregate_utils.c [hunk 1]
```diff
@@ -171,27 +194,55 @@ InitializeStypeBox(FunctionCallInfo fcinfo, StypeBox *box, HeapTuple aggTuple, O
...
+ * when we receive no intermediate rows.
+ *
+ * Returns NULL if the Aggref isn't our expected shape.
+ */
+static StypeBox *
+TryCreateStypeBoxFromFcinfoAggref(FunctionCallInfo fcinfo)
+{
+	Aggref *aggref = AggGetAggref(fcinfo);
+	if (aggref != NULL && aggref->args != NIL)
+	{
```
Comment (marcocitus) [inline src/backend/distributed/utils/aggregate_utils.c]: Would be nice to do early returns.

File: src/test/regress/expected/aggregate_support.out [hunk 2]
```diff
@@ -75,11 +75,11 @@ select key, sum2(val) filter (where valf < 5), sum2_strict(val) filter (where va
  key | sum2 | sum2_strict 
 -----+------+-------------
    1 |      |            
-   2 |      |          10
-   3 |      |            
-   5 |      |            
-   6 |      |            
-   7 |      |            
+   2 |   10 |          10
```
Comment (marcocitus) [inline src/test/regress/expected/aggregate_support.out]: hmz, why was this NULL before?

Comment (serprex) [reply src/test/regress/expected/aggregate_support.out]: Workers returned `NULL` instead of `0` when there were no rows passing filter, which then caused `NULL` to be combined instead of `0`
