### PR TITLE
PG18 - Assert("HaveRegisteredOrActiveSnapshot() fix for cluster creation

### LINKED ISSUE #8055: PG18 - PGXX install check failure
https://github.com/citusdata/citus/actions/runs/16264240287/job/45916335384

```
Run gosu circleci make -C src/test/cdc installcheck
make: Entering directory '/__w/citus/citus/src/test/cdc'
rm -rf '/__w/citus/citus/src/test/cdc'/tmp_check
/bin/mkdir -p '/__w/citus/citus/src/test/cdc'/tmp_check
cd ./ && TESTDIR='/__w/citus/citus/src/test/cdc' PATH="/usr/lib/postgresql/15/bin:$PATH" PGPORT='65432' top_builddir='/__w/citus/citus/src/test/cdc//usr/lib/postgresql/15/lib/pgxs/src/makefiles/../..' PG_REGRESS='/usr/lib/postgresql/15/lib/pgxs/src/test/regress/pg_regress' TEMP_CONFIG='/__w/citus/citus/src/test/cdc'/postgresql.conf /usr/bin/prove -I /usr/lib/postgresql/15/lib/pgxs/src/makefiles/../../src/test/perl/ -I ./  t/*.pl
Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains: ./t /usr/lib/postgresql/15/lib/pgxs/src/makefiles/../../src/test/perl /__w/citus/citus/src/test/cdc /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at t/cdctestlib.pm line 15.

```

need to install the system Perl DBI inside the container before running make installcheck.

`apt-get install -y libdbi-perl libdbd-pg-perl`

### LINKED ISSUE #8072: PG18 - Assert("HaveRegisteredOrActiveSnapshot()
https://github.com/postgres/postgres/commit/706054b11b959c865c0c7935c34d92370d7168d4

```
TRAP: failed Assert("HaveRegisteredOrActiveSnapshot()"), File: "heapam.c", Line: 232, PID: 75572
postgres: citus citus [local] SELECT(ExceptionalCondition+0x6e)[0x5585e16123e6]
postgres: citus citus [local] SELECT(heap_insert+0x220)[0x5585e10709af]
postgres: citus citus [local] SELECT(simple_heap_insert+0x33)[0x5585e1071a20]
postgres: citus citus [local] SELECT(CatalogTupleInsert+0x32)[0x5585e1135843]
/home/citus/.pgenv/pgsql-18beta2/lib/citus.so(+0x11e0aa)[0x7fa26f1ca0aa]
/home/citus/.pgenv/pgsql-18beta2/lib/citus.so(+0x11b607)[0x7fa26f1c7607]
/home/citus/.pgenv/pgsql-18beta2/lib/citus.so(+0x11bf25)[0x7fa26f1c7f25]
/home/citus/.pgenv/pgsql-18beta2/lib/citus.so(+0x11d4e2)[0x7fa26f1c94e2]
postgres: citus citus [local] SELECT(+0x1c267d)[0x5585e10e967d]
postgres: citus citus [local] SELECT(+0x1c6ba0)[0x5585e10edba0]
postgres: citus citus [local] SELECT(+0x1c7b80)[0x5585e10eeb80]
postgres: citus citus [local] SELECT(CommitTransactionCommand+0xd)[0x5585e10eef0a]
postgres: citus citus [local] SELECT(+0x575b3d)[0x5585e149cb3d]
postgres: citus citus [local] SELECT(+0x5788ce)[0x5585e149f8ce]
postgres: citus citus [local] SELECT(PostgresMain+0xae7)[0x5585e14a2088]
postgres: citus citus [local] SELECT(BackendMain+0x51)[0x5585e149ab36]
postgres: citus citus [local] SELECT(postmaster_child_launch+0x101)[0x5585e13d6b32]
postgres: citus citus [local] SELECT(+0x4b273f)[0x5585e13d973f]
postgres: citus citus [local] SELECT(+0x4b49f3)[0x5585e13db9f3]
postgres: citus citus [local] SELECT(PostmasterMain+0x1089)[0x5585e13dcee2]
postgres: citus citus [local] SELECT(main+0x1d7)[0x5585e12e3428]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7fa271421d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7fa271421e40]

```

### PR DESCRIPTION
**Pull request by m3hm3t**
fixes #8072 
fixes #8055 

https://github.com/postgres/postgres/commit/706054b11b959c865c0c7935c34d92370d7168d4

before fix

when try to create cluster with assert on

`citus_dev make test1 --destroy`

```
TRAP: failed Assert("HaveRegisteredOrActiveSnapshot()"), File: "heapam.c", Line: 232, PID: 75572
postgres: citus citus [local] SELECT(ExceptionalCondition+0x6e)[0x5585e16123e6]
postgres: citus citus [local] SELECT(heap_insert+0x220)[0x5585e10709af]
postgres: citus citus [local] SELECT(simple_heap_insert+0x33)[0x5585e1071a20]
postgres: citus citus [local] SELECT(CatalogTupleInsert+0x32)[0x5585e1135843]
/home/citus/.pgenv/pgsql-18beta2/lib/citus.so(+0x11e0aa)[0x7fa26f1ca0aa]
/home/citus/.pgenv/pgsql-18beta2/lib/citus.so(+0x11b607)[0x7fa26f1c7607]
/home/citus/.pgenv/pgsql-18beta2/lib/citus.so(+0x11bf25)[0x7fa26f1c7f25]
/home/citus/.pgenv/pgsql-18beta2/lib/citus.so(+0x11d4e2)[0x7fa26f1c94e2]
postgres: citus citus [local] SELECT(+0x1c267d)[0x5585e10e967d]
postgres: citus citus [local] SELECT(+0x1c6ba0)[0x5585e10edba0]
postgres: citus citus [local] SELECT(+0x1c7b80)[0x5585e10eeb80]
postgres: citus citus [local] SELECT(CommitTransactionCommand+0xd)[0x5585e10eef0a]
postgres: citus citus [local] SELECT(+0x575b3d)[0x5585e149cb3d]
postgres: citus citus [local] SELECT(+0x5788ce)[0x5585e149f8ce]
postgres: citus citus [local] SELECT(PostgresMain+0xae7)[0x5585e14a2088]
postgres: citus citus [local] SELECT(BackendMain+0x51)[0x5585e149ab36]
postgres: citus citus [local] SELECT(postmaster_child_launch+0x101)[0x5585e13d6b32]
postgres: citus citus [local] SELECT(+0x4b273f)[0x5585e13d973f]
postgres: citus citus [local] SELECT(+0x4b49f3)[0x5585e13db9f3]
postgres: citus citus [local] SELECT(PostmasterMain+0x1089)[0x5585e13dcee2]
postgres: citus citus [local] SELECT(main+0x1d7)[0x5585e12e3428]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7fa271421d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7fa271421e40]

```

### CODE REVIEW

File: src/include/distributed/metadata_utility.h [hunk 1]
```diff
@@ -301,6 +304,29 @@ typedef struct BackgroundTask
...
+
+#else
+
+/* no-op wrapper on older PGs */
+#define CATALOG_INSERT_WITH_SNAPSHOT(rel, tup) \
+	CatalogTupleInsert((rel), (tup))
+
+#endif
+
+
```
Comment (naisila) [inline src/include/distributed/metadata_utility.h]: Better to move this to pg_version_compat file

Comment (m3hm3t) [reply src/include/distributed/metadata_utility.h]: moved

**Review by naisila — APPROVED** [review]
LGTM. Reminder to revert first commit before merging.

**Comment by Green-Chan** [comment]
Hi! Since https://github.com/postgres/postgres/commit/706054b11b959c865c0c7935c34d92370d7168d4 was backpatched to older versions, you're going to need this fix not only for PG18, but for other versions as well. I've just run tests for REL_16_10 + release-12.1 and they are failing with the same assertion
