### PR TITLE
return early in case we want to skip outer vars

### LINKED ISSUE #5248: Crash found on SQLSmith, not investigated yet
With: [schema.sql](https://gist.github.com/agedemenli/f3bae82e19e18558a4e294723bd9155f)
Query:
```sql
select  
  subq_3.c15 as c0, 
  subq_3.c0 as c1, 
  subq_3.c15 as c2, 
  subq_0.c1 as c3, 
  
    pg_catalog.string_agg(
      cast((select tgargs from pg_catalog.pg_trigger limit 1 offset 1)
         as bytea),
      cast((select minimum_value from columnar.chunk limit 1 offset 5)
         as bytea)) over (partition by subq_3.c10 order by subq_3.c12,subq_0.c2) as c4, 
  subq_0.c1 as c5
from 
  (select  
        ref_1.address as c0, 
        ref_1.error as c1, 
        sample_0.name as c2, 
        sample_2.trftosql as c3
      from 
        pg_catalog.pg_statio_all_sequences as ref_0
            inner join pg_catalog.pg_hba_file_rules as ref_1
            on ((select pg_catalog.max(aggnumdirectargs) from pg_catalog.pg_aggregate)
                   <= ref_0.blks_hit)
          inner join public.countries_102329 as sample_0 tablesample system (6.4) 
              inner join public.local_data as sample_1 tablesample bernoulli (8) 
              on ((true) 
                  or (sample_0.name is not NULL))
            inner join pg_catalog.pg_transform as sample_2 tablesample bernoulli (1.2) 
                inner join pg_catalog.pg_language as ref_2
                on ((select shard_cost_function from pg_catalog.pg_dist_rebalance_strategy limit 1 offset 1)
                       is NULL)
              right join pg_catalog.pg_index as sample_3 tablesample system (0.3) 
              on ((cast(null as bpchar) ~<=~ cast(null as bpchar)) 
                  or ((EXISTS (
                      select  
                          sample_3.indnkeyatts as c0, 
                          sample_2.trflang as c1, 
                          sample_2.trftype as c2
                        from 
                          pg_catalog.pg_statistic_ext as sample_4 tablesample bernoulli (8.6) 
                        where sample_2.trftype is not NULL)) 
                    and (false)))
            on (EXISTS (
                select  
                    sample_0.id as c0, 
                    sample_3.indisprimary as c1
                  from 
                    public.orgs as sample_5 tablesample system (5.3) 
                  where false))
          on (cast(null as float8) > (select pg_catalog.avg(enumsortorder) from pg_catalog.pg_enum)
                )
      where cast(coalesce(case when ref_1.auth_method ~>=~ ref_1.auth_method then cast(null as path) else cast(null as path) end
            ,
          cast(null as path)) as path) = cast(null as path)) as subq_0,
  lateral (select  
        (select pg_catalog.stddev(total_time) from pg_catalog.pg_stat_user_functions)
           as c0, 
        subq_0.c1 as c1, 
        subq_2.c0 as c2, 
        subq_0.c2 as c3, 
        subq_0.c0 as c4, 
        cast(coalesce(subq_2.c0,
          subq_2.c0) as text) as c5, 
        subq_2.c0 as c6, 
        subq_2.c1 as c7, 
        subq_2.c1 as c8, 
        subq_2.c1 as c9, 
        subq_0.c3 as c10, 
        pg_catalog.pg_stat_get_db_temp_files(
          cast((select objoid from pg_catalog.pg_description limit 1 offset 1)
             as oid)) as c11, 
        subq_0.c3 as c12, 
        subq_2.c1 as c13, 
        subq_0.c0 as c14, 
        subq_0.c3 as c15, 
        subq_0.c3 as c16, 
        subq_0.c1 as c17, 
        subq_0.c2 as c18
      from 
        (select  
              subq_1.c2 as c0, 
              subq_0.c3 as c1
            from 
              information_schema.element_types as ref_3,
              lateral (select  
                    subq_0.c1 as c0, 
                    sample_6.info as c1, 
                    subq_0.c2 as c2, 
                    subq_0.c3 as c3, 
                    ref_3.domain_default as c4, 
                    sample_6.user_id as c5, 
                    ref_3.collation_name as c6
                  from 
                    public.orders as sample_6 tablesample system (3.8) 
                  where sample_6.price = sample_6.org_id
                  limit 58) as subq_1
            where (subq_1.c2 <= subq_0.c2) 
              and (cast(null as line) ?-| cast(null as line))
            limit 59) as subq_2
      where cast(coalesce(pg_catalog.age(
            cast((select pg_catalog.max(event_time) from public.events)
               as "timestamp")),
          (select write_lag from pg_catalog.pg_stat_replication limit 1 offset 3)
            ) as "interval") > (select utc_offset from pg_catalog.pg_timezone_names limit 1 offset 4)
          
      limit 91) as subq_3
where pg_catalog.pg_stop_backup() > cast(null as pg_lsn)
limit 100;
```

Call stack:
```
libc.so.6!__GI_raise(int sig) (\build\glibc-S9d2JN\glibc-2.27\sysdeps\unix\sysv\linux\raise.c:51)
libc.so.6!__GI_abort() (\build\glibc-S9d2JN\glibc-2.27\stdlib\abort.c:79)
ExceptionalCondition(const char * conditionName, const char * errorType, const char * fileName, int lineNumber) (\home\ahmet\.pgenv\src\postgresql-14beta3\src\backend\utils\error\assert.c:69)
citus.so!list_nth_cell(int n, const List * list) (\home\ahmet\.pgenv\pgsql-14beta3\include\server\nodes\pg_list.h:259)
citus.so!list_nth(int n, const List * list) (\home\ahmet\.pgenv\pgsql-14beta3\include\server\nodes\pg_list.h:281)
citus.so!FindReferencedTableColumn(Expr * columnExpression, List * parentQueryList, Query * query, Var ** column, RangeTblEntry ** rteContainingReferencedColumn, _Bool skipOuterVars) (\home\ahmet\citus\src\backend\distributed\planner\multi_logical_optimizer.c:4524)
citus.so!FindReferencedTableColumn(Expr * columnExpression, List * parentQueryList, Query * query, Var ** column, RangeTblEntry ** rteContainingReferencedColumn, _Bool skipOuterVars) (\home\ahmet\citus\src\backend\distributed\planner\multi_logical_optimizer.c:4529)
citus.so!IsPartitionColumn(Expr * columnExpression, Query * query, _Bool skipOuterVars) (\home\ahmet\citus\src\backend\distributed\planner\multi_logical_optimizer.c:4408)
citus.so!PartitionColumnForPushedDownSubquery(Query * query) (\home\ahmet\citus\src\backend\distributed\planner\query_pushdown_planning.c:1840)
citus.so!MultiSubqueryPushdownTable(Query * subquery) (\home\ahmet\citus\src\backend\distributed\planner\query_pushdown_planning.c:1808)
citus.so!SubqueryPushdownMultiNodeTree(Query * originalQuery) (\home\ahmet\citus\src\backend\distributed\planner\query_pushdown_planning.c:1631)
citus.so!SubqueryMultiNodeTree(Query * originalQuery, Query * queryTree, PlannerRestrictionContext * plannerRestrictionContext) (\home\ahmet\citus\src\backend\distributed\planner\query_pushdown_planning.c:527)
citus.so!MultiLogicalPlanCreate(Query * originalQuery, Query * queryTree, PlannerRestrictionContext * plannerRestrictionContext) (\home\ahmet\citus\src\backend\distributed\planner\multi_logical_planner.c:152)
citus.so!CreateDistributedPlan(uint64 planId, Query * originalQuery, Query * query, ParamListInfo boundParams, _Bool hasUnresolvedParams, PlannerRestrictionContext * plannerRestrictionContext) (\home\ahmet\citus\src\backend\distributed\planner\distributed_planner.c:1036)
citus.so!CreateDistributedPlan(uint64 planId, Query * originalQuery, Query * query, ParamListInfo boundParams, _Bool hasUnresolvedParams, PlannerRestrictionContext * plannerRestrictionContext) (\home\ahmet\citus\src\backend\distributed\planner\distributed_planner.c:1008)
citus.so!CreateDistributedPlannedStmt(DistributedPlanningContext * planContext) (\home\ahmet\citus\src\backend\distributed\planner\distributed_planner.c:656)
citus.so!PlanDistributedStmt(DistributedPlanningContext * planContext, int rteIdCounter) (\home\ahmet\citus\src\backend\distributed\planner\distributed_planner.c:593)
citus.so!distributed_planner(Query * parse, const char * query_string, int cursorOptions, ParamListInfo boundParams) (\home\ahmet\citus\src\backend\distributed\planner\distributed_planner.c:229)
pg_stat_statements.so!pgss_planner(Query * parse, const char * query_string, int cursorOptions, ParamListInfo boundParams) (\home\ahmet\.pgenv\src\postgresql-14beta3\contrib\pg_stat_statements\pg_stat_statements.c:946)
planner(Query * parse, const char * query_string, int cursorOptions, ParamListInfo boundParams) (\home\ahmet\.pgenv\src\postgresql-14beta3\src\backend\optimizer\plan\planner.c:269)
pg_plan_query(Query * querytree, const char * query_string, int cursorOptions, ParamListInfo boundParams) (\home\ahmet\.pgenv\src\postgresql-14beta3\src\backend\tcop\postgres.c:847)
pg_plan_queries(List * querytrees, const char * query_string, int cursorOptions, ParamListInfo boundParams) (\home\ahmet\.pgenv\src\postgresql-14beta3\src\backend\tcop\postgres.c:939)
exec_simple_query(const char * query_string) (\home\ahmet\.pgenv\src\postgresql-14beta3\src\backend\tcop\postgres.c:1133)
PostgresMain(int argc, char ** argv, const char * dbname, const char * username) (\home\ahmet\.pgenv\src\postgresql-14beta3\src\backend\tcop\postgres.c:4486)
BackendRun(Port * port) (\home\ahmet\.pgenv\src\postgresql-14beta3\src\backend\postmaster\postmaster.c:4506)
BackendStartup(Port * port) (\home\ahmet\.pgenv\src\postgresql-14beta3\src\backend\postmaster\postmaster.c:4228)
ServerLoop() (\home\ahmet\.pgenv\src\postgresql-14beta3\src\backend\postmaster\postmaster.c:1745)
PostmasterMain(int argc, char ** argv) (\home\ahmet\.pgenv\src\postgresql-14beta3\src\backend\postmaster\postmaster.c:1417)
main(int argc, char ** argv) (\home\ahmet\.pgenv\src\postgresql-14beta3\src\backend\main\main.c:209)
```

### PR DESCRIPTION
**Pull request by SaitTalhaNisanci**
(I don't think we need a DESCRIPTION line because the bug was never released)

We can possibly shorten the query as it is very long, but I also like that it contains many things

Fixes #5248

### CODE REVIEW

File: src/backend/distributed/planner/multi_logical_optimizer.c [hunk 1]
```diff
@@ -4468,34 +4468,46 @@ FindReferencedTableColumn(Expr *columnExpression, List *parentQueryList, Query *
...
-	 * in the subquery that is referred from the outer query.
-	 */
-	if (candidateColumn->varlevelsup > 0 && !skipOuterVars)
+
+	if (candidateColumn->varlevelsup > 0)
 	{
-		int parentQueryIndex = list_length(parentQueryList) -
-							   candidateColumn->varlevelsup;
-		if (!(IsIndexInRange(parentQueryList, parentQueryIndex)))
+		if (!skipOuterVars)
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_logical_optimizer.c:4474]: Minor: I find single level indentation simpler to follow, what do you think?


```C
if (candidateColumn->varlevelsup > 0 && skipOuterVars)
{
/* caller doesn't want to process*/
   return;
}
else if (candidateColumn->varlevelsup > 0 && !skipOuterVars)
{
... do thnigs .. 
}
```

**Review by onderkalaci — APPROVED** [review]
I think it is fine that the test has a failing query

File: src/backend/distributed/planner/multi_logical_optimizer.c (hunk 1 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/multi_logical_optimizer.c:4474]: umm, I didn't want to write `candidateColumn->varlevelsup > 0` twice.

What about this so that there is single level indendation for the main logic?:

```c
if (candidateColumn->varlevelsup > 0){
   if (skipOuterVars) {
      /* caller doesn't want to process*/
   return;
   }
   ... do things ....
}
```

Comment (onderkalaci) [reply src/backend/distributed/planner/multi_logical_optimizer.c:4474]: Yes, this looks nicer, thanks
