### PR TITLE
Fix pushing down wrong queries for INSERT ... SELECT queries

### LINKED ISSUE #1241: INSERT ... SELECT may push down JOINs on non-partition columns
Let me start with a background information. @ozgune asked me to investigate subquery pushdown changes for v6.2. First, I considered applying the logic that we've implemented for `INSERT ... SELECT` changes. During the investigation, I've found a bug / problem with that approach. Below, I share my findings.

To let you follow the issue easily, I created a gist file. As a starting point, to reproduce the bug with the current master branch see [here](https://gist.github.com/onderkalaci/47aea936356f69e5ad20280dff3584f5#file-part_1-sql-L1).

**The description of the problem:** Joins are on non-partition column for `table_3`, but we still allow the query to push down. That could easily lead to wrong results.

**The essence of the problem:** For Postgres, it is safe to distribute quals that are on the joining columns of the table for LEFT/INNER JOINs. I think this [line](https://github.com/postgres/postgres/blob/215b43cdc8d6b4a1700886a39df1ee735cb0274d/src/backend/optimizer/path/equivclass.c#L1466) in the function comment of [`reconsider_outer_join_clauses()` ](https://github.com/postgres/postgres/blob/215b43cdc8d6b4a1700886a39df1ee735cb0274d/src/backend/optimizer/path/equivclass.c#L1532) could explain the situation better than me. Also, note that we have the same problem on equi-joins as well. The problem here is that we shouldn't let this happen unless the tables are JOINed on the partition column.

Details of the problem for `INSERT ... SELECT` implementation:

* Assume we have the following query as the tables are defined on the gist:
  
```SQL
INSERT INTO table_1 (key)
SELECT table_2.key FROM table_2 INNER JOIN table_3 ON (table_2.key = table_3.value);
```

* We find a partition column from the SELECT target list. In this specific case, it is table_2.key
```SQL
INSERT INTO table_1 (key)
SELECT table_2.key FROM table_2 INNER JOIN table_3 ON (table_2.key = table_3.value);
```
* Then, we create a qual in the following form and add to the subquery: (table_2.key = $1)
```SQL  
INSERT INTO table_1 (key)
SELECT table_2.key FROM table_2 INNER JOIN table_3 ON (table_2.key = table_3.value)
WHERE  (table_2.key = $1);
```

Later, we allow standard planner to distribute this qual hen necessary and we end-up with the following (I ensured that with gdb)

As far as I could follow the PostgreSQL source code, the logic is the following: 
* The query has the following join: (table_2.key = table_3.value)
* The query has the following qual:  (table_2.key = $1) 
* Since the qual has (column = const), I could distribute this since the output would always have (table_3.value = $1) as well
* Add the following qual as well: (table_3.value = $1)
 ```SQL
INSERT INTO table_1 (key)
SELECT table_2.key FROM table_2 INNER JOIN table_3 ON (table_2.key = table_3.value)
WHERE  (table_2.key = $1) AND (table_3.value = $1);
```

Finally, we replace OpExpr's with `$1` to `(shardMinValue >= targetShardMinValue && shardMaxValue<= targetShardMaxValue)` and use the shard pruning logic. As you could see, this can easily lead to problems. We replace `(table_3.value = $1)` with shard min/max values as well.

### PR DESCRIPTION
**Pull request by onderkalaci**
(This PR should be back-ported to both 6.0 and 6.1)

Fixes #1241, and since a better approach than #1243 I'm closing it.

Before this commit, in certain cases router planner allowed pushing
down JOINs that are not on the partition keys.

With @anarazel's suggestion, we change the logic to use uninstantiated
parameter. Previously, the planner was traversing on the restriction
information and once it finds the parameter, it was replacing it with
the shard range. With this commit, instead of traversing the restrict
infos, the planner explicitly checks for the equivalence of the relation
partition key with the uninstantiated parameter. If finds an equivalence,
it adds the restrictions. In this way, we have more control over the
queries that are pushed down.

### CODE REVIEW

File: src/backend/distributed/planner/multi_router_planner.c [hunk 1]
```diff
@@ -377,19 +380,43 @@ RouterModifyTaskForShardInterval(Query *originalQuery, ShardInterval *shardInter
...
+		hashedOpExpressions = HashedShardIntervalOpExpressions(shardInterval);
+		Assert(list_length(hashedOpExpressions) == 2);
+
+		/*
+		 * Here we check whether the planner knows an equality between the partition column
+		 * and the uninstantiated parameter. If such an equality exists, we simply add the
+		 * shard restrictions.
+		 */
+		uninstantiatedParameter = UninstantiatedParameterForColumn(relationPartitionKey);
+		if (exprs_known_equal(restriction->plannerInfo, (Node *) relationPartitionKey,
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_router_planner.c]: In his suggestion, @anarazel asked for the following:
> Instead of iterating baserestrictinfo like we currently do, we need a
routine very similar to equivclass.c's exprs_known_equal().  With a
version that additionally checks that EquivalenceClass->ec_relids
contains the current to-be-pruned relation

But, as far as I can see, we could directly use `exprs_known_equal()` given that Partition key already includes the correct varno and thus ensures that it belongs to the relation that is to-be-pruned (via the `equal` call in the `exprs_known_equal ()`).

Do you see any problems with using `exprs_known_equal ()` ?

File: src/backend/distributed/planner/multi_router_planner.c [hunk 2]
```diff
@@ -489,6 +516,98 @@ RouterModifyTaskForShardInterval(Query *originalQuery, ShardInterval *shardInter
...
+ * items in it. The list consists of shard interval ranges with hashed columns
+ * such as (hashColumn >= shardMinValue) and (hashedColumn <= shardMaxValue).
+ *
+ * The function errors out if the given shard interval does not belong to a hash
+ * distributed table.
+ */
+static List *
+HashedShardIntervalOpExpressions(ShardInterval *shardInterval)
+{
+	List *operatorExpressions = NIL;
```
Comment (metdos) [inline src/backend/distributed/planner/multi_router_planner.c]: Minor. Maybe reorder variable declaritions;

```C
	List *operatorExpressions = NIL;
	Var *hashedGEColumn = NULL;
	Var *hashedLEColumn = NULL;
	OpExpr *hashedGEOpExpr = NULL;
	OpExpr *hashedLEOpExpr = NULL;
	Oid integer4GEoperatorId = InvalidOid;
	Oid integer4LEoperatorId = InvalidOid;

	Datum shardMinValue = shardInterval->minValue;
	Datum shardMaxValue = shardInterval->maxValue;
```

File: src/backend/distributed/planner/multi_router_planner.c [hunk 3]
```diff
@@ -489,6 +516,98 @@ RouterModifyTaskForShardInterval(Query *originalQuery, ShardInterval *shardInter
...
+	Datum shardMinValue = shardInterval->minValue;
+
+	Var *hashedLEColumn = NULL;
+	OpExpr *hashedLEOpExpr = NULL;
+	Datum shardMaxValue = shardInterval->maxValue;
+
+	Oid integer4GEoperatorId = InvalidOid;
+	Oid integer4LEoperatorId = InvalidOid;
+
+	if (PartitionMethod(shardInterval->relationId) != DISTRIBUTE_BY_HASH)
```
Comment (metdos) [inline src/backend/distributed/planner/multi_router_planner.c]: I think we prefer separate lines;
```C
	char partitionMethod = PartitionMethod(shardInterval->relationId);
	if (partitionMethod != DISTRIBUTE_BY_HASH)
```

File: src/backend/distributed/planner/multi_router_planner.c [hunk 4]
```diff
@@ -489,6 +516,98 @@ RouterModifyTaskForShardInterval(Query *originalQuery, ShardInterval *shardInter
...
+	{
+		ereport(ERROR, (errcode(ERRCODE_INVALID_PARAMETER_VALUE),
+						errmsg("cannot created shard interval operator expression for "
+							   "distributed relations other than hash distributed "
+							   "relations")));
+	}
+
+	/* get the integer >=, <= operators from the catalog */
+	integer4GEoperatorId = get_opfamily_member(INTEGER_BTREE_FAM_OID, INT4OID,
```
Comment (metdos) [inline src/backend/distributed/planner/multi_router_planner.c]: These are fit in two lines;
```C
	integer4GEoperatorId = get_opfamily_member(INTEGER_BTREE_FAM_OID, INT4OID,
											   INT4OID, BTGreaterEqualStrategyNumber);
	integer4LEoperatorId = get_opfamily_member(INTEGER_BTREE_FAM_OID, INT4OID,
											   INT4OID, BTLessEqualStrategyNumber);
```

Comment (metdos) [inline src/backend/distributed/planner/multi_router_planner.c]: Probably, this is more readable;

```C
	integer4GEoperatorId = get_opfamily_member(INTEGER_BTREE_FAM_OID, INT4OID, INT4OID,
											   BTGreaterEqualStrategyNumber);
	integer4LEoperatorId = get_opfamily_member(INTEGER_BTREE_FAM_OID, INT4OID, INT4OID,
											   BTLessEqualStrategyNumber);
```

File: src/backend/distributed/planner/multi_router_planner.c [hunk 5]
```diff
@@ -489,6 +516,98 @@ RouterModifyTaskForShardInterval(Query *originalQuery, ShardInterval *shardInter
...
+	hashedLEOpExpr->opfuncid = get_opcode(hashedLEOpExpr->opno);
+	hashedLEOpExpr->opresulttype = get_func_rettype(hashedLEOpExpr->opfuncid);
+	operatorExpressions = lappend(operatorExpressions, hashedLEOpExpr);
+
+	return operatorExpressions;
+}
+
+
+/*
+ * Returns a Param that can be used as an uninstantiated parameter for the given
```
Comment (metdos) [inline src/backend/distributed/planner/multi_router_planner.c]: Minor. We add function name to the comment. UninstantiatedParameterForColumn returns ...

File: src/backend/distributed/planner/multi_router_planner.c [hunk 6]
```diff
@@ -489,6 +516,98 @@ RouterModifyTaskForShardInterval(Query *originalQuery, ShardInterval *shardInter
...
+ * column in the sense that paramtype, paramtypmod and collid is set to the input
```
Comment (metdos) [inline src/backend/distributed/planner/multi_router_planner.c]: Can we also note that the use of UNINSTANTIATED_PARAMETER_ID is important here?

We also use the same code snippet in AddUninstantiatedEqualityQual(). Can we also use this function there?

**Comment by metdos** [comment]
@onderkalaci these changes look good. I have minor style comments, feel free to skip them. Just could you make changes related UNINSTANTIATED_PARAMETER_ID and using UninstantiatedParameterForColumn() also in AddUninstantiatedEqualityQual()?

And kudos for extended regression tests.

I think after getting okay from @anarazel on his question, we can ship this.

File: src/backend/distributed/planner/multi_router_planner.c (hunk 2 above)
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_router_planner.c]: Makes sense

File: src/backend/distributed/planner/multi_router_planner.c (hunk 3 above)
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_router_planner.c]: Done

File: src/backend/distributed/planner/multi_router_planner.c (hunk 4 above)
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_router_planner.c]: Blame on `citus_indent` 😅

File: src/backend/distributed/planner/multi_router_planner.c (hunk 6 above)
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_router_planner.c]: > We also use the same code snippet in AddUninstantiatedEqualityQual(). Can we also use this function there?

Oh good catch, I hate duplicate codes. I thought of doing that during the implementation but forgot to do.

File: src/backend/distributed/planner/multi_router_planner.c [hunk 7]
```diff
@@ -543,11 +664,9 @@ AddShardIntervalRestrictionToSelect(Query *subqery, ShardInterval *shardInterval
...
 	Assert(targetPartitionColumnVar != NULL);
 
-	integer4GEoperatorId = get_opfamily_member(INTEGER_BTREE_FAM_OID, INT4OID,
-											   INT4OID,
+	integer4GEoperatorId = get_opfamily_member(INTEGER_BTREE_FAM_OID, INT4OID, INT4OID,
 											   BTGreaterEqualStrategyNumber);
-	integer4LEoperatorId = get_opfamily_member(INTEGER_BTREE_FAM_OID, INT4OID,
-											   INT4OID,
+	integer4LEoperatorId = get_opfamily_member(INTEGER_BTREE_FAM_OID, INT4OID, INT4OID,
 											   BTLessEqualStrategyNumber);
```
Comment (anarazel) [inline src/backend/distributed/planner/multi_router_planner.c]: Why did these lines change?

Comment (onderkalaci) [inline src/backend/distributed/planner/multi_router_planner.c]: Looks like a citus_indent change. I'll update it

**Comment by sumedhpathak** [comment]
@onderkalaci If we have agreement on this approach, is this PR ready to merge?

**Comment by onderkalaci** [comment]
> @onderkalaci If we have agreement on this approach, is this PR ready to merge?

I think this is something the reviewers should answer :) 

The PR follows the approach @anarazel suggested and the approach makes sense to me as well.  @metdos did some review on this PR but no one gave a `shipit` yet.

**Comment by metdos** [comment]
> @metdos did some review on this PR but no one gave a shipit yet.

It looks fine to me, but Andres has a comment so I wanted Andres to make the last call.

As a note, this PR mostly for backport purposes and this code will be changed with upcoming subquery changes. @onderkalaci, could you correct me if I'm wrong?

File: src/backend/distributed/planner/multi_router_planner.c [hunk 8]
```diff
@@ -391,19 +394,43 @@ RouterModifyTaskForShardInterval(Query *originalQuery, ShardInterval *shardInter
...
+		Param *uninstantiatedParameter = NULL;
 
 		/*
-		 * We haven't added the quals if all participating tables are reference
-		 * tables. Thus, now skip instantiating them.
+		 * We don't need to add restriction to reference tables given that they are
+		 * already single sharded and always prune to that single shard.
 		 */
-		if (allReferenceTables)
+		if (!relationPartitionKey)
```
Comment (anarazel) [inline src/backend/distributed/planner/multi_router_planner.c]: I'd slightly prefer testing for this actually being a reference table, rather than nullness of partition column. Seems cleaner.

File: src/backend/distributed/planner/multi_router_planner.c (hunk 1 above)
Comment (anarazel) [inline src/backend/distributed/planner/multi_router_planner.c]: No, it should be ok.  There's some theoretical caveats, but otherwise...

Checking for relids would increase efficiency however - but we can postpone that to the point it's actually a measurable overhead...

File: src/test/regress/expected/multi_insert_select.out [hunk 9]
```diff
@@ -973,115 +1141,577 @@ FROM
...
+DEBUG:  predicate pruning for shardId 13300003
+ERROR:  cannot perform distributed planning for the given modification
+DETAIL:  Select query cannot be pushed down to the worker.
+ 
+ -- same as the above with INNER JOIN
+ INSERT INTO agg_events (user_id)
+ SELECT
+   raw_events_first.user_id
+ FROM
+   raw_events_first INNER JOIN raw_events_second ON raw_events_first.user_id = raw_events_second.value_1;
```
Comment (metdos) [inline src/test/regress/expected/multi_insert_select.out]: I believe you meant `raw_events_first.value_1 = raw_events_second.value_1` here.

Comment (onderkalaci) [inline src/test/regress/expected/multi_insert_select.out]: > I believe you meant raw_events_first.value_1 = raw_events_second.value_1 here.

But we have the same JOIN condition on the above query with a LEFT JOIN?

**Comment by metdos** [comment]
I did the last pass. I have a minor comment on regression tests. After fixing it, we can 🚢  it.

File: src/test/regress/sql/multi_insert_select.sql [hunk 10]
```diff
@@ -496,7 +547,191 @@ FROM
...
+   raw_events_first.user_id
+ FROM
+   raw_events_first LEFT JOIN raw_events_second ON raw_events_first.value_1 = raw_events_second.value_1;
+ 
+ -- same as the above with INNER JOIN
+ INSERT INTO agg_events (user_id)
+ SELECT
+   raw_events_first.user_id
+ FROM
+   raw_events_first INNER JOIN raw_events_second ON raw_events_first.user_id = raw_events_second.value_1;
```
Comment (metdos) [inline src/test/regress/sql/multi_insert_select.sql]: I meant here :)
