### PR TITLE
Fix #7242, CALL(@0) crash backend

### LINKED ISSUE #7242: Citus segfaults and crashes Postgres when calling distributed procedure with a parameterized distribution argument
When calling a distributed function - actually a procedure - with a parameterized distribution argument from outside an explicit transaction, Citus will segfault and crash PostgreSQL. This happens on PostgreSQL 16.0 and Citus 12.1, as well as earlier versions like PG 15 and Citus 11.

**Repro steps:**

First, create the following structure:
```SQL
CREATE TABLE t (phash INT NOT NULL, id UUID NOT NULL, PRIMARY KEY (phash, id));
SELECT create_distributed_table('t', 'phash');

CREATE PROCEDURE p(_phash INT, _id UUID) LANGUAGE plpgsql AS $$
BEGIN
	INSERT INTO t(phash, id) VALUES (_phash, _id);
END; $$;
SELECT create_distributed_function('p(INT, UUID)', distribution_arg_name := '_phash', colocate_with := 't');
```

Then, all you need to do is call the procedure with a distribution argument that is a parameter in the command, like so:

```SQL
CALL p(@0, 'AEDFEB1F-9B1D-40F2-8D03-84BC7DE20C64');
```
where `@0` represents an integer parameter in the command. PostgreSQL will crash, like so:

```
LOG:  server process (PID 760) was terminated by signal 11: Segmentation fault
DETAIL:  Failed process was running: CALL p($1, 'AEDFEB1F-9B1D-40F2-8D03-84BC7DE20C64')
LOG:  terminating any other active server processes
LOG:  all server processes terminated; reinitializing
LOG:  database system was interrupted; last known up at 2023-09-28 03:26:01 UTC
FATAL:  the database system is in recovery mode
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  invalid record length at 0/2513F08: expected at least 24, got 0
...
```

The crash does not occur when the distribution argument is not parameterized, even if other arguments _are_ parameterized:
```SQL
CALL p(123, @0);
```

The crash also does not occur within an explicit transaction:
```SQL
BEGIN;
CALL p(@0, 'AEDFEB1F-9B1D-40F2-8D03-84BC7DE20C64');
COMMIT;
```

The crash also does not occur when the table and procedure are not distributed. This seems to indicate that it's a problem with Citus.

### PR DESCRIPTION
**Pull request by c2main**
When executing a prepared CALL, which is not pure SQL but available with some drivers like npgsql and jpgdbc, Citus entered a code path where a plan is not defined, while trying to increase its cost. Thus SIG11 when plan is a NULL pointer.

Fix by only increasing plan cost when plan is not null.

However, it is a bit suspicious to get here with a NULL plan and maybe a better change will be to not call ShardPlacementForFunctionColocatedWithDistTable() with a NULL plan at all (in call.c:134)

bug hit with for example:
```
CallableStatement proc = con.prepareCall("{CALL p(?)}");
proc.registerOutParameter(1, java.sql.Types.BIGINT);
proc.setInt(1, -100);
proc.execute();
```

where `p(bigint)` is a distributed "function" and the param the distribution key (also in a distributed table), see #7242 for details

Fixes #7242

### CODE REVIEW

**Comment by c2main** [comment]
Oh, and the question is: does citus provides a test framework for testing such corner case ?

File: src/backend/distributed/planner/function_call_delegation.c [hunk 1]
```diff
@@ -526,7 +526,10 @@ ShardPlacementForFunctionColocatedWithDistTable(DistObjectCacheEntry *procedure,
 		if (partitionParam->paramkind == PARAM_EXTERN)
 		{
 			/* Don't log a message, we should end up here again without a parameter */
-			DissuadePlannerFromUsingPlan(plan);
+			if (plan)
```
Comment (JelteF) [inline src/backend/distributed/planner/function_call_delegation.c:529]: I think it's worth updating the comment that sometimes there is no plan at this stage at all yet, for instance when a `CALL` statement is prepared.

Comment (c2main) [reply src/backend/distributed/planner/function_call_delegation.c:534]: yep, applied.

**Review by JelteF — APPROVED** [review]
Thanks for this. Change looks good to me now. (CI might still complain though)

**Comment by JelteF** [comment]
FYI CI complains about some unused imports in the test file

**Comment by c2main** [comment]
> FYI CI complains about some unused imports in the test file, if you fix those I think this is good to merge.

I used other tests as examples...
I removed the "imports" and rebased.

It will also probably be interesting to remove "imports" from [test_columnar.py](https://github.com/citusdata/citus/blob/main/src/test/regress/citus_tests/test/test_columnar.py) and [test_extension.py](https://github.com/citusdata/citus/blob/main/src/test/regress/citus_tests/test/test_extension.py)

**Comment by c2main** [comment]
> > FYI CI complains about some unused imports in the test file, if you fix those I think this is good to merge.
> 
> I used other tests as examples... I removed the "imports" and rebased.
> 
> It will also probably be interesting to remove "imports" from [test_columnar.py](https://github.com/citusdata/citus/blob/main/src/test/regress/citus_tests/test/test_columnar.py) and [test_extension.py](https://github.com/citusdata/citus/blob/main/src/test/regress/citus_tests/test/test_extension.py)

Well, no. Those do really uses `pytest`
