### PR TITLE
Fix multi-row INSERT with RETURNING on reference tables

### LINKED ISSUE #1610: INSERT … RETURNING for multi-row inserts on reference tables errors out
We fixed issue #1596, but it appears INSERTs on reference tables behave differently and we still don't add the alias.

```
postgres=# CREATE TABLE test (x int primary key, y int);
CREATE TABLE
postgres=# SELECT create_reference_table('test');
 create_reference_table 
------------------------
 
(1 row)

postgres=# INSERT INTO test VALUES (1,2), (5,1) RETURNING *;
ERROR:  missing FROM-clause entry for table "test"
CONTEXT:  while executing command on localhost:9700
```

Note that this appears to be specific to reference tables, RETURNING does work on distributed tables, even when they have a single shard.

### PR DESCRIPTION
**Pull request by marcocitus**
Fixes #1610.

I first tried returning a `valuesRTE` for reference tables in `ExtractDistributedInsertValuesRTE`, but then I realised we don't set the `rowValuesList` for reference table inserts. I decided to set the `rowValuesList` in for multi-row inserts on reference tables as well, such that multi-row INSERT on distributed tables and reference tables are handled in the same way, which seems less prone to bugs.

### CODE REVIEW

File: src/backend/distributed/planner/multi_router_planner.c [hunk 1]
```diff
@@ -1987,6 +1998,39 @@ BuildRoutesForInsert(Query *query, DeferredErrorMessage **planningError)
...
 
 /*
+ * ExtractDistributedInsertValuesRTE does precisely that. If the provided
+ * query is not an INSERT, or if the INSERT does not have a VALUES RTE
+ * (i.e. it is not a multi-row INSERT), this function returns NULL.
+ * If all those conditions are met, an RTE representing the multiple values
+ * of a multi-row INSERT is returned.
+ */
+RangeTblEntry *
+ExtractDistributedInsertValuesRTE(Query *query)
```
Comment (jasonmp85) [inline src/backend/distributed/planner/multi_router_planner.c]: The logic here is now identical to `IsMultiRowInsert`. Can you change the sole caller of it to instead call this and just check whether the return value is `NULL`?

File: src/backend/distributed/planner/multi_router_planner.c [hunk 2]
```diff
@@ -1867,7 +1868,17 @@ BuildRoutesForInsert(Query *query, DeferredErrorMessage **planningError)
 		modifyRoute = palloc(sizeof(ModifyRoute));
 
 		modifyRoute->shardId = shardInterval->shardId;
-		modifyRoute->rowValuesLists = NIL;
```
Comment (jasonmp85) [inline src/backend/distributed/planner/multi_router_planner.c]: If it's now an invariant that all `modifyRoutes` have a non-`NULL` `rowValuesList`, can you add an `Assert` somewhere to ensure we catch malformed values correctly?

**Comment by jasonmp85** [comment]
Rebased this for you because why not.

File: src/backend/distributed/planner/multi_router_planner.c (hunk 2 above)
Comment (marcocitus) [inline src/backend/distributed/planner/multi_router_planner.c]: Yep, added it it in deparse_shard_query.c where it gets used.

File: src/backend/distributed/planner/multi_router_planner.c (hunk 1 above)
Comment (marcocitus) [inline src/backend/distributed/planner/multi_router_planner.c]: Changed the implementation of `IsMultiRowInsert` to `return ExtractDistributedInsertValuesRTE(query) != NULL` to preserve readability and the function comment.

**Comment by marcocitus** [comment]
Thanks for the review! Hope you're feeling better.
