### PR TITLE
Handle identity columns properly in the router planner

### LINKED ISSUE #6798: Insert..select queries which use generated identities can get pushed down
With sequences:
```sql
drop table if exists test;
create table test (x int, y int, z bigserial);
select create_distributed_table('test', 'x', colocate_with := 'none');
insert into test values (1,2);
insert into test select x, y from test where x = 1;
select * from test;
┌───┬───┬───┐
│ x │ y │ z │
├───┼───┼───┤
│ 1 │ 2 │ 1 │
│ 1 │ 2 │ 2 │
└───┴───┴───┘
(2 rows)

```
With identity column:
```sql
drop table if exists test;
create table test (x int, y int, z bigint generated by default as identity);
select create_distributed_table('test', 'x', colocate_with := 'none');
insert into test values (1,2);
insert into test select x, y from test where x = 1;
select * from test;
┌───┬───┬─────────────────┐
│ x │ y │        z        │
├───┼───┼─────────────────┤
│ 1 │ 2 │               1 │
│ 1 │ 2 │ 562949953421313 │
└───┴───┴─────────────────┘
(2 rows)
```

That's because in the second case the insert..select gets pushed down to the worker nodes by the router planner. Nowadays, that silently succeeds because worker nodes also have the sequence, but it gives unexpected results when inserting via the coordinator.

We have logic to avoid handling insert..select queries with nextval calls in the router planner.

### PR DESCRIPTION
**Pull request by gokhangulbiz**
DESCRIPTION: Fixes a bug with insert..select queries with identity columns
Fixes #6798

### CODE REVIEW

File: src/backend/distributed/deparser/citus_ruleutils.c [hunk 1]
```diff
@@ -1401,6 +1401,13 @@ contain_nextval_expression_walker(Node *node, void *context)
 		return false;
 	}
 
+	/* check if the node contains an identity column */
+	if (IsA(node, NextValueExpr))
+	{
+		return true;
```
Comment (marcocitus) [inline src/backend/distributed/deparser/citus_ruleutils.c:1407]: makes sense, but could use a test

**Review by marcocitus — APPROVED** [review]
