### PR TITLE
Utility hook does nothing if the extension is not loaded

### LINKED ISSUE #1196: postgres' regression tests fail due to VACUUM output
`make check-vanilla` fails with this diff:

```
--- /home/brian/Work/postgresql-9.5.1/src/test/regress/expected/sanity_check.out        2016-02-08 23:12:28.000000000 +0200
+++ /home/brian/Work/postgresql-9.5.1/src/test/regress/results/sanity_check.out 2017-02-02 11:45:32.120993050 +0300
@@ -1,11 +1,13 @@
 VACUUM;
+WARNING:  not propagating VACUUM command to worker nodes
+HINT:  Provide a specific table in order to VACUUM distributed tables.
 --
 -- sanity check, if we don't have indices the test will take years to
 -- complete.  But skip TOAST relations (since they will have varying
 -- names depending on the current OID counter) as well as temp tables
 -- of other backends (to avoid timing-dependent behavior).
 --
 -- temporarily disable fancy output, so catalog changes create less diff noise
 \a\t
 SELECT relname, relhasindex
    FROM pg_class c LEFT JOIN pg_namespace n ON n.oid = relnamespace
```

### PR DESCRIPTION
**Pull request by lithp**
Fixes #1196, and all other bugs like it.

### CODE REVIEW

File: src/backend/distributed/executor/multi_utility.c [hunk 1]
```diff
@@ -188,6 +188,14 @@ multi_ProcessUtility(Node *parsetree,
 		return;
 	}
 
+	if (!CitusHasBeenLoaded())
+	{
+		standard_ProcessUtility(parsetree, queryString, context,
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_utility.c]: Maybe add a small comment e.g.
```
/* if the extension has not yet been created, then do not change PostgreSQL's behaviour */
```

Comment (lithp) [inline src/backend/distributed/executor/multi_utility.c]: I thought about adding it but couldn't come up with anything that added to the code. Isn't that what the code already says?

Comment (marcocitus) [inline src/backend/distributed/executor/multi_utility.c]: It's not obvious that creating the Citus extension changes PostgreSQL's behaviour even if you have no distributed tables, so this might be the right place to communicate that. Could use better wording.

Comment (lithp) [inline src/backend/distributed/executor/multi_utility.c]: Okay, pushed an updated commit with a comment here

**Comment by marcocitus** [comment]
🚢
