### PR TITLE
Fix a crash when calling a distributed function from PL/pgSQL

### LINKED ISSUE #3291: Using return value of a delegated function inside  another function errors
Reported on slack, I didn't have much time to look,  just created steps to repro:

```SQL
CREATE TABLE statement_table(id int, name text);
SET citus.shard_replication_factor TO 1;
SELECT create_distributed_table('statement_table','id');

CREATE OR REPLACE FUNCTION increment(int)
RETURNS NUMERIC AS $$
DECLARE ret_val NUMERIC;
BEGIN
        SELECT max(id)::numeric INTO ret_val  FROM statement_table WHERE id = $1+1;
        RETURN ret_val;
END;
$$  LANGUAGE plpgsql
    SECURITY DEFINER
    -- Set a secure search_path: trusted schema(s), then 'pg_temp'.
    SET search_path = admin, public;


SELECT create_distributed_function('increment(int)', '$1', colocate_with := 'statement_table');


CREATE OR REPLACE FUNCTION test_func_calls_dist_func()
RETURNS NUMERIC AS $$
DECLARE incremented_val NUMERIC;
BEGIN
        SELECT INTO incremented_val increment(1);
        RETURN incremented_val;
END;
$$  LANGUAGE plpgsql
    SECURITY DEFINER
    -- Set a secure search_path: trusted schema(s), then 'pg_temp'.
    SET search_path = admin, public;

SELECT test_func_calls_dist_func();

SELECT test_func_calls_dist_func();
ERROR:  unexpected plan node type: 34
CONTEXT:  PL/pgSQL function test_func_calls_dist_func() line 4 at SQL statement
Time: 1.305 ms


SELECT test_func_calls_dist_func();
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
Time: 341.933 ms
!> \q
```

### PR DESCRIPTION
**Pull request by marcocitus**
DESCRIPTION: Fix a crash when calling a distributed function from PL/pgSQL

We currently do not always correctly detect being in PL/pgSQL, which causes issues when calling a distributed function from PL/pgSQL since we might incorrectly delegate it.

Fixes #3291

### CODE REVIEW

File: src/backend/distributed/transaction/transaction_management.c [hunk 1]
```diff
@@ -695,9 +697,12 @@ IsMultiStatementTransaction(void)
...
  * CTEs, etc. which also start nested executors.
+ *
+ * If the planner is being called from the executor, then we may also be in
+ * a UDF.
  */
 static bool
 MaybeExecutingUDF(void)
 {
-	return ExecutorLevel > 1;
+	return ExecutorLevel > 1 || (PlannerLevel > 0 && ExecutorLevel > 0);
```
Comment (thanodnl) [inline src/backend/distributed/transaction/transaction_management.c]:
```suggestion
	return ExecutorLevel > 1 || (ExecutorLevel == 1  && PlannerLevel > 0);
```

By rephrasing it like suggested it will be slightly easier to read at once without changing the behaviour.

By having `ExecutorLevel` at the end and the check which has a lot of overlap it made it hard to understand we always return true for `ExecutorLevel` 2 and above. By getting the `ExecutorLevel` check in the front and a hard equal on `1` it reads more intuitive of what we are checking.

File: src/backend/distributed/planner/distributed_planner.c [hunk 2]
```diff
@@ -242,14 +248,24 @@ distributed_planner(Query *parse, int cursorOptions, ParamListInfo boundParams)
 				result->planTree->total_cost = FLT_MAX / 100000000;
 			}
 		}
+
+		PlannerLevel = originalLevel;
```
Comment (thanodnl) [inline src/backend/distributed/planner/distributed_planner.c]: Other places [1] where we keep counters like this we perform a decrement both here and in the `PG_CATCH`. I have two questions:

1. Is the use of  `originalLevel` safe in `PG_CATCH`? I thought all local variables are unsafe to use during rollback, hence we were decrementing global variables in other places:
2. Is it unsafe to decrement? Would there be a possibility of missing a decrement?

[1] https://github.com/citusdata/citus/blob/2829c601dd48dcdbbbf3c748777f0b1b056484fa/src/backend/distributed/commands/utility_hook.c#L269

File: src/backend/distributed/transaction/transaction_management.c [hunk 3]
```diff
@@ -302,6 +303,7 @@ CoordinatedTransactionCallback(XactEvent event, void *arg)
 			activeSetStmts = NULL;
 			CoordinatedTransactionUses2PC = false;
 			ExecutorLevel = 0;
+			PlannerLevel = 0;
```
Comment (thanodnl) [inline src/backend/distributed/transaction/transaction_management.c]: Would it be a bug if this is not reset to `0`? Wonder if an `Assert` is in place.
