### PR TITLE
Loosen the requirements for subquery pushdown for non-dist tables

### LINKED ISSUE #4032: Recursive planning kicks in unnecessarily for reference  table joins  in subqueries/CTEs
I've traced back up to Citus 8.2, and the issue exists there as well. So, not a regression in the latest releases, but could create significant performance increases in certain cases.

The problem seems to stem from [`TargetListOnPartitionColumn()`](https://github.com/citusdata/citus/blob/bc011a6286b7df243c6478ef5bdb3b9f2c04922c/src/backend/distributed/planner/multi_logical_planner.c#L267-L338) function, which aims to ignore columns from reference tables but it seems it cannot for all cases.

Whenever a subquery consists of only reference tables, it should be safe to pushdown. (Outer join checks are done separately anyway)

The below queries are subqueries, but the behavior is the same with CTEs that can be inlined.

```SQL
CREATE TABLE ref_table_1 (a int);
SELECT create_reference_table('ref_table_1');

CREATE TABLE ref_table_2 (a int);
SELECT create_reference_table('ref_table_2');

CREATE TABLE dist (a int,  b text);
SELECT create_distributed_table('dist', 'a');

-- because of the expression, `TargetListOnPartitionColumn()` fails to detect ref table join
SELECT count(*) FROM 
	(SELECT DISTINCT ref_table_1.a + 1 as a FROM  ref_table_1 JOIN ref_table_2 ON (ref_table_1.a = ref_table_2.a)) as foo
		JOIN
	dist
		ON(dist.a = foo.a);
DEBUG:  generating subplan 85_1 for subquery SELECT DISTINCT (ref_table_1.a OPERATOR(pg_catalog.+) 1) AS a FROM (onder.ref_table_1 JOIN onder.ref_table_2 ON ((ref_table_1.a OPERATOR(pg_catalog.=) ref_table_2.a)))
DEBUG:  Plan 85 query after replacing subqueries and CTEs: SELECT count(*) AS count FROM ((SELECT intermediate_result.a FROM read_intermediate_result('85_1'::text, 'binary'::citus_copy_format) intermediate_result(a integer)) foo JOIN onder.dist ON ((dist.a OPERATOR(pg_catalog.=) foo.a)))
 count 
-------
     0
(1 row)


-- because of the expression, `TargetListOnPartitionColumn()` fails to detect ref table join
SELECT count(*) FROM 
	(SELECT ref_table_1.a + 1 as a FROM  ref_table_1 JOIN ref_table_2 ON (ref_table_1.a = ref_table_2.a) GROUP BY ref_table_1.a + 1) as foo
		JOIN
	dist
		ON(dist.a = foo.a);
DEBUG:  generating subplan 87_1 for subquery SELECT (ref_table_1.a OPERATOR(pg_catalog.+) 1) AS a FROM (onder.ref_table_1 JOIN onder.ref_table_2 ON ((ref_table_1.a OPERATOR(pg_catalog.=) ref_table_2.a))) GROUP BY (ref_table_1.a OPERATOR(pg_catalog.+) 1)
DEBUG:  Plan 87 query after replacing subqueries and CTEs: SELECT count(*) AS count FROM ((SELECT intermediate_result.a FROM read_intermediate_result('87_1'::text, 'binary'::citus_copy_format) intermediate_result(a integer)) foo JOIN onder.dist ON ((dist.a OPERATOR(pg_catalog.=) foo.a)))
 count 
-------
     0
(1 row)

-- because of the explicit coercion, `TargetListOnPartitionColumn()` fails to detect ref table join
SELECT count(*) FROM 
	(SELECT DISTINCT ref_table_1.a::text as a_text FROM  ref_table_1 JOIN ref_table_2 ON (ref_table_1.a = ref_table_2.a)) as foo
		JOIN
	dist
		ON(dist.b = foo.a_text);
DEBUG:  generating subplan 89_1 for subquery SELECT DISTINCT (ref_table_1.a)::text AS a_text FROM (onder.ref_table_1 JOIN onder.ref_table_2 ON ((ref_table_1.a OPERATOR(pg_catalog.=) ref_table_2.a)))
DEBUG:  Plan 89 query after replacing subqueries and CTEs: SELECT count(*) AS count FROM ((SELECT intermediate_result.a_text FROM read_intermediate_result('89_1'::text, 'binary'::citus_copy_format) intermediate_result(a_text text)) foo JOIN onder.dist ON ((dist.b OPERATOR(pg_catalog.=) foo.a_text)))
 count 
-------
     0
(1 row)


-- an expression  on PARTITION BY clause for reference tables fail
SELECT  count(*) FROM (
  SELECT
    a, lag(a) OVER my_win  as lag_event_type, row_number() OVER my_win as row_no
  FROM
    ref_table_1 WINDOW my_win AS (PARTITION BY a + 1)) as foo

		JOIN
	dist
		ON(dist.a = foo.a);
DEBUG:  generating subplan 91_1 for subquery SELECT a, lag(a) OVER my_win AS lag_event_type, row_number() OVER my_win AS row_no FROM onder.ref_table_1 WINDOW my_win AS (PARTITION BY (a OPERATOR(pg_catalog.+) 1))
DEBUG:  Plan 91 query after replacing subqueries and CTEs: SELECT count(*) AS count FROM ((SELECT intermediate_result.a, intermediate_result.lag_event_type, intermediate_result.row_no FROM read_intermediate_result('91_1'::text, 'binary'::citus_copy_format) intermediate_result(a integer, lag_event_type integer, row_no bigint)) foo JOIN onder.dist ON ((dist.a OPERATOR(pg_catalog.=) foo.a)))
 count 
-------
     0
(1 row)
```

For distributed tables, the above cases seems to require recursive planning to kick in, though might be nice to test  thoroughly to see it that's the case. I tested briefly, and it all seems to work fine.

### PR DESCRIPTION
**Pull request by SaitTalhaNisanci**
Fixes #4032.

When a subquery doesn't contain a distributed table it is probably safe to push down. We already have separate checks for parts that could cause problems with reference tables etc(e.g. `select * from ref limit 10`).

### CODE REVIEW

File: src/backend/distributed/planner/multi_logical_planner.c [hunk 1]
```diff
@@ -270,8 +269,7 @@ TargetListOnPartitionColumn(Query *query, List *targetEntryList)
 	if (!targetListOnPartitionColumn)
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_logical_planner.c:269]: comment above may have to be updated
