### PR TITLE
Use CustomScan API for query execution

### LINKED ISSUE #372: Remove use of temporary table in real-time executor
The real-time executor currently saves query results from worker nodes into a temporary table, and then runs the final aggregation query on this temporary table. We keep this additional state so that the real-time executor can handle mid-query failures.

We could replace the use of a temporary table in the real-time executor and instead rely on the new custom scan APIs in Postgres.

### LINKED ISSUE #457: Error in pg_stat_statements Results
As described in #251, pg_stat_statement statistics do not reflect the real results for distributed queries.

```
postgres=# SELECT count(*) FROM 
postgres-# github_events t1, github_events_append t2 
postgres-# WHERE t1.repo_id = t2.repo_id;
  count  
---------
 1101049
(1 row)

Time: 6774.647 ms
postgres=# SELECT query, total_time FROM pg_stat_statements;
                                             query                                             | total_time 
-----------------------------------------------------------------------------------------------+------------
 SELECT count(*) FROM github_events t1, github_events_append t2 WHERE t1.repo_id = t2.repo_id; |       0.03
 (temp table creation)                                                                         |       1.03
 (copy job)                                                                                    |      0.318
 SELECT pg_stat_statements_reset();                                                            |      0.107
(4 rows)
```

### LINKED ISSUE #713: Weird error on materialized view creation
``` sql
CREATE MATERIALIZED VIEW materialized_view_test AS SELECT * from lineitem;
ERROR:  cannot create temporary table within security-restricted operation
```

### PR DESCRIPTION
**Pull request by anarazel**
Reason we're working this:
- removing the temp table for real-time queries, which is good for efficiency and for running queries on standbys
- basis for allowing to execute multiple remote queries within one query (i.e. pull to master style queries)
- fix PREPARE + explain
- remove code

Behavioural changes:
- explain now happens inside the custom scan's explain callback. That's good because it removes a bunch of code and add features. But it also means the explain output changes - we're now getting called "within" the master query for real-time/tt queries, i.e. the remote explain is now where the sequential scan of the remote query used to be.  That's hard to avoid without complicating things, *and* seems to be the right thing to anyway, because we'll soon have multiple distributed queries within one query.
- execution now happens during the actual execution phase, not earlier. This means we should be able to make pg_stat_statements work (if it doesn't already)
- no temp tables anymore :) (which means pg matviews are now supported...) 

Todo
- [x] Verify pg_stat_statements now works (i.e. doesn't show "(temp table creation)" and such, and that the times are meaningful) 
- [x] Verify query execution now happens during the 'execute' phase, not the 'bind' phase as before.  A good way to test that is to use pgbench with -M extended, and use log_min_duration_statement=0
- [x] Do some simple benchmarking with a query returning a large number of rows (e.g. just COPY lineitem TO '/dev/null'), to make sure we're not regressing
- [x] Concurrent pgbench for quick router queries.
- [x] Basic testing
- [x] Make sure we still acquire all the right relation level locks

Fixes #457 
Fixes #372 
Fixes #713

### CODE REVIEW

**Comment by anarazel** [comment]
Example of how the explain output now looks
```
postgres[14200][1]=# EXPLAIN SELECT count(*) FROM test_table HAVING count(*) < 3;
┌───────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                              QUERY PLAN                                               │
├───────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Aggregate  (cost=0.00..0.00 rows=0 width=0)                                                           │
│   Filter: (COALESCE((sum(worker_column_2))::bigint, '0'::bigint) < 3)                                 │
│   ->  Custom Scan (CitusScan)  (cost=0.00..0.00 rows=0 width=0)                                       │
│         Executor: Real-Time                                                                           │
│         Task Count: 4                                                                                 │
│         Tasks Shown: One of 4                                                                         │
│         ->  Task                                                                                      │
│               Node: host=localhost port=57637 dbname=postgres                                         │
│               ->  Aggregate  (cost=22.75..22.76 rows=1 width=0)                                       │
│                     ->  Seq Scan on test_table_102453 test_table  (cost=0.00..18.50 rows=850 width=0) │
└───────────────────────────────────────────────────────────────────────────────────────────────────────┘
(10 rows)

Time: 20.584 ms
```

@ozgune @samay-sharma Comments on that aspect?

**Comment by samay-sharma** [comment]
@anarazel : I think this look OK but I liked the previous one better :).

How easy is it to move some content to above the master query (i.e. something like planning information or just text saying that this is the master query)?

If it is not easy, it might be worth doing some rewrite of the format to better align with this way of output (as currently it was written assuming the previous one)

**Comment by anarazel** [comment]
On 2017-02-01 11:23:31 -0800, Samay Sharma wrote:
> @anarazel : I think this look OK but I liked the previous one better :).
> 
> How easy is it to move some content to above the master query (i.e. something like planning information or just text saying that this is the master query)?

Hard. Would require a fair bit of code duplication (because we'd need to
integrate into explain twice).  More importantly there'll soon be more
than one master query and such in one query, so that doesn't work well
anymore.


> If it is not easy, it might be worth doing some rewrite of the format
> to better align with this way of output (as currently it was written
> assuming the previous one)

I'm not sure I'm following? Have a minute after the standup?

**Comment by anarazel** [comment]
@metdos I think it'd make sense to open a separate PR and merge the DEBUG2/DEBUG4 changes quickly? They're verbose and I think uncontroversial?

File: src/backend/distributed/executor/multi_router_executor.c [hunk 1]
```diff
@@ -539,59 +463,42 @@ RouterExecutorRun(QueryDesc *queryDesc, ScanDirection direction, long count)
...
-
-out:
-
-	/* shutdown tuple receiver, if we started it */
-	if (sendTuples)
+	/*
+	 * FIXME: centralize this into function to be shared between router and
+	 * other executors?
+	 */
+	if (scanState->tuplestorestate != NULL)
```
Comment (metdos) [inline src/backend/distributed/executor/multi_router_executor.c]: @anarazel, reading the next tuple is a very concise operation here. Do you still think we need to wrap tuplestore_gettupleslot()?

Comment (anarazel) [inline src/backend/distributed/executor/multi_router_executor.c]: I think it'd make sense, because that'd allow us to support directional cursors more easily.

File: src/backend/distributed/executor/multi_executor.c [hunk 2]
```diff
@@ -24,273 +24,264 @@
...
- * If a distributed relation is the target of the query, perform some validity
- * checks. If a legal statement, start the distributed execution. After that
- * the to-be-executed query is replaced with the portion executing solely on
- * the master.
+ * I think it's better however to only have one type of CitusScanState, to
+ * allow to easily share code between routines.
  */
-void
-multi_ExecutorStart(QueryDesc *queryDesc, int eflags)
+static CustomExecMethods CitusCustomExecMethods = {
```
Comment (anarazel) [inline src/backend/distributed/executor/multi_executor.c]: I'd rather not have this named Citus vs. Router - that seems unclear. Router vs. RealTime?

File: src/backend/distributed/executor/multi_executor.c [hunk 3]
```diff
@@ -24,273 +24,264 @@
...
-			 * temp table later.
-			 *
-			 * We copy the original statement's queryId, to allow
-			 * pg_stat_statements and similar extension to associate the
-			 * statement with the toplevel statement.
-			 */
-			masterSelectPlan->queryId = queryDesc->plannedstmt->queryId;
-			queryDesc->plannedstmt = masterSelectPlan;
-
-			eflags |= EXEC_FLAG_CITUS_MASTER_SELECT;
```
Comment (anarazel) [inline src/backend/distributed/executor/multi_executor.c]: We shouldn't need EXEC_FLAG_CITUS_*  anymore.

File: src/backend/distributed/executor/multi_executor.c [hunk 4]
```diff
@@ -24,273 +24,264 @@
...
+
+	tupleDescriptor = customScanState.ss.ps.ps_ResultTupleSlot->tts_tupleDescriptor;
 
-	/* now copy data from all the remote nodes into temp table */
-	foreach(masterCopyStmtCell, masterCopyStmtList)
+	/*
+	 * To be able to use copy.c, we need a Relation descriptor. As there's
+	 * no relation corresponding to the data loaded from workers, fake one.
+	 * We just need the bare minimal set of fields accessed by BeginCopyFrom().
+	 */
```
Comment (anarazel) [inline src/backend/distributed/executor/multi_executor.c]: Should be hidden, in shame, in its own function.

File: src/backend/distributed/planner/multi_master_planner.c [hunk 5]
```diff
@@ -196,6 +153,11 @@ BuildAggregatePlan(Query *masterQuery, Plan *subPlan)
 							 groupColumnOpArray, NIL, rowEstimate, subPlan);
 #endif
 
+	/* just for reproducible costs between the versions */
+	aggregatePlan->plan.startup_cost = 0;
+	aggregatePlan->plan.total_cost = 0;
+	aggregatePlan->plan.plan_rows = 0;
```
Comment (anarazel) [inline src/backend/distributed/planner/multi_master_planner.c]: These should be split into a separate PR and merged separately.

File: src/backend/distributed/planner/multi_master_planner.c [hunk 6]
```diff
@@ -265,6 +233,12 @@ BuildSelectStatement(Query *masterQuery, char *masterTableName,
 #else
 		Sort *sortPlan = make_sort_from_sortclauses(NULL, sortClauseList, topLevelPlan);
 #endif
+
+		/* just for reproducible costs between the versions */
+		sortPlan->plan.startup_cost = 0;
+		sortPlan->plan.total_cost = 0;
+		sortPlan->plan.plan_rows = 0;
+
```
Comment (anarazel) [inline src/backend/distributed/planner/multi_master_planner.c]: (together with this)

File: src/include/distributed/multi_executor.h [hunk 7]
```diff
@@ -23,10 +27,25 @@
...
-extern void multi_ExecutorEnd(QueryDesc *queryDesc);
+
+typedef struct CitusScanState
+{
+	CustomScanState customScanState;
+	MultiPlan *multiPlan;
+	MultiExecutorType executorType;
+	bool finishedRemoteScan;
+	Tuplestorestate *tuplestorestate;
+} CitusScanState;
```
Comment (anarazel) [inline src/include/distributed/multi_executor.h]: Should add comments about the fields.

File: src/backend/distributed/executor/multi_executor.c [hunk 8]
```diff
@@ -24,273 +24,270 @@
...
- * checks. If a legal statement, start the distributed execution. After that
- * the to-be-executed query is replaced with the portion executing solely on
- * the master.
+ * I think it's better however to only have one type of CitusScanState, to
+ * allow to easily share code between routines.
  */
-void
-multi_ExecutorStart(QueryDesc *queryDesc, int eflags)
+static CustomExecMethods RealTimeCustomExecMethods = {
+	.CustomName = "RealTimeScan",
```
Comment (anarazel) [inline src/backend/distributed/executor/multi_executor.c]: It's not just RealTime but also TaskTracker, no?  Maybe we should have a separate one for TT?

File: src/backend/distributed/executor/multi_router_executor.c [hunk 9]
```diff
@@ -539,59 +458,48 @@ RouterExecutorRun(QueryDesc *queryDesc, ScanDirection direction, long count)
...
 
-	/* shutdown tuple receiver, if we started it */
-	if (sendTuples)
-	{
-		(*destination->rShutdown)(destination);
-	}
 
-	if (queryDesc->totaltime != NULL)
+static bool
+IsModificationPlan(MultiPlan *multiPlan)
```
Comment (anarazel) [inline src/backend/distributed/executor/multi_router_executor.c]: There's also IsModifyCommand() in multi_planner.c...

File: src/backend/distributed/planner/multi_explain.c [hunk 10]
```diff
@@ -91,289 +85,63 @@ static void ExplainJSONLineEnding(ExplainState *es);
...
-		appendStringInfo(es->str, "\n");
+	ExplainCloseGroup("Distributed Query", "Distributed Query", true, es);
+}
 
-		es->indent += 1;
-	}
 
-	routerExecutablePlan = multiPlan->routerExecutable;
+char *
+ExecutorName(MultiExecutorType executorType)
```
Comment (anarazel) [inline src/backend/distributed/planner/multi_explain.c]: Would move that to multi_executor.c

File: src/backend/distributed/planner/multi_master_planner.c [hunk 11]
```diff
@@ -212,56 +170,52 @@ BuildAggregatePlan(Query *masterQuery, Plan *subPlan)
  * and limit plans on top of the scan statement if necessary.
  */
```
Comment (anarazel) [inline src/backend/distributed/planner/multi_master_planner.c]: Comment needs updating.

File: src/backend/distributed/planner/multi_master_planner.c [hunk 12]
```diff
@@ -296,121 +250,30 @@ BuildSelectStatement(Query *masterQuery, char *masterTableName,
...
-
-	return createStatement;
-}
-
-
-/*
  * MasterNodeSelectPlan takes in a distributed plan, finds the master node query
  * structure in that plan, and builds the final select plan to execute on the
  * master node. Note that this select plan is executed after result files are
  * retrieved from worker nodes and are merged into a temporary table.
```
Comment (anarazel) [inline src/backend/distributed/planner/multi_master_planner.c]: Comment needs updating.

File: src/backend/distributed/planner/multi_planner.c [hunk 13]
```diff
@@ -294,176 +298,183 @@ CreateDistributedPlan(PlannedStmt *localPlan, Query *originalQuery, Query *query
...
 
-		fauxFunctionScan->scan.plan.targetlist =
-			lappend(fauxFunctionScan->scan.plan.targetlist,
-					targetEntry);
+/*
+ * CreateFinalPlan combines local plan with distributed plan and creates a plan
+ * which can be run by the PostgreSQL executor.
+ */
+static PlannedStmt *
+CreateFinalPlan(PlannedStmt *localPlan, MultiPlan *multiPlan)
```
Comment (anarazel) [inline src/backend/distributed/planner/multi_planner.c]: Rename to FinalizePlan? and then FinalizeRealTimePlan?

File: src/backend/distributed/planner/multi_planner.c [hunk 14]
```diff
@@ -294,176 +298,183 @@ CreateDistributedPlan(PlannedStmt *localPlan, Query *originalQuery, Query *query
...
 
-	fauxFuncExpr = (FuncExpr *) fauxFunction->funcexpr;
+	customScan->scan.plan.targetlist = targetList;
+	customScanRangeTableEntry = CustomScanRangeTableEntry(columnNameList);
 
-	if (fauxFuncExpr->funcid != CitusExtraDataContainerFuncId())
-	{
-		return NULL;
-	}
+	finalPlan = localPlan;
```
Comment (anarazel) [inline src/backend/distributed/planner/multi_planner.c]: Hm. It might be better to create a "fresh" PlannedStmt here too, like we're doing for real-time/tt.  Right now the PlannedStmt basically has a lot of bogus fields set (like ctes which have been pushed down and such).

File: src/backend/distributed/shared_library_init.c [hunk 15]
```diff
@@ -117,10 +116,6 @@ _PG_init(void)
 	 */
 	if (planner_hook != NULL ||
 		ExplainOneQuery_hook != NULL ||
```
Comment (anarazel) [inline src/backend/distributed/shared_library_init.c]: Hm, why do we still have the ExplainOneQuery_hook check here?

File: src/backend/distributed/executor/multi_executor.c (hunk 8 above)
Comment (metdos) [inline src/backend/distributed/executor/multi_executor.c]: @anarazel, I gave a shot to having separate executors here: https://github.com/citusdata/citus/pull/1185/commits/fe3795dc6fec5703587b9b06c4cae5f5fbf82f5a

However, it increases code duplication, and I'm inclined to drop this commit. What do you think?

File: src/backend/distributed/executor/multi_router_executor.c (hunk 9 above)
Comment (metdos) [inline src/backend/distributed/executor/multi_router_executor.c]: Are you proposing to merge them?

I propose to rename IsModificationPlan() to IsModifyMultiPlan(), and IsModifyCommand() to IsModifyQuery(). Also move IsModifyMultiPlan() to multi_planner.c

File: src/backend/distributed/executor/multi_executor.c [hunk 16]
```diff
@@ -41,17 +41,44 @@
...
+	.CustomName = "RouterModificationScan",
+	.BeginCustomScan = CitusSelectBeginScan,
+	.ExecCustomScan = RouterSelectExecScan,
+	.EndCustomScan = CitusEndScan,
+	.ReScanCustomScan = CitusReScan,
+	.ExplainCustomScan = CitusExplainScan
+};
+
+static CustomExecMethods RouterMultipleTasksCustomExecMethods = {
+	.CustomName = "RouterModificationScan",
```
Comment (anarazel) [inline src/backend/distributed/executor/multi_executor.c]: *RouterMultiModificationScan?

File: src/backend/distributed/executor/multi_executor.c [hunk 17]
```diff
@@ -41,17 +41,44 @@
...
-	.CustomName = "RouterScan",
-	.BeginCustomScan = RouterBeginScan,
-	.ExecCustomScan = RouterExecScan,
+static CustomExecMethods TaskTrackerCustomExecMethods = {
+	.CustomName = "TaskTrackerScan",
+	.BeginCustomScan = CitusSelectBeginScan,
+	.ExecCustomScan = TaskTrackerExecScan,
+	.EndCustomScan = CitusEndScan,
+	.ReScanCustomScan = CitusReScan,
+	.ExplainCustomScan = CitusExplainScan
```
Comment (anarazel) [inline src/backend/distributed/executor/multi_executor.c]: In explain this'd allow removing the executor type...

File: src/backend/distributed/executor/multi_executor.c (hunk 8 above)
Comment (anarazel) [inline src/backend/distributed/executor/multi_executor.c]: I actually like it.

File: src/backend/distributed/executor/multi_executor.c [hunk 18]
```diff
@@ -24,273 +24,384 @@
...
+			if (!nextRowFound)
+			{
+				MemoryContextSwitchTo(oldContext);
+				break;
+			}
+
+			tuplestore_putvalues(scanState->tuplestorestate, tupleDescriptor,
+								 columnValues, columnNulls);
+			MemoryContextSwitchTo(oldContext);
+		}
```
Comment (anarazel) [inline src/backend/distributed/executor/multi_executor.c]: Needs an ```EndCopyFrom(copyState);``` otherwise we're (temporarily) leaking filehandles.  Noticed when playing around with a high shard count ;)

**Comment by metdos** [comment]
@anarazel related the task tracker related issues we have seen on Friday, I dropped all of the four regression tests from task tracker schedule because I think they are executor agnostic. Here is the commit: https://github.com/citusdata/citus/pull/1185/commits/6a814eb4a85cdd70c3181af60d30259669eeca05

**Comment by metdos** [comment]
Hey @anarazel, I'm done with my changes.

File: src/backend/distributed/executor/multi_executor.c (hunk 8 above)
Comment (jasonmp85) [inline src/backend/distributed/executor/multi_executor.c]: :+1: on having full separation.

File: src/backend/distributed/executor/multi_executor.c [hunk 19]
```diff
@@ -24,273 +24,440 @@
...
-
-			eflags |= EXEC_FLAG_CITUS_MASTER_SELECT;
+	multiPlan = scanState->multiPlan;
+	workerJob = multiPlan->workerJob;
+	taskList = workerJob->taskList;
+
+	/* check if this is a single shard query */
+	if (list_length(taskList) == 1)
+	{
+		bool isModificationQuery = IsModifyMultiPlan(multiPlan);
```
Comment (jasonmp85) [inline src/backend/distributed/executor/multi_executor.c]: Adhering to this style here is a little pathological, IMO.

File: src/backend/distributed/executor/multi_executor.c [hunk 20]
```diff
@@ -24,273 +24,440 @@
...
+		if (isModificationQuery)
+		{
+			scanState->customScanState.methods = &RouterSingleModifyCustomExecMethods;
+		}
+		else
+		{
+			scanState->customScanState.methods = &RouterSelectCustomExecMethods;
```
Comment (jasonmp85) [inline src/backend/distributed/executor/multi_executor.c]: Does it make sense to always check `isModificationQuery` so we can put an `Assert(isModificationQuery)` inside this block? Or is it possible to have `SELECTs` with multiple tasks that somehow reach the router executor here?

If so, I think the custom exec methods are misnamed here, since they imply they're for modification only. If not, I think we should add an `Assert`.

File: src/backend/distributed/executor/multi_executor.c [hunk 21]
```diff
@@ -24,273 +24,440 @@
...
+
+	tupleDescriptor = customScanState.ss.ps.ps_ResultTupleSlot->tts_tupleDescriptor;
+	fauxRelation = FauxRelation(tupleDescriptor);
+
+	columnCount = tupleDescriptor->natts;
+	columnValues = palloc0(columnCount * sizeof(Datum));
+	columnNulls = palloc0(columnCount * sizeof(bool));
+
+	Assert(scanState->tuplestorestate == NULL);
+	scanState->tuplestorestate = tuplestore_begin_heap(randomAccess, false, work_mem);
```
Comment (jasonmp85) [inline src/backend/distributed/executor/multi_executor.c]: What is the `false` here for? If we're going through the trouble of assigning names for e.g. `randomAccess`, feels like we could do it for that argument, too.

File: src/backend/distributed/executor/multi_executor.c [hunk 22]
```diff
@@ -24,273 +24,440 @@
...
+/*
+ * Load data collected by real-time or task-tracker executors into the tuplestore
+ * of CitusScanState. For that, we first create a tuple store, and then copy the
+ * files one-by-one into the tuple store.
+ *
+ * Note that in the long term it'd be a lot better if Multi*Execute() directly
+ * filled the tuplestores, but that's a fair bit of work.
+ */
+static void
+LoadTuplesIntoTupleStore(CitusScanState *scanState, Job *workerJob)
```
Comment (jasonmp85) [inline src/backend/distributed/executor/multi_executor.c]: Is `scanState` a good name here? Isn't there also a `ScanState` at `customScanState.ss`? Those are different things, right?

File: src/backend/distributed/executor/multi_executor.c (hunk 18 above)
Comment (jasonmp85) [inline src/backend/distributed/executor/multi_executor.c]: Is there anywhere else we're already doing something similar to what's going on here? Wondering if there's something we could piggyback on for the "copy from files" code (to avoid having to reimplement and missing something like e.g. the `EndCopyFrom`)?

File: src/backend/distributed/executor/multi_executor.c [hunk 23]
```diff
@@ -24,273 +24,440 @@
...
- * master, remove the resources that were needed for distributed execution.
+ * FauxRelation creates a faux Relation from the given tuple descriptor.
+ * To be able to use copy.c, we need a Relation descriptor. As there is no
+ * relation corresponding to the data loaded from workers, we need to fake one.
+ * We just need the bare minimal set of fields accessed by BeginCopyFrom().
  */
-void
-multi_ExecutorEnd(QueryDesc *queryDesc)
+static Relation
+FauxRelation(TupleDesc tupleDescriptor)
```
Comment (jasonmp85) [inline src/backend/distributed/executor/multi_executor.c]: _Faux_'s a bit of a weird modifier here. Can we go with `Stub` (more common in programming) or `Fake` (doesn't mix linguistic roots)?

File: src/backend/distributed/executor/multi_executor.c [hunk 24]
```diff
@@ -24,273 +24,440 @@
...
+		jobDirectoryName = MasterJobDirectoryName(workerTask->jobId);
+		taskFilename = TaskFilename(jobDirectoryName, workerTask->taskId);
+
+		if (BinaryMasterCopyFormat)
+		{
+			DefElem *copyOption = makeDefElem("format", (Node *) makeString("binary"));
+			copyOptions = lappend(copyOptions, copyOption);
+		}
+
+		copyState = BeginCopyFrom(fauxRelation, taskFilename->data, false, NULL,
```
Comment (jasonmp85) [inline src/backend/distributed/executor/multi_executor.c]: How brittle is our use of the `copy.c` stuff here? Worried something'll change and cut off our hack here.

File: src/backend/distributed/executor/multi_executor.c [hunk 25]
```diff
@@ -24,273 +24,440 @@
...
+	{
+		tuplestore_end(scanState->tuplestorestate);
+		scanState->tuplestorestate = NULL;
 	}
 }
+
+
+/*
+ * CitusReScan is just a place holder for rescan callback. Currently, we don't
+ * support rescan given that there is not any way to reach this code path.
```
Comment (jasonmp85) [inline src/backend/distributed/executor/multi_executor.c]: What would actually cause this to be reached? The plan changing from beneath us during execution/plan invalidation? Just want to understand what this path is supposed to be for.

File: src/backend/distributed/planner/multi_planner.c [hunk 26]
```diff
@@ -294,176 +333,235 @@ CreateDistributedPlan(PlannedStmt *localPlan, Query *originalQuery, Query *query
...
- * The exact representation of the top-level node is an implementation detail
- * which should not be referred to outside this file, as it's likely to become
- * version dependant. Use GetMultiPlan() and HasCitusToplevelNode() to access.
+ * SerializeMultiPlan returns the string representing the distributed plan in a
+ * Const node.
  *
- * Internally the data is stored as arguments to a 'citus_extradata_container'
- * function, which has to be removed from the really executed plan tree before
- * query execution.
+ * Note that this should be improved for 9.6+, we we can copy trees efficiently.
```
Comment (jasonmp85) [inline src/backend/distributed/planner/multi_planner.c]: Is there a timeline for this?

File: src/backend/distributed/planner/multi_planner.c [hunk 27]
```diff
@@ -294,176 +333,235 @@ CreateDistributedPlan(PlannedStmt *localPlan, Query *originalQuery, Query *query
...
+	routerPlan->utilityStmt = localPlan->utilityStmt;
+	routerPlan->commandType = localPlan->commandType;
+	routerPlan->hasReturning = localPlan->hasReturning;
+
+	return routerPlan;
+}
+
+
+/*
+ * CustomScanRangeTableEntry creates a range table entry from given column name
```
Comment (jasonmp85) [inline src/backend/distributed/planner/multi_planner.c]: I feel this function could be renamed better. Not very self-descriptive.

File: src/backend/distributed/shared_library_init.c [hunk 28]
```diff
@@ -115,13 +114,7 @@ _PG_init(void)
...
 	 * duties. For simplicity insist that all hooks are previously unused.
 	 */
-	if (planner_hook != NULL ||
-		ExplainOneQuery_hook != NULL ||
-		ExecutorStart_hook != NULL ||
-		ExecutorRun_hook != NULL ||
-		ExecutorFinish_hook != NULL ||
-		ExecutorEnd_hook != NULL ||
-		ProcessUtility_hook != NULL)
+	if (planner_hook != NULL || ProcessUtility_hook != NULL)
```
Comment (jasonmp85) [inline src/backend/distributed/shared_library_init.c]: WAT.

File: src/test/regress/expected/multi_join_order_additional.out [hunk 29]
```diff
@@ -154,10 +156,12 @@ EXPLAIN SELECT count(*) FROM lineitem, orders
...
 LOG:  join order: [ "lineitem" ][ local partition join "orders" ]
-                         QUERY PLAN                         
-------------------------------------------------------------
- explain statements for distributed queries are not enabled
-(1 row)
+                                QUERY PLAN                                
+--------------------------------------------------------------------------
+ Aggregate  (cost=0.00..0.00 rows=0 width=0)
+   ->  Custom Scan (Citus Task-Tracker)  (cost=0.00..0.00 rows=0 width=0)
+         explain statements for distributed queries are not enabled
```
Comment (jasonmp85) [inline src/test/regress/expected/multi_join_order_additional.out]: Is there any good reason to keep this as something the user can disable?

Comment (jasonmp85) [inline src/test/regress/expected/multi_join_order_additional.out]: Also, `EXPLAIN` is a command, not a statement.

File: src/backend/distributed/planner/multi_planner.c [hunk 30]
```diff
@@ -124,11 +144,11 @@ multi_planner(Query *parse, int cursorOptions, ParamListInfo boundParams)
 
 
 /*
- * IsModifyCommand returns true if the query performs modifications, false
+ * IsModifyQuery returns true if the query performs modifications, false
```
Comment (metdos) [inline src/backend/distributed/planner/multi_planner.c]: Function gets a Query parameter, I wanted to make function align with that.

File: src/backend/distributed/planner/multi_planner.c (hunk 26 above)
Comment (metdos) [inline src/backend/distributed/planner/multi_planner.c]: I believe we loosely support last two major PostgreSQL versions, so we can make this change after PostgreSQL 10 is released.

File: src/backend/distributed/planner/multi_planner.c (hunk 27 above)
Comment (metdos) [inline src/backend/distributed/planner/multi_planner.c]: Maybe RemoteScanRangeTableEntry? I'm open to suggestions.

File: src/backend/distributed/planner/multi_planner.c [hunk 31]
```diff
@@ -294,176 +333,235 @@ CreateDistributedPlan(PlannedStmt *localPlan, Query *originalQuery, Query *query
...
+FinalizeRouterPlan(PlannedStmt *localPlan, MultiPlan *multiPlan, CustomScan *customScan)
+{
+	PlannedStmt *routerPlan = NULL;
+	RangeTblEntry *customScanRangeTableEntry = NULL;
+	ListCell *targetEntryCell = NULL;
+	List *targetList = NIL;
+	List *columnNameList = NIL;
+
+	/* we have only one range table entry */
+	int customScanRangeTableIndex = 1;
```
Comment (metdos) [inline src/backend/distributed/planner/multi_planner.c]: I updated the comment. Here, we will create only one range table entry for the router plan, so we know this by sure.

File: src/backend/distributed/executor/multi_executor.c (hunk 19 above)
Comment (metdos) [inline src/backend/distributed/executor/multi_executor.c]: This is not a new style: https://github.com/citusdata/citus/blob/6843ad8e917a45e93b18110ce289d1398c40987b/src/backend/distributed/executor/multi_router_executor.c#L536

If you have a proposal, I'm open change it. However, this PR is already huge, so we may want to do that separately.

File: src/backend/distributed/executor/multi_executor.c (hunk 20 above)
Comment (metdos) [inline src/backend/distributed/executor/multi_executor.c]: I could not exactly understand what you mean. We don't need to check isModificationQuery in RouterMultiModifyExecScan() (I updated now), but I guess you mean something different?

File: src/backend/distributed/executor/multi_executor.c (hunk 22 above)
Comment (metdos) [inline src/backend/distributed/executor/multi_executor.c]: I believe citusScanState is better.

Yes,  with CitusScanState, we are able to reach our tuplestore, executor type etc.

File: src/backend/distributed/executor/multi_executor.c (hunk 24 above)
Comment (metdos) [inline src/backend/distributed/executor/multi_executor.c]: We use same logic for our Copy operations, so there are in the same ship.

Comment (metdos) [inline src/backend/distributed/executor/multi_executor.c]: I don't why, but I can't comment on your next comment :) I don't think copying from files into a tuple store is a common operation :)

File: src/test/regress/expected/multi_join_order_additional.out (hunk 29 above)
Comment (metdos) [inline src/test/regress/expected/multi_join_order_additional.out]: I think "statement" is also used.
"There is no EXPLAIN statement defined in the SQL standard."
From: https://www.postgresql.org/docs/9.6/static/sql-explain.html

Comment (metdos) [inline src/test/regress/expected/multi_join_order_additional.out]: ExplainDistributedQueries is already GUC_NO_SHOW_ALL.

File: src/backend/distributed/executor/multi_executor.c (hunk 25 above)
Comment (metdos) [inline src/backend/distributed/executor/multi_executor.c]: Whenever we implement functionality like pull to master for CTEs, there would be cases we would like to join two custom scans on the master node. This would lead to a nested loop join which requires rescanning on one of the custom scans.

**Comment by metdos** [comment]
> we can (I believe) now fix EXPLAIN PREPARED, 

This is not completely fixed yet. We call ExecuteRemoteQuery() in RemoteExplain() without passing parameters, so currently this fails at remote plan. There are ongoing changes on ExecuteRemoteQuery() in PR #1229, and I think this is not a high priority feature, and we can track this in #982.

> (not to mention the entire removal of temp tables) but for my own knowledge, what's next? Can we build on this work to generate parallel scans to express our work in a way PostgreSQL can better exploit/understand?

It establishes the base to run "Pull to master CTE results" type queries.

>  Without temp tables, can we have read replicas, or are the temp files still a problem?

Temp files are not a problem, but we should also merge #1208. And we should also test if it really works :)

**Comment by metdos** [comment]
@jasonmp85, I either addressed or commented your comments. Please let me now if I missed anything.

File: src/backend/distributed/planner/multi_planner.c [hunk 32]
```diff
@@ -294,176 +333,235 @@ CreateDistributedPlan(PlannedStmt *localPlan, Query *originalQuery, Query *query
...
-	char *serializedMultiPlan = NULL;
 	MultiPlan *multiPlan = NULL;
 
-	serializedMultiPlan = GetMultiPlanString(result);
-	multiPlan = (MultiPlan *) CitusStringToNode(serializedMultiPlan);
-	Assert(CitusIsA(multiPlan, MultiPlan));
-
-	return multiPlan;
-}
+	Assert(IsA(customScan, CustomScan));
```
Comment (anarazel) [inline src/backend/distributed/planner/multi_planner.c]: Not really, we cast stuff around a fair bit around this. C's signatures aren't exactly enforced ;)

File: src/backend/distributed/executor/multi_executor.c (hunk 24 above)
Comment (anarazel) [inline src/backend/distributed/executor/multi_executor.c]: I don't think it's too bad - I looked back and it'd have worked over a couple versions.  And if not the failures are probably going to be obvious.

Comment (anarazel) [inline src/backend/distributed/executor/multi_executor.c]: (I can't comment on the next one either)  I don't see anything we could piggyback on either - this isn't something we have done before or postgres does (might come in 10).

File: src/backend/distributed/executor/multi_executor.c (hunk 23 above)
Comment (anarazel) [inline src/backend/distributed/executor/multi_executor.c]: Hm, you've me to blame for that one... Why is it weird? We've had that in a bunch of places already IIRC.  I've no problem changing this to Stub, just curious.

File: src/backend/distributed/shared_library_init.c (hunk 28 above)
Comment (anarazel) [inline src/backend/distributed/shared_library_init.c]: Hm?

**Comment by anarazel** [comment]
> This is not completely fixed yet. We call ExecuteRemoteQuery() in RemoteExplain() without passing parameters, so currently this fails at remote plan. There are ongoing changes on ExecuteRemoteQuery() in PR #1229, and I think this is not a high priority feature, and we can track this in #982.

Should, however, only fail for router executor, and there only for non-partition things? Right?

**Comment by anarazel** [comment]
> Can we build on this work to generate parallel scans to express our work in a way PostgreSQL can better exploit/understand? 

Right now that's not part of this work, and it's not exactly trivial.  Usually the master isn't a bottleneck anyway, so I'm not sure what exactly you'd want to parallelize? 

> Without temp tables, can we have read replicas, or are the temp files still a problem?

That's a big step towards that, but there's still the jobid sequence. There's an open PR for that however.

**Comment by anarazel** [comment]
@metdos I started a todo list at the top - please investigate and expand.

File: src/backend/distributed/planner/multi_planner.c (hunk 30 above)
Comment (anarazel) [inline src/backend/distributed/planner/multi_planner.c]: This seems like a superflous change to me.

File: src/test/regress/expected/multi_join_order_additional.out (hunk 29 above)
Comment (jasonmp85) [inline src/test/regress/expected/multi_join_order_additional.out]: Hm, I suppose. The three words I have trouble with discerning are _query_, _statement_, and _command_. Clearly _queries_ return results. The latter two, I'm not certain about, but I think I favor _command_ for some reason. _Statement_ seems something like _a = 5_ or _if (error) { return; }`. I guess in some languages those are also _expressions_. I'd have to check PostgreSQL's error messages to know what they favor, but my gut instinct is they also like _command_, even though the SQL standard divides things into _statements_ and _queries_.

This is obviously pretty nitpicky, but it was just something I noticed about that error message which bothered me (and is not even part of this change, so ignore I guess).

File: src/backend/distributed/shared_library_init.c (hunk 28 above)
Comment (jasonmp85) [inline src/backend/distributed/shared_library_init.c]: Just generally excited to see these things removed.

File: src/backend/distributed/executor/multi_executor.c (hunk 23 above)
Comment (jasonmp85) [inline src/backend/distributed/executor/multi_executor.c]: Gave my reasons. Just a little uncommon. Not extant in PostgreSQL symbols, `Stub` and `Fake` both are, and `Stub` at least has a more defined meaning in programming (a construct that will respond to an interface but generally not do anything).

File: src/backend/distributed/executor/multi_executor.c (hunk 20 above)
Comment (jasonmp85) [inline src/backend/distributed/executor/multi_executor.c]: I'm saying something like:

```c
bool isModificationQuery = IsModifyMultiPlan(multiPlan);

if (list_length(taskList) == 1)
{
  if (isModificationQuery)
  {
    scanState->customScanState.methods = &RouterSingleModifyCustomExecMethods;
  }
  else
  {
    scanState->customScanState.methods = &RouterSelectCustomExecMethods;
  }
}
else
{
  Assert(isModificationQuery);
  scanState->customScanState.methods = &RouterMultiModifyCustomExecMethods;
}
/* ... */
```

Does that make sense? I'm trying to figure out whether adding an `Assert` like that would be valid, and if it's not, I want to know why.

**Comment by jasonmp85** [comment]
FWIW none of my requests were blockers and I think I was largely brought on to make sure this knowledge got to someone outside you two anyhow.

That said, I want `DeSerialize` changed to `Deserialize`! Thanks.

File: src/backend/distributed/executor/multi_executor.c [hunk 33]
```diff
@@ -24,273 +24,442 @@
...
+ * results from temporary files into custom scan's tuple store. Then, it returns
+ * tuples one by one from this tuple store.
+ */
+TupleTableSlot *
+RealTimeExecScan(CustomScanState *node)
+{
+	CitusScanState *scanState = (CitusScanState *) node;
+	TupleTableSlot *resultSlot = NULL;
+
+	if (!scanState->finishedRemoteScan)
```
Comment (jasonmp85) [inline src/backend/distributed/executor/multi_executor.c]: Am I missing something, or is there some difference between `finished` and `performed`? They seem the same to me? `completed`?

(Are you reading success into `finished`?)

**Comment by jasonmp85** [comment]
Re: @anarazel's checklist, I feel _Make sure we still acquire all the right relation level locks_ is pretty amorphous :grin:.

File: src/backend/distributed/planner/multi_planner.c (hunk 32 above)
Comment (metdos) [inline src/backend/distributed/planner/multi_planner.c]: @anarazel that was my first impression. However, these functions are only called through Exec_XXX_Node() which checks the node tag and then call related Custom Scan function, so I though it is okay to remove the Assert.

File: src/backend/distributed/executor/multi_executor.c (hunk 20 above)
Comment (metdos) [inline src/backend/distributed/executor/multi_executor.c]: I see, and yeap this works. I don't see too much difference between them but I did the changes.

File: src/backend/distributed/executor/multi_executor.c [hunk 34]
```diff
@@ -24,273 +24,442 @@
...
 
-		ProcessUtility(masterCopyStmt,
-					   "(copy job)",
-					   PROCESS_UTILITY_QUERY,
-					   NULL,
-					   None_Receiver,
-					   NULL);
-	}
+	/* ensure plan is executable */
+	VerifyMultiPlanValidity(scanState->multiPlan);
```
Comment (metdos) [inline src/backend/distributed/executor/multi_executor.c]: @anarazel Hmm, I didn't quite get that. Don't we use the same logic to error out cases with parameterized sql functions? What is the different now?

File: src/backend/distributed/executor/multi_executor.c [hunk 35]
```diff
@@ -24,273 +24,442 @@
...
-	{
-		/* drop into the router executor */
-		RouterExecutorRun(queryDesc, direction, count);
-	}
-	else
-	{
-		/* drop into the standard executor */
-		standard_ExecutorRun(queryDesc, direction, count);
-	}
+	ValidateCitusScanState(node);
```
Comment (metdos) [inline src/backend/distributed/executor/multi_executor.c]: Right! I'm deleting ValidateCitusScanState() and also the Assert.

File: src/backend/distributed/executor/multi_executor.c (hunk 33 above)
Comment (metdos) [inline src/backend/distributed/executor/multi_executor.c]: All of them looks same to me too; finished, performed, completed.

I will let you guys pick one :)

**Comment by metdos** [comment]
> FWIW none of my requests were blockers and I think I was largely brought on to make sure this knowledge got to someone outside you two anyhow.

Sure, all the feedback is welcome.

> That said, I want DeSerialize changed to Deserialize! Thanks.

I already did this change in yesterday's commit.

**Comment by metdos** [comment]
> Should, however, only fail for router executor, and there only for non-partition things? Right?

No, this also fails with partition column parameters in router-executor.

**Comment by metdos** [comment]
> Verify query execution now happens during the 'execute' phase, not the 'bind' phase as before. A good way to test that is to use pgbench with -M extended, and use log_min_duration_statement=0

Nice trick. Thanks!

**Comment by metdos** [comment]
@anarazel, @jasonmp85,

I'm done with my changes and testing.

**Comment by anarazel** [comment]
> I'm done with my changes and testing.

What were the results of those performance tests?

**Comment by metdos** [comment]
> What were the results of those performance tests?

Didn't see any noticeable difference.

**Comment by anarazel** [comment]
> > What were the results of those performance tests?
> 
> Didn't see any noticeable difference.

Could you also check one more testcase: Concurrent pgbench for quick
router queries, let those run for a while. Compare before/after.  That's
something we previously had a lot of performance problems.


Also, did pg_stat_statements and such now work without any issues?

**Comment by metdos** [comment]
> Could you also check one more testcase: Concurrent pgbench for quick
> router queries, let those run for a while. Compare before/after.  That's
> something we previously had a lot of performance problems.

Sure, will run them tomorrow.
 
> Also, did pg_stat_statements and such now work without any issues?

Yeap!

**Comment by anarazel** [comment]
(can't comment directly on thread)

> @anarazel Hmm, I didn't quite get that. Don't we use the same logic to error out cases with parameterized sql functions? What is the different now?

Those should all generate plans with ->planningError set, thus would generate a DelayedError plan.

**Comment by metdos** [comment]
> Those should all generate plans with ->planningError set, thus would generate a DelayedError plan.

Right, now I ditched VerifyMultiPlanValidity and used RaiseDeferredError directly.

**Comment by metdos** [comment]
> Could you also check one more testcase: Concurrent pgbench for quick
> router queries, let those run for a while. Compare before/after.  That's
> something we previously had a lot of performance problems.

I run these today. Actually, I have seen up to 10% improvements on this branch.

**Comment by anarazel** [comment]
> Sure, will run them tomorrow.

Ping?

**Comment by anarazel** [comment]
> I run these today. Actually, I have seen up to 10% improvements on this branch.

Great.

File: src/backend/distributed/planner/multi_planner.c [hunk 36]
```diff
@@ -16,36 +16,55 @@
...
+
+static CustomScanMethods RouterCustomScanMethods = {
+	"Citus Router",
+	RouterCreateScan
+};
+
+static CustomScanMethods InvalidCustomScanMethods = {
+	"Citus Invalid",
+	DelayedErrorCreateScan
+};
```
Comment (anarazel) [inline src/backend/distributed/planner/multi_planner.c]: Inconsistent naming between invalid and delayed.
