### PR TITLE
Fix dropping sequences with metadata syncing

### LINKED ISSUE #1215: Cannot drop a table with a sequence if a node is down
We normally mark placements as having shardstate 4 if a drop table fails, but we still roll back if the table has a sequence.

```
postgres=# CREATE TABLE events (tenant_id int, event_id bigserial);

-- node goes down
postgres=# DROP TABLE events;
ERROR:  connection to the remote node localhost:9701 failed with the following error: could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 9701?
CONTEXT:  SQL statement "SELECT master_drop_sequences(sequence_names)"
PL/pgSQL function citus_drop_trigger() line 23 at PERFORM
```

### LINKED ISSUE #3885: Citus should record dependencies for sequences
If we have a citus table which has a column defaulting to an internal sequence created automatically by postgres (for a column definition like `columnName serial`, `columnName bigserial`), we can switch to MX without getting an error, which means, we propagate the underlying sequence to the worker nodes.

However, as we don't record dependencies for sequences, when we need to drop the table, we need to drop the sequence separately by executing `master_drop_sequences`, which doesn't seem to be a safe udf as @marcocitus mentioned in chat.

Recording dependencies for sequences might also fix another issue immediately: https://github.com/citusdata/citus/issues/3884

### LINKED ISSUE #4192: Cannot drop extension with sequence when metadata is synced
When metadata is synced, dropping an extension might fail with:

```sql
DROP EXTENSION pg_cron;
ERROR:  cannot drop sequence cron.jobid_seq because extension pg_cron requires it
HINT:  You can drop extension pg_cron instead.
CONTEXT:  while executing command on localhost:9700
SQL statement "SELECT master_drop_sequences(sequence_names)"
```

### PR DESCRIPTION
**Pull request by marcocitus**
DESCRIPTION: Fixes a bug that caused drop sequence failures when metadata syncing is enabled

This PR cuts the chord on `master_drop_sequences`, which was a buggy / hacky way of dropping the sequences for bigserial columns in MX tables, that would even wake up even for regular `DROP SEQUENCE` commands unrelated to Citus.

When creating the shell table on the workers during metadata syncing, we now explicitly create a `pg_depend` record via a `worker_record_sequence_dependency` UDF to recreate the dependency that is normally created when using bigserial. That means that dropping the distributed table automatically drops the sequence(s).

After this change, `master_drop_sequences` is still called during `CREATE EXTENSION` because we have many older citus_drop_trigger implementations which call it, and it is still called whenever a sequence is dropped. We may be able to remove it in a few years.

This does not set up dependencies for existing distributed tables with sequences on clusters that use metadata syncing, which would leave sequences behind when dropping those tables. Given that metadata syncing is rare and the problem only occurs once and is relatively easy to resolve (e.g. `SELECT run_command_on_workers('DROP SEQUENCE ...');`), it seemed not worth the added complexity.

Fixes #1215
Fixes #3885
Fixes #4192

### CODE REVIEW

File: src/backend/distributed/metadata/metadata_sync.c [hunk 1]
```diff
@@ -1101,6 +1111,104 @@ SequenceDDLCommandsForTable(Oid relationId)
...
+ * necessary to ensure that the sequence is dropped when the table is
+ * dropped.
+ */
+static List *
+SequenceDependencyCommandList(Oid relationId)
+{
+	List *sequenceCommandList = NIL;
+	char *relationName = generate_qualified_relation_name(relationId);
+	HeapTuple tup = NULL;
+	ScanKeyData key[2];
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/metadata/metadata_sync.c:1127]: Could move the declarations closer to their first usage

File: src/backend/distributed/metadata/metadata_sync.c [hunk 2]
```diff
@@ -1101,6 +1111,104 @@ SequenceDDLCommandsForTable(Oid relationId)
...
+	while (HeapTupleIsValid(tup = systable_getnext(scan)))
+	{
+		Form_pg_depend dependencyRecord = (Form_pg_depend) GETSTRUCT(tup);
+
+		/*
+		 * We assume any auto or internal dependency of a sequence on a column
+		 * must be what we are looking for.  (We need the relkind test because
+		 * indexes can also have auto dependencies on columns.)
+		 */
+		if (dependencyRecord->classid == RelationRelationId &&
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/metadata/metadata_sync.c:1152]: I have some questions/thoughts here:

1-> Why are we interested in DEPENDENCY_INTERNAL case? Does that cover the internal sequence creation for bigserial column?
2-> We could simplify this if check a bit with the usage of some variables maybe. For example it probably makes sense to combine `dependencyRecord->deptype == DEPENDENCY_AUTO` and `get_rel_relkind(dependencyRecord->objid) == RELKIND_SEQUENCE`. I have looked at the specific fields to understand what this if check is doing but for future I would suggest having something like this:

```c
bool isRefObjAColReference = dependencyRecord->refobjsubid != 0;
bool isSeqDepType = (dependencyRecord->deptype == DEPENDENCY_AUTO && get_rel_relkind(dependencyRecord->objid) == RELKIND_SEQUENCE)
 || dependencyRecord->deptype == DEPENDENCY_INTERNAL;
```

File: src/backend/distributed/metadata/metadata_sync.c [hunk 3]
```diff
@@ -1101,6 +1111,104 @@ SequenceDDLCommandsForTable(Oid relationId)
...
+ * the table in pg_depend, such that it will be automatically dropped.
+ */
+Datum
+worker_record_sequence_dependency(PG_FUNCTION_ARGS)
+{
+	Oid sequenceOid = PG_GETARG_OID(0);
+	Oid relationOid = PG_GETARG_OID(1);
+	int columnIndex = PG_GETARG_INT32(2);
+
+	ObjectAddress sequenceAddr = { 0, 0, 0 };
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/metadata/metadata_sync.c:1194]: Could just do:

```c
	ObjectAddress sequenceAddr = { 
		.classId = RelationRelationId, 
		.objectId = sequenceOid,
		.objectSubId = 0};
```

**Review by SaitTalhaNisanci — COMMENTED** [review]
I tested manually some different combinations and they worked as expected

File: src/backend/distributed/metadata/metadata_sync.c (hunk 2 above)
Comment (marcocitus) [reply src/backend/distributed/metadata/metadata_sync.c:1152]: This is copied from getOwnedSequences_internal, I'll add a note.

File: src/backend/distributed/metadata/metadata_sync.c [hunk 4]
```diff
@@ -1101,6 +1113,124 @@ SequenceDDLCommandsForTable(Oid relationId)
...
+ * necessary to ensure that the sequence is dropped when the table is
+ * dropped.
+ *
+ * This function is derived from getOwnedSequences_internal.
+ */
+static List *
+SequenceDependencyCommandList(Oid relationId)
+{
+	List *sequenceCommandList = NIL;
+	char *relationName = generate_qualified_relation_name(relationId);
```
Comment (onurctirtir) [inline src/backend/distributed/metadata/metadata_sync.c:1129]: Can't we directly use `getOwnedSequences` here ?

File: src/backend/distributed/metadata/metadata_sync.c (hunk 2 above)
Comment (onurctirtir) [reply src/backend/distributed/metadata/metadata_sync.c:1156]: >This is copied from getOwnedSequences_internal, I'll add a note.

related: https://github.com/citusdata/citus/pull/4203#discussion_r498256254

**Comment by onurctirtir** [comment]
>Fixes #3885

When openning #3885 & #3884, I thought that fixing #3885 might also fix #3884. Do you think that it is the case @marcocitus  ?

**Comment by marcocitus** [comment]
> When openning #3885 & #3884, I thought that fixing #3885 might also fix #3884. Do you think that it is the case @marcocitus ?

no, that requires propagating CREATE SEQUENCE, which we don't do right now.

File: src/backend/distributed/metadata/metadata_sync.c (hunk 4 above)
Comment (marcocitus) [reply src/backend/distributed/metadata/metadata_sync.c:1129]: we need the pg_depend record to get the column index (refobjsubid)

Comment (onurctirtir) [reply src/backend/distributed/metadata/metadata_sync.c:1129]: If we need column index too, I wonder if `ExtractColumnsOwningSequences` does the same thing then ?

Comment (marcocitus) [reply src/backend/distributed/metadata/metadata_sync.c:1129]: Hmz, that function returns column names instead of indexes, but thinking about this more, it would be good to actually use column names instead of column indexes, since there might be scenarios in which the indexes don't match (drop a column that precedes the sequence, rebalance). Will change that.

File: src/backend/distributed/commands/sequence.c [hunk 5]
```diff
@@ -147,3 +148,57 @@ OptionsSpecifyOwnedBy(List *optionList, Oid *ownedByTableId)
...
 }
+
+
+/*
+ * ExtractColumnsOwningSequences finds each column of relation with relationId
+ * defaulting to an owned sequence. Then, appends the column name and id of the
+ * owned sequence -that the column defaults- to the lists passed as NIL initially.
+ */
+void
+ExtractColumnsOwningSequences(Oid relationId, List **columnNameList,
```
Comment (marcocitus) [inline src/backend/distributed/commands/sequence.c:159]: moved ad verbatim from create_citus_local_table.c

File: src/backend/distributed/metadata/metadata_sync.c [hunk 6]
```diff
@@ -1101,6 +1113,103 @@ SequenceDDLCommandsForTable(Oid relationId)
...
+/*
+ * worker_record_sequence_dependency records the fact that the sequence depends on
+ * the table in pg_depend, such that it will be automatically dropped.
+ */
+Datum
+worker_record_sequence_dependency(PG_FUNCTION_ARGS)
+{
+	Oid sequenceOid = PG_GETARG_OID(0);
+	Oid relationOid = PG_GETARG_OID(1);
+	int columnIndex = PG_GETARG_INT32(2);
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/metadata/metadata_sync.c:1193]: we should probably get column name here

**Review by SaitTalhaNisanci — APPROVED** [review]
