### PR TITLE
Start erroring out for unsupported lateral subqueries

### LINKED ISSUE #5327: LATERAL JOIN with reference table on left side and LIMIT and/or OFFSET returns incorrect results
## Basic problem
A common reason for using a LATERAL JOIN is to get the top-N rows for each row on the left side of the LATERAL JOIN. Similar to what you could do with a window function by using `rownumber() < 3`. See the following plain Postgres example:

Schema:
```sql
set citus.shard_count = 4;
create table ref(
    id bigserial,
    extra bigint
);
create table dist(
    id bigserial PRIMARY KEY,
    foreign_id bigint NOT NULL
);

insert into ref(id, extra) VALUES (1, 2), (3, 4);
insert into dist(id, foreign_id) SELECT i, 1 FROM generate_series(1, 10) i;
insert into dist(id, foreign_id) SELECT i, 3 FROM generate_series(11, 40) i;
```

Query:
```sql
SELECT r.id as rid, q.did as did
FROM ref r
JOIN LATERAL (
    SELECT
        d.id as did
    FROM dist d
    WHERE
        r.id = d.foreign_id
    ORDER BY d.id DESC
    LIMIT 2
) q ON TRUE;
```
```
┌─────┬─────┐
│ rid │ did │
├─────┼─────┤
│   1 │  10 │
│   1 │   9 │
│   3 │  40 │
│   3 │  39 │
└─────┴─────┘
```

However, if I make the first table a reference table and the other a distributed one, and run the query again then results are very totally incorrect:
```sql
select create_reference_table('ref');
select create_distributed_table('dist', 'id');

SELECT r.id as rid, q.did as did
FROM ref r
JOIN LATERAL (
    SELECT
        d.id as did
    FROM dist d
    WHERE
        r.id = d.foreign_id
    ORDER BY d.id DESC
    LIMIT 2
) q ON TRUE;
```
```
┌─────┬─────┐
│ rid │ did │
├─────┼─────┤
│   1 │   7 │
│   1 │   4 │
│   3 │  40 │
│   3 │  37 │
│   1 │  10 │
│   1 │   8 │
│   3 │  35 │
│   3 │  33 │
│   1 │   9 │
│   1 │   2 │
│   3 │  32 │
│   3 │  30 │
│   1 │   6 │
│   3 │  39 │
│   3 │  38 │
└─────┴─────┘
```

We get the top 2 rows for each shard back instead of the top 2 rows for each table. The result can be made correct by re-doing the LATERAL JOIN on the coordinator on this result set:
```sql
WITH cte AS MATERIALIZED (
    SELECT r.id as rid, q.did as did
    FROM ref r
    JOIN LATERAL (
        SELECT
            d.id as did
        FROM dist d
        WHERE
            r.id = d.foreign_id
        ORDER BY d.id DESC
        LIMIT 2
    ) q ON TRUE
)
SELECT r.id as rid, q2.did as did
FROM ref r
JOIN LATERAL (
    SELECT
        cte.did
    FROM cte
    WHERE r.id = cte.rid
    ORDER BY cte.did DESC
    LIMIT 2
) q2 ON TRUE;
```
```
┌─────┬─────┐
│ rid │ did │
├─────┼─────┤
│   1 │  10 │
│   1 │   9 │
│   3 │  40 │
│   3 │  39 │
└─────┴─────┘
```

## Complex problem
However, this is not enough for some more complex query and data. When I add one extra row and run the following slightly more complex query on plain Postgres I get these results:
```sql
select * from undistribute_table('ref');
select * from undistribute_table('dist');

insert into ref(id, extra) VALUES (1, 3);

SELECT r.id as rid, r.extra, q.did as did
FROM ref r
JOIN LATERAL (
    SELECT
        d.id as did
    FROM dist d
    WHERE
        r.id = d.foreign_id
    ORDER BY d.id DESC
    OFFSET 1
    LIMIT 2
) q ON TRUE;
```
```
┌─────┬───────┬─────┐
│ rid │ extra │ did │
├─────┼───────┼─────┤
│   1 │     2 │   9 │
│   1 │     2 │   8 │
│   3 │     4 │  39 │
│   3 │     4 │  38 │
│   1 │     3 │   9 │
│   1 │     3 │   8 │
└─────┴───────┴─────┘
```

And I then distribute again and try to fix the query in the same way, the results are incorrect in a different way:
```sql
select create_reference_table('ref');
select create_distributed_table('dist', 'id');

WITH cte AS MATERIALIZED (
    SELECT r.id as rid, q.did as did
    FROM ref r
    JOIN LATERAL (
        SELECT
            d.id as did
        FROM dist d
        WHERE
            r.id = d.foreign_id
        ORDER BY d.id DESC
        OFFSET 1
        LIMIT 2
    ) q ON TRUE
)
SELECT r.id as rid, r.extra, q2.did as did
FROM ref r
JOIN LATERAL (
    SELECT
        cte.did
    FROM cte
    WHERE r.id = cte.rid
    ORDER BY cte.did DESC
    LIMIT 2
) q2 ON TRUE;
```
```
┌─────┬───────┬─────┐
│ rid │ extra │ did │
├─────┼───────┼─────┤
│   1 │     2 │   8 │
│   1 │     2 │   8 │
│   3 │     4 │  38 │
│   3 │     4 │  37 │
│   1 │     3 │   8 │
│   1 │     3 │   8 │
└─────┴───────┴─────┘
```

To get the correct results the following modifications need to be made:
```sql
WITH cte AS MATERIALIZED (
    SELECT q_r.id as rid, q_d.did as did
    FROM (
        -- subquery that groups reference table by all the columns that are
        -- used in the lateral join
        SELECT r.id from ref r GROUP BY r.id
    ) q_r
    JOIN LATERAL (
        SELECT
            d.id as did
        FROM dist d
        WHERE
            q_r.id = d.foreign_id
        ORDER BY d.id DESC
        -- To be able to use OFFSET and LIMIT correctly on the coordinator we
        -- need to get all relevant rows, so we use the original LIMIT + OFFSET
        -- as the LIMIT here.
        LIMIT 3
    ) q_d ON TRUE
)
SELECT r.id as rid, r.extra, q2.did as did
FROM ref r
JOIN LATERAL (
    SELECT
        cte.*
    FROM cte
    WHERE r.id = cte.rid
    ORDER BY cte.did DESC
    OFFSET 1
    LIMIT 2
) q2 ON TRUE;
```
```
┌─────┬───────┬─────┐
│ rid │ extra │ did │
├─────┼───────┼─────┤
│   1 │     2 │   9 │
│   1 │     2 │   8 │
│   3 │     4 │  39 │
│   3 │     4 │  38 │
│   1 │     3 │   9 │
│   1 │     3 │   8 │
└─────┴───────┴─────┘
```

### PR DESCRIPTION
**Pull request by JelteF**
DESCRIPTION: Start erroring out for unsupported lateral subqueries

With the introduction of #4385 we inadvertently started allowing and
pushing down certain lateral subqueries that were unsafe to push down.
To be precise the type of LATERAL subqueries that is unsafe to push down
has all of the following properties:
1. The lateral subquery contains some non recurring tuples
2. The lateral subquery references a recurring tuple from
   outside of the subquery (recurringRelids)
3. The lateral subquery requires a merge step (e.g. a LIMIT)
4. The reference to the recurring tuple should be something else than an
   equality check on the distribution column, e.g. equality on a non
   distribution column.

Property number four is considered both hard to detect and probably not
used very often. Thus this PR ignores property number four and causes
query planning to error out if the first three properties hold.

Fixes #5327

### CODE REVIEW

File: src/backend/distributed/planner/query_pushdown_planning.c [hunk 1]
```diff
@@ -1397,6 +1427,40 @@ RelationInfoContainsOnlyRecurringTuples(PlannerInfo *plannerInfo, Relids relids)
...
+	while ((relationId = bms_next_member(relids, relationId)) >= 0)
+	{
+		RangeTblEntry *rangeTableEntry = plannerInfo->simple_rte_array[relationId];
+
+		if (!rangeTableEntry->lateral)
+		{
+			continue;
+		}
+
+		/* TODO: What about others kinds? */
```
Comment (onderkalaci) [inline src/backend/distributed/planner/query_pushdown_planning.c:1448]: bool		lateral;		/* subquery, function, or values is LATERAL? */

From `RangeTblEntry`

Comment (marcocitus) [reply src/backend/distributed/planner/query_pushdown_planning.c:1448]: do we need to consider something like `LEFT JOIN LATERAL fn((SELECT count(*) FROM dist)) ON (true)`?

File: src/test/regress/expected/multi_subquery_complex_queries.out [hunk 2]
```diff
@@ -1274,16 +1274,8 @@ FROM
...
-       1 | Thu Nov 23 18:08:26.550729 2017
-       2 | Thu Nov 23 17:26:14.563216 2017
-       3 | Thu Nov 23 18:08:26.550729 2017
-       3 | Thu Nov 23 17:26:14.563216 2017
-       5 | Thu Nov 23 17:26:14.563216 2017
-       6 | Thu Nov 23 18:08:26.550729 2017
-(6 rows)
-
+ERROR:  cannot push down this subquery
+DETAIL:  Limit in subquery is currently unsupported when a subquery references a column from another query
```
[the remark this answers is not in the document]
Comment (JelteF) [reply src/test/regress/expected/multi_subquery_complex_queries.out:1278]: Really it should be:
> Limit in subquery is currently unsupported when a lateral subquery references a column from an {recurring tuple type}

File: src/backend/distributed/planner/query_pushdown_planning.c (hunk 1 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/query_pushdown_planning.c:1448]: As of today, we replace FUNCTIONs in the JOIN trees with subqueries automatically: https://github.com/citusdata/citus/blob/master/src/backend/distributed/planner/recursive_planning.c#L1588

But seems to ignore LATERALS: https://github.com/citusdata/citus/blob/master/src/backend/distributed/planner/recursive_planning.c#L1803-L1812

So, definitely worth testing but I wouldn't mind if it fails

Comment (marcocitus) [reply src/backend/distributed/planner/query_pushdown_planning.c:1448]: Seems this is incorrectly allowed:
```sql
 CREATE OR REPLACE FUNCTION fn(x int)
RETURNS int
AS $$
DECLARE
BEGIN
        RETURN x + 1;
END;
$$ LANGUAGE plpgsql;

SELECT count(*)
FROM ref JOIN test on ref.b = test.x,
    LATERAL fn((
        SELECT
            test_2.x
        FROM test test_2
        WHERE
            test_2.x = test.x
        LIMIT 1
    )) q
;
```

Comment (JelteF) [reply src/backend/distributed/planner/query_pushdown_planning.c:1448]: Yes, but it's not just this new code that doesn't handle it. It doesn't even get to the `DeferredErrorIfUnsupportedLateralSubquery` check. This is because `RelationInfoContainsOnlyRecurringTuples` is not handling this correctly. I discussed with Onder and this query is also wrong, which even uses a LEFT JOIN.
```
SELECT count(*)
FROM ref LEFT JOIN GREATEST(
        0,
        (SELECT
            test.y
        FROM test
        WHERE
            test.y = ref.a
        LIMIT 1)
    ) ON TRUE;
```

Comment (JelteF) [reply src/backend/distributed/planner/query_pushdown_planning.c:1448]: Without the left join also returns incorrect results:
```sql
SELECT count(*)
FROM ref,
    LATERAL GREATEST(
        0,
        (SELECT
            test.y
        FROM test
        WHERE
            test.y = ref.a
        LIMIT 1)
    );
```

Comment (JelteF) [reply src/backend/distributed/planner/query_pushdown_planning.c:1502]: Another one that returns wrong results:
```sql
SELECT count(*)
FROM (select GREATEST(1, 3)) ref(a),
    LATERAL (
        SELECT
            test.y
        FROM test
        WHERE
            test.y = ref.a
        LIMIT 2
    ) q;
```

File: src/test/regress/expected/multi_subquery_complex_queries.out (hunk 2 above)
[the remark this answers is not in the document]
Comment (JelteF) [reply src/test/regress/expected/multi_subquery_complex_queries.out]: I improved the error messages.

File: src/backend/distributed/planner/query_pushdown_planning.c [hunk 3]
```diff
@@ -844,6 +848,35 @@ DeferredErrorIfUnsupportedRecurringTuplesJoin(
 				break;
 			}
 		}
+		else if (joinType == JOIN_INNER && plannerInfo->hasLateralRTEs)
+		{
+			bool innerrelOnlyRecurring = RelationInfoContainsOnlyRecurringTuples(
+				plannerInfo, innerrelRelids);
+			bool outerrelOnlyRecurring = RelationInfoContainsOnlyRecurringTuples(
+				plannerInfo, outerrelRelids);
+			if (innerrelOnlyRecurring && !outerrelOnlyRecurring)
```
Comment (marcocitus) [inline src/backend/distributed/planner/query_pushdown_planning.c:857]: this might error on <dist>, LATERAL (SELECT .. <ref>) type queries, which work fine so we probably don't want to break those

Comment (JelteF) [reply src/backend/distributed/planner/query_pushdown_planning.c:857]: There's this query that looks fine, but also fails
```sql
SELECT count(*)
FROM test,
    LATERAL (
        SELECT
            test_2.y
        FROM test test_2
        WHERE
            test_2.x = test.x
        LIMIT 2
    ) q
    JOIN ref ON q.y = ref.a;
```

File: src/backend/distributed/planner/query_pushdown_planning.c (hunk 1 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/query_pushdown_planning.c:1502]: For future reference: Our brief check with Jelte showed that there are `SubPlans` and they do not show up in `plannerInfo->simple_rte_array[relationId];` So, we might need to include the Rtes of subplans on all the places we rely on `plannerInfo->simple_rte_array[relationId];`

File: src/backend/distributed/planner/query_pushdown_planning.c [hunk 4]
```diff
@@ -1397,6 +1467,259 @@ RelationInfoContainsOnlyRecurringTuples(PlannerInfo *plannerInfo, Relids relids)
...
+	{
+		Query *query = (Query *) node;
+		int flags = 0;
+
+		context->level += 1;
+		bool found = query_tree_walker(query, ContainsReferencesToRelidsWalker,
+									   context, flags);
+		context->level -= 1;
+
+		return found;
```
Comment (marcocitus) [inline src/backend/distributed/planner/query_pushdown_planning.c:1626]: is it possible to cover this code?

File: src/backend/distributed/planner/query_pushdown_planning.c (hunk 1 above)
Comment (marcocitus) [reply src/backend/distributed/planner/query_pushdown_planning.c:1666]: some elaboration on the TODO with this context would be helpful

**Review by marcocitus — APPROVED** [review]

**Comment by JelteF** [comment]
Merging this now so it's included for release testing. I'll add some more coverage somewhere next week.

**Comment by onderkalaci** [comment]
should we backport this to 10.2?

**Comment by marcocitus** [comment]
No, some queries might start erroring out.
