### PR TITLE
Make sure that modifying CTEs always use the correct execution mode

### LINKED ISSUE #2338: Modifying CTEs do not properly switch the execution mode
As the below example show, after `t1` executed, the query execution mode should have been switched to sequential. However, it does not and we got into a self-deadlock.

In general, modifying CTEs may cause such issues given that the decision to use `parallel` vs `sequential` mode has been given before we've executed the subplans.

```SQL
-- set the mode to sequential for the next operations
CREATE TABLE reference_table(id int PRIMARY KEY);
SELECT create_reference_table('reference_table');

CREATE TABLE distributed_table(id int PRIMARY KEY, value_1 int);
SELECT create_distributed_table('distributed_table', 'id');

ALTER TABLE 
	distributed_table 
ADD CONSTRAINT 
	fkey_delete FOREIGN KEY(value_1) 
REFERENCES 
	reference_table(id) ON DELETE CASCADE;

INSERT INTO reference_table SELECT i FROM generate_series(0, 10) i;
INSERT INTO distributed_table SELECT i, i % 10  FROM generate_series(0, 100) i;

WITH t1 AS (DELETE FROM reference_table RETURNING id) 
	DELETE FROM distributed_table USING t1 WHERE value_1 = t1.id RETURNING *;
ERROR:  canceling the transaction since it was involved in a distributed deadlock

```

### PR DESCRIPTION
**Pull request by onderkalaci**
Fixes #2338

We're simply deferring the execution mode decision right after `ExecuteSubPlans ()`. 

Could be backported but doesn't seem like a very critical fix to have a point release only for this (as @marcocitus also thinks similarly).

### CODE REVIEW

File: src/backend/distributed/executor/citus_custom_scan.c [hunk 1]
```diff
@@ -221,20 +212,7 @@ RouterCreateScan(CustomScan *scan)
...
-			 * to 'sequential' or Multi-row INSERT are executed sequentially
-			 * instead of using parallel connections.
-			 */
-			scanState->customScanState.methods = &RouterSequentialModifyCustomExecMethods;
-		}
-		else
-		{
-			scanState->customScanState.methods = &RouterMultiModifyCustomExecMethods;
-		}
+		scanState->customScanState.methods = &RouterModifyCustomExecMethods;
```
Comment (marcocitus) [inline src/backend/distributed/executor/citus_custom_scan.c]: I think the distinction between this block and the one above is no longer relevant.

File: src/backend/distributed/executor/multi_router_executor.c [hunk 2]
```diff
@@ -615,6 +583,77 @@ RouterSequentialModifyExecScan(CustomScanState *node)
...
+	{
+		Task *task = (Task *) lfirst(taskCell);
+
+		/*
+		 * Result is expected for SELECT ... FOR UPDATE queries as well.
+		 */
+		executorState->es_processed +=
+			ExecuteSingleModifyTask(scanState, task, operation,
+									alwaysThrowErrorOnFailure,
+									hasReturning || task->relationRowLockList != NIL);
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_router_executor.c]: As a minor clean-up while we're doing this, it might be nice to declare an `expectResults` variable. It's also not obvious that the comment above applies to this line.

File: src/backend/distributed/executor/citus_custom_scan.c (hunk 1 above)
Comment (onderkalaci) [reply src/backend/distributed/executor/citus_custom_scan.c]: makes sense

**Comment by onderkalaci** [comment]
> @marcocitus I've applied your feedback, could you have a quick look again?

@marcocitus Do you want to have a quick look, or shall I go ahead and merge?

Thanks!
