### PR TITLE
Split columnar stripe reservation into two phases

### LINKED ISSUE #5160: Columnar fails to detect duplicate key violation when there are pending writes
```sql
drop table test;
create table test (a int unique) using columnar;

-- s1 --
begin;
insert into test select s from generate_series(1,2) s;

-- s2 --
-- (s2-insert)->_bt_doinsert checks if there is any unique constraint
-- violation. s1-insert already inserted the tuples into the index
-- but didn't flush the write state yet. (s2-insert)->_bt_doinsert sees
-- index tuples inserted by s1-insert, so calls columnar_index_fetch_tuple
-- to test their visibility, but columnar_index_fetch_tuple can't find
-- index tuples inserted by s1-insert in stripe metadata since write
-- state of s1-insert is not flushed yet.
--
-- moreover, (s2-insert)->columnar_index_fetch_tuple flushes current
-- transaction's write state for each tuple being tested so we end up
-- with a weird stripe metadata, see bottom
insert into test select s from generate_series(1,4) s;

-- s1 --
commit;

-- now we have duplicate values despite the unique index
select * from test;
┌───┐
│ a │
├───┤
│ 1 │
│ 2 │
│ 1 │
│ 2 │
│ 3 │
│ 4 │
└───┘
(6 rows)

-- moreover, since s2 flushes its own writes when checking uniqueness, stripe metadata looks a bit strange
select * from columnar.stripe ;
┌─────────────┬────────────┬─────────────┬─────────────┬──────────────┬─────────────────┬───────────┬───────────────────┬──────────────────┐
│ storage_id  │ stripe_num │ file_offset │ data_length │ column_count │ chunk_row_count │ row_count │ chunk_group_count │ first_row_number │
├─────────────┼────────────┼─────────────┼─────────────┼──────────────┼─────────────────┼───────────┼───────────────────┼──────────────────┤
│ 10000000020 │          1 │       16336 │          16 │            1 │           10000 │         1 │                 1 │           150001 │
│ 10000000020 │          2 │       24504 │          16 │            1 │           10000 │         1 │                 1 │           300001 │
│ 10000000020 │          3 │       32672 │          20 │            1 │           10000 │         2 │                 1 │           450001 │
│ 10000000020 │          4 │       40840 │          20 │            1 │           10000 │         2 │                 1 │                1 │
└─────────────┴────────────┴─────────────┴─────────────┴──────────────┴─────────────────┴───────────┴───────────────────┴──────────────────┘
(4 rows)
```

### PR DESCRIPTION
**Pull request by onurctirtir**
Fixes #5160.
(Rebased onto #5154)

Previously, we were doing `first_row_number` reservation for the first
row written to current `WriteState` but were doing `stripe_id`
reservation when flushing the `WriteState` and were inserting the
related record to `columnar.stripe` at that time as well.

However, inserting `columnar.stripe` record at flush-time is
problematic. This is because, as told in #5160, if relation has
any index-based constraints and if there are two concurrent
writes that are inserting conflicting key values for that constraint,
then postgres relies on `tableAM->fetch_index_tuple`
(=`columnar_fetch_index_tuple`) callback to return `true` when
indexAM is checking against possible constraint violations.

However, pending writes of other backends are not visible to concurrent
sessions in columnar since we were not inserting the stripe metadata
record until flushing the stripe.

With this PR, we split stripe reservation into two phases:
i) Reserve `stripe_id` and insert a "dummy" record to `columnar.stripe`
at the very same time we reserve `first_row_number`, i.e. when writing
the first row to the current `WriteState`.
ii) At flush time, do the storage level allocation and complete the
missing fields of the dummy record inserted into `columnar.stripe`
during i).

That way, any concurrent writes would be able to check against possible
constraint violations by using `SnapshotDirty` when scanning
`columnar.stripe`.

Note that `columnar_fetch_index_tuple` still wouldn't be able to fill
the output tupleslot for the requested tid but it would at least return
`true` for such index look-up's and we believe this should be sufficient
for the caller indexAM callback to make the concurrent writer block on
prior one.

That is how we fix #5160.

Only downside of reserving `stripe_id` at the same time we reserve
`first_row_number` is that now any aborted writes would also waste
some amount of `stripe_id` as in the case of `first_row_number` but
we are just wasting them one-by-one.

Considering the fact that we waste `first_row_number` by the amount
stripe row limit (=150k by default) in such cases, this shouldn't be
important at all.

### CODE REVIEW

File: src/backend/columnar/columnar_tableam.c [hunk 1]
```diff
@@ -529,12 +529,39 @@ columnar_index_fetch_tuple(struct IndexFetchTableData *sscan,
...
+		 * FindStripeWithMatchingFirstRowNumber doesn't verify upper row
+		 * number boundary of found stripe. For this reason, we didn't
+		 * certainly know if given row number belongs to one of the stripes.
+		 */
+		return false;
+	}
+
+	if (!StripeIsFlushed(stripeMetadata))
+	{
+		/*
```
Comment (jeff-davis) [inline src/backend/columnar/columnar_tableam.c:554]: If the snapshot is not SnapshotDirty, it looks like that will be caught later, right? It might be good to Assert here just for documentation.

File: src/backend/columnar/columnar_metadata.c [hunk 2]
```diff
@@ -953,35 +1040,123 @@ GetHighestUsedAddressAndId(uint64 storageId,
...
+				   uint64 stripeRowCount)
 {
-	StripeMetadata stripe = { 0 };
+	EmptyStripeReservation *stripeReservation = palloc0(sizeof(EmptyStripeReservation));
 
 	uint64 storageId = ColumnarStorageGetStorageId(rel, false);
 
-	uint64 stripeId = ColumnarStorageReserveStripe(rel);
+	/* do stripe id and first row number reservations atomically */
+	LockRelationForExtension(rel, ExclusiveLock);
```
Comment (jeff-davis) [inline src/backend/columnar/columnar_metadata.c:1056]: This should be handled by columnar_storage, right?

**Review by jeff-davis — APPROVED** [review]

File: src/backend/columnar/columnar_metadata.c (hunk 2 above)
Comment (onurctirtir) [reply src/backend/columnar/columnar_metadata.c:1056]: Right, then should I add a new function to columnar_storage that reserves both stripe & first_row_number using the lower-level functions ?

Comment (jeff-davis) [reply src/backend/columnar/columnar_metadata.c:1056]: Is there a reason those need to be done automically? I'm fine with adding a function like that, it makes sense, I'm just wondering if it's a requirement.

**Comment by onurctirtir** [comment]
@jeff-davis suggested: What about not inserting dummy stripe metadata entries but doing some bookkeeping in a shared hash-table ?

File: src/backend/columnar/columnar_metadata.c (hunk 2 above)
Comment (onurctirtir) [reply src/backend/columnar/columnar_metadata.c:1056]: Actually there is no reason for doing both atomically, just wanted to be consistent.

Does it still makes sense if I add a function for that to `columnar_storage.c`, or do you think it wouldn't worth as it is not a requirement ?

File: src/backend/columnar/columnar_tableam.c (hunk 1 above)
Comment (onurctirtir) [reply src/backend/columnar/columnar_tableam.c:554]: > it looks like that will be caught later, right?

yes

it might be good to Assert here just for documentation.

👍

**Comment by onurctirtir** [comment]
> @jeff-davis suggested: What about not inserting dummy stripe metadata entries but doing some bookkeeping in a shared hash-table ?

I'm more inclined to deferring this change to later due to limited time, what do you think @jeff-davis ?
