### PR TITLE
Fix error in master_disable_node/citus_disable_node

### LINKED ISSUE #7454: Error in master_disable_node/citus_disable_node
master_disable_node has only two arguments
`CREATE FUNCTION master_disable_node(nodename text, nodeport integer)`
but its realization is
```
Datum
master_disable_node(PG_FUNCTION_ARGS)
{
	return citus_disable_node(fcinfo);
}
```
while citus_disable_node has three arguments and always reads all of them
```
Datum
citus_disable_node(PG_FUNCTION_ARGS)
{
	text *nodeNameText = PG_GETARG_TEXT_P(0);
	int32 nodePort = PG_GETARG_INT32(1);
	bool synchronousDisableNode = PG_GETARG_BOOL(2);
...
```

Thus when master_disable_node is called, memory outside of the function call info is accessed, and further behavior is undefined

### PR DESCRIPTION
**Pull request by Green-Chan**
This fixes #7454: master_disable_node() has only two arguments, but calls citus_disable_node() that tries to read three arguments

### CODE REVIEW

File: src/backend/distributed/metadata/node_metadata.c [hunk 1]
```diff
@@ -507,7 +507,13 @@ citus_disable_node(PG_FUNCTION_ARGS)
 {
 	text *nodeNameText = PG_GETARG_TEXT_P(0);
 	int32 nodePort = PG_GETARG_INT32(1);
-	bool synchronousDisableNode = PG_GETARG_BOOL(2);
+
+	bool synchronousDisableNode = 1;
```
Comment (Green-Chan) [inline src/backend/distributed/metadata/node_metadata.c:511]: I don't understand how master_disable_node() should work (see also #2063 on this topic), but if synchronousDisableNode = 0 by default, some tests are failing. For example, isolation_add_remove_node with
```
 step s1-disable-node-1: 
  SELECT 1 FROM master_disable_node('localhost', 57637);
  SELECT public.wait_until_metadata_sync();
 
-?column?
----------------------------------------------------------------------
-       1
-(1 row)
-
-wait_until_metadata_sync
----------------------------------------------------------------------
-
-(1 row)
-
+ERROR:  disabling the first worker node in the metadata is not allowed
 step s2-disable-node-1: 
  SELECT 1 FROM master_disable_node('localhost', 57637);
  SELECT public.wait_until_metadata_sync();
- <waiting ...>
+
+ERROR:  disabling the first worker node in the metadata is not allowed
```
in diff

**Review by JelteF — APPROVED** [review]
