### PR TITLE
Fixes a crash in queries with a modifying CTE and a SELECT without FROM

### LINKED ISSUE #4798: Modifying local execution queries which require CoordinatorEvaluation and doesn't have any relations crashes
```SQL

select * from pg_dist_node;
 nodeid | groupid | nodename  | nodeport | noderack | hasmetadata | isactive | noderole | nodecluster | metadatasynced | shouldhaveshards 
--------+---------+-----------+----------+----------+-------------+----------+----------+-------------+----------------+------------------
      1 |       0 | localhost |     5432 | default  | t           | t        | primary  | default     | t              | t
(1 row)

Time: 2.286 ms


CREATE TABLE test (a int, b int);
SELECT create_distributed_table('test', 'a');


WITH cte_1 AS (UPDATE test SET b = 1 WHERE a  = 1 RETURNING *)
	SELECT random();
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
Time: 7.724 ms
 @:-!> 
```

The backtrace:
```

* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x000000010ef3f395 citus.so`RebuildQueryStrings(workerJob=0x00007ff178057a28) at deparse_shard_query.c:60:38
   57   {
   58           Query *originalQuery = workerJob->jobQuery;
   59           List *taskList = workerJob->taskList;
-> 60           Oid relationId = ((RangeTblEntry *) linitial(originalQuery->rtable))->relid;
   61           RangeTblEntry *valuesRTE = ExtractDistributedInsertValuesRTE(originalQuery);
   62   
   63           Task *task = NULL;
```

### PR DESCRIPTION
**Pull request by marcocitus**
DESCRIPTION: Fixes a crash in queries with a modifying CTE and a SELECT without FROM

RebuildQueryStrings and UpdateTaskQueryString were a bit messy, which led to this bug. 

I did some basic refactoring to only handle multi-row insert logic in UpdateTaskQueryString and do other pre-processing of the query tree in RebuildQueryStrings. Probably not ideal, but more sane and less crashy.

Fixes #4798

### CODE REVIEW

File: src/backend/distributed/planner/deparse_shard_query.c [hunk 1]
```diff
@@ -57,18 +58,39 @@ RebuildQueryStrings(Job *workerJob)
 {
```
Comment (onderkalaci) [inline src/backend/distributed/planner/deparse_shard_query.c:58]: I think the function comment of `RebuildQueryStrings` is not reflecting what it does anymore (probably not in the last couple of years :))

**Review by onderkalaci — APPROVED** [review]
Working on this part of the code always scares me as we had some prepared statement bugs  in the past. I tried to make sure that we don't have any changes in the flow of the code.

Overall, this is further simplifying the code, thanks for that
