### PR TITLE
Avoid use of pnstrdup

### LINKED ISSUE #836: Wrong use of pstrndup causes valgrind errors
@marcocitus @robin900 
```
		char *shardRelationName = pnstrdup(relationName, NAMEDATALEN);
```
added in f677fadbe686ed370844549e06d9cd3c8c46bbb0 isn't correct, as that tries to copy NAMEDATALEN characters from the input.  This leads to valgrind bleats like
```
==19921== VALGRINDERROR-BEGIN
==19921== Invalid read of size 8
==19921==    at 0x4C31640: memmove (vg_replace_strmem.c:1252)
==19921==    by 0x959410: pnstrdup (mcxt.c:1101)
==19921==    by 0x6910E52: DropShards (master_delete_protocol.c:320)
==19921==    by 0x6910BA5: master_drop_all_shards (master_delete_protocol.c:232)
==19921==    by 0x66DF70: ExecMakeFunctionResultNoSets (execQual.c:2019)
==19921==    by 0x66E88C: ExecEvalFunc (execQual.c:2410)
==19921==    by 0x674E23: ExecTargetList (execQual.c:5401)
==19921==    by 0x675568: ExecProject (execQual.c:5625)
==19921==    by 0x692EEA: ExecResult (nodeResult.c:155)
==19921==    by 0x66A5AB: ExecProcNode (execProcnode.c:385)
==19921==    by 0x667B65: ExecutePlan (execMain.c:1549)
==19921==    by 0x665C50: standard_ExecutorRun (execMain.c:337)
==19921==  Address 0x10f54528 is 936 bytes inside a recently re-allocated block of size 8,192 alloc'd
==19921==    at 0x4C2ABAF: malloc (vg_replace_malloc.c:299)
==19921==    by 0x955C35: AllocSetAlloc (aset.c:852)
==19921==    by 0x958665: palloc (mcxt.c:825)
==19921==    by 0x4CD6A9: heap_tuple_untoast_attr (tuptoaster.c:238)
==19921==    by 0x934DDE: pg_detoast_datum (fmgr.c:2238)
==19921==    by 0x6910A86: master_drop_all_shards (master_delete_protocol.c:188)
==19921==    by 0x66DF70: ExecMakeFunctionResultNoSets (execQual.c:2019)
==19921==    by 0x66E88C: ExecEvalFunc (execQual.c:2410)
==19921==    by 0x674E23: ExecTargetList (execQual.c:5401)
==19921==    by 0x675568: ExecProject (execQual.c:5625)
==19921==    by 0x692EEA: ExecResult (nodeResult.c:155)
==19921==    by 0x66A5AB: ExecProcNode (execProcnode.c:385)
==19921== 
==19921== VALGRINDERROR-END
```

Arguably this is the fault of a weird pnstrdup definition in postgres, but we can't change that for 9.5, so we better actually fix this.

### PR DESCRIPTION
**Pull request by marcocitus**
#819 added some calls to pnstrdup, which doesn't behave as advertised in PostgreSQL 9.5 and breaks valgrind tests. Remove calls to pnstrdup from Citus code.

Fixes #836

### CODE REVIEW

File: src/backend/distributed/relay/relay_event_utility.c [hunk 1]
```diff
@@ -637,6 +637,13 @@ AppendShardIdToName(char **name, uint64 shardId)
 	uint32 longNameHash = 0;
 	int multiByteClipLength = 0;
 
+	if (nameLength >= NAMEDATALEN)
```
Comment (robin900) [inline src/backend/distributed/relay/relay_event_utility.c]: I suppose that Citus code might call this function with a *name longer than NAMEDATALEN - 1, so adding this check provides some benefit.
