### PR TITLE
Fix assertion error when rolling back to savepoint

### LINKED ISSUE #3622: crash after rollback to savepoint
On master, I did this:

```sql

create table t(a int);
select create_distributed_table('t', 'a');

begin;
insert into t values (4);
savepoint s1;
insert into t select i from generate_series(1, 10000000) i;
(wait for 2 seconds and then cancel)
rollback to savepoint s1;
insert into t select i from generate_series(1, 10000000) i;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
Time: 1199.724 ms (00:01.200)

```

backtrace was:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f30599c7801 in __GI_abort () at abort.c:79
#2  0x00005641de0258b3 in ExceptionalCondition (
    conditionName=conditionName@entry=0x7f30569aed30 "!(!placementConnection->hadDML)", 
    errorType=errorType@entry=0x7f30569a7c50 "FailedAssertion", 
    fileName=fileName@entry=0x7f30569aebc8 "connection/placement_connection.c", lineNumber=lineNumber@entry=405) at assert.c:54
#3  0x00007f3056932439 in AssignPlacementListToConnection (placementAccessList=placementAccessList@entry=0x5641e0bdf028, 
    connection=connection@entry=0x5641e0d6bc28) at connection/placement_connection.c:405
#4  0x00007f30569324f6 in StartPlacementListConnection (flags=12, placementAccessList=0x5641e0bdf028, 
    userName=userName@entry=0x5641e04e3c68 "hadi") at connection/placement_connection.c:322
#5  0x00007f30569325e4 in StartPlacementConnection (flags=<optimized out>, placement=placement@entry=0x5641e0b5d9c8, 
    userName=userName@entry=0x5641e04e3c68 "hadi") at connection/placement_connection.c:257
#6  0x00007f3056932606 in GetPlacementConnection (flags=<optimized out>, placement=placement@entry=0x5641e0b5d9c8, 
    userName=userName@entry=0x5641e04e3c68 "hadi") at connection/placement_connection.c:210
#7  0x00007f30569270a0 in CopyGetPlacementConnection (stopOnFailure=false, placement=0x5641e0b5d9c8)
    at commands/multi_copy.c:3228
#8  InitializeCopyShardState (stopOnFailure=false, shardId=<optimized out>, connectionStateHash=0x5641e07c8618, 
    shardState=0x5641e0794fd8) at commands/multi_copy.c:3138
#9  GetShardState (found=0x7ffdf14c9bf2, stopOnFailure=false, connectionStateHash=0x5641e07c8618, 
    shardStateHash=<optimized out>, shardId=<optimized out>) at commands/multi_copy.c:3096
#10 CitusSendTupleToPlacements (copyDest=0x5641e0bdecf8, slot=0x5641e052b3e0) at commands/multi_copy.c:2228
#11 CitusCopyDestReceiverReceive (slot=0x5641e052b3e0, dest=0x5641e0bdecf8) at commands/multi_copy.c:2175
#12 0x00005641ddd88248 in ExecutePlan (execute_once=<optimized out>, dest=0x5641e0bdecf8, direction=-572907836, numberTuples=0, 
    sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x5641e052a070, 
    estate=0x5641e0529e18) at execMain.c:1677
#13 standard_ExecutorRun (queryDesc=queryDesc@entry=0x5641e0388878, direction=direction@entry=ForwardScanDirection, 
    count=count@entry=0, execute_once=execute_once@entry=true) at execMain.c:364
#14 0x00007f305694e7eb in CitusExecutorRun (queryDesc=0x5641e0388878, direction=ForwardScanDirection, count=0, 
    execute_once=<optimized out>) at executor/multi_executor.c:220
#15 0x00005641ddefdd05 in PortalRunSelect (portal=portal@entry=0x5641e0440890, forward=forward@entry=true, count=0, 
    count@entry=9223372036854775807, dest=dest@entry=0x5641e0bdecf8) at pquery.c:929
#16 0x00005641ddeff496 in PortalRun (portal=portal@entry=0x5641e0440890, count=count@entry=9223372036854775807, 
    isTopLevel=isTopLevel@entry=false, run_once=run_once@entry=true, dest=dest@entry=0x5641e0bdecf8, 
    altdest=altdest@entry=0x5641e0bdecf8, completionTag=0x0) at pquery.c:770
#17 0x00007f305694f2e4 in ExecutePlanIntoDestReceiver (queryPlan=0x5641e0bdeb10, params=0x0, dest=0x5641e0bdecf8)
    at executor/multi_executor.c:687
#18 0x00007f305694b806 in ExecutePlanIntoRelation (executorState=0x5641e0513ef8, selectPlan=0x5641e0bdeb10, 
    insertTargetList=0x5641e04e21c0, targetRelationId=16814) at executor/insert_select_executor.c:633
#19 CoordinatorInsertSelectExecScanInternal (node=0x5641e0514180) at executor/insert_select_executor.c:361
#20 CoordinatorInsertSelectExecScan (node=0x5641e0514180) at executor/insert_select_executor.c:99
#21 0x00005641ddd8821a in ExecProcNode (node=0x5641e0514180) at ../../../src/include/executor/executor.h:239
#22 ExecutePlan (execute_once=<optimized out>, dest=0x5641e052e9d0, direction=NoMovementScanDirection, numberTuples=0, 
    sendTuples=<optimized out>, operation=CMD_INSERT, use_parallel_mode=<optimized out>, planstate=0x5641e0514180, 
    estate=0x5641e0513ef8) at execMain.c:1646
```

### PR DESCRIPTION
**Pull request by JelteF**
DESCRIPTION: Fixes crash when using rollback to savepoint after cancelation of DML

Fixes #3622

It was possible to get an assertion error, if a DML command was
cancelled that opened a connection and then "ROLLBACK TO SAVEPOINT" was
used to continue the transaction. The reason for this was that canceling
the transaction might leave the `claimedExclusively` flag on for (some
of) it's connections.

This caused an assertion failure because `CanUseExistingConnection`
would return false and a new connection would be opened, and then there
would be two connections doing DML for the same placement. Which is
disallowed. That this situation caused an assertion failure instead of
an error, means that without asserts this could possibly result in some
visibility bugs, similar to the ones described
https://github.com/citusdata/citus/issues/3867

The fix simply "unclaims" all connections after "ROLLBACK TO SAVEPOINT"
is done.

This specific issue also highlights some other issues:
1. Just like #3867, it shows that the `CanUseExistingConnection` should
   be improved to catch these type of errors.
2. I think we should make these DML and DDL asserts normal errors.
   This way we will not return incorrect data in case of bugs, but instead
   error out:
   https://github.com/citusdata/citus/blob/master/src/backend/distributed/connection/placement_connection.c#L418-L419
   This code is complex and it's quite possible we missed some other
   edge cases.
3. "ROLLBACK TO SAVEPOINT" in plain Postgres undos the locks that the
   rolled back statements took. We do not undo our hadDML and hadDDL
   flags, when rolling back to a savepoint. This could result in some
   queries not being allowed on Citus that would actually be fine to
   execute. Changing this would require us to keep track for each
   savepoint which placement connections had DDL/DML executed at that
   point.

### CODE REVIEW

File: src/backend/distributed/transaction/transaction_management.c [hunk 1]
```diff
@@ -484,8 +484,7 @@ ResetShardPlacementTransactionState(void)
 
 
 /*
- * Subtransaction callback - currently only used to remember whether a
- * savepoint has been rolled back, as we don't support that.
+ * Subtransaction callback used to implement distributed ROLLBACK TO SAVEPOINT.
```
Comment (JelteF) [inline src/backend/distributed/transaction/transaction_management.c:487]: (this comment seemed outdated so I changed it)

File: src/test/regress/sql/rollback_to_savepoint.sql [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+CREATE SCHEMA rollback_to_savepoint;
+SET search_path TO rollback_to_savepoint;
+
+CREATE TABLE t(a int);
+SELECT create_distributed_table('t', 'a');
+
+SET statement_timeout = '5s';
+BEGIN;
+INSERT INTO t VALUES (4);
+SAVEPOINT s1;
```
Comment (SaitTalhaNisanci) [inline src/test/regress/sql/rollback_to_savepoint.sql:14]: I think here we do insertion that would take longer than the preset statement_timeout (5 seconds) so we rollback to the savepoint s1 right? If so it can be useful to add that as a comment `-- trigger statement timeout`

Also why don't we set `statement_timeout` to something even smaller? Maybe `1s`?

File: src/backend/distributed/transaction/transaction_management.c (hunk 1 above)
Comment (SaitTalhaNisanci) [inline src/backend/distributed/transaction/transaction_management.c:487]: We can start with `CoordinatedSubTransactionCallback` to follow the convention

File: src/test/regress/sql/rollback_to_savepoint.sql (hunk 2 above)
Comment (JelteF) [reply src/test/regress/sql/rollback_to_savepoint.sql:17]: I have changed it to 2 seconds now and confirmed that also on CI this timeout triggers the bug here: https://app.circleci.com/pipelines/github/citusdata/citus/8959/workflows/ca8559d1-75fa-4bfe-8a25-5765b6d41eff/jobs/126715

NOTE: Without this PR https://github.com/citusdata/citus/pull/3869, this will actually never fail in CI, since we do not compile with asserts.

File: src/test/regress/multi_schedule [hunk 3]
```diff
@@ -90,6 +90,7 @@ test: multi_basic_queries multi_complex_expressions multi_subquery multi_subquer
 test: multi_subquery_complex_reference_clause multi_subquery_window_functions multi_view multi_sql_function multi_prepare_sql
 test: sql_procedure multi_function_in_join row_types materialized_view
 test: multi_subquery_in_where_reference_clause full_join adaptive_executor propagate_set_commands
+test: rollback_to_savepoint
```
Comment (onderkalaci) [inline src/test/regress/multi_schedule:93]: can we run it in parallel with other tests where parallelism is low?

File: src/test/regress/expected/rollback_to_savepoint.out [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+SELECT create_distributed_table('t', 'a');
+ create_distributed_table
+---------------------------------------------------------------------
+
+(1 row)
+
+-- This timeout is chosen such that the INSERT with
+-- generate_series(1, 100000000) is cancelled at the right time to trigger the
+-- bug
+SET statement_timeout = '2s';
```
Comment (onderkalaci) [inline src/test/regress/expected/rollback_to_savepoint.out:17]: Hmm, what if in 2 seconds Citus cannot start COPY command yet (e.g., still collecting the results of SELECT)? Would we still trigger the bug?

Can we maybe convert this to a failure tests where we fail once COPY starts?

File: src/backend/distributed/transaction/remote_transaction.c [hunk 5]
```diff
@@ -1119,6 +1119,7 @@ CoordinatedRemoteTransactionsSavepointRollback(SubTransactionId subId)
 		}
 
 		FinishRemoteTransactionSavepointRollback(connection, subId);
+		UnclaimConnection(connection);
```
Comment (onderkalaci) [inline src/backend/distributed/transaction/remote_transaction.c:1122]: `UnclaimConnection` means that we'd allow next commands to use this connection. So, I think it  might be useful to add a part of the PR description here as it might be confusing for users as this is an obvious point I guess:

>  We do not undo our hadDML and hadDDL
flags, when rolling back to a savepoint. This could result in some
queries not being allowed on Citus that would actually be fine to
execute. Changing this would require us to keep track for each
savepoint which placement connections had DDL/DML executed at that
point. 

Along with ` hadDML and hadDDL`, we probably should also mention that we do not `ResetShardPlacementAssociation` as well, which is also an interesting

**Comment by metdos** [comment]
This PR seems to approved, @JelteF any reason to not merge it?

**Comment by JelteF** [comment]
@metdos I still want to address Onders feeback on tests and comments.

File: src/test/regress/expected/rollback_to_savepoint.out (hunk 4 above)
Comment (JelteF) [reply src/test/regress/expected/rollback_to_savepoint.out:17]: I wasn't able to reproduce the original issue with our failure testing suite. So I'm keeping it as is.

File: src/test/regress/multi_schedule (hunk 3 above)
Comment (JelteF) [reply src/test/regress/multi_schedule:93]: For some weird reason when running the test in parallel I get distributed deadlocks, instead of timeouts: https://app.circleci.com/pipelines/github/citusdata/citus/9575/workflows/c434721e-d812-45ef-b830-1b86ee3f5d78/jobs/136125/steps

So I'll keep the test as is.

File: src/backend/distributed/transaction/remote_transaction.c (hunk 5 above)
Comment (JelteF) [reply src/backend/distributed/transaction/remote_transaction.c:1137]: Done
