### PR TITLE
EXPLAIN EXECUTE no longer segfaults

### LINKED ISSUE #886: EXPLAIN EXECUTE causes segmentation fault
To reproduce:
```
CREATE TABLE test (x int, y int);
SELECT master_create_distributed_table('test', 'x', 'hash');
SELECT master_create_worker_shards('test', 8, 2);
PREPARE foo AS INSERT INTO test VALUES (1, 2);
EXPLAIN EXECUTE foo;
```

### PR DESCRIPTION
**Pull request by lithp**
Fix #886

The way postgres' explain hook is designed means our hook is never called during
EXPLAIN EXECUTE. So, we special-case EXPLAIN EXECUTE by catching it in the utility hook.
We then replace the EXECUTE with the original query and pass it back to Postgres.

TODO:
- Does this leak memory?
- Add some regression tests!

It doesn't work with parameterized queries (even ones which would have worked if they weren't run under EXPLAIN, such as INSERT) but that's a much larger commit.

### CODE REVIEW

**Comment by jasonmp85** [comment]
Unrelated `git` commit message hygiene question…

  * Your subject should probably say what the commit does, not describe some postcondition
  * You hard-wrap the body, which I also do, but hard-wrap it at some high character limit. Isn't the convention, if you're going to hard-wrap `git` commit bodies, to wrap them at 72?

**Comment by jasonmp85** [comment]
Oh, and a third thing is that you're putting "Fix #886" in your `git` commit body rather than just in the Pull Request description, a thing I've suggested we not do, as merging this to Citus Enterprise would close issue 886 (which does not exist but if it does would be unrelated) there. In particular, we've had fixes for low-numbered Citus issues result in the closing of same-numbered Citus Enterprise bugs by GitHub's auto-close feature when we merge.

Either remove it from the `git` commit message, or fully-qualify it (`citusdata/citus#886`).

**Comment by lithp** [comment]
@jasonmp85 Good catch for your last two points, but I don't see why the subject isn't useful. If you do a blame you'll immediately see why the commit was added, the rest of the message explains the how.

**Comment by jasonmp85** [comment]
I guess? For whatever reason I'm used to seeing commit messages as subjectless imperative tense utterances. "Fix segault in EXPLAIN EXECUTE". It's like a description of the effect of applying the commit. Apparently [came from Git itself](http://stackoverflow.com/questions/3580013/should-i-use-past-or-present-tense-in-git-commit-messages)?

Don't know why, but this particular PR stood out to me. Possibly because in the list of PRs it looked like an _Issue_ subject (describes a state of the world we want to address) rather than a Pull Request (which describes the thing that happens when the pull request is merged).

**Comment by lithp** [comment]
Ahh, interesting. I misunderstood and thought you were objecting to the content and wanted something such as "Special-cases EXPLAIN EXECUTE in utility-hook" rather than describing the result, "we don't segfault".

Now that you point it out the phrasing does feel a little incongruous, I'll make it an imperative.

**Comment by jasonmp85** [comment]
Ah, the time-honored tradition of bikeshedding Git commit messages. On to more productive pastures… 👻

**Comment by marcocitus** [comment]
Code looks fine, though I'm still wondering what's wrong with our plans that made us segfault. Indeed needs regression tests.

**Comment by lithp** [comment]
@marcocitus As far as I can tell (there's more info in the ticket), explain requires some state which is set by standard_ExecutorStart however when the plan was prepared it went through the router executor which never calls back to the standard executor.

**Comment by marcocitus** [comment]
We should fix that separately I guess. In any case it's cool that we get proper distributed explain plans for execute now and avoid the crash.

**Comment by lithp** [comment]
Addressed jason's concerns and added a regression test.

**Comment by lithp** [comment]
As far as I can tell (there's more info in the ticket), explain requires
some state which is set by standard_plannerStart however when the query was
planned it went through the router planner which never calls back to the
standard planner.

24 Eki 2016 Pzt 19:36 tarihinde Marco Slot <notifications@github.com> şunu
yazdı:

File: src/test/regress/sql/multi_explain.sql [hunk 1]
```diff
@@ -108,6 +108,10 @@ SELECT true AS valid FROM explain_xml($$
 SELECT true AS valid FROM explain_json($$
 	SELECT l_quantity FROM lineitem WHERE l_orderkey = 5$$);
 
+-- ensure EXPLAIN EXECUTE doesn't crash
+PREPARE router_executor_query AS SELECT l_quantity FROM lineitem WHERE l_orderkey = 5;
+EXPLAIN EXECUTE router_executor_query;
```
Comment (marcocitus) [inline src/test/regress/sql/multi_explain.sql]: If we just add this to the bottom, does that prevent all the other changes?

Maybe also add a real-time executor query.

Comment (lithp) [inline src/test/regress/sql/multi_explain.sql]: It does but it feels a little weird that the tests are out of order just to minimize the size of the diff, really wish we had better tooling here. Moved it to the bottom and added some more kinds of queries.
