### PR TITLE
Not drop default col exprs from shard when adding local table to metadata

### LINKED ISSUE #6318: Citus local tables is broken with SET DEFAULT on foreign keys
The root of the problem is that we do not create `DEFAULT` values on the shards

```SQL

CREATE TABLE PKTABLE (tid int, id int, PRIMARY KEY (tid, id));

CREATE TABLE FKTABLE (
  tid int,
  fk_id_del_set_default int DEFAULT 0,
  FOREIGN KEY (tid, fk_id_del_set_default) REFERENCES PKTABLE ON DELETE SET DEFAULT
);

SELECT citus_add_local_table_to_metadata('PKTABLE', true);


```

Such that the shard DOES NOT have the default value:
```SQL
\d fktable
                       Table "public.fktable"
┌───────────────────────┬─────────┬───────────┬──────────┬─────────┐
│        Column         │  Type   │ Collation │ Nullable │ Default │
├───────────────────────┼─────────┼───────────┼──────────┼─────────┤
│ tid                   │ integer │           │          │         │
│ fk_id_del_set_default │ integer │           │          │ 0       │
└───────────────────────┴─────────┴───────────┴──────────┴─────────┘
Foreign-key constraints:
    "fktable_tid_fk_id_del_set_default_fkey" FOREIGN KEY (tid, fk_id_del_set_default) REFERENCES pktable(tid, id) ON DELETE SET DEFAULT

[local] onderkalaci@postgres:5432-90200=# \d fktable_102319 
                   Table "public.fktable_102319"
┌───────────────────────┬─────────┬───────────┬──────────┬─────────┐
│        Column         │  Type   │ Collation │ Nullable │ Default │
├───────────────────────┼─────────┼───────────┼──────────┼─────────┤
│ tid                   │ integer │           │          │         │
│ fk_id_del_set_default │ integer │           │          │         │
└───────────────────────┴─────────┴───────────┴──────────┴─────────┘
Foreign-key constraints:
    "fktable_tid_fk_id_del_set_default_fkey_102319" FOREIGN KEY (tid, fk_id_del_set_default) REFERENCES pktable_102318(tid, id) ON DELETE SET DEFAULT
```

As a result of this, the ON DELETE SET DEFAUL is broken:
```
INSERT INTO PKTABLE VALUES (1,1);
INSERT INTO FKTABLE VALUES
  (1, 1);
DELETE FROM PKTABLE WHERE id = 1;
SELECT * FROM FKTABLE ORDER BY id;

-- OPPPS: DEFAULT is ignored
table fktable ;
┌─────┬───────────────────────┐
│ tid │ fk_id_del_set_default │
├─────┼───────────────────────┤
│     │                       │
└─────┴───────────────────────┘
(1 row)
```

Should have been:
```
table fktable ;
┌─────┬───────────────────────┐
│ tid │ fk_id_del_set_default │
├─────┼───────────────────────┤
│     │                     0 │
└─────┴───────────────────────┘
(1 row)


```

### PR DESCRIPTION
**Pull request by onurctirtir**
As we did for GENERATED STORED columns in #4613, we should not drop column 
default expressions that are not based on sequences from shard relation since 
such expressions need to exist e.g. for foreign key actions.

For the column default expressions that are based on sequences we cannot
do much, so we need to disallow having ON DELETE SET DEFAULT actions on
such columns in a separate PR, see #6339.

Fixes #6318.

DESCRIPTION: Fixes a bug that might cause inserting incorrect DEFAULT values when applying foreign key actions

### CODE REVIEW

**Comment by onurctirtir** [comment]
Probably we should not allow such fkey actions if the column default is a sequence.
This is not only a problem for fkeys between citus local tables but also a problem for the fkeys between reference tables and/or citus local tables:

```
CREATE TABLE PKTABLE (tid int, id int, PRIMARY KEY (tid, id));

create sequence my_sequence;
CREATE TABLE FKTABLE (
  tid int,
  fk_id_del_set_default int DEFAULT nextval('my_sequence'),
  FOREIGN KEY (tid, fk_id_del_set_default) REFERENCES PKTABLE ON DELETE SET DEFAULT
);

SELECT create_reference_table('PKTABLE');
SELECT create_reference_table('FKTABLE');

INSERT INTO PKTABLE VALUES (1,1);
INSERT INTO FKTABLE VALUES
  (1, 1);
DELETE FROM PKTABLE WHERE id = 1;

SELECT * FROM FKTABLE ORDER BY tid;
┌─────┬───────────────────────┐
│ tid │ fk_id_del_set_default │
├─────┼───────────────────────┤
│     │                       │
└─────┴───────────────────────┘
(1 row)
```

File: src/backend/distributed/commands/citus_add_local_table_to_metadata.c [hunk 1]
```diff
@@ -1158,27 +1158,62 @@ GetRenameStatsCommandList(List *statsOidList, uint64 shardId)
...
+
+		Form_pg_attribute columnForm = (Form_pg_attribute) GETSTRUCT(columnTuple);
+		bool columnHasDefaultExpr = columnForm->atthasdef;
+
+		ReleaseSysCache(columnTuple);
 
-		/* column might not own a sequence */
+		if (columnHasDefaultExpr)
+		{
+			if (DefExprContainsNextVal(sourceRelationId, sourceRelDefExprArrIndex))
```
Comment (onderkalaci) [inline src/backend/distributed/commands/citus_add_local_table_to_metadata.c:1197]: are we sure that using an `index` is good enough? What happens if a column is dropped? Shouldn't it be safer if we use `attrNo` of the column instead?

Comment (onurctirtir) [reply src/backend/distributed/commands/citus_add_local_table_to_metadata.c:1197]: Unlike `TupleDesc` array, dropped attributes are deleted from `defval` and `defval` array stores default expressions in the order they appear in `TupleDesc` array.

Also, the way we access `defval` array is pretty much similar to what we do in `citus_ruleutils.c/pg_get_tableschemadef_string()`.

However, if you would feel more comfortable, then I can change the function so that it searches for the default expression based on attrNos stored in `defval[i].adnum` (AttrDefault.adnum).

Comment (onurctirtir) [reply src/backend/distributed/commands/citus_add_local_table_to_metadata.c]: done

File: src/backend/distributed/commands/citus_add_local_table_to_metadata.c [hunk 2]
```diff
@@ -1179,9 +1180,29 @@ DropDefaultExpressionsAndMoveOwnedSequenceOwnerships(Oid sourceRelationId,
 	Oid ownedSequenceId = InvalidOid;
 	forboth_ptr_oid(columnName, columnNameList, ownedSequenceId, ownedSequenceIdList)
 	{
-		DropDefaultColumnDefinition(sourceRelationId, columnName);
+		HeapTuple columnTuple = SearchSysCacheAttName(sourceRelationId, columnName);
```
Comment (onderkalaci) [inline src/backend/distributed/commands/citus_add_local_table_to_metadata.c:1183]: can we use `get_attnum (sourceRelationId, columnName)`?

Skip if return value is InvalidAttrNumber

File: src/test/regress/expected/pg15.out [hunk 3]
```diff
@@ -349,6 +349,58 @@ NOTICE:  renaming the new table to pg15.tbl2
...
+DELETE FROM PKTABLE_local WHERE id = 1 OR id = 2;
+SELECT * FROM FKTABLE_local ORDER BY id;
+ tid | id | fk_id_del_set_null | fk_id_del_set_default
+---------------------------------------------------------------------
+   1 |  1 |                    |
+   1 |  2 |                    |                     0
+(2 rows)
+
+\c - - - :master_port
+SET search_path TO pg15;
```
Comment (onderkalaci) [inline src/test/regress/expected/pg15.out:400]: can you also add a test with bigserial column? We should drop the default from the shards

File: src/backend/distributed/commands/citus_add_local_table_to_metadata.c [hunk 4]
```diff
@@ -1179,9 +1180,29 @@ DropDefaultExpressionsAndMoveOwnedSequenceOwnerships(Oid sourceRelationId,
...
+								   columnName, get_rel_name(sourceRelationId))));
+		}
+
+		Form_pg_attribute columnForm = (Form_pg_attribute) GETSTRUCT(columnTuple);
+		AttrNumber columnAttrNumber = columnForm->attnum;
+
+		ReleaseSysCache(columnTuple);
 
-		/* column might not own a sequence */
+		if (ColumnDefaultsToNextVal(sourceRelationId, columnAttrNumber))
```
Comment (onderkalaci) [inline src/backend/distributed/commands/citus_add_local_table_to_metadata.c:1196]: Needs comment, why we only drop defaults for nextval sequences? Because we want to be able to use DEFAULT values in foreign keys when as foreign keys are evaluated on the shards.

I guess it should even be fine to keep nextvals as well, but could be confusing, so I'm fine dropping.

File: src/backend/distributed/commands/sequence.c [hunk 5]
```diff
@@ -213,6 +213,46 @@ ExtractDefaultColumnsAndOwnedSequences(Oid relationId, List **columnNameList,
...
+		}
+
+		Node *defExpr = (Node *) stringToNode(defValue->adbin);
+
+		RelationClose(relation);
+
+		return contain_nextval_expression_walker(defExpr, NULL);
+	}
+
+	/* column doesn't have a DEFAULT expression */
```
Comment (onderkalaci) [inline src/backend/distributed/commands/sequence.c:250]: what if the default is a volatile function? `x int DEFAULT volatile_f()`?

I'm wondering if we should expand next_val check to volatile (or probably non-immutable) check including #6340?

Because we cannot afford to have the default on the shard and the default on the table produce any different values in any case.

what do you think?

File: src/backend/distributed/commands/sequence.c [hunk 6]
```diff
@@ -213,6 +213,46 @@ ExtractDefaultColumnsAndOwnedSequences(Oid relationId, List **columnNameList,
...
+	if (relTupConstraints == NULL)
+	{
+		/* none of the columns have a DEFAULT expression */
+		RelationClose(relation);
+		return false;
+	}
+
+	for (uint16 defExprIndex = 0; defExprIndex < relTupConstraints->num_defval;
+		 defExprIndex++)
+	{
```
Comment (onderkalaci) [inline src/backend/distributed/commands/sequence.c:236]: can we use `build_column_default ` function here? It is kind of tricky to deal with these internal data structures.

(similar thing applies to #6340 as well)

File: src/backend/distributed/commands/citus_add_local_table_to_metadata.c (hunk 2 above)
Comment (onurctirtir) [reply src/backend/distributed/commands/citus_add_local_table_to_metadata.c:1183]: Will use `get_attnum()` instead 👍 But I think we don't need to check for `InvalidAttrNumber` since `ExtractDefaultColumnsAndOwnedSequences()` guarantees not returning such an attribute.

File: src/test/regress/expected/pg15.out (hunk 3 above)
Comment (onurctirtir) [reply src/test/regress/expected/pg15.out:400]: We already have such a test in `citus_local_tables.sql`:
```sql
...
  -- print column default expressions
  -- we should only see shell relation below
  SELECT table_name, column_name, column_default
  FROM information_schema.COLUMNS
  WHERE table_name like 'citus_local_table_3%' and column_default != '' ORDER BY 1,2;
     table_name      | column_name |                  column_default
---------------------------------------------------------------------
 citus_local_table_3 | col1        | nextval('citus_local_table_3_col1_seq'::regclass)
 citus_local_table_3 | col3        | nextval('col3_seq'::regclass)
(2 rows)
...
```

File: src/backend/distributed/commands/sequence.c (hunk 6 above)
Comment (onurctirtir) [reply src/backend/distributed/commands/sequence.c:236]: Wow, I didn't know this function :) Will use this.

File: src/backend/distributed/commands/sequence.c (hunk 5 above)
Comment (onurctirtir) [reply src/backend/distributed/commands/sequence.c:250]: Hmm, I'm not sure what makes allowing such expressions on shards "more dangerous" than allowing them on plain postgres tables.

In other words, I couldn't see any reasons why to disallow them while postgres doesn't have such a limitation.

But in any case, to me this sounds like a broader discussion than this PR's context.

Comment (onurctirtir) [reply src/backend/distributed/commands/sequence.c]: > I cannot think of a case where this would cause a problem right now, but I am also not sure that this is not going to cause any issues :)

Thought a bit more about that and couldn't see anything that could break DEFAULT value assignment on shards, if I'm not missing something obvious :)

File: src/backend/distributed/commands/citus_add_local_table_to_metadata.c [hunk 7]
```diff
@@ -1179,9 +1180,24 @@ DropDefaultExpressionsAndMoveOwnedSequenceOwnerships(Oid sourceRelationId,
 	Oid ownedSequenceId = InvalidOid;
 	forboth_ptr_oid(columnName, columnNameList, ownedSequenceId, ownedSequenceIdList)
 	{
-		DropDefaultColumnDefinition(sourceRelationId, columnName);
+		/*
```
Comment (onderkalaci) [inline src/backend/distributed/commands/citus_add_local_table_to_metadata.c:1183]: Why do we drop if it defaults to nextval? Maybe add -- with better wording: `We drop nextval expressions because Citus currently evaluates nextval on the shell table, not on the shards. Hence, there is no reason for keeping nextval. Also, distributed/reference table shards do not have - so be consistsnt with those` .

**Review by onderkalaci — APPROVED** [review]

**Comment by onurctirtir** [comment]
cherry-picked to versions >= 11.0
