### PR TITLE
Fix FROM ONLY queries on partitioned tables

### LINKED ISSUE #4858: Do not disregard ONLY clause
pg_partman routinely does `SELECT max(partition_column) FROM ONLY partitioned_table` on the parent table. This command is only meaningful for table inheritance, and is expected to be a noop for partitioned tables.

```sql
EXPLAIN SELECT max(batch_hour) AS max FROM ONLY github_events ;
┌────────────────────────────────────────────────┐
│                   QUERY PLAN                   │
├────────────────────────────────────────────────┤
│ Aggregate  (cost=0.00..0.01 rows=1 width=8)    │
│   ->  Result  (cost=0.00..0.00 rows=0 width=0) │
│         One-Time Filter: false                 │
└────────────────────────────────────────────────┘
(3 rows)
```

However, Citus disregards the ONLY and it becomes a full table scan:
```sql
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                            QUERY PLAN                                                             │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Aggregate  (cost=250.00..250.01 rows=1 width=8)                                                                                   │
│   ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=100000 width=8)                                                         │
│         Task Count: 40                                                                                                            │
│         Tasks Shown: One of 40                                                                                                    │
│         ->  Task                                                                                                                  │
│               Node: host=localhost port=1302 dbname=postgres                                                                      │
│               ->  Aggregate  (cost=976.65..976.66 rows=1 width=8)                                                                 │
│                     ->  Append  (cost=0.00..885.70 rows=36380 width=8)                                                            │
│                           ->  Seq Scan on github_events_p2021_03_01_106812 github_events_1  (cost=0.00..20.70 rows=1070 width=8)  │
│                           ->  Seq Scan on github_events_p2021_03_02_106852 github_events_2  (cost=0.00..20.70 rows=1070 width=8)  │
│                           ->  Seq Scan on github_events_p2021_03_03_106892 github_events_3  (cost=0.00..20.70 rows=1070 width=8)  │
│                           ->  Seq Scan on github_events_p2021_03_04_106932 github_events_4  (cost=0.00..20.70 rows=1070 width=8)  │
│                           ->  Seq Scan on github_events_p2021_03_05_106972 github_events_5  (cost=0.00..20.70 rows=1070 width=8)  │
│                           ->  Seq Scan on github_events_p2021_03_06_107012 github_events_6  (cost=0.00..20.70 rows=1070 width=8)  │
│                           ->  Seq Scan on github_events_p2021_03_07_107052 github_events_7  (cost=0.00..20.70 rows=1070 width=8)  │
│                           ->  Seq Scan on github_events_p2021_03_08_107092 github_events_8  (cost=0.00..20.70 rows=1070 width=8)  │
│                           ->  Seq Scan on github_events_p2021_03_09_107132 github_events_9  (cost=0.00..20.70 rows=1070 width=8)  │
│                           ->  Seq Scan on github_events_p2021_03_10_107172 github_events_10  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_03_11_107212 github_events_11  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_03_12_107252 github_events_12  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_03_13_107292 github_events_13  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_03_14_107332 github_events_14  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_03_15_107372 github_events_15  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_03_16_107412 github_events_16  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_03_17_107452 github_events_17  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_03_18_107492 github_events_18  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_03_19_107532 github_events_19  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_03_20_107572 github_events_20  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_03_21_107612 github_events_21  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_03_22_107652 github_events_22  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_03_23_107692 github_events_23  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_03_24_107732 github_events_24  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_03_25_107772 github_events_25  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_03_26_107812 github_events_26  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_03_27_107852 github_events_27  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_03_28_107892 github_events_28  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_03_29_107932 github_events_29  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_03_30_107972 github_events_30  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_03_31_108012 github_events_31  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_04_01_108052 github_events_32  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_04_02_108092 github_events_33  (cost=0.00..20.70 rows=1070 width=8) │
│                           ->  Seq Scan on github_events_p2021_04_03_108172 github_events_34  (cost=0.00..20.70 rows=1070 width=8) │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
(42 rows)
```

### PR DESCRIPTION
**Pull request by marcocitus**
DESCRIPTION: Fixes FROM ONLY queries on partitioned tables

We currently do not generate "FROM ONLY" (`rte->inh` is false) when deparsing a shard name in `get_from_clause_item`. This PR adds the deparsing logic, but that also creates issues for queries that rely on RTEs from rewritten queries, whose `inh` is modified. The latter issue is fixed by storing the old `inh` value in the `values_lists` when we set RTE identity. The old inh value is stored in MultiTable nodes in the logical planner, and to the new RTEs in the physical planner.

This isn't the most efficient implementation, because `FROM ONLY partitioned_table` is effectively a noop, but delegating the noop to workers is still a lot more efficient than scanning the whole table and robust to complex queries.

Fixes #4858

### CODE REVIEW

File: src/backend/distributed/planner/distributed_planner.c [hunk 1]
```diff
@@ -457,12 +456,23 @@ GetRTEIdentity(RangeTblEntry *rte)
...
 	return linitial_int(rte->values_lists);
 }
 
 
+/*
+ * GetOldInh gets the original value of the inheritance flag set by AssignRTEIdentity.
+ * The planner resets this flag in the rewritten query, but we need it during deparsing.
+ */
+bool
+GetOldInh(RangeTblEntry *rte)
```
Comment (onderkalaci) [inline src/backend/distributed/planner/distributed_planner.c:470]: Maybe `GetOriginalInh`

File: src/backend/distributed/planner/distributed_planner.c [hunk 2]
```diff
@@ -164,30 +164,29 @@ distributed_planner(Query *parse,
...
 		 * standard_planner scribbles on it's input, but for deparsing we need the
-		 * unmodified form. Note that before copying we call
-		 * AssignRTEIdentities, which is needed because these identities need
-		 * to be present in the copied query too.
+		 * unmodified form. Before copying we call AssignRTEIdentities to be able
+		 * to match RTEs in the rewritten query tree with those in the original
+		 * tree.
 		 */
 		rteIdCounter = AssignRTEIdentities(rangeTableList, rteIdCounter);
+
```
Comment (onderkalaci) [inline src/backend/distributed/planner/distributed_planner.c:176]: might be good to add a fast-path query to the regression tests, we sometimes get into the mode of optimizing very aggressively, and could potentially ignore `inh` flag :)

File: src/test/regress/expected/multi_partitioning.out [hunk 3]
```diff
@@ -74,6 +74,12 @@ SELECT * FROM partitioning_hash_test ORDER BY 1;
   4 |     4
 (4 rows)
 
+-- should not return results when only querying parent
+SELECT * FROM ONLY partitioning_test ORDER BY 1;
```
Comment (onderkalaci) [inline src/test/regress/expected/multi_partitioning.out:78]: I didn't know that UPDATE/DELETE can also have ONLY. Might be nice to have a simple test for it.

Also, one repartitioning test might be good to have.

(I verified all works fine, this is mostly for future)

**Review by onderkalaci — APPROVED** [review]
