### PR TITLE
Reword error message for outer joins requiring repartition

### LINKED ISSUE #310: Reword "Shards of relations in outer join queries must have 1-to-1 shard partitioning" error message
Follow the steps below:

``` SQL
CREATE TABLE test_1 (key int, dummy int);
CREATE TABLE test_2 (key int, dummy int);
SELECT master_create_distributed_table('test_1', 'key', 'hash');
SELECT master_create_distributed_table('test_2', 'key', 'hash');
SELECT master_create_worker_shards('test_1', 4, 1);
SELECT master_create_worker_shards('test_2', 4, 1);

SELECT * FROM test_1 as a LEFT JOIN test_2 as b ON (a.dummy = b.dummy); 
```

I'd expect to see `cannot run outer joins with re-partition jobs`, but the actual message is: `Shards of relations in outer join queries must have 1-to-1 shard partitioning`, which is wrong since there is a 1-1 shard partitioning.

### PR DESCRIPTION
**Pull request by byucesoy**
Part of #310 

We changed error message which appears when user tries to execute outer join command and
that command requires repartitioning. Old error message mentioned about 1-to-1 shard
partitioning which may not be clear to user.

### CODE REVIEW

**Comment by metdos** [comment]
Hey @samay-sharma, this PR only changes the error message. Could you take a look and see if it's okay to merge? Thanks!

**Comment by samay-sharma** [comment]
@byucesoy : I think the change to error message on the non-partition column outer join makes sense.

To understand the first case well, does it occur when you actually join on partition column and they do not have 1:1 mapping i.e. I create one table with 16 shard and the other with 32 shards and join on the partition column, will I run into it?

If that is the case, I think the previous error message (with some rewording) conveyed that better. The current message doesn't speak about what user behavior triggered the repartitioning.

So, if my assumption on the case which triggers this is correct, can we frame it as:

DETAIL: tables involved in outer join queries must have same shard mappings (or same colocation groups, or even 1:1 shard mapping).

I think one issue with the error message was that it asked you for a 1:1 shard mapping even if you had that and joined on non-partition column, which we've fixed in this PR.

@ozgune : Was there any other case you'd like to address in this PR or any other rephrasing you had in mind?

**Comment by byucesoy** [comment]
@samay-sharma It makes sense to do not change the second error message. I changed this PR to reflect that. Could you have another look?

File: src/backend/distributed/planner/multi_join_order.c [hunk 1]
```diff
@@ -244,9 +244,10 @@ FixedJoinOrderList(FromExpr *fromExpr, List *tableEntryList)
 		{
 			/* re-partitioning for OUTER joins is not implemented */
 			ereport(ERROR, (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
-							errmsg("cannot perform distributed planning on this query"),
-							errdetail("Shards of relations in outer join queries must "
-									  "have 1-to-1 shard partitioning")));
+							errmsg("cannot run outer join query if join is not on "
+								   "partition column"),
```
Comment (samay-sharma) [inline src/backend/distributed/planner/multi_join_order.c]: "on partition column" -> "on the partition column"?

**Comment by samay-sharma** [comment]
@byucesoy : I think this makes sense, 1 last question.

What are the criteria which can cause you to not have a 1:1 shard mapping? Can we verbalize that?

eg. Can we say, "tables in outer join queries must have same shard count, partition method and partition column type".

As next steps:

(a) Address small feedback on new error message.

(b) On the old error message, can we change it to:
ERROR: cannot run outer join query
DETAIL: tables in outer join queries must have same shard count, partition method and partition column type.

The DETAIL message in (b) needs a correction check.

One case I can think of where (b) might not be accurate is reference tables. Do we have a separate error message for that or do we show the 1:1 mapping error message there as well? If we do, I think we should open a separate issue for that unless that is very easily addressable in this PR.

**Comment by byucesoy** [comment]
@samay-sharma I addressed the small feedback you mentioned.

About verbalization of problem, I think most well defined explanation is what Marco write to the [issue](https://github.com/citusdata/citus/issues/310#issuecomment-182144523)

So we accept some queries even if shard counts are not same and we allow joining tables with different partition methods(For example `select hast_table left join reference_table on hash_table.partition_column = reference_table.partition_column` is ok). I do no know how to capture all these cases in a short error message. I think 1:1 shard mapping somehow implies these cases but it needs thinking.

**Comment by ozgune** [comment]
@byucesoy -- I have a few clarification notes and questions.

(1) To clarify, I think @samay-sharma was asking the following rewording in multi_join_order.c's line 237 made sense.

ERROR: cannot run outer join query
DETAIL: tables in outer join queries must have same shard count, partition method, and partition column type.

In the absence of that, I remember he was contemplating about something friendlier than the current message.

(2) Minor. Do DETAIL messages end with periods or not?

(3) Do we error out in the example query you highlighted?

<pre>
select hast_table left join reference_table on hash_table.partition_column = reference_table.partition_column
</pre>

If we do, I don't think our current error message (1:1 shard mapping) communicates the issue to the user. With 1:1 shard mapping, I'm thinking primarily of colocated tables. What do you think?

(4) @byucesoy, could you give 3-4 example queries/scenarios where we run into this error message? That could help us better articulate this error message.

(a) Hash distributed table left join with a reference table
(b) ? Others

**Comment by byucesoy** [comment]
Hi @ozgune, @samay-sharma 

(1) I think following error messsage for multi_join_order.c's line 237 does not capture the actual problem.

```
ERROR: cannot run outer join query
DETAIL: tables in outer join queries must have same shard count, partition method, and partition column type.
```

Because we allow some outer queries even if shard count or partition method are not same. For example we do not error out the example I gave. I runs without any problem.

```sql
CREATE TABLE hash_table(partition_column int);
CREATE TABLE reference_table(random_column int);

SELECT create_distributed_table('hash_table', 'partition_column');
SELECT create_reference_table('reference_table');

SELECT * FROM hash_table LEFT JOIN reference_table ON hash_table.partition_column = reference_table.random_column;
```


(2) DETAIL and HINT messages end with period, ERROR messages do not end with period. Also DETAIL and HINT messages start with uppercase character but ERROR messages start with lowercase character.

(3) No we don't error out when hash distributed table left join with a reference table. Outer join queries are allowed even if tables are not colocated, have different shard count, have different partition type etc.

(4) Some queries we do not error out;

hash_table left join reference_table

Some queries we error out;

hash_table right join reference_table
hash_table full join reference_table

We also error out with this append table example;

```sql
CREATE TABLE append1(c int);
CREATE TABLE append2(c int);

SELECT create_distributed_table('append1', 'c', 'append');
SELECT create_distributed_table('append2', 'c', 'append');

COPY append1 FROM STDIN;
1
\.

COPY append1 FROM STDIN;
1
\.

COPY append1 FROM STDIN;
1
\.

COPY append1 FROM STDIN;
2
\.

-- all fails
SELECT * FROM append1 LEFT JOIN append2 ON append1.c = append2.c;
SELECT * FROM append1 RIGHT JOIN append2 ON append1.c = append2.c;
SELECT * FROM append1 FULL JOIN append2 ON append1.c = append2.c;
```

What we mean by 1:1 matching
```c
/*
 * ShardIntervalsMatch returns true if provided shard interval has one-to-one
 * matching. Shards intervals must be not empty, and their intervals musht be in
 * ascending order of range min values. Shard interval ranges said to be matched
 * only if (1) they have same number of shards, (2) a shard interval on the left
 * side overlaps with corresponding shard on the right side, (3) a shard interval
 * on the right side does not overlap with any other shard. The function does not
 * compare a left shard with every right shard. It compares the left shard with the
 * previous and next shards of the corresponding shard to check they to not overlap
 * for optimization purposes.
 */
```

Note that this check only happens if OUTER JOIN is a LOCAL_PARTITION_JOIN. Reference table joins are broadcast join therefore we do not perform this check for them, as a result OUTER JOINs containing reference table do not need to have same number of shards.

**Comment by metdos** [comment]
Hey @ozgune, do you have any further comments on this. @byucesoy is blocked on the your approval.

**Comment by ozgune** [comment]
@byucesoy (and @metdos) -- Got it, this is helpful. I had four quick comments.

(a) Let's assume that the user's running a real-time query that touches two colocated tables. Do we support left, right, and full outer joins in that case?

(b) Your examples in (4) are helpful. I think we can safely overlook joins between two append distributed tables for now.

(c) To display a correct error message with users' perspective in mind, do we then need to check if the query has a left, right, or full outer join query? Or is there a simpler approach where we say for example, "Citus supports outer joins between two colocated tables and a left join between a large and reference table" (or something to that effect)?

(d) I think the current pull request is an important over what we previous had. **If** you agree, could you merge this pull request? **Could you then copy/paste this conversation into #310?**

Let's leave #310 open for now with these notes so that we can regroup when @samay-sharma's back.
