### PR TITLE
Fix relation access tracking for local only transactions

### LINKED ISSUE #6079: Failure to reset RelationAccessHash at the end of a transaction
In a single coordinator environment

CREATE TABLE test (id int, nonid int);
SELECT create_distributed_table('test', 'id', colocate_with := 'none');
INSERT INTO test  select  generate_series(6, 10000, 1), 0;

CREATE or REPLACE function foo()
returns setof test
AS $$
BEGIN
RETURN query select * from test order by 1 limit 10;
end;
$$ language plpgsql;

CREATE TABLE test2 (id int, nonid int);

-- Leak the relation-access in this session
select foo();

-- As we didn't reset the flag at the end of above transaction, this should fail
BEGIN;
SET LOCAL citus.multi_shard_modify_mode TO sequential;
SELECT create_distributed_table('test2', 'id', colocate_with := 'none');
END;

This fails even though we haven't done any parallel query in the explicit BEGIN-END

 ERROR:  cannot distribute "test2" in sequential mode because a parallel query was executed in this transaction
HINT:  If you have manually set citus.multi_shard_modify_mode to 'sequential', try with 'parallel' option.

### PR DESCRIPTION
**Pull request by onderkalaci**
Fixes #6079 

It seems like we associated `RelationAccessHash` heavily with remote placement accesses. My guess is that this decision was given prior to having local execution.

[Detach relation access tracking from connection management](https://github.com/citusdata/citus/commit/359a916aed03c08b88fdc46d95858f079a083aaa)

[Call relation access hash clean-up irrespective of remote transaction](https://github.com/citusdata/citus/commit/e6c62be2e3c5e2e854d22742af65ea5623238b35)

### CODE REVIEW

File: src/backend/distributed/transaction/relation_access_tracking.c [hunk 1]
```diff
@@ -120,6 +122,18 @@ static bool HoldsConflictingLockWithReferencedRelations(Oid relationId,
...
 
 
+/*
+ * InitRelationAccessHash performs initialization of the
+ * infrastructure in this file at backend start.
+ */
+void
+InitRelationAccessHash(void)
+{
+	/* (relationId) = [relationAccessMode] hash */
```
Comment (tejeswarm) [inline src/backend/distributed/transaction/relation_access_tracking.c:132]: Is this some code commented out?

File: src/test/regress/sql/single_node.sql [hunk 2]
```diff
@@ -252,6 +252,41 @@ INSERT INTO upsert_test (part_key, other_col) VALUES (1, 1) ON CONFLICT ON CONST
...
+RETURN query select * from relation_tracking_table_1 order by 1 limit 10;
+end;
+$$ language plpgsql;
+
+CREATE TABLE relation_tracking_table_2 (id int, nonid int);
+
+-- use the relation-access in this session
+select foo();
+
+-- As we didn't reset the flag at the end of above transaction, this should fail
```
Comment (tejeswarm) [inline src/test/regress/sql/single_node.sql:272]: Now that we fixed the code, the comment should reflect that

File: src/backend/distributed/transaction/relation_access_tracking.c [hunk 3]
```diff
@@ -120,6 +122,18 @@ static bool HoldsConflictingLockWithReferencedRelations(Oid relationId,
...
+	AllocateRelationAccessHash();
```
Comment (tejeswarm) [inline src/backend/distributed/transaction/relation_access_tracking.c:133]: May be rename  AllocateRelationAccessHash() to InitRelationAccessHash() and remove the wrapper?

**Review by tejeswarm — APPROVED** [review]
Left some comments

File: src/backend/distributed/transaction/relation_access_tracking.c (hunk 3 above)
Comment (onderkalaci) [reply src/backend/distributed/transaction/relation_access_tracking.c:133]: We have bunch of `InitXXX` APIs, so I have a slight preference to keep `InitRelationAccessHash` just for readability of this part: https://github.com/citusdata/citus/blob/0f50bef696e8925374a7423f89b7513bf6f31d44/src/backend/distributed/shared_library_init.c#L389-L395

Comment (tejeswarm) [reply src/backend/distributed/transaction/relation_access_tracking.c:133]: I agree, it's better to keep it uniform. My comment was more on the lines, remove the function `AllocateRelationAccessHash`() and put the code directly in `InitRelationAccessHash` , since this is not a hot path, I guess that's fine.
