### PR TITLE
Fix deadlock adding named constraint with long partition name (#7799)

### LINKED ISSUE #7799: Deadlock when specifying constraint name for a parent table with a partition with a long name
Steps to reproduce:

```SQL
-- create partitioned table
CREATE TABLE distributed_partitioned_table (
    id serial NOT NULL,
    partition_col int NOT NULL,
    PRIMARY KEY (id, partition_col)
) PARTITION BY RANGE (partition_col);

-- add normal length name partition
CREATE TABLE distributed_partitioned_table_p1 PARTITION OF distributed_partitioned_table 
FOR VALUES FROM (1) TO (100);

-- add long name partition
CREATE TABLE distributed_partitioned_table_p2_longlonglonglonglonglonglong_name PARTITION OF distributed_partitioned_table 
FOR VALUES FROM (100) TO (200);

-- distribute
SELECT create_distributed_table('distributed_partitioned_table', 'id');

-- Add an exclusion constraint with a name to the distributed partitioned table
-- this seems to deadlock sometimes for the long name partition
SET client_min_messages TO DEBUG1;
ALTER TABLE distributed_partitioned_table ADD CONSTRAINT dist_unique_named UNIQUE(id, partition_col);

ERROR:  canceling the transaction since it was involved in a distributed deadlock
```

### PR DESCRIPTION
**Pull request by codeforall**
DESCRIPTION: Fix deadlock when adding named constraint on partitioned table with long partition name.

Previously, SwitchToSequentialAndLocalExecutionIfConstraintNameTooLong was only called when the user did NOT provide an explicit constraint name. When a name was provided (e.g., ALTER TABLE ... ADD CONSTRAINT myname UNIQUE(...)), the code fell through to the standard parallel DDL path without checking if the auto-generated constraint names on partition shards would exceed NAMEDATALEN, causing potential self-deadlocks.

This commit adds calls to SwitchToSequentialAndLocalExecutionIfConstraintNameTooLong for both named foreign key constraints and named non-FK constraints (PRIMARY KEY, UNIQUE, EXCLUDE, CHECK) in PreprocessAlterTableStmt, so that the long partition shard name check is performed regardless of whether the user specified a constraint name.

Also adds regression tests covering named PRIMARY KEY, UNIQUE, and CHECK constraints on partitioned tables with long partition names, including the error case when a parallel query has already been executed in the same transaction.

DESCRIPTION: PR description that will go into the change log, up to 78 characters

### CODE REVIEW

File: src/backend/distributed/commands/table.c [hunk 1]
```diff
@@ -1000,6 +1000,24 @@ SwitchToSequentialAndLocalExecutionIfConstraintNameTooLong(Oid relationId,
...
+	 * the exact same constraint name from the parent to all partition children
+	 * (see ATAddCheckConstraint and addFkConstraint in tablecmds.c). Since
+	 * user-provided identifiers are already bounded by NAMEDATALEN at parse
+	 * time, the inherited name can never be too long on partition shards.
+	 *
+	 * Only index-backed constraints (PRIMARY KEY, UNIQUE, EXCLUDE) need this
+	 * check because PostgreSQL auto-generates new names for partition child
+	 * indexes based on the partition table name (see generateClonedIndexStmt
+	 * in parse_utilcmd.c which sets idxname = NULL), and those generated
+	 * names can exceed NAMEDATALEN when the partition name is long.
```
Comment (colm-mchugh) [inline src/backend/distributed/commands/table.c:1018]: nit: the check also (correctly) applies to handling *unnamed* non-index constraints (e.g., unnamed CHECK) whose `conname` was assigned by `PrepareAlterTableStmtForConstraint()` earlier, right ? Those generated names are also bounded by NAMEDATALEN, so this early return is correct for them too. How about extending the comment to describe that also, with something like: 
 
```
 * This also correctly handles unnamed non-index constraints whose 
 * conname was assigned by PrepareAlterTableStmtForConstraint(), since
 * those generated names are also bounded by NAMEDATALEN.
```

File: src/test/regress/sql/multi_alter_table_add_constraints.sql [hunk 2]
```diff
@@ -582,6 +582,82 @@ DROP SCHEMA sc1 CASCADE;
...
+BEGIN;
+    SET LOCAL citus.multi_shard_modify_mode TO 'sequential';
+    SELECT count(*) FROM dist_partitioned_table;
+    ALTER TABLE dist_partitioned_table ADD CONSTRAINT my_pk PRIMARY KEY(partition_col);
+ROLLBACK;
+
+SET client_min_messages TO ERROR;
+DROP SCHEMA test_named_constraint_long_partition CASCADE;
+SET search_path TO 'public';
+
```
Comment (colm-mchugh) [inline src/test/regress/sql/multi_alter_table_add_constraints.sql:714]: How about test cases for named `EXCLUDE` and `FOREIGN KEY` constraints ? They should be covered by the fix, but for completeness. Consider as a nice-to-have, ok to skip if lots of setup is required.

**Review by colm-mchugh — APPROVED** [review]
Lgtm, couple of take-or-leave suggestions, I'm ok to merge either way.

File: src/test/regress/sql/multi_alter_table_add_constraints.sql (hunk 2 above)
Comment (codeforall) [reply src/test/regress/sql/multi_alter_table_add_constraints.sql:714]: Thanks for the suggestion! I've added test cases for both

File: src/backend/distributed/commands/table.c (hunk 1 above)
Comment (codeforall) [reply src/backend/distributed/commands/table.c:1018]: Good catch! I've extended the comment to document this.
