### PR TITLE
Fix relkind checks in planner for relkinds other than RELKIND_RELATION 

### LINKED ISSUE #4287: Union with Distributed Partitioned Table Fails
```
CREATE TABLE dist(a int) PARTITION BY RANGE(a);
SELECT create_distributed_table('dist', 'a');

SELECT * FROM dist UNION SELECT 1;
```
```
ERROR:  could not run distributed query with UNION, INTERSECT, or EXCEPT
HINT:  Consider using an equality filter on the distributed table's partition column.
```

### PR DESCRIPTION
**Pull request by onurctirtir**
(Not writing description as this bug was introduced in 9.5 3a73fba)

-----

We were qualifying relations with relkind != RELKIND_RELATION as
non-relations due to the strict checks around RangeTblEntry->relkind
in planner.

Fixes #4287 

-----

I had first run new tests on master and added them in c62d891.
Then after each fix commit, updated the tests outputs to see what previous commit fixed/changed.
(see commits with message=`update test results`)

I will follow squash strategy for merging the pr.

----

TODO:

- [x] Fix weird flakyness in explain output (see https://github.com/citusdata/citus/pull/4295)

### CODE REVIEW

File: src/backend/distributed/planner/distributed_planner.c [hunk 1]
```diff
@@ -2296,12 +2296,29 @@ GetRTEListProperties(List *rangeTableList)
...
 	foreach_ptr(rangeTableEntry, rangeTableList)
 	{
-		if (!(rangeTableEntry->rtekind == RTE_RELATION &&
-			  rangeTableEntry->relkind == RELKIND_RELATION))
+		if (rangeTableEntry->rtekind != RTE_RELATION)
 		{
 			continue;
 		}
 
+		if (rangeTableEntry->relkind == RELKIND_VIEW)
```
Comment (onderkalaci) [inline src/backend/distributed/planner/distributed_planner.c:2304]: should we make it `if/elseif/elseif`?

File: src/test/regress/expected/mixed_relkind_tests.out [hunk 2]
```diff
@@ -0,0 +1,932 @@
...
+-- router query
+SELECT COUNT(*) FROM partitioned_distributed_table p1 JOIN partitioned_distributed_table p2 USING (a) WHERE a = 1;
+ count
+---------------------------------------------------------------------
+     4
+(1 row)
+
+-- repartition query
+SELECT COUNT(*) FROM partitioned_distributed_table p1 JOIN partitioned_distributed_table p2 USING (b) WHERE b = 1;
+ERROR:  the query contains a join that requires repartitioning
```
Comment (onderkalaci) [inline src/test/regress/expected/mixed_relkind_tests.out:492]: should we enable `Set citus.enable_repartition_joins to on` for completeness?

**Comment by onurctirtir** [comment]
>TODO:
 Fix weird flakyness in explain output.

It is not flaky, but output in pg13 is not compatible with pg11&12, looking into that

File: src/test/regress/expected/mixed_relkind_tests.out [hunk 3]
```diff
@@ -0,0 +1,932 @@
...
+BEGIN;
+  ALTER TABLE foreign_distributed_table DROP COLUMN b CASCADE;
+  SELECT * FROM foreign_distributed_table;
+ a
+---------------------------------------------------------------------
+(0 rows)
+
+COMMIT;
+-- cleanup at exit
+DROP SCHEMA mixed_relkind_tests CASCADE;
```
Comment (onderkalaci) [inline src/test/regress/expected/mixed_relkind_tests.out:917]: when there are so many objects, they sometimes lead to flaky tests at DROP. Maybe set the log level to error?

File: src/test/regress/expected/mixed_relkind_tests.out [hunk 4]
```diff
@@ -0,0 +1,932 @@
...
+  15
+(1 row)
+
+SELECT array_agg(a ORDER BY 1,2) FROM partitioned_distributed_table;
+   array_agg
+---------------------------------------------------------------------
+ {1,5,0,3,4,2}
+(1 row)
+
+SELECT array_agg(a ORDER BY 1,2) FROM unlogged_distributed_table;
```
Comment (onderkalaci) [inline src/test/regress/expected/mixed_relkind_tests.out:813]: hmm, tests with `array_agg ORDER BY` could be flaky. Can we have another aggregate, such as
```
 select regr_syy(a,b) from partitioned_distributed_table;
```

The goal is to make sure that we can handle partial agg. without any issues

File: src/backend/distributed/planner/distributed_planner.c [hunk 5]
```diff
@@ -2296,9 +2296,24 @@ GetRTEListProperties(List *rangeTableList)
 	RangeTblEntry *rangeTableEntry = NULL;
 	foreach_ptr(rangeTableEntry, rangeTableList)
 	{
-		if (!(rangeTableEntry->rtekind == RTE_RELATION &&
-			  rangeTableEntry->relkind == RELKIND_RELATION))
+		if (rangeTableEntry->rtekind != RTE_RELATION)
```
Comment (marcocitus) [inline src/backend/distributed/planner/distributed_planner.c:2299]: it kind of seems like we'll have these bug whenever we check rtekind.

Is there a well-named function that we can come up with?

Comment (onurctirtir) [reply src/backend/distributed/planner/distributed_planner.c:2299]: Actually, we can improve `RegularTable` function and use it along the planner.

As we discussed with @onderkalaci, I was thinking of opening an issue for that as 10.0 item.
What do you think @marcocitus ?

Comment (onderkalaci) [reply src/backend/distributed/planner/distributed_planner.c:2299]: @onurctirtir actually suggested having a  function for this as well, but we couldn't find a good name now and didn't want to delay the merge for it now as we considered this like a backport.

Onur will consider having a unified name for this purpose. We currently have `RegularTable()` function, which is also not great

Comment (onurctirtir) [reply src/backend/distributed/planner/distributed_planner.c:2299]: maybe we can rename it to `RelkindIsTable` and do the following:

```c
// was RegularTable
bool
RelkindIsTable(Oid relationId)
{
	char relationKind = get_rel_relkind(relationId);
        switch(relationKind)
        {
                case RELKIND_RELATION:
                case RELKIND_FOREIGN_TABLE:
                case RELKIND_PARTITIONED_TABLE:
                        return true;
                default:
                        return false;
        }
}

File: src/test/regress/sql/mixed_relkind_tests.sql [hunk 6]
```diff
@@ -0,0 +1,260 @@
...
+SELECT * from foreign_distributed_table UNION SELECT 1,1 ORDER BY 1,2;
+SELECT 1 UNION SELECT * FROM citus_local_table ORDER BY 1;
+
+SELECT * FROM view_on_part_dist UNION SELECT 1,1 ORDER BY 1,2;
+SELECT * FROM mat_view_on_part_dist UNION SELECT 1,1 ORDER BY 1,2;
+SELECT * FROM view_on_citus_local UNION SELECT 1 ORDER BY 1;
+SELECT * FROM view_on_dist UNION SELECT 1 ORDER BY 1;
+SELECT * FROM mat_view_on_dist UNION SELECT 1 ORDER BY 1;
+
+-- cannot push down the subquery, should evaluate subquery by creating a subplan
```
Comment (onderkalaci) [inline src/test/regress/sql/mixed_relkind_tests.sql:80]: move DEBUG1 here

File: src/test/regress/sql/mixed_relkind_tests.sql [hunk 7]
```diff
@@ -0,0 +1,260 @@
...
+EXPLAIN (COSTS OFF)
+INSERT INTO partitioned_distributed_table SELECT a + 1 FROM unlogged_distributed_table;
+$Q$);
+
+-- some aggregate queries
+SELECT sum(a) FROM partitioned_distributed_table;
+SELECT array_agg(a ORDER BY 1,2) FROM partitioned_distributed_table;
+SELECT array_agg(a ORDER BY 1,2) FROM unlogged_distributed_table;
+
+-- pushdown WINDOW
```
Comment (onderkalaci) [inline src/test/regress/sql/mixed_relkind_tests.sql:231]: coordinar_plan is OK for window functions

File: src/backend/distributed/planner/distributed_planner.c (hunk 5 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/distributed_planner.c:2299]: I'll be changing this function to also record MAT_VIEWs on #4292. Can we skip changing it now?

File: src/test/regress/expected/mixed_relkind_tests.out [hunk 8]
```diff
@@ -0,0 +1,704 @@
...
+
+-- pull to coordinator WINDOW
+SELECT public.coordinator_plan($Q$
+EXPLAIN (COSTS OFF)
+SELECT a, COUNT(*) OVER (PARTITION BY a+1) FROM partitioned_distributed_table ORDER BY 1,2;
+$Q$);
+                  coordinator_plan
+---------------------------------------------------------------------
+ Sort
+   Sort Key: remote_scan.a, (count(*) OVER (?))
```
Comment (onderkalaci) [inline src/test/regress/expected/mixed_relkind_tests.out:647]: `(count(*) OVER (?))` looks weird, but local table generates the same output.

**Review by onderkalaci — APPROVED** [review]
This looks good to me, thanks for adding test coverage for partitioned, foreign and  unlogged tables.

Let's wait @marcocitus before merging in as he commented and may have further  comments

**Comment by onderkalaci** [comment]
@onurctirtir PG 11 tests are failing,  can you check that? In PG 11, we cannot  do colocated joins via CTEs, maybe convert those to subqueries?

File: src/backend/distributed/planner/distributed_planner.c [hunk 9]
```diff
@@ -2296,9 +2296,24 @@ GetRTEListProperties(List *rangeTableList)
...
+			 * already in rangeTableList.
+			 */
+			continue;
+		}
+		else if (rangeTableEntry->relkind == RELKIND_MATVIEW)
+		{
+			/*
+			 * Skip over materialized views, here we should not consider
+			 * materialized views as local tables.
+			 */
```
Comment (marcocitus) [inline src/backend/distributed/planner/distributed_planner.c:2316]: This was bugging me a bit, but https://github.com/citusdata/citus/pull/4292#discussion_r517945632 clarified and I assume we'll add a comment in #4292

**Review by marcocitus — APPROVED** [review]
