### PR TITLE
Use long-lasting mem cxt during columnar index scan & optimize correlated ones

### LINKED ISSUE #5078: Crash or incorrect result is possible with hash indexes on a columnar table
Maybe not related with hash indexes but with `text` column, not sure yet.
Sharing two cases for me to fix within 10.2:

```sql
create table col_table(a int, b text) USING columnar;
insert into col_table select i, i::text from generate_series(1, 10) i;

create index on col_table using hash (b);

-- force index scan
set columnar.enable_custom_scan to off;
set seq_page_cost TO 10000000;

-- incorrect result
select b from col_table where b = '5';
┌───┐
│ b │
├───┤
└───┘
(0 rows)
```

```sql
create table col_table(a int, b text) USING columnar;
insert into col_table select i, i::text from generate_series(1, 10) i;

create index on col_table using hash (a);

-- force index scan
set columnar.enable_custom_scan to off;
set seq_page_cost TO 10000000;

-- returns weird things
select b from col_table where a = '5';
```

### LINKED ISSUE #5118: Columnar indexes read random data for numeric columns
When querying a columnar table with `numeric` values cause random data to be read when the read hits the table_am. When the query doesn't need to read the tuple back from the table (eg. index only scan) the value's are read correctly.

I guess the bug is in `ColumnarReadRowByRowNumber`, or how the values are read into the tuple slot.

Reproduction:

``` sql
[local] nilsdijk@postgres:9700-69694=# CREATE TABLE foo USING columnar AS SELECT (random() * 10000)::numeric AS x, 0 AS y FROM generate_series(1, 1000000);
SELECT 1000000
Time: 1515.162 ms (00:01.515)

[local] nilsdijk@postgres:9700-69694=# CREATE INDEX foo_idx_x ON foo(x);
NOTICE:  falling back to serial index build since parallel scan on columnar tables is not supported
CREATE INDEX
Time: 1581.795 ms (00:01.582)

[local] nilsdijk@postgres:9700-69694=# ANALYZE foo;
ANALYZE
Time: 170.361 ms

[local] nilsdijk@postgres:9700-69694=# EXPLAIN SELECT * FROM foo WHERE x < .1 LIMIT 10;
┌──────────────────────────────────────────────────────────────────────────────┐
│                                  QUERY PLAN                                  │
├──────────────────────────────────────────────────────────────────────────────┤
│ Limit  (cost=0.42..44.60 rows=10 width=15)                                   │
│   ->  Index Scan using foo_idx_x on foo  (cost=0.42..44.60 rows=10 width=15) │
│         Index Cond: (x < 0.1)                                                │
└──────────────────────────────────────────────────────────────────────────────┘
(3 rows)

Time: 4.663 ms

[local] nilsdijk@postgres:9700-69694=# SELECT * FROM foo WHERE x < .1 LIMIT 10;
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│
├─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ -P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P63
│ -P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P63
│ -P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P63
│ -P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P63
│ -P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P63
│ -P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P63
│ -P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P63
│ -P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P63
│ -P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P63
│ -P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P639P63
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
(10 rows)
Time: 31.641 ms

[local] nilsdijk@postgres:9700-69694=# SELECT x FROM foo WHERE x < .1 LIMIT 10;
┌─────────────────────┐
│          x          │
├─────────────────────┤
│ 0.00100950959591728 │
│   0.018306735967144 │
│  0.0250504939813823 │
│  0.0353427433097409 │
│  0.0417152509157859 │
│  0.0544287814463473 │
│  0.0633858910958907 │
│  0.0702512300421176 │
│  0.0767060532425035 │
│  0.0825564931261624 │
└─────────────────────┘
(10 rows)

Time: 25.313 ms
```

### PR DESCRIPTION
**Pull request by onurctirtir**
Fixes #5078.
Fixes #5118.

With this commit, we start caching both:
* the read state for the last read stripe, and
* the read state for the last de-serialized chunk group

for columnar table index reads.

Note that this is only useful when the index is highly correlated with the columnar table itself.
In future, maybe we can improve this by caching `K` stripes, but we are not doing that now.

To store cached stripe & chunk group read states, we also start using a long lasting memory context.
This change itself fixes #5078.

Also, we stop freeing stripe buffers after de-compressing / de-serializing them, since it's possible that we might need to read same chunk group of the same stripe, as in below:

_**read chunk group 1 of stripe 5**
read chunk group 2 of stripe 5
**read chunk group 1 of stripe 5 again (note that chunk group 1 is not cached anymore)**_

### CODE REVIEW

File: src/backend/columnar/columnar_reader.c [hunk 1]
```diff
@@ -84,10 +84,25 @@ struct ColumnarReadState
...
+	 * cache the last chunk group here since cachedStripeReadState already
+	 * stores chunkGroupReadState and chunkGroupIndex.
+	 */
+	StripeReadState *cachedStripeReadState;
+
+	/* StripeMetadata of the stripe which we cached the read state of */
+	StripeMetadata *cachedStripeMetadata;
+
+	/* MemoryContext that needs to be used during random read operations */
+	MemoryContext stripeReadContext;
```
Comment (jeff-davis) [inline src/backend/columnar/columnar_reader.c:100]: This feels redundant. Isn't stripeReadContext the same as cachedStripeReadState->stripeReadContext? And isn't cachedStripeMetadata the same as the cachedStripeReadState->currentStripe'th element of cachedStripeReadState->stripeList?

I was imagining that this change would be mostly just a way to skip ahead in a ColumnarReadState if necessary. Is there a reason that won't work?

Comment (onurctirtir) [reply src/backend/columnar/columnar_reader.c:100]: > This feels redundant. Isn't stripeReadContext the same as cachedStripeReadState->stripeReadContext? And isn't cachedStripeMetadata the same as the cachedStripeReadState->currentStripe'th element of cachedStripeReadState->stripeList?

Indeed both is true.

> I was imagining that this change would be mostly just a way to skip ahead in a ColumnarReadState if necessary. Is there a reason that won't work?

I think this should work, let me work little more on those changes.

File: src/backend/columnar/columnar_reader.c [hunk 2]
```diff
@@ -269,39 +276,106 @@ ColumnarReadRowByRowNumber(Relation relation, uint64 rowNumber,
...
+		 * XXX: Since stripes in stripeList are ordered by their first row
+		 * numbers, we can't just assume that stripe with "id" will the "id"th
+		 * item of stripe list.
+		 * For this reason, we should either store StripeMetadata instead of
+		 * currentStripe, or we need to linearly search our stripe to set
+		 * currentStripe, as in below.
+		 */
+		readState->currentStripe = StripeListGetStripeIndex(readState->stripeList,
+															stripeMetadata);
+		Assert(readState->currentStripe >= 0);
```
Comment (onurctirtir) [inline src/backend/columnar/columnar_reader.c:306]: Regarding https://github.com/citusdata/citus/pull/5058#discussion_r655918433, I made some changes in d3e8e18890562cc9e0490f391620abcf20e82a5d. 

On the other hand, above part seems a bit annoying to me.
Now we don't store a redundant `StripeMetadata` object and directly make use of `readState->stripeList[readState->currentStripe]`. 
For this reason, we need to linearly search `stripeList` to correctly set `currentStripe`.

Does that look good ?
Or, should we have another field in `ColumnarReadState` to store `StripeMetadata` itself additionally ?
The second approach would make `ColumnarReadState` slightly confusing, but current approach is not very nice from the performance aspect.

What do you think @jeff-davis ?

File: src/backend/columnar/columnar_reader.c [hunk 3]
```diff
@@ -297,78 +276,153 @@ ColumnarReadRowByRowNumber(Relation relation, ColumnarRandomReadState *randomRea
...
+		 * XXX: Since stripes in stripeList are ordered by their first row
+		 * numbers, we can't just assume that stripe with "id" will be the
+		 * "id"th item of given stripe list.
+		 * For this reason, we should either store StripeMetadata instead of
+		 * currentStripe, or we need to linearly search our stripe in stripe
+		 * list to set currentStripe, as in below.
+		 */
+		readState->currentStripe = StripeListGetStripeIndex(readState->stripeList,
+															stripeMetadata);
+		Assert(readState->currentStripe >= 0);
```
Comment (onurctirtir) [inline src/backend/columnar/columnar_reader.c:306]: Regarding https://github.com/citusdata/citus/pull/5058#discussion_r655918433, I made some changes in 01595a14515ecab4337fa0724f8767ef06fb8dc7. 

On the other hand, above part seems a bit annoying to me.
Now we don't store a redundant `StripeMetadata` object and directly make use of `readState->stripeList[readState->currentStripe]`. 
For this reason, we need to linearly search `stripeList` to correctly set `currentStripe`.

Does that look good ?
Or, should we have another field in `ColumnarReadState` to store `StripeMetadata` itself additionally ?
The second approach would make `ColumnarReadState` slightly confusing, but current approach is not very nice from the performance aspect.

What do you think @jeff-davis ?

Comment (jeff-davis) [reply src/backend/columnar/columnar_reader.c:306]: A list is conceptually the wrong structure -- an array would be better. But since PG13, the `List` structure has become more similar to a C++ Vector (growable array), so it's not terribly important. If you think there will be a real performance concern in PG12 we can either change it to an array or keep an extra pointer around to the current cell.

Comment (onurctirtir) [reply src/backend/columnar/columnar_reader.c:306]: Indeed, regardless of underlying list implementation, here we search `StripeMetadata` in given `stripeList` to correctly set `currentStripe`.
For this reason, whether we are on PG12 or PG13, `StripeListGetStripeIndex` is always O(n)`, where `n = length(stripeList)`.

File: src/backend/columnar/columnar_reader.c [hunk 4]
```diff
@@ -258,8 +265,8 @@ ColumnarReadNextRow(ColumnarReadState *readState, Datum *columnValues, bool *col
  * exists, then returns false.
  */
 bool
-ColumnarReadRowByRowNumber(Relation relation, uint64 rowNumber,
-						   List *neededColumnList, Datum *columnValues,
+ColumnarReadRowByRowNumber(Relation relation, ColumnarReadState *readState,
+						   uint64 rowNumber, Datum *columnValues,
 						   bool *columnNulls, Snapshot snapshot)
 {
 	StripeMetadata *stripeMetadata = FindStripeByRowNumber(relation, rowNumber, snapshot);
```
Comment (onurctirtir) [inline src/backend/columnar/columnar_reader.c:272]: first check if given row number matches cached stripe

File: src/backend/columnar/columnar_reader.c (hunk 3 above)
Comment (onurctirtir) [reply src/backend/columnar/columnar_reader.c]: Now we don't have the `stripeList` field anymore, so resolving

File: src/backend/columnar/columnar_tableam.c [hunk 5]
```diff
@@ -87,10 +87,30 @@ typedef struct ColumnarScanDescData
 
 typedef struct ColumnarScanDescData *ColumnarScanDesc;
 
+/*
+ * ColumnarScanDescData is the scan state passed between index_fetch_begin,
```
Comment (onurctirtir) [inline src/backend/columnar/columnar_tableam.c:91]:
```suggestion
 * IndexFetchColumnarData is the scan state passed between index_fetch_begin,
```

File: src/backend/columnar/columnar_reader.c [hunk 6]
```diff
@@ -285,11 +328,13 @@ ColumnarReadRowByRowNumber(Relation relation, uint64 rowNumber,
  * Errors out if no such row exists in the stripe being read.
  */
 static void
-ReadStripeRowByRowNumber(StripeReadState *stripeReadState,
-						 StripeMetadata *stripeMetadata,
+ReadStripeRowByRowNumber(ColumnarReadState *readState,
```
Comment (jeff-davis) [inline src/backend/columnar/columnar_reader.c:331]: I'm curious why the signature is changed, it seems like you're passing the larger struct and just extracting the same two parts of it?

**Review by jeff-davis — APPROVED** [review]

File: src/backend/columnar/columnar_reader.c (hunk 6 above)
Comment (onurctirtir) [reply src/backend/columnar/columnar_reader.c:331]: yes, this is the reason
