### PR TITLE
Set placement to inactive on connection failure in COPY

### LINKED ISSUE #1167: COPY fails to mark placements INACTIVE on failed nodes
Previously, `COPY` was marking placements `INACTIVE` if it cannot run on that placement successfully. Currently, it fails to mark placements `INACTIVE` which could easily lead to divergent placements without noticing it. 

I think, we should consider fixing this before 6.1. Steps:

```SQL

SELECT * FROM pg_dist_node;
 nodeid | groupid | nodename  | nodeport | noderack | hasmetadata 
--------+---------+-----------+----------+----------+-------------
      1 |       1 | localhost |     9700 | default  | f
      2 |       2 | localhost |     9701 | default  | f
(2 rows)

-- these are just to replicate tests easily
SET citus.shard_count TO 4;
SET citus.shard_replication_factor TO 2;

CREATE TABLE dist_table (key int);
SELECT create_distributed_table('dist_table', 'key');

-- get the shard id for a value only for displaying purposes
 SELECT get_shard_id_for_distribution_column('dist_table', 1);
 get_shard_id_for_distribution_column 
--------------------------------------
                               102008
(1 row)

-- now stop one of the workers
/usr/local/pgsql/bin/pg_ctl -D /Users/onderkalaci/Documents/data_dir/worker_9700 stop

-- load data using COPY
-- everything looks fine
COPY dist_table FROM STDIN;
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself.
>> 1
>> \.
COPY 1

-- select WARNs about the placement that it cannot reach
-- also returns a value
SELECT * FROM dist_table ;
WARNING:  connection error: localhost:9700
DETAIL:  could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 9700?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 9700?

WARNING:  connection error: localhost:9700
DETAIL:  could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 9700?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 9700?

 key 
-----
   1
(1 row)


-- restart the worker node that we've stopped before
 /usr/local/pgsql/bin/pg_ctl -D /Users/onderkalaci/Documents/data_dir/worker_9700 -o "-p 9700" -l   /tmp/logfile_9700  start

-- oops now SELECT returns empty because we have divergent placements
 SELECT * FROM dist_table ;
 key 
-----
(0 rows)

-- placement states are ACTIVE
SELECT * FROM pg_dist_shard_placement WHERE shardid = 102008;
 shardid | shardstate | shardlength | nodename  | nodeport | placementid 
---------+------------+-------------+-----------+----------+-------------
  102008 |          1 |           0 | localhost |     9700 |           1
  102008 |          1 |           0 | localhost |     9701 |           2
(2 rows)


```

### PR DESCRIPTION
**Pull request by marcocitus**
After the conversion of COPY to the connection API (#1133), the old code to set placements to inactive was removed, but we did not add call MarkRemoteTransactionFailed on connection failure.

Fixes #1167

### CODE REVIEW

**Comment by mtuncer** [comment]
Verified 
- replication factor = 2, and single worker fails then shard state is set to 3
- replication factor = 2, and both worker containing a particular shard is down, command fails, shard state is unchanged
- replication factor = 1,  and the worker is down. command fails, shard state is unchanged

**Comment by onderkalaci** [comment]
Test idea to increase the coverage: Similar to what we've done for reference tables [here](https://github.com/citusdata/citus/blob/master/src/test/regress/sql/multi_modifying_xacts.sql#L823)

File: src/backend/distributed/commands/multi_copy.c [hunk 1]
```diff
@@ -902,32 +904,25 @@ OpenCopyConnections(CopyStmt *copyStatement, ShardConnections *shardConnections,
...
+			ReportResultError(connection, result, ERROR);
 		}
 
 		PQclear(result);
 		connectionList = lappend(connectionList, connection);
 	}
 
 	/* if all placements failed, error out */
-	if (list_length(failedPlacementList) == list_length(finalizedPlacementList))
+	if (failedPlacementCount == list_length(finalizedPlacementList))
```
Comment (mtuncer) [inline src/backend/distributed/commands/multi_copy.c]: perhaps we can move this where failedPlacementCount is incremented.

File: src/backend/distributed/commands/multi_copy.c [hunk 2]
```diff
@@ -902,32 +904,25 @@ OpenCopyConnections(CopyStmt *copyStatement, ShardConnections *shardConnections,
...
+		ereport(ERROR, (errmsg("could not connect to any active placements")));
 	}
 
 	/*
 	 * If stopOnFailure is true, we just error out and code execution should
 	 * never reach to this point. This is the case for reference tables and
 	 * copy from worker nodes.
 	 */
-	Assert(!stopOnFailure || list_length(failedPlacementList) == 0);
+	Assert(!stopOnFailure || failedPlacementCount == 0);
```
Comment (mtuncer) [inline src/backend/distributed/commands/multi_copy.c]: this is sort of obsolete now. if stopOnFailure is set failedPlacementCount is never incremented

**Comment by mtuncer** [comment]
agree with @onderkalaci if we had such test, we would have caught this.

we can user UDF ```run_command_on_workers()``` create new user on workers. i.e.
```sql
select * from run_command_on_workers('create user test_user');
```

could you add a regression test for this scenario ?

**Comment by onderkalaci** [comment]
> Verified
replication factor = 2, and single worker fails then shard state is set to 3
replication factor = 2, and both worker containing a particular shard is down, command fails, shard state is unchanged
replication factor = 1, and the worker is down. command fails, shard state is unchanged

What about `set citus.multi_shard_commit_protocol TO '2pc';` and reference table cases? What is the expected behavior? Is that still marking the placement INACTIVE?

**Comment by metdos** [comment]
@mtuncer, I'm adding 6.1 tag. Could you let @marcocitus know when you are done with regression tests?

**Comment by mtuncer** [comment]
@marcocitus I am done adding test, could you take a look ?

File: src/test/regress/input/multi_copy.source [hunk 3]
```diff
@@ -538,3 +538,214 @@ SELECT master_create_distributed_table('composite_partition_column_table', 'comp
...
+3,3
+4,4
+5,5
+6,6
+7,7
+8,8
+\.
+
+-- verify shards in the first worker as marked invalid
+SELECT shardid, shardstate, nodename, nodeport
```
Comment (marcocitus) [inline src/test/regress/input/multi_copy.source]: It'd be good to also verify this within the same transaction block.

File: src/test/regress/sql/multi_modifying_xacts.sql [hunk 4]
```diff
@@ -863,13 +875,46 @@ AND      s.logicalrelid = 'reference_failure_test'::regclass
...
+
+BEGIN;
+COPY numbers_hash_failure_test FROM STDIN WITH (FORMAT 'csv');
+1,1
+2,2
+\.
+COMMIT;
+
+-- expect some placements to be market invalid
+SELECT shardid, shardstate, nodename, nodeport
```
Comment (marcocitus) [inline src/test/regress/sql/multi_modifying_xacts.sql]: Could we move this into the transaction block? That's where it's interesting.

File: src/backend/distributed/commands/multi_copy.c (hunk 1 above)
Comment (marcocitus) [inline src/backend/distributed/commands/multi_copy.c]: Well, this can only be true at the very end.

File: src/backend/distributed/commands/multi_copy.c (hunk 2 above)
Comment (marcocitus) [inline src/backend/distributed/commands/multi_copy.c]: I think the Assert still applies. If stopOnFailure is true we should only be able to get here with failedPlacementCount 0.
