### PR TITLE
Fix create index concurrently crash with local execution

### LINKED ISSUE #4090: CREATE INDEX CONCURRENTLY crashes with local execution
```sql
CREATE TABLE tbl_gist (c1 int, c2 int, c3 int, c4 box);
--or CREATE TABLE tbl_gist (c1 int, c2 int, c3 int, c4 box, EXCLUDE USING gist (c4 WITH &&) INCLUDE (c1, c2, c3));
SELECT create_reference_table('tbl_gist');
CREATE INDEX CONCURRENTLY tbl_gist_idx ON tbl_gist using gist (c4) INCLUDE (c1,c2,c3);
```

Above `CREATE INDEX CONCURRENTLY` command seg.faults **when coordinator is added to pg_dist_node**, with the below backtrace:

```c
#0  0x0000000000b06005 in PopActiveSnapshot () at snapmgr.c:818
#1  0x0000000000691468 in DefineIndex (relationId=812292, stmt=0x1df0c38, indexRelationId=812296, parentIndexId=0, parentConstraintId=0,
    is_alter_table=false, check_rights=true, check_not_in_use=true, skip_build=false, quiet=false) at indexcmds.c:1370
#2  0x0000000000928330 in ProcessUtilitySlow (pstate=0x1ddea50, pstmt=0x1df0700,
    queryString=0x1e4bb60 "CREATE  INDEX CONCURRENTLY  tbl_gist_idx_102140 ON public.tbl_gist_102140 USING gist (c4 ) INCLUDE (c1 ,c2 ,c3 )",
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0xcde5e0 <donothingDR>, completionTag=0x0) at utility.c:1372
#3  0x00000000009273ff in standard_ProcessUtility (pstmt=0x1df0700,
    queryString=0x1e4bb60 "CREATE  INDEX CONCURRENTLY  tbl_gist_idx_102140 ON public.tbl_gist_102140 USING gist (c4 ) INCLUDE (c1 ,c2 ,c3 )",
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0xcde5e0 <donothingDR>, completionTag=0x0) at utility.c:927
#4  0x00007f5ffa7b9b98 in multi_ProcessUtility (pstmt=0x1df0700,
    queryString=0x1e4bb60 "CREATE  INDEX CONCURRENTLY  tbl_gist_idx_102140 ON public.tbl_gist_102140 USING gist (c4 ) INCLUDE (c1 ,c2 ,c3 )",
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0xcde5e0 <donothingDR>, completionTag=0x0) at commands/utility_hook.c:490
#5  0x0000000000926399 in ProcessUtility (pstmt=0x1ddfa18,
    queryString=0x1e4bb60 "CREATE  INDEX CONCURRENTLY  tbl_gist_idx_102140 ON public.tbl_gist_102140 USING gist (c4 ) INCLUDE (c1 ,c2 ,c3 )",
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0xcde5e0 <donothingDR>, completionTag=0x0) at utility.c:356
#6  0x00007f5ffa7b8f80 in CitusProcessUtility (node=0x1ddec00,
    queryString=0x1e4bb60 "CREATE  INDEX CONCURRENTLY  tbl_gist_idx_102140 ON public.tbl_gist_102140 USING gist (c4 ) INCLUDE (c1 ,c2 ,c3 )",
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, dest=0xcde5e0 <donothingDR>, completionTag=0x0) at commands/utility_hook.c:97
#7  0x00007f5ffa7e85ac in LocallyExecuteUtilityTask (
    localTaskQueryCommand=0x1e4bb60 "CREATE  INDEX CONCURRENTLY  tbl_gist_idx_102140 ON public.tbl_gist_102140 USING gist (c4 ) INCLUDE (c1 ,c2 ,c3 )")
    at executor/local_executor.c:397
#8  0x00007f5ffa7e8229 in ExecuteLocalTaskListExtended (taskList=0x1ddfc10, orig_paramListInfo=0x0, distributedPlan=0x0, defaultTupleDest=0x1ddfc48,
    isUtilityCommand=true) at executor/local_executor.c:229
#9  0x00007f5ffa7e8110 in ExecuteLocalUtilityTaskList (utilityTaskList=0x1ddfc10) at executor/local_executor.c:171
#10 0x00007f5ffa7dd0c3 in ExecuteTaskListExtended (executionParams=0x1ddfab0) at executor/adaptive_executor.c:1007
#11 0x00007f5ffa7dce0c in ExecuteUtilityTaskList (utilityTaskList=0x1e4be20, localExecutionSupported=true) at executor/adaptive_executor.c:872
#12 0x00007f5ffa7ba0c5 in ExecuteDistributedDDLJob (ddlJob=0x1d792e8) at commands/utility_hook.c:693
#13 0x00007f5ffa7b9e56 in multi_ProcessUtility (pstmt=0x1cb3888,
    queryString=0x1c1fae8 "CREATE INDEX CONCURRENTLY tbl_gist_idx ON tbl_gist using gist (c4) INCLUDE (c1,c2,c3);", context=PROCESS_UTILITY_TOPLEVEL,
    params=0x0, queryEnv=0x0, dest=0x1c20db0, completionTag=0x7ffeb0978690 "") at commands/utility_hook.c:588
#14 0x0000000000926399 in ProcessUtility (pstmt=0x1c20cb8,
    queryString=0x1c1fae8 "CREATE INDEX CONCURRENTLY tbl_gist_idx ON tbl_gist using gist (c4) INCLUDE (c1,c2,c3);", context=PROCESS_UTILITY_TOPLEVEL,
    params=0x0, queryEnv=0x0, dest=0x1c20db0, completionTag=0x7ffeb0978690 "") at utility.c:356
#15 0x0000000000925377 in PortalRunUtility (portal=0x1cf87d8, pstmt=0x1c20cb8, isTopLevel=true, setHoldSnapshot=false, dest=0x1c20db0,
    completionTag=0x7ffeb0978690 "") at pquery.c:1175
#16 0x0000000000925593 in PortalRunMulti (portal=0x1cf87d8, isTopLevel=true, setHoldSnapshot=false, dest=0x1c20db0, altdest=0x1c20db0,
    completionTag=0x7ffeb0978690 "") at pquery.c:1321
#17 0x0000000000924a4d in PortalRun (portal=0x1cf87d8, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x1c20db0, altdest=0x1c20db0,
    completionTag=0x7ffeb0978690 "") at pquery.c:796
#18 0x000000000091e5b4 in exec_simple_query (
    query_string=0x1c1fae8 "CREATE INDEX CONCURRENTLY tbl_gist_idx ON tbl_gist using gist (c4) INCLUDE (c1,c2,c3);") at postgres.c:1215
#19 0x0000000000922a7c in PostgresMain (argc=1, argv=0x1cb8998, dbname=0x1cb87d8 "postgres", username=0x1cb87b0 "postgres") at postgres.c:4247
#20 0x00000000008713bd in BackendRun (port=0x1c3b9f0) at postmaster.c:4448
#21 0x0000000000870b06 in BackendStartup (port=0x1c3b9f0) at postmaster.c:4139
#22 0x000000000086cc46 in ServerLoop () at postmaster.c:1704
#23 0x000000000086c46d in PostmasterMain (argc=3, argv=0x1c1a760) at postmaster.c:1377
#24 0x00000000007850f7 in main (argc=3, argv=0x1c1a760) at main.c:228
```

### PR DESCRIPTION
**Pull request by marcocitus**
DESCRIPTION: Fixes create index concurrently crash with local execution

Stop using local execution for CREATE INDEX CONCURRENTLY. Start a new transaction before sending commands to localhost to avoid deadlock. Move marking the index as valid to the end of execution.

Overall, CREATE INDEX CONCURRENTLY seems quite shaky at the moment. We should maybe handle it separately from other DDL commands.

Fixes #4090

### CODE REVIEW

File: src/backend/distributed/commands/index.c [hunk 1]
```diff
@@ -442,23 +444,6 @@ PostprocessIndexStmt(Node *node, const char *queryString)
...
-	/* now, update index's validity in a way that can roll back */
-	Relation pg_index = table_open(IndexRelationId, RowExclusiveLock);
-
-	HeapTuple indexTuple = SearchSysCacheCopy1(INDEXRELID, ObjectIdGetDatum(
-												   indexRelationId));
-	Assert(HeapTupleIsValid(indexTuple)); /* better be present, we have lock! */
-
-	/* mark as valid, save, and update pg_index indexes */
-	Form_pg_index indexForm = (Form_pg_index) GETSTRUCT(indexTuple);
-	indexForm->indisvalid = true;
```
Comment (marcocitus) [inline src/backend/distributed/commands/index.c:454]: This logic used to mark the index as valid without committing, such that a failure during distributed DDL execution would roll back to the invalid state set above. However, after adding the CommitTransactionCommand in ExecuteDistributedDDLJob we would always commit the valid state. I therefore set the valid state after ExecuteDistributedDDLJob completes, in FinishConcurrentIndexCommand.

File: src/backend/distributed/commands/index.c [hunk 2]
```diff
@@ -921,3 +913,43 @@ DropIndexTaskList(Oid relationId, Oid indexId, DropStmt *dropStmt)
...
+ */
+void
+FinishConcurrentIndexCommand(IndexStmt *indexStmt)
+{
+	Assert(indexStmt->concurrent);
+
+	/* this logic only applies to the coordinator */
+	if (!IsCoordinator())
+	{
+		return;
```
Comment (onurctirtir) [inline src/backend/distributed/commands/index.c:931]: should we add a test in mx for that ?

Comment (marcocitus) [reply src/backend/distributed/commands/index.c:931]: this may be a little misleading since we cannot get here if we're not on the coordinator, changing to an assert

File: src/backend/distributed/commands/index.c [hunk 3]
```diff
@@ -921,3 +913,38 @@ DropIndexTaskList(Oid relationId, Oid indexId, DropStmt *dropStmt)
...
+void
+FinishConcurrentIndexCommand(IndexStmt *indexStmt)
+{
+	Assert(indexStmt->concurrent);
+	Assert(IsCoordinator());
+
+	/*
+	 * We make sure schema name is not null in the PreprocessIndexStmt
+	 */
+	Oid schemaId = get_namespace_oid(indexStmt->relation->schemaname, true);
```
Comment (onurctirtir) [inline src/backend/distributed/commands/index.c:932]: I see that we are sure that table/schema exists but giving missingOk to be false might a bit safer maybe

File: src/backend/distributed/commands/index.c (hunk 2 above)
Comment (onurctirtir) [reply src/backend/distributed/commands/index.c]: does it apply for below check as well ? :

```c
	if (!IsCitusTable(relationId))
	{
		return;
	}
```

Comment (marcocitus) [reply src/backend/distributed/commands/index.c]: yes, changed to assert

File: src/backend/distributed/commands/index.c [hunk 4]
```diff
@@ -442,23 +451,6 @@ PostprocessIndexStmt(Node *node, const char *queryString)
 	CommitTransactionCommand();
```
Comment (onderkalaci) [inline src/backend/distributed/commands/index.c:451]: Do we still need these commit/start calls? We'll do it anyway inside `ExecuteDistributedDDLJob` just before the distributed execution? I mean, we are not doing anything in between this `StartTransactionCommand ()` and `CommitTransactionCommand()` when `if (ddlJob->startNewTransaction)` is true?

**Review by onderkalaci — COMMENTED** [review]
I think this looks okay, tested with failures/single-node/multi-node etc, all works fine as well.

I can maybe look at once more if you agree to change some of the comments I have. Otherwise, feel free to merge

File: src/backend/distributed/commands/index.c (hunk 4 above)
Comment (marcocitus) [reply src/backend/distributed/commands/index.c:451]: Yes, for the DROP INDEX CONCURRENTLY case.

File: src/backend/distributed/commands/index.c [hunk 5]
```diff
@@ -921,3 +913,39 @@ DropIndexTaskList(Oid relationId, Oid indexId, DropStmt *dropStmt)
 
 	return taskList;
 }
+
+
+/*
+ * FinishConcurrentIndexCommand marks new indexes valid if they were created using
```
[the remark this answers is not in the document]
Comment (marcocitus) [reply src/backend/distributed/commands/index.c]: Changed it to MarkIndexValid. PostprocessIndexStmt is very specific due to its commit/start sequence, so I'd rather leave it as is.

File: src/backend/distributed/commands/utility_hook.c [hunk 6]
```diff
@@ -675,6 +689,18 @@ ExecuteDistributedDDLJob(DDLJob *ddlJob)
...
 	{
+		localExecutionSupported = false;
+
+		/*
+		 * Start a new transaction to make sure CONCURRENTLY commands
+		 * on localhost do not block waiting for this transaction to finish.
+		 */
+		if (ddlJob->startNewTransaction)
+		{
+			CommitTransactionCommand();
```
[the remark this answers is not in the document]
Comment (marcocitus) [reply src/backend/distributed/commands/utility_hook.c:701]: I don't think we do.

File: src/backend/distributed/commands/index.c (hunk 4 above)
Comment (marcocitus) [reply src/backend/distributed/commands/index.c:451]: We also need to recommit after checking for metadata syncing, otherwise we still have a snapshot.

**Review by onderkalaci — APPROVED** [review]
Ah, sorry I thought I already approved this.  Thanks for the explanations on the PR
