### PR TITLE
Use translated vars in postgres 13 as well

### LINKED ISSUE #4722: Union ALL behaves wrong on PG 13
Even if operation is not supposed to be pushed down, it is pushed down on PG 13

```SQL
 select version();
                                                      version                                                      
-------------------------------------------------------------------------------------------------------------------
 PostgreSQL 12.3 on x86_64-apple-darwin18.7.0, compiled by Apple clang version 11.0.0 (clang-1100.0.33.17), 64-bit
(1 row)

Time: 0.851 ms

 create table test (x int, y int);
  select create_distributed_table('test', 'x');

  set client_min_messages TO DEBUG1;

 SELECT * FROM ((SELECT x,y FROM test) UNION ALL (SELECT y,x FROM test)) u;

 DEBUG:  generating subplan 5_1 for subquery SELECT x, y FROM public.test
DEBUG:  generating subplan 5_2 for subquery SELECT y, x FROM public.test
DEBUG:  generating subplan 5_3 for subquery SELECT intermediate_result.x, intermediate_result.y FROM read_intermediate_result('5_1'::text, 'binary'::citus_copy_format) intermediate_result(x integer, y integer) UNION ALL SELECT intermediate_result.y, intermediate_result.x FROM read_intermediate_result('5_2'::text, 'binary'::citus_copy_format) intermediate_result(y integer, x integer)
DEBUG:  Plan 5 query after replacing subqueries and CTEs: SELECT x, y FROM (SELECT intermediate_result.x, intermediate_result.y FROM read_intermediate_result('5_3'::text, 'binary'::citus_copy_format) intermediate_result(x integer, y integer)) u
 x | y 
---+---
(0 rows)

Time: 13.138 ms
```

On PG13, the same query is pushed down:
```SQL
select version();
                                                      version                                                      
-------------------------------------------------------------------------------------------------------------------
 PostgreSQL 13.1 on x86_64-apple-darwin20.3.0, compiled by Apple clang version 11.0.0 (clang-1100.0.33.17), 64-bit
(1 row)

Time: 4.837 ms



 create table test (x int, y int);
  select create_distributed_table('test', 'x');

  set client_min_messages TO DEBUG1;

 SELECT * FROM ((SELECT x,y FROM test) UNION ALL (SELECT y,x FROM test)) u;

 x | y 
---+---
(0 rows)

Time: 33.547 ms


-- log_remote_commands to on
NOTICE:  issuing SELECT worker_column_1 AS x, worker_column_2 AS y FROM (SELECT u.x AS worker_column_1, u.y AS worker_column_2 FROM (SELECT test.x, test.y FROM public.test_102078 test UNION ALL SELECT test.y, test.x FROM public.test_102078 test) u) worker_subquery

```

Should be backported to Citus 9.5 where we start to support pg 13. It looks like the bug is on `FindUnionAllVar()`

### PR DESCRIPTION
**Pull request by SaitTalhaNisanci**
Postgres 13 removed translated vars with pg 13 so we had a special logic
for pg 13. However it had some bug, so now we copy the translated vars
before postgres deletes it. This also simplifies the logic.

DESCRIPTION:  Fixes a bug with UNION ALL on PG 13

Fixes #4722.

### CODE REVIEW

File: src/backend/distributed/planner/distributed_planner.c [hunk 1]
```diff
@@ -1815,6 +1817,18 @@ multi_relation_restriction_hook(PlannerInfo *root, RelOptInfo *relOptInfo,
...
 
+	if (root->append_rel_list != NIL)
+	{
+		AppendRelInfo *targetAppendRelInfo = FindTargetAppendRelInfo(
+			root->append_rel_list, relationRestriction->index);
+		if (targetAppendRelInfo != NULL)
+		{
+			/* postgres deletes translated_vars after pg13, hence we copy them here */
+			relationRestriction->translatedVars = 
+				list_copy(targetAppendRelInfo->translated_vars);
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/planner/distributed_planner.c:1828]: list_copy seems enough here because there are Vars in this list and we aren't interested in any pointers in the Vars.

Comment (onderkalaci) [reply src/backend/distributed/planner/distributed_planner.c:1828]: Well, lets be on the safe side an call `list_copy_deep`?

File: src/backend/distributed/planner/distributed_planner.c [hunk 2]
```diff
@@ -1815,6 +1817,18 @@ multi_relation_restriction_hook(PlannerInfo *root, RelOptInfo *relOptInfo,
 	/* see comments on GetVarFromAssignedParam() */
 	relationRestriction->outerPlanParamsList = OuterPlanParamsList(root);
 
+	if (root->append_rel_list != NIL)
```
Comment (onderkalaci) [inline src/backend/distributed/planner/distributed_planner.c:1820]: can we move all this logic to a function, like `OuterPlanParamsList ` does?

**Comment by onderkalaci** [comment]
> DESCRIPTION: Fixes a correctness issue with UNION ALL

Maybe `Fixes a bug with UNION ALL on PG 13` ?

File: src/backend/distributed/planner/distributed_planner.c (hunk 1 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/distributed_planner.c:1828]: list_copy_deep is only available in pg13 I think.

I will manually do the deep copy then.

File: src/backend/distributed/planner/distributed_planner.c [hunk 3]
```diff
@@ -1837,6 +1842,60 @@ multi_relation_restriction_hook(PlannerInfo *root, RelOptInfo *relOptInfo,
...
+ * if there is any append rel list.
+ */
+static List *
+TranslatedVars(PlannerInfo *root, int relationIndex)
+{
+	List *translatedVars = NIL;
+
+	if (root->append_rel_list != NIL)
+	{
+		AppendRelInfo *targetAppendRelInfo = FindTargetAppendRelInfo(
```
Comment (onderkalaci) [inline src/backend/distributed/planner/distributed_planner.c:1856]: Minor: unusual indentation

File: src/backend/distributed/planner/distributed_planner.c [hunk 4]
```diff
@@ -1837,6 +1842,60 @@ multi_relation_restriction_hook(PlannerInfo *root, RelOptInfo *relOptInfo,
...
+			root->append_rel_list, relationIndex);
+		if (targetAppendRelInfo != NULL)
+		{
+			/* postgres deletes translated_vars after pg13, hence we deep copy them here */
+			ListCell *translatedVarCell = NULL;
+			foreach(translatedVarCell, translatedVars)
+			{
+				Node *targetNode = (Node *) lfirst(translatedVarCell);
+				translatedVars =
+					lappend(translatedVars, copyObjectImpl(targetNode));
```
Comment (onderkalaci) [inline src/backend/distributed/planner/distributed_planner.c:1866]: Why don't we use `copyObject` which is much more common?

File: src/backend/distributed/planner/distributed_planner.c [hunk 5]
```diff
@@ -1837,6 +1842,60 @@ multi_relation_restriction_hook(PlannerInfo *root, RelOptInfo *relOptInfo,
...
+
+	if (root->append_rel_list != NIL)
+	{
+		AppendRelInfo *targetAppendRelInfo = FindTargetAppendRelInfo(
+			root->append_rel_list, relationIndex);
+		if (targetAppendRelInfo != NULL)
+		{
+			/* postgres deletes translated_vars after pg13, hence we deep copy them here */
+			ListCell *translatedVarCell = NULL;
+			foreach(translatedVarCell, translatedVars)
```
Comment (onderkalaci) [inline src/backend/distributed/planner/distributed_planner.c:1862]: we try to iterate on a NIL list?

Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/distributed_planner.c:1862]: it should be fine I guess

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 6]
```diff
@@ -374,62 +374,45 @@ SafeToPushdownUnionSubquery(PlannerRestrictionContext *plannerRestrictionContext
...
- * relationRteIndex as its index and the same varattno as the partition key of
- * the given relation with relationOid.
+ * RangeTableOffsetCompat returns the range table offset(in glob->finalrtable) for the appendRelInfo.
+ * For PG < 13 this is a no op.
  */
-static Var *
-FindUnionAllVar(PlannerInfo *root, List *appendRelList, Oid relationOid,
-				Index relationRteIndex, Index *partitionKeyIndex)
+int
+RangeTableOffsetCompat(PlannerInfo *root, AppendRelInfo *appendRelInfo)
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:381]: The following query can be pushed down on PG 12 but not on PG 13. Could it be related to this function where we check only the first inherited entry?
```SQL

     SELECT *
FROM
  (SELECT user_id  AS user_id
   FROM
     (SELECT user_id  AS user_id
      FROM users_table
      UNION ALL SELECT user_id AS user_id
      FROM users_table) AS bar
   UNION ALL SELECT user_id  AS user_id
   FROM users_table) AS fool LIMIT 1;
```

File: src/backend/distributed/planner/distributed_planner.c [hunk 7]
```diff
@@ -1837,6 +1842,62 @@ multi_relation_restriction_hook(PlannerInfo *root, RelOptInfo *relOptInfo,
...
+
+	if (root->append_rel_list != NIL)
+	{
+		AppendRelInfo *targetAppendRelInfo =
+			FindTargetAppendRelInfo(root, relationIndex);
+		if (targetAppendRelInfo != NULL)
+		{
+			/* postgres deletes translated_vars after pg13, hence we deep copy them here */
+			ListCell *translatedVarCell = NULL;
+			foreach(translatedVarCell, targetAppendRelInfo->translated_vars)
```
Comment (onderkalaci) [inline src/backend/distributed/planner/distributed_planner.c:1862]: minor: maybe use foreach_ptr for consistency

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 8]
```diff
@@ -374,62 +374,45 @@ SafeToPushdownUnionSubquery(PlannerRestrictionContext *plannerRestrictionContext
...
-
-
-		int rtoffset = RangeTableOffsetCompat(root, appendRelInfo);
-
-		/*
-		 * We're only interested in the child rel that is equal to the
-		 * relation we're investigating.
-		 */
-		if (appendRelInfo->child_relid - rtoffset == relationRteIndex)
+		RangeTblEntry *rte = root->simple_rte_array[i];
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:387]: I hit another error specific to pg 13
```SQL
SELECT * FROM 
	(SELECT user_id FROM users_table_part UNION ALL SELECT user_id FROM users_table_part) as foo
	JOIN
	(SELECT user_id FROM users_table_part UNION ALL SELECT user_id FROM users_table_part) as bar
USING (user_id);
ERROR:  no relation entry for relid 9
Time: 0.682 ms
```

**Comment by onderkalaci** [comment]
Can you add a new test file, like `union_pushdown` or such with tables/queries like this (and whatever you want): https://gist.github.com/onderkalaci/e767eef68ca1ad83b7b143e6fc48285b

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 9]
```diff
@@ -1387,30 +1384,25 @@ AddUnionAllSetOperationsToAttributeEquivalenceClass(AttributeEquivalenceClass **
...
-	{
-		RangeTblEntry *rte = root->simple_rte_array[i];
-		if (rte->inh)
-		{
-			break;
+static int FindPreviousParentAmount(List* appendRelList, AppendRelInfo* targetAppendRelInfo) {
+	int targetParentIndex = targetAppendRelInfo->parent_relid;
+	Bitmapset *parent_ids = NULL;
+	AppendRelInfo *appendRelInfo = NULL;
+	foreach_ptr(appendRelInfo, appendRelList) {
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1396]: minor: the style should be updated

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 10]
```diff
@@ -1387,30 +1384,25 @@ AddUnionAllSetOperationsToAttributeEquivalenceClass(AttributeEquivalenceClass **
...
+		int curParentIndex = appendRelInfo->parent_relid;
+		if (curParentIndex < targetParentIndex &&
+			!bms_is_member(curParentIndex, parent_ids)) {
+				parent_ids = bms_add_member(parent_ids, curParentIndex);
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1400]: minor: you don't need to check `bms_is_member `

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 11]
```diff
@@ -1387,30 +1384,25 @@ AddUnionAllSetOperationsToAttributeEquivalenceClass(AttributeEquivalenceClass **
...
-{
-	#if PG_VERSION_NUM >= PG_VERSION_13
-	int i = 1;
-	for (; i < root->simple_rel_array_size; i++)
-	{
-		RangeTblEntry *rte = root->simple_rte_array[i];
-		if (rte->inh)
-		{
-			break;
+static int FindPreviousParentAmount(List* appendRelList, AppendRelInfo* targetAppendRelInfo) {
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1392]: Maybe call this: `ParentCountPriorToAppendRel()`  and do `curParentIndex <= targetParentIndex` in the code. And, then:
```C
int parentCount = ParentCountPriorToAppendRel(root->append_rel_list, appendRelInfo);
int skipParentCount = parentCount -1;
```
That looks more natural and easier to follow to me. What do you think?

File: src/test/regress/expected/set_operations.out [hunk 12]
```diff
@@ -829,6 +829,73 @@ DEBUG:  Router planner cannot handle multi-shard select queries
 DEBUG:  Router planner cannot handle multi-shard select queries
 ERROR:  cannot compute aggregate (distinct)
 DETAIL:  table partitioning is unsuitable for aggregate (distinct)
+/* these are not safe to push down as the partition key index is different */
+SELECT x,y FROM test UNION ALL SELECT y,x FROM test ORDER BY 1,2;
```
[the remark this answers is not in the document]
Comment (onderkalaci) [reply src/test/regress/expected/set_operations.out:833]: So, I think we should change the comment to something like: `Top level union all with distribution key indexes do not match` or such

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 13]
```diff
@@ -374,62 +379,55 @@ SafeToPushdownUnionSubquery(PlannerRestrictionContext *plannerRestrictionContext
...
-		if (appendRelInfo->child_relid - rtoffset == relationRteIndex)
+		RangeTblEntry *rte = root->simple_rte_array[i];
+		if (rte->inh)
 		{
-			targetAppendRelInfo = appendRelInfo;
+			/*
+			 * we skip the previous parents because we want to find the offset
+			 * for the given append rel info
+			 */
+			if (skipAmount) {
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:401]: minor: Lets be more explicit: `if (skipParentCount  > 0)` and improve the alignment of curly braces

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 10 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:1400]: what do you mean?  You mean we don't need `!bms_is_member(curParentIndex, parent_ids)` ?

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 11 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:1392]: yes that is easier to follow

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 10 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:1400]: yes, because bms should be fine even if you add the same member multiple times

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 14]
```diff
@@ -156,8 +156,12 @@ static JoinRestrictionContext * FilterJoinRestrictionContext(
 static bool RangeTableArrayContainsAnyRTEIdentities(RangeTblEntry **rangeTableEntries, int
 													rangeTableArrayLength, Relids
 													queryRteIdentities);
-static int RangeTableOffsetCompat(PlannerInfo *root, AppendRelInfo *appendRelInfo);
 static Relids QueryRteIdentities(Query *queryTree);
+static int RangeTableOffsetCompat(PlannerInfo *root, AppendRelInfo *appendRelInfo);
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:160]: very minor: we typically try to keep the order of definitions and declarations the same

File: src/test/regress/expected/union_pushdown.out [hunk 15]
```diff
@@ -0,0 +1,302 @@
...
+      UNION ALL SELECT user_id AS user_id FROM users_table_part JOIN events_table_part USING (user_id) WHERE users_table_part.value_1 = 8  GROUP BY user_id)) AS bar
+      WHERE user_id < 2000 ) as level_1 ) as level_2 ) as level_3
+ORDER BY 1 DESC LIMIT 10;
+DEBUG:  push down of limit count: 10
+ count
+---------------------------------------------------------------------
+    78
+(1 row)
+
+SELECT COUNT(*) FROM
```
Comment (onderkalaci) [inline src/test/regress/expected/union_pushdown.out:257]: maybe add a comment:
```
-- leaves of the top level UNION ALL is recursively planned, but the leaves themselves
-- safe to pushdown
```

File: src/test/regress/expected/union_pushdown.out [hunk 16]
```diff
@@ -0,0 +1,302 @@
...
+DEBUG:  generating subplan XXX_2 for subquery SELECT count(*) AS count FROM ((SELECT users_table_part.user_id FROM union_pushdown.users_table_part UNION ALL SELECT users_table_part.user_id FROM union_pushdown.users_table_part) foo JOIN (SELECT users_table_part.user_id FROM union_pushdown.users_table_part UNION ALL SELECT users_table_part.user_id FROM union_pushdown.users_table_part) bar USING (user_id))
+DEBUG:  Plan XXX query after replacing subqueries and CTEs: SELECT intermediate_result.count FROM read_intermediate_result('XXX_1'::text, 'binary'::citus_copy_format) intermediate_result(count bigint) UNION ALL SELECT intermediate_result.count FROM read_intermediate_result('XXX_2'::text, 'binary'::citus_copy_format) intermediate_result(count bigint)
+ count
+---------------------------------------------------------------------
+   404
+   404
+(2 rows)
+
+SELECT COUNT(*) FROM (
```
Comment (onderkalaci) [inline src/test/regress/expected/union_pushdown.out:277]: again, same comment:
```
-- leaves of the top level UNION ALL is recursively planned, but the leaves themselves
-- safe to pushdown
```

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 8 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:395]: @SaitTalhaNisanci  do we have a test equivalent to this one?

**Review by onderkalaci — APPROVED** [review]

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 17]
```diff
@@ -374,62 +379,64 @@ SafeToPushdownUnionSubquery(PlannerRestrictionContext *plannerRestrictionContext
...
-			targetAppendRelInfo = appendRelInfo;
+			/*
+			 * We skip the previous parents because we want to find the offset
+			 * for the given append rel info.
+			 */
+			if (skipParentCount > 0)
+			{
+				skipParentCount--;
+				continue;
+			}
```
[the remark this answers is not in the document]
Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:406]: The tables were not distributed, fixed now and verified that we enter this block.
