### PR TITLE
Fix null relation name due to DROP on distributed table in a transaction block

### LINKED ISSUE #3520: CheckConflictingRelationAccesses crashes due to NULL relationName when trying to error out for DROP on distributed table in a transaction block
It is easy to reproduce.

Defining a distributed table having a foreign key referencing to a reference table,

```sql
create table ref_table(a int primary key);
select create_reference_table('ref_table');
create table dist_table(a int);
select create_distributed_table('dist_table', 'a');
alter table dist_table add constraint fkey foreign key(a) references ref_table(a);
```

, and, accessing to the reference table and trying to drop the distributed table within the same transaction,

```sql
begin; 
 select * from dist_table;
 drop table ref_table cascade;
```

causes the following PostgreSQL assertion crash due to `NULL`relation name we get in `relation_access_tracking.c:719` with the following stack trace (casserts are enabled):

(Note that here the problem is not the assertion PostgreSQL does, disabling the casserts does only change the situation from `abort` to `SIGSEGV`)

*Actual issue here is `get_rel_name` call for `ref_table_oid` returns `NULL` `char*` within the transaction block*. This is because `standard_ProcessUtility` already dropped the table and we try to get name of the relation, hence PostgreSQL returns us a `NULL` pointer.

```
#0  0x00007f32335f6428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54                                                                                                                                                                                                                       [1/641]
#1  0x00007f32335f802a in __GI_abort () at abort.c:89
#2  0x0000000000ab4514 in ExceptionalCondition (conditionName=0xd6127b "!(strvalue != ((void *)0))", errorType=0xd6126b "FailedAssertion",
    fileName=0xd61260 "snprintf.c", lineNumber=442) at assert.c:54
#3  0x0000000000b1a01a in dopr (target=0x7ffdeeb83f80,
    format=0x7f3230f0369b "\" because there was a parallel %s access to distributed relation \"%s\" in the same transaction", args=0x7ffdeeb840b0)
    at snprintf.c:442
#4  0x0000000000b1984b in pg_vsnprintf (str=0x2910f78 "cannot execute DDL on reference relation \"", '\177' <repeats 158 times>..., count=1024,
    fmt=0x7f3230f03670 "cannot execute %s on reference relation \"%s\" because there was a parallel %s access to distributed relation \"%s\" in the same transaction", args=0x7ffdeeb840b0) at snprintf.c:195
#5  0x0000000000b245e1 in pvsnprintf (buf=0x2910f78 "cannot execute DDL on reference relation \"", '\177' <repeats 158 times>..., len=1024,
    fmt=0x7f3230f03670 "cannot execute %s on reference relation \"%s\" because there was a parallel %s access to distributed relation \"%s\" in the same transaction", args=0x7ffdeeb840b0) at psprintf.c:110
#6  0x000000000076fb57 in appendStringInfoVA (str=0x7ffdeeb84090,
    fmt=0x7f3230f03670 "cannot execute %s on reference relation \"%s\" because there was a parallel %s access to distributed relation \"%s\" in the same transaction", args=0x7ffdeeb840b0) at stringinfo.c:136
#7  0x0000000000ab51d6 in errmsg (
    fmt=0x7f3230f03670 "cannot execute %s on reference relation \"%s\" because there was a parallel %s access to distributed relation \"%s\" in the same transaction") at elog.c:794
#8  0x00007f3230ec08ee in CheckConflictingRelationAccesses (relationId=49577, accessType=PLACEMENT_ACCESS_DDL) at transaction/relation_access_tracking.c:716
#9  0x00007f3230ec0076 in RecordRelationAccessBase (relationId=49577, accessType=PLACEMENT_ACCESS_DDL) at transaction/relation_access_tracking.c:231
#10 0x00007f3230ebffd7 in RecordRelationAccessIfReferenceTable (relationId=49577, accessType=PLACEMENT_ACCESS_DDL)
    at transaction/relation_access_tracking.c:175
#11 0x00007f3230e3e070 in AssignPlacementListToConnection (placementAccessList=0x2b2e480, connection=0x298fc80) at connection/placement_connection.c:441
#12 0x00007f3230e3de31 in StartPlacementListConnection (flags=2, placementAccessList=0x2b2e480, userName=0x2b2e4b8 "onurctirtir")
    at connection/placement_connection.c:321
#13 0x00007f3230e3dcf6 in StartPlacementConnection (flags=2, placement=0x2b2de00, userName=0x0) at connection/placement_connection.c:256
#14 0x00007f3230e3dc56 in GetPlacementConnection (flags=2, placement=0x2b2de00, userName=0x0) at connection/placement_connection.c:209
#15 0x00007f3230e6fb47 in DropShards (relationId=49577, schemaName=0x2b2d828 "public", relationName=0x2b2d848 "ref_table",
    deletableShardIntervalList=0x2b2d930) at master/master_delete_protocol.c:421
#16 0x00007f3230e6f6ae in master_drop_all_shards (fcinfo=0x2b40040) at master/master_delete_protocol.c:235
#17 0x0000000000706d62 in ExecInterpExpr (state=0x2b3ff58, econtext=0x2b3fc48, isnull=0x7ffdeeb8473f) at execExprInterp.c:649
#18 0x0000000000708cbb in ExecInterpExprStillValid (state=0x2b3ff58, econtext=0x2b3fc48, isNull=0x7ffdeeb8473f) at execExprInterp.c:1769
#19 0x0000000000750d82 in ExecEvalExprSwitchContext (state=0x2b3ff58, econtext=0x2b3fc48, isNull=0x7ffdeeb8473f)
    at ../../../src/include/executor/executor.h:307
#20 0x0000000000750dfa in ExecProject (projInfo=0x2b3ff50) at ../../../src/include/executor/executor.h:341
#21 0x0000000000751017 in ExecResult (pstate=0x2b3fb30) at nodeResult.c:136
#22 0x000000000071cb6c in ExecProcNodeFirst (node=0x2b3fb30) at execProcnode.c:445
#23 0x00000000007117c1 in ExecProcNode (node=0x2b3fb30) at ../../../src/include/executor/executor.h:239
#24 0x0000000000714031 in ExecutePlan (estate=0x2b3f8d8, planstate=0x2b3fb30, use_parallel_mode=false, operation=CMD_SELECT, sendTuples=true,
    numberTuples=0, direction=ForwardScanDirection, dest=0xce47e0 <spi_printtupDR>, execute_once=true) at execMain.c:1646
#25 0x0000000000711dfe in standard_ExecutorRun (queryDesc=0x2b4a1a8, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:364
#26 0x00007f3230e656ef in CitusExecutorRun (queryDesc=0x2b4a1a8, direction=ForwardScanDirection, count=0, execute_once=true) at executor/multi_executor.c:177
#27 0x0000000000711c21 in ExecutorRun (queryDesc=0x2b4a1a8, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:306
#28 0x000000000076757a in _SPI_pquery (queryDesc=0x2b4a1a8, fire_triggers=true, tcount=0) at spi.c:2521
#29 0x0000000000766fb2 in _SPI_execute_plan (plan=0x2b46d38, paramLI=0x2ac8840, snapshot=0x0, crosscheck_snapshot=0x0, read_only=false, fire_triggers=true,
    tcount=0) at spi.c:2296
#30 0x0000000000763c8d in SPI_execute_plan_with_paramlist (plan=0x2b46d38, params=0x2ac8840, read_only=false, tcount=0) at spi.c:577
#31 0x00007f32215cec3f in exec_run_select (estate=0x7ffdeeb85010, expr=0x2ad0c00, maxtuples=0, portalP=0x0) at pl_exec.c:5878
#32 0x00007f32215c6f7f in exec_stmt_perform (estate=0x7ffdeeb85010, stmt=0x2ad0d30) at pl_exec.c:2109
#33 0x00007f32215c6b8d in exec_stmt (estate=0x7ffdeeb85010, stmt=0x2ad0d30) at pl_exec.c:1965
#34 0x00007f32215c6a5a in exec_stmts (estate=0x7ffdeeb85010, stmts=0x2ad0818) at pl_exec.c:1924
#35 0x00007f32215cef6d in exec_for_query (estate=0x7ffdeeb85010, stmt=0x2ad0180, portal=0x29e21f0, prefetch_ok=true) at pl_exec.c:6007
#36 0x00007f32215c87a5 in exec_stmt_fors (estate=0x7ffdeeb85010, stmt=0x2ad0180) at pl_exec.c:2791
#37 0x00007f32215c6c65 in exec_stmt (estate=0x7ffdeeb85010, stmt=0x2ad0180) at pl_exec.c:1997
#38 0x00007f32215c6a5a in exec_stmts (estate=0x7ffdeeb85010, stmts=0x2acfe20) at pl_exec.c:1924
#39 0x00007f32215c68f5 in exec_stmt_block (estate=0x7ffdeeb85010, block=0x2ad1fa8) at pl_exec.c:1865
#40 0x00007f32215c6b57 in exec_stmt (estate=0x7ffdeeb85010, stmt=0x2ad1fa8) at pl_exec.c:1957
#41 0x00007f32215c524d in plpgsql_exec_event_trigger (func=0x29f27e8, trigdata=0x7ffdeeb85500) at pl_exec.c:1166
#42 0x00007f32215be0e4 in plpgsql_call_handler (fcinfo=0x7ffdeeb85490) at pl_handler.c:262
#43 0x0000000000abdba6 in fmgr_security_definer (fcinfo=0x7ffdeeb85490) at fmgr.c:748
#44 0x0000000000672deb in EventTriggerInvoke (fn_oid_list=0x2a926b0, trigdata=0x7ffdeeb85500) at event_trigger.c:1082
#45 0x0000000000672a31 in EventTriggerSQLDrop (parsetree=0x2a83590) at event_trigger.c:935
#46 0x000000000092c642 in ProcessUtilitySlow (pstate=0x2b11c60, pstmt=0x2a834f8, queryString=0x29141e8 "drop table ref_table cascade;",
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x2915148, completionTag=0x7ffdeeb86120 "") at utility.c:1711
#47 0x000000000092a913 in standard_ProcessUtility (pstmt=0x2a834f8, queryString=0x29141e8 "drop table ref_table cascade;", context=PROCESS_UTILITY_TOPLEVEL,
    params=0x0, queryEnv=0x0, dest=0x2915148, completionTag=0x7ffdeeb86120 "") at utility.c:839
#48 0x00007f3230e394a9 in multi_ProcessUtility (pstmt=0x2a834f8, queryString=0x29141e8 "drop table ref_table cascade;", context=PROCESS_UTILITY_TOPLEVEL,
    params=0x0, queryEnv=0x0, dest=0x2915148, completionTag=0x7ffdeeb86120 "") at commands/utility_hook.c:484
#49 0x0000000000929bf2 in ProcessUtility (pstmt=0x2915050, queryString=0x29141e8 "drop table ref_table cascade;", context=PROCESS_UTILITY_TOPLEVEL,
    params=0x0, queryEnv=0x0, dest=0x2915148, completionTag=0x7ffdeeb86120 "") at utility.c:356
#50 0x0000000000928bb4 in PortalRunUtility (portal=0x29e20d8, pstmt=0x2915050, isTopLevel=true, setHoldSnapshot=false, dest=0x2915148,
    completionTag=0x7ffdeeb86120 "") at pquery.c:1175
#51 0x0000000000928dd0 in PortalRunMulti (portal=0x29e20d8, isTopLevel=true, setHoldSnapshot=false, dest=0x2915148, altdest=0x2915148,
    completionTag=0x7ffdeeb86120 "") at pquery.c:1321
#52 0x0000000000928279 in PortalRun (portal=0x29e20d8, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x2915148, altdest=0x2915148,
    completionTag=0x7ffdeeb86120 "") at pquery.c:796
#53 0x0000000000921c71 in exec_simple_query (query_string=0x29141e8 "drop table ref_table cascade;") at postgres.c:1215
#54 0x0000000000926290 in PostgresMain (argc=1, argv=0x29aa190, dbname=0x29a9fd0 "onurctirtir", username=0x29a9fa8 "onurctirtir") at postgres.c:4236
#55 0x0000000000874816 in BackendRun (port=0x29a09d0) at postmaster.c:4437
#56 0x0000000000873f77 in BackendStartup (port=0x29a09d0) at postmaster.c:4128
#57 0x00000000008700ee in ServerLoop () at postmaster.c:1704
#58 0x000000000086f8fc in PostmasterMain (argc=5, argv=0x290ed50) at postmaster.c:1377
#59 0x00000000007882ca in main (argc=5, argv=0x290ed50) at main.c:228
```

### PR DESCRIPTION
**Pull request by onurctirtir**
DESCRIPTION:  Fix null relation name due to DROP on distributed table in a transaction block

Fixes #3520

### CODE REVIEW

File: src/backend/distributed/transaction/relation_access_tracking.c [hunk 1]
```diff
@@ -713,14 +713,37 @@ CheckConflictingRelationAccesses(Oid relationId, ShardPlacementAccessType access
...
+		/*
+		 * Relation could already be dropped if the accessType is DDL and the
+		 * command that we were executing were a DROP command. In that case,
+		 * as this function is executed via DROP trigger, standard_ProcessUtility
+		 * had already dropped the table from PostgreSQL's perspective. Hence, it
+		 * returns NULL pointer for the name of the relation.
+		 */
+		if (relationName == NULL)
+		{
+			ereport(ERROR, (errmsg("cannot execute %s on reference relation because "
```
Comment (marcocitus) [inline src/backend/distributed/transaction/relation_access_tracking.c]: Optional: Might be nice to change relation into table in these messages just for consistency with things like create_reference_table.

Comment (onurctirtir) [reply src/backend/distributed/transaction/relation_access_tracking.c]: done in #926a1a6
