### PR TITLE
citus_evaluate_expression: call expand_function_arguments beforehand to avoid segfaulting on implicit parameters

### LINKED ISSUE #3939: Functions with default values
When we have a function with a default parameter and we don't give the default parameter, it seems that in the expression on the executor part, when calling the citus_evaluate_expr function, we don't have the default values in the expression. This seems to cause unexpected things, for example:

```sql
create table text_table(name text);
select create_distributed_table('text_table', 'name');
CREATE OR REPLACE FUNCTION f(theValue integer, k text DEFAULT 'gg')
    RETURNS text AS
$$
BEGIN
    RETURN k;
END;
$$
LANGUAGE 'plpgsql' IMMUTABLE;

insert into text_table values ( f (10, 'z') ); -- works fine

[local] talha@talha:9700-562=# insert into text_table values ( f (10) );
DEBUG:  Creating router plan
DEBUG:  Plan is router executable
ERROR:  cannot perform an INSERT with NULL in the partition column
Time: 0.469 ms

```

So when we don't have the default value in the expression `fcinfo->args` it is not certain what will happen. For example with pg13 there is a function `normalize` which has an optional parameter and the handler function crashes when the default value is not sent. 

the expression has the default value in the planner stage but not in the execution stage.

This happens with `pg12` and `master` branch.

### PR DESCRIPTION
**Pull request by serprex**
DESCRIPTION: Fix segfault when evaluating function calls with default parameters on coordinator

Fix #3939

### CODE REVIEW

File: src/backend/distributed/utils/citus_clauses.c [hunk 1]
```diff
@@ -452,3 +461,40 @@ CitusIsMutableFunction(Node *node)
...
+/* FixFunctionArgumentsWalker is the helper function for fix_funcargs. */
+static bool
+FixFunctionArgumentsWalker(Node *expr, void *context)
+{
+	if (expr == NULL)
+	{
+		return false;
+	}
+
+	if (IsA(expr, FuncExpr))
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/utils/citus_clauses.c:483]: Would it make sense to put this if check inside at the beginning of `PartiallyEvaluateExpression` so that we dont traverse the tree multiple times?

Comment (serprex) [reply src/backend/distributed/utils/citus_clauses.c:483]: The function call could be deeper than the initial node of `PartiallyEvaluateExpression`

For example, returning `funcExpr` in this `if` rather than continuing to recurse causes the `f(f())` test to segfault

Comment (SaitTalhaNisanci) [reply src/backend/distributed/utils/citus_clauses.c:483]: um, so in that case we would handle the first node but the following parts could be going deeper than that and in that case they might encounter nodes with default values not yet evaluated, which might cause the crash.

File: src/backend/distributed/utils/citus_clauses.c [hunk 2]
```diff
@@ -452,3 +461,40 @@ CitusIsMutableFunction(Node *node)
...
+	{
+		FuncExpr *funcExpr = castNode(FuncExpr, expr);
+		HeapTuple func_tuple =
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/utils/citus_clauses.c:486]: For other readers:

https://github.com/postgres/postgres/blob/master/src/backend/optimizer/util/clauses.c#L2427-L2434

File: src/backend/distributed/utils/citus_clauses.c [hunk 3]
```diff
@@ -452,3 +461,40 @@ CitusIsMutableFunction(Node *node)
 
 	return false;
 }
+
+
+/* FixFunctionArguments applies expand_function_arguments to all function calls. */
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/utils/citus_clauses.c:466]: Maybe:

`FixFunctionArguments converts named-notation args to positional args
 and/or inserts default args, as needed in all function calls in the expr node tree.`

File: src/backend/distributed/utils/citus_clauses.c [hunk 4]
```diff
@@ -304,6 +310,9 @@ citus_evaluate_expr(Expr *expr, Oid result_type, int32 result_typmod,
 	/* We can use the estate's working context to avoid memory leaks. */
 	MemoryContext oldcontext = MemoryContextSwitchTo(estate->es_query_cxt);
 
+	/* handles default values */
+	FixFunctionArguments((Node *) expr);
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/utils/citus_clauses.c:314]: Could this cause a problem in other parts as well? If so should we call this method in `PartiallyEvaluateExpression`?

Comment (serprex) [reply src/backend/distributed/utils/citus_clauses.c:314]: No, we don't call `fix_opfuncids` anywhere else either, as this is the only code path to `ExecEvalExprSwitchContext`
