### PR TITLE
Fix COPY TO's COPY (SELECT) with distributed table having generated columns

### LINKED ISSUE #3792: COPY into distributed tables should ignore `generated always` columns
Otherwise, Citus fails whereas Postgres can properly handles it.

```SQL
create table users (
    id bigserial
  , name text
  , created_at timestamptz default now()
  , country_id int
  , score bigint generated always as (id + country_id) stored
);


-- ingest some datat
INSERT INTO users (name, country_id) VALUES ('onder', 1);
INSERT 0 1
INSERT INTO users (name, country_id) VALUES ('nils', 2);
INSERT 0 1
INSERT INTO users (name, country_id) VALUES ('marco', 3);
INSERT 0 1


-- copy in & out on Postgres
COPY users TO '/tmp/data.csv' WITH CSV;
COPY 3
COPY users FROM '/tmp/data.csv' WITH CSV;
COPY 3

SELECT * FROM users;
┌────┬───────┬───────────────────────────────┬────────────┬───────┐
│ id │ name  │          created_at           │ country_id │ score │
├────┼───────┼───────────────────────────────┼────────────┼───────┤
│  1 │ onder │ 2020-04-23 09:14:54.235014+02 │          1 │     2 │
│  2 │ nils  │ 2020-04-23 09:14:54.238569+02 │          2 │     4 │
│  3 │ marco │ 2020-04-23 09:14:54.239817+02 │          3 │     6 │
│  1 │ onder │ 2020-04-23 09:14:54.235014+02 │          1 │     2 │
│  2 │ nils  │ 2020-04-23 09:14:54.238569+02 │          2 │     4 │
│  3 │ marco │ 2020-04-23 09:14:54.239817+02 │          3 │     6 │
└────┴───────┴───────────────────────────────┴────────────┴───────┘
(6 rows)

-- distribute table & do the same
select create_distributed_table('users', 'id');
NOTICE:  Copying data from local table...
NOTICE:  copying the data has completed
DETAIL:  The local data in the table is longer visible, but is still on disk.
HINT:  To remove the local data, run: SELECT truncate_local_data_after_distributing_table($$bug.users$$)
┌──────────────────────────┐
│ create_distributed_table │
├──────────────────────────┤
│                          │
└──────────────────────────┘
(1 row)

COPY users TO '/tmp/data.csv' WITH CSV;
COPY 6
COPY users FROM '/tmp/data.csv' WITH CSV;ERROR:  extra data after last expected column
CONTEXT:  COPY users, line 1: "1,onder,2020-04-23 09:14:54.235014+02,1,2"
Time: 2.509 ms
```

### PR DESCRIPTION
**Pull request by serprex**
It's necessary to omit generated columns from output

Changes `CopyGetAttnums` aren't really necessary, but updates code to match upstream

DESCRIPTION: Fix `COPY distributed_table TO 'file'` when table contains generated columns

Fixes #3792

### CODE REVIEW

File: src/backend/distributed/commands/multi_copy.c [hunk 1]
```diff
@@ -2762,19 +2762,87 @@ ProcessCopyStmt(CopyStmt *copyStatement, char *completionTag, const char *queryS
...
+					if (attr->attgenerated)
+					{
+						hasGeneratedColumns = true;
+						break;
+					}
+				}
+
+				if (hasGeneratedColumns)
+				{
+					for (int i = 0; i < tupleDescriptor->natts; i++)
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/commands/multi_copy.c:2791]: I think this function is already big, Maybe we can use functions for this if/else blocks?

File: src/backend/distributed/commands/multi_copy.c [hunk 2]
```diff
@@ -2762,19 +2762,87 @@ ProcessCopyStmt(CopyStmt *copyStatement, char *completionTag, const char *queryS
 				 * COPY table TO PROGRAM / file is handled by wrapping the table
 				 * in a SELECT * FROM table and going through the result COPY logic.
```
Comment (serprex) [inline src/backend/distributed/commands/multi_copy.c:2763]: update comment to not claim `SELECT *` is the be all end all

File: src/backend/distributed/commands/multi_copy.c [hunk 3]
```diff
@@ -2762,19 +2762,87 @@ ProcessCopyStmt(CopyStmt *copyStatement, char *completionTag, const char *queryS
...
+					allColumns->location = -1;
+
+					ResTarget *selectTarget = makeNode(ResTarget);
+					selectTarget->name = NULL;
+					selectTarget->indirection = NIL;
+					selectTarget->val = (Node *) allColumns;
+					selectTarget->location = -1;
+
+					selectStmt->targetList = list_make1(selectTarget);
+				}
```
Comment (thanodnl) [inline src/backend/distributed/commands/multi_copy.c:2829]: Is there a performance benefit of having this special codepath that selects all columns, instead of _always_ creating the select targetlist by skipping deleted and generated columns?

If there is no performance gain at runtime I think it makes a lot of sense to remove this block. This would also remove the first iteration through the attributes to check if there is a generated column.

Lastly it could isolate the pg12 specific code to the `attr->attgenerated` check.
Now there is a lot of different codepaths to understand depending on pg11/pg12 and having generated columns vs not having generated columns.

Having 1 flow of selecting every column but skip deleted columns, and for pg12 skip generated columns as well will be easier to maintain and understand IMHO.

File: src/backend/distributed/commands/multi_copy.c [hunk 4]
```diff
@@ -3085,6 +3157,14 @@ CopyGetAttnums(TupleDesc tupDesc, Relation rel, List *attnamelist)
 					continue;
 				if (namestrcmp(&(att->attname), name) == 0)
 				{
+#if PG_VERSION_NUM >= PG_VERSION_12
+					if (att->attgenerated)
+						ereport(ERROR,
+								(errcode(ERRCODE_INVALID_COLUMN_REFERENCE),
+								 errmsg("column \"%s\" is a generated column",
+										name),
+								 errdetail("Generated columns cannot be used in COPY.")));
```
Comment (thanodnl) [inline src/backend/distributed/commands/multi_copy.c:3166]: This seems to not be covered in the tests.

Does vanilla postgres support this? What would it entail for use to support it?

Comment (serprex) [reply src/backend/distributed/commands/multi_copy.c:3166]: This is copied from vanilla postgres

**Comment by metdos** [comment]
@serprex thank you for the fix, could you also cherry-pick this to release-9.3 branches on both community and enterprise?
