### PR TITLE
Fixes column default coming from a sequence

### LINKED ISSUE #3884: Cannot create citus table if column defaults to a user created sequence in MX
If we have a table which has a column defaulting to a sequence created by `CREATE SEQUENCE` command, we get the following as we don't propagate sequences to worker nodes by default.

Along with the problem defined by the title of the issue, same problem also occurs when we try to sync metadata to a worker node after creating such a citus table. An example with reference tables:

```sql
CREATE SEQUENCE sequence;
CREATE TABLE reference_table (a int default nextval('sequence'));
SELECT create_reference_table('reference_table');
SELECT start_metadata_sync_to_node('localhost', 9701);
ERROR:  relation "public.sequence" does not exist
CONTEXT:  while executing command on localhost:9701
```

### LINKED ISSUE #4721: Alter distributed table add column bigserial/sequence fails
It seems that we cannot add a new column with a bigserial or a bigint that depends on a sequence even though we can use them at table creation. The workaround is to disable ddl propagation but we should fix this. 

```sql
CREATE SEQUENCE table_id_seq;
CREATE TABLE tbl (a int);
SELECT create_distributed_table('tbl','a');
 ALTER TABLE tbl ADD COLUMN _id BIGINT DEFAULT nextval('table_id_seq');
 ERROR:  relation "table_id_seq" does not exist
 CONTEXT:  while executing command on 10.0.98.206:5432
```

### PR DESCRIPTION
**Pull request by naisila**
DESCRIPTION: Fixes column default coming from a sequence

TODO:

* `create_distribute_table` fixes
- [x] Support user-defined sequences in column defaults of an MX table
- [x] Mark sequence as distributed and propagate `DROP SEQUENCE`
- [x] Check INSERT .. SELECT when it includes a `DEFAULT nextval(...)` column _in progress_

* `ALTER TABLE` fixes
    * `ALTER TABLE ADD COLUMN ... DEFAULT nextval('myseq')`
    * `ALTER TABLE ALTER COLUMN ... SET DEFAULT nextval('myseq')`
    * `ALTER TABLE ADD COLUMN serial_prototype`
- [x] Remove the sequence part when propagating command to shards
- [x] Distribute the sequence in case of MX-table: it doesn't work with serials either
* Also:
- [x] Add tests

Fixes #4721 
Fixes #3884

### CODE REVIEW

File: src/backend/distributed/metadata/metadata_sync.c [hunk 1]
```diff
@@ -537,6 +551,11 @@ GetDistributedTableDDLEvents(Oid relationId)
 		List *sequenceDDLCommands = SequenceDDLCommandsForTable(relationId);
 		commandList = list_concat(commandList, sequenceDDLCommands);
 
+		/* commands to create user-defined functions appearing in DEFAULT values of a column */
+		List *functionDDLCommands = FunctionDDLCommandsForColumnDefaultsOfTable(
+			relationId);
+		commandList = list_concat(commandList, functionDDLCommands);
```
Comment (marcocitus) [inline src/backend/distributed/metadata/metadata_sync.c:557]: For sequences, extending the metadata syncing logic makes sense to me given that we only ever need to propagate them to workers when using metadata syncing and we have special logic to handle sequences which is different from how we handle all other objects. 

For functions, things are a little fuzzier since the function can also be used in other ways (e.g. queries). We normally propagate functions via the object propagation logic after calling create_distributed_function. It seems kind of odd to have another way of propagating functions here that behaves differently. For instance, we normally propagate CREATE OR REPLACE FUNCTION to the workers via object propagation, but we wouldn't do that if the function was propagated via metadata syncing.

Maybe we leave functions out-of-scope for this PR? We can say that we currently require users to call create_distributed_function if they call a function on the DEFAULT and use metadata syncing.

Comment (naisila) [reply src/backend/distributed/metadata/metadata_sync.c:557]: So, for functions, can we do the following for now, for both `create_distributed_table` and `ALTER TABLE ALTER/ADD COLUMN`:
- for non-MX tables, remove the "DEFAULT function_call()" when creating the table shards
- for MX tables, error out and suggest the user to distribute the function first

**Comment by onurctirtir** [comment]
Does this pr also fix https://github.com/citusdata/citus/issues/3884 ?

**Comment by naisila** [comment]
@onurctirtir Yes it does 👍

File: src/backend/distributed/commands/table.c [hunk 2]
```diff
@@ -1469,6 +1618,31 @@ PostprocessAlterTableStmt(AlterTableStmt *alterTableStatement)
...
 	}
+
+	/* for the new sequences coming with this ALTER TABLE statement */
+	if (ShouldSyncTableMetadata(relationId))
+	{
+		List *sequenceCommandList = NIL;
+
+		/* if the table is owned by an extension we only propagate pg_dist_* records */
+		bool tableOwnedByExtension = IsTableOwnedByExtension(relationId);
+		if (!tableOwnedByExtension)
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:1629]: Not sure we should have this check here. Normally we do this to support calling create_distributed_table on a table owned by an extension, which means we should not attempt to create the table on the workers since it would have already come from the extension. If you then attempt to alter the table, I guess we should do it everywhere.

File: src/backend/distributed/metadata/metadata_sync.c (hunk 1 above)
Comment (marcocitus) [reply src/backend/distributed/metadata/metadata_sync.c]: > for MX tables, error out and suggest the user to distribute the function first

makes sense, we currently use separate connections for metadata syncing and function propagation, so it is hard to reconcile these.

File: src/backend/distributed/commands/table.c [hunk 3]
```diff
@@ -666,6 +705,107 @@ PreprocessAlterTableStmt(Node *node, const char *alterTableCommand,
...
+		 * we should not propagate anything to shards
+		 */
+		else if (alterTableType == AT_ColumnDefault)
+		{
+			ParseState *pstate = make_parsestate(NULL);
+			Node *expr = transformExpr(pstate, command->def,
+									   EXPR_KIND_COLUMN_DEFAULT);
+
+			if (contain_nextval_expression_walker(expr, NULL) || contain_funcexpr_walker(
+					expr, NULL))
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:805]: > contain_funcexpr_walker

One thing to note is that we do include `DEFAULT function_call()` when creating shards during `create_distributed_table`. I wonder whether we should propagate it to be consistent. On the other hand, I don't know whether there is ever a case in which we use it.

It's worth noting that functions in Postgres can be volatile, stable or immutable, and they have different behaviour. E.g. INSERT..SELECT does different things for each.

File: src/backend/distributed/commands/table.c [hunk 4]
```diff
@@ -1469,6 +1621,26 @@ PostprocessAlterTableStmt(AlterTableStmt *alterTableStatement)
...
+	if (ShouldSyncTableMetadata(relationId))
+	{
+		List *sequenceCommandList = NIL;
+
+		/* commands to create sequences */
+		List *sequenceDDLCommands = SequenceDDLCommandsForTable(relationId);
+		sequenceCommandList = list_concat(sequenceCommandList, sequenceDDLCommands);
+
+		/* prevent recursive propagation */
+		SendCommandToWorkersWithMetadata(DISABLE_DDL_PROPAGATION);
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:1635]: we usually need to re-enable it. 

It could also be nice to add it to the list.

File: src/backend/distributed/commands/table.c [hunk 5]
```diff
@@ -1736,18 +1908,110 @@ ErrorIfUnsupportedAlterTableStmt(AlterTableStmt *alterTableStatement)
...
+							/*
+							 * We currently don't support adding a serial column for an MX table
+							 * TODO: record the dependency in the workers
+							 */
+							if (ShouldSyncTableMetadata(relationId))
+							{
+								ereport(ERROR, (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
+												errmsg(
+													"cannot execute ADD COLUMN commands "
+													"involving serial pseudotypes with MX tables")));
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:1935]: we don't talk about MX in any error messages so far, maybe "when metadata is synchronized to workers"?

File: src/backend/distributed/commands/table.c [hunk 6]
```diff
@@ -1736,18 +1908,110 @@ ErrorIfUnsupportedAlterTableStmt(AlterTableStmt *alterTableStatement)
...
+									 * if its the only subcommand and has no other constraints
+									 */
+									if (commandList->length > 1 ||
+										columnConstraints->length > 1)
+									{
+										ereport(ERROR, (errcode(
+															ERRCODE_FEATURE_NOT_SUPPORTED),
+														errmsg(
+															"cannot execute ADD COLUMN .. DEFAULT non_const"
+															" command with other subcommands/constraints"),
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:1967]: do we ever support subcommands?

File: src/backend/distributed/metadata/metadata_sync.c (hunk 1 above)
Comment (marcocitus) [reply src/backend/distributed/metadata/metadata_sync.c]: > for MX tables, error out and suggest the user to distribute the function first

thinking about this more: does this recreate the situation where things fail when we start syncing metadata?

if so, we should force the user to *always* distribute the function first, even for non-MX.

File: src/backend/distributed/commands/table.c (hunk 6 above)
Comment (naisila) [reply src/backend/distributed/commands/table.c:1967]: We check this for different cases
https://github.com/citusdata/citus/blob/master/src/backend/distributed/commands/table.c#L1767
https://github.com/citusdata/citus/blob/master/src/backend/distributed/commands/table.c#L1797

So I added a check for this PR's cases as well

File: src/backend/distributed/commands/table.c (hunk 3 above)
Comment (naisila) [reply src/backend/distributed/commands/table.c:805]: I have included this `contain_funcexpr_walker` check during `create_distributed_table` as well, but as discussed, I will not keep the function changes in this PR but rather address them later in another one. Thanks.

File: src/backend/distributed/commands/table.c (hunk 4 above)
Comment (marcocitus) [reply src/backend/distributed/commands/table.c:1635]: ping

File: src/backend/distributed/commands/table.c [hunk 7]
```diff
@@ -574,24 +579,60 @@ PreprocessAlterTableStmt(Node *node, const char *alterTableCommand,
...
+	 *    NOT NULL constraint.
 	 */
 	List *commandList = alterTableStatement->cmds;
 
+	/*
+	 * if deparsing is needed, we will use a different version of the original
+	 * alterTableStmt
+	 */
+	bool deparseAT = false;
+	bool doNothing = false;
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:613]: is there a more descriptive name for doNothing? 

It's usually also better to avoid negations in names, so maybe "propagateCommandToWorkers = true"?

**Review by marcocitus — COMMENTED** [review]
Strange error:
```sql
create sequence foo;
create table test (x int, y int);
select create_distributed_table('test','x');
insert into test select 1, s from generate_series(1,50) s;
alter table test add column z int default nextval('foo');
ERROR:  column "z" of relation "test_102251" contains null values
CONTEXT:  while executing command on localhost:1301
```

**Comment by marcocitus** [comment]
On coordinator:
```
create sequence foo;
create table test (x int, y int);
select create_distributed_table('test','x');
alter table test add column z int default nextval('foo');
```

On worker:
```
insert into test values (1,2);
ERROR:  integer out of range
```

**Comment by marcocitus** [comment]
It seems we also throw this error when metadata is *not* synced:
```
alter table test add column z bigserial;
ERROR:  cannot execute ADD COLUMN commands involving serial pseudotypes when metadata is synchronized to workers
```

**Review by marcocitus — CHANGES_REQUESTED** [review]
Minor observation: we should also start propagating GRANT ... ON SEQUENCE soon-ish (not this PR).

**Comment by naisila** [comment]
> It seems we also throw this error when metadata is _not_ synced:
> 
> ```
> alter table test add column z bigserial;
> ERROR:  cannot execute ADD COLUMN commands involving serial pseudotypes when metadata is synchronized to workers
> ```

@marcocitus This error should appear only when `ShouldSyncTableMetadata(relationId)` returns true. Can you give more error context: what is the case in which the function returned true but metadata was not synced?

**Comment by naisila** [comment]
> On coordinator:
> 
> ```sql
> create sequence foo;
> create table test (x int, y int);
> select create_distributed_table('test','x');
> alter table test add column z int default nextval('foo');
> ```
> 
> On worker:
> 
> ```sql
> insert into test values (1,2);
> ERROR:  integer out of range
> ```

@marcocitus It seems that for a user-defined sequence the default type is `bigint`, and the min/max boundaries in the workers are always set according to `bigint`. I should change the sequence's type before propagation, currently working on that. Thanks for noticing.

**Comment by marcocitus** [comment]
> his error should appear only when ShouldSyncTableMetadata(relationId) returns true. Can you give more error context: what is the case in which the function returned true but metadata was not synced?

ShouldSyncTableMetadata does not check whether metadata is actually synced to any node, just whether the table meets the criteria.

**Comment by naisila** [comment]
> > his error should appear only when ShouldSyncTableMetadata(relationId) returns true. Can you give more error context: what is the case in which the function returned true but metadata was not synced?
> 
> ShouldSyncTableMetadata does not check whether metadata is actually synced to any node, just whether the table meets the criteria.

@marcocitus Is an extra check of `ClusterHasKnownMetadataWorkers()` enough?

**Comment by marcocitus** [comment]
> @marcocitus Is an extra check of ClusterHasKnownMetadataWorkers() enough?

I think so

**Comment by marcocitus** [comment]
We may run into some issues due to some operations happening as superuser and some as current user
```sql
$ psql -U foo
begin;
create sequence seqfoo;
alter table test add column sfoo bigint default nextval('seqfoo');
alter sequence seqfoo rename to myseq;
ERROR:  relation "public.seqfoo" does not exist
CONTEXT:  while executing command on localhost:1301
```
This is expected due to #3398

**Comment by marcocitus** [comment]
I don't see `alter sequence seqfoo owner to foo;` getting propagated if I enable citus.log_remote_commands.

**Review by marcocitus — COMMENTED** [review]
Strange error:
```sql
select start_metadata_sync_to_node(nodename, nodeport) from pg_dist_node;
create sequence seq;
create table test (x int, y bigint default nextval('seq'));
select create_distributed_table('test','x');
drop table test;
create table test (x int, y int default nextval('seq'));
select create_distributed_table('test','x');
drop table test;
create table test (x int, y bigint default nextval('seq'));
select create_distributed_table('test','x');
ERROR:  This operation is currently not allowed for a distributed sequence.
CONTEXT:  SQL statement "ALTER SEQUENCE public.seq AS bigint"
```
```sql
select start_metadata_sync_to_node(nodename, nodeport) from pg_dist_node;
create sequence seq;
create table test (x int, y int default nextval('seq'), z bigint default nextval('seq'));
select create_distributed_table('test','x');
ERROR:  This operation is currently not allowed for a distributed sequence.
CONTEXT:  SQL statement "ALTER SEQUENCE public.seq AS bigint"
```

File: src/backend/distributed/commands/table.c [hunk 8]
```diff
@@ -574,24 +579,53 @@ PreprocessAlterTableStmt(Node *node, const char *alterTableCommand,
 		ErrorIfUnsupportedAlterTableStmt(alterTableStatement);
 	}
 
+	if (ShouldSyncTableMetadata(leftRelationId))
+	{
+		EnsureCoordinator();
+	}
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:585]: What is this for? Does this affect anything else?

File: src/backend/distributed/commands/sequence.c [hunk 9]
```diff
@@ -209,3 +207,394 @@ ExtractDefaultColumnsAndOwnedSequences(Oid relationId, List **columnNameList,
...
+/*
+ * PreprocessRenameSequenceStmt is called when the user is renaming a sequence. The invocation
+ * happens before the statement is applied locally.
+ *
+ * As the sequence already exists we have access to the ObjectAddress, this is used to
+ * check if it is distributed. If so the rename is executed on all the workers to keep the
+ * types in sync across the cluster.
+ */
+List *
+PreprocessRenameSequenceStmt(Node *node, const char *queryString,
```
Comment (marcocitus) [inline src/backend/distributed/commands/sequence.c:373]: A lot of the code here seems uncovered by tests.

File: src/include/distributed/metadata_utility.h [hunk 10]
```diff
@@ -30,7 +30,7 @@
 
 /* total number of hash tokens (2^32) */
 #define HASH_TOKEN_COUNT INT64CONST(4294967296)
-#define SELECT_EXIST_QUERY "SELECT EXISTS (SELECT 1 FROM %s)"
+#define SELECT_EXIST_QUERY "SELECT EXISTS (SELECT TRUE FROM %s LIMIT 1)"
```
Comment (marcocitus) [inline src/include/distributed/metadata_utility.h:33]: maybe remove the `SELECT EXISTS (`. Otherwise, this query still does some extra steps.

**Comment by naisila** [comment]
> I don't see `alter sequence seqfoo owner to foo;` getting propagated if I enable citus.log_remote_commands.

Removing ALTER SEQUENCE propagation from this PR.

**Comment by naisila** [comment]
> Strange error:
> 
> ```sql
> select start_metadata_sync_to_node(nodename, nodeport) from pg_dist_node;
> create sequence seq;
> create table test (x int, y bigint default nextval('seq'));
> select create_distributed_table('test','x');
> drop table test;
> create table test (x int, y int default nextval('seq'));
> select create_distributed_table('test','x');
> drop table test;
> create table test (x int, y bigint default nextval('seq'));
> select create_distributed_table('test','x');
> ERROR:  This operation is currently not allowed for a distributed sequence.
> CONTEXT:  SQL statement "ALTER SEQUENCE public.seq AS bigint"
> ```
> 
> ```sql
> select start_metadata_sync_to_node(nodename, nodeport) from pg_dist_node;
> create sequence seq;
> create table test (x int, y int default nextval('seq'), z bigint default nextval('seq'));
> select create_distributed_table('test','x');
> ERROR:  This operation is currently not allowed for a distributed sequence.
> CONTEXT:  SQL statement "ALTER SEQUENCE public.seq AS bigint"
> ```

As discussed, currently fixed by ensuring that commands that try to use a sequence with a different type error out, both for `create_distributed_table` and `ALTER TABLE` commands

File: src/backend/distributed/commands/table.c (hunk 8 above)
Comment (naisila) [reply src/backend/distributed/commands/table.c:585]: Shouldn't that be the case since in postprocess if MX we send commands to worker nodes?

File: src/backend/distributed/commands/distribute_object_ops.c [hunk 11]
```diff
@@ -967,6 +986,11 @@ GetDistributeObjectOps(Node *node)
 					return &Schema_Rename;
 				}
 
+				case OBJECT_SEQUENCE:
+				{
+					return &Sequence_Rename;
```
Comment (marcocitus) [inline src/backend/distributed/commands/distribute_object_ops.c:991]: we'll need some rename tests to cover this line

File: src/backend/distributed/commands/table.c [hunk 12]
```diff
@@ -666,6 +697,95 @@ PreprocessAlterTableStmt(Node *node, const char *alterTableCommand,
...
+					{
+						ParseState *pstate = make_parsestate(NULL);
+						Node *expr = transformExpr(pstate, constraint->raw_expr,
+												   EXPR_KIND_COLUMN_DEFAULT);
+
+						if (contain_nextval_expression_walker(expr, NULL))
+						{
+							deparseAT = true;
+
+							ColumnDef *newColDef = copyObject(columnDefinition);
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:721]: Could use a comment on why we do this

File: src/backend/distributed/commands/table.c [hunk 13]
```diff
@@ -666,6 +697,95 @@ PreprocessAlterTableStmt(Node *node, const char *alterTableCommand,
...
+					deparseAT = true;
+
+					ColumnDef *newColDef = copyObject(columnDefinition);
+					newColDef->is_not_null = false;
+
+					if (strcmp(typeName, "smallserial") == 0 ||
+						strcmp(typeName, "serial2") == 0)
+					{
+						newColDef->typeName->names = NIL;
+						newColDef->typeName->typeOid = INT2OID;
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:757]: uncovered line, needs some tests

File: src/backend/distributed/metadata/metadata_sync.c [hunk 14]
```diff
@@ -1067,12 +1102,178 @@ SequenceDDLCommandsForTable(Oid relationId)
...
+	SysScanDesc scan = systable_beginscan(depRel, DependDependerIndexId, true,
+										  NULL, 2, key);
+
+	while (HeapTupleIsValid(tup = systable_getnext(scan)))
+	{
+		Form_pg_depend deprec = (Form_pg_depend) GETSTRUCT(tup);
+
+		if (deprec->refclassid == RelationRelationId &&
+			deprec->deptype == DEPENDENCY_NORMAL && get_rel_relkind(
+				deprec->refobjid) == RELKIND_SEQUENCE)
```
Comment (marcocitus) [inline src/backend/distributed/metadata/metadata_sync.c:1263]: slightly odd alignment

**Review by marcocitus — COMMENTED** [review]
Some minor comments, code looks good overall.

**Comment by marcocitus** [comment]
This scenario seems unexpected to me. It's like we don't reset the range if we recreate the sequence after dropping it.

on coordinator:
```sql
create table test (x int, y int);
select create_distributed_table('test','x');
create sequence seq;
alter table test add column a int default nextval('seq');
select start_metadata_sync_to_node(nodename, nodeport) from pg_dist_node;
```

on worker -- high sequence number generated as expected:
```sql
insert into test values (1,2);
NOTICE:  executing the command locally: INSERT INTO public.test_102051 (x, y, a) VALUES (1, 2, 268435458)
INSERT 0 1
```

on coordinator:
```sql
drop sequence seq cascade;
truncate test;
create sequence seq;
alter table test add column b int default nextval('seq');
```

on worker -- sequence number starts at 1:
```sql
insert into test values (1,2);
NOTICE:  executing the command locally: INSERT INTO public.test_102051 (x, y, b) VALUES (1, 2, 1)
INSERT 0 1
insert into test values (1,2);
NOTICE:  executing the command locally: INSERT INTO public.test_102051 (x, y, b) VALUES (1, 2, 2)
INSERT 0 1
insert into test values (1,2);
NOTICE:  executing the command locally: INSERT INTO public.test_102051 (x, y, b) VALUES (1, 2, 3)
INSERT 0 1
```

**Comment by marcocitus** [comment]
Hmz, it seems like LocalGroupId can get cached in the postmaster process, and then every new backend will assume it to be correct.

**Comment by marcocitus** [comment]
I pushed a fix to https://github.com/citusdata/citus/commit/01642d3fefb951cee0dd72378b36550cd690a307 . Can you cherry-pick that commit?

**Comment by marcocitus** [comment]
Issue with drop schema:
```sql
select start_metadata_sync_to_node(nodename, nodeport) from pg_dist_node;
create table test (x int, y int);
select create_distributed_table('test','x');
create schema foo;
create sequence foo.seq;
alter table test add column a int default nextval('foo.seq');
drop schema foo cascade;

-- sequence is gone from coordinator:
insert into test values (1,2) RETURNING *;
NOTICE:  issuing INSERT INTO public.test_102091 (x, y) VALUES (1, 2) RETURNING x, y, a
DETAIL:  on server marco@localhost:1301 connectionId: 1
┌───┬───┬───┐
│ x │ y │ a │
├───┼───┼───┤
│ 1 │ 2 │   │
└───┴───┴───┘
```

but still present on worker:
```sql
insert into test values (1,2) RETURNING *;
┌───┬───┬───────────┐
│ x │ y │     a     │
├───┼───┼───────────┤
│ 1 │ 2 │ 268435457 │
└───┴───┴───────────┘
(1 row)
```

This is probably beyond the scope of this PR. I think the root of the problem is that we don't propagate DROP SCHEMA.

File: src/backend/distributed/commands/table.c (hunk 12 above)
Comment (naisila) [reply src/backend/distributed/commands/table.c:721]: Actually, I don't know why I do this 😆 removing it

**Comment by naisila** [comment]
> I pushed a fix to [8b1abca](https://github.com/citusdata/citus/commit/8b1abcad68e30c9e7f70b0956a0ba9d7c1fe235f) . Can you cherry-pick that commit?
> 
> It would be nice to have a test. I can normally reproduce it when doing the following on a clean cluster:
> 
> ```sql
> create table test (x int, y int);
> select create_distributed_table('test','x');
> create sequence seq;
> alter table test add column a int default nextval('seq');
> select start_metadata_sync_to_node(nodename, nodeport) from pg_dist_node;
> drop sequence seq cascade;
> truncate test;
> create sequence seq;
> alter table test add column b int default nextval('seq');
> ```
> 
> (I think some of the steps might be unnecessary, the main problem is that there is a cached connection to the workers that has not cached the pg_dist_local_group OID)
> 
> and then on a worker:
> 
> ```sql
> insert into test values (1,2) returning *;
> ┌───┬───┬───┬───┐
> │ x │ y │ a │ b │
> ├───┼───┼───┼───┤
> │ 1 │ 2 │   │ 1 │
> └───┴───┴───┴───┘
> ```
> 
> should be:
> 
> ```sql
> insert into test values (1,2) returning *;
> ┌───┬───┬───┬───────────┐
> │ x │ y │ a │     b     │
> ├───┼───┼───┼───────────┤
> │ 1 │ 2 │   │ 268435457 │
> └───┴───┴───┴───────────┘
> ```
> 
> though it may only reproduce if the worker starts with pg_dist_local_group set to 0.

Thanks for fixing the bug. Will write a test about it.

File: src/test/regress/expected/multi_insert_select.out [hunk 15]
```diff
@@ -2719,6 +2738,92 @@ SELECT * FROM dist_table_with_sequence ORDER BY user_id, value_1;
...
+       4 |       4
+       5 |       5
+(5 rows)
+
+WITH top10 AS (
+  SELECT user_id FROM raw_events_second WHERE value_1 IS NOT NULL ORDER BY value_1 LIMIT 10
+)
+INSERT INTO dist_table_with_user_sequence (value_1)
+SELECT * FROM top10;
+ERROR:  cannot handle complex subqueries when the router executor is disabled
```
Comment (marcocitus) [inline src/test/regress/expected/multi_insert_select.out:2800]: this error message is confusing (router executor is enabled here, right?)

probably worth opening an issue

File: src/test/regress/expected/multi_insert_select.out [hunk 16]
```diff
@@ -2212,7 +2212,7 @@ FROM
   table_with_defaults
 GROUP BY
   store_id, first_name, last_name;
--- Volatile function in default should be disallowed
+-- Volatile function in default should be disallowed - serial prototypes
```
Comment (marcocitus) [inline src/test/regress/expected/multi_insert_select.out:2215]: not sure what is meant by "serial prototypes"

File: src/test/regress/expected/insert_select_repartition.out [hunk 17]
```diff
@@ -1267,6 +1267,32 @@ explain insert into table_with_sequences select y, x from table_with_sequences;
...
+                                                           QUERY PLAN
+---------------------------------------------------------------------
+ Custom Scan (Citus INSERT ... SELECT)  (cost=0.00..0.00 rows=0 width=0)
+   INSERT/SELECT method: pull to coordinator
+   ->  Custom Scan (Citus Adaptive)  (cost=0.00..250.00 rows=100000 width=16)
+         Task Count: 4
+         Tasks Shown: One of 4
+         ->  Task
+               Node: host=localhost port=xxxxx dbname=regression
+               ->  Seq Scan on table_with_user_sequences_4213652 table_with_user_sequences  (cost=0.00..28.50 rows=1850 width=8)
```
Comment (marcocitus) [inline src/test/regress/expected/insert_select_repartition.out:1293]: should disable costs

File: src/backend/distributed/deparser/deparse_table_stmts.c [hunk 18]
```diff
@@ -46,3 +50,114 @@ AppendAlterTableSchemaStmt(StringInfo buf, AlterObjectSchemaStmt *stmt)
...
+	if (columnDefinition->is_not_null)
+	{
+		appendStringInfoString(buf, " NOT NULL");
+	}
+
+	Oid collationOid = GetColumnDefCollation(NULL, columnDefinition, typeOid);
+	if (OidIsValid(collationOid))
+	{
+		const char *identifier = FormatCollateBEQualified(collationOid);
+		appendStringInfo(buf, " COLLATE %s", identifier);
```
Comment (marcocitus) [inline src/backend/distributed/deparser/deparse_table_stmts.c:161]: would be good if we can cover the uncovered lines here as well

File: src/backend/distributed/commands/table.c [hunk 19]
```diff
@@ -1736,19 +1940,168 @@ ErrorIfUnsupportedAlterTableStmt(AlterTableStmt *alterTableStatement)
...
+									/*
+									 * Currently we don't support backfilling the new column with default values
+									 * if the table is not empty
+									 */
+									if (!TableEmpty(relationId))
+									{
+										ereport(ERROR, (errcode(
+															ERRCODE_FEATURE_NOT_SUPPORTED),
+														errmsg(
+															"Cannot add a column involving DEFAULT nextval('..') "
```
Comment (marcocitus) [inline src/backend/distributed/commands/table.c:2029]: super minor: Cannot -> cannot, per usual errmsg convention in postgres

File: src/backend/distributed/deparser/citus_ruleutils.c [hunk 20]
```diff
@@ -483,6 +498,126 @@ pg_get_tableschemadef_string(Oid tableRelationId, bool includeSequenceDefaults,
...
+				Oid currentSeqTypId = GetAttributeTypeOid(citusTableId,
+														  currentAttnum);
+				if (seqTypId != currentSeqTypId)
+				{
+					char *sequenceName = generate_qualified_relation_name(
+						seqOid);
+					char *citusTableName =
+						generate_qualified_relation_name(citusTableId);
+					ereport(ERROR, (errmsg(
+										"The sequence %s is already used for a different"
```
Comment (marcocitus) [inline src/backend/distributed/deparser/citus_ruleutils.c:560]: needs some tests

File: src/backend/distributed/deparser/deparse_sequence_stmts.c [hunk 21]
```diff
@@ -0,0 +1,158 @@
...
+	appendStringInfoString(buf, "ALTER SEQUENCE ");
+
+	if (stmt->missing_ok)
+	{
+		appendStringInfoString(buf, "IF EXISTS ");
+	}
+
+	appendStringInfoString(buf, qualifiedSequenceName);
+
+	appendStringInfo(buf, " RENAME TO %s;", quote_identifier(stmt->newname));
```
Comment (marcocitus) [inline src/backend/distributed/deparser/deparse_sequence_stmts.c:136]: Super minor: Personally I kind of dislike when we add ; to a command, because it is only necessary when sending multiple queries as a single command (or to tell psql about the end of the command).

**Review by marcocitus — COMMENTED** [review]
I seem to be getting this error even though this is the first time I'm using the sequence:
```sql
create sequence seq;
create table par (x text, t timestamptz default now(), s int default nextval('seq')) partition by range (t);
select create_distributed_table('par','x');
ERROR:  The sequence public.seq is already used for a different type in column 2 of the distributed table public.par
```

**Comment by marcocitus** [comment]
Weird issue:
```sql
postgres=# \d par
                          Table "public.par"
┌────────┬──────────────────────────┬───────────┬──────────┬─────────┐
│ Column │           Type           │ Collation │ Nullable │ Default │
├────────┼──────────────────────────┼───────────┼──────────┼─────────┤
│ x      │ text                     │           │          │         │
│ t      │ timestamp with time zone │           │          │ now()   │
│ s      │ bigint                   │           │          │         │
└────────┴──────────────────────────┴───────────┴──────────┴─────────┘

postgres=# alter table par alter column s set default nextval('seq');
ERROR:  sequence type must be smallint, integer, or bigint
CONTEXT:  SQL statement "ALTER SEQUENCE public.seq AS timestamp with time zone"
```
seems like it's looking at the wrong column

File: src/backend/distributed/metadata/metadata_sync.c [hunk 22]
```diff
@@ -386,8 +385,12 @@ MetadataCreateCommands(void)
 		ObjectAddressSet(tableAddress, RelationRelationId, relationId);
 		EnsureDependenciesExistOnAllNodes(&tableAddress);
 
-		metadataSnapshotCommandList = list_concat(metadataSnapshotCommandList,
-												  workerSequenceDDLCommands);
+		if (!PartitionTable(relationId))
```
Comment (marcocitus) [inline src/backend/distributed/metadata/metadata_sync.c:388]: It is possible for a partition to have a different DEFAULT than its parent, so this can cause issues:
```sql
create sequence seq;
create table par (x text, s bigint default nextval('seq'), t timestamptz default now()) partition by range (t);
select create_distributed_table('par','x');

create sequence par1_seq;
create table par1 (x text, s bigint default nextval('par1_seq'), t timestamptz default now());
alter table par attach partition par1 for values from ('2021-05-31') to ('2021-06-01');
```

**Comment by naisila** [comment]
> I seem to be getting this error even though this is the first time I'm using the sequence:
> 
> ```sql
> create sequence seq;
> create table par (x text, t timestamptz default now(), s int default nextval('seq')) partition by range (t);
> select create_distributed_table('par','x');
> ERROR:  The sequence public.seq is already used for a different type in column 2 of the distributed table public.par
> ```



> Weird issue:
> 
> ```sql
> postgres=# \d par
>                           Table "public.par"
> ┌────────┬──────────────────────────┬───────────┬──────────┬─────────┐
> │ Column │           Type           │ Collation │ Nullable │ Default │
> ├────────┼──────────────────────────┼───────────┼──────────┼─────────┤
> │ x      │ text                     │           │          │         │
> │ t      │ timestamp with time zone │           │          │ now()   │
> │ s      │ bigint                   │           │          │         │
> └────────┴──────────────────────────┴───────────┴──────────┴─────────┘
> 
> postgres=# alter table par alter column s set default nextval('seq');
> ERROR:  sequence type must be smallint, integer, or bigint
> CONTEXT:  SQL statement "ALTER SEQUENCE public.seq AS timestamp with time zone"
> ```
> 
> seems like it's looking at the wrong column

Thanks for catching this. There is a mix up when associating `attnum` to sequences. Pushing the fix soon.

File: src/test/regress/sql/multi_table_ddl.sql [hunk 23]
```diff
@@ -75,17 +77,39 @@ ALTER SEQUENCE testserialtable_id_seq OWNED BY NONE;
 -- or create a sequence with a distributed owner
 CREATE SEQUENCE standalone_sequence OWNED BY testserialtable.group_id;
 
--- or even change a manual sequence to be owned by a distributed table
-CREATE SEQUENCE standalone_sequence;
-ALTER SEQUENCE standalone_sequence OWNED BY testserialtable.group_id;
```
[the remark this answers is not in the document]
Comment (naisila) [reply src/test/regress/sql/multi_table_ddl.sql:80]: This `owned_by` operation is used when adding a new column with a serial prototype. For this reason I removed the check from the code, and also its test. So, currently this can be done, but I figured supporting serial prototypes is more important right now.

To error out for this operation with a manual sequence, and not error out for serial prototypes, `ALTER SEQUENCE` command needs to be handled in this special case, so we can keep a note of this and fix it in the possible future `ALTER SEQUENCE` PR.

File: src/backend/distributed/deparser/deparse_sequence_stmts.c (hunk 21 above)
Comment (naisila) [reply src/backend/distributed/deparser/deparse_sequence_stmts.c:136]: I was following rename function style, so your preferred format is not followed consistently throughout the code. However, I also prefer your preferred format so will change it.

File: src/test/regress/expected/multi_insert_select.out (hunk 16 above)
Comment (naisila) [reply src/test/regress/expected/multi_insert_select.out:2215]: I meant to write serial pseudo-types. 😆

File: src/test/regress/expected/multi_insert_select.out (hunk 15 above)
Comment (naisila) [reply src/test/regress/expected/multi_insert_select.out:2800]: > (router executor is enabled here, right?)
Yes it seems to be enabled. I didn't notice this problem since it was also occurring for serial pseudo-types. Will open an issue about it.

File: src/backend/distributed/metadata/metadata_sync.c [hunk 24]
```diff
@@ -1042,21 +1046,46 @@ List *
...
+		/* alter the sequence's data type in the coordinator if needed */
+		Oid currentSequenceTypeOid = sequenceData->seqtypid;
+		if (currentSequenceTypeOid != sequenceTypeOid)
+		{
+			UnmarkObjectDistributed(&sequenceAddress);
+			StringInfo sequenceAlterTypeStmt = makeStringInfo();
+			appendStringInfo(sequenceAlterTypeStmt, "ALTER SEQUENCE %s AS %s",
+							 sequenceName,
+							 typeName);
+			ExecuteQueryViaSPI(sequenceAlterTypeStmt->data, SPI_OK_UTILITY);
```
Comment (marcocitus) [inline src/backend/distributed/metadata/metadata_sync.c:1086]: Would be good to avoid the Citus hooks here and use something like:
```c
AlterSeqStmt *alterSequenceStatement = makeNode(AlterSeqStmt);
alterSequenceStatement->sequence = makeRangeVar(schemaName, sequenceName, -1);
Node *asTypeNode = (Node *) makeTypeNameFromOid(currentSequenceTypeOid, -1);
SetDefElemArg(alterSequenceStatement, "as", asTypeNode);
```
I'm also kind of wondering whether we should be doing this as soon as we start using a sequence in a distributed table (e.g. before we do the type sanity checks), but it's not a blocker.

Comment (naisila) [reply src/backend/distributed/metadata/metadata_sync.c]: Thanks!

File: src/backend/distributed/metadata/metadata_sync.c [hunk 25]
```diff
@@ -1042,21 +1049,59 @@ List *
...
+		 * and ALTER TABLE commands that include a sequence default
+		 */
+		Oid currentSequenceTypeOid = sequenceData->seqtypid;
+		if (currentSequenceTypeOid != sequenceTypeOid)
+		{
+			/*
+			 * Need to do this since ALTER SEQUENCE commands
+			 * are not allowed for a distributed sequence
+			 */
+			UnmarkObjectDistributed(&sequenceAddress);
```
Comment (marcocitus) [inline src/backend/distributed/metadata/metadata_sync.c:1093]: do we still need this?

Comment (naisila) [reply src/backend/distributed/metadata/metadata_sync.c:1093]: Probably not 😆

File: src/backend/distributed/metadata/metadata_sync.c [hunk 26]
```diff
@@ -1042,21 +1049,53 @@ List *
...
+		Oid sequenceTypeOid = GetAttributeTypeOid(relationId, attnum);
 		char *typeName = format_type_be(sequenceTypeOid);
 
+		/* get sequence address */
+		ObjectAddress sequenceAddress = { 0 };
+		ObjectAddressSet(sequenceAddress, RelationRelationId, sequenceOid);
+		EnsureDependenciesExistOnAllNodes(&sequenceAddress);
+
+		/*
+		 * Alter the sequence's data type in the coordinator if needed
```
Comment (marcocitus) [inline src/backend/distributed/metadata/metadata_sync.c:1081]: can you elaborate on when this is needed?

**Review by marcocitus — COMMENTED** [review]
We seem to reset sequences on the worker nodes sometimes:
```sql
-- coordinator
select start_metadata_sync_to_node(nodename, nodeport) from pg_dist_node;
create table test (x int, y int);
select create_distributed_table('test','x');
create sequence seq1;
alter table test add column a int default nextval('seq1');

-- worker 2
insert into test values (1,2) returning *;
insert into test values (1,2) returning *;
insert into test values (1,2) returning *;
┌───┬───┬───────────┐
│ x │ y │     a     │
├───┼───┼───────────┤
│ 1 │ 2 │ 536870915 │
└───┴───┴───────────┘
(1 row)


-- coordinator
create sequence seq2;
alter table test add column b int;
alter table test alter column b set default nextval('seq2');

-- worker 2
insert into test values (1,2) returning *;
┌───┬───┬───────────┬───────────┐
│ x │ y │     a     │     b     │
├───┼───┼───────────┼───────────┤
│ 1 │ 2 │ 536870913 │ 536870913 │
└───┴───┴───────────┴───────────┘
(1 row)
```
in the last step, the seq1 sequence is also reset, which would cause problems if this column has a unique constraint.

This appears to happen because we send a worker_apply_sequence_command for the existing sequence.

**Review by marcocitus — APPROVED** [review]
Looks good. 

Some things that would be good to do in the nearish future:
- Move ALTER SEQUENCE .. AS .. out of SequenceDDLCommandList to where we first start using the sequence in a distributed table
- Other ALTER SEQUENCE commands
- GRANT ON SEQUENCE 
- Maybe undistribute sequence after it is no longer used in distributed tables

File: src/test/regress/sql/multi_sequence_default.sql [hunk 27]
```diff
@@ -0,0 +1,215 @@
...
+
+-- cannot use more than one sequence in a column default
+CREATE SEQUENCE seq_9;
+CREATE SEQUENCE seq_10;
+CREATE TABLE seq_test_9 (x int, y int DEFAULT nextval('seq_9') - nextval('seq_10'));
+SELECT create_distributed_table('seq_test_9', 'x');
+
+
+-- clean up
+DROP TABLE seq_test_0, seq_test_1, seq_test_2, seq_test_3, seq_test_4, seq_test_5, seq_test_6, seq_test_7, seq_test_8, seq_test_9;
```
Comment (SaitTalhaNisanci) [inline src/test/regress/sql/multi_sequence_default.sql:213]: Usually we create a schema for a test and drop the schema at the end so that:
- We don't need to drop the tables one by one
- After the test is done, it doesn't affect other tests since we drop the schema
- The test itself is isolated and doesn't depend on the other tests

Currently there are a lot of tests that depend on some other tests(which I believe we should get rid of)

Comment (naisila) [reply src/test/regress/sql/multi_sequence_default.sql:213]: Addressed this in #5046
