### PR TITLE
fix dropping table_name option from foreign table

### LINKED ISSUE #6663: Disallow 'Alter FOREIGN TABLE (DROP table_name)' for foreign tables in metadata
We add foreign table to metadata only if its `table_name` option is set. Then, when we drop `table_name` option, we should disallow  dropping foreign table from metadata. Otherwise, we got an error including shard no like below as table name defaults to foreign table's name. 

-- connect to remote server
```bash
psql -p 9700
```
```sql
CREATE TABLE remote_table(
        id integer NOT NULL,
        data text
);
```

-- connect to local server
```bash
psql -p 10700
```
```sql
CREATE SERVER foreign_server
        FOREIGN DATA WRAPPER postgres_fdw
        OPTIONS (host 'localhost', port '9700', dbname 'aykutbozkurt');

CREATE USER MAPPING FOR CURRENT_USER
        SERVER foreign_server
        OPTIONS (user 'aykutbozkurt');
  
CREATE FOREIGN TABLE foreign_table (
        id integer NOT NULL,
        data text
)
        SERVER foreign_server
        OPTIONS (schema_name 'public', table_name 'remote_table');

SELECT citus_add_local_table_to_metadata('foreign_table');

ALTER FOREIGN TABLE foreign_table options  (drop table_name);  -- still exists in metadata

SELECT * from foreign_table ; -- defaults to foreign table's name
ERROR:  relation "public.foreign_table_local_fails_102013" does not exist
CONTEXT:  remote SQL command: SELECT id, data FROM public.foreign_table_local_fails_102013
```

### PR DESCRIPTION
**Pull request by aykut-bozkurt**
We should disallow dropping table_name option if foreign table is in metadata. Otherwise, we get table not found error which contains shardid.

DESCRIPTION: Fixes user unfriendly foreign table not found message.

Fixes #6663

### CODE REVIEW

File: src/backend/distributed/commands/table.c [hunk 1]
```diff
@@ -3490,6 +3490,23 @@ ErrorIfUnsupportedAlterTableStmt(AlterTableStmt *alterTableStatement)
 			{
 				if (IsForeignTable(relationId))
 				{
+					List *optionList = (List *) command->def;
+
+					if (IsCitusTableType(relationId, CITUS_LOCAL_TABLE) &&
+						ForeignTableDropsTableNameOption(optionList))
```
Comment (onderkalaci) [inline src/backend/distributed/commands/table.c:3496]: shouldn't this only apply to postgres_fdw? Now, we apply the same check for all fdws, which is too restrictive. 

We only strictly require this check for postgres_fdw, see https://github.com/citusdata/citus/pull/6652/files#diff-0e4644d73762dfee1e32c6ac69a46e0802b4675316f466d2c86407464e2cf990R549 and https://github.com/citusdata/citus/pull/6652/files#r1088709237 for some relevant code / discussions

File: src/backend/distributed/commands/table.c [hunk 2]
```diff
@@ -3490,6 +3490,23 @@ ErrorIfUnsupportedAlterTableStmt(AlterTableStmt *alterTableStatement)
 			{
 				if (IsForeignTable(relationId))
 				{
+					List *optionList = (List *) command->def;
```
Comment (onderkalaci) [inline src/backend/distributed/commands/table.c:3493]: maybe move the logic into a function like: `ErrorIfAlterTableChangeTableNameForPostgresFDW` or such (maybe something shorter )

File: src/test/regress/expected/foreign_tables_mx.out [hunk 3]
```diff
@@ -416,6 +416,34 @@ NOTICE:  renaming the new table to foreign_tables_schema_mx.foreign_table_local_
 (1 row)
 
 DROP FOREIGN TABLE foreign_table_local;
+-- disallow dropping table_name when foreign table is in metadata
+CREATE TABLE table_name_drop(id int);
```
Comment (onderkalaci) [inline src/test/regress/expected/foreign_tables_mx.out:420]: at this point, it'd be very useful to have a non postgres-fdw test.

Can we easily add a file_fdw test?

```SQL
CREATE EXTENSION file_fdw;
\copy (select i from generate_series(0,100)i) to '/tmo/test_file_fdw.data';

CREATE SERVER citustest FOREIGN DATA WRAPPER file_fdw;

CREATE FOREIGN TABLE citustest_filefdw (
 data text) SERVER citustest OPTIONS ( filename '/tmp/test_file_fdw.data');
```

and, play with it. Maybe first try checking we cannot add this as citus local table (to cover #6652), and then add table_name option to the create foreign table && make it citus local. Later, play with add/drop table_name options

File: src/backend/distributed/commands/table.c [hunk 4]
```diff
@@ -3078,6 +3081,42 @@ ErrorIfUnsupportedConstraint(Relation relation, char distributionMethod,
...
+		return;
+	}
+
+	if (IsCitusTableType(relationId, CITUS_LOCAL_TABLE) &&
+		ForeignTableDropsTableNameOption(optionList))
+	{
+		ereport(ERROR,
+				(errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
+				 errmsg(
+					 "alter foreign table alter options (drop table_name) command "
```
Comment (onderkalaci) [inline src/backend/distributed/commands/table.c:3109]: minor: maybe the error message should mention that this is for Citus tables (because it looks like a PG error message now)

File: src/test/regress/expected/foreign_tables_mx.out [hunk 5]
```diff
@@ -416,6 +416,62 @@ NOTICE:  renaming the new table to foreign_tables_schema_mx.foreign_table_local_
...
+-- add non-postgres_fdw table into metadata even if it does not have table_name option
+SELECT citus_add_local_table_to_metadata('citustest_filefdw');
+ citus_add_local_table_to_metadata
+---------------------------------------------------------------------
+
+(1 row)
+
+ALTER FOREIGN TABLE citustest_filefdw OPTIONS (ADD table_name 'unused_table_name_option');
+-- drop table_name option of non-postgres_fdw table even if it is inside metadata
+ALTER FOREIGN TABLE citustest_filefdw OPTIONS (DROP table_name);
```
Comment (onderkalaci) [inline src/test/regress/expected/foreign_tables_mx.out:474]: let's clean up what we create (the server is not created in the schema?)

File: src/backend/distributed/commands/citus_add_local_table_to_metadata.c [hunk 6]
```diff
@@ -585,6 +585,30 @@ ErrorIfOptionListHasNoTableName(List *optionList)
...
+bool
+ForeignTableDropsTableNameOption(List *optionList)
+{
+	char *table_nameString = "table_name";
+	DefElem *option = NULL;
+	foreach_ptr(option, optionList)
+	{
+		char *optionName = option->defname;
+		DefElemAction optionAction = option->defaction;
+		if (strcmp(optionName, table_nameString) == 0 &&
```
Comment (onderkalaci) [inline src/backend/distributed/commands/citus_add_local_table_to_metadata.c:601]: do we need case insensitive check? Can you maybe add a regression test like `tablE_Name 'table_name_drop'` or such?

**Review by onderkalaci — APPROVED** [review]
After considering minor suggestions, we are good to merge.


Should we backport this change until where we added this limitation?

File: src/test/regress/expected/foreign_tables_mx.out (hunk 5 above)
Comment (aykut-bozkurt) [reply src/test/regress/expected/foreign_tables_mx.out:474]: It is created in the schema.
