### PR TITLE
Fix casts in insert into local table select from distributed

### LINKED ISSUE #5858: Inserting string literal into local table (by selecting from distributed table) might crash due to invalid tuple repr
Couldn't understand exact conditions that lead to segfault yet, so still investigating.
For example, it's weird to see that it doesn't crash if I shorten (or remove) one of the hardcoded strings being inserted.

```sql
CREATE TABLE local_table(
  col_1 integer,
  col_2 integer,
  col_3 text,
  col_4 text,
  col_5 int,
  col_6 text,
  col_7 text,
  col_8 text
);

CREATE TABLE dist_table_1(
  dist_col integer,
  int_col integer,
  text_col_1 text,
  text_col_2 text
);
SELECT create_distributed_table('dist_table_1', 'dist_col');

INSERT INTO dist_table_1 VALUES (1, 1, 'string', 'string');

CREATE TABLE dist_table_2(
  dist_col integer,
  int_col integer
);
SELECT create_distributed_table('dist_table_2', 'dist_col');

INSERT INTO dist_table_2 VALUES (1, 1);

INSERT INTO local_table
SELECT
  t1.dist_col,
  1,
  'string',
  'string',
  1,
  'string',
  t1.text_col_1,
  t1.text_col_2
FROM dist_table_1 t1
WHERE t1.int_col IN (SELECT int_col FROM dist_table_2);
```

```c
slot_deform_heap_tuple(TupleTableSlot * slot, HeapTuple tuple, uint32 * offp, int natts) (\opt\pgenv\src\postgresql-14.2\src\backend\executor\execTuples.c:991)
tts_minimal_getsomeattrs(TupleTableSlot * slot, int natts) (\opt\pgenv\src\postgresql-14.2\src\backend\executor\execTuples.c:511)
slot_getsomeattrs_int(TupleTableSlot * slot, int attnum) (\opt\pgenv\src\postgresql-14.2\src\backend\executor\execTuples.c:1912)
slot_getsomeattrs(TupleTableSlot * slot, int attnum) (\opt\pgenv\src\postgresql-14.2\src\include\executor\tuptable.h:344)
ExecInterpExpr(ExprState * state, ExprContext * econtext, _Bool * isnull) (\opt\pgenv\src\postgresql-14.2\src\backend\executor\execExprInterp.c:545)
ExecInterpExprStillValid(ExprState * state, ExprContext * econtext, _Bool * isNull) (\opt\pgenv\src\postgresql-14.2\src\backend\executor\execExprInterp.c:1824)
citus.so!ExecEvalExprSwitchContext(ExprState * state, ExprContext * econtext, _Bool * isNull) (\opt\pgenv\pgsql-14.2\include\server\executor\executor.h:339)
citus.so!ExecProject(ProjectionInfo * projInfo) (\opt\pgenv\pgsql-14.2\include\server\executor\executor.h:373)
citus.so!ReturnTupleFromTuplestore(CitusScanState * scanState) (\home\onurctirtir\citus\src\backend\distributed\executor\multi_executor.c:372)
citus.so!CitusExecScan(CustomScanState * node) (\home\onurctirtir\citus\src\backend\distributed\executor\citus_custom_scan.c:229)
ExecCustomScan(PlanState * pstate) (\opt\pgenv\src\postgresql-14.2\src\backend\executor\nodeCustom.c:115)
ExecProcNodeFirst(PlanState * node) (\opt\pgenv\src\postgresql-14.2\src\backend\executor\execProcnode.c:463)
ExecProcNode(PlanState * node) (\opt\pgenv\src\postgresql-14.2\src\include\executor\executor.h:257)
ExecModifyTable(PlanState * pstate) (\opt\pgenv\src\postgresql-14.2\src\backend\executor\nodeModifyTable.c:2425)
ExecProcNodeFirst(PlanState * node) (\opt\pgenv\src\postgresql-14.2\src\backend\executor\execProcnode.c:463)
ExecProcNode(PlanState * node) (\opt\pgenv\src\postgresql-14.2\src\include\executor\executor.h:257)
ExecutePlan(EState * estate, PlanState * planstate, _Bool use_parallel_mode, CmdType operation, _Bool sendTuples, uint64 numberTuples, ScanDirection direction, DestReceiver * dest, _Bool execute_once) (\opt\pgenv\src\postgresql-14.2\src\backend\executor\execMain.c:1551)
standard_ExecutorRun(QueryDesc * queryDesc, ScanDirection direction, uint64 count, _Bool execute_once) (\opt\pgenv\src\postgresql-14.2\src\backend\executor\execMain.c:361)
citus.so!CitusExecutorRun(QueryDesc * queryDesc, ScanDirection direction, uint64 count, _Bool execute_once) (\home\onurctirtir\citus\src\backend\distributed\executor\multi_executor.c:214)
pg_stat_statements.so!pgss_ExecutorRun(QueryDesc * queryDesc, ScanDirection direction, uint64 count, _Bool execute_once) (\opt\pgenv\src\postgresql-14.2\contrib\pg_stat_statements\pg_stat_statements.c:1001)
ExecutorRun(QueryDesc * queryDesc, ScanDirection direction, uint64 count, _Bool execute_once) (\opt\pgenv\src\postgresql-14.2\src\backend\executor\execMain.c:303)
ProcessQuery(PlannedStmt * plan, const char * sourceText, ParamListInfo params, QueryEnvironment * queryEnv, DestReceiver * dest, QueryCompletion * qc) (\opt\pgenv\src\postgresql-14.2\src\backend\tcop\pquery.c:160)
PortalRunMulti(Portal portal, _Bool isTopLevel, _Bool setHoldSnapshot, DestReceiver * dest, DestReceiver * altdest, QueryCompletion * qc) (\opt\pgenv\src\postgresql-14.2\src\backend\tcop\pquery.c:1274)
PortalRun(Portal portal, long count, _Bool isTopLevel, _Bool run_once, DestReceiver * dest, DestReceiver * altdest, QueryCompletion * qc) (\opt\pgenv\src\postgresql-14.2\src\backend\tcop\pquery.c:788)
exec_simple_query(const char * query_string) (\opt\pgenv\src\postgresql-14.2\src\backend\tcop\postgres.c:1214)
PostgresMain(int argc, char ** argv, const char * dbname, const char * username) (\opt\pgenv\src\postgresql-14.2\src\backend\tcop\postgres.c:4486)
BackendRun(Port * port) (\opt\pgenv\src\postgresql-14.2\src\backend\postmaster\postmaster.c:4530)
BackendStartup(Port * port) (\opt\pgenv\src\postgresql-14.2\src\backend\postmaster\postmaster.c:4252)
ServerLoop() (\opt\pgenv\src\postgresql-14.2\src\backend\postmaster\postmaster.c:1745)
PostmasterMain(int argc, char ** argv) (\opt\pgenv\src\postgresql-14.2\src\backend\postmaster\postmaster.c:1417)
main(int argc, char ** argv) (\opt\pgenv\src\postgresql-14.2\src\backend\main\main.c:209)
```

I will also test with older versions since we will probably need to backport the fix.

### LINKED ISSUE #5891: Nonpushable INSERT might throw pseudo-type "unknown" error when inserting string literals
```sql
CREATE TABLE dist_table_1(
dist_col integer,
int_col integer,
text_col_1 text,
text_col_2 text
);

SELECT create_distributed_table('dist_table_1', 'dist_col');

INSERT INTO dist_table_1 VALUES (1, 1, 'string', 'string');

CREATE TABLE dist_table_2(
dist_col integer,
int_col integer
);

SELECT create_distributed_table('dist_table_2', 'dist_col');

INSERT INTO dist_table_2 VALUES (1, 1);

with a as (select random()) INSERT INTO dist_table_1
SELECT
t1.dist_col,
1,
'string',
'string'
FROM a, dist_table_1 t1
join dist_table_2 t2 using (dist_col)
limit 1;
ERROR: column "?column?_1" has pseudo-type unknown
```

Similar to #5858, but this happens when doing a non-pushable insert into a distributed table, so happens at a different codepath (i.e.: in CreateNonPushableInsertSelectPlan()).

The reason behind #5858 was that we were not calling AddInsertSelectCasts() at all so any such query that inserts a string literal was affected, so we proposed a solution for that in #5873.

On the other hand, even if we add casts for non-pushable inserts at CreateNonPushableInsertSelectPlan() on master, it doesn't help if the SELECT query needs to be wrapped in a subquery via BuildSelectForInsertSelect()->WrapSubquery().

This is because, in that case we add casts to the outer SELECT but the inner one would still have unknown typed attributes as in the example given above.

------

The solution seems to be wrapping the query via BuildSelectForInsertSelect() after adding casts so that we can add casts to inner query and then the outer one would anyway fetch the casted attributes.

```diff
index 746e2846c..8e34d938a 100644
--- a/src/backend/distributed/planner/insert_select_planner.c
+++ b/src/backend/distributed/planner/insert_select_planner.c
@@ -1412,9 +1412,8 @@ CreateNonPushableInsertSelectPlan(uint64 planId, Query *parse, ParamListInfo bou
                return distributedPlan;
        }

-       Query *selectQuery = BuildSelectForInsertSelect(insertSelectQuery);
+       Query *selectQuery = selectRte->subquery;

-       selectRte->subquery = selectQuery;
        ReorderInsertSelectTargetLists(insertSelectQuery, insertRte, selectRte);

        /*
@@ -1435,6 +1434,9 @@ CreateNonPushableInsertSelectPlan(uint64 planId, Query *parse, ParamListInfo bou
        List *insertTargetList = insertSelectQuery->targetList;
        RelabelTargetEntryList(selectQuery->targetList, insertTargetList);

+       selectQuery = BuildSelectForInsertSelect(insertSelectQuery);
+       selectRte->subquery = selectQuery;
+
        /*
         * Make a copy of the select query, since following code scribbles it
         * but we need to keep the original for EXPLAIN.
```

However, for some reason, this change seems to be breaking the order of the columns being inserted into the table when set operations are involved and I gave up on trying to fix that, and so opening this issue :)

Probably, ReorderInsertSelectTargetLists() somehow relies on the fact that the SELECT query is wrapped within a subquery if it contains a set operation (see BuildSelectForInsertSelect()->WrapSubquery()).

### PR DESCRIPTION
**Pull request by marcocitus**
DESCRIPTION: Fixes a bug that could cause failures in insert into select

New attempt at #5873. The parser marks strings in insert..select query as having type "unknown", which causes downstream issues  when doing an insert..select into a local table.

This PR fixes issues in adding casts and target list reordering that were largely masked by only deparsing, not planning the query trees.

Fixes #5858
Fixes #5891

### CODE REVIEW

**Comment by marcocitus** [comment]
This query still has an issue:
```sql
INSERT INTO local_table (col_4, col_1)
SELECT
  'string',
   dist_col
FROM dist_table_1
UNION ALL
SELECT
  'string',
   int_col
FROM dist_table_1;
...
NOTICE:  executing the command locally: SELECT ("?column?")::integer AS auto_coerced_by_citus_0, (dist_col)::text AS auto_coerced_by_citus_1 FROM (SELECT intermediate_result."?column?", intermediate_result.dist_col FROM read_intermediate_result('1_3'::text, 'binary'::citus_copy_format) intermediate_result("?column?" text, dist_col integer)) citus_insert_select_subquery("?column?", dist_col)
...
ERROR:  invalid input syntax for type integer: "string"
```

**Comment by marcocitus** [comment]
> Will review once the regression tests pass

Test failures are not too exciting, but the union bug still needs to be fixed. I'll ping you.

File: src/backend/distributed/executor/insert_select_executor.c [hunk 1]
```diff
@@ -299,100 +298,6 @@ NonPushableInsertSelectExecScan(CustomScanState *node)
 }
 
 
-/*
- * BuildSelectForInsertSelect extracts the SELECT part from an INSERT...SELECT query.
- * If the INSERT...SELECT has CTEs then these are added to the resulting SELECT instead.
- */
-Query *
-BuildSelectForInsertSelect(Query *insertSelectQuery)
```
Comment (marcocitus) [inline src/backend/distributed/executor/insert_select_executor.c:307]: Removed

File: src/backend/distributed/executor/insert_select_executor.c [hunk 2]
```diff
@@ -299,100 +298,6 @@ NonPushableInsertSelectExecScan(CustomScanState *node)
...
-	return selectQuery;
-}
-
-
-/*
- * WrapSubquery wraps the given query as a subquery in a newly constructed
- * "SELECT * FROM (...subquery...) citus_insert_select_subquery" query.
- */
-static Query *
-WrapSubquery(Query *subquery)
```
Comment (marcocitus) [inline src/backend/distributed/executor/insert_select_executor.c:344]: Moved to insert_select_planner.c (only caller)

File: src/backend/distributed/planner/insert_select_planner.c [hunk 3]
```diff
@@ -1506,6 +1572,63 @@ InsertSelectResultIdPrefix(uint64 planId)
 }
 
 
+/*
+ * WrapSubquery wraps the given query as a subquery in a newly constructed
+ * "SELECT * FROM (...subquery...) citus_insert_select_subquery" query.
+ */
+static Query *
+WrapSubquery(Query *subquery)
```
Comment (marcocitus) [inline src/backend/distributed/planner/insert_select_planner.c:1580]: Moved ad verbatim from insert_select_executor.c

**Review by marcocitus — COMMENTED** [review]
Still adding more tests, but probably ready for another round of reviews.

**Comment by marcocitus** [comment]
Assert failure after adding default to one of the columns:
```
CREATE TABLE local_dest_table(
  col_1 integer,
  col_2 integer,
  col_3 text,
  col_4 text,
  drop_col text,
  col_5 int,
  col_6 text,
  col_7 text default 'col_7',
  col_8 text
);

ALTER TABLE local_dest_table DROP COLUMN drop_col;

CREATE TABLE dist_source_table_1(
  int_col integer,
  drop_col text,
  text_col_1 text,
  dist_col integer,
  text_col_2 text
);
SELECT create_distributed_table('dist_source_table_1', 'dist_col');

ALTER TABLE dist_source_table_1 DROP COLUMN drop_col;

INSERT INTO dist_source_table_1 VALUES (1, 'value', 1, 'value');
INSERT INTO dist_source_table_1 VALUES (2, 'value2', 1, 'value');
INSERT INTO dist_source_table_1 VALUES (3, 'value', 3, 'value3');


INSERT INTO local_dest_table (col_3)
   SELECT t1.text_col_1
   FROM dist_source_table_1 t1
   GROUP BY t1.text_col_1;
```

**Comment by marcocitus** [comment]
To maintain validity of the query tree, we should not add select target entry in ReorderInsertSelectTargetLists without adjusting rte->eref->colnames.

**Comment by marcocitus** [comment]
> Assert failure, which only happened after adding default to one of the columns:

fixed now

File: src/test/regress/expected/insert_select_into_local_table.out [hunk 4]
```diff
@@ -354,6 +425,346 @@ SELECT * FROM non_dist_2 ORDER BY 1, 2;
 (3 rows)
 
 TRUNCATE non_dist_2;
+-- check issue https://github.com/citusdata/citus/issues/5858
+CREATE TABLE local_dest_table(
```
[the remark this answers is not in the document]
Comment (marcocitus) [reply src/test/regress/expected/insert_select_into_local_table.out:429]: > Also, maybe an already existing another issue on main:

That's mostly just the error you get when casting 'string' to int, would be the same without distributed tables.

[the remark this answers is not in the document]
Comment (onderkalaci) [reply src/test/regress/expected/insert_select_into_local_table.out:429]: ah, sure, result of trying out too many combinations :)

**Comment by onurctirtir** [comment]
(reviewing this now)

**Review by onurctirtir — COMMENTED** [review]
All the test cases that I tried to add into #5873 worked fine (default columns / columns in different order / set operations / group by / ..), so LGTM.

#5873 was testing those scenarios for remote execution as well even if they were already working well. Should we do the same here to be defensive against a future commit accidentally breaking something similar in deparser ?

**Comment by onderkalaci** [comment]
> Should we do the same here to be defensive against a future commit accidentally breaking something similar in deparser ?

Those are mostly covered via: src/test/regress/sql/multi_deparse_shard_query.sql

File: src/test/regress/expected/insert_select_into_local_table.out (hunk 4 above)
[the remark this answers is not in the document]
Comment (onderkalaci) [reply src/test/regress/expected/insert_select_into_local_table.out:429]: this is fixed with the last commit.

File: src/test/regress/sql/insert_select_into_local_table.sql [hunk 5]
```diff
@@ -149,5 +174,238 @@ INSERT INTO non_dist_2 SELECT a, c FROM ref_table;
 SELECT * FROM non_dist_2 ORDER BY 1, 2;
 TRUNCATE non_dist_2;
 
+-- check issue https://github.com/citusdata/citus/issues/5858
+CREATE TABLE local_dest_table(
```
Comment (onderkalaci) [inline src/test/regress/sql/insert_select_into_local_table.sql:178]: It'd be great to have maybe some basic tests for where we add `local_dest_table` to the metadata? 

Then the final step becomes a COPY, which seems to work without issues, but seems like a good idea to given our investments to citus local tables

File: src/backend/distributed/planner/insert_select_planner.c [hunk 6]
```diff
@@ -417,12 +423,84 @@ CreateInsertSelectIntoLocalTablePlan(uint64 planId, Query *originalQuery, ParamL
...
+	/*
+	 * Cast types of insert target list and select projection list to
+	 * match the column types of the target relation.
+	 */
+	selectRte->subquery->targetList =
+		AddInsertSelectCasts(insertSelectQuery->targetList,
+							 copyObject(selectRte->subquery->targetList),
+							 targetRelationId);
+
+	if (list_length(insertSelectQuery->cteList) > 0)
```
Comment (onderkalaci) [inline src/backend/distributed/planner/insert_select_planner.c:485]: one thing that is not very clear to me is why we decide tto `WrapSubquery` for ctes after `AddInsertSelectCasts`, but for set operations before? Can you remind me please? Thanks!

**Review by onderkalaci — APPROVED** [review]
This is marked to backport on for 11.0, but I feel like it'd be better to backport at least to 10.2 as well?

Thanks for fixing this pretty complex bug!

File: src/backend/distributed/planner/insert_select_planner.c (hunk 6 above)
Comment (marcocitus) [reply src/backend/distributed/planner/insert_select_planner.c:485]: The function comment of PrepareInsertSelectForCitusPlanner has an explanation of why we do these steps.

Queries with CTEs should not be wrapped before, because they have the same unknown type problem as other queries (exception set operations). See https://github.com/citusdata/citus/issues/5891

**Comment by onurctirtir** [comment]
> This is marked to backport on for 11.0, but I feel like it'd be better to backport at least to 10.2 as well?
> 
> Thanks for fixing this pretty complex bug!

Reproducible up until 9.4 where we introduced support for such INSERT .. SELECT stmts, so would be nice to backport this at least to 10.2.

**Comment by onurctirtir** [comment]
removing cherry-pick-11.0 label as this is already backported to release-11.0
