### PR TITLE
Fail early when shard can't be safely moved to a new node

### LINKED ISSUE #7426: citus_move_shard_placement to a fresh worker makes cluster unusable
Hi, this may be just a documentation issue. When creating a new worker, it won't immediately have reference tables. They get copied on `citus_rebalance_start()` but not on `citus_move_shard_placement(...)`.

The documentation doesn't mention that one can't use `citus_move_shard_placement(...)` on a fresh node and the function `replicate_reference_tables()` isn't documented.

Steps to reproduce:

1. Create a single-node Citus cluster on localhost.
```
postgres=# SELECT * FROM pg_dist_node;
 nodeid | groupid | nodename  | nodeport | noderack | hasmetadata | isactive | noderole | nodecluster | metadatasynced | shouldhaveshards 
--------+---------+-----------+----------+----------+-------------+----------+----------+-------------+----------------+------------------
      1 |       0 | localhost |     5400 | default  | t           | t        | primary  | default     | t              | t
```
2. Create a distributed table and a reference table.
```sql
CREATE TABLE distributed (id SERIAL PRIMARY KEY, value INT);
CREATE TABLE reference (id SERIAL PRIMARY KEY, value INT);
SELECT create_distributed_table('distributed', 'id');
SELECT create_reference_table('reference');
```
3. Add a worker node. `SELECT citus_add_node('localhost', 5401);`
```
postgres=# SELECT * FROM pg_dist_node;
 nodeid | groupid | nodename  | nodeport | noderack | hasmetadata | isactive | noderole | nodecluster | metadatasynced | shouldhaveshards 
--------+---------+-----------+----------+----------+-------------+----------+----------+-------------+----------------+------------------
      1 |       0 | localhost |     5400 | default  | t           | t        | primary  | default     | t              | t
      2 |       1 | localhost |     5401 | default  | t           | t        | primary  | default     | t              | t
```
4. Move one shard manually. 
```sql
SELECT citus_move_shard_placement(102024, 'localhost', 5400, 'localhost', 5401);
```
5. 💥 
```sql
postgres=# 
    SELECT * FROM distributed JOIN reference USING (id);

ERROR:  relation "public.reference_102040" does not exist
CONTEXT:  while executing command on localhost:5401
```

Calling undocumented `replicate_reference_tables` fixes the problem.

```sql
postgres=# SELECT replicate_reference_tables();
NOTICE:  replicating reference table 'reference' to localhost:5401 ...
 replicate_reference_tables 
----------------------------
 
(1 row)

postgres=# SELECT * FROM distributed JOIN reference USING (id);
 id | value | value 
----+-------+-------
(0 rows)
```

### PR DESCRIPTION
**Pull request by crabhi**
DESCRIPTION: citus_move_shard_placement now fails early when shard cannot be safely moved

The implementation is quite simplistic - `citus_move_shard_placement(...)` will fail with an error if there's any new node in the cluster that doesn't have reference tables yet. 

It could have been finer-grained, i.e. erroring only when trying to move a shard to an unitialized node. Looking at the related functions - `replicate_reference_tables()` or `citus_rebalance_start()`, I think it's acceptable behaviour. These other functions also treat "any" unitialized node as a temporary anomaly.

Fixes #7426

### CODE REVIEW

File: src/test/regress/sql/shard_rebalancer.sql [hunk 1]
```diff
@@ -1359,6 +1362,25 @@ FROM pg_dist_shard
...
+SELECT citus_move_shard_placement(pg_dist_shard.shardid, nodename, nodeport, 'localhost', :worker_2_port)
+    FROM pg_dist_shard JOIN pg_dist_shard_placement USING (shardid)
+    WHERE logicalrelid = 'd1'::regclass AND nodename = 'localhost' AND nodeport = :worker_1_port LIMIT 1;
+
+-- And a JOIN with the reference table should work.
+SELECT 1 as dummy FROM d1 JOIN r1 USING (a);
+
+DROP TABLE d1;
+
 -- rebalance with _only_ a reference table, this should trigger the copy
```
Comment (crabhi) [inline src/test/regress/sql/shard_rebalancer.sql:1384]: Oh, I just realized I need to fix this. The test passes but it doesn't test properly that `rebalance_table_shards()` triggers the copy of reference tables.

I guess removing and adding the node should be enough, am I right?

Comment (JelteF) [reply src/test/regress/sql/shard_rebalancer.sql:1384]: Yeah, add + remove node would do the trick.

Comment (JelteF) [reply src/test/regress/sql/shard_rebalancer.sql:1384]: Or actually you'd also need to drop + re-create the d1 and r1 tables.

Comment (JelteF) [reply src/test/regress/sql/shard_rebalancer.sql:1384]: basically cop paste the start:
```
DROP TABLE d1, r1;

SELECT 1 from master_remove_node('localhost', :worker_2_port);
SELECT public.wait_until_metadata_sync(30000);
CREATE TABLE r1 (a int PRIMARY KEY, b int);
SELECT create_reference_table('r1');

CREATE TABLE d1 (a int PRIMARY KEY, b int);
SELECT create_distributed_table('d1', 'a');

ALTER SEQUENCE pg_dist_groupid_seq RESTART WITH 15;
SELECT 1 from master_add_node('localhost', :worker_2_port);

-- count the number of placements for the reference table to verify it is not available on
-- all nodes
SELECT count(*)
FROM pg_dist_shard
JOIN pg_dist_shard_placement USING (shardid)
WHERE logicalrelid = 'r1'::regclass;
```

Comment (crabhi) [reply src/test/regress/sql/shard_rebalancer.sql:1406]: Yes, this seems to be right. Thank you, added.

File: src/test/regress/sql/shard_rebalancer.sql [hunk 2]
```diff
@@ -1359,6 +1392,18 @@ FROM pg_dist_shard
...
 
+SELECT replicate_reference_tables();
+
+-- After replication, the move should succeed.
+SELECT citus_move_shard_placement(pg_dist_shard.shardid, nodename, nodeport, 'localhost', :worker_2_port)
+    FROM pg_dist_shard JOIN pg_dist_shard_placement USING (shardid)
+    WHERE logicalrelid = 'd1'::regclass AND nodename = 'localhost' AND nodeport = :worker_1_port LIMIT 1;
+
+-- And a JOIN with the reference table should work.
+SELECT 1 as dummy FROM d1 JOIN r1 USING (a);
```
Comment (JelteF) [inline src/test/regress/sql/shard_rebalancer.sql:1403]: This should be moved up to, right above `DROP TABLE d1, r1;`

File: src/test/regress/sql/shard_rebalancer.sql [hunk 3]
```diff
@@ -1359,6 +1392,18 @@ FROM pg_dist_shard
...
+
+DROP TABLE d1;
```
Comment (JelteF) [inline src/test/regress/sql/shard_rebalancer.sql:1405]: This line should be deleted

File: src/test/regress/sql/shard_rebalancer.sql (hunk 2 above)
Comment (crabhi) [reply src/test/regress/sql/shard_rebalancer.sql:1403]: Why do you think so? This is the query that fails when you move a shard but don't replicate reference tables. I intended it to run here to prove that the JOIN can be performed after `citus_move_shard_placement`. It may be pointless when we explicitly do `replicate_reference_tables`, though. So maybe I could just remove it. What do you think?

File: src/test/regress/sql/shard_rebalancer.sql (hunk 3 above)
Comment (crabhi) [reply src/test/regress/sql/shard_rebalancer.sql:1405]: Are you sure? This cleans up the table I introduced earlier for this test (l. 1383).

**Comment by crabhi** [comment]
I'm not sure about the codecov report. The line it is complaining about is explicitly hit by the test - the error message shows at [shard_rebalancer.out:2449](https://github.com/citusdata/citus/pull/7467/files#diff-40823be915bd43bb24d6c1ed0c14750c89c14aa3569098ae98952b8a5eb9aca5R2449).

File: src/test/regress/sql/shard_rebalancer.sql (hunk 3 above)
Comment (JelteF) [reply src/test/regress/sql/shard_rebalancer.sql:1405]: This would only be the case if you move the rest up I guess.

File: src/test/regress/sql/shard_rebalancer.sql (hunk 2 above)
Comment (JelteF) [reply src/test/regress/sql/shard_rebalancer.sql:1403]: to be clear, I meant to that you should move up this whole block.

Comment (crabhi) [reply src/test/regress/sql/shard_rebalancer.sql:1403]: Sorry, that means I have messed up. I'll clean it up but it will take at least a week before I can get back to it and focus properly - just FYI that I'm not giving up, just out of time due to other priorities.

Comment (crabhi) [reply src/test/regress/sql/shard_rebalancer.sql]: You were right. I tried to clean it up. Please have a look at the current state.

**Review by JelteF — APPROVED** [review]
