### PR TITLE
Split list of configuration values properly

### LINKED ISSUE #4012: create table and select table error occured on workers after 'master_add_node()' function is executed
1. phenomenon
The table cannot be created and looked up in public schema on workers after 'master_add_node()' function is executed.

		[postgres@zhengy ~/citus]$ psql -p9701
		psql (12.3)
		Type "help" for help.

		postgres=# create table tb1(c1 int);
		ERROR:  no schema has been selected to create in
		LINE 1: create table tb1(c1 int);
							 ^
		postgres=# create table public.tb1(c1 int);
		CREATE TABLE
		postgres=# select * from tb1;
		ERROR:  relation "tb1" does not exist
		LINE 1: select * from tb1;
							  ^
		postgres=# \dx
						 List of installed extensions
		  Name   | Version |   Schema   |         Description
		---------+---------+------------+------------------------------
		 citus   | 9.3-2   | pg_catalog | Citus distributed database
		 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
		(2 rows)

		postgres=# select version();
														 version
		---------------------------------------------------------------------------------------------------------
		 PostgreSQL 12.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit
		(1 row)

2. Operation
After executing the commands in the following order, the table cannot be created and looked up in public schema on workers.

		mkdir -p citus/coordinator citus/worker1 citus/worker2
		initdb -D citus/coordinator
		initdb -D citus/worker1
		initdb -D citus/worker2

		echo "log_min_duration_statement = 0" >> citus/coordinator/postgresql.conf
		echo "log_min_duration_statement = 0" >> citus/worker1/postgresql.conf
		echo "log_min_duration_statement = 0" >> citus/worker2/postgresql.conf

		echo "shared_preload_libraries = 'citus'" >> citus/coordinator/postgresql.conf
		echo "shared_preload_libraries = 'citus'" >> citus/worker1/postgresql.conf
		echo "shared_preload_libraries = 'citus'" >> citus/worker2/postgresql.conf

		pg_ctl -D citus/coordinator -o "-p 9700" -l coordinator_logfile start
		pg_ctl -D citus/worker1 -o "-p 9701" -l worker1_logfile start
		pg_ctl -D citus/worker2 -o "-p 9702" -l worker2_logfile start

		psql -p 9700 -c "CREATE EXTENSION citus;"
		psql -p 9701 -c "CREATE EXTENSION citus;"
		psql -p 9702 -c "CREATE EXTENSION citus;"

		psql -p 9700 -c "CREATE schema test;"
		psql -p 9701 -c "CREATE schema test;"
		psql -p 9702 -c "CREATE schema test;"

		psql -p 9700 -c "alter user postgres set search_path = test, public;"
		psql -p 9701 -c "alter user postgres set search_path = test, public;"
		psql -p 9702 -c "alter user postgres set search_path = test, public;"

		psql -p 9700 -c "SELECT * from master_add_node('localhost', 9701);"
		psql -p 9700 -c "SELECT * from master_add_node('localhost', 9702);"

3. Occurrence condition
	PostgreSQL：12.3
	citus：9.3-2
	OS：centOS7.3 x86_64

### PR DESCRIPTION
**Pull request by hanefi**
DESCRIPTION: Fixes a bug with lists of configuration values in ALTER ROLE SET statements

An `ALTER ROLE <user> SET <config>=<value>` statement can have a list of values for supported configs. When a new node is added, we can potentially treat the value as a single string and this can result in differing configuration defaults across the cluster.

TODO:
- [x] Allow commas and other characters in the list items.
- [x] Remove banned `memmove()` calls with safer alternatives

Fixes #4012

### CODE REVIEW

**Comment by hanefi** [comment]
During qualification, PostgreSQL down-cases everything that is not in quotes. However when identifiers are placed in a text[] field ( Which is the case in `pg_db_role_settings` ) we should not change the casing.

I'll create a custom parser for `text` -> List of Const Nodes.

File: src/backend/distributed/commands/role.c [hunk 1]
```diff
@@ -776,3 +788,141 @@ ConfigGenericNameCompare(const void *a, const void *b)
...
+ * - Better error mechanisms
+ * - Replace banned memmove calls with pnstrdup
+ *
+ * Inputs:
+ *	configurationList: the input string; must be overwritable!	On return, it's been
+ *					   modified to contain the separated identifiers.
+ *
+ * Returns list of strings that are allocated in the configurationList string
+ *
+ * Note that an empty string is considered okay here, though not in
```
Comment (hanefi) [inline src/backend/distributed/commands/role.c:810]: Outdated comment. I will either add an assertion here, or remove this lines about parsing empty string

File: src/backend/distributed/commands/role.c [hunk 2]
```diff
@@ -776,3 +788,141 @@ ConfigGenericNameCompare(const void *a, const void *b)
...
+/*
+ * SplitConfigurationList --- parse a string containing list of configuration values
+ *
+ * Most of the logic is copied from SplitIdentifierString that is the guts of
+ * textToQualifiedNameList with some changes:
+ * - Unquoted identifiers is not downcased here
+ * - The item seperator is fixed to be a comma as this is the case in pg_db_role_setting
+ * - Simplified set of parameters
+ * - Better error mechanisms
+ * - Replace banned memmove calls with pnstrdup
```
Comment (hanefi) [inline src/backend/distributed/commands/role.c:802]: Outdated comment. I ended up removing pnstrdup calls completely.

File: src/backend/distributed/commands/role.c [hunk 3]
```diff
@@ -776,3 +788,141 @@ ConfigGenericNameCompare(const void *a, const void *b)
...
+ *	configurationList: the input string; must be overwritable!	On return, it's been
+ *					   modified to contain the separated identifiers.
+ *
+ * Returns list of strings that are allocated in the configurationList string
+ *
+ * Note that an empty string is considered okay here, though not in
+ * pg_db_role_setting records.
+ */
+static List *
+SplitConfigurationList(char *configurationList)
```
[the remark this answers is not in the document]
Comment (hanefi) [reply src/backend/distributed/commands/role.c]: Removed the function completely, using the PostgreSQL function SplitIdentifierString now.

File: src/backend/distributed/commands/role.c [hunk 4]
```diff
@@ -776,3 +788,141 @@ ConfigGenericNameCompare(const void *a, const void *b)
...
+	while (scanner_isspace(*nextp))
+	{
+		nextp++;
+	}
+
+	/* do not allow empty string */
+	if (*nextp == '\0')
+	{
+		ereport(ERROR, (errmsg("Mismatched quotation marks"),
+						errhint("TODO: improve error message here")));
```
[the remark this answers is not in the document]
Comment (hanefi) [reply src/backend/distributed/commands/role.c]: Removed the function completely, using the PostgreSQL function SplitIdentifierString now.

File: src/backend/distributed/commands/role.c [hunk 5]
```diff
@@ -776,3 +788,141 @@ ConfigGenericNameCompare(const void *a, const void *b)
...
+		{
+			/* Quoted name --- collapse quote-quote pairs, no downcasing */
+			curname = nextp + 1;
+			for (;;)
+			{
+				endp = strchr(nextp + 1, '"');
+				if (endp == NULL)
+				{
+					ereport(ERROR, (errmsg("Mismatched quotation marks"),
+									errhint("TODO: improve error message here")));
```
[the remark this answers is not in the document]
Comment (hanefi) [reply src/backend/distributed/commands/role.c]: Removed the function completely, using the PostgreSQL function SplitIdentifierString now.

File: src/backend/distributed/commands/role.c [hunk 6]
```diff
@@ -776,3 +788,141 @@ ConfigGenericNameCompare(const void *a, const void *b)
...
+	/* skip leading whitespace */
+	while (scanner_isspace(*nextp))
+	{
+		nextp++;
+	}
+
+	/* do not allow empty string */
+	if (*nextp == '\0')
+	{
+		ereport(ERROR, (errmsg("Mismatched quotation marks"),
```
[the remark this answers is not in the document]
Comment (hanefi) [reply src/backend/distributed/commands/role.c]: Removed the function completely, using the PostgreSQL function SplitIdentifierString now.

File: src/backend/distributed/commands/role.c [hunk 7]
```diff
@@ -776,3 +788,141 @@ ConfigGenericNameCompare(const void *a, const void *b)
...
+						errhint("TODO: improve error message here")));
+	}
```
[the remark this answers is not in the document]
Comment (hanefi) [reply src/backend/distributed/commands/role.c]: Removed the function completely, using the PostgreSQL function SplitIdentifierString now.

File: src/backend/distributed/commands/role.c [hunk 8]
```diff
@@ -410,7 +412,7 @@ MakeVariableSetStmt(const char *config)
 	VariableSetStmt *variableSetStmt = makeNode(VariableSetStmt);
 	variableSetStmt->kind = VAR_SET_VALUE;
 	variableSetStmt->name = name;
-	variableSetStmt->args = list_make1(MakeSetStatementArgument(name, value));
+	variableSetStmt->args = MakeSetStatementArgument(name, value);
```
Comment (thanodnl) [inline src/backend/distributed/commands/role.c:415]: would it make sense to rename this to its plural form? Especially since it is assigned to `args` which is plural on its own.
```suggestion
	variableSetStmt->args = MakeSetStatementArguments(name, value);
```

File: src/backend/distributed/commands/role.c [hunk 9]
```diff
@@ -668,21 +670,42 @@ MakeSetStatementArgument(char *configurationName, char *configurationValue)
...
+					SplitIdentifierString(configurationValueCopy, ',',
+										  &configurationList);
+				}
+				else
+				{
+					configurationList = list_make1(configurationValue);
+				}
+
+				char *configuration = NULL;
+
```
Comment (thanodnl) [inline src/backend/distributed/commands/role.c:703]: nit; this linebreak breaks the logical grouping of `configuration` with the loop it is tied to. Would be great to remove this.

File: src/backend/distributed/commands/role.c [hunk 10]
```diff
@@ -668,21 +670,42 @@ MakeSetStatementArgument(char *configurationName, char *configurationValue)
...
 			case PGC_REAL:
 			{
-				arg = makeFloatConst(configurationValue, -1);
+				Node *arg = makeFloatConst(configurationValue, -1);
+				args = lappend(args, arg);
 				break;
 			}
 
 			case PGC_BOOL:
 			case PGC_STRING:
```
Comment (thanodnl) [inline src/backend/distributed/commands/role.c:686]: It seems Postgres uses Strings and Identifiers the same. Is there any GUC that is a list of strings and should not be treated as an identifier? How does such a guc behave in Postgres?

Examples of string lists seem to include:
 - `plpgsql.extra_warnings`
 - `plpgsql.extra_errors`
 - `DateStyle`
 - `temp_tablespaces` *
 - `session_preload_libraries` *
 - `shared_preload_libraries` *
 - `local_preload_libraries` *
 - `search_path` *
 - `log_destination`
 - `listen_addresses`
 - `synchronous_standby_names`
 - `wal_consistency_checking`

*Some also have `GUC_LIST_QUOTE` set, which we don't seem to use in our logic. Do you know its significance? Some information seems to be encapsulated here https://github.com/postgres/postgres/blob/c410af098c46949e36607eb13689e697fa2def97/src/backend/utils/adt/ruleutils.c#L2759-L2774

Would be great to have tests for both, quoted and non quoted lists to verify both work.

Comment (hanefi) [reply src/backend/distributed/commands/role.c:686]: As of latest `REL_12_STABLE` today (https://github.com/postgres/postgres/commit/17d8cf2897443874fb66d2e4895a049cf961ec58) GUCs that have `GUC_LIST_INPUT` is set are all in the following categories:
- The ones that also have `GUC_LIST_QUOTE` flag set. This means that they will not get downcased ever.
  - temp_tablespaces, session_preload_libraries, shared_preload_libraries, local_preload_libraries, search_path
- Enum values where case is not important
  - DateStyle, log_destination, wal_consistency_checking
- Configuration values that are not allowed on `ALTER ROLE .. SET statements.
  - listen_addresses, synchronous_standby_names

I can add some tests for DateStyle changes without breaking tests I guess.

File: src/backend/distributed/commands/role.c (hunk 9 above)
Comment (hanefi) [reply src/backend/distributed/commands/role.c]: done
