### PR TITLE
Improve WorkerShardStats to avoid invalid value bugs

### LINKED ISSUE #126: Calling master_append_table_to_shard on an empty table can make the table inaccessible
Staging an empty shard causes an empty string to be written to shardminvalue, which can make the table inaccessible if the empty string is not a valid value for the partition column type.

### LINKED ISSUE #669: A bad value in pg_dist_shard causes non-intuitive errors
If shardminvalue or shardmaxvalue contain an empty string instead of NULL queries error out with `ERROR:  invalid input syntax for type timestamp with time zone: ""` instead of something that end-users are likely to understand.

### PR DESCRIPTION
**Pull request by marcocitus**
This is a rewrite of WorkerShardStats to avoid ExecuteRemoteQuery and introduce some better infrastructure for executing remote commands. ExecuteRemoteQuery doesn't check whether return values are NULL, which makes it impossible to distinguish between empty string and NULL results and both are valid min/max results. ExecuteRemoteQuery was always a poor choice for WorkerShardStats, since it can only return 1 column and WorkerShardStats needs several (min, max). As a side-effect of the rewrite, updating the shard statistics we now use only 1 query for min and max, which makes updating shard statistics much faster.

The change does not affect any other code paths that currently rely on ExecuteRemoteQuery or MultiClient* functions.

Fixes #126 
Fixes #669

### CODE REVIEW

File: src/backend/distributed/master/master_stage_protocol.c [hunk 1]
```diff
@@ -314,15 +310,15 @@ master_append_table_to_shard(PG_FUNCTION_ARGS)
...
-	RESUME_INTERRUPTS();
-
 	/* update shard statistics and get new shard size */
 	newShardSize = UpdateShardStatistics(shardId);
 
 	/* calculate ratio of current shard size compared to shard max size */
 	shardMaxSizeInBytes = (int64) ShardMaxSize * 1024L;
 	shardFillLevel = ((float4) newShardSize / (float4) shardMaxSizeInBytes);
 
+	RESUME_INTERRUPTS();
```
Comment (marcocitus) [inline src/backend/distributed/master/master_stage_protocol.c]: Note: I moved this down to avoid erroring out in MultiClientWait if the user cancels, since we want to avoid cancellation here. I separately opened #671, since I don't think we should throw errors from MultiClientWait.

File: src/backend/distributed/executor/multi_client_executor.c [hunk 2]
```diff
@@ -315,6 +315,53 @@ MultiClientConnectionUp(int32 connectionId)
...
+		if (resultStatus == CLIENT_RESULT_READY)
+		{
+			queryReady = true;
+		}
+		else if (resultStatus == CLIENT_RESULT_BUSY)
+		{
+			/* wait for results, errors, or interrupts */
+			MultiClientResetWaitInfo(waitInfo);
+			MultiClientRegisterWait(waitInfo, TASK_STATUS_SOCKET_READ, connectionId);
+			MultiClientWait(waitInfo);
```
Comment (anarazel) [inline src/backend/distributed/executor/multi_client_executor.c]: Hm, if we're doing this synchronously, why are we using the wait info stuff?

Comment (marcocitus) [inline src/backend/distributed/executor/multi_client_executor.c]: I was looking for a way to handle cancellation in this function, though it's not  relevant for master_append_table_to_shard. I could remove the while loop and let it block in MultiClientQueryResult, though I feel like that warrants a /* TODO: handle cancellation */. 

I suppose that if we fix #671 by removing the CHECK_FOR_INTERRUPTS then we would have to check for cancellation explicitly here if we want to handle it. That's something I didn't consider while writing this.

I'd be ok ditching the loop for now, what do you think?

Comment (anarazel) [inline src/backend/distributed/executor/multi_client_executor.c]: Ah, ok. That's a slightly roundabout way - and I don't think it's entirely reliable (because signals don't reliably interrupt poll(), for that you need something like pg_latch.h's stuff, with the self-pipe trick).  I'm fine with leaving it that way, or with leaving it out...

File: src/backend/distributed/executor/multi_client_executor.c [hunk 3]
```diff
@@ -532,6 +579,15 @@ MultiClientGetValue(void *queryResult, int rowIndex, int columnIndex)
 }
 
 
+/* MultiClientValueIsNull returns whether the value at the given position is null. */
+bool
+MultiClientValueIsNull(void *queryResult, int rowIndex, int columnIndex)
+{
+	bool isNull = PQgetisnull((PGresult *) queryResult, rowIndex, columnIndex);
+	return isNull;
+}
```
Comment (anarazel) [inline src/backend/distributed/executor/multi_client_executor.c]: Not in this change, but we really should stop hiding libpq's connection and results, just complicates stuff.

**Comment by anarazel** [comment]
I'm basically inclined to merge this as is, and fix #671 by improving connection handling.

**Comment by anarazel** [comment]
@marcocitus ^

**Comment by marcocitus** [comment]
I'd be fine with that.
