### PR TITLE
Do smarter cleanup of orphaned shards

### LINKED ISSUE #4955: rebalancer can become "permanently" confused if it gets interrupted
In Citus 10.0, we've been doing some testing with killing the coordinator in the middle of a rebalance and it doesn't always recover. The repro steps are:

1. Set up a citus cluster with several nodes and add some distributed tables with data.
2. Set shouldhaveshards = false on one or more nodes.
3. Run "SELECT rebalance_table_shards(shard_transfer_mode := 'force_logical');" on the coordinator to begin rebalancing the shards.
4. While the coordinator node is rebalancing, kill it without doing a graceful shutdown.
5. After a few seconds, start the coordinator node back up and let it recover.
6. Rerun "SELECT rebalance_table_shards(shard_transfer_mode := 'force_logical');" to resume the rebalancing.

We've seen two kinds of errors when doing this:

- "22023: shard 102008 already exists in the target node" - This error is more common and will eventually go away (after a minute or two) if we keep retrying the rebalancing operation.
- "55006: replication slot 'citus_shard_move_subscription' is active for PID 1173" - This error is less common, but when it occurs it does not go away with repeated rebalance attempts. (We retried the rebalancing operation repeatedly for 10 minutes and kept getting the same error.)

This second error was seen repeatedly by @kothapavan35 although I haven't seen it myself.

We are using these postgres settings:

````
citus.defer_drop_after_shard_move = on
citus.defer_shard_delete_interval = 60s
citus.enable_statistics_collection = off
wal_level = logical
wal_receiver_status_interval = 1s
wal_retrieve_retry_interval = 1s
````

We'll update with more details if we can get them.

### PR DESCRIPTION
**Pull request by JelteF**
DESCRIPTION: Do smarter cleanup of orphaned shards

This PR does three things. See commit messages for details:
1. Add citus_cleanup_orphaned_shards UDF
2. Cleanup orphaned shards at the start of a rebalance
3. Cleanup orphaned shards before moving when necessary

Fixes #4955

### CODE REVIEW

File: src/backend/distributed/operations/repair_shards.c [hunk 1]
```diff
@@ -1063,12 +1063,29 @@ EnsureShardCanBeCopied(int64 shardId, const char *sourceNodeName, int32 sourceNo
...
-								"shard " INT64_FORMAT " already exists in the target node",
-								shardId),
-							errdetail(
-								"The existing shard is marked for deletion, but could not be deleted because there are still active queries on it")));
+			/*
+			 * Trigger deletion of orphaned shards and hope that this removes
+			 * the shard.
+			 */
+			DropMarkedShardsInDifferentTransaction();
+			shardPlacementList = ShardPlacementList(shardId);
```
Comment (marcocitus) [inline src/backend/distributed/operations/repair_shards.c:1071]: are we guaranteed that the change is in the snapshot here?

File: src/backend/distributed/operations/repair_shards.c [hunk 2]
```diff
@@ -1063,12 +1063,29 @@ EnsureShardCanBeCopied(int64 shardId, const char *sourceNodeName, int32 sourceNo
...
-							errmsg(
-								"shard " INT64_FORMAT " already exists in the target node",
-								shardId),
-							errdetail(
-								"The existing shard is marked for deletion, but could not be deleted because there are still active queries on it")));
+			/*
+			 * Trigger deletion of orphaned shards and hope that this removes
+			 * the shard.
+			 */
+			DropMarkedShardsInDifferentTransaction();
```
[the remark this answers is not in the document]
Comment (marcocitus) [reply src/backend/distributed/operations/repair_shards.c:1070]: I don't think it can be blocked for more than a few network round trips, while shard moves can take hours.

File: src/backend/distributed/operations/repair_shards.c (hunk 1 above)
Comment (JelteF) [reply src/backend/distributed/operations/repair_shards.c:1071]: We indeed do call `AcceptInvalidationMessages`. Also the tests pass.

File: src/backend/distributed/operations/shard_cleaner.c [hunk 3]
```diff
@@ -12,42 +12,94 @@
...
+ * connecting to localhost. This is done, so that the locks that
+ * DropMarkedShards takes are only held for a short time.
+ */
+void
+DropMarkedShardsInDifferentTransaction(void)
+{
+	int connectionFlag = FORCE_NEW_CONNECTION;
+	MultiConnection *connection = GetNodeConnection(connectionFlag, LocalHostName,
+													PostPortNumber);
+	ExecuteCriticalRemoteCommand(connection, "CALL citus_cleanup_orphaned_shards();");
```
Comment (marcocitus) [inline src/backend/distributed/operations/shard_cleaner.c:101]: super minor: semicolons are redundant when sending a single statement

**Review by marcocitus — APPROVED** [review]
Looks good to me after addressing open comments.
