### PR TITLE
Replace native hash function with worker_hash

### LINKED ISSUE #1279: INSERT INTO SELECT fails if the partition column doesn't have a native hash function
**How to replicate**

```sql
CREATE TABLE test
(
    id BIGINT,
    time DATE
);

CREATE TABLE test_second
(
    id BIGINT,
    time DATE
);

SELECT create_distributed_table('test', 'time');
SELECT create_distributed_table('test_second', 'time');

INSERT INTO test_second SELECT * FROM test;
```

Fails with 
```sql
postgres=# INSERT INTO test_second SELECT * FROM test;
ERROR:  function pg_catalog.hashint4(date) does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
CONTEXT:  while executing command on localhost:9700
```

**Reason:** PostgreSQL does not have a native hash function for every data type. As a result, if the partition key is one of them like date, bytea the worker query fails. 

**Fix:** We had the same problem in tenant isolation. For a proper fix, we can replace hash_xxx function calls with [worker_hash()](https://github.com/citusdata/citus/blob/4a84ee5512f94bab15d38377abdf646e016586b3/src/backend/distributed/master/master_split_shards.c#L61) function. Check the enterprise repo for example usage!

### PR DESCRIPTION
**Pull request by velioglu**
Fixes #1279.

Since partition columns without native hash function error out while using them with INSERT INTO ... SELECT queries, native hash function is replaced by worker_hash function.

### CODE REVIEW

**Comment by onderkalaci** [comment]
> hashint4 function is replaced by worker_hash functio

A minor note on the title: I think this definition does not look accurate enough. `INSERT .. SELECT` does not necessarily uses `inthash4`, it uses `partition_key_hash_func` when necessary.

**Comment by sumedhpathak** [comment]
Is this only for Insert...Select queries? Or are we replacing the hash-function for all hash-partitioned types?

**Comment by metdos** [comment]
> Is this only for Insert...Select queries? Or are we replacing the hash-function for all hash-partitioned types?

This is just for Insert...Select queries. We use same hash-functions but they will be resolved at worker nodes.

File: src/test/regress/sql/multi_insert_select.sql [hunk 1]
```diff
@@ -1574,6 +1574,29 @@ INSERT INTO text_table (part_col) SELECT val FROM text_table;
...
+(
+    id BIGINT,
+    time DATE
+);
+
+SELECT create_distributed_table('test', 'time');
+SELECT create_distributed_table('test_second', 'time');
+
+INSERT INTO test VALUES(1, '11-11-1980');
+INSERT INTO test_second SELECT * FROM test;
```
Comment (metdos) [inline src/test/regress/sql/multi_insert_select.sql]: Maybe, we can use more meaningful names for temporary tables;

`test ` -> `raw_table`
`test_second ` -> `summary_table`

Then;
```sql
INSERT INTO summary_table SELECT time, count(*) FROM raw_table;
```

File: src/backend/distributed/utils/metadata_cache.c [hunk 2]
```diff
@@ -1452,6 +1455,28 @@ CitusExtraDataContainerFuncId(void)
 }
 
 
+/* return oid of the worker_hash function */
+Oid
+CitusWorkerHashFunctionId(void)
+{
+	Oid citusExtensionOid = InvalidOid;
+	Oid citusSchemaOid = InvalidOid;
+	char *citusSchemaName = 0;
```
Comment (metdos) [inline src/backend/distributed/utils/metadata_cache.c]: This should be NULL because this is a pointer.

Comment (metdos) [inline src/backend/distributed/utils/metadata_cache.c]: Actually, we can get these declarations into if block (they are only used there) and merge them with definitions.

File: src/test/regress/sql/multi_insert_select.sql [hunk 3]
```diff
@@ -1574,6 +1574,29 @@ INSERT INTO text_table (part_col) SELECT val FROM text_table;
...
+(
+    id BIGINT,
+    time DATE
+);
+
+SELECT create_distributed_table('raw_table', 'time');
+SELECT create_distributed_table('summary_table', 'time');
+
+INSERT INTO raw_table VALUES(1, '11-11-1980');
+INSERT INTO summary_table SELECT * FROM raw_table;
```
Comment (metdos) [inline src/test/regress/sql/multi_insert_select.sql]: This looks more meaningful I think;

```sql
INSERT INTO summary_table SELECT time, count(*) FROM raw_table GROUP BY time;
```

So we also need to update the `summary_table` table.
```sql
CREATE TABLE summary_table
 (
          time DATE,
          count BIGINT
 );
```

**Comment by metdos** [comment]
Looks good 🚀
