### PR TITLE
Prevent undistribute_table calls for foreign tables

### LINKED ISSUE #4274: undistribute_table() fails on cstore foreign tables
'undistribute_table()' calls fail for foreign tables. We issue `DROP TABLE .. CASCADE` commands that should have been `DROP FOREIGN TABLE .. ` instead.

Steps to reproduce:

```bash
wget http://examples.citusdata.com/customer_reviews_1998.csv.gz
wget http://examples.citusdata.com/customer_reviews_1999.csv.gz

gzip -d customer_reviews_1998.csv.gz
gzip -d customer_reviews_1999.csv.gz
```

```sql
-- load extension first time after install
CREATE EXTENSION cstore_fdw;

-- create server object
CREATE SERVER cstore_server FOREIGN DATA WRAPPER cstore_fdw;

-- create foreign table
CREATE FOREIGN TABLE customer_reviews
(
    customer_id TEXT,
    review_date DATE,
    review_rating INTEGER,
    review_votes INTEGER,
    review_helpful_votes INTEGER,
    product_id CHAR(10),
    product_title TEXT,
    product_sales_rank BIGINT,
    product_group TEXT,
    product_category TEXT,
    product_subcategory TEXT,
    similar_product_ids CHAR(10)[]
)
SERVER cstore_server
OPTIONS(compression 'pglz');

SELECT create_distributed_table('customer_reviews', 'customer_id');

\COPY customer_reviews FROM 'customer_reviews_1998.csv' WITH CSV;

SELECT undistribute_table('customer_reviews');
```

The error messages:
```
...
NOTICE:  00000: Dropping the old public.customer_reviews
LOCATION:  ReplaceTable, create_distributed_table.c:1744
NOTICE:  00000: issuing ROLLBACK
DETAIL:  on server hanefi@localhost:12001 connectionId: 1
LOCATION:  LogRemoteCommand, remote_commands.c:343
NOTICE:  00000: issuing ROLLBACK
DETAIL:  on server hanefi@localhost:12002 connectionId: 2
LOCATION:  LogRemoteCommand, remote_commands.c:343
ERROR:  42809: "customer_reviews" is not a table
HINT:  Use DROP FOREIGN TABLE to remove a foreign table.
CONTEXT:  SQL statement "DROP TABLE public.customer_reviews CASCADE"
LOCATION:  DropErrorMsgWrongType, tablecmds.c:1221
```

### PR DESCRIPTION
**Pull request by hanefi**
To undistribute a table, the list of commands for a foreign table are quite different than regular distributed tables. Therefore Citus should error out until the support for foreign tables are covered.

fixes #4274 

TODO:
- [x] add some tests with a foreign distributed table so that the newly introduced lines are covered by the test suite

### CODE REVIEW

File: src/backend/distributed/commands/create_distributed_table.c [hunk 1]
```diff
@@ -294,7 +295,7 @@ undistribute_table(PG_FUNCTION_ARGS)
 	EnsureCoordinator();
 	EnsureRelationExists(relationId);
 	EnsureTableOwner(relationId);
-
+	EnsureTableNotForeign(relationId);
```
Comment (halilozanakgul) [inline src/backend/distributed/commands/create_distributed_table.c:298]: This looks fine but maybe we can add this check in the `UndistributeTable` function instead with the other checks.
I think the checks here are to see if we can use `undistribute_table` UDF but the ones in `UndistributeTable` are for checking if we can actually undistribute the table.

**Review by halilozanakgul — CHANGES_REQUESTED** [review]

**Review by halilozanakgul — APPROVED** [review]
