### PR TITLE
Early error out when creating citus local from a temp table

### LINKED ISSUE #4533: Strange error message when adding a foreign key from a temp table to a reference table
Pretty minor and totally expected, but the error is a bit confusing:
```sql
create temp table loc as select s as x, s as y from generate_series(1,1) s;
alter table loc add constraint fk foreign key (x) references ref (a) on delete cascade;
...
NOTICE:  issuing CREATE SCHEMA IF NOT EXISTS pg_temp_7 AUTHORIZATION marco
DETAIL:  on server marco@localhost:1302 connectionId: 14
ERROR:  unacceptable schema name "pg_temp_7"
DETAIL:  When adding a foreign key from a local table to a reference table, Citus applies a conversion to all the local tables in the foreign key graph
CONTEXT:  while executing command on localhost:1302
```

### PR DESCRIPTION
**Pull request by onurctirtir**
Closes #4533

### CODE REVIEW

File: src/backend/distributed/commands/citus_add_local_table_to_metadata.c [hunk 1]
```diff
@@ -362,6 +362,13 @@ ErrorIfUnsupportedCitusLocalTableKind(Oid relationId)
 							   "tables and foreign tables can be added to citus metadata ",
 							   relationName)));
 	}
+
+	if (get_rel_persistence(relationId) == RELPERSISTENCE_TEMP)
+	{
+		ereport(ERROR, (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
+						errmsg("cannot add temporary table \"%s\" to citus metadata",
```
Comment (marcocitus) [inline src/backend/distributed/commands/citus_add_local_table_to_metadata.c:369]: Would this make sense in the context of adding a foreign key or a CREATE TABLE?  (as in, would the user know what the problem is and how to fix it?)

Comment (onurctirtir) [reply src/backend/distributed/commands/citus_add_local_table_to_metadata.c:369]: >would the user know what the problem is

yeah, we catch the error messages in utility hook and give below detail in addition to the error message that we give here
https://github.com/citusdata/citus/blob/cacb76d2c6a70383ad5d7c597daa2298e446ac2b/src/backend/distributed/commands/table.c#L870..L874

>and how to fix it?

Maybe I should give a hint for that:
`HINT: Consider using persistent or unlogged tables`

Here I wish to tell `or drop the foreign key` to provide another alternative but since this is `CreateCitusLocalTable` function, it doesn't seem much reasonable/possible.

What do do you think @marcocitus ?

Comment (marcocitus) [reply src/backend/distributed/commands/citus_add_local_table_to_metadata.c:369]: actually, you cannot create foreign keys from temporary table to regular tables at all, so we should just let it fall through / give the same error as postgres.
```sql
postgres=# create table ref (a int primary key);
CREATE TABLE
postgres=# create temp table tmp (a int references ref (a));
ERROR:  constraints on temporary tables may reference only temporary tables
```

Comment (onurctirtir) [reply src/backend/distributed/commands/citus_add_local_table_to_metadata.c:369]: Makes sense, then I guess I should give this error around `ConvertPostgresLocalTablesToCitusLocalTables` (not in `CreateCitusLocalTable`) since `CreateCitusLocalTable` might not be the right place to mention "constraints on temporary tables" ?

Comment (onurctirtir) [reply src/backend/distributed/commands/citus_add_local_table_to_metadata.c:369]: (or for simplicity, let's give the same error in `CreateCitusLocalTable`)

Comment (onurctirtir) [reply src/backend/distributed/commands/citus_add_local_table_to_metadata.c]: cc38e48

**Review by marcocitus — APPROVED** [review]
