### PR TITLE
Fix/task execution

### LINKED ISSUE #3940: Explain Analyze unrecognized node type error
When we use explain with a query that involves repartition joins, it seems that it is possible to get "unrecognized node type" error. For example if we run one of the ch benchmark queries with explain analyze, so if we add the following to the `chbenchmark_all_queries.sql` file:

```sql
\set default_analyze_flags '(ANALYZE on, COSTS off, TIMING off, SUMMARY off)'
EXPLAIN :default_analyze_flags SELECT
    su_name,
    su_address
FROM
    supplier,
    nation
WHERE su_suppkey in
      (SELECT
           mod(s_i_id * s_w_id, 10000)
       FROM
           stock,
           order_line
       WHERE s_i_id IN
             (SELECT i_id
              FROM item
              WHERE i_data LIKE 'co%')
       AND ol_i_id = s_i_id
       AND ol_delivery_d > '2008-05-23 12:00:00' -- was 2010, but our order is in 2008
       GROUP BY s_i_id, s_w_id, s_quantity
       HAVING   2*s_quantity > sum(ol_quantity))
  AND su_nationkey = n_nationkey
  AND n_name = 'Germany'
ORDER BY su_name;
```

`make check-minimal EXTRA_TESTS=chbenchmark_all_queries`:

we get :

```diff
+WARNING:  could not dump unrecognized node type: 2139062143
+WARNING:  could not dump unrecognized node type: 2139062143
+WARNING:  could not dump unrecognized node type: 2139062143
+WARNING:  could not dump unrecognized node type: 2139062143
+ERROR:  unrecognized node type: 2139062143
```

This seems to be related to outfuncs, so probably some repartition related field is missing or using an incorrect function

### PR DESCRIPTION
**Pull request by SaitTalhaNisanci**
DESCRIPTION: Fix explain analyze on adaptive executor repartitions

Adaptive executor is using a utility method from task tracker for
repartition joins, however adaptive executor doesn't need taskExecution.
It is only used by task tracker. This causes a problem when explain
analyze is used because what taskExecution is pointing to might be
random.

We solve this by not setting taskExecution from adaptive executor. So it
will stay NULL as set by CreateTask.

Note that we are already removing this with https://github.com/citusdata/citus/pull/3850/commits/dafa39ebeea69ee131a7ed23dbd41e622d3dcbd6

The root cause of this is as explained by @pykello:
Tasks themselves are created by planner, while task->taskExecution is created by executor. So when the memory context that ran executor is reset, everything else stays valid except for task->taskExecution. When I add some breakpoints, I see that that we call the GetDistributedPlan() for the same distributed plan multiple times, some of them after the executor has already done some processing for that distributed plan. We call CheckNodeCopyAndSerialization() there. We have left over taskExecution in the distributed plan tasks from a previous call to AdaptiveExecutor, which is now out of context, hence the failure.

Fixes #3940.

### CODE REVIEW

File: src/backend/distributed/executor/multi_task_tracker_executor.c [hunk 1]
```diff
@@ -452,7 +453,7 @@ MultiTaskTrackerExecute(Job *job)
  * execution to a list. The function then returns the list.
  */
 List *
-TaskAndExecutionList(List *jobTaskList)
+TaskAndExecutionList(List *jobTaskList, bool viaTaskTracker)
```
Comment (JelteF) [inline src/backend/distributed/executor/multi_task_tracker_executor.c:456]: This function name and comment is quite confusing now. If you pass `viaTaskTracker` you don't actually do anything with a `TaskExecution`. I'd suggest giving it a different name, like:
```c
CreateTaskList(List *jobTaskList, bool withTaskExecution)
```

And update the comment to include something about the `dependendTaskList`, because that's all it does for the adaptive executor afaict.

**Comment by onderkalaci** [comment]
>  This causes a problem when explain
analyze is used because what taskExecution is pointing to might be
random.

Can  you elaborate on this more? Why does EXPLAIN ANALYZE needs that field?

**Comment by JelteF** [comment]
> Can you elaborate on this more? Why does EXPLAIN ANALYZE need that field?

It copies the task at some point and our copyfuncs start reading this `taskExecution` field, but for some reason it points to invalid memory at that point. My guess would be because of a cleared MemoryContext or something.

File: src/backend/distributed/executor/repartition_join_execution.c [hunk 2]
```diff
@@ -63,7 +63,8 @@ ExecuteDependentTasks(List *topLevelTasks, Job *topLevelJob)
 {
 	EnsureNoModificationsHaveBeenDone();
 
-	List *allTasks = TaskAndExecutionList(topLevelTasks);
+	bool createTaskExecutor = false;
```
Comment (JelteF) [inline src/backend/distributed/executor/repartition_join_execution.c:66]:
```suggestion
	bool createTaskExecution = false;
```

**Comment by SaitTalhaNisanci** [comment]
Yeah I also think that the problem is related to memory contexts.  Copy functions and out functions are called with EXPLAIN ANALYZE and taskExecution is in copy and out functions. When it points to an invalid memory, we just see random node ids.

But adaptive executor shouldn't be using `taskExecution` field, so now we are keeping it NULL

**Comment by onderkalaci** [comment]
> It copies the task at some point and our copyfuncs start reading this taskExecution field, but for some reason it points to invalid memory at that point. My guess would be because of a cleared MemoryContext or something.

Would it make sense to look into how to fix this underlying issue? 

(I think it'd be good to avoid passing such a boolean flag. It fixes the issue but kind of interesting/hard to understand thing. Why do we care about `createTaskExecution ` field so much that we pass this flag?)

**Comment by onderkalaci** [comment]
> My guess would be because of a cleared MemoryContext or something.

Or, another question I have is that: Are we confident that this wouldn't cause an issue with regular query executions?

**Comment by onderkalaci** [comment]
> But adaptive executor shouldn't be using taskExecution field, so now we are keeping it NULL

Is adaptive executor using it? I guess no?

**Comment by SaitTalhaNisanci** [comment]
>Are we confident that this wouldn't cause an issue with regular query executions?

TaskExecution is only used by task tracker.  Adaptive executor isn't using it, hence it should be fine to keep taskExecution NULL with adaptive executor. So I think it shouldn't have any side effect with other queries.

**Comment by onderkalaci** [comment]
> TaskExecution is only used by task tracker. Adaptive executor isn't using it, hence it should be fine to keep taskExecution NULL with adaptive executor. So I think it shouldn't have any side effect with other queries.

If it is a memory context issue, are we sure that other fields are all allocated in the correct memory context and only `TaskExecution ` is in a wrong context?

I'd suggest we understand the root cause a little more before merging this.

**Comment by pykello** [comment]
Looked briefly into why this is caused, my current understanding with some gaps is:

Tasks themselves are created by planner, while task->taskExecution is created by executor. So when the memory context that ran executor is reset, everything else stays valid except for `task->taskExecution`. When I add some breakpoints, I see that that we call the `GetDistributedPlan()` for the **same** distributed plan multiple times. We call `CheckNodeCopyAndSerialization()` there. We have left over taskExecution in the distributed plan tasks from a previous call to AdaptiveExecutor, which is now out of context, hence the failure.

I think proper way to solve this to not put anything in `struct Task` that is allocated by the executor, which is done by removing the task tracker. Until then, current solution is also reasonable.

**Comment by pykello** [comment]
@SaitTalhaNisanci Also similar issue might happen using prepared statements, since we reuse the same plan for multiple executions there too. Might be worth spending some time thinking about if there are some cases there with regular non-EXPLAIN ANALYZE executions for which we need to worry about.

**Comment by JelteF** [comment]
> I think proper way to solve this to not put anything in struct Task that is allocated by the executor, which is done by removing the task tracker (as pointed by others). 

This makes sense. In that case a better way to solve this issue might be to allocate the `taskExecution` inside the same MemoryContext as the `Task`. That way it will simply stay valid for it's whole lifetime. This can be done using:
```c
MemoryContext oldContext = MemoryContextSwitchTo(GetMemoryChunkContext(task));
// create taskexecution
MemoryContextSwitchTo(oldContext);
```

**Comment by SaitTalhaNisanci** [comment]
>This makes sense. In that case a better way to solve this issue might be to allocate the taskExecution inside the same MemoryContext as the Task. That way it will simply stay valid for it's whole lifetime. This can be done using:

I think that makes sense, but for adaptive executor we shouldn't set this field since it doesn't need it. For task tracker we can apply your suggestion on top of the current PR, what do you think? Or is it okay to merge the current version as well?

**Comment by SaitTalhaNisanci** [comment]
I have added this commit: 7366e9b9436a57fc674059f9f5d0a66b2d89c612

And as expected it solves the issue without the if check we are adding in this PR. But I'll keep the if check since it seems more correct not to set taskExecution with adaptive executor.
