### PR TITLE
Ensure query is deparse safe for DELETE and UPDATE.

### LINKED ISSUE #8198: Crash raised by Delete statement.(PG17.2 citus 13.0.3)
citus version:
```sql
SELECT citus_version();
---Citus 13.0.3 on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
```
PG version: 17.2
schema:
```sql
---create 5 workers, and we also found the bug can be reproduced without workers
select * from citus_add_node('docker-worker1-1', 5432);

select * from citus_add_node('docker-worker2-1', 5432);

select * from citus_add_node('docker-worker3-1', 5432);

select * from citus_add_node('docker-worker4-1', 5432);

select * from citus_add_node('docker-worker5-1', 5432);

DROP TABLE IF EXISTS t6;
create table t6 ( 
vkey int4 ,
pkey int4 ,
c8 timestamp ,
c9 numeric ,
c10 numeric ,
c11 text ,
c12 text ,
c13 int4 ,
c14 int4 ,
c15 timestamp 

);SELECT create_reference_table('t6');
DROP TABLE IF EXISTS t9;
create table t9 ( 
vkey int4 ,
pkey int4 ,
c25 numeric ,
c26 int4 

);SELECT create_reference_table('t9');
DROP TABLE IF EXISTS t12;
create table t12 ( 
vkey int4 ,
pkey int4 ,
c16 int4 ,
c17 int4 ,
c18 timestamp ,
c19 numeric ,
c20 int4 ,
c21 text ,
c22 text ,
c23 text ,
colocated_key int4 

);SELECT create_distributed_table('t12','colocated_key', colocate_with:='t10');
DROP TABLE IF EXISTS t18;
create table t18 ( 
vkey int4 ,
pkey int4 ,
c24 timestamp 

);SELECT create_distributed_table('t18','vkey', colocate_with:='t17');
DROP TABLE IF EXISTS t20;
create table t20 ( 
vkey int4 ,
pkey int4 ,
c0 int4 ,
c1 int4 ,
c2 text ,
c3 numeric ,
c4 numeric ,
c5 timestamp ,
c6 int4 ,
c7 numeric 

);SELECT create_distributed_table('t20','vkey', colocate_with:='t18');
```
query:
```sql
--- query
delete from t18
where 
((false::bool) in (select  
          null::bool as c_0
        from 
          t12 as ref_0
        where (ref_0.c23) !~~* (ref_0.c22)
      except
      select  
          true::bool as c_0
        from 
          t18 as ref_1
        where exists (
          select  
              ref_2.c1 as c_0, 
              ref_2.c6 as c_1, 
              ref_2.pkey as c_2
            from 
              t20 as ref_2
            where false::bool))) 
  or ((pg_catalog.citus_version()) <= ( 
    select  
        'arKwIv+u}<7XL?*74+YE' as c_0
      from 
        (t20 as ref_3
          full outer join t6 as ref_4
          on (ref_3.vkey = ref_4.vkey ))
      where (false::bool) 
        or (exists (
          select  
              ref_5.vkey as c_0, 
              (ref_3.c3) = (ref_4.c10) as c_1, 
              ref_5.c25 as c_2, 
              (select c2 from t20 order by c2 limit 1 offset 6)
                 as c_3, 
              ref_5.vkey as c_4, 
              (select vkey from t12 order by vkey limit 1 offset 1)
                 as c_5, 
              ref_5.pkey as c_6, 
              ref_5.c25 as c_7, 
              ref_5.c25 as c_8, 
              ref_5.vkey as c_9
            from 
              t9 as ref_5
            where (ref_4.c11) >= ('')))
      order by c_0 desc
       limit 1))
```

log from coordinator:

[coord_20250917_0725-0740.log](https://github.com/user-attachments/files/22379839/coord_20250917_0725-0740.log)

### PR DESCRIPTION
**Pull request by colm-mchugh**
DESCRIPTION: If a modify scan needs to evaluate expressions before worker query execution, ensure the query remains safe for deparse.
    
At the start of a modification scan, the coordinator may need to evaluate expressions (e.g. nextval) before calling worker(s). This can apply transformations that cause query deparsing to error out or worse throw an assert fail, as uncovered by issue #8198. The fix adds an extra step to ensure that the query structure is safe to deparse, and tweak if it is not, before rebuilding the query SQL by deparsing.
    
Fixes #8198.

### CODE REVIEW

File: src/backend/distributed/executor/citus_custom_scan.c [hunk 1]
```diff
@@ -1038,3 +1047,78 @@ EnsureForceDelegationDistributionKey(Job *job)
...
+{
+	if (expr == NULL)
+	{
+		return false;
+	}
+
+	if (IsA(expr, SubLink))
+	{
+		SubLink *sublink = (SubLink *) expr;
+		Node *testexpr = sublink->testexpr;
```
Comment (alperkocatas) [inline src/backend/distributed/executor/citus_custom_scan.c:1075]: We are walking the `testexpr` field, but it looks like the SubLink struct also has a `subselect` field. Could there be a possibility that the `subselect` field of the SubLink also has some expression that we need to walk?

File: src/backend/distributed/executor/citus_custom_scan.c [hunk 2]
```diff
@@ -426,7 +429,13 @@ CitusBeginModifyScan(CustomScanState *node, EState *estate, int eflags)
 		/*
 		 * When there is no deferred pruning, but we did evaluate functions, then
 		 * we only rebuild the query strings in the existing tasks.
+		 *
+		 * Note that because we did evaluate functions we should also
+		 * sanity check the query first, to prevent issues like #8198
```
Comment (alperkocatas) [inline src/backend/distributed/executor/citus_custom_scan.c:434]: I tried to make a quick search o the source code to see if we used issue references like \#8198 directly from inside the source code, but I could not find one (except the test files). I can understand the rationale, it has advantages, but it also could have some disadvantages such as making the source code tightly coupled to the issue numbers in github. Maybe we can also add some more information here to explain what 8198 is about? Anyway, this is just a comment, no need to change anything if you feel this is the right way to do.

File: src/backend/distributed/executor/citus_custom_scan.c [hunk 3]
```diff
@@ -1038,3 +1047,78 @@ EnsureForceDelegationDistributionKey(Job *job)
...
+		if (testexpr && IsA(testexpr, BoolExpr) && ((BoolExpr *) testexpr)->boolop ==
+			NOT_EXPR)
+		{
+			Node *arg = linitial(((BoolExpr *) testexpr)->args);
+
+			/*
+			 * testexpr is of the form: NOT (arg)
+			 * convert NOT (arg) to FALSE = arg
+			 */
+			sublink->testexpr = (Node *) make_opclause(BooleanEqualOperator, BOOLOID,
```
Comment (alperkocatas) [inline src/backend/distributed/executor/citus_custom_scan.c:1086]: Could there be an error case where `make_opclause` returns NULL, and we overwrite the `testexpr` with NULL value. Should we make a NULL check and error out if that happens?

File: src/backend/distributed/executor/citus_custom_scan.c (hunk 2 above)
Comment (colm-mchugh) [reply src/backend/distributed/executor/citus_custom_scan.c:434]: Good point, have updated the comment to include actual details of the problem.

File: src/backend/distributed/executor/citus_custom_scan.c (hunk 1 above)
Comment (colm-mchugh) [reply src/backend/distributed/executor/citus_custom_scan.c:1075]: The `subselect` field is walked when control passes to the `expression_tree_walker()` call after this `if (IsA(expr, SubLink))` check.

File: src/backend/distributed/executor/citus_custom_scan.c (hunk 3 above)
Comment (colm-mchugh) [reply src/backend/distributed/executor/citus_custom_scan.c:1086]: Looking at how `make_opclause` is used elsewhere, both in Citus and Postgres, there is no such check so I prefer to keep in line with that. The only problem I can foresee is that there isn't enough memory and Postgres' memory management (or the OS) will probably error out in that case.

**Review by alperkocatas — APPROVED** [review]
