### PR TITLE
make task cleanup logic less error prone

### LINKED ISSUE #345: Change job cleanup logic in task tracker executor
When the task tracker executor completes a query, it asks worker nodes to clean up resources associated with the query. If the task tracker executor doesn't hear back from a worker node in 150ms, it times out with the following:

<pre>
WARNING:  could not receive response for cleanup query for job 38041 on node
</pre>

Each task occupies shared memory on the worker nodes. If enough cleanup queries time out, we run into the following issue. The only workaround at this stage is to restart the worker node.

<pre>
[unknown] 2016-02-04 23:23:36.693 UTC LOG:  statement: SELECT task_tracker_assign_task  (38047, 2147483647, 'SELECT task_tracker_cleanup_job(38047)')
[unknown] 2016-02-04 23:23:36.693 UTC WARNING:  out of shared memory
[unknown] 2016-02-04 23:23:36.693 UTC ERROR:  out of shared memory
[unknown] 2016-02-04 23:23:36.693 UTC HINT:  You might increase max_tracked_tasks_per_node.
</pre>

The original motivation behind timing out was to make sure that the ``SELECT`` query doesn't block when query results are ready. However, we received enough reports on this particular issue that we should consider simply waiting on ``task_tracker_assign_task(..., task_tracker_cleanup_job(...)``.

### PR DESCRIPTION
**Pull request by mtuncer**
Changed task cleanup logic to remove one large sleep and replaced that with multiple small sleeps until a predetermined timeout occurs.

We used to wait for 150 milliseconds or twice the RemoteTaskCheckInterval whichever is larger before checking if task cleanup job is sent to worker. This approach had problems when there is a load on the master. Cleanup jobs were never delivered to worker, and resources for the job were never released. It had 2 consequences, 1 - warning on the master about job not being cleaned. 2- more importantly, worker run out of shared memory since resources were not reclaimed.

Now it is changed to give more chances to master to deliver the cleanup task. We check every 10 milliseconds until we reach a timeout of Max(200 milliseconds or 2xRemoteTaskCheckInterval). 

Increasing minimum timeout will not have adverse affect on query performance since it is the worse case scenario, most cleanup tasks will be sent before that and we will wait way less than before.

fixes #345 

CR : not determined yet

### CODE REVIEW

**Comment by marcocitus** [comment]
Hey Murat, Why don't we remove the timeout altogether? i.e. remove pg_usleep and call MultiClientQueryStatus on each connection directly. MultiClientQueryStatus will block until the result comes back (or the connection dies). Most of the time clean-up will finish faster than it does now, since there is no forced waiting. Moreover, it's important that we finish these tasks even if they take a little time.

**Comment by mtuncer** [comment]
@marcocitus  I was hesitant to put unbounded block there. @ozgune do you agree on blocking ?

**Comment by marcocitus** [comment]
Lots of things block without timeouts, even in the task-tracker executor (e.g. when assigning tasks). This timeout had a good intention, but ended up providing almost 0 benefit and a quite a few headaches. It was based on the assumption that cleanup failures are less important than query failures, but it's actually the other way around.

There's possibly a separate task of avoid blocking calls and replacing them with poll() with timeouts across the codebase, but that's beyond scope.

**Comment by ozgune** [comment]
@mtuncer -- I'm happy to remove the timeout and just block here.

We already have a connection open, and we're only blocking on sending the "job cleanup" request (and not on its execution).

**Comment by anarazel** [comment]
I don't think that's an as low impact change as one might think. The current non-blocking cancellation approach allows the TCP connections to the various workers to be parallelized.  Going to a one-by-one blocking approach has the potential to be slower with a significant number of nodes.

If you look at the code, I think the problem isn't/wasn't really the non-blocking nature, but that it's simply buggy. The first loop *starts* to send a cancellation. But it's not guaranteed that that actually makes it to the OS, if the tcp buffers are full.   Which means we'll then sleep waiting for something to finish that cannot finish, because it hasn't happened yet.

**Comment by anarazel** [comment]
Btw, the issue with the current code mentioned above, will be a lot more frequent with ssl/tls (which needs to send larger packets, including sometimes having to wait for the remote side when sending data). Which would be in line with what @samay-sharma has observed with a customer.

**Comment by mtuncer** [comment]
I also tested blocking approach in branch https://github.com/citusdata/citus/tree/alternate_task_cleanup . There is no observable performance difference.

Both performed well in our only machine that the issue can be reproduced.

**Comment by marcocitus** [comment]
> If you look at the code, I think the problem isn't/wasn't really the non-blocking nature, but that it's simply buggy. The first loop starts to send a cancellation. But it's not guaranteed that that actually makes it to the OS, if the tcp buffers are full. 

I don't think we set the connections to nonblocking mode, so pqSendQuery should block until the data has been passed to the TCP buffer.

**Comment by anarazel** [comment]
@marcocitus Partially true. But the problem is that you can't just write stuff. To guarantee progress you might *first* have to read data from the wire. Otherwise the remote side might not be able to send you data. And that leaves you with the same situation.   Imagine e.g. all the cancelled backends trying to send responses back. Since we send all cancellations and then block, the incoming tcp buffers will potentially fill up. So they'll go into retrying to send data. If you then accept data socket-by-socket in a blocking manner you'll have to wait for retransmission timeouts on each.

(There's also some stuff with SSL/TLS making this more of an issue)

**Comment by anarazel** [comment]
Independent of what's mentioned in this issue so far, there's also the issue that we might fail to send cancel requests out, because the connection is marked as currently being busy. That could e.g. be the case if a query is cancelled, because then we'll skip to cleanup in ManageTaskExecution(), without any guarantee tasks aren't in connectionBusy state.

**Comment by marcocitus** [comment]
> To guarantee progress you might first have to read data from the wire. 

Sure, but PQsendQuery does this for you.

**Comment by anarazel** [comment]
Don't see how. It only reads data if it could not send all the data.  It'll not solve the fact that the *remote* might try to send data, and fail, because the tcp buffers are full.

**Comment by marcocitus** [comment]
I'm not saying that iteratively blocking on PQgetResult is the optimal solution in all cases, but it will be most of the time and seems like the simplest solution. PQgetResult may sometimes take a few ms if there's a lot of pending data after a cancellation and for very large clusters doing that N times becomes noticeable. I think we should opt for code simplicity unless this actually becomes an issue, though the only way I can see it becoming an issue is if the master and workers are in different regions.

**Comment by mtuncer** [comment]
I think we can make the call now.

We won't be able to get any log data if we block indefinitely and somehow got stuck in there. Shall we go for non-blocking version and observe the behavior ? 

@marcocitus , @anarazel  ?

**Comment by sumedhpathak** [comment]
@anarazel @marcocitus Any resolution on approach here?

**Comment by marcocitus** [comment]
@anarazel @mtuncer 
Hey Murat, sorry for the delay. Me and Andres discussed this today. What initially ticked me off a bit about this change is the short timeout. I think it should be something comfortably high like 4 seconds. It should only take that long if there is a problem with the node.

I think the cleanup code is where it is mainly because it was easy to put it there, but if the code is becoming more complicated and doing polling then the proper place to put it is would be the main task tracker state machine / ManageTaskTracker, but that would require more effort.

Anyway, I'm not strongly opposed to the current approach, but just change 200 to 4000 to make me sleep comfortably :).

**Comment by mtuncer** [comment]
4000 then
code is rebased/squashed ready to merge on final approval

File: src/backend/distributed/executor/multi_task_tracker_executor.c [hunk 1]
```diff
@@ -2821,44 +2824,73 @@ TrackerHashCleanupJob(HTAB *taskTrackerHash, Task *jobCleanupTask)
...
-		uint32 nodePort = taskTracker->workerPort;
+		List *activeTackTrackerList = remainingTaskTrackerList;
+		ListCell *activeTaskTrackerCell = NULL;
+		TimestampTz currentTime = 0;
 
-		ResultStatus resultStatus = MultiClientResultStatus(connectionId);
-		if (resultStatus == CLIENT_RESULT_READY)
+		remainingTaskTrackerList = NIL;
+
+		pg_usleep(statusCheckInterval);
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_task_tracker_executor.c]: Is the intention here to sleep 10 microseconds or milliseconds?

File: src/backend/distributed/executor/multi_task_tracker_executor.c [hunk 2]
```diff
@@ -2821,44 +2824,73 @@ TrackerHashCleanupJob(HTAB *taskTrackerHash, Task *jobCleanupTask)
...
+			ResultStatus resultStatus = MultiClientResultStatus(connectionId);
+			if (resultStatus == CLIENT_RESULT_READY)
 			{
-				ereport(DEBUG4, (errmsg("completed cleanup query for job " UINT64_FORMAT
-										" on node \"%s:%u\"", jobId, nodeName,
-										nodePort)));
+				QueryStatus queryStatus = MultiClientQueryStatus(connectionId);
+				if (queryStatus == CLIENT_QUERY_DONE)
+				{
+					ereport(DEBUG4, (errmsg("completed cleanup query for job "
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_task_tracker_executor.c]: any reason to remove the nodeName?

File: src/backend/distributed/executor/multi_task_tracker_executor.c [hunk 3]
```diff
@@ -2821,44 +2824,73 @@ TrackerHashCleanupJob(HTAB *taskTrackerHash, Task *jobCleanupTask)
...
+											UINT64_FORMAT, jobId)));
 
-				/* clear connection for future cleanup queries */
-				taskTracker->connectionBusy = false;
+					/* clear connection for future cleanup queries */
+					taskTracker->connectionBusy = false;
+				}
+				else if (timedOut)
+				{
+					ereport(WARNING, (errmsg("could not receive response for cleanup "
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_task_tracker_executor.c]: We can maybe give an errhint telling the user that he can run: SELECT task_tracker_cleanup_job( ... ) on the node.

File: src/backend/distributed/executor/multi_task_tracker_executor.c (hunk 2 above)
Comment (mtuncer) [inline src/backend/distributed/executor/multi_task_tracker_executor.c]: that's because of regression tests. We can no longer control the order of log messages. when the order is changed it breaks the regression test

File: src/backend/distributed/executor/multi_task_tracker_executor.c (hunk 1 above)
Comment (mtuncer) [inline src/backend/distributed/executor/multi_task_tracker_executor.c]: milliseconds

Comment (marcocitus) [inline src/backend/distributed/executor/multi_task_tracker_executor.c]: ok, should be multiplied by 1000

File: src/backend/distributed/executor/multi_task_tracker_executor.c (hunk 3 above)
Comment (mtuncer) [inline src/backend/distributed/executor/multi_task_tracker_executor.c]: something like
```
Manually clean job resources by issuing SELECT task_tracker_cleanup_job( ... ) on localhost:57443
```

Comment (marcocitus) [inline src/backend/distributed/executor/multi_task_tracker_executor.c]: yep, seems fine

File: src/backend/distributed/executor/multi_task_tracker_executor.c [hunk 4]
```diff
@@ -2821,44 +2824,79 @@ TrackerHashCleanupJob(HTAB *taskTrackerHash, Task *jobCleanupTask)
...
+											 "query status for job " UINT64_FORMAT " "
+											 "on node \"%s:%u\" with status %d", jobId,
+											 nodeName, nodePort, (int) queryStatus),
+									  errhint("manually clean job resources on node "
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_task_tracker_executor.c]: Should start with a capital letter I think

**Comment by marcocitus** [comment]
Apart from minor comment 🚢

File: src/backend/distributed/executor/multi_task_tracker_executor.c (hunk 4 above)
Comment (mtuncer) [inline src/backend/distributed/executor/multi_task_tracker_executor.c]: weird, we always start in small caps when we do errmsg, but start with capitals in errrhints.

Comment (marcocitus) [inline src/backend/distributed/executor/multi_task_tracker_executor.c]: It's a PostgreSQL convention.
