### PR TITLE
PG18 - use systable_inplace_update_* in UpdateStripeMetadataRow

### LINKED ISSUE #8207: PG18 - columnar crash `ColumnarReadFlushPendingWrites`
`columnar_indexes` crashing, use branch `naisila/pg18_snapshot_crash` to test

Steps to reproduce
```SQL
CREATE TABLE pending_index_scan(i INT UNIQUE) USING columnar;
BEGIN;
  INSERT INTO pending_index_scan SELECT generate_series(1,100);

  -- test index scan when there are pending writes
  SET LOCAL enable_seqscan TO OFF;
  SET LOCAL columnar.enable_custom_scan TO OFF;
  SELECT COUNT(*)=100 FROM pending_index_scan ;
COMMIT;
```

Line that crashes `Assert(!readState->snapshotRegisteredByUs);`

For some reason, we go to `ColumnarReadFlushPendingWrites` function twice, which is not expected. The `stripeWriteState` still appears as `STRIPE_WRITE_IN_PROGRESS`.

### PR DESCRIPTION
**Pull request by naisila**
PG18 has removed `heap_inplace_update()`, which is crucial for `citus_columnar` extension because we always want to update stripe entries for columnar in-place. Relevant PG18 commit: https://github.com/postgres/postgres/commit/a07e03f

`heap_inplace_update()` has been replaced by `heap_inplace_update_and_unlock`, which is used inside `systable_inplace_update_finish`, which is used together with `systable_inplace_update_begin`. This change has been back-patched up to v12, which is enough for us since the oldest version Citus supports is v15. In PG<18, a deprecated `heap_inplace_update()` is retained, however, let's start using the new functions because they are better, and such that we don't need to wrap these changes in PG18 version conditionals.

Basically, in this PR we replace the following:
```C
SysScanDesc scanDescriptor = systable_beginscan(columnarStripes, indexId, indexOk,
										        &dirtySnapshot, 2, scanKey);
heap_inplace_update(columnarStripes, modifiedTuple);
```
with the following:
```C
systable_inplace_update_begin(columnarStripes, indexId, indexOk, NULL,
						      2, scanKey, &tuple, &state);
systable_inplace_update_finish(state, tuple);
```
For more understanding, it's best to refer to an [example](https://github.com/postgres/postgres/blob/REL_18_0/src/backend/catalog/toasting.c#L349-L371) of how `systable_inplace_update_begin` and `systable_inplace_update_finish` are used in PG18, because they mirror the need of citus columnar.

Fixes #8207 

-----------------------------

_Note:_ `heap_inplace_update` was incorrectly replaced by `CatalogTupleUpdate` in https://github.com/citusdata/citus/commit/5d805eb. In Citus, we assume a stripe entry with some columns set to null means that a write is in-progress, because otherwise we wouldn't see a such row. But this breaks when we use `CatalogTupleUpdate` because it inserts a new version of the row, which leaves the in-progress version behind. This was causing various issues in [`PG18 - check-columnar`](https://github.com/citusdata/citus/actions/runs/18407060806/attempts/1#summary-52449529506), such as the following:

```diff
citus/src/test/regress/expected/columnar_create.out

   SELECT * FROM columnar_table_1 WHERE a = 6;
  a 
 ---
- 6
-(1 row)
+(0 rows)

...

   INSERT INTO columnar_internal.stripe SELECT * FROM cte ORDER BY first_row_number DESC;
   SELECT SUM(a) FROM columnar_table_1;
+WARNING:  Metadata index chunk_pkey is not available, this might mean slower read/writes on columnar tables.
+This is expected during Postgres upgrades and not expected otherwise.
+WARNING:  Metadata index chunk_group_pkey is not available, this might mean slower read/writes on columnar tables.
+This is expected during Postgres upgrades and not expected otherwise.
  sum 
 -----
   34
 (1 row)

...

/citus/src/test/regress/expected/columnar_indexes.out

 INSERT INTO columnar_table (a) VALUES (1), (1);
 REINDEX TABLE columnar_table;
-ERROR:  could not create unique index "columnar_table_a_idx"
-DETAIL:  Key (a)=(1) is duplicated.

...

 -- error out
 INSERT INTO columnar_table VALUES (16100), (16101);
-ERROR:  duplicate key value violates unique constraint "columnar_table_pkey"
-DETAIL:  Key (a)=(16100) already exists.

...

 SELECT b='15' FROM hash_int WHERE a=5;
  ?column? 
 ----------
- t
-(1 row)
+(0 rows)

...

   SELECT COUNT(*)=100 FROM pending_index_scan ;
+WARNING:  resource was not closed: snapshot reference 0x56244536a738
+WARNING:  resource was not closed: snapshot reference 0x56244536a6b0

...

 -- should choose index scan; selective but uncorrelated
 EXPLAIN (analyze on, costs off, timing off, summary off, BUFFERS OFF)
 SELECT * FROM uncorrelated WHERE x = 78910;
                                   QUERY PLAN                                  
 ------------------------------------------------------------------------------
- Index Scan using uncorrelated_idx on uncorrelated (actual rows=1 loops=1)
+ Index Scan using uncorrelated_idx on uncorrelated (actual rows=0.00 loops=1)
    Index Cond: (x = 78910)

...

/citus/src/test/regress/expected/columnar_alter.out

 VACUUM FULL zero_col_columnar;
 SELECT * FROM zero_col_columnar;
 --
-(5 rows)
+(0 rows)

...

/citus/src/test/regress/expected/columnar_zstd.out

 -- verify that higher compression level compressed better
 SELECT :size_comp_level_default > :size_comp_level_19 AS size_changed;
  size_changed 
 --------------
- t
+ f
 (1 row)

...

citus/src/test/regress/expected/columnar_vacuum.out

 select
   version_major, version_minor, reserved_stripe_id, reserved_row_number
   from columnar_test_helpers.columnar_storage_info('t');
  version_major | version_minor | reserved_stripe_id | reserved_row_number 
 ---------------+---------------+--------------------+---------------------
-             2 |             0 |                  2 |              150001
+             2 |             0 |                  1 |                   1
 (1 row)
```
and more ...

### CODE REVIEW

File: src/backend/columnar/columnar_metadata.c [hunk 1]
```diff
@@ -1394,9 +1394,6 @@ static StripeMetadata *
 UpdateStripeMetadataRow(uint64 storageId, uint64 stripeId, uint64 fileOffset,
 						uint64 dataLength, uint64 rowCount, uint64 chunkCount)
 {
-	SnapshotData dirtySnapshot;
-	InitDirtySnapshot(dirtySnapshot);
-
```
Comment (onurctirtir) [inline src/backend/columnar/columnar_metadata.c:1399]: Yes, let's discuss why we don't need a dirty snapshot anymore in today's meeting.

**Comment by naisila** [comment]
It seems that we didn't need the dirty snapshot before this commit either. Tested locally with PG 17.6 and 16.9 by running `columnar` and `columnar isolation` schedules that a `NULL` snapshot works with `systable_beginscan` as well.

**Review by onurctirtir — APPROVED** [review]
LGTM, I assume the test failures are unrelated to this PR and will be addressed as part of the remaining PG18 work.

----

I also would like to note one thing for the future readers:

Actually @naisila suggested avoiding the use of dirty snapshots in other columnar code paths as well, but I suggested not making that change until we see another test failure. To me, it seemed less risky to defer such a decision rather than making it proactively. Will see how it goes :)
