### PR TITLE
Error out earlier when creating an index with a name collision.

### LINKED ISSUE #350: Incorrect behavior while creating indexes of same name on different tables
Steps to reproduce:

```sql
postgres=# create index new_index on b_dist (b);
CREATE INDEX

postgres=# create index new_index on a_dist (b);
ERROR:  relation "new_index" already exists
```

In the second command, even though we get the error, the create index command is propagated to the worker node and the indexes are created on the worker nodes. This is because the names on the worker nodes don't contradict because of shardids being appended to index names.

However, when the command is being applied to the master table, this check is performed and we error out as both indexes have the same name. Hence, the master table does not have the indexes, but the worker tables do.

To fix this, we should add a check for verifying that the index with that name does not exist before propagating the command to the worker nodes.

This works properly if we create the index with same name on the same table.
```sql
postgres=# create index a_index on a_dist (b);
WARNING:  could not receive query results from localhost:9700
DETAIL:  Client error: relation "a_index_102011" already exists
ERROR:  could not execute DDL command on worker node shards
```

### PR DESCRIPTION
**Pull request by lithp**
Fixes #350 

Also, make the error prettier when user attempts to create an index
without a name. Previously those statements gave cryptic errors:

````
brian=# create index on c (b);
WARNING:  could not receive query results from localhost:9700
DETAIL:  Client error: cannot extend name for null index name
ERROR:  could not execute DDL command on worker node shards
````

They now return

````
brian=# create index on c (b);
ERROR:  you must specify a name when creating an index on a distributed table
````

### CODE REVIEW

**Comment by mtuncer** [comment]
@lithp can you rebase your changes

**Comment by lithp** [comment]
@mtuncer just rebased

File: src/backend/distributed/executor/multi_utility.c [hunk 1]
```diff
@@ -572,6 +572,23 @@ ProcessAlterTableStmt(AlterTableStmt *alterTableStatement, const char *alterTabl
...
+
+	if (indexRelationName == NULL)
+	{
+		ereport(ERROR, (errcode(ERRCODE_DUPLICATE_TABLE),
+										errmsg("you must specify a name when creating an index "
+													 "on a distributed table")));
+	}
+
+	namespaceId = get_namespace_oid(createIndexStatement->relation->schemaname, false);
+	if (get_relname_relid(indexRelationName, namespaceId))
```
Comment (mtuncer) [inline src/backend/distributed/executor/multi_utility.c]: we usually avoid such function calls and implicit checks in if clause.
instead do something like
```
relationId = get_relname_relid(indexRelationName, namespaceId);
if (relationId == InvalidOid)
...
```

Comment (mtuncer) [inline src/backend/distributed/executor/multi_utility.c]: I could not relate not finding a relationId with already exists error. Could you provide a description here ?

**Comment by mtuncer** [comment]
Hey @lithp. I am done with comments. Unfortunately, you will need to rebase again.

**Comment by lithp** [comment]
Addressed comments and rebased.

**Comment by lithp** [comment]
@mtuncer Addressed comments and rebased

File: src/backend/distributed/executor/multi_utility.c [hunk 2]
```diff
@@ -572,6 +572,25 @@ ProcessAlterTableStmt(AlterTableStmt *alterTableStatement, const char *alterTabl
 static void
 ErrorIfUnsupportedIndexStmt(IndexStmt *createIndexStatement)
 {
+	Oid namespaceId;
+	Oid indexRelationId;
+	char* indexRelationName = createIndexStatement->idxname;
+
+	if (indexRelationName == NULL)
+	{
+		ereport(ERROR, (errcode(ERRCODE_DUPLICATE_TABLE),
```
Comment (mtuncer) [inline src/backend/distributed/executor/multi_utility.c]: I was pretty sure I wrote about this part but can not see it now.
```ERRCODE_DUPLICATE_TABLE``` and having a no name for index is irrelevant.

Also
we usually use 'xxxxx not supported' like error messages. you could state something like 'creating an index without a name is not supported for distributed tables'.

Comment (mtuncer) [inline src/backend/distributed/executor/multi_utility.c]: Also please provide a test case for this check.

**Comment by lithp** [comment]
@mtuncer Good point on the error message/code. Improved them and added a test.

**Comment by mtuncer** [comment]
@lithp looks good. Please reduce commit list into a single commit before merging.
