### PR TITLE
Relax assertion on transaction abort on PREPARE step

### LINKED ISSUE #1966: Assert failure in FinishRemoteTransactionAbort in cancellation test
I'm setting up a CentOS 7.4 VM for development.

When I run `make check` on the `master` branch, I get the following assert failure: 
```
TRAP: FailedAssertion("!(!result)", File: "transaction/remote_transaction.c", Line: 439)
```
Line: https://github.com/citusdata/citus/blob/master/src/backend/distributed/transaction/remote_transaction.c#L439  

It's triggered by a cancellation test in `multi_real_time_transaction.sql`:

```
BEGIN;
SELECT id, pg_advisory_lock(15) FROM test_table;
ERROR:  canceling the transaction since it was involved in a distributed deadlock
ROLLBACK;
BEGIN;
SELECT id, pg_advisory_lock(15) FROM test_table;
ERROR:  canceling the transaction since it was involved in a distributed deadlock
ROLLBACK;
BEGIN;
SELECT id, pg_advisory_lock(15) FROM test_table;
ERROR:  canceling the transaction since it was involved in a distributed deadlock
ROLLBACK;
BEGIN;
SELECT id, pg_advisory_lock(15) FROM test_table;
ERROR:  canceling the transaction since it was involved in a distributed deadlock
ROLLBACK;
BEGIN;
SELECT id, pg_advisory_lock(15) FROM test_table;
ERROR:  canceling the transaction since it was involved in a distributed deadlock
server closed the connection unexpectedly
    This probably means the server terminated abnormally
    before or while processing the request.
connection to server was lost
```

### PR DESCRIPTION
**Pull request by onderkalaci**
Fixes #1966, and actually very similar to #2031. We should probably
fixed them both at that time.

If you look closely, you'll see that the change doesn't effect 
non-assert builds.

In case a failure happens when a transaction is failed on PREPARE,
we used to hit an assertion for ensuring there is no pending
activity on the connection. However, that's not true after the
changes in #2031. Thus, we've replaced the assertion with a more
generic function call to consume any pending activity, if exists.

### CODE REVIEW

File: src/backend/distributed/transaction/remote_transaction.c [hunk 1]
```diff
@@ -528,8 +528,16 @@ FinishRemoteTransactionPrepare(struct MultiConnection *connection)
 		transaction->transactionState = REMOTE_TRANS_PREPARED;
 	}
 
-	result = GetRemoteCommandResult(connection, raiseErrors);
-	Assert(!result);
+	/*
+	 * Try to consume results of any in-progress commands. In the 1PC case
+	 * this is also where we consume the result of the ROLLBACK.
```
Comment (marcocitus) [inline src/backend/distributed/transaction/remote_transaction.c]: Comment is stale.

Comment (onderkalaci) [reply src/backend/distributed/transaction/remote_transaction.c]: It is actually copy & paste 😄

File: src/backend/distributed/transaction/remote_transaction.c [hunk 2]
```diff
@@ -528,8 +528,16 @@ FinishRemoteTransactionPrepare(struct MultiConnection *connection)
...
+	 *
+	 * If we don't succeed the connection will be in a bad state, so we close it.
+	 */
+	if (!ClearResults(connection, raiseErrors))
+	{
+		ShutdownConnection(connection);
```
[the remark this answers is not in the document]
Comment (onderkalaci) [reply src/backend/distributed/transaction/remote_transaction.c]: Hmm, I couldn't find a good answer to this. But, even if we leave any prepared transactions, wouldn't 2PC recovery handle that for us?

**Comment by marcocitus** [comment]
> Hmm, I couldn't find a good answer to this. But, even if we leave any prepared transactions, wouldn't 2PC recovery handle that for us?

Actually, what about throwing an error here? We haven't committed yet and something about the PREPARE TRANSACTION failed, so we're not entirely sure what state the worker is in. Safest course of action seems to be rolling back. The connection might even still be in a state where we can roll it back. 

I realise this would already happen in all cases except replication factor > 1 and we could potentially mark shard placement(s) inactive, but that seems like kind of a poor choice.


Unrelated note: One kind of bad thing about the way Citus handles distributed transaction is that our 2PC logic returns a COMMIT (with warnings) even if we fail to commit a prepared transaction. That breaks read-your-writes consistency. The most correct thing to do would be to wait until recovery completes (potentially forever). A more reasonable, yet correct thing to do would be to close the session entirely, leaving it in an undeterminate state.

**Comment by onderkalaci** [comment]
> Safest course of action seems to be rolling back. 

I agree with that. I updated the PR, though I cannot find a test to add, which seems hard. Do you have any suggestions/ideas for that?

File: src/backend/distributed/transaction/remote_transaction.c [hunk 3]
```diff
@@ -528,8 +528,19 @@ FinishRemoteTransactionPrepare(struct MultiConnection *connection)
...
+	 * Try to consume results of PREPARE TRANSACTION command. If we don't
+	 * succeed, rollback the transaction. Note that we've not committed on
+	 * any node yet, and we're not sure about the state of the worker node.
+	 * So rollbacking seems to be the safest action if the worker is
+	 * in a state where it can actually rollback.
+	 */
+	if (!ClearResults(connection, raiseErrors))
+	{
+		ereport(ERROR, (errmsg("failed to prepare transaction '%s'",
+							   transaction->preparedName),
```
Comment (marcocitus) [inline src/backend/distributed/transaction/remote_transaction.c]: could use a host name/port in the message.
