### PR TITLE
Fix worker_fetch_regular_table with schema

### LINKED ISSUE #504: Joining two append tables within a schema causes 'failed to execute job' error
Creating a table within a schema seems to work as expected. Selecting from two tables within a schema also works as expected. However upon joining them together, it would appear that citus "forgets" the schema information.

## How to Replicate

```
CREATE SCHEMA foo;

CREATE TABLE foo.bar (id INT, created_dt TIMESTAMPTZ);
CREATE TABLE foo.baz (id INT, created_dt TIMESTAMPTZ);

SELECT master_create_distributed_table(
  'foo.bar', 'id', 'append'
);

SELECT master_create_distributed_table(
  'foo.baz', 'id', 'append'
);

SELECT master_create_empty_shard('foo.bar');
SELECT master_create_empty_shard('foo.baz');
```

## Results

As can be seen below, using the tables normally results in normal operation:

```
SELECT * FROM foo.bar;

 id | created_dt
----+------------
(0 rows)

SELECT * FROM foo.baz;

 id | created_dt
----+------------
(0 rows)
```

However, joining the two tables together is a different story:

```
SELECT count(*)
  FROM foo.bar
  JOIN foo.baz USING (id);

WARNING:  could not receive query results from localhost:6100
WARNING:  could not receive query results from localhost:6101
WARNING:  could not receive query results from localhost:6100
ERROR:  failed to execute job 30
```

Shard logs appear to complain that the shards do not exist, yet do not mention the `foo` schema at all:

```
2016-05-06 16:20:58 CDT [29664-1] postgres@execution ERROR:  relation "baz_102027" does not exist
2016-05-06 16:20:58 CDT [29664-2] postgres@execution STATEMENT:  COPY baz_102027 TO STDOUT
2016-05-06 16:20:58 CDT [29665-1] postgres@execution WARNING:  could not receive query results from localhost:6100
2016-05-06 16:20:58 CDT [29665-2] postgres@execution DETAIL:  Client error: relation "baz_102027" does not exist
2016-05-06 16:20:58 CDT [29667-1] postgres@execution ERROR:  relation "baz_102027" does not exist
2016-05-06 16:20:58 CDT [29667-2] postgres@execution STATEMENT:  COPY baz_102027 TO STDOUT
2016-05-06 16:20:58 CDT [29665-3] postgres@execution WARNING:  could not receive query results from localhost:6101
2016-05-06 16:20:58 CDT [29665-4] postgres@execution DETAIL:  Client error: relation "baz_102027" does not exist
2016-05-06 16:20:58 CDT [29665-5] postgres@execution ERROR:  could not fetch relation: "baz_102027"
2016-05-06 16:20:58 CDT [29665-6] postgres@execution STATEMENT:  SELECT worker_fetch_regular_table  ('baz_102027', 0, '{localhost,localhost}', '{6100,6101}')
```

### LINKED ISSUE #646: worker_fetch_foreign_table does not work with schemas
Modified from @onderkalaci 's comment on #504 

```SQL

CREATE SCHEMA tpch_1;
CREATE SCHEMA tpch_2;

CREATE EXTENSION file_fdw;

CREATE SERVER file_fdw_server FOREIGN DATA WRAPPER file_fdw;

CREATE FOREIGN TABLE nation_hash (
    n_nationkey integer not null,
    n_name char(25) not null,
    n_regionkey integer not null,
    n_comment varchar(152)
)
SERVER file_fdw_server
OPTIONS (filename '');

CREATE FOREIGN TABLE tpch_1.nation_hash (
    n_nationkey integer not null,
    n_name char(25) not null,
    n_regionkey integer not null,
    n_comment varchar(152)
)
SERVER file_fdw_server
OPTIONS (filename '');

CREATE FOREIGN TABLE tpch_1.nation_hash_2 (
    n_nationkey integer not null,
    n_name char(25) not null,
    n_regionkey integer not null,
    n_comment varchar(152)
)
SERVER file_fdw_server
OPTIONS (filename '');

CREATE FOREIGN TABLE tpch_2.nation_hash (
    n_nationkey integer not null,
    n_name char(25) not null,
    n_regionkey integer not null,
    n_comment varchar(152)
)
SERVER file_fdw_server
OPTIONS (filename '');

SELECT master_create_distributed_table('public.nation_hash', 'n_nationkey', 'hash');
SELECT master_create_worker_shards('public.nation_hash', 1, 1);

SELECT master_create_distributed_table('tpch_1.nation_hash', 'n_nationkey', 'hash');
SELECT master_create_worker_shards('tpch_1.nation_hash', 1, 1);

SELECT master_create_distributed_table('tpch_1.nation_hash_2', 'n_nationkey', 'hash');
SELECT master_create_worker_shards('tpch_1.nation_hash_2', 1, 1);

SELECT master_create_distributed_table('tpch_2.nation_hash', 'n_nationkey', 'hash');
SELECT master_create_worker_shards('tpch_2.nation_hash', 1, 1);

-- fails
SET search_path TO public;
SELECT 
    count (*)
FROM
    tpch_1.nation_hash n1, tpch_2.nation_hash n2 
WHERE
    n1.n_nationkey = n2.n_nationkey;


-- fails
SET search_path TO tpch_1;
SELECT 
    count (*)
FROM
    tpch_1.nation_hash n1, tpch_2.nation_hash n2 
WHERE
    n1.n_nationkey = n2.n_nationkey;

--fails 
SELECT 
    count (*)
FROM
    tpch_1.nation_hash n1, tpch_2.nation_hash n2 
WHERE
    n1.n_nationkey = n2.n_nationkey;

-- fails
SET search_path TO public;
SELECT 
    count (*)
FROM
    tpch_1.nation_hash n1, tpch_1.nation_hash_2 n2 
WHERE
    n1.n_nationkey = n2.n_nationkey;


-- fails
SET search_path TO tpch_1;
SELECT 
    count (*)
FROM
    nation_hash n1, nation_hash_2 n2 
WHERE
    n1.n_nationkey = n2.n_nationkey;


-- single repartition joins 

-- fails
SET search_path TO public;
SELECT 
    count (*)
FROM
    tpch_1.nation_hash n1, tpch_2.nation_hash n2 
WHERE
    n1.n_nationkey = n2.n_regionkey;


-- fails
SET search_path TO tpch_1;
SELECT 
    count (*)
FROM
    nation_hash n1, nation_hash_2 n2 
WHERE
    n1.n_nationkey = n2.n_regionkey;

-- fails
SET search_path TO tpch_1;
SELECT 
    count (*)
FROM
    nation_hash n1, tpch_2.nation_hash n2 
WHERE
    n1.n_nationkey = n2.n_regionkey;

-- hash repartition joins 

-- fails
SET search_path TO public;
SELECT 
    count (*)
FROM
    tpch_1.nation_hash n1, tpch_2.nation_hash n2 
WHERE
    n1.n_regionkey = n2.n_regionkey;


-- fails
SET search_path TO tpch_1;
SELECT 
    count (*)
FROM
    nation_hash n1, nation_hash_2 n2 
WHERE
    n1.n_regionkey = n2.n_regionkey;

-- fails
SET search_path TO tpch_1;
SELECT 
    count (*)
FROM
    nation_hash n1, tpch_2.nation_hash n2 
WHERE
    n1.n_regionkey = n2.n_regionkey;
```

### PR DESCRIPTION
**Pull request by byucesoy**
Fixes #504
Fixes #646

We changed signature of worker_fetch_regular_table to accept schema name as parameter to
make it work with schemas.

### CODE REVIEW

File: src/backend/distributed/worker/worker_data_fetch_protocol.c [hunk 1]
```diff
@@ -559,15 +563,15 @@ FetchTableCommon(text *tableNameText, uint64 remoteTableSize,
...
+		tableFetched = (*FetchTableFunction)(nodeName, nodePort, schemaName, tableName);
 
 		nodeIndex++;
 	}
 
 	/* error out if we tried all nodes and could not fetch the table */
 	if (!tableFetched)
 	{
-		ereport(ERROR, (errmsg("could not fetch relation: \"%s\"", tableName->data)));
+		ereport(ERROR, (errmsg("could not fetch relation: \"%s\"", tableName)));
```
Comment (jasonmp85) [inline src/backend/distributed/worker/worker_data_fetch_protocol.c]: This should probably include the schema name, no?

File: src/backend/distributed/worker/worker_data_fetch_protocol.c [hunk 2]
```diff
@@ -679,7 +683,7 @@ ExtractShardId(StringInfo tableName)
  * false. On other types of failures, the function errors out.
  */
 static bool
-FetchRegularTable(const char *nodeName, uint32 nodePort, StringInfo tableName)
+FetchRegularTable(const char *nodeName, uint32 nodePort, const char *schemaName, const char * tableName)
```
Comment (jasonmp85) [inline src/backend/distributed/worker/worker_data_fetch_protocol.c]: This exceeds our line limit. Do you have [`citus_indent`](https://github.com/citusdata/tools/tree/v0.3.2/uncrustify) installed?

File: src/backend/distributed/worker/worker_data_fetch_protocol.c [hunk 3]
```diff
@@ -872,13 +876,14 @@ RemoteTableOwner(const char *nodeName, uint32 nodePort, StringInfo tableName)
  * the function returns an empty list.
  */
 List *
-TableDDLCommandList(const char *nodeName, uint32 nodePort, StringInfo tableName)
+TableDDLCommandList(const char *nodeName, uint32 nodePort, const char *schemaName, const char *tableName)
```
Comment (jasonmp85) [inline src/backend/distributed/worker/worker_data_fetch_protocol.c]: Same story (line length too long, `citus_indent` would have caught).

**Comment by jasonmp85** [comment]
Looked over the code here; looks pretty good. Looking at tests now.

File: src/backend/distributed/worker/worker_data_fetch_protocol.c [hunk 4]
```diff
@@ -791,9 +795,9 @@ FetchForeignTable(const char *nodeName, uint32 nodePort, StringInfo tableName)
 
 	/* fetch foreign file to this node in an idempotent manner */
 	localFilePath = makeStringInfo();
-	appendStringInfo(localFilePath, FOREIGN_CACHED_FILE_PATH, tableName->data);
+	appendStringInfo(localFilePath, FOREIGN_CACHED_FILE_PATH, tableName);
```
Comment (jasonmp85) [inline src/backend/distributed/worker/worker_data_fetch_protocol.c]: Shouldn't this have the schema included in the file name somehow? What if there are two foreign tables with the same name in different schemas? Wouldn't they conflict and end up using the same file?

Maybe I'm missing something, but I think this is a place that the schema needs to appear, too. It doesn't look possible to make a directory, so maybe the schema can be included in the file name somehow.

**Comment by jasonmp85** [comment]
OK, the tests are pretty thorough, and the code looks like it does everything we want.

I at first thought the place where we have a file created for the data for a cached foreign table had problem, but now realize that the table name always includes the shard identifier, which will prevent any conflicts even in the absence of a schema.

I've rebased this, fixed your one test (which appears to just be a line you missed copying in an SQL file) and formatted the code and will merge shortly.

File: src/backend/distributed/worker/worker_data_fetch_protocol.c (hunk 4 above)
Comment (jasonmp85) [inline src/backend/distributed/worker/worker_data_fetch_protocol.c]: I take it back, finally (after many times reading the call tree) realized that the table name here has the shard identifier in it, so we're probably good from a collision standpoint.
