### PR TITLE
Fix DDL execution bug on MX when search_path is used

### LINKED ISSUE #2328: DDL operations on the tables that are in the search_path are broken for Citus MX
`public` schema is out of the scope of this issue given that it doesn't need explicit schema on the table names.

The root cause of this issue is that we're directly relaying the command executed on the coordinator to the worker nodes [here](https://github.com/citusdata/citus/blob/master/src/backend/distributed/executor/multi_utility.c#L3150): `SendCommandToWorkers(WORKERS_WITH_METADATA, (char *) ddlJob->commandString);` 

This seems like a must have for 8.0

Steps to reproduce is very straighforward:

```SQL
CREATE SCHEMA mx_bug;
SET search_path TO mx_bug ;
CREATE TABLE test (a int);
SELECT create_distributed_table('test', 'a');


ALTER TABLE test ADD COLUMN x INT;
LOG:  issuing BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;SELECT assign_distributed_transaction_id(0, 18, '2018-08-06 16:17:44.491564+03');
DETAIL:  on server localhost:9700
LOG:  issuing BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;SELECT assign_distributed_transaction_id(0, 18, '2018-08-06 16:17:44.491564+03');
DETAIL:  on server localhost:9703
LOG:  issuing BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;SELECT assign_distributed_transaction_id(0, 18, '2018-08-06 16:17:44.491564+03');
DETAIL:  on server localhost:9701
LOG:  issuing BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;SELECT assign_distributed_transaction_id(0, 18, '2018-08-06 16:17:44.491564+03');
DETAIL:  on server localhost:9702
LOG:  issuing SET citus.enable_ddl_propagation TO 'off'
DETAIL:  on server localhost:9700
LOG:  issuing SET citus.enable_ddl_propagation TO 'off'
DETAIL:  on server localhost:9703
LOG:  issuing SET citus.enable_ddl_propagation TO 'off'
DETAIL:  on server localhost:9701
LOG:  issuing SET citus.enable_ddl_propagation TO 'off'
DETAIL:  on server localhost:9702
LOG:  issuing ALTER TABLE test ADD COLUMN x INT;
DETAIL:  on server localhost:9700
LOG:  issuing ALTER TABLE test ADD COLUMN x INT;
DETAIL:  on server localhost:9703
LOG:  issuing ALTER TABLE test ADD COLUMN x INT;
DETAIL:  on server localhost:9701
LOG:  issuing ALTER TABLE test ADD COLUMN x INT;
DETAIL:  on server localhost:9702
LOG:  issuing ROLLBACK
DETAIL:  on server localhost:9700
ERROR:  relation "test" does not exist
CONTEXT:  while executing command on localhost:9700

-- or create index
postgres=# CREATE INDEX i1 ON test (a);
DEBUG:  building index "i1" on table "test"
LOG:  issuing BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;SELECT assign_distributed_transaction_id(0, 19, '2018-08-06 16:18:04.064978+03');
DETAIL:  on server localhost:9700
LOG:  issuing BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;SELECT assign_distributed_transaction_id(0, 19, '2018-08-06 16:18:04.064978+03');
DETAIL:  on server localhost:9703
LOG:  issuing BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;SELECT assign_distributed_transaction_id(0, 19, '2018-08-06 16:18:04.064978+03');
DETAIL:  on server localhost:9701
LOG:  issuing BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;SELECT assign_distributed_transaction_id(0, 19, '2018-08-06 16:18:04.064978+03');
DETAIL:  on server localhost:9702
LOG:  issuing SET citus.enable_ddl_propagation TO 'off'
DETAIL:  on server localhost:9700
LOG:  issuing SET citus.enable_ddl_propagation TO 'off'
DETAIL:  on server localhost:9703
LOG:  issuing SET citus.enable_ddl_propagation TO 'off'
DETAIL:  on server localhost:9701
LOG:  issuing SET citus.enable_ddl_propagation TO 'off'
DETAIL:  on server localhost:9702
LOG:  issuing CREATE INDEX i1 ON test (a);
DETAIL:  on server localhost:9700
LOG:  issuing CREATE INDEX i1 ON test (a);
DETAIL:  on server localhost:9703
LOG:  issuing CREATE INDEX i1 ON test (a);
DETAIL:  on server localhost:9701
LOG:  issuing CREATE INDEX i1 ON test (a);
DETAIL:  on server localhost:9702
LOG:  issuing ROLLBACK
DETAIL:  on server localhost:9700
ERROR:  relation "test" does not exist
CONTEXT:  while executing command on localhost:9700
```

The workaround is to explicitly add the schema to the query such as:

```SQL
ALTER TABLE mx_bug.test ADD COLUMN x INT;

CREATE INDEX i1 ON mx_bug.test (a);
```

The quickest solution seems to add `search_path` to the points where we send the DDL to the tables with `SendCommandToWorkers(WORKERS_WITH_METADATA, ...)`

### PR DESCRIPTION
**Pull request by onderkalaci**
Fixes #2328 

Make sure that the coordinator sends the commands when the search_path synchronized with the coordinator's search_path. This is only important when Citus sends the commands that are directly relayed to the worker nodes. For example, the DLL commands which are send via `worker_apply_shard_ddl_command` or `SELECT/DML` queries always adds schema qualifications to the queries. So, they do not benefit from this change. This is only useful for the queries that are executed on the actual table, not the shards.

### CODE REVIEW

File: src/backend/distributed/executor/multi_utility.c [hunk 1]
```diff
@@ -3146,7 +3148,19 @@ ExecuteDistributedDDLJob(DDLJob *ddlJob)
...
+			/*
+			 * Given that we're relaying the query to the worker nodes directly,
+			 * we should set the search path exactly the same when necessary.
+			 */
+			if (setSearchPathCommand != NULL)
+			{
+				SendCommandToWorkers(WORKERS_WITH_METADATA, setSearchPathCommand);
+			}
+
 			SendCommandToWorkers(WORKERS_WITH_METADATA, (char *) ddlJob->commandString);
```
[the remark this answers is not in the document]
Comment (onderkalaci) [reply src/backend/distributed/executor/multi_utility.c]: But `SendBareCommandListToWorkers ()` executes outside of the distributed/coordinated transaction whereas `SendCommandToWorkers ` executes inside the distributed/coordinated transaction. So, that'd break the logic.

File: src/backend/distributed/executor/multi_utility.c [hunk 2]
```diff
@@ -3173,8 +3187,24 @@ ExecuteDistributedDDLJob(DDLJob *ddlJob)
...
+				char *setSearchPathCommand = SetSearchPathToCurrentSearchPathCommand();
+				List *commandList = NIL;
+
+				/*
+				 * Given that we're relaying the query to the worker nodes directly,
+				 * we should set the search path exactly the same when necessary.
+				 */
+				if (setSearchPathCommand != NULL)
+				{
+					commandList = list_make3(DISABLE_DDL_PROPAGATION,
```
Comment (mtuncer) [inline src/backend/distributed/executor/multi_utility.c]: I would have preferred
```
list_make1()
if (setSearchPathCommand)
{
    lappend()
}
lappend()
```

for better readability.

File: src/backend/distributed/executor/multi_utility.c (hunk 1 above)
[the remark this answers is not in the document]
Comment (mtuncer) [reply src/backend/distributed/executor/multi_utility.c]: ok

File: src/backend/distributed/executor/multi_utility.c [hunk 3]
```diff
@@ -3193,6 +3223,77 @@ ExecuteDistributedDDLJob(DDLJob *ddlJob)
...
+ * has.
+ *
+ * If the current search path is null (or doesn't have any valid schemas),
+ * the function returns NULL.
+ */
+static char *
+SetSearchPathToCurrentSearchPathCommand(void)
+{
+	StringInfo setCommand = NULL;
+	char *currentSchemas = CurrentSearchPath();
```
Comment (mtuncer) [inline src/backend/distributed/executor/multi_utility.c]: `currentSearchPath` ?

**Comment by mtuncer** [comment]
hit some nasty issue, test case is like you are intentionally trying to shoot yourself in the foot but I felt like reporting any way.

- coordinator
  - set replication model to streaming
  - start metadata sync to worker 1
  - create schema s1, s2;
  - create table s1.t1

- worker 1
  - create schema s2
  - create table s2.t1(a int, b int)

- coordinator
  - set search path to s2, s1
  - alter table t1 add column c int
  - \d s1.t1 --> see new column in s1.t1 

- worker 1
  - \d s1.t1   --> column is not added
  - \d s2.t1  --> wrong table is altered

**Comment by onderkalaci** [comment]
> hit some nasty issue, test case is like you are intentionally trying to shoot yourself in the foot but I felt like reporting any way.

We've discussed this with @mtuncer. It looks like these type of nasty things are possible if users create local tables on the worker nodes. I think we should document and discourage users from doing that. They can obviously create local tables, but, tables with the same names as distributed tables are prone to various edge cases such as this one.

So, we're both leaning towards leaving this issue as a known thing and not attempt to fix. Note that the fix seems a little bit involved so it doesn't worth fixing it.

File: src/backend/distributed/executor/multi_utility.c (hunk 2 above)
Comment (onderkalaci) [reply src/backend/distributed/executor/multi_utility.c]: makes sense.

File: src/backend/distributed/executor/multi_utility.c (hunk 3 above)
Comment (onderkalaci) [reply src/backend/distributed/executor/multi_utility.c]: done

File: src/backend/distributed/executor/multi_utility.c [hunk 4]
```diff
@@ -3193,6 +3223,77 @@ ExecuteDistributedDDLJob(DDLJob *ddlJob)
...
+	{
+		char *schemaName = NULL;
+
+		if (schemaAdded)
+		{
+			appendStringInfoString(currentSchemas, ",");
+		}
+
+		/* watch out for deleted namespace */
+		schemaName = get_namespace_name(lfirst_oid(searchPathCell));
```
[the remark this answers is not in the document]
Comment (onderkalaci) [reply src/backend/distributed/executor/multi_utility.c]: But I don't want to add `,` at the end of the string. So, I kept the loop but set `schemaAdded ` to false if `schemaName == NULL`. Does that look good?

(I actually copy & paste'd this code from Postgres code. I cannot find a case where `schemaName` is null. But, keeping it here just in case.)

File: src/backend/distributed/executor/multi_utility.c [hunk 5]
```diff
@@ -3193,6 +3218,81 @@ ExecuteDistributedDDLJob(DDLJob *ddlJob)
...
+		if (schemaName)
+		{
+			appendStringInfoString(currentSearchPath, quote_identifier(schemaName));
+
+			schemaAdded = true;
+		}
+		else
```
Comment (mtuncer) [inline src/backend/distributed/executor/multi_utility.c]: This makes it a lot less readable. 

How about
```c
	/* watch out for deleted namespace */
	schemaName = get_namespace_name(lfirst_oid(searchPathCell));
	if (schemaName)
	{
		if (schemaAdded)
		{
			appendStringInfoString(currentSearchPath, ",");
		}
		
		appendStringInfoString(currentSearchPath, quote_identifier(schemaName));
		schemaAdded = true;
	}
```

Comment (onderkalaci) [reply src/backend/distributed/executor/multi_utility.c]: Yes, this is much better. I'll update the code accordingly

Comment (onderkalaci) [reply src/backend/distributed/executor/multi_utility.c]: Please see my new code-style now

File: src/backend/distributed/executor/multi_utility.c [hunk 6]
```diff
@@ -3193,6 +3218,76 @@ ExecuteDistributedDDLJob(DDLJob *ddlJob)
...
+ * The function returns NULL if there are no valid schemas in the search_path,
+ * mimicing current_schemas(false) function.
+ */
+static char *
+CurrentSearchPath(void)
+{
+	StringInfo currentSearchPath = makeStringInfo();
+	List *searchPathList = fetch_search_path(false);
+	ListCell *searchPathCell;
+	bool addComma = false;
```
Comment (mtuncer) [inline src/backend/distributed/executor/multi_utility.c]: I would stick with `schemaAdded`, but this is also good

File: src/backend/distributed/executor/multi_utility.c [hunk 7]
```diff
@@ -3193,6 +3218,77 @@ ExecuteDistributedDDLJob(DDLJob *ddlJob)
...
+	{
+		char *schemaName = get_namespace_name(lfirst_oid(searchPathCell));
+
+		/* watch out for deleted namespace */
+		if (schemaName)
+		{
+			if (schemaAdded)
+			{
+				appendStringInfoString(currentSearchPath, ",");
+				schemaAdded = false;
```
Comment (furkansahin) [inline src/backend/distributed/executor/multi_utility.c]: Just a very minor note: I think `schemaAdded = false;`is not necessary here and it confused me a bit, tbh.

Comment (onderkalaci) [reply src/backend/distributed/executor/multi_utility.c]: I agree that it is a little bit confusing. The name should probably have been `addCommaSeperator`.

But, I think it is necessary to have that variable  because we cannot always get a schema in every iteration. So, how could we reset the variable otherwise?

Comment (furkansahin) [reply src/backend/distributed/executor/multi_utility.c]: The thing is, even if we set it to false here, it is immediately set back to true just outside of the curly bracket. I think the check is needed only for the first iteration, don't you think so?

Comment (onderkalaci) [reply src/backend/distributed/executor/multi_utility.c]: Ah, I see. Yes, that seems correct.
