### PR TITLE
Handle rebalance / replication when a node is disabled (Fix #5664)

### LINKED ISSUE #5664: Rebalance after disable node is broken
```SQL
SELECT citus_add_node('localhost', 9700);
SELECT citus_add_node('localhost', 9701);


SET citus.shard_replication_factor TO 2;
CREATE TABLE test(a int);
SELECT create_distributed_table('test', 'a');


SELECT citus_disable_node('localhost', 9701);

 SELECT rebalance_table_shards();
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
Time: 13.790 ms
 @:-!> 

```

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xc)
  * frame #0: 0x0000000102368475 citus.so`InitRebalanceState(workerNodeList=<unavailable>, shardPlacementList=<unavailable>, functions=0x00007ff7bec749d0) at shard_rebalancer.c:1882:24
    frame #1: 0x0000000102368050 citus.so`RebalancePlacementUpdates(workerNodeList=0x00007ff2160fd8c8, shardPlacementListList=0x00007ff216101848, threshold=0, maxShardMoves=1000000, drainOnly=false, improvementThreshold=0, functions=0x00007ff7bec749d0) at shard_rebalancer.c:1748:11
    frame #2: 0x00000001023677f9 citus.so`GetRebalanceSteps(options=0x00007ff7bec74a50) at shard_rebalancer.c:475:9
    frame #3: 0x0000000102366b95 citus.so`RebalanceTableShards(options=0x00007ff7bec74a50, shardReplicationModeOid=16598) at shard_rebalancer.c:1558:30
    frame #4: 0x000000010236684e citus.so`rebalance_table_shards(fcinfo=0x00007ff212832600) at shard_rebalancer.c:822:2
    frame #5: 0x0000000101403cc1 postgres`ExecInterpExpr(state=<unavailable>, econtext=<unavailable>, isnull=0x00007ff7bec74ba7) at execExprInterp.c:725:8
    frame #6: 0x000000010140364b postgres`ExecInterpExprStillValid(state=0x00007ff212832528, econtext=0x00007ff212832250, isNull=<unavailable>) at execExprInterp.c:1824:9
    frame #7: 0x000000010143600d postgres`ExecEvalExprSwitchContext(state=0x00007ff212832528, econtext=0x00007ff212832250, isNull=<unavailable>) at executor.h:339:13
    frame #8: 0x0000000101435fc0 postgres`ExecProject(projInfo=<unavailable>) at executor.h:373:9
    frame #9: 0x0000000101435ea2 postgres`ExecResult(pstate=0x00007ff212832140) at nodeResult.c:136:10
    frame #10: 0x000000010141120b postgres`ExecProcNodeFirst(node=0x00007ff212832140) at execProcnode.c:463:9
    frame #11: 0x000000010140caee postgres`ExecProcNode(node=0x00007ff212832140) at executor.h:257:9
    frame #12: 0x000000010140ab8d postgres`ExecutePlan(estate=0x00007ff212831f18, planstate=0x00007ff212832140, use_parallel_mode=<unavailable>, operation=CMD_SELECT, sendTuples=true, numberTuples=0, direction=ForwardScanDirection, dest=0x00007ff215843bf0, execute_once=<unavailable>) at execMain.c:1551:10
    frame #13: 0x000000010140aac5 postgres`standard_ExecutorRun(queryDesc=0x00007ff214011718, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:361:3
    frame #14: 0x000000010234e107 citus.so`CitusExecutorRun(queryDesc=0x00007ff214011718, direction=ForwardScanDirection, count=0, execute_once=<unavailable>) at multi_executor.c:218:4
    frame #15: 0x0000000101ece855 pg_stat_statements.so`pgss_ExecutorRun(queryDesc=0x00007ff214011718, direction=ForwardScanDirection, count=0, execute_once=true) at pg_stat_statements.c:1001:4
    frame #16: 0x000000010140a9f5 postgres`ExecutorRun(queryDesc=0x00007ff214011718, direction=ForwardScanDirection, count=0, execute_once=<unavailable>) at execMain.c:303:3
    frame #17: 0x000000010156e7b4 postgres`PortalRunSelect(portal=0x00007ff21384b318, forward=<unavailable>, count=0, dest=0x00007ff215843bf0) at pquery.c:919:4
    frame #18: 0x000000010156e422 postgres`PortalRun(portal=0x00007ff21384b318, count=9223372036854775807, isTopLevel=true, run_once=<unavailable>, dest=0x00007ff215843bf0, altdest=0x00007ff215843bf0, qc=0x00007ff7bec750d0) at pquery.c:763:18
    frame #19: 0x000000010156bcbd postgres`exec_simple_query(query_string="select rebalance_table_shards(shard_transfer_mode:='block_writes');") at postgres.c:1214:10
    frame #20: 0x000000010156b221 postgres`PostgresMain(argc=<unavailable>, argv=<unavailable>, dbname=<unavailable>, username=<unavailable>) at postgres.c:0
    frame #21: 0x00000001014f590a postgres`BackendRun(port=<unavailable>) at postmaster.c:4506:2
    frame #22: 0x00000001014f5329 postgres`BackendStartup(port=<unavailable>) at postmaster.c:4228:3
    frame #23: 0x00000001014f48b3 postgres`ServerLoop at postmaster.c:1745:7
    frame #24: 0x00000001014f2cc0 postgres`PostmasterMain(argc=3, argv=<unavailable>) at postmaster.c:1417:11
    frame #25: 0x000000010145727d postgres`main(argc=<unavailable>, argv=<unavailable>) at main.c:209:3
    frame #26: 0x000000010b3854fe dyld`start + 462

```

### PR DESCRIPTION
**Pull request by gledis69**
The issue in question is caused when rebalance / replication call `FullShardPlacementList` which returns all shard placements (including those in disabled nodes with `citus_disable_node`).  Eventually, `FindFillStateForPlacement` looks for the state across active workers and fails to find a state for the placements which are in the disabled workers causing a seg fault shortly after.

Approach:
* `ActivePlacementHash` was not using the status of the shard placement's node to determine if the node it is active. Initially, I just fixed that.
* Additionally, I refactored the code which handles active shards in replication / rebalance to:
	* use a single function to determine if a shard placement is active. 
	* do the shard active shard filtering before calling `RebalancePlacementUpdates` and `ReplicationPlacementUpdates`, so test methods like `shard_placement_rebalance_array` and `shard_placement_replication_array` which have different shard placement active requirements can do their own filtering while using the same rebalance / replicate logic that `rebalance_table_shards` and `replicate_table_shards` use. 

Fix #5664

### CODE REVIEW

File: src/backend/distributed/operations/shard_rebalancer.c [hunk 1]
```diff
@@ -2974,3 +2978,33 @@ EnsureShardAllowedOnNodeUDF(Oid functionOid)
...
+	ShardPlacement *shardPlacement = NULL;
+
+	foreach_ptr(shardPlacement, shardPlacements)
+	{
+		foreach_ptr(workerNode, disabledNodes)
+		{
+			if (shardPlacement->shardState == SHARD_STATE_ACTIVE &&
+				shardPlacement->nodeId == workerNode->nodeId)
+			{
+				ereport(ERROR, (errmsg(
```
Comment (onderkalaci) [inline src/backend/distributed/operations/shard_rebalancer.c:3004]: We currently define active placements to be placements on active nodes. So, by definition, we should not  `ActiveShardPlacementsOnDisabledNodes`. 

It still not very clear to me why changing `ActivePlacementsHash` to consider this new definition does OK? We might need something additional, but it seems like that's a must have?

To me, without fixing that, we are still going to be vulnerable to such weird edge cases.

Comment (gledis69) [reply src/backend/distributed/operations/shard_rebalancer.c:3004]: In that case, if this is run on the coordinator:
```pgsql
SET citus.shard_replication_factor TO 2;
CREATE TABLE test(a int);
SELECT citus_disable_node('localhost', :worker2_id);
SELECT * FROM pg_dist_shard_placement;
```
All the shards will be reported, and they all will be labelled active. The active shards on the disabled node conflict with our definition of active, so we might want to consider to change the shard placement statuses of shards in disabled nodes.

Comment (onderkalaci) [reply src/backend/distributed/operations/shard_rebalancer.c:3004]: Ack., that is confusing. But unfortunately, currently the `shardstate` on `pg_dist_shard_placement ` *does not fully reflect* the shard's state. Maybe we should find a way to show it properly.


As we discussed in person, the new definition of `ActiveShardPlacementList()` does the following such that it should be on an active node:
```C
		if (shardPlacement->shardState == SHARD_STATE_ACTIVE &&
			workerNode->isActive)
		{
			activePlacementList = lappend(activePlacementList, shardPlacement);
		}
```


And, in simple words, the reason can be explained as follows:
(a) Citus never marks any placement `SHARD_STATE_INACTIVE` anymore. All modifications happens via 2PC. Because, on MX, it is non-trivial to propagate metadata changes from any node. (e.g., modifications can happen from any node), we preferred this approach. 
(b) Due to possibility of multiple node failures at the same time, we prefer to let a background daemon to sync the node metadata changes after citus_disable_node
(c) Once a node is activated, we make sure that the "disabled" placements are cleared properly: https://github.com/citusdata/citus/blob/d0aa450d7bc8bc4cebf6cf70ce15b07bbc65a780/src/backend/distributed/metadata/node_metadata.c#L1077-L1091   We do this as `activateNode` because it is much more likely that users activate nodes when all the cluster is up and running (compared to disable node, which happens to shield against failures) 


The more discussion on the PRs landed for this topic is here: https://github.com/citusdata/citus/issues/1033#issuecomment-940806179

File: src/backend/distributed/operations/shard_rebalancer.c [hunk 2]
```diff
@@ -2609,7 +2611,17 @@ ActivePlacementsHash(List *shardPlacementList)
 	foreach(shardPlacementCell, shardPlacementList)
 	{
 		ShardPlacement *shardPlacement = (ShardPlacement *) lfirst(shardPlacementCell);
-		if (shardPlacement->shardState == SHARD_STATE_ACTIVE)
+		WorkerNode *workerNode = FindWorkerNode(shardPlacement->nodeName,
```
Comment (onderkalaci) [inline src/backend/distributed/operations/shard_rebalancer.c:2614]: how can we have NULL worker node? Does that mean the worker removed from the cluster?

Comment (gledis69) [reply src/backend/distributed/operations/shard_rebalancer.c:2614]: When you run smth like this:
```sql
CREATE OR REPLACE FUNCTION shard_placement_rebalance_array(
    worker_node_list json[],
    shard_placement_list json[],
    threshold float4 DEFAULT 0,
    max_shard_moves int DEFAULT 1000000,
    drain_only bool DEFAULT false,
    improvement_threshold float4 DEFAULT 0.5
)
RETURNS json[]
AS 'citus'
LANGUAGE C STRICT VOLATILE;

-- Check that even with threshold=0.0 shard_placement_rebalance_array returns
-- something when there's no completely balanced solution.


SELECT unnest(shard_placement_rebalance_array(
    ARRAY['{"node_name": "hostname1"}',
          '{"node_name": "hostname2"}']::json[],
    ARRAY['{"shardid":1, "nodename":"hostname1"}',
          '{"shardid":2, "nodename":"hostname1"}',
          '{"shardid":3, "nodename":"hostname1"}']::json[]
));
```

`FindWorkerNode` attempts to find the workers of the shards and does not find `hostname1` or `hostname2` in the actual worker nodes.

Comment (onderkalaci) [reply src/backend/distributed/operations/shard_rebalancer.c:2614]: When I saw `workerNode == NULL`, I expected it'd be qualified as !isActive. Or, it can actually never be NULL, because `ResolveGroupShardPlacement` function which is always used to load shardPlacements ensures that via `LookupNodeForGroup()`. If a placement is on a node that doesn't exist, we'd get:
```C
	if (!foundAnyNodes)
	{
		ereport(ERROR, (errmsg("there is a shard placement in node group %d but "
							   "there are no nodes in that group", groupId)));
	}
```


So, we seem to be doing this change for the sake of a fake test with a fake metadata.

I think we should probably insert these dummy host-names to pg_dist_node in the tests, like:
```SQL
BEGIN;
INSERT INTO pg_dist_node ...(hostname1) ;;

 SELECT unnest(shard_placement_rebalance_array( ARRAY['{"node_name": "hostname1"}', '{"node_name": "hostname2"}']::json[], ARRAY['{"shardid":1, "nodename":"hostname1"}', '{"shardid":2, "nodename":"hostname1"}', '{"shardid":3, "nodename":"hostname1"}']::json[] ));

ROLLBACK;
```

Such that they become more realistic. And, we can assert `workerNode != NULL` as described above (e.g., we cannot have placements that is on a non-existing node).

File: src/backend/distributed/operations/shard_rebalancer.c [hunk 3]
```diff
@@ -2609,7 +2611,17 @@ ActivePlacementsHash(List *shardPlacementList)
...
+												shardPlacement->nodePort);
+
+		/*
+		 * If a worker can be found for the shard, that worker should be active.
+		 * For the sake of testing rebalance and replicate, having a null
+		 * worker is also allowed since the tests are done with dummy shard placements
+		 * and workers. The worker will not be NULL with actual shard placements.
+		 */
+		if (shardPlacement->shardState == SHARD_STATE_ACTIVE &&
```
Comment (onderkalaci) [inline src/backend/distributed/operations/shard_rebalancer.c:2623]: Also, do we need any improvements in `ReplicationPlacementUpdates`, where we have:

```C
if (placement->shardState != SHARD_STATE_ACTIVE)
		{
			continue;
		}

```

Should that check for placements on inactive nodes:
```C
if (placement->shardState != SHARD_STATE_ACTIVE || PlacemenOnInactiveNode(placement))
		{
			continue;
		}
```

Comment (gledis69) [reply src/backend/distributed/operations/shard_rebalancer.c]: This doesn't matter. Since we create a table to count how many shard do all the workers have, and all the workers passed to this function are active. Then even though we don't skip the placements in inactive workers, they do not contribute to the count of the workers.

**Comment by gledis69** [comment]
Also it appears that when we disable the node, all the shard placements in that node:
* Are no longer used (or at least are not supposed to be used) by any other functionality
* When the node is reactivated, those shards will be deleted anyway.

So it might make sense to either label as `TO_DELETE` the instances in `pg_dist_shard_placement`. This would also remove the need to check for active workers as the current solution does.

File: src/backend/distributed/operations/shard_rebalancer.c [hunk 4]
```diff
@@ -446,14 +448,17 @@ GetRebalanceSteps(RebalanceOptions *options)
...
-	List *shardPlacementListList = NIL;
+	List *activeShardPlacementListList = NIL;
 
 	Oid relationId = InvalidOid;
 	foreach_oid(relationId, options->relationIdList)
 	{
 		List *shardPlacementList = FullShardPlacementList(relationId,
 														  options->excludedShardArray);
-		shardPlacementListList = lappend(shardPlacementListList, shardPlacementList);
+		activeShardPlacementListList = lappend(activeShardPlacementListList,
```
[the remark this answers is not in the document]
Comment (onderkalaci) [reply src/backend/distributed/operations/shard_rebalancer.c:458]: Also, what happens if `activeShardPlacementListForRelation  == NIL`?  I guess we should be fine, but would be good to have a test where ALL the shards of a given table is excluded:

```SQL
select rebalance_table_shards('test', excluded_shard_list:='{102008, 102009,102010,102011}');
```

(assuming this table has only these shards and not colocated with any other table, e.g., use colocate_with parameter with create_dist_table)

File: src/test/regress/expected/shard_rebalancer.out [hunk 5]
```diff
@@ -2378,3 +2378,44 @@ SELECT rebalance_table_shards();
 
 CALL citus_cleanup_orphaned_shards();
 DROP TABLE test_rebalance_with_index CASCADE;
+-- Test rebalancer with disabled worker
+SET citus.shard_replication_factor TO 2;
+DROP TABLE IF EXISTS test_rebalance_with_disabled_worker;
+CREATE TABLE test_rebalance_with_disabled_worker (a int);
+SELECT create_distributed_table('test_rebalance_with_disabled_worker', 'a');
```
Comment (onderkalaci) [inline src/test/regress/expected/shard_rebalancer.out:2385]: minor: maybe add colocate_with:='none' such that other tests do not interfere with this test

**Review by onderkalaci — COMMENTED** [review]
Very neat refactor & bug fix!

I think I'm mostly OK to merge this, though would be good to double check with @JelteF on whether zero active placements is fine in general in the rebalance code-path.

It looks so, but would be good to verify with Jelte who has more context on this code-path.

**Review by JelteF — COMMENTED** [review]
LGTM, but the PR description seems outdated. Afaict this now implements the second approach.

File: src/test/regress/expected/shard_rebalancer.out [hunk 6]
```diff
@@ -2378,3 +2378,63 @@ SELECT rebalance_table_shards();
...
+CREATE TABLE test_with_all_shards_excluded(a int);
+SELECT create_distributed_table('test_with_all_shards_excluded', 'a', colocate_with:='none', shard_count:=4);
+ create_distributed_table
+---------------------------------------------------------------------
+
+(1 row)
+
+SELECT shardid FROM pg_dist_shard;
+ shardid
+---------------------------------------------------------------------
```
Comment (onderkalaci) [inline src/test/regress/expected/shard_rebalancer.out:2427]: These shardIds might change if say we change the order of the tests.

To avoid such cases, we use the following trick to fix the shardIds:
```SQL
SET citus.next_shard_id TO 433000;
```

In this test file, we already have this, but as we re-connect to the coordinator via `\c - - - :master_port`, we lose the above SET.

So, we should re-set before create_distributed_table to something like the following, where we allow ~500 shards in this file before this line, which should be good enough:
```SQL
SET citus.next_shard_id TO 433500;
```

So that the shards have consistent shardIds.

(alternatively, we may NOT print the shardids and use some psql variable like `SELECT .. INTO variable FROM ...`), and then use the variable in `excluded_shard_list`. Though, still setting the `citus.next_shard_id` is a good practice

File: src/test/regress/expected/shard_rebalancer.out [hunk 7]
```diff
@@ -2378,3 +2378,63 @@ SELECT rebalance_table_shards();
...
+SELECT citus_activate_node('localhost', :worker_2_port);
+ citus_activate_node
+---------------------------------------------------------------------
+                  35
+(1 row)
+
+DROP TABLE test_rebalance_with_disabled_worker;
+-- Test rebalance with all shards excluded
+DROP TABLE IF EXISTS test_with_all_shards_excluded;
+CREATE TABLE test_with_all_shards_excluded(a int);
```
Comment (onderkalaci) [inline src/test/regress/expected/shard_rebalancer.out:2418]: minor: maybe use PRIMARY KEY in the table such that on enterprise repo, the test is triggered  via non-blocking rebalancer such that we get extra coverage. 
(I know the code-path is the same until we get to the actual rebalance -- and we don't to rebalance for this test--, but still it might change in the future.)

**Review by onderkalaci — APPROVED** [review]
After considering some small comments, ready to merge. Thanks!
