### PR TITLE
Error out on CTEs with data modifying statement

### LINKED ISSUE #1038: SIGABRT in RouterSelectTask
To reproduce (on master with pg 9.6):

```
CREATE TABLE test (x int, y int, z int);
SELECT master_create_distributed_table('test', 'x', 'hash');
SELECT master_create_worker_shards('test', 16);
WITH result AS (
 UPDATE test SET y = z WHERE x = 10 AND z in (1, 2, 3, 4) RETURNING *
)
SELECT * FROM result ORDER BY z;
```

Backtrace:
```
#2  0x00000000008197cb in ExceptionalCondition (conditionName=conditionName@entry=0x7f03eeaee928 "!(rte->rtekind == RTE_RELATION)", 
    errorType=errorType@entry=0x7f03eeae6fba "FailedAssertion", fileName=fileName@entry=0x7f03eeaf3b42 "utils/ruleutils_96.c", lineNumber=lineNumber@entry=3155)
    at assert.c:54
#3  0x00007f03eeade23c in get_update_query_def (query=query@entry=0x17f6bc0, context=context@entry=0x7fff5d955960) at utils/ruleutils_96.c:3155
#4  0x00007f03eead8c0a in get_query_def_extended (query=0x17f6bc0, buf=buf@entry=0x18503e8, parentnamespace=0x1852ff8, distrelid=distrelid@entry=0, 
    shardid=shardid@entry=0, resultDesc=resultDesc@entry=0x0, prettyFlags=0, wrapColumn=0, startIndent=0) at utils/ruleutils_96.c:1915
#5  0x00007f03eead8cd4 in get_query_def (query=<optimized out>, buf=buf@entry=0x18503e8, parentnamespace=<optimized out>, resultDesc=resultDesc@entry=0x0, 
    prettyFlags=<optimized out>, wrapColumn=<optimized out>, startIndent=0) at utils/ruleutils_96.c:1844
#6  0x00007f03eead8e71 in get_with_clause (query=query@entry=0x182a358, context=context@entry=0x7fff5d955b50) at utils/ruleutils_96.c:2037
#7  0x00007f03eeaddf2b in get_select_query_def (query=query@entry=0x182a358, context=context@entry=0x7fff5d955b50, resultDesc=resultDesc@entry=0x0)
    at utils/ruleutils_96.c:2070
#8  0x00007f03eead8bf6 in get_query_def_extended (query=query@entry=0x182a358, buf=buf@entry=0x18503e8, parentnamespace=parentnamespace@entry=0x0, 
    distrelid=distrelid@entry=0, shardid=shardid@entry=0, resultDesc=resultDesc@entry=0x0, prettyFlags=0, wrapColumn=0, startIndent=0) at utils/ruleutils_96.c:1911
#9  0x00007f03eead8cd4 in get_query_def (query=query@entry=0x182a358, buf=buf@entry=0x18503e8, parentnamespace=parentnamespace@entry=0x0, resultDesc=resultDesc@entry=0x0, 
    prettyFlags=prettyFlags@entry=0, wrapColumn=wrapColumn@entry=0, startIndent=0) at utils/ruleutils_96.c:1844
#10 0x00007f03eead8cff in pg_get_query_def (query=query@entry=0x182a358, buffer=buffer@entry=0x18503e8) at utils/ruleutils_96.c:441
#11 0x00007f03eeac4c60 in RouterSelectTask (originalQuery=originalQuery@entry=0x182a358, restrictionContext=0x1846260, placementList=placementList@entry=0x7fff5d955cf0)
    at planner/multi_router_planner.c:1850
#12 0x00007f03eeac60ea in CreateSingleTaskRouterPlan (originalQuery=originalQuery@entry=0x182a358, query=query@entry=0x17f6cd8, 
    restrictionContext=restrictionContext@entry=0x1846260) at planner/multi_router_planner.c:209
```

When it fails the assertion that it's passed a RTE_RELATION it actually receives an RTE_FUNCTION.

### PR DESCRIPTION
**Pull request by byucesoy**
Fixes #1038 

With this change we start to error out on router planner queries where a common table
expression with data-modifying statement is present. We already do not support if
there is a data-modifying statement using result of the CTE, now we also error out
if CTE itself is data-modifying statement.

### CODE REVIEW

**Comment by metdos** [comment]
@jasonmp85, adding another one to your queue.

File: src/backend/distributed/planner/multi_router_planner.c [hunk 1]
```diff
@@ -2850,3 +2851,44 @@ InstantiatePartitionQual(Node *node, void *context)
...
+
+/*
+ * ErrorIfRouterSelectQueryNotSupported checks if the query contains unsupported features,
+ * and errors out if it does. Currently we only error out if query contains common table
+ * expressions where CTE part of the query is something other than SELECT.
+ */
+static void
+ErrorIfRouterSelectQueryNotSupported(Query *queryTree)
+{
+	ListCell *cteCell;
```
Comment (jasonmp85) [inline src/backend/distributed/planner/multi_router_planner.c]: Set this to `NULL`, per our style?

File: src/backend/distributed/planner/multi_router_planner.c [hunk 2]
```diff
@@ -2850,3 +2851,44 @@ InstantiatePartitionQual(Node *node, void *context)
...
+		 * nested CTE, however PostgreSQL dictates that data-modifying statements must
+		 * be at top level of CTE. Therefore it is OK to just check for top level.
+		 * Similarly, we do not need to check for subqueries.
+		 */
+		if (cteQuery->commandType != CMD_SELECT)
+		{
+			ereport(ERROR, (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
+							errmsg("cannot perform distributed planning for the given "
+								   "modification"),
+							errdetail("Only SELECT queries is supported as common table "
```
Comment (jasonmp85) [inline src/backend/distributed/planner/multi_router_planner.c]: PostgreSQL refers to these as _data-modifying statements in `WITH` clauses_. In fact, _common table expression_ is only mentioned once at the top of [the relevant documentation page](https://www.postgresql.org/docs/9.6/static/queries-with.html).

Let's use _Data-modifying statements are not supported in the WITH clauses of distributed queries_?

File: src/test/regress/sql/multi_router_planner.sql [hunk 3]
```diff
@@ -226,6 +226,29 @@ WITH RECURSIVE hierarchy as (
 				ce.company_id = 2))
 SELECT * FROM hierarchy WHERE LEVEL <= 2;
 
+-- CTE with queries other than SELECT is not supported
+WITH new_article AS (
+    INSERT INTO articles_hash VALUES (1,  1, 'arsenous', 9572) RETURNING *
+)
+SELECT * FROM new_article;
+
+-- Modifying statement in nested CTE case is covered by PostgreSQL itself
```
Comment (jasonmp85) [inline src/test/regress/sql/multi_router_planner.sql]: Great! I was going to ask about nested CTEs.

File: src/backend/distributed/planner/multi_router_planner.c [hunk 4]
```diff
@@ -204,6 +204,7 @@ CreateSingleTaskRouterPlan(Query *originalQuery, Query *query,
 	{
 		Assert(commandType == CMD_SELECT);
```
Comment (jasonmp85) [inline src/backend/distributed/planner/multi_router_planner.c]: Kill this `Assert` since you've added one in your `ErrorIf` function.

File: src/backend/distributed/planner/multi_router_planner.c [hunk 5]
```diff
@@ -127,7 +127,7 @@ static void ErrorIfInsertPartitionColumnDoesNotMatchSelect(Query *query,
 														   Oid *
 														   selectPartitionColumnTableId);
 static void AddUninstantiatedEqualityQual(Query *query, Var *targetPartitionColumnVar);
-
+static void ErrorIfRouterSelectQueryNotSupported(Query *queryTree);
```
Comment (jasonmp85) [inline src/backend/distributed/planner/multi_router_planner.c]: Maybe consider the more specific `ErrorIfQueryHasModifyingCTE` since that's everything this does right now?
