### PR TITLE
Fix an assertion failure in Citus maintenance daemon that can happen in very slow systems

### LINKED ISSUE #5808: Occasional assertion failure due to race condition in MaintenanceDaemonShmemExit
Sometimes valgrind tests we failing due to an assertion failure that happens in `multi_extension.sql:L599`:
https://github.com/citusdata/citus/blob/3801576dfb6a1088082bf1eb90025ac656d77c14/src/test/regress/sql/multi_extension.sql#L596-L599

And fortunately, this time I was able to collect the coredump for the assertion failure.

After investigating a bit, suspected that if it could be because of a race condition that happens in `MaintenanceDaemonShmemExit`. The reason behind this suspicion was that regression tests take much longer time to complete than usual when postgres process is being tested using valgrind.

And to reproduce the issue locally, inserted some random `pg_usleep` calls into `MaintenanceDaemonShmemExit` and here is what we get:

```diff
diff --git a/src/backend/distributed/utils/maintenanced.c b/src/backend/distributed/utils/maintenanced.c
index 940764235..92ca4c252 100644
--- a/src/backend/distributed/utils/maintenanced.c
+++ b/src/backend/distributed/utils/maintenanced.c
@@ -791,17 +791,25 @@ MaintenanceDaemonShmemInit(void)
 static void
 MaintenanceDaemonShmemExit(int code, Datum arg)
 {
+       pg_usleep(1000000 * 10);
+
        Oid databaseOid = DatumGetObjectId(arg);

+       pg_usleep(1000000 * 10);
+
        LWLockAcquire(&MaintenanceDaemonControl->lock, LW_EXCLUSIVE);

        MaintenanceDaemonDBData *myDbData = (MaintenanceDaemonDBData *)
                                                                                hash_search(MaintenanceDaemonDBHash, &databaseOid,
                                                                                                        HASH_FIND, NULL);

+       pg_usleep(1000000 * 10);
+
        /* myDbData is NULL after StopMaintenanceDaemon */
        if (myDbData != NULL)
        {
+               pg_usleep(1000000 * 10);
+
                /*
                 * Confirm that I am still the registered maintenance daemon before exiting.
                 */
```

```c
libc.so.6!__GI_raise(int sig) (\build\glibc-eX1tMB\glibc-2.31\sysdeps\unix\sysv\linux\raise.c:50)
libc.so.6!__GI_abort() (\build\glibc-eX1tMB\glibc-2.31\stdlib\abort.c:79)
ExceptionalCondition(const char * conditionName, const char * errorType, const char * fileName, int lineNumber) (\opt\pgenv\src\postgresql-14.1\src\backend\utils\error\assert.c:69)
citus.so!MaintenanceDaemonShmemExit(int code, Datum arg) (\home\onurctirtir\citus\src\backend\distributed\utils\maintenanced.c:816)
shmem_exit(int code) (\opt\pgenv\src\postgresql-14.1\src\backend\storage\ipc\ipc.c:239)
proc_exit_prepare(int code) (\opt\pgenv\src\postgresql-14.1\src\backend\storage\ipc\ipc.c:194)
proc_exit(int code) (\opt\pgenv\src\postgresql-14.1\src\backend\storage\ipc\ipc.c:107)
StartBackgroundWorker() (\opt\pgenv\src\postgresql-14.1\src\backend\postmaster\bgworker.c:878)
do_start_bgworker(RegisteredBgWorker * rw) (\opt\pgenv\src\postgresql-14.1\src\backend\postmaster\postmaster.c:5866)
maybe_start_bgworkers() (\opt\pgenv\src\postgresql-14.1\src\backend\postmaster\postmaster.c:6091)
sigusr1_handler(int postgres_signal_arg) (\opt\pgenv\src\postgresql-14.1\src\backend\postmaster\postmaster.c:5255)
libpthread.so.0!<signal handler called> (Unknown Source:0)
libc.so.6!__GI___select(int nfds, fd_set * readfds, fd_set * writefds, fd_set * exceptfds, struct timeval * timeout) (\build\glibc-eX1tMB\glibc-2.31\sysdeps\unix\sysv\linux\select.c:41)
ServerLoop() (\opt\pgenv\src\postgresql-14.1\src\backend\postmaster\postmaster.c:1709)
PostmasterMain(int argc, char ** argv) (\opt\pgenv\src\postgresql-14.1\src\backend\postmaster\postmaster.c:1417)
main(int argc, char ** argv) (\opt\pgenv\src\postgresql-14.1\src\backend\main\main.c:209)
```

, where, `maintenanced.c:816` corresponds to below check:
```c
		/*
		 * Confirm that I am still the registered maintenance daemon before exiting.
		 */
		Assert(myDbData->workerPid == MyProcPid);
```

### PR DESCRIPTION
**Pull request by onurctirtir**
Fixes #5808.

DESCRIPTION: Fixes an assertion failure in Citus maintenance daemon that can happen in very slow systems.

Try running `make -C src/test/regress/ check-multi-1-vg` - while the tests will exit with code 2 at least %50 of the times in the very early stages of the test suite by producing a core-dump on main, it won't be the case on this branch, at least based on my trials :)

### CODE REVIEW

File: src/backend/distributed/utils/maintenanced.c [hunk 1]
```diff
@@ -1040,12 +1040,30 @@ MaintenanceDaemonShmemExit(int code, Datum arg)
 	if (myDbData != NULL)
 	{
 		/*
-		 * Confirm that I am still the registered maintenance daemon before exiting.
+		 * Once the maintenance daemon fails (e.g., due to an error in the main loop),
+		 * both Postgres tries to restart the failed daemon and Citus attempt to start
```
Comment (emelsimsek) [inline src/backend/distributed/utils/maintenanced.c:1044]: Are we sure Postgres restarts the maintenance deamon ever?
We are using [BGW_NEVER_RESTART](https://www.postgresql.org/docs/current/bgworker.html#:~:text=bgw_restart_time%20is%20the%20interval%2C%20in%20seconds%2C%20that%20postgres%20should%20wait%20before%20restarting%20the%20process%20in%20the%20event%20that%20it%20crashes.%20It%20can%20be%20any%20positive%20value%2C%20or%20BGW_NEVER_RESTART%2C%20indicating%20not%20to%20restart%20the%20process%20in%20case%20of%20a%20crash.) flag to prevent that.

**Review by emelsimsek — APPROVED** [review]
If we are running into this assert for some reason (it could be a race condition where Citus tries to start the maintenance deamon since it is in an exiting state etc), I believe this is an acceptable and harmless fix.

File: src/backend/distributed/utils/maintenanced.c (hunk 1 above)
Comment (onurctirtir) [reply src/backend/distributed/utils/maintenanced.c:1044]: Seem we actually provide CITUS_BGW_DEFAULT_RESTART_TIME for Citus Maintenance Daemon:

https://github.com/citusdata/citus/blob/a0dee662a095706edf79a12e147a7a64c48cff85/src/backend/distributed/utils/maintenanced.c#L199
https://github.com/citusdata/citus/blob/a0dee662a095706edf79a12e147a7a64c48cff85/src/backend/distributed/utils/maintenanced.c#L262

Which gets translated to 5 at:

https://github.com/citusdata/citus/blob/a0dee662a095706edf79a12e147a7a64c48cff85/src/include/distributed/background_worker_utils.h#L47

Maybe we should ideally change that instead, but it'd be a bigger change, so I'd prefer merging this as is.
