### PR TITLE
Explicitly mark queries in physical planner for [not] having parameters

### LINKED ISSUE #3789: Some SELECT queries with PREPARE statement and custom types may fail
Seems related to https://github.com/citusdata/citus/pull/3553, we should probably set `task->parametersInQueryStringResolved` for `SELECT`s as well.

```SQL

CREATE TYPE invite_resp AS ENUM ('yes', 'no', 'maybe'); 

CREATE TABLE event_responses (
  event_id int,
  user_id int,
  response invite_resp,
  primary key (event_id, user_id)
);
SELECT create_distributed_table('event_responses', 'event_id');

PREPARE p1(invite_resp) AS select * from event_responses where response = $1::invite_resp LIMIT 1;
EXECUTE p1('yes');

ERROR:  could not determine data type of parameter $1
CONTEXT:  while executing command on localhost:9700
Time: 35.610 ms

PREPARE p2(invite_resp) AS select * from event_responses where response = $1 LIMIT 1;
EXECUTE p2('yes');
ERROR:  could not determine data type of parameter $1
CONTEXT:  while executing command on localhost:9701
Time: 18.474 ms


-- delete works fine
PREPARE p3(invite_resp) AS DELETE FROM event_responses where response = $1;
EXECUTE p3('yes');
DELETE 0
Time: 146.555 ms

```

One thing to note here is that the queries sent to remote nodes doesn't have any parameters `SELECT event_id, user_id, response FROM event_responses_102449 event_responses WHERE (response OPERATOR(pg_catalog.=) 'yes'::public.invite_resp) LIMIT '1'::bigint`, we get the error because the coordiantor sends the parameter even if it is not necessary.

### PR DESCRIPTION
**Pull request by onderkalaci**
Physical planner doesn't support parameters. The parameters have already
been resolved when the physical planner handles queries. However, the executor
is unaware of this, and sends the parameters along with the worker queries.

(See `DissuadePlannerFromUsingPlan()` for the details of parameter resolving)

DESCRIPTION: Fixes a failure when composite types used in prepared statements

Fixes  #3789

### CODE REVIEW

File: src/backend/distributed/planner/multi_physical_planner.c [hunk 1]
```diff
@@ -2130,12 +2130,29 @@ BuildJobTreeTaskList(Job *jobTree, PlannerRestrictionContext *plannerRestriction
...
+		 * Second, assign merge task's data fetch dependencies.
+		 */
 		foreach(assignedSqlTaskCell, assignedSqlTaskList)
 		{
 			Task *assignedSqlTask = (Task *) lfirst(assignedSqlTaskCell);
-			List *assignedMergeTaskList = FindDependentMergeTaskList(assignedSqlTask);
 
+			/* we don't support parameters in the physical planner */
+			if (assignedSqlTask->taskType == SELECT_TASK)
+			{
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_physical_planner.c:2150]: In my first iteration, I simply set `assignedSqlTask->parametersInQueryStringResolved ` to `false` as I  thought physical planner cannot handle parameters and we never get here with parameters. However, it turns  out that with CURSORs, we can get here with parameters (tough we fail when executing it).

Instead, I decided to make it more robust to any further changes and call `HasUnresolvedExternParamsWalker ` on the job query

File: src/test/regress/expected/local_shard_execution.out [hunk 2]
```diff
@@ -1690,6 +1690,237 @@ SELECT create_distributed_table('event_responses', 'event_id');
...
+CALL regular_procedure('no');
+CALL regular_procedure('no');
+CALL regular_procedure('no');
+CALL regular_procedure('no');
+CALL regular_procedure('no');
+PREPARE multi_shard_no_dist_key(invite_resp) AS select * from event_responses where response = $1::invite_resp LIMIT 1;
+EXECUTE multi_shard_no_dist_key('yes');
+ event_id | user_id | response
+---------------------------------------------------------------------
+(0 rows)
```
Comment (marcocitus) [inline src/test/regress/expected/local_shard_execution.out:1768]: It would be better if this returned a row.
