### PR TITLE
Fix the crash that happens when using auto_explain extension with recursive queries

### LINKED ISSUE #2920: Crash in auto_explain
Could be related #2009

### PR DESCRIPTION
**Pull request by emelsimsek**
This crash happens with recursively planned queries. For such queries, subplans are explained via the ExplainOnePlan function of postgresql. This function reconstructs the query description from the plan therefore it expects the ActiveSnaphot for the query be available. This fix makes sure that the snapshot is in the stack before calling ExplainOnePlan.

Fixes #2920.

### CODE REVIEW

File: src/backend/distributed/planner/multi_explain.c [hunk 1]
```diff
@@ -203,7 +203,10 @@ CitusExplainScan(CustomScanState *node, List *ancestors, struct ExplainState *es
 
 	if (distributedPlan->subPlanList != NIL)
 	{
+		/* ExplainSubPlans calls ExplainOnePlan which uses the ActiveSnapshot.*/
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_explain.c:206]: I wonder whether we should push snaphost at the start of CitusExplainScan and pop at the end of the function, such that all the parts of the explain has the same snapshot?

**Review by onderkalaci — COMMENTED** [review]
As we discussed, we should be able to run all the tests with auto_explain enabled in the regression tests. I think @aykut-bozkurt should be able to help you on how to figure out that.

File: src/backend/distributed/planner/multi_explain.c (hunk 1 above)
Comment (emelsimsek) [reply src/backend/distributed/planner/multi_explain.c]: Sure. I see no harm to enclose all the Explain functions called here.

File: src/backend/distributed/planner/multi_explain.c [hunk 2]
```diff
@@ -201,13 +201,22 @@ CitusExplainScan(CustomScanState *node, List *ancestors, struct ExplainState *es
 
 	ExplainOpenGroup("Distributed Query", "Distributed Query", true, es);
 
+	/*
+	 * ExplainOnePlan function of postgres might be called in this codepath.
+	 * It requires an ActiveSnapshot being set. Make sure to make ActiveSnapshot available before calling into
+	 * Citus Explain functions.
+	 */
+	PushActiveSnapshot(executorState->es_snapshot);
+
```
[the remark this answers is not in the document]
Comment (onderkalaci) [reply src/backend/distributed/planner/multi_explain.c:210]: Ok, if tx rollbacks, PG gets rid of all the snapshots https://github.com/postgres/postgres/blob/a601366a460f68472bf70c4d94c57baa0a3ed1b2/src/backend/utils/time/snapmgr.c#L1025

**Review by onderkalaci — APPROVED** [review]
We typically squash commits before merging if the commits do not intended for doing different things. I think the 2 commits this PR has can be categorized doing the same thing.

So please consider squashing commits for this PR. Thanks!

**Comment by JelteF** [comment]
> We typically squash commits before merging if the commits do not intended for doing different things. I think the 2 commits this PR has can be categorized doing the same thing.

I usually use this:
image

**Comment by JelteF** [comment]
PR description should have a line with

DESCRIPTION: .... 

This should be done for any user impacting changes, because it is used to automatically generate the changelog.

**Comment by onderkalaci** [comment]
> PR description should have a line with
DESCRIPTION: ....
This should be done for any user impacting changes, because it is used to automatically generate the changelog.

This fixes only a subset of the issues with auto_explain (see https://github.com/citusdata/citus/issues/6448), and discussed with @emelsimsek that we could add the DESCRIPTION once we resolve that
