### PR TITLE
Keep more execution statistics

### LINKED ISSUE #4689: Make sure to properly terminate not fully established connections
The adaptive executor may have decided to establish connections while the execution is in progress. However, by the time the execution finishes, the connections might not have properly established.

In that case, Citus abruptly terminates the connections, and this fills the logs with errors like:
```SQL
 2020-11-16 21:09:09.800 CET [16633] LOG:  could not accept SSL connection: Connection reset by peer
2020-11-16 21:09:09.872 CET [16657] LOG:  could not accept SSL connection: Undefined error: 0
2020-11-16 21:09:09.894 CET [16667] LOG:  could not accept SSL connection: Connection reset by peer
```

An attempt to fix this which added a lot of perf penalty: https://github.com/citusdata/citus/pull/4317

This is valid for all cases. However, for single node/starter plan, the error logs will be on the coordinator can can be very confusing. Especially under high loads, these errors become more visible.

### PR DESCRIPTION
**Pull request by onderkalaci**
DESCRIPTION: When DEBUG4 enabled, Citus prints per task execution times

(First of the series of 3 patches that fixes #4689, wait until all pieces are ready before review)

### CODE REVIEW

File: src/backend/distributed/executor/adaptive_executor.c [hunk 1]
```diff
@@ -4249,6 +4265,23 @@ PlacementExecutionDone(TaskPlacementExecution *placementExecution, bool succeede
...
+		Assert(INSTR_TIME_IS_ZERO(placementExecution->endTime));
+		INSTR_TIME_SET_CURRENT(placementExecution->endTime);
+
+		if (IsLoggableLevel(DEBUG4))
+		{
+			long durationMillisecs =
+				MillisecondsBetweenTimestamps(placementExecution->startTime,
+											  placementExecution->endTime);
+
+			ereport(DEBUG4, (errmsg("Task execution (%d) for placement (%ld) finished in "
```
Comment (marcocitus) [inline src/backend/distributed/executor/adaptive_executor.c:4278]: could be kind of nice to have the anchor shard id in here

super minor: errmsg should start with lower case

**Review by marcocitus — APPROVED** [review]
I thought about cases where we use debug4 as test output, but it's actually good to discourage that.
