### PR TITLE
Custom Scan (ColumnarScan): exclude outer_join_rels from CandidateRelids

### LINKED ISSUE #7647: postgresql is crashing when selecting from citus columnar table
Hello, 

we have a problem that postgresql is crashing when we left join citus table on heap tables.
OS Redhat 8.9 , Postgresql 16.3 , Citus 12.1.4

How to reproduce:

create extension citus;
create table test1 (a integer);
create table test2 (a integer);
create table test3 (b integer) using columnar;

SELECT *
   FROM test1 a1
     LEFT JOIN test2 a2 ON a1.a = a2.a
     LEFT JOIN test3 b  ON a2.a = b.b
;

server closed the connection unexpectedly

From logs:
<2024-07-09 10:00:21.484 EEST%2048391%668cdfda.1f4187%%%> DETAIL:  Failed process was running: select *
           FROM test1 a1
             LEFT JOIN test2 a2 ON a1.a = a2.a
         left JOIN test3 b  ON a2.a = b.b
        ;
<2024-07-09 10:00:21.484 EEST%2048391%668cdfda.1f4187%%%> LOG:  terminating any other active server processes
<2024-07-09 10:00:21.489 EEST%2048570%668ce005.1f423a%[unknown]%[local]%[unknown]> LOG:  connection received: host=[local]
<2024-07-09 10:00:21.489 EEST%2048570%668ce005.1f423a%postgres%[local]%test> FATAL:  the database system is in recovery mode
<2024-07-09 10:00:21.492 EEST%2048391%668cdfda.1f4187%%%> LOG:  all server processes terminated; reinitializing

### PR DESCRIPTION
**Pull request by OlgaSergeyevaB**
DESCRIPTION: Fixes a crash in columnar custom scan that happens when a columnar table is used in a join.

Fixes #7647.

### CODE REVIEW

**Comment by ivan-v-kush** [comment]
@OlgaSergeyevaB Olga, you can take the tests from here.
https://github.com/hydradatabase/hydra/pull/279/files

**Comment by ivan-v-kush** [comment]
here is also one fix for distributed case
https://github.com/citusdata/citus/pull/7789

**Comment by OlgaSergeyevaB** [comment]
> here is also one fix for distributed case #7789
@ivan-v-kush, these are different cases

**Comment by OlgaSergeyevaB** [comment]
> @OlgaSergeyevaB Olga, thanks for PR. You can take the tests from here. https://github.com/hydradatabase/hydra/pull/279/files
> 
> `outer_join_rels` were introduced in [postgres/postgres@2489d76](https://github.com/postgres/postgres/commit/2489d76c4906f4461a364ca8ad7e0751ead8aa0d)

@ivan-v-kush, thanks for your tests. But its fall without sorting.

**Comment by OlgaSergeyevaB** [comment]
@microsoft-github-policy-service agree

**Comment by colm-mchugh** [comment]
@OlgaSergeyevaB thank you for submitting this PR. Can you rebase it to the [release-13.0](https://github.com/citusdata/citus/tree/release-13.0) branch ? We would like to include this in Citus' next patch release.

**Comment by OlgaSergeyevaB** [comment]
@colm-mchugh , I rebase it to the [release-13.0](https://github.com/citusdata/citus/tree/release-13.0) branch

**Comment by colm-mchugh** [comment]
> @colm-mchugh , I rebase it to the [release-13.0](https://github.com/citusdata/citus/tree/release-13.0) branch

Could you drop all the commits that are not yours, and squash your commits into 1 commit ? Then we can review. Thanks @OlgaSergeyevaB .

**Comment by OlgaSergeyevaB** [comment]
@colm-mchugh, I squash my commits into 1 commit. Thanks @colm-mchugh

**Comment by OlgaSergeyevaB** [comment]
@colm-mchugh , maybe I should add another test [test](https://github.com/OlgaSergeyevaB/citus/compare/db6eaa4af3f76143149fb9b678d04eceb60375b1...1418214e3adb60268eb2f1565724865543cc54ab)

File: src/backend/columnar/columnar_customscan.c [hunk 1]
```diff
@@ -1051,6 +1051,11 @@ FindCandidateRelids(PlannerInfo *root, RelOptInfo *rel, List *joinClauses)
 
 	candidateRelids = bms_del_members(candidateRelids, rel->relids);
 	candidateRelids = bms_del_members(candidateRelids, rel->lateral_relids);
+
```
Comment (naisila) [inline src/backend/columnar/columnar_customscan.c:1054]: Can we add a comment here for the relevant PG16 commit requiring this addition:
https://github.com/postgres/postgres/commit/2489d76c4906f4461a364ca8ad7e0751ead8aa0d

**Review by naisila — APPROVED** [review]

**Review by colm-mchugh — APPROVED** [review]

**Comment by colm-mchugh** [comment]
> 
> @colm-mchugh We can ignore that since I believe it doesn't take into account commits that are not part of the repository, but rather belong to a fork. I was looking at other community contributions to Citus, and in many cases codecov failed.
>
Thanks, sounds like a reasonable explanation, I've approved also. 

> > maybe I should add another test
> 
Yes @OlgaSergeyevaB +1 for the test. The EXPLAIN output *might* differ with different PG versions, but let's see.

File: src/backend/columnar/columnar_customscan.c (hunk 1 above)
Comment (OlgaSergeyevaB) [reply src/backend/columnar/columnar_customscan.c:1054]: @naisila ,  I add comment

**Comment by OlgaSergeyevaB** [comment]
@naisila, @colm-mchugh , I add test
