### PR TITLE
Moves Creation of ALTER INDEX STATISTICS Commands Next to Index Commands

### LINKED ISSUE #4519: alter_table_set_access_method(..,'columnar') fails after ALTER INDEX
```sql
create table test (x int, y int);
select create_distributed_table('test','x');
create index on test ((x+1));
alter index test_expr_idx alter column 1 SET STATISTICS 300;
select alter_table_set_access_method('test','columnar');
ERROR:  relation "public.test_expr_idx" does not exist
CONTEXT:  SQL statement "ALTER INDEX public.test_expr_idx ALTER COLUMN 1 SET STATISTICS 300"
```

### PR DESCRIPTION
**Pull request by halilozanakgul**
Fixes #4519

Moves the call of  `GetAlterIndexStatisticsCommands` from `GetExplicitStatisticsCommandList` to `GatherIndexAndConstraintDefinitionList`

### CODE REVIEW

File: src/backend/distributed/commands/statistics.c [hunk 1]
```diff
@@ -467,19 +467,22 @@ GetExplicitStatisticsCommandList(Oid relationId)
...
-	relation_close(relation, NoLock);
-
-	Oid indexId = InvalidOid;
-	foreach_oid(indexId, indexOidList)
+	if (includeIndexes)
 	{
-		/* we need alter index commands for altered targets on expression indexes */
-		List *alterIndexStatisticsCommands = GetAlterIndexStatisticsCommands(indexId);
+		/* find indexes on current relation, in case of modified stats target */
+		Relation relation = relation_open(relationId, AccessShareLock);
```
Comment (marcocitus) [inline src/backend/distributed/commands/statistics.c:473]: hmz, something seems a little off here. This probably shouldn't have been in GetExplicitStatisticsCommandList to begin with.

**Review by agedemenli — APPROVED** [review]
Thank you

**Review by marcocitus — APPROVED** [review]
