### PR TITLE
Always schema-prefix worker queries

### LINKED ISSUE #215: Worker commands omit target relation's schema
<a href="https://github.com/jasonmp85"></img></a> **Issue by [jasonmp85](https://github.com/jasonmp85)**
_Friday Dec 05, 2014 at 20:27 GMT_
_Originally opened as https://github.com/citusdata/pg_shard/issues/15_

----

_From @samay-sharma on November 21, 2014 15:23_

Steps to reproduce:

```sql
# On master and worker nodes:
CREATE SCHEMA test_schema;
# CREATE SCHEMA

# On master node:
CREATE TABLE test_schema.customer_reviews
(
    customer_id INTEGER,
    review_date DATE,
    review_rating INTEGER,
    review_votes INTEGER,
    review_helpful_votes INTEGER,
    product_id CHAR(10),
    product_title TEXT,
    product_sales_rank BIGINT,
    product_group TEXT,
    product_category TEXT,
    product_subcategory TEXT,
    similar_product_ids CHAR(10)[]
);
# CREATE TABLE

SELECT master_create_distributed_table('test_schema.customer_reviews', 'customer_id', 'hash');
#  master_create_distributed_table
# ---------------------------------
#  
# (1 row)

SELECT master_create_worker_shards('test_schema.customer_reviews', 16, 2);

INSERT INTO test_schema.customer_reviews (customer_id, review_rating) VALUES (4687, 5);
# WARNING:  Bad result from ip-10-181-241-37.ec2.internal:5432
# DETAIL:  Remote message: relation "customer_reviews_86" does not exist
# WARNING:  Bad result from ip-10-102-169-241.ec2.internal:5432
# DETAIL:  Remote message: relation "customer_reviews_86" does not exist
# ERROR:  could not modify any active placements
```

Worker node log:
```sql
# LOG:  statement: INSERT INTO customer_reviews_86 (customer_id, review_rating) VALUES (4687, 5)
# ERROR:  relation "customer_reviews_86" does not exist at character 13
# STATEMENT:  INSERT INTO customer_reviews_86 (customer_id, review_rating) VALUES (4687, 5)
```

### LINKED ISSUE #267: Always schema-prefix table/index names during shard creation
`pg_shard` schema-prefixed _all_ table/index/object names during shard creation, but CitusDB only does so to tables not on the search path. This is probably incorrect and it's easiest to just schema-prefix everything, which we can do.

### LINKED ISSUE #502: master_create_empty_shard function does not propagate schema when search_path is used
If a table is created within a schema implicitly with `search_path` instead of explicitly by prepending the schema, subsequent use of the `master_create_empty_shard` function will create shards in the default `search_path` context on shards. This is despite calling all functions with the explicit schema designation.

## How to Replicate

```
CREATE SCHEMA foo;
SET search_path TO foo;

CREATE TABLE bar (id INT, created_dt TIMESTAMPTZ);

SELECT master_create_distributed_table(
  'foo.bar', 'created_dt', 'append'
);

SELECT master_create_empty_shard('foo.bar');
```

## Results

Attempting to utilize the new table results in a strange error:

```
SELECT * FROM foo.bar;

WARNING:  Bad result from localhost:6100
WARNING:  Bad result from localhost:6101
ERROR:  could not receive query results
```

The error occurs because the shard table, `bar_10217` in this case, exists within the `PUBLIC` schema, while citus expects it in the `foo` schema. Connecting to a shard and viewing the tables shows what happened:

```
\dt

             List of relations
 Schema |     Name      | Type  |   Owner
--------+---------------+-------+-----------
 public | bar_102017    | table | postgres
```

### LINKED ISSUE #556: UDFs created on different schemas does not work
```SQL
CREATE SCHEMA tpch_1;

SET search_path TO public;

CREATE TABLE tpch_1.nation_hash (
    n_nationkey integer not null,
    n_name char(25) not null,
    n_regionkey integer not null,
    n_comment varchar(152));

SELECT master_create_distributed_table('tpch_1.nation_hash', 'n_nationkey', 'hash');
SELECT master_create_worker_shards('tpch_1.nation_hash', 4, 2);
\COPY tpch_1.nation_hash FROM '/Users/onderkalaci/Documents/citus_code/citus/src/test/regress/data/nation.data' with delimiter '|';


CREATE OR REPLACE FUNCTION dummyFunction(theValue integer)
    RETURNS text AS
$$
DECLARE
    strresult text;
BEGIN
    RETURN theValue * 3 / 2 + 1;
END;
$$
LANGUAGE 'plpgsql' IMMUTABLE;


-- works fine
SET search_path TO public;
SELECT dummyFunction(n_nationkey) FROM tpch_1.nation_hash  GROUP BY 1;

-- works fine
SET search_path TO tpch_1;
SELECT dummyFunction(n_nationkey) FROM nation_hash  GROUP BY 1;


-- do this on both the master and workers
SET search_path TO tpch_1;
CREATE OR REPLACE FUNCTION dummyFunction2(theValue integer)
    RETURNS text AS
$$
DECLARE
    strresult text;
BEGIN
    RETURN theValue * 3 / 2 + 1;
END;
$$
LANGUAGE 'plpgsql' IMMUTABLE;

-- works fine
SET search_path TO public;
SELECT tpch_1.dummyFunction2(n_nationkey) FROM tpch_1.nation_hash  GROUP BY 1;

-- errors out
SET search_path TO tpch_1;
SELECT dummyFunction2(n_nationkey) FROM nation_hash  GROUP BY 1;

-- worker log
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
STATEMENT:  COPY (SELECT dummyfunction2(n_nationkey) AS dummyfunction2 FROM tpch_1.nation_hash_102023 nation_hash WHERE true GROUP BY (dummyfunction2(n_nationkey))) TO STDOUT

--similar error without aggreagtes
SELECT dummyFunction2(n_nationkey) FROM nation_hash ;
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
STATEMENT:  COPY (SELECT dummyfunction2(n_nationkey) AS dummyfunction2 FROM tpch_1.nation_hash_102023 nation_hash WHERE true) TO STDOUT

-- Same problem with router planner:

SELECT dummyFunction2(n_nationkey) FROM nation_hash  where n_nationkey = 5;

```

The problem *looks like* generating the function name in the `generate_function_name()` on `ruleutils_9*.c`. We should probably have similar fixes for this one and [267](https://github.com/citusdata/citus/issues/267)

### LINKED ISSUE #557: Cstore_fdw does not work on different schemas
```SQL
CREATE SCHEMA fdw_test;

SET search_path TO public;
CREATE EXTENSION cstore_fdw;

-- create server object
CREATE SERVER cstore_server FOREIGN DATA WRAPPER cstore_fdw;

-- create foreign table
CREATE FOREIGN TABLE fdw_test.customer_reviews
(
    customer_id TEXT,
    review_date DATE,
    review_rating INTEGER,
    review_votes INTEGER,
    review_helpful_votes INTEGER,
    product_id CHAR(10),
    product_title TEXT,
    product_sales_rank BIGINT,
    product_group TEXT,
    product_category TEXT,
    product_subcategory TEXT,
    similar_product_ids CHAR(10)[]
)
SERVER cstore_server
OPTIONS(compression 'pglz');

-- Make regular PostgreSQL table distributed
SELECT master_create_distributed_table('fdw_test.customer_reviews', 'review_date', 'append');

\COPY fdw_test.customer_reviews FROM '/tmp/customer_reviews_1999.csv' WITH CSV;
ERROR:  cannot copy to foreign table "customer_reviews_102008"
DETAIL:  (null)


-- Worker log:

LOG:  duration: 5.084 ms  statement: SELECT worker_apply_shard_ddl_command (102009, 'CREATE EXTENSION IF NOT EXISTS cstore_fdw WITH SCHEMA public')
LOG:  duration: 5.122 ms  statement: SELECT worker_apply_shard_ddl_command (102009, 'CREATE SERVER cstore_server FOREIGN DATA WRAPPER cstore_fdw')
LOG:  duration: 2.032 ms  statement: SELECT worker_apply_shard_ddl_command (102009, 'CREATE SCHEMA IF NOT EXISTS fdw_test')
LOG:  duration: 14.941 ms  statement: SELECT worker_apply_shard_ddl_command (102009, 'CREATE FOREIGN TABLE fdw_test.customer_reviews (customer_id text, review_date date, review_rating integer, review_votes integer, review_helpful_votes integer, product_id character(10), product_title text, product_sales_rank bigint, product_group text, product_category text, product_subcategory text, similar_product_ids character(10)[]) SERVER cstore_server OPTIONS (compression ''pglz'')')
LOG:  duration: 0.226 ms  statement: BEGIN
ERROR:  cannot copy to foreign table "customer_reviews_102009"
STATEMENT:  COPY fdw_test.customer_reviews_102009 FROM STDIN WITH (FORMAT BINARY)
LOG:  duration: 0.120 ms  statement: ROLLBACK



------------ SECOND PART OF THE TEST -----  Create the table when the search_path is set


-- now create the table on the fdw_test schema
SET search_path TO fdw_test;

-- create foreign table
CREATE FOREIGN TABLE customer_reviews_2
(
    customer_id TEXT,
    review_date DATE,
    review_rating INTEGER,
    review_votes INTEGER,
    review_helpful_votes INTEGER,
    product_id CHAR(10),
    product_title TEXT,
    product_sales_rank BIGINT,
    product_group TEXT,
    product_category TEXT,
    product_subcategory TEXT,
    similar_product_ids CHAR(10)[]
)
SERVER cstore_server
OPTIONS(compression 'pglz');

-- Make regular PostgreSQL table distributed
SELECT master_create_distributed_table('customer_reviews_2', 'review_date', 'append');

\COPY customer_reviews_2 FROM '/tmp/customer_reviews_1999.csv' WITH CSV;
WARNING:  Bad result from localhost:9701
DETAIL:  Remote message: relation "fdw_test.customer_reviews_2_102010" does not exist
WARNING:  Bad result from localhost:9700
DETAIL:  Remote message: relation "fdw_test.customer_reviews_2_102010" does not exist
ERROR:  could not find any active placements


-- worker log
 SELECT worker_apply_shard_ddl_command (102010, 'CREATE FOREIGN TABLE customer_reviews_2 (customer_id text, review_date date, review_rating integer, review_votes integer, review_helpful_votes integer, product_id character(10), product_title text, product_sales_rank bigint, product_group text, product_category text, product_subcategory text, similar_product_ids character(10)[]) SERVER cstore_server OPTIONS (compression ''pglz'')')
```
 So, since the root problem here is `worker_apply_shard_ddl_command`, this second part of the test relates to [267](https://github.com/citusdata/citus/issues/267)

  Once the above steps work as expected, try the following queries
```SQL
 SELECT 
    product_category, 
    avg(review_rating) as avg_rating 
FROM 
    customer_reviews 
GROUP BY 
    product_category
ORDER BY 
    avg_rating DESC
LIMIT 10;
```

### LINKED ISSUE #560: Composite types created on different schemas does not work
Here are the steps to re-produce the error:

```SQL
CREATE SCHEMA tpch_1;

SET search_path TO public;

CREATE TYPE tpch_1.new_composite_type as (key1 text, key2 text);


CREATE TABLE tpch_1.nation_hash (
    n_nationkey integer not null,
    n_name char(25) not null,
    n_regionkey integer not null,
    n_comment varchar(152),
    test_col tpch_1.new_composite_type
    );

SELECT master_create_distributed_table('tpch_1.nation_hash', 'n_nationkey', 'hash');
SELECT master_create_worker_shards('tpch_1.nation_hash', 4, 2);
    
\COPY tpch_1.nation_hash FROM STDIN WITH CSV
1,'name',1,'comment_1',"(a,a)"
2,'name',2,'comment_2',"(a,b)"
3,'name',3,'comment_3',"(a,c)"
4,'name',4,'comment_4',"(a,d)"
5,'name',5,'comment_5',"(a,e)"

-- works fine
SELECT * FROM tpch_1.nation_hash  WHERE test_col = '(a,a)'::tpch_1.new_composite_type;
 n_nationkey |          n_name           | n_regionkey |  n_comment  | test_col 
-------------+---------------------------+-------------+-------------+----------
           1 | 'name'                    |           1 | 'comment_1' | (a,a)
           1 | 'name'                    |           1 | 'comment_1' | (a,a)
           1 | 'name'                    |           1 | 'comment_1' | (a,a)
(3 rows)



SET search_path TO tpch_1;
\COPY nation_hash FROM STDIN WITH CSV
1,'name',1,'comment_1',"(a,a)"
2,'name',2,'comment_2',"(a,b)"
3,'name',3,'comment_3',"(a,c)"
4,'name',4,'comment_4',"(a,d)"
5,'name',5,'comment_5',"(a,e)"

-- oops cannot add the type info
SELECT * FROM nation_hash WHERE test_col = '(a,a)'::new_composite_type;
WARNING:  could not receive query results from localhost:9700
DETAIL:  Client error: type "new_composite_type" does not exist

-- worker log
ERROR:  type "new_composite_type" does not exist at character 138
STATEMENT:  COPY (SELECT n_nationkey, n_name, n_regionkey, n_comment, test_col FROM tpch_1.nation_hash_102009 nation_hash WHERE (test_col = '(a,a)'::new_composite_type)) TO STDOUT
```
I haven't looked into the detail but similar to [267](https://github.com/citusdata/citus/issues/267) and [556](https://github.com/citusdata/citus/issues/556), we should add the schema information about the composite type while deparsing the query.

The owner of this task should also ensure that the fix works for router planner as well.

### LINKED ISSUE #568: master_modify_multiple_shards() UDF does not work on different schemas
It looks like the issue is related to [215](https://github.com/citusdata/citus/issues/215) where `deparse_shard_query()` does not take schema of the table into the considiration.

Here are the steps to reproduce the issue:

```SQL
CREATE SCHEMA tpch;

CREATE TABLE tpch.nation_hash (
    n_nationkey integer not null,
    n_name char(25) not null,
    n_regionkey integer not null,
    n_comment varchar(152));

SELECT master_create_distributed_table('tpch.nation_hash', 'n_nationkey', 'hash');
SELECT master_create_worker_shards('tpch.nation_hash', 4, 1);

\COPY tpch.nation_hash FROM STDIN WITH CSV
1,'name',1,'comment_1'
2,'name',2,'comment_2'
3,'name',3,'comment_3'
4,'name',4,'comment_4'
5,'name',5,'comment_5'

SET search_path TO public;
SELECT master_modify_multiple_shards('UPDATE tpch.nation_hash SET n_regionkey = n_regionkey + 1');
WARNING:  Bad result from localhost:9700
DETAIL:  Remote message: relation "nation_hash_102008" does not exist
ERROR:  could not send query to shard placement

-- worker log
LOG:  duration: 0.202 ms  statement: BEGIN
ERROR:  relation "nation_hash_102008" does not exist at character 8
STATEMENT:  UPDATE nation_hash_102008 SET n_regionkey = (n_regionkey + 1)

-- same error
SET search_path TO tpch;
SELECT master_modify_multiple_shards('UPDATE nation_hash SET n_regionkey = n_regionkey + 1');
```

### LINKED ISSUE #623: Operators created on different schemas does not work
Here are the steps to re-produce the error:

```SQL
CREATE SCHEMA tpch_1;

CREATE OPERATOR tpch_1.=== (
    LEFTARG = int,
    RIGHTARG = int,
    PROCEDURE = int4eq,
    COMMUTATOR = ===,
    NEGATOR = !==,
    HASHES, MERGES
);

SET search_path TO public;


CREATE TABLE tpch_1.nation_hash (
    n_nationkey integer not null,
    n_name char(25) not null,
    n_regionkey integer not null,
    n_comment varchar(152)
    );

SELECT master_create_distributed_table('tpch_1.nation_hash', 'n_nationkey', 'hash');
SELECT master_create_worker_shards('tpch_1.nation_hash', 4, 2);

\COPY tpch_1.nation_hash FROM STDIN WITH CSV
1,'name',1,'comment_1'
2,'name',2,'comment_2'
3,'name',3,'comment_3'
4,'name',4,'comment_4'
5,'name',5,'comment_5'

-- this query works as expected
SELECT * FROM tpch_1.nation_hash  WHERE n_nationkey OPERATOR(tpch_1.===) 1;

SET search_path TO tpch_1;

-- this query fails
SELECT * FROM tpch_1.nation_hash  WHERE n_nationkey OPERATOR(===) 1;

-- worker log
ERROR:  operator is only a shell: integer === integer at character 120
STATEMENT:  COPY (SELECT n_nationkey, n_name, n_regionkey, n_comment FROM tpch_1.nation_hash_102008 nation_hash WHERE (n_nationkey === 1)) TO STDOUT
ERROR:  operator is only a shell: integer === integer at character 120
STATEMENT:  COPY (SELECT n_nationkey, n_name, n_regionkey, n_comment FROM tpch_1.nation_hash_102010 nation_hash WHERE (n_nationkey === 1)) TO STDOUT
ERROR:  operator is only a shell: integer === integer at character 120
STATEMENT:  COPY (SELECT n_nationkey, n_name, n_regionkey, n_comment FROM tpch_1.nation_hash_102009 nation_hash WHERE (n_nationkey === 1)) TO STDOUT
ERROR:  operator is only a shell: integer === integer at character 120

```

I haven't looked into the detail but similar to #267, #560 and #556, we should add the schema information about the operators while deparsing the query.

The owner of this task should also ensure that the fix works for router planner as well.

### LINKED ISSUE #624: COLLATION created on different schemas does not work
Steps to re-produce:

```SQL
CREATE TABLE tpch_1.nation_hash (
    n_nationkey integer not null,
    n_name char(25) not null,
    n_regionkey integer not null,
    n_comment varchar(152)
    );

SELECT master_create_distributed_table('tpch_1.nation_hash', 'n_nationkey', 'hash');
SELECT master_create_worker_shards('tpch_1.nation_hash', 4, 2);

\COPY tpch_1.nation_hash FROM STDIN WITH CSV
1,'name',1,'comment_1'
2,'name',2,'comment_2'
3,'name',3,'comment_3'
4,'name',4,'comment_4'
5,'name',5,'comment_5'

CREATE COLLATION tpch_1.german FROM "de_DE";

SET search_path TO public;

-- this works as expected
SELECT n_name = 'Turkey' COLLATE tpch_1.german FROM tpch_1.nation_hash;

SET search_path TO tpch_1;

-- this query fails
SELECT n_name = 'Turkey' COLLATE german FROM nation_hash;

-- master log
WARNING:  collation "german" for encoding "UTF8" does not exist
CONTEXT:  while executing command on localhost:9700

-- worker log
ERROR:  collation "german" for encoding "UTF8" does not exist at character 41
STATEMENT:  COPY (SELECT (n_name = 'Turkey'::bpchar COLLATE german) FROM tpch_1.nation_hash_102010 nation_hash WHERE true) TO STDOUT
```

I haven't looked into the detail but similar to #267, #560, #623 and #556, we should add the schema information about the collations while deparsing the query.

The owner of this task should also ensure that the fix works for router planner as well.

### PR DESCRIPTION
**Pull request by byucesoy**
With this change we schema-prefix table names, operator names and composite types.

Fixes #215
Fixes #267
Fixes #502
Fixes #556
Fixes #557
Fixes #560
Fixes #568
Fixes #623
Fixes #624

### CODE REVIEW

**Comment by onderkalaci** [comment]
@byucesoy I haven't looked into the implementation details yet, but I'm curious whether you'll add regression tests for the PR that fixes 9 issues :)

**Comment by metdos** [comment]
> @byucesoy I haven't looked into the implementation details yet, but I'm curious whether you'll add regression tests for the PR that fixes 9 issues :)

@onderkalaci he will do. I asked Burak to create PR, so I can start reviewing while he adds regression tests :)

File: src/backend/distributed/utils/citus_ruleutils.c [hunk 1]
```diff
@@ -229,51 +229,61 @@ pg_get_tableschemadef_string(Oid tableRelationId)
 	AttrNumber constraintIndex = 0;
 	AttrNumber constraintCount = 0;
 	StringInfoData buffer = { NULL, 0, 0, 0 };
+	OverrideSearchPath *overridePath = GetOverrideSearchPath(CurrentMemoryContext);
```
Comment (metdos) [inline src/backend/distributed/utils/citus_ruleutils.c]: Could you add comments for PG_TRY() and overridePath initialization similar to ones in multi_copy.c?
https://github.com/citusdata/citus/blob/master/src/backend/distributed/commands/multi_copy.c#L450

File: src/backend/distributed/utils/citus_ruleutils.c [hunk 2]
```diff
@@ -325,64 +335,72 @@ pg_get_tableschemadef_string(Oid tableRelationId)
...
+		relation_close(relation, AccessShareLock);
 	}
+	PG_CATCH();
+	{
+		PopOverrideSearchPath();
 
-	relation_close(relation, AccessShareLock);
+		PG_RE_THROW();
+	}
+	PG_END_TRY();
```
Comment (metdos) [inline src/backend/distributed/utils/citus_ruleutils.c]: After PG_END_TRY(), we can put a newline to make it a bit more readable.

File: src/backend/distributed/utils/citus_ruleutils.c [hunk 3]
```diff
@@ -229,51 +229,61 @@ pg_get_tableschemadef_string(Oid tableRelationId)
...
-	}
-	else
-	{
-		appendStringInfo(&buffer, "CREATE FOREIGN TABLE %s (", relationName);
-	}
+		relationKind = relation->rd_rel->relkind;
+		if (relationKind != RELKIND_RELATION && relationKind != RELKIND_FOREIGN_TABLE)
+		{
+			ereport(ERROR, (errcode(ERRCODE_WRONG_OBJECT_TYPE),
+							errmsg("%s is not a regular or foreign table", relationName)));
```
Comment (metdos) [inline src/backend/distributed/utils/citus_ruleutils.c]: Could you run citus_indent? We added PG_TRY() blocks, so some lines are longer than 90 characters now.

File: src/backend/distributed/utils/citus_ruleutils.c [hunk 4]
```diff
@@ -229,51 +229,61 @@ pg_get_tableschemadef_string(Oid tableRelationId)
...
-	 */
-	relation = relation_open(tableRelationId, AccessShareLock);
-	relationName = generate_relation_name(tableRelationId, NIL);
+	overridePath->schemas = NIL;
+	overridePath->addCatalog = true;
+	PushOverrideSearchPath(overridePath);
 
-	relationKind = relation->rd_rel->relkind;
-	if (relationKind != RELKIND_RELATION && relationKind != RELKIND_FOREIGN_TABLE)
+	PG_TRY();
```
Comment (marcocitus) [inline src/backend/distributed/utils/citus_ruleutils.c]: Can we avoid using PG_TRY here? PG_TRY has a lot of caveats and it's unclear to me whether this function correctly handles them. It might cause segfaults on some platforms.

Comment (byucesoy) [inline src/backend/distributed/utils/citus_ruleutils.c]: I am not sure if we can avoid that. We need to be sure that PopOverrideSearchPath(); is called even if some error occures during query execution. Otherwise we may corrupt search_path stack. Do you have any suggestion instead of PG_TRY()?

File: src/backend/distributed/utils/citus_ruleutils.c (hunk 1 above)
Comment (byucesoy) [inline src/backend/distributed/utils/citus_ruleutils.c]: I removed PG_TRY() and added comments for overridePath.

**Comment by metdos** [comment]
@byucesoy, why do we have failing regression tests?

File: src/backend/distributed/utils/citus_ruleutils.c [hunk 5]
```diff
@@ -272,58 +272,60 @@ pg_get_tableschemadef_string(Oid tableRelationId)
 		const char *attributeName = NULL;
 		const char *attributeTypeName = NULL;
 
-		if (!attributeForm->attisdropped && attributeForm->attinhcount == 0)
+		if (attributeForm->attisdropped || attributeForm->attinhcount != 0)
```
Comment (metdos) [inline src/backend/distributed/utils/citus_ruleutils.c]: Do we need these changes if we don't need Pg_TRY blocks?

File: src/backend/distributed/utils/citus_ruleutils.c [hunk 6]
```diff
@@ -284,7 +284,7 @@ pg_get_tableschemadef_string(Oid tableRelationId)
 			appendStringInfo(&buffer, "%s ", quote_identifier(attributeName));
 
 			attributeTypeName = format_type_with_typemod(attributeForm->atttypid,
-														 attributeForm->atttypmod);
+														attributeForm->atttypmod);
```
Comment (metdos) [inline src/backend/distributed/utils/citus_ruleutils.c]: Can we also revert this change?

File: src/backend/distributed/master/master_node_protocol.c [hunk 7]
```diff
@@ -556,6 +556,16 @@ GetTableDDLEvents(Oid relationId)
...
 	int scanKeyCount = 1;
 	HeapTuple heapTuple = NULL;
+	OverrideSearchPath *overridePath = GetOverrideSearchPath(CurrentMemoryContext);
+
+	/*
+	 * Set search_path to NIL so that all objects outside of pg_catalog will be
+	 * schema-prefixed. pg_catalog will be added automatically when we call
+	 * PushOverrideSearchPath(), since we set addCatalog to true;
+	 */
+	overridePath->schemas = NIL;
```
Comment (metdos) [inline src/backend/distributed/master/master_node_protocol.c]: I think it looks better if we keep initialization together.

// comments
OverrideSearchPath *overridePath = GetOverrideSearchPath(CurrentMemoryContext);
overridePath->schemas = NIL;
...

or

// comments
overridePath = GetOverrideSearchPath(CurrentMemoryContext);
overridePath->schemas = NIL; 
....


Similarly for other files.

File: src/backend/distributed/master/master_node_protocol.c [hunk 8]
```diff
@@ -666,6 +676,8 @@ GetTableDDLEvents(Oid relationId)
 	systable_endscan(scanDescriptor);
 	heap_close(pgIndex, AccessShareLock);
 
+	PopOverrideSearchPath();
```
Comment (metdos) [inline src/backend/distributed/master/master_node_protocol.c]: We can add one line comment explain this.

File: src/test/regress/expected/multi_schema_support.out [hunk 9]
```diff
@@ -3,10 +3,19 @@
 --
 ALTER SEQUENCE pg_catalog.pg_dist_shardid_seq RESTART 1190000;
 ALTER SEQUENCE pg_catalog.pg_dist_jobid_seq RESTART 1190000;
--- test master_append_table_to_shard with schema
+-- create schema to test schema support
 CREATE SCHEMA test_schema_support;
 NOTICE:  Citus partially supports CREATE SCHEMA for distributed databases
 DETAIL:  schema usage in joins and in some UDFs provided by Citus are not supported yet
+-- test master_append_table_to_shard with schema
```
Comment (metdos) [inline src/test/regress/expected/multi_schema_support.out]: Is there a reason to move creation of public.nation_local to here.

File: src/test/regress/sql/multi_schema_support.sql [hunk 10]
```diff
@@ -69,3 +70,301 @@ SELECT master_append_table_to_shard(1190001, 'nation_local', 'localhost', :maste
 
 -- verify table actually appended to shard
 SELECT COUNT(*) FROM "nation._'append";
+
+
+-- test shard creation when search_path is set
+SET search_path TO test_schema_support;
+
+-- create shard with COPY on append distributed table
+CREATE TABLE nation_append2(
```
Comment (metdos) [inline src/test/regress/sql/multi_schema_support.sql]: Is this table created for just search path check? I couldn't see other references. Maybe we can rename it to nation_append_search_path, or something else...

**Comment by metdos** [comment]
@byucesoy,

This example from #267 still does not work. Could you also add index creation to regression tests?

```sql
SET search_path TO tpch;
CREATE INDEX i2 ON nation_hash(n_nationkey);
WARNING:  could not receive query results from localhost:9700
DETAIL:  Client error: relation "nation_hash_102008" does not exist
ERROR:  could not execute DDL command on worker node shards
```

File: src/test/regress/expected/multi_schema_support.out (hunk 9 above)
Comment (byucesoy) [inline src/test/regress/expected/multi_schema_support.out]: I want to separate distributed tables and test logic from that particular local table.

**Comment by byucesoy** [comment]
#267 originally opened for a bug which is related with schema prefixing on the queries sent to worker, but then added some other example which are mote related with worker_apply_shard_ddl_command and those bugs will be fixed with #626. I added a comment in #267 explaining this situation.

File: src/test/regress/sql/multi_schema_support.sql (hunk 10 above)
Comment (byucesoy) [inline src/test/regress/sql/multi_schema_support.sql]: Yes it is. I am changing the name.

File: src/test/regress/expected/multi_schema_support.out [hunk 11]
```diff
@@ -107,3 +108,412 @@ SELECT COUNT(*) FROM "nation._'append";
...
+---------------------------------
+ 
+(1 row)
+
+SELECT master_create_worker_shards('test_schema_support.nation_hash_search_path', 4, 1);
+ master_create_worker_shards 
+-----------------------------
+ 
+(1 row)
+
```
Comment (metdos) [inline src/test/regress/expected/multi_schema_support.out]: Could we insert/copy some row/rows to get results from selects?

File: src/test/regress/expected/multi_schema_support.out [hunk 12]
```diff
@@ -107,3 +108,412 @@ SELECT COUNT(*) FROM "nation._'append";
...
+SELECT * FROM test_schema_support.nation_hash_search_path  WHERE test_col = '(a,a)'::test_schema_support.new_composite_type;
```
Comment (metdos) [inline src/test/regress/expected/multi_schema_support.out]: Could we insert/copy some row/rows to get results from selects?

File: src/test/regress/sql/multi_schema_support.sql [hunk 13]
```diff
@@ -69,3 +70,301 @@ SELECT master_append_table_to_shard(1190001, 'nation_local', 'localhost', :maste
 
 -- verify table actually appended to shard
 SELECT COUNT(*) FROM "nation._'append";
+
+
+-- test shard creation when search_path is set
```
Comment (metdos) [inline src/test/regress/sql/multi_schema_support.sql]: We have two newlines between different test groups. Could you use a bit more descriptive comment for this one?

File: src/test/regress/sql/multi_schema_support.sql [hunk 14]
```diff
@@ -69,3 +70,301 @@ SELECT master_append_table_to_shard(1190001, 'nation_local', 'localhost', :maste
...
+\c - - - :master_port
+
+-- UDF in public, table in schema, search_path is not set
+SELECT dummyFunction(n_nationkey) FROM test_schema_support.nation_hash GROUP BY 1;
+
+-- UDF in public, table in schema, search_path is set
+SET search_path TO test_schema_support;
+SELECT public.dummyFunction(n_nationkey) FROM test_schema_support.nation_hash GROUP BY 1;
+
+-- create UDF in master node in schema
```
Comment (metdos) [inline src/test/regress/sql/multi_schema_support.sql]: Do you mean a schema different from the public?

File: src/test/regress/pg_regress_multi.pl [hunk 15]
```diff
@@ -112,7 +113,11 @@ ()
                'bug_status', ' ENUM (\'new\', \'open\', \'closed\')');
 
 # define functions as signature->definition
-%functions = ('fake_fdw_handler()', 'fdw_handler AS \'citus\' LANGUAGE C STRICT;');
+%functions = ('fake_fdw_handler()', 'fdw_handler AS \'citus\' LANGUAGE C STRICT;',
+               'equal_test_composite_type_function(test_composite_type, test_composite_type)', 'boolean AS \'select $1.i = $2.i AND $1.i2 = $2.i2;\' LANGUAGE SQL IMMUTABLE RETURNS NULL ON NULL INPUT;');
```
Comment (metdos) [inline src/test/regress/pg_regress_multi.pl]: This line is very long. Could you make it shorter?

File: src/test/regress/sql/multi_schema_support.sql [hunk 16]
```diff
@@ -69,3 +70,301 @@ SELECT master_append_table_to_shard(1190001, 'nation_local', 'localhost', :maste
...
+
+
+-- test cursors
+SET search_path TO public;
+BEGIN;
+DECLARE test_cursor CURSOR FOR 
+    SELECT *
+        FROM test_schema_support.nation_append
+        WHERE n_nationkey = 1;
+        FETCH test_cursor;
```
Comment (metdos) [inline src/test/regress/sql/multi_schema_support.sql]: Why do you we have  FETCH test_cursor; twice? And why do they return the same result? Do you have a bug in cursors, or do we have the same row twice?

Similarly below

File: src/test/regress/sql/multi_schema_support.sql [hunk 17]
```diff
@@ -69,3 +70,301 @@ SELECT master_append_table_to_shard(1190001, 'nation_local', 'localhost', :maste
...
+BEGIN
+    RETURN theValue * 3 / 2 + 1;
+END;
+$$
+LANGUAGE 'plpgsql' IMMUTABLE;
+
+\c - - - :master_port
+
+-- UDF in public, table in schema, search_path is not set
+SELECT dummyFunction(n_nationkey) FROM test_schema_support.nation_hash GROUP BY 1;
```
Comment (metdos) [inline src/test/regress/sql/multi_schema_support.sql]: Could you also add "order by"  to this query? The result does not need to be in the same order always.

File: src/test/regress/expected/multi_schema_support.out [hunk 18]
```diff
@@ -107,3 +108,412 @@ SELECT COUNT(*) FROM "nation._'append";
...
+SET search_path TO public;
+CREATE COLLATION test_schema_support.english FROM "en_US";
+-- create COLLATION in worker node 1 in schema
+\c - - - :worker_1_port
+CREATE COLLATION test_schema_support.english FROM "en_US";
+-- create COLLATION in worker node 2 in schema
+\c - - - :worker_2_port
+CREATE COLLATION test_schema_support.english FROM "en_US";
+\c - - - :master_port
+SELECT n_name = 'Turkey' COLLATE test_schema_support.english FROM test_schema_support.nation_hash;
```
Comment (metdos) [inline src/test/regress/expected/multi_schema_support.out]: This query does not make sense that much. Could you use a typical COLLATE query? Such as using order by
https://www.postgresql.org/docs/9.5/static/collation.html

File: src/test/regress/sql/multi_schema_support.sql [hunk 19]
```diff
@@ -69,3 +70,342 @@ SELECT master_append_table_to_shard(1190001, 'nation_local', 'localhost', :maste
 
 -- verify table actually appended to shard
 SELECT COUNT(*) FROM "nation._'append";
+
+
+-- test shard creation on append(by data loading) and hash distributed(with UDF) tables when search_path is set
```
Comment (metdos) [inline src/test/regress/sql/multi_schema_support.sql]: Could you use multiple lines for this comment?

File: src/test/regress/expected/multi_schema_support.out [hunk 20]
```diff
@@ -448,33 +429,67 @@ CREATE COLLATION test_schema_support.english FROM "en_US";
 \c - - - :worker_2_port
 CREATE COLLATION test_schema_support.english FROM "en_US";
```
Comment (metdos) [inline src/test/regress/expected/multi_schema_support.out]: Could you also add a select test similar to;

select title from articles_hash order by title COLLATE test_schema_support.english;

**Comment by metdos** [comment]
@byucesoy, 
I have two minor comments. After fixing them, you can squash and :ship:
