### PR TITLE
Use CommitContext for subxact mgmt and reduce memory usage in CommitContext

### LINKED ISSUE #5000: Citus may have lead to PANIC in Abort[Sub]Transaction - Investigate a Abort[Sub]Transaction functions for possible bugs
The following coredump generated with a Postgres server where Citus is installed.  My initial reaction was that this core-dump doesn't have Citus functions involved, hence probably not relevant to Citus.

However, talking with Andres, he thinks that this is a core-dump likely lead by Citus (or any other extension). The server is PG 11.10. 

The crash is generated when more than 5 exceptions are thrown on AbortTransaction callbacks. It is OK to throw an error on AbortTransction, but we should only be throwing the error if the underlying problem has been solved / can be solved. If the underlying problem is not solved, and we throw more than 5 errors via recursive calls during AbortTransction, Postgres cannot handle anymore and leads to PANIC.

```
(gdb) bt
#0 0x00007f85f7c33438 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1 0x00007f85f7c3503a in __GI_abort () at abort.c:89
#2 0x000000000084f169 in errfinish (dummy=<optimized out>) at elog.c:555
#3 0x00000000008534a7 in elog_start (filename=filename@entry=0x89de97 "xact.c", lineno=lineno@entry=4785, funcname=funcname@entry=0x8a1c30 <__func__.28854> "AbortSubTransaction")
at elog.c:1319
#4 0x00000000004faa05 in AbortSubTransaction () at xact.c:4784
#5 0x00000000004faf75 in AbortCurrentTransaction () at xact.c:3163
#6 0x0000000000745785 in PostgresMain (argc=1, argv=argv@entry=XXX, dbname=xXXXXX", username=0x23ffbc8 "XXX") at postgres.c:3968
#7 0x0000000000481677 in BackendRun (port=0x23b7230) at postmaster.c:4402
#8 BackendStartup (port=0x23b7230) at postmaster.c:4066
#9 ServerLoop () at postmaster.c:1728
#10 0x00000000006d768b in PostmasterMain (argc=argc@entry=1, argv=argv@entry=0xdbc220) at postmaster.c:1401
#11 0x00000000004825ab in main (argc=1, argv=0xdbc220) at main.c:228
```

As a side node, if Citus hits to an error on AbortTransaction callbacks, it is often better to throw PANIC at that point unless the problem can be resolved. Because, with this backtrace, we lost all the information about what is causing this core-dump .

### PR DESCRIPTION
**Pull request by onurctirtir**
(Hopefully) Fixes #5000.

If memory allocation done for `SubXactContext *state` in `PushSubXact()`
fails, then `PopSubXact()` might segfault, for example, when grabbing the
topmost `SubXactContext` from `activeSubXactContexts` if this is the first
ever subxact within the current xact, with the following stack trace:
```c
citus.so!list_nth_cell(const List * list, int n) (\opt\pgenv\pgsql-14.3\include\server\nodes\pg_list.h:260)
citus.so!PopSubXact(SubTransactionId subId) (\home\onurctirtir\citus\src\backend\distributed\transaction\transaction_management.c:761)
citus.so!CoordinatedSubTransactionCallback(SubXactEvent event, SubTransactionId subId, SubTransactionId parentSubid, void * arg) (\home\onurctirtir\citus\src\backend\distributed\transaction\transaction_management.c:673)
CallSubXactCallbacks(SubXactEvent event, SubTransactionId mySubid, SubTransactionId parentSubid) (\opt\pgenv\src\postgresql-14.3\src\backend\access\transam\xact.c:3644)
AbortSubTransaction() (\opt\pgenv\src\postgresql-14.3\src\backend\access\transam\xact.c:5058)
AbortCurrentTransaction() (\opt\pgenv\src\postgresql-14.3\src\backend\access\transam\xact.c:3366)
PostgresMain(int argc, char ** argv, const char * dbname, const char * username) (\opt\pgenv\src\postgresql-14.3\src\backend\tcop\postgres.c:4250)
BackendRun(Port * port) (\opt\pgenv\src\postgresql-14.3\src\backend\postmaster\postmaster.c:4530)
BackendStartup(Port * port) (\opt\pgenv\src\postgresql-14.3\src\backend\postmaster\postmaster.c:4252)
ServerLoop() (\opt\pgenv\src\postgresql-14.3\src\backend\postmaster\postmaster.c:1745)
PostmasterMain(int argc, char ** argv) (\opt\pgenv\src\postgresql-14.3\src\backend\postmaster\postmaster.c:1417)
main(int argc, char ** argv) (\opt\pgenv\src\postgresql-14.3\src\backend\main\main.c:209)
```

For this reason, to be more defensive against memory-allocation errors
that could happen at `PushSubXact()`, now we use our pre-allocated memory 
context for the objects created in `PushSubXact()`.

This commit also attempts reducing the memory allocations done under
CommitContext to reduce the chances of consuming all the memory available
to CommitContext.

Note that it's problematic to encounter with such a memory-allocation
error for other objects created in `PushSubXact()` as well, so above is
an **example** scenario that might result in a segfault.

DESCRIPTION: Fixes a bug that might cause segfaults when handling deeply nested subtransactions

### CODE REVIEW

File: src/backend/distributed/transaction/transaction_management.c [hunk 1]
```diff
@@ -730,16 +730,25 @@ static void
 PushSubXact(SubTransactionId subId)
 {
 	/*
-	 * We need to allocate these in TopTransactionContext instead of current
-	 * subxact's memory context. This is because AtSubCommit_Memory won't
-	 * delete the subxact's memory context unless it is empty, and this
+	 * We need to allocate these in a long-living memory context instead of
```
Comment (marcocitus) [inline src/backend/distributed/transaction/transaction_management.c:733]: CitusXactCallbackContext is not particularly long-living

File: src/backend/distributed/transaction/transaction_management.c [hunk 2]
```diff
@@ -730,16 +730,25 @@ static void
...
+	 * current subxact's memory context. This is because AtSubCommit_Memory
+	 * won't delete the subxact's memory context unless it is empty, and this
 	 * can cause in memory leaks. For emptiness it just checks if the memory
 	 * has been reset, and we cannot reset the subxact context since other
 	 * data can be in the context that are needed by upper commits.
 	 *
 	 * See https://github.com/citusdata/citus/issues/3999
+	 *
+	 * Also, any memory error that we might encounter here might leave
+	 * activeSubXactContexts in an inconsistent state and this might result in
```
Comment (marcocitus) [inline src/backend/distributed/transaction/transaction_management.c:743]: As far as I can tell, we're only preventing memory leaks, not changing anything about what's in activeSubXactContexts.

Comment (onderkalaci) [reply src/backend/distributed/transaction/transaction_management.c:743]: It seems `AllocSetContextCreateExtended` does a `malloc` for initSize. Wouldn't it mean we can prevent OOMs might happen below via `palloc`?

Comment (marcocitus) [reply src/backend/distributed/transaction/transaction_management.c:743]: hmz, but if that's the issue we're solving shouldn't we be more worried about things like CoordinatedRemoteTransactionsSavepointRollback ?

The issue described by the comment suggests we're more concerned with OOM leaving the global variables in an inconsistent state.

Comment (onderkalaci) [reply src/backend/distributed/transaction/transaction_management.c:743]: >  but if that's the issue we're solving

Tbh, we cannot reliably produce the issue we are trying to solve. So, we don't have a very specific thing to fix. We sometimes get back-traces, with workloads that involve OOMs, and lots of plpgsql functions with multiple levels of `exception` blocks. And, the `bt`s points to (sub)transaction callbacks.

I think one of our suspicion is that an OOM on these functions, could easily cause crashes in different ways. Sometimes, we get PANIC because we might get 5 OOMs/errors in these functions and Postgres does it somewhere [here](https://github.com/postgres/postgres/blob/b40baa96a7ad789718dcf59b1dd73bae15c3a7e1/src/backend/utils/error/elog.c#L433-L442). Sometimes NULL pointer access, or seg faults, which I suspect because of an OOM during the callbacks, the stack is not properly maintained. 

>  shouldn't we be more worried about things like CoordinatedRemoteTransactionsSavepointRollback ?

I agree that the fix should be covering all the sub-transaction functions if we are really worried about OOMs

**Comment by onurctirtir** [comment]
Another coredump from user, which is nearly the same one that we got from user's cluster! (cc: @onderkalaci, @marcocitus)

```c
#0  0x00007f0fefaae335 in PopSubXact (subId=<optimized out>) from /usr/pgsql-11/lib/citus.so
#1  0x00000000004fb25a in CallSubXactCallbacks (parentSubid=1, mySubid=2,  event=SUBXACT_EVENT_ABORT_SUB) at xact.c:3465
#2  AbortSubTransaction () at xact.c:4842
#3  0x00000000004fb6f5 in AbortCurrentTransaction () at xact.c:3172
#4  0x000000000074911f in PostgresMain (argc=1, argv=argv@entry=0x2b196c8,
    dbname=0x2ae85d8 "citus", username=0x7f0ffeaf8008 "citus")
    at postgres.c:3990
#5  0x00000000004818fc in BackendRun (port=0x2a99bc0) at postmaster.c:4422
#6  BackendStartup (port=0x2a99bc0) at postmaster.c:4086
#7  ServerLoop () at postmaster.c:1728
#8  0x00000000006db759 in PostmasterMain (argc=argc@entry=3,
    argv=argv@entry=0x2a522d0) at postmaster.c:1401
#9  0x000000000048277f in main (argc=3, argv=0x2a522d0) at main.c:228
(gdb)
```

File: src/backend/distributed/transaction/transaction_management.c (hunk 2 above)
Comment (onurctirtir) [reply src/backend/distributed/transaction/transaction_management.c:743]: > shouldn't we be more worried about things like CoordinatedRemoteTransactionsSavepointRollback ?

I think we should be careful about the memory context being used not during "about" but "begin", so that accessing to a NULL pointer --saved at the beginning of the transaction-- doesn't cause a segfault.

And for the abort handlers, I think getting an OOM error is less problematic than the "begin", since it would cause a panic/fatal instead of a segfault in that case.

Comment (onderkalaci) [reply src/backend/distributed/transaction/transaction_management.c:743]: PANIC as worse as a segfault

Comment (thanodnl) [reply src/backend/distributed/transaction/transaction_management.c:743]: If we allocate the state kept for the subxact in the overarching transaciont, could we then remove the pfree's from the PopSubXact callback?

Assuming the change of memory context we allocate the state in we shouldn't be as afraid anymore for leaks do we?

Changing the context we allocate in does not prevent an OOM from happening. This context could also be out of allocated space and failing to expand.

This is ofcourse assuming that an allocation failure causes a segfault, presumably due to double pfree.

Comment (onderkalaci) [reply src/backend/distributed/transaction/transaction_management.c:743]: > Changing the context we allocate in does not prevent an OOM from happening. This context could also be out of allocated space and failing to expand.

Yes, of course that is possible, but with a lot less likelihood. I was also planning to calculate how much memory a single `SAVEPOINT/ROLLBACK` generates, so that we could consider a saner value for the initial allocation, which is 8KB for now.

> If we allocate the state kept for the subxact in the overarching transaciont, could we then remove the pfree's from the PopSubXact callback?
 Assuming the change of memory context we allocate the state in we shouldn't be as afraid anymore for leaks do we?

Sounds interesting, and probably right. I mean, the context we use is not relevant, even for `TopTransactionContext`, we could consider not `pfree`ing anyway. 


ps: I have not looked into the fix (and this code-path for a while), so I still suspect `pfree` is not the only root of these crashes.

Comment (onurctirtir) [reply src/backend/distributed/transaction/transaction_management.c:743]: > so I still suspect pfree is not the only root of these crashes.

This is true, linitial() might also trigger a segfault if the stack is empty (as given in the stack trace at PR description)

Comment (marcocitus) [reply src/backend/distributed/transaction/transaction_management.c:743]: > Yes, of course that is possible, but with a lot less likelihood. I was also planning to calculate how much memory a single SAVEPOINT/ROLLBACK generates, so that we could consider a saner value for the initial allocation, which is 8KB for now.

presumably we know the maximum length that these commands can have, so we should be able to allocate them on the stack

Comment (onurctirtir) [reply src/backend/distributed/transaction/transaction_management.c:743]: > This is ofcourse assuming that an allocation failure causes a segfault

But this is true even in the double-free case, since the main problem there is that we leave PushSubXact() before setting all the globar vars properly, and this could only happen due to an OOM error ?

**Comment by onurctirtir** [comment]
> shouldn't we be more worried about things like CoordinatedRemoteTransactionsSavepointRollback ?

Pushed a new commit to guard all subxact states under CoordinatedSubTransactionCallback by switching to CitusXactCallbackContext in all such subxact states.

And looked into code to see if it could be problematic to do memory allocations under CoordinatedSubTransactionCallback in all such cases and this seems fine as we will be using this memory context only to enlarge some lists or when pushing a SubXactContext into the stack.

Does that make sense to you @marcocitus & @onderkalaci ?

File: src/backend/distributed/transaction/transaction_management.c [hunk 3]
```diff
@@ -321,9 +321,9 @@ CoordinatedTransactionCallback(XactEvent event, void *arg)
 
 			PlacementMovedUsingLogicalReplicationInTX = false;
 
-			/* empty the CommitContext to ensure we're not leaking memory */
+			/* empty the CitusXactCallbackContext to ensure we're not leaking memory */
 			MemoryContextSwitchTo(previousContext);
-			MemoryContextReset(CommitContext);
+			MemoryContextReset(CitusXactCallbackContext);
```
Comment (marcocitus) [inline src/backend/distributed/transaction/transaction_management.c:326]: should also do this in abort handler

File: src/backend/distributed/transaction/transaction_management.c [hunk 4]
```diff
@@ -628,16 +628,25 @@ CoordinatedSubTransactionCallback(SubXactEvent event, SubTransactionId subId,
 		 */
 		case SUBXACT_EVENT_START_SUB:
 		{
+			MemoryContext previousContext = CurrentMemoryContext;
+			MemoryContextSwitchTo(CitusXactCallbackContext);
+
 			PushSubXact(subId);
 			if (InCoordinatedTransaction())
 			{
 				CoordinatedRemoteTransactionsSavepointBegin(subId);
```
Comment (marcocitus) [inline src/backend/distributed/transaction/transaction_management.c:637]: we should avoid doing allocations in these functions (e.g. use sprintf on a char array on the stack), since they're currently leaking into the memory context

File: src/backend/distributed/transaction/transaction_management.c (hunk 3 above)
Comment (onurctirtir) [reply src/backend/distributed/transaction/transaction_management.c:327]: done

File: src/backend/distributed/transaction/transaction_management.c (hunk 4 above)
Comment (onurctirtir) [reply src/backend/distributed/transaction/transaction_management.c:642]: Pushed some changes for this but following functions still use StringInfo's, is that okay ?:

// because this acts on variable length strings
StartRemoteTransactionBegin

// Because those are supposed to return the string buffers they create
//
// Could pass some stack allocated buffers into those functions but not
// sure if that would worth ?
BeginAndSetDistributedTransactionIdCommand
AssignDistributedTransactionIdCommand

File: src/backend/distributed/transaction/remote_transaction.c [hunk 5]
```diff
@@ -395,16 +414,22 @@ StartRemoteTransactionAbort(MultiConnection *connection)
...
-
-		/* await PREPARE TRANSACTION results, closing the connection would leave it dangling */
 		ForgetResults(connection);
 
-		initStringInfo(&command);
-		appendStringInfo(&command, "ROLLBACK PREPARED %s",
-						 quote_literal_cstr(transaction->preparedName));
+		/*
+		 * Await PREPARE TRANSACTION results, closing the connection would leave it dangling.
+		 *
```
Comment (onurctirtir) [inline src/backend/distributed/transaction/remote_transaction.c:421]:
```suggestion
```

File: src/backend/distributed/transaction/remote_transaction.c [hunk 6]
```diff
@@ -395,16 +414,22 @@ StartRemoteTransactionAbort(MultiConnection *connection)
...
+		 * We need to allocate 150 bytes for command buffer (including '\0'):
+		 *  - len("ROLLBACK PREPARED ") = 18
+		 *  - maximum quoted length of transaction->preparedName = 2 * 64 + 3 = 131
+		 */
+
```
Comment (onurctirtir) [inline src/backend/distributed/transaction/remote_transaction.c:426]:
```suggestion
```

File: src/backend/distributed/transaction/remote_transaction.c [hunk 7]
```diff
@@ -519,11 +543,20 @@ StartRemoteTransactionPrepare(struct MultiConnection *connection)
 		LogTransactionRecord(workerNode->groupId, transaction->preparedName);
 	}
 
-	initStringInfo(&command);
-	appendStringInfo(&command, "PREPARE TRANSACTION %s",
-					 quote_literal_cstr(transaction->preparedName));
+	/*
+	 * Await PREPARE TRANSACTION results, closing the connection would leave it dangling.
+	 *
```
Comment (onurctirtir) [inline src/backend/distributed/transaction/remote_transaction.c:548]:
```suggestion
```

File: src/backend/distributed/transaction/remote_transaction.c [hunk 8]
```diff
@@ -519,11 +543,20 @@ StartRemoteTransactionPrepare(struct MultiConnection *connection)
...
+	 * We need to allocate 152 bytes for command buffer (including '\0'):
+	 *  - len("PREPARE TRANSACTION ") = 20
+	 *  - maximum quoted length of transaction->preparedName = 2 * 64 + 3 = 131
+	 */
+
```
Comment (onurctirtir) [inline src/backend/distributed/transaction/remote_transaction.c:553]:
```suggestion
```

File: src/backend/distributed/transaction/remote_transaction.c [hunk 9]
```diff
@@ -395,16 +414,19 @@ StartRemoteTransactionAbort(MultiConnection *connection)
...
-		StringInfoData command;
-
-		/* await PREPARE TRANSACTION results, closing the connection would leave it dangling */
 		ForgetResults(connection);
 
-		initStringInfo(&command);
-		appendStringInfo(&command, "ROLLBACK PREPARED %s",
-						 quote_literal_cstr(transaction->preparedName));
+		/*
+		 * We need to allocate 150 bytes for command buffer (including '\0'):
```
Comment (onurctirtir) [inline src/backend/distributed/transaction/remote_transaction.c:420]:
```suggestion
		 * Await PREPARE TRANSACTION results, closing the connection would leave it dangling
		 * 
		 * We need to allocate 150 bytes for command buffer (including '\0'):
```

File: src/backend/distributed/transaction/transaction_management.c (hunk 4 above)
Comment (marcocitus) [reply src/backend/distributed/transaction/transaction_management.c:642]: it's ok for them to allocate if they don't allocate in CitusXactCallbackContext

Comment (onurctirtir) [reply src/backend/distributed/transaction/transaction_management.c:642]: None of those three seem to be allocating in CitusXactCallbackContext, so I agree that it's okay to skip them.

File: src/backend/distributed/transaction/remote_transaction.c [hunk 10]
```diff
@@ -268,16 +282,21 @@ StartRemoteTransactionCommit(MultiConnection *connection)
...
-
-		initStringInfo(&command);
-		appendStringInfo(&command, "COMMIT PREPARED %s",
-						 quote_literal_cstr(transaction->preparedName));
+		/*
+		 * Commit the prepared transaction.
+		 *
+		 * We need to allocate 148 bytes for command buffer (including '\0'):
+		 *  - len("COMMIT PREPARED ") = 16
+		 *  - maximum quoted length of transaction->preparedName = 2 * 64 + 3 = 131
```
Comment (marcocitus) [inline src/backend/distributed/transaction/remote_transaction.c:290]: what is this length calculation based on?

If we want the general postgres limit it appears to be 200 bytes:
https://www.postgresql.org/docs/current/sql-prepare-transaction.html

Comment (onurctirtir) [reply src/backend/distributed/transaction/remote_transaction.c:290]: I thought that length of `preparedname` could at most be NAMEDATALEN(64) and quoting a string would mean 2*X+3 bytes at the worst case.

```c
char *
quote_literal_cstr(const char *rawstr)
{
....
....
	/* We make a worst-case result area; wasting a little space is OK */
	result = palloc(len * 2 + 3 + 1);
....
....
```

However, now I see that NAMEDATALEN can be configured before initializing the database directory, so I guess I should replace 64 with 200 in the calculation.

File: src/backend/distributed/transaction/remote_transaction.c [hunk 11]
```diff
@@ -106,11 +106,21 @@ StartRemoteTransactionBegin(struct MultiConnection *connection)
...
 	}
 
+	char *assignDistributedTransactionIdCommand = AssignDistributedTransactionIdCommand();
+
 	/* add SELECT assign_distributed_transaction_id ... */
 	appendStringInfoString(beginAndSetDistributedTransactionId,
-						   AssignDistributedTransactionIdCommand());
+						   assignDistributedTransactionIdCommand);
+
+	pfree(assignDistributedTransactionIdCommand);
```
Comment (marcocitus) [inline src/backend/distributed/transaction/remote_transaction.c:115]: wondering what's a good place to add a comment on why we aggressively pfree here (either in function descriptions or above the relevant lines?)

Comment (onurctirtir) [reply src/backend/distributed/transaction/remote_transaction.c:120]: Added a comment to top of the file because it's not only that function but also some other doing aggressive pfree'ing.

File: src/backend/distributed/transaction/transaction_management.c [hunk 12]
```diff
@@ -284,7 +284,7 @@ CoordinatedTransactionCallback(XactEvent event, void *arg)
 			 *   trick, so there's no need for us to do it again.
 			 */
 			MemoryContext previousContext = CurrentMemoryContext;
-			MemoryContextSwitchTo(CommitContext);
+			MemoryContextSwitchTo(CitusXactCallbackContext);
```
Comment (marcocitus) [inline src/backend/distributed/transaction/transaction_management.c:287]: these 2 lines could be merged into:
```
MemoryContext previousContext = MemoryContextSwitchTo(CitusXactCallbackContext);
```

**Review by marcocitus — APPROVED** [review]

File: src/backend/distributed/transaction/transaction_management.c [hunk 13]
```diff
@@ -731,36 +752,22 @@ AdjustMaxPreparedTransactions(void)
...
-	MemoryContextSwitchTo(old_context);
 }
 
 
 /* PopSubXact pops subId from the stack of active sub-transactions. */
 static void
 PopSubXact(SubTransactionId subId)
 {
-	SubXactContext *state = linitial(activeSubXactContexts);
+	SubXactContext *state = llast(activeSubXactContexts);
```
Comment (onderkalaci) [inline src/backend/distributed/transaction/transaction_management.c:770]: Why do we change these operations in this PR? Is that to avoid `reversedSubXactStates` ? I'm asking because some of the comments now seems to not fit as good as before.

In any case, I'd probably make these change in a follow-up PR because felt like we might have missed something
