### PR TITLE
Run replicate_reference_tables background task as superuser.

### LINKED ISSUE #6925: Permission error when running citus_rebalance_start as non-superuser
A user reported an issue with some permissions in the new shard rebalancer: https://citus-public.slack.com/archives/C0XRHT1KJ/p1683884860900569

> {"tasks": [{"state": "runnable", "command": "SELECT pg_catalog.replicate_reference_tables('auto')", "message": "ERROR: permission denied for function replicate_reference_tables\nCONTEXT: Citus Background Task Queue Executor: citus/citus for (2/74)\n", "retried": 3, "task_id": 74}], "task_state_counts": {"blocked": 72, "runnable": 1}}

To fix that we should probably run the background task that runs `replicate_reference_tables` as superuser. Afaict there's no security issue with that.
https://github.com/citusdata/citus/blob/main/src/backend/distributed/operations/shard_rebalancer.c#L2168C5-L2179

A better way would be to allow running `replicate_reference_tables` by all users. But that's a SQL change, which is harder to backport.

### LINKED ISSUE #6926: We should qualify all citus_move_shard_placement and citus_copy_shard_placement
As a defense in depth against privilege escalations we should fully qualify all functions that we call with pg_catalog. Otherwise users might be able to trick us into calling another function.

Known places (but maybe more):
1. https://github.com/citusdata/citus/blob/main/src/backend/distributed/utils/reference_table_utils.c#L422-L429
2. https://github.com/citusdata/citus/blob/main/src/backend/distributed/operations/shard_rebalancer.c#L2279-L2294

### PR DESCRIPTION
**Pull request by emelsimsek**
DESCRIPTION: Fixes a bug in background shard rebalancer where the replicate reference tables task fails if the current user is not a superuser. 

This change is to be backported to earlier releases. We should fix the permissions for replicate_reference_tables  on main branch such that it can be run by non-superuser roles.

Fixes #6925.
Fixes #6926.

### CODE REVIEW

**Comment by emelsimsek** [comment]
Should we go with this then until we fix the permissions on the function? 

From the issue description, the latter sounds like harder to patch.

**Comment by marcocitus** [comment]
Yes, a permissions change will be hard to backport to 11.2. We might want to consider changing permissions on `main`.

It would be good to add a test running `citus_rebalance_start` as non-superuser after adding a node to a cluster with a reference table.

For cleanliness, given that we sometimes run some commands as superuser, it would also be nice if we can include a fix for https://github.com/citusdata/citus/issues/6926 (by adding `pg_catalog.` to queries) in the backport. This is not a critical issue as far as we know, but adds a safeguard.

File: src/test/regress/sql/background_rebalance.sql [hunk 1]
```diff
@@ -110,6 +110,27 @@ SELECT public.wait_for_resource_cleanup();
...
 
+-- make sure a non-super user can rebalance when there are reference tables to replicate
+CREATE TABLE ref_table(a int primary key);
+SELECT create_reference_table('ref_table');
+
+-- add a new node to trigger replicate_reference_tables task
+SELECT 1 FROM citus_add_node('localhost', :worker_3_port);
+
+SET ROLE non_super_user_rebalance;
+SELECT 1 FROM citus_rebalance_start(shard_transfer_mode := 'force_logical');
```
Comment (marcocitus) [inline src/test/regress/sql/background_rebalance.sql:121]: kind of wondering whether we actually want any random user to be able to run a rebalance, but that's a pre-existing issue

**Review by marcocitus — APPROVED** [review]
