### PR TITLE
Make undistribute_table() and citus_create_local_table() work with columnar

### LINKED ISSUE #4465: Cannot Create Columnar Citus Local Table
```
SELECT 1 FROM master_add_node('localhost', 9700, groupId => 0);
CREATE TABLE oz (a INT) USING COLUMNAR;
SELECT create_citus_local_table('oz');

ERROR:  unrecognized node type: 236
```

### PR DESCRIPTION
**Pull request by naisila**
DESCRIPTION: Make undistribute_table() and citus_create_local_table() work with columnar

Check for udf calls in `ExecuteAndLogUtilityCommand`

Fixes #4465

### CODE REVIEW

**Review by pykello — APPROVED** [review]

**Comment by onurctirtir** [comment]
I wonder should we directly use `LocallyExecuteUtilityTask` here (maybe by first renaming it)

**Comment by naisila** [comment]
@onurctirtir I think renaming it is a good idea, because I am actually almost copy pasting from LocallyExecuteUtilityTask. Let me try that

**Comment by naisila** [comment]
@pykello since the udf check I had added to `ExecuteAndLogDDLCommand` was almost a copy-paste of `LocallyExecuteUtilityTask` in `local_executor.c`, I am using the original `LocallyExecuteUtilityTask` after renaming it to simply `ExecuteUtilityCommand`.

`ExecuteUtilityCommand` is now a function that checks whether the utility command triggers a UDF, if not it simply executes the utility command via `ProcessUtilityParseTree`.

File: src/backend/distributed/commands/cascade_table_operation_for_connected_relations.c [hunk 1]
```diff
@@ -428,32 +429,30 @@ ExecuteCascadeOperationForRelationIdList(List *relationIdList,
...
 	{
-		ExecuteAndLogDDLCommand(ddlCommand);
+		ExecuteAndLogUtilityCommand(utilityCommand);
 	}
 }
 
 
 /*
- * ExecuteAndLogDDLCommand takes a ddl command and logs it in DEBUG4 log level.
+ * ExecuteAndLogUtilityCommand takes a ddl command and logs it in DEBUG4 log level.
```
Comment (pykello) [inline src/backend/distributed/commands/cascade_table_operation_for_connected_relations.c:447]: "ddl command" -> "utility command"

File: src/backend/distributed/executor/local_executor.c [hunk 2]
```diff
@@ -373,11 +372,11 @@ ExtractParametersForLocalExecution(ParamListInfo paramListInfo, Oid **parameterT
...
 
 /*
- * LocallyExecuteUtilityTask executes the given local task query in the current
+ * ExecuteUtilityCommand executes the given local task query in the current
  * session.
  */
-static void
-LocallyExecuteUtilityTask(const char *localTaskQueryCommand)
+void
+ExecuteUtilityCommand(const char *localTaskQueryCommand)
```
Comment (pykello) [inline src/backend/distributed/executor/local_executor.c:379]: This previously looked like a local execution specific function, but with the rename it doesn't seem anymore. Its implementation seems to work for non-local commands too, but it needs some clean-up (in names & comments) to remove the "local" references to avoid confusion.

Since @onderkalaci implemented the local executor, can you double check with him to see if we haven't missed anything?

Comment (onderkalaci) [reply src/backend/distributed/executor/local_executor.c:379]: That's right, the input can be any utility command. So I think we should follow Hadi's comment.

**Review by pykello — APPROVED** [review]
