### PR TITLE
Use intermediate results for re-partition joins

### LINKED ISSUE #101: We should batch "merge tasks" in the executor so that we don't have an overwhelming number of requests / connections.
We should batch "merge tasks" in the executor so that we don't have an overwhelming number of requests / connections.

### LINKED ISSUE #2525: Lingering "pg_merge_job_" schemas are not cleaned up
Task-tracker creates some intermediate tables during the execution (and generally! drops them at the end of the execution). On the workers, all the tables are created on schemas prefixed with `pg_merge_job_`. In some cases, task-tracker fails to clean-up those schemas/tables. So, they might stay forever there.

The code is written to clean-up them, but it turns out that it doesn't. There is probably a bug there.

Related code: 

Task-tracker bg worker at init:

https://github.com/citusdata/citus/blob/d63cbf382288358533b71d907f6a3a7fc8a1df5f/src/backend/distributed/worker/task_tracker.c#L210-L223

https://github.com/citusdata/citus/blob/d63cbf382288358533b71d907f6a3a7fc8a1df5f/src/backend/distributed/worker/task_tracker.c#L359-L419

Because of that, pg_upgrade may fail. 

```
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
No match found in new cluster for old relation with OID XXXX in database "citus": \
"pg_merge_job_XXXXX.task_000XXX"
```

The current work around is to manually call `SELECT worker_cleanup_job_schema_cache();
` on the workers.

### LINKED ISSUE #3390: Convert re-partitioning logic to use intermediate results
We currently use `worker_hash_partition_table`, `worker_fetch_partition_file`, and `worker_merge_files_into_table` to perform re-partition jobs. However, these functions are not aware of distributed transactions, may leave files behind, and have various inefficiencies.

We would like to use `worker_partition_query_result`, `fetch_intermediate_results`, and `read_intermediate_result` as used in #3376. This is dependent on removing task-tracker, since intermediate result functions require being in a distributed transactions.

Once we made this conversion we can use CTEs and recursively planned subqueries within re-partition joins.

### LINKED ISSUE #3484: Create temporary schemas in parallel while doing repartitioning
Currently we create the temporary schemas sequentially during repartition joins. Creating them in parallel would improve performance.

Similar to #3464.

### LINKED ISSUE #3727: Local execution with repartition joins
We use ExecuteLocalTaskListOutsideTransaction with repartition joins. It seems that there was some problem with this when we used local execution, the error we would sometimes get is:

```sql
BEGIN;
SET citus.enable_repartition_joins TO ON;
-- trigger local execution
SELECT y FROM test WHERE x = 1;
-- this will use local execution, it should work fine without giving segfault.
SELECT count(*) FROM test t1, test t2 WHERE t1.x = t2.y;
ROLLBACK;
```

```diff
+ERROR:  COPY file signature not recognized
+CONTEXT:  while executing command on localhost:57637
```

We can remove ExecuteLocalTaskListOutsideTransaction and use ExecuteTaskList when we solve this test failure.

Related PR: #3711.

### LINKED ISSUE #5342: Repartition joins might fail with non-superuser when shards are locally avaliable + hit citus.local_shared_pool_size
- create a distributed table with non-super user
- pick a very low max_shared_pool_size/max_local_shared_pool_size, like 5
- Run this query from the workers

```SQL
SELECT count(*)
FROM repartition_prepared_test t1
JOIN repartition_prepared_test t2 USING (b) ;
ERROR:  cannot execute command because a local execution has accessed a placement in the transaction
DETAIL:  Some parallel commands cannot be executed if a previous command has already been executed locally
HINT:  Try re-running the transaction with "SET LOCAL citus.enable_local_execution TO OFF;"
Time: 341.328 ms
```

What is happening is that:
- The superuser connections are used for `worker_create_schema` 
- We reach to max_shared_pool_size/max_local_shared_pool_size
- Now, the actual commands (like `worker_hash_partition)` on the local node failovers to the local execution (see #https://github.com/citusdata/citus/issues/3727)
- We get the error.

Related to https://github.com/citusdata/citus/issues/3727 and https://github.com/citusdata/citus/issues/3390 (as we can avoid superuser for create schema, we could be fine to use the same user/connection)

### PR DESCRIPTION
**Pull request by marcocitus**
DESCRIPTION: Enable re-partition joins on followers
DESCRIPTION: Enable re-partition joins in transaction blocks
DESCRIPTION: Fixes a bug that could cause failed re-partition joins to leak result tables
DESCRIPTION: Fixes a bug that could cause re-partition joins involving local shards to fail
DESCRIPTION: Automatically use binary encoding in re-partition joins when possible

This PR changes the re-partitioning functions used by the physical planner into those introduced by #3329, #3318, and #3304 which are used in #3376. These functions only use temporary files instead of creating intermediate tables. As a result we can immediately:

1) Execute re-partition joins on followers
2) Fix resource leaks from re-partitioning
3) Re-partition joins automatically use binary encoding where possible
4) Run re-partition joins in a write transaction (can see uncommitted writes)

In addition, it opens up additional opportunities such as:

1) Use distributed subplan results (read: subqueries & CTEs) in a re-partition join
2) Show proper explain plans for re-partition joins based on queries on function calls
3) Eventually, simplify the planner by removing subplan vs. Job distinction

In addition, we should be able to remove the old re-partitioning functions (1-2k lines of code) and associated tests (check-worker schedule). I did not remove them yet, since it would break rolling upgrades for users of re-partition joins. Since re-partition joins are not very common yet given to current limitations, we could still consider removing them in a separate PR.

As a result of this change, "merge tasks" effectively become obsolete since merging files is done by passing an array of result names to `read_intermediate_results`. However, a lot of bookkeeping is associated with merge tasks in the physical planner to build the dependency graph of tasks and assign tasks to nodes correctly. Hence, I kept them and instead skip over them in the executor.

Fixes #2525 
Fixes #3390
Fixes #3727
Fixes #5342
Closes #3484
Closes #101 
Closes #3461

### CODE REVIEW

File: src/backend/distributed/executor/partitioned_intermediate_results.c [hunk 1]
```diff
@@ -437,23 +461,37 @@ PartitionedResultDestReceiverReceive(TupleTableSlot *slot, DestReceiver *copyDes
...
+			ereport(ERROR, (errcode(ERRCODE_NULL_VALUE_NOT_ALLOWED),
+							errmsg("the partition column value cannot be NULL")));
+		}
 	}
-
-	Datum partitionColumnValue = columnValues[partitionedDest->partitionColumnIndex];
-	ShardInterval *shardInterval = FindShardInterval(partitionColumnValue,
-													 partitionedDest->shardSearchInfo);
-	if (shardInterval == NULL)
+	else
```
Comment (thanodnl) [inline src/backend/distributed/executor/partitioned_intermediate_results.c:479]: what is the reason for the else block?

both branches above break out of the function already.
the extra level of indent actually threw me off completely while reading the change.

if this was the las part of the function I could understand, however, given the function continues outside of the else block (which is only reached when entering this else block) I would suggest to remove it here.

It also prevents the `partitionIndex` declaration and assignment separation.

File: src/backend/distributed/executor/adaptive_executor.c [hunk 2]
```diff
@@ -946,6 +945,26 @@ ExecuteUtilityTaskListExtended(List *utilityTaskList, int poolSize,
...
+	bool excludeFromXact = false;
+	executionParams->xactProperties = DecideTransactionPropertiesForTaskList(
+		modLevel, taskList, excludeFromXact);
+
+	return ExecuteTaskListExtended(executionParams);
+}
+
+
 /*
  * ExecuteTaskListOutsideTransaction is a proxy to ExecuteTaskListExtended
```
Comment (onderkalaci) [inline src/backend/distributed/executor/adaptive_executor.c:969]: We can remove `ExecuteTaskListOutsideTransaction` and `TRANSACTION_BLOCKS_DISALLOWED`? I always kept an eye on these APIs so that no one else uses them :)

File: src/backend/distributed/planner/multi_physical_planner.c [hunk 3]
```diff
@@ -4433,56 +4401,112 @@ CreateMapQueryString(MapMergeJob *mapMergeJob, Task *filterTask,
...
+	char *partitionMethodString = partitionType == RANGE_PARTITION_TYPE ?
+								  "range" : "hash";
+
+	/* TODO: determine binary safety automatically */
+	bool useBinaryFormat = BinaryWorkerCopyFormat;
+
+	/*
+	 * NULL values never match a join condition, so it's ok to skip them.
+	 */
+	bool skipNullPartitionColumnValue = true;
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_physical_planner.c:4451]: I guess this assumes we only support INNER joins? Because with left joins NULL values can be on the output? Or, am I missing something here?

```SQL
create table test (a int);
insert into test VALUES (NULL);
select * from test t1 LEFT JOIN test t2 USING (a);
 a 
---
  
(1 row)

```

**Comment by onderkalaci** [comment]
> Use distributed subplan results (read: subqueries & CTEs) in a re-partition join

I'm a little confused by this. Can you give some examples? The following still fails?
```SQL
WITH cte_1 AS (SELECT * FROM test LIMIT 10) SELECT count(*) from test t1 JOIN test t2 USING(b) JOIN cte_1 USING(b);
ERROR:  complex joins are only supported when all distributed tables are co-located and joined on their distribution columns
```

File: src/backend/distributed/executor/intermediate_results.c [hunk 4]
```diff
@@ -940,6 +943,16 @@ fetch_intermediate_results(PG_FUNCTION_ARGS)
 static uint64
 FetchRemoteIntermediateResult(MultiConnection *connection, char *resultId)
 {
+	char *localPath = QueryResultFileName(resultId);
```
Comment (onderkalaci) [inline src/backend/distributed/executor/intermediate_results.c:946]: Is it possible that we fetch the same intermediate result more than once?

File: src/backend/distributed/executor/distributed_intermediate_results.c [hunk 5]
```diff
@@ -59,28 +59,6 @@ typedef struct PartitioningTupleDest
...
- */
-typedef struct NodeToNodeFragmentsTransfer
-{
-	NodePair nodes;
-	List *fragmentList;
-} NodeToNodeFragmentsTransfer;
-
-
 /* forward declarations of local functions */
 static List * WrapTasksForPartitioning(const char *resultIdPrefix,
```
Comment (onderkalaci) [inline src/backend/distributed/executor/distributed_intermediate_results.c:63]: Why don't we change the parameters of `worker_partition_query_result ` in `WrapTasksForPartitioning`?

I think I'm a bit confused about the `skipNullPartitionColumnValue ` and `generateEmptyResults ` flags. Are they needed for SELECT queries but not for `INSERT .. SELECT`? Can you clarify a bit for me to follow easier? Thanks!

File: src/backend/distributed/executor/adaptive_executor.c (hunk 2 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/executor/adaptive_executor.c:969]: I guess it is used on the enterprise still, `ExecuteClusterOnCommands` and `ExecuteCreateIndexCommands`

**Comment by marcocitus** [comment]
> I'm a little confused by this. Can you give some examples? The following still fails?

I cautiously worded this as "opens additional opportunities". It fails in the planner, but will no longer fail in the executor.

File: src/backend/distributed/planner/multi_physical_planner.c (hunk 3 above)
Comment (marcocitus) [reply src/backend/distributed/planner/multi_physical_planner.c:4451]: Yes, but the output of worker_partition_query_result is the input to the join, not the output.

The result is the same if you do  `select * from test t1 LEFT JOIN (select * from test limit 0) t2 USING (a);` . The NULL input never matches the join condition, so it might as well not be there.

File: src/backend/distributed/executor/intermediate_results.c (hunk 4 above)
Comment (marcocitus) [reply src/backend/distributed/executor/intermediate_results.c:946]: The skip-if-file-exists is mainly to catch fetches to self. Previously, different names were used between sender and receiver. Intermediate results currently have the same name everywhere.

We do not repeat/retry fetches, though we probably need to reconsider this logic if we do, since we may only have a partial file. The "simplest" solution would be to prune away fetch-to-self tasks, after which we can remove the skip-if-file-exists logic below.

File: src/backend/distributed/executor/distributed_intermediate_results.c (hunk 5 above)
Comment (marcocitus) [reply src/backend/distributed/executor/distributed_intermediate_results.c:63]: > skipNullPartitionColumnValue 

INSERT..SELECT fails when there are NULL values:

> ERROR:  the partition column value cannot be NULL
> CONTEXT:  while executing command on localhost:1402

That's because we currently do not allow NULL values in the partition columns, and FindShardInterval does not work for NULL values.

We do allow NULL values as the input to re-partition joins, but they will never match the join condition, so we might as well skip them.

We will have to revisit this logic if we re-partition for other purposes than joins (e.g. group by). The solution would be to implement shard pruning for NULL, and maybe generally allow NULL as a partition column value.

> generateEmptyResults 

We do not prune away fetch tasks, so fetching an empty file would fail. I tried making COPY .. TO STDOUT WITH (format 'result') tolerate non-existent files, but it got quite complicated because that command does not know the actual formatting of the file (binary vs. text), which then needs to be handled somewhere downstream. Instead, we just generate empty files and fetch them like we always did. One day we'll have pruning like we do in insert..select and the need for this goes away.

Comment (marcocitus) [reply src/backend/distributed/executor/distributed_intermediate_results.c:63]: (will add some comments in multi_physical_planner.c)

File: src/backend/distributed/planner/multi_physical_planner.c (hunk 3 above)
Comment (marcocitus) [reply src/backend/distributed/planner/multi_physical_planner.c]: Actually, you're right, we should preserve NULL values on the outside, but can skip them on the inside. I changed to writing NULL values to the first partition and omitted the skipping logic for now.

File: src/backend/distributed/planner/multi_physical_planner.c [hunk 6]
```diff
@@ -4429,60 +4403,121 @@ PartitionColumnIndex(Var *targetVar, List *targetList)
...
-	{
-		partitionCommand = RANGE_PARTITION_COMMAND;
 	}
-	else
+	else if (partitionType == RANGE_PARTITION_TYPE)
 	{
-		partitionCommand = HASH_PARTITION_COMMAND;
+		/* add a partition for NULL values at index 0 */
+		intervalArray = RangeIntervalArrayWithNullBucket(intervalArray, intervalCount);
+		intervalCount++;
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_physical_planner.c:4436]: We have logic in MergeTaskList that expects an additional bucket to be generated for cases where the join column value is NULL. This was previously done implicitly in worker_range_partition_table, but it seems cleaner to define an actual bucket in the interval array.

We may need to revise this when we allow NULL values in range-partitioned tables, since there is already a bucket in that case (see comments in MergeTaskList and RangeIntervalArrayWithNullBucket).

Alternatively, we could consider removing range-re-partitioning, but it might come in handy one day.

**Comment by onderkalaci** [comment]
Should be fixing #5342, and we can consider adding the test in the issue to the arbitrary configs because we have actually found it via that. WE have a schedule with citus.max_shared_pool_size,  and I think it was in the file ` sql/prepared_statements_1.sql`

**Comment by marcocitus** [comment]
> Should be fixing #5342

Sure, pushed a fix for that.

> because we have actually found it via that. 

Can I find this test somewhere?

File: src/test/regress/sql/prepared_statements_1.sql [hunk 7]
```diff
@@ -17,3 +17,12 @@ BEGIN;
 	CREATE TEMP TABLE repartition_prepared_tmp AS EXECUTE repartition_prepared(1);
 	SELECT count(*) from repartition_prepared_tmp;
 ROLLBACK;
+
+PREPARE xact_repartitioned_prepared AS
+	SELECT count(*) FROM repartition_prepared_test t1 JOIN repartition_prepared_test t2 USING (b);
+
+BEGIN;
+	-- Prepared re-partition join in a transaction block after a write
```
Comment (onderkalaci) [inline src/test/regress/sql/prepared_statements_1.sql:25]: would be nice to have the other order as well:

```
BEGIN;
execute;
INSERT;
```

File: src/test/regress/expected/prepared_statements_1.out [hunk 8]
```diff
@@ -24,3 +24,25 @@ BEGIN;
 (1 row)
 
 ROLLBACK;
+PREPARE xact_repartitioned_prepared AS
+	SELECT count(*) FROM repartition_prepared_test t1 JOIN repartition_prepared_test t2 USING (b);
+BEGIN;
```
Comment (onderkalaci) [inline src/test/regress/expected/prepared_statements_1.out:29]: Hmm, how are the outputs of the same SELECT query differ so much? There seems no concurrent modification to this table

Comment (marcocitus) [reply src/test/regress/expected/prepared_statements_1.out:29]: The table contains a lot of duplicate rows, so 1 additional row containing `2` matches a lot of other rows.
```
INSERT INTO repartition_prepared_test SELECT i%2, i%3 FROM generate_series(0,24)i;
```

Comment (onderkalaci) [reply src/test/regress/expected/prepared_statements_1.out:29]: Ah, that's cool, nice test, I missed such a possibility :)  I was concerned we somehow skip some local placements or such.

 Actually, we already verify against PG within the arbitrary configs, but yeah anyway.

File: src/backend/distributed/executor/intermediate_results.c [hunk 9]
```diff
@@ -940,6 +943,19 @@ fetch_intermediate_results(PG_FUNCTION_ARGS)
...
+
+	struct stat fileStat;
+	int statOK = stat(localPath, &fileStat);
+	if (statOK == 0)
```
Comment (onlined) [inline src/backend/distributed/executor/intermediate_results.c:950]: My preference would be
```c
if (!stat(localPath, &fileStat))
```
or
```c
if (stat(localPath, &fileStat) == 0)
```

but obviously you see value in using a variable there. So, this is my suggestion:
```suggestion
	bool statOK = stat(localPath, &fileStat) == 0;
	if (statOK)
```

Comment (marcocitus) [reply src/backend/distributed/executor/intermediate_results.c:950]: Not sure about this suggestion. The current code seems super explicit about which return code means that the file exists.

`if (!stat(localPath, &fileStat)) ` would be very confusing because we actually go into this code path when `stat` succeeded.

Comment (onlined) [reply src/backend/distributed/executor/intermediate_results.c:950]: Then the name is not that good, because `statOK` means "if `stat` returned OK" to me at first, rather than "return value of `stat`". If you don't like my boolean suggestion (which is more explicit IMO, saying it means `stat` returned OK when the return value is 0), you can change the variable name to `statResult` or `statRet` or more explicitly `statReturnValue`.

Comment (marcocitus) [reply src/backend/distributed/executor/intermediate_results.c:950]: not sure, we seem to have used statOK in 2 other places in this file. I'd favour consistency

**Comment by onderkalaci** [comment]
> ci/circleci: test-12_check-arbitrary-configs — Your tests failed on CircleCI
> dataCitusShardReplicationFactorClusterConfig

In case you missed that we changed this to be MX cluster via https://github.com/citusdata/citus/pull/5392/files#diff-d1277a9adcd9c7f7303eab4e1d0b2b9972b2a799571a473b3392727e7129dcc0R319 on the master branch very recently.

File: src/backend/distributed/executor/intermediate_results.c (hunk 9 above)
Comment (onlined) [reply src/backend/distributed/executor/intermediate_results.c:950]: We could still correct (or improve) the names at the other places, if consistency is favored. I see 5 other usages, it shouldn't be very difficult to replace them.

File: src/backend/distributed/planner/multi_physical_planner.c [hunk 10]
```diff
@@ -854,10 +852,14 @@ TargetEntryList(List *expressionList)
 	foreach(expressionCell, expressionList)
 	{
 		Expr *expression = (Expr *) lfirst(expressionCell);
+		int columnNumber = list_length(targetEntryList) + 1;
+
+		StringInfo columnName = makeStringInfo();
+		appendStringInfo(columnName, "column%d", columnNumber);
```
[the remark this answers is not in the document]
Comment (onderkalaci) [reply src/backend/distributed/planner/multi_physical_planner.c:862]: Might be nice to add some regression tests with expressions on target list + resname (if we d don't already have one)

**Review by onderkalaci — COMMENTED** [review]
I don't really have much to comment here, it looks good. I'm actually still surprised to see how simple the changes are. The only slightly complex part is related to `RangeIntervalArrayWithNullBucket`, but you have a clear comment on that already.

I think there is one test failing, which seems like an actual bug, but didn't look deeper.

I think we are getting closer to support `citus.max_adaptive_executor_pool_size` with repartition joins but still we need some more work there. As a semi-related note, I couldn't follow why `fetch_intermediate_results` does a `FORCE_NEW_CONNECTION`. What would happen if it didn't pass any connection flags?

Few test suggestions:
1- your comment [here](https://github.com/citusdata/citus/pull/3461#issuecomment-582385716). Maybe cancellation tests as well.
2- We might add some fkey to reference table tests with repartition joins here: https://github.com/citusdata/citus/blob/master/src/test/regress/sql/foreign_key_restriction_enforcement.sql

3- [Onder to do] Some large scale tests on Azure to see all works as we'd expect for large data sizes.

**Comment by marcocitus** [comment]
Fixed the arbitrary configs issue via https://github.com/citusdata/citus/pull/5400/commits/8a2cb07e13bdae05ad4f145083ba6a3030cbc7d0

**Comment by onderkalaci** [comment]
I did something interesting to test this PR: https://github.com/citusdata/citus/compare/marcocitus/repartition-using-intermediate-results...disable_normal_joins?expand=1

Where, we force all joins go through the repartition joins. And, majority of the failures are very expected ones!

There are few error like below:
```SQL
+ERROR:  Query could not find the intermediate result file "repartition_40_1_1", it was mostly likely deleted due to an error in a parallel process within the same distributed transaction
```

Which I couldn't reproduce this locally, still trying more. One theory I have is that we see these errors on CI because of low max_connections  + concurrent JOINs.

(I could repro could not connect XX errors with high concurrency locally, but not these above, still looking if they are the same)

**Review by onderkalaci — COMMENTED** [review]
This is a very cool PR! 

 One downside I can see at this moment is that:
We use max_adaptive_executor_pool_size per now, only from the coordinator to that node until the tx ends. (on master we release early?)


I'm also looking to repro the failure I mentioned on another comment.

And, I also really want to have a test with repartition joins in 2- We might add some fkey to reference table tests with repartition joins here: https://github.com/citusdata/citus/blob/master/src/test/regress/sql/foreign_key_restriction_enforcement.sql  

I'm OK to add myself after merging, like adding one more query to this block with a repartition join
```SQL
-- case 2.1: UPDATE to a reference table is followed by a multi-shard SELECT
BEGIN;
	UPDATE reference_table SET id = 101 WHERE id = 99;
	SELECT count(*) FROM on_update_fkey_table WHERE value_1 = 99;
	SELECT count(*) FROM on_update_fkey_table WHERE value_1 = 101;

      /* todo: add a repartition joni */
ROLLBACK;
```

**Comment by onderkalaci** [comment]
> ERROR:  Query could not find the intermediate result file "repartition_40_1_1", it was mostly likely deleted due to an error in a parallel process within the same distributed transaction

Btw, I already found the answer, forgot to write here. Yes, this is expected and could happen if a concurrent backend fails (say due to connection errors): https://github.com/citusdata/citus/blob/13fff9c37a4326713bfa92eaecba3f753cf9c651/src/backend/distributed/executor/intermediate_results.c#L836-L851

**Review by onderkalaci — APPROVED** [review]
Not sure if @thanodnl wants to have a look, but ready to merge from my perspective

**Comment by thanodnl** [comment]
I think it is safe to merge if @onderkalaci reviewed it.

This area is pretty foreign to me, and I don't have the bandwidth soon to dive deep on it.

File: src/backend/distributed/planner/multi_physical_planner.c [hunk 11]
```diff
@@ -5392,6 +5405,16 @@ ActiveShardPlacementLists(List *taskList)
 		/* sort shard placements by their creation time */
 		activeShardPlacementList = SortList(activeShardPlacementList,
 											CompareShardPlacements);
+
+		/*
+		 * The executor currently does not know how to handle map task failover,
+		 * so we generate at most 1 placement.
+		 */
+		if (task->taskType == MAP_TASK)
+		{
```
[the remark this answers is not in the document]
Comment (marcocitus) [reply src/backend/distributed/planner/multi_physical_planner.c]: nope removed
