### PR TITLE
Fix task copy and appending empty task in ExtractLocalAndRemoteTasks

### LINKED ISSUE #3590: Local execution can cause queries to go to the wrong shard or something
```
WITH a as (SELECT rt.value_2 FROM reference_table_test rt where rt.value_2 = 2)
SELECT ct.value_1, count(*) FROM colocated_table_test ct join a on ct.value_1 = a.value_2
WHERE exists (select * from a)
GROUP BY 1 ORDER BY 1;
```

Put this at the end of `multi_reference_table.sql`. Then `make check-base EXTRA_TESTS="multi_reference_table add_coordinator multi_reference_table"`

Initially ran into this while creating test cases for #3568 where I've included changes to `local_executor.c` to work around the issue, but which I don't believe are ultimately correct

My proposed fix was to not push an empty local tasklist task. This ends up essentially tricking the adaptive executor into not thinking it's doing local execution for the latter task list, but we're supposed to error out due to read-your-own-writes reasons. Which implies we could at least allow this sort of thing if no local writes have happened in the transaction yet. However better would be to inhibit local execution from ever happening for this query

### LINKED ISSUE #3801: ExtractLocalAndRemoteTasks may copy task and fail
`ExtractLocalAndRemoteTasks` is a little odd. It assumes that either a task has a single placement or will go to all placements:
https://github.com/citusdata/citus/blob/master/src/backend/distributed/executor/local_executor.c#L471

However, object propagation will typically create a task that has multiple remote-only placements (workers only) and hence runs through the `else` without have local tasks.

That might have been ok, except we call `copyObject` on the `Task`:
https://github.com/citusdata/citus/blob/master/src/backend/distributed/executor/local_executor.c#L497

copyObject on a Task does not actually work, because a task may contain a list of `char *` (e.g. in `queryStringList`, which is used by object propagation) and `copyObject` assumes the list contains only Postgres `Node`s, such that it can tell how to copy the list members from the node type.  
https://github.com/citusdata/citus/blob/master/src/backend/distributed/utils/citus_copyfuncs.c#L280

While making code changes to support distributing tables created by extensions, I've seen this result in:
```
DROP EXTENSION hll;
ERROR:  unrecognized node type: 542393683
```

It seems likely that there is some way to reproduce this on the current master / release-9.3 branch, but even if there isn't we should clean this up.

### PR DESCRIPTION
**Pull request by SaitTalhaNisanci**
DESCRIPTION: Fix task copy and appending empty task in ExtractLocalAndRemoteTasks

Task node has task query, which might contain a list of strings in its
fields. We were using postgres copyObject for these lists. Postgres
assumes that each element of list will be a node type. If it is not a
node type it will error.

As a solution to that, a new macro is introduced to copy a list of
strings.

https://github.com/citusdata/citus/pull/3802/commits/3d9328c017667ac70b373aabd771847bd99bf463 Fixes #3801.

ExtractLocalAndRemoteTasks extracts the local and remote tasks. If we do
not have a local task the localTaskPlacementList will be NIL, in this
case we should not append anything to local tasks. Previously we would
first check if a task contains a single placement or not, now we first
check if there is any local task before doing anything.

https://github.com/citusdata/citus/pull/3802/commits/5ef1b94a50f9246b8dc69077cfee941c0d85593b Fixes #3590.

### CODE REVIEW

File: src/backend/distributed/executor/local_executor.c [hunk 1]
```diff
@@ -468,49 +468,44 @@ ExtractLocalAndRemoteTasks(bool readOnly, List *taskList, List **localTaskList,
...
+				/*
+				 * At this point, we're dealing with reference tables or intermediate
+				 * results where the task has placements on both local and remote
+				 * nodes. We always prefer to use local placement, and require remote
+				 * placements only for modifications.
+				 */
+				task->partiallyLocalOrRemote = true;
 
-			Task *localTask = copyObject(task);
+				Task *localTask = copyObject(task);
```
Comment (onurctirtir) [inline src/backend/distributed/executor/local_executor.c:487]: Thinking of if it is still possible to have "unrecognized node type" errors as we will still be copying `Task` struct at some point. Can we improve `CopyNodeTask` method for `TaskQueryString` ?

Comment (onurctirtir) [reply src/backend/distributed/executor/local_executor.c:487]: Changing "queryStringList" to store `StringInfo`s instead of `char*`s should fix possible further issues like the one explained in #3801.

File: src/backend/distributed/executor/local_executor.c [hunk 2]
```diff
@@ -468,49 +468,44 @@ ExtractLocalAndRemoteTasks(bool readOnly, List *taskList, List **localTaskList,
...
-				Task *remoteTask = copyObject(task);
-				remoteTask->taskPlacementList = remoteTaskPlacementList;
+				if (readOnly)
+				{
+					/* read-only tasks should only be executed on the local machine */
+				}
+				else
+				{
+					Task *remoteTask = copyObject(task);
+					remoteTask->taskPlacementList = remoteTaskPlacementList;
```
Comment (onurctirtir) [inline src/backend/distributed/executor/local_executor.c:499]: (out of the changes done in this pr)
We can add such an assertion & comment here to make it more clear for readers that we do not create remote task with empty task placements

```suggestion
                                /* for non read-only tasks, task would definitely have remote placements */
                                Assert(remoteTaskPlacementList != NIL);
                                
				else
				{
					Task *remoteTask = copyObject(task);
					remoteTask->taskPlacementList = remoteTaskPlacementList;
```

File: src/backend/distributed/executor/local_executor.c (hunk 1 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/executor/local_executor.c:487]: As far as I see StringInfo will have the same problem, looking at postgres code it seems that there is already a copy function for T_String which is of type `Value`. 

We could alternatively have a function that copies a char* list in copyfuncs.

Also I have verified that the following fails:

```sql
set citus.shard_replication_factor to 2;
create table dist (a int);
select create_distributed_table('dist', 'a');
begin;
INSERT INTO dist SELECT a + 1 FROM dist_table;
-- here the copy will fail.
```

Comment (SaitTalhaNisanci) [reply src/backend/distributed/executor/local_executor.c:487]: Also this shouldn't be just queryStringList but also perPlacementQueryStrings. So it might be simpler to introduce a function that copies a string list.

Comment (onurctirtir) [reply src/backend/distributed/executor/local_executor.c:487]: > Also this shouldn't be just queryStringList but also perPlacementQueryStrings. So it might be simpler to introduce a function that copies a string list.

I am ok with this to prevent major change

File: src/test/regress/expected/coordinator_shouldhaveshards.out [hunk 3]
```diff
@@ -375,13 +375,47 @@ NOTICE:  executing the command locally: SELECT a.count, b.x, b.y, c.a, c.b, d.co
...
+NOTICE:  copying the data has completed
+DETAIL:  The local data in the table is longer visible, but is still on disk.
+HINT:  To remove the local data, run: SELECT truncate_local_data_after_distributing_table($$coordinator_shouldhaveshards.dist_table$$)
+ create_distributed_table
+---------------------------------------------------------------------
+
+(1 row)
+
+BEGIN;
+-- use transtion block so that we will call ExtractLocalAndRemoteTasks
```
Comment (onurctirtir) [inline src/test/regress/expected/coordinator_shouldhaveshards.out:393]: I would prefer to add such a comment instead of referring to a function name

```suggestion
-- force using local execution using transaction block to test if
-- we create remote & local tasks properly
```

File: src/test/regress/expected/coordinator_shouldhaveshards.out [hunk 4]
```diff
@@ -375,13 +375,47 @@ NOTICE:  executing the command locally: SELECT a.count, b.x, b.y, c.a, c.b, d.co
...
+INSERT INTO dist_table SELECT a + 1 FROM dist_table;
+ROLLBACK;
+BEGIN;
+SET citus.shard_replication_factor TO 2;
```
Comment (onurctirtir) [inline src/test/regress/expected/coordinator_shouldhaveshards.out:397]: we already set `shard_replication_factor` to 2 in a few lines above

**Comment by onurctirtir** [comment]
It could also be awesome if we could also add a test related with object propagation like mentioned in #3801 but it probobly won't be possible to see such a failure on master with such an object propagation command.

Adding this comment here just as a follow up to see if this pr fixes the problem @marcocitus encountered.

File: src/backend/distributed/utils/citus_copyfuncs.c [hunk 5]
```diff
@@ -73,6 +74,20 @@ CitusSetTag(Node *node, int tag)
...
+	char *curString = NULL; \
+	List *newList = NIL; \
+	foreach_ptr(curString, from->fldname) { \
+		char *newString = curString ? pstrdup(curString) : (char *) NULL; \
+		if (newList == NIL) { \
+			newList = list_make1(newString); \
+		} \
+		else { \
+			newList = lappend(newList, newString); \
+		} \
```
Comment (onlined) [inline src/backend/distributed/utils/citus_copyfuncs.c:87]: Doesn't appending to `NIL` create a new list that contains only appended element? Do you need this branching?

File: src/backend/distributed/utils/citus_copyfuncs.c [hunk 6]
```diff
@@ -73,6 +74,20 @@ CitusSetTag(Node *node, int tag)
...
+	} \
+	newnode->fldname = newList;
```
Comment (onlined) [inline src/backend/distributed/utils/citus_copyfuncs.c:89]: You could wrap the code in `do { } while(0)` for better scoping.

File: src/backend/distributed/utils/citus_copyfuncs.c (hunk 5 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/utils/citus_copyfuncs.c:87]: I guess it does:

```c
List *
lappend(List *list, void *datum)
{
	Assert(IsPointerList(list));

	if (list == NIL)
		list = new_list(T_List);
	else
		new_tail_cell(list);

	lfirst(list->tail) = datum;
	check_list_invariants(list);
	return list;
}
```

File: src/backend/distributed/utils/citus_copyfuncs.c (hunk 6 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/utils/citus_copyfuncs.c:89]: umm, makes sense. For others: https://stackoverflow.com/questions/923822/whats-the-use-of-do-while0-when-we-define-a-macro

File: src/test/regress/expected/coordinator_shouldhaveshards.out (hunk 4 above)
Comment (SaitTalhaNisanci) [reply src/test/regress/expected/coordinator_shouldhaveshards.out:397]: I have actually intentionally used it again here because if someone later adds a test that changes replication factor to 1, this test won't be doing what it needs to do. In this test the replication factor specifically needs to be 2, hence I put it here explicitly. But I am okay with removing it as well hoping that noone will put something before this test. So you decide :)

File: src/test/regress/expected/coordinator_shouldhaveshards.out (hunk 3 above)
Comment (SaitTalhaNisanci) [reply src/test/regress/expected/coordinator_shouldhaveshards.out:393]: Here we test the case where the task query will be `perPlacementQueryStrings`, so maybe something better could be:

```
-- this will use perPlacementQueryStrings, make sure it works correctly with
-- copying task
```

File: src/backend/distributed/executor/local_executor.c [hunk 7]
```diff
@@ -468,48 +468,45 @@ ExtractLocalAndRemoteTasks(bool readOnly, List *taskList, List **localTaskList,
...
-		if (list_length(task->taskPlacementList) == 1)
+		if (list_length(localTaskPlacementList) > 0)
 		{
-			/*
-			 * At this point, the task has a single placement (e.g,. anchor shard
-			 * is distributed table's shard). So, it is either added to local or
-			 * remote taskList.
-			 */
-			if (localTaskPlacementList == NIL)
+			if (list_length(task->taskPlacementList) == 1)
```
Comment (marcocitus) [inline src/backend/distributed/executor/local_executor.c:473]: I think there's nothing particularly interesting about tasks with a single placement.

How about we do something like this?

```c
        if (localTaskPlacementList == NIL)
        {
            *remoteTaskList = lappend(*remoteTaskList, task);
        }
        else if (remoteTaskPlacementList == NIL)
        {
            *localTaskList = lappend(*localTaskList, task);
        }
        else
        {
            /*
             * At this point, we're dealing with a task that has placements on both 
             * local and remote nodes.
             */
            task->partiallyLocalOrRemote = true;

```

File: src/backend/distributed/executor/local_executor.c [hunk 8]
```diff
@@ -468,48 +468,45 @@ ExtractLocalAndRemoteTasks(bool readOnly, List *taskList, List **localTaskList,
...
+				*localTaskList = lappend(*localTaskList, task);
 			}
 			else
 			{
-				*localTaskList = lappend(*localTaskList, task);
+				/*
+				 * At this point, we're dealing with reference tables or intermediate
+				 * results where the task has placements on both local and remote
+				 * nodes. We always prefer to use local placement, and require remote
+				 * placements only for modifications.
```
Comment (marcocitus) [inline src/backend/distributed/executor/local_executor.c:483]: > we're dealing with reference tables or intermediate results

we should probably remove this sentence, since there are other cases so it might be misleading.

File: src/test/regress/expected/coordinator_shouldhaveshards.out (hunk 4 above)
Comment (onurctirtir) [reply src/test/regress/expected/coordinator_shouldhaveshards.out:397]: > hoping that noone will put something before this test

actually that makes sense, seting it to 2 again would be safer than hoping 😄

File: src/backend/distributed/executor/local_executor.c (hunk 7 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/executor/local_executor.c]: This simplifies it further, much easier to understand. Thanks for the idea.

**Comment by SaitTalhaNisanci** [comment]
It is strange that we get codecov report many times. We should fix that if we can
