### PR TITLE
Avoid setting hasWindowFuncs true after window functions have been optimized out of query

### LINKED ISSUE #3754: Assertion failure on window functions
Generated by SQLSimith
```SQL
select  
  ref_0.time as c0, 
  pg_catalog.int28eq(
    cast(pg_catalog.mod(
      cast(case when true then pg_catalog.int2(
          cast(ref_0.y as int4)) else pg_catalog.int2(
          cast(ref_0.y as int4)) end
         as int2),
      cast(cast(coalesce(pg_catalog.int2mul(
          cast(case when cast(null as anyrange) > cast(null as anyrange) then cast(null as int2) else cast(null as int2) end
             as int2),
          cast(cast(null as int2) as int2)),
        case when false then case when true then cast(null as int2) else cast(null as int2) end
             else case when true then cast(null as int2) else cast(null as int2) end
             end
          ) as int2) as int2)) as int2),
    cast(
      pg_catalog.sum(
        cast(case when (ref_0.value_2 < ref_0.value_2) 
            or (ref_0.time < cast(null as date)) then pg_catalog.abs(
            cast(cast(null as int2) as int2)) else pg_catalog.abs(
            cast(cast(null as int2) as int2)) end
           as int2)) over (partition by ref_0.value_3 order by ref_0.user_id) as int8)) as c1, 
  100 as c2, 
  pg_catalog.pg_reload_conf() as c3, 
  ref_0.value_2 as c4
from 
  public.events_table as ref_0
where pg_catalog.timestamptz(
    cast(pg_catalog.clock_timestamp() as timestamptz),
    cast(pg_catalog.pg_backend_pid() as int4)) is NULL
limit 61;
```

```
* thread #1, stop reason = signal SIGSTOP
  * frame #0: 0x00007fff7e0af2c2 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff7e16abf1 libsystem_pthread.dylib`pthread_kill + 284
    frame #2: 0x00007fff7e0196a6 libsystem_c.dylib`abort + 127
    frame #3: 0x0000000100a337ce postgres`ExceptionalCondition(conditionName=<unavailable>, errorType=<unavailable>, fileName=<unavailable>, lineNumber=<unavailable>) at assert.c:54:2
    frame #4: 0x0000000101209c87 citus.so`BuildJobQuery(multiNode=<unavailable>, dependentJobList=<unavailable>) at multi_physical_planner.c:737:2
    frame #5: 0x0000000101209559 citus.so`BuildJobTree(multiTree=<unavailable>) at multi_physical_planner.c:475:28
    frame #6: 0x0000000101209415 citus.so`CreatePhysicalDistributedPlan(multiTree=0x00000001014b9b08, plannerRestrictionContext=0x00000001014b3068) at multi_physical_planner.c:232:19
    frame #7: 0x00000001011fce24 citus.so`CreateDistributedPlan(planId=1, originalQuery=0x00007f9e5b84fa08, query=0x00007f9e5b84fb20, boundParams=0x0000000000000000, hasUnresolvedParams=<unavailable>, plannerRestrictionContext=0x00000001014b3068) at distributed_planner.c:1108:20
    frame #8: 0x00000001011fca5a citus.so`CreateDistributedPlannedStmt(planContext=0x00007ffeef5e11c0) at distributed_planner.c:705:3
    frame #9: 0x00000001011fb9fe citus.so`PlanDistributedStmt(planContext=0x00007ffeef5e11c0, rteIdCounter=<unavailable>) at distributed_planner.c:636:24
    frame #10: 0x00000001011fb540 citus.so`distributed_planner(parse=0x00007f9e5b84fb20, cursorOptions=<unavailable>, boundParams=<unavailable>) at distributed_planner.c:263:14
    frame #11: 0x0000000100932cf8 postgres`pg_plan_query(querytree=0x00007f9e5b84fb20, cursorOptions=256, boundParams=0x0000000000000000) at postgres.c:832:9
    frame #12: 0x0000000100932e1e postgres`pg_plan_queries(querytrees=<unavailable>, cursorOptions=256, boundParams=0x0000000000000000) at postgres.c:898:11
    frame #13: 0x0000000100934f1e postgres`exec_simple_query(query_string="select  \n  ref_0.time as c0, \n  pg_catalog.int28eq(\n    cast(pg_catalog.mod(\n      cast(case when true then pg_catalog.int2(\n          cast(ref_0.y as int4)) else pg_catalog.int2(\n          cast(ref_0.y as int4)) end\n         as int2),\n      cast(cast(coalesce(pg_catalog.int2mul(\n          cast(case when cast(null as anyrange) > cast(null as anyrange) then cast(null as int2) else cast(null as int2) end\n             as int2),\n          cast(cast(null as int2) as int2)),\n        case when false then case when true then cast(null as int2) else cast(null as int2) end\n             else case when true then cast(null as int2) else cast(null as int2) end\n             end\n          ) as int2) as int2)) as int2),\n    cast(\n      pg_catalog.sum(\n        cast(case when (ref_0.value_2 < ref_0.value_2) \n            or (ref_0.time < cast(null as date)) then pg_catalog.abs(\n            cast(cast(null as int2) as int2)) else pg_catalog.abs(\n            cast(cast(null as int2) as int2)) end\n           as int2)) over (partition"...) at postgres.c:1073:19
    frame #14: 0x0000000100934664 postgres`PostgresMain(argc=<unavailable>, argv=<unavailable>, dbname=<unavailable>, username=<unavailable>) at postgres.c:0:11
    frame #15: 0x00000001008b86da postgres`BackendRun(port=0x0000000100becce1) at postmaster.c:4358:2
    frame #16: 0x00000001008b7f60 postgres`BackendStartup(port=<unavailable>) at postmaster.c:4030:3
    frame #17: 0x00000001008b74e2 postgres`ServerLoop at postmaster.c:1707:7
    frame #18: 0x00000001008b5435 postgres`PostmasterMain(argc=3, argv=0x00007f9e5ac03150) at postmaster.c:1380:11
    frame #19: 0x0000000100821026 postgres`main(argc=3, argv=0x00007f9e5ac03150) at main.c:228:3
    frame #20: 0x00007fff7df743d5 libdyld.dylib`start + 1
    frame #21: 0x00007fff7df743d5 libdyld.dylib`start + 1
```

### PR DESCRIPTION
**Pull request by serprex**
Fixes #3754

### CODE REVIEW

File: src/backend/distributed/planner/multi_logical_optimizer.c [hunk 1]
```diff
@@ -2247,15 +2247,23 @@ WorkerExtendedOpNode(MultiExtendedOp *originalOpNode,
...
-		ProcessWindowFunctionsForWorkerQuery(originalWindowClause,
-											 originalTargetEntryList,
-											 &queryWindowClause, &queryTargetList);
-	}
-	else
+	/*
+	 * Planner optimizations may leave window clauses with hasWindowFuncs as false.
+	 * Ignore window clauses in that case.
+	 */
+	if (extendedOpNodeProperties->hasWindowFuncs)
```
Comment (serprex) [inline src/backend/distributed/planner/multi_logical_optimizer.c:2254]: TODO: check what happens when one has a WINDOW clause which is only referenced by window functions in subqueries. We should be erroring out in that scenario if postgres doesn't already
