### PR TITLE
Multi row insert bug

### LINKED ISSUE #3357: multi-row inserts for range-partitioned tables with composite dist column doesn't work
See https://github.com/citusdata/citus/pull/3356

Also, single row inserts work.

After creating the udf for creating shards in #3356, do:

```sql
CREATE TYPE composite_key_type AS (f1 int, f2 text);
SET citus.shard_replication_factor TO 1;

CREATE TABLE t(key composite_key_type);
SELECT create_distributed_table('t', 'key', 'range');
CALL public.create_range_partitioned_shards('t', '{"(0,a)","(25,a)"}','{"(24,z)","(49,z)"}');
INSERT INTO t VALUES ((0, 'a')), ((1, 'z'));
SELECT * FROM t;
 key 
-----
(0 rows)


INSERT INTO t VALUES ((0, 'a'));
INSERT INTO t VALUES ((1, 'z'));
SELECT * FROM t;
  key  
-------
 (0,a)
 (1,z)
(2 rows)

```

Maybe #1597 is also related, but in this case we are not missing min/max values.

### PR DESCRIPTION
**Pull request by serprex**
DESCRIPTION: Fix inserting multiple composite types as partition key in VALUES

For some reason postgres converts RowExpr to Const for single value inserts, but not multi value inserts

Fixes #3357

### CODE REVIEW

File: src/test/regress/sql/multi_row_insert.sql [hunk 1]
```diff
@@ -0,0 +1,45 @@
+-- Test multi row insert with composite type as partition key
+-- https://github.com/citusdata/citus/issues/3357
+
+CREATE OR REPLACE PROCEDURE create_range_partitioned_shards(rel regclass, minvalues text[], maxvalues text[])
```
Comment (pykello) [inline src/test/regress/sql/multi_row_insert.sql]: this is already defined in multi_test_helpers.

File: src/backend/distributed/planner/multi_router_planner.c [hunk 2]
```diff
@@ -2559,8 +2559,8 @@ BuildRoutesForInsert(Query *query, DeferredErrorMessage **planningError)
 
 		if (!IsA(insertValues->partitionValueExpr, Const))
 		{
-			/* shard pruning not possible right now */
-			return NIL;
+			ereport(ERROR, (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
+							errmsg("failed to evaluate partition key in insert")));
```
Comment (pykello) [inline src/backend/distributed/planner/multi_router_planner.c]: maybe add an `errhint("try using constant values for partition column")`
