### PR TITLE
Issue 7887 Enhance AddInsertSelectCasts for Identity Columns

### LINKED ISSUE #7887: Cannot bulk insert from one local table to another local table if one has an identity
Hello!  While implementing Citus distributed and reference tables, we encountered an issue inserting data from one local table to another when the target local table has an identity.  Repro steps below:

Citus version: Citus 12.1.6 on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit

```
--create a test schema
create schema test;

-- add our first local table
create table test.local1(
    id text not null primary key
);

-- add our reference table
create table test.reference1(
    id int not null primary key,
    reference_col1 text not null
);

-- apply the reference table type
select create_reference_table('test.reference1');

-- add our second local table
create table test.local2(
    id int not null generated always as identity,
    local1fk text not null,
    reference1fk int not null,
    constraint loc1fk foreign key (local1fk) references test.local1(id),
    constraint reference1fk foreign key (reference1fk) references test.reference1(id),
    constraint testlocpk primary key (id)
);

-- create a distributed table
create table test.distributed1(
    id int not null generated always as identity,
    distro_key int not null,
    constraint testdistro1pk primary key (id, distro_key)
);

-- apply distribution on the distro key
select create_distributed_table('test.distributed1', 'distro_key');

-- add our first local table values
insert into test.local1(id) values ('aaaaa'), ('bbbbb'), ('ccccc');

-- add our reference data
insert into test.reference1(id, reference_col1) values (1, 'test'), (2, 'test2'), (3, 'test3');

-- add data to our distributed table
insert into test.distributed1(distro_key) values (1), (1), (1), (2), (2), (3);

-- we confirm that we have two local tables and one reference table
select
    a.table_name,
    b.citus_table_type
from information_schema.tables a
    left join citus_tables b on b.table_name::text = concat(a.table_schema::text, '.', a.table_name::text)
where a.table_schema = 'test'
	and a.table_type = 'BASE TABLE'
order by a.table_name

-- bulk insert from our first local table into our second
insert into test.local2(local1fk, reference1fk)
select id, 1 from test.local1

-- why does this fail?  invalid string enlargement request size: -4
```

At first I assumed this might be an unsupported operation, but I tried it again in the exact same scenario in which the local table has a serial PK rather than an identity, and did not receive the error.  As a result, I suspect this is a bug related to support of identities.

Successful test with serial instead:

```
--create a test schema
create schema testserial;

-- add our first local table
create table testserial.local1(
    id text not null primary key
);

-- add our reference table
create table testserial.reference1(
    id int not null primary key,
    reference_col1 text not null
);

-- apply the reference table type
select create_reference_table('testserial.reference1');

-- add our second local table
create table testserial.local2(
    id bigserial,
    local1fk text not null,
    reference1fk int not null,
    constraint loc1fk foreign key (local1fk) references testserial.local1(id),
    constraint reference1fk foreign key (reference1fk) references testserial.reference1(id),
    constraint testlocpk primary key (id)
);

-- create a distributed table
create table testserial.distributed1(
    id bigserial,
    distro_key int not null,
    constraint testdistro1pk primary key (id, distro_key)
);

-- apply distribution on the distro key
select create_distributed_table('testserial.distributed1', 'distro_key');

-- add our first local table values
insert into testserial.local1(id) values ('aaaaa'), ('bbbbb'), ('ccccc');

-- add our reference data
insert into testserial.reference1(id, reference_col1) values (1, 'test'), (2, 'test2'), (3, 'test3');

-- add data to our distributed table
insert into testserial.distributed1(distro_key) values (1), (1), (1), (2), (2), (3);

-- we confirm that we have two local tables and one reference table
select
    a.table_name,
    b.citus_table_type
from information_schema.tables a
    left join citus_tables b on b.table_name::text = concat(a.table_schema::text, '.', a.table_name::text)
where a.table_schema = 'testserial'
	and a.table_type = 'BASE TABLE'
order by a.table_name

-- bulk insert from our first local table into our second
insert into testserial.local2(local1fk, reference1fk)
select id, 1 from test.local1

-- why did this work, but an identity did not?
```

### PR DESCRIPTION
**Pull request by m3hm3t**
## Enhance `AddInsertSelectCasts` for Identity Columns

This PR fixes #7887  and improves the behavior of partial inserts into **identity columns** by modifying the **`AddInsertSelectCasts`** function. Specifically, we introduce **special-case handling** for `nextval(...)` calls (represented in the parse tree as `NextValueExpr`) to ensure that if the identity column’s declared type differs from `nextval`’s default return type (`int8`), we **cast** the expression properly. This prevents mismatches like `int8` → `int4` from causing “invalid string enlargement” errors or other type-related failures.

When `INSERT ... SELECT` is processed, `AddInsertSelectCasts` reconciles each target column’s type with the corresponding SELECT expression’s type. Historically, for identity columns that rely on `nextval(...)`, we can end up with a mismatch:
- `nextval` returns **`int8`**,
- The identity column might be **`int4`**, **`bigint`**, or another integer type.

Without a correct cast, Postgres or Citus can produce plan-time or runtime errors. By **detecting** `NextValueExpr` and applying a cast to the column’s type, the final plan ensures consistent insertion without errors.

## What Changed

1. **Check for `NextValueExpr`**:  
   In `AddInsertSelectCasts`, we now have a code block:
   ```c
   if (IsA(selectEntry->expr, NextValueExpr))
   {
       Oid nextvalType = GetNextvalReturnTypeCatalog();
       ...
       // If (targetType != nextvalType), build a cast from int8 -> targetType
   }
   else
   {
       // fallback to generic mismatch logic
   }
   ```
   This short-circuits any expression that’s a `nextval(...)` call, letting us explicitly cast to the correct type.

2. **Fallback Generic Logic**:  
   If it isn’t a `NextValueExpr` (i.e. a normal column or expression mismatch), we still rely on the existing path that compares `sourceType` vs. `targetType` and calls `CastExpr(...)` if they differ.

3. **`GetNextvalReturnTypeCatalog`**:  
   We added or refined a helper function to confirm that `nextval` returns `int8`, or do a `LookupFuncName("nextval", ...)` to discover the function’s return type from `pg_proc`—making it robust if future changes happen.

## Benefits

- **Partial inserts** into identity columns no longer fail with type mismatches.  
- When `nextval` yields `int8` but the identity column is `int4` (or another type), we properly cast to the column’s type in the plan.  
- Preserves the **existing** approach for other columns—only identity calls get the specialized `NextValueExpr` logic.

## Testing

   - Extended `generatedidentity.sql` test scenario to cover partial inserts into both `GENERATED ALWAYS` and `GENERATED BY DEFAULT` identity columns, including tests for the `OVERRIDING SYSTEM VALUE` clause and partial inserts referencing foreign-key columns.

### CODE REVIEW

**Comment by c2main** [comment]
I wanted to review as I was working on similar topic, but the code move make it hard to use diff. Would it be possible to move the code then have the fix or the reverse but not mixing both ?

**Comment by c2main** [comment]
> I wanted to review as I was working on similar topic, but the code move make it hard to use diff. Would it be possible to move the code then have the fix or the reverse but not mixing both ?

I think you should be just replacing this:

```
+   :targetList (
+      {TARGETENTRY 
+      :expr 
+         {NEXTVALUEEXPR 
+         :seqid 17616 
+         :typeId 23
+         }
+      :resno 1 
+      :resname id 
+      :ressortgroupref 0 
+      :resorigtbl 0 
+      :resorigcol 0 
+      :resjunk false
+      }
```
with:
```
+   :targetList (
+      {TARGETENTRY 
+      :expr 
+         {FUNCEXPR 
+         :funcid 480 
+         :funcresulttype 23 
+         :funcretset false 
+         :funcvariadic false 
+         :funcformat 2 
+         :funccollid 0 
+         :inputcollid 0 
+         :args (
+            {FUNCEXPR 
+            :funcid 1574 
+            :funcresulttype 20 
+            :funcretset false 
+            :funcvariadic false 
+            :funcformat 0 
+            :funccollid 0 
+            :inputcollid 0 
+            :args (
+               {CONST 
+               :consttype 2205 
+               :consttypmod -1 
+               :constcollid 0 
+               :constlen 4 
+               :constbyval true 
+               :constisnull false 
+               :location -1 
+               :constvalue 4 [ -11 68 0 0 0 0 0 0 ]
+               }
+            )
+            :location -1
+            }
+         )
+         :location -1
+         }
+      :resno 1 
+      :resname id 
+      :ressortgroupref 0 
+      :resorigtbl 0 
+      :resorigcol 0 
+      :resjunk false
+      }
```

or similar... i.e. replace node with a `makeFuncExpr` or the like... then the citus executor will handle manage the call to the relevant function.

**Comment by c2main** [comment]
(serial/nextval are replaced by parser, not identity columns, IIRCC)

**Comment by colm-mchugh** [comment]
> > I wanted to review as I was working on similar topic, but the code move make it hard to use diff. Would it be possible to move the code then have the fix or the reverse but not mixing both ?
> 
> I think you should be just replacing this:
> 
> ```
> +   :targetList (
> +      {TARGETENTRY 
> +      :expr 
> +         {NEXTVALUEEXPR 
> +         :seqid 17616 
> +         :typeId 23
> +         }
> +      :resno 1 
> +      :resname id 
> +      :ressortgroupref 0 
> +      :resorigtbl 0 
> +      :resorigcol 0 
> +      :resjunk false
> +      }
> ```
> 
> with:
> 
> ```
> +   :targetList (
> +      {TARGETENTRY 
> +      :expr 
> +         {FUNCEXPR 
> +         :funcid 480 
> +         :funcresulttype 23 
> +         :funcretset false 
> +         :funcvariadic false 
> +         :funcformat 2 
> +         :funccollid 0 
> +         :inputcollid 0 
> +         :args (
> +            {FUNCEXPR 
> +            :funcid 1574 
> +            :funcresulttype 20 
> +            :funcretset false 
> +            :funcvariadic false 
> +            :funcformat 0 
> +            :funccollid 0 
> +            :inputcollid 0 
> +            :args (
> +               {CONST 
> +               :consttype 2205 
> +               :consttypmod -1 
> +               :constcollid 0 
> +               :constlen 4 
> +               :constbyval true 
> +               :constisnull false 
> +               :location -1 
> +               :constvalue 4 [ -11 68 0 0 0 0 0 0 ]
> +               }
> +            )
> +            :location -1
> +            }
> +         )
> +         :location -1
> +         }
> +      :resno 1 
> +      :resname id 
> +      :ressortgroupref 0 
> +      :resorigtbl 0 
> +      :resorigcol 0 
> +      :resjunk false
> +      }
> ```
> 
> or similar... i.e. replace node with a `makeFuncExpr` or the like... then the citus executor will handle manage the call to the relevant function.

This approach was considered in #7911 but we decided instead to favor the insert-a-cast approach here, for the following reasons:
- The Postgres executor handles `NextValueExpr` nodes, which are used only for identity columns. (see `execExpr.c`)
- Postgres ruleutils converts a `NextValueExpr` node to a `FuncExpr` for nextval() 
- The problem is not present if the column is `serial` - in that case, the expression given to the Citus planner hook is a `FuncExpr` for nextval()  casted to the type of the target column if necessary.

So we reckon that emulating the Postgres processing for `serial` columns is the most desirable way to go.

**Comment by colm-mchugh** [comment]
> I wanted to review as I was working on similar topic, but the code move make it hard to use diff. Would it be possible to move the code then have the fix or the reverse but not mixing both ?

This was motivated by the two cases - (1) different target and source types, (2) source is a generated identity - both requiring a cast, so refactoring the code made sense. The flow is the same, but now there's a function to apply the cast and an extra branch for handling `NextValueExpr`

**Comment by m3hm3t** [comment]
> I wanted to review as I was working on similar topic, but the code move make it hard to use diff. Would it be possible to move the code then have the fix or the reverse but not mixing both ?

@c2main 
I apologize for mixing the fix with the refactoring. The fix introduced a lot of duplicate code, so I had to clean it up with some refactoring.

**Comment by m3hm3t** [comment]
> > I wanted to review as I was working on similar topic, but the code move make it hard to use diff. Would it be possible to move the code then have the fix or the reverse but not mixing both ?
> 
> I think you should be just replacing this:
> 


```
selectEntry:
  Address: 0x55eadc13d898

xpr:
  Type: T_TargetEntry
  Expression:
    Address: 0x55eadc13d608
    Type: T_NextValueExpr

resno: 1
resname:
  Address: 0x55eadc13d8e8
  Value: "id"
  First Character: 'i' (ASCII: 105)

ressortgroupref: 0
resorigtbl: 0
resorigcol: 0
resjunk: false
```
=>

```
coercedEntry:
  Address: 0x55eadc13daf8

xpr:
  Type: T_TargetEntry
  Expression:
    Address: 0x55eadc13db80
    Type: T_FuncExpr

resno: 1
resname:
  Address: 0x55eadc13dc50
  Value: "auto_coerced_by_citus_0"
  First Character: 'a' (ASCII: 97)

ressortgroupref: 0
resorigtbl: 0
resorigcol: 0
resjunk: false
```


As @colm-mchugh mentioned earlier, the code is still being replaced in the same way.

**Review by colm-mchugh — APPROVED** [review]
LGTM, thanks for accommodating review comments.  Can we label with `cherry-pick-13.0` ?

File: src/backend/distributed/planner/insert_select_planner.c [hunk 1]
```diff
@@ -1617,11 +1628,87 @@ RelabelTargetEntryList(List *selectTargetList, List *insertTargetList)
...
+							sourceType, targetType,
+							attr->attcollation, attr->atttypmod,
+							targetEntryIndex,
+							projectedEntries, nonProjectedEntries);
+	}
+	else
+	{
+		/* Types match, no cast needed */
+		*projectedEntries = lappend(*projectedEntries, selectEntry);
+	}
```
[the remark this answers is not in the document]
Comment (m3hm3t) [reply src/backend/distributed/planner/insert_select_planner.c]: I attempted to restructure it without introducing complexity.

File: src/backend/distributed/planner/insert_select_planner.c [hunk 2]
```diff
@@ -96,6 +96,17 @@ static List * AddInsertSelectCasts(List *insertTargetList, List *selectTargetLis
...
+static void append_casted_entry(TargetEntry *insertEntry, TargetEntry *selectEntry,
+								Oid castFromType, Oid targetType, Oid collation, int32
+								typmod,
+								int targetEntryIndex,
+								List **projectedEntries, List **nonProjectedEntries);
+static void set_target_entry_name(TargetEntry *tle, const char *format, int index);
+static void reset_target_entry_resno(List *targetList);
+static void process_entry_pair(TargetEntry *insertEntry, TargetEntry *selectEntry,
+							   Form_pg_attribute attr, int targetEntryIndex,
+							   List **projectedEntries, List **nonProjectedEntries);
```
Comment (onurctirtir) [inline src/backend/distributed/planner/insert_select_planner.c:109]: As in `GetNextvalReturnTypeCatalog()`, we prefer CamelCase in code-base over snake-case, except the functions that we copy from Postgres, so it would be better if we rename these functions before merging.

**Review by onurctirtir — COMMENTED** [review]
Let's please add such a line into PR description so that this fix appears in changelog as a user-facing change.

`DESCRIPTION: Fixes a bug ... / `

You can check CHANGELOG.md to see the example formats that we use in release changelog.

File: src/backend/distributed/planner/insert_select_planner.c (hunk 2 above)
Comment (m3hm3t) [reply src/backend/distributed/planner/insert_select_planner.c]: converted
