### PR TITLE
Do not prune shards if the distribution key is NULL

### LINKED ISSUE #3493: WARNING: Major Segmentation Failure bug in Citus 9.2
There is a huge bug in Citus 9.2. We tried to bump to this version and our test suites totally failed. We are using Ruby on Rails and this error happened deep inside framework related queries. But I was able to isolate it, its easy to reproduce:
```
test=# CREATE TABLE test (id text);
CREATE TABLE

test=# SELECT create_distributed_table('test', 'id');
 create_distributed_table
--------------------------

(1 row)

test=# PREPARE stmt(text) AS SELECT * FROM test WHERE id = $1;
PREPARE

test=# EXECUTE stmt(NULL);
server closed the connection unexpectedly
    This probably means the server terminated abnormally
    before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> SEGMENTATION FAULT!!!
```

Here are (coordinator) logs if they are any use
```
2020-02-12 12:16:51.094 UTC [1] LOG:  server process (PID 21697) was terminated by signal 11: Segmentation fault
2020-02-12 12:16:51.094 UTC [1] DETAIL:  Failed process was running: EXECUTE stmt(NULL);
2020-02-12 12:16:51.094 UTC [1] LOG:  terminating any other active server processes
2020-02-12 12:16:51.096 UTC [21674] WARNING:  terminating connection because of crash of another server process
2020-02-12 12:16:51.096 UTC [21674] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2020-02-12 12:16:51.096 UTC [21674] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2020-02-12 12:16:51.102 UTC [23050] FATAL:  the database system is in recovery mode
2020-02-12 12:16:51.107 UTC [1] LOG:  all server processes terminated; reinitializing
2020-02-12 12:16:51.133 UTC [23051] LOG:  database system was interrupted; last known up at 2020-02-12 12:12:42 UTC
2020-02-12 12:16:51.134 UTC [23051] LOG:  database system was not properly shut down; automatic recovery in progress
2020-02-12 12:16:51.136 UTC [23051] LOG:  redo starts at 0/AD208D0
2020-02-12 12:16:51.136 UTC [23051] LOG:  invalid record length at 0/AD20B38: wanted 24, got 0
2020-02-12 12:16:51.136 UTC [23051] LOG:  redo done at 0/AD20B00
2020-02-12 12:16:51.145 UTC [1] LOG:  database system is ready to accept connections
```

### PR DESCRIPTION
**Pull request by onderkalaci**
Fixes #3493

The root of the problem is that, standard_planner() converts the following qual

```
   {OPEXPR
   :opno 98
   :opfuncid 67
   :opresulttype 16
   :opretset false
   :opcollid 0
   :inputcollid 100
   :args (
      {VAR
      :varno 1
      :varattno 1
      :vartype 25
      :vartypmod -1
      :varcollid 100
      :varlevelsup 0
      :varnoold 1
      :varoattno 1
      :location 45
      }
      {CONST
      :consttype 25
      :consttypmod -1
      :constcollid 100
      :constlen -1
      :constbyval false
      :constisnull true
      :location 51
      :constvalue <>
      }
   )
   :location 49
   }
```

To

```
(
   {CONST
   :consttype 16
   :consttypmod -1
   :constcollid 0
   :constlen 1
   :constbyval true
   :constisnull true
   :location -1
   :constvalue <>
   }
)
```

So, Citus doesn't deal with NULL values in real-time or non-fast path router queries.

And, in the FastPathRouter planner, we check constisnull in DistKeyInSimpleOpExpression().
However, in deferred pruning case, we do not check for isnull for const.

Thus, the fix consists of two parts:
- Let PruneShards() not crash when NULL parameter is passed (it used to crash `PerformCompare`)
- For deferred shard pruning in fast-path queries, explicitly check that we have CONST which is not NULL

DESCRIPTION: Fixes a bug that could cause crashes if dist. key is NULL

### CODE REVIEW

File: src/test/regress/sql/null_parameters.sql [hunk 1]
```diff
@@ -0,0 +1,313 @@
+-- this file contain tests with pruning of NULL
+-- values with prepared statements
```
Comment (onderkalaci) [inline src/test/regress/sql/null_parameters.sql]: we can consider making this file smaller, but it only takes around 900msecs on my local, so I'm ok to keep

File: src/backend/distributed/planner/multi_router_planner.c [hunk 2]
```diff
@@ -2407,6 +2407,13 @@ TargetShardIntervalForFastPathQuery(Query *query, Const **partitionValueConst,
 		PruneShards(relationId, relationIndex, make_ands_implicit((Expr *) quals),
 					&queryPartitionValueConst);
 
+	if (PartitionMethod(relationId) != DISTRIBUTE_BY_NONE &&
+		(!queryPartitionValueConst || queryPartitionValueConst->constisnull))
+	{
+		/* we're not interested in NULL values */
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_router_planner.c]: this comment seems unhelpful, what does a NULL value mean?

File: src/backend/distributed/planner/multi_router_planner.c [hunk 3]
```diff
@@ -2407,6 +2407,13 @@ TargetShardIntervalForFastPathQuery(Query *query, Const **partitionValueConst,
 		PruneShards(relationId, relationIndex, make_ands_implicit((Expr *) quals),
 					&queryPartitionValueConst);
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_router_planner.c]: This function could use some clarification. What is the difference between distributionKeyValue and queryPartitionValueConst?

File: src/backend/distributed/planner/shard_pruning.c [hunk 4]
```diff
@@ -756,6 +756,17 @@ AddPartitionKeyRestrictionToInstance(ClauseWalkerContext *context, OpExpr *opCla
 		}
 	}
 
+	if (constantClause->constisnull)
+	{
+		/*
+		 * We cannot do pruning for NULL values, so we note this as a
+		 * restriction we don't grok.
```
Comment (marcocitus) [inline src/backend/distributed/planner/shard_pruning.c]: grok?

File: src/test/regress/sql/null_parameters.sql [hunk 5]
```diff
@@ -0,0 +1,313 @@
...
+
+-- not a fast-path, still good to run
+PREPARE null_select_on_text_param_and_in_5(text, text) AS SELECT count(*) FROM text_dist_column WHERE key = $1 OR key = $2;
+EXECUTE null_select_on_text_param_and_in_5(NULL, NULL);
+EXECUTE null_select_on_text_param_and_in_5(NULL, NULL);
+EXECUTE null_select_on_text_param_and_in_5(NULL, NULL);
+EXECUTE null_select_on_text_param_and_in_5(NULL, NULL);
+EXECUTE null_select_on_text_param_and_in_5(NULL, NULL);
+EXECUTE null_select_on_text_param_and_in_5(NULL, NULL);
+EXECUTE null_select_on_text_param_and_in_5(NULL, NULL);
```
Comment (marcocitus) [inline src/test/regress/sql/null_parameters.sql]: maybe also `1, NULL`

File: src/backend/distributed/planner/multi_router_planner.c [hunk 6]
```diff
@@ -2407,6 +2407,13 @@ TargetShardIntervalForFastPathQuery(Query *query, Const **partitionValueConst,
...
 
+	if (PartitionMethod(relationId) != DISTRIBUTE_BY_NONE &&
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_router_planner.c]: Can we have an early exit for reference tables? It seems odd that we made it all the way here and it's not immediately obvious how this relates to queryPartitionValueConst.

File: src/backend/distributed/planner/shard_pruning.c (hunk 4 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/shard_pruning.c]: > grok


that's a word that @jasonmp85 used in the few lines above, just copy-pasted :D I'll update both

File: src/backend/distributed/planner/multi_router_planner.c (hunk 2 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/multi_router_planner.c]: updated now.

File: src/backend/distributed/planner/multi_router_planner.c (hunk 3 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/multi_router_planner.c]: improved a bit, is it better now?

File: src/backend/distributed/planner/multi_router_planner.c [hunk 7]
```diff
@@ -2376,24 +2376,31 @@ GetAnchorShardId(List *prunedShardIntervalListList)
  * for the detail).
  *
  * Also set the outgoing partition column value if requested via
- * partitionValueConst
+ * outGoingPartitionValueConst.
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_router_planner.c]: outgoing could use some clarification

File: src/backend/distributed/planner/multi_router_planner.c [hunk 8]
```diff
@@ -2416,10 +2437,10 @@ TargetShardIntervalForFastPathQuery(Query *query, Const **partitionValueConst,
 		*isMultiShardQuery = true;
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_router_planner.c]: small note: this line does not seem to be covered by tests. Can it ever happen?

File: src/backend/distributed/planner/shard_pruning.c [hunk 9]
```diff
@@ -749,13 +749,21 @@ AddPartitionKeyRestrictionToInstance(ClauseWalkerContext *context, OpExpr *opCla
 															constantClause);
 		if (constantClause == NULL)
 		{
-			/* couldn't coerce value, so we note this as a restriction we don't grok */
+			/* couldn't coerce value, so we save it in otherRestrictions */
 			prune->otherRestrictions = lappend(prune->otherRestrictions, opClause);
```
Comment (marcocitus) [inline src/backend/distributed/planner/shard_pruning.c]: not covered by tests.

File: src/backend/distributed/planner/multi_router_planner.c (hunk 8 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/multi_router_planner.c]: That's actually a good point, I think it is copy&paste from RouterPlanner, but at this point we're sure that it is `FastPathQuery`, so we cannot/should not have any multi-shard queries.

I can think a bit more and fix it on master? As I'm not very confident to remove it at this point

File: src/backend/distributed/planner/shard_pruning.c (hunk 4 above)
Comment (jasonmp85) [reply src/backend/distributed/planner/shard_pruning.c]: Roughly "understand" or "comprehend". It's slangy, sorry, but at least fairly prevalent among anglophone-country techies…

>  1. (_transitive, slang_) To understand (something) intuitively, to know (something) without having to think intellectually.
>  2. (_transitive, slang_) To fully and completely understand something in all of its details and intricacies.

[Wiktionary entry](https://en.wiktionary.org/wiki/grok). My first instinct is it originated in Heinlein's _Stranger in a Strange Land_, which was apparently correct.

> Grok is used mainly by the geek subculture, though it was heavily used by the counterculture of the 1960s, as evidenced by its repeated appearance in Tom Wolfe's _The Electric Kool-Aid Acid Test._
