### PR TITLE
Fix crash in count distinct with filters in repartition subqueries

### LINKED ISSUE #569: Single table subquery COUNT DISTINCT crashes the server when FILTER clause is used
We recently checked-in #516. I now realzed a bug when FILTER clause is added to the `COUNT DISTINCT` clause where the target entries do not include the elements in FILTER clause.

```SQL
SELECT
   *                                                                                                                                                                                         
FROM
   (                                                                                                                                                                                                      SELECT
      l_orderkey,
      count(DISTINCT l_partkey) FILTER (
   WHERE
      l_shipmode = 'AIR')                                                                                                                                     
   FROM
      lineitem_hash                                                                                                                                                                                          
   GROUP BY
      l_orderkey) sub                                                                                                                                                                                    
ORDER BY
   2 DESC,
   1 DESC                                                                                                                                                                                     LIMIT 10;

server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

The failed assertion is on [citusruleutils_95.c](https://github.com/citusdata/citus/blob/master/src/backend/distributed/utils/ruleutils_95.c#L3604) while creating the `MergeTaskList`. It looks like we need to add FILTER clause entries to the worker/master target lists.

### PR DESCRIPTION
**Pull request by mtuncer**
We now copy all column references in count distinct aggreagete
to worker target list and group by. Master target list is
also updated to reflect changes in attribute order.

Fixes #569

### CODE REVIEW

File: src/backend/distributed/planner/multi_logical_optimizer.c [hunk 1]
```diff
@@ -1877,10 +1875,7 @@ WorkerAggregateExpressionList(Aggref *originalAggregate,
 		CountDistinctErrorRate == DISABLE_DISTINCT_APPROXIMATION &&
 		walkerContext->repartitionSubquery)
 	{
-		Aggref *aggregate = (Aggref *) copyObject(originalAggregate);
-		List *aggTargetEntryList = aggregate->args;
-		TargetEntry *distinctTargetEntry = (TargetEntry *) linitial(aggTargetEntryList);
-		List *columnList = pull_var_clause_default((Node *) distinctTargetEntry);
+		List *columnList = pull_var_clause_default((Node *) originalAggregate);
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_logical_optimizer.c]: Just a tiny difference here is that the code used to `copy` the original aggregate, so using copied `Vars`. Now, it uses the original `Vars`. But, below we already copy the columns when necessary. If you also think that it's OK, this is a :shipit:

Comment (mtuncer) [inline src/backend/distributed/planner/multi_logical_optimizer.c]: This approach is safe since we only return copied columns. However, After going through your comment I have found a simplification on the code.

File: src/backend/distributed/planner/multi_logical_optimizer.c [hunk 2]
```diff
@@ -1878,22 +1876,12 @@ WorkerAggregateExpressionList(Aggref *originalAggregate,
...
 		{
 			Var *column = (Var *) lfirst(columnCell);
-			if (list_member(processedColumnList, column))
-			{
-				continue;
-			}
-
-			processedColumnList = lappend(processedColumnList, column);
-			workerAggregateList = lappend(workerAggregateList, copyObject(column));
+			workerAggregateList = list_append_unique(workerAggregateList, column);
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_logical_optimizer.c]: With this change, we do not copy the `column` anymore. I'm not sure whether we need to copy it or not, but looking into the `else` part of the same function, I see the following such that we copy the aggrefs:
```C
		Aggref *workerAggregate = copyObject(originalAggregate);
		workerAggregateList = lappend(workerAggregateList, workerAggregate);
```

Do you think, should we copy the `column` as well,  to make them consistent with the below and ensure that the columns never change?

**Comment by onderkalaci** [comment]
I added a single comment, you can decide to apply it or not. 
Other than that, all looks good, check-full passes. :shipit:

File: src/backend/distributed/planner/multi_logical_optimizer.c (hunk 2 above)
Comment (mtuncer) [inline src/backend/distributed/planner/multi_logical_optimizer.c]: We are doing very similar thing, but instead of the aggregate itself we are adding the columns referenced from that.
I do not see any additional benefit by adding another level of copy here.

Comment (onderkalaci) [inline src/backend/distributed/planner/multi_logical_optimizer.c]: Well, with this approach we do not copy the target list elements at all for the repartition case. So, I mean that it is not `additional` level of copy, it'd be the only one.

Comment (mtuncer) [inline src/backend/distributed/planner/multi_logical_optimizer.c]: I think you are missing the copy at line 1878
