### PR TITLE
Remove length limitations for table renames

### LINKED ISSUE #4211: Cannot rename table to have a name >56 characters in length
Error message is observed when renaming a distributed table to have a name greater than 56 characters in length. This does not affect creating tables with names of that length. 

Error message observed:

```
psql:rename_issue.sql:5: ERROR:  shard name this_table_name_is_carefully_padded_for_precise_16fc88b7_104057 exceeds 63 characters
CONTEXT:  while executing command on 10.0.0.23:5432
```

Reproduction script:

```
drop table if exists rename_test;
drop table if exists this_table_name_is_carefully_padded_for_precisely_57_char;
create table rename_test(col1 int);
select create_distributed_table('rename_test','col1');
alter table rename_test rename to this_table_name_is_carefully_padded_for_precisely_57_char;

--Proving that same table name is valid when created
create table  this_table_name_is_carefully_padded_for_precisely_57_char (col1 int);
select create_distributed_table('this_table_name_is_carefully_padded_for_precisely_57_char','col1');
```

### LINKED ISSUE #4665: alter_table_set_access_method fails in case of long names
Failure with long names:

```sql
create table abcde_0123456789012345678901234567890123456789012345678901234567890123456789 (x int, y int);
select create_reference_table('abcde_0123456789012345678901234567890123456789012345678901234567890123456789');
select alter_table_set_access_method('abcde_0123456789012345678901234567890123456789012345678901234567890123456789', 'columnar');
ERROR:  shard name local_01234567890123456789012345678901234567890_24f58558_102177 exceeds 63 characters
CONTEXT:  while executing command on localhost:1300
SQL statement "ALTER TABLE public.local_01234567890123456789012345678901234567_24f58558_620070232 RENAME TO local_012345678901234567890123456789012345678901234567890123456"
```

Related to #4211.

### PR DESCRIPTION
**Pull request by hanefi**
DESCRIPTION: Removes limits around long table names

Citus had a limitation of at most 56 characters when renaming a distributed table because of deadlocks on workers with shard name collisions.

`alter_distributed_table` and `alter_table_set_access_method` functions use some RENAME commands that are also affected by this limitation.

This PR aims to switch to sequential and local execution when new table names are too long to fit in `NAMEDATALEN-1` characters when the shardId values are appended to them.

Fixes #4665
Fixes #4211

Related #1664

TODO:
- [x] Missing function comments
- [x] Understand and fix the broken isolation test
- [x] Improve the warning messages
	- [x] fix repetitive warning messages
    - [x] debug messages can be more suitable

### CODE REVIEW

File: src/backend/distributed/commands/rename.c [hunk 1]
```diff
@@ -109,6 +109,12 @@ PreprocessRenameStmt(Node *node, const char *renameCommand,
 	 */
 	ErrorIfUnsupportedRenameStmt(renameStmt);
 
+	if (renameStmt->renameType == OBJECT_TABLE)
+	{
```
Comment (marcocitus) [inline src/backend/distributed/commands/rename.c:113]: would the same logic hold for indexes? (anything else?)

Comment (hanefi) [reply src/backend/distributed/commands/rename.c:113]: I do not think we append shardId to types. So I can't think of a reason why a type rename should create deadlocks.

The 2 types that are created on table creation (such as events and _events[]) are covered by `OBJECT_TABLE`.

I should however test `OBJECT_FOREIGN_TABLE` especially with cstore tables

File: src/backend/distributed/commands/alter_table.c [hunk 2]
```diff
@@ -1572,3 +1577,76 @@ ExecuteQueryViaSPI(char *query, int SPIOK)
...
+		return;
+	}
+
+	if (PartitionedTable(relationId))
+	{
+		longestPartitionName = LongestPartitionName(relationId);
+		if (longestPartitionName == NULL)
+		{
+			/* no partitions have been created yet */
+			return;
```
Comment (marcocitus) [inline src/backend/distributed/commands/alter_table.c:1606]: Does a partitioned table without partitions not have an array type?

File: src/backend/distributed/commands/alter_table.c [hunk 3]
```diff
@@ -1572,3 +1577,76 @@ ExecuteQueryViaSPI(char *query, int SPIOK)
...
+	}
+
+	char *longestShardName = NULL;
+	if (longestPartitionName == NULL)
+	{
+		longestShardName = pstrdup(relationName);
+	}
+	else
+	{
+		longestShardName = pstrdup(relationName);
```
Comment (marcocitus) [inline src/backend/distributed/commands/alter_table.c:1617]: the if and the else are the same here

File: src/backend/distributed/commands/alter_table.c (hunk 2 above)
Comment (hanefi) [reply src/backend/distributed/commands/alter_table.c]: They actually have types. Fixed it in a separate commit.

I copied this logic from `SwitchToSequentialAndLocalExecutionIfIndexNameTooLong`. I confirmed that we do not need to update that function with a similar logic as in here.

The index names of partitioned table shards are managed by Citus, so that's ok. However partition index names are created by vanilla PG, that actually causes deadlocks. So it's ok to skip partitioned tables with no partitions in `SwitchToSequentialAndLocalExecutionIfIndexNameTooLong`.

@onderkalaci Can you confirm if my deductions are correct here?

File: src/backend/distributed/commands/alter_table.c (hunk 3 above)
Comment (hanefi) [reply src/backend/distributed/commands/alter_table.c:1608]: This was the result of an unsuccessful rebase. Fixed it now.

File: src/backend/distributed/commands/alter_table.c [hunk 4]
```diff
@@ -1572,3 +1577,67 @@ ExecuteQueryViaSPI(char *query, int SPIOK)
...
+	if (strlen(longestShardName) >= NAMEDATALEN - 1)
+	{
+		if (ParallelQueryExecutedInTransaction())
+		{
+			/*
+			 * If there has already been a parallel query executed, the sequential mode
+			 * would still use the already opened parallel connections to the workers,
+			 * thus contradicting our purpose of using sequential mode.
+			 */
+			ereport(ERROR, (errmsg(
```
Comment (hanefi) [inline src/backend/distributed/commands/alter_table.c:1623]: I should add a test to cover this line.

File: src/backend/distributed/commands/alter_table.c [hunk 5]
```diff
@@ -511,6 +512,10 @@ ConvertTable(TableConversionState *con)
 	bool oldEnableLocalReferenceForeignKeys = EnableLocalReferenceForeignKeys;
 	SetLocalEnableLocalReferenceForeignKeys(false);
 
+	/* Switch to sequential execution if shard names will be too long */
```
Comment (onderkalaci) [inline src/backend/distributed/commands/alter_table.c:515]: minor: single line comments typically start with lower case

File: src/backend/distributed/commands/alter_table.c [hunk 6]
```diff
@@ -1572,3 +1577,67 @@ ExecuteQueryViaSPI(char *query, int SPIOK)
...
+	if (!IsCitusTable(relationId))
+	{
+		return;
+	}
+
+	char *longestShardName = NULL;
+	if (PartitionedTable(relationId))
+	{
+		/* we may not have any partitions yet, and the function will return NULL in that case */
+		longestShardName = LongestPartitionName(relationId);
```
Comment (onderkalaci) [inline src/backend/distributed/commands/alter_table.c:1603]: I find it confusing to use `longestShardName ` as the output of `LongestPartitionName `, which returns a table. Can we use an intermediate variable like `longestRelationName` or such? Or, even an helper function which calculates `longestShardName ` would be easier to follow, where we still use the intermediate variables to distinguish shards vs tables

File: src/test/regress/expected/alter_distributed_table.out [hunk 7]
```diff
@@ -837,5 +837,35 @@ SELECT * FROM mat_view ORDER BY a;
  2 | 2
 (2 rows)
 
+-- test long table names
+SET client_min_messages TO DEBUG1;
```
Comment (onderkalaci) [inline src/test/regress/expected/alter_distributed_table.out:841]: given that we touch partitioned tables in the code, can you add tests for it as well? Also, for simple RENAME command as well

File: src/backend/distributed/commands/alter_table.c [hunk 8]
```diff
@@ -1572,3 +1577,67 @@ ExecuteQueryViaSPI(char *query, int SPIOK)
...
+	}
+
+	if (longestShardName == NULL)
+	{
+		longestShardName = pstrdup(relationName);
+	}
+
+	ShardInterval *shardInterval = LoadShardIntervalWithLongestShardName(relationId);
```
Comment (onderkalaci) [inline src/backend/distributed/commands/alter_table.c:1611]: If this is a partitioned table, should we use the `relationId` of the child table? I guess this part might be broken for `GenerateLongestShardPartitionIndexName` as well.


I guess `LongestPartitionName` should probably be changed to return the `longestPartitionRelationId` and the callers should use that?

File: src/backend/distributed/commands/alter_table.c (hunk 2 above)
Comment (onderkalaci) [reply src/backend/distributed/commands/alter_table.c]: > So it's ok to skip partitioned tables with no partitions in SwitchToSequentialAndLocalExecutionIfIndexNameTooLong.

This function seems to ignores the check if there are no partitions:

```C
	if (longestPartitionName == NULL)
	{
		/* no partitions have been created yet */
		return NULL;
	}
```

So, I guess you are right, but worth adding a regression test

File: src/backend/distributed/commands/rename.c (hunk 1 above)
Comment (hanefi) [reply src/backend/distributed/commands/rename.c:114]: After some testing, I added `OBJECT_FOREIGN_TABLE` support here. Also added some tests using `fake_fdw`

File: src/backend/distributed/commands/alter_table.c (hunk 2 above)
Comment (hanefi) [reply src/backend/distributed/commands/alter_table.c:1618]: I no longer skip partitioned tables with no partitions.

All distributed tables check their longest shard name lengths, and in case it is a partitioned table then we check the names of the partition shards.

Overall, I think the tests cover this scenario, and I no longer need to add a test for a partitioned table with no partitions. Do you agree @onderkalaci? 

Note that this logic is partially broken for index statements, but I did not fix it here. Maybe I should create an issue for that.

File: src/backend/distributed/commands/alter_table.c (hunk 6 above)
Comment (hanefi) [reply src/backend/distributed/commands/alter_table.c]: I ended up with `GetLongestShardName` and `PartitionWithLongestNameRelationId`

Does it look good?

File: src/test/regress/expected/alter_distributed_table.out (hunk 7 above)
Comment (hanefi) [reply src/test/regress/expected/alter_distributed_table.out:841]: done and done

File: src/backend/distributed/commands/alter_table.c (hunk 8 above)
Comment (hanefi) [reply src/backend/distributed/commands/alter_table.c]: I think it was clearer to name the function `PartitionWithLongestNameRelationId`. I went with this name

File: src/backend/distributed/commands/alter_table.c [hunk 9]
```diff
@@ -1572,3 +1580,95 @@ ExecuteQueryViaSPI(char *query, int SPIOK)
...
+
+/*
+ * SwitchToSequentialAndLocalExecutionIfRelationNameTooLong generates the longest shard name
+ * on the shards of a distributed table, and if exceeds the limit switches to sequential and
+ * local execution to prevent self-deadlocks.
+ *
+ * In case of a RENAME, the relation name parameter should store the new table name, so
+ * that the function can generate shard names of the renamed relations
+ */
+void
```
Comment (onderkalaci) [inline src/backend/distributed/commands/alter_table.c:1593]: An API that gets both the `relationId` and `relationName` feels confusing -- but not easy to avoid, I can see that/

So, maybe at least can we call it `finalRelationName ` / `newRelationName` or such to indicate that this may not be the name of the input relationId?

File: src/test/regress/expected/multi_name_lengths.out [hunk 10]
```diff
@@ -125,12 +125,69 @@ SELECT "Constraint", "Definition" FROM table_checks WHERE relid='public.name_len
...
+-- verify that we can rename partitioned tables and partitions with too-long names
+ALTER TABLE partition_lengths_12345678901234567890123456789012345678901234567890 RENAME TO partition_lengths;
+NOTICE:  identifier "partition_lengths_12345678901234567890123456789012345678901234567890" will be truncated to "partition_lengths_123456789012345678901234567890123456789012345"
+-- Placeholders for unsupported operations
+\set VERBOSITY TERSE
+-- renaming distributed table constraints are not supported
 ALTER TABLE name_lengths RENAME CONSTRAINT unique_12345678901234567890123456789012345678901234567890 TO unique2_12345678901234567890123456789012345678901234567890;
 ERROR:  renaming constraints belonging to distributed tables is currently unsupported
+-- renaming distributed table partitions are not supported
+ALTER TABLE partition_lengths_p2020_09_28 RENAME TO partition_lengths_p2020_09_28_12345678901234567890123456789012345678901234567890;
```
Comment (onderkalaci) [inline src/test/regress/expected/multi_name_lengths.out:174]: Should we create these tables with replication factor == 1, in that case it should be supported?

File: src/test/regress/expected/multi_name_lengths.out [hunk 11]
```diff
@@ -125,12 +125,69 @@ SELECT "Constraint", "Definition" FROM table_checks WHERE relid='public.name_len
...
+NOTICE:  identifier "partition_lengths_p2020_09_28_12345678901234567890123456789012345678901234567890" will be truncated to "partition_lengths_p2020_09_28_123456789012345678901234567890123"
+ERROR:  modifications on partitions when replication factor is greater than 1 is not supported
+-- creating or attaching new partitions with long names create deadlocks
+CREATE TABLE partition_lengths_p2020_09_29_12345678901234567890123456789012345678901234567890 (LIKE partition_lengths_p2020_09_28);
+NOTICE:  identifier "partition_lengths_p2020_09_29_12345678901234567890123456789012345678901234567890" will be truncated to "partition_lengths_p2020_09_29_123456789012345678901234567890123"
+ALTER TABLE partition_lengths
```
Comment (onderkalaci) [inline src/test/regress/expected/multi_name_lengths.out:180]: I think we should open an issue on this and handle separately (probably for Citus 10 as well) , and for now make the tests:
``
BEGIN;
SET citus...modify_mode = sequential;
.. and the command
```
so that we show at least there is a workaound?

File: src/test/regress/expected/multi_name_lengths.out [hunk 12]
```diff
@@ -125,12 +125,69 @@ SELECT "Constraint", "Definition" FROM table_checks WHERE relid='public.name_len
...
 
 \c - - :master_host :master_port
--- Placeholders for RENAME operations
-\set VERBOSITY TERSE
+-- Rename the table to a too-long name
+SET client_min_messages TO DEBUG1;
+SET citus.force_max_query_parallelization TO ON;
+ALTER TABLE name_lengths RENAME TO name_len_12345678901234567890123456789012345678901234567890;
+DEBUG:  the name of the shard (name_len_12345678901234567890123456789012345678_fcd8ab6f_xxxxx) for relation (name_len_12345678901234567890123456789012345678901234567890) is too long, switching to sequential and local execution mode to prevent self deadlocks
+ALTER TABLE name_len_12345678901234567890123456789012345678901234567890 RENAME TO name_lengths;
```
Comment (onderkalaci) [inline src/test/regress/expected/multi_name_lengths.out:133]: I think it might be good to have `SELECT * FROM ....` so that we make sure that all the shards are in a good shape as well

File: src/test/regress/expected/multi_name_lengths.out [hunk 13]
```diff
@@ -209,18 +266,13 @@ SELECT master_create_worker_shards('sneaky_name_lengths', '2', '2');
 
 \c - - :public_worker_1_host :worker_1_port
 \di public.sneaky*225006
-                                                    List of relations
- Schema |                              Name                               | Type  |  Owner   |           Table
+          List of relations
```
Comment (onderkalaci) [inline src/test/regress/expected/multi_name_lengths.out:269]: Hmm, why these tests changed? I couldn't follow

File: src/backend/distributed/utils/shard_utils.c [hunk 14]
```diff
@@ -36,3 +37,21 @@ GetTableLocalShardOid(Oid citusTableOid, uint64 shardId)
...
+
+/*
+ * GetLongestShardName is a utility function that returns the name of the shard of a
+ * table that has the longest name in terms of number of characters.
+ *
+ * Both the Oid and name of the table are required so we can create longest shard names
+ * after a RENAME.
+ */
+char *
+GetLongestShardName(Oid citusTableOid, char *citusTableName)
```
Comment (onderkalaci) [inline src/backend/distributed/utils/shard_utils.c:50]: Again, for this function to get both the `citusTableOid ` and `citusTableName ` is confusing as one normally would expect `citusTableName= get_rel_name(citusTableOid) `. Can we call this `finalCitusTableName` or such?

File: src/backend/distributed/commands/alter_table.c (hunk 2 above)
Comment (onderkalaci) [reply src/backend/distributed/commands/alter_table.c:1618]: > Note that this logic is partially broken for index statements, but I did not fix it here. Maybe I should create an issue for that.


yes, please open an issue and we may want to fix it before Citus 10. Should be a quick fix on top of this?

File: src/test/regress/expected/alter_table_set_access_method.out [hunk 15]
```diff
@@ -681,6 +681,40 @@ CREATE TABLE identity_cols_test (a int, b int generated by default as identity (
...
+NOTICE:  Dropping the old alter_table_set_access_method.abcde_012345678901234567890123456789012345678901234567890123456
+CONTEXT:  SQL statement "DROP TABLE alter_table_set_access_method.abcde_012345678901234567890123456789012345678901234567890123456 CASCADE"
+CONTEXT:  SQL statement "SELECT citus_drop_all_shards(v_obj.objid, v_obj.schema_name, v_obj.object_name)"
+PL/pgSQL function citus_drop_trigger() line 16 at PERFORM
+SQL statement "DROP TABLE alter_table_set_access_method.abcde_012345678901234567890123456789012345678901234567890123456 CASCADE"
+NOTICE:  Renaming the new table to alter_table_set_access_method.abcde_012345678901234567890123456789012345678901234567890123456
+DEBUG:  the name of the shard (abcde_01234567890123456789012345678901234567890_f7ff6612_xxxxxx) for relation (abcde_012345678901234567890123456789012345678901234567890123456) is too long, switching to sequential and local execution mode to prevent self deadlocks
+CONTEXT:  SQL statement "ALTER TABLE alter_table_set_access_method.abcde_0123456789012345678901234567890123456_f7ff6612_4160710162 RENAME TO abcde_012345678901234567890123456789012345678901234567890123456"
+ alter_table_set_access_method
```
Comment (onderkalaci) [inline src/test/regress/expected/alter_table_set_access_method.out:712]: Again, if we can do `SELECT * FROM table xxx` we can ensure that shards are in a good shape.

**Review by onderkalaci — COMMENTED** [review]
This looks good, mostly minor stuff. We are probably doing the last iteration

File: src/test/regress/expected/multi_name_lengths.out (hunk 13 above)
Comment (hanefi) [reply src/test/regress/expected/multi_name_lengths.out:269]: Now that I added more queries in this sql file, it appears that the shardId values are now different.
I should update many shardId occurences to keep the outputs the same as before.

File: src/backend/distributed/commands/alter_table.c (hunk 9 above)
Comment (hanefi) [reply src/backend/distributed/commands/alter_table.c:1593]: I changed all occurences with `finalRelationName`. This is a n effective way to prevent potential confusions. Thanks for pointing it out

File: src/test/regress/expected/alter_table_set_access_method.out (hunk 15 above)
Comment (hanefi) [reply src/test/regress/expected/alter_table_set_access_method.out:712]: Done

File: src/test/regress/expected/multi_name_lengths.out (hunk 12 above)
Comment (hanefi) [reply src/test/regress/expected/multi_name_lengths.out:138]: done

File: src/test/regress/expected/multi_name_lengths.out (hunk 10 above)
Comment (hanefi) [reply src/test/regress/expected/multi_name_lengths.out:182]: I removed the test cases where replication factor > 1

File: src/test/regress/expected/multi_name_lengths.out (hunk 11 above)
Comment (hanefi) [reply src/test/regress/expected/multi_name_lengths.out:188]: added workarounds in sequential mode transaction blocks

File: src/test/regress/expected/multi_index_statements.out [hunk 16]
```diff
@@ -357,13 +357,13 @@ SET client_min_messages TO DEBUG1;
 CREATE INDEX ix_test_index_creation2
     ON test_index_creation1 USING btree
     (tenant_id, timeperiod);
-DEBUG:  the index name on the shards of the partition is too long, switching to sequential and local execution mode to prevent self deadlocks: test_index_creation1_p2020_09_26_10311_tenant_id_timeperiod_idx
```
Comment (hanefi) [inline src/test/regress/expected/multi_index_statements.out:360]: I don't like the these changing debug messages.

We should normalize the outputs here. Should I do that here @onderkalaci ?

File: src/test/regress/expected/multi_name_lengths.out [hunk 17]
```diff
@@ -125,12 +125,96 @@ SELECT "Constraint", "Definition" FROM table_checks WHERE relid='public.name_len
...
+NOTICE:  identifier "partition_lengths_12345678901234567890123456789012345678901234567890" will be truncated to "partition_lengths_123456789012345678901234567890123456789012345"
+-- verify that we can rename partitioned tables and partitions with too-long names
+ALTER TABLE partition_lengths_12345678901234567890123456789012345678901234567890 RENAME TO partition_lengths;
+NOTICE:  identifier "partition_lengths_12345678901234567890123456789012345678901234567890" will be truncated to "partition_lengths_123456789012345678901234567890123456789012345"
+-- Placeholders for unsupported operations
+\set VERBOSITY TERSE
+-- renaming distributed table partitions are not supported
+ALTER TABLE partition_lengths_p2020_09_28 RENAME TO partition_lengths_p2020_09_28_12345678901234567890123456789012345678901234567890;
+NOTICE:  identifier "partition_lengths_p2020_09_28_12345678901234567890123456789012345678901234567890" will be truncated to "partition_lengths_p2020_09_28_123456789012345678901234567890123"
+ERROR:  modifications on partitions when replication factor is greater than 1 is not supported
```
Comment (hanefi) [inline src/test/regress/expected/multi_name_lengths.out:184]: I am not sure why we see a replication factor greater than 1 here.

File: src/backend/distributed/commands/alter_table.c (hunk 2 above)
Comment (hanefi) [reply src/backend/distributed/commands/alter_table.c:1618]: https://github.com/citusdata/citus/issues/4736

File: src/backend/distributed/commands/alter_table.c [hunk 18]
```diff
@@ -1572,3 +1580,95 @@ ExecuteQueryViaSPI(char *query, int SPIOK)
...
+SwitchToSequentialAndLocalExecutionIfRelationNameTooLong(Oid relationId,
+														 char *finalRelationName)
+{
+	if (!IsCitusTable(relationId))
+	{
+		return;
+	}
+
+	char *longestShardName = GetLongestShardName(relationId, finalRelationName);
```
Comment (onderkalaci) [inline src/backend/distributed/commands/alter_table.c:1602]: This fails for zero shard tables, we should fix it:
```SQL
create table test (a int);
select create_distributed_table('test', 'a', 'append');
 alter table test rename to aaaaaa111111111aaaaaa111111111aaaaaa111111111aaaaaa111111111aaaaaa111111111aaaaaa111111111aaaaaa111111111aaaaaa111111111aaaaaa111111111aaaaaa111111111aaaaaa111111111l;
NOTICE:  identifier "aaaaaa111111111aaaaaa111111111aaaaaa111111111aaaaaa111111111aaaaaa111111111aaaaaa111111111aaaaaa111111111aaaaaa111111111aaaaaa111111111aaaaaa111111111aaaaaa111111111l" will be truncated to "aaaaaa111111111aaaaaa111111111aaaaaa111111111aaaaaa111111111aaa"
ERROR:  could not find valid entry for shard 0
```

Check `SwitchToSequentialAndLocalExecutionIfIndexNameTooLong` for an example, and please add regression tests for both rename and create index. Thanks

File: src/test/regress/sql/multi_name_lengths.sql [hunk 19]
```diff
@@ -84,13 +84,89 @@ ALTER TABLE name_lengths ADD CONSTRAINT nl_checky_123456789012345678901234567890
...
+SELECT * FROM name_len_12345678901234567890123456789012345678901234567890;
+ALTER TABLE name_len_12345678901234567890123456789012345678901234567890 RENAME TO name_lengths;
+SELECT * FROM name_lengths;
+
+-- Test renames on zero shard distributed tables
+CREATE TABLE append_zero_shard_table (a int);
+SELECT create_distributed_table('append_zero_shard_table', 'a', 'append');
+ALTER TABLE append_zero_shard_table rename TO append_zero_shard_table_12345678901234567890123456789012345678901234567890;
+
+
```
Comment (marcocitus) [inline src/test/regress/sql/multi_name_lengths.sql:100]: worth adding an ALTER INDEX .. RENAME TO test with a long name.

**Review by onderkalaci — APPROVED** [review]
