### PR TITLE
GetConnParams: Set runtimeParamStart before setting keywords/values to avoid out of bounds access

### LINKED ISSUE #3716: Crash while accessing to the `ConnParamsHashEntry`
```
#0  FreeConnParamsHashEntryFields (entry=0x2099298) at connection/connection_management.c:1034
#1  StartConnectionEstablishment (key=0x7ffdc2d2b8c0) at connection/connection_management.c:972
#2  StartNodeUserDatabaseConnection (flags=flags@entry=12, hostname=hostname@entry=0x58949f0 "10.0.0.175", port=port@entry=5432, user=user@entry=0x58933a8 "citus",
    database=database@entry=0x0) at connection/connection_management.c:324
#3  0x00007f596d30fe32 in StartPlacementListConnection (flags=12, placementAccessList=0x58941c0, userName=userName@entry=0x58933a8 "citus") at connection/placement_connection.c:293
#4  0x00007f596d30ff84 in StartPlacementConnection (flags=<optimized out>, placement=placement@entry=0x5894960, userName=userName@entry=0x58933a8 "citus")
    at connection/placement_connection.c:256
#5  0x00007f596d30ffa6 in GetPlacementConnection (flags=<optimized out>, placement=placement@entry=0x5894960, userName=userName@entry=0x58933a8 "citus")
    at connection/placement_connection.c:209
#6  0x00007f596d304f4a in CopyGetPlacementConnection (stopOnFailure=false, placement=0x5894960) at commands/multi_copy.c:3035
#7  InitializeCopyShardState (stopOnFailure=false, shardId=<optimized out>, connectionStateHash=0x1fe8f70, shardState=0x5193b88) at commands/multi_copy.c:2945
#8  GetShardState (found=0x7ffdc2d2bb92, stopOnFailure=false, connectionStateHash=<optimized out>, shardStateHash=<optimized out>, shardId=6589138) at commands/multi_copy.c:2903
#9  CitusSendTupleToPlacements (copyDest=0x1fc5558, slot=0x1fc4948) at commands/multi_copy.c:2186
---Type <return> to continue, or q <return> to quit---
#10 CitusCopyDestReceiverReceive (slot=0x1fc4948, dest=0x1fc5558) at commands/multi_copy.c:2133
#11 0x00007f596d306153 in CopyToExistingShards (completionTag=<optimized out>, copyStatement=<optimized out>) at commands/multi_copy.c:559
#12 CitusCopyFrom (completionTag=<optimized out>, copyStatement=<optimized out>) at commands/multi_copy.c:325
#13 ProcessCopyStmt (copyStatement=<optimized out>, completionTag=completionTag@entry=0x7ffdc2d2c580 "",
    queryString=queryString@entry=0x1da8440 "COPY XXXXXXXX FROM STDIN with (delimiter '|', NULL '')") at commands/multi_copy.c:2575
#14 0x00007f596d30c7b4 in multi_ProcessUtility (pstmt=0x1da9170, queryString=0x1da8440 "COPY XXXXXXXX FROM STDIN with (delimiter '|', NULL '')",
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x1da9430, completionTag=0x7ffdc2d2c580 "") at commands/utility_hook.c:335
#15 0x00007f5967f9ef4a in pgss_ProcessUtility (pstmt=0x1da9170, queryString=0x1da8440 "COPY XXXXXXXX FROM STDIN with (delimiter '|', NULL '')",
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x1da9430, completionTag=0x7ffdc2d2c580 "") at pg_stat_statements.c:1045
#16 0x000000000074f9e5 in PortalRunUtility (portal=0x1eb5990, pstmt=0x1da9170, isTopLevel=<optimized out>, setHoldSnapshot=<optimized out>, dest=0x1da9430, completionTag=0x7ffdc2d2c580 "")
    at pquery.c:1178
#17 0x0000000000750477 in PortalRunMulti (portal=portal@entry=0x1eb5990, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x1da9430,
    altdest=altdest@entry=0x1da9430, completionTag=completionTag@entry=0x7ffdc2d2c580 "") at pquery.c:1331
---Type <return> to continue, or q <return> to quit---
#18 0x0000000000751060 in PortalRun (portal=portal@entry=0x1eb5990, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true,
    dest=dest@entry=0x1da9430, altdest=altdest@entry=0x1da9430, completionTag=0x7ffdc2d2c580 "") at pquery.c:799
#19 0x000000000074ce94 in exec_simple_query (query_string=0x1da8440 "COPY XXXXXXXX FROM STDIN with (delimiter '|', NULL '')") at postgres.c:1152
#20 0x000000000074e3dc in PostgresMain (argc=<optimized out>, argv=argv@entry=0x1e5af08, dbname=0x1e5ae68 "citus", username=<optimized out>) at postgres.c:4304
#21 0x0000000000480f44 in BackendRun (port=0x1e42e30) at postmaster.c:6036
#22 BackendStartup (port=0x1e42e30) at postmaster.c:5665
#23 ServerLoop () at postmaster.c:2432
#24 0x00000000006ded1d in PostmasterMain (argc=argc@entry=3, argv=argv@entry=0x1da3040) at postmaster.c:1843
#25 0x0000000000481eeb in main (argc=3, argv=0x1da3040) at main.c:240
```

Reported by a user.

### PR DESCRIPTION
**Pull request by serprex**
Not sure how to test this, if someone could get JIT access to the VM this segfault happened on maybe they could check the coredump. I cannot JIT

Fixes #3716

### CODE REVIEW

File: src/backend/distributed/connection/connection_management.c [hunk 1]
```diff
@@ -995,6 +995,13 @@ StartConnectionEstablishment(ConnectionHashKey *key)
 	ConnParamsHashEntry *entry = hash_search(ConnParamsHash, key, HASH_ENTER, &found);
 	if (!found || !entry->isValid)
 	{
+		if (!found)
```
Comment (serprex) [inline src/backend/distributed/connection/connection_management.c:998]: If `MemoryContextAllocZero` throws an error we don't want the next lookup to call `FreeConnParamsHashEntryFields` with potentially random pointers

Comment (marcocitus) [reply src/backend/distributed/connection/connection_management.c:998]: Can you put that into a comment?

File: src/backend/distributed/connection/connection_management.c [hunk 2]
```diff
@@ -1043,9 +1050,6 @@ StartConnectionEstablishment(ConnectionHashKey *key)
 static void
 FreeConnParamsHashEntryFields(ConnParamsHashEntry *entry)
 {
-	char **keyword = NULL;
```
Comment (marcocitus) [inline src/backend/distributed/connection/connection_management.c:1046]: We should probably also reset the size in this function. It's not really necessary anymore after the other fixes, but it seems like a sane thing to do given that we do set keywords and values to NULL.
