### PR TITLE
Fix join pruning performance

### LINKED ISSUE #607: (Co-located) join pruning performance issues
With
```
DROP TABLE IF EXISTS a;
DROP TABLE IF EXISTS b;

CREATE TABLE a(category_id int NOT NULL, data text NOT NULL);
CREATE TABLE b(category_id int NOT NULL, data text NOT NULL);

SELECT master_create_distributed_table('a', 'category_id', 'hash');
SELECT master_create_distributed_table('b', 'category_id', 'hash');

SELECT master_create_worker_shards('a', 512, 1);
SELECT master_create_worker_shards('b', 512, 1);
```

planning
```
SELECT * FROM a JOIN b USING(category_id);
```

takes
```
Time: 8764.395 ms
```

While we can make actual algorithmic improvements to get away from this being an ```O(n^2)``` (or worse) algorithm, the constants here are quite big.  The biggest issue is the function lookup in ShardIntervalsOverlap(), the second biggest the loading of shard intervals in FragmentInterval().

### PR DESCRIPTION
**Pull request by anarazel**
@sumedhpathak @ozgune Could either of you review this soon-ish? Or assign somebody to do that? I think both fixes are fairly simple, the first being nearly trivial.

The first commit gets plan time for the query in issue #607 goes from 8764 ms to 2889 ms, the second from 2889 ms to 106 ms.

Fixes #607

### CODE REVIEW

File: src/backend/distributed/planner/multi_physical_planner.c [hunk 1]
```diff
@@ -3677,22 +3679,26 @@ UniqueFragmentList(List *fragmentList)
...
+		shardInterval = (ShardInterval *) fragment->fragmentReference;
 
 		foreach(uniqueFragmentCell, uniqueFragmentList)
 		{
 			RangeTableFragment *uniqueFragment =
 				(RangeTableFragment *) lfirst(uniqueFragmentCell);
-			uint64 *uniqueShardId = uniqueFragment->fragmentReference;
+			ShardInterval *uniqueShardInterval = NULL;
+
+			Assert(CitusIsA(uniqueFragment->fragmentReference, ShardInterval));
```
Comment (sumedhpathak) [inline src/backend/distributed/planner/multi_physical_planner.c]: The unique list is empty, and we only add ``CITUS_RTE_RELATION`` type fragments. We don't assert for CITUS_RTE_RELATION, so worth removing this assert?

Comment (anarazel) [inline src/backend/distributed/planner/multi_physical_planner.c]: I added most of these because I thought it'd be possible that there's some in development code out there that passes around uint64*'s and these asserts will catch that.

File: src/backend/distributed/planner/multi_physical_planner.c [hunk 2]
```diff
@@ -3725,12 +3730,13 @@ DataFetchTaskList(uint64 jobId, uint32 taskIdIndex, List *fragmentList)
 		RangeTableFragment *fragment = (RangeTableFragment *) lfirst(fragmentCell);
 		if (fragment->fragmentType == CITUS_RTE_RELATION)
 		{
-			uint64 *shardId = fragment->fragmentReference;
-			StringInfo shardFetchQueryString = ShardFetchQueryString(*shardId);
+			ShardInterval *shardInterval = fragment->fragmentReference;
```
Comment (sumedhpathak) [inline src/backend/distributed/planner/multi_physical_planner.c]: Worth adding an assert for IsA(shardInterval) here and at Line 3969?

File: src/backend/distributed/planner/multi_physical_planner.c (hunk 1 above)
Comment (sumedhpathak) [inline src/backend/distributed/planner/multi_physical_planner.c]: The list is populated only within this function. So the assert on line 3690 should be sufficient. However, its not a big deal.

**Comment by sumedhpathak** [comment]
Looks good. Evaluate my assert comments as you deem fit. Otherwise 🚢

**Comment by sumedhpathak** [comment]
Also tested it locally and ran regressions.

File: src/backend/distributed/planner/multi_physical_planner.c (hunk 1 above)
Comment (anarazel) [inline src/backend/distributed/planner/multi_physical_planner.c]: Ok, yea, that makes sense. No point in repeatedly checking.

File: src/backend/distributed/planner/multi_physical_planner.c (hunk 2 above)
Comment (anarazel) [inline src/backend/distributed/planner/multi_physical_planner.c]: I've not done it, because it makes the diff a lot bigger (as one should assert before assigning) ;)
