### PR TITLE
Dropped columns do not diverge distribution column for partitioned tables

### LINKED ISSUE #5123: Partitions of a distributed table get distributed by wrong column after columns drop
### Steps to reproduce:
1. Execute the following SQL:
```sql
CREATE FUNCTION create_month_long_partitions(root_schema CHARACTER VARYING, root_table CHARACTER VARYING,
                                             start_date DATE, end_date DATE) RETURNS VOID
    LANGUAGE plpgsql
AS
$$
DECLARE
    partition_full_name  VARCHAR;
    root_table_full_name VARCHAR;
    d                    DATE;
BEGIN
    FOR d IN SELECT GENERATE_SERIES(DATE_TRUNC('MONTH', start_date),
                                    DATE_TRUNC('MONTH', end_date),
                                    '1 MONTH'::INTERVAL)
        LOOP
            SELECT FORMAT('%I.%I', root_schema, root_table || '_' || TO_CHAR(d, 'YYYY_MON')) INTO partition_full_name;
            SELECT FORMAT('%I.%I', root_schema, root_table) INTO root_table_full_name;
            PERFORM vizor_admin.create_distributed_table_if_not_exists(
                    FORMAT(
                            $str$ CREATE TABLE IF NOT EXISTS %s PARTITION OF %s FOR VALUES FROM ('%sZ') TO ('%sZ')$str$,
                            partition_full_name, root_table_full_name, d, d + '1 MONTH'::INTERVAL));
        END LOOP;
END
$$;

CREATE TABLE t
(
    attributed_touch_type       VARCHAR,
    attributed_touch_time       TIMESTAMP WITH TIME ZONE,
    install_time                TIMESTAMP WITH TIME ZONE,
    event_time                  TIMESTAMP WITH TIME ZONE,
    event_name                  VARCHAR,
    event_value                 VARCHAR,
    event_revenue               NUMERIC,
    event_revenue_currency      VARCHAR,
    event_revenue_usd           NUMERIC,
    event_source                VARCHAR,
    is_receipt_validated        BOOLEAN,
    partner                     VARCHAR,
    media_source                VARCHAR,
    channel                     VARCHAR,
    keywords                    VARCHAR,
    campaign_name               VARCHAR,
    campaign_id                 VARCHAR,
    adset_name                  VARCHAR,
    adset_id                    VARCHAR,
    ad_name                     VARCHAR,
    ad_id                       VARCHAR,
    ad_type                     VARCHAR,
    site_id                     VARCHAR,
    sub_site_id                 VARCHAR,
    sub_param_1                 VARCHAR,
    sub_param_2                 VARCHAR,
    sub_param_3                 VARCHAR,
    sub_param_4                 VARCHAR,
    sub_param_5                 VARCHAR,
    cost_model                  VARCHAR,
    cost_value                  NUMERIC,
    cost_currency               VARCHAR,
    contributor_1_partner       VARCHAR,
    contributor_1_media_source  VARCHAR,
    contributor_1_campaign      VARCHAR,
    contributor_1_touch_type    VARCHAR,
    contributor_1_touch_time    TIMESTAMP WITH TIME ZONE,
    contributor_2_partner       VARCHAR,
    contributor_2_media_source  VARCHAR,
    contributor_2_campaign      VARCHAR,
    contributor_2_touch_type    VARCHAR,
    contributor_2_touch_time    TIMESTAMP WITH TIME ZONE,
    contributor_3_partner       VARCHAR,
    contributor_3_media_source  VARCHAR,
    contributor_3_campaign      VARCHAR,
    contributor_3_touch_type    VARCHAR,
    contributor_3_touch_time    TIMESTAMP WITH TIME ZONE,
    region                      VARCHAR,
    country_code                VARCHAR,
    state                       VARCHAR,
    city                        VARCHAR,
    postal_code                 VARCHAR,
    dma                         VARCHAR,
    ip                          VARCHAR,
    wifi                        VARCHAR,
    operator                    VARCHAR,
    carrier                     VARCHAR,
    language                    VARCHAR,
    appsflyer_id                VARCHAR,
    advertising_id              VARCHAR,
    idfa                        VARCHAR,
    android_id                  VARCHAR,
    customer_user_id            VARCHAR,
    imei                        VARCHAR,
    idfv                        VARCHAR,
    platform                    VARCHAR,
    device_type                 VARCHAR,
    os_version                  VARCHAR,
    app_version                 VARCHAR,
    sdk_version                 VARCHAR,
    app_id                      VARCHAR,
    app_name                    VARCHAR,
    bundle_id                   VARCHAR,
    is_retargeting              BOOLEAN,
    retargeting_conversion_type VARCHAR,
    attribution_lookback        VARCHAR,
    reengagement_window         VARCHAR,
    is_primary_attribution      BOOLEAN,
    user_agent                  VARCHAR,
    http_referrer               VARCHAR,
    original_url                VARCHAR,
    event_net_revenue           NUMERIC,
    event_net_revenue_usd       NUMERIC,
    keyword_id                  VARCHAR,
    store_reinstall             VARCHAR,
    oaid                        VARCHAR,
    install_app_store           VARCHAR,
    match_type                  VARCHAR,
    keyword_match_type          VARCHAR,
    contributor_1_match_type    VARCHAR,
    contributor_2_match_type    VARCHAR,
    contributor_3_match_type    VARCHAR,
    deeplink_url                VARCHAR,
    device_category             VARCHAR,
    gp_broadcast_referrer       VARCHAR,
    gp_click_time               TIMESTAMP WITH TIME ZONE,
    gp_install_begin            TIMESTAMP WITH TIME ZONE,
    gp_referrer                 VARCHAR
) PARTITION BY RANGE (event_time);

ALTER TABLE t
    DROP COLUMN sub_param_3,
    DROP COLUMN sub_param_4,
    DROP COLUMN sub_param_5,
    DROP COLUMN contributor_3_partner,
    DROP COLUMN contributor_3_media_source,
    DROP COLUMN contributor_3_campaign,
    DROP COLUMN contributor_3_touch_type,
    DROP COLUMN contributor_3_touch_time,
    DROP COLUMN contributor_3_match_type,
    DROP COLUMN operator,
    DROP COLUMN user_agent,
    DROP COLUMN keyword_id,
    DROP COLUMN oaid,
    DROP COLUMN install_app_store,
    DROP COLUMN gp_broadcast_referrer,
    DROP COLUMN gp_click_time,
    DROP COLUMN gp_install_begin,
    DROP COLUMN gp_referrer;

SELECT create_distributed_table('t', 'appsflyer_id');

SELECT create_month_long_partitions('public', 't', (NOW() - INTERVAL '3 MONTH')::DATE, NOW()::DATE);
```

2. Observe `citus_tables`

### Expected result

```
+------------+-------------------+
|table_name  |distribution_column|
+------------+-------------------+
|t           |appsflyer_id       |
|"t_2021_MAY"|appsflyer_id       |
|"t_2021_JUN"|appsflyer_id       |
|"t_2021_JUL"|appsflyer_id       |
|"t_2021_APR"|appsflyer_id       |
+------------+-------------------+
```

### Actual result

```
+------------+-------------------+
|table_name  |distribution_column|
+------------+-------------------+
|t           |appsflyer_id       |
|"t_2021_MAY"|os_version         |
|"t_2021_JUN"|os_version         |
|"t_2021_JUL"|os_version         |
|"t_2021_APR"|os_version         |
+------------+-------------------+
```

### Environment
Citus version 10.0.4

### PR DESCRIPTION
**Pull request by onderkalaci**
Before this commit, creating a partition after a DROP column
on the parent (position before dist. key) was leading to
partition to have the wrong distribution column.

DESCRIPTION: Fixes a bug that cause partitions to have wrong dist. key after DROP COLUMN

Fixes #5123 

(Still need to address `alter_table_set_access_method` and check if there are any such cases)

### CODE REVIEW

File: src/backend/distributed/commands/create_distributed_table.c [hunk 1]
```diff
@@ -538,7 +538,10 @@ CreateDistributedTable(Oid relationId, Var *distributionColumn, char distributio
 		Oid partitionRelationId = InvalidOid;
 		foreach_oid(partitionRelationId, partitionList)
 		{
-			CreateDistributedTable(partitionRelationId, distributionColumn,
+			Var *partitionDistributionColumn =
```
Comment (onderkalaci) [inline src/backend/distributed/commands/create_distributed_table.c:541]: a nicer approach could have been to use `columnName` in pg_dist_partition. But, (a) that's a breaking change (b) we want to backport this patch at least to 10.0 and could be very challenging to do that

**Comment by onderkalaci** [comment]
I'm planning to backport this including 9.5.x. We may consider to backport even further

File: src/backend/distributed/commands/create_distributed_table.c (hunk 1 above)
Comment (onderkalaci) [reply src/backend/distributed/commands/create_distributed_table.c]: I'll open an issue to fix this later, in a major/breaking release

File: src/test/regress/sql/drop_column_partitioned_table.sql [hunk 2]
```diff
@@ -0,0 +1,187 @@
...
+ALTER TABLE sensors DROP COLUMN col_to_drop_2;
+
+CREATE TABLE sensors_2002(
+col_to_drop_4 date, col_to_drop_3 inet, measureid integer, eventdatetime date, measure_data jsonb,
+PRIMARY KEY (measureid, eventdatetime, measure_data));
+ALTER TABLE sensors ATTACH PARTITION sensors_2002 FOR VALUES FROM ('2002-01-01') TO ('2003-01-01');
+
+-- drop another column before attaching another partition
+-- that is already distributed
+ALTER TABLE sensors DROP COLUMN col_to_drop_3;
```
Comment (thanodnl) [inline src/test/regress/sql/drop_column_partitioned_table.sql:65]: Currently we are _always_ dropping the then current first column. Would it be more interesting to reverse the order of maybe the first two columns to drop to also test with gaps in between?

**Review by thanodnl — COMMENTED** [review]
Changes look ok to me. I need to look a bit into the uses of the `CreateDistributedTableLike`. The `TableConversionState` is almost turing complete ;).

I wonder if there could be other cases where we create tables like an other one with dropped columns where we need to apply a comparable transformation.

**Comment by onderkalaci** [comment]
> Changes look ok to me. I need to look a bit into the uses of the CreateDistributedTableLike. The TableConversionState is almost turing complete ;).

I presume you saw this: https://github.com/citusdata/citus/issues/5137

Tackling that in a separate PR seemed simpler to me

File: src/test/regress/sql/drop_column_partitioned_table.sql (hunk 2 above)
Comment (onderkalaci) [reply src/test/regress/sql/drop_column_partitioned_table.sql]: Is the change what you have in mind?

File: src/backend/distributed/utils/distribution_column.c [hunk 3]
```diff
@@ -115,6 +116,38 @@ column_to_column_name(PG_FUNCTION_ARGS)
...
+							   generate_qualified_relation_name(sourceRelationId))));
+	}
+
+	char *sourceDistributionKeyStr = nodeToString(sourceColumn);
+	char *columnName = ColumnToColumnName(sourceRelationId, sourceDistributionKeyStr);
+	AttrNumber attributeNumberOnTarget = get_attnum(targetRelationId, columnName);
+	Var *targetColumn =
+		makeVar(sourceColumn->varno, attributeNumberOnTarget,
+				sourceColumn->vartype, sourceColumn->vartypmod,
+				sourceColumn->varcollid, sourceColumn->varlevelsup);
```
[the remark this answers is not in the document]
Comment (onderkalaci) [reply src/backend/distributed/utils/distribution_column.c]: I think I like the function returns `Var` so that we can put the details of creating the `Var` in to the function.

I also agree with you to make it more generic. What do you think about the new API?

File: src/backend/distributed/commands/create_distributed_table.c (hunk 1 above)
Comment (thanodnl) [reply src/backend/distributed/commands/create_distributed_table.c]: makes sense

File: src/test/regress/sql/drop_column_partitioned_table.sql (hunk 2 above)
Comment (thanodnl) [reply src/test/regress/sql/drop_column_partitioned_table.sql]: yeah, these are great. I didn't realise you already had a drop before everything else. By not dropping the logically first column I think we might hit more edgecases. Thanks!

**Review by thanodnl — APPROVED** [review]
LGTM

**Comment by onderkalaci** [comment]
cherry picked to 9.5, 10 and and 10.1, including enterprise
