### PR TITLE
Rethrow original concurrent index creation failure message

### LINKED ISSUE #3951: Errors for CREATE INDEX CONCURRENTLY are hard to understand
When you create an index concurrently and an error happens most of the time you will get the same error message irregardless of the error that caused it. The error message looks like:

```sql
ERROR:  CONCURRENTLY-enabled index command failed
DETAIL:  CONCURRENTLY-enabled index commands can fail partially, leaving behind an INVALID index.
HINT:  Use DROP INDEX CONCURRENTLY IF EXISTS to remove the invalid index, then retry the original command.
```

It would be great if this error is only given if we detect the creation failed due to a naming conflict. Maybe even go as far as verifying the index is the same as the one we want to create, and is active. If the index would be the same as the one we wanted to create we can actually just move on without failure as the system will be in a consistent state after the creation finishes.

A user ran into an issue when creating a unique index concurrently on a table. The failure was not due to the index being partially created. Instead the failure was due to a unique constraint violation that the index creation enforces. However the error the user got was the error above resulting in a support ticket.

Instead it would be great to pass the original message for the failure, potentially with a hint that the index might be partially created and could require removal.

Example to reproduce:
```sql
CREATE TABLE t1 (a int, b int);
CREATE TABLE
Time: 7.818 ms

SELECT create_distributed_table('t1','a');
┌──────────────────────────┐
│ create_distributed_table │
├──────────────────────────┤
│                          │
└──────────────────────────┘
(1 row)

Time: 28.010 ms

INSERT INTO t1 VALUES (1,1), (1,2);
INSERT 0 2
Time: 7.711 ms

SELECT * FROM t1;
┌───┬───┐
│ a │ b │
├───┼───┤
│ 1 │ 1 │
│ 1 │ 2 │
└───┴───┘
(2 rows)

Time: 29.419 ms

CREATE UNIQUE INDEX CONCURRENTLY a_is_not_unique ON t1(a);
ERROR:  CONCURRENTLY-enabled index command failed
DETAIL:  CONCURRENTLY-enabled index commands can fail partially, leaving behind an INVALID index.
HINT:  Use DROP INDEX CONCURRENTLY IF EXISTS to remove the invalid index, then retry the original command.
Time: 25.887 ms
```

### PR DESCRIPTION
**Pull request by naisila**
DESCRIPTION: Rethrow original concurrent index creation failure message

I removed the general `ERROR:  CONCURRENTLY-enabled index command failed` and put the original ERROR message when the concurrent index creation fails. I left the hint of removing the invalid index after the failure.

TODO:

- [x] understand the issue better to provide a full solution
- [x] write tests accordingly

Fixes #3951

### CODE REVIEW

**Comment by naisila** [comment]
@SaitTalhaNisanci maybe we can suggest DROP&RETRY in case of a connection error as well
https://github.com/citusdata/citus/blob/master/src/test/regress/expected/failure_create_index_concurrently.out#L31

File: src/backend/distributed/commands/utility_hook.c [hunk 1]
```diff
@@ -731,12 +732,29 @@ ExecuteDistributedDDLJob(DDLJob *ddlJob)
...
-			ereport(ERROR,
-					(errmsg("CONCURRENTLY-enabled index command failed"),
-					 errdetail("CONCURRENTLY-enabled index commands can fail partially, "
-							   "leaving behind an INVALID index."),
-					 errhint("Use DROP INDEX CONCURRENTLY IF EXISTS to remove the "
-							 "invalid index, then retry the original command.")));
+			MemoryContextSwitchTo(savedContext);
+			ErrorData *edata = CopyErrorData();
+
+			/*in concurrent index creation */
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/commands/utility_hook.c:738]: We prefer a single block of /* */ for multi-line comments. I guess the reason is that it is more readable, especially when there are many lines.

/*
 *
 *
 */

File: src/backend/distributed/commands/utility_hook.c [hunk 2]
```diff
@@ -731,12 +732,29 @@ ExecuteDistributedDDLJob(DDLJob *ddlJob)
...
+			/*if a worker index with the same name already exists, prompt to DROP the current index and retry original command */
+			if (edata->sqlerrcode == ERRCODE_DUPLICATE_TABLE)
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/commands/utility_hook.c:740]: nice that we can use the error code instead of string comparison :)

File: src/backend/distributed/commands/utility_hook.c [hunk 3]
```diff
@@ -731,12 +732,29 @@ ExecuteDistributedDDLJob(DDLJob *ddlJob)
...
+			{
+				ereport(ERROR,
+						(errmsg("CONCURRENTLY-enabled index command failed"),
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/commands/utility_hook.c:743]: is there a test that goes into this branch of if?

Comment (naisila) [reply src/backend/distributed/commands/utility_hook.c:743]: Yes it was already there.
https://github.com/citusdata/citus/blob/master/src/test/regress/sql/multi_index_statements.sql#L178

**Comment by SaitTalhaNisanci** [comment]
>@SaitTalhaNisanci maybe we can suggest DROP&RETRY in case of a connection error as well

I am fine either way. I think it might be nice to suggest "drop & retry" since this possibly doesn't require an extra thing from user(For example in case of duplicate data, the duplicate data should be removed otherwise they will always get this error).

One downside of suggesting "drop & retry" is that now there are two reasons to go into branch and when we get this error, we won't know what the reason is.

Maybe for now we can keep the current logic, what do you think?

**Comment by naisila** [comment]
@SaitTalhaNisanci makes sense. The current logic already warns dropping the invalid index and also explains the connection problem - enough for now for the user to tackle the problem.

I would also say that duplicate table error is more likely to be resolved by "drop&retry" than a connection problem, so for now I agree to keep the current logic.

File: src/backend/distributed/commands/utility_hook.c [hunk 4]
```diff
@@ -731,12 +732,32 @@ ExecuteDistributedDDLJob(DDLJob *ddlJob)
 		}
 		PG_CATCH();
 		{
-			ereport(ERROR,
-					(errmsg("CONCURRENTLY-enabled index command failed"),
-					 errdetail("CONCURRENTLY-enabled index commands can fail partially, "
-							   "leaving behind an INVALID index."),
-					 errhint("Use DROP INDEX CONCURRENTLY IF EXISTS to remove the "
-							 "invalid index, then retry the original command.")));
+			MemoryContextSwitchTo(savedContext);
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/commands/utility_hook.c:735]: Maybe add this comment:

/* CopyErrorData() requires (CurrentMemoryContext != ErrorContext) */

File: src/test/regress/sql/failure_create_index_concurrently.sql [hunk 5]
```diff
@@ -81,6 +81,13 @@ SELECT citus.mitmproxy('conn.allow()');
 SELECT * FROM run_command_on_workers($$SELECT count(*) FROM pg_indexes WHERE indexname LIKE 'idx_index_test%' $$)
 WHERE nodeport = :worker_2_proxy_port;
 
+-- test unique concurrent index creation failure when there are duplicates
+CREATE TABLE index_test_2 (a int, b int);
+SELECT create_distributed_table('index_test_2', 'a');
+INSERT INTO index_test_2 VALUES (1, 1), (1, 2);
+CREATE UNIQUE INDEX CONCURRENTLY index_test_2_a_idx ON index_test_2(a);
+DROP INDEX CONCURRENTLY IF EXISTS index_test_2_a_idx;
```
Comment (SaitTalhaNisanci) [inline src/test/regress/sql/failure_create_index_concurrently.sql:89]: It could be nice to remove the duplicate data and retry creating the index to show that it works.

**Review by SaitTalhaNisanci — APPROVED** [review]
