### PR TITLE
Hint users to call "citus_set_coordinator_host" first

### LINKED ISSUE #6423: Should we auto-insert coordinator when pg_dist_node is _not_ empty (to allow create_distributed_table_concurrently) ?
```sql
SELECT * FROM citus_add_node('localhost', 10701);
SELECT * FROM citus_add_node('localhost', 10702);
CREATE TABLE local(a int, b int, primary key (a));

SELECT create_distributed_table_concurrently('local', 'a');
ERROR:  could not find the coordinator node in metadata as it is not added as a worker
CONTEXT:  while executing command on localhost:10700
```

Error is thrown when internally adding local table into metadata. Note that if we didn't have any workers in pg_dist_node, this wouldn't cause an error thanks to InsertCoordinatorIfClusterEmpty(), but it wouldn't help if we added some worker nodes before.

Having a variant of InsertCoordinatorIfClusterEmpty() --such as InsertCoordinatorIfNotAdded()-- for create_distributed_table_concurrently() might make sense, but I'm not sure if that would be right approach, due to the comment written in `InsertCoordinatorIfClusterEmpty()`:
```c
	/* as long as there is a single node, localhost should be ok */
	AddNodeMetadata(LocalHostName, PostPortNumber, &nodeMetadata, &nodeAlreadyExists);
```

This makes me thinking of whether it would always be ok to hardcode "localhost" for coordinator.

### PR DESCRIPTION
**Pull request by onurctirtir**
If an operation requires having coordinator in pg_dist_node and if that is not the case, then we automatically add the coordinator into pg_dist_node if user didn't add any worker nodes yet.

However, if user have already added some worker nodes before, we throw an error. With this commit, we improve the error thrown in that case.

Closes #6423 based on the discussion made there.

### CODE REVIEW

File: src/backend/distributed/operations/worker_node_manager.c [hunk 1]
```diff
@@ -267,8 +267,11 @@ ErrorIfCoordinatorNotAddedAsWorkerNode()
 		return;
 	}
 
-	ereport(ERROR, (errmsg("could not find the coordinator node in "
-						   "metadata as it is not added as a worker")));
+	ereport(ERROR, (errmsg("operation is not allowed when coordinator "
+						   "is not added into metadata"),
+					errhint("Consider running \"SELECT citus_set_coordinator_host"
```
Comment (onderkalaci) [inline src/backend/distributed/operations/worker_node_manager.c:272]: maybe use consistent wording with others:

```
							errhint("Use SELECT citus_set_coordinator_host('<hostname>') "
									"to configure the coordinator hostname")));

```


feel free to add port param as well here as it might be useful
