### PR TITLE
Fixes geqo outer join bug

### LINKED ISSUE #4223: Outer joins may fail if there are more than `geqo_threshold` tables in the query
While working on #4095, I realized that Citus is not treating `geqo_threshold` well.

```SQL
CREATE TABLE dist (a int, b int);

INSERT INTO dist VALUES (1, 1), (2, 2), (3, 3);

SELECT create_distributed_table ('dist', 'a');

SELECT count(*) FROM dist d1 LEFT JOIN dist d2 on d1.a = d2.a LEFT JOIN dist ON (dist.a = d2.a) LIMIT 1;
 count 
-------
     3
(1 row)



set geqo_threshold = 2;


SELECT count(*) FROM dist d1 LEFT JOIN dist d2 on d1.a = d2.a LEFT JOIN dist ON (dist.a = d2.a) LIMIT 1;
SSL SYSCALL error: EOF detected
The connection to the server was lost. Attempting reset: Failed.
Time: 28172.307 ms (00:28.172)
 @:-!> 
 @:-!> 
```

The bt:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
  * frame #0: 0x000000010a619402 postgres`bms_copy(a=0x7f7f7f7f7f7f7f7f) at bitmapset.c:81:9
    frame #1: 0x000000010d02755a citus.so`RelationInfoContainsOnlyRecurringTuples + 26
    frame #2: 0x000000010d026d23 citus.so`DeferredErrorIfUnsupportedRecurringTuplesJoin + 115
    frame #3: 0x000000010d026924 citus.so`DeferErrorIfUnsupportedSubqueryPushdown + 148
    frame #4: 0x000000010d0267dc citus.so`SubqueryMultiNodeTree + 44
    frame #5: 0x000000010d01927a citus.so`MultiLogicalPlanCreate(originalQuery=0x00007ff15f001888, queryTree=0x00007ff15f0019a0, plannerRestrictionContext=0x00007ff15f826710) at multi_logical_planner.c:157:20
    frame #6: 0x000000010d00aeb7 citus.so`CreateDistributedPlan(planId=2, originalQuery=0x00007ff15f001888, query=0x00007ff15f0019a0, boundParams=0x0000000000000000, hasUnresolvedParams=<unavailable>, plannerRestrictionContext=0x00007ff15f826710) at distributed_planner.c:1059:31
    frame #7: 0x000000010d00c03a citus.so`CreateDistributedPlannedStmt(planContext=0x00007ffee57d5f88) at distributed_planner.c:653:3
    frame #8: 0x000000010d00aafe citus.so`PlanDistributedStmt(planContext=0x00007ffee57d5f88, rteIdCounter=<unavailable>) at distributed_planner.c:584:24
    frame #9: 0x000000010d00a785 citus.so`distributed_planner(parse=0x00007ff15f0019a0, query_string=<unavailable>, cursorOptions=<unavailable>, boundParams=<unavailable>) at distributed_planner.c:231:14
    frame #10: 0x000000010d1e6086 pg_stat_statements.so`pgss_planner(parse=0x00007ff15f0019a0, query_string="SELECT count(*) FROM dist d1 LEFT JOIN dist d2 on d1.a = d2.a LEFT JOIN dist ON (dist.a = d2.a) LIMIT 1;", cursorOptions=256, boundParams=0x0000000000000000) at pg_stat_statements.c:988:13
    frame #11: 0x000000010a735c61 postgres`pg_plan_query(querytree=0x00007ff15f0019a0, query_string="SELECT count(*) FROM dist d1 LEFT JOIN dist d2 on d1.a = d2.a LEFT JOIN dist ON (dist.a = d2.a) LIMIT 1;", cursorOptions=256, boundParams=0x0000000000000000) at postgres.c:875:9
    frame #12: 0x000000010a735da2 postgres`pg_plan_queries(querytrees=0x00007ff15f8248b0, query_string="SELECT count(*) FROM dist d1 LEFT JOIN dist d2 on d1.a = d2.a LEFT JOIN dist ON (dist.a = d2.a) LIMIT 1;", cursorOptions=256, boundParams=0x0000000000000000) at postgres.c:966:11
    frame #13: 0x000000010a737b6a postgres`exec_simple_query(query_string="SELECT count(*) FROM dist d1 LEFT JOIN dist d2 on d1.a = d2.a LEFT JOIN dist ON (dist.a = d2.a) LIMIT 1;") at postgres.c:1158:19
    frame #14: 0x000000010a7373be postgres`PostgresMain(argc=<unavailable>, argv=<unavailable>, dbname=<unavailable>, username=<unavailable>) at postgres.c:0
    frame #15: 0x000000010a6bd105 postgres`BackendRun(port=0x0000000000000001) at postmaster.c:4536:2
    frame #16: 0x000000010a6bc9d0 postgres`BackendStartup(port=<unavailable>) at postmaster.c:4220:3
    frame #17: 0x000000010a6bc1a5 postgres`ServerLoop at postmaster.c:1739:7
    frame #18: 0x000000010a6ba3bc postgres`PostmasterMain(argc=3, argv=0x00007ff15dd02960) at postmaster.c:1412:11
    frame #19: 0x000000010a618fa6 postgres`main(argc=3, argv=0x00007ff15dd02960) at main.c:210:3
    frame #20: 0x00007fff638bf3d5 libdyld.dylib`start + 1
```

### PR DESCRIPTION
**Pull request by halilozanakgul**
DESCRIPTION: Fixes geqo outer join bug
Fixes #4223 

The RelOptInfos in joinRestrictionList was getting freed by Postgres. We needed to copy them.
They were only used for their relids field. Now we are only getting that field so we can copy it.

TODO:
- [x]  Add tests

### CODE REVIEW

File: src/backend/distributed/planner/distributed_planner.c [hunk 1]
```diff
@@ -1731,8 +1731,8 @@ multi_join_restriction_hook(PlannerInfo *root,
 	joinRestriction->joinType = jointype;
 	joinRestriction->joinRestrictInfoList = restrictInfoList;
 	joinRestriction->plannerInfo = root;
-	joinRestriction->innerrel = innerrel;
-	joinRestriction->outerrel = outerrel;
+	joinRestriction->innerrelRelids = bms_copy(innerrel->relids);
```
Comment (onderkalaci) [inline src/backend/distributed/planner/distributed_planner.c:1734]: It looks suspicious. We still heavily rely on `plannerInfo` struct. Are we sure that it is not freed as well?

Comment (halilozanakgul) [reply src/backend/distributed/planner/distributed_planner.c:1734]: Good point. I'll look into that. PlannerInfo doesn't look easily copyable as well.

Comment (onderkalaci) [reply src/backend/distributed/planner/distributed_planner.c:1734]: This code-path very critical in the sense that  we rely on it very heavily and it is called multiple times for every single query. 

Can you backtrace the code a bit to have a clear picture on what is happening when `geqo` is on/off? Why do we not get `innerrel/outerrel ` etc?

Also, I think no one experiencing #4223 means that we don't have any users relying on `geqo` at the moment. If the fix is not trivial, we can even consider ignoring `geqo` for the time being?

Comment (thanodnl) [reply src/backend/distributed/planner/distributed_planner.c:1734]: `plannerInfo` I believe is a context struct that is allocated in the root memory context of the planner. geqo creates a new context that gets reset often. The call to this callback gets called with that context during geqo planning. inner and outer rel are set, but by the time we use the pointers the memory had been reset. Where it resets the memory it actually restores a bit of the state in the `plannerInfo` struct to not keep references to the reset memory.

Given this is the join hook I believe both innerrel and outerrel should be set. Would there be any possibility of it not being set? Did we have `NULL` checks where we were reading the relids before? In that case I'd like some `NULL` checks here instead before copying the relids. A `NULL` in relids is a valid bitmap with no bits set.

Comment (onderkalaci) [reply src/backend/distributed/planner/distributed_planner.c:1734]: >  A NULL in relids is a valid bitmap with no bits set.

That's a good point, `bms_is_empty()` returns true if the input bms is NULL.

Comment (onderkalaci) [reply src/backend/distributed/planner/distributed_planner.c:1734]: Flow of the code is as follows:
```
geqo
    geqo_eval
         CreateTempMemoryContext
                multi_join_restriction_hook
                      bms_copy
         DeleteTempMemoryContext
```

So, in a sense, we are copying a value that Postgres no longer considers valid as it deleted the corresponding memory context. 

Still,  we seem to  do the exact same thing for `extra->restrictlist`, and see https://github.com/citusdata/citus/pull/1349 for related discussions.  Given that the fields that we copy are pointing to `root`, we should be OK.


Should we maybe move the  deep copy parts next to each other?


```
diff --git a/src/backend/distributed/planner/distributed_planner.c b/src/backend/distributed/planner/distributed_planner.c
index a075a0f1e..035f2d157 100644
--- a/src/backend/distributed/planner/distributed_planner.c
+++ b/src/backend/distributed/planner/distributed_planner.c
@@ -1716,12 +1716,7 @@ multi_join_restriction_hook(PlannerInfo *root,
        MemoryContext restrictionsMemoryContext = plannerRestrictionContext->memoryContext;
        MemoryContext oldMemoryContext = MemoryContextSwitchTo(restrictionsMemoryContext);
 
-       /*
-        * We create a copy of restrictInfoList because it may be created in a memory
-        * context which will be deleted when we still need it, thus we create a copy
-        * of it in our memory context.
-        */
-       List *restrictInfoList = copyObject(extra->restrictlist);
+
 
        JoinRestrictionContext *joinRestrictionContext =
                plannerRestrictionContext->joinRestrictionContext;
@@ -1729,8 +1724,15 @@ multi_join_restriction_hook(PlannerInfo *root,
 
        JoinRestriction *joinRestriction = palloc0(sizeof(JoinRestriction));
        joinRestriction->joinType = jointype;
-       joinRestriction->joinRestrictInfoList = restrictInfoList;
        joinRestriction->plannerInfo = root;
+
+       /*
+        * We create a copy of restrictInfoList because it may be created in a memory
+        * context which will be deleted when we still need it, thus we create a copy
+        * of it in our memory context.
+        */
+       List *restrictInfoList = copyObject(extra->restrictlist);
+       joinRestriction->joinRestrictInfoList = restrictInfoList;
        joinRestriction->innerrelRelids = bms_copy(innerrel->relids);
        joinRestriction->outerrelRelids = bms_copy(outerrel->relids);

```

Comment (thanodnl) [reply src/backend/distributed/planner/distributed_planner.c:1734]: I think moving the deep copies together and directly assigning them to the struct we keep makes the code more readable. I would suggest, if this doesn't break the line to go even further:

```C
joinRestriction->joinRestrictInfoList = copyObject(extra->restrictlist);
```

I have been fooled by the assignment of the `restrictInfoList` to the struct we keep before, while following the code.

File: src/backend/distributed/planner/distributed_planner.c [hunk 2]
```diff
@@ -1711,23 +1711,24 @@ multi_join_restriction_hook(PlannerInfo *root,
...
-	 * context which will be deleted when we still need it, thus we create a copy
-	 * of it in our memory context.
-	 */
-	List *restrictInfoList = copyObject(extra->restrictlist);
-
 	JoinRestrictionContext *joinRestrictionContext =
 		plannerRestrictionContext->joinRestrictionContext;
 	Assert(joinRestrictionContext != NULL);
 
+	Assert(!bms_is_empty(innerrel->relids) && !bms_is_empty(outerrel->relids));
```
Comment (onderkalaci) [inline src/backend/distributed/planner/distributed_planner.c:1718]: I think we are more and more  leaning towards not having  asserts, but instead have explicit error messages. The idea is that if we overlook something, in the production systems having the error messages much nicer compared to crashes.

For this case, I'd suggest we do something like the following:

```
if (bms_is_empty(innerrel->relids) || bms_is_empty(outerrel->relids))
{
   ereport(DEBUG1, "Join restriction information is NULL ");

   /* we cannot process empty relids, so ignoring the JoinRestriction is preferable over continuing and likely to  segfaulting  */
   return;
}
```

This check should go to the top of the function, definitely before doing `MemoryContextSwitchTo ()`

File: src/backend/distributed/planner/distributed_planner.c [hunk 3]
```diff
@@ -1711,23 +1711,24 @@ multi_join_restriction_hook(PlannerInfo *root,
...
+
 	JoinRestriction *joinRestriction = palloc0(sizeof(JoinRestriction));
 	joinRestriction->joinType = jointype;
-	joinRestriction->joinRestrictInfoList = restrictInfoList;
 	joinRestriction->plannerInfo = root;
-	joinRestriction->innerrel = innerrel;
-	joinRestriction->outerrel = outerrel;
+
+	/*
+	 * We create a copy of restrictInfoList because it may be created in a memory
```
Comment (onderkalaci) [inline src/backend/distributed/planner/distributed_planner.c:1725]: minor: lets also mention that this  could happen with `geqo` and also mention innerrel/outerrel fields as well

File: src/test/regress/sql/join.sql [hunk 4]
```diff
@@ -180,6 +180,13 @@ SELECT * FROM abcd first join abcd second USING(b) join abcd third on first.b=th
...
 
 
+-- test join with geqo
+CREATE TABLE dist (a int, b int);
+SELECT create_distributed_table('dist', 'a');
+INSERT INTO dist VALUES (1, 1), (2, 2), (3, 3);
 
+SET geqo_threshold to 2;
+
+SELECT count(*) FROM dist d1 LEFT JOIN dist d2 ON d1.a = d2.a LEFT JOIN dist d3 ON d3.a = d2.a;
```
Comment (onderkalaci) [inline src/test/regress/sql/join.sql:190]: can we add few more tests to be defensive for future changes? I've not tried running the tests, so please make sure that the comment matches the query type

```SQL
-- JOINs  with CTEs:
WITH cte_1 AS (SELECT  * FROM dist OFFSET 0)  SELECT count(*) FROM dist d1 LEFT JOIN dist d2 ON d1.a = d2.a LEFT JOIN dist d3 ON d3.a = d2.a LEFT JOIN cte_1 ON true;
WITH cte_1 AS (SELECT  * FROM dist OFFSET 0),     
     cte_2 AS (SELECT * FROM dist OFFSET 0),
     cte_3 AS (SELECT * FROM dist OFFSET 0)
 SELECT count(*) FROM cte_1 d1 LEFT JOIN cte_2 d2 ON d1.a = d2.a LEFT JOIN cte_3 d3 ON d3.a = d2.a LEFT JOIN cte_1 ON true;
                                                                               


-- Inner JOIN:
 SELECT count(*) FROM dist d1 JOIN dist d2 ON d1.a = d2.a JOIN dist d3 ON d3.a = d2.a;

-- subquery join
 SELECT count(*) FROM (SELECT *,random() FROM dist) as d1 JOIN (SELECT *,random() FROM  dist) d2 ON d1.a = d2.a JOIN (SELECT *,random() FROM dist) as d3 ON d3.a = d2.a;

 SELECT count(*) FROM (SELECT *,random() FROM dist) as d1 LEFT JOIN (SELECT *,random() FROM  dist) d2 ON d1.a = d2.a LEFT JOIN (SELECT *,random() FROM dist) as d3 ON d3.a = d2.a;

-- router query
SELECT count(*) FROM dist d1 LEFT JOIN dist d2 ON d1.a = d2.a LEFT JOIN dist d3 ON d3.a = d2.a WHERE d1.a = 1 AND d2.a = 1 AND d3.a = 1;

-- fast path router query
SELECT count(*) FROM dist WHERE a = 1;

-- simple INSERT
INSERT INTO dist (a) VALUES (1);

-- repartition join, probably not relevant, but still be defensive
 SELECT count(*) FROM dist d1 JOIN dist d2 ON d1.b = d2.b JOIN dist d3 ON d3.b = d2.b;

-- update query with join
UPDATE dist SET b = foo.a FROM (SELECT d1.a FROM dist d1 JOIN dist d2 USING(a))foo

-- insert select pushdown
INSERT INTO dist
 SELECT d1.* FROM dist d1 JOIN dist d2 ON d1.a = d2.a JOIN dist d3 ON d3.a = d2.a;

-- insert select via coordinator
INSERT INTO dist
 SELECT d1.* FROM dist d1 JOIN dist d2 ON d1.a = d2.a JOIN dist d3 ON d3.a = d2.a OFFSET 0;

-- insert select via repartitioning
 INSERT INTO dist (a)
 SELECT max(d1.b) FROM dist d1 JOIN dist d2 ON d1.a = d2.a JOIN dist d3 ON d3.a = d2.a GROUP BY d1.a;
```

**Review by onderkalaci — COMMENTED** [review]
I think after considering the comments, we are ready to merge. I'd like to have a quick look before approving, and I can comment  on the performance trade-offs that the PR brings when I approve.

File: src/backend/distributed/planner/distributed_planner.c (hunk 2 above)
Comment (onurctirtir) [reply src/backend/distributed/planner/distributed_planner.c:1718]: or should we give an ERROR with ERRCODE_INTERNAL_ERROR instead of a debug message ?:

```c
		ereport(ERROR, (errcode(ERRCODE_INTERNAL_ERROR),
				errmsg("<errorMessage>")));
```

Comment (onderkalaci) [reply src/backend/distributed/planner/distributed_planner.c:1718]: >ereport(ERROR, (errcode(ERRCODE_INTERNAL_ERROR),
				errmsg("<errorMessage>")));

I  think, to be on  the  safe  side, we should probably not throw an error as those hooks are called for local tables. I see your point, we might return wrong results if we don't add (though we used to crash anyway). Still, I have a slight preference for DEBUG over ERROR

File: src/test/regress/sql/join.sql (hunk 4 above)
Comment (onderkalaci) [reply src/test/regress/sql/join.sql:190]: I think it'd even be better if we add a new test file: `geqo.sql`  and push the limits with setting the following at the top:
```SQL
SET geqo_threshold=2;
SET geqo_generations=1000;
SETT geqo_pool_size=1000;
```

File: src/backend/distributed/planner/distributed_planner.c [hunk 5]
```diff
@@ -1702,6 +1702,15 @@ multi_join_restriction_hook(PlannerInfo *root,
 							JoinType jointype,
 							JoinPathExtraData *extra)
 {
+	if (bms_is_empty(innerrel->relids) || bms_is_empty(outerrel->relids))
+	{
+		/*
```
Comment (onderkalaci) [inline src/backend/distributed/planner/distributed_planner.c:1707]: We do not expect empty relids and we cannot process them as well. Still,  ignoring such JoinRestriction is preferable for two reasons. First, this might be a query that doesn't rely on JoinRestrictions at all (e.g., local query). Second, even if we add these restrictions, we cannot process them (and likely to segfault if we allow as-is).

**Review by onderkalaci — COMMENTED** [review]
minor comment improvement suggestion

File: src/backend/distributed/planner/distributed_planner.c (hunk 5 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/distributed_planner.c:1707]: (This is to include @onurctirtir's feedback)

File: src/test/regress/sql/join.sql (hunk 4 above)
Comment (onderkalaci) [reply src/test/regress/sql/join.sql:190]: ping on this.


Also, can you make sure that the  tests pass and the style check is good?

**Review by onderkalaci — APPROVED** [review]
Let me summarize the whole GEQO thread here. Before this patch, Citus failed to process (e.g., crash) quite a lot of queries as the code was accessing RelOpttInfo that is allocated in GEQO memory context and alread de-allocated when Citus uses them. With this patch, we copy the relevant fields to Citus' own memory context, so we avoid crashes.

We have executed all the regression tests and quite a lot complex joins mentioned [here](https://github.com/citusdata/citus/pull/4264#issue-507358736) with GEQO enabled and the geqo pool size is 1000. Everything works fine as expected. One thing to watch out in the future is that, when GEQO kicks in, it may generate way too many JoinRestrictions compared to GEQO disabled. For example, a JOIn that generates ~6000 JoinRestrictions with GEQO disabled, could generate 200,000 JoinRestrictions with GEQO enabled. Thus, distributed planning times might increase as we now need to process a lot more restrict infos most of which are already equivalent. 

In the future, we might consider ignoring GEQO for the distributed query planning purpuses. In fact, it doesn't give anything extra for our purposes. For now, we found that supporting is easy, and we can revisit this decision if needed.
