### PR TITLE
Fix the way we check for local/reference table joins in the executor

### LINKED ISSUE #3279: Cannot drop a column from a reference table on the coordinator
The checks for reference + local table joins might be too aggressive as they can show up in the drop trigger.

```sql
SELECT master_add_node('localhost', 5432, groupid := 0);
CREATE TABLE ref (a int, b int);
SELECT create_reference_table('ref');
ALTER TABLE ref DROP COLUMN z;
ERROR:  cannot join local tables and reference tables in a transaction block
CONTEXT:  while executing command on 127.0.0.1:5432
SQL statement "SELECT master_unmark_object_distributed(v_obj.classid, v_obj.objid, v_obj.objsubid)"
PL/pgSQL function citus_drop_trigger() line 28 at PERFORM
```

```sql
SELECT worker_apply_shard_ddl_command (102040, 'public', 'ALTER TABLE ref DROP COLUMN z;');
ERROR:  cannot join local tables and reference tables in a transaction block
CONTEXT:  SQL statement "SELECT master_unmark_object_distributed(v_obj.classid, v_obj.objid, v_obj.objsubid)"
PL/pgSQL function citus_drop_trigger() line 28 at PERFORM
```

### PR DESCRIPTION
**Pull request by pykello**
Fixes #3279 

Previously we used `plannedStmt->releationOids` which is the set of relations query depends on to check for the relations "involved" in the query. But this is not correct. For example, citus plans query of the following form in the `citus_drop_trigger()` to have `relationOids = [pg_class, reference_table]`, so we assumed it is a join between reference table and local table.

```sql
SELECT master_unmark_object_distributed(v_obj.classid, v_obj.objid, v_obj.objsubid)
```

This PR changes the behaviour to use the range table entries instead.

### CODE REVIEW

File: src/backend/distributed/executor/multi_executor.c [hunk 1]
```diff
@@ -617,12 +617,22 @@ IsLocalReferenceTableJoinPlan(PlannedStmt *plan)
 		return false;
 	}
 
-	foreach(oidCell, plan->relationOids)
+	foreach(rangeTableCell, plan->rtable)
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_executor.c]: Does this contain RTEs for the entire query? (incl. CTEs, subqueries)

File: src/backend/distributed/executor/multi_executor.c [hunk 2]
```diff
@@ -617,12 +617,22 @@ IsLocalReferenceTableJoinPlan(PlannedStmt *plan)
...
 	{
-		Oid relationId = lfirst_oid(oidCell);
+		RangeTblEntry *rangeTableEntry = (RangeTblEntry *) lfirst(rangeTableCell);
 		bool onlySearchPath = false;
 
-		if (RelationIsAKnownShard(relationId, onlySearchPath))
+		if (rangeTableEntry->rtekind == RTE_FUNCTION)
+		{
+			return false;
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_executor.c]: why return false here? What if we a join between a local table, a reference table and a function?

**Comment by marcocitus** [comment]
if I try without any works (just coordinator), I get:
```sql
postgres=# ALTER TABLE ref ADD COLUMN z int;
WARNING:  could not find any shard placements for shardId 102040
... stuck forever
```

**Comment by marcocitus** [comment]
> if I try without any works (just coordinator), I get:

that actually seems to be a separate bug unrelated to having the coordinator in the metadata

File: src/backend/distributed/executor/multi_executor.c (hunk 2 above)
Comment (pykello) [reply src/backend/distributed/executor/multi_executor.c]: To match distributed_planner.c's `IsLocalReferenceTableJoin()`. Joins between local, reference, and functions will error out in planner. We can remove that restriction in both planner and executor, but maybe in another PR.

Removing the check here, although I think it won't change any behaviour.

File: src/backend/distributed/executor/multi_executor.c (hunk 1 above)
Comment (pykello) [reply src/backend/distributed/executor/multi_executor.c]: Yes, standard_planner stores the flattened rte lists in plannedStmt->rtable. `set_plan_references` concatenates all these lists in `glob->finalrtable`, and then standard_planner does `plannedStmt->rtable = glob->finalrtable`.

Added a comment.

**Comment by pykello** [comment]
> > if I try without any works (just coordinator), I get:
> 
> that actually seems to be a separate bug unrelated to having the coordinator in the metadata

I can look into this tomorrow.

File: src/backend/distributed/executor/multi_executor.c [hunk 3]
```diff
@@ -617,12 +617,24 @@ IsLocalReferenceTableJoinPlan(PlannedStmt *plan)
...
+	foreach(rangeTableCell, plan->rtable)
 	{
-		Oid relationId = lfirst_oid(oidCell);
+		RangeTblEntry *rangeTableEntry = (RangeTblEntry *) lfirst(rangeTableCell);
 		bool onlySearchPath = false;
 
-		if (RelationIsAKnownShard(relationId, onlySearchPath))
+		if (rangeTableEntry->rtekind != RTE_RELATION)
+		{
+			continue;
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_executor.c]: Since views are RTE_RELATION they are also treated as local tables.

```sql
CREATE VIEW v AS SELECT * FROM ref WHERE a = 1;
BEGIN;
SELECT * FROM v JOIN ref ON (v.a = ref.a);
ERROR:  cannot join local tables and reference tables in a transaction block, udf block, or distributed CTE subquery
```

Comment (pykello) [reply src/backend/distributed/executor/multi_executor.c]: Fixed + tests. Also added tests and comments for the function join.
