### PR TITLE
Not try to sync metadata for local tables

### LINKED ISSUE #4624: Error when altering access method of local table that owns sequences
```sql
CREATE TABLE local(a int, b bigserial);
select alter_table_set_access_method('local', 'columnar');
NOTICE:  creating a new table for public.local
NOTICE:  Moving the data of public.local
ERROR:  relation local is not distributed
```

```sql
-- but this works fine
CREATE TABLE local(a int, b int);
select alter_table_set_access_method('local', 'columnar');
```

### PR DESCRIPTION
**Pull request by onurctirtir**
Fixes #4624

Since `ReplaceTable` calls `ShouldSyncTableMetadata` when fixing sequence dependencies,
we were erroring out when executing `alter_table_set_access_method` for local tables.

### CODE REVIEW

File: src/backend/distributed/commands/alter_table.c [hunk 1]
```diff
@@ -1138,7 +1138,7 @@ ReplaceTable(Oid sourceId, Oid targetId, List *justBeforeDropCommands,
 	{
 		changeDependencyFor(RelationRelationId, sequenceOid,
 							RelationRelationId, sourceId, targetId);
-		if (ShouldSyncTableMetadata(sourceId))
+		if (IsCitusTable(sourceId) && ShouldSyncTableMetadata(sourceId))
```
Comment (onderkalaci) [inline src/backend/distributed/commands/alter_table.c:1141]: it seems slightly better to move `IsCitusTable(sourceId)` into `ShouldSyncTableMetadata ` and return false?

Like:
```

if (relationId == InvalidOid || !IsCitusTable(relationId))
{

return false;
}

**Review by onderkalaci — APPROVED** [review]
