### PR TITLE
Fix union pushdown issue

### LINKED ISSUE #4144: Issues with views that utilise union all
I'm having lots of trouble with views that utilise "union all". This is the view:

```
CREATE OR REPLACE VIEW rvpezocoav as
SELECT rtpezocoav.id,
    rtpezocoav.ad_id,
    rtpezocoav.pe_id,
    rtpezocoav.zo_id,
    rtpezocoav.co_id,
    rtpezocoav.value_num,
    rtpezocoav.value_text
   FROM rtpezocoav
     JOIN rmv_active_peco act ON act.co_id = rtpezocoav.co_id AND act.pe_id = rtpezocoav.pe_id
UNION ALL
 SELECT av.id,
    av.ad_id,
    rtpe.id AS pe_id,
    av.zo_id,
    av.co_id,
    av.value_num,
    av.value_text
   FROM rtpezocoav av
     JOIN rtpe ON av.pe_id = rtpe.baseline_id
     JOIN rmv_active_peco act ON act.co_id = av.co_id AND act.pe_id = rtpe.id
  WHERE NOT (EXISTS ( SELECT 1
           FROM rtpezocoav av_1
          WHERE av_1.pe_id = rtpe.id AND av_1.zo_id = av.zo_id AND av_1.co_id = av.co_id AND av_1.ad_id = av.ad_id))
```

- rtpezocoav is a distributed table on zo_id
- rmv_active_peco & rtpe are reference tables

The following query fails after a while with the 'intermediate result size exceeds citus.max_intermediate_result_size (currently 1048576 kB)':
```
select count(1) from rvpezocoav where pe_id = 391;
```

I have no idea why we would need to reshuffle data as it's a join between one distributed table and two reference tables.

What I tried and didn't work:
- remove join with rmv_active_peco
- remove where not (exists ...) clause

Only thing that works is changing the union ALL to just a union. No idea why that makes a difference...

But then I end up with the next problem:

```
select count(1)
	from rvpezocoav pezoco
	join rtco co on pezoco.co_id = co.lo_id
	where ad_id = 4
	        and pe_id = 391
	        and lo_id = 505
```
fails with ERROR: complex joins are only supported when all distributed tables are co-located and joined on their distribution columns.

rtco here is also a reference table.

What I tried according to suggestions on slack:

```
 CREATE OR REPLACE VIEW rvpezocoav as
				select * from 
				(
				select * from 
				(
				SELECT rtpezocoav.id,
				    rtpezocoav.ad_id,
				    rtpezocoav.pe_id,
				    rtpezocoav.zo_id,
				    rtpezocoav.co_id,
				    rtpezocoav.value_num,
				    rtpezocoav.value_text
				   FROM rtpezocoav
				     JOIN rmv_active_peco act ON act.co_id = rtpezocoav.co_id AND act.pe_id = rtpezocoav.pe_id
				     offset 0
				    ) as z1
				UNION --ALL  --!!!!!
				 select * from 
				 (
					SELECT av.id,
				    av.ad_id,
				    rtpe.id AS pe_id,
				    av.zo_id,
				    av.co_id,
				    av.value_num,
				    av.value_text
				   FROM rtpezocoav av
				     JOIN rtpe ON av.pe_id = rtpe.baseline_id
				     JOIN rmv_active_peco act ON act.co_id = av.co_id AND act.pe_id = rtpe.id
				  WHERE NOT (EXISTS ( SELECT 1
				           FROM rtpezocoav av_1
				          WHERE av_1.pe_id = rtpe.id AND av_1.zo_id = av.zo_id AND av_1.co_id = av.co_id AND av_1.ad_id = av.ad_id))
				          offset 0
				      ) as z2
				  ) as z;
```

This brings me back to the original problem: ERROR: the intermediate result size exceeds citus.max_intermediate_result_size (currently 1048576 kB)

I've been going in circles trying to make this work for the last few days... This is a real showstopper for us unfortunately.

### LINKED ISSUE #4781: UNION ALL Pushdown doesn't work if there is an aggregate above
Reported by @saicitus:
Below are steps to repro:
```SQL

CREATE TABLE test_a (id int, k int);
CREATE TABLE test_b (id int, k int);
 SELECT create_distributed_table('test_a','id');
SELECT create_distributed_table('test_b','id');

-- Different filters for sub-queries (Need workaround for this case)

CREATE OR REPLACE VIEW v AS SELECT * from test_a where k>1 UNION ALL SELECT * from test_b where k<1;
explain select count(*) from v; -- aggregate not pushed down to workers, recursive planning

CREATE OR REPLACE VIEW v AS (SELECT * from (SELECT * from test_a)a1 where k>1) UNION ALL SELECT * from (SELECT * from test_b)b1 where k<1;
explain select count(*) from v; -- aggregate not pushed down to workers, recursive planning

--Tried a couple of other cases as below and I was able to find workarounds but they are not what the customer has...

-- No filters for sub-queries:

CREATE OR REPLACE VIEW v AS SELECT * from test_a UNION ALL SELECT * from test_b; -- push down occurs
explain select count(*) from v; -- aggregate is pushed down to workers as per explain plan

-- Same filters for sub-queries:

CREATE OR REPLACE VIEW v AS SELECT * from test_a where k<1 UNION ALL SELECT * from test_b where k<1;
explain select count(*) from v; -- aggregate not pushed down to workers, recursive planning

-- Workaround for above
CREATE OR REPLACE VIEW v AS SELECT * from (SELECT * from test_a UNION ALL SELECT * from test_b)a where k<1;
explain select count(*) from v; -- aggregate is pushed down to workers as per explain plan

```

> -- Different filters for sub-queries (Need workaround for this case)

The problem is that Postgres pulls-up the subqueries and Citus' logic becomes broken. The workarounds is to prevent Postgres to pull-up the union subqueries, so that Citus can pushdown the query
There are two workarounds.

1) Use an ORDER BY for the leaves of the UNION ALL:
```SQL
CREATE OR REPLACE VIEW v AS
(SELECT * from test_a where k>1 ORDER BY 1)
UNION ALL 
(SELECT * from test_b where k<1 ORDER BY 1);

explain select count(*) from v ;
                                                   QUERY PLAN                                                    
-----------------------------------------------------------------------------------------------------------------

 Aggregate  (cost=250.00..250.02 rows=1 width=8)
   ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=100000 width=8)
         Task Count: 32
         Tasks Shown: One of 32
         ->  Task
               Node: host=localhost port=9700 dbname=postgres
               ->  Aggregate  (cost=178.58..178.59 rows=1 width=8)
                     ->  Append  (cost=74.23..174.82 rows=1506 width=0)
                           ->  Subquery Scan on "*SELECT* 1"  (cost=74.23..83.64 rows=753 width=0)
                                 ->  Sort  (cost=74.23..76.11 rows=753 width=8)
                                       Sort Key: test_a.id
                                       ->  Seq Scan on test_a_102042 test_a  (cost=0.00..38.25 rows=753 width=8)
                                             Filter: (k > 1)
                           ->  Subquery Scan on "*SELECT* 2"  (cost=74.23..83.64 rows=753 width=0)
                                 ->  Sort  (cost=74.23..76.11 rows=753 width=8)
                                       Sort Key: test_b.id
                                       ->  Seq Scan on test_b_102074 test_b  (cost=0.00..38.25 rows=753 width=8)
                                             Filter: (k < 1)
(18 rows)

Time: 5.743 ms
```

2) Add a subquery on top and use a volatile function in the SELECT part. But, Postgres is sometimes smart about eliminating un-used elements in the SELECT part, so make sure to use it in an expression with a real-column

```SQL

CREATE OR REPLACE VIEW v AS
SELECT *, id * random() FROM (
SELECT * from test_a where k>1
	UNION ALL 
SELECT * from test_b where k<1) as bar;

explain select count(*) from v ;
                                                   QUERY PLAN                                                    
-----------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=250.00..250.02 rows=1 width=8)
   ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=100000 width=8)
         Task Count: 32
         Tasks Shown: One of 32
         ->  Task
               Node: host=localhost port=9700 dbname=postgres
               ->  Aggregate  (cost=144.27..144.28 rows=1 width=8)
                     ->  Result  (cost=0.00..125.45 rows=1506 width=16)
                           ->  Append  (cost=0.00..99.09 rows=1506 width=4)
                                 ->  Subquery Scan on "*SELECT* 1"  (cost=0.00..45.78 rows=753 width=4)
                                       ->  Seq Scan on test_a_102042 test_a  (cost=0.00..38.25 rows=753 width=8)
                                             Filter: (k > 1)
                                 ->  Subquery Scan on "*SELECT* 2"  (cost=0.00..45.78 rows=753 width=4)
                                       ->  Seq Scan on test_b_102074 test_b  (cost=0.00..38.25 rows=753 width=8)
                                             Filter: (k < 1)
(15 rows)

Time: 6.868 ms
```

My initial investigation shows that the main reason is that we use `plannerinfoRoot->append_rel_list`, but the `append_rel_list` might be in `plannerInfoRoot->parent_root->append_rel_list`

### PR DESCRIPTION
**Pull request by SaitTalhaNisanci**
DESCRIPTION: Fixes a UNION pushdown issue 

Postgres optimizes column fields that are not needed in the output. We
were relying on these fields to understand if it is safe to push down a
union query.

This fix looks at the parse query, which has the original column fields
to detect if it is safe to push down a union query.

This is where postgres optimizes the fields:
https://github.com/postgres/postgres/blob/9ee91cc583802c6507fbc31c348a79e63a10f956/src/backend/optimizer/path/allpaths.c#L3702

Fixes #4781.
Fixes #4144.

### CODE REVIEW

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 1]
```diff
@@ -1782,15 +1798,58 @@ RelationRestrictionPartitionKeyIndex(RelationRestriction *relationRestriction)
 			IsPartitionColumn(targetExpression, relationPlannerParseQuery))
 		{
 			Var *targetColumn = (Var *) targetExpression;
-
-			if (targetColumn->varno == relationRestriction->index)
+			/*
+			 * use the rte that we found while traversing the query tree.
+			 */
+			RangeTblEntry* res = findRteIdentityContext->rte;
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1804]: shouldn't this be: `			RangeTblEntry* res = list_nth(relationPlannerParseQuery->rtable, targetColumn->varno-1);
`

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 2]
```diff
@@ -1760,14 +1771,25 @@ ContainsUnionSubquery(Query *queryTree)
...
+	FindRteIdentityContext *findRteIdentityContext = palloc0(
+		sizeof(FindRteIdentityContext));
+	findRteIdentityContext->targetRTEIdentity = GetRTEIdentity(relationRestriction->rte);
+	FindQueryContainingRTEIdentity((Node *) originalQuery, findRteIdentityContext);
+	if (!findRteIdentityContext->found)
+	{
+		return NULL;
+	}
+
+	Query *relationPlannerParseQuery = findRteIdentityContext->query;
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1792]: It is weird that we use query from rteContext and targetList from parseQuery. Can't we use the former always?

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 3]
```diff
@@ -59,6 +59,14 @@ typedef struct AttributeEquivalenceClass
 	Index unionQueryPartitionKeyIndex;
 } AttributeEquivalenceClass;
 
+typedef struct FindRteIdentityContext
+{
+	uint32 targetRTEIdentity;
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:64]: do we really need `found` and `tempQuery`? Can't we always use `query` and found would mean `query != NULL`?

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 4]
```diff
@@ -59,6 +59,14 @@ typedef struct AttributeEquivalenceClass
 	Index unionQueryPartitionKeyIndex;
 } AttributeEquivalenceClass;
 
+typedef struct FindRteIdentityContext
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:62]: the name sounds hard to understand. Maybe `FindQueryContainingRteIdentityContext`

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 3 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:64]: minor: rte identity is `int` although it cannot be negative.

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 5]
```diff
@@ -1778,19 +1800,116 @@ RelationRestrictionPartitionKeyIndex(RelationRestriction *relationRestriction)
...
 
 		if (!targetEntry->resjunk &&
-			IsA(targetExpression, Var) &&
-			IsPartitionColumn(targetExpression, relationPlannerParseQuery))
+			IsA(targetExpression, Var))
 		{
 			Var *targetColumn = (Var *) targetExpression;
 
-			if (targetColumn->varno == relationRestriction->index)
+			if (!IsPartitionColumn(targetExpression, relationPlannerParseQuery))
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1807]: we do we move this check into the loop from the above `if` statement?

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 6]
```diff
@@ -1760,14 +1771,25 @@ ContainsUnionSubquery(Query *queryTree)
...
-	PlannerInfo *relationPlannerRoot = relationRestriction->plannerInfo;
-	Query *relationPlannerParseQuery = relationPlannerRoot->parse;
+
+	FindRteIdentityContext *findRteIdentityContext = palloc0(
+		sizeof(FindRteIdentityContext));
+	findRteIdentityContext->targetRTEIdentity = GetRTEIdentity(relationRestriction->rte);
+	FindQueryContainingRTEIdentity((Node *) originalQuery, findRteIdentityContext);
+	if (!findRteIdentityContext->found)
+	{
+		return NULL;
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1789]: Is it ever possible that we cannot find the query? I'm fine with having this check, but might use a comment that we should always find the query

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 7]
```diff
@@ -294,22 +305,22 @@ SafeToPushdownUnionSubquery(PlannerRestrictionContext *plannerRestrictionContext
...
-				continue;
-			}
-
-			varToBeAdded = (Var *) targetEntryToAdd->expr;
+			/*
+			 * we update the varno because we use the original parse tree for finding the
+			 * var. However the rest of the code relies on a query tree that might be different
+			 * than the original parse tree because of postgres optimizations.
+			 */
+			varToBeAdded->varno = relationRestriction->index;
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:323]: we already return the var from `relationPlannerParseQuery`. Do we really need to set this if we keep the code as-is?

Comment (onderkalaci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:323]: > relationPlannerParseQuery

as we talked, that's a naming issue. we should keep this

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 8]
```diff
@@ -1778,19 +1800,116 @@ RelationRestrictionPartitionKeyIndex(RelationRestriction *relationRestriction)
...
 		{
 			Var *targetColumn = (Var *) targetExpression;
 
-			if (targetColumn->varno == relationRestriction->index)
+			if (!IsPartitionColumn(targetExpression, relationPlannerParseQuery))
+			{
+				continue;
+			}
+
+			RangeTblEntry *resRTE = FindRelationRTEForColumn(
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1812]: Do we really need `FindRelationRTEForColumn`? Wouldn't `FindReferencedTableColumn` find the target column even if it is coming from a JOIN?

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 9]
```diff
@@ -1778,19 +1800,116 @@ RelationRestrictionPartitionKeyIndex(RelationRestriction *relationRestriction)
...
+	return resRTE;
+}
+
+
+/*
+ * FindQueryContainingRTEIdentity walks on the given node to find a query
+ * which has an RTE that has a given rteIdentity.
+ */
+static bool
+FindQueryContainingRTEIdentity(Node *node, FindRteIdentityContext *context)
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1880]: A high level API might be nicer: `Query * q= FindQueryContainingRTEIdentity(Query *mainQuery, rteIndex)` where we create the context and call `FindQueryContainingRTEIdentity`

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 8 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c]: No we don't need it, you are right. I changed the ordering of calls to avoid calling `FindRelationRTEForColumn`.

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 9 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c]: I named the high level function as `FindQueryContainingRteIdentity` and the internal method with a `Internal` suffix. 

Mainly because I think `Query` is more correct than `SubQuery` and when we have `FindQueryContainingRteIdentity` and `FindSubQueryContainingRteIdentity` it seems a bit confusing to see which one to use

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 6 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:1791]: Assuming we don't have a bug in the `FindQueryContainingRTEIdentity` function, we should find the query, however I think it is good to have this check because if we have a bug etc then instead of crashing, we will just recursively plan a query, which might be pushdownable or not.

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 3 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c]: I removed `found` field, but I think we need at least 2 fields since we need to know:
- we found the query
- what the query that this RTE resides in is

If you think we don't need one of them, let me know

Comment (onderkalaci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c]: If ` the query that this RTE resides in is` is NULL can't we call it as not found, and otherwise found?

Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c]: Yeah but we first need to set the `query` field so that when looking at a single `RTE` we know its parent query. So the query will need to be set before we come to the final call which just has an RTE node. 

And while setting the query, we don't know if we already found the `query` we are looking at without an extra field.

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 10]
```diff
@@ -155,6 +163,11 @@ static bool RangeTableArrayContainsAnyRTEIdentities(RangeTblEntry **rangeTableEn
 													queryRteIdentities);
 static Relids QueryRteIdentities(Query *queryTree);
 
+static bool FindQueryContainingRTEIdentityInternal(Node *node,
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:166]: minor: we typically order the functions the other way, first the one that uses the other one(s)

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 11]
```diff
@@ -1779,18 +1804,86 @@ RelationRestrictionPartitionKeyIndex(RelationRestriction *relationRestriction)
...
-			if (targetColumn->varno == relationRestriction->index)
+			Oid relationId = InvalidOid;
+			Var *column = NULL;
+			FindReferencedTableColumn(targetExpression, NIL,
+									  originalQueryContainingRTEIdentity, &relationId,
+									  &column);
+
+			targetColumn = column;
+			RangeTblEntry *resRTE =
+				(RangeTblEntry *) list_nth(originalQueryContainingRTEIdentity->rtable,
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1819]: `rt_fetch` could be used

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 12]
```diff
@@ -1779,18 +1804,86 @@ RelationRestrictionPartitionKeyIndex(RelationRestriction *relationRestriction)
 
 		if (!targetEntry->resjunk &&
 			IsA(targetExpression, Var) &&
-			IsPartitionColumn(targetExpression, relationPlannerParseQuery))
+			IsPartitionColumn(targetExpression, originalQueryContainingRTEIdentity))
 		{
 			Var *targetColumn = (Var *) targetExpression;
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1809]: do we really need `targetColumn` variable? Lets remove either `column` or `targetColumn`, It seems to complicate things.

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 13]
```diff
@@ -1779,18 +1804,86 @@ RelationRestrictionPartitionKeyIndex(RelationRestriction *relationRestriction)
...
+			Var *column = NULL;
+			FindReferencedTableColumn(targetExpression, NIL,
+									  originalQueryContainingRTEIdentity, &relationId,
+									  &column);
+
+			targetColumn = column;
+			RangeTblEntry *resRTE =
+				(RangeTblEntry *) list_nth(originalQueryContainingRTEIdentity->rtable,
+										   targetColumn->varno - 1);
+			if (resRTE->rtekind == RTE_RELATION && GetRTEIdentity(resRTE) ==
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1821]: can you find a better name for `resRTE` ?

File: src/test/regress/expected/union_pushdown.out [hunk 14]
```diff
@@ -946,7 +945,81 @@ SELECT MAX(k) FROM v;
...
+SELECT public.explain_has_distributed_subplan($$
+EXPLAIN
+SELECT MAX(k) FROM v;
+$$);
+ explain_has_distributed_subplan
+---------------------------------------------------------------------
+ f
+(1 row)
+
+CREATE OR REPLACE VIEW v AS SELECT * from test_a where k<1 UNION ALL SELECT * from test_b where k<1;
```
Comment (onderkalaci) [inline src/test/regress/expected/union_pushdown.out:988]: maybe have some extra tests with the following syntax:
```SQL
CREATE OR REPLACE VIEW v2 AS SELECT test_a.* from test_a where k>1 UNION ALL SELECT test_b.* from test_b where k<1;
explain select count(*) from v;
```

File: src/test/regress/expected/union_pushdown.out [hunk 15]
```diff
@@ -912,14 +912,13 @@ $$);
...
 
--- cannot pushed down because postgres optimizes fields, needs to be fixed with #4781
 SELECT public.explain_has_distributed_subplan($$
 EXPLAIN
 SELECT COUNT(k) FROM v;
 $$);
  explain_has_distributed_subplan
 ---------------------------------------------------------------------
- t
+ f
```
Comment (onderkalaci) [inline src/test/regress/expected/union_pushdown.out:921]: let's also have some basic tests with UNION

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 12 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:1809]: We don't need `column`. removed it.

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 16]
```diff
@@ -1779,18 +1805,97 @@ RelationRestrictionPartitionKeyIndex(RelationRestriction *relationRestriction)
...
+#if PG_VERSION_NUM < PG_VERSION_13
+/*
+ * As of pg13, columns point to RELATION_RTE so we don't need to do
+ * anything further. Prior to pg13, columns point to JOIN_RTE so we 
+ * find the actual column.
+ */
+			Oid relationId = InvalidOid;
+			FindReferencedTableColumn(targetExpression, NIL,
+									  originalQueryContainingRTEIdentity, &relationId,
+									  &targetColumn);
```
[the remark this answers is not in the document]
Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:1820]: It is already set to NULL in the function, do you think we need to set it again here or is the existing enough?

File: src/test/regress/expected/union_pushdown.out [hunk 17]
```diff
@@ -874,6 +876,114 @@ SELECT create_distributed_table('test_b','id');
...
+	  "(10,99)","(20,100)"}');
+INSERT INTO range_dist_table_2 VALUES ((10, 24));
+INSERT INTO range_dist_table_2 VALUES ((10, 60));
+INSERT INTO range_dist_table_2 VALUES ((10, 91));
+INSERT INTO range_dist_table_2 VALUES ((20, 100));
+-- the following can be pushed down
+CREATE OR REPLACE VIEW v2 AS SELECT * from range_dist_table_2 UNION ALL SELECT * from range_dist_table_2;
+SELECT public.explain_has_distributed_subplan($$
+EXPLAIN
+SELECT COUNT(dist_col) FROM v2;
```
Comment (onderkalaci) [inline src/test/regress/expected/union_pushdown.out:904]: shouldn't we need to do select count(*) here?

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 18]
```diff
@@ -287,29 +298,39 @@ SafeToPushdownUnionSubquery(PlannerRestrictionContext *plannerRestrictionContext
...
+			 * var. However the rest of the code relies on a query tree that might be different
+			 * than the original parse tree because of postgres optimizations.
+			 * That's why we update the varno to reflect the rteIndex in the modified query tree.
+			 */
+			varToBeAdded->varno = relationRestriction->index;
+
+			/*
+			 * This should never happen but to be on the safe side, we have this
+			 */
+			if (relationPlannerRoot->simple_rel_array_size >= relationRestriction->index)
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:330]: I'd move this above `varToBeAdded->varno = relationRestriction->index;`

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 16 above)
[the remark this answers is not in the document]
Comment (onderkalaci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:1837]: No, I mean, if `targetColumn` is NULL at this point, just return NULL from the function

File: src/test/regress/expected/union_pushdown.out (hunk 17 above)
Comment (onderkalaci) [reply src/test/regress/expected/union_pushdown.out:904]: maybe have both

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 19]
```diff
@@ -294,22 +307,22 @@ SafeToPushdownUnionSubquery(PlannerRestrictionContext *plannerRestrictionContext
 		}
 		else
 		{
-			partitionKeyIndex =
-				RelationRestrictionPartitionKeyIndex(relationRestriction);
+			varToBeAdded =
+				RelationRestrictionPartitionKeyIndex(originalQuery, relationRestriction,
+													 &partitionKeyIndex);
 
 			/* union does not have partition key in the target list */
```
[the remark this answers is not in the document]
Comment (onderkalaci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:313]: I think we should also add the same check here as well

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 20]
```diff
@@ -1779,18 +1822,89 @@ RelationRestrictionPartitionKeyIndex(RelationRestriction *relationRestriction)
...
 		if (!targetEntry->resjunk &&
 			IsA(targetExpression, Var) &&
-			IsPartitionColumn(targetExpression, relationPlannerParseQuery))
+			IsPartitionColumn(targetExpression, originalQueryContainingRTEIdentity))
 		{
 			Var *targetColumn = (Var *) targetExpression;
 
-			if (targetColumn->varno == relationRestriction->index)
+/*
+ * As of pg13, columns point to RELATION_RTE so we don't need to do
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1830]: why did we remove pg 13 ifdefs here?

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 21]
```diff
@@ -1779,18 +1822,89 @@ RelationRestrictionPartitionKeyIndex(RelationRestriction *relationRestriction)
...
+	return NULL;
+}
+
+
+/*
+ * FindQueryContainingRTEIdentity finds the query/subquery that has an RTE
+ * with rteIndex in its rtable.
+ */
+static Query *
+FindQueryContainingRTEIdentity(Query *mainQuery, int rteIndex)
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1858]: minor: `mainQuery` is a little unusual naming for the query. Maybe `query` is enough?

File: src/backend/distributed/planner/multi_logical_optimizer.c [hunk 22]
```diff
@@ -4407,14 +4407,13 @@ IsPartitionColumn(Expr *columnExpression, Query *query)
  */
 void
 FindReferencedTableColumn(Expr *columnExpression, List *parentQueryList, Query *query,
-						  Oid *relationId, Var **column)
+						  Var **column, RangeTblEntry **rte)
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_logical_optimizer.c:4410]: `FindReferencedTableColumn` / `IsPartitionColumn` seems to be used in several places. I think we should add some regression tests touching those code-paths.

File: src/backend/distributed/planner/multi_logical_optimizer.c [hunk 23]
```diff
@@ -4407,14 +4407,13 @@ IsPartitionColumn(Expr *columnExpression, Query *query)
  */
 void
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_logical_optimizer.c:4408]: we should update function comment of `FindReferencedTableColumn`

File: src/backend/distributed/planner/multi_logical_optimizer.c [hunk 24]
```diff
@@ -4445,7 +4444,18 @@ FindReferencedTableColumn(Expr *columnExpression, List *parentQueryList, Query *
...
+							   candidateColumn->varlevelsup;
+		if (parentQueryIndex < 0)
+		{
+			return;
+		}
+
+		/*
+		 * as we get the query from varlevelsup up, we reset the varlevelsup.
+		 */
+		candidateColumn->varlevelsup = 0;
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_logical_optimizer.c:4457]: are we really allowed to update this var? These are typically the expression from the query tree that we are processing. Shouldn't we need to do:
```C
/*  before we recurse into the query tree, we should update the candidateColumn and we use copy of it. -- followed by your above comment --  */
candidateColumn = copyObject(candidateColumn);
candidateColumn->varlevelsup = 0;

File: src/test/regress/sql/union_pushdown.sql [hunk 25]
```diff
@@ -703,6 +783,286 @@ EXPLAIN
...
+) as bar;
+$$);
+
+SELECT public.explain_has_distributed_subplan($$
+EXPLAIN
+SELECT count(*) FROM
+(
+SELECT bar.user_id FROM users_table_part u1 JOIN LATERAL (SELECT u1.user_id, random() FROM users_table_part u2 WHERE u2.user_id = u1.user_id) as bar ON (true)
+UNION
+SELECT bar.user_id FROM users_table_part u1 JOIN LATERAL (SELECT u1.user_id, random() FROM users_table_part u2 WHERE u2.user_id = u1.user_id) as bar ON (true)
```
Comment (onderkalaci) [inline src/test/regress/sql/union_pushdown.sql:845]: maybe make subqueries one level deeper here:
```SQL
SELECT bar.user_id FROM users_table_part u1 JOIN LATERAL (SELECT *,random() FROM (SELECT u1.user_id FROM users_table_part u2 WHERE u2.user_id = u1.user_id) as foo) as bar ON (true)
```

File: src/backend/distributed/planner/multi_logical_optimizer.c (hunk 24 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/multi_logical_optimizer.c:4457]: You are right, we should copy the variable.

File: src/backend/distributed/planner/multi_logical_optimizer.c (hunk 22 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/multi_logical_optimizer.c:4410]: minor suggestion: `rte` -> `rteContainingReferencedColumn`

File: src/backend/distributed/planner/multi_logical_optimizer.c [hunk 26]
```diff
@@ -4445,7 +4444,18 @@ FindReferencedTableColumn(Expr *columnExpression, List *parentQueryList, Query *
 	 */
 	if (candidateColumn->varlevelsup > 0)
 	{
-		return;
+		int parentQueryIndex = list_length(parentQueryList) -
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_logical_optimizer.c:4447]: just to be on the safe side, we should check the length of `parentQueryList`. Users might call this function on an unexpected state (e.g., candidateColumn->varlevelsup > 0 AND parentQueryList = NIL)

File: src/backend/distributed/planner/multi_logical_optimizer.c [hunk 27]
```diff
@@ -4445,7 +4444,18 @@ FindReferencedTableColumn(Expr *columnExpression, List *parentQueryList, Query *
...
+		if (parentQueryIndex < 0)
+		{
+			return;
+		}
+
+		/*
+		 * as we get the query from varlevelsup up, we reset the varlevelsup.
+		 */
+		candidateColumn->varlevelsup = 0;
+		query = list_nth(parentQueryList, parentQueryIndex);
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_logical_optimizer.c:4458]: Should we be also adjusting the `parentQueryList`? I guess it might be necessary because we still need the accurate parentQueryList for to hold for `ctelevelsupctelevelsup`.

Could you find a query where we both have `ctelevelsupctelevelsup > 0` and `varlevelsup > 0`?

**Comment by metdos** [comment]
Removed cherry-pick 10.1 and added 10.2 milestone.

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 20 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:1832]: ping on this

File: src/test/regress/expected/union_pushdown.out [hunk 28]
```diff
@@ -874,6 +876,123 @@ SELECT create_distributed_table('test_b','id');
...
+$$);
+ explain_has_distributed_subplan
+---------------------------------------------------------------------
+ f
+(1 row)
+
+SELECT public.explain_has_distributed_subplan($$
+explain SELECT * FROM users_table_part u1 WHERE (user_id) IN
+(
+SELECT user_id FROM (SELECT * FROM users_table_part) as foo
```
Comment (onderkalaci) [inline src/test/regress/expected/union_pushdown.out:939]: I guess we should add something to prevent pulling up the subquery to `foo`, such as `SELECT *, random() FROM ..`

File: src/test/regress/expected/union_pushdown.out [hunk 29]
```diff
@@ -937,18 +1055,394 @@ SELECT SUM(k) FROM v;
...
+UNION
+SELECT bar.user_id FROM users_table_part u1 JOIN LATERAL (SELECT u1.user_id FROM users_table_part u2 WHERE u2.user_id = u1.user_id) as bar ON (true)
+) as bar;
+$$);
+ explain_has_distributed_subplan
+---------------------------------------------------------------------
+ f
+(1 row)
+
+SELECT public.explain_has_distributed_subplan($$
```
Comment (onderkalaci) [inline src/test/regress/expected/union_pushdown.out:1158]: as we talked in person, there are some other issues in the planner regarding CTEs in UNION pushdown:
```
p *deferredError
(DeferredErrorMessage) $5 = {
tag = {
extensible = (type = T_ExtensibleNode, extnodename = "DeferredErrorMessage")
citus_tag = T_DeferredErrorMessage
}
code = 1088
message = 0x00000001066150bd "cannot push down this subquery"
detail = 0x0000000106616e7a "Complex subqueries and CTEs are not supported within a UNION"
hint = 0x0000000000000000
filename = 0x0000000106616a68 "planner/query_pushdown_planning.c"
linenumber = 1327
functionname = 0x0000000106616da4 "DeferErrorIfUnsupportedUnionQuery"
}
```

I think we can still keep this test, but add a comment on why we are not pushing down at the moment

File: src/test/regress/expected/union_pushdown.out [hunk 30]
```diff
@@ -937,18 +1055,394 @@ SELECT SUM(k) FROM v;
...
+                               FROM   cte_1 ) ;
+$$);
+ explain_has_distributed_subplan
+---------------------------------------------------------------------
+ f
+(1 row)
+
+SELECT public.explain_has_distributed_subplan($$
+EXPLAIN SELECT * FROM users_table_part u1 WHERE (value_1, user_id) IN
+(
```
Comment (onderkalaci) [inline src/test/regress/expected/union_pushdown.out:1407]: Do you know why this fails? For example, if we only had `user_id` on the WHERE clause, would it pushdown?

File: src/backend/distributed/planner/multi_logical_optimizer.c [hunk 31]
```diff
@@ -4400,21 +4403,23 @@ IsPartitionColumn(Expr *columnExpression, Query *query)
...
  * FindReferencedTableColumn recursively traverses query tree to find actual relation
  * id, and column that columnExpression refers to. If columnExpression is a
- * non-relational or computed/derived expression, the function returns InvalidOid for
- * relationId and NULL for column. The caller should provide parent query list from
+ * non-relational or computed/derived expression, the function returns NULL for
+ * rte and NULL for column. The caller should provide parent query list from
  * top of the tree to this particular Query's parent. This argument is used to look
  * into CTEs that may be present in the query.
+ *
+ * If skipOuterVars is true, then it doesn't check vars coming from outer queries.
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_logical_optimizer.c:4411]: Would be nice to add a comment why we made this optional. I think we can openly write that it should just work, but as the change touches wide range of query classes, we wanted to work on that separately, make this false for all, and remove this flag.

File: src/backend/distributed/planner/multi_logical_optimizer.c (hunk 27 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/multi_logical_optimizer.c:4466]: > Could you find a query where we both have ctelevelsupctelevelsup > 0 and varlevelsup > 0?

Is this possible with the current patch?

Comment (onderkalaci) [reply src/backend/distributed/planner/multi_logical_optimizer.c:4466]: Even if not, I think we should add a comment here warning the future code changes to be careful about it.

File: src/test/regress/expected/union_pushdown.out (hunk 30 above)
Comment (SaitTalhaNisanci) [reply src/test/regress/expected/union_pushdown.out:1407]: https://github.com/citusdata/citus/blob/f00c63c33daf3d16f06462626ca14732b141ae7a/src/backend/distributed/planner/relation_restriction_equivalence.c#L235

I think we are hitting this, maybe I can add that as a comment.

File: src/test/regress/multi_schedule [hunk 32]
```diff
@@ -14,6 +14,7 @@ test: multi_shard_update_delete recursive_dml_with_different_planners_executors
 test: insert_select_repartition window_functions dml_recursive multi_insert_select_window
 test: multi_insert_select_conflict citus_table_triggers
 test: multi_row_insert insert_select_into_local_table multi_create_table_new_features
+test: multi_agg_approximate_distinct
```
Comment (SaitTalhaNisanci) [inline src/test/regress/multi_schedule:17]: The reason for this change is because multi_agg_approximate_distinct doesn't have its own schema(so it is not isolated) and this is the fastest/easiest way to accomplish having the necessary tables.

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 20 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:1832]: Because now we need to process the varlevelsup > 0 even for pg13. Otherwise we will have the same regression on master compared to this branch on pg13.

Adding the ifdefs back makes 2 tests not pushdown on pg13.

File: src/backend/distributed/planner/multi_logical_optimizer.c (hunk 27 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/multi_logical_optimizer.c:4466]: I have added this but I guess it doesn't have ctelevelsup > 0.

https://github.com/citusdata/citus/pull/5079/files#diff-fb756d0d31008052220149d21e9990dccba97f3b65e643d860d271ff565ed1c9R1159

Anyways, I will add a comment either way

**Comment by onderkalaci** [comment]
Is https://github.com/citusdata/citus/issues/4144 relevant to this PR?

**Comment by SaitTalhaNisanci** [comment]
Is #4144 relevant to this PR?

Yes, this PR fixes #4144 as well.

File: src/backend/distributed/planner/multi_logical_optimizer.c [hunk 33]
```diff
@@ -4445,7 +4453,26 @@ FindReferencedTableColumn(Expr *columnExpression, List *parentQueryList, Query *
 	 */
 	if (candidateColumn->varlevelsup > 0)
 	{
-		return;
+		int parentQueryIndex = list_length(parentQueryList) -
+							   candidateColumn->varlevelsup;
+		if (skipOuterVars || !(IsIndexInRange(parentQueryList, parentQueryIndex)))
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_logical_optimizer.c:4458]: Very minor, I'd move `skipOuterVars` check above for ease of readability:
```if (candidateColumn->varlevelsup > 0 && !skipOuterVars)```

File: src/backend/distributed/planner/multi_logical_optimizer.c [hunk 34]
```diff
@@ -4445,7 +4453,26 @@ FindReferencedTableColumn(Expr *columnExpression, List *parentQueryList, Query *
...
+		 */
+		candidateColumn = copyObject(candidateColumn);
+		candidateColumn->varlevelsup = 0;
+
+		/*
+		 * We should be careful about these fields because they need to
+		 * be updated correctly based on ctelevelsup and varlevelsup.
+		 */
+		query = list_nth(parentQueryList, parentQueryIndex);
+		parentQueryList = list_truncate(parentQueryList, parentQueryIndex);
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_logical_optimizer.c:4475]: Lets add the following assert/comment (or something similar) to CTE section, because I really doubt this would work there. I think without supporting it, there is no code-base to test, but we should be careful when we enable in the future.

```C
	else if (rangeTableEntry->rtekind == RTE_CTE)
	{
		/*
		 * When outerVars are considered, we modify parentQueryList, so this
		 * logic might need to change when we support outervars in CTEs.
		 */
		Assert (!skipOuterVars);
```

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 35]
```diff
@@ -1756,41 +1778,136 @@ ContainsUnionSubquery(Query *queryTree)
 
 
 /*
- * RelationRestrictionPartitionKeyIndex gets a relation restriction and finds the
- * index that the partition key of the relation exists in the query. The query is
- * found in the planner info of the relation restriction.
+ * PartitionKeyForRTEIdentityInQuery finds the partition key var(if exists), in the given original query for the rte that has targetRTEIndex.
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1781]: this comment should be spread in to 2 or more lines

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 20 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:1832]: So, the comment is wrong and also wrongly indented :) 

I think we should tell here that we have to do this to support distributions columns that are correlated

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 36]
```diff
@@ -287,29 +298,40 @@ SafeToPushdownUnionSubquery(PlannerRestrictionContext *plannerRestrictionContext
...
+			if (partitionKeyIndex == 0 || varToBeAdded == NULL)
 			{
 				continue;
 			}
 		}
 		else
 		{
-			partitionKeyIndex =
-				RelationRestrictionPartitionKeyIndex(relationRestriction);
+			int targetRTEIndex = GetRTEIdentity(relationRestriction->rte);
```
Comment (onderkalaci) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:308]: The next obvious question is that why do we have the distinction between certain UNION ALL queries and the rest of UNION/UNION ALL queries. 

Can't we get rid of the above part as well? https://github.com/citusdata/citus/compare/fix/union_pushdown...onder_test?expand=1


I think we should do and try to find a simple correlated UNION ALL test which used to work with the above code, and now works with the new code.

What do you think?

**Review by onderkalaci — APPROVED** [review]
I have very last few comments, lets try to see if we can apply my suggestion. If not, I'm good to merge as-is. Let me know if you hit any problems on applying the suggestion

Also, please open an issue that we discussed earlier on expand colocated-correlated query support and give the some of the examples we discussed on our private chat.

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 36 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:308]: Good point.

Some example query that would fail without the above block you shared prior to the fix but passes with the new logic is:

```sql
  SELECT
   (SELECT count(*) FROM users_table_part WHERE user_id = e.user_id
       UNION ALL
    SELECT count(*) FROM users_table_part WHERE user_id = e.user_id)
 FROM
   (SELECT * FROM users_table_part UNION ALL SELECT * FROM users_table_part) as e;
```

File: src/backend/distributed/planner/multi_logical_optimizer.c [hunk 37]
```diff
@@ -4485,11 +4514,17 @@ FindReferencedTableColumn(Expr *columnExpression, List *parentQueryList, Query *
...
 
 		/* parent query list stays the same since still in the same query boundary */
-		FindReferencedTableColumn(joinColumn, parentQueryList, query,
-								  relationId, column);
+		FindReferencedTableColumn(joinColumn, parentQueryList, query, column,
+								  rteContainingReferencedColumn, skipOuterVars);
 	}
 	else if (rangeTableEntry->rtekind == RTE_CTE)
 	{
+		/*
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_logical_optimizer.c:4522]: @SaitTalhaNisanci this hits an assertion failure on multi-mx-schedule on coordinator_should_have_shards mx test:

```SQL
WITH a AS (SELECT * FROM table_1 ORDER BY 1,2 DESC LIMIT 1)
 INSERT INTO table_1 SELECT count(*),
 key
 FROM a JOIN table_2 USING (key)
 GROUP BY key
 HAVING (max(table_2.value) >= (SELECT value FROM a));
```

Comment (SaitTalhaNisanci) [reply src/backend/distributed/planner/multi_logical_optimizer.c:4522]: @onderkalaci looking at this assert, I am curious why we have added it. Because if `skipOuterVars` is true then we don't modify the `parentQueryList`:
image

And we haven't changed the CTE block, so when `skipOuterVars` is true, the function will be executed same as the previous version. In that case it seems like we remove this assert?

Comment (onderkalaci) [reply src/backend/distributed/planner/multi_logical_optimizer.c:4522]: I think when `! skipOuterVars ` we modify `parentQueryList` and `parentQueryList` is used when `RTE_CTE`.

I think one reason we added the assert was we weren't sure if  `rangeTableEntry->ctelevelsup > 0` and `candidateColumn->varlevelsup > 0` can happen at the same time.

If that happens, our logic could be broken for `RTE_CTE`.

@SaitTalhaNisanci does that make sense?

**Comment by onderkalaci** [comment]
>  Because if skipOuterVars is true

btw, assert is (!skipOuterVars), so it is triggered with `skipOuterVars=false`
