### PR TITLE
ensure we have more active nodes than replication factor.

### LINKED ISSUE #6332: create_distributed_table_concurrently throws floating point exception
When all the nodes have shouldhaveshards false, create_distributed_table_concurrently throws the following error:

```sql
select citus_set_node_property(nodename, nodeport, 'shouldhaveshards', false) from pg_dist_node;

select create_distributed_table_concurrently('test','x');
ERROR:  floating-point exception
DETAIL:  An invalid floating-point operation was signaled. This probably means an out-of-range result or an invalid operation, such as division by zero.
```
Stack trace
```
(gdb) bt
#0  0x00007f762456b669 in RoundRobinWorkerNodeList (workerNodeList=0x0, listLength=listLength@entry=32) at commands/create_distributed_table.c:861
#1  0x00007f762456cbc1 in CreateDistributedTableConcurrently (relationId=relationId@entry=2432648, distributionColumnName=distributionColumnName@entry=0x55a505ba2ad0 "x", 
    distributionMethod=distributionMethod@entry=104 'h', colocateWithTableName=colocateWithTableName@entry=0x55a505ba2af0 "default", shardCount=32, 
    shardCountIsStrict=shardCountIsStrict@entry=false) at commands/create_distributed_table.c:559
#2  0x00007f762456ce85 in create_distributed_table_concurrently (fcinfo=0x55a505b7b368) at commands/create_distributed_table.c:330
#3  0x000055a504b2216e in ExecInterpExpr (state=0x55a505b7b280, econtext=0x55a505b7af80, isnull=0x7ffccc84c847) at execExprInterp.c:725
#4  0x000055a504b1e354 in ExecInterpExprStillValid (state=0x55a505b7b280, econtext=0x55a505b7af80, isNull=0x7ffccc84c847) at execExprInterp.c:1824
#5  0x000055a504b60462 in ExecEvalExprSwitchContext (isNull=0x7ffccc84c847, econtext=0x55a505b7af80, state=0x55a505b7b280) at ../../../src/include/executor/executor.h:339
#6  ExecProject (projInfo=0x55a505b7b278) at ../../../src/include/executor/executor.h:373
#7  ExecResult (pstate=<optimized out>) at nodeResult.c:136
#8  0x000055a504b2f2d7 in ExecProcNodeFirst (node=0x55a505b7ae68) at execProcnode.c:463
#9  0x000055a504b2718b in ExecProcNode (node=0x55a505b7ae68) at ../../../src/include/executor/executor.h:257
#10 ExecutePlan (estate=estate@entry=0x55a505b7ac30, planstate=0x55a505b7ae68, use_parallel_mode=<optimized out>, operation=operation@entry=CMD_SELECT, 
    sendTuples=sendTuples@entry=true, numberTuples=numberTuples@entry=0, direction=ForwardScanDirection, dest=0x55a505bb5168, execute_once=true) at execMain.c:1551
#11 0x000055a504b27e4f in standard_ExecutorRun (queryDesc=queryDesc@entry=0x55a505bf36f0, direction=direction@entry=ForwardScanDirection, count=count@entry=0, 
    execute_once=execute_once@entry=true) at execMain.c:361
#12 0x00007f76245c4a3e in CitusExecutorRun (queryDesc=0x55a505bf36f0, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at executor/multi_executor.c:238
#13 0x000055a504b27f12 in ExecutorRun (queryDesc=queryDesc@entry=0x55a505bf36f0, direction=direction@entry=ForwardScanDirection, count=count@entry=0, 
    execute_once=<optimized out>) at execMain.c:303
#14 0x000055a504cf3c6a in PortalRunSelect (portal=portal@entry=0x55a505ae75b0, forward=forward@entry=true, count=0, count@entry=9223372036854775807, 
    dest=dest@entry=0x55a505bb5168) at pquery.c:921
#15 0x000055a504cf5788 in PortalRun (portal=portal@entry=0x55a505ae75b0, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, 
    dest=dest@entry=0x55a505bb5168, altdest=altdest@entry=0x55a505bb5168, qc=0x7ffccc84ccd0) at pquery.c:765
#16 0x000055a504cf1603 in exec_simple_query (query_string=query_string@entry=0x55a505a050d0 "select create_distributed_table_concurrently('test','x');") at postgres.c:1213
#17 0x000055a504cf36ba in PostgresMain (argc=argc@entry=1, argv=argv@entry=0x7ffccc84ced0, dbname=<optimized out>, username=<optimized out>) at postgres.c:4496
#18 0x000055a504c4b3e9 in BackendRun (port=port@entry=0x55a505aa2cc0) at postmaster.c:4530
#19 0x000055a504c4e7a7 in BackendStartup (port=port@entry=0x55a505aa2cc0) at postmaster.c:4252
#20 0x000055a504c4e9f0 in ServerLoop () at postmaster.c:1745
#21 0x000055a504c4ff4c in PostmasterMain (argc=<optimized out>, argv=<optimized out>) at postmaster.c:1417
#22 0x000055a504b8c5a1 in main (argc=3, argv=0x55a5059fdcd0) at main.c:209
```

create_distributed_table has a nicer error:
```sql
select create_distributed_table('test','x');
ERROR:  replication_factor (1) exceeds number of worker nodes (0)
HINT:  Add more worker nodes or try again with a lower replication factor.
```

### PR DESCRIPTION
**Pull request by aykut-bozkurt**
DESCRIPTION: Fixes floating exception during create_distributed_table_concurrently.

Fixes #6332.
During create_distributed_table_concurrently, when there is no active primary node, it fails with floating exception. We added similar check with create_distributed_table. It will fail with proper message if current active node is less than replication factor.

### CODE REVIEW

File: src/backend/distributed/commands/create_distributed_table.c [hunk 1]
```diff
@@ -528,6 +528,17 @@ CreateDistributedTableConcurrently(Oid relationId, char *distributionColumnName,
...
 	}
 
+	List *workerNodeList = DistributedTablePlacementNodeList(NoLock);
+	int32 workerNodeCount = list_length(workerNodeList);
+	if (ShardReplicationFactor > workerNodeCount)
+	{
+		ereport(ERROR, (errcode(ERRCODE_INVALID_PARAMETER_VALUE),
+						errmsg("replication_factor (%d) exceeds number of worker nodes "
+							   "(%d)", ShardReplicationFactor, workerNodeCount),
+						errhint("Add more worker nodes or try again with a lower "
```
Comment (marcocitus) [inline src/backend/distributed/commands/create_distributed_table.c:538]: a bit misleading since we only support replication factor 1 in this case, maybe something like:

errmsg("no worker nodes are available for placing shards")

File: src/test/regress/expected/create_distributed_table_concurrently.out [hunk 2]
```diff
@@ -57,6 +57,51 @@ ERROR:  cannot colocate tables nocolo and test
 DETAIL:  Distribution column types don't match for nocolo and test.
 select create_distributed_table_concurrently('test','key', colocate_with := 'noexists');
 ERROR:  relation "noexists" does not exist
+select citus_set_node_property('localhost', :worker_1_port, 'shouldhaveshards', false) from pg_dist_node;
```
Comment (marcocitus) [inline src/test/regress/expected/create_distributed_table_concurrently.out:60]: you can remove the ` from pg_dist_node` part, since we're passing in all the information directly

Comment (marcocitus) [reply src/test/regress/expected/create_distributed_table_concurrently.out:60]: well, then my feedback changes to: This thing returns 5 rows, I'm quite not sure what we're updating here. Can we just update the 2 worker nodes? :)

**Review by marcocitus — APPROVED** [review]
