### PR TITLE
Simplify and fix issues in intermediate result pruning

### LINKED ISSUE #3708: Subqueries in HAVING fail with query pushdown
It seems that the assumption of the result of subqueries in HAVING is only necessary at the coordinator is wrong for query-pushdown case:
```SQL
 SELECT user_id, count (user_id) OVER (PARTITION BY user_id) FROM users_table GROUP BY user_id HAVING avg(value_1) > (SELECT value_1 FROM users_table_ref) LIMIT 1;
SELECT user_id, count (user_id) OVER (PARTITION BY user_id) FROM users_table GROUP BY user_id HAVING avg(value_1) > (SELECT value_1 FROM users_table_ref) LIMIT 1;
DEBUG:  Router planner cannot handle multi-shard select queries
DEBUG:  Distributed planning for a fast-path router query
DEBUG:  Creating router plan
DEBUG:  Plan is router executable
DEBUG:  generating subplan 9_1 for subquery SELECT value_1 FROM public.users_table_ref
DEBUG:  Plan 9 query after replacing subqueries and CTEs: SELECT user_id, count(user_id) OVER (PARTITION BY user_id) AS count FROM public.users_table GROUP BY user_id HAVING (avg(value_1) OPERATOR(pg_catalog.>) ((SELECT intermediate_result.value_1 FROM read_intermediate_result('9_1'::text, 'binary'::citus_copy_format) intermediate_result(value_1 integer)))::numeric) LIMIT 1
DEBUG:  Router planner cannot handle multi-shard select queries
DEBUG:  Subplan 9_1 will be written to local file
..
NOTICE:  issuing SELECT worker_column_1 AS user_id, count(worker_column_1) OVER (PARTITION BY worker_column_1) AS count, sum(worker_column_2) AS worker_column_3, count(worker_column_2) AS worker_column_4 FROM (SELECT users_table.user_id AS worker_column_1, users_table.value_1 AS worker_column_2 FROM public.users_table_102009 users_table) worker_subquery GROUP BY worker_column_1 HAVING (avg(worker_column_2) OPERATOR(pg_catalog.>) ((SELECT intermediate_result.value_1 FROM read_intermediate_result('9_1'::text, 'binary'::citus_copy_format) intermediate_result(value_1 integer)))::numeric)

```

And  the relevant code here: https://github.com/citusdata/citus/blob/ed0376bb41421067a66d60cd0a2bd9b0eafd9d01/src/backend/distributed/planner/distributed_planner.c#L1141-L1157

### LINKED ISSUE #3717: Segfault in INSERT..SELECT with subquery in HAVING
```sql
WITH 
a AS (SELECT avg(x) FROM test), 
b AS (INSERT INTO test SELECT x, count(*) FROM test WHERE y > (SELECT * FROM a) GROUP BY x HAVING count(*) < (SELECT * FROM a) LIMIT 3 RETURNING *) 
SELECT * FROM b;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
Time: 296.557 ms
``` 

Stack trace:
```
182             List *taskList = distributedPlan->workerJob->taskList;
(gdb) bt
#0  0x00007f8be5c4f6bd in AppendAllAccessedWorkerNodes (entry=0x20c9368, distributedPlan=distributedPlan@entry=0x7f8bd79ca048, workerNodeCount=workerNodeCount@entry=2)
    at planner/intermediate_result_pruning.c:182
#1  0x00007f8be5c4fad6 in RecordSubplanExecutionsOnNodes (intermediateResultsHash=0x20c7938, distributedPlan=0x7f8bd79ca048) at planner/intermediate_result_pruning.c:145
#2  0x00007f8be5c4fb4d in RecordSubplanExecutionsOnNodes (intermediateResultsHash=intermediateResultsHash@entry=0x20c7938, distributedPlan=distributedPlan@entry=0x7f8bd79d1040)
    at planner/intermediate_result_pruning.c:159
#3  0x00007f8be5c378e1 in ExecuteSubPlans (distributedPlan=distributedPlan@entry=0x7f8bd79d1040) at executor/subplan_execution.c:47
#4  0x00007f8be5c2b61e in AdaptiveExecutorPreExecutorRun (scanState=<optimized out>) at executor/adaptive_executor.c:648
#5  0x00007f8be5c2ca36 in CitusPreExecScan (scanState=<optimized out>) at executor/citus_custom_scan.c:217
#6  0x00007f8be5c329b6 in CitusExecutorRun (queryDesc=0x20c1508, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at executor/multi_executor.c:213
#7  0x00000000006400b8 in ExecutorRun (queryDesc=queryDesc@entry=0x20c1508, direction=direction@entry=ForwardScanDirection, count=count@entry=0, execute_once=<optimized out>)
    at execMain.c:305
#8  0x00000000007a3fbf in PortalRunSelect (portal=portal@entry=0x1ff2488, forward=forward@entry=true, count=0, count@entry=9223372036854775807, dest=dest@entry=0x7f8bd79d1ff0)
    at pquery.c:932
#9  0x00000000007a5605 in PortalRun (portal=portal@entry=0x1ff2488, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, 
    dest=dest@entry=0x7f8bd79d1ff0, altdest=altdest@entry=0x7f8bd79d1ff0, completionTag=0x7ffc92023c50 "") at pquery.c:773
#10 0x00000000007a1a94 in exec_simple_query (
    query_string=query_string@entry=0x1f3c3b8 "WITH a AS (SELECT avg(x) FROM test), b AS (INSERT INTO test SELECT x, count(*) FROM test WHERE y > (SELECT * FROM a) GROUP BY x HAVING count(*) < (SELECT * FROM a) LIMIT 3 RETURNING *) SELECT * FROM b"...) at postgres.c:1145
#11 0x00000000007a38c6 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x1fb6b20, dbname=<optimized out>, username=<optimized out>) at postgres.c:4193
#12 0x0000000000722ce7 in BackendRun (port=port@entry=0x1fb0110) at postmaster.c:4364
#13 0x0000000000725d30 in BackendStartup (port=port@entry=0x1fb0110) at postmaster.c:4036
#14 0x0000000000725f3f in ServerLoop () at postmaster.c:1707
#15 0x0000000000727354 in PostmasterMain (argc=argc@entry=3, argv=argv@entry=0x1f35b50) at postmaster.c:1380
#16 0x000000000068dee8 in main (argc=3, argv=0x1f35b50) at main.c:228
(gdb) 
```

### PR DESCRIPTION
**Pull request by marcocitus**
DESCRIPTION: Fixes a bug that could cause failures in queries with subqueries or CTEs

Follow up on #3709. This cut a bit deeper than I expected.

After this PR we explicitly find subplans in the masterQuery (local) and the jobQuery (remote) instead of only looking at having in the original query (?). The masterQuery gets rewritten by standard_planner, so I moved building `usedSubPlanNodeList` to just before the standard_planner call. To make sure we descend into sublinks correctly, I moved setting masterQuery->hasSubLinks into the physical planner, where it was supposed to be all along.

At some point we may want to make a copy of the original masterQuery instead of keeping the rewritten one, but since it wasn't strictly necessary here I'll leave the for another day.

A bunch of code was dealing with de-duplication in `usedSubPlanNodeList`, which seems unnecessary since we map all matching subplan IDs to the same `IntermediateResultsHashEntry ` in `RecordSubplanExecutionsOnNodes` and the de-duplication logic mostly just moves work from `RecordSubplanExecutionsOnNodes` to `FindSubPlansUsedInNode`. I removed this code.

While working on the changes I found a crash in INSERT..SELECT in combination with intermediate results (#3717). This PR addresses that issue by sending the intermediate results that are used in the SELECT part everywhere, since we currently do planning for the SELECT part in the executor, so we cannot easily do proper pruning.

Fixes #3708
Fixes #3717 
Closes #3709

### CODE REVIEW

File: src/backend/distributed/planner/intermediate_result_pruning.c [hunk 1]
```diff
@@ -24,25 +25,71 @@
...
+		/*
+		 * Mark the subplans as needed on remote side. Note that this decision is
+		 * revisited on execution, when the query only consists of intermediate
+		 * results.
+		 */
+		remoteSubPlans = FindSubPlansUsedInNode((Node *) plan->workerJob->jobQuery,
+												SUBPLAN_ACCESS_REMOTE);
+	}
+
+	if (plan->insertSelectQuery != NULL)
```
Comment (serprex) [inline src/backend/distributed/planner/intermediate_result_pruning.c:71]: `Assert(plan->workerJob == NULL)`

Comment (onderkalaci) [reply src/backend/distributed/planner/intermediate_result_pruning.c:71]: Is there a reason that it is not `else if (plan->insertSelectQuery != NULL)`?  Now it feels a little unusual to update `remoteSubPlans ` in two different places.

File: src/backend/distributed/planner/multi_master_planner.c [hunk 2]
```diff
@@ -207,10 +207,6 @@ BuildSelectStatementViaStdPlanner(Query *masterQuery, List *masterTargetList,
 	remoteScan->custom_scan_tlist = copyObject(masterTargetList);
 	remoteScan->scan.plan.targetlist = copyObject(masterTargetList);
 
-	/* probably want to do this where we add sublinks to the master plan */
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_master_planner.c:210]: what is the reason for removing this? To be more specific, I expected to see we set `masterQuery->hasSubLinks` somewhere else, but we don't anymore?

File: src/include/distributed/multi_physical_planner.h [hunk 3]
```diff
@@ -409,7 +405,8 @@ typedef struct DistributedPlan
 	 * contains the subplans generated part of the DistributedPlan.
 	 *
 	 * On the other hand, usedSubPlanNodeList keeps track of which subPlans
-	 * are used within this distributed plan.
+	 * are used within this distributed plan as a list of
+	 * UsedDistributedSubPlan pointers.
```
Comment (onderkalaci) [inline src/include/distributed/multi_physical_planner.h:409]: As I'm getting used to having the same ids for different UsedsubPlan in the list change, I think it'd be nice to have the same explicit comment here:
```
* The list may contain duplicates if the subplan is referenced multiple
 * times.
```

File: src/test/regress/expected/multi_subquery.out [hunk 4]
```diff
@@ -911,8 +911,16 @@ RESET citus.coordinator_aggregation_strategy;
 SELECT t1.event_type FROM events_table t1
 GROUP BY t1.event_type HAVING t1.event_type > corr(t1.value_3, t1.value_2 + (SELECT t2.value_2 FROM users_table t2 ORDER BY 1 DESC LIMIT 1))
 ORDER BY 1;
-ERROR:  result "68_1" does not exist
-CONTEXT:  while executing command on localhost:xxxxx
+ event_type
```
Comment (onderkalaci) [inline src/test/regress/expected/multi_subquery.out:914]: might be nice to add this query as well: https://github.com/citusdata/citus/pull/3709/files#diff-14b324e6d5be7acd78f5be06eabddd3fR113

File: src/backend/distributed/planner/multi_master_planner.c (hunk 2 above)
Comment (marcocitus) [reply src/backend/distributed/planner/multi_master_planner.c:210]: We do in BuildJobQuery. Both masterQuery and jobQuery are created by BuildJobQuery.
