### PR TITLE
Disallow volatile functions on single shard update subqueries

### LINKED ISSUE #2148: Volatile functions in subqueries in UPDATE incorrectly evaluated on coordinator
If I run the following command on the master branch:

```
CREATE TABLE sessions(session_id int, priority double precision);
SELECT create_distributed_table('sessions', 'session_id');
INSERT INTO sessions VALUES (1);
INSERT INTO sessions VALUES (2);
UPDATE sessions s SET priority = r.random FROM (SELECT session_id, random() FROM sessions) r WHERE s.session_id = r.session_id;

SELECT * FROM sessions;
 session_id │     priority      
────────────┼───────────────────
          1 │ 0.706227001734078
          2 │ 0.706227001734078
(2 rows)
```

All rows are assigned the same priority, but the Postgres behaviour is to re-evaluate `random()` for every row. The problem is that the coordinator evaluates the `random()`, though we should be erroring out when there's a volatile function.

### PR DESCRIPTION
**Pull request by hanefi**
DESCRIPTION: Disallows volatile functions in UPDATE subqueries.

If there is a volatile function in the subquery of an UPDATE query, it was incorrectly evaluated on the coordinator node, as mentioned on https://github.com/citusdata/citus/issues/2148#issuecomment-504430905 :
```
UPDATE test SET y = 3 WHERE x = 3 AND y IN (SELECT y FROM test WHERE x = 3 AND y > random());
LOG:  issuing UPDATE public.test_102738 test SET y = 3 WHERE ((x OPERATOR(pg_catalog.=) 3) AND (y OPERATOR(pg_catalog.=) ANY (SELECT test_1.y FROM public.test_102738 test_1 WHERE ((test_1.x OPERATOR(pg_catalog.=) 3) AND ((test_1.y)::double precision OPERATOR(pg_catalog.>) '0.731105228886008'::double precision)))))
DETAIL:  on server localhost:9701
```

The same query now returns the error message:
```
ERROR:  0A000: functions used in UPDATE queries on distributed tables must not be VOLATILE
LOCATION:  SingleShardModifyQuerySupported, multi_router_planner.c:1290
```

This PR aims to resolve that by erroring out to prevent diverting from Vanilla behavior.

Note: I removed a test introduced in #3625 as it is no longer valid because it contains a volatile function in a subquery. It can possibly be rewritten, and I do not yet know how.

Fixes #2148

### CODE REVIEW

File: src/backend/distributed/planner/multi_router_planner.c [hunk 1]
```diff
@@ -1261,6 +1274,28 @@ MultiShardModifyQuerySupported(Query *originalQuery,
...
+/*
+ * SingleShardModifyQuerySupported returns the error message if the modify query is
+ * not routable, otherwise it returns NULL.
+ */
+static DeferredErrorMessage *
+SingleShardModifyQuerySupported(Query *originalQuery,
+								PlannerRestrictionContext *plannerRestrictionContext)
+{
+	DeferredErrorMessage *errorMessage = NULL;
+	if (FindNodeMatchingCheckFunction((Node *) originalQuery,
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_router_planner.c:1286]: Maybe add a comment on why we're disallowing volatile functions:

We currently do not support volatile functions in update/delete statements because the function evaluation logic does not know how to distinguish volatile functions (that need to be evaluated per row) from stable functions (that need to be evaluated per query), and it is also not safe to push the volatile functions down on replicated tables.

File: src/backend/distributed/planner/multi_router_planner.c [hunk 2]
```diff
@@ -1061,10 +1064,20 @@ ModifyQuerySupported(Query *queryTree, Query *originalQuery, bool multiShardQuer
...
+		DeferredErrorMessage *errorMessage = NULL;
+
+		if (multiShardQuery)
+		{
+			errorMessage = MultiShardModifyQuerySupported(originalQuery,
+														  plannerRestrictionContext);
+		}
+		else
+		{
+			errorMessage = SingleShardModifyQuerySupported(originalQuery,
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_router_planner.c:1078]: kind of wonder whether we should change ModifyQuery -> UpdateDelete in these names.

**Review by marcocitus — APPROVED** [review]
