### PR TITLE
invalidate plan cache in master_update_node

### LINKED ISSUE #3743: master_update_node does not work when using dbcp
### master_update_node does not work when using dbcp
* **version** : citus-v9.1.2
* **symptom** : master_update_node does not work when using dbcp

* I have 2 worker groups. Each group has a primary and a standby.
```sql
-- two dist nodes
pgdb# select nodeid, nodename, nodeport from pg_dist_node;
 nodeid |       nodename       | nodeport 
--------+----------------------+----------
      1 | dev-testcitus003-g0  |     5432
      2 | dev-testcitus005-g1  |     5432

--Each group has a primary and a standby.
               Name |   Port | Group |  Node |     Current State |    Assigned State
---------------------+--------+-------+-------+-------------------+------------------
dev-testcitus003-g0 |   5432 |     0 |     1 |           primary |           primary
dev-testcitus004-g0 |   5432 |     0 |     2 |         secondary |         secondary
dev-testcitus005-g1 |   5432 |     1 |     3 |           primary |           primary
dev-testcitus006-g1 |   5432 |     1 |     4 |         secondary |         secondary

```
In my case, the following error occurred in my application
when dev-testcitus003-g0 failed and dev-testcitus004-g0 was promoted.

```java
org.postgresql.util.PSQLException: ERROR: connection error: dev-testcitus003-g0:5432
  Detail: could not connect to server: Connection refused
	Is the server running on host "dev-testcitus003-g0" (10.113.255.1) and accepting
	TCP/IP connections on port 5432?
```
so, I updated work node metadata on the coordinator.
and I performed an ad-hoc query via psql to confirm that there was no problem.
Everything was perfect.
```sql
--master_update_node
pgdb# select master_update_node(1, 'dev-testcitus004-g0', 5432);

--test : OK! 
pgdb# select count(*) from ads;
 count 
-------
  4766
(1 row)

```
But my application was still throwing errors.
The errors seemed to be still referring to the old primary worker node.
```java
org.postgresql.util.PSQLException: ERROR: connection error: dev-testcitus003-g0:5432
  Detail: could not connect to server: Connection refused
	Is the server running on host "dev-testcitus003-g0" (10.113.255.1) and accepting
	TCP/IP connections on port 5432?
```
Of course, I know how to fix it with validationQuery of Apache commons-dbcp.
But I think the master_update_node function should work properly.

Could I get some help please.

Regards,
Han

### PR DESCRIPTION
**Pull request by SaitTalhaNisanci**
DESCRIPTION: invalidate the plan cache in master_update_node

If a plan is cached by postgres but a user uses master_update_node, then
when the plan cache is used for the updated node, they will get the old
nodename/nodepost in the plan. This is because the plan cache doesn't
know about the master_update_node. This could be a problem in prepared
statements or anything that goes into plancache. As a solution the plan
cache is invalidated inside master_update_node.

Fixes #3743.

### CODE REVIEW

File: src/backend/distributed/metadata/node_metadata.c [hunk 1]
```diff
@@ -724,6 +725,12 @@ master_update_node(PG_FUNCTION_ARGS)
 		LockShardsInPlacementListMetadata(placementList, AccessExclusiveLock);
 	}
 
+	/*
+	 * if we have planned statements such as prepared statements, we should clear the cache so that
+	 * the planned cache doesn't return the old nodename/nodepost.
+	 */
+	ResetPlanCache();
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/metadata/node_metadata.c:732]: Is it enough to run this only in this node? Say if worker1 has a plancache and we run master_update_node for worker1, then if we run something directly in worker1 it might actually cause a problem.

I think we should add more tests.

Comment (marcocitus) [reply src/backend/distributed/metadata/node_metadata.c:732]: In the procedure call delegation / MX case, the sessions on the workers have prepared statements. When a master_update_node happens, we ultimately resync the metadata from the maintendance daemon:
https://github.com/citusdata/citus/blob/master/src/backend/distributed/metadata/metadata_sync.c#L1383

That will effectively drop all the distributed tables and recreate them, which would certainly clear the prepared statement cache.

This area does require more attention, e.g. does this always work correctly in the rebalancer case? (perhaps it does)

Comment (SaitTalhaNisanci) [reply src/backend/distributed/metadata/node_metadata.c:732]: Should we add rebalancer tests too?

File: src/backend/distributed/sql/udfs/invalidate_inactive_shared_connections/latest.sql [hunk 2]
```diff
@@ -0,0 +1,10 @@
+CREATE OR REPLACE FUNCTION pg_catalog.invalidate_inactive_shared_connections()
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/sql/udfs/invalidate_inactive_shared_connections/latest.sql:1]: I moved this from test to UDF since we will use this in MX case.

Comment (onderkalaci) [reply src/backend/distributed/sql/udfs/invalidate_inactive_shared_connections/latest.sql:1]: Thanks @SaitTalhaNisanci, @marcocitus noted that we need to invalidate the inactive shared connections on the MX worker nodes. And, we need a SQL interface anyway, so I can use this.

File: src/test/regress/expected/ensure_no_shared_connection_leak.out [hunk 3]
```diff
@@ -117,6 +117,13 @@ SELECT pg_reload_conf();
 
 \c - - - :master_port
 SET search_path TO ensure_no_shared_connection_leak;
+-- invalidate inactive shared connections
```
Comment (onderkalaci) [inline src/test/regress/expected/ensure_no_shared_connection_leak.out:120]: minor: `invalidate inactive shared connections` -> `invalidate inactive shared connections to ensure  that test output doesn't change due to inactive nodes`

**Comment by SaitTalhaNisanci** [comment]
Is this PR good to merge @marcocitus ?

File: src/backend/distributed/connection/shared_connection_stats.c [hunk 4]
```diff
@@ -109,6 +109,18 @@ static uint32 SharedConnectionHashHash(const void *key, Size keysize);
...
+PG_FUNCTION_INFO_V1(invalidate_inactive_shared_connections);
+
+/*
+ * invalidate_inactive_shared_connections invalidates inactive
+ * and not used shared connections by removing from the global hash.
+ */
+Datum
+invalidate_inactive_shared_connections(PG_FUNCTION_ARGS)
+{
+	RemoveInactiveNodesFromSharedConnections();
```
Comment (marcocitus) [inline src/backend/distributed/connection/shared_connection_stats.c:121]: I'd prefer if `citus_remote_connection_stats` would just omit inactive connections instead of introducing this UDF.

Comment (SaitTalhaNisanci) [reply src/backend/distributed/connection/shared_connection_stats.c:121]: So are you suggesting that we call `RemoveInactiveNodesFromSharedConnections` at the beginning of `citus_remote_connection_stats`?

Comment (onderkalaci) [reply src/backend/distributed/connection/shared_connection_stats.c:121]: I guess we'll need such a UDF  anyway for  https://github.com/citusdata/citus/pull/3765 ?

Comment (onderkalaci) [reply src/backend/distributed/connection/shared_connection_stats.c:121]: (we can do what Marco suggests here, and  add the UDF in  that PR if that makes more sense)

File: src/backend/distributed/sql/udfs/invalidate_inactive_shared_connections/latest.sql (hunk 2 above)
Comment (marcocitus) [reply src/backend/distributed/sql/udfs/invalidate_inactive_shared_connections/latest.sql:1]: Can we cherry pick this commit onto the relevant branch? It's hard for me to assess whether this is useful / necessary / right in the context of a different PR.

File: src/backend/distributed/connection/shared_connection_stats.c (hunk 4 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/connection/shared_connection_stats.c:121]: Both of them are okay with me, how do we want to proceed?

Comment (marcocitus) [reply src/backend/distributed/connection/shared_connection_stats.c:121]: decouple the PRs by removing the function from here and cherry-picking it in #3765.

File: src/backend/distributed/sql/udfs/invalidate_inactive_shared_connections/latest.sql (hunk 2 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/sql/udfs/invalidate_inactive_shared_connections/latest.sql:1]: Sorry I saw this message just now.

File: src/test/regress/expected/ensure_no_shared_connection_leak.out (hunk 3 above)
Comment (SaitTalhaNisanci) [reply src/test/regress/expected/ensure_no_shared_connection_leak.out:120]: As I removed this udf, this is no more relevant.

File: src/backend/distributed/connection/shared_connection_stats.c [hunk 5]
```diff
@@ -121,6 +120,7 @@ citus_remote_connection_stats(PG_FUNCTION_ARGS)
 	TupleDesc tupleDescriptor = NULL;
 
 	CheckCitusVersion(ERROR);
+	RemoveInactiveNodesFromSharedConnections();
```
Comment (marcocitus) [inline src/backend/distributed/connection/shared_connection_stats.c:123]: We should be a little careful about calling this function, since it can have weird side effects, e.g. this would wipe out all the entries:

```sql
BEGIN;
DELETE FROM pg_dist_node;
SELECT * FROM citus_remote_connection_stats();
END;
```

Maybe just filter out the inactive nodes in StoreAllRemoteConnectionStats?

Comment (SaitTalhaNisanci) [reply src/backend/distributed/connection/shared_connection_stats.c]: I have moved the filtering to StoreAllRemoteConnectionStats
