### PR TITLE
Prevent empty placement creation in the coordinator

### LINKED ISSUE #4237: master_append_table_to_shard()  fails when the placement is on the same node
```SQL
CREATE TABLE test_append_table(a int);
SELECT create_distributed_table('test_append_table', 'a', 'append');

SELECT master_create_empty_shard('test_append_table');
 master_create_empty_shard
---------------------------------------------------------------------
                   102170
(1 row)

CREATE TABLE append_stage_table(a int);

SELECT * FROM master_append_table_to_shard(102170, 'append_stage_table', 'localhost', :master_port);
ERROR:  canceling the transaction since it was involved in a distributed deadlock

```

### PR DESCRIPTION
**Pull request by naisila**
DESCRIPTION: Prevent empty placement creation in the coordinator when executing `master_create_empty_shard()` (valid when the coordinator is also a worker-node)

This is the first attempt on solving this problem.

TODO:

- [x] discuss for a possible better solution

- [x] tests

Trying to fix #4237

### CODE REVIEW

File: src/backend/distributed/operations/stage_protocol.c [hunk 1]
```diff
@@ -177,6 +178,17 @@ master_create_empty_shard(PG_FUNCTION_ARGS)
 		attemptableNodeCount = ShardReplicationFactor;
 	}
 
+	/* check if we are trying to create an empty placement on the coordinator */
```
Comment (onderkalaci) [inline src/backend/distributed/operations/stage_protocol.c:181]: This error check seems a little implicit. It is not trivial for the readers of the code that `workerNodeListLength + 1 == ShardReplicationFactor` means we are not creating the placement on the coordinator. Also, do we strictly need this check? Wouldn't we end up the check in `CreateAppendDistributedShardPlacements` if we cannot all the necessary placements? 

```C

	/* check if we created enough shard replicas */
	if (placementsCreated < replicationFactor)
	{
		ereport(ERROR, (errmsg("could only create %u of %u of required shard replicas",
							   placementsCreated, replicationFactor)));
	}
```



Overall, to keep the changes small, would it make sense to have a check on `CreateAppendDistributedShardPlacements ()` such that `if (NodeIsCoordinator(workerNode))`, Citus skips (e.g., `continue`) creating placements on the node, and giving a `NOTICE` level message stating that creating placements for the append partitioned tables on the coordinator is not allowed. And, if there not enough placements that are created, Citus would throw and error as stated above.

Comment (naisila) [reply src/backend/distributed/operations/stage_protocol.c:181]: Makes sense. The idea was to explain the error further when there aren't enough shard replicas created because the coordinator is a worker node, so the `NOTICE` you suggested does the work with smaller changes (it is also more readable).

**Review by halilozanakgul — CHANGES_REQUESTED** [review]
This prevents creating a placement on the coordinator but I'm still not able to append a table to that shard.

```
SELECT master_add_node('localhost', 9700, groupid:=0);
SELECT 1 FROM master_set_node_property('localhost', 9700, 'shouldhaveshards', true);

SET citus.shard_replication_factor TO 3;
CREATE TABLE oz (a INT);
SELECT create_distributed_table ('oz', 'a', 'append');

SELECT master_create_empty_shard('oz');

NOTICE:  Creating placements for the append partitioned tables on the coordinator is not allowed.
ERROR:  could only create 2 of 3 of required shard replicas
```
Even though there is an `ERROR` I thought the message meant 2 of the shards replicas are ready to use. And I checked the workers and the shards were there. Then I tried:
```
CREATE TABLE an (a INT);
INSERT INTO an VALUES (1), (2);
SELECT master_append_table_to_shard(<shard_id>, 'an', 'localhost', '9700');

ERROR:  could not find valid entry for shard <shard_id>
```

After discussing with @naisila we realised even though there are shards on the workers the `pg_dist_placement` is empty. (I got the `<shard_id>` by looking at the shards at workers.)

This looks like a different issue but I think we need to at least tell user to reduce `citus.shard_replication_factor`.

File: src/backend/distributed/operations/stage_protocol.c [hunk 2]
```diff
@@ -411,6 +411,14 @@ CreateAppendDistributedShardPlacements(Oid relationId, int64 shardId,
 	{
 		int workerNodeIndex = attemptNumber % workerNodeCount;
 		WorkerNode *workerNode = (WorkerNode *) list_nth(workerNodeList, workerNodeIndex);
+
+		if (NodeIsCoordinator(workerNode))
+		{
+			ereport(NOTICE, (errmsg(
```
Comment (marcocitus) [inline src/backend/distributed/operations/stage_protocol.c:417]: if it's never allowed, could we maybe exclude it from the list in master_create_empty_shard? (i.e. ignore shouldhaveshards)

Comment (naisila) [reply src/backend/distributed/operations/stage_protocol.c:417]: It is actually never allowed, and what you mentioned was the first draft, commits have disappeared because of my force push :)

A new variant of `DistributedTablePlacementNodeList`, for example `AppendDistributedTablePlacementNodeList` can be done. However, more checks are needed in the shard placement policies other than round robin, because they don't use the list from `DistributedTablePlacementNodeList`. https://github.com/citusdata/citus/blob/master/src/backend/distributed/operations/stage_protocol.c#L185

With the current solution, there are minimal changes and also it can be understood clearly if not enough shard replicas were created because of prevention of empty placement in the coordinator.

Comment (naisila) [reply src/backend/distributed/operations/stage_protocol.c:417]: @marcocitus @halilozanakgul my first solution is not shown here because of force push but you can check from https://github.com/citusdata/citus/tree/issue4237-2. It probably needs improvement but it applies the idea of not putting the coordinator in any list beforehand. As I said, in my solution I have to take care of different shard_placement policies (maybe I am missing something ?). On the other hand, checking it afterwards like @onderkalaci suggested is brief and quite readable. 

@halilozanakgul in that solution I am also giving a hint of reducing shard_replication_factor.

I would appreciate your opinions to decide which approach is best for this. :)

Comment (marcocitus) [reply src/backend/distributed/operations/stage_protocol.c:417]: > With the current solution, there are minimal changes and also it can be understood clearly if not enough shard replicas were created because of prevention of empty placement in the coordinator.

ok, that's reasonable. 

Could you:
a) Add a test that is successful (e.g. replication factor 2)
b) check the group IDs of the shard in pg_dist_placement in the test
b) Maybe adjust the notice. "Is not allowed" sounds security related, but it's just that we haven't implemented it. We could say "creating append-distributed shards placements on the coordinator is not supported, skipping coordinator", or just omit the notice.

Comment (naisila) [reply src/backend/distributed/operations/stage_protocol.c:417]: @marcocitus done.
I think it's better to mention that we are skipping coordinator so I didn't omit it.

**Review by marcocitus — APPROVED** [review]

File: src/test/regress/sql/coordinator_shouldhaveshards.sql [hunk 3]
```diff
@@ -214,13 +214,28 @@ INSERT INTO ref_table SELECT *, * FROM generate_series(1, 100);
 SELECT COUNT(*) FROM test JOIN ref_table USING(x);
 ROLLBACK;
 
+-- issue #4237
```
Comment (halilozanakgul) [inline src/test/regress/sql/coordinator_shouldhaveshards.sql:217]: Could you also put a small explanation here?

File: src/test/regress/sql/coordinator_shouldhaveshards.sql [hunk 4]
```diff
@@ -214,13 +214,28 @@ INSERT INTO ref_table SELECT *, * FROM generate_series(1, 100);
...
+SELECT create_distributed_table('test_append_table', 'a', 'append');
+-- this will fail since it will try to create an empty placement in the
+-- coordinator as well
+SET citus.shard_replication_factor TO 3;
+SELECT master_create_empty_shard('test_append_table');
+-- this will create an empty shard with replicas in the two worker nodes
+SET citus.shard_replication_factor TO 2;
+SELECT master_create_empty_shard('test_append_table');
+-- verify groupid is not 0 for each placement
+SELECT COUNT(*) FROM pg_dist_placement WHERE shardid = 1503037 AND groupid > 0;
```
Comment (halilozanakgul) [inline src/test/regress/sql/coordinator_shouldhaveshards.sql:228]: The `shardid` will change when new tests are added. You can try to do a join between `pg_dist_placement` and `pg_dist_shard`.

**Review by halilozanakgul — CHANGES_REQUESTED** [review]

File: src/test/regress/sql/coordinator_shouldhaveshards.sql (hunk 4 above)
Comment (naisila) [reply src/test/regress/sql/coordinator_shouldhaveshards.sql:228]: I thought new tests will be added below it. The shardid is an output of line 226 as well (so I put `1503037` in `.out` file) and I don't have an idea how to omit that shardid.

Comment (halilozanakgul) [reply src/test/regress/sql/coordinator_shouldhaveshards.sql:228]: Doing `SELECT 1 FROM master_create_empty_shard('test_append_table')` would fix for the line above.
And you could do something like this
```
SELECT COUNT(*) FROM pg_dist_placement p, pg_dist_shard s WHERE p.shardid=s.shardid AND s.logicalrelid = 'test_append_table'::regclass AND p.groupid > 0;
```

But I also saw some examples in the tests that set a new_shard_id parameter, maybe that could work too:
```
SELECT master_create_empty_shard('...') AS new_shard_id
\gset
```

Comment (naisila) [reply src/test/regress/sql/coordinator_shouldhaveshards.sql:228]: Makes sense, thanks!

**Review by halilozanakgul — APPROVED** [review]
