### PR TITLE
Prevent failures on partitioned distributed tables with statistics objects on PG 15

### LINKED ISSUE #6329: Unexpected error when querying a distributed partitioned table with statistics
PG15beta4, Relevant PG commits: https://github.com/postgres/postgres/commit/20b9fa308ebf7d4a26ac53804fce1c30f781d60c https://github.com/postgres/postgres/commit/269b532aef55a579ae02a3e8e8df14101570dfd9

```SQL
-- create parent table
CREATE TABLE stxdinp(i int, a int, b int) PARTITION BY RANGE (i);

-- create partition
CREATE TABLE stxdinp1 PARTITION OF stxdinp FOR VALUES FROM (1) TO (100);

-- populate table
INSERT INTO stxdinp SELECT 1, a/100, a/100 FROM generate_series(1, 999) a;

-- create extended statistics
CREATE STATISTICS stxdinp ON a, b FROM stxdinp;

-- distribute parent table
SELECT create_distributed_table('stxdinp', 'i');

-- run select query, works fine
SELECT a, b FROM stxdinp GROUP BY 1, 2;
 a | b
---+---
 1 | 1
 3 | 3
 7 | 7
 2 | 2
 8 | 8
 0 | 0
 5 | 5
 6 | 6
 9 | 9
 4 | 4
(10 rows)

-- partitions are processed recursively
VACUUM ANALYZE stxdinp;

-- UNEXPECTED ERROR FACED
SELECT a, b FROM stxdinp GROUP BY 1, 2;
ERROR:  cache lookup failed for statistics object 17135
```

**Note: it doesn't matter whether the statistics is created before or after distributing the table**

### PR DESCRIPTION
**Pull request by onderkalaci**
Fixes #6329

Comment from the code is clear on this:
```
/*
 * The statistics objects of the distributed table are not relevant
 * for the distributed planning, so we can override it. *
 * Normally, we should not need this. However, the combination of
 * Postgres commit 269b532aef55a579ae02a3e8e8df14101570dfd9 and
 * Citus function AdjustPartitioningForDistributedPlanning()
 * forces us to do this. The commit expects statistics objects
 * of partitions to have "inh" flag set properly. Whereas, the
 * function overrides "inh" flag. To avoid Postgres to throw error,
 * we override statlist such that Postgres does not try to process
 * any statistics objects during the standard_planner() on the
 * coordinator. In the end, we do not need the standard_planner()
 * on the coordinator to generate an optimized plan. We call
 * into standard_planner() for other purposes, such as generating the
 * relationRestrictionContext here. *
 * AdjustPartitioningForDistributedPlanning() is a hack that we use
 * to prevent Postgres' standard_planner() to expand all the partitions
 * for the distributed planning when a distributed partitioned table
 * is queried. It is required for both correctness and performance
 * reasons. Although we can eliminate the use of the function for
 * the correctness (e.g., make sure that rest of the planner can handle
 * partitions), it's performance implication is hard to avoid. Certain
 * planning logic of Citus (such as router or query pushdown) relies
 * heavily on the relationRestrictionList. If
 * AdjustPartitioningForDistributedPlanning() is removed, all the
 * partitions show up in the, causing high planning times for
 * such queries. */
```

### CODE REVIEW

File: src/backend/distributed/planner/distributed_planner.c [hunk 1]
```diff
@@ -1919,10 +1919,42 @@ multi_relation_restriction_hook(PlannerInfo *root, RelOptInfo *relOptInfo,
...
+		 * reasons. Although we can eliminate the use of the function for
+		 * the correctness (e.g., make sure that rest of the planner can handle
+		 * partitions), it's performance implication is hard to avoid. Certain
+		 * planning logic of Citus (such as router or query pushdown) relies
+		 * heavily on the relationRestrictionList. If
+		 * AdjustPartitioningForDistributedPlanning() is removed, all the
+		 * partitions show up in the, causing high planning times for
+		 * such queries.
+		 */
+		relOptInfo->statlist = NIL;
```
Comment (marcocitus) [inline src/backend/distributed/planner/distributed_planner.c:1956]: thanks for the thorough explanation

main danger is that we're in the middle of the planner, so if it relies on this being set based on earlier state then we're in trouble, but it doesn't seem like there are a lot of callers

Comment (onderkalaci) [reply src/backend/distributed/planner/distributed_planner.c:1956]: I can think of two options for the future:

- Do not use standard_planner() on the coordinator, only extract the restriction related information (as you noted in the private chat)
- Do not use AdjustPartitioningForDistributedPlanning(). I think this is doable, but we should be careful with the performance implications as Postgres generates restrict infos per partition. So `restrictionContext->relationRestrictionList` and `joinRestrictionContext->joinRestrictionList` becomes huge lists when # partitions is high

**Review by naisila — APPROVED** [review]
LGTM. Tested the following scenarios:

- partition column being distribution column
- shards in coordinator
- citus local table
- creating the statistics after distributing the table
- we already can't have reference partitioned tale
```SQL
-- a combination of the following commands
-- also a straight test to run all of them
SELECT 1 FROM master_add_node('localhost', 9700, groupId => 0);
CREATE TABLE parent(a int, b int) PARTITION BY RANGE (a);
CREATE TABLE child PARTITION OF parent FOR VALUES FROM (1) TO (100);
INSERT INTO parent SELECT a, 2 * a FROM generate_series(1, 99) a;
SELECT create_distributed_table('parent', 'a');
CREATE STATISTICS stat1 ON a, b FROM parent;
SELECT count(*) FROM parent;
VACUUM ANALYZE parent;
SELECT count(*) FROM parent;
SELECT undistribute_table('parent');
SELECT citus_add_local_table_to_metadata('parent');
SELECT count(*) FROM parent;
VACUUM ANALYZE parent;
SELECT count(*) FROM parent;
```

File: src/backend/distributed/planner/distributed_planner.c (hunk 1 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/distributed_planner.c:1956]: Looking into this thread on psql-hackers (https://www.postgresql.org/message-id/flat/CAMbWs48pb_-fV%3DkG8CRVvZEHhCgTFUi6XY6UPK9Ob32LzH%2Bd8g%40mail.gmail.com#eec957e600172936e233aed44daf22af), I started to think whether our case can also be resolved with that patch.

Wanted to share to keep an eye on this
