### PR TITLE
Avoid error during CREATE INDEX IF NOT EXISTS

### LINKED ISSUE #926: CREATE INDEX if not exists doesn't work with distributed tables
```
CREATE TABLE t1(c1 int);
SELECT master_create_distributed_table('t1','c1','hash');
SELECT master_create_worker_shards('t1',16,1);
CREATE INDEX if not exists i1 ON t1(c1);

CREATE INDEX if not exists i1 ON t1(c1);
CREATE INDEX
CREATE INDEX if not exists i1 ON t1(c1);
ERROR:  relation "i1" already exists
```

### PR DESCRIPTION
**Pull request by samay-sharma**
Previously, we threw an error when we ran CREATE INDEX IF NOT EXISTS
with an already existing index. This change enables expected behavior by
checking if the statement has IF NOT EXISTS before throwing the error.
We also ensure that we don't execute the command on the workers, if an
index already exists on the master.

Fixes #926

### CODE REVIEW

**Comment by samay-sharma** [comment]
@sumedhpathak : Could you assign a reviewer?

File: src/backend/distributed/executor/multi_utility.c [hunk 1]
```diff
@@ -630,10 +630,22 @@ ProcessIndexStmt(IndexStmt *createIndexStatement, const char *createIndexCommand
...
 		if (isDistributedRelation)
 		{
+			Oid namespaceId = InvalidOid;
+			Oid indexRelationId = InvalidOid;
 			ErrorIfUnsupportedIndexStmt(createIndexStatement);
 
-			/* if it is supported, go ahead and execute the command */
-			ExecuteDistributedDDLCommand(relationId, createIndexCommand, isTopLevel);
+			/*
+			 * If the command is supported, and the index does not exist,
```
Comment (jasonmp85) [inline src/backend/distributed/executor/multi_utility.c]: This comment is actually more misleading the helpful. It comes right before whether you check if the index exists, and is _after_ the part that checks whether the command is supported. It looked like an outdated comment to me.

Can this be changed to _Skip sending distributed CREATE INDEX statements when an index of that name already exists_? That better states our logic (since AFAIK, the local command continues execution).

File: src/backend/distributed/executor/multi_utility.c [hunk 2]
```diff
@@ -630,10 +630,22 @@ ProcessIndexStmt(IndexStmt *createIndexStatement, const char *createIndexCommand
 
 		if (isDistributedRelation)
 		{
+			Oid namespaceId = InvalidOid;
+			Oid indexRelationId = InvalidOid;
 			ErrorIfUnsupportedIndexStmt(createIndexStatement);
```
Comment (jasonmp85) [inline src/backend/distributed/executor/multi_utility.c]: Wouldn't we usually have a newline here?

File: src/backend/distributed/executor/multi_utility.c [hunk 3]
```diff
@@ -630,10 +630,22 @@ ProcessIndexStmt(IndexStmt *createIndexStatement, const char *createIndexCommand
...
 
-			/* if it is supported, go ahead and execute the command */
-			ExecuteDistributedDDLCommand(relationId, createIndexCommand, isTopLevel);
+			/*
+			 * If the command is supported, and the index does not exist,
+			 * go ahead and execute the command.
+			 */
+			namespaceId = get_namespace_oid(createIndexStatement->relation->schemaname,
```
Comment (jasonmp85) [inline src/backend/distributed/executor/multi_utility.c]: Actually, now that I've looked at this a little longer, I dislike how we duplicate the `get_namespace`/`get_relname` calls between here and `ErrorIfUnsupportedIndexStmt`, which is only called by this function in the first place.

It could be argued that `ErrorIfUnsupportedIndexStmt` shouldn't even be checking for duplicates in the first place, as duplicate indexes aren't actually about whether or not we support a given statement, but about the state of the database system when the `CREATE INDEX` runs.

With that in mind, I think this would be easier to reason about if the "what to do about duplicates" logic were all in one place, i.e. remove the duplicate-checking code from `ErrorIfUnsupportedIndexStmt` and put it in the `if` statement, like so…

```c
char *indexName = createIndexStatement->idxname;
Oid namespaceId = InvalidOid;
Oid indexRelationId = InvalidOid; 

ErrorIfUnsupportedIndexStmt(createIndexStatement);

namespaceId = get_namespace_oid(createIndexStatement->relation->schemaname,
								false);
indexRelationId = get_relname_relid(indexName, namespaceId);

/* If the index name is in use but no `IF EXISTS` option was used, error out */
if (OidIsValid(indexRelationId) && !createIndexStatement->if_not_exists)
{
	ereport(ERROR, (errcode(ERRCODE_DUPLICATE_TABLE),
			errmsg("relation \"%s\" already exists", indexName)));
}

/* Otherwise, it's safe to send the DDL command to worker nodes */
ExecuteDistributedDDLCommand(relationId, createIndexCommand, isTopLevel);
```

File: src/backend/distributed/executor/multi_utility.c (hunk 1 above)
Comment (jasonmp85) [inline src/backend/distributed/executor/multi_utility.c]: Deleting this comment in favor of my other suggestion, which I like better for readability.
