### PR TITLE
Fix Shard Pruning Problem With Subqueries on VARCHAR Partition Columns

### LINKED ISSUE #375: Subquery pushdown does not support shard prunning on varchar partition columns for hash partitioned tables
Steps to reproduce:

```SQL
CREATE TABLE test 
(
   a varchar,
   b int
);

SELECT master_create_distributed_table('test', 'a', 'hash');
SELECT master_create_worker_shards('test', 4, 1);

set citus.subquery_pushdown to true;
set client_min_messages to debug2;

SELECT 
	*
FROM
(
    (
        SELECT 
            count(*)
        FROM 
            test
        where
            a = 'val'
      GROUP BY a
    )
) as foo;
```

When the partition column is changed to text (or int) the shard pruning logic works as expected.

Might be related to #328

### PR DESCRIPTION
**Pull request by aamederen**
Prior to this change, shard pruning couldn't be done if:
- Table is hash-distributed
- Partition column of is VARCHAR
- Query to be pruned is a subquery

There were two problems:
- A bug in left-side/right-side checks for the partition column
- We were not considering relabeled types (VARCHAR was relabeled as TEXT)

### CODE REVIEW

**Comment by sumedhpathak** [comment]
He @aamederen Could you update the title with something more descriptive?

**Comment by aamederen** [comment]
Hey @sumedhpathak I have updated the the title.
About the Travis health checks, It was an issue with PG9.4 on Debug2 level messages on Drop Table command. Fixed it as well.

File: src/backend/distributed/planner/multi_logical_optimizer.c [hunk 1]
```diff
@@ -3742,14 +3742,14 @@ PartitionColumnOpExpressionList(Query *query)
 			continue;
 		}
 
-		leftArgument = (Node *) linitial(argumentList);
-		rightArgument = (Node *) lsecond(argumentList);
+		leftArgument = strip_implicit_coercions((Node *) linitial(argumentList));
```
Comment (metdos) [inline src/backend/distributed/planner/multi_logical_optimizer.c]: Here, we do two things at one line;
i. We get the data in the first cell of a List
ii. We apply coercion strip

For coding convention and better readability, we prefer to do this kind of work on individual code lines. An example from the code base;

```
Node *leftOpExpression = linitial(arrayOperatorExpression->args);
Node *strippedLeftOpExpression = strip_implicit_coercions(leftOpExpression);
```

File: src/test/regress/input/multi_subquery.source [hunk 2]
```diff
@@ -294,3 +294,31 @@ FROM
...
+
+SELECT * FROM 
+	(SELECT count(*) FROM subquery_pruning_varchar_test_table WHERE a = 'onder' GROUP BY a) 
+AS foo;
+
+SELECT * FROM 
+	(SELECT count(*) FROM subquery_pruning_varchar_test_table WHERE 'eren' = a GROUP BY a)
+AS foo;
+
+SET client_min_messages TO INFO;
```
Comment (onderkalaci) [inline src/test/regress/input/multi_subquery.source]: I just realized that the default value of `client_min_messages` is `NOTICE`. Could you please check whether do we need `NOTICE` or `INFO` here (i.e., What is the value of `client_min_messages` before it is set to `DEBUG2`)?

Comment (aamederen) [inline src/test/regress/input/multi_subquery.source]: I checked that out and you are right, it was NOTICE. Changed INFO to NOTICE.

**Comment by aamederen** [comment]
While searching for improvements, saw that the solution to #76 seems very similar to the solution of #375  so, I have added the solution as a different commit.

**Comment by aamederen** [comment]
Also added a fix for #379.

**Comment by jasonmp85** [comment]
I'm going to give this a deep look starting tomorrow morning; for now I'm updating #76 with the other places I thought I saw this issue in our codebase…

**Comment by aamederen** [comment]
Hey @jasonmp85, is this PR good for :shipit: ? If so, should we merge this PR and address the possible issues separately?

**Comment by jasonmp85** [comment]
@aamederen: yes. In fact, I've rebased this (I merged several other lingering PRs today) and will hit "Merge" as soon as the status checks pass.

File: src/backend/distributed/planner/multi_logical_optimizer.c [hunk 3]
```diff
@@ -2907,14 +2907,15 @@ IsPartitionColumnRecursive(Expr *columnExpression, Query *query)
 	List *rangetableList = query->rtable;
 	Index rangeTableEntryIndex = 0;
 	RangeTblEntry *rangeTableEntry = NULL;
+	Expr *strippedColumnExpression = strip_implicit_coercions(columnExpression);
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_logical_optimizer.c]: @jasonmp85  @aamederen  I get compile warnings with this line on MacOS with the following gcc:
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```
 
The warning:
```
planner/multi_logical_optimizer.c:2911:60: warning: incompatible pointer types passing 'Expr *' (aka 'struct Expr *') to parameter of type 'Node *'
      (aka 'struct Node *') [-Wincompatible-pointer-types]
        Expr *strippedColumnExpression = strip_implicit_coercions(columnExpression);
                                                                  ^~~~~~~~~~~~~~~~
/usr/local/pgsql/include/server/nodes/nodeFuncs.h:33:45: note: passing argument to parameter 'node' here
extern Node *strip_implicit_coercions(Node *node);
                                            ^
planner/multi_logical_optimizer.c:2911:8: warning: incompatible pointer types initializing 'Expr *' (aka 'struct Expr *') with an expression of type
      'Node *' (aka 'struct Node *') [-Wincompatible-pointer-types]
        Expr *strippedColumnExpression = strip_implicit_coercions(columnExpression);
```

Comment (jasonmp85) [inline src/backend/distributed/planner/multi_logical_optimizer.c]: Ugh. We need to enable -Werror in Travis. Looked OK to me but I didn't inspect warnings (I've become used to the ones we have).

Can you slap some casts in here? That's all it'll take, right?

Comment (onderkalaci) [inline src/backend/distributed/planner/multi_logical_optimizer.c]: Yeah, I think so. I'll update it to in my PR:
```C
Expr *strippedColumnExpression = strip_implicit_coercions((Node *) columnExpression);
```
But, I'm sure @anarazel will complain about why it is in fast shard pruning PR :))

Comment (onderkalaci) [inline src/backend/distributed/planner/multi_logical_optimizer.c]: Ok, so @aamederen will create a very simple PR and I'll check-in the changes.
