### PR TITLE
Columnar: disallow CREATE INDEX CONCURRENTLY

### LINKED ISSUE #4599: Crash after CREATE INDEX CONCURRENTLY when using columnar
CREATE INDEX CONCURRENTLY on columnar table errors out, but it creates an index relation anyway, which causes further queries to crash.

```
postgres(5432)=# create table t(a int, b int) using columnar ;
CREATE TABLE
Time: 3.306 ms
postgres(5432)=# create index CONCURRENTLY t_idx on t(a, b);
ERROR:  indexes not supported for columnar tables
Time: 3.041 ms
postgres(5432)=# \d t
                 Table "public.t"
 Column |  Type   | Collation | Nullable | Default 
--------+---------+-----------+----------+---------
 a      | integer |           |          | 
 b      | integer |           |          | 
Indexes:
    "t_idx" btree (a, b) INVALID

postgres(5432)=# insert into t values (1, 2);
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
Time: 317.875 ms
```

The trace in pg12 is:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f9229ee4859 in __GI_abort () at abort.c:79
#2  0x000056552315863a in ExceptionalCondition (
    conditionName=conditionName@entry=0x5655232e8aa8 "!(((_Bool) (((const void*)(tupleid) != ((void *)0)) && ((tupleid)->ip_posid != 0))))", errorType=errorType@entry=0x5655231ae01d "FailedAssertion", 
    fileName=fileName@entry=0x5655232e893d "execIndexing.c", lineNumber=lineNumber@entry=291) at assert.c:54
#3  0x0000565522eaddce in ExecInsertIndexTuples (slot=slot@entry=0x5655255b4338, 
    estate=estate@entry=0x5655255b3048, noDupErr=noDupErr@entry=false, specConflict=specConflict@entry=0x0, 
    arbiterIndexes=arbiterIndexes@entry=0x0) at execIndexing.c:291
#4  0x0000565522ed9ed9 in ExecInsert (mtstate=mtstate@entry=0x5655255b3400, slot=0x5655255b4338, 
    planSlot=planSlot@entry=0x5655255b4338, estate=estate@entry=0x5655255b3048, canSetTag=<optimized out>)
    at nodeModifyTable.c:592
#5  0x0000565522edaa99 in ExecModifyTable (pstate=0x5655255b3400) at nodeModifyTable.c:2215
#6  0x0000565522eaef53 in ExecProcNode (node=0x5655255b3400) at ../../../src/include/executor/executor.h:239
#7  ExecutePlan (execute_once=<optimized out>, dest=0x5655254712c0, direction=NoMovementScanDirection, 
    numberTuples=0, sendTuples=<optimized out>, operation=CMD_INSERT, use_parallel_mode=<optimized out>, 
    planstate=0x5655255b3400, estate=0x5655255b3048) at execMain.c:1646
#8  standard_ExecutorRun (queryDesc=queryDesc@entry=0x565525590508, 
    direction=direction@entry=ForwardScanDirection, count=count@entry=0, execute_once=execute_once@entry=true)
    at execMain.c:364
#9  0x00007f9226c6a304 in CitusExecutorRun (queryDesc=0x565525590508, direction=ForwardScanDirection, 
    count=0, execute_once=<optimized out>) at executor/multi_executor.c:217
#10 0x0000565523032990 in ProcessQuery (plan=<optimized out>, 
    sourceText=0x5655252daa18 "insert into t values (1, 2);", params=0x0, queryEnv=0x0, dest=0x5655254712c0, 
    completionTag=0x7fff3bb16230 "") at pquery.c:161
#11 0x0000565523032c0b in PortalRunMulti (portal=portal@entry=0x5655253bad78, 
    isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, 
    dest=dest@entry=0x5655254712c0, altdest=altdest@entry=0x5655254712c0, 
    completionTag=completionTag@entry=0x7fff3bb16230 "") at pquery.c:1283
```

Andres says this is the expected behaviour since CONCURRENT CREATE INDEX needs to do the work in multiple transactions, so erroring out during the index build isn't sufficient.

We raise the error in index_build_range_scan.

### PR DESCRIPTION
**Pull request by pykello**
Fixes #4599

### CODE REVIEW

File: src/backend/columnar/cstore_tableam.c [hunk 1]
```diff
@@ -1292,6 +1305,49 @@ ColumnarTableAMObjectAccessHook(ObjectAccessType access, Oid classId, Oid object
...
+ * Utility hook for columnar tables.
+ */
+static void
+ColumnarProcessUtility(PlannedStmt *pstmt,
+					   const char *queryString,
+					   ProcessUtilityContext context,
+					   ParamListInfo params,
+					   struct QueryEnvironment *queryEnv,
+					   DestReceiver *dest,
+					   QueryCompletionCompat *completionTag)
```
Comment (jeff-davis) [inline src/backend/columnar/cstore_tableam.c:1318]: Don't different versions have different signatures for the hook?

Comment (pykello) [reply src/backend/columnar/cstore_tableam.c:1318]: This is abstracted by definition of `QueryCompletionCompat` in `version_compat.c`.

**Review by jeff-davis — APPROVED** [review]
