### PR TITLE
Skip copying GENERATED ALWAYS AS STORED cols in ReplaceTable

### LINKED ISSUE #4614: Cannot alter_/undistribute_table that has generated column
```sql
CREATE TABLE generated_stored_col_test (x int, y int generated always as (x+1) stored);
SELECT create_reference_table('generated_stored_col_test');

SELECT undistribute_table('generated_stored_col_test');
NOTICE:  creating a new table for public.generated_stored_col_test
NOTICE:  Moving the data of public.generated_stored_col_test
ERROR:  cannot insert into column "y"
DETAIL:  Column "y" is a generated column.
CONTEXT:  SQL statement "INSERT INTO public.generated_stored_col_test_840664567 SELECT * FROM public.generated_stored_col_test"
```

This is because postgres doesn't allow inserting into generated columns.

### PR DESCRIPTION
**Pull request by onurctirtir**
Since undistribute_table exists in 9.5, worth to have a pr description for that. But not sure if it's worth to put a backport label.

DESCRIPTION: Fixes undistribute_table when table has column with GENERATED ALWAYS AS STORED expr

Fixes  #4614.

---

Postgres doesn't allow inserting into columns having GENERATED ALWAYS
AS (...) STORED expressions.
For this reason, when executing undistribute_table or an alter_* udf,
we should skip copying such columns.
This is not bad since Postgres would already generate such columns.

---

Also realized that ReplaceTable cannot handle GENERATED IDENTITY
columns and fix for that seems to be as simple as adding OVERRIDING
SYSTEM VALUE to INSERT... SELECT query that we execute in ReplaceTable.
Maybe we should fix this in another pr.

\+ It is not that easy as deparser still doesn't know how to generate
table creation commands when we have such identity columns. :/

### CODE REVIEW

File: src/backend/distributed/commands/alter_table.c [hunk 1]
```diff
@@ -1122,10 +1125,20 @@ ReplaceTable(Oid sourceId, Oid targetId, List *justBeforeDropCommands,
 									quote_qualified_identifier(schemaName, sourceName))));
 		}
 
-		appendStringInfo(query, "INSERT INTO %s SELECT * FROM %s",
-						 quote_qualified_identifier(schemaName, targetName),
-						 quote_qualified_identifier(schemaName, sourceName));
-		ExecuteQueryViaSPI(query->data, SPI_OK_INSERT);
+		/*
+		 * Since we wrap target columns with paranthesis, skip executing
```
Comment (onurctirtir) [inline src/backend/distributed/commands/alter_table.c:1129]: parenthesis

**Comment by onurctirtir** [comment]
>However, I didn't prefer to fix it in this pr since we can't already create
reference tables & distributed tables with such columns so we cannot test
what fixed.

Actually we can test this via `alter_table_set_access_method` udf :)

File: src/test/regress/expected/alter_distributed_table.out [hunk 2]
```diff
@@ -837,5 +837,41 @@ SELECT * FROM mat_view ORDER BY a;
  2 | 2
 (2 rows)
 
+CREATE TABLE distributed_table_1 (
+  col_1 int,
+  "col\'_2" text,
+  col_3 text generated always as (UPPER("col\'_2")) stored
```
Comment (onderkalaci) [inline src/test/regress/expected/alter_distributed_table.out:843]: Lets make sure that generated by default .. sequence works fine as well

File: src/backend/distributed/commands/alter_table.c [hunk 3]
```diff
@@ -1122,10 +1125,20 @@ ReplaceTable(Oid sourceId, Oid targetId, List *justBeforeDropCommands,
...
-		appendStringInfo(query, "INSERT INTO %s SELECT * FROM %s",
-						 quote_qualified_identifier(schemaName, targetName),
-						 quote_qualified_identifier(schemaName, sourceName));
-		ExecuteQueryViaSPI(query->data, SPI_OK_INSERT);
+		/*
+		 * Since we wrap target columns with parenthesis, skip executing
+		 * INSERT .. SELECT if relation has no columns that require moving
+		 * data. Otherwise, postgres could error out.
+		 */
+		if (AnyColumnsRequireDataCopy(sourceId))
```
Comment (onderkalaci) [inline src/backend/distributed/commands/alter_table.c:1133]: do we have a test where `AnyColumnsRequireDataCopy ` returns false?

Comment (onurctirtir) [reply src/backend/distributed/commands/alter_table.c:1133]: not added in this pr but yes
https://github.com/citusdata/citus/blob/cacb76d2c6a70383ad5d7c597daa2298e446ac2b/src/test/regress/expected/fkeys_between_local_ref.out#L117..L118

but I can add such a test in this pr too

Comment (onderkalaci) [reply src/backend/distributed/commands/alter_table.c:1133]: Yes, lets have one. Thanks!

File: src/test/regress/sql/alter_distributed_table.sql [hunk 4]
```diff
@@ -280,5 +280,19 @@ CREATE MATERIALIZED VIEW mat_view AS SELECT * FROM mat_view_test;
 SELECT alter_distributed_table('mat_view_test', shard_count := 5, cascade_to_colocated := false);
 SELECT * FROM mat_view ORDER BY a;
 
+CREATE TABLE distributed_table_1 (
```
Comment (onderkalaci) [inline src/test/regress/sql/alter_distributed_table.sql:283]: Can we have a test `citus_local` is converted via `create_reference_table` and `create_distributed_table`?

File: src/test/regress/expected/alter_distributed_table.out (hunk 2 above)
Comment (onurctirtir) [reply src/test/regress/expected/alter_distributed_table.out:843]: To clarify, there are three options around generated columns:
1) generated by default .. as identity
2) generated always .. as identity
3) generated always .. as stored

This pr fixes 3), 1) already works fine on master, 2) is still broken.
For 2), I noted below in pr description:
>Also realized that ReplaceTable cannot handle GENERATED IDENTITY
columns and fix for that seems to be as simple as adding OVERRIDING
SYSTEM VALUE to INSERT... SELECT query that we execute in ReplaceTable.
Maybe we should fix this in another pr. #4624

I guess here `generated by default .. sequence` correponds to 1) and in this pr I will add some tests for 1) too.

File: src/test/regress/expected/undistribute_table.out [hunk 5]
```diff
@@ -384,9 +384,81 @@ SELECT * FROM another_schema.undis_view3 ORDER BY 1, 2;
...
+ col_1 | col_2 | col_3 | col_4 | col_5
+---------------------------------------------------------------------
+     1 |       |       |     2 |     3
+    11 |       |       |    12 |    13
+   100 |   101 |   201 |   102 |   104
+   200 |   201 |   401 |   202 |   204
+(4 rows)
+
+BEGIN;
+  SELECT undistribute_table('reference_table_1');
```
Comment (onderkalaci) [inline src/test/regress/expected/undistribute_table.out:412]: lets add some more data after undistribute?

File: src/backend/distributed/commands/alter_table.c [hunk 6]
```diff
@@ -1183,6 +1196,72 @@ ReplaceTable(Oid sourceId, Oid targetId, List *justBeforeDropCommands,
...
+ */
+static char *
+BuildInsertColumnStringForReplaceTable(Oid relationId)
+{
+	/*
+	 * When copying data to temp table, we skip columns having GENERATED
+	 * GENERATED ALWAYS AS (...) STORED expressions since Postgres doesn't
+	 * allow inserting into such columns. This is not bad since Postgres
+	 * would already generate such columns.
+	 */
```
Comment (onderkalaci) [inline src/backend/distributed/commands/alter_table.c:1222]: might be useful to have a comment on why we don't filter out default columns?

File: src/backend/distributed/commands/alter_table.c [hunk 7]
```diff
@@ -1183,6 +1196,72 @@ ReplaceTable(Oid sourceId, Oid targetId, List *justBeforeDropCommands,
...
+	for (int columnIndex = 0; columnIndex < tupleDescriptor->natts; columnIndex++)
+	{
+		Form_pg_attribute currentColumn = TupleDescAttr(tupleDescriptor, columnIndex);
+		if (currentColumn->attisdropped)
+		{
+			continue;
+		}
+
+#if PG_VERSION_NUM >= 120000
+		if (currentColumn->attgenerated == ATTRIBUTE_GENERATED_STORED)
```
Comment (onderkalaci) [inline src/backend/distributed/commands/alter_table.c:1248]: What about `ATTRIBUTE_IDENTITY_ALWAYS ` and `ATTRIBUTE_IDENTITY_BY_DEFAULT`?

Comment (onurctirtir) [reply src/backend/distributed/commands/alter_table.c:1248]: https://github.com/citusdata/citus/pull/4616#discussion_r568524393

File: src/test/regress/expected/alter_distributed_table.out (hunk 2 above)
Comment (onurctirtir) [reply src/test/regress/expected/alter_distributed_table.out:843]: ah, seems that 1) depends on #4625

File: src/backend/distributed/commands/alter_table.c (hunk 7 above)
Comment (onderkalaci) [reply src/backend/distributed/commands/alter_table.c:1248]: Let's add comment on the two others must be tackled separately, and open a new issue to track?

File: src/test/regress/expected/alter_distributed_table.out (hunk 2 above)
Comment (onurctirtir) [reply src/test/regress/expected/alter_distributed_table.out:843]: Plus, even if #4625 is merged, we still don't know how to create new table in `ReplaceTable` since we don't have the logic to deparse such expresssions 1) & 2) in deparser :/

**Review by onderkalaci — COMMENTED** [review]
This is a one good step to cover, ` GENERATED ALWAYS AS STORED`, in the future we should consider fixing it for `ATTRIBUTE_IDENTITY_ALWAYS ` and `ATTRIBUTE_IDENTITY_BY_DEFAULT `.

I'll do one final test after you address some of the minor notes

File: src/backend/distributed/commands/alter_table.c (hunk 3 above)
Comment (onurctirtir) [reply src/backend/distributed/commands/alter_table.c:1133]: a08014663729b3f6b9788c26ed92a3330f721b6b

File: src/test/regress/expected/undistribute_table.out (hunk 5 above)
Comment (onurctirtir) [reply src/test/regress/expected/undistribute_table.out:412]: 7609700d334e7f7f7ecd9579f89e94cff4fcf22c

File: src/backend/distributed/commands/alter_table.c (hunk 6 above)
Comment (onurctirtir) [reply src/backend/distributed/commands/alter_table.c:1224]: dc76a40785f9bfc4e48255177fcae0da6c332f41

File: src/test/regress/sql/alter_distributed_table.sql (hunk 4 above)
Comment (onurctirtir) [reply src/test/regress/sql/alter_distributed_table.sql:283]: this depends on #4613 since we cannot have `generated as always stored` expressions on citus local table columns currrently :/

File: src/backend/distributed/commands/alter_table.c (hunk 3 above)
Comment (onderkalaci) [reply src/backend/distributed/commands/alter_table.c:1133]: Ok, it seems that this logic is broken:
```SQL
CREATE TABLE t1 (a int, b int generated always as (a + 1) stored);

INSERT INTO t1 (a) VALUES (1), (2);


ALTER TABLE t1 DROP COLUMN a;

SELECT * FROM t1;
--
(2 rows)

Time: 0.469 ms

 select alter_table_set_access_method('t1', 'columnar');

-- !!---!! This should have returned two rows
SELECT * FROM t1;
--
(0 rows)

Time: 0.935 ms

```

File: src/backend/distributed/commands/alter_table.c (hunk 7 above)
Comment (onurctirtir) [reply src/backend/distributed/commands/alter_table.c:1251]: Yeah, I will open an issue for that.
Other than that, not sure if it's a good place to add such comment since even if we supported such identity columns, we wouldn't have to handle such columns when executing `INSERT .. SELECT` here, what do you think ?

File: src/backend/distributed/commands/alter_table.c (hunk 3 above)
Comment (onurctirtir) [reply src/backend/distributed/commands/alter_table.c:1133]: tbh, first one sounds like a postgres bug to me at first glance, but in the end, it should be normal to see `0` rows after altering the table since we create the table from scratch ?

Comment (onurctirtir) [reply src/backend/distributed/commands/alter_table.c:1133]: seems that below was crashing on master, but not on this branch since we skip `insert select`:
```sql
create table local(y int);
alter table local drop column y;
select alter_table_set_access_method('local', 'columnar');
```

Comment (onderkalaci) [reply src/backend/distributed/commands/alter_table.c:1133]: > moreover, seems that below was crashing on master, but not on this branch since we skip insert select:

Good that we catch this

> tbh, first one sounds like a postgres bug to me at first glance (or I'm missing something, is it the expected behavior ?)

Why is so? The table has two rows and PG gives that information to us? This behavior is valid regardless of generated columns. If you drop all columns of a table, you'd see the row count is unchanged.

I guess if the table has no columns, we should do?
```SQL
insert into t2 select * from t1;
```

Comment (onurctirtir) [reply src/backend/distributed/commands/alter_table.c:1133]: to handle https://github.com/citusdata/citus/pull/4616#discussion_r568646297:

when no columns available, we should execute plain `INSERT INTO temp_table SELECT * FROM input_table` so that we don't break pg output but not sure if it's worth ?

Comment (onderkalaci) [reply src/backend/distributed/commands/alter_table.c:1133]: Yes, I think it is definitely worth, we cannot return wrong results. We need good comments around it. And, maybe logic should be changed to:

```C
if (HasAnyGeneratedStoredColumns())
{
     build list, do insert select with the list
}
else
{
  do the regular thing
}
```

We should add a test for this scenario

File: src/backend/distributed/commands/alter_table.c (hunk 7 above)
Comment (onderkalaci) [reply src/backend/distributed/commands/alter_table.c:1251]: Yes, makes sense

File: src/test/regress/sql/alter_distributed_table.sql (hunk 4 above)
Comment (onurctirtir) [reply src/test/regress/sql/alter_distributed_table.sql:283]: since we are about to merge #4613, I will add that test before merging this pr

File: src/backend/distributed/commands/alter_table.c (hunk 3 above)
Comment (onurctirtir) [reply src/backend/distributed/commands/alter_table.c:1128]: 0fc3153e1f7a1cb8c2a084e728dbfb5995516109

File: src/test/regress/sql/alter_distributed_table.sql (hunk 4 above)
Comment (onurctirtir) [reply src/test/regress/sql/alter_distributed_table.sql]: fa3123c75d1dccd7c2762fbd6fd2de0f28a0c793

File: src/backend/distributed/commands/alter_table.c (hunk 7 above)
Comment (onurctirtir) [reply src/backend/distributed/commands/alter_table.c:1259]: I will open that issue after opening pr's to error out for identity cols in `CreateCitusLocalTable` & `ReplaceTable`

**Review by onurctirtir — COMMENTED** [review]
I will squash all the commits before merging, jfyi

File: src/backend/distributed/commands/alter_table.c [hunk 8]
```diff
@@ -1183,6 +1204,75 @@ ReplaceTable(Oid sourceId, Oid targetId, List *justBeforeDropCommands,
...
+	return list_length(GetNonGeneratedStoredColumnNameList(relationId)) > 0;
+}
+
+
+/*
+ * BuildInsertColumnStringForReplaceTable is a helper function that returns
+ * comma seperated columns that we can insert into for ReplaceTable.
+ */
+static char *
+BuildInsertColumnStringForReplaceTable(Oid relationId)
```
Comment (onderkalaci) [inline src/backend/distributed/commands/alter_table.c:1223]: This functions name is obsolete with the latest changes. In fact, we can get rid of this function and inline the two lines just before `appendStringInfo ` as `GetNonGeneratedStoredColumnNameList ` makes it much easier to follow.
(as I noted in the other comment, moving this comment above sounds better to me)

File: src/backend/distributed/commands/alter_table.c [hunk 9]
```diff
@@ -1122,9 +1125,27 @@ ReplaceTable(Oid sourceId, Oid targetId, List *justBeforeDropCommands,
...
+			/* see comment in BuildInsertColumnStringForReplaceTable */
+			char *insertColumnString = BuildInsertColumnStringForReplaceTable(sourceId);
+			appendStringInfo(query, "INSERT INTO %s (%s) SELECT %s FROM %s",
+							 quote_qualified_identifier(schemaName, targetName),
+							 insertColumnString, insertColumnString,
+							 quote_qualified_identifier(schemaName, sourceName));
+		}
+		else
+		{
+			/*
```
Comment (onderkalaci) [inline src/backend/distributed/commands/alter_table.c:1139]: Minor: I think this comment is good, but it felt that we are not reflecting the vast majority of the cases: Table has columns :) 

So, maybe start with that in a single sentence.

File: src/backend/distributed/commands/alter_table.c [hunk 10]
```diff
@@ -1122,9 +1125,27 @@ ReplaceTable(Oid sourceId, Oid targetId, List *justBeforeDropCommands,
 									quote_qualified_identifier(schemaName, sourceName))));
 		}
 
-		appendStringInfo(query, "INSERT INTO %s SELECT * FROM %s",
-						 quote_qualified_identifier(schemaName, targetName),
-						 quote_qualified_identifier(schemaName, sourceName));
+		if (HasAnyGeneratedStoredColumns(sourceId))
+		{
+			/* see comment in BuildInsertColumnStringForReplaceTable */
```
Comment (onderkalaci) [inline src/backend/distributed/commands/alter_table.c:1130]: I'd move that comment to here

**Review by onderkalaci — APPROVED** [review]
This all looks good to me with some minor comments.

@halilozanakgul do you want to have a quick look before we merge this?

File: src/backend/distributed/commands/alter_table.c (hunk 10 above)
Comment (onurctirtir) [reply src/backend/distributed/commands/alter_table.c]: addressed all three of them in 7fa29c15b19672cb9119802068d50e21387b9f04
