### PR TITLE
Acquire AccessShareLock before updating table statistics

### LINKED ISSUE #5116: Concurrent citus_update_table_statistics fails with DROP table
Create 1000 partitions.

On the first session, start running the below:
```SQL
select citus_update_table_statistics(logicalrelid) from pg_dist_partition;
```

On the second session, drop a partition (e.g., the last partition )
```SQL
drop table "Energy Added_18585";
```

Update statistics fails:
```SQL
select citus_update_table_statistics(logicalrelid) from pg_dist_partition;
ERROR:  relation with OID 23587 does not exist
Time: 12966.122 ms (00:12.966)
```

### PR DESCRIPTION
**Pull request by naisila**
DESCRIPTION: Acquire AccessShareLock before updating table statistics to verify the table exists

If the table doesn't exist, meaning it was concurrently dropped elsewhere, we throw a warning and continue.

Fixes #5116

### CODE REVIEW

File: src/backend/distributed/operations/stage_protocol.c [hunk 1]
```diff
@@ -380,7 +380,13 @@ citus_update_table_statistics(PG_FUNCTION_ARGS)
 
 	Oid distributedTableId = PG_GETARG_OID(0);
 
-	UpdateTableStatistics(distributedTableId);
+	Relation relation = try_relation_open(distributedTableId, AccessShareLock);
```
Comment (onderkalaci) [inline src/backend/distributed/operations/stage_protocol.c:383]: Why do we use `try_relation_open`? What happens if we cannot acquire the lock?

Also, I think this needs an isolation test given the issues we had

File: src/backend/distributed/operations/stage_protocol.c [hunk 2]
```diff
@@ -380,7 +380,13 @@ citus_update_table_statistics(PG_FUNCTION_ARGS)
...
+
+	if (relation != NULL)
+	{
+		UpdateTableStatistics(distributedTableId);
+		relation_close(relation, AccessShareLock);
+	}
```
Comment (marcocitus) [inline src/backend/distributed/operations/stage_protocol.c:389]: Should we keep this lock after the function is finished? That probably invites deadlocks.

**Review by marcocitus — COMMENTED** [review]
I'm not sure this lock really fixes the linked issue. The table can still be dropped in between the query getting a snapshot and citus_update_table_statistics getting called.

File: src/backend/distributed/operations/stage_protocol.c (hunk 1 above)
Comment (naisila) [reply src/backend/distributed/operations/stage_protocol.c:383]: With this command `select citus_update_table_statistics(logicalrelid) from pg_dist_partition;` we will call the function for each table one by one and if the table has already been dropped, using `relation_open` will give an error saying the table doesn't exist.

Comment (SaitTalhaNisanci) [reply src/backend/distributed/operations/stage_protocol.c:383]: As far as I know `select citus_update_table_statistics(logicalrelid) from pg_dist_partition;` is called with the rebalancer page load on cloud, do we know what happens if the call cannot finish because we can't take the lock? I guess they use a timeout?

File: src/backend/distributed/operations/stage_protocol.c [hunk 3]
```diff
@@ -380,7 +380,18 @@ citus_update_table_statistics(PG_FUNCTION_ARGS)
...
+	else
+	{
+		ereport(WARNING, (errmsg("relation with OID %u does not exist",
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/operations/stage_protocol.c:392]: Why do we give a warning here? I think this can be confusing for the users, any thoughts?

Comment (naisila) [reply src/backend/distributed/operations/stage_protocol.c:392]: Maybe the warning can be better, but the motivation is to _let the user know_ a table from `pg_dist_partition` existed before executing `SELECT citus_update_table_statistics(logicalrelid) FROM pg_dist_partition;` and was dropped concurrently.

Comment (onderkalaci) [reply src/backend/distributed/operations/stage_protocol.c:392]: I think a NOTICE might be nicer: `Relation with oid is dropped concurrently, skipping to update statistics`  or something like that?

Comment (onderkalaci) [reply src/backend/distributed/operations/stage_protocol.c:392]: (Or even DEBUG1 might be fine)

Comment (SaitTalhaNisanci) [reply src/backend/distributed/operations/stage_protocol.c:392]: umm, if the table is dropped it doesn't need to be updated and the user probably doesn't need to know about this. Why do you think it is useful for the user?

Comment (marcocitus) [reply src/backend/distributed/operations/stage_protocol.c:392]: I suggested adding this because the user might be calling citus_update_table_statistics directly and making a typo/bug. If we say nothing the user will falsely assume the function worked. Hence, a WARNING seems right, but it should be a NOTICE at minimum.

**Comment by naisila** [comment]
As I also updated in the [issue](https://github.com/citusdata/citus/issues/5116#issuecomment-892035501), for the scenario in #5116 the same failure occurs with `citus_shards` view.
For this reason we acquire a lock for each distributed table before generating shard queries.
Note that this lock is not enough for `citus_update_table_statistics` as the failure can also happen in the update step, whereas citus_shards has n update step.

There is one thing I don't quite like though: we generate shard statistics queries for each worker node, so we will get the notice of relation being dropped concurrently multiple times (the number of worker nodes). However I believe this is not expected to happen often. @SaitTalhaNisanci do you think this is worth making some changes regarding where we acquire the lock?

File: src/backend/distributed/operations/stage_protocol.c (hunk 3 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/operations/stage_protocol.c]: umm, makes sense. I think we can consider updating the message then because if I call citus_upate_table_statistics with a non-existing oid then the output is incorrect:

```
[local] talha@talha:9700-7016=# SELECT citus_update_table_statistics(21111);
NOTICE:  relation with OID 21111 was concurrently dropped, skipping
 citus_update_table_statistics
-------------------------------

(1 row)

Time: 0.665 ms
```

Comment (marcocitus) [reply src/backend/distributed/operations/stage_protocol.c]: Agree, would be better to say "relation with OID %d does not exist"

File: src/backend/distributed/metadata/metadata_utility.c [hunk 4]
```diff
@@ -893,11 +893,28 @@ GenerateAllShardStatisticsQueryForNode(WorkerNode *workerNode, List *citusTableI
...
+		Relation relation = try_relation_open(relationId, AccessShareLock);
+		if (relation != NULL)
+		{
+			List *shardIntervalsOnNode = ShardIntervalsOnWorkerGroup(workerNode,
+																	 relationId);
+			char *shardStatisticsQuery =
+				GenerateShardStatisticsQueryForShardList(shardIntervalsOnNode,
+														 useShardMinMaxQuery);
+			appendStringInfoString(allShardStatisticsQuery, shardStatisticsQuery);
+			relation_close(relation, AccessShareLock);
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/metadata/metadata_utility.c:910]: Note that it is still possible to drop the table after this line but since we will send the command optionally, we will get a warning from workers saying that the relation(shard) doesn't exist on the workers.

Comment (naisila) [reply src/backend/distributed/metadata/metadata_utility.c:910]: Can we keep the lock until after the function is finished? In that case it's not possible to drop until the function is done, but I'm not sure about the consequences of that.

File: src/backend/distributed/metadata/metadata_utility.c [hunk 5]
```diff
@@ -893,11 +893,28 @@ GenerateAllShardStatisticsQueryForNode(WorkerNode *workerNode, List *citusTableI
...
+		}
+		else
+		{
+			ereport(NOTICE, (errmsg(
+								 "relation with OID %u was concurrently dropped, skipping",
```
Comment (SaitTalhaNisanci) [inline src/backend/distributed/metadata/metadata_utility.c:915]: I am thinking that we can remove this NOTICE here while keeping the other one. Because this will be triggered with only citus_shards and I feel like showing this notice message isn't that useful in that case.

File: src/backend/distributed/metadata/metadata_utility.c (hunk 4 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/metadata/metadata_utility.c:910]: If you close the relation with `NoLock` then the lock will be held until the transaction finishes (either aborted or committed). One consequence would be holding the locks for a long time. If we had many tables it is possible that citus_shards would block the drop operations and it can possibly take a long time until we can acquire all the locks on all the tables. So I think we shouldn't hold the locks until the transaction is finished and I think it is fine to get the warnings from the workers

File: src/backend/distributed/metadata/metadata_utility.c (hunk 5 above)
Comment (naisila) [reply src/backend/distributed/metadata/metadata_utility.c:915]: That makes sense. After all `citus_shards` shows an output and the user knows which tables exist. That also fixes the problem of showing the same warning multiple times that I mentioned [here](https://github.com/citusdata/citus/pull/5155#issuecomment-892113662)

> There is one thing I don't quite like though: we generate shard statistics queries for each worker node, so we will get the notice of relation being dropped concurrently multiple times (the number of worker nodes). However, I believe this is not expected to happen often.

File: src/backend/distributed/operations/stage_protocol.c (hunk 3 above)
Comment (naisila) [reply src/backend/distributed/operations/stage_protocol.c]: Makes sense, I will go with "relation with OID %d does not exist, skipping"

File: src/backend/distributed/metadata/metadata_utility.c (hunk 5 above)
Comment (SaitTalhaNisanci) [reply src/backend/distributed/metadata/metadata_utility.c:915]: Yeah this came to my mind while thinking about the problem you mentioned :)

**Comment by naisila** [comment]
Command: `SELECT citus_update_table_statistics(logicalrelid) FROM pg_dist_partition;`

If we run a `DROP dist_table` command concurrently while the above command is being processed, and that table's statistics are already updated from `pg_dist_partition` ordering of tables, then the DROP command will wait until the above command is finished updating all the tables' statistics, and then the DROP will fail with the following error:
```SQL
ERROR:  tuple concurrently deleted
CONTEXT:  SQL statement "SELECT citus_drop_all_shards(v_obj.objid, v_obj.schema_name, v_obj.object_name)"
```

The error happens while trying to delete `pg_dist_placement` entries for the table we wish to drop. **This error is expected** and currently not avoidable, because `citus_update_table_statistics` deletes `pg_dist_placement` original entries for `dist_table` (and inserts new entries with updated statistics). However, the original entries are considered as _locked modified rows of `pg_dist_placement`_ until the end of the transaction, that's why the DROP command waits when trying to drop those rows, and when the other transaction finishes, it is considered as concurrent tuple deletion, and that's not allowed. `DROP dist_table` uses `simple_heap_delete` function to delete `pg_dist_placement` tuples, which doesn't expect concurrent deletes/updates of the target tuples. The following is `simple_heap_delete` documentation:
```
/*
 *	simple_heap_delete - delete a tuple
 *
 * This routine may be used to delete a tuple when concurrent updates of
 * the target tuple are not expected (for example, because we have a lock
 * on the relation associated with the tuple).  Any failure is reported
 * via ereport().
 */
```

We add a test for this expected error in the PR.

**Review by SaitTalhaNisanci — APPROVED** [review]
