### PR TITLE
Error out on parametrized SQL functions

### LINKED ISSUE #981: SQL functions(called by SELECT * FROM) with parameters throw wrong results
```
CREATE TABLE lineitem(id integer, org_id integer);
select master_create_distributed_table('lineitem','org_id','hash');
select master_create_worker_shards('lineitem',16,1);

CREATE OR REPLACE FUNCTION count_rows(org_id_val integer)
RETURNS TABLE (a bigint)
AS $$
  SELECT count(*) AS count_val from lineitem where org_id=org_id_val;
$$ LANGUAGE SQL STABLE;
```
The below test throws wrong results. The query doesn't run on the distributed table.
```
select * from count_rows(1);
 a

---
 0
```

### PR DESCRIPTION
**Pull request by byucesoy**
Fixes #981 

Before this commit, we were erroring out for queries containing parameterized SQL functions
like 'SELECT parameterized_sql_query(value)' as we should, however, we were returning wrong
results for queries like 'SELECT * FROM parameterized_sql_query(value)'. With this commit
we started to error out on such queries too.

### CODE REVIEW

File: src/backend/distributed/planner/multi_planner.c [hunk 1]
```diff
@@ -127,6 +127,18 @@ multi_planner(Query *parse, int cursorOptions, ParamListInfo boundParams)
 			result = CreateDistributedPlan(result, originalQuery, parse,
 										   boundParams, restrictionContext);
 		}
+		else
+		{
+			needsDistributedPlanning = NeedsDistributedPlanning(parse);
```
Comment (metdos) [inline src/backend/distributed/planner/multi_planner.c]: I think we can do this check after PG_TRY()/PG_CATCH() blocks just before returning. 

We can also use just one if block such as;

```C
	if (!needsDistributedPlanning && NeedsDistributedPlanning(parse))
	{
		ereport(ERROR, (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
						errmsg("cannot perform distributed planning on this "
							   "query because parametrized queries for SQL "
							   "functions referencing are not supported."),
						errhint("Consider using PLPGSQL functions instead.")));
	}
```

I think this is nicer because it shows in one line that it was not distributed but now it returns distributed so something is wrong :)

Comment (byucesoy) [inline src/backend/distributed/planner/multi_planner.c]: @metdos  fixed

File: src/backend/distributed/planner/multi_planner.c [hunk 2]
```diff
@@ -138,6 +138,21 @@ multi_planner(Query *parse, int cursorOptions, ParamListInfo boundParams)
 	/* remove the context from the context list */
 	PopRestrictionContext();
 
+	/*
+	 * In some cases, for example; parametrized SQL functions, we may miss that
```
Comment (metdos) [inline src/backend/distributed/planner/multi_planner.c]: parametrized -> parameterized

File: src/backend/distributed/planner/multi_planner.c [hunk 3]
```diff
@@ -138,6 +138,21 @@ multi_planner(Query *parse, int cursorOptions, ParamListInfo boundParams)
...
+	 * there is a need for distributed planning. Such cases only become clear after
+	 * standart_planner performs some modifications on parse tree. In such cases
+	 * we will simply error out.
+	 */
+	if (!needsDistributedPlanning && NeedsDistributedPlanning(parse))
+	{
+		ereport(ERROR, (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
+						errmsg("cannot perform distributed planning on this "
+							   "query because parametrized queries for SQL "
+							   "functions referencing are not supported."),
```
Comment (metdos) [inline src/backend/distributed/planner/multi_planner.c]: Maybe: referencing distributed tables are not supported yet

File: src/backend/distributed/planner/multi_planner.c [hunk 4]
```diff
@@ -138,6 +138,21 @@ multi_planner(Query *parse, int cursorOptions, ParamListInfo boundParams)
...
+						errhint("Consider using PLPGSQL functions instead.")));
```
Comment (metdos) [inline src/backend/distributed/planner/multi_planner.c]: PLPGSQL -> PL/pgSQL

File: src/test/regress/expected/multi_sql_function.out [hunk 5]
```diff
@@ -319,7 +319,31 @@ SELECT * FROM prepare_table ORDER BY key, value;
    6 |      
 (8 rows)
 
+-- test running parametrized SQL funtion
```
Comment (metdos) [inline src/test/regress/expected/multi_sql_function.out]: replace all `parametrized` with `parameterized`

File: src/test/regress/sql/multi_sql_function.sql [hunk 6]
```diff
@@ -140,7 +140,24 @@ SELECT non_partition_parameter_delete_sql(62);
 -- check after deletes
 SELECT * FROM prepare_table ORDER BY key, value;
 
+-- test running parametrized SQL funtion
```
Comment (metdos) [inline src/test/regress/sql/multi_sql_function.sql]: replace all `parametrized` with `parameterized`

File: src/backend/distributed/planner/multi_planner.c [hunk 7]
```diff
@@ -148,9 +148,10 @@ multi_planner(Query *parse, int cursorOptions, ParamListInfo boundParams)
 	{
 		ereport(ERROR, (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
 						errmsg("cannot perform distributed planning on this "
-							   "query because parametrized queries for SQL "
-							   "functions referencing are not supported."),
-						errhint("Consider using PLPGSQL functions instead.")));
+							   "query because parameterized queries for SQL "
+							   "functions referencing distributed tables are "
+							   "not supported."),
```
Comment (metdos) [inline src/backend/distributed/planner/multi_planner.c]: Minor. We don't put a dot at the end of `errmsg`.
