### PR TITLE
Disallow colocating tables when collations don't match

### LINKED ISSUE #7683: unable to add node when distribution columns have different collation types
## Description
- two tables were created in a single node cluster, with  text type but different collations ( C versus default)
- both tables were distributed using create distributed table call
- noticed they were colocated
- attempt to add a new node fails
- alter table alter column command to set the collation is rejected by coordinator due to it is being distribution key

### Expected
- Either created_distributed_table should fail or citus_add_node should succeed

##  Detailed repro steps

```sql
citus=> select version();
-------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 14.13 (Ubuntu 14.13-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0, 64-bit 
(1 row) 

citus=> select citus_version();
----------------------------------------------------------------------------------------------------
 Citus 12.1.5 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0, 64-bit 
(1 row) 

citus=> create table t1 ( a text collate "C", b text collate "C"); 
CREATE TABLE 
citus=> \d t1 
Table "public.t1" 
Column | Type | Collation | Nullable | Default 
--------+------+-----------+----------+--------- 
 a      | text | C         |          | 
 b      | text | C         |          | 
citus=> create table t2( a text, b text); 
CREATE TABLE 
citus=> select create_distributed_table('t1', 'a'); 
create_distributed_table 
-------------------------- 
(1 row)
citus=> select create_distributed_table('t2', 'a');
create_distributed_table 
--------------------------
(1 row)
citus=>

citus=> select * from pg_dist_partition;     
 logicalrelid | partmethod |                                                          partkey                                                           | colocationid | repmodel | autoconverted   
--------------+------------+----------------------------------------------------------------------------------------------------------------------------+--------------+----------+---------------   
 t1           | h          | {VAR :varno 1 :varattno 1 :vartype 25 :vartypmod -1 :varcollid 950 :varlevelsup 0 :varnosyn 1 :varattnosyn 1 :location -1} |            1 | s        | f        
 t2           | h          | {VAR :varno 1 :varattno 1 :vartype 25 :vartypmod -1 :varcollid 100 :varlevelsup 0 :varnosyn 1 :varattnosyn 1 :location -1} |            1 | s        | f       
(2 rows)  

citus=> select * from pg_collation where oid = 100 or oid=950; 
 oid | collname | collnamespace | collowner | collprovider | collisdeterministic | collencoding | collcollate | collctype | collversion
-----+----------+---------------+-----------+--------------+---------------------+--------------+-------------+-----------+-------------
 100 | default  |            11 |        10 | d            | t                   |           -1 |             |           |
 950 | C        |            11 |        10 | c            | t                   |           -1 | C           | C         |
(2 rows)   

select citus_add_node('<redacted>', 5432);
NOTICE:  shards are still on the coordinator after adding the new node
HINT:  Use SELECT rebalance_table_shards(); to balance shards data between workers and coordinator or SELECT citus_drain_node('<redacted>',5432); to permanently move shards away from the coordinator.
WARNING:  cannot colocate tables t2 and t1 
DETAIL:  Distribution column collations don't match for t2 and t1.  
ERROR:  failure on connection marked as essential: <redacted>:5432
```

### PR DESCRIPTION
**Pull request by onurctirtir**
DESCRIPTION: Disallows creating a distributed table or altering it to be colocated with another table if distribution key collations don't match.

Fixes #7683.

- No need to make any changes for the following UDFs:

  - update_distributed_table_colocation()/create_distributed_table_concurrently()
    These are already checking whether collations of distribution keys match.

  - ALTER TABLE .. ALTER COLUMN .. TYPE .. COLLATE ..
    We already don't allow changing the collation of a distribution column.

- The following UDFs are fixed with this commit:
  These UDFs were not explicitly checking whether collation of the distribution
  keys of two distributed tables match, however, we were catching this via
  EnsurePartitionMetadataIsSane() when syncing metadata. And this incorrectly
  caused allowing to colocate two such distributed tables in a single-node setup
  as we don't have any nodes to sync metadata there. In such cases, we would only
  become aware of the situation **when adding a new node to the cluster etc.**.

  Otherwise, i.e., if we already had more than one nodes in the cluster, we were
  seeing this error while Citus is syncing metadata for the new / altered distributed
  table, which wasn't too bad but not ideal too:

  ```sql
  ERROR:  cannot colocate tables test_a_tbl_2 and test_a_tbl_1
  DETAIL:  Distribution column collations don't match for test_a_tbl_2 and test_a_tbl_1.
  CONTEXT:  while executing command on localhost:9701
  ```

  - create_distributed_table()
    To fix that, now EnsureTableCanBeColocatedWith() calls EnsureColumnTypeEquality()
    to perform necessary checks, which already ensures collation match.

    And to do that, now EnsureTableCanBeColocatedWith() has to accept distributionColumn
    Var as an argument (to be passed into EnsureColumnTypeEquality()), so now it doesn't
    have to accept distributionColumnType separately, so refactor accordingly.

    And to provide distributionColumn Var to EnsureTableCanBeColocatedWith(), similarly
    the call sites of the function also need to have distributionColumn Var, like
    FindColocateWithColocationId(). And now that FindColocateWithColocationId() accepts
    distributionColumn Var, it doesn't have to accept distributionColumnType and
    distributionColumnCollation separately, so refactor accordingly.

    Plus, now this UDF also correctly records the colocation groups with the correct
    distribution column collations.

  - alter_distributed_table()
    Make sure to check column collations.

- Also added fix_pre_citus14_colocation_group_collation_mismatches(), which is
  automatically called by citus_finish_citus_upgrade() to automatically fix such
  colocation groups when executed after upgrading to Citus 14.

  Tested fix_pre_citus14_colocation_group_collation_mismatches() on a 3-node
  "Standard D4ds_v5" cluster, and;

  - Moving 10k tables out from their original colocation groups to fix the bug for an
    existing cluster took 4.5 sec for a 3-node "Standard D4ds_v5" cluster. (#nodes
    matters because the UDF syncs the corrected colocation entries to all nodes).

  - For 10k tables, in the same cluster setup, when there is nothing to fix, the
    function returns at 200 ms.

  This also helps removing the last alternative test output for
  upgrade_citus_finish_citus_upgrade. This is because, the recent change made in
  citus_finish_citus_upgrade() to automatically fix such colocation groups results in
  updating last_upgrade_version in pg_dist_node_metadata when upgrading to Citus 14,
  so the notice message in the mentioned test is now gone, so we don't anymore need to
  have an alternative output for that test.

### CODE REVIEW

File: src/backend/distributed/commands/alter_table.c [hunk 1]
```diff
@@ -2125,6 +2125,23 @@ CheckAlterDistributedTableConversionParameters(TableConversionState *con)
 								   "distribution column is different than %s",
 								   con->colocateWith, con->relationName)));
 		}
+		else if (con->distributionColumn &&
+				 colocateWithPartKey->varcollid != con->distributionKey->varcollid)
+		{
+			ereport(ERROR, (errmsg("cannot colocate with %s and change distribution "
+								   "column to %s because collation of column %s is "
+								   "different then the distribution column of the %s",
```
Comment (naisila) [inline src/backend/distributed/commands/alter_table.c]: nit
```suggestion
								   "different than the distribution column of the %s",
```

File: src/backend/distributed/commands/alter_table.c [hunk 2]
```diff
@@ -2125,6 +2125,23 @@ CheckAlterDistributedTableConversionParameters(TableConversionState *con)
 								   "distribution column is different than %s",
 								   con->colocateWith, con->relationName)));
 		}
+		else if (con->distributionColumn &&
+				 colocateWithPartKey->varcollid != con->distributionKey->varcollid)
```
Comment (naisila) [inline src/backend/distributed/commands/alter_table.c:2126]: Can you add a test for this case?

Comment (onurctirtir) [reply src/backend/distributed/commands/alter_table.c:2126]: sure

Comment (onurctirtir) [reply src/backend/distributed/commands/alter_table.c:2126]: done

File: src/test/regress/sql/update_colocation_mx.sql [hunk 3]
```diff
@@ -53,6 +53,93 @@ SELECT count(DISTINCT colocationid) FROM pg_dist_partition WHERE logicalrelid IN
...
+create table test_c_tbl_3(int_col int, text_col text collate "C");
+create table test_c_tbl_4(text_col text collate "en-x-icu");
+
+select create_distributed_table('test_c_tbl_3', 'int_col');
+select create_distributed_table('test_c_tbl_4', 'text_col', colocate_with => 'none');
+
+-- errors
+select alter_distributed_table('test_c_tbl_3', colocate_with=>'test_c_tbl_4', distribution_column:='text_col');
+
+DROP TABLE test_c_tbl_1, test_c_tbl_2;
```
[the remark this answers is not in the document]
Comment (onurctirtir) [reply src/test/regress/sql/update_colocation_mx.sql:130]: the whole schema is dropped at the end

File: src/backend/distributed/sql/udfs/fix_pre_citus14_colocation_group_collation_mismatches/14.0-1.sql [hunk 4]
```diff
@@ -0,0 +1,83 @@
+CREATE OR REPLACE FUNCTION pg_catalog.fix_pre_citus14_colocation_group_collation_mismatches()
```
Comment (codeforall) [inline src/backend/distributed/sql/udfs/fix_pre_citus14_colocation_group_collation_mismatches/14.0-1.sql:1]: Minor suggestion: could we add an optional dry_run argument? When enabled, the UDF wouldn’t apply any updates, instead, it would print a preview of all the changes it would make.

File: src/backend/distributed/sql/udfs/fix_pre_citus14_colocation_group_collation_mismatches/14.0-1.sql [hunk 5]
```diff
@@ -0,0 +1,83 @@
...
+            FOR v_table_to_move_out IN SELECT unnest(v_tables_to_move_out)
+            LOOP
+                IF v_first_table IS NULL then
+                    -- Move the first table out to start a new colocation group.
+                    --
+                    -- Could check if there is an appropriate colocation group to move to instead of 'none',
+                    -- but this won't be super easy. Plus, even if we had such a colocation group, the user
+                    -- was anyways okay with having this in a different colocation group in the first place.
+
+                    RAISE DEBUG 'Moving out table with oid % to a new colocation group', v_table_to_move_out;
```
Comment (codeforall) [inline src/backend/distributed/sql/udfs/fix_pre_citus14_colocation_group_collation_mismatches/14.0-1.sql:65]: Maybe a NOTICE message would be more useful than DEBUG, so the caller gets visibility into the changes being made?

**Comment by codeforall** [comment]
When we move tables with mismatched collations into new colocation groups, what happens to any distributed functions/procedures that were colocated with those tables? Could this change break function call delegation for the affected functions?

File: src/backend/distributed/commands/alter_table.c [hunk 6]
```diff
@@ -2122,6 +2122,23 @@ CheckAlterDistributedTableConversionParameters(TableConversionState *con)
...
```
Comment (codeforall) [inline src/backend/distributed/commands/alter_table.c:2126]: You’re not using EnsureColumnTypeEquality() and instead added a separate check. Was that done to provide a more descriptive error message?

Comment (codeforall) [reply src/backend/distributed/commands/alter_table.c:2126]: If that’s the case and it’s not in the scope right now, we could emit a WARNING at the end of the UDF and document it as a known limitation.

File: src/backend/distributed/sql/udfs/fix_pre_citus14_colocation_group_collation_mismatches/14.0-1.sql (hunk 5 above)
Comment (onurctirtir) [reply src/backend/distributed/sql/udfs/fix_pre_citus14_colocation_group_collation_mismatches/14.0-1.sql:65]: but that would slow down the things a lot, so thought having them as debug messages that can be optionally enabled

File: src/backend/distributed/commands/alter_table.c (hunk 6 above)
Comment (onurctirtir) [reply src/backend/distributed/commands/alter_table.c:2126]: the problem is that EnsureColumnTypeEquality takes two relation ids but this code-path only expects a set of arguments to alter the table with, that's why we cannot use it here

**Comment by onurctirtir** [comment]
> When we move tables with mismatched collations into new colocation groups, what happens to any distributed functions/procedures that were colocated with those tables? Could this change break function call delegation for the affected functions?

I don't think so because we actually don't seem to care about the collation saved in pg_dist_colocation when distributing the functions or when pushing them down, but we do care about the collation of the Vars / Consts passed to the dist function etc.

File: src/backend/distributed/sql/udfs/fix_pre_citus14_colocation_group_collation_mismatches/14.0-1.sql (hunk 4 above)
Comment (onurctirtir) [reply src/backend/distributed/sql/udfs/fix_pre_citus14_colocation_group_collation_mismatches/14.0-1.sql:1]: let me note this as a follow up improvement for a subsequent PR to unblock the release, makes sense

**Review by ihalatci — APPROVED** [review]
