### PR TITLE
Fix subquery arguments in aggregates

### LINKED ISSUE #3432: Queries with subqueries in HAVING may error unexpectedly - 2
This looks different than #3424, so marking as related, but opening a separate issue.

```SQL
CREATE TABLE table_1 (key int, value int);
SELECT create_distributed_table('table_1', 'key');

CREATE TABLE table_2 (key int, value int);
SELECT create_distributed_table('table_2', 'key');


SELECT count(*) FROM table_1 GROUP BY key HAVING avg(value) > avg((SELECT value FROM table_2 ORDER BY 1 DESC LIMIT 5));
ERROR:  cannot handle unplanned sub-select
```

bt:
```
 thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
  * frame #0: 0x0000000102f53707 postgres`errstart(elevel=20, filename="costsize.c", lineno=4038, funcname="cost_qual_eval_walker", domain=0x0000000000000000) at elog.c:263:14
    frame #1: 0x0000000102f558c1 postgres`elog_finish(elevel=20, fmt="cannot handle unplanned sub-select") at elog.c:1347:7
    frame #2: 0x0000000102ffb1bd postgres`cost_qual_eval_walker.cold.1 + 45
    frame #3: 0x0000000102d96f23 postgres`cost_qual_eval_walker(node=<unavailable>, context=<unavailable>) at costsize.c:4038:3
    frame #4: 0x0000000102d96e06 postgres`cost_qual_eval_walker(node=<unavailable>, context=<unavailable>) at costsize.c:4088:9
    frame #5: 0x0000000102d5d5f3 postgres`expression_tree_walker(node=<unavailable>, walker=(postgres`cost_qual_eval_walker at costsize.c:3860), context=0x00007ffeed079b10) at nodeFuncs.c:2126:9
    frame #6: 0x0000000102d96e06 postgres`cost_qual_eval_walker(node=<unavailable>, context=<unavailable>) at costsize.c:4088:9
    frame #7: 0x0000000102d940df postgres`cost_qual_eval_node(cost=0x00007ffeed079b60, qual=<unavailable>, root=<unavailable>) at costsize.c:3853:2
    frame #8: 0x0000000102dc5b3b postgres`get_agg_clause_costs_walker(node=0x0000000104324f30, context=0x00007ffeed079d78) at clauses.c:372:4
    frame #9: 0x0000000102d5d5f3 postgres`expression_tree_walker(node=<unavailable>, walker=(postgres`get_agg_clause_costs_walker at clauses.c:242), context=0x00007ffeed079d78) at nodeFuncs.c:2126:9
    frame #10: 0x0000000102dc5942 postgres`get_agg_clause_costs(root=<unavailable>, clause=<unavailable>, aggsplit=<unavailable>, costs=<unavailable>) at clauses.c:237:9
    frame #11: 0x0000000103cb1cbc citus.so`WorkerAggregateExpressionList(originalAggregate=<unavailable>, walkerContext=<unavailable>) at multi_logical_optimizer.c:3107:2
    frame #12: 0x0000000103cb1718 citus.so`WorkerAggregateWalker(node=<unavailable>, walkerContext=0x0000000104324a70) at multi_logical_optimizer.c:2863:31
    frame #13: 0x0000000102d5d5f3 postgres`expression_tree_walker(node=<unavailable>, walker=(citus.so`WorkerAggregateWalker at multi_logical_optimizer.c:2853), context=0x0000000104324a70) at nodeFuncs.c:2126:9
    frame #14: 0x0000000102d5d56a postgres`expression_tree_walker(node=0x00007ff98d88f910, walker=(citus.so`WorkerAggregateWalker at multi_logical_optimizer.c:2853), context=0x0000000104324a70) at nodeFuncs.c:0:2
    frame #15: 0x0000000102d5d5f3 postgres`expression_tree_walker(node=<unavailable>, walker=(citus.so`WorkerAggregateWalker at multi_logical_optimizer.c:2853), context=0x0000000104324a70) at nodeFuncs.c:2126:9
    frame #16: 0x0000000103cb144a citus.so`ProcessHavingClauseForWorkerQuery(originalHavingQual=0x0000000104322868, extendedOpNodeProperties=0x00007ffeed07a060, workerHavingQual=0x00007ffeed079fe8, queryTargetList=0x00007ffeed079f90, queryGroupClause=0x00007ffeed079ff0) at multi_logical_optimizer.c:2396:3
    frame #17: 0x0000000103caee33 citus.so`WorkerExtendedOpNode(originalOpNode=<unavailable>, extendedOpNodeProperties=0x00007ffeed07a060) at multi_logical_optimizer.c:2218:2
    frame #18: 0x0000000103cae5fe citus.so`MultiLogicalPlanOptimize(multiLogicalPlan=0x00000001043228a0) at multi_logical_optimizer.c:410:3
    frame #19: 0x0000000103ca9253 citus.so`CreateDistributedPlan(planId=20, originalQuery=0x00007ff98d808900, query=0x00007ff98d808a18, boundParams=0x0000000000000000, hasUnresolvedParams=<unavailable>, plannerRestrictionContext=0x00007ff98d890618) at distributed_planner.c:1062:2
    frame #20: 0x0000000103ca9330 citus.so`CreateDistributedPlan(planId=20, originalQuery=0x00007ff98d808900, query=0x00007ff98d808a18, boundParams=0x0000000000000000, hasUnresolvedParams=<unavailable>, plannerRestrictionContext=0x00007ff98d890618) at distributed_planner.c:1031:21
    frame #21: 0x0000000103ca8eea citus.so`CreateDistributedPlannedStmt(planContext=0x00007ffeed07a1c0) at distributed_planner.c:667:3
    frame #22: 0x0000000103ca7f0e citus.so`PlanDistributedStmt(planContext=0x00007ffeed07a1c0, rangeTableList=0x00007ff98d886060, rteIdCounter=<unavailable>) at distributed_planner.c:598:24
    frame #23: 0x0000000103ca7a18 citus.so`distributed_planner(parse=0x00007ff98d808a18, cursorOptions=<unavailable>, boundParams=<unavailable>) at distributed_planner.c:254:14
    frame #24: 0x0000000102e67f38 postgres`pg_plan_query(querytree=0x00007ff98d808a18, cursorOptions=256, boundParams=0x0000000000000000) at postgres.c:878:9
    frame #25: 0x0000000102e6804e postgres`pg_plan_queries(querytrees=<unavailable>, cursorOptions=256, boundParams=0x0000000000000000) at postgres.c:968:11
    frame #26: 0x0000000102e69d9e postgres`exec_simple_query(query_string="SELECT count(*) FROM table_1 GROUP BY key HAVING avg(value) > avg((SELECT value FROM table_2 ORDER BY 1 DESC LIMIT 5));") at postgres.c:1143:19
    frame #27: 0x0000000102e69624 postgres`PostgresMain(argc=<unavailable>, argv=<unavailable>, dbname=<unavailable>, username=<unavailable>) at postgres.c:0
    frame #28: 0x0000000102df42a6 postgres`BackendRun(port=0x00000001031c564c) at postmaster.c:4437:2
    frame #29: 0x0000000102df3b6f postgres`BackendStartup(port=<unavailable>) at postmaster.c:4128:3
    frame #30: 0x0000000102df3325 postgres`ServerLoop at postmaster.c:1704:7
    frame #31: 0x0000000102df13bf postgres`PostmasterMain(argc=3, argv=0x00007ff98d403130) at postmaster.c:1377:11
    frame #32: 0x0000000102d5b4c6 postgres`main(argc=3, argv=0x00007ff98d403130) at main.c:228:3
    frame #33: 0x00007fff658e43d5 libdyld.dylib`start + 1

```

The following also fails:
```SQL
WITH cte AS (SELECT value FROM table_2 ORDER BY 1 DESC LIMIT 5) SELECT count(*) FROM table_1 GROUP BY key HAVING avg(value) > avg((SELECT * FROM cte));
ERROR:  cannot handle unplanned sub-select

### LINKED ISSUE #3433: Some subqueries in HAVING is not recursively planned
We could potentially force all subqueries in HAVING to be recursively planned via `RecursivelyPlanAllSubqueries((Node *) query->havingQual, context);` somewhere in the code.

```SQL
CREATE TABLE table_1 (key int, value int);
SELECT create_distributed_table('table_1', 'key');

CREATE TABLE table_2 (key int, value int);
SELECT create_distributed_table('table_2', 'key');
```

The following query is not very meaningful, as we'd mostly expect many results in the subquery

```SQL
SELECT count(*) FROM table_1 GROUP BY key HAVING sum(value) > (SELECT sum(value) FROM table_2 GROUP BY key);
ERROR:  complex joins are only supported when all distributed tables are co-located and joined on their distribution columns
```

However, the following might be a useful query, still erroring out the same:

```SQL
SELECT count(*) FROM table_1 GROUP BY key HAVING avg(value) > avg((SELECT sum(value) FROM table_2 GROUP BY key));
ERROR:  complex joins are only supported when all distributed tables are co-located and joined on their distribution columns
```

The current workaound is to add `OFFSET 0` to the subquery, which hits #3432

```SQL
SELECT count(*) FROM table_1 GROUP BY key HAVING avg(value) > avg((SELECT sum(value) FROM table_2 GROUP BY key OFFSET 0));
ERROR:  cannot handle unplanned sub-select
```

### PR DESCRIPTION
**Pull request by serprex**
DESCRIPTION: avoid raising errors which could occur when subqueries are parameters to aggregates

`get_agg_clause_costs` will be handled by `standard_planner`

Fixes #3432

### CODE REVIEW

File: src/backend/distributed/planner/recursive_planning.c [hunk 1]
```diff
@@ -314,6 +314,11 @@ RecursivelyPlanSubqueriesAndCTEs(Query *query, RecursivePlanningContext *context
 		RecursivelyPlanAllSubqueries((Node *) query->jointree->quals, context);
 	}
 
+	if (query->havingQual != NULL)
+	{
+		RecursivelyPlanAllSubqueries((Node *) query->havingQual, context);
```
Comment (marcocitus) [inline src/backend/distributed/planner/recursive_planning.c]: Are there cases in which we can normally push this down? E.g. select on reference table?

Comment (serprex) [reply src/backend/distributed/planner/recursive_planning.c]: Might be best to fold this into `RecursivelyPlanNonColocatedSubqueries`. Will include a test that has a plan which differs between the two approachs

Comment (marcocitus) [reply src/backend/distributed/planner/recursive_planning.c]: Seems like we don't really support pushing down subqueries in having and the planner will end up doing the wrong thing if we allow selects on reference tables to go through here: The plan will select from the local reference table, rather than pushing down the subquery. Added a comment to #3433.

**Comment by serprex** [comment]
```
SELECT DISTINCT l_orderkey, avg(l_linenumber)
FROM lineitem_hash_part
GROUP BY l_orderkey
HAVING avg(l_linenumber) = (select avg(distinct l_linenumber))
LIMIT 10;
ERROR:  invalid attnum 4 for relation "worker_subquery"
```

**Comment by marcocitus** [comment]
This does not address the main problem of invalid results yet:
```
explain SELECT x, count(*) FROM test GROUP BY x HAVING (SELECT a FROM ref where a = 1) > 0;
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                            QUERY PLAN                                            │
├──────────────────────────────────────────────────────────────────────────────────────────────────┤
│ HashAggregate  (cost=538.25..541.75 rows=200 width=12)                                           │
│   Group Key: remote_scan.x                                                                       │
│   InitPlan 1 (returns $0)                                                                        │
│     ->  Seq Scan on ref  (cost=0.00..38.25 rows=11 width=4)                                      │
│           Filter: (a = 1)                                                                        │
│   ->  Result  (cost=0.00..0.00 rows=100000 width=12)                                             │
│         One-Time Filter: ($0 > 0)                                                                │
│         ->  Custom Scan (Citus Adaptive)  (cost=0.00..0.00 rows=100000 width=12)                 │
│               Filter: ($0 > 0)                                                                   │
│               Task Count: 32                                                                     │
│               Tasks Shown: One of 32                                                             │
│               ->  Task                                                                           │
│                     Node: host=localhost port=9700 dbname=postgres                               │
│                     ->  HashAggregate  (cost=43.90..45.90 rows=200 width=12)                     │
│                           Group Key: test.x                                                      │
│                           ->  Seq Scan on test_102008 test  (cost=0.00..32.60 rows=2260 width=4) │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
```

It would be good if we can address this one as a separate PR, which we then backport to 9.2. The fixes for all the weird errors we can include in 9.3.

File: src/backend/distributed/planner/multi_logical_optimizer.c [hunk 2]
```diff
@@ -2013,6 +2013,10 @@ MasterAggregateExpression(Aggref *originalAggregate,
 			elog(ERROR, "Aggregate lacks COMBINEFUNC");
 		}
 	}
+	else if (aggregateType == AGGREGATE_CUSTOM_NO_PUSHDOWN)
```
Comment (serprex) [inline src/backend/distributed/planner/multi_logical_optimizer.c:2016]: This doesn't make sense. We need the aggregate to be applied to every record, even if the parameters are constant
