### PR TITLE
Do not rely on set_rel_pathlist_hook for finding local relations

### LINKED ISSUE #4280: Join with Recursive View and Condition Fails
```
CREATE TABLE local_table(a INT);
CREATE RECURSIVE VIEW vw(c) AS (SELECT 1 FROM local_table);

CREATE TABLE ref_table(b INT);
SELECT create_reference_table('ref_table');

SELECT * FROM ref_table LEFT OUTER JOIN (SELECT * FROM vw WHERE FALSE) AS sub ON FALSE;

ERROR:  relation "public.local_table" does not exist
CONTEXT:  while executing command on localhost:9701
```
This query does not fail when the view is not recursive or when there is no `WHERE FALSE` statement.

### PR DESCRIPTION
**Pull request by onderkalaci**
When a relation is used on an OUTER JOIN with FALSE filters,
set_rel_pathlist_hook may not be called for the table.

There might be other cases as well, so do not rely on the hook
for classification of the tables.

DESCRIPTION: Fixes a bug that cause failures when RECURSIVE VIEW joined reference table

Fixes #4280

### CODE REVIEW

File: src/backend/distributed/planner/multi_logical_planner.c [hunk 1]
```diff
@@ -334,6 +334,18 @@ IsCitusTableRTE(Node *node)
...
 
 
+/*
+ * IsLocalPostgresTableRTE gets a node and returns true if the node is a
+ * range table relation entry that points to a local postgres relation.
+ */
+bool
+IsLocalPostgresTableRTE(Node *node)
+{
+	Oid relationId = NodeTryGetRteRelid(node);
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_logical_planner.c:344]: do we need to be concerned about partitioned tables, views, etc.?

it seems this function is strictly identifying relations

Comment (onderkalaci) [reply src/backend/distributed/planner/multi_logical_planner.c:344]: That's a good point. On the hook, we don't get Views/Mat views, so we don't qualify those as local tables. Now, we do.

Looking to find a solution

Comment (marcocitus) [reply src/backend/distributed/planner/multi_logical_planner.c:344]: The current check in NodeTryGetRteRelid on master is:
```

    if (!(rangeTableEntry->rtekind == RTE_RELATION &&
          rangeTableEntry->relkind == RELKIND_RELATION))
    {
        return InvalidOid;
    }
```

which means it would return InvalidOid for a partitioned/foreign/matview local table when it probably shouldn't

File: src/backend/distributed/planner/multi_router_planner.c [hunk 2]
```diff
@@ -2267,8 +2265,10 @@ PlanRouterQuery(Query *originalQuery,
 	/* we need anchor shard id for select queries with router planner */
 	uint64 shardId = GetAnchorShardId(*prunedShardIntervalListList);
 
-	bool hasLocalRelation = relationRestrictionContext->hasLocalRelation;
-
+	/* both Postgres tables and materialized tables are locally avaliable */
```
Comment (onderkalaci) [inline src/backend/distributed/planner/multi_router_planner.c:2268]: my current thinking is to  consider :
```C
bool hasLocalRelation =
		rteProperties->hasPostgresLocalTable || rteProperties->hasMaterializedView;
```

What  we are looking for is wether the data is locally avaliable or not on a PG table. Regular views are different because they are already expanded in  the  queryTree,  so any local tables inside the  view will be detected  anyway. For materialized  views, that's not the case.

Does that make sense  @marcocitus ?

File: src/backend/distributed/planner/multi_logical_planner.c (hunk 1 above)
Comment (onderkalaci) [reply src/backend/distributed/planner/multi_logical_planner.c]: That is certainly a bug that we are fixing on #4294. This bug leads to various issues with partitioned/foreign tables

File: src/backend/distributed/planner/multi_router_planner.c (hunk 2 above)
Comment (marcocitus) [reply src/backend/distributed/planner/multi_router_planner.c:2268]: I think materialized view is oddly selective. What about RELKIND_FOREIGN_TABLE or RELKIND_PARTITIONED_TABLE?

Comment (marcocitus) [reply src/backend/distributed/planner/multi_router_planner.c:2268]: I guess those do fall through to hasPostgresLocalTable. 

Is there a way to treat materialized views in the same way? or are they too special?

It's going to be hard to remember these subtle distinctions.

Comment (marcocitus) [reply src/backend/distributed/planner/multi_router_planner.c:2268]: Name should probably be hasPostgresLocalRelation

Comment (onderkalaci) [reply src/backend/distributed/planner/multi_router_planner.c:2268]: > Is there a way to treat materialized views in the same way? or are they too special?

Unfortunately they look special :/ 

For regular tables, partitioned tables or foreign tables, they can be a local or distributed tables and we can qualify them accurately.

For regular views, we don't care because their definitions are already be in the same query tree.

For Mat views, they are just local tables in the queries. But, when `REFRESH 
 MATERIALIZED VIEW` is used, it behaves similar to regular views, adds the definition.

So, still looking for a middle ground

Comment (marcocitus) [reply src/backend/distributed/planner/multi_router_planner.c:2268]: got it, thanks for the clarification. Can you add that clarification to a comment somewhere?

Comment (onderkalaci) [reply src/backend/distributed/planner/multi_router_planner.c:2268]: This is not the best approach to  detect  joins between local tables/mat.view, but seems ok to continue for now.

 We should probably explicitly check the joinTree as opposed to any rangeTable entry in the queryTree. That'd improve the situation a bit. I'll follow up such a change in #4128 as that's already explicitly checking joins

Comment (onderkalaci) [reply src/backend/distributed/planner/multi_router_planner.c:2268]: For  this  specific point, when user does a `REFRESH MAT VIEW` where the underlying query is a router query, we'll have `rteProperties->hasMaterializedView = true` and router planner would fail. Looking into that:
```SQL
create materialized view router_view as select * from users_table WHERE user_id = 1 FOR UPDATE;
SELECT 7
Time: 133.988 ms
ERROR:  could not run distributed query with FOR UPDATE/SHARE commands
HINT:  Consider using an equality filter on the distributed table's partition column.
Time: 3.502 ms
```

Comment (onderkalaci) [reply src/backend/distributed/planner/multi_router_planner.c:2268]: Though it is not a regression from 9.4. It is the same at least from Citus  8.3 (the error messages were different: `ERROR:  relation router_view is not distributed`

So, I'm leaning towards leaving this as is and open an issue. What do you think?

Comment (onderkalaci) [reply src/backend/distributed/planner/multi_router_planner.c:2268]: We should be doing something like: https://github.com/citusdata/citus/commit/48025072431e3946ff342ff3e230840de6e08bbc though I  don't want to change the behavior right before the release.

And, we should probably doing  similar changes in some other places as well

Comment (onderkalaci) [reply src/backend/distributed/planner/multi_router_planner.c:2268]: (https://github.com/citusdata/citus/issues/4297)

File: src/backend/distributed/planner/distributed_planner.c [hunk 3]
```diff
@@ -2308,12 +2305,25 @@ GetRTEListProperties(List *rangeTableList)
...
+			 *
+			 * Regular tables, partitioned tables or foreign tables can be a local or
+			 * distributed tables and we can qualify them accurately.
+			 *
+			 * For regular views, we don't care because their definitions are already
+			 * in the same query tree and we can detect what is inside the view definition.
+			 *
+			 * For materialized views, they are just local tables in the queries. But, when
+			 * REFRESH MATERIALIZED VIEW is used, they behave similar to regular views, adds
+			 * the view definition to the query. Hence,
```
Comment (marcocitus) [inline src/backend/distributed/planner/distributed_planner.c:2324]: missing words

**Review by marcocitus — APPROVED** [review]

**Comment by onurctirtir** [comment]
This also fixes https://github.com/citusdata/citus/issues/4392

**Comment by onurctirtir** [comment]
We should backport this to 9.4 but it wouldn't be trivial as this pr depends on `GetRTEListProperties` and but `GetRTEListProperties` depends on https://github.com/citusdata/citus/pull/4132, which is slightly a major change.
