### PR TITLE
Prevent outer join crash when subquery is flatten

### LINKED ISSUE #601: Various crashes with multiple restrictions in ON clauses
```
DROP TABLE IF EXISTS a;
DROP TABLE IF EXISTS b;
DROP TABLE IF EXISTS target;

CREATE TABLE a(category_id int NOT NULL, data text NOT NULL);
CREATE TABLE b(category_id int NOT NULL, data text NOT NULL);
CREATE TABLE target(category_id int NOT NULL, data text NOT NULL);

CREATE INDEX a_category_id ON a(category_id);
CREATE INDEX b_category_id ON b(category_id);
CREATE INDEX target_category_id ON target(category_id);


SELECT master_create_distributed_table('a', 'category_id', 'hash');
SELECT master_create_distributed_table('b', 'category_id', 'hash');
SELECT master_create_distributed_table('target', 'category_id', 'hash');

SELECT master_create_worker_shards('a', 16, 1);
SELECT master_create_worker_shards('b', 16, 1);
SELECT master_create_worker_shards('target', 16, 1);

INSERT INTO a VALUES('1', 'frakbar');
INSERT INTO a VALUES('1', 'barfrak');
INSERT INTO b VALUES('1', 'frakbar');
INSERT INTO b VALUES('1', 'barfrak');
```

running
```
postgres[1992][1]=# SELECT * FROM a JOIN b ON (a.category_id = b.category_id) LEFT JOIN target ON (a.category_id = target.category_id AND target.category_id = -1);
```
yields
```
#0  0x00007fd0515d6458 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007fd0515d78da in __GI_abort () at abort.c:89
#2  0x0000000000926a65 in ExceptionalCondition (conditionName=0x7fd050e645e9 "!(list_length(varList) == 1)", errorType=0x7fd050e643e6 "FailedAssertion", 
    fileName=0x7fd050e64250 "/home/andres/src/citusdb/src/backend/distributed/planner/multi_join_order.c", lineNumber=1482) at /home/andres/src/postgresql-9.5/src/backend/utils/error/assert.c:54
#3  0x00007fd050e1f939 in RightColumn (joinClause=0x164d1b0) at /home/andres/src/citusdb/src/backend/distributed/planner/multi_join_order.c:1482
#4  0x00007fd050e2f49e in JoinSequenceArray (rangeTableFragmentsList=0x7fd0527e9040, jobQuery=0x7fd052841f40, dependedJobList=0x0) at /home/andres/src/citusdb/src/backend/distributed/planner/multi_physical_planner.c:3290
#5  0x00007fd050e2f007 in FragmentCombinationList (rangeTableFragmentsList=0x7fd0527e9040, jobQuery=0x7fd052841f40, dependedJobList=0x0) at /home/andres/src/citusdb/src/backend/distributed/planner/multi_physical_planner.c:3126
#6  0x00007fd050e2d786 in SqlTaskList (job=0x7fd052842058) at /home/andres/src/citusdb/src/backend/distributed/planner/multi_physical_planner.c:2166
#7  0x00007fd050e2cec4 in BuildJobTreeTaskList (jobTree=0x7fd052842058) at /home/andres/src/citusdb/src/backend/distributed/planner/multi_physical_planner.c:1869
#8  0x00007fd050e29f36 in MultiPhysicalPlanCreate (multiTree=0x7fd052831240) at /home/andres/src/citusdb/src/backend/distributed/planner/multi_physical_planner.c:213
#9  0x00007fd050e3310d in CreatePhysicalPlan (parse=0x15993a8) at /home/andres/src/citusdb/src/backend/distributed/planner/multi_planner.c:99
#10 0x00007fd050e33010 in multi_planner (parse=0x15993a8, cursorOptions=0, boundParams=0x0) at /home/andres/src/citusdb/src/backend/distributed/planner/multi_planner.c:54
#11 0x000000000072026d in planner (parse=0x15993a8, cursorOptions=0, boundParams=0x0) at /home/andres/src/postgresql-9.5/src/backend/optimizer/plan/planner.c:155
#12 0x00000000007e2641 in pg_plan_query (querytree=0x15993a8, cursorOptions=0, boundParams=0x0) at /home/andres/src/postgresql-9.5/src/backend/tcop/postgres.c:809
#13 0x00000000007e26f4 in pg_plan_queries (querytrees=0x162d190, cursorOptions=0, boundParams=0x0) at /home/andres/src/postgresql-9.5/src/backend/tcop/postgres.c:868
#14 0x00000000007e2999 in exec_simple_query (query_string=0x1597808 "SELECT * FROM a JOIN b ON (a.category_id = b.category_id) LEFT JOIN target ON (a.category_id = target.category_id AND target.category_id = -1);")
    at /home/andres/src/postgresql-9.5/src/backend/tcop/postgres.c:1033
#15 0x00000000007e6b89 in PostgresMain (argc=1, argv=0x157e970, dbname=0x157e7d0 "postgres", username=0x157e7b0 "andres") at /home/andres/src/postgresql-9.5/src/backend/tcop/postgres.c:4030
#16 0x000000000076577c in BackendRun (port=0x159ee50) at /home/andres/src/postgresql-9.5/src/backend/postmaster/postmaster.c:4239
#17 0x0000000000764ee0 in BackendStartup (port=0x159ee50) at /home/andres/src/postgresql-9.5/src/backend/postmaster/postmaster.c:3913
#18 0x00000000007616e8 in ServerLoop () at /home/andres/src/postgresql-9.5/src/backend/postmaster/postmaster.c:1684
#19 0x0000000000760d1d in PostmasterMain (argc=9, argv=0x157d0d0) at /home/andres/src/postgresql-9.5/src/backend/postmaster/postmaster.c:1292
#20 0x00000000006b9de3 in main (argc=9, argv=0x157d0d0) at /home/andres/src/postgresql-9.5/src/backend/main/main.c:228
```

running
```
CREATE FUNCTION returnfalse() RETURNS bool LANGUAGE plpgsql VOLATILE AS $$BEGIN RETURN false;END;$$;
SELECT * FROM a JOIN b ON (a.category_id = b.category_id) LEFT JOIN target ON (a.category_id = target.category_id AND returnfalse());
```
yields
```
#0  0x00007fd0515d6458 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007fd0515d78da in __GI_abort () at abort.c:89
#2  0x0000000000926a65 in ExceptionalCondition (conditionName=0x7fd050e64930 "!(list_length(selectColumnList) > 0)", errorType=0x7fd050e6473b "FailedAssertion", 
    fileName=0x7fd050e646e8 "/home/andres/src/citusdb/src/backend/distributed/planner/multi_logical_optimizer.c", lineNumber=814) at /home/andres/src/postgresql-9.5/src/backend/utils/error/assert.c:54
#3  0x00007fd050e208f8 in SelectClauseTableIdList (selectClauseList=0x7fd05282ef98) at /home/andres/src/citusdb/src/backend/distributed/planner/multi_logical_optimizer.c:814
#4  0x00007fd050e2075f in Distributive (parentNode=0x7fd05282f058, childNode=0x7fd05282ee08) at /home/andres/src/citusdb/src/backend/distributed/planner/multi_logical_optimizer.c:751
#5  0x00007fd050e20468 in CanPushDown (parentNode=0x7fd05282f058) at /home/andres/src/citusdb/src/backend/distributed/planner/multi_logical_optimizer.c:605
#6  0x00007fd050e1ffd5 in PushDownNodeLoop (currentNode=0x7fd05282f058) at /home/andres/src/citusdb/src/backend/distributed/planner/multi_logical_optimizer.c:389
#7  0x00007fd050e1fc36 in MultiLogicalPlanOptimize (multiLogicalPlan=0x7fd05282f370) at /home/andres/src/citusdb/src/backend/distributed/planner/multi_logical_optimizer.c:243
#8  0x00007fd050e330f5 in CreatePhysicalPlan (parse=0x1599240) at /home/andres/src/citusdb/src/backend/distributed/planner/multi_planner.c:87
#9  0x00007fd050e33010 in multi_planner (parse=0x1599240, cursorOptions=0, boundParams=0x0) at /home/andres/src/citusdb/src/backend/distributed/planner/multi_planner.c:54
#10 0x000000000072026d in planner (parse=0x1599240, cursorOptions=0, boundParams=0x0) at /home/andres/src/postgresql-9.5/src/backend/optimizer/plan/planner.c:155
#11 0x00000000007e2641 in pg_plan_query (querytree=0x1599240, cursorOptions=0, boundParams=0x0) at /home/andres/src/postgresql-9.5/src/backend/tcop/postgres.c:809
#12 0x00000000007e26f4 in pg_plan_queries (querytrees=0x1631088, cursorOptions=0, boundParams=0x0) at /home/andres/src/postgresql-9.5/src/backend/tcop/postgres.c:868
#13 0x00000000007e2999 in exec_simple_query (query_string=0x1597808 "SELECT * FROM a JOIN b ON (a.category_id = b.category_id) LEFT JOIN target ON (a.category_id = target.category_id AND returnfalse());")
    at /home/andres/src/postgresql-9.5/src/backend/tcop/postgres.c:1033
```

it's also wrong / misleading to output this:
```
postgres[2522][1]=# SELECT * FROM a JOIN b ON (a.category_id = b.category_id) LEFT JOIN target ON (a.category_id = target.category_id AND false);
ERROR:  0A000: cannot perform distributed planning on this query
DETAIL:  Shards of relations in outer join queries must have 1-to-1 shard partitioning
LOCATION:  FixedJoinOrderList, multi_join_order.c:236
Time: 7.539 ms
```
although it doesn't crash.

### LINKED ISSUE #657: Segmentation fault on outer joins for flattened out subquery
@fdr reproduced "segmentation fault on flattened out subquery" in the cloud repo. @mtuncer proposed a fix for it today. I'm copy/pasting their comments to this issue.

@fdr commented:

Version: 5.1.1, as seen on Citus Cloud. I reproduced this.

Highlight: the pointer nextTable is NULL, and dereferenced.

Query
```
SELECT
  AVG((base.j->>'first_reply_time')::bigint) av,
  requester.j->>'email' email
FROM (
  SELECT j, pk
  FROM records
  WHERE join_path = 'd41d8cd98f00b204e9800998ecf8427e'
  AND service = 'zendesk'
  AND team_ark_id = 'ark_team_4c348ea1_3a56_11e6_86df_6c40089cf8ca'
  AND resource = 'tickets'
) base
LEFT JOIN (
  SELECT j, pk
  FROM records
  WHERE join_path = 'f9a5ae780fd012fd46e6d333f0f73fd1'
  AND service = 'zendesk'
  AND team_ark_id = 'ark_team_4c348ea1_3a56_11e6_86df_6c40089cf8ca'
  AND resource = 'tickets'
) requester ON base.pk = requester.pk
GROUP BY email
ORDER BY av DESC
LIMIT 50;
```

Schema
```
CREATE TABLE records (
    pk text,
    j jsonb,
    join_path text,
    team_ark_id text,
    service text,
    resource text
);


CREATE INDEX records_join_path ON records USING btree (join_path, team_ark_id, service, resource);

SELECT master_create_distributed_table('records', 'pk', 'hash');
SELECT master_create_worker_shards('records', 32);
```

GDB transcript
```
Program received signal SIGSEGV, Segmentation fault.
0x00007f1c975878bf in FixedJoinOrderList (fromExpr=<optimized out>, tableEntryList=tableEntryList@entry=0x7f1ca29f6858)
    at planner/multi_join_order.c:178
178                     candidateShardList = LoadShardIntervalList(nextTable->relationId);
(gdb) bt
#0  0x00007f1c975878bf in FixedJoinOrderList (fromExpr=<optimized out>, tableEntryList=tableEntryList@entry=0x7f1ca29f6858)
    at planner/multi_join_order.c:178
#1  0x00007f1c9758d58c in MultiPlanTree (queryTree=queryTree@entry=0x23f0cd0) at planner/multi_logical_planner.c:307
#2  0x00007f1c9758da78 in MultiLogicalPlanCreate (queryTree=queryTree@entry=0x23f0cd0) at planner/multi_logical_planner.c:128
#3  0x00007f1c975935e8 in CreatePhysicalPlan (parse=parse@entry=0x2317678) at planner/multi_planner.c:86
#4  0x00007f1c975937c8 in multi_planner (parse=0x2317678, cursorOptions=<optimized out>, boundParams=<optimized out>)
    at planner/multi_planner.c:54
#5  0x00000000006b8dfa in pg_plan_query (querytree=<optimized out>, cursorOptions=<optimized out>, boundParams=<optimized out>)
    at postgres.c:809
#6  0x00000000006b8ee4 in pg_plan_queries (querytrees=<optimized out>, cursorOptions=0, boundParams=0x0) at postgres.c:868
#7  0x00000000006b9504 in exec_simple_query (
    query_string=0x22e5b30 "SELECT\n  AVG((base.j->>'first_reply_time')::bigint) av,\n  requester.j->>'email' email\nFROM (\n  SELECT j, pk\n  FROM records\n  WHERE join_path = 'd41d8cd98f00b204e9800998ecf8427e'\n  AND service = 'zende"...) at postgres.c:1033
#8  0x00000000006baa45 in PostgresMain (argc=<optimized out>, argv=<optimized out>, dbname=0x231e1c8 "citus", username=<optimized out>)
    at postgres.c:4030
#9  0x0000000000661490 in BackendRun (port=0x2310d10) at postmaster.c:4239
#10 BackendStartup (port=0x2310d10) at postmaster.c:3913
#11 ServerLoop () at postmaster.c:1684
#12 PostmasterMain (argc=<optimized out>, argv=<optimized out>) at postmaster.c:1292
#13 0x00000000005f3388 in main (argc=3, argv=0x22cb6b0) at main.c:228
(gdb) list
173                             /* also consider WHERE clauses for INNER joins */
174                             joinClauseList = list_concat(joinClauseList, joinWhereClauseList);
175                     }
176
177                     /* get the sorted list of shards to check broadcast/local join possibility */
178                     candidateShardList = LoadShardIntervalList(nextTable->relationId);
179
180                     /* find the best join rule type */
181                     nextJoinNode = EvaluateJoinRules(joinedTableList, currentJoinNode,
182                                                                                      nextTable, candidateShardList,
(gdb) p nextTable
$1 = (TableEntry *) 0x0
(gdb) info locals
onClauseList = 0x7f1ca29f7b20
joinType = JOIN_LEFT
nextRangeTableRef = <optimized out>
nextTable = 0x0
joinExpr = <optimized out>
joinClauseList = 0x7f1ca29f7b70
nextJoinNode = 0x0
candidateShardList = 0x0
joinList = <optimized out>
joinCell = 0x7f1ca29f6b40
joinWhereClauseList = 0x0
joinOrderList = 0x7f1ca29f7a80
joinedTableList = 0x7f1ca29f7ad0
firstJoinNode = <optimized out>
currentJoinNode = 0x7f1ca29f6be0
tableEntryCell = <optimized out>
__func__ = "FixedJoinOrderList"
```

### PR DESCRIPTION
**Pull request by mtuncer**
This fixes crash in multi_join_order::FixedJoinOrderList function due to dereferencing a null pointer.

postgresql standand planner leaves some recursive structure in Query->joinExpr after flattening out a subquery.  In this case a subquery outer join is get flattened to a single level query.  We expect a join tree where each right child is a ```RangeTblRef *``` but in this case we found another ```FromExpr*``` with expected ```RangeTblRef *``` is inside ```FromExpr->fromList``` list as the only element. Depending on the flattening level of a subquery ```FromExpr->fromList``` may contain another ```FromExpr *```.

Full fix involves better selection of where clauses when outer join is present and recursively looking for RangeTblRef inside joinExpr->rarg. 

This work only detects the unexpected structure an errors out.

Also added a regression test to cover the query that caused the crash.

fixes #657 
Fixes #601

### CODE REVIEW

File: src/backend/distributed/planner/multi_join_order.c [hunk 1]
```diff
@@ -398,6 +399,42 @@ ExtractLeftMostRangeTableIndex(Node *node, int *rangeTableIndex)
...
+	if (IsA(joinExprRightArg, RangeTblRef))
+	{
+		rangeTableRef = (RangeTblRef *) joinExprRightArg;
+	}
+	else if (IsA(joinExprRightArg, FromExpr))
+	{
+		FromExpr *fromExpr = (FromExpr *) joinExprRightArg;
+		Node *firstNode = NULL;
+
+		Assert(list_length(fromExpr->fromlist) == 1);
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_join_order.c]: Could this be >1?

Comment (mtuncer) [inline src/backend/distributed/planner/multi_join_order.c]: JoinExpr is already taken care of in logical planner ```ErrorIfQueryNotSupported()``` after call to ```HasComplexJoinOrder()```

Comment (marcocitus) [inline src/backend/distributed/planner/multi_join_order.c]: Don't we just ignore the rarg if it's not a JoinExpr in HasComplexJoinOrder? In this case rarg is a FromExpr with stuff inside, so it's not seen as a complex join.

Comment (mtuncer) [inline src/backend/distributed/planner/multi_join_order.c]: correct. If there is a join expr on rarg, it is rejected there.  So far we could only found rarg to be RangeTblRef* or FromExpr*. 

We never seen JoinExpr inside FromExpr->fromlist during tests, we could crash if that happens.

Comment (marcocitus) [inline src/backend/distributed/planner/multi_join_order.c]: So this might be pedantic then, but could we error out somewhere to make sure we never crash?

Comment (mtuncer) [inline src/backend/distributed/planner/multi_join_order.c]: I will add that to HasComplexJoinOrder where we report error depending on the result of the function.

Comment (marcocitus) [inline src/backend/distributed/planner/multi_join_order.c]: Makes sense.

Comment (mtuncer) [inline src/backend/distributed/planner/multi_join_order.c]: just pushed, however restricted the check to outer joins only.

File: src/backend/distributed/planner/multi_logical_planner.c [hunk 2]
```diff
@@ -636,13 +637,66 @@ HasComplexJoinOrder(Query *queryTree)
 			hasComplexJoinOrder = true;
 			break;
 		}
+
+		/*
+		 * join tree structure is more important for outer joins. right branch
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_logical_planner.c]: Does it not matter for inner joins, or does this situation not happen?

(ultra minor: comment should start with capital letter)

File: src/test/regress/output/multi_outer_join.source [hunk 3]
```diff
@@ -732,6 +732,64 @@ LOG:  join order: [ "multi_outer_join_right" ][ local partition join "multi_oute
...
+
+-- this query is flattened out to following by postgresql
+SELECT 
+	l1.l_custkey, count(*) AS cnt
+FROM (
+	multi_outer_join_left l1 
+	LEFT JOIN
+	multi_outer_join_right l2
+	ON ((l1.l_custkey = l2.r_custkey))) 
+WHERE ( l1.l_comment like '%a%' AND l2.r_comment like '%b%')
```
Comment (marcocitus) [inline src/test/regress/output/multi_outer_join.source]: Shouldn't the l2.r_comment like '%b%' be in the ON() section? Otherwise this would be transformed into an inner join.

**Comment by marcocitus** [comment]
Makes sense 🚢 , you should update the PR description, otherwise it auto-clauses the issues.
