### PR TITLE
Pass text oid instead of invalid oid for null values

### LINKED ISSUE #752: Insert query with arguments inside a plpgsql function fails to evaluate parameters
Version: Citus 5.2
**Steps to reproduce:**
```
create table table1 (
key int not null,
value int
);
select master_create_distributed_table('table1','key','hash');
select master_create_worker_shards('table1',16,1);

create table table2 (
key int not null,
value int
);
select master_create_distributed_table('table2','key','hash');
select master_create_worker_shards('table2',16,1);

CREATE OR REPLACE FUNCTION insert_func( key_arg int,
val_arg int
) RETURNS void as $$
DECLARE
distribution_col CONSTANT INTEGER := key_arg;
BEGIN
INSERT INTO table1 (key, value)
VALUES (distribution_col,val_arg);
END;
$$ language plpgsql;
select insert_func(1,3);
```
**Error:**
```
WARNING:  could not determine data type of parameter $1
CONTEXT:  while executing command on <ip>:5432
SQL statement "INSERT INTO table1 (key, value)
VALUES (distribution_col,val_arg)"
PL/pgSQL function insert_func(integer,integer) line 5 at SQL statement
ERROR:  could not modify any active placements
CONTEXT:  SQL statement "INSERT INTO table1 (key, value)
VALUES (distribution_col,val_arg)"
PL/pgSQL function insert_func(integer,integer) line 5 at SQL statement
```

Even if I hardcode the partition column as below, similar error persists:
```
CREATE OR REPLACE FUNCTION insert_func( key_arg int,
val_arg int
) RETURNS void as $$
DECLARE
distribution_col CONSTANT INTEGER := key_arg;
BEGIN
INSERT INTO table1 (key, value)
VALUES (1,val_arg);
END;
$$ language plpgsql;
```

A simple work around is to wrap the INSERT statement in an EXECUTE.
```
CREATE OR REPLACE FUNCTION test_schema.insert_func( key_arg int,
val_arg int
) RETURNS void as $$
DECLARE
distribution_id CONSTANT INTEGER := key_arg;
BEGIN
EXECUTE format('INSERT INTO test_schema.table1 (key, value)
VALUES (%s,%s)',distribution_id,val_arg);
END;
$$ language plpgsql;
```

### PR DESCRIPTION
**Pull request by metdos**
Passing invalid oids even for null values in PQsendQueryParams() causes worker
nodes to fail. Therefore, we pass text oid for null values.

Fixes #752.

### CODE REVIEW

**Comment by metdos** [comment]
Hey @anarazel, after discovering a bug in router executor selects, I have noticed a simpler solution to this problem and changed the code.

The first commit is a copy of PR 776 which is required for my fix. After PR 776 is merged to master, I will remove it from this PR.

File: src/test/regress/sql/multi_prepare_plsql.sql [hunk 1]
```diff
@@ -247,6 +247,104 @@ SELECT plpgsql_test_2();
...
+SELECT master_create_distributed_table('temp_table','key','hash');
+SELECT master_create_worker_shards('temp_table',4,1);
+
+CREATE OR REPLACE FUNCTION no_parameter_insert() RETURNS void as $$
+BEGIN
+	INSERT INTO temp_table (key) VALUES (0);
+END;
+$$ LANGUAGE plpgsql;
+
+SELECT no_parameter_insert();
```
Comment (anarazel) [inline src/test/regress/sql/multi_prepare_plsql.sql]: Add comment along the lines of ```-- execute 6 times to trigger prepared statement usage ```

File: src/test/regress/sql/multi_prepare_plsql.sql [hunk 2]
```diff
@@ -247,6 +247,104 @@ SELECT plpgsql_test_2();
...
+		key,
+		value;
+END;
+$$ LANGUAGE plpgsql;
+
+SELECT partition_column_select(1);
+SELECT partition_column_select(2);
+SELECT partition_column_select(3);
+SELECT partition_column_select(4);
+SELECT partition_column_select(5);
```
Comment (anarazel) [inline src/test/regress/sql/multi_prepare_plsql.sql]: I'd rather test the failing case as well here, with a ```-- will fail``` comment

File: src/test/regress/sql/multi_prepare_plsql.sql [hunk 3]
```diff
@@ -247,6 +247,104 @@ SELECT plpgsql_test_2();
...
+		key,
+		value;
+END;
+$$ LANGUAGE plpgsql;
+
+SELECT non_partition_column_select(10);
+SELECT non_partition_column_select(20);
+SELECT non_partition_column_select(30);
+SELECT non_partition_column_select(40);
+SELECT non_partition_column_select(50);
```
Comment (anarazel) [inline src/test/regress/sql/multi_prepare_plsql.sql]: Why only five times here?

**Comment by anarazel** [comment]
This approach looks a lot better than the previous one...

File: src/test/regress/sql/multi_prepare_plsql.sql (hunk 2 above)
Comment (metdos) [inline src/test/regress/sql/multi_prepare_plsql.sql]: That's a good point. This was my initial idea, but for failing case, the order of errors changes from execution to execution.

```sql
SELECT partition_column_select(6);
WARNING:  there is no parameter $1
CONTEXT:  while executing command on localhost:57637
PL/pgSQL function partition_column_select(integer) line 4 at RETURN QUERY
WARNING:  there is no parameter $1
CONTEXT:  while executing command on localhost:57638
PL/pgSQL function partition_column_select(integer) line 4 at RETURN QUERY
WARNING:  there is no parameter $1
CONTEXT:  while executing command on localhost:57637
PL/pgSQL function partition_column_select(integer) line 4 at RETURN QUERY
WARNING:  there is no parameter $1
CONTEXT:  while executing command on localhost:57638
PL/pgSQL function partition_column_select(integer) line 4 at RETURN QUERY
WARNING:  there is no parameter $1
CONTEXT:  while executing command on localhost:57637
PL/pgSQL function partition_column_select(integer) line 4 at RETURN QUERY
WARNING:  there is no parameter $1
CONTEXT:  while executing command on localhost:57638
PL/pgSQL function partition_column_select(integer) line 4 at RETURN QUERY
WARNING:  there is no parameter $1
CONTEXT:  while executing command on localhost:57637
PL/pgSQL function partition_column_select(integer) line 4 at RETURN QUERY
WARNING:  there is no parameter $1
CONTEXT:  while executing command on localhost:57638
PL/pgSQL function partition_column_select(integer) line 4 at RETURN QUERY
WARNING:  there is no parameter $1
CONTEXT:  while executing command on localhost:57637
PL/pgSQL function partition_column_select(integer) line 4 at RETURN QUERY
WARNING:  there is no parameter $1
CONTEXT:  while executing command on localhost:57638
PL/pgSQL function partition_column_select(integer) line 4 at RETURN QUERY
ERROR:  failed to execute job 780037
DETAIL:  Failure due to failed task 2
CONTEXT:  PL/pgSQL function partition_column_select(integer) line 4 at RETURN QUERY
```

File: src/test/regress/sql/multi_prepare_plsql.sql (hunk 3 above)
Comment (metdos) [inline src/test/regress/sql/multi_prepare_plsql.sql]: This is similar to above comment. After 5th execution, we get errors in unpredictable orders.

**Comment by anarazel** [comment]
On 2016-09-21 00:33:04 -0700, Metin Döşlü wrote:
> metdos commented on this pull request.
> 
> 
> 
> > +		temp_table.value
> +	FROM
> +		temp_table
> +	WHERE
> +		temp_table.key = key_arg
> +	ORDER BY
> +		key,
> +		value;
> +END;
> +$$ LANGUAGE plpgsql;
> +
> +SELECT partition_column_select(1);
> +SELECT partition_column_select(2);
> +SELECT partition_column_select(3);
> +SELECT partition_column_select(4);
> +SELECT partition_column_select(5);
> 
> That's a good point. This was my initial idea, but for failing case, the order of errors changes from execution to execution.

How about reducing error verbosity to ERROR?

File: src/test/regress/sql/multi_prepare_plsql.sql (hunk 1 above)
Comment (metdos) [inline src/test/regress/sql/multi_prepare_plsql.sql]: > How about reducing error verbosity to ERROR?

That's a good idea, but still, job ids in the ERROR message can change because we run multi_prepare_sql and multi_prepare_plsql in parallel. We can run them sequentially, but the comment here notes that running them decreases regression test time 5 seconds.
https://github.com/citusdata/citus/issues/346#issue-134118154

What do you think? Do you have any preference?

**Comment by metdos** [comment]
> How about reducing error verbosity to ERROR?

That's a good idea, but still, job ids in the ERROR message can change because we run multi_prepare_sql and multi_prepare_plsql in parallel. We can run them sequentially, but the comment here notes that running them decreases regression test time 5 seconds.
#346 (comment)

What do you think? Do you have any preference?

**Comment by anarazel** [comment]
I think in that case it's ok to forgo the tests. But I suggest adding a comment about not wanting to run the failing test because of changing output.

**Comment by metdos** [comment]
> I think in that case it's ok to forgo the tests. But I suggest adding a comment about not wanting to run the failing test because of changing output.

I updated comments and squashed commits related to this PR. After #776 is merged, I will drop the first commit, and merge this PR.

File: src/backend/distributed/executor/multi_router_executor.c [hunk 4]
```diff
@@ -840,11 +841,14 @@ ExtractParametersFromParamListInfo(ParamListInfo paramListInfo, Oid **parameterT
...
 		 * If the parameter is NULL, or is not referenced / used (ptype == 0
 		 * would otherwise have errored out inside standard_planner()),
-		 * don't pass a value to the remote side.
+		 * don't pass a value to the remote side, and pass text oid to prevent
+		 * undetermined data type errors on workers.
 		 */
 		if (parameterData->isnull || parameterData->ptype == 0)
 		{
 			(*parameterValues)[parameterIndex] = NULL;
+			(*parameterTypes)[parameterIndex] = TEXTOID;
```
Comment (marcocitus) [inline src/backend/distributed/executor/multi_router_executor.c]: This seems to cause #978
