### PR TITLE
Fix ALTER TABLE SET SCHEMA

### LINKED ISSUE #132: Error out / warn on ALTER TABLE SET SCHEMA and ALTER TABLE ALL IN TABLESPACE
Currently, we only hook into AlterTableStmt and RenameStmt. We should also hook into these commands and error out (or warn).

### PR DESCRIPTION
**Pull request by byucesoy**
Fixes #132

We hook into ALTER ... SET SCHEMA and warn out if user tries to change schema of a
distributed table.

We also hook into ALTER TABLE ALL IN TABLE SPACE statements and warn out if citus has
been loaded.

### CODE REVIEW

**Comment by metdos** [comment]
I got an error if I follow the steps in the related issue, it seems that worker_apply_shard_ddl_command() doesn't recognize ALTER TABLE ... SET SCHEMA ...

Master:

```
postgres=# ALTER TABLE nation_hash SET SCHEMA tpch;
WARNING:  relation "nation_hash" does not exist
CONTEXT:  while executing command on localhost:9700
ERROR:  could not execute DDL command on worker node shards
```

Worker:
```
LOG:  statement: BEGIN
LOG:  statement: BEGIN
LOG:  statement: SELECT worker_apply_shard_ddl_command (102008, 'public', 'ALTER TABLE nation_hash SET SCHEMA tpch;')
LOG:  statement: ALTER TABLE nation_hash SET SCHEMA tpch;
WARNING:  unsafe statement type in name extension
DETAIL:  Statement type: 769
ERROR:  relation "nation_hash" does not exist
STATEMENT:  SELECT worker_apply_shard_ddl_command (102008, 'public', 'ALTER TABLE nation_hash SET SCHEMA tpch;')
```

File: src/backend/distributed/executor/multi_utility.c [hunk 1]
```diff
@@ -198,6 +198,26 @@ multi_ProcessUtility(Node *parsetree,
...
 			}
 		}
+
+		/*
+		 * ALTER ... SET SCHEMA statements have their node type as AlterObjectSchemaStmt
+		 * So, we intercept AlterObjectSchemaStmt to tackle these commands.
+		 */
+		if (IsA(parsetree, AlterObjectSchemaStmt))
+		{
+			ereport(NOTICE, (errmsg("Citus does not support ALTER ... SET SCHEMA")));
```
Comment (metdos) [inline src/backend/distributed/executor/multi_utility.c]: We can use a WARNING instead of NOTICE. And may we can use a similar message to this one;
```
		ereport(NOTICE, (errmsg("not propagating CREATE ROLE/USER commands to worker"
								" nodes"),
						 errhint("Connect to worker nodes directly to manually create all"
								 " necessary users and roles.")));
```

File: src/backend/distributed/executor/multi_utility.c [hunk 2]
```diff
@@ -647,6 +675,52 @@ ProcessAlterTableStmt(AlterTableStmt *alterTableStatement, const char *alterTabl
...
+	if (!OidIsValid(relationId) || !IsDistributedTable(relationId))
+	{
+		return (Node *) alterObjectSchemaStmt;
+	}
+
+	/* warn out if a distributed relation is affected */
+	ereport(WARNING, (errmsg("not propagating ALTER ... SET SCHEMA commands to "
+							 "worker nodes"),
+					  errhint("Connect to worker nodes directly to manually "
+							  "create all necessary users and roles.")));
```
Comment (metdos) [inline src/backend/distributed/executor/multi_utility.c]: You should update this :)

File: src/backend/distributed/executor/multi_utility.c [hunk 3]
```diff
@@ -198,6 +201,31 @@ multi_ProcessUtility(Node *parsetree,
...
 			}
 		}
+
+		/*
+		 * ALTER ... SET SCHEMA statements have their node type as AlterObjectSchemaStmt
+		 * So, we intercept AlterObjectSchemaStmt to tackle these commands.
+		 */
+		if (IsA(parsetree, AlterObjectSchemaStmt))
+		{
+
```
Comment (metdos) [inline src/backend/distributed/executor/multi_utility.c]: Is this new line extra?

File: src/backend/distributed/executor/multi_utility.c [hunk 4]
```diff
@@ -647,6 +675,52 @@ ProcessAlterTableStmt(AlterTableStmt *alterTableStatement, const char *alterTabl
 
 
 /*
+ * ProcessAlterObjectSchemaStmt processes ALTER ... SET SCHEMA statements for distributed
+ * objects. The function first checks if the statement belongs to a distributed objects or
+ * not. If it does, then it checks whether given object is a table. If it is, it executes
+ * distributed logic for the command.
+ *
+ * At the moment we only support ALTER TABLE SET SCHEMA. It is possible to extend this
```
Comment (metdos) [inline src/backend/distributed/executor/multi_utility.c]: We should update the copy/paste comment :)

File: src/test/regress/output/multi_alter_table_statements.source [hunk 5]
```diff
@@ -639,6 +639,16 @@ SELECT  indexname, tablename FROM pg_indexes WHERE tablename like 'lineitem_alte
 (0 rows)
 
 \c - - - :master_port
+-- test ALTER TABLE ALL IN TABLESPACE
+-- we expect that it will error out
```
Comment (metdos) [inline src/test/regress/output/multi_alter_table_statements.source]: not error out but warn out

Comment (metdos) [inline src/test/regress/output/multi_alter_table_statements.source]: And citus_indent

**Comment by metdos** [comment]
minor comments, then :ship:
