### PR TITLE
Use original relation to retrieve column name because of syscache

### LINKED ISSUE #5137: `alter_distributed_table` with dropped columns
```SQL
create table t1(a int, b int);
select create_distributed_table('t1', 'b', colocate_with:='none');
 create_distributed_table 
--------------------------
 
(1 row)

Time: 68.417 ms

alter table t1 drop column a;
ALTER TABLE
Time: 18.519 ms

 SELECT alter_distributed_table('t1', shard_count:='3');
NOTICE:  creating a new table for public.t1
ERROR:  cache lookup failed for attribute 2 of relation 26060
Time: 10.166 ms
```

Related to #5123 but a different root cause, so better to be fixed seperately

### PR DESCRIPTION
**Pull request by naisila**
Attribute syscache of the original table and the newly created table _changes_ if the original table has dropped columns. Therefore, let's use the original table's syscache.

Explaining better with an example:
```SQL
CREATE TABLE original_table (a int, b int, c int);
-- Attribute cache for original_table is:
-- column a, position 1
-- column b, position 2
-- column c, position 3
```

```SQL
ALTER TABLE original_table DROP COLUMN b;
-- Attribute cache for original_table becomes:
-- column a, position 1
-- column b, position 2, attisdropped = true
-- column c, position 3
```

```SQL
CREATE TABLE new_identical_table AS original_table;
-- Attribute cache for new_identical_table is:
-- column a, position 1
-- column c, position 2
```

Notice the difference of position of column c in these two seemingly identical tables. If column c was the distribution column for this table, we would hit the issue.

Fixes #5137

### CODE REVIEW

**Review by halilozanakgul — APPROVED** [review]
Thanks for fixing this interesting bug! 😄

File: src/backend/distributed/commands/alter_table.c [hunk 1]
```diff
@@ -1223,8 +1223,14 @@ CreateDistributedTableLike(TableConversionState *con)
...
 
+	/*
+	 * To get the correct column name, we use the original relation id, not the
+	 * new relation id. The reason is that the cached attributes of the original
+	 * and newly created tables are not the same if the original table has
+	 * dropped columns (dropped columns are still present in the attribute cache)
+	 */
 	char *distributionColumnName =
-		ColumnToColumnName(con->newRelationId, (Node *) newDistributionKey);
+		ColumnToColumnName(con->relationId, (Node *) newDistributionKey);
```
Comment (onderkalaci) [inline src/backend/distributed/commands/alter_table.c:1233]: what if `con->relationId` also has a dropped column, do we hit a similar issue?

Comment (naisila) [reply src/backend/distributed/commands/alter_table.c:1233]: This issue _is_ hit if `con->relationId` has a dropped column. Did you mean to say something else? con->newRelationId doesn't have any dropped columns because it is newly created.

Comment (onderkalaci) [reply src/backend/distributed/commands/alter_table.c:1234]: Ok, reading the code a bit more, I realized that we have:
```C
	con->distributionKey =
		BuildDistributionKeyFromColumnName(con->relationId, con->distributionColumn,
										   NoLock);
```

So, what you do is probably right. Still, dropped columns are tricky, and we had so many bugs in the past. Would you mind doing some more extensive testing: 

For example, can we also change distribution column of a table whose column is dropped? Can that column be before/after the dropped column? And/or, the dropped column is dropped even before the table is distributed?

**Comment by JelteF** [comment]
Can you add cherry-pick-xx labels to the pull request, to indicate to which versions this needs to be backported?

File: src/backend/distributed/commands/alter_table.c (hunk 1 above)
Comment (naisila) [reply src/backend/distributed/commands/alter_table.c:1234]: I think we can backport this fix all the way to 10.0

Comment (onderkalaci) [reply src/backend/distributed/commands/alter_table.c:1234]: > I think we can backport this fix all the way to 10.0

I guess up to 11.0 should be fine. Otherwise, you need to handle enterprise repo as well, which I'd probably avoid unless someone explicitly asks ;)
