### PR TITLE
Do not evaluate functions on the coordinator for SELECT queries

### LINKED ISSUE #3436: Crash when using sublink and function call without FROM
Following SQL crashes:
```sql
SELECT (SELECT count(*) FROM test), random();
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
Time: 328.922 ms
!> 
```

Stack trace:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fbe0f8f15b3 in RebuildQueryStrings (originalQuery=0x12c2920, taskList=0x12c3770) at /home/marco/pgsql-11/include/server/nodes/pg_list.h:79                                 
79              return l ? l->head : NULL;

(gdb) bt
#0  0x00007fbe0f8f15b3 in RebuildQueryStrings (originalQuery=0x12c2920, taskList=0x12c3770) at /home/marco/pgsql-11/include/server/nodes/pg_list.h:79
#1  0x00007fbe0f8d4f17 in CitusBeginScanWithCoordinatorProcessing (node=node@entry=0x1248330, estate=estate@entry=0x1248118, eflags=eflags@entry=16)
    at executor/citus_custom_scan.c:270
#2  0x00007fbe0f8d4fe9 in CitusBeginScan (node=0x1248330, estate=0x1248118, eflags=16) at executor/citus_custom_scan.c:152
#3  0x0000000000657439 in ExecInitCustomScan (cscan=cscan@entry=0x7fbe01623708, estate=estate@entry=0x1248118, eflags=eflags@entry=16) at nodeCustom.c:101
#4  0x0000000000648990 in ExecInitNode (node=node@entry=0x7fbe01623708, estate=estate@entry=0x1248118, eflags=eflags@entry=16) at execProcnode.c:282
#5  0x0000000000642a12 in InitPlan (queryDesc=queryDesc@entry=0x1250e48, eflags=eflags@entry=16) at execMain.c:1046
#6  0x0000000000642bc5 in standard_ExecutorStart (queryDesc=queryDesc@entry=0x1250e48, eflags=16, eflags@entry=0) at execMain.c:265
#7  0x00007fbe0f8da126 in CitusExecutorStart (queryDesc=0x1250e48, eflags=0) at executor/multi_executor.c:111
#8  0x0000000000642cab in ExecutorStart (queryDesc=queryDesc@entry=0x1250e48, eflags=<optimized out>) at execMain.c:145
#9  0x00000000007a8b88 in PortalStart (portal=portal@entry=0x11ae488, params=params@entry=0x0, eflags=eflags@entry=0, snapshot=snapshot@entry=0x0) at pquery.c:520
#10 0x00000000007a5460 in exec_simple_query (query_string=query_string@entry=0x10f83b8 "SELECT (SELECT count(*) FROM test), citus_total_relation_size('test');")
    at postgres.c:1106
#11 0x00000000007a7310 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x1172a08, dbname=<optimized out>, username=<optimized out>) at postgres.c:4193
#12 0x000000000072641a in BackendRun (port=port@entry=0x116c170) at postmaster.c:4364
#13 0x0000000000729471 in BackendStartup (port=port@entry=0x116c170) at postmaster.c:4036
#14 0x0000000000729680 in ServerLoop () at postmaster.c:1707
#15 0x000000000072aab3 in PostmasterMain (argc=argc@entry=3, argv=argv@entry=0x10f1b50) at postmaster.c:1380
#16 0x0000000000690023 in main (argc=3, argv=0x10f1b50) at main.c:228
```

### PR DESCRIPTION
**Pull request by onderkalaci**
Fixes #3436

Previously, the logic for evaluating the functions and the parameters
were the same. That ended-up evaluating the functions inaccurately
on the coordinator. Instead, split the function evaluation logic
from parameter evaluation logic.

### CODE REVIEW

File: src/backend/distributed/executor/citus_custom_scan.c [hunk 1]
```diff
@@ -245,20 +245,33 @@ CitusBeginScanWithCoordinatorProcessing(CustomScanState *node, EState *estate, i
...
 	/*
 	 * ExecuteMasterEvaluableFunctions handles both function evalation
 	 * and parameter evaluation. Pruning is most likely deferred because
 	 * there is a parameter on the distribution key. So, evaluate in both
 	 * cases.
 	 */
-	bool shoudEvaluteFunctionsOrParams =
-		modifyQueryRequiresMasterEvaluation || workerJob->deferredPruning;
-	if (shoudEvaluteFunctionsOrParams)
+	if (modifyQueryRequiresMasterEvaluation)
```
Comment (onderkalaci) [inline src/backend/distributed/executor/citus_custom_scan.c]: with #3388, I tried to make sure that we don't have any specific logic for modify  vs SELECT, but it turns out that my push broke some cases. So,  the aim of  these changes it  make it back as it  used to be. For modifications, to the function/param evaluation, for select queries only param evaluation when needed, otherwise do nothing.

File: src/test/regress/expected/master_evaluation.out [hunk 2]
```diff
@@ -0,0 +1,127 @@
+CREATE SCHEMA master_evaluation;
```
Comment (onderkalaci) [inline src/test/regress/expected/master_evaluation.out]: we seem to have specific tests for local execution master  evaluation for modifications:  https://github.com/citusdata/citus/blob/2f0ef8bc36d84283cbac055dd1b00028b2726988/src/test/regress/expected/local_shard_execution.out#L1339-L1415

File: src/backend/distributed/utils/citus_clauses.c [hunk 3]
```diff
@@ -64,27 +88,68 @@ ExecuteMasterEvaluableFunctions(Query *query, PlanState *planState)
...
+												PartiallyEvaluateExpression,
+												masterEvaluationContext);
+	}
+
+	return expression;
+}
+
 
+static bool
+ShouldEvaluateNode(NodeTag nodeTag)
```
Comment (onderkalaci) [inline src/backend/distributed/utils/citus_clauses.c]: Missing comment, and probably find  a better  name

File: src/include/distributed/citus_clauses.h [hunk 4]
```diff
@@ -15,9 +15,25 @@
...
+
+/*
+ * This struct is used to pass information to master
+ * evaluation logic.
+ */
+typedef struct MasterEvaluationContext
+{
+	PlanState *planState;
+	bool evaluateParams;
+	bool evaluateFunctions;
```
Comment (onderkalaci) [inline src/include/distributed/citus_clauses.h]: maybe use `evaluateExpressions` instead of `evaluateFunctions `?

File: src/backend/distributed/executor/citus_custom_scan.c [hunk 5]
```diff
@@ -245,20 +245,33 @@ CitusBeginScanWithCoordinatorProcessing(CustomScanState *node, EState *estate, i
...
+		/* we'll use generated strings, no need to have the parameters anymore */
+		EState *executorState = planState->state;
+		ResetExecutionParameters(executorState);
+
+		/* we're done,  we don't want to evaluate functions for SELECT queries */
+		return;
+	}
+	else if (jobQuery->commandType == CMD_SELECT && workerJob->deferredPruning)
+	{
+		/* evaluate parameters, we don't  want to evaluate functions for read-only queries */
```
Comment (marcocitus) [inline src/backend/distributed/executor/citus_custom_scan.c]: why not? (add answer to comment)

File: src/include/distributed/citus_clauses.h (hunk 4 above)
Comment (marcocitus) [reply src/include/distributed/citus_clauses.h]: I think evaluateFunctions is fine and consistent with the rest of the code.

File: src/test/regress/multi_mx_schedule [hunk 6]
```diff
@@ -36,7 +36,7 @@ test: recursive_dml_queries_mx multi_mx_truncate_from_worker
 test: multi_mx_repartition_udt_prepare mx_foreign_key_to_reference_table
 test: multi_mx_repartition_join_w1 multi_mx_repartition_join_w2 multi_mx_repartition_udt_w1 multi_mx_repartition_udt_w2
 test: multi_mx_metadata
-test: multi_mx_call
+test: multi_mx_call master_evaluation
```
Comment (marcocitus) [inline src/test/regress/multi_mx_schedule]: Worth adding a comment somewhere that this test relies on metadata being synced.

Comment (onderkalaci) [reply src/test/regress/multi_mx_schedule]: I added on top of `master_evaluation .sql`

File: src/backend/distributed/executor/citus_custom_scan.c [hunk 7]
```diff
@@ -245,20 +245,45 @@ CitusBeginScanWithCoordinatorProcessing(CustomScanState *node, EState *estate, i
...
+		/* we'll use generated strings, no need to have the parameters anymore */
+		EState *executorState = planState->state;
+		ResetExecutionParameters(executorState);
+
+		/* we're done,  we don't want to evaluate functions for SELECT queries */
+		return;
+	}
+	else if (jobQuery->commandType == CMD_SELECT && workerJob->deferredPruning)
+	{
+		/*
```
Comment (onderkalaci) [inline src/backend/distributed/executor/citus_custom_scan.c]: This is my understanding on the reason, my confidence is medium-high, so please give feedback if the comment doesn't make sense  to you

File: src/backend/distributed/executor/citus_custom_scan.c [hunk 8]
```diff
@@ -245,20 +245,45 @@ CitusBeginScanWithCoordinatorProcessing(CustomScanState *node, EState *estate, i
...
+		 * Evaluate parameters, because the parameters are only avaliable on the
+		 * coordinator and are required for pruning.
+		 *
+		 * But, we don't  want to evaluate functions for read-only queries on the
+		 * coordinator as the volatile functions could yield different
+		 * results per shard and could have side-effects.
```
Comment (marcocitus) [inline src/backend/distributed/executor/citus_custom_scan.c]: per shard and per row.

**Comment by onderkalaci** [comment]
it is fascinating that 4 random test failures happened on the same run. When I first saw it, I was afraid that something  is broken  :)

File: src/backend/distributed/utils/citus_clauses.c [hunk 9]
```diff
@@ -64,27 +88,72 @@ ExecuteMasterEvaluableFunctions(Query *query, PlanState *planState)
...
+	return expression;
+}
 
+
+/*
+ * ShouldEvaluateNode returns true if Citus should evaluate the
+ * input node on the coordinator.
+ */
+static bool
+ShouldEvaluateNode(NodeTag nodeTag)
```
Comment (marcocitus) [inline src/backend/distributed/utils/citus_clauses.c]: Maybe ShouldEvaluateNode -> ShouldEvaluateExpressionType?

File: src/backend/distributed/utils/citus_clauses.c [hunk 10]
```diff
@@ -160,6 +207,24 @@ citus_evaluate_expr(Expr *expr, Oid result_type, int32 result_typmod,
...
+		planState = masterEvaluationContext->planState;
+
+		if (!masterEvaluationContext->evaluateParams && IsA(expr, Param))
+		{
+			/* bail out, the caller doesn't want params to be evaluated  */
+			return expr;
+		}
+
+		if (!masterEvaluationContext->evaluateFunctions &&
+			ShouldEvaluateNode(nodeTag(expr)))
```
Comment (marcocitus) [inline src/backend/distributed/utils/citus_clauses.c]: This check is a little confusing. Can we do something like:

```c
if (IsA(expr, Param))
{
    if (!masterEvaluationContext->evaluateParams)
    {
        /* bail out, the caller doesn't want params to be evaluated  */
        return expr;
    }
}
else if (!masterEvlauationContext->evaluateFunctions)
{
    /* should only get here for node types we should evaluate */
    Assert(ShouldEvaluateNode(nodeTag(expr)));

    /* bail out, the caller doesn't want functions/expressions to be evaluated */
    return expr;
}
```
