### PR TITLE
Don't crash when upgrading to citus 6

### LINKED ISSUE #875: Upgrading from 5.2 to the master branch is failing
I didn't have time to investigate this in detail. But, upgrading from 5.2 to the current master branch is not working smoothly.

```
git checkout tags/v5.2.1
make clean -s
 make -j9 -s
sudo make install

/* a custom script that creates 3 node cluster */
init_dbs.sh 


psql -c "CREATE TABLE asd(a int);"
psql -c "SELECT master_create_distributed_table('asd', 'a', 'hash')"
psql -c "SELECT master_create_worker_shards('asd', 8, 2)"
psql -c "SELECT * FROM asd;"

git checkout master
make clean -s
 make -j9 -s
sudo make install

psql -c "SELECT * FROM asd;"


psql -c "ALTER EXTENSION citus UPDATE;"
ERROR:  could not find function "column_to_column_name" in file "/usr/local/pgsql/lib/citus.so"

/* now that restart all nodes */
restart_workers.sh 

/* still failing */
 psql -c "ALTER EXTENSION citus UPDATE;"
ERROR:  could not find function "cluster_create_distributed_table" in file "/usr/local/pgsql/lib/citus.so"
```

Besides, we've another issue that I've mentioned on #816 . We should fix these two issues before the code-freeze. In general, we should make sure that user can smoothly upgrade to 6.0

@sumedhpathak can you assign someone to work on this?

### PR DESCRIPTION
**Pull request by lithp**
Fixes #875. I couldn't reproduce the missing function error, but fixed the crash from https://github.com/citusdata/citus/pull/816

### CODE REVIEW

File: src/backend/distributed/utils/metadata_cache.c [hunk 1]
```diff
@@ -334,11 +334,19 @@ LookupDistTableCacheEntry(Oid relationId)
...
-											 tupleDescriptor,
-											 &isNull);
-		Assert(!isNull);
+		if (tupleDescriptor->natts == Natts_pg_dist_partition)
+		{
+			replicationModelDatum = heap_getattr(distPartitionTuple,
+												 Anum_pg_dist_partition_repmodel,
+												 tupleDescriptor,
+												 &isNull);
+			Assert(!isNull);
```
Comment (mtuncer) [inline src/backend/distributed/utils/metadata_cache.c]: This still keeps Assert in place. There were 2 requests to remove the assert.

Comment (marcocitus) [inline src/backend/distributed/utils/metadata_cache.c]: Well, now it really shouldn't be null here.

**Comment by sumedhpathak** [comment]
@lithp @mtuncer Anything blocking this merge? Could we prioritize wrapping this up? Thanks

**Comment by lithp** [comment]
@mtuncer Addressed your comment, rebased on master, added a better commit message

**Comment by mtuncer** [comment]
thanks 🚢
