### PR TITLE
Prevent using parallel workers for columnar tables

### LINKED ISSUE #5241: CREATE INDEX on columnar table using parallel workers fails when there are unflushed writes
Ran into the following error using alter_table_set_access_method to convert a large table with an index to columnar

```sql
create table events (event_id bigserial, event_time timestamptz default now(), payload text);
create index on events (event_id);
insert into events (payload) select 'hello-'||s from generate_series(1,10000000) s;

select alter_table_set_access_method('events','columnar');
NOTICE: creating a new table for public.events
NOTICE: moving the data of public.events
NOTICE: dropping the old public.events
NOTICE: renaming the new table to public.events
NOTICE: falling back to serial index build since parallel scan on columnar tables is not supported
ERROR: cannot update tuples during a parallel operation
CONTEXT: SQL statement "CREATE INDEX events_event_id_idx ON public.events USING btree (event_id)"
```

### PR DESCRIPTION
**Pull request by onurctirtir**
Fixes #5241.
(Rebased onto #5244 since changes done in this pr revelated another bug)

Previously, for regular table scans, we were setting `RelOptInfo->partial_pathlist`
to `NIL` via `set_rel_pathlist_hook` to discard scan `Path`s that need to use any
parallel workers, this was working nicely.

However, when building indexes, this hook doesn't get called so we were not
able to prevent spawning parallel workers when building an index. For this
reason, #4950 - 9b4dc2f804d67a1f5b41fab9d0dfeaa4fe365739 added basic
implementation for `columnar_parallelscan_*` callbacks but also made some
changes to skip using those workers when building the index.

However, now that we are doing stripe reservation in two stages, we call 
`heap_inplace_update` at some point to complete stripe reservation.
However, postgres throws an error if we call `heap_inplace_update` during
a parallel operation, even if we don't actually make use of those workers.

For this reason, with this pr, we make sure to not generate scan `Path`s that
need to use any parallel workers by using `get_relation_info_hook`.

This is indeed useful to prevent spawning parallel workers during index builds.

### CODE REVIEW

**Comment by onurctirtir** [comment]
codecov fails due to unreachable error checks, this is totally ok.

File: src/backend/columnar/columnar_customscan.c [hunk 1]
```diff
@@ -274,8 +281,14 @@ ColumnarSetRelPathlistHook(PlannerInfo *root, RelOptInfo *rel, Index rti,
...
-		/* columnar doesn't support parallel paths */
-		rel->partial_pathlist = NIL;
+		if (list_length(rel->partial_pathlist) != 0)
+		{
+			/*
+			 * Parallel scans on columnar tables are already discardad by
+			 * ColumnarGetRelationInfoHook but be on the safe side.
+			 */
+			ereport(ERROR, (errmsg("parallel scans on columnar are not supported")));
+		}
```
Comment (thanodnl) [inline src/backend/columnar/columnar_customscan.c:291]: you mentioned this code is unreachable. IIRC Postgres uses `elog(ERROR, ...)` instead of `ereport(ERROR, ...)` for these situations.

**Review by thanodnl — COMMENTED** [review]
Seems like a more legit way of disabling parallelism for columnar tables compared to removing paths we find :D

File: src/backend/columnar/columnar_customscan.c [hunk 2]
```diff
@@ -318,6 +331,23 @@ ColumnarSetRelPathlistHook(PlannerInfo *root, RelOptInfo *rel, Index rti,
...
+{
+	if (PreviousGetRelationInfoHook)
+	{
+		PreviousGetRelationInfoHook(root, relationObjectId, inhparent, rel);
+	}
+
+	if (IsColumnarTableAmTable(relationObjectId))
+	{
+		/* disable parallel query */
+		rel->rel_parallel_workers = 0;
```
Comment (jeff-davis) [inline src/backend/columnar/columnar_customscan.c:346]: Good find!

**Review by jeff-davis — APPROVED** [review]
