### PR TITLE
Do EXPLAIN ANALYZE at the same time as execution to avoid executing twice.

### LINKED ISSUE #621: Explain Analyze makes a distributed query go much slower
When the user runs a distributed query in Citus, Citus breaks up the query into query fragments and executes those query fragments in parallel.

Running `EXPLAIN ANALYZE` on a distributed query changes that behavior by running query fragments in serial. This significantly increases the distributed query's runtime. The behavior also diverges from the one users are accustomed to with Postgres. We're documenting this behavior in https://github.com/citusdata/citus_docs/issues/69.

In a meeting yesterday, we also talked about adding a `WARNING` or `NOTICE` message to immediately inform the user of this change in behavior. I'm opening this issue to add a log message to the `EXPLAIN ANALYZE` output.

@samay-sharma and @anarazel -- if you have additional feedback, could you comment on this issue?

### LINKED ISSUE #2347: EXPLAIN ANALYZE error while inserting in a distributed or reference table
I'm working with the dataset of the tutorials and while trying to use `EXPLAIN ANALYZE` in `INSERT` queries I ran into errors.

```
postgres=# SELECT * FROM companies WHERE id=5005;
 id | name | image_url | created_at | updated_at | something_unique | country
----+------+-----------+------------+------------+------------------+---------
(0 rows)

postgres=# EXPLAIN ANALYZE INSERT INTO companies (id, name, created_at, updated_at) VALUES (5005, 'citus', NOW(), NOW());
WARNING:  duplicate key value violates unique constraint "companies_pkey_102024"
DETAIL:  Key (id)=(5005) already exists.
WARNING:  could not commit transaction for shard 102024 on any active node
ERROR:  could not commit transaction on any active node
postgres=# SELECT * FROM companies WHERE id=5005;
  id  | name  | image_url |         created_at         |         updated_at         | something_unique | country
------+-------+-----------+----------------------------+----------------------------+------------------+---------
 5005 | citus |           | 2018-08-22 18:51:10.193422 | 2018-08-22 18:51:10.193422 |                  |
(1 row)
```

In this case the row is still inserted.

I ran into a similar error while inserting in a reference table. Here are the steps to reproduce:

```
CREATE TABLE countries (id serial, name varchar(250), CONSTRAINT countries_pkey PRIMARY KEY (id));

INSERT INTO countries (name) VALUES ('France');

select create_reference_table('countries');
```

Here is the error

``` 
postgres=# EXPLAIN ANALYZE INSERT INTO countries (name) VALUES ('Germany');
WARNING:  duplicate key value violates unique constraint "countries_pkey_102104"
DETAIL:  Key (id)=(3) already exists.
WARNING:  prepared transaction with identifier "citus_0_2762_6_67" does not exist
WARNING:  failed to commit transaction on citus_worker_1:5432
WARNING:  failed to roll back prepared transaction 'citus_0_2762_6_67'
HINT:  Run "COMMIT PREPARED 'citus_0_2762_6_67'" on citus_worker_1:5432
                                               QUERY PLAN
--------------------------------------------------------------------------------------------------------
 Custom Scan (Citus Router)  (cost=0.00..0.00 rows=0 width=0) (actual time=0.914..0.914 rows=0 loops=1)
   Task Count: 1
   Tasks Shown: All
   ->  Task
         Error: Could not get remote plan.
 Planning time: 0.068 ms
 Execution time: 1.029 ms
(7 rows)
```

In this case the row wasn't inserted:

```
postgres=# SELECT * FROM countries;
 id |  name
----+--------
  1 | France
(1 row)
```

In both cases using `EXPLAIN` or no `EXPLAIN` solves the problem.

Here is the result for the distributed table:

```
postgres=#  EXPLAIN INSERT INTO companies (id, name, created_at, updated_at) VALUES (5006, 'citus', NOW(), NOW());
                                QUERY PLAN
---------------------------------------------------------------------------
 Custom Scan (Citus Router)  (cost=0.00..0.00 rows=0 width=0)
   Task Count: 1
   Tasks Shown: All
   ->  Task
         Node: host=citus_worker_1 port=5432 dbname=postgres
         ->  Insert on companies_102030  (cost=0.00..0.01 rows=1 width=96)
               ->  Result  (cost=0.00..0.01 rows=1 width=96)
(7 rows)
```

And for a reference table:

```
postgres=#  EXPLAIN INSERT INTO countries (name) VALUES ('Germany');
                                 QUERY PLAN
----------------------------------------------------------------------------
 Custom Scan (Citus Router)  (cost=0.00..0.00 rows=0 width=0)
   Task Count: 1
   Tasks Shown: All
   ->  Task
         Node: host=citus_worker_1 port=5432 dbname=postgres
         ->  Insert on countries_102104  (cost=0.00..0.01 rows=1 width=520)
               ->  Result  (cost=0.00..0.01 rows=1 width=520)
(7 rows)
```

### LINKED ISSUE #2613: Inaccurate timings in EXPLAIN ANALYZE for cold cache queries
EXPLAIN ANALYZE for router queries run against cold cache misleadingly attributes time spent on the query to the coordinator when it was actually spent on workers, leading to confusion in investigations. 

Steps to reproduce: 

1. Apply and populate example schema:
```
drop table if exists t1;
create table t1(col1 int,col2 int,col3 text);
select create_distributed_table('t1','col2');
insert into t1(col1,col2,col3) select generate_series(1,10000000),floor(random()*10)::int,md5(random()::text);
```
2. Reboot cluster to get cold cache results
3. Connect to coordinator and issue router query:
```
explain analyze select count(*) from t1 where col2 = 1;
```
4. Identify worker used in (3) and restart it
5. Connect to same worker and issue query against appropriate local table:
explain analyze select count(*) from t1_102073 where col2 = 1;
6. Compare explain plans. Note similar overall times, but implausible results from coordinator copy

Example worker explain plan:
```
 Finalize Aggregate  (cost=16614.66..16614.67 rows=1 width=8) (actual time=882.279..882.279 rows=1 loops=1)
   ->  Gather  (cost=16614.44..16614.65 rows=2 width=8) (actual time=882.163..884.418 rows=3 loops=1)
         Workers Planned: 2
         Workers Launched: 2
         ->  Partial Aggregate  (cost=15614.44..15614.45 rows=1 width=8) (actual time=874.948..874.948 rows=1 loops=3)
               ->  Parallel Seq Scan on t1_102073  (cost=0.00..14571.54 rows=417163 width=0) (actual time=0.929..857.8
22 rows=333730 loops=3)
                     Filter: (col2 = 1)
 Planning Time: 2.481 ms
 Execution Time: 884.494 ms
(9 rows)

```

Example coordinator explain plan:
```
 Custom Scan (Citus Router)  (cost=0.00..0.00 rows=0 width=0) (actual time=885.738..885.739 rows=1 loops=1)
   Task Count: 1
   Tasks Shown: All
   ->  Task
         Node: host=ec2-34-206-28-19.compute-1.amazonaws.com port=5432 dbname=citus
         ->  Finalize Aggregate  (cost=16614.66..16614.67 rows=1 width=8) (actual time=166.809..166.809 rows=1 loops=1)
               ->  Gather  (cost=16614.44..16614.65 rows=2 width=8) (actual time=164.384..166.853 rows=3 loops=1)
                     Workers Planned: 2
                     Workers Launched: 2
                     ->  Partial Aggregate  (cost=15614.44..15614.45 rows=1 width=8) (actual time=157.810..157.810 rows=1 loops=3)
                           ->  Parallel Seq Scan on t1_102073 t1  (cost=0.00..14571.54 rows=417163 width=0) (actual time=0.007..87.527 rows=333730 loops=3)
                                 Filter: (col2 = 1)
             Planning Time: 0.057 ms
             Execution Time: 166.897 ms
 Planning Time: 0.110 ms
 Execution Time: 885.760 ms
(16 rows)
```

### LINKED ISSUE #3519: Incorrect EXPLAIN plans
We have observed that when you run an explain plan even after setting SET citus.explain_all_tasks = 1; the plan on all the tasks doesn't explain the overall execution time. We have seen this with 3-4 customers now and is becoming painful to debug.

One of the customer also created a coordinator table and re-ran the EXPLAIN (ANALYZE,BUFFERS) and it was all IO bound. So looks like IO metrics aren't being captured well on worker shard executions.

Example:
**Query:**
```
SET citus.explain_all_tasks = 1;
EXPLAIN (analyze, verbose, buffers, costs, timing)
SELECT a.column_id, a.ref_id, SUM(a.v)
  FROM table_anonymous AS a
  WHERE a.column_id = ANY(ARRAY['']::TEXT[])
    AND (fr >= '2019-08-29'::DATE)
  GROUP BY a.column_id, a.ref_id
  ORDER BY SUM(a.v) DESC,  a.ref_id
;
```
**Output:**
```
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Custom Scan (Citus Router)  (cost=0.00..0.00 rows=0 width=0) (actual time=104630.372..104630.385 rows=220 loops=1)
   Output: remote_scan.column_id, remote_scan.ref_id, remote_scan.sum
   Task Count: 1
   Tasks Shown: All
   ->  Task
         Node: host=10.0.0.80 port=5432 dbname=citus
         ->  Sort  (cost=36058.46..36058.58 rows=47 width=101) (actual time=112.621..112.648 rows=220 loops=1)
               Output: column_id, ref_id, (sum(v))
               Sort Key: (sum(a.v)) DESC, a.ref_id
               Sort Method: quicksort  Memory: 67kB
               Buffers: shared hit=57590
               ->  GroupAggregate  (cost=36056.10..36057.15 rows=47 width=101) (actual time=111.922..112.141 rows=220 loops=1)
                     Output: column_id, ref_id, sum(v)
                     Group Key: a.column_id, a.ref_id
                     Buffers: shared hit=57590
                     ->  Sort  (cost=36056.10..36056.21 rows=47 width=77) (actual time=111.908..111.945 rows=735 loops=1)
                           Output: column_id, ref_id, v
                           Sort Key: a.column_id, a.ref_id
                           Sort Method: quicksort  Memory: 114kB
                           Buffers: shared hit=57590
                           ->  Index Scan using table_anonymous_fr_column_id_hashed_ref_id_idx_102474 on public.table_anonymous_102474 a  (cost=0.56..36054.79 rows=47 width=77) (actual time=0.025..110.669 rows=735 loops=1)
                                 Output: column_id, ref_id, v
                                 Index Cond: ((a.fr >= 'xxxxxxxx'::date) AND (a.column_id = ANY ('{xxxxx}'::text[])))
                                 Buffers: shared hit=57590
             Planning Time: 0.202 ms
             Execution Time: 112.696 ms
   Buffers: shared hit=60
Planning Time: 4.867 ms
Execution Time: 104630.460 ms
(29 rows)
```

### PR DESCRIPTION
**Pull request by pykello**
DESCRIPTION: Fix several EXPLAIN ANALYZE issues.

We wrap worker tasks in `worker_save_query_explain_analyze()` so we can fetch their explain output later by a call to `worker_last_saved_explain_analyze()`.

Note that this doesn't change the behaviour for `EXPLAIN ANALYZE EXECUTE`, and it uses the old method. Main obstacle is that PQsendQueryParams doesn't accept multiple statements, which can be worked around in a future PR.

Fixes #3519
Fixes #2347
Fixes #2613
Fixes #621

Also see the discussion in https://github.com/citusdata/citus/pull/3833

### CODE REVIEW

File: src/include/distributed/multi_physical_planner.h [hunk 1]
```diff
@@ -337,6 +337,13 @@ typedef struct Task
 	 * NULL, in which case executor might use a default destination.
 	 */
 	struct TupleDestination *tupleDest;
+
+	/*
+	 * EXPLAIN ANALYZE output fetched from worker. This is saved to be used later
+	 * by RemoteExplain().
+	 */
+	StringInfo fetchedExplainAnalyzePlan;
+	int fetchExplainAnalyzePlacementIndex;
```
Comment (marcocitus) [inline src/include/distributed/multi_physical_planner.h:346]: You've not added these to citus_copyfuncs.c et al., is that intentional?

File: src/include/distributed/multi_physical_planner.h [hunk 2]
```diff
@@ -337,6 +337,13 @@ typedef struct Task
 	 * NULL, in which case executor might use a default destination.
 	 */
 	struct TupleDestination *tupleDest;
+
+	/*
+	 * EXPLAIN ANALYZE output fetched from worker. This is saved to be used later
+	 * by RemoteExplain().
+	 */
+	StringInfo fetchedExplainAnalyzePlan;
```
Comment (marcocitus) [inline src/include/distributed/multi_physical_planner.h:345]: I'm wondering whether there is a way to avoid putting execution information in the Task, which is meant to represent a part of a plan. I'm guessing there isn't, since we need to pass the information via the explain hooks.

Comment (marcocitus) [reply src/include/distributed/multi_physical_planner.h:345]: I suppose we could interpret remote explain plans as being part of the distributed plan (has valuable cost information).

File: src/backend/distributed/executor/adaptive_executor.c [hunk 3]
```diff
@@ -3155,13 +3155,25 @@ TransactionStateMachine(WorkerSession *session)
...
 					placementExecution->shardCommandExecution;
-				bool storeRows = shardCommandExecution->expectResults;
+				Task *task = shardCommandExecution->task;
+
+				/*
+				 * In EXPLAIN ANALYZE we need to store results except for multiple placements,
+				 * regardless of query type. In other cases, doing the same doesn't seem to have
+				 * a drawback.
+				 */
+				bool storeRows = true;
```
Comment (marcocitus) [inline src/backend/distributed/executor/adaptive_executor.c:3165]: do we still need the expectResults flag in that case?

**Comment by marcocitus** [comment]
Seems ready to :ship: after small comments.

File: src/backend/distributed/planner/multi_explain.c [hunk 4]
```diff
@@ -421,6 +462,32 @@ RemoteExplain(Task *task, ExplainState *es)
...
+														'\n');
+		}
+		else
+		{
+			remotePlan->explainOutputList = list_make1(task->fetchedExplainAnalyzePlan);
+		}
+
+		remotePlan->placementIndex = task->fetchExplainAnalyzePlacementIndex;
+
+		return remotePlan;
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_explain.c:488]: pretty minor, but when a function has two wholly different implementations I find it nicer if it's structured as :
```c
if (useImplementation1)
{
    return Implementation1();
}
else
{
    return Implementation2();
}
```

File: src/backend/distributed/planner/multi_explain.c [hunk 5]
```diff
@@ -875,6 +976,289 @@ ExtractFieldJsonbDatum(Datum jsonbDoc, const char *fieldName, Datum *result)
...
+					 CurrentDistributedQueryExplainOptions.verbose ? "true" : "false",
+					 CurrentDistributedQueryExplainOptions.costs ? "true" : "false",
+					 CurrentDistributedQueryExplainOptions.buffers ? "true" : "false",
+					 CurrentDistributedQueryExplainOptions.timing ? "true" : "false",
+					 CurrentDistributedQueryExplainOptions.summary ? "true" : "false",
+					 ExplainFormatStr(CurrentDistributedQueryExplainOptions.format));
+
+	StringInfo wrappedQuery = makeStringInfo();
+	appendStringInfo(wrappedQuery,
+					 "SELECT * FROM worker_save_query_explain_analyze(%s, %s) AS (%s)",
```
Comment (marcocitus) [inline src/backend/distributed/planner/multi_explain.c:1213]: It's useful useful to explicitly list the columns in the target list in internal queries, because it allows us to add more output columns to the function in a rolling upgrade without breaking things on the coordinator.

File: src/test/regress/expected/local_shard_execution.out [hunk 6]
```diff
@@ -327,10 +327,11 @@ EXPLAIN (ANALYZE, COSTS OFF, SUMMARY OFF, TIMING OFF) DELETE FROM distributed_ta
    ->  Task
          Node: host=localhost port=xxxxx dbname=regression
          ->  Delete on distributed_table_1470001 distributed_table (actual rows=0 loops=1)
-               ->  Index Scan using distributed_table_pkey_1470001 on distributed_table_1470001 distributed_table (actual rows=0 loops=1)
+               ->  Index Scan using distributed_table_pkey_1470001 on distributed_table_1470001 distributed_table (actual rows=1 loops=1)
                      Index Cond: (key = 1)
                      Filter: (age = 20)
-(9 rows)
+             Trigger for constraint second_distributed_table_key_fkey_1470005: calls=1
```
Comment (marcocitus) [inline src/test/regress/expected/local_shard_execution.out:333]: That's a pretty interesting side effect.

**Comment by adarshprakash** [comment]
Hi @pykello , I have 2 small doubts here. 

1. Why we need to execute udf functions to fetch the explain analyze results from workers? Do we fetch more details than normal EXPLAIN ANALYZE command in workers?
2. Why do we need to execute 2 udf functions (worker_save_query_explain_analyze & worker_last_saved_explain_analyze)? Can the first function itself return the explain analyze results?

**Comment by pykello** [comment]
Hi @adarshprakash ,

Distributed EXPLAIN ANALYZE has 2 components:
1. Coordinator EXPLAIN ANALYZE: for this we need query results from workers
2. Worker EXPLAIN ANALYZE

So we need both worker results & worker EXPLAIN ANALYZE. If we do this by first sending worker queries & fetching results to construct coordinator EXPLAIN ANALYZE, and then send EXPLAIN ANALYZE to workers (or the reverse order), then worker queries will be executed twice, because EXPLAIN ANALYZE itself executes the query.

This brings couple of problems:
1. Execution stats of 2 executions can be different, because of cache state difference, difference in amount of concurrent queries running in cluster, ... Then the numbers in coordinator EXPLAIN ANALYZE won't be consistent with numbers in worker node stats, e.g. it might read the worker nodes finished in few milliseconds (because of caching, or low load), but coordinator query started after 1 second.
2. This won't work for EXPLAIN ANALYZE of DDL, because it will have side effects.

So this PR makes the worker queries execute only once. First it returns the actual query results, but saves the worker EXPLAIN ANALYZE somewhere so it can be fetched without a 2nd execution by calling worker_last_saved_explain_analyze.

The answer to your second question is also in the previous paragraph. First udf returns the query results, second one returns the EXPLAIN ANALYZE result. Doing it in one call to return both results might be possible, but might be more complicated, because of more result parsing, etc.

p.s. I don't work at Citus or Microsoft anymore.

**Comment by adarshprakash** [comment]
Hi @pykello , Thank you so much for your time and the detailed explanation. I understood the dual execution problem. So my doubt was why we could not directly execute the EXPLAIN ANALYZE in the worker node and return the results back to the user. 

But as you pointed out, if we do this way, we will get only the results of EXPLAIN ANALYZE command from the worker. We will not get back the actual result data from the coordinator. So we split it into two parts. In the first function worker_save_query_explain_analyze(), we will write the results to the tuplestore. And in the second function worker_last_saved_explain_analyze(), we will return the EXPLAIN ANALYZE result. 

Is my understanding correct here?

**Comment by pykello** [comment]
Yes, that's right.
