### PR TITLE
Parition shards to be colocated with parent shards

### LINKED ISSUE #5121: Colocate with none on partitioned tables behave unexpectedly
```SQL
CREATE TABLE sensors(
measureid         integer,
eventdatetime     date,
measure_data      jsonb,
PRIMARY KEY (measureid, eventdatetime, measure_data))
PARTITION BY RANGE(eventdatetime);

CREATE TABLE sensors_old PARTITION OF sensors FOR VALUES FROM ('2000-01-01') TO ('2020-01-01');
CREATE TABLE sensors_2020_01_01 PARTITION OF sensors FOR VALUES FROM ('2020-01-01') TO ('2020-02-01');

SELECT create_distributed_table('sensors', 'measureid', colocate_with:='none');

SELECT logicalrelid, colocationid FROM pg_dist_partition WHERE logicalrelid IN ('sensors'::regclass, 'sensors_old'::regclass, 'sensors_2020_01_01'::regclass);
    logicalrelid    | colocationid 
--------------------+--------------
 sensors            |            4
 sensors_old        |            5
 sensors_2020_01_01 |            6
(3 rows)

Time: 5.334 ms
```

### PR DESCRIPTION
**Pull request by tejeswarm**
DESCRIPTION: Partition shards to be co-located with the parent shards.

Fixes #5121

### CODE REVIEW

File: src/backend/distributed/commands/create_distributed_table.c [hunk 1]
```diff
@@ -556,11 +556,15 @@ CreateDistributedTable(Oid relationId, Var *distributionColumn, char distributio
 	{
 		List *partitionList = PartitionList(relationId);
 		Oid partitionRelationId = InvalidOid;
+		char *parentRelationName, *nspname;
+		nspname = get_namespace_name(get_rel_namespace(relationId));
+		parentRelationName = quote_qualified_identifier(nspname, get_rel_name(
```
Comment (tejeswarm) [inline src/backend/distributed/commands/create_distributed_table.c:561]: We have to bend over backwards to make the name fully qualified, if not for SQL
SELECT create_distributed_table('ppp', 'measureid', colocate_with:='soo.moo');
'moo' may be mapped falsely to another table in the current search_path

File: src/backend/distributed/commands/create_distributed_table.c [hunk 2]
```diff
@@ -556,11 +556,15 @@ CreateDistributedTable(Oid relationId, Var *distributionColumn, char distributio
 	{
 		List *partitionList = PartitionList(relationId);
 		Oid partitionRelationId = InvalidOid;
+		char *parentRelationName, *nspname;
+		nspname = get_namespace_name(get_rel_namespace(relationId));
```
Comment (tejeswarm) [inline src/backend/distributed/commands/create_distributed_table.c:560]: We have to bend over backwards to make the name fully qualified, if not for SQL
SELECT create_distributed_table('ppp', 'measureid', colocate_with:='soo.moo');
'moo' may be mapped falsely to another table in the current search_path

File: src/backend/distributed/commands/create_distributed_table.c [hunk 3]
```diff
@@ -556,11 +556,15 @@ CreateDistributedTable(Oid relationId, Var *distributionColumn, char distributio
 	{
 		List *partitionList = PartitionList(relationId);
 		Oid partitionRelationId = InvalidOid;
+		char *parentRelationName, *nspname;
```
Comment (marcocitus) [inline src/backend/distributed/commands/create_distributed_table.c:559]: Our usual style (which is slightly different from PG) is to have declaration and assignment be the same line, and to avoid acronyms.

e.g.
```c
char *schemaName = get_namespace_name(get_rel_namespace(relationId));
char *parentRelationName = ...;
```

We also tend to avoid nested calls to explicitly name the arguments, so the usual pattern is:
```c
Oid namespaceId = get_rel_namespace(relationId);
char *schemaName = get_namespace_name(namespaceId);
```

File: src/backend/columnar/columnar_reader.c [hunk 4]
```diff
@@ -756,7 +756,9 @@ SnapshotMightSeeUnflushedStripes(Snapshot snapshot)
 		}
 
 		default:
+		{
 			return false;
+		}
```
Comment (marcocitus) [inline src/backend/columnar/columnar_reader.c:761]: You might have a slightly different version of uncrustify. 

If it passes check-style on GitHub, it seems fine to make this change. It would be preferable to do it as a separate commit to not obscure the history.

File: src/test/regress/expected/multi_partitioning.out [hunk 5]
```diff
@@ -1028,6 +1028,29 @@ CREATE TABLE partitioned_users_table_2009 PARTITION OF partitioned_users_table F
...
+CREATE TABLE sensors_old PARTITION OF sensors FOR VALUES FROM ('2000-01-01') TO ('2020-01-01');
+CREATE TABLE sensors_2020_01_01 PARTITION OF sensors FOR VALUES FROM ('2020-01-01') TO ('2020-02-01');
+CREATE TABLE sensors_new PARTITION OF sensors DEFAULT;
+SELECT create_distributed_table('sensors', 'measureid', colocate_with:='none');
+ create_distributed_table
+---------------------------------------------------------------------
+
+(1 row)
+
+SELECT logicalrelid, colocationid FROM pg_dist_partition
```
Comment (onderkalaci) [inline src/test/regress/expected/multi_partitioning.out:1043]: Minor: maybe do not print the `colocationId` as that might change if other tests change the colocationId.
```SQL
SELECT 
    count(DISTINCT colocationid)
FROM 
    pg_dist_partition
WHERE logicalrelid IN ('sensors'::regclass, 
                                        'sensors_old'::regclass, 
                                        'sensors_2020_01_01'::regclass, 
'sensors_new'::regclass);
```

File: src/backend/columnar/columnar_reader.c (hunk 4 above)
Comment (tejeswarm) [reply src/backend/columnar/columnar_reader.c:761]: Agreed, reinstalled an older version to match with what everyone is using, shortly will upload the changes.

File: src/backend/distributed/commands/create_distributed_table.c (hunk 3 above)
Comment (tejeswarm) [reply src/backend/distributed/commands/create_distributed_table.c:559]: Changed to the new format.

File: src/backend/distributed/commands/create_distributed_table.c [hunk 6]
```diff
@@ -556,11 +556,15 @@ CreateDistributedTable(Oid relationId, Var *distributionColumn, char distributio
 	{
 		List *partitionList = PartitionList(relationId);
 		Oid partitionRelationId = InvalidOid;
+		Oid namespaceId = get_rel_namespace(relationId);
+		char *schemaName = get_namespace_name(namespaceId);
+		char *relationName = get_rel_name(relationId);
+		char *parentRelationName = quote_qualified_identifier(schemaName, relationName);
 		foreach_oid(partitionRelationId, partitionList)
```
Comment (marcocitus) [inline src/backend/distributed/commands/create_distributed_table.c:563]: wouldn't mind an empty line here

File: src/backend/distributed/commands/create_distributed_table.c [hunk 7]
```diff
@@ -556,11 +556,15 @@ CreateDistributedTable(Oid relationId, Var *distributionColumn, char distributio
...
 		{
 			CreateDistributedTable(partitionRelationId, distributionColumn,
 								   distributionMethod, shardCount, false,
-								   colocateWithTableName, viaDeprecatedAPI);
```
Comment (marcocitus) [inline src/backend/distributed/commands/create_distributed_table.c:563]: What happens if the parent relation name is "none"?

**Review by marcocitus — APPROVED** [review]

**Comment by marcocitus** [comment]
We could maybe backport this to 10.2. @onderkalaci what do you think?

**Comment by onderkalaci** [comment]
> We could maybe backport this to 10.2. @onderkalaci what do you think?

Yes, would be good to backport

> Partition shards to be co-located with parent shards

@tejeswarm, some minor notes. We add `DESCRIPTION` tag if we want to have this PR to show up in the release notes, which I think we want for this PR?

Also, if you add `Fixes ###`, the relevant issue is automatically closed. An example PR description can be found here: https://github.com/citusdata/citus/pull/5254#issue-990362855

File: src/backend/distributed/commands/create_distributed_table.c (hunk 6 above)
Comment (tejeswarm) [reply src/backend/distributed/commands/create_distributed_table.c:563]: I felt so, but I wasn't sure about it and kept the way it is. Will add.

File: src/backend/distributed/commands/create_distributed_table.c (hunk 7 above)
Comment (tejeswarm) [reply src/backend/distributed/commands/create_distributed_table.c:563]: Hmm, I thought these are keywords when I was reading the code
    if (pg_strncasecmp(colocateWithTableName, "**default**", NAMEDATALEN) != 0)

    pg_strncasecmp(colocateWithTableName, "**none**", NAMEDATALEN) == 0;

Comment (tejeswarm) [reply src/backend/distributed/commands/create_distributed_table.c:563]: I got it now, you meant for the parent relation :)

Comment (tejeswarm) [reply src/backend/distributed/commands/create_distributed_table.c:563]: Parent name can be either 'none' or 'schema.none', in both the cases we resolve it 'schema.none', using the parent Oid, which shouldn't match.

pg_strncasecmp(colocateWithTableName, "default", NAMEDATALEN) != 0)
pg_strncasecmp(colocateWithTableName, "none", NAMEDATALEN) == 0
