### PR TITLE
PG18: fix regress test failures in subquery_in_targetlist.

### LINKED ISSUE #8296: PG18 - test failures in subquery_in_targetlist
Failing to identify that a correlated subquery cannot be planned when the parent query FROM clause has a reference table:
```
SELECT (SELECT max(u1.time) FROM users_table u1 JOIN users_reference_table u2 USING (user_id) WHERE u2.user_id = e.user_id GROUP BY use
r_id), 5
FROM events_reference_table e
GROUP BY 1
ORDER BY 1,2 LIMIT 1;
< ERROR:  correlated subqueries are not supported when the FROM clause contains a reference table
---
>               max               | ?column?
> ---------------------------------------------------------------------
>  Thu Nov 23 13:52:54.83829 2017 |        5
> (1 row)
> 

WITH cte_1 AS (SELECT min(user_id) u, max(time) m FROM users_table)
SELECT count(*), (SELECT max(time) FROM users_table WHERE user_id = cte_1.u GROUP BY user_id)
FROM cte_1
GROUP BY 2
ORDER BY 1,2 LIMIT 1;
< ERROR:  correlated subqueries are not supported when the FROM clause contains a CTE or subquery
---
>  count |               max
> ---------------------------------------------------------------------
>      1 | Thu Nov 23 17:30:34.635085 2017
> (1 row)
>
```

Failing to identify equivalence between the subquery and parent query on the distribution column:
```
 SELECT sum(e.user_id) + (SELECT max(value_3) FROM users_table WHERE user_id = e.user_id GROUP BY user_id)
FROM events_table e
GROUP BY e.user_id
ORDER BY 1 LIMIT 3;
188,194c196
<  ?column?
< ---------------------------------------------------------------------
<        19
<        53
<        65
< (3 rows)
< 
---
> ERROR:  complex joins are only supported when all distributed tables are co-located and joined on their distribution columns
```

### PR DESCRIPTION
**Pull request by colm-mchugh**
The failing queries all have a GROUP BY, and the fix teaches the planner to correctly handle PG18's GROUP range table entry:
- In recursive query planning, don't recurse into subquery expressions in a GROUP BY clause
- Flatten references to a GROUP rte before creating the worker subquery in pushdown planning
- If a PARAM node points to a GROUP rte then tunnel through to the underlying expression

Fixes #8296

### CODE REVIEW

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 1]
```diff
@@ -971,6 +971,36 @@ GetVarFromAssignedParam(List *outerPlanParamsList, Param *plannerParam,
...
+	 */
+	if (assignedVar != NULL)
+	{
+		Query *parse = (*rootContainingVar)->parse;
+		if (parse->hasGroupRTE)
+		{
+			RangeTblEntry *rte = rt_fetch(assignedVar->varno, parse->rtable);
+			if (rte->rtekind == RTE_GROUP)
+			{
+				Node *groupVar = list_nth(rte->groupexprs, assignedVar->varattno - 1);
```
Comment (m3hm3t) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:991]: maybe add bound check
```suggestion
                if (assignedVar->varattno <= 0 ||
                    assignedVar->varattno > list_length(rte->groupexprs))
                    return NULL;  /* corrupt or unexpected */
				Node *groupVar = list_nth(rte->groupexprs, assignedVar->varattno - 1);
```

File: src/backend/distributed/planner/relation_restriction_equivalence.c [hunk 2]
```diff
@@ -971,6 +971,36 @@ GetVarFromAssignedParam(List *outerPlanParamsList, Param *plannerParam,
...
+				if (IsA(groupVar, Var))
+				{
+					assignedVar = (Var *) groupVar;
+				}
+				else
+				{
+					/* todo: handle PlaceHolderVar case if needed */
+					assignedVar = NULL;
```
Comment (m3hm3t) [inline src/backend/distributed/planner/relation_restriction_equivalence.c:1001]:
```suggestion
                    ereport(DEBUG2, (errmsg("GroupVar maps to non-Var group expr; bailing out")));
					assignedVar = NULL;
```

**Review by m3hm3t — APPROVED** [review]
LGTM, nits

File: src/backend/distributed/planner/relation_restriction_equivalence.c (hunk 1 above)
Comment (colm-mchugh) [reply src/backend/distributed/planner/relation_restriction_equivalence.c:991]: Thx, added an Assert. If pg18 planner is doing its job it should not be tripped.
