### PR TITLE
Make sure that local execution starts coordinated transaction

### LINKED ISSUE #4829: CoordinatedTransactionShouldUse2PC assert failure in regression tests
`single_node.sql`:
```c
#0  0x00007f3bc9bb2428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f3bc9bb402a in __GI_abort () at abort.c:89
#2  0x0000000000b0513e in ExceptionalCondition (conditionName=0x7f3bc74afafd "InCoordinatedTransaction()", errorType=0x7f3bc74afa63 "FailedAssertion",
    fileName=0x7f3bc74afad8 "transaction/transaction_management.c", lineNumber=202) at assert.c:67
#3  0x00007f3bc745589d in CoordinatedTransactionShouldUse2PC () at transaction/transaction_management.c:202
#4  0x00007f3bc73d61de in ExecuteLocalTaskListExtended (taskList=0x2eeb4e8, orig_paramListInfo=0x0, distributedPlan=0x0, defaultTupleDest=0x2eeb560,
    isUtilityCommand=true) at executor/local_executor.c:247
#5  0x00007f3bc73d60d4 in ExecuteLocalUtilityTaskList (utilityTaskList=0x2eeb4e8) at executor/local_executor.c:185
#6  0x00007f3bc73ca380 in ExecuteTaskListExtended (executionParams=0x2eeb368) at executor/adaptive_executor.c:1001
#7  0x00007f3bc73ca181 in ExecuteUtilityTaskListExtended (utilityTaskList=0x2eeb310, poolSize=1, localExecutionSupported=true)
    at executor/adaptive_executor.c:903
#8  0x00007f3bc73fcf8f in CreateShardsOnWorkers (distributedRelationId=21927, shardPlacements=0x2ee86e0, useExclusiveConnection=false, colocatedShard=false)
    at operations/stage_protocol.c:616
#9  0x00007f3bc73f10b4 in CreateReferenceTableShard (distributedTableId=21927) at operations/create_shards.c:384
#10 0x00007f3bc738107c in CreateDistributedTable (relationId=21927, distributionColumn=0x0, distributionMethod=110 'n', shardCount=4,
    colocateWithTableName=0x0, viaDeprecatedAPI=false) at commands/create_distributed_table.c:469
#11 0x00007f3bc7380dd4 in create_reference_table (fcinfo=0x2e72a38) at commands/create_distributed_table.c:288
#12 0x0000000000727009 in ExecInterpExpr (state=0x2e72950, econtext=0x2e72650, isnull=0x7ffd88e8653f) at execExprInterp.c:699
#13 0x00000000007290fe in ExecInterpExprStillValid (state=0x2e72950, econtext=0x2e72650, isNull=0x7ffd88e8653f) at execExprInterp.c:1802
#14 0x000000000077abbe in ExecEvalExprSwitchContext (state=0x2e72950, econtext=0x2e72650, isNull=0x7ffd88e8653f)
    at ../../../src/include/executor/executor.h:316
#15 0x000000000077ac36 in ExecProject (projInfo=0x2e72948) at ../../../src/include/executor/executor.h:350
#16 0x000000000077ae5c in ExecResult (pstate=0x2e72538) at nodeResult.c:136
#17 0x000000000073e48a in ExecProcNodeFirst (node=0x2e72538) at execProcnode.c:450
#18 0x00000000007324ff in ExecProcNode (node=0x2e72538) at ../../../src/include/executor/executor.h:248
#19 0x0000000000734fc8 in ExecutePlan (estate=0x2e72300, planstate=0x2e72538, use_parallel_mode=false, operation=CMD_SELECT, sendTuples=true,
    numberTuples=0, direction=ForwardScanDirection, dest=0x2eb1548, execute_once=true) at execMain.c:1646
#20 0x0000000000732b4e in standard_ExecutorRun (queryDesc=0x2eb5de0, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:364
#21 0x00007f3bc73d8033 in CitusExecutorRun (queryDesc=0x2eb5de0, direction=ForwardScanDirection, count=0, execute_once=true)
    at executor/multi_executor.c:217
#22 0x00007f3bc1b97fe0 in pgss_ExecutorRun (queryDesc=0x2eb5de0, direction=ForwardScanDirection, count=0, execute_once=true) at pg_stat_statements.c:1043
#23 0x0000000000732963 in ExecutorRun (queryDesc=0x2eb5de0, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:306
#24 0x0000000000970ce4 in PortalRunSelect (portal=0x2dce4b0, forward=true, count=0, dest=0x2eb1548) at pquery.c:912
#25 0x000000000097092f in PortalRun (portal=0x2dce4b0, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x2eb1548, altdest=0x2eb1548,
    qc=0x7ffd88e86bc0) at pquery.c:756
#26 0x000000000096a60c in exec_simple_query (query_string=0x2ced7b0 "SELECT create_reference_table('ref');") at postgres.c:1239
#27 0x000000000096e96d in PostgresMain (argc=1, argv=0x2d84ba8, dbname=0x2d84950 "regression", username=0x2d84928 "postgres") at postgres.c:4315
#28 0x00000000008b5ca3 in BackendRun (port=0x2d7fae0) at postmaster.c:4536
#29 0x00000000008b541c in BackendStartup (port=0x2d7fae0) at postmaster.c:4220
#30 0x00000000008b1851 in ServerLoop () at postmaster.c:1739
#31 0x00000000008b1080 in PostmasterMain (argc=5, argv=0x2ce8190) at postmaster.c:1412
#32 0x00000000007b0914 in main (argc=5, argv=0x2ce8190) at main.c:210
```

`ref_citus_local_fkeys.sql`:
```c
#0  0x00007f3bc9bb2428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f3bc9bb402a in __GI_abort () at abort.c:89
#2  0x0000000000b0513e in ExceptionalCondition (conditionName=0x7f3bc74afafd "InCoordinatedTransaction()", errorType=0x7f3bc74afa63 "FailedAssertion",
    fileName=0x7f3bc74afad8 "transaction/transaction_management.c", lineNumber=202) at assert.c:67
#3  0x00007f3bc745589d in CoordinatedTransactionShouldUse2PC () at transaction/transaction_management.c:202
#4  0x00007f3bc73d61de in ExecuteLocalTaskListExtended (taskList=0x2e998a8, orig_paramListInfo=0x0, distributedPlan=0x2edd560, defaultTupleDest=0x2e99648,
    isUtilityCommand=false) at executor/local_executor.c:247
#5  0x00007f3bc73ca078 in RunLocalExecution (scanState=0x2e8d030, execution=0x2e996a0) at executor/adaptive_executor.c:855
#6  0x00007f3bc73c9f6e in AdaptiveExecutor (scanState=0x2e8d030) at executor/adaptive_executor.c:808
#7  0x00007f3bc73cf85d in CitusExecScan (node=0x2e8d030) at executor/citus_custom_scan.c:224
#8  0x000000000075ac49 in ExecCustomScan (pstate=0x2e8d030) at nodeCustom.c:115
#9  0x000000000073e48a in ExecProcNodeFirst (node=0x2e8d030) at execProcnode.c:450
#10 0x00000000007324ff in ExecProcNode (node=0x2e8d030) at ../../../src/include/executor/executor.h:248
#11 0x0000000000734fc8 in ExecutePlan (estate=0x2e8cdf0, planstate=0x2e8d030, use_parallel_mode=false, operation=CMD_INSERT, sendTuples=false,
    numberTuples=0, direction=ForwardScanDirection, dest=0x2e6c3e0, execute_once=true) at execMain.c:1646
#12 0x0000000000732b4e in standard_ExecutorRun (queryDesc=0x2e570f0, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:364
#13 0x00007f3bc73d8033 in CitusExecutorRun (queryDesc=0x2e570f0, direction=ForwardScanDirection, count=0, execute_once=true)
    at executor/multi_executor.c:217
#14 0x00007f3bc1b97fe0 in pgss_ExecutorRun (queryDesc=0x2e570f0, direction=ForwardScanDirection, count=0, execute_once=true) at pg_stat_statements.c:1043
#15 0x0000000000732963 in ExecutorRun (queryDesc=0x2e570f0, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:306
#16 0x000000000096fa35 in ProcessQuery (plan=0x2e94d60, sourceText=0x2ced7b0 "INSERT INTO citus_local_table VALUES (11);", params=0x0, queryEnv=0x0,
    dest=0x2e6c3e0, qc=0x7ffd88e86bc0) at pquery.c:160
#17 0x00000000009714b1 in PortalRunMulti (portal=0x2dcdfd0, isTopLevel=true, setHoldSnapshot=false, dest=0x2e6c3e0, altdest=0x2e6c3e0, qc=0x7ffd88e86bc0)
    at pquery.c:1265
#18 0x00000000009709dd in PortalRun (portal=0x2dcdfd0, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x2e6c3e0, altdest=0x2e6c3e0,
    qc=0x7ffd88e86bc0) at pquery.c:779
#19 0x000000000096a60c in exec_simple_query (query_string=0x2ced7b0 "INSERT INTO citus_local_table VALUES (11);") at postgres.c:1239
#20 0x000000000096e96d in PostgresMain (argc=1, argv=0x2d84ba8, dbname=0x2d84950 "regression", username=0x2d84928 "postgres") at postgres.c:4315
#21 0x00000000008b5ca3 in BackendRun (port=0x2d7fae0) at postmaster.c:4536
#22 0x00000000008b541c in BackendStartup (port=0x2d7fae0) at postmaster.c:4220
#23 0x00000000008b1851 in ServerLoop () at postmaster.c:1739
#24 0x00000000008b1080 in PostmasterMain (argc=5, argv=0x2ce8190) at postmaster.c:1412
#25 0x00000000007b0914 in main (argc=5, argv=0x2ce8190) at main.c:210
```

### PR DESCRIPTION
**Pull request by onderkalaci**
With https://github.com/citusdata/citus/pull/4806 we enabled
2PC for any non-read-only local task. However, if the execution
is a single task, enabling 2PC (CoordinatedTransactionShouldUse2PC)
hits an assertion as we are not in a coordinated transaction.

There is no downside of using a coordinated transaction for single
task local queries.

Fixes #4829

DESCRIPTION: Makes sure that local execution starts coordinated transaction

### CODE REVIEW

File: src/backend/distributed/executor/local_executor.c [hunk 1]
```diff
@@ -239,6 +239,16 @@ ExecuteLocalTaskListExtended(List *taskList,
...
+			/*
+			 * We might be executing a single local task, so make sure that
+			 * we are already in a coordinated transaction so that the below
+			 * CoordinatedTransactionShouldUse2PC() wouldn't complain.
+			 *
+			 * In case this task is a part of multi-task command, we would have
+			 * already started the coordinated transaction.
+			 */
+			UseCoordinatedTransaction();
+
```
Comment (onurctirtir) [inline src/backend/distributed/executor/local_executor.c:251]: >However, if the execution is a single task, ..

I'm a little bit confused how does that "if" implies single task

**Comment by onurctirtir** [comment]
Fixes #4829

**Review by marcocitus — APPROVED** [review]

**Review by onurctirtir — APPROVED** [review]
