### PR TITLE
Fix CTE traversal for outer Vars in FindReferencedTableColumn (remove assert; correct parentQueryList handling)

### LINKED ISSUE #8105: Assert(skipOuterVars) crash after lifting volatile target-list items in WrapSubquery
Steps to reproduce:

```
CREATE TABLE nullkey_c1_t1(a int, b int);
CREATE TABLE nullkey_c1_t2(a int, b int);
SELECT create_distributed_table('nullkey_c1_t1', null, colocate_with=>'none');
SELECT create_distributed_table('nullkey_c1_t2', null, colocate_with=>'nullkey_c1_t1');

CREATE TABLE reference_table(a int, b int);
SELECT create_reference_table('reference_table');

CREATE TABLE distributed_table_c1_t1(a int, b int);
SELECT create_distributed_table('distributed_table_c1_t1', 'a');

WITH cte_1 AS (
  SELECT nullkey_c1_t1.a, reference_table.b FROM nullkey_c1_t1 JOIN reference_table USING (a)
),
cte_2 AS (
  SELECT * FROM nullkey_c1_t2 WHERE EXISTS (
    SELECT 1 FROM reference_table WHERE reference_table.a = nullkey_c1_t2.a
  )
  ORDER BY 1,2 OFFSET 1 LIMIT 4
)
INSERT INTO distributed_table_c1_t1
SELECT * FROM cte_1 UNION SELECT * FROM cte_2 EXCEPT SELECT * FROM reference_table;
```

Caused by https://github.com/citusdata/citus/commit/a4040ba5da2203f976bd2f4f54ffc56cf0fa2ce8

Crash in `insert_select_single_shard_table` in local tests, `multi-1`

Possible reason: we have a subquery inside a CTE

Suggestion: the initialization of  `bool skipOuterVars = false;` in `InsertPartitionColumnMatchesSelect` needs to be more context sensitive.

### PR DESCRIPTION
**Pull request by m3hm3t**
fixes #8105 

This change lets `FindReferencedTableColumn()` correctly resolve columns through a CTE even when the expression comes from an outer query level (`varlevelsup > 0`, `skipOuterVars = false`). Before, we hit an `Assert(skipOuterVars)` in this path.

**Problem**

* Hitting a CTE after walking outer Vars triggered `Assert(skipOuterVars)`.
* Cause: we modified `parentQueryList` in place and didn’t rebuild the correct parent chain before recursing into the CTE, so the path was considered unsafe.

**Fix**

* Remove the `Assert(skipOuterVars)` in the `RTE_CTE` branch.
* Find the CTE’s owning level via `ctelevelsup` and compute `cteParentListIndex`.
* Rebuild a private parent list for recursion: `list_copy` → `list_truncate` → `lappend(current query)`.
* Add a bounds check before indexing the CTE’s `targetList`.

**Why it works**

```diff
-parentQueryList = lappend(parentQueryList, query);
-FindReferencedTableColumn(targetEntry->expr, parentQueryList,
-                          cteQuery, column, rteContainingReferencedColumn,
-                          skipOuterVars);
+    /* hand a private, bounded parent list to the recursion */
+    List *newParent = list_copy(parentQueryList);
+    newParent = list_truncate(newParent, cteParentListIndex + 1);
+    newParent = lappend(newParent, query);
+
+    FindReferencedTableColumn(targetEntry->expr,
+                              newParent,
+                              cteQuery,
+                              column,
+                              rteContainingReferencedColumn,
+                              skipOuterVars);
+}


```
**Before:** We changed `parentQueryList` in place (`parentQueryList = lappend(...)`) and didn’t trim it to the CTE’s owner level.

**After:** We copy the list, trim it to the CTE’s owner level, then append the current query. This keeps the parent list accurate for the current recursion and safe when following outer Vars.

**Example: Nested subquery referencing the CTE (two levels down)**

```
WITH c AS MATERIALIZED (SELECT user_id FROM raw_events_first)
SELECT 1
FROM raw_events_first t
WHERE EXISTS (
  SELECT 1
  FROM (SELECT user_id FROM c) c2
  WHERE c2.user_id = t.user_id
);
```

Levels:
Q0 = top SELECT
Q1 = EXISTS subquery
Q2 = inner (SELECT user_id FROM c)

When resolving c2.user_id inside Q2:

- parentQueryList is [Q0, Q1, Q2].
- `ctelevelsup`: 2

`cteParentListIndex = length(parentQueryList) - ctelevelsup - 1`

- Recurse into the CTE’s query with [Q0, Q2].

**Tests (added in `multi_insert_select`)**

* **T1:** Correlated subquery that references a CTE (one level down) 
Verifies that resolving through `RTE_CTE` after following an outer `Var` succeeds, row count matches source table.
* **T2:** Nested subquery that references a CTE (two levels down) 
Exercises deeper recursion and confirms identical to T1.
* **T3:** Scalar subquery in a target list that reads from the outer CTE
Checks expected row count and that no NULLs are inserted.

These tests cover the cases that previously hit `Assert(skipOuterVars)` and confirm CTE references while following outer Vars.

### CODE REVIEW

**Comment by m3hm3t** [comment]
> Can you run `make check-enterprise` locally with asserts enabled?
> 
> I am getting another crash with PG17.5. Not sure if it is related to this, looking into it.

It looks like the branch failed on the "single\_node\_enterprise" test, but I haven’t found any evidence yet that it’s connected to this PR or its commits. If I do, I’ll share it.

**Comment by naisila** [comment]
> It looks like the branch failed on the "single_node_enterprise" test, but I haven’t found any evidence yet that it’s connected to this PR or its commits. If I do, I’ll share it.

Sounds good. If it's not related, we can merge this PR.

File: src/test/regress/sql/multi_insert_select.sql [hunk 1]
```diff
@@ -2583,5 +2583,129 @@ SELECT id, val FROM version_dist_union ORDER BY id;
...
+-- Deterministic sample of results
+SELECT 't3_sample' AS test, user_id, value_1_agg
+FROM agg_events
+ORDER BY user_id
+LIMIT 5;
+
+----------------------------------------------------------------------
+-- Cleanup
+----------------------------------------------------------------------
+DROP SCHEMA pr8106_cte_outervar CASCADE;
```
Comment (colm-mchugh) [inline src/test/regress/sql/multi_insert_select.sql]: Maybe put this `DROP SCHEMA` statement after line 2710?

File: src/backend/distributed/planner/multi_logical_optimizer.c [hunk 2]
```diff
@@ -4618,14 +4617,26 @@ FindReferencedTableColumn(Expr *columnExpression, List *parentQueryList, Query *
...
-			FindReferencedTableColumn(targetEntry->expr, parentQueryList,
-									  cteQuery, column, rteContainingReferencedColumn,
-									  skipOuterVars);
+			if (targetEntryIndex >= 0 &&
+				targetEntryIndex < list_length(cteQuery->targetList))
+			{
+				TargetEntry *targetEntry =
+					list_nth(cteQuery->targetList, targetEntryIndex);
+
+				/* hand a private, bounded parent list to the recursion */
```
Comment (colm-mchugh) [inline src/backend/distributed/planner/multi_logical_optimizer.c]: nit: let's expand this comment, because its important to understanding why the code works - I'd suggest incorporating parts of the explanation in the PR description, particularly the `After`  description.

**Comment by colm-mchugh** [comment]
> > Can you run `make check-enterprise` locally with asserts enabled?
> > I am getting another crash with PG17.5. Not sure if it is related to this, looking into it.
> 
> It looks like the branch failed on the "single_node_enterprise" test, but I haven’t found any evidence yet that it’s connected to this PR or its commits. If I do, I’ll share it.

It looks like the test failures in `make check-enterprise` with asserts enabled predate a4040ba5d so looks unrelated.
