### PR TITLE
Fixes empty password issue

### LINKED ISSUE #6408: Alter Role Password to Empty Crashes
``` SQL
ALTER ROLE role1 PASSWORD '';
```
and
``` SQL
ALTER ROLE role1 PASSWORD NULL;
```
crash with backtrace
```
Program received signal SIGSEGV, Segmentation fault.
pg_detoast_datum_packed (datum=datum@entry=0x0) at fmgr.c:1756
1756            if (VARATT_IS_COMPRESSED(datum) || VARATT_IS_EXTERNAL(datum))
(gdb) bt
#0  pg_detoast_datum_packed (datum=datum@entry=0x0) at fmgr.c:1756
#1  0x000055770ebd5eea in text_to_cstring (t=0x0) at varlena.c:225
#2  0x00007f5701377e31 in ExtractEncryptedPassword (roleOid=<optimized out>) at commands/role.c:357
#3  0x00007f5701378cf4 in PostprocessAlterRoleStmt (node=0x557710db7158, queryString=<optimized out>)
    at commands/role.c:168
#4  0x00007f5701387545 in ProcessUtilityInternal (pstmt=0x557710db70c0, pstmt@entry=0x557710d37400,
    queryString=queryString@entry=0x557710d36590 "ALTER ROLE oz1 PASSWORD NULL;",
    context=context@entry=PROCESS_UTILITY_TOPLEVEL, params=params@entry=0x0,
    queryEnv=queryEnv@entry=0x0, dest=dest@entry=0x557710d374f0, completionTag=0x7ffddebe7420)
    at commands/utility_hook.c:753
#5  0x00007f570138816e in multi_ProcessUtility (pstmt=0x557710d37400,
    queryString=0x557710d36590 "ALTER ROLE oz1 PASSWORD NULL;", readOnlyTree=<optimized out>,
    context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0, dest=0x557710d374f0,
    completionTag=0x7ffddebe7420) at commands/utility_hook.c:305
#6  0x000055770eabfd23 in ProcessUtility (pstmt=pstmt@entry=0x557710d37400,
    queryString=<optimized out>, readOnlyTree=<optimized out>, context=<optimized out>,
    params=<optimized out>, queryEnv=<optimized out>, dest=0x557710d374f0, qc=0x7ffddebe7420)
    at utility.c:523
#7  0x000055770eabd1c0 in PortalRunUtility (portal=portal@entry=0x557710e16f70,
    pstmt=pstmt@entry=0x557710d37400, isTopLevel=isTopLevel@entry=true,
    setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x557710d374f0,
    qc=qc@entry=0x7ffddebe7420) at pquery.c:1147
#8  0x000055770eabd4d0 in PortalRunMulti (portal=portal@entry=0x557710e16f70,
    isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false,
    dest=dest@entry=0x557710d374f0, altdest=altdest@entry=0x557710d374f0, qc=qc@entry=0x7ffddebe7420)
    at pquery.c:1304
#9  0x000055770eabd927 in PortalRun (portal=portal@entry=0x557710e16f70,
    count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true,
    run_once=run_once@entry=true, dest=dest@entry=0x557710d374f0,
    altdest=altdest@entry=0x557710d374f0, qc=0x7ffddebe7420) at pquery.c:786
#10 0x000055770eab98ed in exec_simple_query (
    query_string=query_string@entry=0x557710d36590 "ALTER ROLE oz1 PASSWORD NULL;")
    at postgres.c:1214
#11 0x000055770eabba24 in PostgresMain (argc=argc@entry=1, argv=argv@entry=0x7ffddebe7620,
    dbname=<optimized out>, username=<optimized out>) at postgres.c:4486
#12 0x000055770ea13f10 in BackendRun (port=port@entry=0x557710dd6c00) at postmaster.c:4506
#13 0x000055770ea171a1 in BackendStartup (port=port@entry=0x557710dd6c00) at postmaster.c:4228
#14 0x000055770ea173e6 in ServerLoop () at postmaster.c:1745
#15 0x000055770ea18991 in PostmasterMain (argc=5, argv=<optimized out>) at postmaster.c:1417
#16 0x000055770e954360 in main (argc=5, argv=0x557710d2df80) at main.c:209
```

### PR DESCRIPTION
**Pull request by naisila**
Fixes #6408

### CODE REVIEW

File: src/backend/distributed/commands/role.c [hunk 1]
```diff
@@ -354,16 +354,18 @@ ExtractEncryptedPassword(Oid roleOid)
...
-	table_close(pgAuthId, AccessShareLock);
-	ReleaseSysCache(tuple);
+	/* empty password is treated the same as NULL (no password) */
 
-	if (isNull)
+	const char *passwordCstring = "";
+	if (!isNull)
 	{
-		return NULL;
+		passwordCstring = TextDatumGetCString(passwordDatum);
```
Comment (thanodnl) [inline src/backend/distributed/commands/role.c:363]: why are we 'changing' the behaviour from the previous intent?
we planned to return `NULL` when the password was set not set, eg `isNull` became true.

However, with this change we choose to return an empty string.

I do see that an empty string is treated as `NULL` password, which could explain how this works.
However, our tests seem to disagree with this statement:

> ALTER ROLE new_role PASSWORD '';
> NOTICE:  empty string is not a valid password, clearing password

Would it make sense to default to `NULL` here if `isNull` is set. We can easily move the pstrdup inside the scope of the branch here, and change the initialization of `passwordCstring` to `NULL`.

If that is not possible or desirable we need to have better documentation of its subtleties.

Comment (naisila) [reply src/backend/distributed/commands/role.c:363]: > The reason why I 'changed' the behavior was because it's better to send the same command to the worker nodes. If we return NULL instead of an empty string, the workers would get this command ALTER ROLE new_role PASSWORD NULL, whereas in the coordinator we run ALTER ROLE new_role PASSWORD. Right now these two commands do the same thing, but maybe it will change in the future. I prefer to maintain consistency here.

Okay this is not true, in this way the other way around doesn't work. So the question is whether I should pick '' or NULL to send to the workers. You're right, considering the notice, it's better to default to NULL.

Comment (JelteF) [reply src/backend/distributed/commands/role.c]: For future reference: This is because of this fix for a security issue I reported ~6 years ago to Postgres: https://github.com/postgres/postgres/commit/bf6b9e94445610a3d84cf9521032fab993f96fd6

**Comment by hanefi** [comment]
Do we want a changelog entry for this?
