### PR TITLE
Not skip relation in conversion if it doesn't have RelationRestriction

### LINKED ISSUE #4682: Join Fails with "ERROR:  row field count is 1, expected 4"
```
create table tbl (a int, b int, c int, d int);
select create_distributed_table('tbl', 'a'); 

select 1 from
  pg_operator
  inner join tbl on (select 1 from pg_type) > d
  left join pg_dist_rebalance_strategy on 'a' = name
where a + b + c > 0;

ERROR:  row field count is 1, expected 4
```

### PR DESCRIPTION
**Pull request by SaitTalhaNisanci**
We would exclude tables without relationRestriction from conversion
candidates in local-distributed table joins. This could leave a leftover
local table which should have been converted to a subquery.

Ideally I would expect that in each call to CreateDistributedPlan we
would pass a new plan id, but that seems like a bigger change.

We probably hit this if statement:
https://github.com/citusdata/citus/blob/7170ed287c83044910aa0d5d8a0e8f67c75d2647/src/backend/distributed/planner/relation_restriction_equivalence.c#L1936-L1938

Fixes #4682

### CODE REVIEW

File: src/test/regress/sql/local_table_join.sql [hunk 1]
```diff
@@ -336,6 +336,17 @@ ALTER TABLE local DROP column key1;
 SELECT COUNT(*) FROM distributed_table JOIN local ON distributed_table.value = 'text';
 
 
+-- issue 4682
+create table tbl (a int, b int, c int, d int);
```
Comment (onderkalaci) [inline src/test/regress/sql/local_table_join.sql:340]: Is it possible that this query returns some rows? Maybe introduce custom tables instead of `pg_type ` and compare the results with all local tables?

File: src/backend/distributed/planner/local_distributed_join_planner.c [hunk 2]
```diff
@@ -538,11 +538,6 @@ CreateConversionCandidates(PlannerRestrictionContext *plannerRestrictionContext,
 
 		RelationRestriction *relationRestriction =
 			RelationRestrictionForRelation(rangeTableEntry, plannerRestrictionContext);
```
Comment (onderkalaci) [inline src/backend/distributed/planner/local_distributed_join_planner.c:540]: outer joins with WHERE false prevents relation restrictions generated, see https://github.com/citusdata/citus/pull/4292#issue-514909101

And somehow PG decides to do that for this query as `pg_dist_rebalanc_strategy` is not showing up on EXPLAIN output for local-only tables schema. I guess PG decides that `pg_dist_rebalanc_strategy` does not contribute to the result at all and do not generate restrictions

```SQL
explain select 1 from
  pg_operator
  inner join tbl on (select 1 from pg_type) > d
  left join pg_dist_rebalance_strategy on 'a' = name
where a + b + c > 0;
                             QUERY PLAN                             
--------------------------------------------------------------------
 Nested Loop  (cost=19.31..2071.28 rows=158620 width=4)
   InitPlan 1 (returns $0)
     ->  Seq Scan on pg_type  (cost=0.00..19.31 rows=531 width=4)
   ->  Seq Scan on pg_operator  (cost=0.00..21.70 rows=770 width=0)
   ->  Materialize  (cost=0.00..48.03 rows=206 width=0)
         ->  Seq Scan on tbl  (cost=0.00..47.00 rows=206 width=0)
               Filter: (($0 > d) AND (((a + b) + c) > 0))
(7 rows)

```

So, this change makes sense

Comment (onderkalaci) [reply src/backend/distributed/planner/local_distributed_join_planner.c:540]: I also guess that the other tests that fail are all expected. Because they are:
```SQL

 SELECT count(*) FROM distributed LEFT JOIN local USING (id);

```

Where, `id` is PRIMARY KEY. So, Postgres doesn't need the inner tables to calculate the result

File: src/backend/distributed/planner/local_distributed_join_planner.c [hunk 3]
```diff
@@ -384,7 +384,7 @@ static bool
 HasConstantFilterOnUniqueColumn(RangeTblEntry *rangeTableEntry,
 								RelationRestriction *relationRestriction)
 {
-	if (rangeTableEntry == NULL)
+	if (rangeTableEntry == NULL || relationRestriction == NULL)
```
Comment (onderkalaci) [inline src/backend/distributed/planner/local_distributed_join_planner.c:387]: might be useful to have a comment on the meaning of `relationRestriction == NULL`

Comment (onderkalaci) [reply src/backend/distributed/planner/local_distributed_join_planner.c:387]: Just noting from our internal chat: In a sense, it doesn't make sense to recursively plan a table that doesn't contribute to the result. Still, for the time being it makes sense to not have any special cases in the logic as it might have some side-effect like the bug that we are fixing.

Comment (onderkalaci) [reply src/backend/distributed/planner/local_distributed_join_planner.c:387]: actually, it might be nice to have a comment like the above in the code

**Review by onderkalaci — APPROVED** [review]
All looks good to me with a minor comment improvement area

File: src/test/regress/expected/local_table_join.out [hunk 4]
```diff
@@ -1466,7 +1466,48 @@ DEBUG:  Plan XXX query after replacing subqueries and CTEs: SELECT count(*) AS c
...
+-- there is a different output in pg11 and in this query the debug messages are not
+-- as important as the others so we use notice
+set client_min_messages to NOTICE;
+select COUNT(*) from
+  pg_operator
+  inner join tbl1 on (select 1 from custom_pg_type) >= d
+  left join custom_pg_dist_rebalance_strategy on 'a' = name
+where a + b + c > 0;
+ count
+---------------------------------------------------------------------
```
Comment (onderkalaci) [inline src/test/regress/expected/local_table_join.out:1505]: hmm, would this result rely on the size of `pg_operator `? So, maybe create a placeholder table instead to make it consistent output?

Comment (SaitTalhaNisanci) [reply src/test/regress/expected/local_table_join.out:1505]: Ahh, I haven't seen pg_operator :) I was wondering why it wasn't consistent with the other tables. Thanks!
