### PR TITLE
Columnar: fix wraparound bug.

### LINKED ISSUE #5958: Columnar: vacuum freeze does not advance relfrozenxid
With `postgresql.conf`:

```
wal_level=logical
shared_preload_libraries='citus'
autovacuum_freeze_max_age = 100000
vacuum_freeze_min_age = 50000
vacuum_freeze_table_age = 75000
synchronous_commit = off
fsync = off
```

And doing:

```
CREATE EXTENSION citus;
CREATE TABLE test_row(i int);
INSERT INTO test_row VALUES (1);
CREATE TABLE test_col(i int) USING columnar;
INSERT INTO test_col VALUES (1);
```

Then doing:

```
(for i in `seq 1 200000`; do echo "UPDATE test_row SET i = i + 1;"; done) | ./bin/psql -q -X postgres
```

I see:

```
=# select datname, relname, age(datfrozenxid) datage, age(relfrozenxid) as relage from pg_database, pg_class where datname='postgres' and (relname='test_row' or relname='test_col');
 datname  | relname  | datage | relage 
----------+----------+--------+--------
 postgres | test_row | 200018 | 200010
 postgres | test_col | 200018 | 200008
(2 rows)
```

After I wait for autovacuum to kick in, I see:

```
=# select datname, relname, age(datfrozenxid) datage, age(relfrozenxid) as relage from pg_database, pg_class where datname='postgres' and (relname='test_row' or relname='test_col');
 datname  | relname  | datage | relage 
----------+----------+--------+--------
 postgres | test_row | 200010 |  50002
 postgres | test_col | 200010 | 200010
(2 rows)
```

And further manual `VACUUM` or `VACUUM FREEZE` do not fix it.

### PR DESCRIPTION
**Pull request by jeff-davis**
columnar_vacuum_rel() now advances relfrozenxid.

Fixes #5958.

DESCRIPTION: Fix columnar freezing/wraparound bug.

### CODE REVIEW

File: src/backend/columnar/columnar_tableam.c [hunk 1]
```diff
@@ -1071,6 +1092,74 @@ columnar_vacuum_rel(Relation rel, VacuumParams *params,
...
 	}
+
+	BlockNumber new_rel_pages = smgrnblocks(RelationGetSmgr(rel), MAIN_FORKNUM);
+
+	/* get the number of indexes */
+	Relation *indrels = NULL;
+	int nindexes;
+	vac_open_indexes(rel, RowExclusiveLock, &nindexes, &indrels);
+	vac_close_indexes(nindexes, indrels, NoLock);
+
```
Comment (onurctirtir) [inline src/backend/columnar/columnar_tableam.c:1103]: Should we do someting with indRels ? Since this code currently just opens and closes those indexes.

Comment (onurctirtir) [reply src/backend/columnar/columnar_tableam.c:1103]: vac_open_indexes seems() to be skipping invalid indexes, so might be nice to add a test where we vacuum a relation that has an invalid index ?

File: src/backend/columnar/columnar_tableam.c [hunk 2]
```diff
@@ -1071,6 +1092,74 @@ columnar_vacuum_rel(Relation rel, VacuumParams *params,
...
+	vac_update_relstats(rel, new_rel_pages, new_live_tuples,
+						new_rel_allvisible, nindexes > 0,
+						newRelFrozenXid, newRelminMxid,
+						&frozenxid_updated, &minmulti_updated, false);
+#else
+	vac_update_relstats(rel, new_rel_pages, new_live_tuples,
+						new_rel_allvisible, nindexes > 0,
+						newRelFrozenXid, newRelminMxid, false);
+#endif
```
Comment (onurctirtir) [inline src/backend/columnar/columnar_tableam.c:1162]: should we call pgstat_report_vacuum at some point ?

File: src/backend/columnar/columnar_tableam.c (hunk 1 above)
Comment (jeff-davis) [reply src/backend/columnar/columnar_tableam.c:1103]: I changed to use `RelationGetIndexList()` instead, which is lighter-weight.

It doesn't look like it's skipping indexes where `!indisvalid`... the comment over `vac_open_indexes()` says:

```
 * We consider an index vacuumable if it is marked insertable (indisready).                                                
 * If it isn't, probably a CREATE INDEX CONCURRENTLY command failed early in                                               
 * execution, and what we have is too corrupt to be processable.  We will                                                  
 * vacuum even if the index isn't indisvalid; this is important because in a                                               
 * unique index, uniqueness checks will be performed anyway and had better not                                             
 * hit dangling index pointers.                                                                                            
```

If you mean try to test the case where `!indisready`, that seems like overkill, unless there's a case I'm missing.

File: src/backend/columnar/columnar_tableam.c (hunk 2 above)
Comment (jeff-davis) [reply src/backend/columnar/columnar_tableam.c:1162]: Yes, done.

We could also improve the logging/instrumentation output, but I'll leave that for another PR.

**Review by onurctirtir — APPROVED** [review]
