### PR TITLE
Remove hash-pruning logic for NULL values

### LINKED ISSUE #628: Hash-distributed anti-joins return wrong results
# Steps

```sql
CREATE TABLE t_left(val int);
select master_create_distributed_table('t_left','val','hash');
select master_create_worker_shards('t_left',16,1);
INSERT INTO t_left VALUES(1);
INSERT INTO t_left VALUES(2);
INSERT INTO t_left VALUES(3);
INSERT INTO t_left VALUES(4);
INSERT INTO t_left VALUES(5);

CREATE TABLE t_right(val int);
select master_create_distributed_table('t_right','val','hash');
select master_create_worker_shards('t_right',16,1);
INSERT INTO t_right VALUES(2);
INSERT INTO t_right VALUES(3);
INSERT INTO t_right VALUES(4);

select * from t_left as l LEFT JOIN t_right as r ON l.val=r.val where r.val is NULL;
```

# Expected

|  val  |  val  |
| ----- | ----- |
|     1 |    ∅   |
|     5 |     ∅  |
_(2 rows)_

# Actual

|  val  |  val  |
| ----- | ----- |
|     1 |      ∅ |
|     5 |      ∅ |
|     4 |      ∅ |
|     3 |      ∅ |
|     2 |      ∅ |

_(5 rows)_

### PR DESCRIPTION
**Pull request by jasonmp85**
It turns out some tests exercised this behavior, but removing it should have no ill effects. Besides, both copy and `INSERT` disallow `NULL`s in a table's partition column.

Fixes #628

### CODE REVIEW

**Comment by jasonmp85** [comment]
I kept the commits separate here because it's kind of neat to see the exact failure reported by @metdos replicated in Travis, then fixed in the next commit. I'll obviously squash them before merging.

**Comment by sumedhpathak** [comment]
@jasonmp85 : Taking a look.

File: src/backend/distributed/planner/multi_physical_planner.c [hunk 1]
```diff
@@ -2838,24 +2838,6 @@ HashableClauseMutator(Node *originalNode, Var *partitionColumn)
...
-		Expr *nullTestOperand = nullTest->arg;
-		if (IsA(nullTestOperand, Var))
-		{
-			column = (Var *) nullTestOperand;
-		}
-
-		if ((column != NULL) && equal(column, partitionColumn) &&
-			(nullTest->nulltesttype == IS_NULL))
-		{
-			OpExpr *opExpressionWithZeroConst = MakeOpExpressionWithZeroConst();
```
Comment (sumedhpathak) [inline src/backend/distributed/planner/multi_physical_planner.c]: I think ``MakeOpExpressionWithZeroConst`` is no longer called. Could you double check and remove if not needed?

Comment (jasonmp85) [inline src/backend/distributed/planner/multi_physical_planner.c]: Yeah, the compiler probably warned about it because when I opened it up in Eclipse it was highlighted as unused. I removed it (and its declaration) and pushed.

**Comment by sumedhpathak** [comment]
I think looks good. I did some testing as well, and am unable to find any issues. 🚢

**Comment by jasonmp85** [comment]
OK, squashing and merging.
