### PR TITLE
ruleutils: use get_rtable_name for deparsing resultRelation

### LINKED ISSUE #3975: Unreferenced modifying CTE on single shard gives an error
An unreferenced modifying CTEs in a router query gives an error on master:
```
WITH a AS (UPDATE test SET y = 3 WHERE x = 1 RETURNING x) SELECT * FROM test WHERE x = 1;
NOTICE:  issuing WITH a AS (UPDATE public.test_102009 test SET y = 3 WHERE (test_1.x OPERATOR(pg_catalog.=) 1) RETURNING test_1.x) SELECT x, y FROM public.test_102009 test WHERE (x OPERATOR(pg_catalog.=) 1)
DETAIL:  on server marco@localhost:9701 connectionId: 17
ERROR:  missing FROM-clause entry for table "test_1"
```

The same query works in Citus 9.3.

### PR DESCRIPTION
**Pull request by serprex**
Deparsing doesn't always preserve aliases, `get_rtable_name` accounts for this

Second test case is still not correct. Could use more test coverage of other DMLs which this PR fixes

Fixes #3975

### CODE REVIEW

File: src/backend/distributed/deparser/ruleutils_11.c [hunk 1]
```diff
@@ -3036,7 +3036,7 @@ get_insert_query_def(Query *query, deparse_context *context)
 	/* INSERT requires AS keyword for target alias */
 	if (rte->alias != NULL)
```
Comment (serprex) [inline src/backend/distributed/deparser/ruleutils_11.c:3037]: Should we remove the alias null check?

File: src/test/regress/expected/with_modifying.out [hunk 2]
```diff
@@ -964,6 +964,15 @@ DETAIL:  distribution column value: 1
 (1 row)
 
 RESET client_min_messages;
+-- https://github.com/citusdata/citus/issues/3975
+WITH mb AS (UPDATE modify_table SET val = 3 WHERE id = 3 RETURNING NULL) SELECT * FROM modify_table WHERE id = 3;
+ id | val
+---------------------------------------------------------------------
+(0 rows)
+
+WITH mb AS (UPDATE modify_table SET val = 3 WHERE id = 3 RETURNING NULL) SELECT * FROM modify_table, mb WHERE id = 3;
```
Comment (serprex) [inline src/test/regress/expected/with_modifying.out:973]: With non-distributed tables this results in 3 columns, the last being unnamed `?column?`

Comment (marcocitus) [reply src/test/regress/expected/with_modifying.out:973]: We seem to have a general issue with unnamed columns:
```sql
WITH a AS (SELECT '' FROM test) SELECT * FROM a;
NOTICE:  issuing SELECT worker_column_1 AS "?column?" FROM (SELECT a."?column?" AS worker_column_1 FROM (SELECT ''::text FROM public.test_102009 test) a) worker_subquery
DETAIL:  on server marco@localhost:9701 connectionId: 6
```

Comment (marcocitus) [reply src/test/regress/expected/with_modifying.out:973]: That's actually a regression from 9.2, I opened an issue: https://github.com/citusdata/citus/issues/3985

though the regression was introduced by inlining, so the obvious fix (not inlining) might not help the modifying CTE case.

Comment (marcocitus) [reply src/test/regress/expected/with_modifying.out:973]: I think the proper fix would be to explicitly name the columns, e.g. this works:
```sql
WITH a AS (UPDATE public.test SET y = 3 WHERE x = 1 RETURNING NULL) SELECT "?column?" FROM a AS a ("?column?");
```

Comment (marcocitus) [reply src/test/regress/expected/with_modifying.out:973]: Actually, it would be better to explicitly name the columns in the CTE.

```
WITH a ("?column?") AS (UPDATE public.test SET y = 3 WHERE x = 1 RETURNING NULL) SELECT "?column?" FROM a;
```

That way, we can do this for modifying CTEs in router queries without looking at the rest of the query tree.

File: src/test/regress/sql/with_modifying.sql [hunk 3]
```diff
@@ -539,5 +539,9 @@ WITH mu AS (WITH allref AS (SELECT id a FROM anchor_table) UPDATE modify_table S
 WITH mu AS (WITH allref AS (SELECT now() a FROM anchor_table) UPDATE modify_table SET val = 3 WHERE id = 1 AND now() IN (SELECT a FROM allref) RETURNING id+1) SELECT count(*) FROM mu;
 RESET client_min_messages;
 
+-- https://github.com/citusdata/citus/issues/3975
+WITH mb AS (UPDATE modify_table SET val = 3 WHERE id = 3 RETURNING NULL) SELECT * FROM modify_table WHERE id = 3;
```
Comment (marcocitus) [inline src/test/regress/sql/with_modifying.sql:543]: Maybe also add a query with a regular (named) RETURNING.
